### ISSUE TITLE
Arc Warden Clone Problem with Fountain Invulnerability

### ISSUE THREAD

**Issue by jeffhill** [ValveSoftware/Dota2-Gameplay#1]
Fountain invincibility breaks the ability to control Arc Warden's Clone until enemies leave your base.

https://www.reddit.com/r/DotA2/comments/v336r8/game_breaking_arc_warden_bug/

**Comment by natesampo** [comment]
https://user-images.githubusercontent.com/22483011/171696712-8df89ffb-528f-4446-a4fc-eb7cb3bb05da.mov

@jeffhill You can't click on the arc illusion, but you can select it via tabbing or box selecting. In the video I'm spam clicking and cannot select it though, which is very odd behavior.

**Comment by natesampo** [comment]
https://user-images.githubusercontent.com/22483011/171697778-bbe80b4e-c287-4a47-b901-5688b70fbab8.mov

Oh wow this is very strange behavior. The arc clone gets spawn invulnerability upon being summoned only if the last clone you had died away from enemies. If you summon an arc clone when the previous one was close to enemies, it won't have spawn invulnerability, but if you summon an arc clone when the previous one was far from enemies it will.

**Comment by Xaltyn** [comment]
Hey, thanks for looking at my reddit post. Currently the replay system is broken, maybe another bug. So I can't download my previous games to see which game it happens in. But a few of my match's it could have happened in are:

6582942639
6569080165
6553356171

**Comment by Xaltyn** [comment]
I just tried to recreate it in this match: 6599440057 but was not able to. Maybe it has something to do with an specific item? 
https://i.imgur.com/T6n3ZoY.jpeg
are the commonly purchased items I buy on Arc Warden.

**Comment by MatteoBonomi** [comment]
> Hey, thanks for looking at my reddit post. Currently the replay system is broken, maybe another bug. So I can't download my previous games to see which game it happens in. But a few of my match's it could have happened in are:
> 
> 6582942639 6569080165 6553356171


You cant download replays older than 7 days. 

If you have them downloaded you can watch them whenever.

**Comment by Xaltyn** [comment]
6602085582
Fresh game, bug happens twice near the end of the game.

**Comment by Stephanie55** [comment]
Happened to me today in a game. That's the ID: 6715033534. It happened at 30:55.

**Comment by Stephanie55** [comment]
Now the clone is getting fountain invulnerability every time you spawn it. Hopefully it makes the solution simpler somehow.

**Comment by Infamous540** [comment]
Now that the clone is getting fountain invulnerability everytime we spawn, why is that good? and why should it have to be like that? if you spawn it anywhere outside the base it should not get invu at all, this invulnerability is a nightmare imo.

When i use hotkey "choose all other units" that was perfect way to control the illusion, but with that hotkey you cannot move the illusion asap anymore, you have to tab it and move it first or select it before you can control it.

Please make it so that hotkey works for the illusion instant atleast.

**Comment by Dota-Exp** [comment]
This issue should be resolved as of this time.
