### ISSUE TITLE
Fantasy for days 2-5 of Bali Major did not give correct levels (only gave 1 level per day)

### ISSUE THREAD

**Issue by TheBugReporter** [ValveSoftware/Dota2-Gameplay#10005]
### Description

For fantasy days 2-5 of the Bali Major main event, all scores and percentiles were (and still are) 0.  Since the percentile & score was incorrectly calculated at the end of the day (it was 0), we received Bottom 50% rewards (1 level) for each of those days.  

This is similar to the issue of the leaderboards not displaying properly, but it directly affected our rewards for those days too.

I'm asking Valve to re-calculate those days properly.  Thank you!

**Comment by gine1** [comment]
same
