### ISSUE TITLE
Naga Ensare sleep heroes

### ISSUE THREAD

**Issue by sommerVA** [ValveSoftware/Dota2-Gameplay#10010]
### Ability name

Ensare

### Description

7.33b Fixed Naga Siren Aghanim's Scepter ensnare not targetting sleeping/invulnerable units
still bug  ensnare on sleeping heroes without aghs in 7.33d

### Example Match ID (and possibly Timestamp)

-

**Comment by Aluerie** [comment]
cant reproduce ; works just in line with 733

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/33165440/240d3525-5998-41d7-a89e-109a87034932)

https://github.com/ValveSoftware/Dota2-Gameplay/assets/33165440/32fb5ccc-b02b-43dc-a5fd-58e5c972b698
