### ISSUE TITLE
Razor quest "damage towers with eye of the storm" does not work

### ISSUE THREAD

**Issue by WarpGhost** [ValveSoftware/Dota2-Gameplay#10052]
### Hero and spell

Razor, Eye of the storm

### Description

Title, match 7237951514
I am quite sure that i damaged towers (and other building) with it quite some times. Yet counter remain 0

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/74701599/d9a5c034-2dc4-4482-b5e9-b3c9973c90db)

**Comment by LokeLok** [comment]
You need aghs to do building damage with Razor ulti and you had no aghs. The challenge does work, please close this issue.
