### ISSUE TITLE
Perfect behavior score but bug tells me that my behavior score has fallen below 3k and so other players wont hear me?

### ISSUE THREAD

**Issue by AnujModi** [ValveSoftware/Dota2-Gameplay#10073]
### Description

I have a perfect behavior score... always have had it... the current one, as seen from the screenshot that was generated on July 11, 2023, at 6:50 PM. The screenshot was taken at 8:23 PM... also I haven't played ten games after that... nor do I think I have been reported as such...
I noticed this bug that won't let me type in post-game chat for some reason...
It may be a server issue/game issue or my account problem...
Can you guys look into this? I don't mind not being able to chat... I generally don't... but annoying if this is going to happen in-game...

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/9489130/3a582800-0215-48e9-81ba-1993f98f3a71)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/9489130/eec77dfb-4d6f-4c48-8929-1fcb40f1d901)

**Comment by Aluerie** [comment]
#10068

**Comment by drewdicaro** [comment]
patch is rolling out. shouldnt be too long.

**Comment by Nathanael-Valve** [comment]
Fixed
