### ISSUE TITLE
10k behavior score players are chat muted and under getting error

### ISSUE THREAD

**Issue by ribuz11** [ValveSoftware/Dota2-Gameplay#10081]
### Description

Players who are 10k behavior score including me are getting chat muted and getting a message saying "Other players may be unable to hear you. The behavior score in your last behavior report has fallen below 3000 and your communication privileges have been temporarily revoked."

A reddit post with this issue "https://www.reddit.com/r/learndota2/comments/14y3ozj/behavior_score_under_3000_cant_chat_oo/"

Thank you

### Screenshots

![pic 1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/139497869/9fac1532-2c28-4663-bf5a-8e5cdca71667)
![behavior 2](https://github.com/ValveSoftware/Dota2-Gameplay/assets/139497869/3239cc02-ca40-4bcd-be40-7328df4d8e13)

**Comment by Aluerie** [comment]
Duplicate #10068

**Comment by ribuz11** [comment]
![screenshot 3](https://github.com/ValveSoftware/Dota2-Gameplay/assets/139497869/c8059696-ab2f-4671-b7df-7a08f5813bed)

The new behavior score updated but the problem persists.

**Comment by Nathanael-Valve** [comment]
Fixed
