### ISSUE TITLE
Upheaval Warlock shard

### ISSUE THREAD

**Issue by dirubens21** [ValveSoftware/Dota2-Gameplay#10131]
### Ability name

Upheaval

### Description

Warlock  Upheavel with Shard can disable tower backdoor protection 

![warlock](https://github.com/ValveSoftware/Dota2-Gameplay/assets/124630114/0b218fd6-9c51-4ac6-900f-8473bc203e17)

![warlock2](https://github.com/ValveSoftware/Dota2-Gameplay/assets/124630114/099655bc-7a1a-4ed6-a34b-7fba11ba3b6e)

### Example Match ID (and possibly Timestamp)

-

**Comment by LokeLok** [comment]
This has been fixed, you can close this.
