### ISSUE TITLE
Undying Aganim's Shard

### ISSUE THREAD

**Issue by SirBocha** [ValveSoftware/Dota2-Gameplay#10167]
### Ability name

Tombstone Aganim's Shard

### Description

Allies themselves cannot hide in Tombstone. Even though the description says they can.

### Example Match ID (and possibly Timestamp)

-

**Comment by Avarise831** [comment]
#10091

**Comment by SirBocha** [comment]
[Avarise831](https://github.com/Avarise831) Thank you
