### ISSUE TITLE
[Visual Bug] Enigma Armor of Twisted Maelstrom Particle BUG

### ISSUE THREAD

**Issue by 130N1D** [ValveSoftware/Dota2-Gameplay#10173]
### Cosmetic Item Name

Armor of Twisted Maelstrom

### Description

The particle attached to his right shoulder, outermost tine, halfway tethers to the spawn point on the map and the further from that point I go, the longer the line becomes.

### Example Match ID

7247622147

### Screenshots

![Screenshot_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/81698733/173f9e27-34c6-4dca-b2ac-fb2606ebdda8)
![Screenshot_2](https://github.com/ValveSoftware/Dota2-Gameplay/assets/81698733/16c7478a-2eb0-4a5d-aa2b-8e6928f00268)
![Screenshot_3](https://github.com/ValveSoftware/Dota2-Gameplay/assets/81698733/28666001-c16a-4afa-a651-8d9ca9d814d1)

**Comment by Aluerie** [comment]
dup #7333

**Comment by Aluerie** [comment]
this was fixed today, you can close the issue
