### ISSUE TITLE
skywrath_mage_concussive_shot creep damage 225 (should be 300?)

### ISSUE THREAD

**Issue by cma290** [ValveSoftware/Dota2-Gameplay#10257]
### Ability name

skywrath_mage_concussive_shot

### Description

creep has no magic resistance but the 300 concussive_shot dmg is dealt as 225.

### Example Match ID (and possibly Timestamp)

any

**Comment by Aluerie** [comment]
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/33165440/dd08fe08-b16c-4d7d-bc29-585bdc1bd78f)

**Comment by cma290** [comment]
> ![image](https://user-images.githubusercontent.com/33165440/256477394-dd08fe08-b16c-4d7d-bc29-585bdc1bd78f.png)

omg I'm blind😂。thank you!

**Comment by Aluerie** [comment]
Opendota API is pretty good/popular suggestion. https://docs.opendota.com/#tag/constants has jsons about various stuff including abilities info. 

Another option that might suit you is getting this data directly from game files, for example `pak01_dir.vpk/scripts/npc/npc_abilities.txt` has some info about hero abilities.
