### ISSUE TITLE
endless cooldown gem of true sight 

### ISSUE THREAD

**Issue by AndrosovLeonid** [ValveSoftware/Dota2-Gameplay#10277]
### Item name

gem of true sight 

### Description

When a character with "Gem of true sight" is killed in "Chronosphere", the item cannot use the active ability. This only happens when "Gem of true sight" is on cooldown.

### Example Match ID and Timestamp

https://youtu.be/TGka7JpxfHM

**Comment by Aluerie** [comment]
* Duplicate #8773

**Comment by Nathanael-Valve** [comment]
Fixed in next update.
