### ISSUE TITLE
Conduct summary needs better wording

### ISSUE THREAD

**Issue by BenLubar** [ValveSoftware/Dota2-Gameplay#10307]
Here's what a conduct summary currently looks like:
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/4257305/b9c1fd36-639c-4002-ad1d-2359dad2d2b6)

Here's the tooltip associated with the behavior score:
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/4257305/67e6c839-47dc-4e37-bd9d-941ea48d581f)

The problem (which I've seen people run into again and again) is that this screen implies two things it probably shouldn't:

1. The layout and lack of any explanatory text saying otherwise implies that behavior score is a direct function of the numbers shown below it and nothing else.
2. The tooltip reinforces this incorrect interpretation by implying that playing a match where you don't get reported is the one and only way to increase your behavior score.

Now, I don't have any kind of internal knowledge on how behavior scores are calculated, but from screenshots posted by people complaining I can clearly see that the two assumptions are both incorrect. Coupled with @vMcJohn's excellent GDC presentation about implementing VACnet for CS:GO, which didn't reveal the formula for Trust Factor, but did say that it is not solely based on a player's in-game actions. An example given in the presentation was that a player was complaining about cheaters in their matches and it turned out the player had 50 closely associated accounts that had been VAC banned.

I've seen people on the Dota 2 forum complaining that they created a smurf account and their behavior score followed them and even decreased further, so there's definitely something similar going on (or the behavior score system is just ridiculously good at guessing intent).

---

With all that said, my suggestion is a simple one: add one additional sentence to the conduct summary, reading:

> Your behavior score is not solely determined by the numbers on this screen.

**Comment by JQINX** [comment]
I want to see post summary of Did you enjoy that match get removed.

**Comment by BenLubar** [comment]
The new conduct summary doesn't have this issue as far as I can tell.
