### ISSUE TITLE
No hero clip under radiant sentiel

### ISSUE THREAD

**Issue by Tes-id** [ValveSoftware/Dota2-Gameplay#10313]
### Description

basicly, there is no texture on top side of a clip (fix plz, cuz hero's can't normaly walk on it)

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/16212836/890fd5ec-d59d-4db5-ab78-b2d36cc46bab)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/16212836/8946d94f-e635-48cf-8a54-bede3dfed089)

**Comment by Aluerie** [comment]
D #10204
