### ISSUE TITLE
Everytime i start DOTA2 alays a blank screen

### ISSUE THREAD

**Issue by pwahhh** [ValveSoftware/Dota2-Gameplay#10324]
### Description

Everytime i start DOTA2 alays a blank screen and i end up abandoning the game for some reason i cant do anything about it even if i close the game i relaunch it when i go back its already safe to leave ive been in low prio 4 weeks straight because of this issue i get out of low prio then this happens again i cant even play rank anymore its depressing already ive reinstalled DOTA 2 for like 5 times now just this week and still happens

### Example Match ID (and possibly Timestamp)

7264491481

### Screenshots

![360141463_1789349758211077_5258874545814769233_n](https://github.com/ValveSoftware/Dota2-Gameplay/assets/141026016/4d061083-bf8d-4c51-a4f7-c12a69b12e11)

**Comment by OwLester** [comment]
Same problem game sucks and developers is faggots

**Comment by pwahhh** [comment]
> Same problem game sucks and developers are faggots

i mean i respect them but its not funny anymore being low prio all the time i play the game casually and not to be able to pick the herous that you want to play

**Comment by pwahhh** [comment]
> Same problem game sucks and developers are faggots

i mean i respect them but its not funny anymore being low prio all the time i play the game casually and not to be able to pick the herous that you want to play
