### ISSUE TITLE
Legion Commander's Baneful Devotion won't apply effects when not equipped directly.

### ISSUE THREAD

**Issue by Chakalaka11** [ValveSoftware/Dota2-Gameplay#10322]
### Cosmetic Item Name

Baneful Devotion

### Description

Given that LC doesn't have helm on her directly, when I try to change ability effects from hero screen, icon changes but ability animation  stays the same. Also wierdly enough, post-end game screen has helm equipped, althought I haven't change anything since game start.

### Example Match ID

7260176849

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/12372021/6fbaa62a-f38c-43e9-acaf-62ed8ef8f814)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/12372021/41213720-18ce-45d9-8bca-17e2eeb56e94)

When helm equipped directly:
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/12372021/862c2897-55cf-4516-bae2-30a361f17b68)

**Comment by Aluerie** [comment]
Duolicate #1031
