### ISSUE TITLE
Impossible dota plus missions

### ISSUE THREAD

**Issue by skiner7** [ValveSoftware/Dota2-Gameplay#10368]
### Description

The issue with these "impossible" missions is that the objective that is proposed is ridiculously difficult to complete in a normal game, I attach some examples in the images, for example the faceless void, you must hit 3 enemies in a chronosphere.

What does this mean, that a Void should use a chronosphere, to hit 1 to 1 each of the 3 heroes in order to get a point in this achievement.
What would result in not finishing a kill for having to hit the other heroes within the chronosphere

I honestly don't make sense to it, that a player should spend his chronosphere just to "hit" one player and then go to another and not kill anyone.

Otherwise it would be impossible to do this mission.

What is the problem, then?
To complete these types of missions players should "DO NOT PLAY NORMALLY" as the achievement is totally opposite to the objective of the game.

So the simple solution is simply not to do the mission or complete it in 1 star, which does not affect the quality of the game in any way (But it does affect the quality of the game for the players who like to do the dotaplus missions)

It is not a single mission, there are many more, but I leave two examples

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/141285255/42334e8a-c17b-4ea8-b06c-b4899cd3d0fc)

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/141285255/9ea32c57-2c2e-40c6-b663-91b224f3c7a2)

**Comment by Aluerie** [comment]
You misinterpreted the mission. You don't need to attack three different heroes in chrono. You just need to place chromosphère on 3 enemy heroes at once.
