### ISSUE TITLE
Zeus shard not working

### ISSUE THREAD

**Issue by stillwaters1981** [ValveSoftware/Dota2-Gameplay#10405]
### Ability name

Shard lightning hands

### Description

Bug Description: towards the end of the game, zeus' shard ability doesn't work.

Match ID (important): 7274696374

Your Steam Profile Link (important): https://steamcommunity.com/profiles/76561198188498569/home

Other Helpful Information: none.

### Example Match ID (and possibly Timestamp)

7274696374

**Comment by Aluerie** [comment]
you turned it off yourself at 43:41.

Please close your issue.

**Comment by stillwaters1981** [comment]
Oh I didnt know about it and thank you for replying so quick! This is awesome!
