### ISSUE TITLE
xd

### ISSUE THREAD

**Issue by amssljc** [ValveSoftware/Dota2-Gameplay#10404]
xd

**Comment by kaaiuta** [comment]
Did you just admit to smurfing on a bug tracker page or something?

**Comment by amssljc** [comment]
> Did you just admit to smurfing on a bug tracker page or something?

In fact, my new account and my old account have approximate MMRs, both around Ancient 5. I've calibrated my account 100%, and I don't understand why I've become smurf, does it mean that the system actually thinks I have a higher MMR? For example immortal?Then why doesn't he give me a higher score but extend my matchmaking time ？？？？ I don't understand the logic.
