### ISSUE TITLE
Smoke of Deceit have 0% 

### ISSUE THREAD

**Issue by rosesagaming** [ValveSoftware/Dota2-Gameplay#10429]
### Item name

Smoke of Deceit

### Description

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/110391669/15b43ea3-81c9-43e4-bd36-bd952d71b5f3)

At current update, Smoke of Deceit ability is "Turns the caster and all allied player-controlled units in a 1200 radius invisible and grants 15% bonus movement speed for 45s."

But based on screenshot above, the movement bonus speed is 0%, I've tried to test on bot and Hero Demo as well. Most likely it happened because the devs put same % amount of Ninja Gear on this update, where Ninja Gear no longer grant the movement speed bonus.

### Example Match ID and Timestamp

7276580036 at Before the Match Begins (-01:13 ish)

**Comment by Nathanael-Valve** [comment]
This is purely cosmetic and was true before 7.34, but will nonetheless be fixed in the next update! 👍
