### ISSUE TITLE
Drow Ranger Multishot on Glacier with Talent 25 +1 Multishot wave bug

### ISSUE THREAD

**Issue by zerot69** [ValveSoftware/Dota2-Gameplay#10424]
### Ability name

Multishot

### Description

![Untitled](https://github.com/ValveSoftware/Dota2-Gameplay/assets/55183414/ecdd7df4-11d7-4e41-82eb-accd50b2a786)

Drow Ranger only used 1 Multishot Wave on Glacier with the talent +1 Multishot wave

### Example Match ID (and possibly Timestamp)

none

**Comment by BradMuir** [comment]
Should be fixed in the next udpate ➡️
