### ISSUE TITLE
7.34 Witch Doctor Aghanims bounces deal physical damage

### ISSUE THREAD

**Issue by Jamather** [ValveSoftware/Dota2-Gameplay#10426]
### Ability name

Death Ward

### Description

Death ward does pure damage now, but the aghs bounces from death ward are not pure damage.
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/15044542/c3abae6b-cd68-4404-9db4-c39c3679f816)

### Example Match ID (and possibly Timestamp)

0

**Comment by BradMuir** [comment]
Should be fixed in the next release. Feeling good, man. 👍
