### ISSUE TITLE
7.34 Elder Titan Echo Stomp Shard Upgrade can no longer be activated mid-animation while casting.

### ISSUE THREAD

**Issue by eboug92** [ValveSoftware/Dota2-Gameplay#10420]
### Ability name

Echo Stomp Shard Upgrade

### Description

Elder Titan's Echo Stomp Shard Upgrade can no longer be activated mid-animation while casting. This issue was introduced with the new patch 7.34 containing the new "Alternative Cast Abilities" behavior.

Bonus inconsistency:
Before the new patch, the Echo Stomp Shard upgrade required you to put the ability on auto-cast. However, it was impossible to put the ability on auto-cast with the Astral Spirit selected making it very annoying to use.

I was hoping the "Alternative Cast Abilities" mentioned in the new 7.34 patch notes would fix this, but it didn't. You still can only cast the Shard-upgraded version of Echo Stomp on the main hero.

I'm sure this is partly why people rarely buy his Shard. I hope Valve makes this behavior consistent between ET and his Astral Spirit!

### Example Match ID (and possibly Timestamp)

Easily Reproducible in Demo Mode

**Comment by HonestCosby** [comment]
I’m really hoping this is a bug and and no an intended change cause not being able to toggle after starting the channel combined with the problem of no toggled while microing the spirit mean you would start a stomp and select hero while channeling and then toggle accordingly. It’s made my favorite hero feel unplayable and all the muscle memory I’ve built over years of ET spam just doesn’t work at all any more. I’m truly beside myself out here

**Comment by arvidz** [comment]
This needs to be fixed ASAP! huge nerf to ET shard and stomp

**Comment by eboug92** [comment]
The main issue above has been fixed. Everything else reported is still broken/inconsistent.
