### ISSUE TITLE
beastmaster talent tooltip

### ISSUE THREAD

**Issue by dzhkaeffi** [ValveSoftware/Dota2-Gameplay#10423]
### Hero and spell

level 15 beastmaster talent

### Description

instead of showing ms value on rightside level 15 talent, its shows +[!s:bonus_ms] Move speed aura to beastmaster and his units

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/87204828/8b519bbf-4e5e-40f1-9c57-55129ac1728b)

**Comment by eugene-valve** [comment]
This will be fixed in the next update, thanks!
