### ISSUE TITLE
AM bug with the ability

### ISSUE THREAD

**Issue by 7oom1k** [ValveSoftware/Dota2-Gameplay#10425]
### Ability name

COUNTERSPELL ALLY

### Description

COUNTERSPELL ALLY can be used on an enemy, and also, if you use it on an enemy and use COUNTERSPELL on yourself, then when the spell is directed, 2 copies appear instead of one, that's how it works: https://www.youtube.com/watch?v=wO2-1LRBfs8 
 and also here is my steam profile: https://steamcommunity.com/profiles/76561198372312586/

### Example Match ID (and possibly Timestamp)

0:00 - 0:24

**Comment by BradMuir** [comment]
Should be fixed in the next release! 👍
