### ISSUE TITLE
AM, DROW RANGER 

### ISSUE THREAD

**Issue by dprcold** [ValveSoftware/Dota2-Gameplay#10422]
### Ability name

1. Conterspell 2. multishot

### Description

1. AM spell, 'counterspell' can be used on enemies, and all the same, the anti-mage creates an illusion
2. DROW RANGER , 'multishot' on 'glacier'  use only ONE wave of arrows

### Example Match ID (and possibly Timestamp)

undefined

**Comment by BradMuir** [comment]
Both should be fixed in the next release. 👍
