### ISSUE TITLE
Multishot only releases the first wave if you cast it atop the Glacier.

### ISSUE THREAD

**Issue by sandersontavares** [ValveSoftware/Dota2-Gameplay#10436]
### Ability name

Multishot

### Description

Tested on Demo Hero.

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/7301818/eb3b880a-7da9-4aed-9c1f-4c506e3c993b)

### Example Match ID (and possibly Timestamp)

demo

**Comment by Sensei1999** [comment]
I noticed this too and did some more testing. It only happens if you pick the lvl25 talent for +1 wave.

**Comment by BradMuir** [comment]
issue should be fixed in the next build! 🏹
