### ISSUE TITLE
7.34 - Morphling Aghanim's Scepter Enemy Illusion Damage Incorrect

### ISSUE THREAD

**Issue by c5shen** [ValveSoftware/Dota2-Gameplay#10437]
### Ability name

Morph

### Description

The new Morphling Aghanim's scepter creation of the illusion seems to have more than 100% of the target attack point. To replicate:

1. Spawn Skywraith Mage at level 1 as enemy (0 armor point at level 1, easy to track the damage done)
2. Use Morphling Aghanim's on Skywraith Mage (create an illusion).
3. Hit the enemy Skywraith Mage with the Illusion.

(optional) to get the correct damage for 100% of Skywraith Mage right click damage:
1. Spawn an ally Skywraith Mage.
2. Hit the enemy Skywraith Mage with the ally.

Images to the two scenarios: [Imgur Link](https://imgur.com/a/2Kk68bz)

### Example Match ID (and possibly Timestamp)

N/A

**Comment by c5shen** [comment]
To add: my guess is that the code incorrectly applies an **additional 100%** attack damage to the illusion, resulting in a total of 200% outgoing attack damage for the illusion.

**Comment by chrisf-valve** [comment]
This has been fixed in the latest update.
