### ISSUE TITLE
Elder Titan New Stomp change

### ISSUE THREAD

**Issue by come219** [ValveSoftware/Dota2-Gameplay#10438]
Elder Titan's Echo Stomp when casted no longer causes the spirit to stop moving and finish casting the stomp.

Previous update: Elder Titan could control where the spirit would stomp.

In 7.34, the spirit stomps while also being moved towards Elder Titan.

Not sure if that was a direct nerf that was also not mentioned but it is definitely a major change since Elder titan cannot perform the trick effectively and sometimes not able to stomp like previous instances.

**Comment by tommy1416** [comment]
Please fix this :)

**Comment by HonestCosby** [comment]
I can’t even describe how brutal and awful this is as an ET spammer. I would very often return the spirit to move it along a path to set up my stomps and along with the shard not being able to be toggled with when the hero is selected or after the stomp animation has started has made my favorite hero feel unplayable. I understand if he has to be nerfed but I can’t understand my valve would have to mess with the basic mechanics like this that have become muscle memory to me for years.

**Comment by eboug92** [comment]
Potentially related ET issue introduced in 7.34: https://github.com/ValveSoftware/Dota2-Gameplay/issues/10420#issue-1842231951

**Comment by dosha212113** [comment]
Yeah, that should be fixed.

**Comment by eboug92** [comment]
Fixed now: https://store.steampowered.com/news/app/570/view/7160213079732689910?l=english

Fixed an issue where Elder Titan Astral Spirit would keep flying without stopping when casting Echo Stomp
