### ISSUE TITLE
Ninja Gear can AoE smoke allies if they walk through the carrier of Ninja Gear

### ISSUE THREAD

**Issue by TheZett** [ValveSoftware/Dota2-Gameplay#10442]
### Item name

Ninja Gear

### Description

Smoke's new "secondary_application_radius", that applies the smoke effect to allies that come within 300 AoE of the Smoker user, seems to be functional for Ninja Gear as well.

The "secondary_application_radius" for Ninja Gear seems to be set to 1 AoE though, thus phased movement (e.g. Phase Boots) is required for it to be able to apply the smoke effect to allies.

Ninja Gear should be changed to get its own smoke modifier, so it is not affected by future changes to Smoke of Deceit that might cause bugs with Ninja Gear.

### Example Match ID and Timestamp

explanation provided above

**Comment by BradMuir** [comment]
should be fixed in the next patch! 🚭
