### ISSUE TITLE
Meepo Earthbind

### ISSUE THREAD

**Issue by ToiNguBo475** [ValveSoftware/Dota2-Gameplay#10452]
### Ability name

Earthbind

### Description

Meepo earthbind has infinite cast range
![20230809115103_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/86058158/a60d41e3-b782-455e-a28e-848ee9f45eac)

### Example Match ID (and possibly Timestamp)

7276707984

**Comment by BradMuir** [comment]
should be fixed in the next update! 🤡 🤡 🤡 🤡 🤡
