### ISSUE TITLE
Ubuntu Linux post-game screen Player Items tab crash

### ISSUE THREAD

**Issue by WillMatthews** [ValveSoftware/Dota2-Gameplay#1045]
### Description

Dota 2 consistently crashes when clicking on clicking "Player Items" in the graphs tab when looking at a past match's 'postgame view'. Sometimes it occurs when changing tab out of the player items tab.
Both my system (18.04, detailed below) and my friend's system (20.04) have this problem, we both have multiple display configurations but different window managers (GNOME for me, XMonad for him).

The game just freezes and I have to send a SIGKILL to it for it to close, it's totally unresponsive to anything else.
If there's anything else I can add please let me know, many thanks.

OS: Ubuntu 18.04.6 LTS x86_64
Kernel: 5.4.0-107-generic
Uptime: 11 days, 18 hours, 44 mins
Packages: 3495
Shell: zsh 5.4.2
Resolution: 1920x1080, 1920x1080
DE: GNOME 3.28.4
WM: GNOME Shell
WM Theme: Adwaita
Theme: Adwaita-dark [GTK2/3]
Icons: Ubuntu-mono-dark [GTK2/3]
Terminal: x-terminal-emul
CPU: AMD Ryzen 5 3600X 6- (12) @ 3.8
GPU: NVIDIA GeForce RTX 2060 SUPER
Memory: 24473MiB / 32036MiB

**Comment by LokeLok** [comment]
There is a separate github for Linux and Mac, you should post it there instead. They're very helpful over there: https://github.com/ValveSoftware/Dota-2

**Comment by WillMatthews** [comment]
> There is a separate github for Linux and Mac, you should post it there instead. They're very helpful over there: https://github.com/ValveSoftware/Dota-2

Done. I will leave this issue open until the bug is resolved.
