### ISSUE TITLE
OD's new ulti effect doesn't work

### ISSUE THREAD

**Issue by elyra1** [ValveSoftware/Dota2-Gameplay#10460]
### Ability name

Sanity's Eclipse + Astral Imprisoment

### Description

New ulti effect doesn't work, if you use it on enemy that in astral imprisoment.

https://github.com/ValveSoftware/Dota2-Gameplay/assets/115139605/39cf8f20-c661-40cc-bbdc-2e0ac112f036

### Example Match ID (and possibly Timestamp)

-

**Comment by emonikaa** [comment]
Please fix this bug. this is a huge bug which affects the game play especially in the early game.
