### ISSUE TITLE
Doom level 25 talent "apply mute" doesn't work

### ISSUE THREAD

**Issue by shubhrathi** [ValveSoftware/Dota2-Gameplay#10468]
### Ability name

Doom

### Description

Doom level 25 talent "apply mute" doesn't work

https://github.com/ValveSoftware/Dota2-Gameplay/assets/12682588/3720542a-07a2-4f65-854a-a3c867656bcb

### Example Match ID (and possibly Timestamp)

NA

**Comment by Aluerie** [comment]
#10453 adresses

**Comment by peroni981** [comment]
classic dota bug

**Comment by peroni981** [comment]
2 bug on doom you can't mute enemy and you cant heal your self when you use aganim on you. same for your allies with ganim your allies near you cant heal.
