### ISSUE TITLE
7.34 Patсh Witch doctor ward does not penetrate status resistance

### ISSUE THREAD

**Issue by P1irate** [ValveSoftware/Dota2-Gameplay#10461]
### Ability name

Death Ward

### Description

After changing the damage type of the Death Ward ability to pure, the line "Now the totem deals pure damage passing through immunity to effects" was added, but when checking in the lobby, I noticed an error, projectiles flying at the main target do not pierce the resistance to the effect (checked on the abilities of Rage Lifestealer and Blade Fury Juggernaut), only his bounces with Aganim's scepter do this. Attached file where it is visible.
![witch_doctor_ward_bug](https://github.com/ValveSoftware/Dota2-Gameplay/assets/44859445/1a432f45-d076-4cf7-8767-cc2000245395)

### Example Match ID (and possibly Timestamp)

 Demo mode

**Comment by P1irate** [comment]
Death ward bounces even pierce BKB, although the description says that BKB grants immunity to pure and reflected damage.

**Comment by P1irate** [comment]
Death ward bounces even pierce BKB, although the description says that BKB grants immunity to pure and reflected damage.
![bkb witch doctor ](https://github.com/ValveSoftware/Dota2-Gameplay/assets/44859445/07fd8384-385c-4a57-86db-4c2ea13eb2e0)

**Comment by adelalyasyn** [comment]
@IngEyn 
''This ability does not directly imply that it provides the user with debuff immunity; it is described but not defined in-game so if we would take the official description at face value, Black King Bar's Avatar ability does not provide debuff immunity but damage immunity to pure damage (amongst other things, that aren't important in this case). Therefore the Death Ward should not be able to damage the user for the duration of Avatar.''

Bain ult is pure and it deals dmg to enemy even if they have BKB active

**Comment by P1irate** [comment]
I just checked it, now it breaks through immunity to magic and BKB and into skills, apparently this is the correct way BKB works, the bug has been fixed
