### ISSUE TITLE
Ult readiness indicator not working properly for Brewmaster with Aghs purchased.

### ISSUE THREAD

**Issue by Saggentemp** [ValveSoftware/Dota2-Gameplay#1048]
### Ability name

Primal Split

### Description

The ultimate ready status icon (the green/blue/black square tilted 45 degrees below the portraits of teammates at the top of the UI) does not always display the correct status of your ultimate skill after you buy Aghanim's scepter on Brewmaster. I assume it has something to do with the charges and other heroes with charge based ultimates might have a similar issue, but I'm too lazy and drunk to check.
On Brewmaster in particular it can become annoying to keep track of your ultimate charges when the ultimate is active as your main hero becomes hidden and knowing whether it will be ready when you reassemble is important.

As a QOL suggestion, I think having a number to indicate the amount of charges ready at the top of the screen on the indicator icon would be helpful for all team compositions that have a hero with a charge based ultimate spell.

### Example Match ID (and possibly Timestamp)

Just play Brewmaster for one game and buy aghs

**Comment by TheUnholyWrath** [comment]
The underlying issue (#54) hasn't been fixed, but Brewmaster has a new aghs now so you can close this.

**Comment by Nathanael-Valve** [comment]
The underlying issue was fixed in today's patch.
