### ISSUE TITLE
7.34 Veil of Discord does not deal damage to Ember Spirit's Flame Guard (Visual Bug)

### ISSUE THREAD

**Issue by nvwhy** [ValveSoftware/Dota2-Gameplay#10481]
### Ability name

Flame Guard

### Description

As tested, Veil of Discord dealt 200 damage as stated to Glimmer Cape's magic barrier (and even every other type of barrier, including but not limited to Aphotic Shield, Shield Crash, Pavise, Blood Mist, and Shield rune).
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/141827847/34e2b948-d291-4d35-bf5a-7859b62493df)

However, it does not work against Flame Guard which is categorized as a magic barrier in its description.
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/141827847/b541c1d3-f44d-4c67-ade9-de401b8563d7)

It only deals damage to the magic barrier on the second attempt.
1st attempt:
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/141827847/b1d2f83a-da84-4be1-97fe-ceffe9ce48c5)

2nd attempt:
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/141827847/7997a17c-574a-4397-946e-8aaccd210ee0)

3rd attempt:
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/141827847/afdcbcaa-401d-4d3a-bdee-21b80b112768)

4th attempt:
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/141827847/f08f1d23-1c24-43d6-b4d9-b44ac85638dd)

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/141827847/8d93d027-2736-4c92-b7a2-79d06da65e3e)
Magic resistance was 34%, thus damage dealt should be 132 per attempt. It showed 140 per attempt instead. Regardless, the barrier was gone in 4 attempts, which should be right. 

It's a visual bug indeed. Please refer to #8884 

### Example Match ID (and possibly Timestamp)

Demo Mode

**Comment by Aluerie** [comment]
it's only visual bug #8884
