### ISSUE TITLE
Dazzle -- Bad Juju does not reduce recharge times of items/abilities

### ISSUE THREAD

**Issue by blessedmulligan** [ValveSoftware/Dota2-Gameplay#10483]
### Ability name

Bad Juju

### Description

Notably, Bad Juju does not reduce the recharge time of Hand of Midas.

If stolen by a Rubick (or in ability draft) along with a charge-based ability, it will also not decrease the recharge time. This is inconsistent with Chakra Magic, which does reduce (non-ultimate) recharge times.

### Example Match ID (and possibly Timestamp)

n/a

**Comment by chrisf-valve** [comment]
This has been fixed in the latest update.
