### ISSUE TITLE
Phantom Assassin's Level 25 Talent not working

### ISSUE THREAD

**Issue by Nobody17** [ValveSoftware/Dota2-Gameplay#10486]
### Ability name

+7% Coup de Grace Chance

### Description

The 7% Coup de Grace Chance from the talent is not applied.
I tested this in Demo mode with two PAs, one with the talent and one without. Both have the same DPS.

The right one without the talent:
![pa bug 2](https://github.com/ValveSoftware/Dota2-Gameplay/assets/24973487/72d605a0-a8ca-40f8-a0fb-0516dbea8f20)

The left one with the talent:
![pa bug](https://github.com/ValveSoftware/Dota2-Gameplay/assets/24973487/52336495-9995-4b67-919b-4e8019e88e56)

### Example Match ID (and possibly Timestamp)

No match ID

**Comment by BradMuir** [comment]
should be fixed in the next patch. 🩸 🩸 🩸 🩸 🩸 🩸 🩸
