### ISSUE TITLE
Stealing Dark Ascension on Rubick refreshes all spells, including itself (apart from Spell Steal)

### ISSUE THREAD

**Issue by SebboScruff** [ValveSoftware/Dota2-Gameplay#10485]
### Ability name

Spell Steal; Dark Ascension

### Description

If Rubick steals Night Stalker's Ultimate, Dark Ascension, it will refresh all non-ultimate spells on cast as per the changes in 7.34.
However, since it isnt an ultimate on Rubick, it refreshes itself, essentially turning it into a 0-cooldown refresher orb. Example given below:

https://github.com/ValveSoftware/Dota2-Gameplay/assets/36053779/2eb56e04-e5ea-490b-8f5d-03f831dbf7bb

### Example Match ID (and possibly Timestamp)

Video attached in description

**Comment by chrisf-valve** [comment]
This has been fixed in the latest update.
