### ISSUE TITLE
Phantom Assassin -Coup De Grace Buff Bug 7.34

### ISSUE THREAD

**Issue by d-dawgg** [ValveSoftware/Dota2-Gameplay#10498]
### Ability name

Coup De Grace

### Description

PA's Ultimate - Coup De Grace's is an ultimate  buff. Throughout the game's  history, buffs provided by ultimate's have always been 'not purgeable'

For whatever reason, the new Coup De Grace Buff is Purgeable. Can you please fix it for consistency, or state it explicitly in the ability that the buff is intended to be purgeable?

![Coup De Grace](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109176085/ec08c9ad-c7d6-457c-84f7-4f8eed49c716)

### Example Match ID (and possibly Timestamp)

Testable in Demo hero

**Comment by mnosuk** [comment]
let's see that's a bug or intentional

**Comment by BradMuir** [comment]
deadly focus is no longer purgable. thanks! 🗡️
