### ISSUE TITLE
Timbersaw - Whirling Death 15 talent bug vs Universal Hero

### ISSUE THREAD

**Issue by apolunderblade** [ValveSoftware/Dota2-Gameplay#10513]
### Ability name

Whirling Death

### Description

Whirling Death additional stat loss doesn't affect Universal Heroes

Timber without talent:
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/46679896/4fb72885-07a0-4622-ab77-0541774164cb)

Timber with talent learned:
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/46679896/b1171d58-36ae-4438-b7f6-eb6af6b6b911)

P.S. Please update Timber outdated talent level 15 talent +6 stacks reactive armor to proper +10 stacks

### Example Match ID (and possibly Timestamp)

Discovered on Demo Mode

**Comment by eugene-valve** [comment]
This should be fixed in the next update, thanks!
