### ISSUE TITLE
Lone Druid Bear Illusions do not benefit from Lone Druid's level.

### ISSUE THREAD

**Issue by Retoonetoo** [ValveSoftware/Dota2-Gameplay#10512]
### Ability name

Summon Spirit Bear

### Description

Illusions created of Lone Druid's Spirit bear do not gain the 90 HP and 5 damage per hero level that Lone Druid has.
![Screenshot_794](https://github.com/ValveSoftware/Dota2-Gameplay/assets/2886858/3e521816-17b2-435d-9735-3e13d94c7d6e)
![Screenshot_793](https://github.com/ValveSoftware/Dota2-Gameplay/assets/2886858/fcc6f141-7ccc-46a3-937b-aee3c0edbb46)

### Example Match ID (and possibly Timestamp)

No match ID, can be replicated easily in demo hero.

**Comment by SethDusek** [comment]
This appears to be fixed. 
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/9436380/d703bd48-5100-492d-a027-089390720d51)
