### ISSUE TITLE
Midas bug when used by Ogre Magi

### ISSUE THREAD

**Issue by SteambreadC** [ValveSoftware/Dota2-Gameplay#10526]
### Item name

Hand of Midas

### Description

In the latest patch, multiple hands of Midas share cooldown now. 
But when Ogre Magi uses Midas and triggers multicast, the single cast of Hand of Midas will cost all 2 charges.

### Example Match ID and Timestamp

Demo

**Comment by eugene-valve** [comment]
This will be fixed in the next patch, thanks!
