### ISSUE TITLE
Zeus shard stops working after dead

### ISSUE THREAD

**Issue by pegdan** [ValveSoftware/Dota2-Gameplay#10521]
### Ability name

Zeus shard (Lightning Hands)

### Description

The Zeus shard stops to work after dead. It looks like this is an common issue, because there is an reddit post about it.

### Example Match ID (and possibly Timestamp)

7277745166 (for example last dead / end of the game)

**Comment by pegdan** [comment]
The icon looks "active", but is disabled. You have to toggle it off and on again, but this did give me "IT Crowd"-Vibes. Which is good.

**Comment by eugene-valve** [comment]
This should be fixed in the next update, thanks!
