### ISSUE TITLE
Bristleback Aghanim's Scepter Quills Rotate with Hero

### ISSUE THREAD

**Issue by Jawbone999** [ValveSoftware/Dota2-Gameplay#10524]
### Ability name

Bristleback

### Description

When using BristleBack's 7.34 Aghanim's Sceptre, he turns to face away from the targeted point. However, on the last quill spray, when turning back around, the quills will turn with him.

This can be seen in demo by surrounding Bristleback with enemies and casting the Aghanim's Sceptre ability. Some enemies will be hit with 5 times, and others will be hit 1 time. The expected behavior is that the cone of quills would be static upon cast, and would never rotate.

### Example Match ID (and possibly Timestamp)

Demo

**Comment by BradMuir** [comment]
this should be fixed 🦔
