### ISSUE TITLE
Tempest Double now always spawns with at least 1 Hand of Midas charge

### ISSUE THREAD

**Issue by kaaiuta** [ValveSoftware/Dota2-Gameplay#10533]
### Item name

Hand of Midas

### Description

After the recent hotfix, Midas on Tempest no longer loses a second charge if it was off cooldown (#10520), but instead gets both of them every time Tempest Double spawns. 
EDIT: Alt-pinging it shows 0 seconds cooldown, and using only one charge visually shows you still got 2 left

EDIT2: A way to replicate this -

-  You buy Hand of Midas on Arc Warden
-  First Tempest Double spawns with 1 charge initial
-  You have to let Tempest's Midas get to 2 charges WHILE ITS STILL ALIVE (crucial to replicate)
-  After that, you can use two Midases every time you resummon the Tempest, no matter the cooldown.

Using Midas on Tempest while it has 1 charge will always resummon the Tempest with 1 charge, even if its supposed to be on cooldown. Letting Tempest's Midas get to 2 charges while its down will STILL cause it to respawn with 1 charge.

### Example Match ID and Timestamp

7277986295 - 13:22, and another summon on 14:19.

**Comment by TheChetu** [comment]
Another issue in addition to this, additional Midases still function independently on the Tempest Double and the Tempest Double always spawns with at least one charge available in the Midas even if it should have zero based on timing.

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/9092744/7ed02467-3af9-4b28-888f-5e76df343f73)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/9092744/bd1ea159-28b3-4e41-bfc2-04208100be22)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/9092744/606f18a3-5e4b-452e-8652-52b40c5cea58)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/9092744/de266d0a-c73e-4d7e-a54c-d9dd6a1badbe)

**Comment by kaaiuta** [comment]
Something extremely weird is going on, actually. So, double midases are fixed on all heroes, that is out of the way.

In a normal game this is what happens: 

- You buy Hand of Midas on Arc Warden
- First Tempest Double spawns with 1 charge initial
- You have to let Tempest's Midas get to 2 charges WHILE ITS STILL ALIVE (crucial to replicate)
- After that, you can use two Midases every time you resummon the Tempest, no matter the cooldown.

Using Midas on Tempest while it has 1 charge will always resummon the Tempest with 1 charge, even if its supposed to be on cooldown. Letting Tempest's Midas get to 2 charges while its down will STILL cause it to respawn with 1 charge.

I have absolutely no idea what to make of this sequence of events.

**Comment by kaaiuta** [comment]
FIXED

**Comment by xenomorfff** [comment]
why did you mark this issue as solved if the copy of the arc warden still spawns with one charge even though you might have 2

**Comment by kaaiuta** [comment]
> why did you mark this issue as solved if the copy of the arc warden still spawns with one charge even though you might have 2

Because its a different issue. This one was about Tempest getting 2 charges, no cooldown, every time it gets resummoned.
Its true that the issue you described is still present, but idk what to expect, perhaps "not a bug, but a feature"...

**Comment by TheChetu** [comment]
It is definitely a bug. Always spawning with one Midas charge is not a feature. Prior to the two charge patch if the clone Midas was on CD when summoned it would retain the CD time, now it does not retain the CD time and is always summoned with one charge regardless of where the CD/Charge counter was at.
