### ISSUE TITLE
templar assassin bug

### ISSUE THREAD

**Issue by darklonel** [ValveSoftware/Dota2-Gameplay#10549]
### Ability name

TRAP

### Description

When i press ctrl it says ability not learned i dont have lvl 6 to remove alternative use. I can't usually buy items in quick buy, I see an annoying inscription that the ability is not learned

### Example Match ID (and possibly Timestamp)

demo lobby

**Comment by Aluerie** [comment]
It's a case for pretty much all new Ctrl AutoCast alternative additions.

**Comment by flovnes** [comment]
It would be nice if this feature could be toggled.
Disabling it while shop is open would also solve the problem.
Best solution would probably be a different bindable key for the alternative cast added to the hotkeys. 
![dota2_altcast](https://github.com/ValveSoftware/Dota2-Gameplay/assets/106932515/73ec551f-ad7f-4f8a-8b2b-d42198c0aa40)
How queuing up quickbuy items triggers queuing up Alternative cast toggle:
![dota2_27hIZZVjTN](https://github.com/ValveSoftware/Dota2-Gameplay/assets/106932515/20c2e52c-3b01-4cc2-8b24-4610bab8a288)

**Comment by flovnes** [comment]
#10534

**Comment by Saddl3r** [comment]
Yeah I have same problem, was writing my own post but found this:

_When I play Templar Assassin and press "ctrl" I get the error message "Ability not learned". This problem goes away when I learn Psionic Trap. When I've learned ulti and I hold "ctrl" the symbol for TRAP changes, which makes me believe this ability is the issue.

Easy to test in demo.

I have quick cast turned on._

**Comment by flovnes** [comment]
you can close the issue, it has been fixed

**Comment by darklonel** [comment]
> you can close the issue, it has been fixed

ez
