### ISSUE TITLE
[Broodmother] Immotal Limbs of Lycosidae + Spin Web. The web is broken, texture elements are pulled to the center of the map.

### ISSUE THREAD

**Issue by Astiberon** [ValveSoftware/Dota2-Gameplay#10558]
### Cosmetic Item Name

Limbs of Lycosidae

### Description

Immotal Limbs of Lycosidae + Spin Web. 
The web is broken, texture elements are pulled to the center of the map.
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/107125193/de6f009d-a3c1-403d-96e0-2062bfd041e2)

### Example Match ID

-

**Comment by Astiberon** [comment]
FIXED

**Comment by LokeLok** [comment]
Not fixed, still happens.

**Comment by Astiberon** [comment]
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/107125193/8dc30fd3-809e-4e48-8c54-c0785382dc9c)

**Comment by Astiberon** [comment]
FIXED
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/107125193/68d77796-59fb-4e0b-8853-cece605cc904)
