### ISSUE TITLE
Witch Doctor death ward does not pierce debuff immunity 

### ISSUE THREAD

**Issue by Kurashiv** [ValveSoftware/Dota2-Gameplay#10559]
### Ability name

Death Ward

### Description

Witch doctor ultimate Death Ward does not pierce debuff immunity despite changes 
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/141940181/03c9e998-f9e1-4e1c-b66a-ad50e1d93aee)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/141940181/0021edb5-bb91-484a-8d82-cb705a660cd9)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/141940181/473ea34a-d726-4e1f-8030-71e6ae3ecf84)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/141940181/14112738-69ec-4566-b7be-32734bff5aeb)

### Example Match ID (and possibly Timestamp)

7277308686 - 40:23

**Comment by Avarise831** [comment]
#10461

**Comment by P1irate** [comment]
Just checked, bug fixed, ward deals damage in BKB, please clouse issue
