### ISSUE TITLE
Elder Titan Spirit Stomp Still Broken

### ISSUE THREAD

**Issue by come219** [ValveSoftware/Dota2-Gameplay#10557]
Many issues have been raised regarding this change which has not been raised or mentioned.

Elder titan, when channeling stomp, would previously cause the spirit to stomp at the location as it was returning.

In 7.34 and in 7.34a, the spirit still moves towards Elder titan while still channeling the stomp.

Major gameplay changes were taken away from this change and I think the Elder Titan community would prefer if it were to be reverted such that the spirit stops moving when channeling Echo Stomp. Thank you

Also very sad that you would nerf the stomp radius with no talent or item to get it back 😭.

**Comment by HonestCosby** [comment]
also mentioned hero: #10543

**Comment by eboug92** [comment]
Fixed now: https://store.steampowered.com/news/app/570/view/7160213079732689910?l=english

Fixed an issue where Elder Titan Astral Spirit would keep flying without stopping when casting Echo Stomp
