### ISSUE TITLE
Death ward doesn't pierce debuff immunity

### ISSUE THREAD

**Issue by Klasuren** [ValveSoftware/Dota2-Gameplay#10562]
### Ability name

Death ward

### Description

Witch doctor's spell Death ward does not deal damage to bebuff immunity units even when the description of the spell says it does. I also tried with aghanim's scepter and found out that is the first target the ward hits that does not take damage, the others do take damage when they are on bebuff immunity.

In the match at 25:30 the ward hits invoker who is on bkb, but takes no damage.

### Example Match ID (and possibly Timestamp)

7278842213 - 25:30

**Comment by Avarise831** [comment]
#10461

**Comment by sikleq** [comment]
Fixed
