### ISSUE TITLE
[Qop] Sonic Wave Pur Damage pierce bkb

### ISSUE THREAD

**Issue by S1lv3r4ng3l** [ValveSoftware/Dota2-Gameplay#10565]
### Ability name

Sonic Wave

### Description

Sonic wave pierce bkb

https://streamable.com/0kleme

### Example Match ID (and possibly Timestamp)

7279029202 - 39:10

**Comment by S1lv3r4ng3l** [comment]
Seems legit.

**Comment by BenjinZA** [comment]
Sonic Wave pierces debuff immunity. Working as intended.
