### ISSUE TITLE
Lone Druid bear auto attack bugged

### ISSUE THREAD

**Issue by HEISEN3ERG** [ValveSoftware/Dota2-Gameplay#10570]
### Ability name

Summon Spirit Bear

### Description

since the change applied to lone druid's bear, making it a universal creep hero, it seems it doesn't belong to either "hero auto attack" part of settings nor "controlled unit auto attack" settings, turning both auto attack types to "always" still doesn't work and the bear just stops attacking after each unit is killed, rather than trying to attack the closest unit possible

### Example Match ID (and possibly Timestamp)

7278449533

**Comment by crystalveins** [comment]
ye, i had the same problems when i player ld and there is nothing how you can fix it

**Comment by sikleq** [comment]
Fixed
