### ISSUE TITLE
Buying items during pick phase causes game to crash

### ISSUE THREAD

**Issue by kharon666** [ValveSoftware/Dota2-Gameplay#10578]
### Description

When purchasing items in before game start in the pick phase the game will instantly crash

### Example Match ID (and possibly Timestamp)

7279504592

**Comment by tkchiu** [comment]
Same as above 
using tany

**Comment by Mightykiller817** [comment]
Me too I just bought item and suddenly dota2 crushed

**Comment by kharon666** [comment]
Looks like its been fixed! Thanks for quick resolution - closing this now.
