### ISSUE TITLE
Phantom Assassin's lvl 25 talent not applying to dagger

### ISSUE THREAD

**Issue by d-dawgg** [ValveSoftware/Dota2-Gameplay#10573]
### Ability name

Coup De Grace

### Description

PA's level 25 talent does not apply to dagger crit chance. The talent states "7% coup de grace chance" which implies it should also apply to the dagger crit rate

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109176085/e232d289-daa2-49e9-8b9f-26c4c3d7ba11)

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109176085/678cd39a-ec3e-45e8-a492-36a36eb62020)

Cheers,

Derek

### Example Match ID (and possibly Timestamp)

Testable in demo hero

**Comment by BradMuir** [comment]
should be fixed in the next update! 🗡️

**Comment by d-dawgg** [comment]
Awesome thanks. It should be 'double that of the base chance' per the description
