### ISSUE TITLE
Both Lone Druid and his bear heal each (only the bear should heal LD)

### ISSUE THREAD

**Issue by sikleq** [ValveSoftware/Dota2-Gameplay#10609]
### Ability name

Spirit Link

### Description

The ability allows both the hero and its summon to heal each other with attacks. Pre 7.34 it used to be that only the bear healed Lone Druid. Now it works the same as the old version of the ability million patches ago.

[Video inserted into Reddit post](https://www.reddit.com/r/DotA2/comments/15ohozv/since_734_lone_druid_heals_the_bear_and_vice/)

### Example Match ID (and possibly Timestamp)

none

**Comment by Avarise831** [comment]
#10600

**Comment by sikleq** [comment]
Fixed.

**Comment by sikleq** [comment]
Fixed
