### ISSUE TITLE
Torrent change not being implemented (7.34)

### ISSUE THREAD

**Issue by irismus** [ValveSoftware/Dota2-Gameplay#10601]
### Ability name

Torrent

### Description

> Torrent
Damage and slow are now applied to all enemies in the torrent area throughout the duration, not just to enemies caught by the stun

Sorry for opening this issue, but this feels like it is not being implemented yet.
According to the description, slow and damage should also be applied during the effect delay.

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/74582118/bb830256-6859-40b6-92f2-da1c67ecb14f)

### Example Match ID (and possibly Timestamp)

demo mode

**Comment by LokeLok** [comment]
I can see why you would think so, that line can be a bit confusing. If they meant that it would do damage/slow during the delay, they would probably specify it. Nothing happens before the delay happens and anyone walking into an active Torrent does take damage/slow now. 

> not just to enemies caught by the stun

I think this part of the line indicates that it still works the same delay-wise.

**Comment by irismus** [comment]
>  anyone walking into an active Torrent does take damage/slow now.
Thank you for your time explaining. I think I'll close this for now since it is still working the same delay-wise.
