### ISSUE TITLE
the tempest MAGNETIC FIELD adds bonus attack damage (green number) instead of base damage

### ISSUE THREAD

**Issue by Syntax-J** [ValveSoftware/Dota2-Gameplay#10644]
### Ability name

MAGNETIC FIELD

### Description

> MAGNETIC FIELD
Tempest version no longer provides a magical attack bonus
Tempest version now provides 20/40/60/80 base bonus attack damage

It seems the tempest bubble adds bonus attack damage (green number) instead of base damage 

### Example Match ID (and possibly Timestamp)

any

**Comment by duckbotx** [comment]
they usually confuse bonus base damage and bonus damage based on a percentage of base damage

**Comment by Syntax-J** [comment]
> they usually confuse bonus base damage and bonus damage based on a percentage of base damage, see Vengeful Spirit's Vengeance Aura and Double Damage Rune though in Arc's case, the given bonus base damage is flat so it must be not the green bonus, the base bonus damage is not mentioned in game but only in the patch update notes edit: the base damage increase is seen in the buff info

solved in 7.34b 
> Over the last few days we've addressed several gameplay issues:
>
>Fixed Arc Warden Magnetic Field granting bonus damage instead of base damage
Fixed Bane illusion waking up Nightmared Units
Fixed Brewmaster Level 25 Talent Drunken Brawler Passive on brewlings Primal 
.......
