### ISSUE TITLE
Dawnbreaker spell abilities hotkeys in settings are not the way it should be.

### ISSUE THREAD

**Issue by nelsonchacko98** [ValveSoftware/Dota2-Gameplay#10657]
### Description

The ultimate ability is not in the last place like it is for all the other heroes.

<img width="1280" alt="image" src="https://github.com/ValveSoftware/Dota2-Gameplay/assets/23289511/cbfd838e-4b09-417a-b9cc-9ceeab6c4799">

### Screenshots

<img width="1280" alt="image" src="https://github.com/ValveSoftware/Dota2-Gameplay/assets/23289511/c0605901-f0cb-4238-9095-6b4a35644a56">

**Comment by Avarise831** [comment]
#7603

**Comment by nelsonchacko98** [comment]
> 

Thanks closing this.
