### ISSUE TITLE
Lone druid shard bug from tormentor 

### ISSUE THREAD

**Issue by steven-basart** [ValveSoftware/Dota2-Gameplay#10650]
### Item name

Aghnim shard

### Description

Lone druid bought his own shard and after defeating tormentor the bear had empty shard slot but it went to lone druid instead. 

It wasn't my match I have the clip from qovfa stream.
https://clips.twitch.tv/HandsomeCautiousPastaHassanChop-tZ5pwa8TptqTJ4kL

Please ignore the match I'd and timestamp as it's not from my own game. 

### Example Match ID and Timestamp

11675941888 - 25:22

**Comment by Avarise831** [comment]
#10621

**Comment by Avarise831** [comment]
#10615

**Comment by steven-basart** [comment]
Duplicate
