### ISSUE TITLE
Tempest Double always loses 2nd Midas charge on (re-)summon

### ISSUE THREAD

**Issue by TheZett** [ValveSoftware/Dota2-Gameplay#10718]
### Item name

Hand of Midas

### Description

The new charge-based Midas is not properly working on Arc Warden's Tempest Double.

If the Tempest Double's Hand of Midas ever has 2 charges, and then the Double gets (re-)summoned, it will always spawn with just 1 charge on its Midas.

Additionally this also causes the Hand of Midas' recharge timer to desync on the Tempest Double (not sure if just visually or also functionally).

**Case 1:** This happens when the Double gains its 2nd charge while it is dead and then gets summoned afterwards.
**Case 2:** This also happens when the Double gains its 2nd charge while it is alive, and then gets resummoned via e.g. Refresher Orb.

**Video (case 1):** https://youtu.be/DKUdRe8QhwA
**Video (case 2):** https://youtu.be/aJ-L_M86EyQ

### Example Match ID and Timestamp

two videos are provided above

**Comment by SiqingYu** [comment]
I encountered the same issue in gameplay. It has an impact on Arc Warden's farming speed.

**Comment by TheZett** [comment]
This is still bugged, the Tempest Double ALWAYS loses its 2nd charge on Midas upon being summoned.

**Comment by TheZett** [comment]
This is STILL bugged in 7.34d, even though 7.34d claims to having fixed this issue.

The clone still loses its 2nd Midas Charge upon being summoned, if its Midas had 2 charges prior to being summoned.

**Comment by TheZett** [comment]
This has been fixed.
