### ISSUE TITLE
NP Sprout Tango Interaction

### ISSUE THREAD

**Issue by TxNoto** [ValveSoftware/Dota2-Gameplay#10742]
### Item name

Tango

### Description

When eating a tango from NP's sprout, it does not give the regenerative benefits.

### Example Match ID and Timestamp

7287017148 - 0:40 Gametime top lane

**Comment by LokeLok** [comment]
Intended.

> Consuming a tree spawned from Sprout with a Tango no longer grants healing

This is the line from the 7.34 patch stating it no longer grants healing benefits. 

You can close this issue.
