### ISSUE TITLE
Mortimer's Kisses is canceled by self casting Glimmer Cape

### ISSUE THREAD

**Issue by NKeklikian** [ValveSoftware/Dota2-Gameplay#10756]
### Item name

Glimmer Cape

### Description

Since Snapfire's ultimate is a channeled spell, it should not be canceled by casting Glimmer Cape

### Example Match ID and Timestamp

7287965743 - 22:38

**Comment by NKeklikian** [comment]
Looks like Mortimer's Kisses doesn't count as a channeled spell... weird, but enough to close the issue.

**Comment by Daar543** [comment]
> Looks like Mortimer's Kisses doesn't count as a channeled spell... weird, but enough to close the issue.

I would advise to reopen it, as the spell execution is meant to lock you in place, but also allow you to turn. Therefore it makes sense to allow it everything you are able to do during channel, in the spell hierarchy.
