### ISSUE TITLE
lone druid aghanim shard from tormentor didn't work

### ISSUE THREAD

**Issue by HEISEN3ERG** [ValveSoftware/Dota2-Gameplay#10766]
### Description

I bought shard my my hero and not the bear, and few minutes after that I killed tormentor and it said that it gave lone druid the shard, I had bought the shard for my hero, so I checked my bear, but my bear didn't also have the shard, so the shard from tormentor wasn't given to anyone

### Example Match ID (and possibly Timestamp)

7287942600

**Comment by Avarise831** [comment]
#10615

**Comment by BryanHongRMIT** [comment]
Same problem - Match ID below around 38mins when tormentor was killed

7288861950
