### ISSUE TITLE
Luna Lucent Beam + Eclipse damage pierces debuff immunity

### ISSUE THREAD

**Issue by achoooooo** [ValveSoftware/Dota2-Gameplay#10764]
### Ability name

Lucent Beam, occuring in 7.34b

### Description

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/80604052/7530c085-0caf-4ff4-88fb-64a6b2bb4a36)

**Expectation**: Luna's spells Lucent Beam and Eclipse should not damage or stun debuff immune target, because neither Eclipse, or Lucent Beam are marked as piercing debuff immunity.

**Actual beahavior**: For targets that are spell immune, both Eclipse and Lucent Beam will not stun, but will still deal magical damage to the target. This is magnified by Luna's Aghanim's Scepter upgrade, which removes the limit on times you can be hit.

I searched through the logs and couldn't find any change showing this is the intended behavior, but even if this is working as expected the tooltip is incorrect. I am also making the assumption that debuff immunity here means that the target absolutely will not receive any effects of the debuff during that period, which my cursory research seems to indicate is true, but I'm honestly not sure I understand this mechanic well enough to say for certain if this is the expected behavior.

My team had a very hard time dealing with an Aghs Luna, we kept getting owned by Eclipse in a game that was otherwise a stomp. Luckily we barely were able to pull it together win, but this spell definitely felt overpowered in my game (match id 7288332338). I noticed this when I died to just Eclipse after popping my BKB.

### Example Match ID (and possibly Timestamp)

7288332338

**Comment by LokeLok** [comment]
Intended.

> Avatar Reworked: applies a basic dispel. Provides Debuff Immunity for the duration: any negative effect on the user won't affect them, Magic Resistance increased by 50% and they're immune to pure and reflected damage. These only affect spells that don't pierce Debuff Immunity

Taken from 7.33 patch notes. BKB only grants 50% resistance instead of having spell immunity and that is the reason why Lucent Beam did damage. You can close this issue.
