### ISSUE TITLE
Clockwerk Shard and Aghanims preview does not shows the cooldown and mana cost of the skills. Jetpack does not indicate that it is dispellable anywhere.

### ISSUE THREAD

**Issue by 5Starkiller3** [ValveSoftware/Dota2-Gameplay#1077]
### Hero and spell

Clockwerk - Overclocking and Jetpack

### Description

On Clockwerk, when you mouse over to the Aghanims and Shard part of the UI, it does not show the mana cost and cooldown of the skills Overclocking and Jetpack.
Jetpack (the buff that makes you fly) is dispellable but it isnt indicated at anywhere on the actual skill or the shard preview.

### Screenshots

![cse](https://user-images.githubusercontent.com/8082443/173177441-d7af2b58-72b8-4755-9497-e11aae12156c.jpg)

**Comment by TheUnholyWrath** [comment]
This has been fixed, you can close this.

**Comment by 5Starkiller3** [comment]
Sorry for not checking it. Closing now
