### ISSUE TITLE
Gem bug

### ISSUE THREAD

**Issue by Tiera** [ValveSoftware/Dota2-Gameplay#10772]
### Item name

Gem of true sight

### Description

After the next use of the gem, the cooldown simply stopped refreshing. 
I threw it on the ground, passed it to another player. Nothing worked  

### Example Match ID and Timestamp

7289311168 - 49:30

**Comment by Avarise831** [comment]
#8773

**Comment by Nathanael-Valve** [comment]
Fixed in next update.
