### ISSUE TITLE
10 year anniversary update broke the game on linux

### ISSUE THREAD

**Issue by neimovirne** [ValveSoftware/Dota2-Gameplay#10794]
### Description

After start game freeze and is unplayable

**Comment by TimYi** [comment]
The same issue, wait for update.

**Comment by Sectoid** [comment]
Experiencing the same issue. Debian 12, nVidia GTX1070, driver 525.125, Vulkan API.

**Comment by diniciacci** [comment]
Hello, looks like the main issue is being tracked upstream [#2414](https://github.com/ValveSoftware/Dota-2/issues/2414).

This can be closed.

**Comment by TimYi** [comment]
Upgrade my nvidia driver to nvidia-driver-535 resolved this issue.

**Comment by MhDiViBe** [comment]
Also have this problem with AMD Graphic Card. Can't play the game since 10th anniversary.
