### ISSUE TITLE
Tango bug every game constantly

### ISSUE THREAD

**Issue by stevanstetzvanin** [ValveSoftware/Dota2-Gameplay#10807]
### Item name

Tango

### Description

I use tango in a tree and the hero star walking to a random place.

Happens everygame. since update 7.34, simple as that.

Its killing my games, because I can't use tango, so please fix it.

### Example Match ID and Timestamp

any match

**Comment by Aluerie** [comment]
This bug only happens if you use modded maps. Remove them.

**Comment by stevanstetzvanin** [comment]
> This only happens if you use modded maps.

Yeah I figured that now, I was using a terrain from 7.33, so I updated and it got fixed finally @
