### ISSUE TITLE
Puck Dream coil with refresher orb (7.34b still work)

### ISSUE THREAD

**Issue by Avarise831** [ValveSoftware/Dota2-Gameplay#10802]
### Ability name

Dream coil

### Description

https://github.com/ValveSoftware/Dota2-Gameplay/assets/37029303/dbded69f-4ecc-429c-88bb-3321a383d04a

### Example Match ID (and possibly Timestamp)

-

**Comment by LokeLok** [comment]
Just tested in demo mode and it seems to be fixed, can you test to see if it works for you as well?
