### ISSUE TITLE
Misssing Persona

### ISSUE THREAD

**Issue by engrenanm** [ValveSoftware/Dota2-Gameplay#10838]
### Description

Win a Void Spirit Persona, but cant find her
the item dont apear for me to use

### Screenshots

![WhatsApp Image 2023-08-19 at 23 15 51 (1)](https://github.com/ValveSoftware/Dota2-Gameplay/assets/142703319/266fe832-5ab8-4f3a-9350-6feaaf908145)
![WhatsApp Image 2023-08-19 at 23 15 51](https://github.com/ValveSoftware/Dota2-Gameplay/assets/142703319/40cdca26-7b63-45e9-9324-9eb2692657df)

**Comment by LokeLok** [comment]
Go to Armory and unbundle the set.

**Comment by interstellarjam** [comment]
> Go to Armory and unbundle the set.

Thanks for posting this. Honestly I clicked around every part of the interface but the armoury is basically invisible if you've never used it (appeared during a period I wasn't playing Dota).

**Comment by LokeLok** [comment]
> 

No problem. You're not alone in not knowing this, there are surprisingly many people unaware of how this works.
