### ISSUE TITLE
Enchant Remnant didn't grant the properties of a Stone Remnant to Earth Spirit

### ISSUE THREAD

**Issue by bertgalit75** [ValveSoftware/Dota2-Gameplay#10842]
### Ability name

Enchant Remnant

### Description

• Enchant Remnant didn't grant the properties of a Stone Remnant to Earth Spirit
• It has a 31.5 second cooldown, but when I used it, it became a 5 second cooldown skill

### Example Match ID (and possibly Timestamp)

7292377269 - 28:18

**Comment by TheUnholyWrath** [comment]
You used Enchant Remnant on a Stone Remnant. The tooltip documents this interactions please go read it. There is no bug here, close this issue.
