### ISSUE TITLE
Mic does not work on linux from patch 7.34

### ISSUE THREAD

**Issue by Blu3cr0ss** [ValveSoftware/Dota2-Gameplay#10865]
### Description

I don't remember exactly, but I think this problem started in patch 7.34. The microphone works even in steam, but not in dota. I have not changed any sound settings. It was working and then it just stopped working

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/49835293/9b3d9a19-fce4-4505-8ee7-039793466e7a)

dota sound settings (microphone test shows that there is no sound):
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/49835293/665b2bf3-621b-4093-ac03-2df62f3e784c)

steam sound settings (microphone test shows that there is sound):
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/49835293/4ec45227-cb03-4a10-884e-d633828165fc)

**Comment by ryuoryuo** [comment]
Возможно микрофон в настройках винды не одноканальный?

![изображение](https://github.com/ValveSoftware/Dota2-Gameplay/assets/15220217/1835db06-b3e1-45f7-b48d-6004f5105319)
Вот здесь нужно выставить 1 канал, и микрофон (в случае использования звуковой карты) вставить в 1 Input, возможно поможет.

**Comment by Blu3cr0ss** [comment]
> Возможно микрофон в настройках винды не одноканальный?
> 
> ![изображение](https://github.com/ValveSoftware/Dota2-Gameplay/assets/15220217/1835db06-b3e1-45f7-b48d-6004f5105319)
> Вот здесь нужно выставить 1 канал, и микрофон (в случае использования звуковой карты) вставить в Input 1, возможно поможет. 

Написано же Linux)) 
Вообще я 2 недели в доту не играл надеюсь уже пофиксили

**Comment by ryuoryuo** [comment]
А, точно) Просто натыкался на реддите на похожую проблему, и там у чела винда была, перепутал

Думаю не пофиксили, хд, но в любом случае - думаю проблема может быть в этом независимо от ОС, если микрофон прилетает на второй канал, а игра пытается забрать его с первого

**Comment by Blu3cr0ss** [comment]
> А, точно) Просто натыкался на реддите на похожую проблему, и там у чела винда была, перепутал
> 
> Думаю не пофиксили, хд, но в любом случае - думаю проблема может быть в этом независимо от ОС, если микрофон прилетает на второй канал, а игра пытается забрать его с первого

Я кстати тоже на реддит постил, но чет и валв на своём баг трекере и комьюнити на реддите положило болт на этот issue. Интересно вольво вообще читают тут баги или репо по рофлу сделали 🤔

**Comment by Blu3cr0ss** [comment]
>  Думаю не пофиксили, хд, но в любом случае - думаю проблема может быть в этом независимо от ОС, если микрофон прилетает на второй канал, а игра пытается забрать его с первого
Вообще я в звуке не шарю и хз че это за каналы. Но за наводку спасибо, погуглю

**Comment by Blu3cr0ss** [comment]
Fixed
