### ISSUE TITLE
Mirana's skin

### ISSUE THREAD

**Issue by Ekronus3** [ValveSoftware/Dota2-Gameplay#10860]
### Item name

Mirana 10-Year Anniversary

### Description

**Today(20.09.2023) I was got a skin of Mirana because of 10-Year Anniversary.**

![photo_2023-08-20_21-45-07](https://github.com/ValveSoftware/Dota2-Gameplay/assets/142748007/7ecf0fde-3db5-4e11-8ec9-b13aa2a9d1c2). 
**When I want to check it I noticed that he wasn't there. I have proves in the photos**. 

![photo_2023-08-20_21-46-25](https://github.com/ValveSoftware/Dota2-Gameplay/assets/142748007/0eae7db3-ad71-436b-a3b5-e609ed682f40)

### Example Match ID and Timestamp

.

**Comment by LokeLok** [comment]
Go to Armory and unbundle the set.
