### ISSUE TITLE
Gem stopped working 

### ISSUE THREAD

**Issue by Dota2bug** [ValveSoftware/Dota2-Gameplay#10880]
### Item name

GEM OF TRUE SIGHT

### Description

Gem of true Sight stopped working at 51:20 on Silencer. 
The item became frozen (locked on cooldown) and was not revealing invisible items. I scanned at 51:20 and it immediately went into lock and was no longer usable. see attached image 
This is not the first time it has happened to me either around the 50 minute mark. 

<img width="887" alt="Gem bug" src="https://github.com/ValveSoftware/Dota2-Gameplay/assets/142896199/f30b8b80-3a6f-4ded-86f5-16d96385881e">

### Example Match ID and Timestamp

7297434218 @ 51:20

**Comment by Avarise831** [comment]
#8773

**Comment by Dota2bug** [comment]
> #8773

Ty Avarise, sorry first time on Github

**Comment by Nathanael-Valve** [comment]
Fixed in next update.
