### ISSUE TITLE
Cosmetic The Alpine Stalker set not received for my inventory

### ISSUE THREAD

**Issue by apacheontour** [ValveSoftware/Dota2-Gameplay#10905]
### Cosmetic Item Name

The Alpine Stalker set

### Description

I open the 10th aniversary chest and im got The Apline Stalker set, but this item not received in my inventory

### Example Match ID

123966742

### Screenshots

![1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/143018573/86494c55-2349-4dc2-94f7-f367e8a254ba)
![2](https://github.com/ValveSoftware/Dota2-Gameplay/assets/143018573/543c7bc9-9c0e-41f4-a875-d8baee65464f)

**Comment by irismus** [comment]
Have you unbundled your chest yet?
