### ISSUE TITLE
(WK)Wraith King with Arcana breaks Kinetic: Wraith Spin full Crit spin Animation

### ISSUE THREAD

**Issue by Aphotic** [ValveSoftware/Dota2-Gameplay#1091]
### Cosmetic Item Name

Kinetic: Wraith Spin + Crown of the One True King

### Description

with new immortal effects being useable on other items now I'm experimenting a lot with all my hero skins
i read Jeff said Arcanas take priority on all even immortals
but I like to plea a case(I'm sure there are many more) here that 
Kinetic: Wraith Spin offers much better in-game full spin crit animation than Arcana
with Arcana + Kinetic: Wraith Spin, it just uses about 50% of the spin animation.

so why not **_let us choose even to override Arcana effects_**? :}
since the game is getting more Arcanas over the years
if we own it then it is ours to choose what overrides or not?

what do you guys think? 

example videos i've found on both Animations:

Kinetic: Wraith Spin
https://dota2.fandom.com/wiki/Kinetic:_Wraith_Spin

w/wo Arcana 
https://reddit.com/link/hi5zix/video/j4xtfypvaw751/player

half-spin
https://www.youtube.com/watch?v=DBCJb8wbGWU

read Suggestion here: #1153 

### Example Match ID

Demo

**Comment by DeadPANK** [comment]
+1, 2 years after arcana reliase valve cant fix it...

**Comment by Aphotic** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/1838#issuecomment-1188222931
fixed! case closed!
