### ISSUE TITLE
UI rendering bug on Mac

### ISSUE THREAD

**Issue by aTan-aka-Xellos** [ValveSoftware/Dota2-Gameplay#10921]
### Description

Since 23-08-2023, having bug where the game world doesn't render properly. It happened without game restart (one game was ok, next one - with this bug).
Notice on the screenshot that the rendering of the elements unrelated to the game world are completely okay.
Same for simply watching matches.

**I use:**
Macbook Pro 2019
macOS Version 13.5.1 (22G90) (after upgrade)
AMD Radeon Pro 5300M 4 GB (GPU auto-switch disabled)
Intel UHD Graphics 630 1536 MB

Tried:
- Restart game/OS
- Upgrade OS to the latest
- Verify game files
- Completely re-install Dota
- Run with '-safe' flag
- Run with various resolutions/settings

Nothing helped. And so far haven't found similar issue in the internet.

### Example Match ID (and possibly Timestamp)

Appeared during match **7299225683**

### Screenshots

![Screenshot 2023-08-24 at 18 24 46](https://github.com/ValveSoftware/Dota2-Gameplay/assets/7886823/4dd09b79-f4ac-49b2-a277-21215c11aeac)

**Comment by LokeLok** [comment]
Go to your Armory>World>Map Effects>Right-Click on Item>Unequip Item.

**Comment by aTan-aka-Xellos** [comment]
Thanks. Very dumb item. Equipped while doing staff on background without reading what it is.
