### ISSUE TITLE
When receiving a set on Void Spirit from the jubilee treasury, there is no way to put it on

### ISSUE THREAD

**Issue by Ramsler** [ValveSoftware/Dota2-Gameplay#10931]
### Cosmetic Item Name

10th Anniversary: Haidden Vector

### Description

When receiving a set on Void Spirit from the jubilee treasury, there is no way to put it on. It's the same with Gabe's chat sounds, what could be the problem?

### Example Match ID

1

### Screenshots

![Void1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/143127496/a56e4085-30aa-4430-a489-5a40281d708a)
![Void2](https://github.com/ValveSoftware/Dota2-Gameplay/assets/143127496/af2c8b35-27e6-49ea-bd3e-e26fa033b68c)
![Void3](https://github.com/ValveSoftware/Dota2-Gameplay/assets/143127496/5e7ff973-2c0f-4184-928a-2c9e37c76743)

**Comment by LokeLok** [comment]
You need to go to Armory and unbundle the Cosmetic first.

**Comment by Ramsler** [comment]
> You need to go to Armory and unbundle the Cosmetic first.

I don't understand where to do it?

**Comment by LokeLok** [comment]
https://prnt.sc/mEyyGi1ZrgZ7 Click on the top right, that is your Armory. Should be one of the first Cosmetics under Recent Items tab.
