### ISSUE TITLE
can't wear a skin

### ISSUE THREAD

**Issue by RusIan-Tagiev1005** [ValveSoftware/Dota2-Gameplay#10938]
### Cosmetic Item Name

10th anniversary: Hidden Vector

### Description

I got a skin from the treasury, but I can't put it on, it's in the inventory, but not in the game itself.
Here is video and screenshot. https://www.youtube.com/watch?v=RmsMUMy28-s&ab_channel=ya3000

### Example Match ID

6576575657

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/58120498/2a36c991-9ae2-4158-910e-dc92dbfa6999)

**Comment by LokeLok** [comment]
You need to go to Armory and unbundle the Cosmetic first.
