### ISSUE TITLE
Dark Willow Shadow Realm damage goes through BKB

### ISSUE THREAD

**Issue by Sh3ogorath** [ValveSoftware/Dota2-Gameplay#10944]
### Ability name

Shadow Realm

### Description

I played a match against Dark Willow recently. The issue I have is with the fact that her Shadow Realm is not supposed to pierce spell immunity, yet there i was with bkb and she had agh's and her shadow realm damage went straight through my BKB. In addition, I'd like to just comment that making her a Universal Hero was a terrible decision, since she completely satisfies the requirements of being an Intelligence hero. Not only was that change completely unnecessary and uncalled for, but it's outright senseless and unbalanced. What's more, that Agh's upgrade of hers needs a nerf, or a rework, as does Shadow Realm, because her ability to completely replace carry-level damage by just having agh's and be completely untargetable, which still doesn't make aoe spells as relevant as it may seem since aoe can be mitigated with good positioning and strategy, is absurd. Nerf her!

### Example Match ID (and possibly Timestamp)

7301341797 - 24/8/2023 18:57

**Comment by LokeLok** [comment]
Intended.

> Avatar Reworked: applies a basic dispel. Provides Debuff Immunity for the duration: any negative effect on the user won't affect them, Magic Resistance increased by 50% and they're immune to pure and reflected damage. These only affect spells that don't pierce Debuff Immunity

Taken from 7.33 patch notes. BKB only grants 50% resistance instead of having spell immunity and that is the reason why Shadow Realm did damage. For your other complaints, this is not a place to ask about balance changes. This place is for bugs and there is no bug here, you can close this issue.
