### ISSUE TITLE
Unable to set 10th Anniversary Staff of Gun-Yu as alternate immortal effect for weapon effect cosmetic

### ISSUE THREAD

**Issue by ruinfx** [ValveSoftware/Dota2-Gameplay#10965]
### Cosmetic Item Name

10th Anniversary Staff of Gun-Yu

### Description

The 10th Anniversary Staff of Gun-Yu does not appear in the list of immortals that you can select for the cosmetic effect in the boundless strike skill.

### Example Match ID

123456789

**Comment by duckbotx** [comment]
So is Void Spirit's 10th Anniversary Hidden Vector Astral Step effect.
