### ISSUE TITLE
Wrong invite button animation.

### ISSUE THREAD

**Issue by aoisensi** [ValveSoftware/Dota2-Gameplay#11]
![Animation](https://user-images.githubusercontent.com/1350990/171679922-780fea13-f476-45e6-a17e-bb37c04f9007.gif)
Old Dota 2 was animated correctly.

**Comment by NMOTH** [comment]
this is not a bug, it has to do with your in-game graphical settings.

**Comment by aoisensi** [comment]
Confirmed it's fixed.
