### ISSUE TITLE
Some 10th Anniversary items are incorrectly configured

### ISSUE THREAD

**Issue by TheCyberTronn** [ValveSoftware/Dota2-Gameplay#11001]
### Cosmetic Item Name

10th Anniversary Immortals

### Description

1. The Void Spirit 10th Anniversary Hidden Vector set does not appear as a "Full Set" when clicking on the "FULL SETS" button in the Hero "LOADOUT" tab.
2. The Mirana 10th Anniversary Dark Moon set does not appear as a "Full Set" when clicking on the "FULL SETS" button in the Hero "LOADOUT" tab.
3. The Ursa 10th Anniversary (Lucky) Alpine Stalker set does not appear as a "Full Set" when clicking on the "FULL SETS" button in the Hero "LOADOUT" tab.
4. None of the Ability Effects can be equipped when other cosmetic items are in that slot. This includes the 10th Anniversary Totem of Deep Magma, 10th Anniversary Staff of Gun-Yu, and 10th Anniversary Hidden Vector - Blade.

While searching for this before reporting this myself, please note that many users have previously reported bugs, confused that these new sets did not originally appear in the "Full Sets" tab, and they didn't understand how to equip them.

Strangely, the 10th Anniversary Bindings of Deep Magma set DOES appear correctly in the Hero Loadout tab.
Also note that equipping Ability Effects from older items while 10th Anniversary items are equipped correctly displays their intended Ability Effect.

Also also, while you're in the region of Full Sets, it'd be cool if a player has additional styles all unlocked for them to display in the Full Sets tab. Would make UI navigation just that little bit easier.

### Example Match ID

Dashboard

**Comment by shaileshgarg** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/259, issue related to multiple sets not avaible as sets to select. Maybe add these also as a comment.

**Comment by vivi-lili** [comment]
Fix in next patch
