### ISSUE TITLE
Endgame screen cosmetic visual bug affecting immortal effects.

### ISSUE THREAD

**Issue by zoonzoon2** [ValveSoftware/Dota2-Gameplay#11011]
### Cosmetic Item Name

Possibly affects every immortal item

### Description

Changing the effects of a hero's spell in the loadout to an immortal one shows the hero having the immortal equipped during the endgame screen. In the example I'm posting, Omniknight is using the Helm of the Thunderwrath's Calling with Repel's effects changed to Paragon's Rebuke (immortal). During the endgame screen, Omniknight is seen wearing the Paragon's Rebuke item.
![20230830121231_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/115463071/093fcd7a-7d54-4edf-b12f-f6eaaada6f05)
![20230830121219_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/115463071/303831bb-fbb9-495a-9954-4e60404e07d5)

### Example Match ID

7310524099

**Comment by vivi-lili** [comment]
This will be fixed in next patch.
