### ISSUE TITLE
Troll Warlord's Scepter Whirling Axes (Ranged) doesn't dispel debuff immunity targets.

### ISSUE THREAD

**Issue by matr9xnb** [ValveSoftware/Dota2-Gameplay#11015]
### Ability name

Troll Warlord's Scepter Whirling Axes (Ranged)

### Description

Troll Warlord's Scepter Whirling Axes (Ranged) doesn't dispel debuff immunity targets even level 25 right talent learned.

### Example Match ID (and possibly Timestamp)

Demo hero.

**Comment by Avarise831** [comment]
#10632
