### ISSUE TITLE
Warlock model small

### ISSUE THREAD

**Issue by JACM8544** [ValveSoftware/Dota2-Gameplay#11028]
### Cosmetic Item Name

Warlock Default

### Description

Warlock loads on post game like he loads on the armory, but Golem isn't visible, so he just looks silly

### Example Match ID

7311662359

### Screenshots

![image_2023-08-30_170423290](https://github.com/ValveSoftware/Dota2-Gameplay/assets/38405235/0c926d99-25e0-41e3-bfff-a781edadc2be)

**Comment by JACM8544** [comment]
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/38405235/c0a26fc4-ab1d-4f60-b34d-698b9c206896)
I think its not just me

**Comment by vivi-lili** [comment]
Fixed next patch
