### ISSUE TITLE
Game visuals broke after the update! HELP

### ISSUE THREAD

**Issue by shaxx2** [ValveSoftware/Dota2-Gameplay#11051]
### Description

i tried to apply different terrains to the game but same issue. 
game is fine if i demo a hero but spectate and play is the same as the screenshot

### Screenshots

![DOTA LAYOUT](https://github.com/ValveSoftware/Dota2-Gameplay/assets/143668942/5b41ea4f-2dc8-4864-bfc5-3d94e48349b1)

**Comment by prividenyaaaa** [comment]
I have the same problem, I attached screenshots below. Checked the integrity of the files, did not help
![20230831024842_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/143669403/f7a6684d-95ee-4dab-93e3-cf6d787273b4)

**Comment by prividenyaaaa** [comment]
I have the same problem, I attached screenshots below. Checked the integrity of the files, did not help
![Uploading 20230831033457_1.jpg…]()

**Comment by prividenyaaaa** [comment]
I have the same problem, I attached screenshots below. Checked the integrity of the files, did not help
![20230831033542_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/143669403/fdac809c-146b-499a-8c4e-a574d3d91469)

**Comment by shaxx2** [comment]
i reinstalled dota and it did not help either.
i do believe its related to directx 11. im updating my windows and will see how it goes.

**Comment by yunielleal** [comment]
Same here!!!
also on the minimap the icons of the heroes blink

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/888549/ce45297a-b7b0-485d-bfb1-f95712168cbe)

**Comment by juwe99** [comment]
same. i am using windows 8 right now.

**Comment by Chill-Babak** [comment]
same issue :(((((((((( , tried several terrain and still have this bug !
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/143709925/4f99d385-85c6-4761-8036-76e63efe4dd6)

**Comment by aecchamp** [comment]
Is it possible that now dota2 is looking for GPU only to load full terrain.
I am using Integrated Graphics as my GPU is not working properly for playing dota2.

**Comment by yunielleal** [comment]
> Is it possible that now dota2 is looking for GPU only to load full terrain. I am using Integrated Graphics as my GPU is not working properly for playing dota2.

I'm using Integrated Graphics too, this may be the problem.
Could Valve fix this??, or need to delete Dota2, can't have Graphic Card right now . 😥

**Comment by aecchamp** [comment]
They said they've fixed this in an update last night.

If still not working, someone suggested the below (will try this tonight myself if the update didn't fix it):

- right click on dota 2

- go to properties

- put -dxlevel 80 in launch options

**Comment by norbi201097** [comment]
> 

With launch options, working for me, thanks

**Comment by yunielleal** [comment]
> * put -dxlevel 80 in launch options

Work for me!!! thanks

**Comment by ramazyant** [comment]
-dxlevel 80 does not work with vulcan renderer, so the bug still exists...

**Comment by yunielleal** [comment]
✅Fixed in last update!!!

Thanks Valve

**Comment by ramazyant** [comment]
I really got fixed! ty guys
