### ISSUE TITLE
Game freezes when making in game purchase

### ISSUE THREAD

**Issue by legcan** [ValveSoftware/Dota2-Gameplay#11058]
### Description

Trying to purchase the treasure for the Collectors cache and every time I hit "Purchase Treasure" , I can see the steam overlay trying to load but then the game freezes.

I'm on a 2020 macbook air m1, macOs 13.1

### Screenshots

![Screenshot 2023-08-30 at 21 56 44](https://github.com/ValveSoftware/Dota2-Gameplay/assets/86305316/90308b49-98ce-4f9a-a723-4433bb4d2238)

**Comment by pbinh** [comment]
Me too I use MBP M2 chip encountered the same issue, it's freaky annoying

**Comment by legcan** [comment]
Not sure if related but I got a small update and this issue seems to be fixed now.
