### ISSUE TITLE
Dawnbreaker - Starlorn Adjudicator set is missing from armory after receiving Astral Herald one (both are from collector's caches)

### ISSUE THREAD

**Issue by zatroch** [ValveSoftware/Dota2-Gameplay#11070]
### Cosmetic Item Name

Starlorn Adjudicator

### Description

Starlorn Adjudicator set is missing from armory after receiving Astral Herald one (both are from collector's caches)

### Example Match ID

Armory View

**Comment by robinh-valve** [comment]
Will be fixed in the next release
