### ISSUE TITLE
Monkey King bundle is in the wrong section

### ISSUE THREAD

**Issue by LokeLok** [ValveSoftware/Dota2-Gameplay#11084]
### Description

The Monkey King bundle is in the Tool section instead of the Premium section.

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/106764092/e438d78b-e6b4-4997-b7c2-0ed593caa66d)

**Comment by robinh-valve** [comment]
Will be fixed in the next release
