### ISSUE TITLE
My console disappear 

### ISSUE THREAD

**Issue by gowthamang56** [ValveSoftware/Dota2-Gameplay#11082]
### Description

I trying to drag my console windows in dota surrender it vanished , after i press console button my mouse pointer, change into small, that I can see, i can't see my console, i need to reinstall dota or any solution?

**Comment by XkTheMaster** [comment]
Go into your "Steam\steamapps\common\dota 2 beta\game\dota\cfg" find file "machine_convars.vcfg" right click it and open it with Notepad after that find "panorama_console_position_and_size" and change whatever values are there with these "20.00|20.00|1000.00|800.00"

**Comment by Joyfulbeekeeper** [comment]
> Go into your "Steam\steamapps\common\dota 2 beta\game\dota\cfg" find file "machine_convars.vcfg" right click it and open it with Notepad after that find "panorama_console_position_and_size" and change whatever values are there with these "20.00|20.00|1000.00|800.00"

Valve still haven't resolve the issue themselves. I found your solution and it helped me.
I had inf|inf instead of 20.00|20.00
