### ISSUE TITLE
Missing Killstreak Effects after The Summer Client update

### ISSUE THREAD

**Issue by CloudWolf23** [ValveSoftware/Dota2-Gameplay#11086]
### Description

I bought my Fire Kill Streak Effect on 05/25/2023 for 150k Shards.. after this Summer Client update. It was locked again?

Any solutions on how to fix this?

Dota ID # 156867553

### Example Match ID (and possibly Timestamp)

N/A

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/143691572/c1884393-dfa4-4243-a62b-d09086798b26)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/143691572/a98e02a3-cfa7-46ce-bb50-11e13e48c30c)

**Comment by running88** [comment]
me too, 
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/7047149/9e356ed1-4bc8-4e63-b554-d63f12c3b721)
my Dota ID # 244882613

**Comment by robinh-valve** [comment]
Please look it up in the Armory/Interface. Do you have it unlocked there? We will fix it in the shard shop, so that it says owned.

**Comment by robinh-valve** [comment]
Anyway, will be fixed in the next release.

**Comment by CloudWolf23** [comment]
Thanks it is now fixed!

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/143691572/12c115b7-116b-41d3-b763-8e1e1e50e2c2)
