### ISSUE TITLE
Monkey King set shars shop Bug

### ISSUE THREAD

**Issue by Unluck666** [ValveSoftware/Dota2-Gameplay#11102]
### Cosmetic Item Name

Mask of Mischief

### Description

Set is in the tools contribution

### Example Match ID

none

### Screenshots

(https://github.com/ValveSoftware/Dota2-Gameplay/assets/143705158/4c4c4bf5-4eb5-4d77-b14d-3c26e1529891)

**Comment by robinh-valve** [comment]
fixed in the next build
