### ISSUE TITLE
Item Icon sporadically missing when dragging in inventory.

### ISSUE THREAD

**Issue by nijbuu** [ValveSoftware/Dota2-Gameplay#11106]
### Description

Have had an instance where items remain highlighted (how they look while being dragged) after drag has finished.

https://github.com/ValveSoftware/Dota2-Gameplay/assets/9077011/18dc3390-3138-48f4-ba6f-b427bdfb12c5

**Comment by grja99** [comment]
If it helps, this happens with dragging a Guild contract into your active contracts too.

**Comment by fjre** [comment]
Same issue happens in CS:GO2 beta when trying to move weapons in the inventory tab. Sometimes weapons vanish upon dragging.

**Comment by DuMuT6p** [comment]
We can close the issue.
Its been fixed on September 8 patch - https://dota2.fandom.com/wiki/September_08,_2023_Patch

"Fixed a bug where inventory item icons would sometimes disappear when dragging them"
