### ISSUE TITLE
[UI|Minimap]Use ALT to show hero "Icons" flicker on minimap 

### ISSUE THREAD

**Issue by Aphotic** [ValveSoftware/Dota2-Gameplay#11114]
### Description

Use ALT to show hero "Icons"

having this combination of options/icon sizes selected makes minimap icons flicker

Holding ALT ingame will make hero icons flicker on the minimap 
Also **_Lone Druit spirit bear_** shows the "Text name" instead of "Icon"

> Edit:
 _"The flickering stems from using the option to dynamically scale the minimap icons."_

### Example Match ID (and possibly Timestamp)

7312150837

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/30921064/540b6965-1c75-40b8-bc5b-77ed4ee1fb90)

**Comment by hai-ben** [comment]
Still getting this after the Sep 1 patch.

https://imgur.io/a/gNi1qfP

**Comment by shaileshgarg** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/11031
