### ISSUE TITLE
Graphics unplayable

### ISSUE THREAD

**Issue by forrestchump1** [ValveSoftware/Dota2-Gameplay#11136]
Device : Macbook Pro Mid 15" 2015 (2.2 GHz Quad-Core Intel Core i7, 16 GB RAM
)
Please refer the screenshots.
How are we supposed to collect the free chests like this? 

Note : This issue does not occur in Bot matches.
<img width="1440" alt="Screenshot 2023-08-31 at 4 18 41 PM" src="https://github.com/ValveSoftware/Dota2-Gameplay/assets/143719314/cd22ffdb-3633-404c-b675-693091ced9c3">
<img width="1440" alt="Screenshot 2023-08-31 at 6 11 09 PM" src="https://github.com/ValveSoftware/Dota2-Gameplay/assets/143719314/4d61d475-6009-4e4b-9dbb-02928b4c3b47">
<img width="1440" alt="Screenshot 2023-08-31 at 5 53 46 PM" src="https://github.com/ValveSoftware/Dota2-Gameplay/assets/143719314/4a7845b4-e258-4719-86da-cb1087cffd19">

**Comment by yng0dzz** [comment]
HAHAHAH WTFF

**Comment by trying2** [comment]
Same issue

**Comment by SevenofNine709** [comment]
Same issue, so frustrating

**Comment by Riyanp** [comment]
my friend got the same problem too, currently got abandoned because of this issue

it seems like it only occur on macOS

**Comment by forrestchump1** [comment]
> Same issue



> my friend got the same problem too, currently got abandoned because of this issue
> 
> it seems like it only occur on macOS

Sure seems like it. Such a waste of the chest event. Even wasted 2 holidays cus of this.

**Comment by 4erepaxen** [comment]
try thath https://github.com/ValveSoftware/Dota2-Gameplay/issues/11361#issuecomment-1703915017

**Comment by forrestchump1** [comment]
> try thath [#11361 (comment)](https://github.com/ValveSoftware/Dota2-Gameplay/issues/11361#issuecomment-1703915017)

"-dxlevel 100" in "launch options" fixed my problems . Thanks a lot!

**Comment by VladYY** [comment]
I'm on windows 7, not a macdonald or whatever hegemon, abusing garbage y'all are talking about. 
But I have the same issue, -dxlevel 100 "fixes" it but shadows start bugging out AND,
if you play with/against the Ogre Immortal Gemlick Decanter item cosmetic, frames drop to a maximum of 10, totally unplayable...
People then say you gotta remove the -dxlevel 100 to fix the ogre cosmetic problem, total loop...   
Not to mention that frames are only 120 when alone on screen but when action happens they drop to like 50-ish, sometimes 30
