### ISSUE TITLE
Custom announcers auto unequip once in game

### ISSUE THREAD

**Issue by isdra113** [ValveSoftware/Dota2-Gameplay#11137]
Announcer equiped before the game
![20230831143733_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/46230436/6d08d5e3-065a-49bf-bdd7-5846ca906438)
Once in game it unequip and play the default announcer instead
![20230831143759_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/46230436/e5a0a4cf-5c2a-47c6-993f-db8da63299ba)

**Comment by Animosity** [comment]
This issue is 100% reproducible
