### ISSUE TITLE
Vrad 3 lightmapper missing files

### ISSUE THREAD

**Issue by gabengaGamer** [ValveSoftware/Dota2-Gameplay#11148]
* System information from steam (Steam -> Help -> System Information) in a [gist](https://gist.github.com/):
https://gist.github.com/gabengaGamer/9df1d0a334dfa814c2e60a3b249b13c7
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

Hammer 2 cannot be launched due to missing .dll files for the Vrad3 lightmapper
![dota2_clvPCePAR1](https://github.com/ValveSoftware/Dota-2/assets/54669564/60e17da0-348b-45be-9523-304e16d51559)

#### Steps for reproducing this issue:

1. Start dota 2 workshop tools
2. Select addon
3. Start Hammer 2
4. See Vrad3 error 

Also minidump: 
[dota2_2023_0831_162041_0_error.zip](https://github.com/ValveSoftware/Dota2-Gameplay/files/12487072/dota2_2023_0831_162041_0_error.zip)

**Comment by gabengaGamer** [comment]
But that's an engine issue, not a gameplay issue. @kisak-valve I think you moved it here by mistake

**Comment by kisak-valve** [comment]
Hello @gabengaGamer, the Dota-2 issue tracker is limited to issues with the Mac and Linux client of Dota-2, which puts your feedback here out of scope for that issue tracker.

This issue tracker is used by the larger Dota 2 team and is a closer match since it involves the Windows only workshop tools.

**Comment by gabengaGamer** [comment]
understood, thanks for the answer 🙂

**Comment by gabengaGamer** [comment]
fixed, thanks!
