### ISSUE TITLE
Low Graphics issue in Dota 2 After 28 August Update 

### ISSUE THREAD

**Issue by Yousafbhutta86** [ValveSoftware/Dota2-Gameplay#11175]
### Description

Whenever I attempt to connect to an online match or watch a previously played match, I encounter issues. The pc screen becomes black on the all side, it shows in the image and low graphics is showing there. When I was off my internet, then tried a demo hero. All graphics are working fine there. Kindly fix this bug.

Using Window 11 on Hp Victus 12 gentration.... Featuring a powerful Nvidia graphics card... 

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/143741349/3ce09b2e-cac0-4890-992b-1d2803a65356)

**Comment by Imperator-Nero** [comment]
You have unlocked and applied a world effect cosmetic. You can fix it by entering your armoury and un-equiping the world effect.

**Comment by Yousafbhutta86** [comment]
Where I will find these things. Kindly help me in a details plz

**Comment by Imperator-Nero** [comment]
Top right of your main menu there should be a button to access the armoury. From there navigate to the World section at the top then select the Map Effects section the left there you will see the 10th anniversary shader effect 2023. Right click the item and unequip it.

**Comment by forrestchump1** [comment]
> Thanks a lot the problem is solved... Lot of thanks man..

Close the thread then?

**Comment by Yousafbhutta86** [comment]
Okay Closed now
