### ISSUE TITLE
Critical image error. MacOS 

### ISSUE THREAD

**Issue by 4erepaxen** [ValveSoftware/Dota2-Gameplay#11172]
### Description

Start Allpick

### Example Match ID (and possibly Timestamp)

7312807773

### Screenshots

![Снимок экрана 2023-08-31 в 19 58 52](https://github.com/ValveSoftware/Dota2-Gameplay/assets/112718720/34563297-8ab2-4e7b-a8f7-c39cac2b6577)
![Снимок экрана 2023-08-31 в 19 59 02](https://github.com/ValveSoftware/Dota2-Gameplay/assets/112718720/b9e50f7c-d8a4-4268-8f41-f7fa7ccf92a5)
![Снимок экрана 2023-08-31 в 19 59 12](https://github.com/ValveSoftware/Dota2-Gameplay/assets/112718720/626ad3f5-8c63-4041-a0fc-4b602ad7b48e)

**Comment by Hotdog541** [comment]
same issue. 
<img width="1280" alt="Screen Shot 2023-08-30 at 5 06 22 PM" src="https://github.com/ValveSoftware/Dota2-Gameplay/assets/143739712/84df3a0d-e0ff-4c4e-a380-a540debb1280">

**Comment by 4erepaxen** [comment]
#11171

**Comment by Golf129** [comment]
Same issue in #11136

**Comment by Vodi4kaa** [comment]
The same problem how to fix?

**Comment by 4erepaxen** [comment]
@Vodi4kaa Waiting for fix by valve

**Comment by Vodi4kaa** [comment]
How long maybe are u know ?)))

**Comment by 4erepaxen** [comment]
Last time was 2-3 weeks

**Comment by Chill-Babak** [comment]
They said they've fixed this in an update last night.

If still not working, someone suggested the below (will try this tonight myself if the update didn't fix it):

right click on dota 2

go to properties

put -dxlevel 80 in launch options

**Comment by pbli** [comment]
-dxlevel 100, instead of 80 works for me.

**Comment by Hotdog541** [comment]
on a Macbook?  @Chill-Babak @pbli if yes. could you walk me through it. am computer dummy. I feel like yall on PC sayin terms like properties. but i dont know

**Comment by 4erepaxen** [comment]
Go to valve-macOs github
