### ISSUE TITLE
terrain not showing properly since the new patch

### ISSUE THREAD

**Issue by BienDev** [ValveSoftware/Dota2-Gameplay#11199]
### Description

I'm the only one affected in the match, here is my pc spec

GPU: AMD RX 6600
CPU: AMD Ryzen 5600x

### Screenshots

![2023-08-31 21_51_36-Dota 2](https://github.com/ValveSoftware/Dota2-Gameplay/assets/51485586/48c1bf52-0538-4f14-ac55-12bece0049be)
![2023-08-31 22_46_19-Dota 2](https://github.com/ValveSoftware/Dota2-Gameplay/assets/51485586/21096b85-029b-4329-abb4-32a341b89703)

**Comment by shadowblade227** [comment]
Not everyone with an AMD video card experiences this problem, but everyone who does has an AMD video card.

**Comment by arfn1366** [comment]
I have this problem too, My graphic card is Geforce GT 610

**Comment by jeffhill** [comment]
Could you share which rendering API you're using (DX or Vulkan), and what your graphics settings are?

**Comment by Darsha-1** [comment]
> Not everyone with an AMD video card experiences this problem, but everyone who does has an AMD video card.

I have been using intel instead of nvidia. i have this issue too

**Comment by arfn1366** [comment]
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/48623848/b124a954-b49a-4a14-ad68-93ca9fd0b659)

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/48623848/4f5d5d32-0d9d-4d4c-80b4-075938d9c5b5)

**Comment by jeffhill** [comment]
This isn't a fix, but debugging info - does going into "Use Advanced Settings" and changing the game screen render quality change anything for you?

**Comment by shadowblade227** [comment]
> This isn't a fix, but debugging info - does going into "Use Advanced Settings" and changing the game screen render quality change anything for you?

For me it does nothing, same result. 
With GTX 1060 i have no problems, RX 6700XT looks like this.
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/68826076/b214f833-3205-485b-9948-59e91961a931)

With lowest settings I have also "trails" of the objects
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/68826076/3262beb0-0d95-4aff-814a-36eaed37abe4)

**Comment by jeffhill** [comment]
Could you try with setting "r_dota_render_ground_last 0" in the console?

**Comment by jeffhill** [comment]
A possible fix for this is shipping in this evening's update - if you're still seeing the issue once that's shipped, trying with "r_dota_render_ground_last 0" will rule in/out a number of possible suspects for the problem. Thank you all so much for the help tracking this down!

**Comment by Darsha-1** [comment]
guys . FOUND A SOULUTION .   right click on dota 2, go to properties. put -dxlevel 80 in launch options . Works fine for me after a day of trouble.

**Comment by BienDev** [comment]
> guys . FOUND A SOULUTION . right click on dota 2, go to properties. put -dxlevel 80 in launch options . Works fine for me after a day of trouble.

Thank you so much Darsha-1 it worked for me also

**Comment by rcampos99** [comment]
please tutorial plz

**Comment by CnrDmr** [comment]
Does this solution work for the MacBook render problem?

**Comment by iMusss** [comment]
Worked like a charm, playing off a MacBook Pro 2016 model even improved all my setting running smoother than ever

**Comment by VladYY** [comment]
Wait till y'all encounter a game with the Ogre Immortal Gemlick Decanter PepeLaugh
