### ISSUE TITLE
Flag bearer creep

### ISSUE THREAD

**Issue by regalado24** [ValveSoftware/Dota2-Gameplay#11192]
### Description

Flagbearer creep doesn't show on enemy.

**Comment by rairulyle** [comment]
Up

**Comment by Digestivee** [comment]
Same

**Comment by segastep** [comment]
same, at some point starts to show

**Comment by venus12345678** [comment]
tried changing skins to fix, didn't work, upvote this

**Comment by frostseeker2640** [comment]
same issue please fix it

**Comment by animeisreal** [comment]
Same issue, have tried changing from vulcan to directX11 but does not fix issue. Will continue to tinker to find solutions.

**Comment by animeisreal** [comment]
This issue occurred in the most recent DPC match with LUNA and QUEST. Quest No!ob was unable to see banner creep.

**Comment by shaileshgarg** [comment]
This was fixed.
