### ISSUE TITLE
New behavior system

### ISSUE THREAD

**Issue by zlooun** [ValveSoftware/Dota2-Gameplay#11235]
### Description

Hello,
My dota 2 profile id:155697161.
Id of the last match after which my behavior was renewed: 7313402682.

I have a problem after behavior system update.

I won 11 out of 15 games. Not ruined, not toxic. I didn't even have the possibility of voice communication because it's only from 8k. There is not much time to write to the chat when you play the game. And judging by the report. I somehow got 27 reports in 5 games. And I was stripped of almost 2.5 behavior. It's impossible.

Now I have 5200 behavior, and I can't even write to the chat. Another 10 wins out of 15 and I won't be able to play in the ranking. I'm afraid to imagine what will happen if I catch a lose streak, I'll probably be banned in steam after 1,000,000 reports in one game. I spent so much money on this game. I got 1000 lvl in last battle pass. Today I wanted to buy new treasures, to got anti mage person. But if I don't have the opportunity to play the game, why do I need them?

Give me back my behavior, please and fix that.

By the way, I don't understand at all what is the point in a team game to forcibly prohibit players from communicating when everyone has a personal mute button. If someone doesn't like how someone communicates, he is able to mute him. And if the players want to win, but because of your ban they can't communicate. Then what's the point of playing it at all?

### Example Match ID (and possibly Timestamp)

7313402682

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/50909481/7c4a72c9-5057-4ea0-99f9-d461c662fbf0)

**Comment by ValveHatesDotA** [comment]
>By the way, I don't understand at all what is the point in a team game to forcibly prohibit players from communicating when everyone has a personal mute button. If someone doesn't like how someone communicates, he is able to mute him. And if the players want to win, but because of your ban they can't communicate. Then what's the point of playing it at all?


Valve believes it's a fair game even if only one team is able to communicate
