### ISSUE TITLE
Invoker ability effects menu

### ISSUE THREAD

**Issue by g0dm0d** [ValveSoftware/Dota2-Gameplay#11258]
### Description

In the new menu, invoker shows non-existent effects

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/45468452/24255606-8af3-4107-8f97-e73d19c3011f)

**Comment by shaileshgarg** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/11162

**Comment by vivi-lili** [comment]
Fix in next patch
