### ISSUE TITLE
List of game modes is not fully displayed.

### ISSUE THREAD

**Issue by Lemax1995** [ValveSoftware/Dota2-Gameplay#11276]
### Cosmetic Item Name

Game mode menu

### Description

In the main game menu, the list of available game modes is not fully displayed (I highlighted the problem with red arrows).

### Example Match ID

Not relevant

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/8769337/264192ed-f8bc-487f-bc3b-b60ad2975055)

**Comment by SoftPancakes42** [comment]
I have the same issue - it further affects bot options etc. You cannot access all the game modes and ways to play which is fine if you're just all pick and ranked but...I can't do anything else with friends or try other modes.

**Comment by commentator24** [comment]
a bit annoying but still can pick mode with console commands.
e.g. for single draft open console and type "dota_match_game_modes 16" #7006

**Comment by OTPb1B** [comment]
I have this problem too...
