### ISSUE TITLE
HELP ! VISUAL BUG AFTER UPDATE 

### ISSUE THREAD

**Issue by veeowvee23** [ValveSoftware/Dota2-Gameplay#11280]
### Description

Hello Valve/Steam,

Please help on the below error encountered after the game update. I can't play since the whole video is messed up and pixelated.

In the main window there's already a visual glitchy feel but when you are in game in gets worse.

Hope you can help.

Thanks!

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/128350982/7f5d308c-5ed1-4f22-8179-a53295a9dfde)

**Comment by segastep** [comment]
This is not a bug you have equipped a terrain item, from the anniversary cache. Simply  unequip the item from armory.
