### ISSUE TITLE
issue with the video graphs of game since age last summer client update august 31st 

### ISSUE THREAD

**Issue by andrewd19** [ValveSoftware/Dota2-Gameplay#11316]
### Description

since the last update of 31 august summer client 2023 update i have noticed and i can't play any online games or spectate one , because the screen just goes different color on antiheroes u select and u cannot see anything on the screen but different colors shining on it , its an issue which never happened i thought it must be a issue for my MacBook , but i got it fully tested through the help of apple technicians , but as per them the mac is in a top condition and there is nothing wrong with it , and when i play other games like csgo it is running smoothly , also when i play bot matches it works completely normal , so please look after this i am really looking forward to watch ti internationals 2023 matches also i wanna play games i really hope u all can help me with this issue thank u

please find the issue regarding screen shots bellow and if u can help me in anyways please let me know i will be great full , here is my contact number +966554987656 
and email id - andrewdomingo@ymail.com 
please call or email me about the concern 
regards
ANDREW 

![20230902052231_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/143856764/c366925e-229a-412c-9f31-05177629fcaa)
![20230902052235_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/143856764/0a79e169-3140-43e2-a025-86b5342788f1)
![20230902052240_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/143856764/b9205c87-7b9f-48f2-ab2b-a6d800980859)

![20230902052200_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/143856764/2ec77b5d-f0b7-46d2-939f-2dd59f84d625)
![20230902052203_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/143856764/d80ac4ca-d822-45d1-8c44-0e59df281e35)
![20230902052206_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/143856764/e9cea805-ddf3-494f-8af9-2cda63839875)
![20230902052218_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/143856764/ad36a57a-4c76-4c21-8389-6d96737cbb25)
![20230902052223_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/143856764/a47fd662-95ff-4303-9bb4-d6cfcb0f77dd)

### Example Match ID (and possibly Timestamp)

340152223 - 05:34

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/143856764/f7db0a43-1150-4480-8423-60da6a026325)![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/143856764/9de4ea44-d852-410a-99eb-723de03eff3b)![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/143856764/1a9357cc-057b-4a86-952c-3fcb19bbaf74)![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/143856764/4798b8ab-296d-4d32-9c8e-aa697215c366)![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/143856764/7f89a855-92b0-4303-a238-f7011fd2f443)![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/143856764/9f6c4ea7-d5de-488f-8547-85e931cbc73e)![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/143856764/7eaddfaa-440a-4779-8167-c396c0af3aaa)

**Comment by plantaz** [comment]
Same problem here.
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/16445333/e876d1c1-780c-4406-b7c8-98d45561e373)

**Comment by pbli** [comment]
do not thank me. adding -dxlevel 100 will fix. guess the rending constructor uses a lower level for plotting.

**Comment by plantaz** [comment]
Worked for me! thnkz @pbli !

**Comment by andrewd19** [comment]
Worked for me as well thanks @pbli
