### ISSUE TITLE
No courier in Dire side to start with.

### ISSUE THREAD

**Issue by salehinRafi** [ValveSoftware/Dota2-Gameplay#11334]
### Description

In the turbo gameplay, no courier is available for my team (Dire). Even reconnecting didn't make it appear. everytime need to back to base to get an item which loses time and is not effective.

### Example Match ID (and possibly Timestamp)

7315076944 - Whole game

**Comment by robertusaryo** [comment]
and no gold per sec too

**Comment by EyeKon8** [comment]
Turbo, 
no courier dire side.
match ID 7320132534
![20230904214733_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/144089842/5b19a471-5c55-4a21-be09-040a60f482e6)

**Comment by shaileshgarg** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/11639

**Comment by Nathanael-Valve** [comment]
Fixed in next update.
