### ISSUE TITLE
Name of the custom sets doesn't show up in hero's tab if the set contains a taunt

### ISSUE THREAD

**Issue by ShizueKaryan** [ValveSoftware/Dota2-Gameplay#11330]
### Description

There is a feature that allows us to name a custom mix set for heroes. In the new hero's tab UI, name of the custom set intends to show up under the hero's level progress. However, the name only shows up if the custom set doesn't contains a taunt. If the custom set has a taunt, then the name always shows up as "Customized set".
I tried to equip the custom set with name in the loadout, however name of the set still doesn't show up.
It isn't a big problem because all items are still equipped, but I'm appreciate if it can be fixed because I like to name my custom mix set. 
Thanks. 

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/124510132/f474adf9-b557-4088-8587-75cea6b1c813)
I tried to equip the custom mix set with name in the loadout (this set contains a taunt).

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/124510132/c0b4180e-9c5c-40e1-8106-a9202b25f767)
But in the hero's main tab, name of the mix set still shows up as "Customized set". 

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/124510132/cb88f90d-6294-4f97-b598-447f079976d3)
Name of the custom mix set still show up in the hero's main tab if the set doesn't have a taunt.

**Comment by vivi-lili** [comment]
Fixed in next patch.
