### ISSUE TITLE
Turbo bug

### ISSUE THREAD

**Issue by TaDaShi131313** [ValveSoftware/Dota2-Gameplay#11339]
### Description

Timer 2:38

MK discount from the game since the game start everything is fine until mk reconnected back to game the game broken all couriers at dire side disappear all some have passive gold (3 players) and some not respawn time increase.

### Example Match ID (and possibly Timestamp)

7315166122

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/114374787/1c6d8bf0-1ba0-4175-8801-7ccd6a790068)

**Comment by balidani** [comment]
Another game where the same thing happened after storm disconnected during pick phase and came back during the game: https://www.dotabuff.com/matches/7322475920

No passive gold or courier.

**Comment by shaileshgarg** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/11639

**Comment by Nathanael-Valve** [comment]
Fixed in next update.
