### ISSUE TITLE
Chaos Knight crashes the game

### ISSUE THREAD

**Issue by zyunwei** [ValveSoftware/Dota2-Gameplay#11347]
### Ability name

Reality Rift

### Description

Chaos Knight with activated BKB and cast Reality Rift to a target with activated Lotus Orb cause game client crash.

### Example Match ID (and possibly Timestamp)

no need

**Comment by deanrih** [comment]
I can't really confirm wether or not this is caused by CK using BKB casting Reality Rift to a target with Lotus Orb, but my recent match have that exact combination, here's my Match ID `7315270234`

**Comment by zyunwei** [comment]
Yes it's client crash, not server crash.
you can reproduce the bug now at any where.

**Comment by ggspiritbreaker** [comment]
> Yes it's client crash, not server crash.

Is a server crush. Match after this crush is not scored and all players even spectators are droped.
Bug work like this, if CK while he is under BKB or buff that grants him bkb effect(repel, press of the attack with talent) use reality rift in lotus orb, counterspell or mirrorshild server crashes, also works if ck will use bkb instant after reality rift, also works with rubick/morph doesn't matter who is owner of rift or counter spell.

**Comment by nabilnbgh** [comment]
here's my match id 7315169120 around minutes 30 all disconnect and crash

**Comment by deanrih** [comment]
> > Yes it's client crash, not server crash.
> 
> Is a server crush. Match after this crush is not scored and all players even spectators are droped.
> Bug work like this, if CK while he is under BKB or buff that grants him bkb effect(repel, press of the attack with talent) use reality rift in lotus orb, counterspell or mirrorshild server crashes, also works if ck will use bkb instant after reality rift, doesn't matter who is owner of rift or counter spell that means that works with rubick/morph.

It's not, if it is, you won't be able to reconnect

**Comment by ggspiritbreaker** [comment]
It's not, if it is, you won't be able to reconnect

> > > Yes it's client crash, not server crash.
> > 
> > 
> > Is a server crush. Match after this crush is not scored and all players even spectators are droped.
> > Bug work like this, if CK while he is under BKB or buff that grants him bkb effect(repel, press of the attack with talent) use reality rift in lotus orb, counterspell or mirrorshild server crashes, also works if ck will use bkb instant after reality rift, doesn't matter who is owner of rift or counter spell that means that works with rubick/morph.
> 
> It's not, if it is, you won't be able to reconnect

Client crash could cause the game to not be scored?

**Comment by deanrih** [comment]
> It's not, if it is, you won't be able to reconnect
> 
> > > > Yes it's client crash, not server crash.
> > > 
> > > 
> > > Is a server crush. Match after this crush is not scored and all players even spectators are droped.
> > > Bug work like this, if CK while he is under BKB or buff that grants him bkb effect(repel, press of the attack with talent) use reality rift in lotus orb, counterspell or mirrorshild server crashes, also works if ck will use bkb instant after reality rift, doesn't matter who is owner of rift or counter spell that means that works with rubick/morph.
> > 
> > 
> > It's not, if it is, you won't be able to reconnect
> 
> Client crash could cause the game to not be scored?

I think it's a system the server have, if multiple players disconnected at the same time from each team, it will mark the game as safe to leave and flag it with "Poor connection detected", unlike other actual server crashes where it is just safe to leave and you can't re connect at all (stuck at loading transition and then back to dashboard).

Also if this is Server crash, we only need one crash, not multiple since we all reconnect again (for some reason)

**Comment by ggspiritbreaker** [comment]
topic fixed
