### ISSUE TITLE
Hero Stats (Wins & Lossess) Incorrect or Not updated

### ISSUE THREAD

**Issue by n01root** [ValveSoftware/Dota2-Gameplay#11354]
### Description

I played a match yesterday as Wraith King before I started the match I had 33 Wins & 36 Losses. After the game ended and I won the match my stats were not updated they remained the same (33 Ws & 36 Ls) I'm positive that the game counted as no one had abandoned or failed to reconnect in time and the match was a Normal unranked dota 2 match. In addition when I looked at my wk arcana I could see that it said 65 unique hero kills where as when I look at the hero loadout it says 63 unique hero kills.

### Example Match ID (and possibly Timestamp)

7314841994

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/69567854/9ab9567d-3517-4df4-9827-2e40709a6a36)

**Comment by n01root** [comment]
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/69567854/25319508-9db0-42db-9443-e5a7fc48475d)

**Comment by vivi-lili** [comment]
Fix for refreshing stats page after a match will be in next patch.

As for the WK arcana progress.  You must harvest the bones before the count will go up.  Click on the progress and find the heroes to harvest.
