### ISSUE TITLE
Missing courier

### ISSUE THREAD

**Issue by MrMisticksPlay** [ValveSoftware/Dota2-Gameplay#11387]
### Description

Hello, I've been playing dota and I've run into a problem. My courier has disappeared. When I wanted to bring an item for myself, I was lit up with a sign "no courier". Below is a screenshot. As soon as I ran into an error, I turned on screen recording. game recording is present

### Example Match ID (and possibly Timestamp)

7316110969 - ~11

### Screenshots

![Снимок экрана 2023-09-02 195755](https://github.com/ValveSoftware/Dota2-Gameplay/assets/92387038/4b2f41bc-9326-4bd6-94c9-d4bd76267c04)

**Comment by Nathanael-Valve** [comment]
Fixed in next update.
