### ISSUE TITLE
Еhe ethereal blade has incorrect damage when it is used by ogre magi

### ISSUE THREAD

**Issue by Nimyakish** [ValveSoftware/Dota2-Gameplay#11415]
![570_20230903002014_1](https://github.com/ValveSoftware/Dota-2/assets/143908549/b524f0b2-f4eb-4780-a92b-26a77374ba68)

**Comment by LokeLok** [comment]
The damage is based on the primary attributes of the enemy you're casting it on, not your own. You can close this.
