### ISSUE TITLE
Bad resolution/Bug in map and terrain graphics 

### ISSUE THREAD

**Issue by Kab-stain** [ValveSoftware/Dota2-Gameplay#11412]
After the latest update, the in-game graphics resolution are very low and looks blurred. I can't fix it even the video options are all set to high!!! Please assist to resolve this issue, its terrible to play the game with these graphics!!
![Dota 2 Screenshot 2023 09 03 - 02 02 06 61](https://github.com/ValveSoftware/Dota2-Gameplay/assets/143911940/08cb61f3-2d89-4bf1-9802-08dc79c2809c)

**Comment by BenLubar** [comment]
You have the 10th anniversary map effect equipped.

**Comment by kumero96** [comment]
Arsenal - Environment - Landscape - Select Standard

**Comment by Kab-stain** [comment]
> You have the 10th anniversary map effect equipped.

thanks its fixed now
