### ISSUE TITLE
Bug report:Armory

### ISSUE THREAD

**Issue by PandaGenius89** [ValveSoftware/Dota2-Gameplay#11491]
### Cosmetic Item Name

A few full sets

### Description

A few full sets can't be recognized in the Armory

Ogre Magi:Stonebreak
Puck:Luminous Scarab
NYX Assassin:Sapphire CraB
Tusk:Eternal Icebreacker

Upon these sets can't be recognized in the Armory.
It's not convinient for us to buy a full set.We need to click one by one and find which is missing.
Please fix it,thanks.

### Example Match ID

None

**Comment by shaileshgarg** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/259
