### ISSUE TITLE
Summon Spirit Bear uses pre-reduction logic instead of post-reduction

### ISSUE THREAD

**Issue by cycycy-g** [ValveSoftware/Dota2-Gameplay#115]
### Ability name

Summon Spirit Bear

### Description

The Spirit Bear cannot be resummoned, if it has taken damage within the last 3 seconds.

This is the same restriction that is applied to Blink Dagger (and similar items) and Monkey King’s Tree Dance.

The difference is that a hero with Blink Dagger or Tree Dance can utilise a Hood of Defiance or Raindrop to block damage and have their item/spell not go on a damage cooldown.

Various regeneration effects behave the same, they use post-reduction logic, not pre-reduction.

Summon Spirit Bear currently uses pre-reduction logic, so the bear cannot be resummoned even if a Pipe’s barrier protected it from magical damage.

All the other pre-reduction spells have been changed to post-reduction (except for Chen’s teleport), Summon Spirit Bear should not be an exception.

### Example Match ID (and possibly Timestamp)

https://youtu.be/QVkTVtMpodI

**Comment by xtiaaaan** [comment]
Very insightful bug report

**Comment by cycycy-g** [comment]
Credits to my good friend [TheZett](https://github.com/TheZett)

**Comment by Nathanael-Valve** [comment]
Fixed in next update.
