### ISSUE TITLE
Dota crashes

### ISSUE THREAD

**Issue by serg2702** [ValveSoftware/Dota2-Gameplay#11509]
### Description

Problems started after the summer update. After launching DotA, a picture with new skins in the main menu starts loading. As soon as she appears, the dota immediately crashes. I tried the command map_enable_background_maps 0. It helped a little. The game no longer crashes in the main menu. But as soon as I start the game and select a character, it immediately crashes again. I checked the integrity of the files twice, reinstalled dota completely, but it did not help. The micro patches you did didn't help either. Please help me solve this problem.

**Comment by M-boxx** [comment]
Had the same problem today, on win11. Tried reinstalling dota completely several times. Did not help. 
It always asks something like: "Verify integrity of game files." Got banned today, thats the reason why I'm here.
Developers, please help us :c

**Comment by serg2702** [comment]
FOUND A SOULUTION . right click on dota 2, go to properties. put -dxlevel 80 in launch options .
