### ISSUE TITLE
Scan is always on cooldown

### ISSUE THREAD

**Issue by hgajshb** [ValveSoftware/Dota2-Gameplay#11556]
### Description
Scan on the Dire is always on cooldown.
Like someone used it but there is no log

### Example Match ID (and possibly Timestamp)

7320282823

**Comment by mmm-da** [comment]
Same issue; We play on Dire and reproduce this bug
Match id with issue: 7331900063

**Comment by mmm-da** [comment]
Screenshot from private lobby:
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/39336091/f257fbdf-9e4a-4066-aff7-a601060beef5)

**Comment by chrisf-valve** [comment]
This has been fixed in an update that shipped yesterday.
