### ISSUE TITLE
MacOS significant FPS drop if function key is in use

### ISSUE THREAD

**Issue by homerblr** [ValveSoftware/Dota2-Gameplay#11608]
### Description

MacBook Pro M2 Pro 16GB

When using functional keys like F1(decrease screen brightness) fps can drop down to 10.
Also game sometimes (I can't find the pattern) can also drop FPS down to 10. This started to happen after Summer client update.

### Screenshots

<img width="1634" alt="Screenshot 2023-09-06 at 16 27 44" src="https://github.com/ValveSoftware/Dota2-Gameplay/assets/44680861/886d8981-3b07-4c60-8dcf-84e75b8006e5">

**Comment by homerblr** [comment]
duplicated at dota-2

**Comment by jamesranu** [comment]
An [SMM server](https://smmpanelproviders.com/) is a centralized platform that facilitates the management, scheduling, and analysis of social media campaigns, allowing users to efficiently plan and execute their marketing strategies across various social media channels.
