### ISSUE TITLE
Soul Ring does not remove ununsed mana

### ISSUE THREAD

**Issue by Richard-Degenne** [ValveSoftware/Dota2-Gameplay#11601]
### Item name

Soul Ring

### Description

In this game, Dawnbreaker uses a Soul Ring but does not use any of the bonus mana during the 10 second duration of Sacrifice.

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/6302494/708fe7be-3b41-4317-bdcc-af4067b29e06)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/6302494/050d6217-8ccb-4065-a730-f8c1aef56795)

# Expected behavior

When the duration of Sacrifice runs out, Dawnbreaker should lose the unused mana. In this instance, the whole 170 mana.

# Actual behavior

When the duration of Sacrifice runs out, Dawnbreaker does not lose any mana.

---

It goes without saying that this bug breaks the item, and provides a huge unintended advantage to heroes that tend to buy it, turning a temporary mana boost into what is effectively a (170 mana ÷ 25 seconds) 6.8 mana regeneration item.

### Example Match ID and Timestamp

7319926442 - 03:20

**Comment by shaileshgarg** [comment]
Easily reproducable in Demo.

**Comment by eugene-valve** [comment]
Thanks for reporting this, it should be fixed in an upcoming update.
