### ISSUE TITLE
Dota plus not activated after purchase

### ISSUE THREAD

**Issue by system6605** [ValveSoftware/Dota2-Gameplay#11618]
### Item name

Dota Plus — one month subscription

### Description

Dota Plus —  one month subscription was purchased and was not activated in the game. I have found it in the inventory but it doesnt have any buttons for activation or something - opened info and also clicked by both mouse buttons.
![Screenshot 2023-09-06 224817](https://github.com/ValveSoftware/Dota2-Gameplay/assets/104530257/8a24aa14-ea2a-40a8-b8af-c8bbb11cd9ab)
![Screenshot 2023-09-06 224919](https://github.com/ValveSoftware/Dota2-Gameplay/assets/104530257/9daeac91-515f-459b-841b-0a3ec033b1d7)
Steam transaction id: 3431234397228860667
my Dota player id: 1016739291

### Example Match ID and Timestamp

1016739291

**Comment by Xeo322** [comment]
I have the same issue, but today this items was removed from my inventory
Steam transaction id: 3418849498251765971
Steam transaction id: 3418849498252715279
Dota player id: 188380850

**Comment by illuminati152** [comment]
I have the same issue, but today this items were removed from my inventory
Steam transaction id: 3173403318558860989
Steam ID: 76561198244475768

**Comment by DDemons** [comment]
Same issue, I can see in my dota plus in steam inventory but can't find it in dota armory. No way to activate it

**Comment by sarseniy** [comment]
+1

**Comment by system6605** [comment]
My issue with dota plus subscription was resolved, now I have an active one. Thanks

**Comment by domants** [comment]
@system6605 bro, I'm having the same issue. Can you share the steps how to rectify the issue? Thanks

**Comment by illuminati152** [comment]
Update: They fixed it for me, I checked on the third day. I didn't do anything, did not use an item. I was just subscribed.
