### ISSUE TITLE
Missing courier on turbo match.

### ISSUE THREAD

**Issue by wonderkid21** [ValveSoftware/Dota2-Gameplay#11639]
### Description

Missing courier while playing turbo match. Reconnecting doesn't seem to solve the problem. The courier was really gone like Dota 2 in 2012 where you have to buy it first before using it.

It seems not the entire players courier had gone, just few of them including me.

### Example Match ID (and possibly Timestamp)

7323545934 - 20:24

### Screenshots

![Screenshot (8)](https://github.com/ValveSoftware/Dota2-Gameplay/assets/144355198/719fcbe6-d7e8-440e-8858-3542ded23712)
![Screenshot (7)](https://github.com/ValveSoftware/Dota2-Gameplay/assets/144355198/509a3cfc-2193-42b6-9f4d-1cb7969c10ef)

**Comment by the-hyp0cr1t3** [comment]
Same thing happened with my team (dire). 4/5 couriers disappeared from dire and their passive gold income also stopped for the remainder of the entire game. Reconnecting didn't solve the problem.

Match ID: 7323845723
Timestamp: 3:05 - end

**Comment by codydorsettlynn** [comment]
Same bug in this match ID: 7331419410

**Comment by ragago29** [comment]
Same bug, no courier in turbo playing as Jakiro on dire side. Match ID 7330573340 

![20230911203205_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/132935099/0892e822-5055-4305-8aa6-efd9b414e914)

**Comment by Meridiann** [comment]
Same thing happened to me

Match ID: 7332421533

**Comment by Nathanael-Valve** [comment]
Fixed in next update.

**Comment by Nathanael-Valve** [comment]
Fixed in next update.
