### ISSUE TITLE
Feature Request: Keep same tab open when scrolling through Heroes tab?

### ISSUE THREAD

**Issue by damer76** [ValveSoftware/Dota2-Gameplay#11630]
### Description

After the Summer 2023 update, when you go to the Heroes tab in the main menu and select any hero, switching to another one (whether by pressing arrow keys or searching a hero by name) moves you to the Loadout tab for that new hero, regardless of which tab you had open for the previous hero.

Before the update, the tab was maintained when changing heroes, so it was easy to check stats or hero progress for multiple heroes. Currently you need to re-select the tab every time you move to another hero. This is especially annoying when refreshing quests, previously you could just spam click LMB and right arrow.

Maybe revert to old behaviour for this (i.e. maintain the currently opened tab when switching to another hero)?

**Comment by vivi-lili** [comment]
Fixed in next patch
