### ISSUE TITLE
Cannot report or avoid player after match

### ISSUE THREAD

**Issue by devrimcavusoglu** [ValveSoftware/Dota2-Gameplay#11633]
### Description

If you ignore (mute or ignore) or report a player during a match, there is no report flag after the match ends. You **cannot report or avoid** a previously ignored/reported player which is undesirable. I know that the avoid can now be applied during a match, but if you do not avoid in the match, but want to avoid or report after the match that is impossible currently. As a side note, you can nor like neither dislike that player too.

**Comment by rupakbajgain** [comment]
It would be even better if i could report after watching replay to be sure.

**Comment by gabrielheming** [comment]
Same issue here. I found out that after issuing a report during the game, you cannot add any other report after the match.
Also, **it would be extremely useful to report while watching the replay,** it would give a lot of precision on reports timing, mainly for hacks/scripts.

**Comment by devrimcavusoglu** [comment]
This seems fixed currently.
