### ISSUE TITLE
After stutter stuff was fixed I am experiencing lots of disconnections from the game.

### ISSUE THREAD

**Issue by AmanovAkbar** [ValveSoftware/Dota2-Gameplay#1163]
### Description

Since today players get disconnected from the game a lot. Like a lot. The last few games I played each and every player in the game disconnected at least once, but most of us several times. It is probably not caused by internet connection because everything works fine after reconnection, at least until you are forcefully disconnected again. Every few minutes somebody will get diconnected and we all had to wait for him. 
What I noticed is that first you lose control over you hero for a few seconds, then the whole map freezes and then you get thrown out of the game and need to reconnect. 
Some of you might think that this is not much of a problem, but we had really absurdic amounts of disconnects.

### Example Match ID (and possibly Timestamp)

6614625731 the longest one is 42:08 but if you watch through the game we were pausing game pretty often.

**Comment by silimp77** [comment]
I have the same problem. A very big request to fix !!!

**Comment by Aphotic** [comment]
i am experiencing exactly the opposite, smoother connection somehow! 10-20pings lower than usual!
hope DotA keeps improving daily for everyone.
It's no longer a game, it's a lifestyle!  :}

**Comment by reacheight** [comment]
same #1081

**Comment by Masda-X** [comment]
Exact same problem.

**Comment by Bratish971** [comment]
Same

**Comment by AmanovAkbar** [comment]
Since constant and regular disconnects no longer happen I guess I gotta close the issue for now.
