### ISSUE TITLE
No Couriers in a Game

### ISSUE THREAD

**Issue by ktha00** [ValveSoftware/Dota2-Gameplay#11647]
### Description

While playing in turbo, After game started there is no couriers in Dire team, On Radiant team couriers are present. 

### Example Match ID (and possibly Timestamp)

7323938801 0:00

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/119751906/be0516f9-5867-4714-81c0-81029261d6e0)

**Comment by shaileshgarg** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/11639

**Comment by Nathanael-Valve** [comment]
Fixed in next update.

**Comment by Nathanael-Valve** [comment]
Fixed in next update.
