### ISSUE TITLE
No courier or passive income on turbo match

### ISSUE THREAD

**Issue by AyaxReloaded** [ValveSoftware/Dota2-Gameplay#11655]
### Item name

Courier

### Description

everybody had no couriers, and no passive gold income, as well as weird behavior on hero´s movements speed

### Example Match ID and Timestamp

7324340822 0:00

**Comment by shaileshgarg** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/11639

**Comment by Nathanael-Valve** [comment]
Fixed in next update.

**Comment by Nathanael-Valve** [comment]
Fixed in next update.
