### ISSUE TITLE
I received a personality for an invoker as a gift, but it is not visually put on the hero, but is worn in the arsenal

### ISSUE THREAD

**Issue by ishseikatsu** [ValveSoftware/Dota2-Gameplay#11664]
### Cosmetic Item Name

Angel of Vex(Invoker)

### Description

Received a personality for an inviter as a gift, unpacked the personality, put it on, and neither in the game nor in the menu of the hero himself does it visually display that the personality is dressed, but in the arsenal it is written that everything is dressed. I don't understand how to fix this problem?

### Example Match ID

*nothing*

### Screenshots

*nothing*

**Comment by commentator24** [comment]
persona is at the top i think, like this am
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109324155/c595cbb8-4c62-41df-82bd-4c4aca9398c0)
