### ISSUE TITLE
Dota Plus Week Bundle

### ISSUE THREAD

**Issue by AbominationSVR** [ValveSoftware/Dota2-Gameplay#11668]
### Description

After your update of the arsenal: Dota Plus Week Bundle missed from my inventory in dota. But I still have it in my Steam inventory. What I should do to activate it?

Steam ID:880055535351337228
Dota ID: 178194508

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/119545361/cfda6539-d115-4107-96a5-1aba31e7cd0c)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/119545361/0fda686e-5982-4b10-bc3f-b510dab10cdd)

**Comment by sarseniy** [comment]
Yeah, I have the same issue. Please fix it

**Comment by vtyric** [comment]
+1

**Comment by ChocolateHacker** [comment]
+1

**Comment by onezuppi** [comment]
+1

**Comment by GUIDE-WS** [comment]
I also have the same problem. How to fix it?

**Comment by globusqq** [comment]
+1

**Comment by euikon00** [comment]
+1
