### ISSUE TITLE
Getting 2 kills from a single kill/ 2 deaths from 1

### ISSUE THREAD

**Issue by AlirezaCrash** [ValveSoftware/Dota2-Gameplay#11684]
### Description

Enemy Spectre death counted as 2. The kills were awarded to two different heroes.
(and no he does not have armlet, and no he was not Grim ultied)

### Example Match ID (and possibly Timestamp)

7323851619 - timestamp : 31:18

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/106863505/8a21186d-88c5-492c-b6df-81948f91e9df)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/106863505/c3bbd136-3565-4b06-b02a-14275a49708c)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/106863505/b3711b67-f59d-4f52-8d99-dec40d67ec7e)

**Comment by KazsaB** [comment]
Explained in #11736
