### ISSUE TITLE
Armlet bug mechanics

### ISSUE THREAD

**Issue by KazsaB** [ValveSoftware/Dota2-Gameplay#11697]
### Item name

Armlet of Mordiggian

### Description

Any hero dies twice with an active armlet under certain circumstances explained in linked video.
https://www.youtube.com/watch?v=IRBwWHybAqw&ab_channel=Kazsaj 
still works in 7.34c.
Example match id and timestamp is an example, but better explained in video

### Example Match ID and Timestamp

7323090800 - 35:53

**Comment by shaileshgarg** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/11139
