### ISSUE TITLE
Quickcast is not working for jungle items

### ISSUE THREAD

**Issue by SilverKn1ght** [ValveSoftware/Dota2-Gameplay#11739]
### Item name

Every ground selectable item

### Description

Quickcast is not working for neutral jungle items like FALLEN SKY etc.

Video showing example:
https://youtu.be/3qU7Wb5Uz58

### Example Match ID and Timestamp

Doesn't have.

**Comment by shaileshgarg** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/8540

**Comment by SilverKn1ght** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/8540#issuecomment-1551074771 solved for now...
