### ISSUE TITLE
Track, Open Wounds, Tether, Blademail Multi-Kill Bug Mechanics

### ISSUE THREAD

**Issue by KazsaB** [ValveSoftware/Dota2-Gameplay#11744]
### Ability name

Open Wounds, Tether

### Description

Using these spells in a certain way causes high amounts of kills to occur at once.
https://www.youtube.com/watch?v=Zi3pEjFwPRE&ab_channel=Kazsaj

### Example Match ID (and possibly Timestamp)

7325608231 - 23:58

**Comment by KazsaB** [comment]
#11686

**Comment by POLIVALKA** [comment]
like

**Comment by KazsaB** [comment]
Track is not needed to reproduce bug
