### ISSUE TITLE
Warlock is always small in the overview

### ISSUE THREAD

**Issue by frankcalise** [ValveSoftware/Dota2-Gameplay#11746]
### Description

After the game ends, the Warlock image on the score screen is always tiny compared to others in 7.34+

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/374022/1c180841-fccd-464f-a544-bff413889bd8)

**Comment by shaileshgarg** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/11255
