### ISSUE TITLE
Triple Kill Bug Mechanics

### ISSUE THREAD

**Issue by KazsaB** [ValveSoftware/Dota2-Gameplay#11742]
### Ability name

Laser and Armlet

### Description

https://youtu.be/1kSWEQ_S_qA 
Combining laser and armlet bug you can do triple kills with certain abilities.
No match ID as this was done through demo.

### Example Match ID (and possibly Timestamp)

XXXXXXXXXX

**Comment by shaileshgarg** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/11139
