### ISSUE TITLE
dota plus gift bug

### ISSUE THREAD

**Issue by nestyraee** [ValveSoftware/Dota2-Gameplay#11756]
### Description

I was given a dota plus, but when I entered the game I can't find it in the arsenal, but there is a subscription in the inventory

### Example Match ID (and possibly Timestamp)

-

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/144589077/45a659e6-e4d8-48b7-ba44-d29cf192d55a)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/144589077/7745b3ef-6e60-4580-bb84-037a02872141)

**Comment by Aluerie** [comment]
fixed
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/33165440/e9fcd519-c46a-48f2-97c0-d23b9aaf6aeb)
