### ISSUE TITLE
Dota 2 Game Crash Issue Report

### ISSUE THREAD

**Issue by bored17** [ValveSoftware/Dota2-Gameplay#11761]
### Description

Steps to Reproduce:

1. Launch Dota 2 and enter a match.
2. Choose a hero with an active item (e.g., Storm Hammer).
3. Without selecting a target, use the active item.
4. Immediately drop the active item.

Expected Behavior:

The game should handle this situation, for example, by displaying an error message or not allowing the item to be dropped, but it should not result in a game crash.

Actual Behavior:

The game crashes and displays an error message (if any).
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/38162332/68f7677f-09b0-40d0-aabf-2e3952d54f2f)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/38162332/1eeab4d2-22fd-41ce-884a-7347134fe7ff)

Additional Information:

This issue was observed in Dota 2 version [7.34C].
I am using the operating system [windos11].
My hardware configuration includes [Your computer hardware specifications, uter hardware specifications, such as CPU, GPU, etc.].such as CPU[rx5600], GPU[gtx 3060ti], etc.].

**Comment by zyunwei** [comment]
it occurs on unit target item only.

**Comment by bored17** [comment]
FIXED
