### ISSUE TITLE
Dota Plus Bug

### ISSUE THREAD

**Issue by magemiralles** [ValveSoftware/Dota2-Gameplay#11809]
### Description

I can't find/activate my dota plus membership because it is missing in game.
The new armory can't locate my one month membership.

### Screenshots

![Dota Plus Bug](https://github.com/ValveSoftware/Dota2-Gameplay/assets/144517641/4d78add9-c7de-48b0-b177-859d3983d3f1)

**Comment by DDemons** [comment]
same issue
