### ISSUE TITLE
Wraith King ulti strange behaviors

### ISSUE THREAD

**Issue by wmpay** [ValveSoftware/Dota2-Gameplay#11812]
### Ability name

Reincarnation

### Description

1st death as wraith king counted as 2 deaths, even though I only died once.
Other death later, instead of respawning at the point of death, I respawned in the fountain.

### Example Match ID (and possibly Timestamp)

7329548010

**Comment by shaileshgarg** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/11524

**Comment by irismus** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/11524#issuecomment-1749795727

Issue fixed and please help close the issue OP.
