### ISSUE TITLE
Legacy Sets from Shard Shop, not shown in new Armory

### ISSUE THREAD

**Issue by shaileshgarg** [ValveSoftware/Dota2-Gameplay#11828]
### Cosmetic Item Name

All Legacy Sets

### Description

In the new Armory the Premium Sets from Shard Shop are present, but the Legacy Sets are not. The shard shop has to be opened explicity to view them.

### Example Match ID

-

**Comment by vivi-lili** [comment]
Were there specific Legacy Sets that are not showing?  I've checked several and they do appear in Armory.

Did you mean that they are not showing in Armory with Shards as the primary purchase option?

**Comment by shaileshgarg** [comment]
Yeah, either they show as Available in Treasure or Show a $ value, no Shard cost is mentioned.

**Comment by shaileshgarg** [comment]
Hmm, I feel that the Shard Shop can be completely be done with, if Legacy Sets, Tools, Hero Relics are available to purchase in the Armory with Shards.

**Comment by vivi-lili** [comment]
Added support for showing Shard cost in Loadout/Armory pages, even if the primary purchase option is $ value or Treasure.  Will be in next patch.  Decided to keep the Shard shop since it is a streamlined shop for Shards-only customers.
