### ISSUE TITLE
Can not watch tournament games

### ISSUE THREAD

**Issue by olagheparande** [ValveSoftware/Dota2-Gameplay#11837]
### Description

Hey guys, I think everybody knows this issue but I could not find anyone talking about it and how/when it will be fixed.
No one can watch a tournamet from in-game watch system, every game ticket and every tour is the same.

**Comment by T1HGO** [comment]
Yes, i opened a ticket here yesterday with this issue, and also on reddit. Seems no one cares about it.

**Comment by Mystiques1** [comment]
We need Jeff Hill

**Comment by T1HGO** [comment]
This issue has been going on since the update on 31st of August. I can already see TI coming up in a month, and this issue still to be fixed.

**Comment by Jaymeetvasava** [comment]
right now, I cannot watch any games in dotatv. valve, pls fix this issue.
