### ISSUE TITLE
No courier game at turbo mode

### ISSUE THREAD

**Issue by bolodjah** [ValveSoftware/Dota2-Gameplay#11858]
### Description

Turbo mode all match w/o courier and gained 0 gold. Boots of travel don't have tp at 1st time

### Example Match ID (and possibly Timestamp)

7331553281

**Comment by shaileshgarg** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/11639

**Comment by Nathanael-Valve** [comment]
Fixed in next update.
