### ISSUE TITLE
Dota Plus as a gift is not displayed in the inventory

### ISSUE THREAD

**Issue by prokuratura13** [ValveSoftware/Dota2-Gameplay#11855]
### Description

I was given Dota Plus, I unwrapped the gift but the item activation subscription is just not, neither in the search nor in the arsenal dota. And in the inventory of the steam is what to do ?
my steam id is 1121922161

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/144804476/29378f95-803d-4d2c-9466-4a46cd8af740)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/144804476/d307fd2e-b318-4e10-a99d-990b2469123f)

**Comment by prokuratura13** [comment]
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/144804476/61d9c6fd-97b4-467f-a775-306af27bd98b)

**Comment by euikon00** [comment]
same to me can't find it since the update of the new armory in dota 2, but it's in my steam inventory. any fix for this???

**Comment by Kazumo0** [comment]
+

**Comment by DDemons** [comment]
same issue, please fix

**Comment by Aluerie** [comment]
fixed
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/33165440/e9fcd519-c46a-48f2-97c0-d23b9aaf6aeb)
