### ISSUE TITLE
Watch Live not functional

### ISSUE THREAD

**Issue by NoMore201** [ValveSoftware/Dota2-Gameplay#11869]
### Description

Currently I'm unable to watch any game in the "Watch Live" section. The game is stuck in "Waiting to watch game..." for 30 seconds to 2 minutes , and finally I'm greeted with the following empty message:
![immagine](https://github.com/ValveSoftware/Dota2-Gameplay/assets/3220188/4d37a9ee-6ced-4062-9b0b-3bc976f44d04)

### Example Match ID (and possibly Timestamp)

any live game 

### Screenshots

![immagine](https://github.com/ValveSoftware/Dota2-Gameplay/assets/3220188/aa0522d3-ecfc-4a99-9c4f-f979f20fcff0)

**Comment by robert-gogolan** [comment]
Seems to be fixed now. Can you check again?

**Comment by NoMore201** [comment]
Yes it's solved
