### ISSUE TITLE
Finger of Death stack gaining malfunctions when used against Meepo (clones)

### ISSUE THREAD

**Issue by TheZett** [ValveSoftware/Dota2-Gameplay#1187]
### Ability name

Finger of Death

### Description

Lion’s Finger of Death seems to utilise 3 different stack gaining logics when used against Meepo, depending on directly targeting a non-Meepo hero, the real Meepo (Prime) / a Meepo clone or a Meepo illusion.

There are multiple issues with its current implementation and it should get fixed to always grant 1 stack in total for all Meepoes (except Meepo illusions).

**Scenario 1 – Targeting a non-Meepo hero:**

When directly targeting a non-Meepo hero, and Meepo clones die to the AoE Aghs effect, Lion gains too many FoD (Finger of Death) charges.

He gains a charge for every Meepo clone, instead of just 1 charge in total for all Meepoes (the behaviour being used by Flesh Heap, Glaives of Wisdom, Essence Shift and effectively all other abilities that gain benefits when a hero dies).

This allows Lion to gain up to 9 charges at once, when targeting a non-Meepo hero with Aghs FoD by killing 4 non-Meepo heroes, a Meepo Prime and 4 Meepo Clones with a single cast of FoD.

Video: https://youtu.be/WcBBteA2-mg

**Scenario 2 – Targeting Meepo Prime or a Meepo clone:**

When directly targeting either Meepo Prime or one of the Meepo clones, Finger of Death will only grant a single FoD charge per cast, even if 4 non-Meepo heroes died to the AoE effect.

In this case Lion gains too little charges, he only ever gets 1 charge, instead of up to 5 (one for all the Meepoes + 4 for the non-Meepo heroes).

Video: https://youtu.be/WEFKieDPmZc

**Scenario 3 – Targeting a Meepo illusion:**

When directly targeting a Meepo illusion, Finger of Death will grant zero charges per cast, even if 5 real heroes died to the AoE effect.

In this case Lion gets no charges at all, once again a case where he does not gain the correct amount of charges.

Video: https://youtu.be/1UCQdx5aTSo

### Example Match ID (and possibly Timestamp)

3 videos are provided above

**Comment by Dota-Exp** [comment]
Will be fixed in upcoming update (1 stack for killing Meepo). Thank you
