### ISSUE TITLE
Player View Won't work

### ISSUE THREAD

**Issue by Mahyardana** [ValveSoftware/Dota2-Gameplay#11916]
### Description

while watching live games player view locks in middle of map and cursor of player would not appear in the screen but you can see clicks of player on ground and camera will be locked in middle of map no matter what you do

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/31076059/e9223820-e5c6-4091-8d1b-14bf8772b3fb)

**Comment by Avarise831** [comment]
#11026

**Comment by robert-gogolan** [comment]
@Mahyardana can you confirm the issue if fixed and close this?

**Comment by Mahyardana** [comment]
yes it seems that the issue is gone now
thank you
