### ISSUE TITLE
Dota plus error

### ISSUE THREAD

**Issue by Kazumo0** [ValveSoftware/Dota2-Gameplay#11917]
### Item name

dota plus:subscription month

### Description

A friend gave me a dota plus subscription, it is in the steam inventory, but it is not in the dota arsenal itself (what would you advise to do in this situation?)
(https://github.com/ValveSoftware/Dota2-Gameplay/assets/144835326/8b7f6a98-ac7f-47a3-8cd0-8044cd48ebc4)

### Example Match ID and Timestamp

.

**Comment by DDemons** [comment]
same issue, please fix
