### ISSUE TITLE
Rubick PlayerHero cease to exist in MMR Game

### ISSUE THREAD

**Issue by MontyTonty** [ValveSoftware/Dota2-Gameplay#11929]
id:19713961
Bug time: 32:40
Rubick used "Spell Steal" on Rasta but he turned into a "Death Pulse" which he had stolen before. He then went into "death pulse" towards Rasta who died meanwhile. Rubick from that point on could not be found on the map anymore. When double click on Rubick Portrait it goes to the position he was on before he cast "Spell Steal" on Rasta. 

Please fix this beta game and compensate our mmr, thanks. 
![20230915000309_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/1450
![20230915000319_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/145070562/9de5b53d-a15f-4074-8ee4-b36cb3819571)
70562/ce29315c-b8a9-40bb-86f0-9a5cda0c0d9a)
![20230915000326_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/145070562/acbbc72b-c5b7-47af-8663-71c065e4c78d)
![20230915000349_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/145070562/b7f9bae2-fd9b-4618-a1d7-2b6aae860014)

**Comment by Aluerie** [comment]
D #8208

**Comment by MontyTonty** [comment]
Fuck, they knew about it for month and didn’t just disable that spell from stealing/morphing. Wtf are you doing with your compendium billions
