### ISSUE TITLE
Arc warden starts game with tempest double abilities

### ISSUE THREAD

**Issue by Patronams** [ValveSoftware/Dota2-Gameplay#11941]
### Description

I played a few games with arc warden and every now and then you start the game with arc wardens tempest doubles abilities.
this make things like farming with second ability bad etc. unfair when you use 1st ability in lane phase and 3rd ability.
see match for reference: 7335725471

### Example Match ID (and possibly Timestamp)

7335725471

### Screenshots

![2](https://github.com/ValveSoftware/Dota2-Gameplay/assets/145130766/ca5b9897-7786-4fb7-bab1-b623d7e33026)
![1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/145130766/41b4a0a2-766b-4565-99ba-0fd936156ca0)

**Comment by Aluerie** [comment]
Read 733

**Comment by coolguy38** [comment]
close the issue OP
