### ISSUE TITLE
Camera! live watching! #BUG!

### ISSUE THREAD

**Issue by trgd15** [ValveSoftware/Dota2-Gameplay#11947]
### Description

While watching a game live, if you click VIEW THROUGH THE PLAYER'S EYES, the camera is moved to the middle and cannot be moved. There is no such problem when watching the replay!

**Comment by Avarise831** [comment]
#11026

**Comment by coolguy38** [comment]
close the issue OP

**Comment by robert-gogolan** [comment]
@trgd15 can you confirm the issue if fixed and close this?
