### ISSUE TITLE
Nyxs eyes texture stretch while moving

### ISSUE THREAD

**Issue by Anotheraq** [ValveSoftware/Dota2-Gameplay#11955]
### Cosmetic Item Name

Oculi of the Chitinous Stalker

### Description

Nyxs eyes positioned in wrong way while moving which causes texture to stretch. It can be seen in heroes tab in main menu, directly in game and on portrait(all attached in screenshots). It is not cause of any combination of the cosmetic items because it can be observed too while wearing only the Oculi of the Chitinous Stalker.

### Example Match ID

7330763063 (every match)

#### In main menu:
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/62223979/74510354-f4e4-41fe-8ba3-b9872e239438)
#### In game:
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/62223979/696c91e6-f3d1-433f-b268-f8a41220ba4a)
#### Portrait:
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/62223979/135d961c-135e-4033-b88c-5d89e8f85dfb)

**Comment by Anotheraq** [comment]
#7948

**Comment by coolguy38** [comment]
close the issue OP

**Comment by Anotheraq** [comment]
> close the issue OP
#### Duplicate
good call, hope they still find this one helpful :)
