### ISSUE TITLE
Disappeared Gabe Newell 10-Year Anniversary Celebration Item

### ISSUE THREAD

**Issue by gswempire** [ValveSoftware/Dota2-Gameplay#11969]
### Item name

10-Year Anniversary Gabe Newell Chat Lines

### Description

I won the match, received the item, opened it, but it was gone. 
There are no changes to the armory, 
It's not in the interface, and it's not in any items.

It just says 'received'.

If I click ‘Available in treasure’, it returns to the previous step.

my friend code : 40474902
my nickname : Dino

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/86782577/83c01a39-16be-4516-821b-4f70a0931233)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/86782577/71f860d0-6cee-4e9d-a962-94369636899d)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/86782577/81e323ab-a990-47e6-bb2a-4fab897d536a)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/86782577/dc29cbd3-3000-49c6-a4b9-4e1870bcb2a3)

### Example Match ID and Timestamp

Store error

**Comment by Aluerie** [comment]
i mean, did you activate it? You gotta check voice-lines first, not all this crap.

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/33165440/123059dd-1630-4468-b683-102e96841bc9)

the item indeed "disappears" after you activate it because you have the voice-lines "inventory".

**Comment by gswempire** [comment]
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/86782577/0dd788cb-3aae-401a-8d1a-c9e0fe0f899e)

Oh I found it. thanks! :0 

I thought it was gone because it didn't show up in my inventory or armory.
