### ISSUE TITLE
Aghanim's Scepter stat was lost when upgrade to non-inventory mode

### ISSUE THREAD

**Issue by hohoangtung** [ValveSoftware/Dota2-Gameplay#11966]
### Item name

Aghanim's Scepter

### When upgrade Aghanim's Scepter (5800). All Aghanim's Scepter stat was lost.

**Before**
![before](https://github.com/ValveSoftware/Dota2-Gameplay/assets/13851541/8bb99bcc-5eaa-47ee-80bd-e152e4819e5a)

**After**
![after](https://github.com/ValveSoftware/Dota2-Gameplay/assets/13851541/e64f8820-7639-4901-a087-1798b908c289)

### Example Match ID and Timestamp

7338713578 aroud 54:30

**Comment by shaileshgarg** [comment]
That is intended behavior for upgraded Aghanim's

**Comment by hohoangtung** [comment]
@shaileshgarg  Thank you. I got it. 
But seem that's not fairly upgrade :(
