### ISSUE TITLE
Player's Spectator cam problem

### ISSUE THREAD

**Issue by vitorgomes** [ValveSoftware/Dota2-Gameplay#11976]
### Description

Every time now when i spectate some games, when i choose "player" cam option (the one where we see what is looking and how he is moving his/her mouse) is locked at the center of the map and does not move. In my client, when you choose the option, the cam does not move and stay there in the center of the map.

I provided a Match ID, but for me, all games that i start to watch and choose this cam option shows this problem.

### Example Match ID (and possibly Timestamp)

7339335858

**Comment by shaileshgarg** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/11026

**Comment by vitorgomes** [comment]
There are some issues opened for the problem, closing my so we do not have a duplicated
