### ISSUE TITLE
Mirana Persona Bundle 10th Year Anniversary Is not showing anywhere on my Armory 

### ISSUE THREAD

**Issue by akiyokallen** [ValveSoftware/Dota2-Gameplay#11980]
### Item name

Mirana Persona Bundle

### Description

I received Mirana Persona Bundle from 10th Anniversary a week ago, but I couldn't find it on my armory I couldn't find it anywhere, I tried everything just to locate the Mirana Personal but still it doesn't show even in the (Owned) I took all the 13th Treasure only the Mirana Persona is missing. please help me to have it again,  Here's my DOTA2 ID NUMBER: 910346021

![1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/145279419/24c9cffb-0666-4ab7-8ea8-6a007a81ee69)
![2](https://github.com/ValveSoftware/Dota2-Gameplay/assets/145279419/4608528a-f758-4bef-a152-4abea125fa84)

### Example Match ID and Timestamp

5:30 PM today

**Comment by revdepign** [comment]
Maybe the interface is confusing for some people including me.
![mirana1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/143705201/ca7caa0d-28f4-4c78-b5af-f47659ade77f)

**Comment by akiyokallen** [comment]
Hi,

    Oh, have you done something? I am not quite sure if this Mirana Persona
was there earlier when I checked, but right now it is now showing.
Thanks for your help man.

**Comment by revdepign** [comment]
You can close this issue, I think?

**Comment by akiyokallen** [comment]
Yes, it's done.
