### ISSUE TITLE
Player perspective in the live game is not executed

### ISSUE THREAD

**Issue by NeomMael** [ValveSoftware/Dota2-Gameplay#11995]
### Description

Player perspective in the live game is not executed, the image always remains in the middle of Tier 1. It's all about tracking hero.
Here I have the player view of Monkey King and that no matter with which hero, with each one the picture always goes here in the middle of the Tier1 Tower. The picture doesn't move, you can't see how a player is playing! That was different before the update. When will this issue be resolved????

### Example Match ID (and possibly Timestamp)

in all matches 

### Screenshots

![20230915173128_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/145142730/351d488c-5bcb-44c6-8bc9-627324d4233d)

**Comment by NeomMael** [comment]
(this is copied from vitorgomes Player's Spectator cam problem #11976 he has formulated better than me thank you vitorgomes man)

Description

Every time now when i spectate some games, when i choose "player" cam option (the one where we see what is looking and how he is moving his/her mouse) is locked at the center of the map and does not move. In my client, when you choose the option, the cam does not move and stay there in the center of the map.

I provided a Match ID, but for me, all games that i start to watch and choose this cam option shows this problem.
this is copied from vitorgomes Player's Spectator cam problem #11976 he has formulated better than me thank you vitorgomes man

**Comment by shaileshgarg** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/11026

**Comment by robert-gogolan** [comment]
@NeomMael can you confirm the issue if fixed and close this?
