### ISSUE TITLE
Tuskar dotaPlus Shard 75,000k Set NOT WORKING OR SHOWING UP

### ISSUE THREAD

**Issue by riverus12** [ValveSoftware/Dota2-Gameplay#12011]
### Cosmetic Item Name

Hammer Of The Guarded Word Bundle Set

### Description

I just wasted the 150k worth of dotaPlus shards that I saved up to but the Tusk set bundle called Hammer Of The Guarded Word and it does not show up to my account equipped. It shows the same default set. I bought it once and noticed nothing happened, then I tried to buy it again cuz I thought it just didn't went through without realizing that I have spent 150k shards already. Please help me dota2 devs lmao. I want that set or either I want my shards back. 

### Example Match ID

857879217

**Comment by commentator24** [comment]
have you unbundled it? you wont see it until you unbundle.
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109324155/e821a39e-af6d-4fa9-9540-e9efd42df361)

2nd set you buy dont unbundle it, i think you can change it to another set if havent unbundle.

if you unbundle 2x you may need to contact steam support. they cant help u here

**Comment by commentator24** [comment]
and next time before you buy 2x you can check your shards log actually. click your available currency. look at the top left
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109324155/34856ead-452c-44b3-945f-58c04831f6e3)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109324155/034191bd-0ecf-41ac-8c2f-11e65f3dd1bf)

**Comment by riverus12** [comment]
sadly the item doesn't show in the bundles too. And yes it shows in my shards log.
