### ISSUE TITLE
Gem Cooldown stops when dropping on the ground and picking up

### ISSUE THREAD

**Issue by billmcdulin** [ValveSoftware/Dota2-Gameplay#12038]
### Item name

Gem

### Description

Cooldown stops when dropping on the ground and picking up

### Example Match ID and Timestamp

7343149938 45:55

**Comment by shaileshgarg** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/8773

**Comment by Nathanael-Valve** [comment]
Fixed in next update.
