### ISSUE TITLE
BUSHWHACK HOODWINK

### ISSUE THREAD

**Issue by maJlina** [ValveSoftware/Dota2-Gameplay#12041]
### Ability name

BUSHWHACK

### Description

all skills with a stun aimed at a point give stun and damage to invisible enemies, but skill 2 of the hoodwink BUSHWHACK does not give stun and damage to invisible enemies, please fix it

### Example Match ID (and possibly Timestamp)

was checked in the lobby

**Comment by commentator24** [comment]
please close this issue, unfortunately it's not meant to hit invisible. you can press alt + hover skill
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109324155/630f283d-ecf9-42c7-89da-7bc0c4339378)
