### ISSUE TITLE
Aegis doesn't expire.

### ISSUE THREAD

**Issue by thgiNd1M** [ValveSoftware/Dota2-Gameplay#12059]
### Item name

Aegis of the Immortal

### Description

When Aegis's timer run out. Aegis didn't disappear and still resurrect holder. Can't me move, drop or swap with other item in inventory. When you ping aegis it show timer that have minus before the timer ex. -15 seconds.

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/145611583/871923d1-b2f7-46f1-858f-806ce3aa8dd5)

### Example Match ID and Timestamp

7344254194 - 37:05

**Comment by irismus** [comment]
#12055 

Please help close this issue, OP. Thank you.
