### ISSUE TITLE
The new reporting and behavior summary system is intransparent and broken

### ISSUE THREAD

**Issue by WolftaresDerCoder** [ValveSoftware/Dota2-Gameplay#12065]
### Description

After the Update and the new reporting system I have gotten a well deserved 48 hour chat ban. Since then I gave my very best to stay calm and collected throuought my games and have recieved a lot of commends after won games. As someone who uses Voicechat frequently I suppose I also got muted a few times, but my behavior score increased again today. 
However, the message 'you are being reported more frequently than other players' never disappeared. After the increase in behaviour score earlier today, I played a few more games, in which I recieved even more commends. After my last game today, I have been chatbanned for 7 days. I have no idea why, we had someone literally griefing with IO position 1, not listening to any calls in a 4 v 5 situation after someone had abandoned and I have not spoken much in the whole game. Whenever I spoke, I reminded my team to stay calm and try to win the game. I did not flame in this game whatsoever. The game before that I got 4 commends by teammates and the game before that I had a griefing tinker (action taken in report log) and again I did not flame but instead stayed pma and gave my best to win.

I honestly believe that 
1. Commends should counteract communication reports, as the environment in losing games is often much more hostile and I have even been reported for literally defending myself against my teammates flaming me
2. I did not deserve that chatban since in the game in question, I didnt even flame a player that actively ruined my game, I even defended him at times
3. The system should be more transparent and give actual numbers and games in which you got reported, so you can do something about your behaviour
4. The system in its current state disincentivizes people to use the chat function in fear of losing important and basic tools such as pinging abilities and items and literally COMMUNICATING
5. If the system stays this way, the game will lose part of their playerbase (including me), as for me, a team game is not playable without communication.

Please undo my chat ban or AT LEAST work on the system behind it, so that stuff like this doesnt happen anymore. 

### Example Match ID (and possibly Timestamp)

7344406519 (I am Void Spirit)

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109857890/cdf96df0-6c83-4f10-9434-9c29908d1be4)

**Comment by SurDno** [comment]
Sir, this is a Wendy’s. 

It’s bug tracker, not a suggestion forum. Please close.

**Comment by WolftaresDerCoder** [comment]
> Sir, this is a Wendy’s. 
> 
> 
> 
> It’s bug tracker, not a suggestion forum. Please close.

1. From my point of view, there is clearly something wrong with the system, therefore i consider it a bug

2. where else am i gonna write, considering that this game has literally no support and steam always redirects you to this very page?
