### ISSUE TITLE
datadriven  CleaveAttack  error

### ISSUE THREAD

**Issue by XuanlZhu** [ValveSoftware/Dota2-Gameplay#12071]
### Ability name

battlefury_cleave

### Description

datadriven  CleaveAttack  error

CDOTA_AttackRecordManager::GetRecordByIndex - Could not find attack record (-1)!
FixupResourceName: Illegal path, missing extension passed in ("battlefury_cleave")!

### Example Match ID (and possibly Timestamp)

no

**Comment by TobyFlendersonFromHR** [comment]
Good

**Comment by XuanlZhu** [comment]
1
