### ISSUE TITLE
rebundle error

### ISSUE THREAD

**Issue by alaspaul** [ValveSoftware/Dota2-Gameplay#12070]
### Cosmetic Item Name

dancer of the spiteful eye

### Description

the problem im having is i cant seem to rebundle shadow shamans "dancer of the spiteful eye" set i have all the items needed for the bundle and all are tradable but when i press rebundle on the set it says "The bundle for this item cannot be re-bundled"

### Example Match ID

not in-Game

### Screenshots

![dancer of the spiteful eye set SHAMAN](https://github.com/ValveSoftware/Dota2-Gameplay/assets/53499601/a364db3d-9edc-42ce-af5c-c75e1e9b174a)
![rebundle error](https://github.com/ValveSoftware/Dota2-Gameplay/assets/53499601/fdda9666-6068-4b7e-acf5-c35332e6fb4d)
![screenshot of the loading screen of the set](https://github.com/ValveSoftware/Dota2-Gameplay/assets/53499601/66777a7e-8d7b-4fde-ba40-a400c0189650)
![screenshot of the set in my armory](https://github.com/ValveSoftware/Dota2-Gameplay/assets/53499601/7faf2b62-ae4e-4c50-88ce-2665c2da7007)

**Comment by Natuhaka** [comment]
Dota 2 Update - 9/1/2023

"Disabled rebundling for items with unlocked styles, or which unpack with dynamic gems"

But they disable all items have styles including non-unlocked items or free styles.
