### ISSUE TITLE
[Lion] Aghs upgraded AoE Finger of Death doesn't grant damage stacks properly when there is Meepo on the enemy team

### ISSUE THREAD

**Issue by Bu3nyy** [ValveSoftware/Dota2-Gameplay#1208]
### Ability name

Finger of Death

### Description

Currently, if you cast aghs AoE Finger of Death on a Meepo (prime or clone, doesn't matter), it will not place the debuff on any unit within the area, it only places it on the targeted Meepo.

On the other side, if you don't target a Meepo, it places the debuff on all enemies in the area, including multiple Meepos.

What this basically means is:

Target Meepo -> get rampage -> gain ONE stack for Finger of Death (only the targeted Meepo grants a stack)
Don't target Meepo -> get rampage -> gain up to NINE stacks for Finger of Death (5 heroes + 4 meepo clones)

**Expected behavior:** Finger of Death should place the debuff on one _hero per player_, regardless of who the primary target is. This way, even if multiple Meepos get hit by it, only one of them gets the debuff.

Also, it should place the debuff on actual heroes only. Right now, it paces the debuff on every unit, including creeps.

[video demo](https://www.youtube.com/watch?v=vHxznCn3-aI)

**Comment by ZZalles11** [comment]
This is contained within https://github.com/jeffhill/Dota2/issues/1187. Please close this issue.

**Comment by Dota-Exp** [comment]
Will be fixed in upcoming update (1 stack for killing Meepo). Thank you
