### ISSUE TITLE
Game doesnt react to number hotkeys if another language with accents is set

### ISSUE THREAD

**Issue by sicarionox** [ValveSoftware/Dota2-Gameplay#12086]
### Description

Since a few weeks ago, if a language with accents is set on my keyboard (in my case, Lithuanian), where the numbers are replaced by symbols with accents (i.e. ą instead of 1), the game does not react to the number keypresses. It has been fine since I've started playing the game. I'm not certain if this is a bug or a recent feature, but either way, this is incredibly inconvenient.

**Comment by Aluerie** [comment]
There is a setting in Hotkeys > to advanced "Bind keys based on keyboard position". Make sure it's on.

Otherwise idk.

**Comment by sicarionox** [comment]
oh that was indeed the culprit! mustve turned itself off for some reason. thank you! closing the issue since, well, not much of an issue anymore
