### ISSUE TITLE
my last post for now and the next month

### ISSUE THREAD

**Issue by NeomMael** [ValveSoftware/Dota2-Gameplay#12095]
### Description

this is not a game what i wants! this makes no fun! seriously what is going with you all? when you start make games balanced and communicative? when when when?
lose and ive got 4 afk and then in another game i made post the toxic shaman and bane and then now this match????????????????
wow you realy wants me to quiet dota and uninstall it right????????? np if you keep doing more like this in unrank then for sure i quiet dota for sure 100%

### Example Match ID (and possibly Timestamp)

7345673204

**Comment by MenOfWar** [comment]
you know this is a bug tracker right? nothing they will do about your case. just report the players ingame and their steam profile if you want. can be frustrating of course, but this is not the place to report those issues.

**Comment by TobyFlendersonFromHR** [comment]
no one cares, you suck
