### ISSUE TITLE
[Main Menu] Last pressed button is pressed again when you press any other clickable button after disconnecting from game

### ISSUE THREAD

**Issue by Asekeeewka** [ValveSoftware/Dota2-Gameplay#121]
When you do leave in-match view/screen (literally disconnect from game), last pressed button in main menu will be pressed again when you press any other button.
[This thread has video](https://www.reddit.com/r/DotA2/comments/k76i5z/last_pressed_button_is_pressed_again_if_you_click/). What happens in this video is:
1) I started last hit trainer
2) I disconnected from last hit trainer (**in-trainer** button, not the main menu one!)
3) I pressed "Play Dota" button. 
4) Because I pressed "Play Dota", last hit trainer activates again.

Same thing happens if you:
1) Disconnect from game (using main menu disconnect button)
2) Press Quit button
3) **Game Abandon** pop-up menu shows
4) You do not read it and press **Yes**
5) You get abandon

I found it to be hardware independent, as I could replicate it in my i5-7300hq, 1050, laptop and h4700, 1650ti laptop. 
First one barely manages the game between 40-90 fps (constantly going back and forth)  at lowest settings and second one managing dota at 90-110 fps at max settings possible.

**Comment by Ahimtar** [comment]
I'd suggest changing the title to something like
[Main Menu] Accidental abandon bug - Last pressed button is pressed again when you press any other clickable button after disconnecting from game
to be a bit more descriptive, since that's the most important impact of this bug, I think. (and it'll probably lead to more people upvoting)

**Comment by Ahimtar** [comment]
More cases: https://github.com/ValveSoftware/Dota2-Gameplay/issues/1436

**Comment by gumacahin** [comment]
Happened at TI11 group stage: 

https://www.reddit.com/r/DotA2/comments/y64fbb/misha_got_abandon_bug_in_og_vs_liquid_game_1/

**Comment by an3hul** [comment]
Happened to OG.Misha today. Gg

**Comment by Fjara-h** [comment]
Here is a video of it occuring just as documentation: https://www.youtube.com/watch?v=ZStgyP8mOKo

The first part is showing the issue happening and my second version is how you get around the problem. The mouse has to move before the new button hover is registered.

**Comment by cameron-valve** [comment]
Both the the general button press issue (as described in the behavior with the last hit trainer), and the specific issue of accidentally abandoning games, whether through this bug or just clicking too quickly, should both now be fixed.  Detailed and reliably reproduceable steps like this report absolutely help us track these things down.  Thank you! 

If you're aware of this behavior still existing in any way, please re-open the issue!
