### ISSUE TITLE
Aeon Disk buff shared with enemy

### ISSUE THREAD

**Issue by mr5z** [ValveSoftware/Dota2-Gameplay#12104]
### Item name

Aeon Disk

### Description

Earth Shaker didn't take any damage from finger. Succeeding normal hits from Lion is also disregarded. Interestingly, Lion's Aeon Disk got triggered as soon as he blinked in to kill ES but there is no damage coming from anywhere which seems ES received the AD buff?
![output](https://github.com/ValveSoftware/Dota2-Gameplay/assets/6318395/0ce5b22f-00dc-40a8-b343-7fed8c552088)

### Example Match ID and Timestamp

7345934800 - 33:33

**Comment by Artanisky** [comment]
Item description from wiki:
When you take damage and your health falls below 70%, a strong dispel is applied and you gain a second buff that provides +2.5 Status Resistance and causes all damage **you** deal and are dealt to be **reduced to zero**. Only triggers on player based damage. Cooldown increases every time it triggers.

Your damage to the enemy will be zero during the operation of the item

**Comment by mr5z** [comment]
@Artanisky ohh my bad. Didn't know that. I should read description more often 😅.
Will close this now.
