### ISSUE TITLE
Visage Familiars Tower Agro 

### ISSUE THREAD

**Issue by Avarise831** [ValveSoftware/Dota2-Gameplay#1212]
### Description

Tower never agro on familiar when u push tower near wave creeps

**Comment by Krev5** [comment]
Im 98% certain that this type of a unit just has one of the least tower-aggro priorities and its not a bug

**Comment by Avarise831** [comment]
> Im 98% certain that this type of a unit just has one of the least tower-aggro priorities and its not a bug

no way its broken
