### ISSUE TITLE
Faerie Fire bug

### ISSUE THREAD

**Issue by Zavadskiy-Kostya** [ValveSoftware/Dota2-Gameplay#12120]
### Item name

Faerie Fire

### Description

Buy two Faerie Fire and use both instantly. Faerie Fire will never recharge.

### Example Match ID and Timestamp

...

**Comment by saber-saber** [comment]
I had same issue with the lotus

**Comment by eugene-valve** [comment]
Thanks for reporting this! This should be fixed in an upcoming update.

**Comment by Avarise831** [comment]
> Thanks for reporting this! This should be fixed in an upcoming update.

Can you fix this old bug also please -  I can’t press Faerie Fire during "ALT  when I want to press Faerie Fire it says "No target" for example if uses mango no problem there
![212273662-1462b672-320d-4179-ba44-e6465bd736dd](https://github.com/ValveSoftware/Dota2-Gameplay/assets/37029303/4376dc6d-7f8a-487c-b1bc-25dc1718ba3f)
