### ISSUE TITLE
Lone Druid skill Fetch bugs Earth Spirit into an infinite roll

### ISSUE THREAD

**Issue by Korovjev** [ValveSoftware/Dota2-Gameplay#12135]
### Ability name

Fetch

### Description

When Lone Druid casts Fetch to Earth Spirit just before rolling takes place, then Earth Spirit is bugged into infinite rolling animation. So far only manta seems to end this infinite roll in one place. Earth Spirit can cast spells, but otherwise cannot move or do anything else.

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/145850516/d539878c-a868-42dc-b779-ed9497b5be4e)

### Example Match ID (and possibly Timestamp)

7348186855 - 24:45

**Comment by shaileshgarg** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/10651

**Comment by Korovjev** [comment]
Closing this issue because duplicate
