### ISSUE TITLE
Monkey King Aghanim's Scepter Bug

### ISSUE THREAD

**Issue by tinaungkhant** [ValveSoftware/Dota2-Gameplay#12150]
### Ability name

Wukong's Command Aghanim's Scepter Effect

### Description

I got video as proof.
Effect only trigger when Spell is in cooldown or not being available.
https://www.facebook.com/tinaung.khant.94/videos/184645371319712

### Example Match ID (and possibly Timestamp)

can test in demo

**Comment by shaileshgarg** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/12089

**Comment by powerofgreed** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/12064

**Comment by Chitnaymin** [comment]
right!

**Comment by khant-game-dev1437** [comment]
wew, right. unbelieveable what I am seeing! what just happened???
