### ISSUE TITLE
Bristleback's loadout displaying wrong ability for ability effect changing cosmetic

### ISSUE THREAD

**Issue by Alesksi** [ValveSoftware/Dota2-Gameplay#12179]
### Description

Going to Bristlebacks' loadout and selecting the _ability effects_ tab displays _hairball_ as the changing ability for a _warpath_ changing cosmetic item. The item's ability preview shows _warpath_ icon however. Haven't checked if there are similar cases with different heroes.

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/44261246/07f576f3-b735-4283-ad0d-5da751a4c172)

**Comment by shaileshgarg** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/11273

**Comment by vivi-lili** [comment]
Fix in next patch
