### ISSUE TITLE
Audio was just now broken on archlinux

### ISSUE THREAD

**Issue by DisplayTalk** [ValveSoftware/Dota2-Gameplay#12230]
### Description

I was playing right before the update with no problem. Now after the most recent update I can no longer play while simultaneously listening to music in firefox. Even just trying to test the same audio device dota is using(usb c to 3.5mm audio) crashes the kde plasma audio control panel. Running audio on this output before launching the game works but then = no sound in dota. Basically it seems dota can't share audio outputs with other applications any more.

**Comment by pleish** [comment]
Can confirm on Arch linux. No audio after recent update, Dota only.

**Comment by petry078** [comment]
Same thing on pop os.

**Comment by petry078** [comment]
Recent update from a minute ago fixed for me.

**Comment by Forage** [comment]
> Same thing on pop os.
> 
> Found this related issue, but no fix: #12233

Make sure you follow the link and apply the Flatpak method for a Flatpak install. This did the trick for me. By setting it to "pulse" despite a pipewire install, oddly enough.

**Comment by icculus** [comment]
Duplicate of https://github.com/ValveSoftware/Dota-2/issues/2491

**Comment by DisplayTalk** [comment]
Fixed for me now! Didn't have to apply any patch, last update has just fixed it, so I will close this. Thanks to the dota team at Valve!
