### ISSUE TITLE
Overwatch bug

### ISSUE THREAD

**Issue by Ezuq90** [ValveSoftware/Dota2-Gameplay#12244]
### Description

Cosmetics and items can't be seen in overwatch game.

### Screenshots

![resim](https://github.com/ValveSoftware/Dota2-Gameplay/assets/127225595/0fab44be-e03f-4218-9817-a7f6fc19ef98)
![resim](https://github.com/ValveSoftware/Dota2-Gameplay/assets/127225595/1b18f2f2-5f2c-45da-ac5d-fbbc7e64b0ff)
![resim](https://github.com/ValveSoftware/Dota2-Gameplay/assets/127225595/4ffe0e7d-ba89-495e-ab0a-5f058c3a2343)
![resim](https://github.com/ValveSoftware/Dota2-Gameplay/assets/127225595/91ab04cb-8b6d-421f-8eb1-e6950ad5d7b5)

**Comment by ShinigamiGamingInc** [comment]
Abilitys are also missing, over all everything that is temporary or an overlay is missing

**Comment by TobyFlendersonFromHR** [comment]
that is ok, nobody does overwatch anyways

**Comment by ShinigamiGamingInc** [comment]
> that is ok, nobody does overwatch anyways

It's ok, you don't have to comment or care, but please stop playing Dota.
