### ISSUE TITLE
Naga Siren's passive problem

### ISSUE THREAD

**Issue by SkadrirWhite** [ValveSoftware/Dota2-Gameplay#12242]
### Ability name

Rip Tide

### Description

At some point, illusions stop gaining stacks for Rip Tide.

### Example Match ID (and possibly Timestamp)

7354843098 - 19:05

**Comment by SPARR0W1** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/12234

**Comment by SPARR0W1** [comment]
This issue already out there
