### ISSUE TITLE
Replaying games before the Compendium update is bugged.

### ISSUE THREAD

**Issue by revdepign** [ValveSoftware/Dota2-Gameplay#12243]
### Description

All heroes have no cosmetics, no ability icons, and no items.

### Example Match ID (and possibly Timestamp)

7341448039

### Screenshots

![naked](https://github.com/ValveSoftware/Dota2-Gameplay/assets/143705201/a4f6cf21-d4d8-4e83-8d9d-81393d8173d6)

**Comment by Necrofastz** [comment]
Please fix this ASAP. Pros need to study replays of past ESL matches

**Comment by revdepign** [comment]
Can confirm the bug is fixed. Hope devs let bug reporters know.
