### ISSUE TITLE
All Hero challenge progress screen is missing from profile

### ISSUE THREAD

**Issue by DSDV** [ValveSoftware/Dota2-Gameplay#12264]
### Description

I like the new profile, 

but all customers lost the ability to see their all hero challenge progress.
there is currently no known way to access your all hero challenge

**Comment by shaileshgarg** [comment]
It is there
Profile -> History -> Hero Stats (Check the bottom)

**Comment by DSDV** [comment]
You are correct o.o 
that is hidden very good but its there <3 
thank you
