### ISSUE TITLE
Significant lags and freezes when Phantom Lancer is in-game at specific timings

### ISSUE THREAD

**Issue by wise-danya** [ValveSoftware/Dota2-Gameplay#12337]
### Description

Hello Dota 2 development team,

We've identified a specific scenario causing significant performance issues in patch `7.34c` during matches involving Phantom Lancer. At the 16+ minute mark, when Phantom Lancer reaches level 12 and possesses an Aghanim's Scepter, all players in the match experience substantial lags and freezes. This issue becomes especially prominent during team fights, severely affecting the gaming experience. Furthermore, the problem persists and doesn't resolve even after restarting the game.

#### Steps to reproduce:

Start a game with Phantom Lancer as one of the heroes.
Ensure Phantom Lancer obtains an Aghanim's Scepter.
Play until Phantom Lancer reaches level 12.
Continue the game until the 16-minute mark.
Observe significant lags and freezes affecting all players in the match.

#### Expected behaviour:
Gameplay should remain smooth and uninterrupted regardless of the heroes, their levels, items, or match timings.

#### Actual behaviour:
When Phantom Lancer reaches level 12 with an Aghanim's Scepter at the 16-minute mark, all players experience severe lags and freezes.

Thank you for your attention to this matter.

### Example Match ID (and possibly Timestamp)

7356100800 - 16:38
https://www.twitch.tv/videos/1937282099?t=6h6m20s

7357568811 - 17:30
https://www.twitch.tv/videos/1938191621?t=3h25m

### Screenshots and GIFs

https://github.com/ValveSoftware/Dota2-Gameplay/assets/12139489/708a16e5-cf55-4423-988b-f7f14a3e50a8

https://github.com/ValveSoftware/Dota2-Gameplay/assets/12139489/fa513741-cbaf-417a-9fed-cfa565e86cc2

**Comment by TpsArchyy** [comment]
same thing happens when you are in a match against or with Broodmother as of late, chaos knight with sceptre upgrade and spectre with sceptre upgrade.  

In the match with broodmother (ID: 7357442831) it got so bad at a point that we were not able to play the game if broodmother was alive and spawning / having broodlings.  
If you think is our pc's fault Evilu (spirit breaker) has 13700k cpu and 4070ti gpu and it got to a point when even on that fucking machine he was now able to control his hero during teamfights.

**Comment by Doomblaze** [comment]
Same thing just happened to me. Felt like the PL was doing something intentionally to make the game lag, but it might have just been a byproduct of the patch. Everyone in the game was getting severe stutters after the PL had aghs.

Match id 7358050819

**Comment by wide-danya** [comment]
@TpsArchyy, @Doomblaze, and others facing the same issue, please give a thumbs-up vote. As they've mentioned:
`Community voting is effective! Thank you!`

**Comment by TpsArchyy** [comment]
Hopefully someone working at valve will see this and atleast admitt they have issues and give us a timeframe for the fix... They fixed these issues for like 2 weeks then another 500 mb patch was released and they were back... i think they made a rollback on their patch.

**Comment by pobrohlman** [comment]
Affected last night in match 7362774054

**Comment by bassdweller** [comment]
Can confirm issue is still present even in lobby matches with PL and other illusion heroes. Severe stuttering and input lag, game was essentially unplayable once PL hit level 6.

**Comment by TpsArchyy** [comment]
heroes that have the same issue:
- Spectre with aghanim scepter upgrade
- Chaos Knight with aghanim sceptre upgrade
- Naga siren
- Broodmother after level 6

**Comment by T666M** [comment]
Can confirm massive lags with hero like Phantom Lancer. Match number: 7370780287

**Comment by wise-danya** [comment]
Hey guys 👋 

I'll close this one. 
It seems the problem is no longer relevant and it was most likely due to the high load on the servers.
