### ISSUE TITLE
Dying with a Gem in Chronosphere permanently disables the activated ability

### ISSUE THREAD

**Issue by AbyssalD2** [ValveSoftware/Dota2-Gameplay#12362]
### Item name

Gem of True Sight

### Description

- If a hero is carrying a gem and dies inside a chronosphere, the gem's activated ability will not cool down after being picked up again.
The only way to reset the ability cool-down is now a refresher orb. lol

### Example Match ID and Timestamp

NaN

**Comment by Avarise831** [comment]
#8773

**Comment by Nathanael-Valve** [comment]
Fixed in next update.
