### ISSUE TITLE
Clockwerk's Hookshot + Q W combo causes the game to crash

### ISSUE THREAD

**Issue by milan-sedivy** [ValveSoftware/Dota2-Gameplay#12371]
### Ability name

Hookshot

### Description

Played a game where the game crashed twice after performing a Hookshot and following up with Q W. After checking reddit I noticed that I'm not the only one noticing this. 

### Example Match ID (and possibly Timestamp)

7358980936

**Comment by imfinethnku** [comment]
that's the issue with cogs, had the same problem with 3 matches in a row. 2 Times the game crashed for everyone, and once only for the opponents

**Comment by milan-sedivy** [comment]
> that's the issue with cogs, had the same problem with 3 matches in a row. 2 Times the game crashed for everyone, and once only for the opponents

At least it is confirmed, is there an existing issue so that I can close this one as a duplicate?

**Comment by Avarise831** [comment]
#12265

**Comment by milan-sedivy** [comment]
Closing as a duplicate
