### ISSUE TITLE
NEW UPDATE CAUSES KEYBIND ISSUES

### ISSUE THREAD

**Issue by zhengningg** [ValveSoftware/Dota2-Gameplay#12379]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/zhengningg/20529243eb721414088ca104c8e833a6
 
* Have you checked for system updates?: [**Yes**/No]
* Are you using the latest stable video driver available for your system? [**Yes**/No]
* Have you verified the game files?: [**Yes**/No]

#### Please describe your issue in as much detail as possible: 
New update causes keybind issues. Each individual keybind should bind to the illusion/unit i have set. But it controls all the unit after summoning the illusion(after using the **Q** spells 2-3 times) please fix this man.
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

#### Steps for reproducing this issue:

1. Use any illusion hero naga/tb/pl 
2. Take naga for fast results. max level and get the items octarine core, manta ,spell prism 
3. After spawning the illusions for 2-3 times (using the **Q** spells 2-3 times) the keybind all got fked and messed up.  1 keybind = control all illusion instead of the specific ones.

**Comment by yarsammm** [comment]
the same

**Comment by rektaexpress** [comment]
same happened. I can replicate this on demo mode. Whenever you level up the skill. It forgets your keybinds. Frustrating.

**Comment by kagurakaratachi777** [comment]
same
