### ISSUE TITLE
Lol Valve, you did patch, and did not fix MAIN bug - broken binds :) Anyone can't play with heroes which has illusion or multiple units. Thanks for your service

### ISSUE THREAD

**Issue by kagurakaratachi777** [ValveSoftware/Dota2-Gameplay#12375]
## Ability name

Mirror image

### Description

Still can't play with naga.
I have binds for each illussion from Mirror Image and Manta Style.

**WHEN I USE MY BINDS, IT'S MIXING.** DON'T WORK PROPERLY.

When i use bind for 1 illusion, it selects 2 illusions. Why? what a ......??

I didn't play dota 3-days because of this issue. Maybe you pay attention for that, it's not a little issue. IT BROKES ENTIRE HERO. NOONE PLAY NAGA NOW, you can check it on twitch))

I counted the opened issues related to "binds" for the last 3 days, it's 12 and now new patch with no fix, one more thanks a lot for your service, **AND IT IS BEST COMPENDIUM EVER, WITH BEST BUGS**

I did your work and collected each issue related to this:
1. #12240 
2. #12255 
3. #12270 
4. #12278 
5. #12280 
6. #12310 
7. #12322 
8. #12329 
9. #12331 
10. #12340 
11. #12361 
12. #12364 

i'm done, you're broking my game and soul
guys, naga-players maybe help to thumbs up this topic? we can do this, guys come on, i need your help, Naga need your help

### Example Match ID (and possibly Timestamp)

7355664086

**Comment by 0xB455** [comment]
yes... it is super annoying :(

**Comment by NothingToLoseme** [comment]
Bug's with illusion with Terrorblade too. When you pressed manta you can't find next unit , cuz manta illusions going crazy, and your binds going crazy as well. Sometimes that's bug comes without manta, and my illusions works like clowns :)
About naga funny moment that after you pressing Manta and then you press first skill your illusions from manta just instantly destroyed :) Funny one.

**Comment by zhengningg** [comment]
+1 indeed please fix this shit man jesus

**Comment by yhunahran** [comment]
+ 1. 3 days not playing dota

**Comment by yarsammm** [comment]
+

**Comment by padalshchik** [comment]
VALVE FIX PLS!!!

**Comment by yoyoinneverland** [comment]
Valve, please. This is a big bug,

**Comment by canofwhoopas** [comment]
unplayable

**Comment by bensinkek** [comment]
I encountered this bug as well on Naga Siren. After some testing, the bug happens when the hero or illusions dies, if the illusions timer expire normally, it doesn't happen. It can happen with Illusion from Mirror Image skill and Manta (haven't tested illusion from rune) . I also tested Phantom Lancer and Chaos Knight. They can get affected too.

**Comment by m13253** [comment]
Valve, pls fix!

**Comment by m13253** [comment]
The bug seems to get fixed as of 2023-10-03T21:47:00Z.

**Comment by B1st777** [comment]
> Valve, pls fix!

Dude, they already fixed it

**Comment by m13253** [comment]
> Dude, they already fixed it

Not until last hour.

**Comment by B1st777** [comment]
> > Dude, they already fixed it
> 
> Not until a few minutes ago.

![Screenshot_2023-10-04-00-50-59-642_com.github.android.jpg](https://github.com/ValveSoftware/Dota2-Gameplay/assets/146597513/22a2f8d1-6187-4a6e-a703-b2198f5c43fd)

**Comment by yoyoinneverland** [comment]
It's fixed now? Awesome, thank you guys.
