### ISSUE TITLE
Game crashed due to Primal Roar

### ISSUE THREAD

**Issue by Karn4132** [ValveSoftware/Dota2-Gameplay#12391]
### Ability name

Primal Roar

### Description

Beastmaster casted Primal Roar, then the game crashed

https://github.com/ValveSoftware/Dota2-Gameplay/assets/128893391/2ccbf197-b421-4056-8177-5d0a17fe4f38

### Example Match ID (and possibly Timestamp)

7357197713 - 32:15

**Comment by TobyFlendersonFromHR** [comment]
i think the roar was too loud and caused an audio glitch which resulted in the crash for all 10 players, it is happening in other matches too, including pro matches
