### ISSUE TITLE
Can't open console

### ISSUE THREAD

**Issue by VetaLioSTV** [ValveSoftware/Dota2-Gameplay#12403]
### Description

Hello, from latest updates ( i guess august 2023 ~~), i dont know what excatly happened, but i can't open console anyhow.

Tried a lot of things, like - 

- Added `-console` in properties of Dota at steam library (with disabled checkmark `Enable console` in game settings)
- (vice versa) Added check mark `Enable console` in game settings and removed `-console` tag in properties 
- Added `con_enable 1` on **_config.cfg_** in **steam>steam app>common>dota2beta>Dota>cfg folder**

And still nothing. It's just not want to open.... 

Any ideas \ suggestions please?

My current startup params (maybe problem has reference with it? Since some of them are depricated i guess) - 
`-novid -noforcemaccel -noforcemspd -dx11 -nofocus -novr -nohltv -nojoy -usetcp -uselocalweb -disablehangwatchdog -console -condebug -conclearlog -swap_chain_as_is`

**Comment by SpiritWinD86** [comment]
you can try a few more things:
 - verify integrity of game files in steam, 
 - try to rebind a hotkey in the game settings (hotkeys->to advanced hotkeys->interface->console).
 - try to open file "machine_convars.vcfg" in the game folder (path - .../Steam/steamapps/common/dota 2 beta/game/dota/cfg/machine_convars.vcfg), look there for "panorama_console_position_and_size" and change value to "20.00|20.00|1000.00|800.00" , save changes  and try to launch the game.

**Comment by VetaLioSTV** [comment]
> you can try a few more things:
> 
> * verify integrity of game files in steam,
> * try to rebind a hotkey in the game settings (hotkeys->to advanced hotkeys->interface->console).
> * try to open file "machine_convars.vcfg" in the game folder (path - .../Steam/steamapps/common/dota 2 beta/game/dota/cfg/machine_convars.vcfg), look there for "panorama_console_position_and_size" and change value to "20.00|20.00|1000.00|800.00" , save changes  and try to launch the game.

Hello!

Thanks for your fast reply.

I forgot to mention that i already tried it (with combinations of first two notes as described on my initial post) 
> try to rebind a hotkey in the game settings (hotkeys->to advanced hotkeys->interface->console).

Then i made change as you described in last note and it worked,lol. For some reason i had such values - 
> "panorama_console_position_and_size"		> "340282346638528859811704183484516925440.00|340282346638528859811704183484516925440.00|1000.00|800.00"

Can you explain what excatly happened and why it didn't work before? I guess it has reference when you're changing resolution, something happens under the hood which brokes console layout size?

**Comment by SpiritWinD86** [comment]
> Thanks for your fast reply.
> 
> I forgot to mention that i already tried it (with combinations of first two notes as described on my initial post) , plus also i tried to rebind to another hotkey
> 
> > try to rebind a hotkey in the game settings (hotkeys->to advanced hotkeys->interface->console).
> 
> Then i made change as you described in last note and it worked,lol. For some reason i had such values -
> 
> > "panorama_console_position_and_size"		> "340282346638528859811704183484516925440.00|340282346638528859811704183484516925440.00|1000.00|800.00"
> 
> Can you explain what excatly happened and why it didn't work before? I guess it has reference when you're changing resolution, something happens under the hood which brokes console layout size?
> 
> PS Also, i want to mention that when i tried to "open" console at game, i randomly pushed some combinations of hotkeys, like SHIFT + ` (my default button for console) and sometimes i saw at right corner (bottom) a drop down list with possible values(like a hint, when you write something in console and it shows possible results, like auto generated). So definitely it has something with layout and out of bounds location or something similiar :)


you are right, the console worked, just the window was outside of the screen. 
these values are position of the console window in pixels. this is an old bug of source games. it may appear when changing the screen resolution in the settings or changing from window mode from borderless to fullscreen mode, especially if there are several monitors, or mb something else, i'm not sure.
well, if you reproduce this bug in the future, you'll know what to do. ;)

**Comment by VetaLioSTV** [comment]
> you are right, the console worked, just the window was outside of the screen.
> these values are position of the console window in pixels. this is an old bug of source games. it may appear when changing the screen resolution in the settings or changing window mode from borderless to fullscreen mode (or vice versa), especially if there are several monitors, or mb something else, i'm not sure.
> well, if you reproduce this bug in the future, you'll know what to do. ;)

Yeah, excatly.. I changed resolution / window type (full screen / borderless and etc) at that time too frequently, plus i have added second monitor, so i guess it has reference on it.

Many thanks!
