### ISSUE TITLE
fuck your single draft after 4 imbecil morons in team

### ISSUE THREAD

**Issue by NeomMael** [ValveSoftware/Dota2-Gameplay#12427]
### Description

what else just destroy items after so many games only fucking noobs

**Comment by TobyFlendersonFromHR** [comment]
have fun in low prio, you deserve it

**Comment by NeomMael** [comment]
my stalker answer me You're all anti-social IDIOTS

**Comment by NeomMael** [comment]
match id: 7362033734 witch doctor grief pro master
with shit profilpicture retard
