### ISSUE TITLE
Control Groups is stateless - Hero Naga Siren

### ISSUE THREAD

**Issue by AndyRand** [ValveSoftware/Dota2-Gameplay#12434]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
Computer Information:
Manufacturer: Gigabyte Technology Co., Ltd.
Model: B560M DS3H V2
Form Factor: Desktop
No Touch Input Detected
Processor Information:
CPU Vendor: GenuineIntel
CPU Brand: Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz
CPU Family: 0x6
CPU Model: 0xa5
CPU Stepping: 0x5
CPU Type: 0x0
Speed: 2904 MHz
16 logical processors
8 physical processors
Hyper-threading: Supported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Unsupported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Supported
AVX2: Supported
AVX512F: Unsupported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Unsupported
AVX512VNNI: Unsupported
SHA: Unsupported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported
Operating System Version:
Windows 11 (64 bit)
NTFS: Supported
Crypto Provider Codes: Supported 311 0x0 0x0 0x0
Video Card:
Driver: NVIDIA GeForce RTX 3080
DirectX Driver Name: nvldumd.dll
Driver Version: 31.0.15.3129
DirectX Driver Version: 31.0.15.3129
Driver Date: 3 8 2023
OpenGL Version: 4.6
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 60 Hz
DirectX Card: NVIDIA GeForce RTX 3080
VendorID: 0x10de
DeviceID: 0x2216
Revision: 0xa1
Number of Monitors: 1
Number of Logical Video Cards: 1
No SLI or Crossfire Detected
Primary Display Resolution: 2560 x 1440
Desktop Resolution: 2560 x 1440
Primary Display Size: 23.50" x 13.23" (26.97" diag), 59.7cm x 33.6cm (68.5cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 10239 MB
Supported MSAA Modes: 2x 4x 8x
Sound card:
Audio device: Haut-parleurs (Realtek(R) Audio
Memory:
RAM: 32637 Mb
VR Hardware:
VR Headset: None detected
Miscellaneous:
UI Language: English
Media Type: Undetermined
Total Hard Disk Space Available: 2860844 MB
Largest Free Hard Disk Block: 1843157 MB
OS Install Date: nov. 01 2022
Game Controller: None detected
MAC Address hash: f11ae370926230b49719217d3feadea36be5b019
Storage:
Disk serial number hash: dccd148
Number of SSDs: 1
SSD sizes: 1000G
Number of HDDs: 1
HDD sizes: 2000G
Number of removable drives: 0

* Have you checked for system updates?: [Yes/No]
Yes

* Are you using the latest stable video driver available for your system? [Yes/No]
Yes

* Have you verified the game files?: [Yes/No]
Yes

#### Please describe your issue in as much detail as possible:
When playing Naga Siren, I lost my control group configuration. I retried to re-configure my control groups during Demo Hero, sometimes it works but sometimes after a while (maybe some levels), the same control group selects randomly my illusions and is really frustrating during games. Everytime I spawn illusions, I have to re-configure the control groups and waste time not farming. Please help.

#### Steps for reproducing this issue:

1. Pick Naga Siren
2. Configure a custom advanced control group
3. Use manta and illu
4. The selection is wrong while using the assigned group
![steamuserimages-a akamaihd](https://github.com/ValveSoftware/Dota-2/assets/38816092/50c2e08a-f0ca-4509-8528-46c5006be3c8)

**Comment by bensinkek** [comment]
I encountered this bug as well on Naga Siren. After some testing, the bug happens when the hero or illusions dies, if the illusions timer expire normally, it doesn't happen. It can happen with Illusion from Mirror Image skill and Manta (haven't tested illusion from rune) . I also tested Phantom Lancer and Chaos Knight. They can get affected too.

**Comment by jeffhill** [comment]
The update which just shipped contains a number of fixes to the behavior of illusions, control groups, and tab selection which should fix what you're reporting.

Thanks for the bug report, and thank you for the detailed repro steps!

**Comment by AndyRand** [comment]
Bug Fixed! Thank you

**Comment by m13253** [comment]
> The update which just shipped contains a number of fixes to the behavior of illusions, control groups, and tab selection which should fix what you're reporting.
> 
> Thanks for the bug report, and thank you for the detailed repro steps!

As of 2023-10-22, it seems the control group bug is still not fully fixed.
I can confirm it is still reproducible with a Meepo match.

The only difference is: it’s no longer 100% reproducible, maybe only 50% games you have the bug.
When the bug occurs, the behavior is the same.

**Comment by LoliPain** [comment]
> Bug Fixed! Thank you

Terrorblade's conjure image groups are still bugged 
https://github.com/ValveSoftware/Dota2-Gameplay/issues/12853
