### ISSUE TITLE
[Controller] Can anyone play with the gamepad? Controller seems to be broken since last week.

### ISSUE THREAD

**Issue by ice-blaze** [ValveSoftware/Dota2-Gameplay#12444]
### Description

Since last week I can't use the xbox one controller anymore. Any one experience the same issue?

(I'm using windows 10)

**Comment by jeffhill** [comment]
Try adding "+dota_disable_controller_support 0" to the command line. We had to default controller support off while we're debugging a problem with some players getting controller support enabled undesirably.

**Comment by ice-blaze** [comment]
@jeffhill I can confirm now I can move the character but there is still a big issue, the camera goes directly to the top of the map. 

I tried to disabled steam input but didn't change anything and also to install the xbox extended feature support driver.

(extra curious question: are there a lot of gamepad player? I have the feeling I'm the only one x))

**Comment by ice-blaze** [comment]
If I keep right joystick pressed I can kind of play. But once released, the camera slide to the top of the map.

**Comment by ice-blaze** [comment]
I have oponned another github issue which is more accurate #12623 Since I'm not convinced about this bug tracker and if issues are really tracked I create this other issue.

**Comment by ayellaz** [comment]
Yeah, I’ve been trying to figure it out for a week, and I’ve encountered the same issue.

**Comment by Alex-Kizilov** [comment]
It don't work now. Gaben, pls fix

**Comment by ice-blaze** [comment]
Dunno why I closed this one. My bad, I reopen the issue.

**Comment by mirddes** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/27564
