### ISSUE TITLE
AFK leave without any reason 

### ISSUE THREAD

**Issue by BogdanVolna** [ValveSoftware/Dota2-Gameplay#12447]
### Description

Unexpected afk leave on 48:36 without any reason for active player (no any suspect actions, afk at base or something). We just gathered for final push.

### Example Match ID (and possibly Timestamp)

ID: 7362376643 Timestamp: 48:36 PlayerID: 105161601

### Screenshots

<img width="2056" alt="Screenshot 2023-10-02 at 22 01 12" src="https://github.com/ValveSoftware/Dota2-Gameplay/assets/23221619/be3e7548-65e9-4ae0-a97c-3da16cbaf437">

**Comment by TobyFlendersonFromHR** [comment]
I just watched it, the reason was because the cm ran around the base for 5 minutes, you absolute moron.
