### ISSUE TITLE
go uninstall dota

### ISSUE THREAD

**Issue by NeomMael** [ValveSoftware/Dota2-Gameplay#12445]
### Description

shit noobs toxic stalkers and ruiners in all my games
dexter stalker ursa my lane and ruin my game typical russian authist

### Example Match ID (and possibly Timestamp)

give me more shit noobbs i love it

### Screenshots

![anforderungen](https://github.com/ValveSoftware/Dota2-Gameplay/assets/145142730/3b39f926-fcc7-4450-bdc3-e861b06c45c4)
![anforderungen](https://github.com/ValveSoftware/Dota2-Gameplay/assets/145142730/3d1ea497-0eb9-4bd4-87d9-e395b5cab64f)

**Comment by NeomMael** [comment]
give me more shit ruiner i love your matchmaking lose every game cause 4 random noobs in my teams! games are disaster i love it give me more imbecil handicapped braindead cancer i love it! next level .!. !!!!

**Comment by NeomMael** [comment]
give me all the noobs cause i have 13000 games i should literally play together with immortals but valve gives me shit ruiner heralds hahahahahahahahhahahahahahahhahahahahhaha i love it give me more valve give me more and more of these shit games i have so much fun play games like these! i love watching shit noobs and narzist players narzissm trash authis players stalks me and think they harming my games! hahahahaha give me more of that imbecil handicapped mates more and more never stop ok! i love it! all toxic shit i love it! more toxic noobs please please pease

**Comment by NeomMael** [comment]
You're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTS

**Comment by Jimmy9877** [comment]
Dota2 is a team game teammates do matter but your mental health too, consider taking a break and playing again when you're more happy you know this way you won't drag your teammates down (mentally).

**Comment by TobyFlendersonFromHR** [comment]
13000 games and still in archon bracket? lol what a joke, you don't deserve to be anywhere near any immortal players.

**Comment by nikohd12** [comment]
Haha 13k games as an archon. A true divine player can even climb you up to ancient EASILY playing OFFLANE or SUPPORT. Go practice and get gud bro.
