### ISSUE TITLE
teammates wants me to destroy my items

### ISSUE THREAD

**Issue by NeomMael** [ValveSoftware/Dota2-Gameplay#12466]
### Description

all grief afk bothering ruining lane leave lane come and stalking ghosting me and then not destroy items? what you do fight for, if you like only def , then without me! 

### Screenshots

![aaa](https://github.com/ValveSoftware/Dota2-Gameplay/assets/145142730/3dc6cb07-c1f5-4461-a84a-be0ab0d95a32)
![bbb](https://github.com/ValveSoftware/Dota2-Gameplay/assets/145142730/a7fe5e72-8e07-476a-8a23-2011c7b0a16f)

**Comment by NeomMael** [comment]
![aaa](https://github.com/ValveSoftware/Dota2-Gameplay/assets/145142730/e008f50d-3edc-4c6f-908b-6be6db016c5f)

**Comment by NeomMael** [comment]
very good carry player hahahahaha You're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTS

**Comment by NeomMael** [comment]
without plan valve you build a shit matchmaking really fix this shit!

**Comment by NeomMael** [comment]
i can not stand these anti-social IDIOTS anymore, braindead cancer's in my games over and over again! give me more of these shit players! and oponents with vac banns give more of these dirt games! i love it! i love it so much!

**Comment by TobyFlendersonFromHR** [comment]
your dota skills are on the same level as your writing skills, both herald level stuff. Nobody can even understand what you are trying to say. I feel bad for your teammates who have to try and decipher your ramblings. A 5 year old can write more understandable sentences.

**Comment by Endeavour18** [comment]
Dude this is a bug report forum, not a wall that you can talk to

**Comment by NeomMael** [comment]
sure toby the 5 years kids in my games and beeing trash play ok ok ok
