### ISSUE TITLE
toxic ruiner come to my lane and wants ruin my game 

### ISSUE THREAD

**Issue by NeomMael** [ValveSoftware/Dota2-Gameplay#12465]
### Description

bann him for stalking and bothering me he played slark and ruined all the game from the team! bann him for destruptive dirt toxic behaviour and manners! he actually the most egoist scumback ever! bann the low shit!

### Screenshots

![anforderungen](https://github.com/ValveSoftware/Dota2-Gameplay/assets/145142730/e001edaf-1707-4e8e-a1c3-6baf3edd7f80)

**Comment by NeomMael** [comment]
steam id: 1476050199 game ruiner account moron needs low prioty and bann

**Comment by NeomMael** [comment]
he sabotage games must bann him

**Comment by NeomMael** [comment]
![anforderungen](https://github.com/ValveSoftware/Dota2-Gameplay/assets/145142730/971f18ba-ec51-4e16-93dd-1879453f3f04)

**Comment by NeomMael** [comment]
and the authist slark support this cheater! so they want us make dumb! this steam id: 306557354 vac bann with cheats allowed to play games! and the steam id : 1476050199 support him! bann both for abuse matchmaking!

**Comment by NeomMael** [comment]
great community valve good matches valve give me more i love it valve give me more of this please! it makes me stronger give me all the dirt shit show! i cant get enough of that! give me more shit in game! give everything what you have cheat players and noobs give me all! 
You're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTS

**Comment by NeomMael** [comment]
steam id: 1476050199  nice vac bann moron support other vac bann account steam id: 306557354 
wow what for dota scumbacks exist
You're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTS
give more of this valve give me more of this more and more! dont stop give me dirt games! makes me stronger give me more of this please! every time when i play dota i must have anti-social IDIOTS in matches more more and more and again more and more valve please

**Comment by NeomMael** [comment]
another idiot
![Uploading anforderungen.PNG…]()

**Comment by NeomMael** [comment]
another toxic idiot
![anforderungen](https://github.com/ValveSoftware/Dota2-Gameplay/assets/145142730/2df17d52-15d4-4fcf-95f8-2ec36e42386c)

**Comment by keithn** [comment]
this is for reporting bugs, the game has inbuilt mechanisms for reporting people and avoiding people

**Comment by SolarPhoenix** [comment]
Found another toxic person, valve should bann
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/26413994/09477770-7be4-40a5-80d2-02de4d8acdd6)
They destroyed their items. 
You're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTSYou're all anti-social IDIOTS

**Comment by NeomMael** [comment]
when your trash team wants that then they become that! easy going not?

**Comment by SolarPhoenix** [comment]
Looks like this issue should be marked as fixed then! Ty for the fun NeomMael

**Comment by Jimmy9877** [comment]
I agree with SolarPhoenix
