### ISSUE TITLE
Kunkka torrent stuns through BKB

### ISSUE THREAD

**Issue by roman-vygon** [ValveSoftware/Dota2-Gameplay#12473]
### Ability name

Torrent Storm

### Description

Anti-mage presses BKB then get's stunned by torrent.
Timestamp: 65:17

https://github.com/ValveSoftware/Dota2-Gameplay/assets/48095750/49303585-86ae-4c21-8278-baed7262fe8d

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/48095750/e6d2bf04-8602-43f4-ab01-93aa2cfe0e53)

### Example Match ID (and possibly Timestamp)

7362131768

**Comment by eugene-valve** [comment]
Thanks for reporting this, it should be fixed in an upcoming update!
