### ISSUE TITLE
KAYA and it's descendants spell amplification does not work with techies spells

### ISSUE THREAD

**Issue by Nallefjant** [ValveSoftware/Dota2-Gameplay#12474]
### Item name

KAYA and it's descendants

### Description

KAYA and it's descendants spell amplification does not work with techies spells

### Example Match ID and Timestamp

Tested in demo

**Comment by TheZett** [comment]
It works on all his spells, except for the ultimate mine.

Since the ultimate has the mine itself as the damage source, thus damage also gets reflected back to the mine and not to techies, it is intended that spell amp does not work on his ultimate mine.

**Comment by Nallefjant** [comment]
> It works on all his spells, except for the ultimate mine.
> 
> Since the ultimate has the mine itself as the damage source, thus damage also gets reflected back to the mine and not to techies, it is intended that spell amp does not work on his ultimate mine.

Then how do you explain that KAYA does not work for his Q and E?

**Comment by BlueMageBrilly** [comment]
Tested it using the Dummy Target and Kaya works fine on both his Q and E. His W, with shard, is harder to properly test, but should work as well. 

Max Sticky without Kaya does 240 - Kaya does 259.20 - Ethereal 268 - Kaya + Sange/Yasha 278.40. 

Not going to bother giving numbers for the others, but this is working as intended. Be sure to use the Dummy!

**Comment by Nallefjant** [comment]
Funny, today when I tested I didn't get the problem.
