### ISSUE TITLE
Dota Plus Required? 

### ISSUE THREAD

**Issue by Hawski** [ValveSoftware/Dota2-Gameplay#12488]
### Description

I just logon (from steam to Dota 2).
Pressed play and join a game.

And now I can't play (time out).

### Screenshots

![20231003212819_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/69961102/802a5137-a769-47b7-b6a6-bbadfd803ec7)
![20231003212826_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/69961102/a0569278-c84a-4986-b32f-335630ca531d)
![20231003212704_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/69961102/ccef505d-56b5-4928-9094-09c358053c36)
![20231003213830_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/69961102/1fbdbd12-2573-4af5-bdab-f898d318fe89)

**Comment by Hawski** [comment]
PS: "Help Me" and "123123131" was me who typed

**Comment by LokeLok** [comment]
You need to change it to either Attributes or Custom Layout.

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/106764092/6e367645-2a6e-4b5c-a3a4-9a2eab91f493)

**Comment by Hawski** [comment]
how do I do that?

**Comment by LokeLok** [comment]
See the red box in the picture I posted? Click it and choose attributes. You can do this in the Heroes section in the Main Menu.

**Comment by Hawski** [comment]
Thank you
