### ISSUE TITLE
muerta + grimstroke vs. lone druid crash

### ISSUE THREAD

**Issue by lolkaspy** [ValveSoftware/Dota2-Gameplay#12524]
### Ability name

Parting shot

### Description

this skill crashing the game, if grimstroke binds the bear and the hero, every player can't reconnect to the game

### Example Match ID (and possibly Timestamp)

Game statistics are not specified

**Comment by lolkaspy** [comment]
still works in 7.34d

**Comment by BradMuir** [comment]
this should be fixed in the next update 🐻
