### ISSUE TITLE
Dota2 segfaulting upon startup   Ubuntu 22.03

### ISSUE THREAD

**Issue by dotaplayer42069** [ValveSoftware/Dota2-Gameplay#12536]
### Description

Hi, the latest patch as of October 5th 2023 has caused Dota2 to segfault upon startup running the latest updated Ubuntu 22.03

Notes:
-   Have done apt-update/apt-upgrade
-   Verified dota2 game files via steam client
-   No custom launch options
-   Steam client is up-to-date

crash dump:  
[crash_20231005231523_2_omitted.txt](https://github.com/ValveSoftware/Dota2-Gameplay/files/12819479/crash_20231005231523_2_omitted.txt)

Heres the logs from the terminal after trying to start dota2:

/bin/sh\0-c\0/home/USER/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=570 -- /home/USER/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/USER/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper'/_v2-entry-point --verb=waitforexitandrun --  '/home/USER/.local/share/Steam/steamapps/common/dota 2 beta/game/dota.sh' +@panorama_min_comp_layer_dimension 0 -prewarm_panorama +dota_disable_controller_support 1\0
chdir "/home/USER/.local/share/Steam/steamapps/common/dota 2 beta"
ERROR: ld.so: object '/home/USER/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/USER/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/USER/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/USER/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/USER/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 2999 != 2998, skipping destruction (fork without exec?)
pid 3000 != 2998, skipping destruction (fork without exec?)
Loaded /home/USER/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so, got 0x55a9d2bf92c0
Using breakpad crash handler
[S_API] SteamAPI_Init(): Loaded '/home/USER/.local/share/Steam/linux64/steamclient.so' OK.
Setting breakpad minidump AppID = 570
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
10/05 23:15:22 Init: Installing breakpad exception handler for appid(570)/version(8394495)/tid(3002)
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  42069 [API loaded yes]
SteamInternal_SetMinidumpSteamID:  Setting Steam ID:  42069
Setting breakpad minidump AppID = 373300
Loaded libSDL3.so.0, got 0x55a9d2e99eb0
Loaded /home/USER/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libtier0.so, got 0x55a9d2be29a0
Loaded /home/USER/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libfilesystem_stdio.so, got 0x55a9d2eb02b0
Loaded /home/USER/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libinputsystem.so, got 0x55a9d2eb0f90
Loaded /home/USER/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/liblocalize.so, got 0x55a9d2f1b7f0
Loaded /home/USER/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/librendersystemvulkan.so, got 0x55a9d2f090e0
Loaded /home/USER/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libresourcesystem.so, got 0x55a9d2f1df90
Loaded /home/USER/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libschemasystem.so, got 0x55a9d2f155d0
Fossilize INFO: Overriding serialization path: "/home/USER/.local/share/Steam/steamapps/shadercache/570/fozpipelinesv6/steamapprun_pipeline_cache".
Fontconfig error: Cannot load default config file

(process:3002): GLib-GObject-WARNING **: 23:15:23.201: specified class size for type 'PangoCairoFcFont' is smaller than the parent type's 'PangoFcFont' class size

(process:3002): GLib-GObject-CRITICAL **: 23:15:23.201: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed

(process:3002): GLib-CRITICAL **: 23:15:23.201: g_once_init_leave: assertion 'result != 0' failed

(process:3002): GLib-GObject-CRITICAL **: 23:15:23.201: g_object_new_valist: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
crash_20231005231523_2.dmp[3030]: Uploading dump (out-of-process)
/tmp/dumps/crash_20231005231523_2.dmp
/home/USER/.local/share/Steam/steamapps/common/dota 2 beta/game/dota.sh: line 117:  3002 Segmentation fault      (core dumped) ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
crash_20231005231523_2.dmp[3030]: Finished uploading minidump (out-of-process): success = yes
crash_20231005231523_2.dmp[3030]: response: CrashID=bp-528d44e4-2701-491a-8441-7848d2231005
crash_20231005231523_2.dmp[3030]: file ''/tmp/dumps/crash_20231005231523_2.dmp'', upload yes: ''CrashID=bp-528d44e4-2701-491a-8441-7848d2231005''
pid 3030 != 3029, skipping destruction (fork without exec?)
Game 570 created interface STEAMAPPLIST_INTERFACE_VERSION001 / 
Game 570 created interface STEAMAPPS_INTERFACE_VERSION008 / 
Game 570 created interface STEAMHTMLSURFACE_INTERFACE_VERSION_005 / 
Game 570 created interface STEAMHTTP_INTERFACE_VERSION003 / 
Game 570 created interface STEAMINVENTORY_INTERFACE_V003 / 
Game 570 created interface STEAMMUSICREMOTE_INTERFACE_VERSION001 / 
Game 570 created interface STEAMMUSIC_INTERFACE_VERSION001 / 
Game 570 created interface STEAMPARENTALSETTINGS_INTERFACE_VERSION001 / 
Game 570 created interface STEAMREMOTESTORAGE_INTERFACE_VERSION016 / 
Game 570 created interface STEAMSCREENSHOTS_INTERFACE_VERSION003 / 
Game 570 created interface STEAMUGC_INTERFACE_VERSION018 / 
Game 570 created interface STEAMUSERSTATS_INTERFACE_VERSION012 / 
Game 570 created interface STEAMVIDEO_INTERFACE_V003 / 
Game 570 created interface SteamController008 / 
Game 570 created interface SteamFriends017 / 
Game 570 created interface SteamInput006 / 
Game 570 created interface SteamMatchGameSearch001 / 
Game 570 created interface SteamMatchMaking009 / 
Game 570 created interface SteamMatchMakingServers002 / 
Game 570 created interface SteamNetworking006 / 
Game 570 created interface SteamUser023 / 
Game 570 created interface SteamUser023 / User
Game 570 created interface SteamUtils010 / 
Game 570 method call count for IClientAppManager::GetCurrentLanguage : 1
Game 570 method call count for IClientAppManager::GetAppStateInfo : 1
Game 570 method call count for IClientUtils::RecordSteamInterfaceCreation : 24
Game 570 method call count for IClientUtils::IsSteamChina : 1
Game 570 method call count for IClientUtils::GetLauncherType : 1
Game 570 method call count for IClientUtils::GetSteamUILanguage : 1
Game 570 method call count for IClientUtils::GetAppID : 27
Game 570 method call count for IClientFriends::GetFriendPersonaName_Public : 2
Game 570 method call count for IClientUser::GetUserDataFolder : 1
Game 570 method call count for IClientUser::GetSteamID : 5
Uploaded AppInterfaceStats to Steam

**Comment by LokeLok** [comment]
Go create an issue over at: https://github.com/ValveSoftware/Dota-2
