### ISSUE TITLE
[QoL][Easy] Magic wand should be available to purchase in strategy phase

### ISSUE THREAD

**Issue by moonrobin** [ValveSoftware/Dota2-Gameplay#1253]
Magic wand + 3 branches or some variation is a pretty popular starting build in the current meta. It's weird having to buy magic wand via the components + recipe individually, please add the complete item to the strategy phase item list for quality of life.

**Comment by Aluerie** [comment]
Also, currently, it doesn't make any sense to buy Recipe alone (because side shop doesn't exist anymore to complete it in the lane).

So removing recipe and adding the full item would be nice.

**Comment by Aluerie** [comment]
Fixed.

#1348 still there tho :c

**Comment by moonrobin** [comment]
Added in today's update.
