### ISSUE TITLE
QOL: Please make Aghanims Scepter/Shard abilities show up for advanced quickcast key mapping at all times

### ISSUE THREAD

**Issue by noideas4thisname** [ValveSoftware/Dota2-Gameplay#1254]
### Description

As it is today, to get abilities to show up for mapping Quickcast you have obtain the shard or scepter before it shows in the options UI. I'd love to have the option to see which slot abilities will be in even without having the ability yet. I think this would also be helpful for players trying out new heroes and customizing them to their liking.

Example: On Juggernaut it would be nice to see Swiftslash here rather than mapping an empty ability slot before having scepter.

There are plenty of heroes with extra abilities that are constant. It would be nice if the default options always showed their default set of extras.

### Screenshots

![Screenshot 2022-06-14 224240](https://user-images.githubusercontent.com/2354213/173752474-7dd71ac7-99b9-41f0-965d-10c6fa983db9.png)

**Comment by shaileshgarg** [comment]
Don't know when this was implemented, but currently for Heroes the new abilities do show up here.

**Comment by noideas4thisname** [comment]
Just double checked and you are right - this is new behavior since I filed this. Thanks for noting this! I'll close the bug for now.
