### ISSUE TITLE
dota2 launch error on macos

### ISSUE THREAD

**Issue by Metal-joker** [ValveSoftware/Dota2-Gameplay#12548]
### Description

after today's update, an error occur when launching dota2, blocking launch currently
<img width="266" alt="image" src="https://github.com/ValveSoftware/Dota2-Gameplay/assets/27676994/b3879c98-e7f6-48b5-92cd-193fbc381ed7">

**Comment by shubhamkokul** [comment]
Similar issue on my Mac too.
