### ISSUE TITLE
UI Scan says its on cooldown when its not

### ISSUE THREAD

**Issue by dillomn** [ValveSoftware/Dota2-Gameplay#12560]
### Description

The map scans at the bottom right of my screen are ALWAYS grey, it's been like this for a really long time now. I remember them being blue and with a little icon telling you if you had 1 or 2 scans but now it always shows as the scan being on cooldown. This is happening in all games, bots, ranked, unranked. Not sure what is causing it but its extremely frustrating since I have to hover over the icon to see if there are any remaining charges. Also sometimes I notice there just aren't any charges left so my teammates must of used them, however I never heard or saw the scans being used.

Anyone else experienced this or have any fixes?

### Example Match ID (and possibly Timestamp)

N/A

**Comment by Memoframe** [comment]
I have something similar, altho I see number of charges (not sure if they are correct tho)

**Comment by dillomn** [comment]
Mine actually seems to have fixed over the weekend randomly despite being broken for like a month, not sure what fixed it and not sure if it will stay fixed. We will see.

**Comment by dillomn** [comment]
Dunno it's super inconsistent now, sometimes works sometimes doesn't.
