### ISSUE TITLE
Invoker emp bug 7.34d

### ISSUE THREAD

**Issue by dweksa** [ValveSoftware/Dota2-Gameplay#12563]
### Ability name

EMP

### Description

Mana gain to invoker is completely removed = 0 mana gained per mana drained. 

(In Demo) I had to enter random match ID.

### Example Match ID (and possibly Timestamp)

7367140312

**Comment by Wumbo31** [comment]
okay good i’m not crazy.

**Comment by Avarise831** [comment]
#12562

**Comment by irismus** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/12562#issuecomment-1751219906

Fixed. Please close the issue, thank you!
