### ISSUE TITLE
MacOS dock is not completely hidden in exclusive full screen mode 

### ISSUE THREAD

**Issue by mylaluna** [ValveSoftware/Dota2-Gameplay#12580]
### Description

With my current MacOS Sonoma 14.1, the application dock is not completely hidden even in exclusive full screen display mode.

Every time I move my game mouse cursor to the screen area of the system application dock which is invisible, the mouse cursor switches to the system mouse cursor. To switch it back, I have to move the cursor over a creep.

In theory, the full screen mode should disable the dock entirely but it does not.

This is a super annoying bug for me as I keep losing track of my mouse during team fights.

**Comment by ToanHoangHuy** [comment]
are you using macOS version beta? if so why do you report bug?

**Comment by mylaluna** [comment]
The bug is gone somehow after yesterday's dota2 update.

**Comment by Barentsailor** [comment]
The exact same problem is still present in display mode "Exclusive Fullscreen" on M1 Max 16 with Sonoma 14.3. There is no cursor problem in "Desktop-friendly Fullscreen" but at a way lower resolution, same for windowed modes.
