### ISSUE TITLE
[Naga Siren] Immortal "The Bell of Meranthia". The hair looks broken.

### ISSUE THREAD

**Issue by Astiberon** [ValveSoftware/Dota2-Gameplay#12617]
### Cosmetic Item Name

The Bell of Meranthia

### Description

The hair looks broken.
The algae (hair) is stretched and twitching.
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/107125193/84b33463-7d11-45e9-a61e-222e246e6f69)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/107125193/d7b0c30a-0a16-4001-8b0f-acdd9172591a)

### Example Match ID

-

**Comment by floptropica** [comment]
Yes this bug is so annoying. Please fix.

**Comment by alchemist367** [comment]
I also have this bug, any fix for this? Thanks!

**Comment by noedigsti** [comment]
Clearly something funky with the hair physics for this one, don't know since when. It was not always like this.

**Comment by Lyralei27** [comment]
It was like this:
![Naga 2](https://github.com/ValveSoftware/Dota2-Gameplay/assets/106769496/29748bc4-62f5-460e-a614-d673e4d2f587)
But it is like this:
![Naga 3](https://github.com/ValveSoftware/Dota2-Gameplay/assets/106769496/7d7e4373-94a5-4183-8fee-3d934ffcd52d)

**Comment by Astiberon** [comment]
FIXED!
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/107125193/7d5ca526-2bb4-47a9-8a59-b8b36c902874)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/107125193/423bb0cf-5970-4de8-9be4-ffeec51a4f55)
