### ISSUE TITLE
Ethereal Blade active does less damage than it's supposed to

### ISSUE THREAD

**Issue by luckytaurus11** [ValveSoftware/Dota2-Gameplay#12632]
### Item name

Ethereal Blade

### Description

Ethereal Blade is supposed to do 1.5x your main stat + 50 base.

I have 132 intelligence (1.5x = roughly 200 damage) plus the 50 base = 250 total damage it should do.

When I use the active on the dummy target (seen in link below) the dummy only took 59 damage? That's 191 damage blocked which equals to 76% magic resistance when the dummy target should only have 25%

Link to my reddit post with screen capture: [https://www.reddit.com/r/DotA2/comments/172ot1t/ethereal_blades_active_damage_is_bugged/](url)

### Example Match ID and Timestamp

n/a (tested in demo mode)

**Comment by Aluerie** [comment]
read 731

**Comment by LokeLok** [comment]
False.

It's based on the target you use it on and not your own stats. The tooltip could written better to make it clearer.

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/106764092/188bb87e-43da-4ce1-9d2e-462e24139afe)

**Comment by luckytaurus11** [comment]
Damn I can't believe I missed that. Thanks for clearing it up. I don't know why I assumed it would be based on MY primary attribute
