### ISSUE TITLE
Crash to desktop when dropping targeting items

### ISSUE THREAD

**Issue by Sadixe** [ValveSoftware/Dota2-Gameplay#12647]
### Item name

Some items and neutral items with a targeted ability

### Description

When you press on a item with a targeted ability like Psychic Headband and then drop the item while having the targeting reticule active the game crashed to desktop. I've tested in demo mode and the game crashed with for example Psychic Headband, Nullifier, Abyssal blade. It doesn't crash every time you drop an item.

### Example Match ID and Timestamp

7314753002 - 38:10

**Comment by eugene-valve** [comment]
Thanks for reporting this crash, it should be fixed in an upcoming update.
