### ISSUE TITLE
Battle fury making lower damage with Kunka

### ISSUE THREAD

**Issue by Vasyokvk** [ValveSoftware/Dota2-Gameplay#12697]
### Item name

Battle fury

### Description

Battle fury making lower damage with Kunka's second abillity(Tidebringer). Looks like it ignoring abillity where bf working.

### Example Match ID and Timestamp

Training. Testing.

**Comment by erkantaylan** [comment]
It does not, fury does second damage so last visible damage is less. but total is more (total damage) = (tide bringer) + (furry damage)

**Comment by Vasyokvk** [comment]
Yep, my miss, thx
