### ISSUE TITLE
Compendium Oracle Challenge causes Dota 2 Network to get lost

### ISSUE THREAD

**Issue by stiggy87** [ValveSoftware/Dota2-Gameplay#12716]
### Description

When trying to fill out the Oracle's Challenge, the Dota 2 network gets dropped and takes a while to reconnect. It also resets anything I pick. It seems to have been added since it went live.

### Screenshots

https://imgur.com/a/aeTgRkn

**Comment by pomid** [comment]
+
it really fucks it up hard ....
console goes crazy
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/26696482/5f9ee6d6-fd6e-4ced-a410-2347d77b0269)

**Comment by eugene-valve** [comment]
Thank you for taking the time to report this, a fix will be going live shortly!
