### ISSUE TITLE
Multiple match replays unavailable

### ISSUE THREAD

**Issue by erxor-github** [ValveSoftware/Dota2-Gameplay#12733]
### Description

I played some games last night and I cannot download the replays. It just says 'replay pending'. This has been happening in SEA and OCE servers quite frequently.

Would appreciate help with downloading this one please. Plus also a fix for future replays. TIA!

### Example Match ID (and possibly Timestamp)

7375647299

### Screenshots

<img width="1920" alt="image" src="https://github.com/ValveSoftware/Dota2-Gameplay/assets/107615194/18ab0dd3-81b2-4ca6-8a78-e8396a083278">

**Comment by erxor-github** [comment]
Some more match IDs that have issues:

7375574989 - 'looking for replay'
7374075879 - download replay button is available, but it fails to download

**Comment by erxor-github** [comment]
both replays now available. not sure if you fellas fixed the cause, but much appreciated for making them both downloadable. cheers

**Comment by sunnybeats** [comment]
Another Match ID

7472871382 - looking for replay…

is there a genral problem at the moment?

**Comment by sdasrc** [comment]
Same issue - 7475907843. Played the match 12 hours ago. Any ideas what might be causing this?

**Comment by aliaksandr-karpovich** [comment]
Yeah I have games played 2 days ago that don't have replays available
