### ISSUE TITLE
no text

### ISSUE THREAD

**Issue by dota-2-player** [ValveSoftware/Dota2-Gameplay#12740]
no text

**Comment by VicenteHKT** [comment]
I know a real professional hacker who has worked for me once in this past month. He is very good at hacking. He offers legit services such as clearing of bad records online without it being traced backed to you, he clones phones, hacks facebook, Instagram, whatsapp, emails, twitter, you can recover your bitcoin/cryptocurrency from scammers. His charges are affordable, reliable. Contact him via this email address: (WISETECHHACK@ GMAIL. COM)

**Comment by dota-2-player** [comment]
> I know a real professional hacker who has worked for me once in this past month. He is very good at hacking. He offers legit services such as clearing of bad records online without it being traced backed to you, he clones phones, hacks facebook, Instagram, whatsapp, emails, twitter, you can recover your bitcoin/cryptocurrency from scammers. His charges are affordable, reliable. Contact him via this email address: (WISETECHHACK@ GMAIL. COM)

Thank you for your words of encouragement, but this is not a "digital prorblem"... that would call for a "digital hacker". 

I don't have money;
I have no influence;
I have nothing to steal;
I'm a nobody.

I'm a simple guy who just plays the game.

Why would I want to hack into Valve's servers? 

If I can "ask" the developer for something.

The developer can't be a "sociopathic maniac" that enjoys the suffering of "players" and not help me in this situation?

Why "sociopathic maniac"?

What would it take to:

https://youtu.be/tbyrkzRPIWI

1) Brand people "not decent" based on the developer's own opinion.
2) Brand people "not polite" based on the developer's own opinion.
3) Turn off voice and letter chat based on 1 and 2 points.
4) Ban people from playing the game based on 1 and 2 points.
5) Allow other players, hackers, developers based on 1 and 2 points to torment other players not being able to defend themselves.

https://youtu.be/rhhI_qYOacw?si


Isn't it better to live in God's world and lovingly find out relationships than to ask to do 1-5 points that are mentioned above in the text?

why have enemies when you can have friends:
https://youtu.be/6gUwgHan5Rc

**Comment by dota-2-player** [comment]
The "title" of the "topic" was changed due to the fact that after writing this topic, this movie:

https://youtu.be/hbrsX1_Bj88

appeared in my YouTube recommendations.... .... ..... ....  

Google cookies are safe, Google said...

Agree with the use of Google cookies in Steam, Steam said...

yeah...

The bear is with you ʕಠᴥಠʔ  .
I mean, I wish you perseverance and patience, dear reader and I also wish you love (^=◕ᴥ◕=^) .

P.S.

 (╥﹏╥) Please help ｡･ﾟﾟ*(>д<)*ﾟﾟ･｡

**Comment by dota-2-player** [comment]
And I noticed something else, if you think about it in reverse:

Is it possible that the “nicknames” (and profile picture) of the “players” with whom I play a round in Dota 2 can:

infect with the meaning (text) of your nicknames, my Cookies files A MEANS:

 -----> and-----> YouTube will start showing me a video “based on their nicknames and pictures”.... ----->

-----> that is: some 9 people impose their opinions on me through nicknames by infecting cookies so that my browser shows:

 what does one of the 9 other players **"want"**... but **"does"** DOTA 2 + Cookies:


Hey.. then doesn’t “Dota 2” go beyond “the limits of what is permitted” and the cookies that I had in the game are now infected with “information from other players” and affect the video that I would not like to see in “recommended YouTube” or advertising.

That is, this is violent marketing...? 

https://youtu.be/KpPE85Jogjw

### Something like this:

Exceeding the license agreement for the distribution and use of information, not as an “intermediary”:
**Example 1**: Cookies --> Steam --> Cookies --> YouTube based on cookies, 

but as an accomplice in the person of the received “feedback from other players in DOTA 2: player names (nickname)” and  

**the influence of this information on the software computer support...**

**Example 2**: Cookies -- Steam -- Cookies with user information -- YouTube based on cookies + information from steam dota 2 valve)

_**### Isn't this called information leakage?**_

**Comment by dota-2-player** [comment]
The "title" of the "topic" was changed due to the fact that after writing this topic, this movie:

https://youtu.be/hbrsX1_Bj88

and

https://youtu.be/70TmR6f0j1U
(my grandfather was a beekeeper... 😭 respect to the author film-video).

appeared in my YouTube recommendations.... .... ..... ....

Google cookies are safe, Google said...

Agree with the use of Google cookies in Steam, Steam said...

yeah...

The bear is with you ʕಠᴥಠʔ .
I mean, I wish you perseverance and patience, dear reader and I also wish you love (^=◕ᴥ◕=^) .

P.S.

(╥﹏╥) Please help ｡･ﾟﾟ*(>д<)*ﾟﾟ･｡

I liked the video above, but unlike "situation with branding (stigmatizing/blaming) players of unpolitens and dishonests” in "DOTA 2" Valve and using "Google" as a weapon against players...

Let's live in God Peace with love.

https://youtu.be/KSwy13vayiE

**Comment by TobyFlendersonFromHR** [comment]
shopify rebellion need to shop for a new carry player

**Comment by dota-2-player** [comment]
> shopify rebellion need to shop for a new carry player

Thanks for your comment, but Shopify Rebellion? What is this?
