### ISSUE TITLE
Steam scammed me for my intire wallet balance

### ISSUE THREAD

**Issue by OGRizzler** [ValveSoftware/Dota2-Gameplay#12754]
### Description

I just wanted to gift R6S to a friend from my steam wallet, it was on sale for $7.99 and I had $8.25 but I kept getting an error and told to try later and contact Steam Support if I keep getting the error.
I tried several times for 2 days but no luck and the Steam Support closed my multiple requests without getting a single reply from them.
Yesterday I was surprised to see a purchase of a Dragon Knight Shield for $8.25 which was my whole wallet balance (the shield only costs $0.03), I didn't even know this item existed and wasn't interested in buying anything.
I took screen shots of the whole incident and sent them with yet another support request.
I reported the seller for phishing and scamming and tried another support request but all were closed with no response and didn't get a refund.
My steam account is well protected and only accessible throughout my phone (was with me) and my laptop (Closed in my room)
What am I supposed to do now?

### Screenshots

![Error inside Steam Market](https://github.com/ValveSoftware/Dota2-Gameplay/assets/147740599/1443a395-5930-4c2f-9538-44a2b2e73a16)
![Error sent via email](https://github.com/ValveSoftware/Dota2-Gameplay/assets/147740599/38cefb0a-8942-4467-81eb-0719cba2d3ae)
![Item details](https://github.com/ValveSoftware/Dota2-Gameplay/assets/147740599/394656ca-b504-407b-bc3f-1009fc454649)
![Steam emails](https://github.com/ValveSoftware/Dota2-Gameplay/assets/147740599/84e17d5f-e85b-42d5-a02c-f64764f315c5)
![Steam support history](https://github.com/ValveSoftware/Dota2-Gameplay/assets/147740599/d115b82f-163b-41a0-b4af-be1b7f8df72e)
![Purchase recipt ](https://github.com/ValveSoftware/Dota2-Gameplay/assets/147740599/7a30e2e6-6d64-43c0-a627-c581b6e84272)

**Comment by pinguluk** [comment]
Contact steam support, this repo is for dota2

**Comment by OGRizzler** [comment]
> Contact steam support, this repo is for dota2
@pinguluk not directly, tried buying r6s for a friend and ended up with a dota 2 item that i know nothing about
I did, you can see how many times I did but no response.

**Comment by commentator24** [comment]
no one can help you here. you need to contact steam support.

**Comment by OGRizzler** [comment]
@commentator24 
I did but all of my reports keep getting closed without getting a reply maybe one of them would see it here.

**Comment by OGRizzler** [comment]
@commentator24 @pinguluk 
Someone had access to my account from Russia, but I have the Steam Guard Authenticator and 2FA all enabled, how did he get in? and why I wasn't notified?!
I deauthorised all devices and changed my password now, hopefully this time the Guard does its job and my balance problem get reveiwed and resolved now.

**Comment by pinguluk** [comment]
Check if you have an API key created in your account

https://cran.r-project.org/web/packages/CSGo/vignettes/auth.html

If so, revoke it

**Comment by OGRizzler** [comment]
@pinguluk 
it tells me to register for a new key so I guess I don't have it?
I truly thank u for ur effort and time.

**Comment by TobyFlendersonFromHR** [comment]
why would you buy a cosmetic for 8 dollars

**Comment by TobyFlendersonFromHR** [comment]
why would you buy a cosmetic for 8 dollars, that is the real crime here

**Comment by OGRizzler** [comment]
@TobyFlendersonFromHR 
I did not, I just wanted to buy r6s but got multiple unknown errors.
Next day got an email of a cosmetic purchase.
I have no idea about it and I didn't even buy a single cosmetic since 28 September.

**Comment by commentator24** [comment]
do you remember what other websites you login to?
you probably clicked on random phishing sites like fake trade offers and gave away your steam credentials

**Comment by OGRizzler** [comment]
@commentator24 Just the steam market through steam itself
