### ISSUE TITLE
Fantasy score calculates wrong

### ISSUE THREAD

**Issue by centralnui** [ValveSoftware/Dota2-Gameplay#12772]
### Description

Hello!
Please, take a look at this screenshot. 
![unnamed](https://github.com/ValveSoftware/Dota2-Gameplay/assets/113243212/854a2096-9ffe-48db-8fae-ce4a3a1799dc)

As you can see the total score hadn't support score.

**Comment by Markezzzz** [comment]
Yeah it only calculates Core and Mid score.

**Comment by centralnui** [comment]
![unnamed](https://github.com/ValveSoftware/Dota2-Gameplay/assets/113243212/b157ef8a-94ef-4e50-9f4a-e9231115fcc4)
I've got new data, but looks like it even not recalculates.

**Comment by centralnui** [comment]
It's fixed with the latest update, thx a lot!
