### ISSUE TITLE
Roshan didn't change his position on a day/night changing

### ISSUE THREAD

**Issue by EmitriusDin** [ValveSoftware/Dota2-Gameplay#12783]
### Description

As you can see, time of match was 25:43 and Roshan was on radiant side. Match ID 7379220160

At 25:00 Roshan moved to gates, stunned me when I followed him but when I waited and moved to dire lair it was empty - I found Roshan back at radian side.

### Example Match ID (and possibly Timestamp)

7379220160 - 25:00-26:00

### Screenshots

![20231013160145_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/147829815/6e6c23d1-943a-498b-9f55-b02e1d9bc16d)

**Comment by Philaeux** [comment]
Transition: https://youtu.be/tg6cy_QFLLk

**Comment by commentator24** [comment]
#8577 i think it's an issue with defiant shell
i remember i saw a video where MK jump to a tree with defiant shell and roshan walk back too

**Comment by eugene-valve** [comment]
Thanks for the bug report and the video, this should be fixed in an upcoming update.
