### ISSUE TITLE
Eternal Shroud add magic resistance to illusion

### ISSUE THREAD

**Issue by GTOL** [ValveSoftware/Dota2-Gameplay#12792]
### Item name

Eternal Shroud

### Description

I tested with Chaos Knight ultimate illusions and Lion's Finger of Death. 

Illusion took 30% less damage with Eternal Shroud in the inventory.

Added 2023-10-16:
I test again with other heroes and manta style and the results remain the same. It is confirmed that Eternal Shroud provides magic resistance to illusions.

### Example Match ID and Timestamp

N.A.

**Comment by TobyFlendersonFromHR** [comment]
no i dont think so

**Comment by GTOL** [comment]
> no i dont think so

it doesn't matter what you think. Just go test in the practice mode.

**Comment by Aluerie** [comment]
Looks like, this issue is fixed.

**Comment by GTOL** [comment]
Yep they mentioned it in the newest update.
