### ISSUE TITLE
I am not able to purchase Compendium levels

### ISSUE THREAD

**Issue by AgroDota** [ValveSoftware/Dota2-Gameplay#12805]
### Description

I'm trying to purchase some Dota 2 compendium levels but I cant complete the purchase. 
I'm not able to press "Authorize" when trying to complete the purchase and I'm just stuck at the same window and cant even press "Cancel" (please check the attached screenshot),  I have more than enough money in my Steam Wallet which is the chosen payment method for this purchase. 

### Screenshots

![w32312ed123123123](https://github.com/ValveSoftware/Dota2-Gameplay/assets/147919586/28a4e776-7e01-4c97-81dd-9b510b3ace3f)

**Comment by RaymondMcGuire** [comment]
+1

**Comment by AgroDota** [comment]
> +1

I was able to fix it by removing Steam client Beta Testing 
1- Steam 
2- Settings 
3- Interface 
4- Change " Client Beta Participation" from (Steam Beta Update) to (No beta chosen) 

Let steam restart and complete the updates and you're good to go.

**Comment by RaymondMcGuire** [comment]
> > +1
> 
> I was able to fix it by removing Steam client Beta Testing 1- Steam 2- Settings 3- Interface 4- Change " Client Beta Participation" from (Steam Beta Update) to (No beta chosen)
> 
> Let steam restart and complete the updates and you're good to go.

Worked! Thank you!!!!

**Comment by GarageDragon** [comment]
> > +1
> 
> I was able to fix it by removing Steam client Beta Testing 1- Steam 2- Settings 3- Interface 4- Change " Client Beta Participation" from (Steam Beta Update) to (No beta chosen)
> 
> Let steam restart and complete the updates and you're good to go.

This worked, thanks!

**Comment by ErikHumphrey** [comment]
The workaround worked, but FWIW attempting the same purchase on Steam Deck just closed the purchase overlay without completing the purchase. Though the game isn't Deck-verified, so whatever.
