### ISSUE TITLE
Some minor issues with the UI

### ISSUE THREAD

**Issue by charpplie** [ValveSoftware/Dota2-Gameplay#12807]
### Description

- [ ] The wrong sizes of the filter backgrounds are set on the Arcade tab.
- [ ] The "Featured" section does not fit completely to the top bar, which is very annoying whenever you go to the "Armory" tab.
- [ ] In the main tab of the Compendium, when you hover over the section, a small transparent stripe appears in the description.
- [ ] The last thing that is possible is not a flaw, but I think it is. The International Hud 2023 contains an empty space between the quick purchase panel and the lower functional panel (I do not know exactly what to call it).
- [ ] On the History tab, the column name is not centered by its value. The same visual flaw is observed in the Teammates tab.

### Screenshots

1. 
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/95695663/36c61f17-194a-4741-b5e8-55c2dd5aaffe)
2.
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/95695663/1d4f4270-c9dd-41d4-b6c4-83cf507e03ac)
3.
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/95695663/4ffb6c4c-4957-492e-a739-394a07af336f)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/95695663/48b28699-9d72-40e1-98ad-6c0a4674c15e)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/95695663/c137c001-46bc-4243-9bf7-f8f4c3ddd102)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/95695663/b67b1277-dac6-4d07-9876-264068616bb3)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/95695663/a987e0ff-9cc0-472f-8133-246f42c920e3)
4.
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/95695663/fb02bfd4-eaa2-4409-91ab-69da314da266)
5.
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/95695663/88e887d1-ae4d-4cc4-87b8-0ae42b377e59)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/95695663/eda56732-9be5-4519-9e16-186e7c597567)

**Comment by AutumnDota** [comment]
To add to this:

On the new HUD, the map sticks out of its space slightly at the top, when the "Use Extra Large Minimap" option is enabled, blocking a lot of the brightly colored stained glass at the top.

![design error](https://github.com/ValveSoftware/Dota2-Gameplay/assets/149004855/1262a2e9-2e85-451d-9c39-6a0a6adda8a8)

If this and issue #4 you mentioned above are fixed, this hud will look way cleaner.

Also (and this one's super nitpicky) the glow at the very top of the Minimap part of the hud is (non-animated, unlike the glows in the rest of the hud, but also) cut off at the top, like it reached the edge of a box that it's constrained to. It's only really noticeable on a very dark background.

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/149004855/29e35119-cb01-4577-bb9c-c4891b9e226c)
