### ISSUE TITLE
Techies Land Mines

### ISSUE THREAD

**Issue by KyTOK** [ValveSoftware/Dota2-Gameplay#12810]
### Description

The "Land Mines" ability is a magic damage type, just like its other abilities. I don't understand why if I have some item equipped that applies a % of life regeneration based on the damage done by the spell, it doesn't apply to "Land Mines". I leave a video.

The other abilities, as you can see in the video, do have that % of life regeneration, but not with Land Mines.

https://github.com/ValveSoftware/Dota2-Gameplay/assets/38820768/875a0f3e-5411-4aee-afec-a7930d245abb

**Comment by LokeLok** [comment]
Intended.

Land Mines are considered a Ward and therefore its own Unit. Land Mines do not benefit from Spell Lifesteal and Spell Amp. Look at the bright side, you don't take any Blade Mail damage either from Land Mines.

**Comment by KyTOK** [comment]
It makes sense, an example could be Zeus' "Nimbus"?. As you said, let's look on the bright side :). Thanks for your explanation.

**Comment by LokeLok** [comment]
Yes, it has the same rules as Nimbus.
