### ISSUE TITLE
MISSING ITEMS

### ISSUE THREAD

**Issue by SesameSeed69** [ValveSoftware/Dota2-Gameplay#12816]
My dota2 items are missing in my armory. My hero`s set are missing. I still have all my items last game yesterday and now i noticed that some of my items bought in the market and obtained in the game are missing. I checked the market and my trade history but none of it are there. My items cannot be gifted. I have steam guard and only on my computer is the registered computer i can log in my account. I updated my dota 2 and now my items are missing. Please fix this and return all of my missing items. My DOTA 2 ID is 253824660. Thank you!

**Comment by commentator24** [comment]
no one can help you here, you need to contact steam support.

and check your gifting history. go to your profile.. click games
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109324155/33f18216-4932-4810-b2d2-d1557bb190e1)
then click personal game dota
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109324155/6c1ce657-847e-44f0-bcfb-1922ed70ba16)
then gifting history
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109324155/cb6d8ffe-df9c-4dd0-8e7e-9d72fdf7e5b8)

**Comment by vivi-lili** [comment]
What's your Steam ID?

**Comment by commentator24** [comment]
@vivi-lili you can check his steam id from dota id 253824660 inside dota 
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109324155/57b007d8-67e2-41d4-9b66-b86c716f359f)
then click steam 
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109324155/77b121b9-486f-45de-8c05-490d65e271f8)
https://steamcommunity.com/profiles/76561198214090388

**Comment by vivi-lili** [comment]
Looks like many items were traded away on 10/14.  You can check your inventory history here https://steamcommunity.com/profiles/76561198214090388/inventoryhistory/

If you didn't do this yourself, then your account is likely compromised.  Since this is not a UI bug, please instead reach out to Steam support.
