### ISSUE TITLE
URGENT: Game does stay open longer than 1 minute.

### ISSUE THREAD

**Issue by atheistium** [ValveSoftware/Dota2-Gameplay#12814]
### Description

- Open Game via Steam
- Client opens and loads in
- You can click through to tabs but after a minute the client closes.
- Client force closes itself.

- Tried validating files
- Re-opening game
- same issue

Multiple Reports: https://www.reddit.com/r/DotA2/comments/177x8jv/broken_game/

**Comment by atheistium** [comment]
Patch was just released. I believe this has fixed it! ty

**Comment by atheistium** [comment]
Patch released has not fixed it :(

**Comment by lukaswittmann** [comment]
I think the reason is the mini-profile showcase loading in; it crashes the moment the profile showcase finishes loading.

**Comment by lukaswittmann** [comment]
Dota 2 game coordinate beeing down fixed the issue. lol.

**Comment by lukaswittmann** [comment]
Issue seems to be fixed after game coordinator is up again.

**Comment by atheistium** [comment]
This looks fixed now. I can queue and profile images have loaded.
