### ISSUE TITLE
ROAD TO TI CHALLENGE LOCKED QUEST BUG

### ISSUE THREAD

**Issue by fdesutv** [ValveSoftware/Dota2-Gameplay#12822]
I have completed the challenge, but it does not give me the reward or unlock the next challenge
![Captura de pantalla 2023-10-15 001814](https://github.com/ValveSoftware/Dota2-Gameplay/assets/146380033/7327f3e4-5d8b-4eba-9d20-72359add82e9)
![Captura de pantalla 2023-10-15 005829](https://github.com/ValveSoftware/Dota2-Gameplay/assets/146380033/c0f27cac-f9c7-4732-a921-eadbfe17e9c7)

**Comment by Kodorieg** [comment]
Win with **2**
