### ISSUE TITLE
Gem would not go offcooldown

### ISSUE THREAD

**Issue by originalProgrammer** [ValveSoftware/Dota2-Gameplay#12839]
### Item name

Gem of True Sight

### Description

The active ability of Gem of True sight does not go off cooldown. It is stuck at 10.6 seconds.

7384229334 25:31

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/65430521/a56b1393-1f49-410e-961a-368b67469faa)

### Example Match ID and Timestamp

7384229334 - 25:31

**Comment by Aluerie** [comment]
d #8773

**Comment by Nathanael-Valve** [comment]
Fixed in next update.
