### ISSUE TITLE
Talents sticker bundle

### ISSUE THREAD

**Issue by CrazySnakeMan** [ValveSoftware/Dota2-Gameplay#12830]
### Description

Unable to authorise purchase of any bundle on steam. I can buy cosmetics and sets in dota, but every time I try to buy any talent sticker bundle, I cant authorise the purchase.

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/119517185/c9803b67-7ad9-4ccb-875e-3f9e4ac71dd3)

stuck on this page, clicking authorise does nothing and if I refresh it, I get the following.

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/119517185/b593fab5-7ae4-4949-a139-3315b22b10fb)

**Comment by AgroDota** [comment]
Same here, you also cant buy levels.

**Comment by AgroDota** [comment]
I was able to fix it by removing Steam client Beta Testing 
1- Steam 
2- Settings 
3- Interface 
4- Change " Client Beta Participation" from (Steam Beta Update) to (No beta chosen) 

Let steam restart and complete the updates and you're good to go.

**Comment by CrazySnakeMan** [comment]
> I was able to fix it by removing Steam client Beta Testing 1- Steam 2- Settings 3- Interface 4- Change " Client Beta Participation" from (Steam Beta Update) to (No beta chosen)
> 
> Let steam restart and complete the updates and you're good to go.

wow you were right. for some reason removing steam beta  testing fixed it for me thanks!!
