### ISSUE TITLE
Fantasy Craft Roll reward bugged

### ISSUE THREAD

**Issue by ElDude1** [ValveSoftware/Dota2-Gameplay#12873]
### Description

The fantasy craft roll reward is bugged. I sometimes turn it in but don't get additional rolls. This happened to me like 5 times already and it is really annoying. Steam support told me they can't help and I should post here.

**Comment by SoftPancakes42** [comment]
Are you sure those rolls aren't for the International part? Some of the fantasy rolls are specifically for playoffs or The International.

**Comment by ElDude1** [comment]
> Are you sure those rolls aren't for the International part? Some of the fantasy rolls are specifically for playoffs or The International.

Yes I am sure, because I receive some of the rolls and some of them I dont receive

**Comment by ElDude1** [comment]
Well seems I cant read an you are absolutely right
