### ISSUE TITLE
net_option SDRClient_ForceRelayCluster no longer works

### ISSUE THREAD

**Issue by SethDusek** [ValveSoftware/Dota2-Gameplay#12883]
### Description

This command lets you change your routing ingame (Steam Datagram Relay). However this feature has been broken for months despite being a lifesaver for many of us in my country.

The game by default selects the Dubai route for me when playing Singapore. This has 120-ish ping and constant 20% loss making the game unplayable. Before I used to be able to force "sgp" and get 94 ping and usually 0 loss. But this feature has been working sporadically for months, either not working, or requiring restarting the game, entering the command and then reconnecting.

**Comment by Aluerie** [comment]
#7113

**Comment by SethDusek** [comment]
Thanks, closing this issue
