### ISSUE TITLE
Arc Warden tempest double and main abilities are swapped 

### ISSUE THREAD

**Issue by balenamiaa** [ValveSoftware/Dota2-Gameplay#12918]
### Ability name

All of Arc Warden's abilities

### Description

I started the game with the tempest double's abilities instead of the main hero's. Even after unlocking ultimate, my main continues to have the tempest double's variation of the abilities meanwhile the clone has the main abilities.

### Example Match ID (and possibly Timestamp)

7389779392

**Comment by Aluerie** [comment]
intended read 733
> The upheaval has attuned Arc Warden to the Ancients. When playing on Dire side, Arc Warden will have the Tempest abilities by default and his Tempest Double will have its normal abilities. This condition is temporary and will go away once Zet adapts to the new paradigm.

**Comment by balenamiaa** [comment]
Aha, I see. Perhaps the tooltips could make the intent clearer
