### ISSUE TITLE
dotaplus 200 enemy wards not progressing at all

### ISSUE THREAD

**Issue by commentator24** [ValveSoftware/Dota2-Gameplay#12912]
Hi not sure what the devs did, but deward 200 quest no longer progressing. it works last season
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109324155/17268c8c-f641-4927-bca9-f7f582078ca5)

**Comment by Aluerie** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/11442
