### ISSUE TITLE
Razor shard bugged with Primal Beast ultimate.

### ISSUE THREAD

**Issue by ashwinramavarma** [ValveSoftware/Dota2-Gameplay#12983]
### Ability name

Static link, Pulverize

### Description

Pulling enemy with shard on razor causes it to be thrown around like crazy when Primal casts Pulverize. Can do around 2.5k pure damage if abused with Rupture. [Streamable link](https://streamable.com/rzh0vv) demoing effect.

### Example Match ID (and possibly Timestamp)

Found in demo.

**Comment by Dota-Exp** [comment]
fixed in upcoming update, thank you
