### ISSUE TITLE
Troll warlord

### ISSUE THREAD

**Issue by MiulescuTim** [ValveSoftware/Dota2-Gameplay#12985]
### Ability name

Battle trance

### Description

Steam profile: https://steamcommunity.com/profiles/76561198045851083/
Hey team,

So it seems that Troll had only 125 mana points in minute 25 or so, hero was lest say level 10, The ultimate Battle trance requires 150 mana. Not sure what happened but no spell was on the hero that made him loose any mana points so it seemed a bit odd.

### Example Match ID (and possibly Timestamp)

7394711724

**Comment by LokeLok** [comment]
Radiant has Silencer which permanently steals intelligence, that's the reason for the low mana pool. 

Please close this issue.
