### ISSUE TITLE
Hero disappeared - nothing could have been done.

### ISSUE THREAD

**Issue by papanireal** [ValveSoftware/Dota2-Gameplay#13010]
### Ability name

Spell steal

### Description

Playing Rubick, used Spell steal then Death seeker then the hero disappeared. More details you can see in the replay.

### Example Match ID (and possibly Timestamp)

7396693944 - 39:23

**Comment by Dota-Exp** [comment]
fixed in upcoming update, thank you

**Comment by shaileshgarg** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/8208
