### ISSUE TITLE
no award in fantasy playoffs

### ISSUE THREAD

**Issue by Positive2** [ValveSoftware/Dota2-Gameplay#13022]
### Description

i scored 79952.22 points, but didn't receive any award and don't have any percentile, also my friends don't see my score on their screens

### Screenshots

![fantasy](https://github.com/ValveSoftware/Dota2-Gameplay/assets/148853664/a35f862f-1bfc-4b57-bfb7-e49abdaf7390)

**Comment by vtebe** [comment]
same here

**Comment by lirest2** [comment]
так же

**Comment by dSharkz** [comment]
same

**Comment by 0Zen11** [comment]
I am having the same issue, i haven't received points for Fantasy or the Oracle's Challenge.

**Comment by ligaapl** [comment]
yep, i am too didn't receive any award

**Comment by 0Zen11** [comment]
> I am having the same issue, i haven't received points for Fantasy or the Oracle's Challenge.

I have now recieved Oracle's Challenge but still waiting on Fantasy.

**Comment by EmreBaltacii** [comment]
same. 4 hours ago, I recieved Oracle's Challenge but still waiting on Fantasy

**Comment by Positive2** [comment]
fuxed

**Comment by 0Zen11** [comment]
fixed for me too
