### ISSUE TITLE
Items are missing from my inventory after update

### ISSUE THREAD

**Issue by DasNorthman** [ValveSoftware/Dota2-Gameplay#13036]
### Description

I have hundreds of items from over the years and several that I opened recently however the vast majority of them no longer show up on my heroes. This applies for both items acquired in-game as well as off the community market. 

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/148911610/c1a30427-eaa6-4761-af26-d34775474e61)

**Comment by DasNorthman** [comment]
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/148911610/372499bf-dc52-4c2b-9474-152ca5c40131)
Example of one item I have purchased that doesn't show up, however the are hundreds with this behavior. I was not hacked and there is no history of any items being sold.

**Comment by vivi-lili** [comment]
What's your steam ID?

**Comment by DasNorthman** [comment]
Thanks for the response, my steamid is: 76561198049232324Sent from my iPhoneOn Oct 24, 2023, at 5:35 PM, vivi-lili ***@***.***> wrote:﻿
What's your steam ID?

**Comment by thomas1803** [comment]
I think it is a bug because I encountered the same issue with missing items from my inventory after the update. <a href="https://pokedoku.io">pokedoku</a>

**Comment by vivi-lili** [comment]
It looks like the items have been traded away.  You can find your inventory history here: https://steamcommunity.com/profiles/76561198049232324/inventoryhistory/

**Comment by DasNorthman** [comment]
How is that possible? I’ve never traded anything before. Does this mean my steam account was hacked??Sent from my iPhoneOn Oct 25, 2023, at 3:37 PM, vivi-lili ***@***.***> wrote:﻿
It looks like the items have been traded away.  You can find your inventory history here: https://steamcommunity.com/profiles/76561198049232324/inventoryhistory/

**Comment by vivi-lili** [comment]
If you didn't do this yourself then likely your account is compromised, sorry about that.  Since this is no longer a bug, please instead reach out to Steam support.
