### ISSUE TITLE
No reward for Fantasy

### ISSUE THREAD

**Issue by Slivofr** [ValveSoftware/Dota2-Gameplay#13056]
### Description

Hi, i didnt receive reward for fantasy.

Id contact : 82959071

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/148962060/3169d567-b994-4c28-a568-363c889de8a7)

**Comment by EmreBaltacii** [comment]
same here

**Comment by Slivofr** [comment]
it ok for me now
