### ISSUE TITLE
Lunas lucent beam comeing from ult didn't do a single stun entire match

### ISSUE THREAD

**Issue by kuborek2** [ValveSoftware/Dota2-Gameplay#13131]
### Ability name

Eclipse

### Description

Played luna pos 5, and whenever I used my ulimate ability "R" lucent beams froming from eciplise never ever stunned anything.

### Example Match ID (and possibly Timestamp)

7406095581 TImestamp: 17:21, 19:48, 23:50, 26:27

**Comment by Aluerie** [comment]
> 17:21, 19:48, 23:50, 26:27

you were below 25 at these timestamps.

**Comment by kuborek2** [comment]
Nevermind
