### ISSUE TITLE
Didn't receive the trophey 99% International 2023 Fantasy Percentile

### ISSUE THREAD

**Issue by ligaapl** [ValveSoftware/Dota2-Gameplay#13148]
### Description

At the time of publication of the news, the compendium levels for the final stage of the fantasy draft were issued, but the trophy 99% International 2023 Fantasy Percentile remained unchanged: bronze for 50 percent :(
p.s. on first stage of the fantasy i have 47%, but in second stage i have 97%. Where is my trophy? ID 113184848

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/146592265/2351def6-7962-4b84-86a7-6c420801f79a)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/146592265/e2888a0a-8c99-4ce6-9cbf-ce64888c0ab9)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/146592265/c34364b1-10ae-482b-9815-0060e864534b)

**Comment by oisinhg** [comment]
you are looking at the active trophy panel. click on the "my collection" panel to view the trophies you actually have, and you will see that you have no trophy for the fantasy challenge at all. they haven't been given out yet.

**Comment by ligaapl** [comment]
> you are looking at the active trophy panel. click on the "my collection" panel to view the trophies you actually have, and you will see that you have no trophy for the fantasy challenge at all. they haven't been given out yet.

Yep, I see. Thank you! It's okay, if they haven't been given out yet. It's my first compendium, and i don't know how it works, but I've encountered bugs before and decided to play it safe and identify the problem.
