### ISSUE TITLE
Incorrect rewards for the oracle test

### ISSUE THREAD

**Issue by MasterS112** [ValveSoftware/Dota2-Gameplay#13156]
### Description

In the third stage, I guessed 10,000 experience, but only five thousand were awarded!

### Example Match ID (and possibly Timestamp)
Dota2 ID NUMBER: 337286218

_No response_

### Screenshots

![загруженное - 2023-10-31T065224 719](https://github.com/ValveSoftware/Dota2-Gameplay/assets/149443752/84634e36-8767-475c-a7d7-26d7a310529c)
![загруженное - 2023-10-31T065201 441](https://github.com/ValveSoftware/Dota2-Gameplay/assets/149443752/d8988b32-ac81-42da-8060-feda7ade0e17)

**Comment by Nbvgstghhj** [comment]
Same here, #13155
