### ISSUE TITLE
stickers for centaur and outworld destroyer

### ISSUE THREAD

**Issue by Kirpich158** [ValveSoftware/Dota2-Gameplay#13203]
### Cosmetic Item Name

any player/team/talent stickers

### Description

Can't apply any sticker that I have to centaur and OD, because their names are too long and so there are just no "apply sticker" button at the end of their names. also the problem is with Legion Commander, Ancient Apparition (also Team Spirit Breaker, but it's temp cause you will probably change his name back), but now with the size of that button, it becomes smaller when name becomes longer

### Example Match ID

-

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/44980707/801b756e-0b7e-4ea0-a639-978c0139b4f4)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/44980707/f0beb8fd-f626-45fb-ae5c-df523298201f)

**Comment by cocolad** [comment]
This issue is very frustrating for sticker collectors. Please fix

**Comment by seowth** [comment]
Noticed this problem as well. Please fix.

**Comment by sadikiniku** [comment]
Same issue, i want to replace the sticker hahaha hope they fix it soon

**Comment by Kodorieg** [comment]
This issue still hasn't been fixed in patch 7.35. There are stickers as Frostivus rewards. I hope devs fix this issue quickly.
And after assigning sticker, the sticker size is very small in hero loadout. We need a way to make the assigned sticker appear larger when we move mouse cursor over it.

**Comment by Aluerie** [comment]
d #13186 #12978

in the meantime you can decrease font size with dev tools or try diff reso
