### ISSUE TITLE
Role Queue

### ISSUE THREAD

**Issue by k1ngm0ym0y** [ValveSoftware/Dota2-Gameplay#13216]
### Description

I have not gained role queue for weeks now I have been playing support all the time but I still don't have role queue. The only time I can play other role is when I play with my friends. But when I'm playing alone I don't get any role queues.
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/149588166/91feebcc-e2e1-465b-a2b8-35924766e962)

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/149588166/c240428b-dc07-4a1f-bbad-4b8aff8c4dfa)

**Comment by commentator24** [comment]
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109324155/12c7c076-b0f3-43ca-8b0b-61f5becdb0fc)
tick all 5 roles to get 4 role queue (solo). 2 for party of 2. 1 for party of 3. half for losses.
tick both 2 support roles to get 0
if tick only Support (but not hard support) you will spend 1 role queue

you didnt tick both support and only ticked 2 here
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109324155/96f1c488-6396-418c-9afb-7762c892e2a1)

can close issue not a bug

**Comment by TobyFlendersonFromHR** [comment]
not just guardian mmr, but also guardian at reading

**Comment by k1ngm0ym0y** [comment]
> not just guardian mmr, but also guardian at reading

Well, that is why we newbies brother. This is the reason people are afraid to ask, cause people like you make them feel stupid asking something they don't know! Get a life bro

**Comment by k1ngm0ym0y** [comment]
thanks brother I was playing supports only cause of the stars beside it
