### ISSUE TITLE
Compendium - wrong level ammount received for oracles challenge

### ISSUE THREAD

**Issue by Kuboserd** [ValveSoftware/Dota2-Gameplay#13218]
### Description

I achived 7/10 in the international part of this challenge, but I received only 5 levels rather than 10.
Here is a link to my profile https://steamcommunity.com/id/Kuboserd/

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/46865452/1ea8d08f-9858-43dd-bc89-dbbdd0c11b8f)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/46865452/502fccf4-ddbc-4148-b205-80ba4c2f017b)

**Comment by Ghost-of-Dark2God** [comment]
Yeah. It is sad story. It is 5 lvls of compendium, but we don't got it... Sadness...

![2023-10-31](https://github.com/ValveSoftware/Dota2-Gameplay/assets/149622972/c2fcf84a-d0d5-4d85-8856-4826164d7429)
![2023-10-31 (1)](https://github.com/ValveSoftware/Dota2-Gameplay/assets/149622972/c194b7b6-0866-4980-a75e-d68a17a4b5ae)

**Comment by gabrielpastega** [comment]
Same problem here, bunch of friends with the same.
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/88066683/673e48a3-d838-4008-a039-8ed1cb2946e7)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/88066683/4a6fb565-3231-4dc5-9349-fba90c71286f)

**Comment by Singidunum1** [comment]
I have the same problem, made all predictions correct however GG vs BB is giving me that i failed and didnt 
get 20k points just 10k because of that.



![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/149668369/1b89bf5b-7f60-4ecc-99d3-be26d04989b0)
