### ISSUE TITLE
Team Spirit Cheese DUPE on The International 2023 TS vs VP game 3

### ISSUE THREAD

**Issue by Savemech** [ValveSoftware/Dota2-Gameplay#13275]
### Item name

Cheese

### Description

Dead shot makes items use Infinitely
there is video with Russian comments https://www.youtube.com/watch?v=OBmRMWZX_WY

### Example Match ID and Timestamp

7391367511 45:11
<img width="1457" alt="image" src="https://github.com/ValveSoftware/Dota2-Gameplay/assets/8943498/4c6f4de5-f863-40a8-993e-18cf5264805b">

**Comment by LegionOriginal** [comment]
wow

**Comment by TobyFlendersonFromHR** [comment]
big, if true

**Comment by kovalskydoto** [comment]
Man, look at Mira(DW) and his use GHLotus. no thanks.

**Comment by Savemech** [comment]
@kovalskydoto oh wow, thanks for pointing it out
I did rechecked it, and yes it is GHLotus from Mira, sorry folks, my bad
