### ISSUE TITLE
[Ogre Magi] Fire Shield Tooltips Do Not Display Damage Reduction Percentage

### ISSUE THREAD

**Issue by Spastic230** [ValveSoftware/Dota2-Gameplay#1330]
### Hero and spell

Ogre Magi - Fire Shield

### Description

Currently, the Tooltip for Ogre Magi's Aghanim Shard ability Fire Shield does not display the amount of damage reduction the Fire Shield applies to the target for the next 3 incoming attacks. 

Additionally, this information cannot be found by attempting the following:

* Holding Alt on the Tooltip for additional information.
* Viewing the Modifier on an affected unit. 
* Checking the official DotA 2 website for Ogre Magi.

Note: According to the DotA 2 Wiki, Incoming Damage Reduction is 85%. 

Attached are screenshots of the Fire Shield Tooltip on the Heroes Tab, In-Game, and Modifier.

### Screenshots

![OgreMagi_FireShield_Tooltip_Expanded](https://user-images.githubusercontent.com/84210052/174135675-7566831f-5f63-4ffe-b5af-c110e5a6f735.jpg)
![OgreMagi_FireShield_Tooltip_HeroTab](https://user-images.githubusercontent.com/84210052/174135800-c29c12ab-58b4-4341-97f5-64783806286c.jpg)
![OgreMagi_FireShield_Modifier](https://user-images.githubusercontent.com/84210052/174135804-6b246af3-a3de-4f3e-9a39-e0beacf8d8c7.jpg)

**Comment by TheUnholyWrath** [comment]
This has been fixed, you can close this.
