### ISSUE TITLE
Behavior score bug

### ISSUE THREAD

**Issue by JohnDope90** [ValveSoftware/Dota2-Gameplay#13330]
### Description

I was playing a turbo game: 7420859848. I was DP in the game and got run over in my lane. My pudge was incredibly toxic and I reported him and he was muted. He left me alone in lane and I couldn't do anything. I didn't give up though and kept trying. After the match I received an overwatch penalty and additionally lost 2,500 behavior score! How is that fair? I have to play about 100 games to get my lost bahavior score back. I don't think it's fair in any way. Of course, that's also only if I don't get reported in a single one of the 100 games. Which seems inevitable since everyone has unlimited reporter. It is really frustrating and I hope the behavior system is fixed as soon as possible. I think it's crazy that I can lose 2,500 behavior scores over a turbo game. Is that really true?

### Example Match ID (and possibly Timestamp)

7420859848

**Comment by Redo02** [comment]
Its TRUTH.
i played 105 match for 2800 to 3000
now im at 1 score
if score increase, it increased by 15. other time around 50
if you lose its 400 500 600 and 1000
i never ping, troll, afk, throw just casually try to win
but peolle will report you bcuz of lost game or lane, or they solo dive feed then they Ping you bcuz you didnt dive their base for 2vs5.

So if you want increase score. YOU MUST WIN 
WITHOUT MAKING MISTAKE OR MAKING YOUR TEAMMATE ANGRY.
one win is One score so i need 3000 straight win for reach 3000 again.
Just forgot about increase your score. bro
Its stress forgot it

**Comment by marcelmaster** [comment]
#13340
upvote pls
