### ISSUE TITLE
Behavior score bug ( again ) 

### ISSUE THREAD

**Issue by marcelmaster** [ValveSoftware/Dota2-Gameplay#13340]
### Description

I've played 30 games with barely any reports and many commends yet my behavior score barely moves it's like before everybody got their behavior fixed because everyone was abusing the infinite report feature , seems impossible to gain any behavior score so I think it's bugged again and would like any valve employee to please give a check on this since it's impossible to play under 7500 behavior score and also impossible to win because commends seem not work and also not being reported doesn't give almost any behavior score back please give it a check thank you so much

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/149974837/4699cbf3-f019-4d7a-abc6-79705df09c37)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/149974837/30a5e42d-6b95-430f-a014-d5b935babc95)

**Comment by Redo02** [comment]
its not bug its intentional by valve
I just tired of it once i increased score from 1 to 3000
but now i lost to around 2800
then i played 105 match it never increased.
if it increase score is only incresed by 50 or 15
I never pinged. afk. troll throw
i normally play for win
people will report you Hust bcuz We lost game.
 so you supposed to win EVERY MATCH. one win is one score. so you need to win 3000 Straight game without getting reported. After 2999 win. at 3000th game if you lose you wil lose 2999 score. good luck bro

**Comment by marcelmaster** [comment]
well I lost 1.5k behavior score in games where i didn't ruin and was playing in party as 5 people, when is this going to get fixed ? Unplayable rn.

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/149974837/e9a9d5b3-9c21-452c-9923-07a5efe285ee)

**Comment by NAlexP** [comment]
#13000

**Comment by lewisdiamond** [comment]
Something is DEFINITELY bugged: 
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/1375600/49a98d88-afbc-4528-8a62-1f3fcd65bf0a)

**Comment by marcelmaster** [comment]
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/149974837/fcc1a893-4193-4fb6-878e-c50d93399093)
still not fixed... 
more than a week that this keeps happening

**Comment by Sm1leFriend** [comment]
Now I have 1 decency point
![20231028092444_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/148719698/d4e47550-cc18-4155-bb92-5c3df8fede15)
![20231028092445_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/148719698/27571616-12bf-4ae5-8d99-40abddacb211)

**Comment by flames321** [comment]
#13486

**Comment by arturkrugol** [comment]
they will not ingore the topics if we will remind them about it together constantly

**Comment by Jalapan** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/13752
