### ISSUE TITLE
Problem with Spectre hero's ability with aghanim's shard

### ISSUE THREAD

**Issue by Raevsk1i** [ValveSoftware/Dota2-Gameplay#13354]
### Ability name

Dispersion

### Description

When you purchase an Aghanim's Shard, the Dispersion ability becomes active; when pressed, it should reflect 100% of the damage the Spectre takes for 5 seconds, but the damage will still be dealt.
7421554266 - 01:04 (UTC +3)

### Example Match ID (and possibly Timestamp)

7421554266 - 01:04

**Comment by Raevsk1i** [comment]
The patch may say something different, but in the game itself, in the description of the ability in Russian, it says that the reflected damage is not inflicted on the hero, also in the description of Aghanim's Shard.

**Comment by Avarise831** [comment]
#12624
