### ISSUE TITLE
Bug interaction between URSA & QOP

### ISSUE THREAD

**Issue by LSZDota** [ValveSoftware/Dota2-Gameplay#13361]
### Ability name

EARTHSHOCK

### Description

Hello, 

I noticed it in my game today and in demo. This is my explanation : 

1. Ursa's earthshock with shard should apply Enrage
2. Enrage is a "Strong Dispel"
3. On the other hand, QOP Shadow Strike is a dispellable spell

The bug is that the Earthshock with shard didn't dispell the Shadow Strike. On the other hand, Enrage Dispelled it. So it seems that this specific interaction is not working as intended.

In the game, our legion was able easily to dispel the Shadow Strike.

I tried it in demo too, it works as in game, so I am reporting it here. 

### Example Match ID (and possibly Timestamp)

7423421609 (no need for ID or timestamp, it happens in demo too)

**Comment by Aluerie** [comment]
WAI according to original 729. Just a bad tooltip.

**Comment by LSZDota** [comment]
Original 729? Sorry, i can't follow. 
I would appretiate if you have more info about the matter.

**Comment by williamBoshi** [comment]
@LSZDota idk what he means cause issue 729 isn't related and idk what WAI mean but I tested with earth spirit ult and it doesn't dispels, I guess the shard doesn't dispel anything

**Comment by LSZDota** [comment]
WAI : Work as intended
Earth Spirit ult is not dispallable so Earthshock's shard shouldn't work on it.

I am still curious in Aluerie's take, she maybe found something that I missed.

**Comment by LSZDota** [comment]
Only the [incoming damage reduction](https://dota2.fandom.com/wiki/Incoming_damage_reduction) and [status resistance](https://dota2.fandom.com/wiki/Status_resistance) bonus are applied. Other of Enrage's cast effects (e.g. strong dispel) are not applied.

It is indeed not a bug, WAI. 
I will close this, my bad
