### ISSUE TITLE
Leshrac's "10% movespeed during Pulse Nova" doesn't work on Yasha-based items

### ISSUE THREAD

**Issue by jlkj11** [ValveSoftware/Dota2-Gameplay#13418]
### Ability name

Pulse Nova

### Description

As title says, Yasha-based items (that is, Manta Style, Yasha+Kaya and Yasha itself) don't count towards the amplification granted by Leshrac's talent. The talent works correctly with other movespeed-increasing items or skills.

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/120787118/d9a572c2-e084-4b0f-8dd4-6cdbab2a7f3b)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/120787118/8f9a2bbd-6cc5-45bb-b2de-0852626a03df)

### Example Match ID (and possibly Timestamp)

any

**Comment by commentator24** [comment]
#9823 can you upvote mine? i think they should fix it
