### ISSUE TITLE
Cannot ping items or runes in game

### ISSUE THREAD

**Issue by jarrito27** [ValveSoftware/Dota2-Gameplay#13436]
### Description

I have recently returned to dota after a long break, I since (3 months~) cannot ping any dropped items or runes simply the normal ping occurs on the selected spot. My left click ping is default.

**Comment by Aluerie** [comment]
means you set ping menu delay to 0. Try default which is 0.15

**Comment by jarrito27** [comment]
I had never changed this before, I had changed it to 1.0 at an attempt to fix, this was unsuccessful. 0.15 however has fixed it. Thank you very much!
