### ISSUE TITLE
Workshop Tools Crashing

### ISSUE THREAD

**Issue by zyunwei** [ValveSoftware/Dota2-Gameplay#13438]
### Description

Can not open, crash directly.

**Comment by LiuTaolang** [comment]
I have the same problem. I record the video of crashing. 

https://github.com/ValveSoftware/Dota2-Gameplay/assets/24557433/c919e3e8-974e-48d1-beeb-bb78506f1ab3

OS: Windows 11
Model - AMD Ryzen 5 5600G with Radeon Graphics
Processor Speed - 3.89 GHz
Cores - 6
Threads - 12
RAM - 32 GB

**Comment by LiuTaolang** [comment]
I ask my friends for testing but all failed. The second computer with i3 10105f, AMD RX 6400, 32G RAM; the third computer with i5 12100f, AMD RX6600, 16G RAM.  I update the lastest AMD drivers for their computers but still not work.

I try to find some log files in disk. but every time I try to launch the workshop tools, only webhelper.txt in "D:\Program Files (x86)\Steam\logs" modified:

[2023-11-11 14:31:05] SP Shared JS Context-'SharedJSCo': CreatingPopup name:notificationtoasts_6_desktop browser:65536 pid:9912 type:4 flags:1340266: (-2147483648.00, -2147483648.00) 424.50x105.00: url:about:blank?createflags=1340170&browserType=4
[2023-11-11 14:31:05] CBrowserComposerSystem::CreateOutputWindow: Creating browser window at: 805240832,805240832 size: 424x105
[2023-11-11 14:31:05] notificationtoasts_6_desktop: Created window: size: 424,105 pos: 805240832,805240832 mode: System window: 00000000007510D0
[2023-11-11 14:31:05] notificationtoasts_6_desktop: AfterCreated handle:6160386 type:4: (0, 0) 424x105
[2023-11-11 14:31:05] notificationtoasts_6_desktop-'notificati': WasHidden 0: (0, 0) 424x105
[2023-11-11 14:31:11] notificationtoasts_6_desktop-'notificati': WasHidden 1: (0, 0) 424x105

What to do then?

**Comment by Elyision01** [comment]
I am currently experiencing the same problem. It's exactly the same as the video above.

**Comment by larrylian** [comment]
Me too!  I have the same problem.

**Comment by zeebiedeebie** [comment]
I have the same issue. The video above shows my problem exactly.

**Comment by FiFTY4-f4** [comment]
Same problem. i guess it's valve fault

**Comment by brking014** [comment]
> 我有同样的问题。我录制了崩溃的视频。
> 
>  dota.2.work.shop.tools.crash.mp4 
> 操作系统： Windows 11 型号 - AMD Ryzen 5 5600G with Radeon Graphics 处理器速度 - 3.89 GHz 内核 - 6 线程 - 12 内存 - 32 GB

yes,me too

**Comment by chrisbog94** [comment]
This issue is impacting me as well. Requesting patch!

**Comment by BogdanDumi** [comment]
Same issue!
Env: Windows 11
<img width="284" alt="image" src="https://github.com/ValveSoftware/Dota2-Gameplay/assets/68294340/89e7886f-e065-46ce-adc1-211ed038f888">

**Comment by brking014** [comment]
> Same issue! Env: Windows 11 <img alt="image" width="284" src="https://user-images.githubusercontent.com/68294340/282296441-89e7886f-e065-46ce-adc1-211ed038f888.png">

only wait dota2 team repaired!!

**Comment by hobolyra** [comment]
Same issue. Guess it's a workshop tools problem in general.

**Comment by deanalvero** [comment]
This has been happening to me since that Dota 2 update last Friday.

**Comment by RyanEEEEE** [comment]
> This has been happening to me since that Dota 2 update last Friday.

That's the day I started, too. Problem solved.

I tried 1, run as administrator

2. There is no problem with memory detection

3. Turn off the DVR

4. Run in Windows 8 compatibility mode

5. The window system is updated to the latest

6, Microsoft Windows [version 10.0.22631.2428]

(c) Microsoft Corporation. All rights reserved.



C:\Windows\System32&gt; bcdedit.exe /set {current} nx AlwaysOn

The operation was successfully completed.



C:\Windows\System32&gt;

7. The hard disk is repaired

8, after Lenovo reformatted the hard disk to install the system

9. Reinstalled the software

Ultimately, there are problems.

**Comment by chrisbog94** [comment]
> > This has been happening to me since that Dota 2 update last Friday.
> 
> That's the day I started, too. Problem solved.
> 
> I tried 1, run as administrator
> 
> 2. There is no problem with memory detection
> 3. Turn off the DVR
> 4. Run in Windows 8 compatibility mode
> 5. The window system is updated to the latest
> 
> 6, Microsoft Windows [version 10.0.22631.2428]
> 
> (c) Microsoft Corporation. All rights reserved.
> 
> C:\Windows\System32> bcdedit.exe /set {current} nx AlwaysOn
> 
> The operation was successfully completed.
> 
> C:\Windows\System32>
> 
> 7. The hard disk is repaired
> 
> 8, after Lenovo reformatted the hard disk to install the system
> 
> 9. Reinstalled the software
> 
> Ultimately, there are problems.

I'm pretty good at reading... but you say 'problem solved', but also 'there are problems'.
Is the problem solved, or are there still problems? hahaha

What was your fix? a reformat?

**Comment by chrisbog94** [comment]
> Same issue. Guess it's a workshop tools problem in general. Windows 10, no logfile update so nothing to post there. EDIT: Ok so there is an Mdump file, and the Vconsole2 picking up some errors. seems a bunch of team and TI files can't be read or found, then it tosses out a cfg exception because it can't find the addon keys file, and crashes.
> 
> ` Loading Dump File [G:\SteamLibrary\steamapps\common\dota 2 beta\game\bin\win64\dota2_2023_1112_181320_0_accessviolation.mdmp] Comment: 'Crash Uptime( 11.086311 ) Total frames( 18446744073709551615 ) Current Map: '(unknown)' Addons: sfm VPK overrides: SpawnCount: 0 Command Line: "dota2.exe" -addon sfm -tools -steam Launch path: G:\SteamLibrary\steamapps\common\dota 2 beta\game\bin\win64\dota2.exe Build: 9846 (revision 8487172) OS: Windows 10 Pro (Build: 19045) (UBR: 3570) (Administrator User) OS type: Windows 10 (17) Windows Game DVR: not enabled Windows Game Mode: not active App UI Language: english, convar english, localization english_CA Windows user default LCID: 0x1009 Misc: rate 80000 update 0 latency 0 msec Net: Not Connected Time: Sun Nov 12 06:13:19 2023 Engine thread pool: 7 thread(s)
> 
> Render system: DX11 Driver Name: NVIDIA GeForce RTX 4090 Driver Version: 31.0.15.3758 VendorId / DeviceId: 0x10de / 0x2684 SubSystem / Rev: 0x40bf1458 / 0xa1 DXLevel: 110 Texture memory: 25,329,401,856 Vid: Windowed, render at 1900 x 1080, display at 1900 x 1080, refresh rate 0.00Hz (120Hz desktop) Version:0, cpu_level:2, mem_level:2, gpu_mem_level:2, defaultres:1900, defaultresheight:1080, gpu_level:3, version:1, knowndevice:0, recommendedwidth:1900, recommendedheight:2160, refreshrate_numerator:0, refreshrate_denominator:0, fullscreen:0, coop_fullscreen:0, nowindowborder:0, mat_vsync:0, fullscreen_min_on_focus_loss:1, high_dpi:0, cl_particle_fallback_base:0, cl_particle_fallback_multiplier:0, dota_cheap_water:0, r_deferred_height_fog:1, r_deferred_simple_light:1, r_ssao:1, cl_globallight_shadow_mode:2, r_dota_fxaa:1, r_deferred_additive_pass:1, dota_portrait_animate:1, r_deferred_specular_bloom:1, r_deferred_specular:1, dota_ambient_creatures:1, dota_ambient_cloth:1, r_texture_stream_mip_bias:0, r_dota_normal_maps:1, r_dashboard_render_quality:1, shaderquality:1, r_grass_quality:2, r_dota_allow_wind_on_trees:1, r_dota_allow_parallax_mapping:1, r_dota_bloom_compute_shader:1, r_depth_of_field:1, mat_viewportscale:1.000000,
> 
> System Memory: Memory load: 14% Total physical memory: 65439.95 MiB Free physical memory: 56082.18 MiB Total page file: 75167.95 MiB Free page file: 63341.25 MiB
> 
> ConVars (non-default):
> 
> ```
>                                            var                            value                          default
>                       engine_rendersystem_used                            -dx11                                 
>                       engine_rendersystem_init                            -dx11                                 
>               engine_rendersystem_shader_model                              110                                0
>                  engine_platform_name_extended                             pc64                                 
>                                  engine_ostype                       Windows 10                                 
>                       engine_cpu_info_extended 16 CPUs (8 cores), Frequency: 3.                                 
>                                           name                   I shoot letuce                          unnamed
>                          d3d_max_feature_level                             11_1                        <Not set>
>                      r_texturefilteringquality                                3                                1
>                            r_texture_pool_size                            23132                             1600
>                r_texture_stream_throttle_count                               10                                3
>                        soundsystem_device_used DFX Speakers (DFX Audio Enhancer                                 
>                    r_dota_bloom_compute_shader                                1                                0
>                  r_dota_allow_parallax_mapping                             true                            false
>                      dota_video_config.Version                                0                                 
>                     dota_video_config.VendorID                             4318                                 
>                     dota_video_config.DeviceID                             9860                                 
>            dota_video_config.setting.cpu_level                                2                                 
>            dota_video_config.setting.mem_level                                2                                 
>        dota_video_config.setting.gpu_mem_level                                2                                 
>           dota_video_config.setting.defaultres                             1900                                 
>     dota_video_config.setting.defaultresheight                             1080                                 
>            dota_video_config.setting.gpu_level                                3                                 
>              dota_video_config.setting.version                                1                                 
>          dota_video_config.setting.knowndevice                                0                                 
>     dota_video_config.setting.recommendedwidth                             1900                                 
>    dota_video_config.setting.recommendedheight                             2160                                 
> ```
> 
> dota_video_config.setting.refreshrate_numerator 0 dota_video_config.setting.refreshrate_denominator 0 dota_video_config.setting.fullscreen 0 dota_video_config.setting.coop_fullscreen 0 dota_video_config.setting.nowindowborder 0 dota_video_config.setting.mat_vsync 0 dota_video_config.setting.fullscreen_min_on_focus_ 1 dota_video_config.setting.high_dpi 0 dota_video_config.setting.dota_cheap_water 0 dota_video_config.setting.dota_portrait_animate 1 dota_video_config.setting.dota_ambient_creatures 1 dota_video_config.setting.dota_ambient_cloth 1 dota_video_config.setting.shaderquality 1 dota_video_config.setting.mat_viewportscale 1
> 
> Console History (reversed)
> 
> 477(10.963942): CGameEventManager::AddListener: event 'client_reload_addon_game_keyvalues' unknown. 476(10.956585): ReadSteamRemoteStorageFile( bufOut, "scripts/clientstorage.txt" ) -> 0.002461 seconds 475(10.954084): ReadSteamRemoteStorageFile( bufOut, "cfg/pending_replay_requests.lst" ) -> 0.000485 seconds 474(10.822697): Event System loaded 264 events from file: vpk:G:/SteamLibrary/steamapps/common/dota 2 beta/game/dota/pak01.vpk:resource/game.gameevents. 473(10.819682): Event System loaded 93 events from file: vpk:G:/SteamLibrary/steamapps/common/dota 2 beta/game/core/pak01.vpk:resource/core.gameevents. 472(10.810944): Loaded 80721 .vcds from 191 vcdlist files 471(10.510654): CClientSteamContext init ok, logged on = 1 470(10.465244): Failed loading resource "panorama/dynamic_images_heroes.vpdi_c" (ERROR_FILEOPEN: File not found) 469(10.465210): Failed loading resource "panorama/dynamic_images_abilities.vpdi_c" (ERROR_FILEOPEN: File not found) 468(10.465118): Failed loading resource "panorama/dynamic_images_set_portraits.vpdi_c" (ERROR_FILEOPEN: File not found) 467(10.465045): Failed loading resource "panorama/dynamic_images_profile_backgrounds.vpdi_c" (ERROR_FILEOPEN: File not found) 466(10.465008): Failed loading resource "panorama/dynamic_images_staging.vpdi_c" (ERROR_FILEOPEN: File not found) 465(10.464914): Failed loading resource "panorama/dynamic_images_ti7.vpdi_c" (ERROR_FILEOPEN: File not found) 464(10.464836): Failed loading resource "panorama/dynamic_images_ti8.vpdi_c" (ERROR_FILEOPEN: File not found) 463(10.464806): Failed loading resource "panorama/dynamic_images_ti9.vpdi_c" (ERROR_FILEOPEN: File not found) 462(10.464721): Failed loading resource "panorama/dynamic_images_ti10.vpdi_c" (ERROR_FILEOPEN: File not found) 461(10.464627): Failed loading resource "panorama/dynamic_images_spring2021.vpdi_c" (ERROR_FILEOPEN: File not found) 460(10.464606): Failed loading resource "panorama/dynamic_images_fall2021.vpdi_c" (ERROR_FILEOPEN: File not found) 459(10.464516): Failed loading resource "panorama/dynamic_images_ti11.vpdi_c" (ERROR_FILEOPEN: File not found) 458(10.464425): Failed loading resource "panorama/dynamic_images_ti12.vpdi_c" (ERROR_FILEOPEN: File not found) 457(10.464405): Failed loading resource "panorama/dynamic_images_events.vpdi_c" (ERROR_FILEOPEN: File not found) 456(10.464321): Failed loading resource "panorama/dynamic_images_plus.vpdi_c" (ERROR_FILEOPEN: File not found) 455(10.464224): Failed loading resource "panorama/dynamic_images_teamfandom_5_8131728.vpdi_c" (ERROR_FILEOPEN: File not found) 454(10.464207): Failed loading resource "panorama/dynamic_images_teamfandom_5_8318683.vpdi_c" (ERROR_FILEOPEN: File not found) 453(10.464118): Failed loading resource "panorama/dynamic_images_teamfandom_5_8169775.vpdi_c" (ERROR_FILEOPEN: File not found) 452(10.464022): Failed loading resource "panorama/dynamic_images_teamfandom_5_350190.vpdi_c" (ERROR_FILEOPEN: File not found) 451(10.464005): Failed loading resource "panorama/dynamic_images_teamfandom_5_8725475.vpdi_c" (ERROR_FILEOPEN: File not found) 450(10.463915): Failed loading resource "panorama/dynamic_images_teamfandom_5_8376696.vpdi_c" (ERROR_FILEOPEN: File not found) 449(10.463808): Failed loading resource "panorama/dynamic_images_teamfandom_5_8687717.vpdi_c" (ERROR_FILEOPEN: File not found) 448(10.463791): Failed loading resource "panorama/dynamic_images_teamfandom_5_8597976.vpdi_c" (ERROR_FILEOPEN: File not found) 447(10.463710): Failed loading resource "panorama/dynamic_images_teamfandom_5_8604954.vpdi_c" (ERROR_FILEOPEN: File not found) 446(10.463595): Failed loading resource "panorama/dynamic_images_teamfandom_5_8272699.vpdi_c" (ERROR_FILEOPEN: File not found) 445(10.463556): Failed loading resource "panorama/dynamic_images_teamfandom_5_7119077.vpdi_c" (ERROR_FILEOPEN: File not found) 444(10.463503): Failed loading resource "panorama/dynamic_images_teamfandom_5_726228.vpdi_c" (ERROR_FILEOPEN: File not found) 443(10.463392): Failed loading resource "panorama/dynamic_images_teamfandom_5_15.vpdi_c" (ERROR_FILEOPEN: File not found) 442(10.463354): Failed loading resource "panorama/dynamic_images_teamfandom_5_8680612.vpdi_c" (ERROR_FILEOPEN: File not found) 441(10.463301): Failed loading resource "panorama/dynamic_images_teamfandom_5_8180753.vpdi_c" (ERROR_FILEOPEN: File not found) 440(10.463190): Failed loading resource "panorama/dynamic_images_teamfandom_5_7391077.vpdi_c" (ERROR_FILEOPEN: File not found) 439(10.463151): Failed loading resource "panorama/dynamic_images_teamfandom_5_5014799.vpdi_c" (ERROR_FILEOPEN: File not found) 438(10.463098): Failed loading resource "panorama/dynamic_images_teamfandom_5_8261648.vpdi_c" (ERROR_FILEOPEN: File not found) 437(10.462988): Failed loading resource "panorama/dynamic_images_teamfandom_5_2586976.vpdi_c" (ERROR_FILEOPEN: File not found) 436(10.462950): Failed loading resource "panorama/dynamic_images_teamfandom_5_8724984.vpdi_c" (ERROR_FILEOPEN: File not found) 435(10.462894): Failed loading resource "panorama/dynamic_images_teamfandom_5_8668460.vpdi_c" (ERROR_FILEOPEN: File not found) 434(10.462789): Failed loading resource "panorama/dynamic_images_teamfandom_5_7453020.vpdi_c" (ERROR_FILEOPEN: File not found) 433(10.462750): Failed loading resource "panorama/dynamic_images_teamfandom_5_4.vpdi_c" (ERROR_FILEOPEN: File not found) 432(10.462698): Failed loading resource "panorama/dynamic_images_teamfandom_5_7407260.vpdi_c" (ERROR_FILEOPEN: File not found) 431(10.462576): Failed loading resource "panorama/dynamic_images_teamfandom_5_6209166.vpdi_c" (ERROR_FILEOPEN: File not found) 430(10.462530): Failed loading resource "panorama/dynamic_images_teamfandom_5_7356881.vpdi_c" (ERROR_FILEOPEN: File not found) 429(10.462478): Failed loading resource "panorama/dynamic_images_teamfandom_5_8525778.vpdi_c" (ERROR_FILEOPEN: File not found) 428(10.462373): Failed loading resource "panorama/dynamic_images_teamfandom_5_2289950.vpdi_c" (ERROR_FILEOPEN: File not found) 427(10.462327): Failed loading resource "panorama/dynamic_images_teamfandom_5_8421850.vpdi_c" (ERROR_FILEOPEN: File not found) 426(10.462281): Failed loading resource "panorama/dynamic_images_teamfandom_5_8724829.vpdi_c" (ERROR_FILEOPEN: File not found) 425(10.462172): Failed loading resource "panorama/dynamic_images_teamfandom_5_5055770.vpdi_c" (ERROR_FILEOPEN: File not found) 424(10.462124): Failed loading resource "panorama/dynamic_images_teamfandom_5_5.vpdi_c" (ERROR_FILEOPEN: File not found) 423(10.462079): Failed loading resource "panorama/dynamic_images_teamfandom_5_8261500.vpdi_c" (ERROR_FILEOPEN: File not found) 422(10.461968): Failed loading resource "panorama/dynamic_images_teamfandom_5_6209804.vpdi_c" (ERROR_FILEOPEN: File not found) 421(10.461918): Failed loading resource "panorama/dynamic_images_teamfandom_5_8260983.vpdi_c" (ERROR_FILEOPEN: File not found) 420(10.461880): Failed loading resource "panorama/dynamic_images_teamfandom_5_8360138.vpdi_c" (ERROR_FILEOPEN: File not found) 419(10.461769): Failed loading resource "panorama/dynamic_images_teamfandom_5_8545488.vpdi_c" (ERROR_FILEOPEN: File not found) 418(10.461717): Failed loading resource "panorama/dynamic_images_teamfandom_5_8582076.vpdi_c" (ERROR_FILEOPEN: File not found) 417(10.461675): Failed loading resource "panorama/dynamic_images_teamfandom_5_8721219.vpdi_c" (ERROR_FILEOPEN: File not found) 416(10.461561): Failed loading resource "panorama/dynamic_images_teamfandom_5_8255756.vpdi_c" (ERROR_FILEOPEN: File not found) 415(10.461515): Failed loading resource "panorama/dynamic_images_teamfandom_5_8126892.vpdi_c" (ERROR_FILEOPEN: File not found) 414(10.461477): Failed loading resource "panorama/dynamic_images_teamfandom_5_8261554.vpdi_c" (ERROR_FILEOPEN: File not found) 413(10.461359): Failed loading resource "panorama/dynamic_images_teamfandom_5_8599101.vpdi_c" (ERROR_FILEOPEN: File not found) 412(10.461313): Failed loading resource "panorama/dynamic_images_teamfandom_5_7732977.vpdi_c" (ERROR_FILEOPEN: File not found) 411(10.461275): Failed loading resource "panorama/dynamic_images_teamfandom_5_7119388.vpdi_c" (ERROR_FILEOPEN: File not found) 410(10.461149): Failed loading resource "panorama/dynamic_images_teamfandom_5_8291895.vpdi_c" (ERROR_FILEOPEN: File not found) 409(10.461110): Failed loading resource "panorama/dynamic_images_teamfandom_5_8574561.vpdi_c" (ERROR_FILEOPEN: File not found) 408(10.461071): Failed loading resource "panorama/dynamic_images_teamfandom_5_111474.vpdi_c" (ERROR_FILEOPEN: File not found) 407(10.460920): Failed loading resource "panorama/dynamic_images_teamfandom_5_8261882.vpdi_c" (ERROR_FILEOPEN: File not found) 406(10.460889): Failed loading resource "panorama/dynamic_images_teamfandom_5_8376426.vpdi_c" (ERROR_FILEOPEN: File not found) 405(10.460865): Failed loading resource "panorama/dynamic_images_teamfandom_5_8605863.vpdi_c" (ERROR_FILEOPEN: File not found) 404(10.460710): Failed loading resource "panorama/dynamic_images_teamfandom_5_8260932.vpdi_c" (ERROR_FILEOPEN: File not found) 403(10.460666): Failed loading resource "panorama/dynamic_images_teamfandom_5_36.vpdi_c" (ERROR_FILEOPEN: File not found) 402(10.460644): Failed loading resource "panorama/dynamic_images_teamfandom_5_8607159.vpUser Mini Dump File: Only registers, stack and portions of memory are available
> 
> ************* Path validation summary ************** Response Time (ms) Location Deferred srv* Symbol search path is: srv* Executable search path is: Windows 10 Version 19045 MP (16 procs) Free x64 Product: WinNt, suite: SingleUserTS Debug session time: Sun Nov 12 18:13:20.000 2023 (UTC - 7:00) System Uptime: not available Process Uptime: 0 days 0:00:15.000 ................................................................ ................................................................ ................................................................ .................. Loading unloaded module list ................. This dump file has an exception of interest stored in it. The stored exception information can be accessed via .ecxr. (1450.d54): Access violation - code c0000005 (first/second chance not available) For analysis of this file, run !analyze -v ntdll!NtGetContextThread+0x14: 00007fff`925aee34 c3 ret `

I opened a ticket with Valve regarding this... and provided my mdmp file for analysis... thanks to Dimitris and Nick from the support team for closing my ticket: HT-FGC7-3X85-7QDR

Here's what they said:
> Thanks for writing in. Steam support does not provide specific assistance for the creation and curation of Dota 2 Workshop content.

**Comment by RyanEEEEE** [comment]
> 我很擅长阅读……但你说“问题已解决”，但也说“存在问题”。 问题解决了吗，还是还有问题？哈哈
> 
> 如果您重新格式化 并且是不需要的信息，则此行“bcdedit.exe /set {current} nx AlwaysOn”之前的所有内容都将被删除/重置

Sorry for the input error, the final result is still not solved, or crashed, not only workshop, but also me.

**Comment by AlanPony** [comment]
[crash_dota2.exe_20231114210417_1.dmp](https://github.com/ValveSoftware/Dota2-Gameplay/files/13353732/crash_dota2.exe_20231114210417_1.dmp)

Same problem. I had crash Dota 2 WorkShop Tools

CPU Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz   3.50 GHz
RAM 16
GPU GeForce GTX 960 4 Gb
OS: Windows 10 Pro 21H2

**Comment by oddtrix** [comment]
Guys!!! Just had an update (10-15 minutes ago) and I got tuls open!!! (Problem was the same as in the video) Try it!

**Comment by zyunwei** [comment]
Fixed.

**Comment by zyunwei** [comment]
Fixed.
