### ISSUE TITLE
I can't re-bundle items

### ISSUE THREAD

**Issue by Haunterrr** [ValveSoftware/Dota2-Gameplay#13465]
### Description

Hello!

Can someone please explain to me why I can't re-bundle items of "Gambits of Nishai" into a set? I have all the pieces of it, all the pieces are marketable, not equipped, and tradable so why can't I re-bundle it? Just an error with "The bundle for this item cannot be re-bundled" and that's all, no more explanations.

P.s. Where can I even read official instructions or guidance on this?
![Screenshot from 2023-11-12 00-44-10](https://github.com/ValveSoftware/Dota2-Gameplay/assets/12453075/3f12a10c-9f56-4eee-884b-79f2cbf1d4b2)
![Screenshot from 2023-11-12 00-40-59](https://github.com/ValveSoftware/Dota2-Gameplay/assets/12453075/5ab06405-621e-439b-827d-700b1788c5f3)
![Screenshot from 2023-11-12 00-40-01](https://github.com/ValveSoftware/Dota2-Gameplay/assets/12453075/e2e44de8-8c81-43d2-aff8-5edc7241ba16)

### Example Match ID (and possibly Timestamp)

7364200736

**Comment by mihaly99** [comment]
Dota 2 Update - 9/1/2023
"Disabled rebundling for items with unlocked styles, or which unpack with dynamic gems"

Gambits of Nishai used to have 2 styles & was changed later on I guess, might be the internal tag hasn't been changed yet

https://www.reddit.com/r/DotA2/comments/k3rj6w/til_that_gambits_of_nishai_has_2_styles_but_the/
