### ISSUE TITLE
behavior problem valve fix

### ISSUE THREAD

**Issue by sommerVA** [ValveSoftware/Dota2-Gameplay#13467]
### Description

behavior score just falling down for no reason can valve fix alredy
unlimited reports for all DOTA2 players what a joke 
and delete party players from immortal drafts thanks 

### Example Match ID (and possibly Timestamp)

-

**Comment by marcelmaster** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/13340
same here , upvote please ( thumbs up )
