### ISSUE TITLE
Я удалил эту игру и больше не скачаю.

### ISSUE THREAD

**Issue by arturkrugol** [ValveSoftware/Dota2-Gameplay#13481]
### Description

Любите руинить доту последние годы. Хорошо. Вы заслуживате того, чтобы онлайн падал постоянно.

1) Заруинили раз систему порядочности
2) Заруинил Интернешнл
3) Заруинили 2 раз систему порядочности, хуевы экспериментаторы.

Нахуй вы вообще там работаете тупые ублюдки. Просто заебало. Просто удалил эту парашу навсегда.

**Comment by Memoframe** [comment]
Touch some grass.

**Comment by AlanPony** [comment]
Проблема решена, поздравляю

**Comment by arturkrugol** [comment]
> Проблема решена, поздравляю

Что вы имеете ввиду?
