### ISSUE TITLE
Keyboard input not working for items with non English keyboard

### ISSUE THREAD

**Issue by MatasLTP** [ValveSoftware/Dota2-Gameplay#13534]
### Description

Hello,
We noticed for couple of months now that when playing for example with Lithuanian keyboard you can't use items with key bindings. After switching language back to english keyboard everything works fine. 

It's a minor bug but when it occurs it's really annoying.

Thank you

**Comment by Aluerie** [comment]
Have you tried bind keys based on keyboard position setting

**Comment by MatasLTP** [comment]
Thanks, just tested it works

**Comment by Aluerie** [comment]
You can close your issue then
