### ISSUE TITLE
Phylactery do not work with Spectre spectral  dagger

### ISSUE THREAD

**Issue by MerovingL** [ValveSoftware/Dota2-Gameplay#13579]
### Item name

Phylactery 

### Description

Spectre spectral  dagger type: Target Point / Target Unit
Phylactery description: The next single target spell you cast on an enemy deals a separate 150 bonus damage to the target and slows them by 50% for 1.5 seconds.

Phylactery do not work with Spectre spectral  dagger when target unit

**Comment by Aluerie** [comment]
#8572 #12579

**Comment by commentator24** [comment]
@MerovingL should close issue, works now
