### ISSUE TITLE
alt+` dont work after patch

### ISSUE THREAD

**Issue by shadle1** [ValveSoftware/Dota2-Gameplay#13594]
### Description

after today patch i cant use alt+`,
this keyboard shortcut doesn't work for anything in dota right now
also, when I switch to another language, the alt+` or alt+ё (ru layout) button changes along with the language on the computer, this has not happened before

valve fix that please...

**Comment by Aluerie** [comment]
> after today patch

alt + ` never worked in dota. 

for language just turn on "bind keys based on keyboard position" on.

**Comment by shadle1** [comment]
> > after today patch
> 
> alt + ` never worked in dota.
> 
> for language just turn on "bind keys based on keyboard position" on.

it worked for at least 2 years, I somehow pressed the neutral item)
and what is the "bind key based on keyboard position" setting? I have no idea where it is, I have never turned it on or off

**Comment by shadle1** [comment]
> #158

oh, it really just flew off the setup (though without my participation), the existence of which I did not even know. thanks
