### ISSUE TITLE
Chat wheel sprays are broken

### ISSUE THREAD

**Issue by erxor-github** [ValveSoftware/Dota2-Gameplay#13604]
### Description

Chat wheel sprays show up as blank on the ground. Tried multiple team liquid sprays. Not sure if other sprays have this issue as I only have a couple unlocked.

### Screenshots

![20231119091740_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/107615194/3219d874-2ec9-4446-b779-91188c7127d9)

**Comment by Aluerie** [comment]
arent they supposed to expire after TI? so the real bug here is that you can use them at all?

**Comment by erxor-github** [comment]
> werent they supposed to expire after TI? so the real bug here is that you can use them at all?

They changed the supporters packs so that the rewards are permanent. Same with the chat wheel lines in the compendium.

From ["The International 2023 Celebration"](https://www.dota2.com/international2023?1) blog post

_Supporters Club Rewards are like the joys of youth — enjoy them while you can, because they're fleeting. Or at least they were. Starting now, they're permanent! So now you can enjoy them forever! Unless you get hit by a bus._

**Comment by ctulloch137** [comment]
Would be great if this was fixed some day...  Still having this with ALL sprays

**Comment by chrisf-valve** [comment]
Hello, this issue should be fixed in our most recent update. If you are still unable to use your sprays please leave a comment and I’ll take a look.

**Comment by erxor-github** [comment]
You're amazing @chrisf-valve

Many thanks for the update
