### ISSUE TITLE
7.34e Witch Doctor ulti + aghs crashes the game

### ISSUE THREAD

**Issue by Fermander** [ValveSoftware/Dota2-Gameplay#13660]
### Ability name

Death Ward

### Description

Witch doctor ultimate with aghanim crashes the game, probably due to the change to its targeting mechanics in 7.34e. 

Steps to replicate:
1. Go to demo and select Witch Doctor.
2. Level witch doctor to 6 and skill Death Ward.
3. Give Witch Doctor aghanim's upgrade.
4. Create an enemy Phantom Lancer and skill Doppelwalk.
5. Cast Death Ward with Witch Doctor.
6. Cast Doppelwalk with PL.

This isn't dependent on PL, the crash happened to me in a game with no PL, it's probably something to do with illusions or losing a target/switching target. Not sure. But it's crashing games pretty reliably.

### Example Match ID (and possibly Timestamp)

can't enter

**Comment by Avarise831** [comment]
#13659

**Comment by uraniumheart** [comment]
Can't enter the match ID since it crashed the server, but two games in a row crashed when Aghanims Shard was used with multiple heroes in the area I believe.

**Comment by hperera1** [comment]
patched. close report.

**Comment by Nathanael-Valve** [comment]
Fixed
