### ISSUE TITLE
Helm of the Overlord Alt-text is incorrect

### ISSUE THREAD

**Issue by smurrei** [ValveSoftware/Dota2-Gameplay#137]
### Hero and spell

Helm of the Overlord - Alt-text

### Description

The alt-text of the item is wrong. It says "Can dominate up to two at a time."

This is incorrect because that functionality has been removed.

### Screenshots

[Here](https://imgur.com/a/qZnQWM3)

**Comment by shaileshgarg** [comment]
Still not fixed.

**Comment by smurrei** [comment]
See's "Fixed a multitude of tooltips" in the patchnotes.

Goes to check... Nope, still not fixed Sadge

**Comment by Avarise831** [comment]
This has been fixed in some recent patch

**Comment by smurrei** [comment]
Closed due to being fixed.
