### ISSUE TITLE
Set (unpacked/packed) does not show under preview in hero loadout 

### ISSUE THREAD

**Issue by tieko3000** [ValveSoftware/Dota2-Gameplay#1375]
### Description

The set (in my case "Upland Pride") does not show under set preview in hero loadout and neither as unpacked nor as available set. 
The individual skins only show on the individual slots.
Due to this I have opened this very rare and not marketable/tradeable disruptor set "Upland Pride" a second time.

In case this doesn't cause too much trouble for you, I would also appreciate if my set could be unpacked again.

Thank you for keeping dota great and making it better. Love you all!

### Screenshots

![Screenshot 2022-06-17 212208](https://user-images.githubusercontent.com/84246857/174389357-ef05062f-b3ee-448a-9f38-e83121c3bbe6.png)
![Screenshot 2022-06-17 212237](https://user-images.githubusercontent.com/84246857/174389367-2a0d8c62-8778-4af3-a257-3eb05a0a6e60.png)

**Comment by shaileshgarg** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/259
