### ISSUE TITLE
Holding Shift while moving items around in your inventory adds actions to the shift-queue, which don't clear normally

### ISSUE THREAD

**Issue by anko** [ValveSoftware/Dota2-Gameplay#1401]
### Description

Repro steps:

1. Purchase any item.
2. Hold <kbd>Shift</kbd>.
3. Drag item from one inventory slot to another.

The item's icon will appear as a queued action, as if you had shift-queued it.  The actual item move happens immediately regardless of how many actions are queued, so the queue icons serve no purpose. These item-related queue icons linger for about 1 minute before clearing.

(Dropping items can also be shift-queued, and that works normally.)

It would be nice if item move within the inventory could be shift-queued properly. Then you could for example have a full inventory with an Observer Ward in one slot, and shift-queue placing the ward, then shift-queue moving an item from the backpack into the now-vacant slot where the ward used to be.  Currently, the item move happens immediately, and swaps your ward into your backpack, so the queue is interrupted once it gets to the warding step, with an error of "Item must be in inventory to use".

### Example Match ID (and possibly Timestamp)

Happen in any match, and in demo mode

### Screenshots

https://user-images.githubusercontent.com/5231746/174448578-4f7713e7-356c-42e0-a4da-001b7be944a6.mp4

**Comment by Stephanie55** [comment]
This is very annoying indeed. I removed "show Queued Orders On the HUD" because of it.

**Comment by eugene-valve** [comment]
Thanks for reporting this, this should be fixed in an upcoming update.
