### ISSUE TITLE
Bug with dota 2 guides 

### ISSUE THREAD

**Issue by Athroenus** [ValveSoftware/Dota2-Gameplay#14049]
### Description

Apperantly there is a bug with in-game dota 2 guides, when you want to click them they didn't show at all or takes a years to load. I mean i don't necessarily need them but this could be crucial for new players who wants to learn something by natural way and they can't. 

### Example Match ID (and possibly Timestamp)

7475314739 12/6/2023 3:51 PM

### Screenshots

![Screenshot_3](https://github.com/ValveSoftware/Dota2-Gameplay/assets/153099702/b9a04561-2f5a-467a-8fc0-619eeabc8b73)

**Comment by alexeik** [comment]
2 weeks ago...
too bad) that developers does not play dota2:)
