### ISSUE TITLE
Rubick spell steal on quickcast players

### ISSUE THREAD

**Issue by orczz** [ValveSoftware/Dota2-Gameplay#14094]
### Ability name

Spell steal

### Description

Rubick also steals the quick cast setting from the players that have it enabled it on abilities. It happened in this game when stealing any spell from Pugna. 

### Example Match ID (and possibly Timestamp)

7480245073 - 24:14, 33:02

**Comment by Aluerie** [comment]
R u sure it's not yours

**Comment by orczz** [comment]
> R u sure it's not yours

I triple checked my settings, enabled and disabled quickcast and nothing changed. And it only happened to pugna spells, no other spells that game.
