### ISSUE TITLE
Guides are not working!

### ISSUE THREAD

**Issue by IMAVIA** [ValveSoftware/Dota2-Gameplay#14105]
### Hero and spell

Any hero

### Description

The guides do not work even after reinstalling or checking the game files. Please fix this asap!

### Screenshots

![ZvgNtlauY4w](https://github.com/ValveSoftware/Dota2-Gameplay/assets/153443119/56a56498-10cc-41cc-8012-147343f21780)

**Comment by PlimpyD** [comment]
A plus one to this.
