### ISSUE TITLE
You can't sell the item: Bloodfeather Frock

### ISSUE THREAD

**Issue by 1100VIRUS1001** [ValveSoftware/Dota2-Gameplay#14111]

**Comment by irismus** [comment]
#13573 
Please close this and move all of your info to that ticket. Thanks!

**Comment by Hosi123** [comment]
a there a way to solve this problem ?

**Comment by AdmiralMonkey** [comment]
> a there a way to solve this problem ?

I think there's nothing, how u can solve it. W8 for Gaben, it's 2 month in, and still nothing. We get trouble and valve get money, ez for em, like always)
