### ISSUE TITLE
cant trade or sell Bloodfeather Frock 

### ISSUE THREAD

**Issue by ghqp14** [ValveSoftware/Dota2-Gameplay#14123]
### Item name

Bloodfeather Frock Bloodfeather Boots Dancing Queen-#570

### Description

cant trade or sell Bloodfeather Frock please help me
Dancing Queen-#570_2_28657953683
Bloodfeather Boots-#570_2_28657953531
Bloodfeather Frock-#570_2_28658905091

### Example Match ID and Timestamp

Dancing Queen-#570_2_28657953683 Bloodfeather Boots-#570_2_28657953531 Bloodfeather Frock-#570_2_2865890509

**Comment by Hosi123** [comment]
could u find a way for that ?
