### ISSUE TITLE
Problem getting the key.

### ISSUE THREAD

**Issue by losyash1** [ValveSoftware/Dota2-Gameplay#14140]
### Description

I bought a key for 20 thousand shards, in the history is displayed, but the key itself I did not get, and I can not open the case.

What should I do?

P.s. provide skirnshots.

### Example Match ID (and possibly Timestamp)

-

### Screenshots

![Screenshot 2023-12-13 061546](https://github.com/ValveSoftware/Dota2-Gameplay/assets/102725678/2274c13f-8d9d-4cbb-af97-3d2592071615)
![Screenshot 2023-12-13 061157](https://github.com/ValveSoftware/Dota2-Gameplay/assets/102725678/bdccda5f-d2e5-4712-9f7e-ddc3f10e7d84)

**Comment by NAlexP** [comment]
Try steam support.
