### ISSUE TITLE
Autoattack settings are disregarded on start up.

### ISSUE THREAD

**Issue by Fjara-h** [ValveSoftware/Dota2-Gameplay#1415]
### Description

I've posted about this several times on the dev forums, it was fixed for a day or two with the spring cleaning update, but quickly became in issue again.

Auto attack setting is ignored, I have both my hero and summoned units autoattack set to "Never", everytime Dota is launched, it acts as though "Standard" is selected, even though it isn't and the radial is selected on "Never" in the settings. If I switch off of "Never" to any other option, and then reselect "Never", it works like it should. This works as intended until I restart the client.

For whatever reason, in demo mode it works fine ons tartup, however in bot, custom, matchmaking, and private lobbies it does not. 

In console "dota_player_units_auto_attack_mode" and "dota_summoned_units_auto_attack_mode_2" return 0 even when it isn't functioning that way.

I've tried completely all my settings (several times), as in, I forced steam to forget everything about my dota settings and what not so I had to completely re-setup everything, except this still occurred immediately after doing this with otherwise totally default settings, no launch params, no autoconfig, etc.

Here is a video showing the problem, how it is fixed, and how it repeats: https://www.youtube.com/watch?v=ElMqSLP2RM4

If I can provide more info or config files or anything let me know.

**Comment by opomuc** [comment]
I've never seen or noticed such behavior. Do you use any console settings in `autoexec.cfg`?

**Comment by Fjara-h** [comment]
This has been resolved as of 7.32 release.

**Comment by andrei128x** [comment]
No, actually with 7.32 the file user_convars_*.vcfg get overwritten with some default values each time the game starts, making it incredibly annoying; Cloud Sync setting do not affect this bug.

**Comment by Fjara-h** [comment]
Now fixed once again from something in the past week or so.

**Comment by Fjara-h** [comment]
occuring again
