### ISSUE TITLE
Facelessvoid scepter not adding reverse time walk

### ISSUE THREAD

**Issue by fob362** [ValveSoftware/Dota2-Gameplay#14159]
### Ability name

reverse time walk (scepter)

### Description

when i buy scepter the ability button doesnt appear
![Screenshot 2023-12-15 044947](https://github.com/ValveSoftware/Dota2-Gameplay/assets/153878811/6e7bd697-4b8d-4a0b-b7c2-20bc3e0658e3)

### Example Match ID (and possibly Timestamp)

demo

**Comment by Dota-Exp** [comment]
reverse time walk is granted by Shard
