### ISSUE TITLE
Mini-map settings missed displaying Hero Names instead of Color Arrows

### ISSUE THREAD

**Issue by ZivilynNks** [ValveSoftware/Dota2-Gameplay#14178]
### Description

After patch 7.35 the update with mini-map, display Hero Names isn't supported. For some players like me who most use that it is unacceptable and torturing to use other mini-map figures. Please rewind some changes you have done, which are important for us. 

### Example Match ID (and possibly Timestamp)

none

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/121831621/6ec92384-f42c-4d2a-96ab-2161183d8296)
Quite hard to catch those running arrows, when the background is colorful too.

**Comment by bringbackheronames** [comment]
+

**Comment by Gee-had** [comment]
this update made me hate this game. please bring back hero names on the minimap. you left us with the worst and usles options.
thank you.
