### ISSUE TITLE
Map background option visual stuck

### ISSUE THREAD

**Issue by nijbuu** [ValveSoftware/Dota2-Gameplay#14185]
### Description

Checkbox appears to be stuck, correct setting is applied and reopening settings fixes.

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/9077011/e48359ab-a294-43d1-8c57-54a0adff58ec)

**Comment by commentator24** [comment]
#14179

**Comment by commentator24** [comment]
this seems fixed today, should close the issue
