### ISSUE TITLE
我需要小地图英雄名称显示

### ISSUE THREAD

**Issue by wanhuashisjian** [ValveSoftware/Dota2-Gameplay#14193]
### Description

我需要在小地图中显示英雄名称，而不是英雄图标。小地图游戏名称在7.35更新后被删掉了。
只有图标，我没法快速告诉队友英雄名称、影响沟通效率。
![Image_1702617252811](https://github.com/ValveSoftware/Dota2-Gameplay/assets/153888271/73eb2986-7116-4c2b-adab-f01f0c033d28)

**Comment by pinkido** [comment]
Give back hero names in minimap!
强烈支持，和当时单位信息不占用英雄面板一样，这种功能虽然用的人少总有人用，但是V社问都不问就删掉
Strongly support. Similar to the situation when removing unit information not occupying the hero panel, although this feature is used by a minority, there are always people using it. However, without any inquiry, Valve simply and brutally removed it.

**Comment by jsjxbjyg** [comment]
需要文字，文字信息比图标直接

**Comment by weifong208** [comment]
+1

**Comment by zz106x** [comment]
I need words to represent heroes on the minimap

**Comment by wanhuashisjian** [comment]
Ame直播也在说，需要这个小地图显示英雄名称的功能

**Comment by UNKN-OWN** [comment]
we need it, bring it back pls

**Comment by thjiang** [comment]
支持一下，这个功能特别重要，极度不适应，我刚才刚打开游戏玩了一把就放弃了

**Comment by Jiangsc** [comment]
bring it back！！！！

**Comment by monkeyhzyyy** [comment]
支持，V社真的恶心

**Comment by hatred229** [comment]
agreed. I don't see any point removing this feature

**Comment by h1102970406** [comment]
+1

**Comment by bringbackheronames** [comment]
pls read my username

**Comment by wanhuashisjian** [comment]
upup

**Comment by qxt610505633** [comment]
请恢复小地图上显示英雄名称的功能，中文文字就是图像，这个功能对中文来说很方便。
Please reinstate the ability to display hero names on the mini-map, as Chinese characters are images and this feature is very convenient for Chinese users.

**Comment by weitong123456** [comment]
+1！！！！！！！！！Agree！！！！！I have been using this setting for 10 years！Surprisingly, it changed today？？？？？I can't get used to it！！！！

**Comment by iorileslie** [comment]
+10086

**Comment by wanhuashisjian** [comment]
已经改了
