### ISSUE TITLE
Chen Recall Bug - Talent for Teleport Delay Not Working

### ISSUE THREAD

**Issue by elurzen** [ValveSoftware/Dota2-Gameplay#14197]
### Ability name

Divine Favor

### Description

Chen's level 10 talent still states "-2s Holy Persuasion Teleport Delay" after the change to Divine Favor being the skill to recall creeps. When leveling up the talent the time to teleport creeps to Chen is still 6 seconds

**Comment by sikleq** [comment]
Yeah since the talent is linked to Holy Persuasion. Imo, they should just remove that useless talent and replace it to something like +10% ms speed buff to teleported units for 6 seconds or so.
