### ISSUE TITLE
Tutorial Bug - Tier 4 Advanced Tactics

### ISSUE THREAD

**Issue by LittleRanga** [ValveSoftware/Dota2-Gameplay#14205]
### Description

Hey Guys,

In the tier 4 tutorials, the tutorial called Advanced Items requires you to dissemble arcane boots, patch 7.35 changed arcane boots to not be able to be dissembled. 

https://www.dota2.com/patches/7.35

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/153897245/163370a6-9267-498d-8e13-18f23028c6a5)

**Comment by eugene-valve** [comment]
This should be fixed in an upcoming update, thank you for the bug report!
