### ISSUE TITLE
I need words to represent heroes on the minimap

### ISSUE THREAD

**Issue by zz106x** [ValveSoftware/Dota2-Gameplay#14211]
### Description

I need to use words to represent heroes on the minimap. Words are more concise and intuitive in some languages, and a considerable number of players are using this setting. Modifying this setting will cause great inconvenience to these players.

**Comment by weitong123456** [comment]
+1！！！！！！！！！Agree！！！！！I have been using this setting for 10 years！Surprisingly, it changed today？？？？？I can't get used to it！！！！

**Comment by commentator24** [comment]
#14193
