### ISSUE TITLE
Last Word (LW) damage calculation vs creeps (zero attributes = 0 int) appears bugged with new patch 7.35

### ISSUE THREAD

**Issue by WilliamAtlas** [ValveSoftware/Dota2-Gameplay#14217]
### Ability name

Last Word

### Description

Had to check the wiki which states LW deals the base damage and Silencer's current Intelligence to units without [attributes] (e.g. lane creeps). In an attempt to isolate hitting the test dummy with 300+ int Silencer seems to be calculating this interaction correctly with 0 Int -> 900dmg last word. Creeps appear to still be only taking around 400dmg leaving creeps on one/two hits to CS when in previous patch you could clear waves with Last Word and 100+ Int. 

Haven't yet jumped into a game on the new patch to get a Match ID but previous patch ID + timestamp clearly show LW ability to one-shot waves with 169 Int - creeps in this instance have 598hp and 0% magic res.

### Example Match ID (and possibly Timestamp)

7481354399 (35:55)

**Comment by TKler** [comment]
fixed at least since .35b
Thanks
