### ISSUE TITLE
I recieved Toxic coal on my main account

### ISSUE THREAD

**Issue by ScaredByBeauty** [ValveSoftware/Dota2-Gameplay#14248]
### Item name

Toxic coal

### Description

It's my main account. I've been using it since 2013 and never been toxic to anyone else. Never gave to anyone my account so why I do get a toxic coal for? I don't get it, please explain it to me or remove it.
id: 88160180
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/153932939/46485f2a-8e7f-4123-a8ea-6a7e8a369f8c)

### Example Match ID and Timestamp

88160180

**Comment by TobyFlendersonFromHR** [comment]
No explanation needed, also no removal, enjoy your ban. 

Have a Merry Christmas!

**Comment by commentator24** [comment]
you probably got caught smurfing / evading punishment on your 2nd accounts

a main account found associated with a smurf account could result in a wide range of punishments, from temporary adjustments to behavior scores to permanent account bans.

**Comment by t0bi971** [comment]
> Объяснений не требуется, удаления также нет, наслаждайтесь своим баном.
> 
> Счастливого Рождества!

То есть если на моем ip используеться 2 аккаунта, 1 мой, 2 жены то это наказуемо !? Где такое в правилах прописано или где доказательства смурфинга !? Если уж меня обвинили будьте добры доказать мою вину !
