### ISSUE TITLE
Mid-Game Progression tutorial is broken

### ISSUE THREAD

**Issue by Grammis** [ValveSoftware/Dota2-Gameplay#14305]
### Description

In the tutorial you are required to purchase a Quarterstaff to build your Echo Sabre but the latest patch changed the items required to build an Echo Sabre making the tutorial impossible to complete.

### Screenshots

![Echo Sabre](https://github.com/ValveSoftware/Dota2-Gameplay/assets/65136693/92f2d11b-bf11-4456-92fe-9fcda41dc9ca)

**Comment by troutnut68** [comment]
So glad you posted this already.  Was here to report it myself.

**Comment by UnixNight** [comment]
Also the enemy in the beginning of the game is missing a model

![20231217192310_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/17035391/8440b546-8319-47ab-9f9d-dafba0947536)

**Comment by Grammis** [comment]
> Also the enemy in the beginning of the game is missing a model
> 
> ![20231217192310_1](https://private-user-images.githubusercontent.com/17035391/291115725-8440b546-8319-47ab-9f9d-dafba0947536.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MTExMzQsIm5iZiI6MTcwMjkxMDgzNCwicGF0aCI6Ii8xNzAzNTM5MS8yOTExMTU3MjUtODQ0MGI1NDYtODMxOS00N2FiLTlmOWQtZGFmYmEwOTQ3NTM2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDE0NDcxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5Njk1N2I1ZmExNjU1MWQ2ODQ2NzA0YjQ5MGU5ODExMmYxODVmYTY5MGNiMDUyODQ0NmY0N2U1ODY4YmE2NTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s-50dbMtWObOI2hXD9U75pZ6A-x1DvsQAHyVnzeWVEg)

This wasn't an issue for me.

![Echo Sabre2](https://github.com/ValveSoftware/Dota2-Gameplay/assets/65136693/ba0d431e-ff8d-4047-8c53-c5b2bd3297f2)

**Comment by eugene-valve** [comment]
This should be fixed in an upcoming update, thanks for reporting this!
