### ISSUE TITLE
Parasma is missing 1.5 mana regen

### ISSUE THREAD

**Issue by HEISEN3ERG** [ValveSoftware/Dota2-Gameplay#14344]
### Item name

Parasma

### Description

Witchblade gives you 1.5 mana regen, but when upgraded to Parasma, you lose the 1.5 mana regen, also, the parasma tooltip is missing the 1.5 mana regen too

### Example Match ID and Timestamp

0

**Comment by LHitmaN** [comment]
There is also missing True Strike in the passive of witchblade in Parasma, i've tested it vs PA 6 bfly in demo, seems like the true strike works

**Comment by LHitmaN** [comment]
If u lock witch blade and buy mystic staff u get more regen when u combine them into parasma
