### ISSUE TITLE
Right now anyone can crash(ranked) lobbies on demand when they lose

### ISSUE THREAD

**Issue by F1nery** [ValveSoftware/Dota2-Gameplay#14362]
### Description

I was playing a ranked game yesterday ,the game was 50/50 until like minute 30,then we won a fight and enemy PA started spamming 1000 chinese hieroglyphs in all chat per second or smth(idk what they were),he was spamming so hard my fps went down,and while doing this,he bought back and went to feed.We won,and the game didn't count.

I'm writing this post today because I assumed the game will count today after some time,but It didn't. It's been like 12hrs to no avail.Valve plz fix or It's pointless to play ranked rn.

There's no match id btw,the game is just gone.

**Comment by alexandershmatkov** [comment]
Same problem.
https://steamcommunity.com/id/sashashmatkov/
played a hour ago. Player on broodmother started typing hieroglyphs in all chat. When game finished, there was an error about problems with connection to the server. In main menu "reconnect" and "leave match" buttons were available. I left match and it was not counted

**Comment by Azmar19** [comment]
Same problem.

it is very sad and disappointing

**Comment by Nathanael-Valve** [comment]
Fixed.
