### ISSUE TITLE
Helm of the Overlord still has a Vlad's aura with no benefit

### ISSUE THREAD

**Issue by ttoma97** [ValveSoftware/Dota2-Gameplay#14397]
### Item name

Helm of the Overlord

### Description

Helm of the Overlord no longer builds from Vladmir's Offering, but still has a Vlad's aura built in with all buffs set to 0. This means you cannot benefit from a real Vladmir's Offering on your team while holding Helm of the Overlord, as the auras conflict with each other.

### Example Match ID and Timestamp

n/a - reproducible in demo mode

**Comment by Nathanael-Valve** [comment]
Fixed in next update
