### ISSUE TITLE
Khanda not registering damage

### ISSUE THREAD

**Issue by Krome00** [ValveSoftware/Dota2-Gameplay#14407]
### Item name

Khanda

### Description

The Khanda item does not register its damage when the enemy has no items equipped.
Video of bug attached: [https://drive.google.com/file/d/1XEOhtZJLEyz8-u_moyeNhlHbJ7M-z2bn/view?usp=sharing](url)

### Example Match ID and Timestamp

00:00 - 1:00

**Comment by commentator24** [comment]
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109324155/e7da21e1-2be5-48fe-bdeb-426ee821d82f)
unfortunately you simply picked a bad hero to test with. nothing to do with no items as shown above.
phylactery / khanda only works on Unit Target.
nature prophet ultimate is Unit or Point Target. 
not sure what setting you have, but when you tested it sometimes you clicked Point Target on the ground hence doesnt work.
try a hero that guarantee a unit target spell like venge
should close this issue not a bug

**Comment by Krome00** [comment]
Well, probably my fault for only sending the video with using only Natures Prophet when I tried other heroes as well.
ITS FIXED, I see you also nerfed Spirit Breaker with Khanda and 5 divine rapiers by not activating khanda until the skill hits.
