### ISSUE TITLE
Animation Anchor Points in Profile Misaligned in Non-16:9 Aspect Ratios

### ISSUE THREAD

**Issue by dz0039** [ValveSoftware/Dota2-Gameplay#14473]
### Description

Profile animation anchor points have an fixed offset to the right when play in non-16:9 mode. Screenshots should be self-explanatory.

### Screenshots

**Expected behavior, in 16:9**
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/10943272/a308b32d-5102-4496-bf46-b5a02a386443)

**Bugged behavior, in 21:9**
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/10943272/3e804550-a6e7-4d69-ab77-aeea33716acd)

**Comment by robinh-valve** [comment]
Thanks for reporting the issue. Fix will be released next week.
