### ISSUE TITLE
Helm of the Overlord has the aura with 0% values

### ISSUE THREAD

**Issue by sikleq** [ValveSoftware/Dota2-Gameplay#14492]
### Item name

Helm of the Overlord / Vladmir's Offering

### Description

HotO still has the aura but with 0% values. However, that aura still overrides the aura from Vladmir's making the latter useless.
![Снимок экрана 2023-12-18 184540](https://github.com/ValveSoftware/Dota2-Gameplay/assets/53887950/f6db00d5-d9a3-4586-ab09-f46d54fbe42f)
 

### Example Match ID and Timestamp

no

**Comment by Avarise831** [comment]
#14397
