### ISSUE TITLE
Kunkka, dont work cleve in tidebringer

### ISSUE THREAD

**Issue by stormcrvfter** [ValveSoftware/Dota2-Gameplay#14519]
### Ability name

Tidebringer

### Description

Dont work 150% cleave damage in tidebringer. Also dont work talents in 70% cleave on 20 lvl. https://youtu.be/2yoxPop1B3E?si=tz29BNtqnLOX4vb2

### Example Match ID (and possibly Timestamp)

7493424629

**Comment by Aluerie** [comment]
already fixed
