### ISSUE TITLE
Bloodfeather Frock Bundle UNMARKETABLE

### ISSUE THREAD

**Issue by 202010693** [ValveSoftware/Dota2-Gameplay#14536]
### Cosmetic Item Name

Bloodfeather Frock Bundle 

### Description

Queen of Pain's Bloodfeather Frock Bundle is still UNMARKETABLE!

### Example Match ID

N/A

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/153983229/204ee19d-e3ba-4ab2-97ea-9beb4ca6849a)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/153983229/c8dbd188-c14a-42be-94a1-6e687e9a84b2)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/153983229/8dffa735-c74e-4d5b-b509-805defda7f59)

**Comment by shaileshgarg** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/13573
