### ISSUE TITLE
Physical damage passes through Guardian Angel

### ISSUE THREAD

**Issue by itonskie** [ValveSoftware/Dota2-Gameplay#14555]
### Ability name

Guardian Angel

### Description

When activating Guardian angel there is a moment at the start where I still receive damage from coup de grace even though its shows that the buff is already active. I've tried to recreate this in demo mode and seem to find that it shouldn't do this. I've noticed this in other games too but this one I played last night where I finally caught the bug.

### Example Match ID (and possibly Timestamp)

7497456197 - 35:14

**Comment by commentator24** [comment]
you need to open combat log if want to check dmg bug. you can do this during game as well.
it looks like PA is doing crit dmg but it's actually from timbersaw whirling death 13% stat loss + 293 dmg. 149 str dropped to 130. 19 str loss x 22 hp = 418 dmg
1712-418-293 = 1001 not 989 but probably the hidden decimal places.
you can further see that stiffling dagger did 0 dmg

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109324155/34de4c92-8811-49a2-94a2-6fc58d7863d0)
you can close the issue doesnt seem like a bug.
