### ISSUE TITLE
[Game-breaking] Granite Aura drastically restores HP after leaving and entering the AoE

### ISSUE THREAD

**Issue by sikleq** [ValveSoftware/Dota2-Gameplay#14569]
### Ability name

Granite Aura

### Description

As title says if you leave and enter the aura radius constantly you are basically healing your teammates for 300 or more HP.

https://www.youtube.com/watch?v=P9hkK4vDu2w

### Example Match ID (and possibly Timestamp)

no

**Comment by alar1ch** [comment]
fix url youtube

**Comment by irismus** [comment]
Fixed in 7.35b.

**Comment by sikleq** [comment]
Fixed in 7.35b.
