### ISSUE TITLE
Winter Wyvern - Winter's Curse disappear's much sooner than it should be like `3s

### ISSUE THREAD

**Issue by tje3d** [ValveSoftware/Dota2-Gameplay#14618]
### Ability name

Winter's Curse

### Description

Winter's Curse expires much sooner than it should be, for example rank3 should be up for 5.5s but it expires in 3s

### Example Match ID (and possibly Timestamp)

0

**Comment by TamamoKitsune** [comment]
Read the Alt-Tooltip, it has condition for ending earlier if no other opponent units in ability range

**Comment by tje3d** [comment]
> Read the Alt-Tooltip, it has condition for ending earlier if no other opponent units in ability range
