### ISSUE TITLE
Facesles Void Time Lock still bashes on denies after 7.35b

### ISSUE THREAD

**Issue by Fjara-h** [ValveSoftware/Dota2-Gameplay#14636]
### Ability name

Time Lock

### Description

From 7.35b patch notes: "No longer procs on denies."

https://clips.twitch.tv/BlueKitschyFloofCopyThis-HV-4cNnCDUJaKNhF

### Example Match ID (and possibly Timestamp)

7503857801 - 3:42

**Comment by RANDOMUSERSS** [comment]
та же хрень сегодня была
