### ISSUE TITLE
Zeus don't have 2 heavenly jumps (+1 from talent tree)

### ISSUE THREAD

**Issue by dzoole** [ValveSoftware/Dota2-Gameplay#14631]
### Ability name

Heavenly jump

### Description

After reaching level 15 you can choose from talent tree +1 heavenly jump target, but actually you didn't get +1 heavenly jump.

### Example Match ID (and possibly Timestamp)

7502002912 - 13:03

**Comment by Aluerie** [comment]
it s target

**Comment by dzoole** [comment]
Aha, so you've probably changed it in the previous versions, cuz I know for sure there were 2 jumps and little icon 2 on the spell.
So this work only if I have target and than I have 2 jumps only on that specific target?

**Comment by Aluerie** [comment]
1. i m not with valve
2. Heavenly jump never had charge-based cooldown
3. this talent increases target count, like when he jumps - the lighting (that slows and deals damage) strikes two enemies instead of one.

**Comment by dzoole** [comment]
Than I'm tripin :)
