### ISSUE TITLE
Eternal Shroud doesn't restore mana before damage reduction.

### ISSUE THREAD

**Issue by matr9xnb** [ValveSoftware/Dota2-Gameplay#14635]
### Item name

Eternal Shroud

### Description

Eternal Shroud should restore mana before magic resistance, all damage reduction abilities (like Ursa - Enrage but not Medusa), all shield barrier (like Abaddon - Aphotic Shield) and all damage negation (like Abaddon – Borrowed Time).

### Example Match ID and Timestamp

Demo heroes

**Comment by matr9xnb** [comment]
Actually it's not restore any mana. 
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/13233278/3f5706b1-9b97-47de-8706-43ce04fdd169)

**Comment by matr9xnb** [comment]
Hope this issue be fixed soon.

**Comment by masual95** [comment]
It's been several weeks, and it hasn't been fixed yet!
Isn't the vacation already over?
