### ISSUE TITLE
ward can't be hit

### ISSUE THREAD

**Issue by lx19930** [ValveSoftware/Dota2-Gameplay#14638]
### Item name

ward

### Description

ward placed by lc can't be hit

### Example Match ID and Timestamp

7504067079

**Comment by jukibuki** [comment]
Adding another match id: 7508120170 12:46

**Comment by mariostoev** [comment]
Another one: 7508778172. Warlock wards cannot be targeted

**Comment by checor** [comment]
Another match ID 7509270683 before starting the match, midlane ward couldn't be dewarded

**Comment by Aluerie** [comment]
the initial comment is missing details so I will comment

The wards in issue are "Frosty the North Ward" - the last reward from the Frostivus event

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/33165440/dd5070ac-6e4a-465f-aabb-851a098b4ee8)

**Comment by andresdlt93** [comment]
same issue on my game 7510474046

**Comment by GathX** [comment]
> This is intentional. P2W bullshit.

they are free though, WTF. did you mean PLAY to win?

**Comment by StoryDevOffical** [comment]
same here.
refund all ranked from this time.
10 keys for frostivus chest as compensation.
regarding this bug skill level, get back false positive banned account.

**Comment by JCrick-dotes** [comment]
Valve, just remove the ward till fixed.  makes for a frustrating an unfair game.  Whoever uses this ward is op.

**Comment by SherazMalik86** [comment]
My wards (Spirit Breaker) cant be hit by Jakiro and vice versa

Match ID # 7511707766

**Comment by apurific-sfu** [comment]
+1
Match ID 7513479356

**Comment by icarogtavares** [comment]
Match ID: 7514049295
Time: ~4:45 midlane

**Comment by paboum** [comment]
They can be hit, just cannot be targeted.
And yes, this is a game breaking bug. Inexcusable. As promised, I will spend exactly $0 on valve products in 2024.

**Comment by Tanzwurm** [comment]
Match ID:7515617538

Why it takes so long to fix this? more and more player's get this ward and abuse it. I wont play more, still the bug is fixed or the ward removed. This breaks the game hard

**Comment by icarogtavares** [comment]
> Why it takes so long to fix this?

hey @Tanzwurm I know some people are playing dota, but today is December 31… today we celebrate the new year in US (and other countries)

I know your pain, but let’s understand their side… the entire year working… this week can be the only week with their entire family to celebrate the new year…

**Comment by Tanzwurm** [comment]
> > Why it takes so long to fix this?
> 
> hey @Tanzwurm I know some people are playing dota, but today is December 31… today we celebrate the new year in US (and other countries)
> 
> I know your pain, but let’s understand their side… the entire year working… this week can be the only week with their entire family to celebrate the new year…

I try to understand their side and it dont need to be today :) But i think, it should be possible to remove a ward skin/game breaking bug, in the time frome one week. 
But yeah, i have no idea how much work it realy is.

It's just super frustrating when you're playing against someone who uses the bug deliberately. And he always stands at the ward in such a way that you always attack the hero and not the ward with an auto attack.

Happy new year

**Comment by behavioural-exercise** [comment]
Match ID: 7516585396
Timestamp: 23:40-24:20

Died because of undestroyable ward. Players on Treant and Gyrocopter intentionally abused this ward and wrote about it in game chat.


https://github.com/ValveSoftware/Dota2-Gameplay/assets/103511814/a1b3c702-b233-424b-85ee-71973b4121b4

**Comment by GathX** [comment]
The only thing you can do is issue an attack ground command while nothing else is around. By default, this should be "A" and lick on the ground.

**Comment by atheistium** [comment]
MID: 7517808513
Top lane couldnt deward. When I went up, I also couldn't deward it. 

Tried with Tangos as well.

**Comment by slimaster88** [comment]
Absolutely terrible bug! Pleace fix this!!!

**Comment by Sanckijonizator** [comment]
Guys listen to me, the problem was also before this frostivus ward, if you remember  here in my picture, you could deward ward which waas posted in lower grounds near snow shards, but you needed to TARGET it only if you not target and try to left click atack on ground was imposible you needed to target it!! now remember im telling you this cuz now this new ward is untargetable and as mele hero you cant left click atack on ground so basically you cant deward camp as mele hero its imposible cuz you cant left click atack on ground and you cant target ward!! this is imbalanced and you can lose lane due to unable to pull! very bad shit and they dont wanna fix this!
![Uploading FIX THIS ITS NOT BALANCED.png…]()

**Comment by Aluerie** [comment]
fixed with ClientVersion 5961
