### ISSUE TITLE
pinging quickbuy says UNKNOWN and hangs/lags all allied clients

### ISSUE THREAD

**Issue by Fjara-h** [ValveSoftware/Dota2-Gameplay#14683]
### Description

Rubick alt-clicks to ping his quick-buy, which is arcane boots, I watched with the 2-minute delay to see if the lag would occur as a spectator. It only occurred for the dire allies. It somehow resolves to UNKNOWN and lags all allies only.

### Example Match ID (and possibly Timestamp)

7508706334 - 4:30

### Screenshots

https://clips.twitch.tv/VainRockyMomWow-Pxsh_XMDkMwa9d6c

**Comment by eugene-valve** [comment]
This should be fixed in an upcoming update, thanks for the bug report!
