### ISSUE TITLE
Dota 2 guides won't load (FIX)

### ISSUE THREAD

**Issue by TheJowley** [ValveSoftware/Dota2-Gameplay#14703]
### Description

Hello, you've probably already heard about the problem with loading hero manuals in the game.
So, I determined that after deleting the large file D:\Steam\steamapps\workshop\appworkshop_570.acf and deleting the folder D:\Steam\steamapps\workshop\content\570 everything starts working fine.

I described everything in detail here: https://www.reddit.com/r/DotA2/comments/18swz83/dota_2_guides_wont_load_fix/

**Comment by neogamerdrew** [comment]
This worked, thanks!
