### ISSUE TITLE
Mage Slayer's debuff does not reduce damage by 40%, but by 35%

### ISSUE THREAD

**Issue by danielhenrymantilla** [ValveSoftware/Dota2-Gameplay#14758]
### Item name

Mage Slayer

### Description

Despite the patch notes of 7.35 / what the item itself says:

![WhatsApp Image 2023-12-31 at 15 21 02_cdddce5f](https://github.com/ValveSoftware/Dota2-Gameplay/assets/9920355/e4605d37-251f-442f-9615-6f68fa122ba0)

It turns out that Mage Slayer's debuff reports a reduction of 35%, and when looking at the damage log, that's indeed the reduction that is taking place:

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/9920355/1f4076af-8a42-4db1-9dfb-286cb32e467b)

**Comment by commentator24** [comment]
i tested with DP crypt swarm and it shows normally
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109324155/22459681-16da-4271-88e6-43a79df077d9)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109324155/c7074aab-0ed4-4161-a127-bf1b7602a9fe)

just the tooltip incorrect still says 35%.
the amount you sap also seems odd 101. are you sure you didnt accidentally use bounty hunter talent 30% less damage taken during shadow walk?

**Comment by danielhenrymantilla** [comment]
Interesting, thanks for pointing this out @commentator24. So I've gone back and tested, and indeed, with 0 spell amp, it's just the tooltip which is wrong.

The actual "bug", or I guess now it could be relegated to an interaction quirk, is that once spell amp is involved, the reduction from mage slayer only applies to the base spell damage, hence the mismatch.

  - For instance, with 6 Rapiers and a Titan Sliver, lvl 1 brain Sap deals 238 damage, and with the Mage Slayer debuff it becomes 202):

    ![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/9920355/e25ad151-ae35-421c-aeb6-1e4145fcd8f8)

    We can notice that `202 = 238 - 40% * 90`, with `238` being the spell damage without mage slayer, and 90 being the "base" spell damage (before amplifications).
