### ISSUE TITLE
Venomanser Aganim issue

### ISSUE THREAD

**Issue by waterwalk2024** [ValveSoftware/Dota2-Gameplay#14762]
If we play Venomanser + Aganim Ability - > should be triggered if Venomanser dies or venomous gale dispelled. If we have Nullifier item, we can not dispel the Gale (yet it is dispellable in despribtion) so that Nullifier triggers the Aganim ability. Please check and fix.

**Comment by Aluerie** [comment]
Intended, Nullifier doesn't dispel your own team offensive spells.
