### ISSUE TITLE
Bug Ward

### ISSUE THREAD

**Issue by Tunggakjati** [ValveSoftware/Dota2-Gameplay#14765]
### Item name

Frosty the north ward

### Description

I cant hit/deward the "Frosty the north ward"

### Example Match ID and Timestamp

7515390679

**Comment by Aluerie** [comment]
Duplicate https://github.com/ValveSoftware/Dota2-Gameplay/issues/14638

**Comment by Nathanael-Valve** [comment]
Fixed
