### ISSUE TITLE
Sentry and Observer enemy ward its cant attack by my team.

### ISSUE THREAD

**Issue by Myuliantino** [ValveSoftware/Dota2-Gameplay#14768]
### Description

We can't attack observer or sentry enemy ward. i dont know its bug or cheat. 

pls watch the barra too. He cant stun after ES using his skill too.
Thanks.

### Example Match ID (and possibly Timestamp)

7515714229

**Comment by Aluerie** [comment]
Duplicate https://github.com/ValveSoftware/Dota2-Gameplay/issues/14638 you can close your issue and read contributor guidelines
