### ISSUE TITLE
Bug Warding

### ISSUE THREAD

**Issue by AwesomeCheng123** [ValveSoftware/Dota2-Gameplay#14769]
### Item name

Sentry Wards

### Description

The comestic ward is unclickable.

### Example Match ID and Timestamp

7515781585

**Comment by Aluerie** [comment]
Duplicate https://github.com/ValveSoftware/Dota2-Gameplay/issues/14638 you can close your issue and read contributor guidelines

**Comment by Nathanael-Valve** [comment]
Fixed
