### ISSUE TITLE
Silencer Last Word doesn't silence units after they used a channelled spell

### ISSUE THREAD

**Issue by ElLoco1122** [ValveSoftware/Dota2-Gameplay#14796]
### Ability name

Last Word

### Description

When using Last Word on Witch Doctor (WD) and WD uses Death Ward after that, he isn't silenced. Used to silence a while ago.

### Example Match ID (and possibly Timestamp)

7518312246

**Comment by Aluerie** [comment]
invalid, duplicate https://github.com/ValveSoftware/Dota2-Gameplay/issues/3003#issuecomment-1242803532

**Comment by Aluerie** [comment]
intended, duplicate https://github.com/ValveSoftware/Dota2-Gameplay/issues/3003#issuecomment-1242803532

**Comment by ElLoco1122** [comment]
when did they change that?
