### ISSUE TITLE
Dark Willow's stun refuses to trigger

### ISSUE THREAD

**Issue by 777bronzestar** [ValveSoftware/Dota2-Gameplay#14817]
### Ability name

Cursed Crown

### Description

When the cursed crown effect expires, the stun effect does not trigger.
This is not the first time I have encountered this bug, because previously I thought it was dispelled by the heroes themselves or other heroes in the fog of war and did not attach any importance to it. 
But now nothing could dispel this effect.
Preview video with combat log and screenshot with combat log:
https://github.com/ValveSoftware/Dota2-Gameplay/assets/106770009/2fd8860f-0db8-48e7-98c6-f07f0494cdbb
![S2lpu4-38IQ](https://github.com/ValveSoftware/Dota2-Gameplay/assets/106770009/76df6cb7-0dee-4f3a-ba55-11cc10c9545a)

Thank you, developer, for spending time on this "specific bug" and i'm sorry, for me, that this bug is "specific".

### Example Match ID (and possibly Timestamp)

Match ID - 7520682019 ; Timestamp - 4:08

**Comment by Aluerie** [comment]
Duplicate #9090
