### ISSUE TITLE
MegaMeepo bug

### ISSUE THREAD

**Issue by jjangchan** [ValveSoftware/Dota2-Gameplay#14826]
### Ability name

MegaMeepo bug

### Description

Mega meepo is invalidated when written before the end of the face void chrono

### Example Match ID (and possibly Timestamp)

7521600021-3359

**Comment by gelo0313** [comment]
It's happening even on other disables.

I hope there's a fix on this. Another similar behavior but this one coming off Naga's sleep.

[Megameepo didn't pull all meepo clones](https://streamable.com/98hf6m)

Match ID: 7683162504
