### ISSUE TITLE
Invoker 25lvl left talent doesn't work for sunstrike

### ISSUE THREAD

**Issue by ezzxx** [ValveSoftware/Dota2-Gameplay#14917]
### Hero and spell

Invoker 25lvl left talent and sunstrike

### Description

At level 25, Invoker has a talent that increases spell damage from 7% to 14%, but the damage of the Sunstrike spell remains the same with or without the talent upgrade, equal to 605 damage.

### Screenshots

https://github.com/ValveSoftware/Dota2-Gameplay/assets/77077443/59521575-cfb9-435d-a2bf-ca1c313f63fc

**Comment by Aluerie** [comment]
you need to recycle orbs for it to proc
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/33165440/05aa22bb-a232-4361-b9ce-bb89d0901be4)
