### ISSUE TITLE
Watchers are the wrong colour for dire in game

### ISSUE THREAD

**Issue by VenomRaven** [ValveSoftware/Dota2-Gameplay#14912]
### Description

While it shows the correct colour if you are spectating a game, when you are playing as dire the watchers show radiant teal when taken by the dire, and dire red when taken by the radiant (whilst playing as dire).

**Comment by VenomRaven** [comment]
![20240112021500_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/59765344/860e22b2-3df1-409a-81b1-6312e21bb33f)

this is in game
![20240112025639_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/59765344/b46eeadc-2282-450e-864d-d37f067404af)
this in replay

**Comment by VenomRaven** [comment]
this in game
![20240112021500_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/59765344/f788a6d1-be41-46b2-b049-b8f91c573350)
this is in replay
![20240112025639_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/59765344/469d42a8-603c-492a-815d-b3cd5e461fb6)

**Comment by yckmm** [comment]
It was intentionally changed to be like this. Blue = watcher owned by your team, red = watcher owned by enemy team.

**Comment by VenomRaven** [comment]
It doesnt make sense. The rest of the building UI follows a rule that teal = radiant. Orange = dire. Outposts follow this rule. The tormentors follow this rule. Why don't watchers? And you can see the colouring in towers and creeps too.
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/59765344/499528f6-1945-4bfc-9ca1-be3f8d599e7b)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/59765344/cff7fdfb-2820-4540-879f-38bf96ae9a32)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/59765344/e8e11774-94ec-41d5-b83a-c47d5db0721a)

Its especially obvious on custom towers added to the game.
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/59765344/b5a27fc2-904b-45e1-8dae-9057d7333095)

![dire_tower_2021](https://github.com/ValveSoftware/Dota2-Gameplay/assets/59765344/cde8de04-0e09-440e-a0be-2d2f3a46f0a3)
As it is - its just confusing. I feel like this is an example where the designers know what they are doing far more than the public. I wish they would have stood their ground if it was indeed originally like this.

**Comment by VenomRaven** [comment]
An easy fix would to be to make them actually green and red rather than blue and orange - if they are supposed to be linked to ally health bar colours.
But I still think the dev's were right the first time making them act like everything else in DOTA.
