### ISSUE TITLE
Phoenix egg is healed by Lich's frost shield + ice spire

### ISSUE THREAD

**Issue by nunosilva800** [ValveSoftware/Dota2-Gameplay#14922]
### Ability name

Supernova

### Description

Seems like when Ice spire is close to the egg and Lich applies Frost Shield to it, it gets healed.

Frost Spire description:

> Each Frost Shield tick will heal the Spire by 1 hero attack.

Perhaps this is interacting weirdly with the egg?

### Example Match ID (and possibly Timestamp)

7532729876 - 49:55

**Comment by nunosilva800** [comment]
![20240111185950_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/1113178/87809cff-7ad2-47f2-b6bb-382bd31472a8)
![20240111185957_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/1113178/c78b5f06-7788-4e09-b94d-e193fd5eb86c)

**Comment by Aluerie** [comment]
only visual bug, also duplicate #5889
