### ISSUE TITLE
Can't Find Match for Single Draft, I can play SD only with party

### ISSUE THREAD

**Issue by billytisna** [ValveSoftware/Dota2-Gameplay#14925]
### Description

Help me to discover how to play dota with my account, Friend ID : 139900843

I cant Find Match for Single Draft alone, If i party with friend, my friend can click Find Match with me

Help me!, i want to play solo Single Draft to end this penalty

### Example Match ID (and possibly Timestamp)

7532430815

### Screenshots

![Bug Cant Find Match Dota 2](https://github.com/ValveSoftware/Dota2-Gameplay/assets/156383224/2fd6f26f-eaf7-467e-aac0-fda5230c5487)

**Comment by yckmm** [comment]
You have to deselect the "All Pick" mode.

**Comment by billytisna** [comment]
Thank you, damn! i dont play for 2 day bcoz of it,
