### ISSUE TITLE
OD Arcane Orb damage applied as Spell Damage not being affected by Spell Amplification 

### ISSUE THREAD

**Issue by WilliamAtlas** [ValveSoftware/Dota2-Gameplay#14999]
### Ability name

Arcane Orb

### Description

As per title. Damage applied in separate Spell Damage instance not being affected by Spell Amplification - likely having an impact on OD win rate at the moment. e.g., not reduced by Mage Slayer debuff or amplified by Veil of Discord or Shiva's debuffs.

Comparable Active Attack Modifiers, such as Silencer's Glaives of Wisdom, are being correctly affected by Spell Amplification mechanics.

Default attack = 361 damage
![Default attack - 361 damage](https://github.com/ValveSoftware/Dota2-Gameplay/assets/153910535/59b6f075-426f-4f6b-9e8e-14a032463ded)

Mage Slayer applied = 361 damage
![Mage Slayer applied - 361 damage](https://github.com/ValveSoftware/Dota2-Gameplay/assets/153910535/8f13d6ea-fb51-4981-b287-243a6d08e275)

Shiva's applied = 361 damage
![Shiva's applied - 361 damage](https://github.com/ValveSoftware/Dota2-Gameplay/assets/153910535/2724ab41-74d4-4351-8de0-fb0555250c6f)

Mage Slayer + Shiva's applied = 361 damage
![Mage Slayer + Shiva's applied - 361 damage](https://github.com/ValveSoftware/Dota2-Gameplay/assets/153910535/f72a8842-2dcb-4213-90d6-c85c65671689)

### Example Match ID (and possibly Timestamp)

None - demo mode w dummy

**Comment by zyunwei** [comment]
It's the same damage the purple number displayed, you can press F10, the actually damage is changed.

**Comment by Aluerie** [comment]
intended, purple numbers are only visuals that calculated before damage reductions. 

its' the same for all similar stuff like PA crit red number is indifferent to enemy armor.
