### ISSUE TITLE
Death Ward Piercing BKB's pure damage immunity

### ISSUE THREAD

**Issue by ningW123** [ValveSoftware/Dota2-Gameplay#15026]
### Ability name

Death Ward

### Description

The Death Ward skill displays as Pure damage, which should be blocked by BKB's pure damage immunity as described in BKB item description. but Death ward is doing full damage to both BKB and non-BKB target. if this is a special case, please provide clarification on how is this happening.

### Example Match ID (and possibly Timestamp)

7543387261

**Comment by Aluerie** [comment]
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/33165440/728fea3c-00f7-4c11-abf1-e01b6ea5980f)
intended
