### ISSUE TITLE
demoinfo2 relevance

### ISSUE THREAD

**Issue by tonymonsalo** [ValveSoftware/Dota2-Gameplay#15056]
### Description

Have a question about [valve demoinfo2 tool](https://developer.valvesoftware.com/wiki/Demoinfo2)
I guess, since this tool was released, the format of .dem file was changed (or the proto buffer thing was changed). I am able to rebuild project so at least it started, but it is not enough.

Is there currently any way to parse replays?
I believe i know a good way for catching smurfers/boosters/accbuyers (if it is i want to share it with devs)

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/20268195/35604371-633d-43fa-8ac9-060708328b91)

**Comment by Aluerie** [comment]
[odota/parser](https://github.com/odota/parser)

**Comment by tonymonsalo** [comment]
> [odota/parser](https://github.com/odota/parser)

Thank you a lot!
