### ISSUE TITLE
Binding '~' only works for one keyboard layout

### ISSUE THREAD

**Issue by w84april** [ValveSoftware/Dota2-Gameplay#15086]
### Description

Way to reproduce:
1. Bind any any slot on ~
2. Switch layout in game (ENG-RU) in my case
3. This bind doesn't work anymore

Also when binding the slot it is visible in settings that different key is binded on different layouts (doesn't work like this for different keyboard buttons - eng is default), re screenshots

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/32621609/992e21c4-cbe5-4e5a-9684-691b72e06869)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/32621609/ffb694b8-0f83-4de4-a347-195940400b96)

**Comment by Aluerie** [comment]
use position based bind seting
