### ISSUE TITLE
2016 International Collector Cache Issue : Phantom Assassin - Creeping Shadow

### ISSUE THREAD

**Issue by CrIoS917** [ValveSoftware/Dota2-Gameplay#15088]
### Cosmetic Item Name

Phantom Assassin - Creeping Shadow

### Description

Once unbundled, only show trade cool down and not (May be gifted once) unlike all other caches before 2023. Some customer service replied with : cache only able to gift once which is _**UNTRUE**_, where you can refer to my attachment showing unbundling a gifted Ursa cache and immediately can be wrap gift piece by piece in game,. 
![PA5](https://github.com/ValveSoftware/Dota2-Gameplay/assets/157441518/2f504e80-d4aa-4d26-afda-33fb887742d7)
![PA4](https://github.com/ValveSoftware/Dota2-Gameplay/assets/157441518/f20d1764-772d-4009-9016-32cc3497e154)
![PA3](https://github.com/ValveSoftware/Dota2-Gameplay/assets/157441518/d547aaa3-450a-4ea6-8b52-2081c2f6aa47)
![PA2](https://github.com/ValveSoftware/Dota2-Gameplay/assets/157441518/01c6ae28-3ef1-4d50-8629-6818360c4930)
![PA1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/157441518/cf8eadb4-1e4c-4aaa-a028-e22827cff887)
![Showing able to GiftWrap Item2](https://github.com/ValveSoftware/Dota2-Gameplay/assets/157441518/f9700419-de8e-4565-8998-52c1f01b9a8d)
![Showing able to GiftWrap Item](https://github.com/ValveSoftware/Dota2-Gameplay/assets/157441518/6e9cff81-a30f-41d5-9bd9-24ce135d2fee)
![Unbundled Ursa](https://github.com/ValveSoftware/Dota2-Gameplay/assets/157441518/4a1ae373-7503-401e-9dfd-35c8f1066941)
![ursa bundled gift](https://github.com/ValveSoftware/Dota2-Gameplay/assets/157441518/1682f496-3b66-44dd-b210-ce90b2778ff4)

### Example Match ID

irrelevant to match

### Screenshots

As attached

**Comment by Aluerie** [comment]
Intended, your example was from exception year

**Comment by CrIoS917** [comment]
> Intended, your example is from exception year

Thanks for the clarification. Since is implemented globally, I can't do anything can I? As I have got two sets don't know what to do with it... May I also ask is 2017 international affected as well?
