### ISSUE TITLE
BUG Playing bot maches wont remove the 2 games ban

### ISSUE THREAD

**Issue by leojoipas** [ValveSoftware/Dota2-Gameplay#15101]
### Description

I got a ban for quiting a match some time ago and the game says i need to play 2 bots games to take the ban off but i already played like 5+ games and it doesnt count to remove the penality

**Comment by amirsaam** [comment]
uh, i think you misunderstood it. dota penalty is playing sd matches.

**Comment by DeckCardCain** [comment]
> Sorry im kinda new in the game, what "SD" means?

Single Draft. It's a mode everyone get to choose between 3 random heroes.

**Comment by leojoipas** [comment]
Yeah was my bad ty for helping out
