### ISSUE TITLE
Dota no longer launching on Linux Ubuntu

### ISSUE THREAD

**Issue by moorateeahtashil** [ValveSoftware/Dota2-Gameplay#15115]
### Description

After update, dota is no longer launching

**Comment by Aluerie** [comment]
Wrong repo. 

https://github.com/ValveSoftware/Dota-2/

look at open/closed issues there before crossposting though. There are some about launch problem.

you can close this post.

**Comment by governorquota** [comment]
Although Dota 2 is playable on various distributions, some offer better support and a smoother setup for gaming purposes. Among the well-known choices are Ubuntu, Linux Mint, and Manjaro. <a href="https://littlerunmo.com/">little runmo</a>
