### ISSUE TITLE
Мне дали бан на 24 часа за игру, где я выложился на полную и выиграл. Только потому, что я не выдержал и негативно ответил союзнику, который нёc чушь про то, что в ситуации, где я не мог драться на моём герое, так как у меня ничего не было, я должен был пойти и отдать преимущество оппонентам. (I got a 24-hour ban for a game where I gave it my best shot and won. Only because I couldn’t stand it, and I responded negatively to an ally who was talking nonsense about the fact that in a situation where I couldn't fight on my hero, since I had nothing, I had to go and give the advantage to opponents.)

### ISSUE THREAD

**Issue by DragoniteDuskull** [ValveSoftware/Dota2-Gameplay#15172]
### Description

Ситуация такова: мы убиваем 5 героев оппонентов и идём ломать Т3. Ломаем и барак тоже. Я говорю "отойдём" так как там почти все герои возродились, а у меня день и нет ульты на Night Stalker и Bkb перезаряжается. Я отхожу, но мои 3 союзника идут и фидят. Мне Nature"s Prothet в недовольном тоне говорит, что я что-то сделал не так. Я поясняю, что мой герой в той ситуации ничего не мог сделать и что если я пошёл бы драться, я бы умер. На что мне он отвечает "хороший у тебя герой" в недовольном тоне. Меня это раздражает и я ору на него и репортаю. Так как по мне это руин, когда человек не слышит, что ему говорят, что надо отойти и потом с Аегисом закончить игру, а он идёт и фидит с двумя другими, а потом недовольным тоном говорит, что я должен был сыграть иначе. Я признаю, что я негативно ему ответил, но я не понимаю, почему мне дают бан на 24 часа за игру, в которой я выиграл и не руинил, так как негативно ответил человеку, который не прав. Я считаю, что за такое нарушение мне должны дать мут на 24 часов. Первый тайм код - это момент, когда мои союзники вместе с Nature"s Prothet нафидили второй тайм код, когда я объяснил, почему я не мог пойти драться и после ответа Nature"s Prothet наорал на него и репортнул его. (The situation is this: we kill 5 opponent heroes and go break T3. We break T3 and barracks. I say "back away" as there are almost all the heroes revived, and I have a day and no ultimate on Night Stalker and Bkb reloads. I walk away, but my 3 allies go and feed. Nature's Prothet tells me in a dissatisfied tone that I did something wrong. I explain that my hero couldn't do anything in that situation and that if I went to fight, I would have died. To which he replies to me, "you have a good hero" in a dissatisfied tone. It annoys me and I yell at him and report him. Since for me this is ruin, when a person does not hear that others say to him that he needs to move away and then finish the game with Aegis, and he goes and feed with two others, and then says in a dissatisfied tone that I should have played differently. I admit that I responded negatively to him, but I do not understand why I am being banned for 24 hours for a game in which I won and did not ruin, only because I responded negatively to a person who is wrong. I believe that for such a violation I should be given a mute for 24 hours. The first time code is the moment when my allies, along with Nature's Prothet feeded, the second time code, when I explained why I couldn't go to fight and after Nature's Prothet's response, yelled at him and reported him.)

### Example Match ID (and possibly Timestamp)

7562916495 31:20-31:55 33:00-33:25

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/158303532/e22479d8-bb6f-4ddb-aa3e-935edba271a4)

**Comment by SpiritWinD86** [comment]
This is not a bug, please close the issue.
Most likely your teammates and opponents reported you.
There is a link to your steam profile where you can see reports that you've received:
https://steamcommunity.com/my/gcpd/570/?category=Account&tab=MatchPlayerReportIncoming

**Comment by DragoniteDuskull** [comment]
Many reports and system automatically ban you?

**Comment by ziganshintimur** [comment]
this is just not right Valve, how people can get a ban after 1 game immediately (without even overwatch being review) just by getting too many reports????????? maybe people who reported him deserves ban more?

**Comment by DragoniteDuskull** [comment]
In my case, I can say that I deserved it a little bit, but look at this guy https://github.com/ValveSoftware/Dota2-Gameplay/issues/15168 he 100% didn't decerve to get ban.
