### ISSUE TITLE
Hoodwink bushwhack forced to quickcast despite being turned off in settings

### ISSUE THREAD

**Issue by DJDavid98** [ValveSoftware/Dota2-Gameplay#15186]
### Ability name

Bushwhack

### Description

When casting bushwhack it used to show an indicator circle with the range, now it immediately casts at the mouse cursor position even with quickcast off in the game settings.

[Hero Demo recording](https://www.youtube.com/watch?v=fItaL9qqpaw)

* OS: Windows 11 23H2 (build 22631.3007)
* Game version: 5,978
* Gameplay version: 7.35B

### Example Match ID (and possibly Timestamp)

7564963415 - 13:53

**Comment by Aluerie** [comment]
couldnt reproduce ;

**Comment by DJDavid98** [comment]
After enabling advanced quickcast, then binding and unbinding W from hero-specific quickcast from settings (it was not bound before at all but I tried anyway) it seems to have fixed itself. I have no clue how this happened but it seems to be resolved now.
