### ISSUE TITLE
 Witch Blade doesn't work with Crackshot of Specialist's Array

### ISSUE THREAD

**Issue by ArtemBal** [ValveSoftware/Dota2-Gameplay#15217]
### Item name

Specialist's Array

### Description

Witch Blades passive ability doesn't work with Crackshot ability of Specialist's Array. While Crackshot is on cooldown Witch Blade works but if both abilities are not on cooldown and there is two or more enemies for Crackshot activation then only Сrackshot works and Witch Blade goes on cooldown. 

### Example Match ID and Timestamp

7564957932 20:45 Winter wyvern

**Comment by Aluerie** [comment]
duplicate https://github.com/ValveSoftware/Dota2-Gameplay/issues/5783
