### ISSUE TITLE
Dota 2 crashes on macOS

### ISSUE THREAD

**Issue by petersamokhin** [ValveSoftware/Dota2-Gameplay#15259]
### Description

The app crashes on start every time, after the latest update (that arrived around 23:00 GMT).

macOS Sonoma 14.2.1 (23C71), M1 Pro

**Comment by mylaluna** [comment]
I have the same issue! I think it is caused by the new update.

**Comment by linxkaa** [comment]
i have the same issues also

**Comment by liringlas** [comment]
Same issue, macOS 14.1.2 (23B92), M1 Pro

**Comment by mylaluna** [comment]
I found a workaround from reddit. 
Add -sw or -autoconfig to your lanuch option.
-sw makes the game running in window mode. 
-autoconfig resets your display settings to default. 

You can try to change your settings back after getting into the game and see if the game crashes.

I have a feeling the issue has something to do with the display settings.

**Comment by showme032** [comment]
Same thing for me, on M1 Pro. Here's the crash log: 
[dota2crash.log](https://github.com/ValveSoftware/Dota2-Gameplay/files/14219316/dota2crash.log)

**Comment by wenqf11** [comment]
Same thing 

> I found a workaround from reddit. Add -sw or -autoconfig to your lanuch option. -sw makes the game running in window mode. -autoconfig resets your display settings to default.
> 
> You can try to change your settings back after getting into the game and see if the game crashes.
> 
> I tried to adjust resolution and toggle display settings. 4K95fps and render over 75% crashed the game. I could also hear macbook fan is spinning like crazy.
> 
> I have a feeling the issue has something to do with the new updates, particularly the new treasure advertisment, consumes too much GPU, which may or may not lead to the crash.

I updated os version, reinstalled Dota2, and tried both -aw and -autoconfig, but still crash.   OS: 14.3.1 (23D60)   Apple M1 Pro 32GB

**Comment by mustaqimtay** [comment]
-sw works. Thanks

**Comment by liringlas** [comment]
> I found a workaround from reddit. Add -sw or -autoconfig to your lanuch option. -sw makes the game running in window mode. -autoconfig resets your display settings to default.
> 
> You can try to change your settings back after getting into the game and see if the game crashes.
> 
> I tried to adjust resolution and toggle display settings. 4K95fps and render over 75% crashed the game. I could also hear macbook fan is spinning like crazy.
> 
> I have a feeling the issue has something to do with the new updates, particularly the new treasure advertisment, consumes too much GPU, which may or may not lead to the crash.

Also confirm, -sw worked for me. Thank you!

**Comment by tytygelu** [comment]
-sw works

![Screenshot 2024-02-11 at 01 24 12](https://github.com/ValveSoftware/Dota2-Gameplay/assets/95012/1f084d4b-00ea-4289-96ca-bdbb6e7a2f8d)

**Comment by tytygelu** [comment]
-sw works

![Screenshot 2024-02-11 at 01 24 12](https://github.com/ValveSoftware/Dota2-Gameplay/assets/95012/c44320d3-bb1a-4f3d-823e-904881f262fc)

![Screenshot 2024-02-11 at 01 26 48](https://github.com/ValveSoftware/Dota2-Gameplay/assets/95012/21a21ded-74da-462e-a608-54b55c59aee0)

**Comment by wenqf11** [comment]
<img width="957" alt="image" src="https://github.com/ValveSoftware/Dota2-Gameplay/assets/3581877/02fad13c-2e03-4f6b-98dc-45b261bf4372">
not works for me

**Comment by tytygelu** [comment]
just "-sw"

![Screenshot 2024-02-11 at 22 43 32](https://github.com/ValveSoftware/Dota2-Gameplay/assets/95012/a0e1ce08-49c2-4a39-94fc-b9c2cd5c44b0)

**Comment by tytygelu** [comment]
and you play it in window mode

![Screenshot 2024-02-11 at 22 47 46](https://github.com/ValveSoftware/Dota2-Gameplay/assets/95012/06948285-fbf5-488b-96b4-1b07456aca91)

**Comment by linxkaa** [comment]
changing the resolution after in game doesn't give me crash, you can change to desktop friendly fullscreen mode every time u enter dota. but pls fix this ASAP valveee why mac user have the least support :(

**Comment by xxtochoxx** [comment]
In exclusive mode, the game breaks and a huge red screen appears.
![Captura de pantalla 2024-02-12 a la(s) 12 50 15](https://github.com/ValveSoftware/Dota2-Gameplay/assets/7839541/126dac60-afdd-4414-83fc-d59bc44a6cab)

**Comment by xxtochoxx** [comment]
in window mode and with the following configuration the appearance and slowness are improved but it is not feasible until today for it to work on the entire screen
<img width="1347" alt="Captura de pantalla 2024-02-12 a la(s) 13 05 00" src="https://github.com/ValveSoftware/Dota2-Gameplay/assets/7839541/5f757bb8-e759-4da3-a65f-206c66c3882d">

**Comment by mylaluna** [comment]
Just verified on my Macbook that this issue is fixed.

**Comment by josefdclxvi** [comment]
i have encountered the same issue, crashing dota2 on mac. im not so sure how and i dont know how do i reproduce the issue. it sometimes happens when playing only AI/bot (a lot of time always crashing) just to test the new patch. sometimes when playing ranked/unranked.

![Screenshot 2024-06-08 at 15 21 55](https://github.com/ValveSoftware/Dota2-Gameplay/assets/45645153/29bcc28e-8175-44f4-ba47-d56b090f8418)

**Comment by waadeetv** [comment]
Thank you for this info even if it is a bit old. I am a new play to the Dota2 Game & was unable to access any of it. Launching it from Steam Games just crashed each time until I had added [ -sw ] in properties 
![Screenshot 2024-07-21 at 11 46 30 PM](https://github.com/user-attachments/assets/ef50447b-bf63-4dad-8428-a522c8f84e74)

**Comment by Soarrre** [comment]
Launch through the game folder : dota 2 beta / game / bin / osx64 / dota2

this worked for me, try it out :)

**Comment by SpinachXPasta** [comment]
Aswome, this helps me as well. I am using the following options to also adjust the height. -sw -w 1750 -h 1000 -noborder

**Comment by cuong-dang** [comment]
> i have encountered the same issue, crashing dota2 on mac. im not so sure how and i dont know how do i reproduce the issue. it sometimes happens when playing only AI/bot (a lot of time always crashing) just to test the new patch. sometimes when playing ranked/unranked.
> 
> ![Screenshot 2024-06-08 at 15 21 55](https://github.com/ValveSoftware/Dota2-Gameplay/assets/45645153/29bcc28e-8175-44f4-ba47-d56b090f8418)

I'm experiencing the same issue on M4 Pro.

**Comment by zi6di** [comment]
sudo  /Users/**/Library/Application\ Support/Steam/steamapps/common/dota\ 2\ beta/game/dota.sh

** Replace with your username

**Comment by zachdaniel** [comment]
Same issue here.

**Comment by yordanvpetrov** [comment]
MacBook Pro M4 OS 26.2 I still have same issue. I tried everything from above and still crashes... It crash everytime when the game start playing. 

Is anyother option I ca try?
