### ISSUE TITLE
Can't equip CM persona from Dragons gift update

### ISSUE THREAD

**Issue by mkrakowitzer** [ValveSoftware/Dota2-Gameplay#15262]
### Cosmetic Item Name

Spirit of the Frozen Flow

### Description

 I got the CM personal from one of the chests. I do not own any previous CM personas. Even though I have unbundled it and equiped it. It can not be selected when playing a game with her. 

### Example Match ID

no match id

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/454776/9efdfa80-1220-417a-bced-4ef0e22fd140)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/454776/b5877585-69c4-4557-9003-cc01913898b3)

**Comment by weapongroza** [comment]
have a same problem, think need a wait hotfix

**Comment by Moki-Weak** [comment]
Також вибив новий скін на CM ну неможу спорядити його до матчу

**Comment by weapongroza** [comment]
> Також вибив новий скін на CM ну неможу спорядити його до матчу

гадаю це баг, може за добу пофіксять 
бо у героя має бути перемикач (як у Мірани)
![20240209033945_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/159502042/26d84500-226c-43ad-b1f9-40d0f299edb1)

**Comment by sanekmashina** [comment]
Вы не сможете использовать этот сет, потому что в наборе отсутствует сама личность цм

**Comment by weapongroza** [comment]
> Вы не сможете использовать этот сет, потому что в наборе отсутствует сама личность цм

трудно понять тогда почему этот набор есть в ящике..

**Comment by sanekmashina** [comment]
> > Вы не сможете использовать этот набор, так как в наборе отсутствует сама личность цм.
> 
> тогда трудно понять, почему этот набор есть в ящике..

ага) я на радостях купил за 6 соток, а там как говорится х.й плавал, а не личность на девочку цмочку

**Comment by weapongroza** [comment]
> > > Вы не сможете использовать этот набор, так как в наборе отсутствует сама личность цм.
> > 
> > 
> > тогда трудно понять, почему этот набор есть в ящике..
> 
> ага) я на радостях купил за 6 соток, а там как говорится х.й плавал, а не личность на девочку цмочку

теперь понятно почему на ТП так дешево сливают набор

**Comment by weapongroza** [comment]
![зображення](https://github.com/ValveSoftware/Dota2-Gameplay/assets/159502042/bbfc05fd-c284-48b0-a24a-2078dcd63d06)
персону выдадут позже

**Comment by sanekmashina** [comment]
>  Персону выдаст позже
отпишешь когда придёт личность? а то я че-то ваще не уверен в том что мне кто-то что-то выдаст)

**Comment by sanekmashina** [comment]
криво комментарий написал, ну ладно

**Comment by h6rd** [comment]
> отпишешь когда придёт личность? а то я че-то ваще не уверен в том что мне кто-то что-то выдаст)

Должны, этот сет изначально содержал личность, просто это баг

**Comment by weapongroza** [comment]
> отпишешь когда придёт личность? а то я че-то ваще не уверен в том что мне кто-то что-то выдаст)

+
Главное что бы бан не дали )

**Comment by sanekmashina** [comment]
> > отпишешь когда придёт личность? а то я че-то ваще не уверен в том что мне кто-то что-то выдаст)
> 
> Должно быть, этот набор изначально устанавливает личность, просто это ошибка ![chrome_YKmr5OBSub](https://private-user-images.githubusercontent.com/51972490/303643997-09439dde-de49-42cd-91c2-1dcbedd17f24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0OTQzNDgsIm5iZiI6MTcwNzQ5NDA0OCwicGF0aCI6Ii81MTk3MjQ5MC8zMDM2NDM5OTctMDk0MzlkZGUtZGU0OS00MmNkLTkxYzItMWRjYmVkZDE3ZjI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA5VDE1NTQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlYzJhZWUzZmQzYjE0M2QxYWJiMDg3ZjAzZjc4MzNjYjM1MzFjNWJlODA3MjA2MTM5Nzg3MmNmN2E4MzhjYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0bKzjkoXEiUTgB_qFqpWEbiOFPBZqIksIUbRlTBgowM)

![IMG_20240209_190243_980](https://github.com/ValveSoftware/Dota2-Gameplay/assets/159502687/badddaf6-f5aa-4c25-be86-c49451293861)
да тут сомнения чисто из-за того что я изначально сетик купил без личности)

**Comment by weapongroza** [comment]
> > > отпишешь когда придёт личность? а то я че-то ваще не уверен в том что мне кто-то что-то выдаст)
> > 
> > 
> > Должно быть, этот набор изначально устанавливает личность, просто это ошибка ![chrome_YKmr5OBSub](https://private-user-images.githubusercontent.com/51972490/303643997-09439dde-de49-42cd-91c2-1dcbedd17f24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0OTQzNDgsIm5iZiI6MTcwNzQ5NDA0OCwicGF0aCI6Ii81MTk3MjQ5MC8zMDM2NDM5OTctMDk0MzlkZGUtZGU0OS00MmNkLTkxYzItMWRjYmVkZDE3ZjI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA5VDE1NTQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlYzJhZWUzZmQzYjE0M2QxYWJiMDg3ZjAzZjc4MzNjYjM1MzFjNWJlODA3MjA2MTM5Nzg3MmNmN2E4MzhjYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0bKzjkoXEiUTgB_qFqpWEbiOFPBZqIksIUbRlTBgowM)
> 
> ![IMG_20240209_190243_980](https://private-user-images.githubusercontent.com/159502687/303707704-badddaf6-f5aa-4c25-be86-c49451293861.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0OTg3ODYsIm5iZiI6MTcwNzQ5ODQ4NiwicGF0aCI6Ii8xNTk1MDI2ODcvMzAzNzA3NzA0LWJhZGRkYWY2LWY1YWEtNGMyNS1iZTg2LWM0OTQ1MTI5Mzg2MS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOVQxNzA4MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YjBjZjI5ZDk2NzlhZDRmMjg3ZTMzNWFjNmRiNTFmZTUzOGJmMTJiOWJmZjE1NzYzOTAxZWE1MGU5ZmYzNzAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2wez2VO_yCdJqvRCrtrzpp5ZqiixXPL_YoeRlhDQPvc) да тут сомнения чисто из-за того что я изначально сетик купил без личности) а так конечно да если выдадут личность буду рад очевидный момент

там уже в ящике личность добавили, но на аккаунте так и не появилась.
написал в суппорт
жду
в прошлый раз за 2 часа ответили
отпишусь как будет что то новое

**Comment by weapongroza** [comment]
> > > отпишешь когда придёт личность? а то я че-то ваще не уверен в том что мне кто-то что-то выдаст)
> > 
> > 
> > Должно быть, этот набор изначально устанавливает личность, просто это ошибка ![chrome_YKmr5OBSub](https://private-user-images.githubusercontent.com/51972490/303643997-09439dde-de49-42cd-91c2-1dcbedd17f24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0OTQzNDgsIm5iZiI6MTcwNzQ5NDA0OCwicGF0aCI6Ii81MTk3MjQ5MC8zMDM2NDM5OTctMDk0MzlkZGUtZGU0OS00MmNkLTkxYzItMWRjYmVkZDE3ZjI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA5VDE1NTQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlYzJhZWUzZmQzYjE0M2QxYWJiMDg3ZjAzZjc4MzNjYjM1MzFjNWJlODA3MjA2MTM5Nzg3MmNmN2E4MzhjYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0bKzjkoXEiUTgB_qFqpWEbiOFPBZqIksIUbRlTBgowM)
> 
> ![IMG_20240209_190243_980](https://private-user-images.githubusercontent.com/159502687/303707704-badddaf6-f5aa-4c25-be86-c49451293861.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1NDg2MDIsIm5iZiI6MTcwNzU0ODMwMiwicGF0aCI6Ii8xNTk1MDI2ODcvMzAzNzA3NzA0LWJhZGRkYWY2LWY1YWEtNGMyNS1iZTg2LWM0OTQ1MTI5Mzg2MS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMFQwNjU4MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODQxODU3YjA5NmY5OGQxN2U1NDg5NDc4MDJmZjUwMzQzMjI3MTJmZmRlYTU4YzNhZmJiMjk5NzQxNDAyZGI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DD_fvzgF2VcWUP7gR0wxd0-t_VMYcH0dRBwc2DgpoQw) да тут сомнения чисто из-за того что я изначально сетик купил без личности) а так конечно да если выдадут личность буду рад очевидный момент

спустя 12 часов саппорт выдал мне личность 
![20240210090026_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/159502042/4543c2de-9d51-4716-879e-8ab4f3e78379)
![20240210090030_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/159502042/cc5c454e-378f-4043-819e-3b61ad7616ff)
так что если у тебя еще не появилось, то напиши в поддержку

**Comment by sanekmashina** [comment]
> > > > отпишешь когда придёт личность? а то я че-то ваще не уверен в том что мне кто-то что-то выдаст)
> > > 
> > > 
> > > Должно быть, этот набор изначально устанавливает личность, просто это ошибка ![chrome_YKmr5OBSub](https://private-user-images.githubusercontent.com/51972490/303643997-09439dde-de49-42cd-91c2-1dcbedd17f24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0OTQzNDgsIm5iZiI6MTcwNzQ5NDA0OCwicGF0aCI6Ii81MTk3MjQ5MC8zMDM2NDM5OTctMDk0MzlkZGUtZGU0OS00MmNkLTkxYzItMWRjYmVkZDE3ZjI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA5VDE1NTQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlYzJhZWUzZmQzYjE0M2QxYWJiMDg3ZjAzZjc4MzNjYjM1MzFjNWJlODA3MjA2MTM5Nzg3MmNmN2E4MzhjYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0bKzjkoXEiUTgB_qFqpWEbiOFPBZqIksIUbRlTBgowM)
> > 
> > 
> > ![IMG_20240209_190243_980](https://private-user-images.githubusercontent.com/159502687/303707704-badddaf6-f5aa-4c25-be86-c49451293861.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1NDg2MDIsIm5iZiI6MTcwNzU0ODMwMiwicGF0aCI6Ii8xNTk1MDI2ODcvMzAzNzA3NzA0LWJhZGRkYWY2LWY1YWEtNGMyNS1iZTg2LWM0OTQ1MTI5Mzg2MS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMFQwNjU4MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODQxODU3YjA5NmY5OGQxN2U1NDg5NDc4MDJmZjUwMzQzMjI3MTJmZmRlYTU4YzNhZmJiMjk5NzQxNDAyZGI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DD_fvzgF2VcWUP7gR0wxd0-t_VMYcH0dRBwc2DgpoQw) да тут сомнения чисто из-за того что я изначально сетик купил без личности) а так конечно да если выдадут личность буду рад очевидный момент
> 
> спустя 12 часов саппорт выдал мне личность ![20240210090026_1](https://private-user-images.githubusercontent.com/159502042/303821353-4543c2de-9d51-4716-879e-8ab4f3e78379.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1NTA3MjksIm5iZiI6MTcwNzU1MDQyOSwicGF0aCI6Ii8xNTk1MDIwNDIvMzAzODIxMzUzLTQ1NDNjMmRlLTlkNTEtNDcxNi04NzllLThhYjRmM2U3ODM3OS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMFQwNzMzNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NDI0NmM4NmU3MzZlNGJmMzI4NDNhNDU3OWUwNDIzNzhlMWJhZDI0MWUzZmM5NjU2NDdjMDk0ZTRkMDE0N2MxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oOMCW7_Vjye-hsanf9AZ1A27fwva8GXsb1TPCGOGzkg) ![20240210090030_1](https://private-user-images.githubusercontent.com/159502042/303821355-cc5c454e-378f-4043-819e-3b61ad7616ff.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1NTA3MjksIm5iZiI6MTcwNzU1MDQyOSwicGF0aCI6Ii8xNTk1MDIwNDIvMzAzODIxMzU1LWNjNWM0NTRlLTM3OGYtNDA0My04MTllLTNiNjFhZDc2MTZmZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMFQwNzMzNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MzJhNzI1ZjgyYTg1ODdkM2Y0Mjg0MzZiMDgwYzlkOGI2MjVhNzEyNGEwM2UzNjY3MjljMjE4ZWNmYTdlN2IzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aAN0B4KEbKOMekMcn6_aq5P4ggMXJxZzEFTxFycRcGw) так что если у тебя еще не появилось, то напиши в поддержку

ща проверил, мне тоже выдали

**Comment by mkrakowitzer** [comment]
I was awarded the persona by support, thank you. Closing this ticket.
