### ISSUE TITLE
Can't watch replays, a message pops up after a good 10 seconds then the game crashes.

### ISSUE THREAD

**Issue by theghettofresh** [ValveSoftware/Dota2-Gameplay#15276]
### Description

Every time I try to watch a replay. my game will crash after a message will pop up saying "CopyExistingEntity: missing clienty entity 1219. I've validated my game files, reinstalled, redownloaded the replay. Nothing.

### Screenshots

![Screenshot 2024-02-08 220235](https://github.com/ValveSoftware/Dota2-Gameplay/assets/144865397/871132a5-a7d2-496b-9250-9205eb97112d)

**Comment by boasmithc** [comment]
I'm getting a very similar error when watching a replay.
![dotaerror](https://github.com/ValveSoftware/Dota2-Gameplay/assets/20523395/8168fa9d-82a8-431c-b072-15fd1f25ee52)

**Comment by tryhardkaiken** [comment]
i guess it's the new update
![replayerror](https://github.com/ValveSoftware/Dota2-Gameplay/assets/159512657/e632e918-1f1c-4897-b76d-1b730ebd14b8)

**Comment by helix-d2** [comment]
Same issue here, I can't watch replays, haven't played the game after today's update yet. Hope it doesn't affect that. 
![Screenshot 2024-02-09 122407](https://github.com/ValveSoftware/Dota2-Gameplay/assets/67186043/c60c6aca-bfb9-4237-93b3-aabb6a042c00)

**Comment by helix-d2** [comment]
Ok so it seems, only older replays crash the game for me, current patch replays work just fine.

**Comment by wekcbadct** [comment]
![Screenshot 2024-02-09 030720](https://github.com/ValveSoftware/Dota2-Gameplay/assets/159522087/da6fd814-a4ce-47f4-872b-be0681cd2026)
![Screenshot 2024-02-09 031009](https://github.com/ValveSoftware/Dota2-Gameplay/assets/159522087/f4db69c9-6ccb-49fc-b35b-9d5260a3e8b8)

same error match id: 7573084685

**Comment by w200me** [comment]
All the replays before the patch are broken, new ones are fine. Bump.

**Comment by theghettofresh** [comment]
Well hopefully it gets fixed soon. I've been trying to watch a couple replays to review for myself and a buddy.

**Comment by theghettofresh** [comment]
Issue resolved, old replays can now be watched again.
