### ISSUE TITLE
Cannot connect to a found match. 

### ISSUE THREAD

**Issue by JDotes29** [ValveSoftware/Dota2-Gameplay#15297]
### Description

I need help because I cannot connect to a found match, whether it's on normal or ranked, checking on available servers I'm seeing low 40's on both Japan and SEA servers that's where I'm queuing. It wasn't like this before the Chinese New Year update, I have updated my client, restarted Steam, restarted my PC, and reinstalled DotA 2 already. I've ran out of options that's why I'm contacting you now.

I've already been penalized multiple times by match cooldowns from 2 minutes to an hour now. Please help! Thanks!

### Example Match ID (and possibly Timestamp)

NA

### Screenshots

![vlcsnap-2024-02-09-17h29m32s898](https://github.com/ValveSoftware/Dota2-Gameplay/assets/159527569/895cc165-8ffd-4a90-ba8e-b54e5eea29d5)
![vlcsnap-2024-02-09-17h30m13s199](https://github.com/ValveSoftware/Dota2-Gameplay/assets/159527569/56f513dc-66a0-4d79-9821-f439a151937c)
![vlcsnap-2024-02-09-17h30m19s932](https://github.com/ValveSoftware/Dota2-Gameplay/assets/159527569/e28c3fd5-1e39-4d38-ac69-2303c3fc3335)
![vlcsnap-2024-02-09-17h30m28s246](https://github.com/ValveSoftware/Dota2-Gameplay/assets/159527569/fb504695-e43f-4219-a88a-f3021c4e7dc0)

**Comment by DocMorg** [comment]
Same error! 
Checked game files and etc. nothing helps
Found on forum that this bug is from 2015

**Comment by Riismannen** [comment]
Same here….. very frustrating

**Comment by amir90002** [comment]
same here ....

**Comment by fasjkhygfda8yhgfiuqwyehi7u** [comment]
same guys

**Comment by amir90002** [comment]
so many guys sayed it's Bug at 2015

**Comment by Nathhhhhhhhhhhhhhhhhhhhh** [comment]
bro i get 2 hrs q banned and 4 LP match for this, fix this please

**Comment by JDotes29** [comment]
Deleting the bin folder inside the Dota steamapps folder didn't help me.

**Comment by JDotes29** [comment]
What fixed the issue for me is unticking / unchecking the "Run as administrator" on the "dota.exe" inside the game folder. I hope this help you guys in the future.
