### ISSUE TITLE
Linux hotkeys after patch

### ISSUE THREAD

**Issue by Snowurm** [ValveSoftware/Dota2-Gameplay#15307]
### Description

In the most recent patch,some keys that were bindable to items/abilities in previous patch, are no longer bindable in the current patch. 
OS: Linux/Debian
Example: Finnish keyboard layout < binded to town portal scroll, worked in previous patch. The key is no longer bindable and doesn't work in the current patch.

Could this be fixed? Thank you in advance.

### Example Match ID (and possibly Timestamp)

Not available

**Comment by lvlyRyuzaki** [comment]
Same problem on windows machine, and german keyboard

cant bind my "<" key

**Comment by SylvainBoilard** [comment]
There is an option called something like "bind keys according to their physical keyboard location" under Advanced Shortcuts, in the Shortcut Options section. It might have been modified recently and messed your configuration, try enabling/disabling it to see if that fixes your issue.

**Comment by Snowurm** [comment]
> There is an option called something like "bind keys according to their physical keyboard location" under Advanced Shortcuts, in the Shortcut Options section. It might have been modified recently and messed your configuration, try enabling/disabling it to see if that fixes your issue.

This worked and fixed the issue, thank you.
