### ISSUE TITLE
After unpacking the new set "Spirit of the Frozen Flow", I was not given Persona Crystal Maiden (Wolf)

### ISSUE THREAD

**Issue by vampujnik** [ValveSoftware/Dota2-Gameplay#15327]
### Cosmetic Item Name

Spirit of the Frozen Flow

### Description

Today, Feb 9 3:25 am, I received the "**Spirit of the Frozen Flow**" item in the treasury, opened it and realized that I had not received a **person** for this skin. At the moment, this set includes a person for **CM**, but it is not in my steam and dota 2 inventory.

### Example Match ID

-

### Screenshots

![1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/159554888/d126f55b-8b81-4168-80d7-f8b41d1e985f)
![2](https://github.com/ValveSoftware/Dota2-Gameplay/assets/159554888/f1ae6360-ccd6-4382-a61f-af2cfe60a454)
![3](https://github.com/ValveSoftware/Dota2-Gameplay/assets/159554888/1bf50245-fc34-47f3-9483-a8bde262b9eb)
![4](https://github.com/ValveSoftware/Dota2-Gameplay/assets/159554888/7f5bd548-fb6e-46eb-aae4-7f2ce89b44a6)

**Comment by akrumiki** [comment]
такая же фигня

**Comment by vampujnik** [comment]
> такая же фигня

невнимательность, плюс поторопились) я думал, так и должно быть, пока не увидел, что сет Turstarkuri Pilgrim(антимаг(вей)) имеет такое же качество + включает в себя саму персону

**Comment by akrumiki** [comment]
там даже если кликнуть информация о наборе пишет, что сет персону включает, ждем фикс получается?

**Comment by vampujnik** [comment]
> ам даже если кликнуть информация о наборе пишет, что сет персону включает, ждем фикс получается?

ну когда я распаковал предмет, такой информации не было) будет забавно, если скажут докупать на торговой площадке или открывать новую))

**Comment by jfbigorna** [comment]
same

**Comment by akrumiki** [comment]
> > ам даже если кликнуть информация о наборе пишет, что сет персону включает, ждем фикс получается?
> 
> ну когда я распаковал предмет, такой информации не было) будет забавно, если скажут докупать на торговой площадке или открывать новую))

не смешно будет

**Comment by almute4** [comment]
такая же проблема. только у моего кента все в наличии в то время как у меня только шмотки на личность(((( написал в поддержку и молюсь чтоб помогли или пофиксили

**Comment by Nathanael-Valve** [comment]
See https://github.com/ValveSoftware/Dota2-Gameplay/issues/15335
