### ISSUE TITLE
I didn't get all the items from the Crystal Made Spirit of the Frozen Flow package

### ISSUE THREAD

**Issue by Gofelerion** [ValveSoftware/Dota2-Gameplay#15335]
### Cosmetic Item Name

 Crystal Made Spirit of the Frozen Flow

### Description

I didn't get persona for crystal maiden

### Example Match ID

/

### Screenshots

![Знімок екрана 2024-02-09 191950](https://github.com/ValveSoftware/Dota2-Gameplay/assets/159568500/a21d9027-1b56-444c-bec3-885c437a9c00)
![Знімок екрана 2024-02-09 192146](https://github.com/ValveSoftware/Dota2-Gameplay/assets/159568500/c09d7165-25e6-46f6-9adb-c9f8773e0a25)
![Знімок екрана 2024-02-09 192257](https://github.com/ValveSoftware/Dota2-Gameplay/assets/159568500/0c7e1717-717e-4f0c-8d60-c574267cb155)

**Comment by Gofelerion** [comment]
![Знімок екрана 2024-02-09 195246](https://github.com/ValveSoftware/Dota2-Gameplay/assets/159568500/d78b5981-c62b-455a-94d2-554b4b7d6017)

**Comment by Gofelerion** [comment]
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/159568500/af075b1e-5744-4d0b-b9f7-7503f6842446)

**Comment by almute4** [comment]
I have the same problem. I'm currently waiting for help from support

**Comment by AksisSA** [comment]
We'll probably have to wait for a fix, and hopefully the items will be given out as well.

**Comment by Nathanael-Valve** [comment]
This was fixed going forward and we are granting the missing items to affected accounts today.
