### ISSUE TITLE
I didn't get all the items from the Crystal Made Spirit of the Frozen Flow package

### ISSUE THREAD

**Issue by AN855** [ValveSoftware/Dota2-Gameplay#15332]
### Item name

Crystal Maiden(The wolf),Blueheart Familiar

### Description

![2024-02-10_01-44-37](https://github.com/ValveSoftware/Dota2-Gameplay/assets/159559752/57044003-d19c-4dbc-b179-fc1db8ed9864)
![2024-02-10_01-44-53](https://github.com/ValveSoftware/Dota2-Gameplay/assets/159559752/341e8a98-9da7-4898-9427-83edb0647c6b)
I bought a set from the marketplace and I got only parts of the skin, but I didn't get the Crystal Maiden personality and the pet.

### Example Match ID and Timestamp

.

**Comment by Nathanael-Valve** [comment]
See https://github.com/ValveSoftware/Dota2-Gameplay/issues/15335

**Comment by AN855** [comment]
And how long to wait for the delivery of items?
