### ISSUE TITLE
Time Warp Aura - passive from Ancient Frostbitten Golem - Tooltip broken

### ISSUE THREAD

**Issue by ETalanian** [ValveSoftware/Dota2-Gameplay#1536]
### Hero and spell

Ancient Frostbitten Golem - Time Warp Aura

### Description

When controlling an Ancient Frostbitten Golem, nearby allies gain Time Warp Aura.  The buff bar tooltip shows the #Dota_Tooltip_Modifier... thing instead of "Gaining 10% cooldown reduction"

**Comment by TheUnholyWrath** [comment]
This has been fixed, you can close this issue.
