### ISSUE TITLE
Performance drop

### ISSUE THREAD

**Issue by maxence33** [ValveSoftware/Dota2-Gameplay#15374]
### Description

Since last update performance dropped significantly to the point it is barely playable.
FPS were about 90-100 now 60-70 but game experience feels really worse than that.
My NVIDIA DRIVER is 535 under Ubuntu 20.04.6
Card is NVIDIA GP107 Geforce GTX 1050 TI

(Also keyboard seemed remapped to Querty but easy to bring back to Azerty)

**Comment by DragoniteDuskull** [comment]
For me too

**Comment by maxence33** [comment]
Seems much better after 17 february patch
