### ISSUE TITLE
Unable to connect to matchmaking lobby after accepting a match

### ISSUE THREAD

**Issue by envp** [ValveSoftware/Dota2-Gameplay#15386]
### Description

This has started manifesting since the Feb 9 2024 update (after 5PM Eastern Time), there have been various issues with connecting to matchmaking for me.

The most pressing one is being unable to connect to a game after accepting a match:

### Steps I took
1. Click on "Find Match"
2. Accept the found match
3. Status indicator on bottom right says "Connecting ...", but client is never able to join after screen transitions to black
4. Client disconnects from game automatically, and pressing the "Reconnect" button goes through the same cycle of [connecting -> black screen -> disconnect]
5. Received matchmaking time-out

### Workarounds
Re-installing the game helped once, but it only helped with the first game I found. The connection issue re-surfaced in the next game I tried to queue on. I am currently sitting at 4 failed attempts.

Re-installing the game after every match also isn't a great solution.

For me deleting the "bin/" folder and re-acquiring it using the "Verify Integrity" feature **does not** help. I can join a custom lobby, spectate game but get kicked out of matchmaking.

### Console logs
Here are console logs, hopefully this is useful: [dota2_console_logs.txt](https://github.com/ValveSoftware/Dota2-Gameplay/files/14230469/dota2_console_logs.txt)

### Related discussion
Seems this is a rather widespread issue
https://www.reddit.com/r/DotA2/comments/1ammm81/cant_connect_to_game_after_accepting_match/

cc @wykrhm @jeffhill please take a look soon! I'm happy to provide any other info/logs required to debug this.

### Example Match ID (and possibly Timestamp)

None

### Screenshots

My region is US East, and I faced this issue connecting to **Europe West Turbo servers**. I am able to reproduce it using a custom lobby. The repro video below, and the experience connecting to a real game is exactly the same:

[Europe West bug repro](https://github.com/ValveSoftware/Dota2-Gameplay/assets/3663231/17c26f28-7482-46d2-b5d3-391d5ae2a103)

I am however, able to create an join a US East/US West lobby. But I am afraid to queue to test this because any more timeouts might mean worse consequences.

**Comment by arcticburn** [comment]
If it crashes after you click accept button try deleting all steam information in regedit. I used programm "Reg Organiser". Open regedit and search for "steam", "dota", "valve" and delete all. Helped me.

**Comment by envp** [comment]
> If it crashes after you click accept button try deleting all steam information in regedit. I used programm "Reg Organiser". Open regedit and search for "steam", "dota", "valve" and delete all. Helped me.

There's no crash, I stay in the client the whole time but can't join the match I just accepted.

**Comment by francois-engelbrecht** [comment]
What seems to work for me is I have to clear the cache after every game. Steam Client > Settings > Downloads > Clear Download Cache. This is what provides me with the highest success rate. I've re-installed the game didn't work works once and then the very next game issue resurfaces, verified the files didn't work. 

Imo, it seems like it has something to do with the caching mechanism

**Comment by envp** [comment]
> What seems to work for me is I have to clear the cache after every game. Steam Client > Settings > Downloads > Clear Download Cache. This is what provides me with the highest success rate. I've re-installed the game didn't work works once and then the very next game issue resurfaces, verified the files didn't work.
> 
> Imo, it seems like it has something to do with the caching mechanism

Are you connecting to EU West? The issue seems to be server specific to me at least, I am able to queue on SEA pretty consistently. That seems to be my working hypothesis

**Comment by Darentei** [comment]
Myself and many friends have had this issue as well. We usually play on EU so that could be true. Not the first time EUW had problems.

**Comment by victorgugo95** [comment]
any actions were taken for this issue?
I've never left a game and now got a ban and have to win 5 SD games in order to play AP again because of this issue. (I even got disconnected during the match)

**Comment by MarlonAEC** [comment]
I never had this issue before until the year of the dragon patch, Now I got banned because of it for 2 minutes. Any solutions or tips on this one?

**Comment by victorgugo95** [comment]
Does anyone know if the most recent update fixes the issue?

**Comment by envp** [comment]
Fixed in a recent update.
