### ISSUE TITLE
Getting Healing Lotus removes Spells from all heroes

### ISSUE THREAD

**Issue by Bloppppppp** [ValveSoftware/Dota2-Gameplay#15414]
### Description

Picking up a Healing Lotus causes all 10 heroes to lose their spells in Ability draft

It doesn't happen every game, but just had 2 games in a row with this bug & it makes AD unplayable. Happens since we got the AD-patch 3 days ago - or to be clear i heard it happend before but since patch I heard from multiple people with that issue, who never experienced it before. 

Match-IDs: 7582110690, 7582160723, 7580450926

Video etc. can be found here: https://www.reddit.com/r/DotA2/comments/1aok72a/gamebreaking_bug_in_ability_draft_getting_healing/

### Example Match ID (and possibly Timestamp)

7582110690 7582160723 7580450926 always at 3min lotus
Additional match-ids: 7590347603 7590347603

**Comment by zycboss** [comment]
After almost a month, still no fix to this problem? 
This exists since the recent major AD patch, and why so hard to fix it?
Do heroes really need specific hidden abilities only for interacting with certain things on the map? This is not how DOTA use to work.

**Comment by chrisf-valve** [comment]
Thank you for the report! We've just shipped some additional server logging to try and track down the issue. If anyone comes across this bug in the future, please comment with the match id and it will be investigated.

**Comment by cy2000** [comment]
Just had a game with this bug
match id 7623150868
at 3 minutes Sven picked up a healing lotus at bottom line

**Comment by chrisf-valve** [comment]
Thank you for the follow up information, we have located the source of the bug and have just deployed a fix. This should be completely resolved, but if you run across disappearing abilities again feel free to re-open this bug (or @ me on a new bug)
