### ISSUE TITLE
Horrible Matchmaking

### ISSUE THREAD

**Issue by saeedbackfire** [ValveSoftware/Dota2-Gameplay#15451]
### Description

Hi, I'm not a toxic gamer at all You can understand from my rating. Unfortunately the kids who befriend me are not only bad people but also extremely clumsy and stubborn and I experience weak enemies who are much stronger than me are i can't hit a creep in the game don't take it easy my problem is really crazy please check my account status please i love this game and i really want to succeed in this game please help me I am a Dota 2 player with ID 1216334309 and my name is SaeedBackfire.

### Example Match ID (and possibly Timestamp)

7586552721

**Comment by DragoniteDuskull** [comment]
Party q is so much harder that a solo q. Don't play party if you want to gain mmr
