### ISSUE TITLE
Bug on the drop of Ultra rare item on treasure Dragon's Hoard

### ISSUE THREAD

**Issue by Chalsinton** [ValveSoftware/Dota2-Gameplay#15495]
### Description

Hi, I think the drop of ultra rare items its is bugged for my account. 

I had opened 74 treasures, and still didn't get any drop of ultra rare items (neither the ancient or the primal beast one). 

At this point, accordingly to the escalating odds information, my odd of this happening its 2.802 E - 257 (It means, 257 zeros before the 0,2%, so close to impossible that looks like it must be bugged).       

I add the 2 screenshots to prove that its my 75 attempt, and still nothing (its hard to identify that they are different rewards but you can see in the background the primal beast in one, and the ancient dragon in the other).

Can we do something to try to repair this, almost sure,  99,99% (and 257 nines after), bug in my account? 

Thanks in advance. 
 

### Screenshots

![Ancient 74 attempts not getting it](https://github.com/ValveSoftware/Dota2-Gameplay/assets/160287765/523eba38-e1a8-4388-974f-e2a23cc9c7bb)

![Primal beast 74 attempts not getting it](https://github.com/ValveSoftware/Dota2-Gameplay/assets/160287765/8162f31e-9d95-41a9-ab0e-fad8e0e1ca18)

**Comment by Aluerie** [comment]
your math is wrong, the answer is about 3%.
