### ISSUE TITLE
I swear valve you do this shit on purpose

### ISSUE THREAD

**Issue by jcho796** [ValveSoftware/Dota2-Gameplay#15528]
### Description

Why is that every fucking game I get fucking retards just throwing and feeding? Do you do this shit on purpose valve? I don't understand not one single fucking game I get normal fucking players who actually play dota properly is actually absurd. Your matchmaking system is horrendous please fucking fix. Stop matching me with retard heralds and guardians who have absolutely 0 clue how to fucking play. Please make a separate fucking lobby for fucking noob heralds and guardians. I literally can not fucking take this anymore.
PLEASEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

### Example Match ID (and possibly Timestamp)

7595093962

**Comment by jcho796** [comment]
More match IDs
7594971623 - I was playing zeus, but my fucking dumbass pudge buybacks and runs down mid and throws like wtf....
7594937870 - Only person that has fucking positive kd everyone one else jerking off doing random shit and just feeding...
7593259587 - Do I even have to explain any further?
7591386988 - Again... all feeding except me

**Comment by stiggy87** [comment]
This isn't a bug, just an irate player.

Go outside and take a break. You're putting too much into a game.

**Comment by TobyFlendersonFromHR** [comment]
if you really want to see a bug, just go outside and look for some on the trees

**Comment by jcho796** [comment]
> This isn't a bug, just an irate player.
> 
> Go outside and take a break. You're putting too much into a game.

bro I literally took so many breaks you don't understand its every fucking game i come back to

**Comment by jcho796** [comment]
> if you really want to see a bug, just go outside and look for some on the trees

you clearly don't understand the pain i'm going through

**Comment by jcho796** [comment]
7595114333 - and another

**Comment by jcho796** [comment]
> You're basically reporting a bug on matches you're making due to toxic behavior. How is that a bug? Report them and move on. Another thing to look at too is yourself. If you're getting this upset at a video game, then you really need to reprioritize your life in such a way that the game gives you joy, not anger management issues.

you are only saying that because you obviously haven't gone through what I have. Another thing is I DO REPORT EVERYTIME NOTHING HAPPENS LOL for 10+ years this shit company doesn't do anything for the benefits of its players.

**Comment by jcho796** [comment]
> > > if you really want to see a bug, just go outside and look for some on the trees
> > 
> > 
> > you clearly don't understand the pain i'm going through
> 
> is it like childbirth pain or kidney stones pain or asking out your crush and she rejects you pain?

bro has the audacity to say go outside to see bugs and basically lives here LMFAO. Do you have anything else to do besides comment here all day?

**Comment by jcho796** [comment]
> > Do you have anything else to do besides comment here all day?
> 
> i also do ur mom.

lmfao nice one man very original. You are the literal definition of a pathetic useless piece of shit in this society. get a life loser

**Comment by TobyFlendersonFromHR** [comment]
i felt that.

**Comment by jcho796** [comment]
> i felt that.

good that’s exactly what it was meant for
now go touch some grass
