### ISSUE TITLE
config file game\dota\cfg\video.txt doesn't work on windows 11

### ISSUE THREAD

**Issue by gonggqing** [ValveSoftware/Dota2-Gameplay#15594]
### Description

Before I can modify the video.txt cfg file to control the in-game video settings such as resolution, after a recent update (2024.02) this config file can not work anymore. For example, when I modify "setting.defaultres" "setting.defaultresheight", it doesn't affect the in-game settings. I try to delete the video.txt and restart the game, however the config file can not regenerate in the "game\dota\cfg" folder which can work before. Hope this bug could be fixed, we use this for automating graphic card testing.

**Comment by SpiritWinD86** [comment]
video.txt and some other config files from dota's cfg folder was moved to userdata folder (570) in steam\userdata\yourID\570\local\cfg

**Comment by gonggqing** [comment]
Thanks! I have found the target config!
