### ISSUE TITLE
Timbersaw's Whirling Death gives strength gain to enemy targets under the effects of Omniknight's Repel

### ISSUE THREAD

**Issue by JayeMcC** [ValveSoftware/Dota2-Gameplay#15602]
### Ability name

Whirling Death

### Description

If an enemy hero is under the effects of Omniknight's Repel, Timbersaw's Whirling Death will give strength gain to that target instead of having no effect.

### Example Match ID (and possibly Timestamp)

Just playing in hero demo

**Comment by AkovBrick** [comment]
That is how repel works.

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/151986380/f0cbd9ff-879c-41f2-b1c5-5ff71bc44c0b)

**Comment by JayeMcC** [comment]
MB!, closing
