### ISSUE TITLE
Command Console Invisible/Not working

### ISSUE THREAD

**Issue by ahmadesat** [ValveSoftware/Dota2-Gameplay#15607]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/):

Computer Information:
Manufacturer: LENOVO
Model: 82JU
Form Factor: Laptop
No Touch Input Detected
Processor Information:
CPU Vendor: AuthenticAMD
CPU Brand: AMD Ryzen 7 5800H with Radeon Graphics
CPU Family: 0x19
CPU Model: 0x50
CPU Stepping: 0x0
CPU Type: 0x0
Speed: 3194 MHz
16 logical processors
8 physical processors
Hyper-threading: Supported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Supported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Supported
AVX2: Supported
AVX512F: Unsupported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Unsupported
AVX512VNNI: Unsupported
SHA: Supported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported
Operating System Version:
Windows 11 (64 bit)
NTFS: Supported
Crypto Provider Codes: Supported 311 0x0 0x0 0x0
Video Card:
Driver: NVIDIA GeForce RTX 3060 Laptop GPU
DirectX Driver Name: nvldumd.dll
Driver Version: 31.0.15.5161
DirectX Driver Version: 31.0.15.5161
Driver Date: 2 15 2024
OpenGL Version: 4.6
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 143 Hz
DirectX Card: NVIDIA GeForce RTX 3060 Laptop GPU
VendorID: 0x10de
DeviceID: 0x2560
Revision: 0xa1
Number of Monitors: 1
Number of Logical Video Cards: 1
No SLI or Crossfire Detected
Primary Display Resolution: 1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 23.50" x 13.23" (26.97" diag), 59.7cm x 33.6cm (68.5cm diag)
Primary Bus: PCI Express 8x
Primary VRAM: 6143 MB
Supported MSAA Modes: 2x 4x 8x
Sound card:
Audio device: Speakers (Realtek(R) Audio)
Memory:
RAM: 16236 Mb
VR Hardware:
VR Headset: None detected
Miscellaneous:
UI Language: English
Media Type: Undetermined
Total Hard Disk Space Available: 975366 MB
Largest Free Hard Disk Block: 108040 MB
OS Install Date: Feb 25 2023
Game Controller: None detected
Storage:
Disk serial number hash: f6b57b1
Number of SSDs: 1
SSD sizes: 1024G
Number of HDDs: 0
Number of removable drives: 0

* Have you checked for system updates?: [Yes/No] Yes
* Are you using the latest stable video driver available for your system? [Yes/No] Yes
* Have you verified the game files?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
I wanted to open the command console in game, but instead, only cursor changes icon to PC's default cursor, everything works fine, but no console is showing, its invisible probably.

#### Steps for reproducing this issue:

1. Add "-console" to launch properties of Dota in steam
2. Click "~" (or whatever key you have set to open Console)
3. Cursor turns to a default (reading) cursor, but I can't see the console, I can still click on game elements even with an invisible console open.

**Comment by SpiritWinD86** [comment]
This is very old bug with console for many Source games. Do't know how exactly to reproduce this, but you can fix this:
Open cfg file "**machine_convars.vcfg**" with notepad (path- .../Steam/userdata/<yourID>/570/local/cfg/machine_convars.vcfg), search for command **"panorama_console_position_and_size"** , change its value to **"20.00|20.00|1000.00|800.00"** and save.

or you can try to delete this file and verify game's files in steam.

**Comment by ahmadesat** [comment]
@SpiritWinD86 I saw this fix in reddit, tried it but it didn't work, still invisible :/

**Comment by SpiritWinD86** [comment]
> @SpiritWinD86 I saw this fix in reddit, tried it but it didn't work, still invisible :/

Are you sure that you tried changing the value in the file at this path - ...**/Steam/userdata/yourID/570/local/cfg/**?
I ask this because with the latest update "The Dragon's gift" the devs moved this file from the game's folder to the folder listed above. If post on reddit was older then month, then you probably changed the old file (which was there - .../Steam/steamapps/common/dota 2 beta/game/dota/cfg/... ).

Also you can check if the Console still working off screen - if you press your console button and start to write any command, then text\commands can pops up somewhere on screen.

**Comment by ahmadesat** [comment]
Ok this was a weird one, I did the same steps a 2nd time, and it worked!
Thanks @SpiritWinD86

**Comment by m29a** [comment]
> This is very old bug with console for many Source games (console window outside of the screen). Do't know how exactly to reproduce this issue (mb it's happening when alt+tab'ing or when changing display mode), but you can fix this: Open cfg file "**machine_convars.vcfg**" with notepad (path- .../Steam/userdata/>yourID</570/local/cfg/machine_convars.vcfg), search for command **"panorama_console_position_and_size"** , change its value to **"20.00|20.00|1000.00|800.00"** and save.
> 
> or you can try to delete this file and verify game's files in steam.

You have to close dota 2 and steam.
also in lunch options only put  -console  , some command rewrite settings 

thank you. I was searching for solution for hours
