### ISSUE TITLE
Why doesn't Revenant's Brooch work with Sword Pangolier? It's a damage modifier, isn't it?

### ISSUE THREAD

**Issue by D1Angeloo** [ValveSoftware/Dota2-Gameplay#15604]
### Item name

Revenant's Brooch 

### Description

Why doesn't Revenant's Brooch work with Sword Pangolier? It's a damage modifier, isn't it? 

### Example Match ID and Timestamp

Lobby-test

**Comment by Hex2D2** [comment]
It is a physical damage spell that procs attack modifiers, but they are not attacks. This is similar to Snapfire E. The brooch does not affect Snapfire E until you get the 25 talent making it use auto attacks. This is the intended effect.

**Comment by commentator24** [comment]
i think they fixed it.
left side 41 right side 55 when toggled on. works vs ghosted enemies too
currently the only bug is it doesnt cost any mana (but i think 50 mana cost is a bit silly)

should close the issue

**Comment by commentator24** [comment]
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109324155/59d29795-1284-48ed-9156-54a64f612ec1)
i think they fixed it.
left side 41 right side 55 when toggled on. works vs ghosted enemies too
currently the only bug is it doesnt cost any mana (but i think 50 mana cost is a bit silly)

should close the issue
