### ISSUE TITLE
Io Relocate Getting Cancelled/Not Teleporting

### ISSUE THREAD

**Issue by yehlebm** [ValveSoftware/Dota2-Gameplay#15606]
### Ability name

Relocate

### Description

I attempted to relocate Storm Spirit when getting jumped and the teleport never went off for either of us. I didn't relocate back either. 

### Example Match ID (and possibly Timestamp)

7602395275 - 36:03

**Comment by Aluerie** [comment]
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/33165440/6490b2e2-6849-4a74-bc42-c2509732dcda)
