### ISSUE TITLE
[BUG] Some players have additional armor and some less according to agility

### ISSUE THREAD

**Issue by mapeke** [ValveSoftware/Dota2-Gameplay#15617]
### Description

I played 3 matches after the patch and already encountered bug.
As we can see in the screenshot, from the start of the game puck has less armor than he should have from the agility.

![photo_2024-02-24_18-02-36](https://github.com/ValveSoftware/Dota2-Gameplay/assets/126239203/4c34df22-ee13-4b13-ab3d-46fdcb16dd5e)

Centaur also suffered from loss of armor

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/126239203/9061062f-fe09-4827-8bf9-876f43aec4f6)

but in the other hand we have players that gained armor like primal beast and bane

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/126239203/4e1eac6a-6745-4b8a-9d5d-d35dfbf779e3)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/126239203/b0936fa2-cc1f-4e77-b180-231fe4c95cdf)

### Example Match ID (and possibly Timestamp)

7604862859, 7604813043 and 7604615071

**Comment by Hex2D2** [comment]
Armor isn't only affected by agility. Heroes have base armor values separate from that. Take Puck for example: He has -3 Base armor. So if you look at his 27 agility and divide it by 6, it gives him 4.5 armor. Subtract the base armor of 3 and you get 1.5, which is roughly what he has there. All heroes have a base armor value for balancing purposes. Some of them are positive, others are negative.
