### ISSUE TITLE
Witch Doctor's Death Ward Aghanim's Scepter bounce attacks miss on targets with no evasion

### ISSUE THREAD

**Issue by JayeMcC** [ValveSoftware/Dota2-Gameplay#15634]
### Ability name

Death Ward

### Description

Witch Doctor's Death Ward Aghanim's Scepter bounce attacks miss on targets with no evasion.
I assume the bounces have been set to .5 accuracy instead of having 1.5.

Also the Aghanim's Scepter tooltip still says it grants Death Ward true strike.

### Example Match ID (and possibly Timestamp)

Just playing in hero demo

**Comment by atomupgrader** [comment]
fixed, close!
