### ISSUE TITLE
hotkey issue

### ISSUE THREAD

**Issue by spcgreenman** [ValveSoftware/Dota2-Gameplay#1563]
so i use alt+hotkey to self target items and abilities and one of my items hotkeys is ` (tilde, the key left of 1) but some reason self cast with alt doesn't work on this hotkey, it works fine on every other hotkey even mouse buttons but not `

pls fix, thx jeff

**Comment by pontuslaestadius** [comment]
I don't think this is a game issue. I use tilde for neutral item actives and self-casting isn't an issue.

**Comment by spcgreenman** [comment]
even when using alt instead of doubletap?

**Comment by spcgreenman** [comment]
alright well thanks for looking into it, no idea what the problem is then.
