### ISSUE TITLE
Dark Willow Unexpectedly Losing Shadow Realm (Possibly from Aghs Life Break)

### ISSUE THREAD

**Issue by FlorianWendelborn** [ValveSoftware/Dota2-Gameplay#15668]
### Ability name

Shadow Realm

### Description

1. Dark Willow casts Shadow Realm at 19:13.466
2. Dark Willow gains Shadow Realm buff at 19:13.766
3. Dark Willow unexpectedly loses Shadow Realm buff after 367ms (19:14.133) even though it should’ve lasted for roughly 5 seconds

![Screenshot 2024-02-26 at 22 20 00](https://github.com/ValveSoftware/Dota2-Gameplay/assets/1133858/013ffdf3-a3cd-49fd-8eec-ba8a21698d13)

### Example Match ID (and possibly Timestamp)

7607999040 19:14

**Comment by PaddyVu97** [comment]
Agha force you to hit him and you dont have agha to maintain shadow realm, that's why you lost it. There's no bug. Closed topic!

**Comment by FlorianWendelborn** [comment]
@PaddyVu97 ah, it’s just listed in the logs in a confusing way. I expected that the hit should’ve been logged first so I stopped reading the logs after the buff was lost. However, the hit that "caused" the loss of shadow realm happened after the loss of shadow realm, so you’re right, closing.
