### ISSUE TITLE
Talent Tree Upgrade does not reflect in Spell Tooltip

### ISSUE THREAD

**Issue by shaileshgarg** [ValveSoftware/Dota2-Gameplay#1571]
### Hero and spell

Multiple Heroes

#### Beastmaster

Level 20 Talent: +35 Boar Damage, after upgrade should be 55/70/85/100
![20220625211112_1](https://user-images.githubusercontent.com/26450759/175780829-f9e58202-ffe6-496b-9ca5-c2fa82c8ad1e.jpg)

#### Drow Ranger

Level 10 Talent: +15 Frost Arrow Damage, after upgrade should be 20/25/30/35
![20220625211438_1](https://user-images.githubusercontent.com/26450759/175780952-328d327e-c5ec-4387-85f3-39a1a940e3bf.jpg)

#### Dawnbreaker

Level 15 Talent: +50% Luminously Crit, after upgrade should be 175/200/225/250
![20220625211726_1](https://user-images.githubusercontent.com/26450759/175781074-d1b4c73f-fa10-4e27-bfb0-9d6ea01dff4f.jpg)

Level 20 Talent: -1 Luminousity Crit, Spell Tooltip should say 2 not 3 attacks
![20220625211950_1](https://user-images.githubusercontent.com/26450759/175781135-331a89cb-2282-4ff7-86fd-a4ee11ac165e.jpg)

Level 25 Talent: +1100 Celestial Hammer Cast Range,  after upgrade should be 2100/2200/2300/2400
![20220625212032_1](https://user-images.githubusercontent.com/26450759/175781177-6fe11bf5-93d9-48d7-b056-2ca6728ca26c.jpg)

#### Dragon Knight

Level 20 Talent: +175 Elder Dragon Form Attack Range, after upgrade should be 525
![20220625212332_1](https://user-images.githubusercontent.com/26450759/175785383-900e235d-2ca1-45c6-a3ff-31cf5a5d95f1.jpg)

#### Husker

Level 10 Talent: +2s Life Break Slow Duration , after upgrade should be 5/6/7
![20220625213238_1](https://user-images.githubusercontent.com/26450759/175785369-65b73b48-0851-4a68-8436-d6070cf3aef3.jpg)

#### Legion Commander

Level 15 Talent: +40 Press the Attack HP Regen, after upgrade should be 70/80/90/100
![20220626001032_1](https://user-images.githubusercontent.com/26450759/175786500-ee423fdb-888b-44a6-abe0-b6734377781e.jpg)

#### Lycan

Level 10 Talent: +10 Wolves Damage, after upgrade should be 28/34/40/46
![20220626001344_1](https://user-images.githubusercontent.com/26450759/175786589-93085f45-e8fb-4e43-a61c-c7c2928cdca8.jpg)

#### Sven

Level 15 Talent: -15s God's Strenght Cooldown, after upgrade should be 90/85/80
![20220626002754_1](https://user-images.githubusercontent.com/26450759/175787053-e1ab4bcc-dd45-4b86-b22b-fa2fdf3318a5.jpg)

#### Tusk

Level 20 Talent: -6s Ice Shards Cooldown, after upgrade should be 17/14/11/8
![20220626003322_1](https://user-images.githubusercontent.com/26450759/175787213-e4e470c9-b433-4efd-8982-9138512445db.jpg)

#### Hoodwink

Level 15 Talent: +2 Acorn Shot Bounces, after upgrade should be 4/5/6/7
![20220626101500_1](https://user-images.githubusercontent.com/26450759/175799788-6204f19b-c192-43da-9cf8-ef91377d80d2.jpg)

Level 20 Talent: 25% Sharpshooter Faster Porjectile/Charge Time, the numbers in the lower half of the tooltip are updated correctly to 2.25s, but the spell description still has 3 seconds.
![20220626101712_1](https://user-images.githubusercontent.com/26450759/175799842-a6c92b46-9583-49ff-a2fe-890b72d99b12.jpg)

#### Lone Druid

Level 10 Talent: +25 Spirit Bear Movement Speed, after upgrade should be 365/385/405/425
![20220626102125_1](https://user-images.githubusercontent.com/26450759/175799929-311ffba9-0253-4a46-9423-5479d2d7db5e.jpg)

Level 25 Talent: +1000 True Form and Spirit Bear Health, after upgrade Spirit bear HP tooltip is incorrect, it should be 2100/2400/2700/3000
![20220626102252_1](https://user-images.githubusercontent.com/26450759/175799972-c1f03179-4227-47a1-b5f1-3a8981fd4fb9.jpg)

#### Sniper

Level 10 Talent: +1s Take Aim Duration, after upgrade tooltip should be 4s.
![20220626104230_1](https://user-images.githubusercontent.com/26450759/175800377-5596af08-d4fb-4824-9604-0c41095ab1e0.jpg)

#### Disruptor

Level 25 Talent: +250 Static Storm AOE, after upgrade should be 750
![20220626111300_1](https://user-images.githubusercontent.com/26450759/175801119-4533078a-7047-4a3b-a9e7-a0554260e92e.jpg)

#### Tinker

Level 20 Talent: -0.5s Keen CConveyance Channel Time, after upgrade should be 4/3.5/3
![20220626114729_1](https://user-images.githubusercontent.com/26450759/175802151-cae69b66-bee1-492b-ab91-f4799b949295.jpg)

#### Visage

Level 10 Talent: +6 Visage and Familiars Attack Damage, after upgrade should be 31/56/81
![20220626143028_1](https://user-images.githubusercontent.com/26450759/175807132-8f70373b-c647-49aa-9b67-0993d893edca.jpg)

Level 25 Talent: +1 Familiar, after upgrade it should 3 familiars. 
![20220626143242_1](https://user-images.githubusercontent.com/26450759/175807180-9aa56dd8-ff61-4e58-a75f-5c4b47ed4016.jpg)

#### Winter Wyvern

Level 20 Talent: +100 Splinter Blast Damage, after upgrade should be 200/280/360/440
![20220626143725_1](https://user-images.githubusercontent.com/26450759/175807323-6bc7af30-28ff-4835-9014-30c890e10d4a.jpg)

#### Zeus

Level 20 Talent: +0.4s Lighting Bolt Ministun, currently the spell tooltip doesn't specify the Ministun before or after the talent.
![20220626144133_1](https://user-images.githubusercontent.com/26450759/175807423-8ba3e6bf-0c09-4eb2-b794-c462d18cfaab.jpg)

**Comment by shaileshgarg** [comment]
Additional Talent Tree Bugs: #1977

**Comment by TheUnholyWrath** [comment]
Snapfire Level 15 +2 Lil' Shredder Attacks Talent increases Scatterblast Slow Duration by 1. Talent is likely still connected to Scatterblast for Ability Draft #1890

**Comment by shaileshgarg** [comment]
> Snapfire Level 15 +2 Lil' Shredder Attacks Talent increases Scatterblast Slow Duration by 1. Talent is likely still connected to Scatterblast for Ability Draft #1890

Tested in Demo, this talent is doing both increasing Shredder count and slow from Scatterblast.

For the talents that I have listed above the talent are working as expected, it is only the spell tooltip which is incorrect. Here the talent is working incorrectly.

**Comment by shaileshgarg** [comment]
Removed the ones fixed or no longer applicable in 7.32
