### ISSUE TITLE
something wrong with new spring courier

### ISSUE THREAD

**Issue by yitian2000** [ValveSoftware/Dota2-Gameplay#15764]
### Cosmetic Item Name

Sir Molestach Irondrill

### Description

Cosmetic Item Name
Sir Molestach Irondrill

Description
The packaged set contains gems, upon unpacking the gems disappear and the courier becomes default's like ID[pressure112](https://github.com/pressure112)siad.

### Example Match ID

https://steamcommunity.com/id/summerflyaw/

### Screenshots

![E9B625D385DE2E007EE2DF55B44C8257](https://github.com/ValveSoftware/Dota2-Gameplay/assets/43241388/f693d64d-8781-41d3-bf68-4322abf0ac9f)
![2D14EE3D62BFF392439D5AE3303383A4](https://github.com/ValveSoftware/Dota2-Gameplay/assets/43241388/d71d49e4-f18f-4957-a3b2-7f3a48296f3b)

**Comment by MarinaMendeleev999999** [comment]
So you're just creating a new issue after you see the three most recent posts being about the same thing? What a scum

**Comment by yitian2000** [comment]
> So you're just creating a new issue after you see the three most recent posts being about the same thing? What a scum

More feedback data helps with the fix, you fool .
