### ISSUE TITLE
Can't rebuy hero relics after deleting them - Dota Plus Subscription

### ISSUE THREAD

**Issue by dimmeto** [ValveSoftware/Dota2-Gameplay#15762]
### Description

With the introduction of new armory some time ago, we had the ability to delete hero relics for a limited time period. During that period my curiosity stroke in and I decided to delete some relics to see what happens with the hero level. Nothing happened. What did happen was my ability to rebuy the relics is gone even though there was no warning for that. The relic shard roulette spins and when it tries to apply the relic I get the "Internal server error try again later". I've been trying for over 6-7 months now and still not possible. 
Related: I can buy other hero's relics, I do have enough shards. I am 100% sure deleting the relics is the problem.

**Comment by mihailspirkoski** [comment]
I am experiencing the same problem.

**Comment by YanVega** [comment]
Updated for visibility bro, I know how it feels to be in this boat.

**Comment by marc-1999** [comment]
Came for the courier bug stayed for this xd

**Comment by anagarcia33** [comment]
Choo Choo HYPE TRAIN!
