### ISSUE TITLE
AD: All abilities have been removed after a few mins ingame

### ISSUE THREAD

**Issue by stringnotfound1** [ValveSoftware/Dota2-Gameplay#15819]
### Description

After a few mins of playing the abilities for all heroes have been removed, including passives and their effects. e.g. mana shield stopped working

### Example Match ID (and possibly Timestamp)

7624226704 - 3:02

**Comment by cy2000** [comment]
I think this is the same bug https://github.com/ValveSoftware/Dota2-Gameplay/issues/15414 
it's being fixed

**Comment by stringnotfound1** [comment]
According to https://github.com/ValveSoftware/Dota2-Gameplay/issues/15414#issuecomment-1984791588 the issue should be resolved.
