### ISSUE TITLE
Astral Spirit Bug

### ISSUE THREAD

**Issue by ahugo75** [ValveSoftware/Dota2-Gameplay#15841]
### Ability name

Astral Spirit

### Description

I was playing Elder Titan, and astral spirit was invisible on use and un-selectable. I couldn't tab to it or use control groups; only bring it back using the button on the hero. I could still stomp people from the location of where I placed it, which ended up being pretty unfair. Everyone in the game was not seeing the spirit, and it didn't reset on death.

### Example Match ID (and possibly Timestamp)

7625909494 - Entire Game

**Comment by eboug92** [comment]
happened to me as well 7625919538 game losing bug

**Comment by eboug92** [comment]
Same issue as #15842

**Comment by chrisf-valve** [comment]
This bug has been fixed in the latest update.
