### ISSUE TITLE
Elder Titan Astral projection not visible

### ISSUE THREAD

**Issue by Jarimu** [ValveSoftware/Dota2-Gameplay#15842]
### Ability name

Astral Spirit

### Description

Astral spirit not visible by myself, my team and apparently enemy team (confirmed post game chat).
Astral spirit still seemed to be effective in able to stun enemies and give buff, but it wasnt visible at all.

Edit: it was the entire game duration, and I tried reloaded game since I thought it was a personal bug. Also, I played 2 games in a row with Elder Titan, only difference in Second game that had the bug was I took Echo Stomp ability first

### Example Match ID (and possibly Timestamp)

7625907688

**Comment by eboug92** [comment]
happened to me as well 7625919538 game losing bug

**Comment by eboug92** [comment]
Same issue as #15841

**Comment by chrisf-valve** [comment]
This bug has been fixed in the latest update.

**Comment by eboug92** [comment]
Thanks for the quick turnaround @chrisf-valve !
