### ISSUE TITLE
it's pretty awesome that ppl can't see io balls, but I'm not sure most ppl would be confortable with it

### ISSUE THREAD

**Issue by swfsql** [ValveSoftware/Dota2-Gameplay#15844]
### Ability name

Io Spirits

### Description

The Spirits are invisible after a certain level, confirmed with allies.
(on the first match I noticed I couldn't confirm cuz ass 4 ppl team wouldn't even say an "a")

### Example Match ID (and possibly Timestamp)

7625930520
(no need for timestap cuz I made an agha half into the game)

###### Dislcaimer
I think it's awesome for this to be invis, even if it is for me, but unfortunately I think it's a bug
if you would let me let it be invis, that would be pretty awesome!

**Comment by chrisf-valve** [comment]
This bug has been fixed in the latest update.
