### ISSUE TITLE
Elder titan astral bug

### ISSUE THREAD

**Issue by 2she31** [ValveSoftware/Dota2-Gameplay#15843]
### Cosmetic Item Name

ET

### Description

Astral spirit invisible. no chance to operate

### Example Match ID

7625908783

### Screenshots

<img width="1280" alt="Снимок экрана 2024-03-08 025511" src="https://github.com/ValveSoftware/Dota2-Gameplay/assets/162650336/847fe507-37ad-458b-a0b2-f5a4807fa637">

**Comment by eboug92** [comment]
happened to me as well 7625919538 game losing bug

same issue as #15841 and #15842

**Comment by arsendzh** [comment]
Just happened to me as well, luckily woo against me broke her items xD

**Comment by rchsun25** [comment]
Just happened to me as well 
7625938919

**Comment by chrisf-valve** [comment]
This bug has been fixed in the latest update.
