### ISSUE TITLE
Astral Spirit MIA (another case)

### ISSUE THREAD

**Issue by ahugo75** [ValveSoftware/Dota2-Gameplay#15845]
### Ability name

Astral Spirit

### Description

I played another game. The bug still persists. Invisible to allies and enemies/uncontrolable.

### Example Match ID (and possibly Timestamp)

7625938631 - Entire Game

**Comment by eboug92** [comment]
happened to me as well 7625919538 game losing bug

same issue as #15841 and #15842 and #15843

**Comment by chrisf-valve** [comment]
This bug has been fixed in the latest update.
