### ISSUE TITLE
Elder Titan astral spirit invisible to everyone in game 

### ISSUE THREAD

**Issue by ab5tract7** [ValveSoftware/Dota2-Gameplay#15859]
### Description

Elder Titan's astral spirit was invisible in my last game. I could still move it around using the "d" hot key, however no one in game (including myself) could see the actual spirit...

### Example Match ID (and possibly Timestamp)

7625944903 - 9:39

**Comment by chrisf-valve** [comment]
This issue has been fixed in the latest update.
