### ISSUE TITLE
Invoker Forge Spirit 4/4 quas-wex not spawning forge spirits

### ISSUE THREAD

**Issue by clb294** [ValveSoftware/Dota2-Gameplay#15895]
### Ability name

Forge Spirit

### Description

The ability is not spawning 2 forge spirits reliably at 4/4 level. In some games I will never get a 2nd spirit to spawn. In others it will start spawning at later than 4/4 level, usually after I have died. Once it starts spawning a 2nd forge spirit it always spawns 2.

This has been happening on and off for a few weeks now.

### Example Match ID (and possibly Timestamp)

7619926476 at 19:50 before invoker is ganked on radiant offlane tower top

**Comment by Aluerie** [comment]
3
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/33165440/cc03129b-c3f3-476e-8ad9-1c48a21e0e5c)

**Comment by Reki1994** [comment]
You need **4 Quas and 4 Exort** for it to spawn 2 forged :))
