### ISSUE TITLE
7.1 speaker configuration problem - side & rear channels are ignoring master volume setting?

### ISSUE THREAD

**Issue by Skooz** [ValveSoftware/Dota2-Gameplay#1591]
### Description

Typically use a 7.1 speaker configuration, but recently had to bump down to 5.1 because of this.

Don't know when it started happening exactly, but side and rear channels are still audible even with master volume set to 0%. I presume they're just not being modified by the master volume slider, and thus are always stuck at 100%? 5.1 doesn't seem to have this issue.

Not sure how else to demonstrate this, [so here's a video with downmixed 7.1](https://www.youtube.com/watch?v=khjOnMQGUwE).

As you can probably hear, with 7.1 you can still hear sound effects that would be coming from the side & rear channels, despite the master volume being set to 0%.

### Example Match ID (and possibly Timestamp)

N/A

### Screenshots

https://www.youtube.com/watch?v=khjOnMQGUwE

**Comment by Hatsura** [comment]
Not sure if this info may help, but this is happening since the "Battle Report Update".
