### ISSUE TITLE
Starting the game on hebrew keyboard layout removes all ability/item hotkeys

### ISSUE THREAD

**Issue by OranShuster** [ValveSoftware/Dota2-Gameplay#15959]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/OranShuster/127b69ff48d63edd032c384faea2cc48):
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:
When starting dota with the hebrew keyboard layout, all ability and item cast hotkeys are removed.
If i try to rebind the keys i can only bind Q/W, binding E/R/D/F/A/S (with or without alt, for items) doesn't work 
"Bind using key location" is checked and i didn't change this setting in the past
Closing the game and starting it again with the english layout fixes the issue (i can bind the keys again and even what i tried to bind before now shows up)

* I tested the hotkeys after setting them during the first launch, didn't work
* Changing the layout to english when the game is running does change / -> Q but doesn't help with the rest of the keys

#### Steps for reproducing this issue:

1. Switch to hebrew  keyboard layout
2. Launch dota 2
3. Look at hotkey settings

**Comment by omershemesh1** [comment]
Annoying one.. happening for 2 months already. I am also experiencing this when on Hebrew keyboard. Relaunching the game on US-EN keyboard fixes the issue and all hotkeys are re-bound again.

**Comment by OranShuster** [comment]
This seems to be fixed

@omershemesh1 for you as well?

**Comment by omershemesh1** [comment]
@OranShuster Yes, toda for noting, hasn’t encountered this in a while actually.
