### ISSUE TITLE
Oracle's Healing with Holy Locket problem

### ISSUE THREAD

**Issue by xDShnick** [ValveSoftware/Dota2-Gameplay#15955]
### Ability name

Purifying Flames

### Description

So, I was testing out Oracle and noticed that Holy Locket healed to much HP after his ultimate. I don't know if I'm wrong(I hope I am) but I did a little math.

https://www.youtube.com/watch?v=gm4lU_hMrlE - video for future context

So, level 4 ability in heals 405 HP total, Holy locket heal amp is 30%, Ultimate delayed heal amp: 100%. In a video, I used a spell 2 times during ultimate, so we go on with that. 405x2=810 810+30%=1053 1053+100%=2106. Total Theoretical Heal after ultimate should be: 2106

Now, HP After ultimate in the video: 2708, Health before ultimate: 36, And his HP regen is 2.9. 2.9x11.5(ultimate ability duration)=33.35+30%=43.355+100%=86.7. 86+36=122. 2708-122=2586 is a total amount of heal Morphling got during the ultimate. That's not considering last tick of 3rd spell after the ultimate. Even with that, amount of heal he got was 480 higher than should be. If considering last tick of 3rd ability after ultimate, would be in ultimate, that should've given with holy locket +117 HP more.

I'm kind of bad in math, so I hope if I'm wrong, someone corrects me, but I don't get why Morphling got more heal that he should've.

### Example Match ID (and possibly Timestamp)

Tested In Lobby

**Comment by aoisensi** [comment]
Close the issue
