### ISSUE TITLE
Play button goes red while searching for a game

### ISSUE THREAD

**Issue by Kowalski-BKL** [ValveSoftware/Dota2-Gameplay#15971]
### Description

As the title states I search for a game and suddenly the play button is red (cannot queue due to excessive reports blablabla)
I did not have a game to accept no message pop up it just goes red

**Comment by commentator24** [comment]
#6567 upvote 👍 that
it's probably problem on your side not server?
screenshot console log to see what's happening.
someone also comment -tcp protocol on steam.exe might help

**Comment by Kowalski-BKL** [comment]
closing as its duplicate
