### ISSUE TITLE
Spectating - Green Ultimate Diamond on portraits at top of screen do not grey out with "charged" abilities

### ISSUE THREAD

**Issue by freddiehill28** [ValveSoftware/Dota2-Gameplay#1598]
As a spectator, I would like the green diamond to "grey out" when a hero with charged abilities runs out of charges.

Hero example.

When spectating a game with a void spirit, if he runs out of charges on "astral step" I would like the green diamond on the hero portrait to go "grey" when he runs out of charges.

<img width="60" alt="image" src="https://user-images.githubusercontent.com/29414061/175917495-a7a20763-6bb1-44d3-91e8-c7c9c3b2908a.png">

This would allow spectators much better glance value to see the availability of all ultimates in the game.

**Comment by LokeLok** [comment]
This is not an issue with spectating, it's a game issue see #54

**Comment by Nathanael-Valve** [comment]
Fixed with latest patch.
