### ISSUE TITLE
not issue, just ban the account on which the booster is playing

### ISSUE THREAD

**Issue by alar1ch** [ValveSoftware/Dota2-Gameplay#16020]
### Description

https://steamcommunity.com/id/CtCacat/
booster performs calibration on this account live. Can Valve figure it out?
this account already has a VAC I think he deserves to get it in Dota too.
twitch.tv/ckootuha

### Example Match ID (and possibly Timestamp)

-

**Comment by bonkmaykrQ** [comment]
This is a bug tracking forum, not for player reports.
