### ISSUE TITLE
Game Crash, Juego se cierra de la nada en fase de selección, MMR, atajo de teclado 4 atajos de teclado no se pueden asignar "º", "Alt + º"; "<", "Alt + <"

### ISSUE THREAD

**Issue by asktion123** [ValveSoftware/Dota2-Gameplay#16049]
### Description

hola, busqué partida de MMR dos veces, las dos veces el juego se cerró de la nada al cargar la partida en la fase de selección, dos veces seguidas este día, la primera vez luego de aceptar la partida, no pude buscar partida durante 1 minuto, la segunda en plena fase de selección,  ahora no puedo jugar durante 1 hora y media, y estoy en baja prioridad, y no es la única vez que pasa esto, hace más de 5 días me pasó lo mismo, tuve que jugar dos partidas de selección simple por que el juego me puso en baja prioridad, ahora estoy seguro de que son cinco, no sé, creo que sería bueno que hagan que la aplicación de Steam o el mismo Dota 2 detecte cuando el juego se cierre de la nada para no estar esperando una hora y media y encima que ponga en baja prioridad cuando el juego se cierre de la nada, me parece injusto que ponga en baja prioridad a aquellos que no abandonan la partida, no abandono nunca las partidas y que me ponga en baja prioridad me parece injusto, espero que puedan arreglarlo gracias, y no es el único problema que tiene el juego, tambien las teclas tienen un problema, no se puede asignar algunas teclas como "<", Alt + <", también la tecla que está a la izquierda del 1 encima de la tecla de tabulación y debajo de la tecla de escape, es esta tecla "º", "Alt + º", estas dos se pueden asignar, pero en plena partida no funcionan y es incómodo, porque son cuatro acciones que no puedo realizar en el juego, ¿pueden arreglarlo por favor?, al principio pensé que era porque no tenía dota plus, luego compré un mes de dota plus y sigue igual, ahora tengo que usar el mouse para realizar esas cuatro acciones, y no solo eso tengo que esperar una hora y jugar 5 partidas de selección simple, porque el juego se me cerró de la nada, espero que puedan arreglar este juego gracias

### Screenshots

![crash](https://github.com/ValveSoftware/Dota2-Gameplay/assets/163630843/4c51a885-1a7a-41a6-9ef4-00e0b9fea620)
![crash2](https://github.com/ValveSoftware/Dota2-Gameplay/assets/163630843/0a431d17-2dbf-42a4-be1c-a7e84073af9e)

**Comment by TobyFlendersonFromHR** [comment]
si senor
