### ISSUE TITLE
Brewmaster banned 100%

### ISSUE THREAD

**Issue by hrkministr** [ValveSoftware/Dota2-Gameplay#16070]
### Description

Hero brewmaster is currently banned 100% of the time. When you try to search live games by hero in watch game tab, there is 0 games going on with brewmaster. This has started 25.3.2024.

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/164962256/5c299152-9aa9-4cad-a8ef-011c879a56d4)

**Comment by commentator24** [comment]
something wrong on your end, not server
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109324155/813d7308-1b1e-40fd-98eb-272760c763a2)

**Comment by hrkministr** [comment]
yes it was fixed 26.3.
