### ISSUE TITLE
Sven

### ISSUE THREAD

**Issue by pernazza** [ValveSoftware/Dota2-Gameplay#16113]
### Description

the Aghanim's Scepter is not working In sven

### Example Match ID (and possibly Timestamp)

161592343-35:00

**Comment by commentator24** [comment]
you need to alt-toggle it, by right clicking storm hammer icon.
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109324155/ae9b26e1-bd8b-4df7-a8a3-e805a9341032)
pls close the issue not a bug

**Comment by pernazza** [comment]
thanks
