### ISSUE TITLE
Elder Titan's Astral Spirit only pierces BKB if Natural Order is NOT leveled

### ISSUE THREAD

**Issue by FN322** [ValveSoftware/Dota2-Gameplay#1621]
### Ability name

Astral Spirit

### Description

Somehow natural order being leveled is stopping astral spirit from applying on BKB'd units that it passes through, and for Elder Titan's Aghanims upgrade this makes a huge difference in fights. Tooltip also says that it SHOULD pierce through bkb. I don't have a match ID I found this in demo mode.

### Example Match ID (and possibly Timestamp)

N/A

**Comment by wtstephe** [comment]
Relevant reddit thread with a video: https://www.reddit.com/r/DotA2/comments/vv42m0/what_in_the_spaghetti_code/

**Comment by ebouganim** [comment]
Tested this again in 7.32b and it's still broken. Please fix.

**Comment by Dota-Exp** [comment]
Will be fixed in upcoming update.
