### ISSUE TITLE
Sniper's ulti does not deal bonus damage at "long range"

### ISSUE THREAD

**Issue by BladeofTomoe** [ValveSoftware/Dota2-Gameplay#16229]
### Hero and spell

Sniper's Assasinate

### Description

Tested in demo, it just deals the same damage every time no matter the range.

**Comment by commentator24** [comment]
it's just saying the casting range is big (3000). it doesn't mean damage is based on distance like mirana arrow

**Comment by BladeofTomoe** [comment]
> it's just saying the casting range is big (3000). it doesn't mean damage is based on distance like mirana arrow

yeah my bad i read that wrong
