### ISSUE TITLE
CAN'T USE THE LETTER "p" OR  "P" IN THE CHAT.

### ISSUE THREAD

**Issue by coevodelaselva** [ValveSoftware/Dota2-Gameplay#16220]
### Description

Hello.
I am old dota 2 player and i have a serious in-game problem. When i tried to use the letter "P" or "p" nothing happens. 
Please help me, i tried to re-download dota 2 again and the error persist.
I dont have money to buy a mic u.u the comunication with my teammates is based in text instrucctions. Please help me, because my strategy skills are reduced when I have to write a word containing "p" or "P".

**Comment by coevodelaselva** [comment]
Can you teach me? please

**Comment by SpiritWinD86** [comment]
> Can you teach me? please

Do I really have to explain this simple thing to you step by step?
just open console window in the game, write this command **`unbind p`**

Ok... If you don't know how to open console try this:
You can put in the launch options of the game in steam (right click game in the library -> properties -> genereal ->) this command **`-console`** and start the game -> after start in the console window write **`unbind p`** and hit Enter key -> close it and check if it works now.
or
launch dota2  -> settings -> options -> to advanced options -> check enable console -> open console (usually by default it's **"~"** key or **" \ "** - you can find out what keybinding it is in hotkeys settings -> advanced -> interface "Console") and then open console  -> and write there **`unbind p`** and hit Enter key -> and check if the it works.

Also you can try to check in the game settings option "Bind keys based on keyboard position" in case if `unbind p` didn't work.

**Comment by coevodelaselva** [comment]
omg thanks mate I really apreciatte your time. Sorry, i am old and i dont know about computers I'm 62.

**Comment by coevodelaselva** [comment]
thanks mate xd
