### ISSUE TITLE
Dota2 is slowing down after 15-20min micro stutters, glitches

### ISSUE THREAD

**Issue by dota-2003** [ValveSoftware/Dota2-Gameplay#16235]
### Description
update:
the game is set to graphics minimum, it makes no real difference, maybe the "issues" start a few minutes later.

Situation:
### Game starts getting slow after around 15-20min online ingame playtime.
**_There are micro stutters._**
**_This is reproducible._** 

In online matches this happens faster.
At single player bot match it can take approx. 35-40min and maybe a little less. (tested once)

The game is then slowing there are like glitches, like lag jumps, you cant hit your hero or others precisely.
The UI is hardly usable cause its like lagging, but network pings are ok.
 
Memory and CPU is consumed but not to a level where it is swapping.
Load is going up between 2 and 3. (normal load like 0,75 -1.x) 

The game seems to use around 4 CPU Siblings out of 8.

If the problem occurs it wont go away only this helps:

Temporary solution:
Killall -9 dota2 or klick "stop" in steam for "DOTA2".

Then it starts over again.

**_Other games just run fine for more than 4 hours+ with the same Hardware and Software Setup,_** so i am pretty sure i got  no "General Computer performance" problem, if i "TAB out of the game" the system responds smooth outside dota2.

My Setup:
All other visible applications are closed. Dota 2 is Running on:

Vulkan is used.

CPU: AMD Ryzen 7 3700X 8-Core Processor
Graphics and Driver:
GL_VERSION:  4.6.0 NVIDIA 545.29.06
GL_VENDOR:   NVIDIA Corporation
GL_RENDERER: NVIDIA GeForce GTX 1070/PCIe/SSE2
`Linux Kernel 6.5.0-26-generic ~22.04.1-Ubuntu`
(i upgraded the kernel to the latest Distro available and tested some other kernels but problem seems the same)
NAME="Linux Mint"
VERSION="21.2 (Victoria)
48GB RAM
HDD: SSD

This seemed to have been introduced with one of the latest updates and is persistent since around a week 
(Maybe with the End of March 7.35d Version Update)

Any help appreciated, Thanks

### Example Match ID (and possibly Timestamp)
7668072283

_No response_

**Comment by IgorHoruzha** [comment]
Could You check Your CPU temperature when it happened, please?

**Comment by dota-2003** [comment]
> Could You check Your CPU temperature when it happens, please?

my cpu temperature has nothing to do with it:
quote:
 if i "TAB out of the game" **### the system responds smooth outside dota2**
its a Dota2 only problem some processes, threads, memory, cpu inside "dota" go berserk  (or steamwebhelper i suppose but thats only a guess i am not able to nail this down)
Last ingame time when i had to leave was after reconnect 27:03 this is perfectly reproducible the time varies though.
from around 15min till approx 20-25min more intense games maybe trigger this earlier.

**Comment by SpiritWinD86** [comment]
Check if there is an opened browser in steam overlay or something, and if it's open close it.
Also try to set graphics settings in game on minimum and check if there any difference in performance.
idk.. dota2 beta...

**Comment by dota-2003** [comment]
> Check if there is an opened browser in steam overlay or something, and if it's open close it. Also try to set graphics settings in game on minimum and check if there any difference in performance. idk.. dota2 beta...

I could mention i already set to minimum graphics level.
There is no open browser (at least not visible) as soon as i kill steamwebhelper (which seems to be the browser chromium as binary?) its getting even worse

**Comment by IgorHoruzha** [comment]
> > Check if there is an opened browser in steam overlay or something, and if it's open close it. Also try to set graphics settings in game on minimum and check if there any difference in performance. idk.. dota2 beta...
> 
> I could mention i already set to minimum graphics level. There is no open browser (at least not visible) as soon as i kill steamwebhelper (which seems to be the browser chromium as binary?) its getting even worse, the "sniper*sh" is restarting steamwebhelper in an endless loop which is intended i think, since this seems to "render the avatars?"
> 
> Do you have any idea which logfiles might help?
> 
> Thanks for your help btw

@dota-2003 
Using the launch options **-console** and -**condebug** will result in the game writing logs to the folder \SteamLibrary\steamapps\common\dota 2 beta\game\dota\console.log, and also displaying information in the Dota 2 console.

Could You please record a video demonstrating the issue as it occurs? If possible, include a display of Your CPU, RAM, Disk, and GPU load.

**Comment by dota-2003** [comment]
> Could You check Your CPU temperature when it happens, please?

I did it is fine. Got an oversized fan. CPU seems not to throttle down.

**Comment by dota-2003** [comment]
Update:
Distro Upgrade to Mint 21.3
Test of XFCE4, several Kernels and Nvidia Drivers. (Kernels 5.15, 6.2.x, 6.5.x) Nvidia-driver (5.15,5.30,5.35,5.45)
(that combos that worked) Mesa/Noveau only was so slow that i gave up after 5min.
stopwatch it: error occured between 18min and 26min latest ingame timer.

**Comment by kaisenbaka** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/16533
i think im having same issue, i had this one for over a year and i finally stepped out to record in 3 different ways to convince myself this isn't normal
