### ISSUE TITLE
kill urself on with doctor by blade mail

### ISSUE THREAD

**Issue by DogMaraDok** [ValveSoftware/Dota2-Gameplay#16251]
### Ability name

Death ward

### Description

whit aghanim's scepter on with doctor if in other team u hero with blade mail, attack some one with out bm u die by bm

https://github.com/ValveSoftware/Dota2-Gameplay/assets/81328077/d428653f-68af-4110-8c93-33f6a9f1bfa0

### Example Match ID (and possibly Timestamp)

7668124948

**Comment by commentator24** [comment]
i think you're not familiar with how the skills work.
here you don't receive dmg by blademail. witchdoc ult is a separate entity. just like techie ult, veno wards etc.
test with any other hero than spectre and give blademail to see if you take any dmg (You won't). 
spectre dispersion reflects dmg he received to surrounding area. this would be the same with shadow demon W

you can close the issue not a bug

**Comment by DogMaraDok** [comment]
yes I checked spectre nothing to do with it

**Comment by DogMaraDok** [comment]
fixed
