### ISSUE TITLE
Cosmetic item (legs) on Mars broken

### ISSUE THREAD

**Issue by Kolissimo** [ValveSoftware/Dota2-Gameplay#16266]
### Cosmetic Item Name

Forgotten fate - legs 

### Description

This cosmetic item twitches strangely and looks back. Visible in the game itself and in the hero's equipment

(I didn’t find a match ID with such an item, but the bug is clearly visible in the equipment and in the lobby)

### Example Match ID

-

**Comment by squeeish** [comment]
Here's my issue
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/3531468/055d7735-8c53-48d7-aae4-18c167b18921)
