### ISSUE TITLE
Rapier drop on hero's death location when unlocking item in backpack

### ISSUE THREAD

**Issue by mikhatanu** [ValveSoftware/Dota2-Gameplay#16285]
### Item name

Divine Rapier

### Description

Prerequisite:
1. Hero is dead
2. Demon edge is locked in backpack before dying
3. item slot is full + neutral item

Steps to reproduce:
1. Buy sacred relic from courier
2. Use 'courier deliver item (f3)' to deliver item to base
4. sacred relic is sent to backpack
5. unlock demon edge

Expected result: rapier is set in backpack or dropped on fountain
actual result: rapier is dropped on death location

https://github.com/ValveSoftware/Dota2-Gameplay/assets/8099814/8c69b524-7202-4977-914d-0f08f95945de

### Example Match ID and Timestamp

7672318439 -  44:49

**Comment by commentator24** [comment]
there is no bug here, like aegis, you cannot put rapier in backpack.
parts of rapier should be in inventory so it will combine there.
if combined in stash, it stays in stash. but courier cannot pick it up / deliver from stash.
if combined in courier, I think it stays in courier. but once dropped etc courier cannot pick it up again. 
you combine in backpack while dead. so rapier drops upon death on ground where you died.

here I locked the parts and combined in inventory while dead. still in inventory when i respawned.
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109324155/a4fcbd95-ad6d-495d-bbc2-4416264c0dc5)

**Comment by mikhatanu** [comment]
so it is intended? I think they should change the default behavior as this can potentially change the flow of a match.
