### ISSUE TITLE
[GAMEBREAKING] Orge Mage's Ult applies Hex (from item) way outside of cast range

### ISSUE THREAD

**Issue by BurlakaBohdan** [ValveSoftware/Dota2-Gameplay#16293]
### Ability name

Orge Mage's Ult + Scythe of Vyse (Hex)

### Description

The ult of orge mage can proc items such as Hex, however, in my match I was way outside of hex range and still got hexed. 

On the video I show my position (Queen of Pain) and Ogr Mage's position + cast range of hex is highlighted. You may say, that replay may not properly highlight the cast range, because it may not apply aether lense to it. So next, I actually highlight his second skill (ignite) cast range (1000 range) which would be cast range of hex 800 + 225 range from aether lense. I am still not in that range. 

https://www.youtube.com/watch?v=zggvn7DYR5U

Timestamp: 23:15, bottom line, near T2

### Example Match ID (and possibly Timestamp)

7673146732 (timestamp 23:15)

**Comment by commentator24** [comment]
tested in lobby for you, i had aether lens and it seems the range is about 1600.
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109324155/0d0fcd62-093b-4a48-a2a6-7f13b9f0c960)
wiki says Multicast item range can be defined as expr ItemCastRange + CastRangeBonus + 600
800 + 225 + 600 seems about right 1625

wouldve been nice to show cast range bonus in tooltip, but i think theres no bug here, should close issue

**Comment by BurlakaBohdan** [comment]
Yeah, you right. Nice hero then :)
