### ISSUE TITLE
Incorrect localization for Lifestealer on Russian

### ISSUE THREAD

**Issue by 808thlife** [ValveSoftware/Dota2-Gameplay#16381]
### Description

In Russian Localization 20th level talent on Lifestealer says +15 to movespeed instead of +15% to movespeed.
It misses %

**Comment by sommerVA** [comment]
#9473

**Comment by 808thlife** [comment]
dulbicate of the issue
https://github.com/ValveSoftware/Dota2-Gameplay/issues/9473

**Comment by 808thlife** [comment]
So basically this issue was known about a year ago in the issue mentioned above and it still isn't fixed.
