### ISSUE TITLE
dummy target is dying and not respawning

### ISSUE THREAD

**Issue by Acer-Samsung** [ValveSoftware/Dota2-Gameplay#16444]
### Description

when u demo hero the dummy target is dying and not respawning but still showing dps numbers

**Comment by Magic-wei** [comment]
Dummy target actually respawns at the enemy's tower. This behaves differently to hero in-place respawning.

**Comment by Magic-wei** [comment]
This bug has been fixed in the update patch today. You can close this issue.

**Comment by Magic-wei** [comment]
@Acer-Samsung This bug has been fixed in the update patch today. You can close this issue.
