### ISSUE TITLE
TImebersaw's ult not returning correctly

### ISSUE THREAD

**Issue by pathhubhmrguez** [ValveSoftware/Dota2-Gameplay#16449]
### Ability name

TImbersaw's Chakram

### Description

When you use the ability again to make it return it doesn't return to timbersaw. It goes somewhere else. I kind of triangulated it to be somewhere in mid river, everytime, no matter where Timbersaw is.

### Example Match ID (and possibly Timestamp)

7692927785

**Comment by Magic-wei** [comment]
@pathhubhmrguez This bug has been fixed in the update patch today. You can close this issue.

**Comment by hmrguez** [comment]
Thank you
