### ISSUE TITLE
Timbersaw Chakram Bug animation ability and is not showing with default Skin

### ISSUE THREAD

**Issue by erfan569** [ValveSoftware/Dota2-Gameplay#16452]
### Ability name

Chakram and Second Chakram

### Description

Timbersaw's Ultimate after Crownfall Update is not showing and players are abusing it.
this bug causes many problems such as you can not dodge it.
this bug happens with Timbersaw's default skin.
also after pushing Return for Timbersaw's Chakram it goes somewhere else and hit damage!!
please Fix this it's annoying.
Thank you

### Example Match ID (and possibly Timestamp)

7692936588

**Comment by cwboyspike** [comment]
This is also confusing playing as Timber.

**Comment by Magic-wei** [comment]
@cwboyspike This bug has been fixed in the update patch today. You can close this issue.

**Comment by JJTia** [comment]
it hasn't fixed yet,
