### ISSUE TITLE
Game crashing after Crownfall update

### ISSUE THREAD

**Issue by ruchanb** [ValveSoftware/Dota2-Gameplay#16457]
### Description

 I am having frequent crashes in game every time a co-op game is played. No error is shown, the game just closes. Solo bot game has not crashed yet. This has started to happen after the Crownfall update as I could play the games before.

I have tried verifying the integrity of the game files. I also tried uninstall and re-install the game, and the crash is still happening.

Here are the crash dumps i found from the `bin/win64` folder
[dota2_2024_0419_172724_0_accessviolation.zip](https://github.com/ValveSoftware/Dota2-Gameplay/files/15041550/dota2_2024_0419_172724_0_accessviolation.zip)
 (before re-install)
[dota2_2024_0419_192948_0_accessviolation.zip](https://github.com/ValveSoftware/Dota2-Gameplay/files/15041547/dota2_2024_0419_192948_0_accessviolation.zip)
 (After re-install)

Laptop Specs:

    Windows 11 (auto updated)

    Ram:16gb

    Processor: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz, 2201 Mhz, 6 Core(s)

    Graphics: NVIDIA RTX 2060

**Comment by f35irani** [comment]
I have the same issue with i3 12100 playing with the onboard graphics. before the update, it was fine, but after the Crownfall update, it will crash out of the game in the online matches and watch section. It has irregular timing. it may crash in less than one minute or more. It is unplayable.

**Comment by qukankan** [comment]
yes, same issu, once it crashed, rejoin can not help. It will crashed right after rejoin. I need reboot my pc. And sure, after this match, i need w8 30 min for "abandoned game". Is this a joke feature include with this update?

**Comment by f35irani** [comment]
[Crownfall error log.zip](https://github.com/ValveSoftware/Dota2-Gameplay/files/15044343/Crownfall.error.log.zip)
this is my error for today's game crashes I have abandoned 2 games because of these crashes.

**Comment by ruchanb** [comment]
Closing as issue fixed for me from today's update.
