### ISSUE TITLE
2024-04-19 Update Bug: Timbersaw's Chakram is rendered abnormally

### ISSUE THREAD

**Issue by Magic-wei** [ValveSoftware/Dota2-Gameplay#16462]
### Ability name

Timbersaw's Chakram

### Description

Timbersaw's Chakram is rendered abnormally (as shown in the first video `Timbersaw-Chakram-Bug.webm`). It only behaves normally when equips Rectifier or Golden Rectifier (as shown in the second video `Timbersaw-Chakram-With-Rectifier.webm`).

[Timbersaw-Chakram-Bug.webm](https://github.com/ValveSoftware/Dota2-Gameplay/assets/29951097/c74327a1-1fdd-49ea-b12b-f0c0ad4e4429)

[Timbersaw-Chakram-With-Rectifier.webm](https://github.com/ValveSoftware/Dota2-Gameplay/assets/29951097/7542ae6f-81c3-4c6e-9f63-121302d9c453)

### Example Match ID (and possibly Timestamp)

I record these videos in demo scenario, but I saw this bug in some players' live streaming

**Comment by Magic-wei** [comment]
Same issue with:
- #16452 
- #16449
- #16438

**Comment by Magic-wei** [comment]
Closed the issue since this bug has been fixed in the update patch today.

**Comment by Anutrix** [comment]
Bug is still there. Facing it live right now.

**Comment by zooperuser** [comment]
can confirm its still there until now.
