### ISSUE TITLE
[Ability Draft] Dazzle's Shadow Wave still shows being Scepter upgradable in Drafting Phase

### ISSUE THREAD

**Issue by Dagsss** [ValveSoftware/Dota2-Gameplay#1647]
### Description

When you hold alt+ctrl during the Drafting Phase, the ability Shadow Wave still highlights as a Scepter upgradable skill even though it isn't anymore. 

Sorry I can't provide a better screenshot, I screenshot using F12 in game when I am holding alt+ctrl.

![shadow wave](https://user-images.githubusercontent.com/106859871/176726314-bbae6d7b-d6d6-477d-a064-3b7ad48e9c7f.jpg)
![20220701000657_1](https://user-images.githubusercontent.com/106859871/176726660-a5f1464d-f28e-417a-a97d-645c5eb1d7b9.jpg)

### Example Match ID (and possibly Timestamp)

6641624310

**Comment by TheUnholyWrath** [comment]
This has been fixed, you can close this issue.
