### ISSUE TITLE
Crownfall : after latest update 1.36gb~ binds became broken

### ISSUE THREAD

**Issue by VetaLioSTV** [ValveSoftware/Dota2-Gameplay#16489]
### Description

As title says, after huge update (today) which had 1.36gb~, binds became broken. In my case i have logitech mouse with extra media buttons and "stop" button are not working anymore in dota, its like suppressed \ overtaken by some other stuff (i guess it has some reference to map of crownfall(?), but i'm not sure).

Please revert binds changes back.

**Comment by VetaLioSTV** [comment]
On 23.04.24 22:53 UTC+02 still not fixed.

Guys for Seattle, any chance to fixit it soon please ?

Similiar: 
#16486
#16520
#16481
#16445
#16509
#16486
#16445

and so on.

**Comment by VetaLioSTV** [comment]
@ValveSoftware 30.04.24 still not fixed, so its over :( ?

**Comment by PerryPerro** [comment]
Still waiting for fix 5/5-24. Would be nice atleast with some form of input so we don´t need to wait for fix, currently my hero pool is cut in half since i can barely play some of them without quickcasting. (Which i use with my remapped key).

**Comment by VetaLioSTV** [comment]
@PerryPerro unfortunately zero reaction :( , previously as far as i remember fix was made for 1-2 days. Maybe Valve have made some breaking changes and these changes will not be reverted :\ ?

Maybe we should create a new issue with more detailed description, idk..

**Comment by VetaLioSTV** [comment]
@PerryPerro do you have any updates? Still nothing from my side, i even raised a new detailed standalone issue here on repo...

**Comment by VetaLioSTV** [comment]
Finally its fixed with update 7.36!

Thanks, i hope it will not became broken!
