### ISSUE TITLE
[Linux] Selecting two or more Terrorblade's Conjure Image illusions will crash the game

### ISSUE THREAD

**Issue by deanrih** [ValveSoftware/Dota2-Gameplay#16485]
### Ability name

Conjure Image

### Description

When selecting two or more Terrorblade's Conjure Image illusions will crash the game
(client only)

Here's the video capture in action

https://github.com/ValveSoftware/Dota2-Gameplay/assets/16235605/11e3f157-5a7c-47bd-97a8-9860da2666f3

### Example Match ID (and possibly Timestamp)

n/a

**Comment by deanrih** [comment]
Fixed to use re-encoded video

**Comment by joulei** [comment]
Having same issue on macOS

**Comment by deanrih** [comment]
Update:

It actually not isolated to Conjure Image illusions, just any Terrorblade illusions, ally, enemy, and yes if you have Shadow Demon and casts disruption on to Terrorblade and select all the illusion, the game will crash, any Terrorblade illusions (manta, conjure image, illusion rune, phantasm, disruptions) will crash upon being selected

**Comment by gregory112** [comment]
Same here too I got to LP because of this

**Comment by deanrih** [comment]
The new update (version 6036) seems to have fixed the issue.

**Comment by deanrih** [comment]
Closing this issue since the bug already fixed and no additional input being added.
