### ISSUE TITLE
[Ability Draft] -4s cooldown on Smoke Screen on Riki's talent doesn't show even when drafted by Riki

### ISSUE THREAD

**Issue by Dagsss** [ValveSoftware/Dota2-Gameplay#1648]
### Description

Even when Riki drafts Smoke Screen, the left talent -4s cooldown still doesn't show.

![20220630232007_1](https://user-images.githubusercontent.com/106859871/176728086-b6c9bd63-c9d2-43e5-b61e-ccc73e433e2f.jpg)
![20220630231905_1](https://user-images.githubusercontent.com/106859871/176728112-5ea18c2d-2985-439e-904a-7e89f8622ce1.jpg)
![20220701001915_1](https://user-images.githubusercontent.com/106859871/176728438-5f5fa7e2-7de7-4b1d-8027-2d1458816c15.jpg)
 

### Example Match ID (and possibly Timestamp)

6641649357 - 27:26

**Comment by TheUnholyWrath** [comment]
This has been fixed, you can close this issue.
