### ISSUE TITLE
Crownfall Store coins Bug!!

### ISSUE THREAD

**Issue by kyhb0** [ValveSoftware/Dota2-Gameplay#16511]
### Description

Im try to use Crownfall Store coins discount and buy midgate pathfinder pack
then error message pop up
now my Store coins are gone??
pls help.

### Screenshots

![20240421012755_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/167643785/d8591c46-70c5-476f-b2f8-040c1205b475)

![20240421012806_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/167643785/d5557bc7-ac45-43de-9d80-86bc91d719a2)

**Comment by Shalidol** [comment]
I have exactly the same problem! (((Did you manage to solve it?
