### ISSUE TITLE
[Linux | Linux Mint] Broken text input / e.g. can't type russian

### ISSUE THREAD

**Issue by IAmLosingSanity** [ValveSoftware/Dota2-Gameplay#16523]
### Description

Happens when entering text in a language other than English (in my case, in Russian).
After entering any letter from Russian layout (except ascii symbols) it prints letter with some garbage at right. Commonly, it is the question mark, but sometimes it can be a bit random. 
This may be due to other problems with the layouts described in other issues.
The bug appeared after one of the "Crownfall" updates.

### Screenshots

![1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/112655242/dac1a93b-c698-488a-8f74-73d746af24be)
![2](https://github.com/ValveSoftware/Dota2-Gameplay/assets/112655242/59ec33dd-c67c-4d9a-a24c-642b6d650c53)
![3](https://github.com/ValveSoftware/Dota2-Gameplay/assets/112655242/ed2f7389-229e-4767-849a-fc3eb6840faa)
![4](https://github.com/ValveSoftware/Dota2-Gameplay/assets/112655242/5a23e3e2-a007-4e81-a3b1-ecb0664c9bf5)

**Comment by Melon-peel** [comment]
Same thing here... Also a Linux mint user. Upgrading to a newer kernel didn't solve the issue

**Comment by GregTheMadMonk** [comment]
Bump. The issue is still there on Arch Linux 6.8.6-zen1

**Comment by batkor** [comment]
I confirm

**Comment by Andrey9096** [comment]
Also on KDE Neon and Fedora 39/40

**Comment by Krithx** [comment]
+1 Fedora 39 and 40, its bug on client of dota

**Comment by vmrfriz** [comment]
Also on Manjaro KDE

**Comment by radicalaction** [comment]
Same on arch. I don't think that WM matters that much. Seems like volvo fixed hotkeys not being registered on non-latin layouts even with layout-agnostic option unchecked but broke this one.

**Comment by Deissson** [comment]
Same here on Ubuntu 24.04

**Comment by Wild-Magic-Sorcerer** [comment]
Same here on Gentoo KDE

**Comment by wwDG3jz** [comment]
+ mint

**Comment by Skullckoor** [comment]
Mint 21.3
6.5.0-35-generic #35~22.04.1-Ubuntu

**Comment by vmrfriz** [comment]
Solved for Manjaro today. Idk, is it Dota 2 fix or is it related to the linux update. Kernel 6.1.92-1-MANJARO

**Comment by IAmLosingSanity** [comment]
Seems like it solved (I guess). I am sure that it was Dota fix, Mint 21.3 with last xanmod works perfectly. I will close this thread as soon as I make sure everything is working.

**Comment by borisovdev** [comment]
I had the problem fixed after the last update
Thanks devs!
