### ISSUE TITLE
Crownfall tokens dissapear

### ISSUE THREAD

**Issue by Mekanik228** [ValveSoftware/Dota2-Gameplay#16525]
### Description

after recrived 10 tokens i decided to buy bundle, but when i clicked on puschare dota lagged and my tokkens dissapear

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/167656474/522eb528-441c-4d88-96cc-d979b8f48136)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/167656474/65538b21-6020-4d3d-86bb-e82c185244ef)

**Comment by LegendaHluPa** [comment]
Exactly the same problem, UP

**Comment by JgMeh** [comment]
need help for this

**Comment by laflairdrip** [comment]
i have the same 
HELP!

**Comment by laflairdrip** [comment]
I lost it before buying a discount
