### ISSUE TITLE
Unable to purchase Hero Relics since the introduction of new Armory and Profile (I've made this post and upvoted numerous with the same issue but the problem still persists check it out please)

### ISSUE THREAD

**Issue by dimmeto** [ValveSoftware/Dota2-Gameplay#16544]
With the introduction of the new profile cases and armory around a year ago, there was a small period where you could delete/reset hero relics (idk why the feature was removed), and since it struck me by surprise and I only have relics for my favourite hero I decided to check it out see what happens - I was curious to see if my hero level will go down, or shards will get refunded w/e I just wanted to see what happens.... Annd nothing happened, relics disappeared, but the funny thing is, when I tried repurchasing them the game just wouldn't let me. For the past maybe year I've been trying after every patch no matter how small it is, and I always get the same error: The relics roullette spins and when it tries to apply the relic to the hero no matter if its common or rare I get Internal server error try again later message. For some weird reason I was able to buy only 1 relic, idk how that happened. I also tried purchasing other heroes' relics and there is nothing wrong when doing so... - I deleted them afterwards ofc...I only want them for my favourite hero as crazy as it sounds... I've contacted Steam Support, made issues here every month, upvoted numerous issues regarding the same problem... so far nothing...
So... please guys and girls at Valve if there is anything you can do to fix this issue I beg you I just want to track my favourite hero stats again please! 
I send you all my love <3 and I hope this gets fixed
Sincerely, dimmeto

**Comment by anagarcia33** [comment]
Same here, I got tired of posting the same thing over and over again
