### ISSUE TITLE
Consistent micro stutters on AMD

### ISSUE THREAD

**Issue by roddejams** [ValveSoftware/Dota2-Gameplay#16567]
### Description

Hi there,

I recently upgraded my PC and since then I've had only issues with running Dota 2. I get consistent 0.3-0.5s freezes every 5-10 seconds, but no issues in any other game. 

I only get the freezes when connected to the dota 2 game server (not in a local private lobby or when demoing heroes), and it's different depending on what game server I'm connected to. For example, Stockholm and Austria servers the stutters are less severe than the EU West or US East servers. 

My PC specs are as follows:
AMD Ryzen 7 7800X3D 8-Core Processor              4.20 GHz
32gb ram
Radeon 7900XT 

I've got an ETW file but it's too big to attach here, what's the best way to share it?

Thanks!

**Comment by IgorHoruzha** [comment]
Do You still have the issue?

**Comment by roddejams** [comment]
Hi @IgorHoruzha. 

I managed to solve the issue, it was caused by an outdated bluetooth driver & adaptor that I was using. Once I replaced the adapter and re-installed drivers the issue was fixed.
