### ISSUE TITLE
Coins fallen crown disappeared 

### ISSUE THREAD

**Issue by pudraa** [ValveSoftware/Dota2-Gameplay#16587]
### Item name

Fallen crown: shop coin 

### Description

I finally accumulated 10 coins in the event of the fallen crown. I wanted to buy a set, activated the discount and clicked "buy." The inscription "connection to dota 2" came out. THE OPERATION WAS NOT CARRIED OUT, THE MONEY WAS NOT WRITTEN OFF, BUT THE COINS WERE GONE. I didn't get the set. I'm asking you to return my 10 coins. 

My steam

Https://steamcommunity.com/id/youmidzu/

### Example Match ID and Timestamp

Below

**Comment by pudraa** [comment]
![IMG_2687](https://github.com/ValveSoftware/Dota2-Gameplay/assets/167719058/9833e457-1b92-4282-8b4b-47152dc6e5d8)
![IMG_2686](https://github.com/ValveSoftware/Dota2-Gameplay/assets/167719058/0031a556-11d4-46b9-8ffb-8b3a254ec94e)

**Comment by hatred0** [comment]
same issue

**Comment by pudraa** [comment]
> тот же вопрос
In 30 minutes they returned everything, ok
