### ISSUE TITLE
Incorrect display of the debuff status

### ISSUE THREAD

**Issue by Hekp0** [ValveSoftware/Dota2-Gameplay#1665]
### Description

Most items and abilities with an aura effect, but without a visual effect, are incorrectly displayed when using Shadow Blade. For example, presence of the dark lord does not display the debuff status and does not reduce armor during the Shadow Blade action. Shiva's Guard reduces the attack speed, but is not displayed as a debuff. Assault Cuirass reduces armor, but does not appear as a debuff during the Shadow Blade action. But Radiance and other items/abilities that have a visual effect on the enemy are displayed correctly. More information in this post on reddit:
https://www.reddit.com/r/DotA2/comments/vgn6ns/incorrect_display_of_the_debuff_status/

### Screenshots

![SF](https://user-images.githubusercontent.com/95239339/176944033-f9bcda3b-004a-4f26-a9b2-dbd92576aa70.png)

**Comment by shaileshgarg** [comment]
![20230111201724_1](https://user-images.githubusercontent.com/26450759/211836352-836b1238-fd08-4940-8f63-f467e1f8c1fc.jpg)

Seems to working fine now, can be closed.

**Comment by Hekp0** [comment]
It is probably worth checking if the debuffs will be displayed if SF uses Shadow Blade in a war mist and gets close to your hero

**Comment by shaileshgarg** [comment]
Did some more research

https://dota2.fandom.com/wiki/Version_6.82, AC and Shiva's not showing debuff, but applying when enemy is not visible is intented.

https://dota2.fandom.com/wiki/July_08,_2011_Patch, SF not applying Armor reduction when not visible is intented. Check for Nevermore changes.

**Comment by Hekp0** [comment]
Ok, thank you.
