### ISSUE TITLE
Dire gets scan charges only when Radiant isn't at max charges.

### ISSUE THREAD

**Issue by 1ukeman** [ValveSoftware/Dota2-Gameplay#16702]
### Description

Scan starts on cooldown and correctly gets the initial charge after the cooldown. After gaining that first charge, Dire will only gain charges if Radiant doesn't already have 2 charges when the cooldown expires.

### Example Match ID (and possibly Timestamp)

Every match played as Dire.
7406424070 5:29

Here's a table recording all the scan events for the replay:

| Timestamp | Radiant | Dire | Notes                                                            |
|-----------|---------|------|------------------------------------------------------------------|
|  -1:30    | 0       | 0    | 3:30 cooldown on both teams                                      |
|   2:00    | 1       | 1    | +1 both, 3:30 cooldown on both teams                             |
|   5:30    | 2       | 1    | +1 Radiant, +0 Dire despite the cooldown resetting, 3:30 cd both | 
|   9:00    | 2       | 1    | Radiant at max charges, +0 Dire despite the cooldown resetting   |
|  11:08    | 1       | 1    | -1 Radiant, scan used. Radiant 3:30 cd, Dire 1:22 cd             |
|  12:30    | 1       | 2    | +1 Dire. Radiant 2:08 cd                                         |
|  14:38    | 2       | 2    | +1 Radiant. Both teams at max charges.                           |
|  15:31    | 1       | 2    | -1 Radiant uses a scan. Radiant 3:30 cd                          |
|  16:07    | 1       | 1    | -1 Dire uses a scan. Radiant 2:55 cd, Dire 3:30 cd               |
|  16:46    | 0       | 1    | -1 Radiant uses a scan. Radiant 2:15 cd, Dire 2:50 cd            |
|  17:13    | 0       | 0    | -1 Dire uses a scan. Radiant 1:47 cd, Dire 2:22 cd               |
|  19:02    | 1       | 0    | +1 Radiant. Radiant 3:30 cd, Dire 0:35 cd                        |
|  19:37    | 1       | 1    | +1 Dire. Radiant 2:55 cd, Dire 3:30 cd                           |
|  22:31    | 2       | 1    | +1 Radiant. Dire 0:35 cd                                         |
|  23:06    | 2       | 1    | +0 Dire. Dire 3:30 cd                                            |
|  23:13    | 1       | 1    | -1 Radiant uses a scan. Radiant 3:30 cd, Dire 3:22 cd            |
|  23:34    | 1       | 0    | -1 Dire uses a scan. Radiant 1:09 cd, Dire 1:02 cd               |
|  26:36    | 1       | 1    | +1 Dire. Radiant 0:06 cd, Dire 3:30 cd                           |
|  26:43    | 2       | 1    | +1 Radiant. Dire 3:24 cd                                         |
|  27:31    | 1       | 1    | -1 Radiant uses a scan. Radiant 3:30 cd, Dire 2:35 cd            |
|  29:38    | 1       | 0    | -1 Dire uses a scan. Radiant 1:22 cd, Dire 0:28 cd               |
|  30:07    | 1       | 1    | +1 Dire. Radiant 0:53 cd, Dire 3:30 cd                           |
|  31:00    | 2       | 1    | +1 Radiant. Dire 2:37 cd                                         |
|  31:49    | 2       | 0    | -1 Dire uses a scan. Dire 1:47 cd                                |
|  32:51    | 1       | 0    | -1 Radiant uses a scan. Radiant 3:30 cd, Dire 0:45 cd            |
|  33:27    | 1       | 0    | Match ends. Radiant 2:55 cd, Dire 0:10 cd                        |

### Screenshots
![20240423113043_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/73172684/88d549ef-ccce-49fe-88fe-3b328593fcf5)
![20240423113044_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/73172684/13c3a27a-4c3a-4247-8aaa-cc8261ee3cf7)

_No response_

**Comment by 1ukeman** [comment]
Still broken in 7.36.
Steps to reproduce: join a lobby as Dire and wait until 5:30.

**Comment by 1ukeman** [comment]
Still broken in 7.36a.

**Comment by chrisf-valve** [comment]
This has been fixed in an update that shipped yesterday.
