### ISSUE TITLE
Invalid purchase and I don't have my crown drop store coins

### ISSUE THREAD

**Issue by Banditbitcon** [ValveSoftware/Dota2-Gameplay#16771]
### Description

at 12:42 pm UTC, I made a recharge to buy the middle neighborhood explorer lot since I had 10 tokens that gave me the discount but at the time of making the purchase the product was not delivered to me and he took away my tokens

### Example Match ID (and possibly Timestamp)

317309728 - 12:42
identificacion de vapor : 76561198277575456

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/90337749/4d35a1bb-90fc-4b50-a97b-4b40d98f8393)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/90337749/402a3bad-aae1-48ee-900d-b39218a0d37c)

**Comment by Red-Zeff** [comment]
![1212](https://github.com/ValveSoftware/Dota2-Gameplay/assets/168020468/61dccc01-c908-4ad1-9c72-246ef2857e73)
![Untitled](https://github.com/ValveSoftware/Dota2-Gameplay/assets/168020468/07e41016-dcb1-4fbc-b225-0e26f253b089)

**Comment by Red-Zeff** [comment]
Please fix the crownfall store coin bug

**Comment by Banditbitcon** [comment]
Solucionado, solo esperar unos minutos
