### ISSUE TITLE
Sand King "Epicenter" channeling, cannot be cancelled by "walking" where as Crystal Maiden ultimate ability "can"

### ISSUE THREAD

**Issue by BitterLemons88** [ValveSoftware/Dota2-Gameplay#16797]
### Ability name

Epicenter

### Description

You can't cancel "Epicenter" by walking, when this was allowed before. (Maybe before Crownfall?)
It doesn't make sense, when Crystal Maiden can do that, whilst Sand King isn't capable to do so.
You can still cancel "Epicenter" from Sand King by pressing "Stop/Hold" but you're not allowed to cancel it by walking, how is it so?
I believe this to be a bug.

*extra search*
I've figured out this was the same with "Shadow Fiend" ultimate ability "Requiem of Souls" as well.
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/71393423/38c54556-96fa-46cb-9984-552fa27b90ad)
I've had the "Channeled abilities requires Hold/Stop" Box, unchecked, and there seems to be no walk-cancelling for both "Sand King" and "Shadow Fiend"
So in terms of digging deeper into this problem, "Sand King" was the first I've noticed, but it has the same issue with "Shadow Fiend" as well.

### Example Match ID (and possibly Timestamp)

7703823581

**Comment by Aluerie** [comment]
those 2 arent channeling, it's just long downswing animation; all is fine

**Comment by BitterLemons88** [comment]
They aren't considered to be channeling? Woah that was an eye opener for me.
Maybe it's because I played HoN in the past ... and you could cancel their "downswing animation" by walking.
They considered those as channeling.
My confusion is solved.
Thanks.
