### ISSUE TITLE
Using Dispose to throw ally out of Black hole (Agh shard) teleports ally back into BH right after they land outside.

### ISSUE THREAD

**Issue by HGrandin** [ValveSoftware/Dota2-Gameplay#1681]
### Ability name

Dispose + Black Hole

### Description

So this has happened to me twice in real games. And in both cases i did not find any reason for the wierd teleportation back into the black hole other than the black hole itself. When testing in demo mode it seems to be linked to the shard of enigma. But i never had the teleportation becoming as bad in demo, as in this case.

The match id of this game is 6643114215, and happens at ingame time 39:40.

https://user-images.githubusercontent.com/776920/177018906-3f21e27a-1e7b-4717-8ee6-2523dc1a25f2.mp4

### Example Match ID (and possibly Timestamp)

6643114215 - 39:40

**Comment by jere535** [comment]
Briefly tested this in demo mode, easy to reproduce. 
Distance teleported seems to be relative to duration affected by BH, longer duration equals greater distance moved after dispose ends. 
If BH ends before dispose lands, the target isn't affected by this bug

Units thrown inside the shard area but unaffected by the BH itself will not get teleported anywhere.

**Comment by Nathanael-Valve** [comment]
Can no longer repro.
