### ISSUE TITLE
Winters curse and Berserker's call conflicting behavior

### ISSUE THREAD

**Issue by rcgRaf** [ValveSoftware/Dota2-Gameplay#1683]
### Ability name

Berserker's call, Winters curse

### Description

When Winter Wyvern uses Winter's curse while the targets under the effect of berserkers call, after the taunt effect of berserkers call wears off, the target heroes can ignore winter's curse taunt effect

### Example Match ID (and possibly Timestamp)

6644834894 - 39:30

**Comment by shaileshgarg** [comment]
Checked in demo, working fine now.
