### ISSUE TITLE
Dark Willow can be targeted by allies spells

### ISSUE THREAD

**Issue by michmot546** [ValveSoftware/Dota2-Gameplay#16882]
### Ability name

Shadow Realm

### Description

You can target Dark Willow in Shadow Realm by clicking on the portrait and not the hero. Works only with allies and not with enemies. Found it while playing ranked match as Abaddon.

https://github.com/ValveSoftware/Dota2-Gameplay/assets/72617993/973e2ede-a284-487a-92df-4c28879a4bfc

### Example Match ID (and possibly Timestamp)

7708247027

**Comment by TheZett** [comment]
Intended as of 7.33.
