### ISSUE TITLE
CandyWorks Caravan Bug? - CrownFall

### ISSUE THREAD

**Issue by arjarath** [ValveSoftware/Dota2-Gameplay#16888]
### Description

When I reached this encounter, I had 4 bonuses to choose from, after the dialogue ended. 
Since I was not very sure on which bonus I should pick, I thought to myselft that it was ok to close the window and choose after some time, so I just clicked on the "X" button to close the choices screen/window. The options were (extra candies, +10 inventory slots and 2 other ones which I cannot remember)

After clicking the X button, it went straight to the screen/window where you are supposed to trade candies for sets/treasures and I feel like I didn't get any bonuses at all? The idea of not being able to pick a bonus after clicking on the "X" to close the screen is messing with my mind tbh. Because I haven't seen this screen ever again. And I already completed the whole CrownFall Act 1.

So that is why I am making this post here on GitHub. I think I've search for a similar query but I couldn't find anything like this problem I came through.

Hopefully this helps, thank you.

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/96953620/ebe58fe4-ec60-4834-a46f-c0e4566bfdee)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/96953620/586d3a81-b88a-4723-933b-cfa33626de4f)

**Comment by Aluerie** [comment]
https://imgur.com/Wa1pv66

its not a choice

**Comment by arjarath** [comment]
Oh, I probably didn't pay enough attention or it was my classical ADHD kicking in. Looked like choices at my first glance though lol

Thank you for clarifying, let's close the issue
