### ISSUE TITLE
Two roshan spawned in a pro match

### ISSUE THREAD

**Issue by shubhrathi** [ValveSoftware/Dota2-Gameplay#1690]
### Description

I just saw twitch clip that shows two roshan in a pit

### Example Match ID (and possibly Timestamp)

https://clips.twitch.tv/ExuberantWildShieldTBTacoLeft-6l9mC7QhXG3R66QB

### Screenshots

https://clips.twitch.tv/ExuberantWildShieldTBTacoLeft-6l9mC7QhXG3R66QB

**Comment by asmodeus941** [comment]
I think they already know about this since it happened in an official game xd
