### ISSUE TITLE
Can't write non english letters to chat on linux

### ISSUE THREAD

**Issue by strainxx** [ValveSoftware/Dota2-Gameplay#16965]
### Description

When i writing non latin letters to chat dota adds random symbols after each letter.
Example:

ф?$?в?$?ы?$?ф?$?в?$?Ы?$?В?$?Ы?$?Ф?$?ЫZ#Ф?$?

Operating System: Debian GNU/Linux 12
KDE Plasma Version: 5.27.5
KDE Frameworks Version: 5.103.0
Qt Version: 5.15.8
Kernel Version: 6.1.0-20-amd64 (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 5600H with Radeon Graphics
Memory: 5,6 GiB of RAM
Graphics Processor: AMD Radeon Graphics

**Comment by phraggers** [comment]
could this be an SDL related issue? Don't know how the dota internals work but I know they use SDL as platform layer.

**Comment by Captain-Cyborg** [comment]
#16895 Same problem

**Comment by Blu3cr0ss** [comment]
same

**Comment by batkor** [comment]
+

**Comment by drevofil** [comment]
Same here

**Comment by PavelHouze** [comment]
same

**Comment by Skullckoor** [comment]
same Mint 21.3
6.5.0-35-generic #35~22.04.1-Ubuntu

**Comment by borisovdev** [comment]
same here
Arch Linux x86_64

**Comment by borisovdev** [comment]
I had the problem fixed after the last update
Thanks devs!

**Comment by strainxx** [comment]
solved after update
