### ISSUE TITLE
The game was not counted because of the dota 2 servers

### ISSUE THREAD

**Issue by Mokarth** [ValveSoftware/Dota2-Gameplay#16995]
### Description

I played a rating game, spent my rating token, as a result, the game was canceled and it is not in the history of the match.

https://youtu.be/Tfwn4_mp5U4

### Example Match ID (and possibly Timestamp)

05.01.2024

### Screenshots

https://youtu.be/Tfwn4_mp5U4

**Comment by SkyKota** [comment]
I came across the same thing, it was a game to raise the shooting range on the Dazle and I also spent a rating token, the game is not counted even in the history of fights

**Comment by itzjustclouddd** [comment]
i use double rate token too and win the 50 minute game( hope valve do something with it

**Comment by Madjed00** [comment]
i have the same problem they did not count 2 games

**Comment by Mokarth** [comment]
Everything counted
