### ISSUE TITLE
If Rubick Steal pudge ult without pudge have shard rubick can't eject the hero

### ISSUE THREAD

**Issue by tisoga** [ValveSoftware/Dota2-Gameplay#1705]
### Ability name

Speal Steal + Dismember

### Description

If Rubick Steal pudge ult without pudge have shard rubick can't eject the hero, but if pudge buy it rubick can eject allies manual.

- Pudge Without Shard
![Pudge Without Shard](https://i.postimg.cc/TwWNtFvt/20220704222513-1.jpg)

- Rubick Steal Dismember Without pudge buy shard, rubick can't manual eject allies
![Rubick can't eject manual](https://i.postimg.cc/JhFdcmvy/20220704222511-1.jpg)

- pudge buy shard
![Pudge With Shard](https://i.postimg.cc/yx4QtjVs/20220704222513-2.jpg)

- Rubick can manual eject allies
![Rubick can eject manual](https://i.postimg.cc/QCQ437t5/20220704222519-1.jpg)

### Example Match ID (and possibly Timestamp)

Demo Hero

**Comment by Usera2** [comment]
Duplicate [https://github.com/jeffhill/Dota2/issues/186](url)

**Comment by shaileshgarg** [comment]
#186

**Comment by tisoga** [comment]
my bad.
