### ISSUE TITLE
Комплект исследователя из «Павшей короны» в Dota 2 не рабоатет

### ISSUE THREAD

**Issue by uertyla** [ValveSoftware/Dota2-Gameplay#17071]
### Description

Я использовал баг для получения свечи в первом акте Катакомб и теперь не могу применить пропуск за 7$.

### Screenshots

![Screenshot_36](https://github.com/ValveSoftware/Dota2-Gameplay/assets/168686764/c76255f8-0de9-43c2-a728-3db99d989e46)

**Comment by Ex1s11L** [comment]
The same . I bought a pass from the website, since purchasing on Steam was impossible. when trying to activate, it gives an error

**Comment by J4cka133** [comment]
Такая же история. Купил и думал что за...

**Comment by Yur3355** [comment]
Купил 5~10 мин назад и тоже самое выдает
