### ISSUE TITLE
I didn't receive the tokens/reroll for the match and I didn't receive the rewards on the map.

### ISSUE THREAD

**Issue by PhoenixLabella** [ValveSoftware/Dota2-Gameplay#17103]
### Description

I wasn't rewarded with tokens and reroll from the "Emporium Caravan" on my last victory. So, I traded with the "Token Dealer" and proceeded to collect the rewards, only in those three that I highlighted in the screenshot, but I didn't receive anything from it. No Coins, no treasure chest, no secondary style set for Invoker and not even the Meepo profile decoration.

Now I'm in this situation where it shows that I received the items.

Profile ID: 39195482

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/41215996/9e02ba19-230e-4972-85d9-91a2aeafd104)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/41215996/adf570db-b0ea-48e2-929c-3eceab3d02a5)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/41215996/67b8f109-0d37-4843-aaab-c0b3d86a7b18)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/41215996/773f0ebe-fa2b-4b4b-b96e-abe28820af14)

**Comment by ClipChampion** [comment]
Same thing happened with me, but I have missed on LOTS more of the awards, I missed Awards for like 15-20 steps, I thought I would get the items after it has stopped lagging :(

**Comment by PretOFA** [comment]
Same thing happened with me too. I was supposed to receive the rewards for complete the before last quest but i didnt =(

**Comment by PhoenixLabella** [comment]
Problem was solved. Every Item was delivered.

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/41215996/841bc7c2-f791-4ae1-839c-73ec723d61fd)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/41215996/26098d19-ccab-475d-a0b5-14d19009d9bb)
