### ISSUE TITLE
crownfall bug

### ISSUE THREAD

**Issue by neirrro** [ValveSoftware/Dota2-Gameplay#17165]
### Item name

treasury and tokens

### Description

Last night I started farming tokens for treasures, I started one game, I lost, I started the second and I won, but they didn’t give me tokens, but I didn’t pay attention to it and started the next game, they didn’t give me tokens again, but again I didn’t pay attention to it, maybe some kind of bug 
![KSkYR0dz7l0](https://github.com/ValveSoftware/Dota2-Gameplay/assets/168725537/9bc86014-33b8-4dfb-afbd-d192b8d28872)
![bXfN30vhYNc](https://github.com/ValveSoftware/Dota2-Gameplay/assets/168725537/6826c056-7a78-442d-9e80-f5d557d405fa)
![K3a0at3Ujno](https://github.com/ValveSoftware/Dota2-Gameplay/assets/168725537/4e6f296b-14b9-4209-853f-35fe2ce2be10)
I never received tokens for the games I won
game id 7716076398
2.05.2024    01:06

### Example Match ID and Timestamp

7716076398   2.05.2024    01:06

**Comment by dobstotev** [comment]
same thing happened to me in the exact same location

**Comment by neirrro** [comment]
> ### Item name
> treasury and tokens
> 
> ### Description
> Last night I started farming tokens for treasures, I started one game, I lost, I started the second and I won, but they didn’t give me tokens, but I didn’t pay attention to it and started the next game, they didn’t give me tokens again, but again I didn’t pay attention to it, maybe some kind of bug ![KSkYR0dz7l0](https://private-user-images.githubusercontent.com/168725537/327388274-9bc86014-33b8-4dfb-afbd-d192b8d28872.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NjUzMDIsIm5iZiI6MTcxNDY2NTAwMiwicGF0aCI6Ii8xNjg3MjU1MzcvMzI3Mzg4Mjc0LTliYzg2MDE0LTMzYjgtNGRmYi1hZmJkLWQxOTJiOGQyODg3Mi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMlQxNTUwMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MWE3N2FiNzYzMjAzMzM5NGQwMTViY2NiYWFmZDdiNDkzM2U4NmU0MWE1YmY3MTZlODk3MDc1ODk3MjgyYmE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WGjD2rVQNoxz2107xBSrq9CVUXuxrqj-tXpkGteMYtI) ![bXfN30vhYNc](https://private-user-images.githubusercontent.com/168725537/327388323-6826c056-7a78-442d-9e80-f5d557d405fa.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NjUzMDIsIm5iZiI6MTcxNDY2NTAwMiwicGF0aCI6Ii8xNjg3MjU1MzcvMzI3Mzg4MzIzLTY4MjZjMDU2LTdhNzgtNDQyZC05ZTgwLWY1ZDU1N2Q0MDVmYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMlQxNTUwMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Y2Q2ZDM3ZDJiZTI5NWU3MmFjMTU3MmNkOGJmMTM3ZDIwNDgzMjVhZmJiYmIzYjc2MThkYjcyOTAyNDAxYTI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.H1y7RK5SnuidPTWYe1VIJwrP5w2Yrq-CGh82qv5G0qI) ![K3a0at3Ujno](https://private-user-images.githubusercontent.com/168725537/327388359-4e6f296b-14b9-4209-853f-35fe2ce2be10.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NjUzMDIsIm5iZiI6MTcxNDY2NTAwMiwicGF0aCI6Ii8xNjg3MjU1MzcvMzI3Mzg4MzU5LTRlNmYyOTZiLTE0YjktNDIwOS04NTNmLTM1ZmUyY2UyYmUxMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMlQxNTUwMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00M2EyOWIwOTNiMTg3NWM0ODE0MDFiZWJmOTZlZmFmYTUyN2ZjZmM1ZGVhOGU2ZDJjNmZkNjFlZWJjN2JhYzg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hvDFjEVvjxnmHV0PbBZXPMOSN2-GDta9agu06WNt_Dc) I never received tokens for the games I won game id 7716076398 2.05.2024 01:06
> 
> ### Example Match ID and Timestamp
> 7716076398 2.05.2024 01:06

dota id: 1095417668
