### ISSUE TITLE
Didn't get Invoker set in Crownfall

### ISSUE THREAD

**Issue by calaquend1** [ValveSoftware/Dota2-Gameplay#17225]
### Description

Finished Crownfall labyrinth yesterday when everything lagged, got my tokens, got my candyshop rerolls, but didn't get Invoker set.

dota id: 98953955
steam id: 76561198059219683

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/45256936/86560c46-2e21-42ca-aa35-cb602bfa4255)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/45256936/89473248-675e-4b57-b4b5-68754f71869f)

**Comment by Adityaj54** [comment]
yep happened to me also

**Comment by Pikulinaha** [comment]
and me

**Comment by calaquend1** [comment]
fixed, items delivered
