### ISSUE TITLE
Juggernaut lv20 bladedance lifesteal works on normal hits not just crit hits

### ISSUE THREAD

**Issue by eggers09** [ValveSoftware/Dota2-Gameplay#17312]
### Ability name

Bladedance

### Description

Juggernaut lv20 bladedance lifesteal works on normal hits and not just crit hits. 

This talent used to only work and critical hits and not normal hits, no changes were mentioned in the patch notes. Almost certain it's a bug and it is pretty game breaking that a hero can have 60% constant lifesteal. 

https://github.com/ValveSoftware/Dota2-Gameplay/assets/55358270/232c0d5a-3fb0-4419-a445-2cd5824d5b83

### Example Match ID (and possibly Timestamp)

7714861938-26:56

**Comment by Jarg0vsk1** [comment]
game has no bugs aghh volvo

**Comment by Avarise831** [comment]
#15478
