### ISSUE TITLE
Meepo has Heart Of Terrasque in neural item slot

### ISSUE THREAD

**Issue by u023871** [ValveSoftware/Dota2-Gameplay#17337]
### Item name

Heart Of Terrasque

### Description

Hi!

Meepo had Heart Of Terrasque in neural item slot - at least in summary screen, as I did not yet watch the replay.

BR, eztup

### Example Match ID and Timestamp
![20240504224746_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/15835306/00faa0c1-4f4c-4a39-89ec-e7d01ad252d8)

7721269925

**Comment by u023871** [comment]
Here an in-game screenshot.

![20240504233535_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/15835306/d1400ad3-dbe9-4755-92ba-acbb355793de)

**Comment by Avarise831** [comment]
Check 25 lvl meepo talent

**Comment by u023871** [comment]
Thanks for your quick reply! Never noticed before... Closing.

**Comment by u023871** [comment]
Closed.
