### ISSUE TITLE
3 Greater Healing Lotus + Cheese Didn't Combine and Possibly Crashed the Whole Match

### ISSUE THREAD

**Issue by yvlaZ** [ValveSoftware/Dota2-Gameplay#17340]
### Item name

Greater Healing Lotus and Cheese

### Description

I (steam name : yvlaZ) played a ranked match yesterday with my friend (steam name : RealExos) and we were on the 45 minute mark when everyone suddenly got disconnected and the match didn't count and we can't even find the match id because it doesn't show up in our history. 
Here's how I think I caused it : 
I had cheese and I have 2 greater healing lotus, I said to my team to wait for 45 mins so I can make a block of cheese (my 2 greater healing lotus is in my stash). Then I asked my friend (RealExos) to give me his healing lotus (only 1), so he dropped it back in base. I tried picking it up with my courier but I couldn't somehow so I just waited for the 45 min mark to take the last healing lotus i needed and then I tped to base. Now I have 2 greater healing lotus in stash, 1 great healing lotus and 2 healing lotus in my inventory, and I'm back in base. I tried to grab the healing lotus that's on the ground (dropped by friend) but I couldn't, so I stashed the lotuses but strangely now in my stash I have 2 greater healing lotus, 1 great healing lotus, and 2 healing lotus + 1 healing lotus that didn't combine. So I stashed everything and used courier in hopes of everything just combining to make a block of cheese. But it didn't make it, now I have 2 greater healing lotus, 2 great healing lotus. So then I dropped the cheese and lotuses. I picked them all up and it still didn't combine. So I dropped them again on the ground and tried picking it back up. And that's when everything froze, I thought it was my connection but my friend also froze and we all got dced. Suddenly the match isn't recorded and I can't even find the match ID.
My friend might have the recording of the game but he probably wasn't looking at my hero doing all this. I can't provide the match id since it doesn't show on our matches history but if you see my friend's dotabuff (https://www.dotabuff.com/players/257407849) this happened before his match as Io. 

### Example Match ID and Timestamp

-

**Comment by Avarise831** [comment]
#15991

**Comment by yvlaZ** [comment]
> #15991

Thank you very much, I thought I was crazy
