### ISSUE TITLE
Lost all ITEMS in armoty!

### ISSUE THREAD

**Issue by LockDownSI** [ValveSoftware/Dota2-Gameplay#17346]
### Description

Hello,

I returned to the game after some time off. I noticed I lost all items? I had arcana PA(fully built), arcana terrorblade, arcana Shadowfriend etc... What the hell??!?!??

How can I just loose items like that with 0 notice??????

Please check and get me back all items I had when I played ASAP

Name in game: LockDown
ID: 66069448

Best regards,
DoomsDay

**Comment by commentator24** [comment]
you probably login steam to dodgy websites. view your inventory history / gifting history

**Comment by LockDownSI** [comment]
all Steam items gone... case closed by Steam support.
