### ISSUE TITLE
Sword of the Colossus cosmetic bug

### ISSUE THREAD

**Issue by Polykomodo** [ValveSoftware/Dota2-Gameplay#17420]
### Cosmetic Item Name

Majesty of the Colossus/ Sword of the Colossus

### Description

The sword in Tiny's arms is placed wrongly, please fix it.

### Example Match ID

123

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/107393089/bc7f570f-19fa-4b5d-9d5e-1dd792ea360e)

**Comment by Astiberon** [comment]
FIXED
