### ISSUE TITLE
Black king bar is broken when it comes to pure damage

### ISSUE THREAD

**Issue by Magik3222** [ValveSoftware/Dota2-Gameplay#17451]
### Item name

Black king bar 

### Description

Black king bar description says that "Grants 60% magic resistance and immunity to reflected and pure damage" 
The problem is when it comes to pure damage, its not working, for example queen of pain sonic wave, enigma black hole, witch doctor death ward and axe counter helix & culling blade are ignoring black king bar and dealing damage as always.
There is more examples of ignoring pure damage immunity but as long as i was looking i found one example when item work properly, timbersaw whirling death deal no damage to heroes with active black king bar effect.

### Example Match ID and Timestamp

none (issue is always present)

**Comment by jlkj11** [comment]
Not a bug. All of these are supposed to pierce BKB. It has never been consistent but, as a good rule of thumb, if it says on the tooltip that the skill pierces spell immunity, then the damage probably will too if it's Pure.

**Comment by Magik3222** [comment]
> Not a bug. All of these are supposed to pierce BKB. It has never been consistent but, as a good rule of thumb, if it says on the tooltip that the skill pierces spell immunity, then the damage probably will too if it's Pure.

it's feel like this item grants pure immunity but nearly every possible pure damage source ignore it 
i cheked little more and bkb is saving you from omniknight, tinker q and meepo pasive, there is still a lot more like leshrac, invo, pudge, spectre etc. who are ignoring it 
its kinda useless description when it only works in a few cases (5 maybe 6 spells, i can't found more) when nearly every one is ignoring it and there are tones of spells like this it's confusing as hell
thanks for response and yes it is not bug just a confusing thing
