### ISSUE TITLE
The game was not counted because of the dota 2 servers

### ISSUE THREAD

**Issue by itzjustclouddd** [ValveSoftware/Dota2-Gameplay#17487]
### Description

i won game on pangolier but it was not counted because of the Dota 2 servers.
my id - 1455889087

### Screenshots

![Снимок экрана (126)](https://github.com/ValveSoftware/Dota2-Gameplay/assets/168658232/5458c2e3-d75f-4bdb-9bd9-284a63602d2f)
![Снимок экрана (127)](https://github.com/ValveSoftware/Dota2-Gameplay/assets/168658232/6b5378c9-e5ec-473f-9717-9ec293f105bf)

**Comment by zerkass** [comment]
таже проблема, сперва в истории из 4 игр была одна, теперь их три, осталось дождаться пока появится игра на джаге (самая первая)

**Comment by zerkass** [comment]
у меня история всех игр появилась, по времени спустя 1,5 часа

**Comment by itzjustclouddd** [comment]
now game was counted thx!
