### ISSUE TITLE
Spirit breaker relic doesnt count

### ISSUE THREAD

**Issue by RedVampirium** [ValveSoftware/Dota2-Gameplay#17574]
### Description

Spirit breaker  relic long charges doesnt count or update . It s been like this for a while.

Please help
Steam ID: 76561199319275076

### Screenshots

![20240514190056_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/118635067/86327fee-7c87-4c1f-969c-402b71778141)

**Comment by dimmeto** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/17554 check this out too
