### ISSUE TITLE
Nature's Prophet bug(i hope this is bug)

### ISSUE THREAD

**Issue by Profectuss** [ValveSoftware/Dota2-Gameplay#1758]
### Ability name

Sprout

### Description

Right LvL 20 talent not have to working on heroes under magic immune.

### Example Match ID (and possibly Timestamp)

6657130147 - 47:49

**Comment by Avarise831** [comment]
#1210

**Comment by TheUnholyWrath** [comment]
This has been fixed, please close this issue.
