### ISSUE TITLE
What u thick of 50% of victory!

### ISSUE THREAD

**Issue by hoverwings** [ValveSoftware/Dota2-Gameplay#17594]
### Description

After 10 years of playing this game.I believe the only thing prevent me to have fun in this game is this fxxking 50% of victory!
After 10 years in Dota2， Now when i gonna relax myself after a long day work,i turn on my computer.Before starting Dota2,I always tell myself,you may lose all night，this matchmaker just give 4 fxxking retarrds to tortune you!Eveything you do,every hard work may be in vain just becouse of  4 fxxking retards.If this game only bring you sadness ,there is no need to play it,then i will just do other things to have my fun.
There is one circle:win in a row and then lose in a row and win again！The fun is that in the lose-in-row,no matter how hard you do,you just cant win.then  the next game will give you 4 much noobier players.Maybe the matchmaker gain the data that this one just love to struggle in this game.when i finally start to win.i feel nothing, no joy no fun.just a feeling:the tortune finally stop!
I believe this has  happenned to all the million of players over the past 12 years,and gonna happen in the future!
This is not a fair game. Every match is not a fair match.All becouse of those fxxking idiots in Valve playing god,50% of victory to everyone，so they can feel so much Self-satisfaction.
I love dota,its once a belief. now its just one piece of garbage!Fxxk you Valve!Fxxk you matchmaker!Fuck you 50% of victory！

**Comment by Dum0sss** [comment]
after you played 10 years you cant tell that it just math behind 50% system? Nothing holding you back, matches are found by Rating and geo position, that's it, also it account for behavior and comm scores if possible, the longer you wait for a match, the more it ignores scores and rating range, only accounting for server and geo position. Also you can use 3rd party sites to see that people with you same roughly same stats most of the time, its just people are upredictable and etc.
