### ISSUE TITLE
Leshrac misanthropy facet appears higher rate visually but no extra dmg at all

### ISSUE THREAD

**Issue by commentator24** [ValveSoftware/Dota2-Gameplay#17803]
as shown, higher rate explosions seem restricted by the hidden max tick rate? in combat log, resulting in same total dmg.
e.g. like sandking is every 0.25 sec so 4x tick rate right? not sure what it's called. if anyone know pls tell me :D 
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109324155/14003634-4db4-4891-971c-6aaf02ee92c0)

**Comment by Teddymannen** [comment]
The facet is only supposed to make you deal damage faster, not more in total. This is not a bug. 
The difference (other than working on towers) is that you deal 1360 dmg over 10 seconds or over 7 seconds.

**Comment by commentator24** [comment]
i see i'll close the issue then
