### ISSUE TITLE
7.36 Ability Bug - Phantom Assassin

### ISSUE THREAD

**Issue by pencoder10** [ValveSoftware/Dota2-Gameplay#17878]
### Ability name

Coup De Grace

### Description

When using the "Methodical" Facet on Phantom Assassin, the hero should land a critical strike on creeps every 6 attacks, and 4 attacks on heroes. When using the item "Manta Style", the critical counter (Deadly Focus) reaches up to 9, to 0, then back to 1 without ever hitting a critical strike.

This happens only if the hero and the illusions hit the same target. Easier seen when fighting Roshan at around 41:55.

### Example Match ID (and possibly Timestamp)

7751112334 - 41:55

**Comment by muditk98** [comment]
Fixed can close. Illus no longer consume or produce the counter
