### ISSUE TITLE
 Veno lvl 25 ward-talent not working. 

### ISSUE THREAD

**Issue by robinhood1596** [ValveSoftware/Dota2-Gameplay#17998]
### Ability name

Plague Ward

### Description

Level 25 Talent doesn't grant x2,5 hp or damage to wards. Just skill it and spawn wards to check. Straight up not applied

### Example Match ID (and possibly Timestamp)

1111111

**Comment by qwenough** [comment]
+1

**Comment by somethingxful49** [comment]
Can this be reproduced in demo mode (using a terrain so it's the normal Dota map)?

**Comment by robinhood1596** [comment]
Nvm it was fixed
