### ISSUE TITLE
Dota has 0 settings for talent buttons

### ISSUE THREAD

**Issue by Yan00r** [ValveSoftware/Dota2-Gameplay#180]
### Dota has 0 settings for talens buttons

Dota has 0 settings for talens buttons. It can't be remapped, and dota hasn't settings for +2 for all attributes. It is need to be settings for theese important binds that by default bind on [1] and [2] key's. I use [1] and [2] buttons for 1 and 2 spells on heroes. And this default binds [1] and [2] on talents sometimes in fight makes me learn wrong talent instead of using spell on these buttons.

### Screenshots

![image](https://user-images.githubusercontent.com/106772815/171724079-340f9a67-f78f-4950-91c2-b8af7eda0cfe.png)

**Comment by Yan00r** [comment]
> Вы можете нажать [U] (по умолчанию), чтобы вызвать меню талантов, в котором он будет выбран, а затем нажать соответствующую цифру, чтобы разблокировать талант. Поскольку меню выбрано (или, скажем так, активно), нажатие [1] или [2] не будет использовать заклинание или предмет, если у вас что-то привязано к этим клавишам. Тем не менее, нет специальной кнопки для прокачки статистики, поэтому ее следует добавить.

[1] and [2] can't be remapped. This is a big problem for me, because i don't know when some enemy blink in front of me, and in dota this situation is common. When you open that talent menu. And want to use spell on enemy when it appear from nowere, but you learn wrong talent instead of using important skill. I can remap [U] but i can't remap [1] [2] and [+2 for all attributes]

**Comment by mosi3883** [comment]
I don't know what happened to him, don't forget this repo
@jeffhill

**Comment by alexeik** [comment]
its even HIDES map while you get access to this. 
maybe allow player upgrade talants without TalentUI ? or optional.

**Comment by eddieparker** [comment]
Fixed with latest patch.

**Comment by Yan00r** [comment]
thx)
