### ISSUE TITLE
In update 7.36, Lina's talent at level 25 "150% critical damage to Dragon Slave victims" does not work

### ISSUE THREAD

**Issue by kinetic234** [ValveSoftware/Dota2-Gameplay#18053]
### Ability name

Lina's talent at level 25 "150% critical damage to Dragon Slave victims"

### Description

If you upgrade your talent to LVL 25 for critical damage, nothing changes, there are no crits from hitting the victims "Dragon slave". And it doesn't matter which aspect to choose, "thermal ranaway" or "slow burn"

### Example Match ID (and possibly Timestamp)

I tried it in the lobby

**Comment by dogmelons** [comment]
+1, happened to me in match 7750849234.

**Comment by Valisk** [comment]
This seems to be related to Slow Burn's damage over time being credited to a new buff effect so Dragon Slave no longer applies a debuff. They have to either change the talent to "+150% Crit on Targets Affected by Burn" and give a new talent to Thermal Runway or simply return Dragon Slave's debuff for the same duration as Burn.

**Comment by kinetic234** [comment]
The bug was fixed with an update
