### ISSUE TITLE
Skadi Melee/Ranged slow effects are backwards

### ISSUE THREAD

**Issue by VoxxL** [ValveSoftware/Dota2-Gameplay#18061]
### Item name

Eye of Skadi

### Description

Eye of Skadi effect is applying melee effects to ranged heroes and vice versa. So a melee hero is slowed by 50% and a ranged hero by 20%.
Example: Both Huskar and Alchemist have 295 base movespeed. Alchemist is reduced to 147 while Huskar is reduced to 235.
![alchemist_skadi](https://github.com/ValveSoftware/Dota2-Gameplay/assets/87580268/ffbf6624-32a3-4a70-a154-dd7229954032)
![huskar_skadi](https://github.com/ValveSoftware/Dota2-Gameplay/assets/87580268/2e40a95e-5e97-47d8-ae9d-53ba32ad9cc0)

### Example Match ID and Timestamp

Demo

**Comment by Turmfalke2** [comment]
possibly related: skadi treats a melee veng as a melee hero and hits her with the bugged 50% slow. This is inconsistent with vanguard only providing the ranged block chance to her.  
Should veng still be a ranged hero that just happens to have a melee typed ranged attack?

**Comment by Turmfalke2** [comment]
Fixed in today's patch:

> Fixed Skadi slow values being inverted for Ranged vs Melee.

just veng is still weird.

**Comment by VoxxL** [comment]
fixed in 7.36a
