### ISSUE TITLE
Timbersaw's chakrams aren't showing properly

### ISSUE THREAD

**Issue by terentyevalexey** [ValveSoftware/Dota2-Gameplay#18084]
### Ability name

Timbersaw - chakrams

### Description

If you put the chakram on the ground its fine
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/47413011/66c16b89-8ef8-4bcd-b109-e14baafc27a0)
If you try to return it, that's what you get [it moves to the different direction visually, not to you]
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/47413011/0d18ef3f-2433-4eb4-95a6-0a3fddbcc2e6)
Twisted chakram just visually spawns inside you and doesn't move, but breaks trees
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/47413011/1bf808e8-7cf4-45dd-9dd4-b7a69c5c9912)

### Example Match ID (and possibly Timestamp)

test lobby new patch

**Comment by terentyevalexey** [comment]
I wrote a better description in another issue https://github.com/ValveSoftware/Dota2-Gameplay/issues/18714 due to  this being a cosmetic item bug and not a spell bug. Closing this one to remove duplications.

**Comment by Plernix** [comment]
Bug still has not been fixed since the Facet update. Here is what happens when using both Chakram. 

https://github.com/user-attachments/assets/1f146dbe-b7e5-4f14-a6b8-eb8e871aac78
