### ISSUE TITLE
7.36 Slark's Depth Shroud aghanim's shard ability no longer heals allies.

### ISSUE THREAD

**Issue by Terlingue** [ValveSoftware/Dota2-Gameplay#18083]
### Ability name

Depth Shroud

### Description

Slark's Depth Shroud aghanim's shard ability no longer heals allies.

### Example Match ID (and possibly Timestamp)

7752538460 -19:56

**Comment by terentyevalexey** [comment]
As it shouldn't if you read the patchnotes. Not a bug.

**Comment by Terlingue** [comment]
> If you read the patchnotes, it grants them just the ultimate buff, not the innate healing buff. Not a bug.


"No longer stacks with Shadow Dance" - does imply that it should still provide healing. As it used to give allies and slark 100%  of shadow dance regen, effectively making slark regen twice as much.

**Comment by commentator24** [comment]
Regen bonuses moved as slark innate ability. other allies do not have this innate ability..

**Comment by Terlingue** [comment]
fixed in 7.36a
