### ISSUE TITLE
Witch Doctor's Gris-Gris doesn't say that it can be placed in regular item slot anywhere, but it can.

### ISSUE THREAD

**Issue by terentyevalexey** [ValveSoftware/Dota2-Gameplay#18099]
### Hero and spell

Witch Doctor - Gris-Gris

### Description

Witch Doctor's Gris-Gris doesn't say that it can be placed in regular item slot anywhere, but it can. Also, a description bug for income interval.

### Screenshots

This is the description for Gris-Gris
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/47413011/124f2384-3a22-4e52-abb3-6bd31544c7c3)
As you can see, the item can be stored in a regular item slot [btw here's another tooltip bug with old_tick_interval_tooltip%]
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/47413011/da4a827c-568c-438d-b108-15320f9cdb92)
The patch notes description for a similar spell/item for warlock has this description:
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/47413011/d19be61f-a414-4c97-8007-7b992771354e)
It doesn't say that you can put it in a regular item slot in game as well, but it has a red text that tells it can't be dropped unlike Gris-Gris
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/47413011/30d1334f-7aa3-44b0-874c-36bf7ff1e958)

**Comment by HeenLight** [comment]
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/113137398/dc629ac6-8957-4487-b7a8-f4645815f578)
негры пидор негры пидоры пофиксите игру пидоры негры

**Comment by terentyevalexey** [comment]
Fixed [NOT IN RUSSIAN LOCALIZATION]
