### ISSUE TITLE
Dark Moon game mode would not advance while all enemies dead, matchmaking penalties ensue

### ISSUE THREAD

**Issue by benhorst** [ValveSoftware/Dota2-Gameplay#1828]
### Description

We faced the undying zombie horde with Lifestealer champs. The enemy counter ticked to 0 and we were unable to proceed.

The team eliminated the last of the enemies and nothing happened. We all died to a tower in an attempt to end the game and the game still would not advance to next state.

One of our players (Dice) had to accept an abandon to get us out. Matchmaking paused for 15mins :(
[Dice profile](https://steamcommunity.com/profiles/76561198000821915/)

I normally wouldn't make an issue about this, but being in Spotlight and incurring the 15 min penalty rather stinks. Thanks for taking a look!

### Example Match ID (and possibly Timestamp)

6663571320

### Screenshots

![image](https://user-images.githubusercontent.com/104176/179331506-8d7a0a84-1e4c-428f-8a3e-acd033b349b0.png)

**Comment by LawrenceWeng** [comment]
Same thing in GameID: 934370

**Comment by omararcay** [comment]
Same here! Our match ID: 6663598070

**Comment by joshmouch** [comment]
Same, but I'm locked out for 45 minutes for some reason.

**Comment by avisom** [comment]
Same, match id 6663582135

**Comment by flyingzambie** [comment]
Same. id: 6663618191

**Comment by Nathanael-Valve** [comment]
Fixed at 7:34PDT.

**Comment by Nathanael-Valve** [comment]
Note: matches formed before that still ran on the old server, apologies. But all matches formed after that update was pushed are fine.

**Comment by benhorst** [comment]
Thanks,  @Nathanael-Valve. Appreciate the look!
