### ISSUE TITLE
Sunder goes into cooldown when used on an ally in BKB, but does not swap HP

### ISSUE THREAD

**Issue by kaci4kemba** [ValveSoftware/Dota2-Gameplay#1831]
### Ability name

Sunder

### Description

Sunder goes into cooldown when used on an ally in BKB, but does not swap HP, although the description of the ability says that sunder cannot be used on a hero in BKB at all. At the same time, it is impossible to use a sander on the enemy, respectively, the ability works correctly on the enemy.
P.S. sry for google translate, ty for u work! :)

### Example Match ID (and possibly Timestamp)

6663509634 - 47:55-48:05

**Comment by BenjinZA** [comment]
Duplicate of #1290

**Comment by TheUnholyWrath** [comment]
This has been fixed, please close this issue.

**Comment by kaci4kemba** [comment]
Fixed
