### ISSUE TITLE
Wraith King Kinetic Cosmetic Skip Animation

### ISSUE THREAD

**Issue by Enivoke** [ValveSoftware/Dota2-Gameplay#1838]
### Cosmetic Item Name

Kinetic: Wraith Spin

### Description

It skips most of the animation to the end of the attack cycle.

Intended behavior: 360 jump before critical hitting.

### Example Match ID

None, It's cosmetic animation related.

### Screenshots

https://user-images.githubusercontent.com/107162297/179379387-2a6a1937-4847-48a7-bd6d-c9bfbc20732d.mp4

**Comment by Aphotic** [comment]
already posted:
#1091 #1153 
#1306 #1512 
but good effort on the comparison video, liked.

**Comment by Enivoke** [comment]
Thanks, I thought I was the only one to care about it! I made the video carefully to see the comparison :)

**Comment by jeffhill** [comment]
This will be fixed in a hotfix today, by our animation team!

**Comment by gidroponix** [comment]
tnx so much!
i've created exact same issue few weeks ago #1562
