### ISSUE TITLE
Buggy edge pan / camera

### ISSUE THREAD

**Issue by commentator24** [ValveSoftware/Dota2-Gameplay#1853]
I've been having this issue for a long time. really dont know what's wrong.
edgepan sometimes zoom to other ally / enemy heroes / enemy base / random places. can anyone explain why? i've tried to be careful not to click minimap.

This is one example game id: 6667658490 - 4:41 
i dont think i clicked on WK? i was only right clicking to move, suddenly zoomed on WK then radiant fountain / radiant shopkeeper
https://user-images.githubusercontent.com/109324155/179604794-edefb341-9737-440f-91cf-8ceebd03be1a.mp4

6667952080  - 18:47
https://user-images.githubusercontent.com/109324155/179620582-dbeffbf6-3381-4cab-b40c-d549654e1544.mp4
again here i dont think i clicked Dire base??

6673644494 - 28:06
https://user-images.githubusercontent.com/109324155/180588599-4d6a4971-48ef-4cae-9e76-70dd42222e3a.mp4

6965518998 - 27:40
https://user-images.githubusercontent.com/109324155/212118975-93a14f3f-9b64-4ba2-95bb-d52304f9545c.mp4
edgepan bottom screen + spamming right clicks to go back up, suddenly stuck to tiny icon and camera goes elsewhere. no minimap accidents here.

6965518998 - 39:25
https://user-images.githubusercontent.com/109324155/212119812-999bccd2-bccf-415e-b374-9cca6505b55f.mp4
waiting to respawn, camera changed to location of death, clicked zeus but zoomed to base instead. no minimap accidents here.

im starting to see a pattern. it looks as though im holding left click as i edgepan to minimap, which i dont think i did.

if i find more evidence, i'll post it here

**Comment by AnanasSok** [comment]
Yes, I also had similar camera movements. But they appear rarely and occur very quickly.

**Comment by commentator24** [comment]
maybe this is not related, but it seems player view of rubick changed to veno when he dc.
buggy camera?
https://user-images.githubusercontent.com/109324155/192236390-3e90f3b9-6f45-4de6-8f1e-e798fb964a7c.mp4

**Comment by commentator24** [comment]
hasnt happen in 7.33c. will close this issue until it happen again
