### ISSUE TITLE
Allies get stuck in Rubick with Shard Upgraded Dismember

### ISSUE THREAD

**Issue by XenophinH** [ValveSoftware/Dota2-Gameplay#186]
### Ability name

Dismember/Eject (Stolen)

### Description

If Rubick has Aghanim's Shard and steals Dismember from a Pudge without Aghanim's Shard, using the upgraded ability on an ally results in Eject being greyed out with no way to get the ally out. The only way to get the ally out is to steal another ability.

If Pudge and Rubick have Shard upgrade when Dismember is stolen, then the stolen ability works as intended and Rubick can use Eject.

### Example Match ID (and possibly Timestamp)

https://youtu.be/DaHqY2j5VD4

**Comment by XenophinH** [comment]
This occurred in a match a few months ago and I do not have the match ID. But confirmed the issue is still present when testing in the demo mode. The linked video outlines a couple of cases when the bug does or does not appear.

**Comment by ZViesturs** [comment]
Hi, I reproduced this issue multiple times during the this week. The issue still remains, to the point I came to submit it, only to find out it has been reported already.

**Comment by Dota-Exp** [comment]
Will be fixed in upcoming update, thank you.
