### ISSUE TITLE
Emoticons don't work in console anymore

### ISSUE THREAD

**Issue by ETalanian** [ValveSoftware/Dota2-Gameplay#1863]
### Description

We used to be able to create commands in the console such as `Bind "k" "Say_Team Well Played :bountyrune:"`.  About 3 years ago (maybe longer) this stopped working.  Old keybinds created this way still work, but we're unable to modify or create new ones.  I would really appreciate this being fixed :)

### Example Match ID (and possibly Timestamp)

N/A

**Comment by Aluerie** [comment]
Actually this still works.
You just need to copy unicode character itself rather than a keyword.

![image](https://user-images.githubusercontent.com/33165440/179851429-a2844bcb-2b8c-450e-b10d-69e4a50bea30.png)

**Comment by ETalanian** [comment]
Oh, I thought I had tried that but this works perfectly.  Thank you @Aluerie !
