### ISSUE TITLE
[Silencer] Immortal "Glaive of Oscilla"+"Glaives of Wisdom". The attack projectile is partially disrupted.

### ISSUE THREAD

**Issue by Astiberon** [ValveSoftware/Dota2-Gameplay#18661]
### Cosmetic Item Name

Glaive of Oscilla

### Description

The attack projectile is partially disrupted.
Some elements are missing.
Now:
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/107125193/b2b0fb60-0c10-46e7-be15-135a1b820a2d)
Then:
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/107125193/7b883e83-fb28-4baf-b52f-5793b35642aa)

### Example Match ID

-

**Comment by BiosPlus** [comment]
Can confirm.

Happened in match **7785779553**, no other attack modifiers on but the glaives are set to auto cast.

**Comment by Astiberon** [comment]
FIXED
![image](https://github.com/user-attachments/assets/65ff0678-1668-41dd-9ba5-d177ea6a8a54)
