### ISSUE TITLE
Players trying to lower their mmr to do things they want

### ISSUE THREAD

**Issue by hgajshb** [ValveSoftware/Dota2-Gameplay#1873]
### Description

This player 179839673 keeps their relatively low rank by partying with 4 players and intentionally lose games. It's now relatively easy because they can type gg at 30 min. I mean it's OK if they do fixed matches to do Dota Plus quests etc. But you see they actually have 4 Battle Cup championships. Something must be done to stop these 5-party teams trying to lower their MMR, because there will be no reports from their teammates.  

### Example Match ID (and possibly Timestamp)

6670005070

### Screenshots

![image](https://user-images.githubusercontent.com/306685/180113883-e2918793-25dd-472b-af93-bcbd50f5752f.png)

**Comment by AnanasSok** [comment]
Who are they disturbing?
