### ISSUE TITLE
Most of my heroes start the game without equip Taunt Item.

### ISSUE THREAD

**Issue by weiseng101** [ValveSoftware/Dota2-Gameplay#18834]
### Cosmetic Item Name

Taunt Item of most of heroes

### Description

Hi Value,

    Most of the Heroes dont have Taunt equiped when entering the game. Kindly check it~~ THanks.

### Example Match ID

-

### Screenshots

![cm](https://github.com/ValveSoftware/Dota2-Gameplay/assets/15317730/84249a4e-860e-4eec-9aa4-c2e7c4ec6bc0)

**Comment by vcv8** [comment]
Also from the heros tab when you have a hero selected that doesn't have a taunt equipped and jump to a hero with an equipped taunt it will automatically unequip itself.

**Comment by chrisf-valve** [comment]
This should be fixed in an update that shipped yesterday night.
