### ISSUE TITLE
[7.36a] [Lich] Regeneration Rune - No Mana Regeneration

### ISSUE THREAD

**Issue by aleksan4eg** [ValveSoftware/Dota2-Gameplay#18858]
### Ability name

Regeneration Rune

### Description

> Regenerates health and mana to the maximum. 

I've noticed in one of my last games t (in the last patch 7.36a) that after regeneration rune activation Lich's mana does not regenerate.

I'm adding a Video below. Also, tested it in a Lobby game and I'm confirming there is a bug.

![334181369-987e2da3-6fe7-45a0-929e-574173ad0f2c](https://github.com/ValveSoftware/Dota2-Gameplay/assets/41654555/ca8161a2-798d-46db-b16a-f308530ee000) ![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/41654555/c4ec26d1-93f5-4928-9f4a-b63473ad2037)

https://github.com/ValveSoftware/Dota2-Gameplay/assets/41654555/2885ed8d-2a81-486e-80a9-119dc90d1c86

### Example Match ID (and possibly Timestamp)

7760722505 - 24:12

**Comment by aleksan4eg** [comment]
I've noticed that it seems that **any mana regen is not applied** :D

**Comment by Turmfalke2** [comment]
yeah, more like a regen rune grants mana regeneration - similar to cm arcane aura, but LIch can't have mana regeneration. That +0.0 isn't allowed to ever change. It would consider this not a bug, just something to learn.

**Comment by NichCodes** [comment]
Correct. This is why Clarities don't work (grants +6 Mana Regen), but Mangoes do (grants +100 flat mana).

**Comment by aleksan4eg** [comment]
Yeah, it's a new change. 

> **DEATH CHARGE**
> Lich cannot gain passive mana regeneration, but any unit dying within 1200 range of Lich restores 2.5% of his Max Mana (Dying heroes restore 15% of Lich's Max Mana). Instant mana restoration from items and abilities apply to Lich as normal.

**Comment by aleksan4eg** [comment]
I'm closing this issue.
