### ISSUE TITLE
Warlock Golem still doesnt use any responses

### ISSUE THREAD

**Issue by Foto-raptor** [ValveSoftware/Dota2-Gameplay#1886]
### Description

Warlock Golem doesnt talk at all, though hes the only controlled unit with hes [own responses](https://dota2.fandom.com/wiki/Warlock_Golem/Responses) in the game. This bug probably appear after switching into source 2 engine. The only line he use is death response.

**Comment by Cymen90** [comment]
Already covered in #689 please close <3

**Comment by Foto-raptor** [comment]
> Already covered in #689 please close <3
> 
> Edit: Please do not make duplicates of your own threads.

Noone cared about old thread. I really doubt that anyone will notice 1,5 month old thread on like 30 page and do anything about it.

**Comment by shaileshgarg** [comment]
> 

The previous issue is on Page 1, if sorted by Upvotes.

**Comment by Foto-raptor** [comment]
> > > Already covered in #689 please close <3
> > > Edit: Please do not make duplicates of your own threads.
> 
> > Noone cared about old thread. I really doubt that anyone will notice 1,5 month old thread on like 30 page and do anything about it.
> 
> The previous issue is on Page 1, if sorted by Upvotes. But in this bug tracker, I haven't seen much activity from the Devs in last 1 month apart from the Wk prismatic gem fix

WK prismatic is why i made this anather thread about this + reddit post, couz I belived thats why this wk thing got fixeed - they notice it on reddit and also here. Now idk what to do really. Should I delete this thread and hoped that 1,5 month old post will achieve anything? Noone cared about that post then, why would anyone care now?
Also sorry for my bad grammar etc.  Hope everything is understandable.

**Comment by Liam-NFLD** [comment]
> WK prismatic is why i made this anather thread about this + reddit post, couz I belived thats why this wk thing got fixeed - they notice it on reddit and also here. Now idk what to do really. Should I delete this thread and hoped that 1,5 month old post will achieve anything? Noone cared about that post then, why would anyone care now? Also sorry for my bad grammar etc. Hope everything is understandable.

The devs look at this bug tracker and prioritize based on the thumbs up it receives. Mark this thread as a duplicate and let the original gather thumbs up's rather than getting them divided among multiple threads.

The old post will probably get some attention eventually given how high it is on the list.
