### ISSUE TITLE
Ghost Shroud (?) is not behaving correctly with Sange effects

### ISSUE THREAD

**Issue by BDRA-OCEE** [ValveSoftware/Dota2-Gameplay#18887]
### Ability name

Ghost Shroud

### Description

![necroSange](https://github.com/ValveSoftware/Dota2-Gameplay/assets/99892358/6d88fef8-e335-4167-8c0e-142a5d555b8d)

So I was playing around in demo with necrophos, testing out items, when I noticed that something is not mathing correctly here with the Sange increased heal & regen amp and ghost shroud's regen amp.

 - **Default Regen (no stacks, no temporary regen): 97.5**

 - **Regen with KayaSange: 130.9**

 This checks out, as you will get ~7.2 hp regen from the strength and heart hp% regen, totalling 104.7, which will then get increased by 25% resulting in 130.9.

 - **Regen with Ghost shroud active (no sange effects): 185.2**

 Again, math checks out, Ghost shroud with talent increases regen by 90%. 97.5 * 1.9 = 185.25, which is rounded down. So far everything works correctly.

 - **Regen with Ghost Shroud and KayaSange: 201.5**

 This is where it stops making sense. From the above examples, one would expect to get at least 33 regen with the above items and ghost shroud active and depending on whether its additive or multiplicative, it can have 2 different values: 

- base * 2.15 --> **104.7 * 2.15 = 225.1**

- base * 1.25 * 1.9 --> **104.7 * 1.25 * 1.9 = 248.6**

 Yet instead he only gets 201.5, which makes no sense. Something isn't mathing here.

### Example Match ID (and possibly Timestamp)

Demo mode.

**Comment by Aluerie** [comment]
104.7 * (1 + (1 - (1 - 0.25) * (1 - 0.9)))

**Comment by BDRA-OCEE** [comment]
> 104.7 * (1 + (1 - (1 - 0.25) * (1 - 0.9)))

Yeah, I found out after this post that there was such a formula for diminishing stacking.
