### ISSUE TITLE
Venom Aghanim's Scepter deals 22.5% extra damage per debuff, not 15%.

### ISSUE THREAD

**Issue by lazy1023** [ValveSoftware/Dota2-Gameplay#18889]
### Ability name

Poison Sting

### Description

Venom Aghanim's Scepter deals 22.5% extra damage per debuff, not 15%.
![屏幕截图 2024-05-28 201423](https://github.com/ValveSoftware/Dota2-Gameplay/assets/52149120/e99b6bb9-c7ab-4f7a-9640-8347adf7e4fd)

### Example Match ID (and possibly Timestamp)

..

**Comment by Avarise831** [comment]
#18883
