### ISSUE TITLE
Arc warden 3x clones

### ISSUE THREAD

**Issue by Avarise831** [ValveSoftware/Dota2-Gameplay#189]
### Ability name

Tempest Double

### Description
https://youtu.be/xGsWkKKxZ3Q
 it's very hard to do, even replay owner can't reapeat this next matches (he explains like randomly lvl uped ulty on his clone). 

### Example Match ID (and possibly Timestamp)

6570574482

**Comment by SutraWasTaken** [comment]
Please provide match IDs when possible, not YouTube links. I found the match ID - 6570574482. Example timestamp from YT vid is 11:56. Unfortunately this replay seems to have expired (15th of May.)
