### ISSUE TITLE
Tinker matrix dispells Bane's ulti

### ISSUE THREAD

**Issue by justmayori** [ValveSoftware/Dota2-Gameplay#18906]
### Ability name

DEFENSE MATRIX

### Description

When matrix on Tinker is destroyed, Fiend's Grip is just canceled.

### Example Match ID (and possibly Timestamp)

7762719646 - 40:40

**Comment by Aluerie** [comment]
736a

**Comment by justmayori** [comment]
they just forgot to add this in the skill description
