### ISSUE TITLE
Bane Fiend's Grip gets dispelled when Juggernaut's Blade Fury ends

### ISSUE THREAD

**Issue by mitchi** [ValveSoftware/Dota2-Gameplay#18948]
### Ability name

Fiend's Grip

### Description

No need for a replay. Just try it in hero mode and you'll see. Aghanim Scepter Fiend's grip also gets dispelled.

Recipe:
1. Level 30 bane, aghs
2. Level 30 juggernaut. 
3. Use Bladefury on jugg. Spin.
4. Fiends Grip during the Bladefury.
5. When Bladefury ends, Fiends Grip immediately ends as well. This does not happen with BKB

### Example Match ID (and possibly Timestamp)

7765825198 49:07 game time

**Comment by NichCodes** [comment]
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/90598280/acfd98c6-9dbe-43a0-be16-0bc7b9888c59)

Intended since Fiend's Grip is removed by hard dispels. [Read the patch notes.](https://www.dota2.com/patches/7.36)

**Comment by mitchi** [comment]
Insane buff for jugg. Thanks for clarifying!
