### ISSUE TITLE
the battlepass act does not work

### ISSUE THREAD

**Issue by karifan0** [ValveSoftware/Dota2-Gameplay#19012]
### Description

I couldn't pick up the tokens when I needed to. steam tech support did not respond to the problem. I demand compensation for the shortcoming of the PAID battlepass, without receiving full functionality for the money I paid.

Strangely, all the conditions are met
I really hope for a quick response

### Screenshots

![photo_5391193269955844094_w](https://github.com/ValveSoftware/Dota2-Gameplay/assets/170708293/21ba9e05-dc32-43b9-b684-5f39e65a4e8c)
![photo_5391193269955844093_w](https://github.com/ValveSoftware/Dota2-Gameplay/assets/170708293/6576728e-07c4-46aa-b1a2-e473b49b1920)

**Comment by Aluerie** [comment]
exhaust the dialogs

**Comment by karifan0** [comment]
it has been done for a long time, but there is no way to get a token
