### ISSUE TITLE
[Linux] Dota2 can't review overwatch cases (stuck on loading screen)

### ISSUE THREAD

**Issue by rstegg** [ValveSoftware/Dota2-Gameplay#19039]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/):
Steam Deck 256GB 1st Gen
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

#### Steps for reproducing this issue:

1. Open Overwatch Case [Review Case]
2. Wait for game to load
3. Replay controls are displayed but loading screen remains on screen, infinite load

**Comment by adrien-berchet** [comment]
Same here, I'm on Linux Mint.

**Comment by ChrisLauinger77** [comment]
I just reviewed a case - seems to work again

**Comment by adrien-berchet** [comment]
Works again for me too!
