### ISSUE TITLE
Manta Style doesn't apply debuffs from DK's Wyrm's Wrath

### ISSUE THREAD

**Issue by jlkj11** [ValveSoftware/Dota2-Gameplay#19067]
### Item name

Manta Style

### Description

As title says, none of Wyrm's Wrath passive effect get applied by DK's illusions.

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/120787118/e8739e2d-5c34-462c-b0fd-31195d9d1726)

### Example Match ID and Timestamp

any

**Comment by Dum0sss** [comment]
read patch bruv, funny thread
