### ISSUE TITLE
Spectre, Aghanim shard doesn't work

### ISSUE THREAD

**Issue by Raevsk1i** [ValveSoftware/Dota2-Gameplay#19107]
### Ability name

Dispersion

### Description

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/150054332/0bc5a0cc-0b92-4150-85cb-ecbeb2dd7aaa)

As you can see from the screenshot, the damage dealt and the damage taken do not change when using the dispersal ability.

### Example Match ID (and possibly Timestamp)

7775077791 - 15:30

**Comment by Raevsk1i** [comment]
Sorry, timestamp 21:20

**Comment by Dum0sss** [comment]
context is probably needed, but judging from log, it doesnt return more damage, only effect activation. Also you might be standing on maximum activation range, which will always return minimum damage to target, since morph is ranged that's seems the case.

**Comment by Raevsk1i** [comment]
> context is probably needed, but judging from log, it doesnt return more damage, only effect activation. Also you might be standing on maximum activation range, which will always return minimum damage to target, since morph is ranged that's seems the case.

The bug is fixed in today's update. I just checked. The issue has been resolved.
