### ISSUE TITLE
Hero losing most of his vision 

### ISSUE THREAD

**Issue by emmdvv** [ValveSoftware/Dota2-Gameplay#19116]
### Description

Lost all hero's vision. Not noticeable when the hero is in the base or is within an ally observer ward but when alone most vision is lost. Tried disconnecting and reconnecting as well as closing the game but the bug was not fixed. Tested in solo game with bots as well as demo and the same bug still happened

### Example Match ID (and possibly Timestamp)

7777999099 - Start until the end of the game

### Screenshots

![grim](https://github.com/ValveSoftware/Dota2-Gameplay/assets/104746823/590fb631-9561-47dc-97ae-1338bf31f5df)
![grim1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/104746823/357a9672-b07c-4b57-ace1-25b544b44fbb)
![grim2](https://github.com/ValveSoftware/Dota2-Gameplay/assets/104746823/9b5dfce5-ce12-409d-93f9-d447e68d2808)

**Comment by Avoirs** [comment]
Same! Just played a game without hero vision!

**Comment by emmdvv** [comment]
Looks like it's fixed.
