### ISSUE TITLE
Drow ranger multishot issue

### ISSUE THREAD

**Issue by Awey01** [ValveSoftware/Dota2-Gameplay#19139]
### Hero and spell

Drow ranger, Multishot

### Description

Drow ranger multishot is interrupted when using Glacier (Aghanim's Shard), but the tooltip says that it cannot be interrupted

**Comment by commentator24** [comment]
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109324155/f49b39e7-6532-4bbb-aac0-0d7294623d79)
seems fixed today should close issue
