### ISSUE TITLE
Timbersaw's Chakram deals half the periodic damage it should

### ISSUE THREAD

**Issue by mitrokosta** [ValveSoftware/Dota2-Gameplay#19143]
### Ability name

Chakram

### Description

Timbersaw's Chakram deals half the periodic damage advertised. Lvl 1 Chakram deals 25 damage per second, lvl 2 Chakram deals 37.5 damage per second and lvl 3 chakram deals 50 damage per second. Reproducible in lobby.
 See screenshots below.
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/47641608/e46873cf-f133-4c27-b706-6eaeeaab7f09)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/47641608/853e77dd-6960-47ba-99f5-c9643059e199)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/47641608/f3d8ecde-092c-4883-a4c2-22327889a76c)

### Example Match ID (and possibly Timestamp)

7779343891 - 6:59

**Comment by LokeLok** [comment]
It does 25/37.5/50 damage every 0.5 seconds, nothing wrong here.

**Comment by mitrokosta** [comment]
It seems I was wrong, sorry.
