### ISSUE TITLE
Doom's devour skill not gaining the neutral's skills

### ISSUE THREAD

**Issue by SKreAMmiX** [ValveSoftware/Dota2-Gameplay#19168]
### Ability name

Devour

### Description

Doom usually has 2 slots in his skills that are grayed out when the game starts, but now he only has his basic four skills. When you devour a creep, you only gain the active skills and not the passive skills. Some passives still take effect but won't show on his skills.

### Example Match ID (and possibly Timestamp)

no match ID as it was only a custom lobby.

**Comment by DariusLaw** [comment]
This is a really big bug. Please help fix this as i am unable to get any of ther neutral creep passives.

**Comment by chrisf-valve** [comment]
This has been fixed in today's update.

**Comment by Heorhi-Puhachou** [comment]
I got this bug today in match 8331267888. Please reopen issue.
