### ISSUE TITLE
[Cosmetic] If Techies reflects Shiruken Toss, Spleen will be tossed instead

### ISSUE THREAD

**Issue by Mabadman** [ValveSoftware/Dota2-Gameplay#1917]
### Item/Ability

Shiruken Toss
Lotus Orb, Mirror Shield, other sources of spell reflection

### Description

If Techies has spell reflection on them, and Shiruken Toss is used on them, the reflected Shiruken Toss will have the model of Spleen (the one in the cart) being tossed at the enemy. Very intimidating.

### Screenshot
![ezgif-2-a4781c190d](https://user-images.githubusercontent.com/42493726/180648912-e0097d4c-20aa-4a26-9eef-b06bdcf7a03d.gif)

**Comment by TheUnholyWrath** [comment]
#485
