### ISSUE TITLE
Meepo "More Meepo" Facet gives 1 less skill point so you can't max out at level 30 (Still not fixed)

### ISSUE THREAD

**Issue by Mahctep** [ValveSoftware/Dota2-Gameplay#19192]
### Ability name

More Meepo

### Description

When you select More Meepo as a Facet as meepo, when you get to level 30, you can't fully max out your talent tree. You lack 1 skill point required to max out everything.

Further testing it seems the bug occurs when leveling up from lvl 16 to lvl 17, when you have all skill points used up at level 16, and then you level up to 17, you just don't get a skill point at all.

So, to take advantage of the more meepo facet (which should make you be able to level up meepo ult at lvl 17, when you get to level 16 and have an unused skill point, you should skill it on anything.

Here's hoping this gets fixed fast. It's really annoying.

Fixed temporarily when patch 7.36a came out but as of June 7, 2024, 7.36b, the bug seems to have come back and still exists.

### Example Match ID (and possibly Timestamp)

7781203177 - 30:00

**Comment by chrisf-valve** [comment]
This should be fixed in this afternoons update
