### ISSUE TITLE
Venomancer Plague Wards always do 50% less base damage to heroes and 50% increased base damage to all units

### ISSUE THREAD

**Issue by Gitpushka** [ValveSoftware/Dota2-Gameplay#19190]
### Ability name

Plague Ward

### Description

Venomancer Plague Ward damage is completely broken. Does 50% less damage to heroes and 50% more to creeps at any level even after getting the level 25 talent for wards. Nice job on this one dev Team :)

Screenshots and tests have been done in every situation and facet.

![dota2_wYaanfn63W](https://github.com/ValveSoftware/Dota2-Gameplay/assets/128396023/31c8a95f-6ad5-4b50-b434-37c263d213bd)
![dota2_QDw4wbnf8I](https://github.com/ValveSoftware/Dota2-Gameplay/assets/128396023/cdf88598-ba3f-4e91-a879-9255648f9cf1)

### Example Match ID (and possibly Timestamp)

visible in every game, tested in Demo for certainty

**Comment by Sanekkk2** [comment]
i can't believe you are golden venomancer and have never clicked on wards. Wards have piercing damage class , it's works as intended

**Comment by Gitpushka** [comment]
Lack of Statements on spells in dota is misleading

**Comment by Gitpushka** [comment]
Lack of Statements on spells in dota is misleading
