### ISSUE TITLE
Snapfire Ricochet II, the ricochet attacks can be missed

### ISSUE THREAD

**Issue by lazy1023** [ValveSoftware/Dota2-Gameplay#19215]
### Ability name

Ricochet II

### Description

Snapfire Ricochet II, the ricochet attacks can be missed
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/52149120/8b256b1d-6886-4295-9eba-ab52a888a36d)

https://github.com/ValveSoftware/Dota2-Gameplay/assets/52149120/243c1e15-db36-4615-9085-f77112d89760

### Example Match ID (and possibly Timestamp)

.

**Comment by commentator24** [comment]
this guy's video is cooler #19178
please close the issue, they said this will be fixed in next patch
