### ISSUE TITLE
Unable to view the replay of an overwatch replay

### ISSUE THREAD

**Issue by gelo0313** [ValveSoftware/Dota2-Gameplay#19240]
### Description

Hi - attaching the view. I'm not sure how to point to the replay because I can't see even the Match ID. But as you can see in the video, I have downloaded the replay, but when reviewing the case it only shows a loading screen. Nothing happens regardless of whatever button I click. I have tried to re-launch Dota 2 and restart the PC but it's the same. This is the first time I'm reviewing an overwatch replay. I'd really like to contribute to reduce toxicity in the community specially my favorite player (Grubby) quit Dota 2 streaming simply because there's toxicity even at the highest rank.

https://github.com/ValveSoftware/Dota2-Gameplay/assets/166331007/42f50dd9-63de-4b04-a492-606390785753

### Example Match ID (and possibly Timestamp)

NA

**Comment by commentator24** [comment]
#17822 upvote and close your issue.

hasn't been fixed since 2 weeks ago
duplicates
#18835
#19030
#19082

**Comment by gelo0313** [comment]
Thank you. Closing this as duplicate.
