### ISSUE TITLE
Sprays doesnt work

### ISSUE THREAD

**Issue by shade2105** [ValveSoftware/Dota2-Gameplay#19256]
### Description

Team supporter spray doesnt work

### Example Match ID (and possibly Timestamp)

0

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/102245384/d5020d48-73af-4427-bbd2-d2fddbc25f09)

**Comment by chrisf-valve** [comment]
Hello, this should be fixed with an update that was released yesterday. If you are still experiencing issues with your supporter's club sprays, please comment with the spray that is not working and I will take a look.

**Comment by shade2105** [comment]
Its fixed now. Thank You for your work.
