### ISSUE TITLE
Vengeful spirit - Avenging missile doesn't work

### ISSUE THREAD

**Issue by KaZaaM4iK** [ValveSoftware/Dota2-Gameplay#19261]
### Ability name

Avenging missile

### Description

Hello. The Vengeful spirit character's Avenging missile ability does not work. I tested this in test ground. 100 creeps and 100 heroes were killed and the damage never increased above 270 taking into account the 25% resist. I am attaching a screenshot. Sorry for the English, I'm writing via Google translated/
![venga](https://github.com/ValveSoftware/Dota2-Gameplay/assets/12086799/f345df64-67e2-4049-81fb-95a3c22b3496)

### Example Match ID (and possibly Timestamp)

7784955435

**Comment by Aluerie** [comment]
it's reverse.

**Comment by commentator24** [comment]
it deals bonus dmg for every creep the enemy has killed, not venge.
test again with 100 last hits by enemy 🙄

**Comment by KaZaaM4iK** [comment]
> it deals bonus dmg for every creep the enemy has killed, not venge.
> test again with 100 last hits by enemy 🙄

Thanks for the info. You're right. I needed to look at the English version of the description of this ability. In the English version it is written that “for every creep the enemy has killed”, and in the Russian version it is written “for every creep killed by the target”. Under the target, I thought that Vengeful Spirit itself was the target. In this case, it is necessary to change the description of the abilities.
