### ISSUE TITLE
Bristleback w/ Goo Facet also releases Quill Spray

### ISSUE THREAD

**Issue by TheUnholyWrath** [ValveSoftware/Dota2-Gameplay#19270]
### Ability name

Bristleback

### Description

https://github.com/ValveSoftware/Dota2-Gameplay/assets/46859977/16b456a1-ed80-41ff-be31-d8718f54e460

For large damage instances, Bristleback will shoot out one copy of Goo and the rest of the bristleback procs will be Quill Spray

### Example Match ID (and possibly Timestamp)

demo

**Comment by Aluerie** [comment]
duplicte #19164
