### ISSUE TITLE
Darkseer Lv10 +20% wall illusion damage talent doesn't work

### ISSUE THREAD

**Issue by eggers09** [ValveSoftware/Dota2-Gameplay#19353]
### Ability name

+20% wall of replica illusion damage (talent)

### Description

As can been seen in the video, the lv10 talent that is supposedly giving wall of replica illusion extra 20% damage completely doesn't function. The illusion is doing the same amount of damage (around 30) with or without the talent. 

https://github.com/ValveSoftware/Dota2-Gameplay/assets/55358270/6145103f-12eb-4614-b5d2-d550b68a0c22

### Example Match ID (and possibly Timestamp)

It's not match specific

**Comment by Avarise831** [comment]
i can confirm most likely this does not work with aganim too

**Comment by Avarise831** [comment]
i can confirm most likely this does not work with aghs too

**Comment by eggers09** [comment]
fixed 7.36c
