### ISSUE TITLE
Some taunts are randomly getting unequipped

### ISSUE THREAD

**Issue by Smashthedude** [ValveSoftware/Dota2-Gameplay#19371]
### Cosmetic Item Name

Taunts in general

### Description

I've noticed sometimes whenever i try to use taunt on a hero nothing happens, lo and behold upon checking the armory, the taunt was unequipped, there's no shuffle on taunts. 
I appreciate the effort put into modernizing the armory, but for a game where cosmetics are a main part of monetization, one would think there would be a streamlined and working process. There has been plenty of suggestions and feedback and i hope we will see improvements soon.

### Example Match ID

n/a

**Comment by chrisf-valve** [comment]
This should be fixed in an update that shipped yesterday night.
