### ISSUE TITLE
Taunts automatically become unequipped 

### ISSUE THREAD

**Issue by Kyleoth** [ValveSoftware/Dota2-Gameplay#19449]
### Cosmetic Item Name

all Taunts

### Description

Taunts automatically become unequipped even when i equip them before game, when game starts, they are unequipped.

### Example Match ID

7769344906

**Comment by BgueC6595** [comment]
duplicate of #18703

**Comment by chrisf-valve** [comment]
This should be fixed in an update that shipped yesterday night.
