### ISSUE TITLE
Linken Sphere procs multiple times when work with Mirror Shield and Lotus Orb 's buff

### ISSUE THREAD

**Issue by Emerald-flipflap** [ValveSoftware/Dota2-Gameplay#19506]
### Item name

Linken Sphere, Mirror Shield, Lotus Orb 

### Description

Linken procs/works multiple  on Witch Doctor's Q (Paralyzing Cast) when the heroes have Linken also have Mirror Shield and under Lotus Orb's buff. After the 1st time this bug occurred on a hero, Linken kept its multiple procs/works ability even when not under Lotus Orb's buff.

### Example Match ID and Timestamp

7804549754 - 36:25 41:00 41:15

**Comment by dampf1** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/3928
It is this thing.
