### ISSUE TITLE
Mana Regen is 0 on Lich

### ISSUE THREAD

**Issue by StefanVinica** [ValveSoftware/Dota2-Gameplay#19532]
### Description

Im playig lich and i have 0 mana regen even I bought items for mana regen

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/26149819/2b110b78-b232-4e89-ac89-30e4f920156f)

**Comment by Memoframe** [comment]
innate ability, no mana regen but gain mana from dead units

**Comment by GameExplorer** [comment]
New lich meta

**Comment by TpsArchyy** [comment]
are you a cretin or you dont understand "lich cannot regen mana"?

**Comment by StefanVinica** [comment]
oh i see its just a game mech

**Comment by Harry284** [comment]
Same on ranked s match 8149078320 clarity does not work only Mango and Fountain worked, Mamaboots only on actication, please repoen issue
