### ISSUE TITLE
Incorrect ammout of Dota+ Progress rewarded

### ISSUE THREAD

**Issue by FireWolf-f** [ValveSoftware/Dota2-Gameplay#1953]
### Description

I played a normal unranked game with juggernaut and my dota+ progress went from 2800 to 2830 instead of 2900.
There isnt even a scenario where 30 ld be added as far as i know.

### Example Match ID (and possibly Timestamp)

6682684684

### Screenshots

![image](https://user-images.githubusercontent.com/110227424/181723613-32b9c340-56a0-41bc-87db-ee60cbaa6a43.png)

**Comment by commentator24** [comment]
not a bug. rare relics give 30 xp per level up. common 5 xp.
im guessing u win the game +100, level up rare +30 = 130

**Comment by FireWolf-f** [comment]
i checked my progress before the game and i could swear it was 2800 but now im starting to doubt myself...
ty
