### ISSUE TITLE
AUTOMATIC BAN????

### ISSUE THREAD

**Issue by JohnDope90** [ValveSoftware/Dota2-Gameplay#19554]
### Description

Just got a 24 hour ban for this game - 7810515679. 
I was the pos 5 WD. I didnt type a single word in the game, my mid and safelaner had a hard time and both had bad scores, sniper mid 14-17, pos 1 ursa 8-10.

I went for team items like pipe, crimson and shivas, bcs i had such a good game,  and enemy had hard time to kill me.
Anyhow, my team reported me, and i think ur automatic system gave me a ban. EVENTHO we won the game, i had most dmg, second highest networth in the game? I dont see how i did grief this game, i won the game as i see it. And yes i didnt go for standard support items, but we had techies offlane, so we needed some team aura items.
AND btw, i did buy most wards and smokes in the game, dire + radiant.
I dont think this ban is fair at all, and im very sad to lose 500 behavior score bcs of this. 
PLS FIX UR AUTOMATIC SYSTEM, AND LET OVERWATCH DECIDE! THX

I have posted about this before, and rly think u should look into it.

### Example Match ID (and possibly Timestamp)

7810515679.

**Comment by Dum0sss** [comment]
You got reported and was banned, for excessive reports or for overwatch multiple sentences. It rarely fails and there is no way to remove it. Dont be a pain in the arse and thats it. The fact that my overwatch not always works on single game griefers, it means that you have to accumulate it for over some games. Also people from both teams will report you for playing broken heroes. its really annoying.

**Comment by Nallefjant** [comment]
I really think it makes no sense to get banned in games that you win. Even if someone "grief" the griefing can logically not have been that bad if you win.
