### ISSUE TITLE
Vengeful Spirit Aghs doesn't work until item is dropped and picked up

### ISSUE THREAD

**Issue by Loc-Tran** [ValveSoftware/Dota2-Gameplay#19555]
### Ability name

Aghs

### Description

There are several instances of me dying after getting the aghs and the passive does not activate. Prior to getting it to work, I tried switching into my backpack and back into my items but it was still broken.

### Example Match ID (and possibly Timestamp)

7810599294

**Comment by TheUnholyWrath** [comment]
venge aghs is an upgrade to vengeance aura. you need to put a skill point in it for it to work. you can close this
