### ISSUE TITLE
Changing Facets in Demo Mode doesn't work

### ISSUE THREAD

**Issue by LokeLok** [ValveSoftware/Dota2-Gameplay#19585]
### Description

Changing to a different Facet in Demo Mode doesn't work atm(it does work if you go back to dashboard and change it from there). Happened after the client update earlier today(the one before 7.36c). 

https://github.com/ValveSoftware/Dota2-Gameplay/assets/106764092/e69ec34d-dbd3-4d95-818b-6d71d61d4852

**Comment by chrisf-valve** [comment]
This has been fixed, thanks for the report!

**Comment by LokeLok** [comment]
Thank you!
