### ISSUE TITLE
Venomancer plague carrier facet cannot attack neutral creeps

### ISSUE THREAD

**Issue by ZeChicken** [ValveSoftware/Dota2-Gameplay#19586]
### Ability name

Plague Ward Facet

### Description
This was tested in  demo mode, turbo, and all pick with the same result.

Venomancer plague wards with the plague carrier (On a hero) facet cannot attack neutral camps in the 7.36c update. When plague wards are casted on a hero, you must be near another unit that can be attacked (Heroes, Lane Creeps) for the plague wards to start attacking neutral creeps.

When selecting the plague wards, It shows an error saying "Cannot Attack"
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/28941132/f849a7d8-7bb2-456c-9664-adf685d89431)

### Example Match ID (and possibly Timestamp)

none

**Comment by emmdvv** [comment]
Playing turbo right now and I'm having the same issue. Plague wards hits dire/radiant creeps but not neutrals. Plague wards can attack if planted on the ground but not when attached to heroes

**Comment by Codball** [comment]
Just happened to me in a ranked match. Seemed to work fine on everything but neutral creeps. Match ID 7813896005.

**Comment by kirsanium** [comment]
This basically makes the facet unusable, valve please fix

**Comment by Kagotpush** [comment]
Wards can actually hit neutral creeps if you're under enemy team's vision. It might be connected with latest 7.36c bug fix:
"Fixed Venomancer's Plague Wards attacking while their carrier is invisible to the target"

**Comment by ZeChicken** [comment]
This issue has been fixed in todays tiny patch! closing the issue as complete
