### ISSUE TITLE
Clockwerk have movement speed with no boot

### ISSUE THREAD

**Issue by timlovedota** [ValveSoftware/Dota2-Gameplay#19604]
Match ID : 7812398029

![Untitled](https://github.com/ValveSoftware/Dota2-Gameplay/assets/173664178/971de688-793c-427c-a5f9-d53e7b1cb7d5)

how is clockwerk with base movespeed of 310 have 360 at start of the game?

steam ID : 137528291 seems to know the bug very well with a suspected smurf account

**Comment by lazy1023** [comment]
310+Nighttime Move Speed Bonus(30)+Wind Lace(20)=360
