### ISSUE TITLE
Lina is too skilled

### ISSUE THREAD

**Issue by Fluffy-Slippers** [ValveSoftware/Dota2-Gameplay#19721]
### Description

At the match beginning Lina with only 1 ability with level 0, has 3 abilities in total
Before selecting skill to upgrade
![dota2_bug_22_06_001](https://github.com/ValveSoftware/Dota2-Gameplay/assets/174530014/e3853a45-18cf-4438-8e43-88b18ec17fc0)
After selecting skill to upgrade
![dota2_bug_22_06_002](https://github.com/ValveSoftware/Dota2-Gameplay/assets/174530014/4f1c18ed-f5cc-404e-b41d-da0c31cff23a)

### Example Match ID (and possibly Timestamp)

7810058840 -0:46

**Comment by neverm0rebetter** [comment]
fiery soul is an innate ability, invoker's abilities are always learned when picked in ability draft, so he still has a skill point on crypt swarm
