### ISSUE TITLE
Linken's blocks LC duel

### ISSUE THREAD

**Issue by ShawnTheSheep101** [ValveSoftware/Dota2-Gameplay#19765]
### Ability name

DUEL

### Description

_Linken's Sphere_ **dispells** _Legion Commander_ **Duel**, even tho the spell says it **CANNOT be dispelled**. This is a bug, or just a miss wording.

### Example Match ID (and possibly Timestamp)

7829264997 Time: 34:40 and at 53:10

**Comment by AkovBrick** [comment]
As per item description Linkens does not provide a dispel. A dispel removes the buff/debuff from a successfully cast spell, whereas Linkens prevents, or "blocks," the spell from being casted. 

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/151986380/005cd524-ee94-4285-9a1b-796e3d575f91)

**Comment by vivi-lili** [comment]
Linken's Sphere provides spell block at the time of cast, it is not a dispel.
