### ISSUE TITLE
Exalted Arcana has been switched for regular quality X2

### ISSUE THREAD

**Issue by broknfutr** [ValveSoftware/Dota2-Gameplay#19850]
### Cosmetic Item Name

Exalted Bladeform Legacy, Exalted feast of Abcession 

### Description

I opened Dota 2 and received two Arcana, Blade-form Legacy and Feast of Abcession, which I was initially happy about then I realised that my Exalted versions of those items were missing. 

In the now in Armoury category at top right the new Arcana are listed as recently un-bundled,  which I have no memory of doing and are subsequently on trade cool-down.

I've provided a screenshot of my Rubick Arcana, which is unchanged for reference. 

Please Help!

### Example Match ID

n/a

### Screenshots

![20240710122449_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/35979710/1348160b-1114-4731-862b-3ad31c35a63e)
![20240710122457_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/35979710/81ed0bb5-a02d-4aa7-b475-e2a33dfdc84c)
![20240710123246_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/35979710/b036eb58-08a8-49df-86cd-94d06ac9eb75)
![20240710122629_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/35979710/e9756222-ffcb-4ba6-a751-06454d3209cf)

**Comment by lordjhay88** [comment]
Same issue bro
i have exalted arcana jug and pudge 
and my jug have all Gem and autograph gem. 
wtf they doing to us after we pay a high price they will exchange to low price

**Comment by lacountread** [comment]
Same issue

But I only have Pudge's Arcana.
I lost my gems with all the progression and the autograph gem.

**Comment by broknfutr** [comment]
Fixed for me! Thank you!
