### ISSUE TITLE
 missing arcane on Pudge

### ISSUE THREAD

**Issue by darp11t** [ValveSoftware/Dota2-Gameplay#19863]
### Item name

Feast of Abscession

### Description

I haven’t logged into the game for a long time even before the release of episode 3. Today I logged into the game and discovered that I was given the item Feast of Abscession - Back and the main item disappeared before I had it, my steam name is “tempo di tortura”.

### Example Match ID and Timestamp

steam id:1172314768. 10:57.

**Comment by Ghozt93** [comment]
Item name
Feast of Abscession

Description
I played till yesterday with my PUDGE Full ARCANA Set.[ MATCH: 7836210419 ].Today I logged into the game and discovered that I was given the item Feast of Abscession - Back and the main item disappeared before I had it, my steam account name is " Ghost ". I am really frustrated of DOTA did to me today. Very disappointing. I want this to be fixed as soon as possible as i have spent 3000rs in purchasing the PUDGE FULL arcana set years back..!!!

**Comment by LokeLok** [comment]
Go to Pudge and re-equip the arcana.

**Comment by LokeLok** [comment]
Do this:


https://github.com/ValveSoftware/Dota2-Gameplay/assets/106764092/d39c0714-a9df-48b8-8b5c-c146d347adb4

**Comment by darp11t** [comment]
thx
