### ISSUE TITLE
A issue with watch dota2 replays

### ISSUE THREAD

**Issue by kkk5555** [ValveSoftware/Dota2-Gameplay#19918]
### Description

https://streamable.com/tjuucu
After updated, when i watch replay , i puase then  click play button ,it is freeze and i cant do anything

**Comment by PriscillAAH** [comment]
Been getting this bug too

**Comment by spalw** [comment]
I've been getting this issue since ACT 3 released.

Opening and closing the combat log will unfreeze the demo and allow you to continue as normal without relaunching. 

The freeze is triggered when being paused and skipping forwards or backwards.

**Comment by eugene-valve** [comment]
Thanks for the bug report, this should be fixed in the latest update.
