### ISSUE TITLE
Can't queue ranked as demands associated phone even when one already set. 

### ISSUE THREAD

**Issue by EugeneGGHQ** [ValveSoftware/Dota2-Gameplay#1993]
### Description

Can't queue ranked at the moment (probably a saving grace for my MMR). Receive prompts to say that I need an associated phone verified. However, I already have a phone linked to my account, so lawd knows what's happnin. 

Thanks for all your hard work! Hope this one is an easy one to fix :) 

### Screenshots

[Shazam!](https://i.redd.it/ebs6zf9iqhf91.png)

**Comment by filipejunqueira** [comment]
Exactly same problem here. 
Running pop_os 22.04 in case this is relevant. Using "native steam" version (NOT the flatpak).  

![image](https://user-images.githubusercontent.com/22006279/182625575-2ee42426-dbcd-4f86-b39d-3b2fea8cd9b0.png)

**Comment by EugeneGGHQ** [comment]
Seems to have resolved after last night's patch <3
