### ISSUE TITLE
Slark dispelling UNDISPELLABLE CORROSIVE HAZE by Shadow Dance or Depth Shroud

### ISSUE THREAD

**Issue by aidatgunes** [ValveSoftware/Dota2-Gameplay#2000]
When the UNDISPELLABLE Corrosive Haze is applied through aghanim's shard with Slithereen Crush, Slark dispels this by using Ulti or Shard, despite being under the effect of Slithereen Crush which opposes how aghanim's shard describes the skill for Slardar.

**Comment by TheZett** [comment]
He does not dispel it, but his ultimate cannot be revealed at all, even if affected by True Sight.

You lost vision of him, because his ult makes him unrevealable. The debuff stayed.

**Comment by aidatgunes** [comment]
Right after discussing this on reddit, someone pointed out something I missed, aghanim's shard applies corrosive haze for 5 seconds, and depth shroud is 3 seconds, meaning it just wears off by the time slark is out of shadow dance. My bad.

But I never mentioned anything about being revealed. I didn't expect that to happen.
