### ISSUE TITLE
Juggernaut Arcana Missing 

### ISSUE THREAD

**Issue by HorrorDamian** [ValveSoftware/Dota2-Gameplay#20013]
### Cosmetic Item Name

Bladeform Legacy Arcana

### Description

After Collector's Cache Update: Juggernauts Arcana Mask was given out for free with people that already owned the arcana. But now I only own the mask and my arcana is completely missing.

My previous games also show juggernaut without the arcana even tho i played the match with the set.

### Example Match ID

7833777023

**Comment by irector** [comment]
![Uploading photo_2024-07-13_23-30-31.jpg…]()

**Comment by irector** [comment]
![photo_2024-07-13_23-30-31](https://github.com/user-attachments/assets/7b5134a9-8457-4584-ac53-c558e54f891a)

**Comment by LokeLok** [comment]
Press equip

![image](https://github.com/user-attachments/assets/bfee9084-ff31-4485-b8e7-f54a993d6a27)

**Comment by HorrorDamian** [comment]
I didn't look in the category of "Hero Base" :O lol

Thanks

**Comment by irector** [comment]
> Press equip
> 
> ![image](https://private-user-images.githubusercontent.com/106764092/348512076-bfee9084-ff31-4485-b8e7-f54a993d6a27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5NDU5MTgsIm5iZiI6MTcyMDk0NTYxOCwicGF0aCI6Ii8xMDY3NjQwOTIvMzQ4NTEyMDc2LWJmZWU5MDg0LWZmMzEtNDQ4NS1iOGU3LWY1NGE5OTNkNmEyNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNFQwODI2NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMGVmZmUzZTZlNWFjNzcyM2QxZTNjY2IwZTdmMTI2MmViYzk2OTFhMDU2MTYxMDlmYzVkOTM2MWJkYTIwYWRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EMx71k9eidHQ_mceuoj-tIp8ecCB10FTkwt4sgrw_ms)

why you resend my screenshoot?))
