### ISSUE TITLE
Treant Protector's Overgrowth [R] does not display its radius

### ISSUE THREAD

**Issue by massivebird** [ValveSoftware/Dota2-Gameplay#20038]
### Ability name

Overgrowth

### Description

Unlike other No Target abilities, Treant Protector's Overgrowth does not display its radius when the player hovers over it. By extension, its radius cannot be "pinned" to the character with `Alt + Right Click`.

<img width="828" alt="tree" src="https://github.com/user-attachments/assets/e1d42769-a92f-44cf-930f-bcac096038b2">

### Example Match ID (and possibly Timestamp)

Hero Demo

**Comment by Jordan11599** [comment]
This is most likely because overgrowth is global (from aghs usage) but looks to be a possible oversight

**Comment by ASDadsfq23** [comment]
> This is most likely because overgrowth is global (from aghs usage) but looks to be a possible oversight

that might be because of the aghanim, but as someone who mains Treant for a while i can say that it showed radius just fine one or two patch before, and for unknown reason it doesn't anymore, which is really unfair cause now you have to press it based on your intuition

**Comment by massivebird** [comment]
This seems fixed now! Overgrowth displays a radius now :3 thank you!
