### ISSUE TITLE
Got removed from a match while playing

### ISSUE THREAD

**Issue by Deadp00li0** [ValveSoftware/Dota2-Gameplay#20046]
### Description

Just got removed from a match I was constantly playing, only thing I did was stay in base for around 2 minutes, I was moving and talking to other players during that time not afk for even a second and still got removed from it, please check it out, lost 1400 gold and the match probably because of that and also got sent to the low priority.

### Example Match ID (and possibly Timestamp)

7846700301 - 45:45

### Screenshots

![DC](https://github.com/user-attachments/assets/dc7926a2-b31b-4b8d-b5d5-a6030d6ea260)

**Comment by Deadp00li0** [comment]
Learn how do read einstein, I was inside the base not sitting there, if being inside the base removed you from a game, then playing high ground would be against the rules of the game.

**Comment by serak88** [comment]
If you don't get any experience from creeps or kills for 5 minutes you are marked as afk and removed from the game.
