### ISSUE TITLE
Snapfire Ricochet II bug

### ISSUE THREAD

**Issue by lazy1023** [ValveSoftware/Dota2-Gameplay#20063]
### Ability name

Ricochet II

### Description

When Snapfire is affected by mars's Blood sport or NS's Blinding void, ricochet II splits to the enemy ward.
Then the split attack will keep triggering. 

https://github.com/user-attachments/assets/2ab64b60-1700-4f1b-9f25-b03cb4784715

https://github.com/user-attachments/assets/30050639-bfa9-4eea-ac72-ecec8a137548

### Example Match ID (and possibly Timestamp)

7841628288 - 20:54

**Comment by Jordan11599** [comment]
That's very interesting, appreciate the post on this, hopefully can be resolved soon.
