### ISSUE TITLE
Zaug's Lair (Dragon Head Token Reward) Crownfall Act3

### ISSUE THREAD

**Issue by ro-wan** [ValveSoftware/Dota2-Gameplay#20113]
### Description

I scored 500k+ in Zaug's Lair, but no token was given. 

Do I need to kill the final boss to get the reward token?

Thank you.

### Screenshots

![att z38NIXAi1EHgCG5NMsxPWNtUyDbKBB1dX_VTO5IHsxE](https://github.com/user-attachments/assets/034b9c21-97cc-4704-9624-c373a6854e82)

**Comment by dayvough** [comment]
Happening to me as well, am on a Mac Sonoma 14.5. Points aren't being counted for me either. I also know something is up because I'm seeing the instructions "Move using WASD keys" popups again and again. I was thinking those would be gone once I go through it once.

**Comment by ro-wan** [comment]
Hi @dayvough!

Did you make any progress? I tried to play once and scored 700k+ again, but still nothing. 

I did played using both WASD and arrow keys, same results.
