### ISSUE TITLE
Input lag

### ISSUE THREAD

**Issue by gorterg** [ValveSoftware/Dota2-Gameplay#20131]
### Description

After the release of Crownfall ACT III there is 4-5 second delay between movement and ability cast actions. The ping averages around 30-40 with 0% packet loss, indicating it might be a server-side problem.

Please take a look at this issue with utmost priority, game has been unplayable for approx. a week.

**Comment by EternalllZM** [comment]
Do you have an AMD graphics card? I found that "Anti-Lag 2.0" was enabled in video settings which would (under certain circumstances) create severe input lag for a few seconds or until disabled.

**Comment by z4p0v** [comment]
> Do you have an AMD graphics card? I found that "Anti-Lag 2.0" was enabled in video settings which would (under certain circumstances) create severe input lag for a few seconds or until disabled.

I have the same problem, but I don't have this feature in the settings due to the fact that I have old graphics cards and a processor in my laptop. How can I fix it?

**Comment by RamyFerhat59** [comment]
I have similar problem that where i get input lag for like 30-60sec when i change windows on wayland session

**Comment by RamyFerhat59** [comment]
a fix that worked for me is to not start the game fullscreen can you try that ?

**Comment by JCMC05** [comment]
this issue happened earlier this year and they fixed, now with act 3 a bunch of people are getting the issue again
no word from valve yet
https://github.com/ValveSoftware/Dota2-Gameplay/issues/19894
we are trying to gather their attention, we need to keep reporting on steam and here to try and make them aware of this

**Comment by lvefunc** [comment]
![20240718202135_1](https://github.com/user-attachments/assets/aa98dbb2-bcbd-4df5-ab1e-69a216db2cc8)

Can confirm there's no "Anti-Lag 2.0" setting for me too. Also starting the game in windowed mode did not help.

**Comment by VetaLioSTV** [comment]
I have the same.. after ACT 3, i have instant 34 delay input lag, which is super annoying and i also dont have any "anti-lag" feature in settings, maybe it can be disabled in console command?!

**Comment by z4p0v** [comment]
> I have the same.. after ACT 3, i have instant 34 delay input lag, which is super annoying and i also dont have any "anti-lag" feature in settings, maybe it can be disabled in console command?!

I have the same problem and I also thought about using the command, but I couldn't find a command to do it

**Comment by VetaLioSTV** [comment]
> > I have the same.. after ACT 3, i have instant 34 delay input lag, which is super annoying and i also dont have any "anti-lag" feature in settings, maybe it can be disabled in console command?!
> 
> I have the same problem and I also thought about using the command, but I couldn't find a command to do it

I have GTX 1050ti and there is seems to be an analogue of "anti-lag" technology which is called "**NVIDIA Reflex**", unfortunately i do not remember when it appeared in Dota 2, but its was enabled for a while, so i have tried to disable it completely and as result nothing has been changed, same instant 32-34 delay input lag without any packet loss...

Seems to be we need a hot fix from Valve.

Hey, any thoughts @ValveSoftware @wykrhm @beeequeue @jeffhill @danieljennings ?

**Comment by amonpxh** [comment]
yeah, same problem. Also not being able to connect.

**Comment by JCMC05** [comment]
> need a hot fix from V

earlier this year same problem happened, i wasnt affected but a friend was, i think valve fixed it with a patch

**Comment by IgorHoruzha** [comment]
Hello, do anybody still have the issue?

**Comment by gorterg** [comment]
> Hello, do anybody still have the issue?

Hey, the issue was solved for me as of last bug fix patch, game runs really smooth now.

**Comment by VetaLioSTV** [comment]
> Hey, the issue was solved for me as of last bug fix patch, game runs really smooth now.

are you sure on 200% that is completely fixed? For me it still shows input lag(with enabled fps/network setting), plus from start of the game i have it, but later it became more stable... Something strange with that input lag, how and why it appeared and why it still shown...

**Comment by IgorHoruzha** [comment]
> > Hey, the issue was solved for me as of last bug fix patch, game runs really smooth now.
> 
> are you sure on 200% that is completely fixed? For me it still shows input lag(with enabled fps/network setting), plus from start of the game i have it, but later it became more stable... Something strange with that input lag, how and why it appeared and why it still shown...

IMO it makes sense to create a new issue and link related issues to it. Describe the issue as clear as possible, write Your hardware information, and add a video to show how does it feels and looks like. Could You, if You still have the issue, please?
