### ISSUE TITLE
[QoP] Arcana+"Form of the Abyssal Kin"/"Abyssal Kin Legs"

### ISSUE THREAD

**Issue by Astiberon** [ValveSoftware/Dota2-Gameplay#2013]
### Cosmetic Item Name

Arcana+"Form of the Abyssal Kin"/"Abyssal Kin Legs"

### Description

If Arcana is equipped, some bugs occur:

- [x] The armor slot still displays the leg slot from the set.( FIXED)

- [x] The leg slot from the set looks incorrect.( FIXED)

### Example Match ID

-

### Screenshots

![image](https://user-images.githubusercontent.com/107125193/183156139-37763c67-1935-4060-94d2-d4fe330ef4e1.png)
![image](https://user-images.githubusercontent.com/107125193/183156249-6e0fb052-65ba-45af-a76b-39938656ceb4.png)

**Comment by AncientsAndAntiques** [comment]
Those reading see my comment on #2030

**Comment by Astiberon** [comment]
> Those reading see my comment on #2030

This is a different bug and it's still not fixed.

**Comment by AncientsAndAntiques** [comment]
> This is a different bug and it's still not fixed.
Apologies - I misread this one. I was not able to replicate this but I see what you mean in your first example image. Do you have replication steps for this?

**Comment by Astiberon** [comment]
> Apologies - I misread this one. I was not able to replicate this but I see what you mean in your first example image. Do you have replication steps for this?

1)
Without Arcana / With Arcana:
![Без имени](https://user-images.githubusercontent.com/107125193/187746874-c378b7f2-d660-4514-98f3-1737454306c4.png)

2)
Arcana+Legs:
![gdsfg](https://user-images.githubusercontent.com/107125193/187747594-7ee16b2f-8b60-40be-94bb-a6b7b3264ff1.png)

**Comment by shaileshgarg** [comment]
- [ ] This is still not fixed, Form of the Abyssal Kin Shoulder still has Leg Cosmetic linked to it.
 - [ ] The Leg cosmetic itself is bugged when used with Arcana
 - [ ] Lineage The Arch Temptress, should also get a Leg Slot Item.
