### ISSUE TITLE
Portal scroll buy slot became hurricane pike

### ISSUE THREAD

**Issue by Human0797** [ValveSoftware/Dota2-Gameplay#20224]
### Item name

Portal scroll and Hurricane Pike

### Description

![WhatsApp Image 2024-07-19 at 19 47 32](https://github.com/user-attachments/assets/1c4fac33-d578-4995-9a0d-8544395e9a8c)
Just look at the picture

### Example Match ID and Timestamp

Everytime, every match i play dota2

**Comment by Jordan11599** [comment]
Youve accidently done this. Just drag the teleport scroll over and replace

**Comment by Human0797** [comment]
Oh my bad, i've never done this before
