### ISSUE TITLE
Crownfall Act III Strange Vendor Encounter Error

### ISSUE THREAD

**Issue by cdavis963** [ValveSoftware/Dota2-Gameplay#20249]
### Description

Despite having the necessary tokens to get the third option for 15 scraps (or even one of the lower tier ones), I am unable to spend the tokens due to "tokens needed".
![Screenshot (401)](https://github.com/user-attachments/assets/9965a9c6-0d83-4351-959f-22240b8ef9fc)

**Comment by Aluerie** [comment]
it s the other way around deal

**Comment by cdavis963** [comment]
Ah, thank you Aluerie.
