### ISSUE TITLE
[Queen of Pain] "The Rose of Ristul-Shoulder"+Arcana. The dress has several problems.

### ISSUE THREAD

**Issue by Astiberon** [ValveSoftware/Dota2-Gameplay#20241]
### Cosmetic Item Name

"The Rose of Ristul-Shoulder"+Arcana.

### Description

Dress "The Rose of Ristul-Shoulder" has problems when combined with arcana.
-Some elements are duplicated.
-The gold chain on the chest is missing.
-Missing elements/textures that are on the original dress (overlays/bends/patterns)
![image](https://github.com/user-attachments/assets/4f11767a-e029-453c-a741-b2a823f75785)

### Example Match ID

-

**Comment by Astiberon** [comment]
FIXED
![image](https://github.com/user-attachments/assets/4541e368-4ff1-4609-9790-941c2562a5ee)

**Comment by fischakes** [comment]
Thank you for finding and updating the status of this @Astiberon.
