### ISSUE TITLE
Unstable Concoction and Linken Sphere interaction compared to other similar abilities is inconsistant.

### ISSUE THREAD

**Issue by shaileshgarg** [ValveSoftware/Dota2-Gameplay#2026]
### Ability name

Unstable Concoction

### Description

Unstable concoction is a Unit Target Ability that applies Stun and damage in a AOE around the target. Other abilities with similar are Sven's Storm Hammer, Oracle Fortunes End, Lich Frost Blast.

 1. If Unstable concoction is thrown on a target with Linken Sphere, then Linken is triggered on the Unit dealing no damage and no stun on the target(this is expected). But any unit around the target are stunned and receive damage. This is different from other similar abilites, where the unit around the target are not stunned/rooted/slowed and receive no damage.

https://user-images.githubusercontent.com/26450759/183481406-3220c5d3-8909-48b6-8ac2-211a91d69797.mp4

https://user-images.githubusercontent.com/26450759/183481590-1e862bdc-907e-4872-b301-0c5dad8b142d.mp4

https://user-images.githubusercontent.com/26450759/183481592-46056317-86f5-42f6-b88f-ea08f92e256d.mp4

2. The opposite of the above, if Unstable Concoction is thrown on a unit, and the adjacent unit has Linken Sphere, then the Linken is triggered, and it is not stunned. But other similar abilites, do not trigger the linken of the adjacent unit, and they are stunned/Rooted/slowed normally.

https://user-images.githubusercontent.com/26450759/183481831-e5e9877c-e158-45e8-ae22-9738124c5c73.mp4

https://user-images.githubusercontent.com/26450759/183481839-da464056-b9a2-4421-81c4-cf033d104363.mp4

https://user-images.githubusercontent.com/26450759/183481849-23553ae5-18bc-4f6f-b35b-3f9f637fd9c3.mp4

### Example Match ID (and possibly Timestamp)

-

**Comment by commentator24** [comment]
lotus on nearby allies also reflects alch stun. 5 lotus = alche will get hit by 5 stuns 😆

**Comment by shaileshgarg** [comment]
> lotus on nearby allies also reflects alch stun. 5 lotus = alche will get hit by 5 stuns 😆

LoL, can confirm

https://user-images.githubusercontent.com/26450759/183636235-dc5cea60-28c1-48ee-95d9-c1c7b847e655.mp4

**Comment by Farzam2003** [comment]
the reason for that is that the projectile follows you, u cant dodge the stun for example with storm spirit unless you are invulnurable for the whole projectile travel time, but for other stuns like sven all u have to do is actually a quick zip and it will stop chasing u

**Comment by PingwinGrisha** [comment]
It is really annoying bug what in game about half year, when fix?

**Comment by shaileshgarg** [comment]
Not sure if it really is a bug, lion earthspike also behaves the same.
