### ISSUE TITLE
Storm spirit mana cost mana loss reduction from fairy trinket and kaya and sange not working

### ISSUE THREAD

**Issue by HEISEN3ERG** [ValveSoftware/Dota2-Gameplay#20447]
### Item name

Kaya and Sange

### Description

the mana cost/ mana loss reduction doesn't work on storm spirit ball lightning, this is true for fairy trinket as well, It only reduces activation mana for ball lightning not travel distance mana cost

### Example Match ID and Timestamp

doesn't work all the time

**Comment by a100kpm** [comment]
Not a bug, it's one of the first line of the 7.36 patch.
only apply for initial cost.
There is even a small pop up example about ball lightning specifically
