### ISSUE TITLE
Dota Plus required to play? #help needed 

### ISSUE THREAD

**Issue by Navuri** [ValveSoftware/Dota2-Gameplay#20476]
### Description

Hi,

I cannot start a new game because I get the message 'This grid arrangement is only available for DOTA PLUS members'.
I tried using a PS5 controller in Dota2, which did not work, so I disconnected the controller but now I cannot start a new match again. The online guide I used said I had to 'add' the controller support via the ingame console but that did not do anything as far as I can see. However, I am stuck now.

- I am able to play the tutorial (if that helps)
- I am also unable to start a custom (lobby) match.
- I am unable to start a bot match
- I can access the learn and watch sections of the game
- I have deleted and re-installed the game
- When the controller was connected to my pc I entered ' dota_use_controller 1' in the ingame console because the online tutorial gave it as a work-around.
- I don't see a 'ban' anywhere
- My communication score is a happy green smiley.

My guess is that the whole controller issue caused an error in one of the game files, but that's a wild guess.

Can someone help me with this issue? 

### Screenshots

![dotabug2](https://github.com/user-attachments/assets/642c0445-533d-4e3d-822e-b6b55f774e72)
![dotabug](https://github.com/user-attachments/assets/38bf5631-b092-47dd-8fdf-1a40f6f905c2)

**Comment by Aluerie** [comment]
![image](https://github.com/user-attachments/assets/70929030-1682-41c2-aadc-b7196d3c1d51)

**Comment by Navuri** [comment]
> ![image](https://private-user-images.githubusercontent.com/33165440/353772980-70929030-1682-41c2-aadc-b7196d3c1d51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MTgwMzEsIm5iZiI6MTcyMjQxNzczMSwicGF0aCI6Ii8zMzE2NTQ0MC8zNTM3NzI5ODAtNzA5MjkwMzAtMTY4Mi00MWMyLWFhZGMtYjcxOTZkM2MxZDUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDA5MjIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzYTI0Nzk0YmUyNGE3MWNiYjg0YmUzZWIwOTM0MTA0MWIxZGM3Y2MyNjM5ZTE1OWVkYTM1NWNlYzdlMTVmNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VXAeo7LrfUlLyo-DUhtBl6_EQu04n1lYOVxLRYg2FcQ)

This solved the problem. Thank you very much for your reply.
