### ISSUE TITLE
7.37 version: troll warlord skill bug

### ISSUE THREAD

**Issue by DengJiu** [ValveSoftware/Dota2-Gameplay#20499]
### Cosmetic Item Name

nine thousand

### Description

The skill of the troll warrior, Fury of the Berserker, triggers a disabling effect during ranged attacks, causing damage to oneself. At present, we only see that the damage increases with the skill level.

### Example Match ID

Trial Mode

### Screenshots

![屏幕截图 2024-08-01 112654](https://github.com/user-attachments/assets/bcf8f80b-02bc-42c2-bfa5-685d9e7c4035)

**Comment by chrisf-valve** [comment]
Thank you for the bug report! We have just released an update that should resolve this issue.
