### ISSUE TITLE
7.37 Lone druid spirit link doesn't heal bear 

### ISSUE THREAD

**Issue by EbToXx** [ValveSoftware/Dota2-Gameplay#20509]
### Ability name

Spirit Link

### Description

When selecting bear necessities facet, lone druids attack do not heal the bear. It is gamebreaking since the shared lifesteal is the core of the hero.

### Example Match ID (and possibly Timestamp)

demo mode

**Comment by Janexo27** [comment]
Lone druid heals the bear only with "bear with me" facet.

**Comment by EbToXx** [comment]
> Lone druid heals the bear only with "bear with me" facet.

Did not realise he now had 3 talents. My mistake.
