### ISSUE TITLE
Lina: innate in 7.37 does not work at all

### ISSUE THREAD

**Issue by ketchuup** [ValveSoftware/Dota2-Gameplay#20505]
### Ability name

Combustion

### Description

New innate `Combustion` does not deal additional damage.

### `Dragon slave` (3 level) 245 damage (> 150)

`Dragon slave` damage with `Combustion` at level 1:
![Dragon slave damage with Combustion at level 1](https://github.com/user-attachments/assets/b1917028-c424-416c-aa11-7541a1f3d6f8)

`Dragon slave` damage with `Combustion` at level 2:
![Dragon slave damage with Combustion at level 2](https://github.com/user-attachments/assets/ba503811-f843-487b-bf87-1bef701b84ba)

`Dragon slave` damage with `Combustion` at level 3:
![Dragon slave damage with Combustion at level 3](https://github.com/user-attachments/assets/0790da68-9de1-4e24-8a40-2b59f9a7de3c)

`Dragon slave` damage with `Combustion` at level 4:
![Dragon slave damage with Combustion at level 4](https://github.com/user-attachments/assets/8a8c947e-940f-4801-8edf-85f38b34ef0f)

---

### `Dragon slave` (4 level) + `Kaya` = 357.5 damage (> 150)

`Combustion` at level 1:
![Combustion at level 1](https://github.com/user-attachments/assets/55d4802b-3bd7-452c-af61-d975f58b8bbf)

`Combustion` at level 4:
![Combustion at level 4](https://github.com/user-attachments/assets/ce418f24-18ef-4b2a-82fd-fab0fe63c595)

**Note**: I have the same damage without `Fiery soul` leveled up, or with `Fiery soul` at 4 level.

### Example Match ID (and possibly Timestamp)

Demo

**Comment by leparrain777** [comment]
I think you missed this part: "to their allies in a 400 radius" aka, it doesn't do extra single target damage as you have shown.

**Comment by ketchuup** [comment]
@leparrain777 Yes, you are right. My bad. Closing issue.
