### ISSUE TITLE
Phantom Lancer infinity damage

### ISSUE THREAD

**Issue by xekridi** [ValveSoftware/Dota2-Gameplay#20500]
### Ability name

Illusory Armaments (innate)

### Description

Phantom Lancer gains infinity amount of damage after all buffs:
1) Vengeful spirit with talent (+16% base damage)
2) Marci sidekick with talent (+50% base damage)
3) Magnus empower with talent (+50% base damage)  
  The speed of increasing damage can be manipulated with vladimir's offering and gaining any agility\damage
  The damage cycles in int rangez
![image](https://github.com/user-attachments/assets/dedb8217-883b-467f-979d-375828b6b31a)
![image](https://github.com/user-attachments/assets/27ec1ae0-fa78-44ec-9bc8-26a46528725a)
![image](https://github.com/user-attachments/assets/d375cc54-25dd-49c6-97b4-0b888a465d97)

### Example Match ID (and possibly Timestamp)

no

**Comment by chrisf-valve** [comment]
Thank you for the bug report! We have just released an update that should resolve this issue.
