### ISSUE TITLE
Fantasy cards 0 score

### ISSUE THREAD

**Issue by commentator24** [ValveSoftware/Dota2-Gameplay#2050]
4 july xiaoyu showed correctly that the team is not playing that day.
8 aug ghost yield 0 score, but royal played 2 games that day.
9 aug ghost yield 0 score, and team is not playing that day? not sure. 
and bzm - OG played on 8 aug but still counts, and yet quincy crew MSS get 0 score. inconsistent.

so far i know 2 cards yield 0 scores.
Misha - OG
Ghost - royal never give up

![image](https://user-images.githubusercontent.com/109324155/184062588-859f8cde-7b88-4f14-968a-a7cbabd34af0.png)
![image](https://user-images.githubusercontent.com/109324155/184063467-747cc72f-ca14-4e4c-a87b-2ed91bb9d797.png)

**Comment by kacanuna** [comment]
https://i.imgur.com/7ZP77jt.jpg

**Comment by TheUnholyWrath** [comment]
Please close this issue.
