### ISSUE TITLE
PL's new innate Illusory Armaments provides no damage at all

### ISSUE THREAD

**Issue by leparrain777** [ValveSoftware/Dota2-Gameplay#20501]
### Ability name

Illusory Armaments

### Description

Illusory armaments does not grant any base damage in demo mode. In testing a pl at level 30 with 6 divine rapiers shows base damage 1832, and hitting a level 3 huskar dealt just over 160 damage. This damage not existing at all means that illusions don't scale from the facet. I also checked other bonus damage items, and none worked

### Example Match ID (and possibly Timestamp)

N/A

**Comment by chrisf-valve** [comment]
Thanks for the bug report! We have just released an update that addresses this issue.
