### ISSUE TITLE
Windranger - whirldwind facet - focus fire being dispelled/cancelled (spell says it cannot be dispelled)

### ISSUE THREAD

**Issue by NicolasZim** [ValveSoftware/Dota2-Gameplay#20511]
### Ability name

whirldwind focus fire

### Description

The spell focus fire (whirldwind facet) says it cannot be dispelled, however, right after I ulted it finished (like 1 second after) and it went on cooldown. I don't understand if that might be related to being stunned, but it might be the case, Marci used her first spell on me right before this hapenning.

### Example Match ID (and possibly Timestamp)

7875002650 - 10:00 and the next 20 seconds.

**Comment by YashSwaraj** [comment]
Could be you cancelled it by pressing the ult keybind again?

**Comment by NicolasZim** [comment]
@YashSwaraj Yeah that makes sense, I never noticed that you could do that, but they should move that to something else is so easy to cancel it.
Thanks for the heads up.
