### ISSUE TITLE
PL innate doesnt work

### ISSUE THREAD

**Issue by airuhelp** [ValveSoftware/Dota2-Gameplay#20514]
### Ability name

Illusory Armaments

### Description

Bonus damage is only added as a visual indicator to base damage, in fact any bonus damage does not work.

Here is the PL with 3 rapiers, and there is lvl 1 sven, you'd expect PL to oneshot sven with 1.4k damage, but he only does 40  
![image](https://github.com/user-attachments/assets/d0449ada-c806-4b55-811d-b6e8b2e5feeb)

fix pls!

### Example Match ID (and possibly Timestamp)

no timestamp

**Comment by chrisf-valve** [comment]
Thanks for the bug report! We have just released an update that addresses this issue.
