### ISSUE TITLE
Lycan Alpha Wolves not receiving armor bonus mentioned

### ISSUE THREAD

**Issue by Loe151** [ValveSoftware/Dota2-Gameplay#20543]
### Ability name

Summon Wolves

### Description

BUG: The ingame tooltip mentions that the Alpha wolves receive 5/10 armor at levels 5 and 6, but their armor value remains at 0. 
![Alpha Wolves](https://github.com/user-attachments/assets/1f085a1a-554d-4512-aa66-5cdeb011b8be)

### Example Match ID (and possibly Timestamp)

7875094994

**Comment by failure2represent** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/20502
