### ISSUE TITLE
Phylactery and Khanda didn't proc on Tiny's Toss

### ISSUE THREAD

**Issue by ulimtjiatawi** [ValveSoftware/Dota2-Gameplay#20555]
### Item name

Phylactery and Khanda

### Description

Phylactery and Khanda didn't proc on Tiny's toss, tried it with:
1. tossing enemy unit to friendly unit
2. tossing enemy unit to enemy unit
3. tossing enemy unit to itself
4. tossing enemy unit to ground

Phylactery and Khanda do work on tree toss though 

### Example Match ID and Timestamp

7877340737 - 22:22 ; 25:45

**Comment by vivi-lili** [comment]
Phylactery and Khanda procs on the spell's target, not the unit being tossed.
