### ISSUE TITLE
Tiny's prestige item visual bug

### ISSUE THREAD

**Issue by Polykomodo** [ValveSoftware/Dota2-Gameplay#20550]
### Cosmetic Item Name

Majesty of the Colossus/ Sword of the Colossus

### Description

The sword in Tiny's arms is placed wrongly, please fix it.

### Example Match ID

123

### Screenshots

![image](https://github.com/user-attachments/assets/27cab33b-53ea-4288-8567-9c9db3b7e3e3)

**Comment by Astiberon** [comment]
FIXED
