### ISSUE TITLE
Broken Torrent of Kunnka

### ISSUE THREAD

**Issue by Crow6oy** [ValveSoftware/Dota2-Gameplay#2058]
### Description

Hello.  When you press the Torrent button, the Kunkka performs a certain animation with his hands, which clearly lets the enemy know that you have pressed the Torrent, and begins to dodge him not even giving a chance to hit, because the enemy’s movement is completely random.  For example, Pugna's Nether blast, when pressed, plays an attack animation that is then canceled immediately, giving the opponent no understanding of the skill being played.  Could you please change the torrent click animation, because this skill becomes useless until the sixth level. I apologize in advance for the large number of grammatical errors, I do not speak English well.

**Comment by arthurnalves** [comment]
This is not a bug, please close issue.

**Comment by Crow6oy** [comment]
Чурки
