### ISSUE TITLE
Replay rewind function broken?

### ISSUE THREAD

**Issue by commentator24** [ValveSoftware/Dota2-Gameplay#20591]
Not sure if its just me, but pressing rewind 10 seconds might be broken.
Had to stop watching and load replay from main menu again

**Comment by airuhelp** [comment]
if you happen to rewind or go to some other section of replay during the pause, replay will get broken and you'll have to press watch game again, and rewind to the game in order for everything to be fixed.

**Comment by nijbuu** [comment]
Just a video of it
https://github.com/user-attachments/assets/ab8e5306-019e-49d5-b8fe-bc4a568057b9

**Comment by williamBoshi** [comment]
same, I have to reload a lot it's a pain nothing works to unfreeze it
