### ISSUE TITLE
Icon crit phantom assasin

### ISSUE THREAD

**Issue by list1kmerrypaws** [ValveSoftware/Dota2-Gameplay#20646]
### Description

![Безымянный](https://github.com/user-attachments/assets/f3ab46ed-6b77-4076-9537-041348b963b0)
Good afternoon, there is a problem in the game that when the crit is focused, the wrong icon appears on the mortra. 
Everyone I know has a skull icon in focus and in crete, but I have a strange hieroglyph.
This happens exactly on my computer, when I checked on another computer - everything is fine and the skull is displayed. I double-checked the game files on my personal computer, checked the settings - everything is fine. but the hieroglyph is still displayed.
Unfortunately, there is currently no way to make a screenshot from a personal computer, but I am attaching a screenshot of how it actually looks in the game.
![image](https://github.com/user-attachments/assets/c02d081f-9a22-462c-9fc1-e39fa7f953b8)

### Example Match ID (and possibly Timestamp)

no

**Comment by Aluerie** [comment]
`violence_ablood`

**Comment by list1kmerrypaws** [comment]
> `violence_ablood`

I'll check it out today, I'll come back with a solved problem or not. Thank you in advance. I'll leave the topic open for now.
