### ISSUE TITLE
[Visual Bug] Meepo Pack Rat item not showing visually on Meepo clones but working

### ISSUE THREAD

**Issue by gelo0313** [ValveSoftware/Dota2-Gameplay#20834]
### Description

I think the best way I can show this is by sharing my point of view. Here's a short clip of the Meepo clones. You can see that their neutral item slot is empty, but shows the hotkey indicator meaning I can use the active ability of the diffusal blade (which I confirmed) and the passive mana burn is also affecting the neutral creep, so basically this is just a visual bug. 

https://github.com/user-attachments/assets/fcaaf533-5f14-4626-918b-222e0db00199

**Expected result:**

The item equipped neutral item slot in Meepo prime should show in Meepo clone if using the Pack Rat facet. 

### Example Match ID (and possibly Timestamp)

7888410223

**Comment by mirddes** [comment]
#20496 #20616 #20834

**Comment by gelo0313** [comment]
Closing this as duplicate to the other cases commented by mirddes
