### ISSUE TITLE
Bushwack doesn't work on invisible units

### ISSUE THREAD

**Issue by MikioKyo** [ValveSoftware/Dota2-Gameplay#2090]
### Ability name

Bushwack

### Description

The ability doesn't work on invisible targets (although if reveal them it does).

If it is working as intented, can we please add this to ALT description of the ability?

### Example Match ID (and possibly Timestamp)

No need of Match ID

**Comment by TheUnholyWrath** [comment]
This has been fixed. You can close this issue.

**Comment by MikioKyo** [comment]
yep, alt description was added, thanks!
closing the issue now
