### ISSUE TITLE
Silencer Arcane Curse and Last Word Piercing Starbreaker Spell immunity

### ISSUE THREAD

**Issue by MDMith** [ValveSoftware/Dota2-Gameplay#2093]
### Ability name

Starbreaker

### Description

See summary

### Example Match ID (and possibly Timestamp)

6707572944 52:00

**Comment by Fuck-Polytech** [comment]
Starbreaker does not provide any kind of dispel, unlike from other sources of spell immunity-like abilities and items, duh. And without basic (at least) dispel, you will still be affected by Arcane Curse and Last Word's silence. Abilities that do not pierce spell immunity still damages spell-immune units (if they wasn't dispelled) and abilities that partially pierce spell immunity don't deal any damage to spell-immune units (test Jakiro, Venom and Necro interaction with Dawnbreaker, for example). I guess it's just devs laziness.

**Comment by MDMith** [comment]
If an abilities description states that it grants spell immunity, it should act the same as BKB and dispel everything BKB dispels. This is true for Juggernaut's Blade Fury, Lifestealer's Rage, Elder Titan's Aghanim's Astral Spirit, and Legion Commander's and Marci's level 25 talents, all of which do dispel Arcane Curse and Last word. There is no reason why Dawnbreaker's Shard should behave differently.

**Comment by commentator24** [comment]
not a bug.

dawnbreaker shard states "gains MAGIC immunity", which does not dispels.
while spirit breaker shard states "grants SPELL immunity", which dispels like BKB.

it's like saying all pineapples 🍍 should act the same as an apple 🍎 because it has the word apple 🍎 
Juggernaut's Blade Fury, Lifestealer's Rage, Elder Titan's Aghanim's Astral Spirit, and Legion Commander's and Marci's level 25 talents, all of which has 🍎 There is no reason why Dawnbreaker's Shard should behave like 🍍

**Comment by TheZett** [comment]
> not a bug.
> 
> dawnbreaker shard states "gains MAGIC immunity", which does not dispels. while spirit breaker shard states "grants SPELL immunity", which dispels like BKB.
> 
The tooltip is wrong, her shard actually grants her spell immunity (unaffected/untargetable by certain spells), it does not grant her magic immunity (taking zero damage from magical damage).

Her spell immunity not coming with a basic dispel is for balancing reasons, just like Lion’s shard spell immunity does not come with a dispel.

The tooltip uses the wrong wording, but the interaction is intended.

**Comment by commentator24** [comment]
> Same for Lion’s spell immunity, which does not dispel either.
ah i see. would be nice if they use same wording to differentiate immunity that dispels and ones that don't then

**Comment by Fuck-Polytech** [comment]
> > Same for Lion’s spell immunity, which does not dispel either.
> 
> ah i see. would be nice if they use same wording to differentiate immunity that dispels and ones that don't then

Not needed. If an ability applies any dispel, it is written at the bottom of the ability or in the talent (as in the case of Marci's level 25 talent). It's just that there are people who don't know how the ability mechanic works in Dota. Read the Dota wiki, I dunno.
