### ISSUE TITLE
"Immortal" Creep

### ISSUE THREAD

**Issue by eidlin** [ValveSoftware/Dota2-Gameplay#20940]
### Description

The enemy team turn on Glyph of Fortification and it last on one Creep about 1 minute.
we could not do nothing to the creep he was "Immortal" Creep.
It happend in 35:25 at the top tower.

### Example Match ID (and possibly Timestamp)

7894183181- 35:25

### Screenshots

![Invincible creep](https://github.com/user-attachments/assets/fb1b7d5c-7f19-45f3-9736-623ffd30ff58)
![Invincible Creep2](https://github.com/user-attachments/assets/659eb712-ad6e-40d3-9a4f-8053d487ad4a)
![TimeStamp](https://github.com/user-attachments/assets/509fb522-4da1-4b69-9ab0-c4aaa700f096)

**Comment by daMpoff** [comment]
dude, u have roshan banner, open your eyes

**Comment by eidlin** [comment]
Sorry I didn't see it 😕

**Comment by daMpoff** [comment]
> Sorry I didn't see it 😕

not a problem) good luck
