### ISSUE TITLE
Phylactery doesnt work on Omni's Hammer of purity and AA's Chilling touch

### ISSUE THREAD

**Issue by JohnyFlyer** [ValveSoftware/Dota2-Gameplay#20979]
### Item name

Phylactery

### Description

Phylactery's empower spell doesn't work while casting auto spells like hammer of purity or chilling touch after the 7.37 game update. I have not found anything about it shouldnt be working anymore. 

### Example Match ID and Timestamp

7896444284

**Comment by leparrain777** [comment]
None of the other attack modifiers trigger phylactery and they mentioned that it was fully converted into an attack modifier. They didn't explicitly state the interaction, but it isn't a bug.

**Comment by JohnyFlyer** [comment]
oh, ok. Thank you for the answer!
