### ISSUE TITLE
The dpc points standings on Dota2.com site are calculated wrong

### ISSUE THREAD

**Issue by kecewka** [ValveSoftware/Dota2-Gameplay#2100]
### Description

The dpc stadings calculation rounds down the points after penalties. Therefore Outsiders having 1.055 (1 point 55 thousandth's) points less in standings. 
The correct calculation is
`120 + 78 = 198`
`198 - (198 * 0.15) = 168.3`
`168.3 + 20 = 188.3`
`188.3 - (188.3 * 0.15) = 160.055`
`160.055 + 500 = 660.055`
`660.055 + 360 = 1020.055 `

Dota2.com's calculation uses round down (`floor`) function after each penalty.
`120 + 78 = 198`
`198 - (198 * 0.15) = 168.3`
`floor(168.3) = 168` (0.3 points are missed here)
`168 + 20 = 188`
`188 - (188 * 0.15) = 159.8` (additional 0.2055 are missed here) 
`floor(159.8) = 159`
`159 + 500 = 659`
`659 + 360 = 1019`
and 0.5 additional points are missed because 15% deductions were not correctly calucalated because of rounding down
### Example Match ID (and possibly Timestamp)

https://www.dota2.com/esports/ti11/tistandings

**Comment by kecewka** [comment]
@jeffhill @kisak-valve this has made a lot of confusion of whether Outsiders or Fnatic will get invited to the TI

**Comment by TheUnholyWrath** [comment]
Please close this issue.
