### ISSUE TITLE
Invoker 7.37b new talent bug

### ISSUE THREAD

**Issue by fptitsyn** [ValveSoftware/Dota2-Gameplay#21001]
### Ability name

Forge Spirit

### Description

If you choose talent which gives you +1 forge spirit, when you spawn your 3 forges and use the ability again while they are still alive - only 2 original forges die before respawning, meaning that you get 4 forges (more in theory)

### Example Match ID (and possibly Timestamp)

7897206757 - 21:24

**Comment by Dota-Exp** [comment]
issue should be fixed, thank you
