### ISSUE TITLE
Reactive tazer Russian localization mistake

### ISSUE THREAD

**Issue by Avarise831** [ValveSoftware/Dota2-Gameplay#21058]
### Hero and spell

Reactive tazer 

### Description

It haves correct description in english version, but in russian version it is written "attacking hero will get break" but there should be disarm 

![techies](https://github.com/user-attachments/assets/3c2678cd-1100-4581-9753-f7b22668a6b6)

**Comment by Rand0mNicknam3** [comment]
Чет я запутался, а что не так ? Чечка дает 2 скиллом развеивание + бессилие(disarm), на скрине так и написанно вроде
