### ISSUE TITLE
Rewinding paused replay leads to it becoming unplayable.

### ISSUE THREAD

**Issue by IgorHoruzha** [ValveSoftware/Dota2-Gameplay#21080]
### Description

Today, I was watching a replay and encountered an issue with rewinding. If I try to rewind a replay that was paused, the replay becomes unplayable. There are two ways to resolve this: either reopen the replay or create a clip of a replay.

https://github.com/user-attachments/assets/f204482c-7e24-40c4-b9f0-db55a2227e9f

### Example Match ID (and possibly Timestamp)

7871190909

**Comment by ZeroUnderscoreOu** [comment]
Came here to report this issue. Makes watching demos quite annoying.

**Comment by IgorHoruzha** [comment]
The issue is solved.
