### ISSUE TITLE
Aghanim's scepter gifted by Alchemist doesn't work on Vengeful Spirit.

### ISSUE THREAD

**Issue by nebabinda** [ValveSoftware/Dota2-Gameplay#21105]
### Ability name

Vengeance Aura

### Description

Aghanim's gifted to Vengeful Spirit gives the stats but doesn't give  the vengeance aura upgrade that creates a strong illusion after death. Happened 2 times in the same game, then got fixed after disconnect/reconnect. (after DC, both aghs + aghs shard visuals were gone, until used a magic missile to trigger the shard)

### Example Match ID (and possibly Timestamp)

7904234851 - 19:35

**Comment by Aluerie** [comment]
intended, no e

**Comment by nebabinda** [comment]
my bad did not realize E wasn't actually skilled
