### ISSUE TITLE
Flying Courier bug

### ISSUE THREAD

**Issue by Adityal111** [ValveSoftware/Dota2-Gameplay#21102]
When i was playing ranked match i see Flying courier bug at the start of the match, it happens often while ranked games. This can gives game advantage to allies and as well enemy 

Game id:7905434939

![20240820111109_1](https://github.com/user-attachments/assets/95221eaf-2e1f-4c38-b6c7-e8c8d7bb688d)

**Comment by KirbyRedius** [comment]
This is Marcy's innate ability
It gives +3 levels to the team's couriers, which is why apparently they start flying 

Marcy is on your team as I see 😊
