### ISSUE TITLE
The game is CRASHING

### ISSUE THREAD

**Issue by reborone** [ValveSoftware/Dota2-Gameplay#21141]
### Description

after the dota logo appears, the game crashes without error
upd:I tried to enlarge the swap file, delete the bin folder, check the game files in steam, reinstall it..
unsuccessfully.
upd2:the fix is out, but it still crushes
upd3:I changed derectX to vulcan, it doesn't help either

**ALL FIX**

**Comment by Hursofid** [comment]
It's crashing for me too. Not sure what OS you are using, but here's my attempt to run it from shell on debian 11:

`~/.steam/bin/steam-runtime/run.sh /games/steam/steamapps/common/dota\ 2\ beta/game/dota.sh`

And I got it crashed with log:

```
Loaded /games/steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/librenderdoc.so, got (nil)
 failed to dlopen "/games/steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/librenderdoc.so" error=/games/steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/librenderdoc.so: cannot open shared object file: No such file or directory
Loaded librenderdoc.so, got (nil)
 failed to dlopen "librenderdoc.so" error=librenderdoc.so: cannot open shared object file: No such file or directory
double free or corruption (fasttop)
crash_20240823131353_2.dmp[1204031]: Uploading dump (out-of-process)
/tmp/dumps/crash_20240823131353_2.dmp
/games/steam/steamapps/common/dota 2 beta/game/dota.sh: line 122: 1203929 Aborted                 ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
username@hostname:~/.steam/bin/steam-runtime$ crash_20240823131353_2.dmp[1204031]: Finished uploading minidump (out-of-process): success = yes
crash_20240823131353_2.dmp[1204031]: response: CrashID=bp-2cab7132-1479-4387-b600-915852240823
crash_20240823131353_2.dmp[1204031]: file ''/tmp/dumps/crash_20240823131353_2.dmp'', upload yes: ''CrashID=bp-2cab7132-1479-4387-b600-915852240823''
```

I'm quietly not sure whether is this a correct attempt to run it, but at least I've reproduced crash with this attempt.

Here are some last lines from crash dump:

```
12(1.557454):   failed to dlopen libpangoft2-1.0.so error=libpangoft2-1.0.so: cannot open shared object file: No such file or directory
11(1.393339):  Trying to set dxlevel (111) which is higher than the card can support (110)!
10(1.390028):  Attempting to load S
```

P.S. Is dev.dota2.com forum is now closed? I'm getting redirected to issues here.

**Comment by ploiid10** [comment]
it keeps crashing for me as well. Linux mint user here!

**Comment by Svinyaka** [comment]
same on windows 11

**Comment by reborone** [comment]
> Not sure what OS you are using

i use win 10

**Comment by reborone** [comment]
> And I got it crashed with log:

where to find the log?

**Comment by TpsArchyy** [comment]
crashed during a game , using win 10 and is up to date.

**Comment by xchaBBy** [comment]
crashing here as well after startup dota logo. windows 10.

**Comment by reborone** [comment]
fix

**Comment by Hursofid** [comment]
Still crashing, do not close the issue
