### ISSUE TITLE
Ringmaster's illusions have unusual scaling

### ISSUE THREAD

**Issue by rudebear** [ValveSoftware/Dota2-Gameplay#21156]
### Ability name

Dark Carnival Barker - Funhouse Mirror

### Description

When creating an illusion with Funhouse Mirror, the illusion has different sized body parts sometimes. 
![image](https://github.com/user-attachments/assets/6880ac9f-9303-4701-81eb-b9f7721ddf9c) ![image](https://github.com/user-attachments/assets/f0fd8f04-553f-4a2e-b2ef-f1995664fc06) ![image](https://github.com/user-attachments/assets/90052bb8-fbfe-479d-96dd-b788e1731b98) ![image](https://github.com/user-attachments/assets/7cc43a4f-0b40-4d0d-80f2-eaeaf93cc0d1)

Example in attached replay is just above and behind radiant middle tower 

### Example Match ID (and possibly Timestamp)

7909765969 - 18:23

**Comment by justinband** [comment]
From the Funhouse Mirror description found [here](https://www.dota2.com/hero/ringmaster): "Creates 1 **imperfect** image of your hero that lasts ...". See a big head Ringmaster from the same link below:

<img width="273" alt="image" src="https://github.com/user-attachments/assets/eea3dbe6-bb69-4b59-82fe-1a472f1c6ca5">

I believe this is intended.

**Comment by rudebear** [comment]
Ah, my misunderstanding. I thought the imperfect illusion was reference to the reduced damage dealt and increased damage received.
