### ISSUE TITLE
Bingo Tokens Vanished?

### ISSUE THREAD

**Issue by BubonicUK** [ValveSoftware/Dota2-Gameplay#21171]
### Description

I had 36 Bingo points I think it was I used an upgrade for one of the squares and it went to zero..

I bought the the bigger one of the two (50 levels)

**Comment by eugene-valve** [comment]
Hi, this sounds like a bug. Do you mind sharing your account ID so I can look into what happened?

**Comment by eugene-valve** [comment]
Thank you for reporting this bug.

There was an issue where some player's bingo tokens and squares wouldn't get saved properly. This issue has been fixed, and all affected player's missing tokens will be refunded soon.
