### ISSUE TITLE
Fantasy Roster Broken, Can't Choose Players

### ISSUE THREAD

**Issue by jpakdel** [ValveSoftware/Dota2-Gameplay#21245]
### Description

See

https://www.reddit.com/r/DotA2/comments/1f0gcog/why_cant_i_choose_my_fantasy_roster_the_screen_is/
https://www.reddit.com/r/DotA2/comments/1f0k34i/fantasy_roster_broken/

Using a macbook pro OS Sonoma 14.6.1 (23G93)

When I go to open the fantasy roster in the compendium, no players are available to be chosen.

**Comment by chrisf-valve** [comment]
Hello,

A speculative fix has been submitted in addition to some additional debug tracking for if it is still failing. When able, please try to pick a roster again
