### ISSUE TITLE
Smoke Screen applies to teammates and counts as assist 

### ISSUE THREAD

**Issue by karvlad** [ValveSoftware/Dota2-Gameplay#2126]
### Ability name

Smoke Screen

### Description

I'm sorry I did't search this issue properly, there're already 2 posts about it. Is it possible to delete issue?
After the game our Riki had more kill participation count than team's total score (kda 21/5/23 and 43 kills total). After replay check I've noticed that Smoke Screen also applies to teammates and counts as assist for Riki. I recreated it in hero test. It does nothing critical, but messes up with the score.
![image](https://user-images.githubusercontent.com/111394289/184990652-1965c3ed-e505-4ccf-80a2-31fc37c6e42b.png)

Log during 18:00 teamfight: ally Pango gets negative effect Smoke Screen, then loses it, but dies after. That death counted as an assist for Riki.
![image](https://user-images.githubusercontent.com/111394289/184990920-6b9b284b-7be7-4844-93d6-07c6b746aaab.png)

### Example Match ID (and possibly Timestamp)

6710439009,12:00,18:00

**Comment by TheUnholyWrath** [comment]
#83

**Comment by tomadam123** [comment]
Something you do or say to hide something or distract attention  from something. his campaign promises were just a smoke screen https://www.walgreenslistens.me/

**Comment by alexanderchael** [comment]
I am very happy to read about your magnolia market trip. This information is very helpful for the trip and I also know about the site about this. [Check this website](https://quotesmakers.com/kid-quotes/) for more information.

**Comment by TheUnholyWrath** [comment]
This has been fixed. You can close this issue.
