### ISSUE TITLE
Replacement tokens are not issued in the fantasy draft compendium

### ISSUE THREAD

**Issue by ligaapl** [ValveSoftware/Dota2-Gameplay#21380]
### Cosmetic Item Name

Roll Tokens

### Description

I don't get replacement tokens in the "fantasy draft" and "bingo" compendium when I get the level to get them (12, 15 lvls on this time), Steam ID 113184848

### Example Match ID

-

### Screenshots

![Compendium](https://github.com/user-attachments/assets/f6f08ee2-100b-440d-a3bf-54bc929cfdff)

**Comment by ligaapl** [comment]
From 9 lvl i havent get on 12 and 15 lvls in compendium

**Comment by Quequmber** [comment]
Have the same problem not receiving roll tokens

**Comment by Tapa6** [comment]
Same issue, got this on video
https://www.youtube.com/watch?v=Uyl3dWmNtxc

**Comment by ligaapl** [comment]
> Same issue, got this on video https://www.youtube.com/watch?v=Uyl3dWmNtxc

yes, me too, 200% like that
