### ISSUE TITLE
Euls fly time not being reduced for Ursa Enrage Status Resist

### ISSUE THREAD

**Issue by joao-amendola** [ValveSoftware/Dota2-Gameplay#21412]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/):

* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:
Euls fly time is not being reduced by status resistance from Ursa ultimate (which is undispellable)

#### Steps for reproducing this issue:

1.  Ursa R
2.  Use Euls on Ursa with ulti buff
3.  Euls will fly Ursa for full duration (not calculating Status Resistance)

**Comment by cwolff2** [comment]
This is a feature, not a bug. This is a well known attribute to Cyclone from Eul's Scepter, hence why it's popular against Ursa, specifically to hold them in place during their ultimate.
