### ISSUE TITLE
Bingo in the new Compendium

### ISSUE THREAD

**Issue by lexerq** [ValveSoftware/Dota2-Gameplay#21421]
### Description

The bingo of the new compendium does not show the task cells in Russian.

### Screenshots

![29db2c97-e495-4a12-a58b-366bc3617781](https://github.com/user-attachments/assets/4ba65605-7e7b-41e3-a9eb-ee8fc0bad17d)

**Comment by eugene-valve** [comment]
This should be fixed in the latest update, thanks for your report.
