### ISSUE TITLE
Compendium Bingo upgrades gone

### ISSUE THREAD

**Issue by Skamandros** [ValveSoftware/Dota2-Gameplay#21435]
### Description

I bought a level 50 compendium which contains a lot of bingo tokens with which I bought many bingo card upgrades, but now they are all gone as well as the tokens (except for the ones from the last level-up).

Friend ID: 36713485

### Screenshots

![20240828212216_1](https://github.com/user-attachments/assets/3e925c52-bba3-4f10-b890-9d3a48b3c64b)

**Comment by eugene-valve** [comment]
Hi @Skamandros, could you check your bingo card again to verify that the upgrades aren't showing up?

I've confirmed your upgrades were saved and exist in the database, but it's possible that there's a bug preventing them from showing up for you.

**Comment by Skamandros** [comment]
They are still not showing up unfortunately, but I tried upgrading "Gym Rats" with my new tokens and this then shows up.
![20240828231611_1](https://github.com/user-attachments/assets/31dead7b-1c93-4cad-ae1c-40f92e4fb708)

**Comment by eugene-valve** [comment]
Thank you for testing, I am looking into this.

**Comment by eugene-valve** [comment]
There was a bug with the upgrade levels not getting loaded properly, but this should be fixed in an update later today and you'll see your levels again.

Thank you for the detailed bug report.

**Comment by Skamandros** [comment]
I checked it and everything is there now, thank you! :)
