### ISSUE TITLE
Lich Death Charge Range Incorrectly Decreased Post-Update (Expected 1500, now only 900)

### ISSUE THREAD

**Issue by dani-rodr** [ValveSoftware/Dota2-Gameplay#21444]
### Ability name

Death Charge

### Description

Lich Death Charge Range Incorrectly Decreased Post-Update (Expected 1500, now only 900)

![image](https://github.com/user-attachments/assets/cd6eb35b-9519-4447-9466-86774e87ca1c)

### Example Match ID (and possibly Timestamp)

any match

**Comment by cris458carlo** [comment]
Hello,

You are experiencing an issue with the Lich Death Charge range in a game after a recent update. The expected range was 1500, but it’s now only 900. This could be a bug or an unintended change. you might want to report this issue to the game’s support team or check their forums for any announcements or similar reports from other players. They might already be aware of the issue and working on a fix.
