### ISSUE TITLE
Atrophy aura value and cleave fall off faster than expected (but damage seems to be correct)

### ISSUE THREAD

**Issue by colettak** [ValveSoftware/Dota2-Gameplay#21556]
### Ability name

Atrophy Aura (Demon's reach)

### Description

It seems like the value that shows up as the atrophy aura value in the UI is incorrect, which causes the cleave to also be incorrect. It does seem like the damage stays, but you lose the cleave. We can't figure out exactly what causes it. Wondering if it has to do with the stacks persisting beyond death bug. But basically the game gets into a state where the atrophy aura value is incorrect. You can see it in the example ID.

Underlord kills two neutral camps at ~18:20, meaning he should have at least 48 atrophy aura stacks by 19:20, but the value is 4 instead, and there is no visible cleave to him hitting the creeps that spawn at 19:00, either.

### Example Match ID (and possibly Timestamp)

7924874202 (~19:20)

**Comment by florence0239** [comment]
Thanks for providing the details. It sounds like a complex issue with the Atrophy Aura value and cleave. I’ll take a closer look at the match ID and timestamp you shared to see if we can identify the cause of the discrepancy. I appreciate the thorough explanation—this will definitely help in troubleshooting the problem.
