### ISSUE TITLE
TI2024 Compendium - HUD Skin tooltip typo

### ISSUE THREAD

**Issue by wickedplayer494** [ValveSoftware/Dota2-Gameplay#21577]
### Hero and spell

N/A - In the Dashboard

### Description

Within The International 2024 Compendium's Rewards section, hovering over the description for The International 2024 HUD reads "A custom HUD to celebrate this year's **Carival** theme." when it should instead read "A custom HUD to celebrate this year's _**Carnival**_ theme."

### Screenshots

![image](https://github.com/user-attachments/assets/b8fa0b6d-010e-4dea-9ef7-bee7cae032aa)

**Comment by anton-roos** [comment]
Also getting this bug on my side +1

**Comment by wickedplayer494** [comment]
Fixed in ClientVersion 6188, thanks all, and to all, a good night!
![image](https://github.com/user-attachments/assets/772a92eb-d787-4ac6-bc3f-aca434706c63)
