### ISSUE TITLE
Ringmaster not in hero list

### ISSUE THREAD

**Issue by shaunferns1** [ValveSoftware/Dota2-Gameplay#21586]
### Description

hey there my username in dota is {{DarkTroll}} ever since the release of ringmaster i can demo the hero but it not in my hero list to play the hero in any of the games.  basically i cant play the hero at all

### Screenshots

![Screenshot 2024-09-04 144538](https://github.com/user-attachments/assets/b8e1f02c-194c-491f-b146-4d5e930422fe)

**Comment by commentator24** [comment]
just edit the layout and add yourself

**Comment by shaunferns1** [comment]
I appreciate the help it worked thx, feels so simple now and is the 1 thing I didn't try.

**Comment by commentator24** [comment]
glad to help 
you can close the issue then
