### ISSUE TITLE
Cant watch any the international match online in game

### ISSUE THREAD

**Issue by centralnui** [ValveSoftware/Dota2-Gameplay#21582]
### Description

No way to watch any the international game online in game.
Every time I click "watch" button it says "Waiting to watch game" and then I got message "After several attempts to connect, the server did not respond".
![After several attempts to connect, the server did not respond](https://github.com/user-attachments/assets/c6463ac0-01c0-4bf3-b930-65ed1a0c542e)

**Comment by ShallowSoulBL** [comment]
Same problem here!

**Comment by centralnui** [comment]
Seems like they just fixed it. It works for me now, with no PC restart or anything else.
Thanks for your messages.
