### ISSUE TITLE
Doesn't count compendium points for correctly given predictions

### ISSUE THREAD

**Issue by ligaapl** [ValveSoftware/Dota2-Gameplay#21596]
### Cosmetic Item Name

compendium points

### Description

Does not count compendium points for correctly given predictions at the beginning of the game when viewing the game in full. On first screen I was only credited with 6 predictions for watching previous games: liquid - aurora (id 7927914488), falcons - nouns (id 7928100793). And where in dota client full rules for calculating compendium points are described? Developers: where? On second screen 2 another right predictions in second game Liquid - Beastcost (ID match 7928396832), but i take 0 points in compendium for that!
My ID account Dota 113184848

### Example Match ID

7928288761 (liquid - beastcoast 1st game), 7928396832 (liquid - beastcoast 2nd game)

### Screenshots

![compend 2](https://github.com/user-attachments/assets/12714ee7-7caf-4ce8-bdc2-e12551a54b90)
![image](https://github.com/user-attachments/assets/831579fc-2b21-4344-be2e-77b939588187)

**Comment by gowthamang56** [comment]
Yea same problem me too i got 4out 3 correct points not adding to compendium , I pay for compendium

**Comment by ligaapl** [comment]
> Yea same problem me too i got 4out 3 correct points not adding to compendium , I pay for compendium

I think they limited the number of predictions you can get points for to 6 per day, but why it's a great question how and for what we paid 7$ :\
