### ISSUE TITLE
Blank screen with only cursor and background sound

### ISSUE THREAD

**Issue by bluedonut110** [ValveSoftware/Dota2-Gameplay#21592]
After about 2-3 minutes in the menu, screen suddenly turned black with only the dota2 cursor visible and bckground sound. Is this because of the new update? Previously i had no probs! I have done all the tips given online it doesnt work pls help!

**Comment by commentator24** [comment]
curently the main menu automatically play twitch link to dota2ti
you might have issue playing the browser? or maybe graphic card / driver issue
![image](https://github.com/user-attachments/assets/7284391a-845a-4ab3-8a02-b6ae4a01da05)

**Comment by bluedonut110** [comment]
> curently the main menu automatically play twitch link to dota2ti you might have issue playing the browser? or maybe graphic card / driver issue ![image](https://private-user-images.githubusercontent.com/109324155/364487250-7284391a-845a-4ab3-8a02-b6ae4a01da05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MDQyNjMsIm5iZiI6MTcyNTUwMzk2MywicGF0aCI6Ii8xMDkzMjQxNTUvMzY0NDg3MjUwLTcyODQzOTFhLTg0NWEtNGFiMy04YTAyLWI2YWU0YTAxZGEwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNVQwMjM5MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZjgwZTgzM2UzZGMwYWQ3OTBmMmE2ZTMwYTU1ZmFhZDUzNmJmMWNlMzk0MGQzMTNhMmE5MmFkY2M2MDUwZDI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.scVW5fWSPzl8m_47-7lt47NZXUTna3ResQxDRbqwdt0)
> 
> maybe try to open the twitch link with steam browser see if you have issue

Hey man.. thanks it is fixed now. Did what u suggested, open twitch on steam browser.. immediately steam went haywire and crashed. Re-opened steam and i saw dota was downloading some sort of plug in. I restart the pc after download and its good now. Thank you kind sir 😁🙏
