### ISSUE TITLE
Can't Bind § hotkey anymore

### ISSUE THREAD

**Issue by mambo1287** [ValveSoftware/Dota2-Gameplay#21614]
### Description

I have a swedish keyboard and it works correctly when typing ingame, but when it comes to Hotkeys the "§" key is changed to "½" (which is the § key but holding shift).
So one hotkey I have is ½ now, which works. However Alt ½ does not work. Have had § Assigned since I started in 2012, and was now in 2024 that it changed.

![hotkey](https://github.com/user-attachments/assets/ce0c9c87-95de-454a-9304-3f0a31657bd8)
![hotkey2](https://github.com/user-attachments/assets/966ea378-ee07-4b89-b843-48c24bf22b47)

**Comment by commentator24** [comment]
is bind keys based on keyboard position ticked or unticked?

**Comment by mambo1287** [comment]
It was ticked. Unticking it made it work. It does still show ½ instead of §, but my 2nd hotkey with alt+§ "(alt+½)" is working. So problem solved. Thanks
