### ISSUE TITLE
"Endangered Species" Bingo square's requirement increases instead of decreasing, when upgrading

### ISSUE THREAD

**Issue by alincnita** [ValveSoftware/Dota2-Gameplay#21621]
### Description

the way i've noticed the Bingo squares to behave when upgrading is they will lower the requirement needed to complete. 

well, I upgraded my "Endangered Species" card, and it now requires me for 5 couriers to die 10 times instead of 6. that is in no way an upgrade for me, now it's even harder. when upgrading any other cards, they will always lower requirement, so I'm quite sure this is a bug.

### Screenshots

![image](https://github.com/user-attachments/assets/1460272f-4cc0-494c-83ad-d8fd43880dd6)

**Comment by commentator24** [comment]
maybe fixed?
i upgraded mine and it lowers from 7 to 5
![image](https://github.com/user-attachments/assets/a76bee3e-78c1-4575-9f8b-a5edbfcdd706)

**Comment by alincnita** [comment]
> maybe fixed? i upgraded mine and it lowers from 7 to 5 ![image](https://private-user-images.githubusercontent.com/109324155/365337854-a76bee3e-78c1-4575-9f8b-a5edbfcdd706.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2ODA5OTIsIm5iZiI6MTcyNTY4MDY5MiwicGF0aCI6Ii8xMDkzMjQxNTUvMzY1MzM3ODU0LWE3NmJlZTNlLTc4YzEtNDU3NS05ZjhiLWE1ZWRiZmNkZDcwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwN1QwMzQ0NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NTNmMTViZmI5YjNkYjIxYTMwZGI1ODE1NGEyMzkxNjg3ZjA5N2NjN2Q1NzgxYjkwMDQ1N2I0YzI3NmRkYThhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GM2-fLIBkYJLhNXX7cogKCNO1clJ28Yq1t__yBsNlrI)

seems like it was fixed when they also made the bingo challenge easier by nerfing numbers
so, solved

**Comment by alincnita** [comment]
> maybe fixed? i upgraded mine and it lowers from 7 to 5 ![image](https://private-user-images.githubusercontent.com/109324155/365337854-a76bee3e-78c1-4575-9f8b-a5edbfcdd706.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2ODA5OTIsIm5iZiI6MTcyNTY4MDY5MiwicGF0aCI6Ii8xMDkzMjQxNTUvMzY1MzM3ODU0LWE3NmJlZTNlLTc4YzEtNDU3NS05ZjhiLWE1ZWRiZmNkZDcwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwN1QwMzQ0NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NTNmMTViZmI5YjNkYjIxYTMwZGI1ODE1NGEyMzkxNjg3ZjA5N2NjN2Q1NzgxYjkwMDQ1N2I0YzI3NmRkYThhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GM2-fLIBkYJLhNXX7cogKCNO1clJ28Yq1t__yBsNlrI)

seems like it was fixed when they also made the bingo challenge easier by nerfing numbers
so, solved
