### ISSUE TITLE
Fantasy not giving correct points

### ISSUE THREAD

**Issue by alincnita** [ValveSoftware/Dota2-Gameplay#21669]
### Description

my Nisha has around 10,000 points fantasy in his first game of the series against XG, and then around 4,500 in the second one, which should both sum to around 14,500

however, taking also in consideration the war banner, it should be way way higher with all the bonuses my war banner has.
also, Nisha got a RAMPAGE in this series, and also HE HAS 0 DEATHS in 2 GAMES of the series, so how is this even possible? **what does he need to do, re-establish the byzantine empire?** (or, to be more related to him, does he need to re-establish the great polish-lithuanian commonwealth?)

so.... how does my nisha have only 11,375 points total? like there are people having even 35,000 points on their players, so how does my fantasy player, which got a RAMPAGE and died 0 times in both games of the series, and has a decent war banner have 11,000 points...?

again, i will mention it once again, the first game of the series, he ends with around 10,000 points, he gets a rampage, he has 0 deaths. and on the second one, with around 4,500, again 0 deaths. so, therefore, it should be at least 14,500 by default. what is even the point of the "Fantasy Points" function in the spectator mode if it's not correct?????????????

### Example Match ID (and possibly Timestamp)

7933540966 - check Fantasy Points at the end
7933465064 - check Fantasy Points at the end 

### Screenshots

![image](https://github.com/user-attachments/assets/059f1ae0-d232-464b-8f4f-007a23c3f811)

**Comment by extrajexter** [comment]
так вроде фэнтези поинты в игре это другое, они вроде даются за то как он хорошо играет относительно других игроков
