### ISSUE TITLE
Fantasy points

### ISSUE THREAD

**Issue by SuNrEdAkYT** [ValveSoftware/Dota2-Gameplay#21671]
### Description

Yesterday they didn't give fantasy points for my team.

### Screenshots

![20240908123552_1](https://github.com/user-attachments/assets/291ee12b-6b56-4cb9-957a-16bb6ae1659f)
![20240908123602_1](https://github.com/user-attachments/assets/96db9a94-e4e1-4a59-87b2-ff42dfe0497f)

**Comment by extrajexter** [comment]
просто еще не все матчи прошли

**Comment by SuNrEdAkYT** [comment]
> просто еще не все матчи прошли

надеюсь, что так
а когда закончатся матчи?

**Comment by extrajexter** [comment]
> надеюсь, что так а когда закончатся матчи?

я точно не знаю, сам впервые донатил на бп, тк играю около 3к часов, думаю что через 4 дня будут все результаты тк в прошлый раз я смог забрать награду только когда новый раздел фэнтези вышел

**Comment by SuNrEdAkYT** [comment]
> > надеюсь, что так а когда закончатся матчи?
> 
> я точно не знаю, сам впервые донатил на бп, тк играю около 3к часов, думаю что через 4 дня будут все результаты тк в прошлый раз я смог забрать награду только когда новый раздел фэнтези вышел

понял, спасибо
