### ISSUE TITLE
Dota 2 Not Identifying CPU Correctly, FPS Issues

### ISSUE THREAD

**Issue by Zeeeze** [ValveSoftware/Dota2-Gameplay#21694]
### Description

This is an issue I've had since moving to Linux from Windows where it did not exist.

I've had this issue now with two Skylake-X processors (an older one that died and I replaced with a different model and this one) where I get a very low framerate in Dota 2 with low GPU and CPU utilization. I found a launch option that was able to resolve this issue when using my previous CPU (in both Counter Strike and Dota 2), -disable_affinity_preferences, however that launch option is no longer resolving the issue on my replacement which is an older and weaker model. So I began to dig more to try and resolve the issue again.

The thing I noticed while running mangohud and expanding to show all CPU cores, was 100% utilization on a single core, and very low utilization elsewhere as this is a 10 core CPU. I noticed on the older CPU, when running the -disable_affinity_preferences launch command, I had a very uniform distribution of utilization across the CPU of around 20-30% per core, which while not ideal somehow culminated in a good framerate and GPU usage. So I tried another command on the same reddit post, -threads and selected 5 and 9 as arguments, which has once again resulted in a good framerate and good utilization on the new CPU. That post warned about -threads not being ideal to use and so I started digging into the sys_info section of the console where I may have found what I believe to be the issue.

You'll see this in the screenshots, and I am not a game developer and so apologize for any incorrect terminology, but the issue appears to be in Dota's recognition of my CPU hardware and deciding how many threads to use.

In the first screenshot with no launch options, you can see it has correctly identified it as an Intel 7900X, but appears to have incorrectly marked it as having only 1 P core and 6 E cores, while also assigning it a thread pool of 0.

In the second screenshot, you'll see the same in regards to the CPU, but using the -threads 5 launch option has given it a thread pool of 4, and performance in game is fine and/or better than when I was on windows.

All of this to say I hope that this provides value and can be resolved as I don't enjoy using advanced launch options to force game compatibility with my operating system (and especially a native client), and if this issue is more widespread it might explain the significant (from what I've read at least) performance challenges a lot of users are reporting in Dota and Counter Strike when moving to Linux from Windows. Thanks for reading.

### Screenshots

![Screenshot from 2024-09-09 19-39-26](https://github.com/user-attachments/assets/3dc0975d-8c56-45b0-9ba9-c5e86cf9d7cd)
![Screenshot from 2024-09-09 19-50-15](https://github.com/user-attachments/assets/c87c592f-5365-4040-816a-0f3f94c31988)

**Comment by Zeeeze** [comment]
With all due respect, this is a Linux client issue, so completely unrelated to Microsoft and the game is correctly identifying the CPU, so also unrelated to Intel or the BIOS. It just appears to have incorrect logic when deciding what to do with that CPU.

I would be interested to see if Dota is assigning the correct core counts for other users' CPUs based on their sys_info output.

**Comment by Nallefjant** [comment]
It's not the job of the game to identify and utilize the CPU correctly, it's the operating system and layers below. You may write code that says "run these threads", but you don't specify what core to use or when.

**Comment by Zeeeze** [comment]
Agreed with the text suggestion. That is good that yours is correctly allocating threads! This has persisted across Linux kernels 5.15-6.8 for me as well as multiple cpu's and bios's, though all were Skylake-X processors.

I have a friend who is having a similar issue with a Threadripper CPU, but isn't at home right now to grab sys_info. I'm hoping to get more data points on this issue. I think I'll also follow your advice and cross post this to the client issue tracker as well. Thanks!

**Comment by Zeeeze** [comment]
Moved this thread here: https://github.com/ValveSoftware/Dota-2/issues/2814
