### ISSUE TITLE
Compendium Bingo for playoffs too high threshold to complete

### ISSUE THREAD

**Issue by Vench05** [ValveSoftware/Dota2-Gameplay#21726]
### Description

Just like in the group stage, Compendium Bingo for playoffs has too high thresholds to complete but this time its not updating

![image](https://github.com/user-attachments/assets/21a37b1f-637a-4fa1-8fa6-04d503bd53dd)
![image](https://github.com/user-attachments/assets/ee5616c6-8f9b-4a33-987d-b82aed55818a)

### Example Match ID (and possibly Timestamp)

my id: 369744289

### Screenshots

![image](https://github.com/user-attachments/assets/21a37b1f-637a-4fa1-8fa6-04d503bd53dd)
![image](https://github.com/user-attachments/assets/ee5616c6-8f9b-4a33-987d-b82aed55818a)

**Comment by eugene-valve** [comment]
Hi, it's not guaranteed that you can finish every square of your bingo card. The results of your Bingo card are a matter of chance; while upgrading your card greatly increases your chance, some squares may not reach your rolled threshold based on the results of the tournament.

The notification you see there for a fix to too high completion threshold has already been applied to your account, and the thresholds you now see are correct.

**Comment by Vench05** [comment]
@eugene-valve what kind of nonsense you're talking about? Stop guessing
Its clearly high like the group stage before, because they have the same amount of requirement before it updated
right now with 3 upgrade the amount needed is 8 while in group stage after the update its 3 for 1 upgrade

Dont reply if you don't even investigate its to rude and disrespectful, what a bad job you're doing. @eugene-valve re-open it

![image](https://github.com/user-attachments/assets/e4d80828-1420-45e4-a489-e1e6a181efc7)
![image](https://github.com/user-attachments/assets/8185a1da-bfe8-4111-b42c-d92b3809688c)

**Comment by Vench05** [comment]
> Hi, it's not guaranteed that you can finish every square of your bingo card. The results of your Bingo card are a matter of chance; while upgrading your card greatly increases your chance, some squares may not reach your rolled threshold based on the results of the tournament.
> 
> The notification you see there for a fix to too high completion threshold has already been applied to your account, and the thresholds you now see are correct.


@eugene-valve what kind of nonsense you're talking about? Stop guessing
Its clearly high like the group stage before, because they have the same amount of requirement before it updated
right now with 3 upgrade the amount needed is 8 while in group stage after the update its 3 for 1 upgrade

Dont reply if you don't even investigate its to rude and disrespectful, what a bad job you're doing. @eugene-valve re-open it

![image](https://github.com/user-attachments/assets/e4d80828-1420-45e4-a489-e1e6a181efc7)
![image](https://github.com/user-attachments/assets/8185a1da-bfe8-4111-b42c-d92b3809688c)
