### ISSUE TITLE
Can’t wear set Doll of the Dead

### ISSUE THREAD

**Issue by Viktor9710** [ValveSoftware/Dota2-Gameplay#21738]
### Item name

Doll of the Dead

### Description

![photo_5413388509890341120_y](https://github.com/user-attachments/assets/2d3f7269-758d-46f1-bd7c-79ca778396d0)

This set came out of my chest Dead Reckoning Chest . Can’t wear set

### Example Match ID and Timestamp

no match ID

**Comment by IgorHoruzha** [comment]
It is possible that the set is in Bundle, and it is necessary to unbundle it first.
 Could You try to find the bundle in Your inventory, then right click on it then unbundle button, please?
![image](https://github.com/user-attachments/assets/e4e3e625-0f33-4498-90f6-1576b3d53863)

**Comment by commentator24** [comment]
#7992 Need Toy butcher persona as well. 
Doll of dead is useless without toy persona. if you unbundle the set it should include toy persona.
not sure if toy persona needs to be unbundled, but do it. then simply select it during game or change from Heroes tab > pudge > toy persona to use doll of dead. 
![image](https://github.com/user-attachments/assets/0cccd03a-9b1c-451c-9b1f-1cd4dc10ec44)
#21682
#13112
#12646
#12116
#10475
#8763
#8509
#8380
#7875
#7866

**Comment by Viktor9710** [comment]
The item description says that a pudge doll is included, but it was not
provided.

пт, 13 сент. 2024 г., 11:06 commentator24 ***@***.***>:

**Comment by IgorHoruzha** [comment]
>The item description says that a pudge doll is included, but it was not


To get the Persona, it's important to unbundle.
![image](https://github.com/user-attachments/assets/584f5ea7-aad7-4869-8e51-d31e25ccb812)

**Comment by Viktor9710** [comment]
Здравствуйте.
У меня набор распакован. Но куклы нету.

пт, 13 сент. 2024 г. в 20:07, Igor ***@***.***>:

**Comment by IgorHoruzha** [comment]
>Здравствуйте.
У меня набор распакован. Но куклы нету.

Could You try to record a video for example using [Snipping Tool](https://apps.microsoft.com/detail/9mz95kl8mr0l?launch=true&mode=full&hl=en-us&gl=us&ocid=bingwebsearch) or [OBS](https://obsproject.com/), please?

Could You provide Your SteamId?

**Comment by Viktor9710** [comment]
Dota 2 2024-09-15 10-36-12.mp4
<https://drive.google.com/file/d/1TPgUIn8DSUZqsZHs42Dh_cWyvnkxC0HK/view?usp=drive_web>
ID  207776554

вс, 15 сент. 2024 г. в 10:26, Igor ***@***.***>:

**Comment by IgorHoruzha** [comment]
Could You make Your Profile and inventory Public, please?
Could You make the URL public, please?

**Comment by Viktor9710** [comment]
Сделанный.

вс, 15 сент. 2024 г. в 10:47, Igor ***@***.***>:

**Comment by Viktor9710** [comment]
Name is Мафиозник

вс, 15 сент. 2024 г. в 10:53, Виктор Кононенко ***@***.***>:

**Comment by IgorHoruzha** [comment]
>Name is Мафиозник

I see Your point, but there are 11_690 Individuals who have the same Nick name. It would be nice to have an URL to exact account.
![image](https://github.com/user-attachments/assets/3576ad78-2935-4851-83a0-c846f98230de)

**Comment by IgorHoruzha** [comment]
>Сделанный.

Could You send a shared URL please?

**Comment by Viktor9710** [comment]
Steam ID: 76561198168042282

it's him?

вс, 15 сент. 2024 г. в 11:04, Igor ***@***.***>:

**Comment by Viktor9710** [comment]
account   babayoga1

вс, 15 сент. 2024 г. в 11:06, Виктор Кононенко ***@***.***>:

**Comment by IgorHoruzha** [comment]
>babayoga1

Searching by account name is disabled.
![image](https://github.com/user-attachments/assets/a509f9f0-e1cd-4f9f-a91e-c13ba1d0bddb)

**Comment by Viktor9710** [comment]
https://steamcommunity.com/profiles/76561198168042282/

вс, 15 сент. 2024 г. в 11:29, Igor ***@***.***>:

**Comment by IgorHoruzha** [comment]
I have checked Your inventory, currentlу The Toy Butcher was not found in Your inventory.

Could You provide a source of the items using Inventory History, please?
![image](https://github.com/user-attachments/assets/55ca5088-737b-48cd-85ff-ebcdd93ed077)

**Comment by Viktor9710** [comment]
Source Trading Floor

вс, 15 сент. 2024 г. в 12:23, Igor ***@***.***>:

**Comment by IgorHoruzha** [comment]
Have You bought each item separately?

**Comment by Viktor9710** [comment]
Yes, I did.

вс, 15 сент. 2024 г., 12:48 Igor ***@***.***>:

**Comment by IgorHoruzha** [comment]
>Yes, I did.

To wear the set You also need the The Toy Butcher (Pudge persona). The only way to get it now is to Unbundle a bundle that contains it. For example "[Doll of the Dead](https://dota2.fandom.com/wiki/Doll_of_the_Dead)" or "[Frosty the Sew-Man](https://dota2.fandom.com/wiki/Frosty_the_Sew-Man)".

**Comment by IgorHoruzha** [comment]
![image](https://github.com/user-attachments/assets/aec89d34-cdd7-4a68-8411-aa24f73d2770)

**Comment by Viktor9710** [comment]
Thank you

вс, 15 сент. 2024 г. в 13:02, Igor ***@***.***>:

**Comment by IgorHoruzha** [comment]
You are welcome. Could You close the issue, if it is solved, please?
