### ISSUE TITLE
Map bug

### ISSUE THREAD

**Issue by aramirezm89** [ValveSoftware/Dota2-Gameplay#21730]
### Description

I have problems with the map, I dont know what happend with the ground, I can't see it

### Screenshots

<img width="1280" alt="Captura de pantalla 2024-09-12 123911" src="https://github.com/user-attachments/assets/cb7f3cea-5fcc-4ef6-9e9e-4daa6f661ba3">

**Comment by aramirezm89** [comment]
<img width="1280" alt="image" src="https://github.com/user-attachments/assets/4aeb6259-7df4-4004-bd8c-4be225d9bf50">

**Comment by IgorHoruzha** [comment]
Could You provide a video with steps were made that lead to the issue, please?

**Comment by aramirezm89** [comment]
I'm only executing the game like always, yesterday I began to have this problem, I dont think you need a video beacuse only I'm executing the game normaly and like always

**Comment by IgorHoruzha** [comment]
>I'm only executing the game like always, yesterday I began to have this problem, I dont think you need a video beacuse only I'm executing the game normaly and like always

Each detail may be useful to find in research, the nice that video usually has a lot of data itself on each frame.

As for now with data I have from text and images, I can recommend You update drivers, check RAM using [memtest86+](https://en.wikipedia.org/wiki/MemTest86), make some stress test to CPU and GPU Using Cinebench, Furmark  or Intel Extreme Tuning Utility .  Also reinstall Dota 2, Steam, Windows. 

But the reason in not clearly known. The more data provided the higher chances to find the reason.

**Comment by commentator24** [comment]
it looks like terrain bug. only terrain is not loading? maybe directX driver/rendering issue? what directx are you using and did you update windows recently? 

if you have older hardwares or outdated graphic drivers you may need to set to specific -dxlevel in launch options for compatibility. i think currently dota use directx11 and you may have issue after recent patches
#11594 e.g. try put -dxlevel 80 in launch options

if that doesnt work provide more info, like what terrain, map effects, weather effects you use. also screenshot your graphic settings. you can also open console to see what resources not loaded properly, usually in red text e.g. my console errors #15041

**Comment by IgorHoruzha** [comment]
>it looks like terrain bug. only terrain is not loading?

I see Your point, it may also be useful to try different or default terrain.

**Comment by aramirezm89** [comment]
Yeah, yesterday I update windows, and for some reason Nvidia misconfigured, I hadn't notice of it until I try to open Nvidia control panel and I had an error to open it, then I re install the Nvidia's  drivers and everything is ok right now with the game

**Comment by commentator24** [comment]
glad to help, you can close the issue then
