### ISSUE TITLE
Bots no longer use their ults

### ISSUE THREAD

**Issue by dino572** [ValveSoftware/Dota2-Gameplay#21768]
### Description

Since few months back, bots cannot use their ults. Literally all bots.

### Example Match ID (and possibly Timestamp)

7942327557

**Comment by IgorHoruzha** [comment]
Hello, which bots do You usually use to play with?

**Comment by dino572** [comment]
Sorry, I realized that this bug concerns RMMAI, not the default bots. I will close this thread.
