### ISSUE TITLE
Lone Druid Beer Necessities

### ISSUE THREAD

**Issue by kokotzlesa** [ValveSoftware/Dota2-Gameplay#21775]
### Ability name

Beer Necessities

### Description

evasion is multiplied by passive skill Beer Necessities, Talisman of evasion = 33% , but slow resist is not multiplied
![1](https://github.com/user-attachments/assets/4b66ae81-1006-4980-841a-976312d963fc)

### Example Match ID (and possibly Timestamp)

NA

**Comment by Aluerie** [comment]
![image](https://github.com/user-attachments/assets/f94785bd-93a6-445b-a7a5-bbb5e83312e6)
