### ISSUE TITLE
Kill goes to Zeus which is on other lane farming

### ISSUE THREAD

**Issue by ubrits** [ValveSoftware/Dota2-Gameplay#2179]
Match ID: 6716830340
Min: 3:00 - 3:20

Zeus uses ulti on mid lane min 3:05
I hooked Ancient Apparition on min 3:15

Only ME and the TOWER hit the player and the kill goes to ZEUS.......?!

Best regards

**Comment by TheUnholyWrath** [comment]
![20220821123602_1](https://user-images.githubusercontent.com/46859977/185772889-597fbe31-2d64-4bd7-bc1a-f0bf7cc1e99f.jpg)
The tower got the last hit. There is no bug here, please close this

**Comment by ubrits** [comment]
No bug
