### ISSUE TITLE
Clicking the scan icon to use it does not work 

### ISSUE THREAD

**Issue by kingcrimson43** [ValveSoftware/Dota2-Gameplay#218]
### Description

When you click the scan icon in the lower left you sometimes have to click it up to 3 times before it will register and allow you to scan.

**Comment by judge2020** [comment]
Can you replicate this? Can't reproduce this behavior myself and I haven't had this issue before.

**Comment by NMOTH** [comment]
can you provide screen recording of this issue? Because I can't replicate and have never had this issue.
