### ISSUE TITLE
Cannot connect to any match

### ISSUE THREAD

**Issue by persannn** [ValveSoftware/Dota2-Gameplay#21827]
### Description

Each time I try to connect to a game, I get to the screen where the smoke animation starts rolling, the 10 rectangles for players are in place, chat window is also in place. But that's where it ends, I get disconnected from the server, without ever seeing other player's names. I get the message shown in the screenshot and a timeout. This has happened the last 8 times I tried to queue a game.

### Screenshots

![image](https://github.com/user-attachments/assets/a0fd266b-ec05-4693-bca5-566c1c4ba72c)

**Comment by Avarise831** [comment]
map_enable_portrait_worlds 0  try this in console

**Comment by persannn** [comment]
Nevermind,  a fresh install of Dota fixed this issue. I'm stupid for not trying that earlier.

**Comment by persannn** [comment]
No issues anymore
