### ISSUE TITLE
international 2024 fantasy percentile throphy not updated

### ISSUE THREAD

**Issue by chymi01** [ValveSoftware/Dota2-Gameplay#21852]
### Description

the international is over but the international 2024 fantasy percentile throphy not updated still at level 1

### Screenshots

the international is over but the international 2024 fantasy percentile throphy not updated still at level 1
![1 t](https://github.com/user-attachments/assets/5a377ade-6f5b-469a-843e-36f98262106c)
![2 t](https://github.com/user-attachments/assets/bc37f3f9-b40d-4b4e-b3d1-d6485d6584f6)

**Comment by commentator24** [comment]
wow how did you get 99% can you reveal what you got? wp aha

**Comment by cbq1232006** [comment]
same issue, the trophy is still not updated.

**Comment by chymi01** [comment]
> wow how did you get 99% can you reveal what you got? wp aha
my pick :) falcons, BB , Liquid
![f1](https://github.com/user-attachments/assets/fb0c4173-b0fe-4b81-83f8-f928cafc20b4)

**Comment by chymi01** [comment]
fixed problem

**Comment by chymi01** [comment]
fixed
