### ISSUE TITLE
I can't get the reward because of an error

### ISSUE THREAD

**Issue by bosinkiller666** [ValveSoftware/Dota2-Gameplay#21857]
### Description

all the shops are open but the candy bins haven't opened

### Screenshots

![Снимок экрана 2024-09-18 153214](https://github.com/user-attachments/assets/f74e4866-2d46-4df7-b3ca-dba32a5033eb)
![Снимок экрана 2024-09-18 153159](https://github.com/user-attachments/assets/ffc0bd47-1066-4db8-89a8-01860309c7c1)
![Снимок экрана 2024-09-18 153136](https://github.com/user-attachments/assets/fcc9c7c1-6772-4848-8aad-0d52bab333e8)
![Снимок экрана 2024-09-18 153126](https://github.com/user-attachments/assets/8a8c6f38-33ad-4ee2-97dd-ab5c468ab323)

**Comment by IgorHoruzha** [comment]
>all the shops are open but the candy bins haven't opened

Act 4 is coming, and I suppose the candy bins will be opened in that act.
