### ISSUE TITLE
Darkening the screen

### ISSUE THREAD

**Issue by Stealinski** [ValveSoftware/Dota2-Gameplay#21889]
### Description

Two seconds after the start of the match, the screen darkens like this, checking the files did not give anything, the steam shows that everything is fine. It helps to solve problems only by re-entering the match

### Screenshots

![image](https://github.com/user-attachments/assets/5b4e04f9-8b6b-4011-b117-da7909aa68ba)

**Comment by commentator24** [comment]
#21809 rendering issue? what direct x are you using

**Comment by Stealinski** [comment]
dx 11

**Comment by Stealinski** [comment]
if I launch using vulkan, the game just crashes at the very beginning
