### ISSUE TITLE
Dota2 Matchmaking System

### ISSUE THREAD

**Issue by JoaoPedro1304** [ValveSoftware/Dota2-Gameplay#21891]
### Description

your system is ridiculous, whenever someone wins a lot of games in a row, very horrible players start to fall into our team so that we have a drop in mmr, that is, defeats in a row, don't know if it's because you guys payd badly there at valve or are physically abused who do this to ruin the gameplay of Dota players, idiot fats

### Example Match ID (and possibly Timestamp)

7951531820

**Comment by IgorHoruzha** [comment]
#17396 Related issue

**Comment by IgorHoruzha** [comment]
Could You please share Your point of view and suggest any actions that might be helpful?

![image](https://github.com/user-attachments/assets/97cfbe01-2995-41e5-968c-edd6805da3e9)

**Comment by JoaoPedro1304** [comment]
Your Matchmaking system is very bad, every time that i win games in a row yout system automatically will put bad, worst and toxic player in my team, and have a lot of topics talking about that in redit, and this system continuous the same, this is ridiculous. Even if I play very well the system is designed for me to lose, putting very bad players on my team and normal players on the other, I went up from archon 1 to legend 1 in 2 weeks and after that very toxic and bad players started to fall on my team, making me lose and return to Archon 3 and there's no point in saying that this was a coincidence, because many players complain about the same thing and we all know that the matchmaking system does this on purpose, you are making the Dota community very worse
[Community Verified icon]



________________________________
De: Igor ***@***.***>
Enviado: domingo, 22 de setembro de 2024 09:01
Para: ValveSoftware/Dota2-Gameplay ***@***.***>
Cc: João Pedro Assis ***@***.***>; Author ***@***.***>
Assunto: Re: [ValveSoftware/Dota2-Gameplay] Dota2 Matchmaking System (Issue #21891)


Could You please share Your point of view and suggest any actions that might be helpful?

image.png (view on web)<https://github.com/user-attachments/assets/97cfbe01-2995-41e5-968c-edd6805da3e9>

**Comment by JoaoPedro1304** [comment]
Yes i have dota+ and the same way, every time that i win some games in a row or upgrade a star on my medal even using dota+ queue again feature this shit happens, guys with the same medal in both teams but a big gameplay diferrence, they seems like herolds with a bad game play and bad behaviour, this system is made to make you lose when you win games in a row or your performance is above average, is that because valve can't controll the smurfs and boosters ?
________________________________
De: Igor ***@***.***>
Enviado: segunda-feira, 23 de setembro de 2024 18:30
Para: ValveSoftware/Dota2-Gameplay ***@***.***>
Cc: João Pedro Assis ***@***.***>; Author ***@***.***>
Assunto: Re: [ValveSoftware/Dota2-Gameplay] Dota2 Matchmaking System (Issue #21891)


Your Matchmaking system is very bad, every time that i win games in a row yout system automatically will put bad, worst and toxic player in my team, and have a lot of topics talking about that in redit, and this system continuous the same, this is ridiculous. Even if I play very well the system is designed for me to lose, putting very bad players on my team and normal players on the other, I went up from archon 1 to legend 1 in 2 weeks and after that very toxic and bad players started to fall on my team, making me lose and return to Archon 3 and there's no point in saying that this was a coincidence, because many players complain about the same thing and we all know that the matchmaking system does this on purpose, you are making the Dota community very worse

Have You tried Dota+ Queue Again feature?

**Comment by IgorHoruzha** [comment]
>smurfs and boosters

Smurfs and boosters usually play in a separate pool. Like this one #20423 or #21906 . If You see any. It makes sense to report them to reduce the time needed to switch them to the appropriate pool.

Interesting, I see Your point. I checked Legion Commander’s (LC) profile, and it seems his average win rate on LC is about 48%, with only 25 games played on that hero. He didn’t pick his main hero, which may explain his performance.
![image](https://github.com/user-attachments/assets/0842fcae-933c-4962-a47f-9ca1a2b065d3)


Just look at his stats—he has a 75% win rate on Terrorblade and other heroes with 50%+ win rates and more games won. If he had chosen his main hero, his performance and playstyle could have been significantly different.
![image](https://github.com/user-attachments/assets/1a346c23-00bd-4f28-b106-820e326ba2f4)

**Comment by JoaoPedro1304** [comment]
Rlx, i am already find some smurf friends and we will close party to stomp pub players, because enhance mmr playing solo with this matchmaking system that makes you lose puting worst palyers with low winrate in my team to balance 50/50 winrate is ridiculous. Valve's systems have always been horrible, both vac which is one of the worst anti cheats in existence and dota's mm systems, valve only cares about money that's why they're losing audiences in dota and cs2, sad!

________________________________
De: Igor ***@***.***>
Enviado: terça-feira, 24 de setembro de 2024 08:42
Para: ValveSoftware/Dota2-Gameplay ***@***.***>
Cc: João Pedro Assis ***@***.***>; Author ***@***.***>
Assunto: Re: [ValveSoftware/Dota2-Gameplay] Dota2 Matchmaking System (Issue #21891)


smurfs and boosters

Smurfs and boosters usually play in a separate pool. Like this one #20423<https://github.com/ValveSoftware/Dota2-Gameplay/issues/20423> or #21906<https://github.com/ValveSoftware/Dota2-Gameplay/issues/21906> . If You see any. It makes sense to report them to reduce the time needed to switch them to the appropriate pool.

Interesting, I see Your point. I checked Legion Commander’s (LC) profile, and it seems his average win rate on LC is about 48%, with only 25 games played on that hero. He didn’t pick his main hero, which may explain his performance.
image.png (view on web)<https://github.com/user-attachments/assets/0842fcae-933c-4962-a47f-9ca1a2b065d3>

Just look at his stats—he has a 75% win rate on Terrorblade and other heroes with 50%+ win rates and more games won. If he had chosen his main hero, his performance and playstyle could have been significantly different.
image.png (view on web)<https://github.com/user-attachments/assets/1a346c23-00bd-4f28-b106-820e326ba2f4>
