### ISSUE TITLE
Unusual Bloomjewel Brawler - Back (Smoke)  absence of smoke

### ISSUE THREAD

**Issue by czzey** [ValveSoftware/Dota2-Gameplay#21890]
### Cosmetic Item Name

Unusual Bloomjewel Brawler - Back (Smoke)

### Description

**Good evening dear Dota 2 developers.**

Today I want to report a bug with my Marci cosmetic in the game, today I made the purchase of this, also to know if I missed adding the effects of the unusuals on the screen of both teams at the end of a game where you can see the cosmetics of the allies and opponents.

**"The main thing in this report for now is about the purchased cosmetic / Unusual Bloomjewel Brawler - Back / Smoke Unusual"**

It is known that the cosmetic when equipped releases its pink smoke correctly, however, the hero (Marci) in the game lobby or when playing a game does the following:

**//LOBBY HERO//:**

-When turning my hero with the mouse wheel the smoke disappears and becomes like an aura that concentrates on the edges of the cosmetic, making the smoke disappear.
-When the hero is not rotated, his smoke moves away from the cosmetic, meaning sometimes it concentrates on a single part of the hero like the feet, the head, or even moves away from the hero model appearing behind it and not surrounding the main cosmetic as it should be.

**//IN THE GAME//:**

-When starting the confrontation loading screen, my hero appears correctly but with the smoke errors that I mentioned that occur almost continuously in the lobby (smoke appears everywhere). It happens with all the Confrontation Loading Screens, so I think it is more of a cosmetic error.

-When starting the Game, the smoke from the animation does appear on my hero (marci) correctly, however on the hero model the smoke does not appear as I saw in videos of other people who had it, so I am very sorry that it does not appear as it should.

**//ITEM LABEL NAME OR DESCRIPTION//**

-When I noticed these bugs happening I tried to change the name of the cosmetic in case it fixed it, however its gem that used to be on the cosmetic next to the orders disappeared but was no longer visible.

But its effect is still active, with the bugs.
-In light of this report, please I would love it if when you fix it you could add a little more color to the cosmetic in general or have more smoke in the game when we are in the middle of a game.

I saw videos of people who also had it and I see that the effects are somewhat noticeable when playing with the hero since like every hero model the model is in constant movement so the smoke disperses a lot.

-In my case I can't enjoy it even as it is currently, since due to the error that my cosmetic has I feel sad for not being able to enjoy the item like in other people's videos.

**-This is my steam profile in case you need to see the problem in more depth. ( https://steamcommunity.com/id/czzey/ )

-I hope you understand me and can find a solution to my problem. Thank you very much.**

### Example Match ID

7952387852

### Screenshots

![image](https://github.com/user-attachments/assets/a1246788-a980-40cb-82e0-a48379b2b025)
![image](https://github.com/user-attachments/assets/0496698a-ab70-4b1d-a9a2-5d29b76c2ac5)
![image](https://github.com/user-attachments/assets/38c121dc-c397-4396-9b9c-fbaeb74c01d0)
![image](https://github.com/user-attachments/assets/0b5f559f-0f18-4b92-9d19-32badf2ab509)
![image](https://github.com/user-attachments/assets/b4eea927-903f-44cf-9ed8-d7799d41b6eb)
![image](https://github.com/user-attachments/assets/b33679fd-b917-4a62-b328-8166ae95c058)
![image](https://github.com/user-attachments/assets/ba2aa836-6f68-4595-9dfc-1e7188472a9d)
![image](https://github.com/user-attachments/assets/897e91d8-b7c6-4d66-a42c-45bc03642935)

**Comment by czzey** [comment]
> ### Cosmetic Item Name
> Unusual Bloomjewel Brawler - Back (Smoke)
> 
> ### Description
> **Good evening dear Dota 2 developers.**
> 
> Today I want to report a bug with my Marci cosmetic in the game, today I made the purchase of this, also to know if I missed adding the effects of the unusuals on the screen of both teams at the end of a game where you can see the cosmetics of the allies and opponents.
> 
> **"The main thing in this report for now is about the purchased cosmetic / Unusual Bloomjewel Brawler - Back / Smoke Unusual"**
> 
> It is known that the cosmetic when equipped releases its pink smoke correctly, however, the hero (Marci) in the game lobby or when playing a game does the following:
> 
> **//LOBBY HERO//:**
> 
> -When turning my hero with the mouse wheel the smoke disappears and becomes like an aura that concentrates on the edges of the cosmetic, making the smoke disappear. -When the hero is not rotated, his smoke moves away from the cosmetic, meaning sometimes it concentrates on a single part of the hero like the feet, the head, or even moves away from the hero model appearing behind it and not surrounding the main cosmetic as it should be.
> 
> **//IN THE GAME//:**
> 
> -When starting the confrontation loading screen, my hero appears correctly but with the smoke errors that I mentioned that occur almost continuously in the lobby (smoke appears everywhere). It happens with all the Confrontation Loading Screens, so I think it is more of a cosmetic error.
> 
> -When starting the Game, the smoke from the animation does appear on my hero (marci) correctly, however on the hero model the smoke does not appear as I saw in videos of other people who had it, so I am very sorry that it does not appear as it should.
> 
> **//ITEM LABEL NAME OR DESCRIPTION//**
> 
> -When I noticed these bugs happening I tried to change the name of the cosmetic in case it fixed it, however its gem that used to be on the cosmetic next to the orders disappeared but was no longer visible.
> 
> But its effect is still active, with the bugs. -In light of this report, please I would love it if when you fix it you could add a little more color to the cosmetic in general or have more smoke in the game when we are in the middle of a game.
> 
> I saw videos of people who also had it and I see that the effects are somewhat noticeable when playing with the hero since like every hero model the model is in constant movement so the smoke disperses a lot.
> 
> -In my case I can't enjoy it even as it is currently, since due to the error that my cosmetic has I feel sad for not being able to enjoy the item like in other people's videos.
> 
> **-This is my steam profile in case you need to see the problem in more depth. ( https://steamcommunity.com/id/czzey/ )
> 
> -I hope you understand me and can find a solution to my problem. Thank you very much.**
> 
> ### Example Match ID
> 7952387852
> 
> ### Screenshots
> ![image](https://private-user-images.githubusercontent.com/182302512/369589784-a1246788-a980-40cb-82e0-a48379b2b025.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNTg5MjQsIm5iZiI6MTcyNzA1ODYyNCwicGF0aCI6Ii8xODIzMDI1MTIvMzY5NTg5Nzg0LWExMjQ2Nzg4LWE5ODAtNDBjYi04MmUwLWE0ODM3OWIyYjAyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QwMjMwMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MjZkN2RkYzg5NGQ0ZDNhNTgyZGZhMTgwZTg2NGI0OGY1Y2YxMWRiN2ZhMGVlYTg5Zjk0NjVlMjM5MzVlMTliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.YV50wxydol_XuiUJTghjRthUusSR64qOuNzChxraHAY) ![image](https://private-user-images.githubusercontent.com/182302512/369589800-0496698a-ab70-4b1d-a9a2-5d29b76c2ac5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNTg5MjQsIm5iZiI6MTcyNzA1ODYyNCwicGF0aCI6Ii8xODIzMDI1MTIvMzY5NTg5ODAwLTA0OTY2OThhLWFiNzAtNGIxZC1hOWEyLTVkMjliNzZjMmFjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QwMjMwMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZjliNjY4OWU4ODVlMWQ1OGVlN2UzMGNlMjFjNGM0YmFlYTJhNmNhYzI3YWM3NTliNmFmOTBhMTY3ZjU1YjgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.A1o5C40OFaDhJSANGG9RE2PnKXjsG7sAL4Kd3CuT_rw) ![image](https://private-user-images.githubusercontent.com/182302512/369589808-38c121dc-c397-4396-9b9c-fbaeb74c01d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNTg5MjQsIm5iZiI6MTcyNzA1ODYyNCwicGF0aCI6Ii8xODIzMDI1MTIvMzY5NTg5ODA4LTM4YzEyMWRjLWMzOTctNDM5Ni05YjljLWZiYWViNzRjMDFkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QwMjMwMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNTQxZDA4ZWFiNjc0MjcwYzQ5ZWFiZWVlMjQ3YzAzMmI0OGMzZjFiZmZmZTJhMzQ5OThiY2Q5YmY3OTNkYTExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.n8ctLVT-GBSEdP5-72BNz9zhB97INYf8CFmbNLrQLXw) ![image](https://private-user-images.githubusercontent.com/182302512/369589815-0b5f559f-0f18-4b92-9d19-32badf2ab509.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNTg5MjQsIm5iZiI6MTcyNzA1ODYyNCwicGF0aCI6Ii8xODIzMDI1MTIvMzY5NTg5ODE1LTBiNWY1NTlmLTBmMTgtNGI5Mi05ZDE5LTMyYmFkZjJhYjUwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QwMjMwMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZWM0MDU0YWNmMWVhYzkyMjQwNTY2YzBkNjNhOWFkMDkzNGRlZmRkMDhjMDQ1Y2Y1ODkxMGZjZTgyOThiMjNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.HahjloHirSTRiLRhmHzIzAImgD-BvMs85GH_KrRFnEw) ![image](https://private-user-images.githubusercontent.com/182302512/369589825-b4eea927-903f-44cf-9ed8-d7799d41b6eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNTg5MjQsIm5iZiI6MTcyNzA1ODYyNCwicGF0aCI6Ii8xODIzMDI1MTIvMzY5NTg5ODI1LWI0ZWVhOTI3LTkwM2YtNDRjZi05ZWQ4LWQ3Nzk5ZDQxYjZlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QwMjMwMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYjM2OTNlYmQ1ZWMxN2RmN2RjYmQ5ODIxZWQxYzEwNmVkNzQ5ZGI2YjRiNDBhMjQ1OTQ1ZTEwOWVhZjM0MDdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.yFyVVC0WtWg6JTk3rOE0K_Mqnx08X68piiyJhxe1VFs) ![image](https://private-user-images.githubusercontent.com/182302512/369589842-b33679fd-b917-4a62-b328-8166ae95c058.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNTg5MjQsIm5iZiI6MTcyNzA1ODYyNCwicGF0aCI6Ii8xODIzMDI1MTIvMzY5NTg5ODQyLWIzMzY3OWZkLWI5MTctNGE2Mi1iMzI4LTgxNjZhZTk1YzA1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QwMjMwMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZDcwMDQ2NGQ5MTI3MDhiYThjZTZlNjhjNzFhYjhiZGYyMDc2ZGE4NTkyM2M0ODEyOTlkMzBmNTY4N2ExYWIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Rgbc9DfcRtSqrUf_Q26ANMNPO2f89lnqcuSHshH_R4g) ![image](https://private-user-images.githubusercontent.com/182302512/369589853-ba2aa836-6f68-4595-9dfc-1e7188472a9d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNTg5MjQsIm5iZiI6MTcyNzA1ODYyNCwicGF0aCI6Ii8xODIzMDI1MTIvMzY5NTg5ODUzLWJhMmFhODM2LTZmNjgtNDU5NS05ZGZjLTFlNzE4ODQ3MmE5ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QwMjMwMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Mjc2NGMwNjJmZTZjNWU1MzhhZDg1MDljNGQ4YzZjYmYzNmE1ZjUyMjRiZWVkM2NmNDAzZTAwNDhjZWFmNDU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.K7nrbvZJjEsZes41BDjGuu-b7uhOyybz3AINv2R1z8Q) ![image](https://private-user-images.githubusercontent.com/182302512/369589866-897e91d8-b7c6-4d66-a42c-45bc03642935.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNTg5MjQsIm5iZiI6MTcyNzA1ODYyNCwicGF0aCI6Ii8xODIzMDI1MTIvMzY5NTg5ODY2LTg5N2U5MWQ4LWI3YzYtNGQ2Ni1hNDJjLTQ1YmMwMzY0MjkzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QwMjMwMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04M2YyMmExMzNlZDAwOGZhYmQ0NjUwMTM5NjYyMzYxNDc0YzE4MWQwYmMxZjBjOTUwMjU1ZThlZjRhMDU0MWM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.91oVI2T_wh_LBf6vEPwEUlPrGZoBBbeKDBjyJETPbuw)

**Comment by Hujikuio** [comment]
@czzey was this fixed?
