### ISSUE TITLE
Enemy heroes in demo hero mode don't have ability cooldowns, manacost or coloured abilities when skilled

### ISSUE THREAD

**Issue by EugeneGGHQ** [ValveSoftware/Dota2-Gameplay#2201]
### Description

Noticed when wanting to try something in hero demo mode - To replicate:

Load Dota > Heroes > Centaur Warrunner Demo Hero > Spawn Underlord > +Enemy > Skill Firestorm > Cast Firestorm

Expected behaviour:
Ability would be coloured and given a manacost attribute, and when cast given countdown timer

Actual behaviour:
Ability remains greyed out, and no mana indication or indication that the skill has been learned. 

### Screenshots

![demohero](https://user-images.githubusercontent.com/60108700/185908084-3402cd91-7e6b-429a-9c20-8d7645b94f56.PNG)

**Comment by WibWabWubWeb** [comment]
That's because Underlord is an enemy. You can't see what spells an enemy has skilled or it's cooldowns. This is working as expected.
