### ISSUE TITLE
Hero did not get banned after both teams picked it

### ISSUE THREAD

**Issue by Victov** [ValveSoftware/Dota2-Gameplay#22024]
### Description

Both teams picked pudge, but the enemy managed to get the hero picked anyway. See the chatbox in the screenshot

https://www.dotabuff.com/matches/7963410088

### Screenshots

![image](https://github.com/user-attachments/assets/39231d12-c613-43f7-af93-54ccbb96c1b0)

**Comment by Aluerie** [comment]
intended per unnamed/undocumented patch a day after 725c ; 

You can check https://liquipedia.net/dota2/index.php?title=Game_Modes#Ranked_All_Pick they documented it pretty well.

In nutshell, double pick ban can only occur twice otherwise there is a malicious hostage possibility.

**Comment by Victov** [comment]
Well yeah there was definitely a hostage situation. Pudges always hold you hostage from having fun. Oh well, I guess if it's intended behaviour I'll close the ticket.
