### ISSUE TITLE
Crown fall collector 2 cant be gifted

### ISSUE THREAD

**Issue by chanjane4514012** [ValveSoftware/Dota2-Gameplay#22092]
### Item name

Crown fall collector 2

### Description

Crown fall collector 2 cant be gifted

### Example Match ID and Timestamp

1545451

**Comment by eugene-valve** [comment]
Hi, thanks for reporting this. This should be fixed in the latest updated, but please let me know if it isn't for you.

**Comment by Flam3sDOTA** [comment]
@eugene-valve Both Collector's Cache I and Collector's Cache II Ultra Rares(Pudge and Rubick Sets) are not marketable. Is that intended? The Ultra Rare ones from previous Collector Caches were marketable.
