### ISSUE TITLE
Phantom Lancer Innate Does Not Benefit From % Damage Increase

### ISSUE THREAD

**Issue by Holodota** [ValveSoftware/Dota2-Gameplay#22095]
### Ability name

Illusory Armaments

### Description

Phantom Lancer innate does not work with % damage increases. Pictures below showing vlads being used, also tested with vengeful spirit passive and that doesn't seem to work either. The % bonus will only consider the original base damage of Phantom Lancer before his Innate.
 ![pl_bug_1](https://github.com/user-attachments/assets/1fe3cb59-84ba-4a32-9094-efa1a1ee1e78)
![pl_bug_2](https://github.com/user-attachments/assets/c726d435-81c0-4e54-bc14-bca6ce8dcb7c)

### Example Match ID (and possibly Timestamp)

7969028954

**Comment by chrisf-valve** [comment]
We have just shipped an update which should address this issue
