### ISSUE TITLE
Rubick / Warlock Golem on Death Interaction

### ISSUE THREAD

**Issue by Raaaaaaabb** [ValveSoftware/Dota2-Gameplay#2218]
### Ability name

Spell Steal

### Description

In the teamfight in the match at 43 mins, Rubick Spell Steals Chaotic Offering from my character (Warlock) and attempts to cast the spell.  He is killed prior to being able to cast, but a golem was spawned from his death.  Note that Warlock did not have the talent elected for Summoning a golem on death until after the fight, and Rubick was at level 19 so could not have elected the right side of his talent tree.

Issue being claimed is an erroneous golem spawn resulting from the interaction.

Many thanks!

### Example Match ID (and possibly Timestamp)

6720191813 - 43:00

**Comment by TheUnholyWrath** [comment]
https://user-images.githubusercontent.com/46859977/186109467-a3557139-fff1-43e0-abbf-a41bde37454e.mp4

**Comment by TheUnholyWrath** [comment]
![20220823182043_1](https://user-images.githubusercontent.com/46859977/186109600-26a3e4cc-57f1-4f01-a42e-e7d591487775.jpg)

**Comment by Raaaaaaabb** [comment]
Appreciate the digging in here Unholy - will close as won't do.
