### ISSUE TITLE
silenced dark willow casted W

### ISSUE THREAD

**Issue by Farzam2003** [ValveSoftware/Dota2-Gameplay#2223]
### Item name

Orchid

### Description

so i silenced him and he casted W afterwards, ill share the video

### Example Match ID and Timestamp

6720977251 - 23:37

**Comment by Farzam2003** [comment]
https://streamable.com/53icrk
and
https://streamable.com/txziq8

**Comment by Farzam2003** [comment]
> ![20220824033928_1](https://user-images.githubusercontent.com/46859977/186227497-feffe6ae-7467-4cf2-80ca-4c7698e49737.jpg) Dark Willow casted W before you used Orchid. Shadow Realm has a fade time of 0.3s since 7.31

lol my bad ill close this

**Comment by Kabamon** [comment]
> > ![20220824033928_1](https://user-images.githubusercontent.com/46859977/186227497-feffe6ae-7467-4cf2-80ca-4c7698e49737.jpg) Dark Willow casted W before you used Orchid. Shadow Realm has a fade time of 0.3s since 7.31
> 
> lol my bad ill close this

noob

**Comment by Farzam2003** [comment]
> > > ![20220824033928_1](https://user-images.githubusercontent.com/46859977/186227497-feffe6ae-7467-4cf2-80ca-4c7698e49737.jpg) Dark Willow casted W before you used Orchid. Shadow Realm has a fade time of 0.3s since 7.31
> 
> > 
> 
> > lol my bad ill close this
> 
> 
> 
> noob
> 
> 

kys faggot
