### ISSUE TITLE
Command "map_enable_background_maps 0" flagged as cheat

### ISSUE THREAD

**Issue by helgitheo** [ValveSoftware/Dota2-Gameplay#22245]
Can you please deflag it as cheats, it gives 20-30 fps on low end/mid range machines. I'm down from 55 fps to 30 fps in team fights.

What happens:
1. map_enable_background_maps was flagged as cheats by developers and you can't add +parameter in the launch options.

Should be:

2. You may add +map_enable_background_maps 0 in dota 2 launch options and it works in-game.

Proof it is flagged: https://developer.valvesoftware.com/wiki/List_of_Dota_2_console_commands_and_variables

**Comment by gwendolynemaxinegwenstacy** [comment]
use +map_enable_portrait_worlds 0

**Comment by helgitheo** [comment]
> use +map_enable_portrait_worlds 0

Thanks. Looks like it indeed does everything as the old one. Issue is closed.
