### ISSUE TITLE
Queue for ranked match shows confirming match and then punish for not been ready

### ISSUE THREAD

**Issue by clintonshane84** [ValveSoftware/Dota2-Gameplay#22261]
### Description

Today I cannot play Dota 2 and I have Plus subscription. When I try to queue for a ranked match it says its "Finding Match" and does that for 10 or more secs and then I when I get the "Confiming Match" text on the match queue screen it doesnt bring up the expect accept match or confirm match dialog. It just stays on "Confirming Match" and after 10 or more seconds it finally resolves and then my play button is red and have been punished from playing. So I tried to exit Steam completely even reset my Fibre router all of which didn't help. I tried to requeue after the ban was lifted and try again and again the same thing, I get "Finding Match" after 5 or so minutes I then get the "Confirming Match" text and am punished for not readying up when I dont have any dialog coming up for me? Please help you keep punishing me but your interface not working?!

### Screenshots

![Dota 2 2024_10_14 21_58_53](https://github.com/user-attachments/assets/0e4610ea-6ab8-475f-8acc-c5dd148544db)

**Comment by NEO4190** [comment]
same shit

**Comment by NEO4190** [comment]
its been like that for me for 3 days.

**Comment by ErfTherGreat** [comment]
i found that you should just stay in finding mode until couple of times the match will be finally ready for start

**Comment by uldall** [comment]
It has been like this for many days now.

**Comment by clintonshane84** [comment]
As @ErfTherGreat says, if you just wait, and boy that can take up to 30 min sometimes, it eventually does resolve the match without punishing.
