### ISSUE TITLE
[QoL Suggestion] TA D spell (Trap ability) to blow up the trap located closest to the cursor instead of closest to the hero 

### ISSUE THREAD

**Issue by Aluerie** [ValveSoftware/Dota2-Gameplay#223]
**Basically title:** Make Templar Assassin's D spell (Trap ability) to blow up the trap located closest to the cursor instead of closest to the hero. 

It will give player more control over blowing up traps nearby and over the map (+allow mini-map usage) which would be easier, more responsive and intuitive.

**Example:** I want to use trap on enemy Naga but pressing D blows up the wrong trap on the left no matter cursor-targeting. "High-skill-cap" (can select the correct trap manually) but if the button exists then why don't we make it easier/noob-friendlier to use.
![image](https://user-images.githubusercontent.com/33165440/171738778-1b19f56e-ca8b-4c91-b3ef-c97745bf4915.png)

TA players even recommend *against* using the D button because of this issue; currently, it's always better to just manually select the trap.

Moreover, Select trap + Use its Q = ~2 actions *versus* press D = just ~1

**Bonus idea.** If you still want to blow up the closest trap - you would be able to self-cast (cast on place where hero is) to achieve that anyway, so we aren't even losing any functionality.

**Summary.** Make TA D button behave in same way as her scepter spell "Psionic Projection" does: "Target Point" ability which would detonate the closest trap from the targeted point instead of current "No-target" (the closest trap from the hero) implementation. 

This suggestion was discussed (and quite upvoted) on reddit many times in a span of many years - i.e.: [2 month ago](https://www.reddit.com/r/DotA2/comments/tts4bs/suggestion_templar_assassins_spring_nearest_trap/), [even 7 years ago](
https://www.reddit.com/r/DotA2/comments/4dq06p/suggestion_make_ta_activate_traps_closest_to/) and many more

--- 

PS I know at least 3 downvotes were given bcs these guys say the repository is not for QoL posts, while [JeffHill comment](https://www.reddit.com/r/DotA2/comments/vgmr7i/comment/id3w00f/?utm_source=share&utm_medium=web2x&context=3) states otherwise, so please, only downvote this issue if you genuinely think the suggestion is *a total crap*.

**Comment by Daar543** [comment]
That would also make it consistent with the other trap activation skill (scepter upgrade).

**Comment by Aluerie** [comment]
Even though this suggestion is for the better of TA (and Visage) players - I should admit: It is a bit of a "breaking" change.

Quick Cast users will need to aim Cursor properly instead of just pressing the "D" button

Normal Cast users will need to press Confirmation Click in addition to that^

Thus, if this is decided to be implemented, it should probably be notified to players in some official patch notes so TA players don't get confused :smile:

**Comment by Aluerie** [comment]
We did it, chat ! 🎆 

![image](https://user-images.githubusercontent.com/33165440/233511942-411bf675-e627-4460-9229-c7541b8a2db6.png)

**Comment by Aluerie** [comment]
Apparently, current implementation doesn't work. I guess, I will reopen the issue for more attention since issues like #8045 #8053 #8111 are getting buried under hundreds of "harpoon abusers pls ban" posts. 

looks like, it springs the trap closest to the top edge of the screen. 

https://user-images.githubusercontent.com/33165440/233747976-7cd55108-c8fc-4f11-bc1b-a7e6965a2ffe.mp4

**Comment by Dota-Exp** [comment]
will be fixed in an upcoming update, thank you for the report/video

**Comment by Aluerie** [comment]
@Dota-Exp sorry for the ping, but one remaining detail.

It doesn't work when pressing on the mini-map (her Scepter Spell works just fine via mini-map). 

Not really a bug, but it would be very handy...

**Comment by Aluerie** [comment]
Well. opened #8675 for that^ request :D
