### ISSUE TITLE
Purchase I have not made

### ISSUE THREAD

**Issue by ALEXXADE** [ValveSoftware/Dota2-Gameplay#22365]
### Description

Hi, today I received an email from Steam saying that I had bought two wallpapers for a game that I don't even know (Dota 2) the purchase was 5 euros and I would like a refund since I didn't buy anything myself or anyone who uses the computer. Thanks

### Screenshots

![Captjmura](https://github.com/user-attachments/assets/ff7364ac-7116-4e5e-986e-14bd1d3e4ce5)

**Comment by ALEXXADE** [comment]
Hello, I just received more purchases and now also sales from my inventory that I have not made.

**Comment by ALEXXADE** [comment]
![image](https://github.com/user-attachments/assets/2e42c273-7701-4516-8960-70ebc65c1abc)

**Comment by commentator24** [comment]
try not to login to dodgy websites. if you have to enter steam login, only do it on official website like store.steampowered and nothing else

you need to deauthorise all devices on steam setting then contact steam support. not here
![image](https://github.com/user-attachments/assets/f286411f-4c6c-44a3-aaf6-ba33a7e0528b)

**Comment by ALEXXADE** [comment]
Sorry, I've already found where it is, thanks for the help
