### ISSUE TITLE
[Ability Draft] Missing Granted Abilities

### ISSUE THREAD

**Issue by RGBKnights** [ValveSoftware/Dota2-Gameplay#2238]
### Description

As part of the 7.32 patch a number of new granted abilities where added but these are not enabled in AD yet. Below is the list of the missing abilities granted by shard and scepter. As well most of the ultimate's still reference the old upgrade or make no mention new grants within the AD notes.

- Beastmaster - DRUMS OF SLOM
- Brewmaster - PRIMAL COMPANION
- Centaur - HITCH A RIDE
- Enchantress - LITTLE FRIENDS
- Lina - FLAME CLOAK
- Naga - REEL IN
- Nature's Prophet - CURSE OF THE OLDGROWTH 
- Spirit Breaker - PLANAR POCKET
- Tide hunter - TENDRILS OF THE DEEP
- Venomancer - LATENT TOXICITY
- Viper - NOSEDIVE 

This has been verified and tested by the AD community using the [Console Commands ](https://dota2.fandom.com/wiki/Ability_Draft#Console_Commands)to setup and test drafts.

### Example Match ID (and possibly Timestamp)

N/A

**Comment by dhabiheng** [comment]
Fixed in next patch
