### ISSUE TITLE
Disruptor glimpse has 0 cd with the lvl 25 cd reduction talent.

### ISSUE THREAD

**Issue by GiatheFierce** [ValveSoftware/Dota2-Gameplay#2242]
### Ability name

Glimpse

### Description

Disruptor glimpse has 0 cd with the lvl 25 cd reduction talent. It is spammable to death.

### Example Match ID (and possibly Timestamp)

6721472938

**Comment by TheUnholyWrath** [comment]
This has been fixed, please close this issue.
