### ISSUE TITLE
Ridiculous Relics and Quests

### ISSUE THREAD

**Issue by CihatKOCAK** [ValveSoftware/Dota2-Gameplay#22493]
### Ability name

Posion Nova for venom etc

### Description

When do you plan to update hero Relics and Quests according to the patch? For example, if you look at Venomancer or Wraith King, you will understand what I mean :D Especially venom...

Among the progress quests, Posion Nova is still coming, I'm not even going to mention relics...

Or Golem Kills not working for Warlock relics

What about Medallion of Courage quests? Despite the item being removed, we still see it in progress quests weekly (for example Abbadon progress quests)

These are the things that come to my mind for now, but you need to fix them as soon as possible, because these problems have been around for a long time.

### Example Match ID (and possibly Timestamp)

timestamp --> 1730449116

**Comment by Aluerie** [comment]
duplicate https://github.com/ValveSoftware/Dota2-Gameplay/issues/5749
