### ISSUE TITLE
[Luna] Ability icon doesn't change

### ISSUE THREAD

**Issue by leesxcz** [ValveSoftware/Dota2-Gameplay#22504]
### Cosmetic Item Name

Twilight Schism of the Crimson Witness

### Description

The ability icon Moon glavies and the ability effect Lunar orbit doesn't change when equipped with Twilight Schism of the Crimson Witnessof the Crimson Witness. (fig.1 and match 1)

Golden Twilight Schism overwrites the icon and ability effect, and even I am not using Golden Twilight Schism. (fig2)

But I saw this cosmetic works on other people's sets.(match 2)

### Example Match ID

8006055786, 8007895831

### Screenshots

![20241101180515_1](https://github.com/user-attachments/assets/192328d5-4f35-44c1-b7ba-3b899f4c1f22)
![20241101180556_1](https://github.com/user-attachments/assets/e2de2413-b690-49f4-8b36-de2ce73e6056)

**Comment by Astiberon** [comment]
Most likely you have golden immortal chosen as the ability effect. Reset the ability effect and check again.

**Comment by leesxcz** [comment]
> Most likely you have golden immortal chosen as the ability effect. Reset the ability effect and check again.

What do you mean by resetting the ability effect?

**Comment by Astiberon** [comment]
> > Most likely you have golden immortal chosen as the ability effect. Reset the ability effect and check again.
> 
> What do you mean by resetting the ability effect?

![image](https://github.com/user-attachments/assets/93e929c5-4bab-479d-a12f-11248beb9029)

**Comment by leesxcz** [comment]
> > > Most likely you have golden immortal chosen as the ability effect. Reset the ability effect and check again.
> > 
> > 
> > What do you mean by resetting the ability effect?
> 
> ![image](https://private-user-images.githubusercontent.com/107125193/382478341-93e929c5-4bab-479d-a12f-11248beb9029.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1Njk4MTUsIm5iZiI6MTczMDU2OTUxNSwicGF0aCI6Ii8xMDcxMjUxOTMvMzgyNDc4MzQxLTkzZTkyOWM1LTRiYWItNDc5ZC1hMTJmLTExMjQ4YmViOTAyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQxNzQ1MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NDVkMTNhN2I5MmI4NzZlMWFhYWQ1MDZmOWIwNTgwNTFhYzNhN2M0MGZlMzZmNWEyNjJhZDQ5NmFkMDMxZGUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4UMlTcA3WE1vGbRhGuihBlQ_y1mQkPAOwwNObMRj5Cw)

Thanks. It works. I just know there is an option here.
