### ISSUE TITLE
Summoned unit auto attack -> never does not work

### ISSUE THREAD

**Issue by Fjara-h** [ValveSoftware/Dota2-Gameplay#2253]
### Description

In settings, make sure the "Summoned Unit Auto Attack" setting is set to never. Go into demo, select Naga, level mirror image, spawn an enemy and stand next to them. Use mirror image. 

The illusions that are spawned will autoattack the hero that is spawned. This is not the correct behavior and wasn't an issue until recently. The illusions should not instantly attack, only after an attack command is issued.

**Comment by Fjara-h** [comment]
Here is a video of it occuring
https://user-images.githubusercontent.com/22579764/186329972-ccfa3a68-f966-4437-8186-ded1c0163365.mp4

**Comment by Fjara-h** [comment]
https://user-images.githubusercontent.com/22579764/186330083-da327da6-d135-4870-aedf-57787926c0e8.mp4

**Comment by ptohidi** [comment]
There's a hotkey for toggling auto attack. Have you tried binding it and pressing it in-game to see if the illusions will stop attacking?

**Comment by Fjara-h** [comment]
> There's a hotkey for toggling auto attack. Have you tried binding it and pressing it in-game to see if the illusions will stop attacking?

I do not normally have it bound, but I did just do so to test. It does not change the behavior.

**Comment by allidep** [comment]
Autoattack -> never doesnt work ofr heros too. I have the same problem. That option doesnt seems to work. Is there any fix for it yet?

**Comment by Fjara-h** [comment]
No, I've not found a fix yet and none of the recent updates have accidentally fixed it either.

**Comment by Fjara-h** [comment]
Fixed at some point in the past week or so.

**Comment by Fjara-h** [comment]
Occurring again
