### ISSUE TITLE
7.32 - Voodoo Restoration only deals damage based on default value

### ISSUE THREAD

**Issue by Drezzz** [ValveSoftware/Dota2-Gameplay#2254]
### Ability name

Voodoo Restoration

### Description

According to the tool tip "deals 100% of heal damage" - with holy locket, it heals 33 hp, deals 30 damage.

### Example Match ID (and possibly Timestamp)

-

**Comment by TheUnholyWrath** [comment]
#2248

**Comment by Drezzz** [comment]
10-4 closing
