### ISSUE TITLE
Hoodwink's new decoy acting like old decoy

### ISSUE THREAD

**Issue by TalonJG** [ValveSoftware/Dota2-Gameplay#2260]
### Ability name

Decoy

### Description

When using Hoodwink's new decoy, instead of placing a decoy in place and using sharpshooter on the nearest visible enemy, it will sometimes instead run towards where my cursor was. When it does this, I am unable to fully control the illusion, and it just walks forwards and dies. 

You can see in the video provided at the 37:24 timestamp, the illusion stutters a few times. That was me inputting a movement command to stop it from moving, but it overwrote it and continued.

I have been unable to replicate this in the demo hero.

https://user-images.githubusercontent.com/107222880/186328628-bad16ee5-dd11-4e87-9b84-e939f56b5a3b.mp4

https://user-images.githubusercontent.com/107222880/186328621-368d124e-0631-4c12-8fa2-2e2706888e9e.mp4

### Example Match ID (and possibly Timestamp)

6721595906 - 32:52, 37:24

**Comment by Mabadman** [comment]
See #2532 for explanation. It's due to the illusion not having enough mana to cast Sharpshooter.

**Comment by Dota-Exp** [comment]
Will be fixed in upcoming update, thank you
