### ISSUE TITLE
Veno Level 10 Talent 20% Health Regen Reduction

### ISSUE THREAD

**Issue by shaileshgarg** [ValveSoftware/Dota2-Gameplay#2262]
### Ability name

Poison Sting

### Description

Veno Level 10 Talent 20% Health Regen Reduction, only works if Poison Sting is applied by Plague Wards. If Veno attacks then Health regen reduction is not applied.

Also the Debuff Tooltip on the enemy should mention that Health regen is reduced by 20%

### Example Match ID (and possibly Timestamp)

-

**Comment by Sebastian1124** [comment]
Thank you for the excellent blog. It was extremely beneficial to me. Continue to share such ideas in the future. The goal of the game [geometry dash](https://geometry-dash.co) is to control a square and jump through a series of interactive and spiky obstacles to reach the end of each level without crashing into any traps.
