### ISSUE TITLE
Sky ulti Mystic Fare level 3 damage bug

### ISSUE THREAD

**Issue by trnozz** [ValveSoftware/Dota2-Gameplay#22630]
### Ability name

Mystic Fare

### Description

![image](https://github.com/user-attachments/assets/139d5b24-9ea7-46c9-82f8-8e7b83d44fe8)
![image](https://github.com/user-attachments/assets/dc6450ae-2c84-4bc7-b453-08d07e6b4d7f)
should be 1600 but it giving level 2 damage 1200 

### Example Match ID (and possibly Timestamp)

Demo

**Comment by commentator24** [comment]
the dummy has 25% magic resist like all heroes.
0.75 x 1600 = 1200

should close issue not a bug
