### ISSUE TITLE
Crashes the game when there are a large number of skills or items or level in Nest of Thorns

### ISSUE THREAD

**Issue by Wh1teParad1se** [ValveSoftware/Dota2-Gameplay#22707]
### Description

The second time it crashes from the game is when my level increases to 15-16 or when I take an additional slot

### Screenshots

![Снимок экрана 2024-11-11 190754](https://github.com/user-attachments/assets/d7d95cea-d6ed-464a-a1c5-cb17851c946e)

**Comment by SahilValve** [comment]
This has been fixed in a previous update. Thanks for the report!
