### ISSUE TITLE
The phrase "pathetic" was not received after completing the 7th difficulty of "nest of thorns"

### ISSUE THREAD

**Issue by Ramladu** [ValveSoftware/Dota2-Gameplay#22712]
### Description

The phrase "pathetic" was not received after completing the 7th echelon of "nest of thorns"

UPD: completed 7th echelon 2 times already, phrase still not received

### Example Match ID (and possibly Timestamp)

minigame "nest of thorns"

### Screenshots

![photo_2024-11-11_17-21-06](https://github.com/user-attachments/assets/d36425f3-804b-490c-ae66-8d281da0774a)
![photo](https://github.com/user-attachments/assets/3aa451ba-1b9c-419b-8fef-df99833c8c1f)

**Comment by SahilValve** [comment]
Hi, we pushed an update that should have fixed this and gave the reward to anyone who should have had it. Let us know if you are still experiencing the problem.

**Comment by Ramladu** [comment]
good, thx
