### ISSUE TITLE
Crownfall IV end minigame (nest of thorns) Crash.

### ISSUE THREAD

**Issue by Floatydevice** [ValveSoftware/Dota2-Gameplay#22739]
### Description

After completing the minigame and defeating imperia.
The game freezes for 3 seconds and the task ends itself.

I tried 2 times just to make sure and on both I crashed.
How do I finish it then?

### Example Match ID (and possibly Timestamp)

00000000

### Screenshots

https://github.com/user-attachments/assets/d7d6eec7-1b71-4e10-b891-9a20040b05e0

**Comment by SahilValve** [comment]
Hi, has this problem happened recently?

**Comment by Floatydevice** [comment]
After a small update released on that same day of my report I was able to
complete it without crashing. I have played many times since on every
echelon and seems to be working just fine.
Thanks for the reply <3
