### ISSUE TITLE
Juggernaut -  Primal Prowl | Cosmetic Bug

### ISSUE THREAD

**Issue by 00AyanamiRei** [ValveSoftware/Dota2-Gameplay#22749]
### Cosmetic Item Name

Primal Prowl

### Description

I have fully completed the fourth act (59/59), obtained all styles for the Juggernaut Primal Prowl skin, but only two out of five styles were activated.
Steam profile link: https://steamcommunity.com/profiles/76561199009939120/
Dota 2 profile ID: 1049673392

### Example Match ID

1049673392

### Screenshots

![image](https://github.com/user-attachments/assets/60fa7f79-bc0b-4c75-a0c5-bd40e1d99def)
![image](https://github.com/user-attachments/assets/a5dee6ae-8fc6-437a-a365-7ab6f3bfdfe3)
![image](https://github.com/user-attachments/assets/7fca38ca-52dd-470b-a750-bb3186545ede)
![image](https://github.com/user-attachments/assets/60b77bc8-be16-4aa7-a00f-7d64241e0bfb)
![image](https://github.com/user-attachments/assets/57255924-1866-4232-b0bd-4086f2471393)
![image](https://github.com/user-attachments/assets/8ca9c18b-c3ec-4a84-a914-54b6f4c60541)
![image](https://github.com/user-attachments/assets/46752ca0-6111-4ac7-ad5f-dbb746e60357)

**Comment by Gogos2007** [comment]
We’re praying with the whole family for this bug to be resolved.
