### ISSUE TITLE
Dota crashes when launching last mini-game "Nest of Thorns" 

### ISSUE THREAD

**Issue by DavesMk** [ValveSoftware/Dota2-Gameplay#22747]
### Description

When I start this latest mini-game "Nest of Thorns" I get a Dota crash, 
I can choose a character, but at the stage where you have to click play it instantly crashes and there is a window with this inscription

game/client/dota/panorama/crownfall/ survivors/dota_survivors_player.cpp
(1366) : Assertion Failed in function void
CSurvivorsPlayer::LevelUpPowerUp(Sur-
vivorsPowerUpID_t, const
CSurvivorsUpgradeDefinition &) ():
fnCreatelnstance

HELP ME
![Screenshot 2024-11-12 at 12 32 51 AM](https://github.com/user-attachments/assets/df2c000c-9f75-4f9b-b853-0dbaa436804f)

### Example Match ID (and possibly Timestamp)

1234567891 - 12:46

**Comment by SahilValve** [comment]
We fixed this crash in a previous update. Let us know if the problem persists.
