### ISSUE TITLE
Error when starting Crownfall Final battle on Mac

### ISSUE THREAD

**Issue by For8or** [ValveSoftware/Dota2-Gameplay#22756]
### Description

When selecting hero for final battle on MacBook M2 Pro Game crashes with Error message: game/client/dota/panorama/crownfall/survivors/dota_survivors_player.cpp (1370) : Assertion Failed in function void CSurvivorsPlayer::LevelUpPowerUp(SurvivorsPowerUpID_t, const CSurvivorsUpgradeDefinition &)():
fnCreateInstance

### Screenshots

![image](https://github.com/user-attachments/assets/a7332a8c-08f0-40e4-9ee0-e2ed97e41ae6)

**Comment by mknikoloza** [comment]
same problem UP

**Comment by kstan79** [comment]
+1

**Comment by kingoflorderon** [comment]
same problem

**Comment by fikriww** [comment]
same problem +up 
the only fix for me is to play on windows desktop :( ( local i-cafe )

**Comment by fikriww** [comment]
> same problem +up the only fix for me is to play on windows desktop :( ( local i-cafe )

![Uploading Screenshot 2024-11-13 at 05.19.20.png…]()

**Comment by fikriww** [comment]
![Screenshot 2024-11-13 at 05 19 20](https://github.com/user-attachments/assets/102e3c6c-8f5d-4e87-917f-a305dc912c0a)


> same problem +up the only fix for me is to play on windows desktop :( ( local i-cafe )

**Comment by For8or** [comment]
> ![Screenshot 2024-11-13 at 05 19 20](https://private-user-images.githubusercontent.com/91867817/385484109-102e3c6c-8f5d-4e87-917f-a305dc912c0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0NTA5MzksIm5iZiI6MTczMTQ1MDYzOSwicGF0aCI6Ii85MTg2NzgxNy8zODU0ODQxMDktMTAyZTNjNmMtOGY1ZC00ZTg3LTkxN2YtYTMwNWRjOTEyYzBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDIyMzAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4OWJiNmIyZDY3ZjI1ZDBiZWI3ODRiZThkYjJlODBiZWIzMzU3YjEyODdmNDgzNGMxYmZjNmY3MjU4YmRjNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-RT9OoKUY-HSZh9aIeUcp6CbqZPvBPxFBXSnrxqf2R0)
> 
> > same problem +up the only fix for me is to play on windows desktop :( ( local i-cafe )

You can also use free plan on Nvidia Geforce Now if you have stable connection at home. It limits your session for an hour, but it's free

**Comment by mylaluna** [comment]
+1

**Comment by kemalmaulana** [comment]
still no fix progress gaben ?

**Comment by fakedol1** [comment]
+

**Comment by For8or** [comment]
Looks like it is fixed on Nov 14th, thanks. I will close the issue now
