### ISSUE TITLE
Act 4 minigame | Spleen Sweeper | No points for 5 stage

### ISSUE THREAD

**Issue by Rommmmaha** [ValveSoftware/Dota2-Gameplay#22758]
### Description

`Stages cleared(4 x 4,000): 16,000`
But I did 5 stages, after which this final message appeared.
And I think that the game itself is too difficult, and if this bug is fixed, then consider raising the reward from 4,000 to 4,250

### Screenshots

![image](https://github.com/user-attachments/assets/ab5fdaf9-bddb-46d5-8fea-6ee5fa9f0550)

**Comment by Nathanael-Valve** [comment]
Fixed
