### ISSUE TITLE
act 4 spleen sweeper dont count the 5th stage points BUG

### ISSUE THREAD

**Issue by stranislav** [ValveSoftware/Dota2-Gameplay#22760]
### Description

5th stage points are missing , and sometime time remaining points too

### Screenshots

![www](https://github.com/user-attachments/assets/a4918416-e122-4474-a834-622f22511d89)

**Comment by qwertyfive** [comment]
I get the same. 
![image](https://github.com/user-attachments/assets/c7f7a47a-0fc6-4d2b-add0-f81d1d367d79)

**Comment by commentator24** [comment]
yup when lost 4x
![image](https://github.com/user-attachments/assets/bf63b240-9de2-4de9-81ed-b13ec0a8bdb2)

win also 4x
![image](https://github.com/user-attachments/assets/3400d71e-ea67-4d73-8064-e164c8efa8ea)

**Comment by Nathanael-Valve** [comment]
Fixed
