### ISSUE TITLE
Shen (Venge) arcana still locked

### ISSUE THREAD

**Issue by MysterioK** [ValveSoftware/Dota2-Gameplay#22766]
### Cosmetic Item Name

For arcana The Ressurection of Shen

### Description

I completed the "Nest of Thorns" and used the tool to unlock imperia, but it's still locked and tool is gone now. 

### Example Match ID

No match idea 

### Screenshots

![image](https://github.com/user-attachments/assets/7ebe8dee-517f-4634-8094-9711c3387fb3)
![image](https://github.com/user-attachments/assets/8717ff84-e45a-4dc0-9b50-f08241ae0be0)

**Comment by MysterioK** [comment]
ID would be 112038841

**Comment by eugene-valve** [comment]
It looks like you haven't claimed the Imperia Style unlock yet. Have you tried going to the Commodore's Club on the right side of Act IV?

**Comment by MysterioK** [comment]
Colled it from commodore's, worked, but now I also have this in inventory that I cannot use: 
![image](https://github.com/user-attachments/assets/85f33b49-bd74-44ea-b96f-016b6775a248)
![image](https://github.com/user-attachments/assets/e1a94922-0f00-4251-a136-e62668a664c1)

same with this one: 
![image](https://github.com/user-attachments/assets/b8b0c99b-09e6-49d1-b94c-1214b428ef6b)
