### ISSUE TITLE
No reward after completing Echelon 7 in Dota2 Nest of Thorns Minigame

### ISSUE THREAD

**Issue by NaldaNiased** [ValveSoftware/Dota2-Gameplay#22761]
### Description

I already cleared Echelon 7 in Dota2 Nest of Thorns Mini game
but didnt get any reward after completing it
no item pop up, or even when i check in the Voice Line settings

Link video of my gameplay

### Example Match ID (and possibly Timestamp)

https://youtu.be/Yb1pHTCsO6U time at 5:04 

### Screenshots

![Screenshot_23](https://github.com/user-attachments/assets/932f6214-dd0a-425a-8a76-09a0fc4aaedb)
![Screenshot_24](https://github.com/user-attachments/assets/cd676f74-79af-448f-97d2-6d89209a4593)

**Comment by slagar32** [comment]
Up. Having the same issue.

**Comment by SahilValve** [comment]
Hi, we pushed an update that should have fixed this and gave the rewards to anyone who didn't have the rewards who should have. Let us know if you're still experiencing this issue.

**Comment by NaldaNiased** [comment]
> Hi, we pushed an update that should have fixed this and gave the rewards to anyone who didn't have the rewards who should have. Let us know if you're still experiencing this issue.

Thanks you for the work, already got the voiceline now
thank you so much
