### ISSUE TITLE
Nest of Thorns loading screen problem

### ISSUE THREAD

**Issue by Nothsaw** [ValveSoftware/Dota2-Gameplay#22764]
### Cosmetic Item Name

Nest of Thorns loading screen

### Description

There is no image in the loading screen

### Example Match ID

-

### Screenshots

![Снимок экрана 2024-11-12 164151](https://github.com/user-attachments/assets/e625d5af-ce29-4aac-be15-96ff9b9a8ec8)

**Comment by Hallievhrun** [comment]
![Select Background](https://github.com/user-attachments/assets/34afced1-55df-4fb4-b32c-cdce0c2be0dc)
![Profile View](https://github.com/user-attachments/assets/88b5c814-0366-4423-882d-e55efad8de77)

**Comment by SahilValve** [comment]
Hi, we fixed this problem in a previous update. Let us know if it is still happening.
