### ISSUE TITLE
Nest of Thorns Tier 7 reward can't be claimed

### ISSUE THREAD

**Issue by slagar32** [ValveSoftware/Dota2-Gameplay#22781]
### Description

Today I beat the Nest of Thorns mini-game in Crownfall Act IV a few times
![2](https://github.com/user-attachments/assets/f68c133f-56f3-44a1-8594-a8508e872874)
, and for some reason, I didn't recive the access to the last reward. It's still stays locked for me.
![1](https://github.com/user-attachments/assets/aff414ca-e3b2-410b-9683-bb7ee0fa4069)

**Comment by slagar32** [comment]
After todays update, I still can't unlock it. Even beat it again, and nothing.

**Comment by l3ladenine** [comment]
I have the same problem. I have completed 4 rounds but did not receive any rewards.

**Comment by SahilValve** [comment]
Hi, we pushed an update that should have fixed this and gave the reward to anyone who should have had it. Let us know if you are still experiencing the problem.

**Comment by Ulquiorrra4** [comment]
@slagar32 what upgrades do u have ?
