### ISSUE TITLE
CRASH issue on Nest of Thorns (Crownfall's Act IV last minigame)

### ISSUE THREAD

**Issue by ecarvallo** [ValveSoftware/Dota2-Gameplay#22783]
### Description

Whenever I fail after a long run (8mins+) and I try to press on the button Upgrades and Difficulties the game and my PC crashes.
The first time it happened a Windows alert appears and it says something about some corrupted files with some name and locations refering to the same minigame or just the event.
I couldn't save a screenshot of this but please see this issue!

**Comment by SahilValve** [comment]
Hi, is this problem still occurring?

**Comment by ecarvallo** [comment]
I always try to close the window after winning or losing now, but I tried to press that button again right now and it didnt crash this time.
