### ISSUE TITLE
No tokens after finishing Act IV of Crownfall

### ISSUE THREAD

**Issue by Aedrio** [ValveSoftware/Dota2-Gameplay#22780]
### Description

So, i just finished the Act IV for Crownfall and i wanted to farm some tokens while playing ranked in order to upgrade my abilities and finish the full mini-game at the end called nest of thorns but for some reason, my tokens won't show on the Crownfall map, they do show after every single match that im winning that i have received them.

Match ID: 8032896363 / 8032982482.

Already tried to restart the game, changes acts betwen them or wait for a while. Nothing seems to be happening.

### Example Match ID (and possibly Timestamp)

8032896363 / 8032982482.

**Comment by SahilValve** [comment]
Hi, we fixed this problem in a previous update. Let us know if you are still running into this.
