### ISSUE TITLE
Venomancer poison sting talent only work with plague ward

### ISSUE THREAD

**Issue by kirka7** [ValveSoftware/Dota2-Gameplay#2278]
### Ability name

poison sting

### Description

lvl 10 talent  "20% Poison Sting Health Regen Reduction" only work with poison sting applied by plague ward. 
If you hit by ward and then by hero with poison sting talent doesnt work. Its only work if plague ward hit enemy alone.
![1 talent working with plague ward](https://user-images.githubusercontent.com/111957624/186354218-54c59335-bd9a-4574-8f15-5cea37c67687.jpeg)
![2 talent doesnt work with hero](https://user-images.githubusercontent.com/111957624/186354231-eb12855b-a5a1-421b-bb4e-6411a48248d7.jpeg)
![3 talent doesnt work with hero and ward](https://user-images.githubusercontent.com/111957624/186354232-43915712-723f-497f-9180-65b9695ba266.jpeg)

### Example Match ID (and possibly Timestamp)

6721756661 - 18:55

**Comment by TheUnholyWrath** [comment]
#2262

**Comment by nathank-valve** [comment]
the fix will be included in the next hotfix
