### ISSUE TITLE
Silencer arcane curse undispellable talent still can be dispel by bkb

### ISSUE THREAD

**Issue by aryopd04** [ValveSoftware/Dota2-Gameplay#2279]
### Ability name

arcane curse

### Description

I tried with basic dispel and strong dispel and its works fine, only when u activated bkb and it will dispel the arcane curse debuff, I tried with slardar corrosive haze undispelable talent and its works fine even with bkb. I tried it in demo mode.

### Example Match ID (and possibly Timestamp)

----

**Comment by nathank-valve** [comment]
the fix will be included in the next hotfix

**Comment by nathank-valve** [comment]
actually, there were several abilities that could still remove arcane curse beyond just bkb. I just cleaned those up to, so that fix will be included in the next next hotfix
