### ISSUE TITLE
Overwhelming Odds typo

### ISSUE THREAD

**Issue by devotion26** [ValveSoftware/Dota2-Gameplay#22816]
### Hero and spell

Legion Commander - Overwhelming Odds

### Description

The buff description for overwhelming odds says "Gaining 50% attack speed." 
This spell does not increase attack speed by a percentage.

### Screenshots

![image](https://github.com/user-attachments/assets/47526d15-5400-4621-a6df-4d99cbe03fa5)

**Comment by SahilValve** [comment]
Hi, thanks for the report. I have fixed this for the next update.
