### ISSUE TITLE
Crownfall IV Nest of Thorns crashes the game

### ISSUE THREAD

**Issue by fakedol1** [ValveSoftware/Dota2-Gameplay#22814]
### Description

when i'm trying to even start the minigame on my mac, dota just crashes. it's been several days and i thought you would already fix it, but no. Please, let all the players complete the mini-game

### Screenshots

<img width="1512" alt="Снимок экрана 2024-11-14 в 13 40 28" src="https://github.com/user-attachments/assets/809a37e3-957c-4362-8d46-6308821746f1">

**Comment by buttersome** [comment]
Yep. It's only on Mac OS. Somebody already posted the issue, maybe go there leave a comment so they notice it or something.

**Comment by SahilValve** [comment]
This issue has been resolved. Thanks for reporting.
