### ISSUE TITLE
Specialists Array is broken

### ISSUE THREAD

**Issue by Boccian** [ValveSoftware/Dota2-Gameplay#2282]
### Item name

Specialists Array

### Description

gives 3 multishots instead of two, also drows ulti works with those multishots.
![image](https://user-images.githubusercontent.com/111973724/186392923-5e70824f-bad8-4343-a1d7-81be54e8ae9f.png)
![image](https://user-images.githubusercontent.com/111973724/186393010-44e0e56f-5234-4370-a3ca-7b248cae8ae5.png)
(4 arrows on first image, 2 ulti at the same time on second)

### Example Match ID and Timestamp

custom game

**Comment by Boccian** [comment]
also works with venomancer passive

**Comment by Farzam2003** [comment]
check this #2293

**Comment by Dota-Exp** [comment]
This will be fixed in the next update
