### ISSUE TITLE
[Kez] Grappling claw no longer applies lifesteal

### ISSUE THREAD

**Issue by apflu** [ValveSoftware/Dota2-Gameplay#22830]
### Ability name

Grappling Claw

### Description

https://github.com/user-attachments/assets/3f11d505-2c46-4a0b-9517-dc504e2bd7f0

https://github.com/user-attachments/assets/4d470817-0558-4140-aafb-656fba678ace

### Example Match ID (and possibly Timestamp)

0

**Comment by qh010207** [comment]
this bug just bursted my lane, plz fix

**Comment by qh010207** [comment]
to follow up this issue with a match ID: 8036377115 .  Starting min 1

**Comment by qh010207** [comment]
and I personally think is not  lifesteal, kez no longer attacks after using the crawl, which leaded into not lifestealing

**Comment by qh010207** [comment]
think can be closed now, bug fixed!

**Comment by apflu** [comment]
Closed #22830 due to recent hotfix fixed the issue.
