### ISSUE TITLE
Crownfall - Nest of Thorns loading screen blank

### ISSUE THREAD

**Issue by atlab89** [ValveSoftware/Dota2-Gameplay#22879]
### Description

When trying to use Crownfall - Nest of Thorns loading screen it appears as blank.

### Screenshots

![Screenshot 2024-11-17 222633](https://github.com/user-attachments/assets/73001dfa-391a-4996-a490-7fd9f4830ec4)

**Comment by SahilValve** [comment]
Hi, I believe this problem was fixed. Let us know if it persists.

**Comment by atlab89** [comment]
Just checked it and it's working fine now. Thank you.
