### ISSUE TITLE
Crownfall nest of thorns steam deck issues

### ISSUE THREAD

**Issue by notryn** [ValveSoftware/Dota2-Gameplay#22872]
### Description

I loaded up nest of thorns on my steam deck and encountered 2 bugs.  One is that hitboxes for melee attacks (echo slash, swashbuckle) seem to sometimes miss the hurtbox of the creeps.  It is very noticeable in early levels, not sure if it matters so much towards the middle of the game when the screen is covered in enemies.  

The other bug is that after maximizing the nest of thorns window (top left button) on my steam deck, anytime I would re-roll an item or ability, the nest of thorns game would reload itself, sometimes with the previous item choices still in the middle of the screen.

Please let me know if there is any other helpful info I can provide.  Thanks!

**Comment by TaylorP** [comment]
Just wanted to add that I'm also experiencing the hitbox issues with both Echo Slash and Swashbuckle on desktop Linux (Ubuntu 22.04.5 LTS). It's especially obvious right after loading into a new game as Kez -- aiming his Echo Slash directly at a single skeleton frequently does no damage or knockback.

**Comment by SahilValve** [comment]
Hi, thanks for the report but unfortunately we are not officially supporting the Steam Deck as a platform where you can play this.
