### ISSUE TITLE
Crownfall - Nest of Thorns level 7 reward is bugged

### ISSUE THREAD

**Issue by Meti0X7CB** [ValveSoftware/Dota2-Gameplay#22885]
### Description

Upon completing level 7 difficulty of Nest of Thorns, I did not get the reward voice line.

### Screenshots

![image](https://github.com/user-attachments/assets/bf51aa28-0daf-45c0-9bfc-afb3e3ea0f5a)

![20241117154739_1](https://github.com/user-attachments/assets/3fcb781b-80cd-4014-af08-5ced8e1e0038)

![image](https://github.com/user-attachments/assets/0e97a075-b47d-4a1a-b94e-4bf5689d00d8)

**Comment by meowlisha** [comment]
I have the same issue! 
I spent on this almost 7 days🙃
There was an error
![IMG_4227](https://github.com/user-attachments/assets/9d4ace86-abfc-49b1-a5b4-83c2ae5ba8f6)
![IMG_4228](https://github.com/user-attachments/assets/737d61e7-b073-4ea1-92a3-7c1c0fa95d28)
 on final screen “k_Timeout (4)”
