### ISSUE TITLE
Basher not work on new hero kez discipline Shodo Sai

### ISSUE THREAD

**Issue by doomhammer56** [ValveSoftware/Dota2-Gameplay#22882]
### Item name

Skull Basher

### Description

When Activated Shodo Sai , Basher passive will no longer activate 

### Example Match ID and Timestamp

8041511834 - 35:19

**Comment by Conrayy** [comment]
This intentional, not a bug.

**Comment by doomhammer56** [comment]
> This intentional, not a bug.

really? but i dint see at description

**Comment by commentator24** [comment]
![image](https://github.com/user-attachments/assets/bb42a55e-6d9c-4bbf-86ed-075a5d3c2b29)
should close issue not a bug

**Comment by doomhammer56** [comment]
alright
