### ISSUE TITLE
The 'Crownfall - Nest of Thorns' loading screen can't be used in player profiles as a background.

### ISSUE THREAD

**Issue by WhereThighs** [ValveSoftware/Dota2-Gameplay#22899]
### Description

The loading screen from the 'Nest of Thorns' minigame in Crownfall Act IV won't work as a background for player profiles, which is a shame because I'd hoped to use it for that purpose and love the style of it!

It also doesn't preview properly, instead showing up as a blank window.

**Comment by SahilValve** [comment]
Thanks for the report! We've found the issue and it will be fixed in the next update.
