### ISSUE TITLE
no mana regen on lich

### ISSUE THREAD

**Issue by wahyuahkam** [ValveSoftware/Dota2-Gameplay#22897]
### Description

i ahve alot item mana regen but its not working

### Example Match ID (and possibly Timestamp)

8042639157

**Comment by commentator24** [comment]
![image](https://github.com/user-attachments/assets/aab3b193-273b-40dc-aa4b-11973eac479f)
should close issue not a bug

✔️arcane boot, mango, soul ring works
❌Bottle, clarity, alot item mana regen do not work
