### ISSUE TITLE
Shadow Demon bug with every cosmetics

### ISSUE THREAD

**Issue by Rainogh** [ValveSoftware/Dota2-Gameplay#2291]
### Cosmetic Item Name

All of them

### Description

We can see the original Shadow Demon parts going through the cosmetics

### Example Match ID

1234

### Screenshots

![image](https://user-images.githubusercontent.com/107361399/186405641-3315e2f2-cbe9-4bad-8924-54cb02e1abae.png)

![image](https://user-images.githubusercontent.com/107361399/186405870-3e52f048-d5e0-4f5b-b30b-0465122b904f.png)

![image](https://user-images.githubusercontent.com/107361399/186406002-84a1e5ec-c29d-429b-bc70-cfc33f271090.png)

![image](https://user-images.githubusercontent.com/107361399/186406047-efdeb91f-6f5c-4bcb-b775-f5585dc6a370.png)

**Comment by EnlilPlaysDota2** [comment]
Yep, same trouble. Hope Valve will fix it soon.

**Comment by Dota-Exp** [comment]
This will be fixed in the next update

**Comment by Rainogh** [comment]
The issue is still present but only on the belt since the new update
![image](https://user-images.githubusercontent.com/107361399/187558371-0514e8fc-0161-40db-92c7-083f53f2c43d.png)

![image](https://user-images.githubusercontent.com/107361399/187558452-1ecab602-36d5-4ab4-bf49-739775efacb5.png)

![image](https://user-images.githubusercontent.com/107361399/187558482-cd491fb1-ab46-4ff5-a907-d89fca96ee53.png)

![image](https://user-images.githubusercontent.com/107361399/187558522-6bdc20b6-0637-425e-97d7-2a92ead7f3ae.png)

**Comment by Rainogh** [comment]
2 years later and this is not fixed still
![image](https://github.com/user-attachments/assets/9b5eadcc-01b3-4483-8677-8e069da3fc9f)
