### ISSUE TITLE
Throne of Thorns Loading Screen Display Error

### ISSUE THREAD

**Issue by wtreeh** [ValveSoftware/Dota2-Gameplay#22913]
### Item name

fallen crown act 4 loading screen throne of thorns

### Description

instead of the loading screen element, a transparent element was issued
can't set as profile background

![image](https://github.com/user-attachments/assets/e55b3193-2ff0-412a-a868-63d76cf85b33)

**Comment by SahilValve** [comment]
Thanks for the report! We've found the issue and it will be fixed in the next update.

**Comment by wtreeh** [comment]
> Thanks for the report! We've found the issue and it will be fixed in the next update.

I really hope so, thanks for the answer.
