### ISSUE TITLE
Shadow Fiend's Pressence of the dark lord doesn't lose stacks while sf dies

### ISSUE THREAD

**Issue by mironov1971144** [ValveSoftware/Dota2-Gameplay#22928]
### Ability name

Pressence of the dark lord

### Description

Shadow Fiend doesn't lose stacks of passive while dies, despite the fix
![1](https://github.com/user-attachments/assets/5d1ebfc3-9957-4536-bc47-e47d6de0dbb0)
![2](https://github.com/user-attachments/assets/cfa30d85-200e-4c0b-9b7a-7d9a62f53624)
![3](https://github.com/user-attachments/assets/2ae7d5ce-30de-423a-876d-3562482bfdba)

### Example Match ID (and possibly Timestamp)

8045108120 5:52-6:00

**Comment by mironov1971144** [comment]
Here's  correct screenshots
![image](https://github.com/user-attachments/assets/5a0de949-a504-44b0-99e9-093b88b07c70)
![image](https://github.com/user-attachments/assets/bb6257eb-7b23-435b-b4d0-163147ad4041)
![image](https://github.com/user-attachments/assets/9054f965-fb0d-4588-b899-17c508c67364)

**Comment by Nathanael-Valve** [comment]
Fixed in next update.
