### ISSUE TITLE
New OD buff is not working

### ISSUE THREAD

**Issue by kowaw** [ValveSoftware/Dota2-Gameplay#22925]
### Description

in 7.37e OD got buffed and mana per intellect was scaled from 2.0 to 2.5, but i tested it in lobby and after I did the calculations OD have the same amount of mana per intellect (2.0), so staff of wizardry should give 25 mana, but in reality it gives 20

### Example Match ID (and possibly Timestamp)

none

**Comment by commentator24** [comment]
ur math sounds so confusing lol. at first i was like huh staff 25 mana, and where 20 from
normally 1 int 12 mana. so 10 int 120 mana.
OD gets 2.5 more, so 1 int 14.5 mana. 10 int 145 mana.
OD currently gets 140 mana from 10 int as shown below, so yeah as you said gives only 20 difference not 25
![image](https://github.com/user-attachments/assets/b69589db-8031-4f39-919c-bfef8ed38811)

**Comment by commentator24** [comment]
seems fixed should close issue
@Nathanael-Valve
