### ISSUE TITLE
IO Aghanim's Scepter does not work

### ISSUE THREAD

**Issue by M4NG0-x** [ValveSoftware/Dota2-Gameplay#22932]
### Ability name

Spirits

### Description

IO Aghanim's Scepter does not work in the final minigame of Act 4 of the Fall of the Crown "Nest of Thorns" with the new updates.
![Captura de pantalla (233)](https://github.com/user-attachments/assets/6af0e10b-3e30-4b14-b5ac-b6a9b881ccdb)

### Example Match ID (and possibly Timestamp)

04:37

**Comment by commentator24** [comment]
its not non stop spin now, just explosion when hit
