### ISSUE TITLE
Nest of Thorns loading screen is missing

### ISSUE THREAD

**Issue by recreamu** [ValveSoftware/Dota2-Gameplay#22942]
### Cosmetic Item Name

Crownfall - Nest of Thorns loading screen

### Description

There is loading screen missing, in loading its just black, in the profile and inventory its transparent

### Example Match ID

.

### Screenshots

![image](https://github.com/user-attachments/assets/35a8901e-3170-477b-b1c6-a0cc18afd75e)

**Comment by SahilValve** [comment]
Thanks for the report! We've found the issue and it will be fixed in the next update.
