### ISSUE TITLE
Crownfall Act IV: Retired Queensguard: Cannot Spend Tokens for Scrap

### ISSUE THREAD

**Issue by SimoRiikonen** [ValveSoftware/Dota2-Gameplay#22964]
### Description

I have all the required tokens for 2 different options, "Spend Tokens"-buttons remain gray and cannot be pressed to complete transaction. 

### Screenshots

![image](https://github.com/user-attachments/assets/4bf40e4d-3080-41e5-bca3-27848e6c865b)

**Comment by commentator24** [comment]
its the other way around. you spend scraps to get those tokens shown

**Comment by commentator24** [comment]
its the other way around. you spend 9 12 or 15 scraps to get those tokens shown. you currently hv 2 scraps

**Comment by SimoRiikonen** [comment]
> its the other way around. you spend 9 12 or 15 scraps to get those tokens shown. you currently hv 2 scraps

Ah..Ok. Thanks, It did cross my mind but after googling around and reading a few trash articles I was still under the assumption it was the other way around.
