### ISSUE TITLE
Laguna blade does not receive bonus damage from fiery soul shard.

### ISSUE THREAD

**Issue by zurekl** [ValveSoftware/Dota2-Gameplay#2300]
### Ability name

Laguna blade

### Description

According to fiery soul shard description it should give bonus damage to all Lina spells ("Lina's spells deal 15 more damage for each Fiery Soul Charge."). When I test damage I can see that stacks apply to Dragon Slave i Light Strike Array but not Laguna blade.

### Example Match ID (and possibly Timestamp)

0

**Comment by TheUnholyWrath** [comment]
#2241

**Comment by zurekl** [comment]
Bug has been fixed. Works properly now.
