### ISSUE TITLE
Nest of Thorns graphics setting

### ISSUE THREAD

**Issue by Born2carry** [ValveSoftware/Dota2-Gameplay#23024]
### Description

Hi. I just want the option for the Nest of Thorns minigame to lower the graphics like in normal dota.
For some reason a game starts with graphics at higher settings than what I want.
I know this cuz for example I have animated portraits turned off but those just come enabled there and I can't turn it off.
My PC is basically Frankenstein's monter held together by hope and It definitely could use a break from this.
The gamemode that is supposed to last 20 minutes per Match takes 2 hours thanks to how slow it gets.
Plz help

**Comment by Christin602Bey** [comment]
Hello!
I understand your frustration with the high graphics settings in the Nest of Thorns minigame. Unfortunately, I can't directly change the graphics settings for you. However, you can try adjusting the graphics settings manually in the Dota 2 settings menu. Look for options related to "Graphics Quality" or "Advanced Graphics" and lower the settings there.

**Comment by Born2carry** [comment]
> Hello! I understand your frustration with the high graphics settings in the Nest of Thorns minigame. Unfortunately, I can't directly change the graphics settings for you. However, you can try adjusting the graphics settings manually in the Dota 2 settings menu. Look for options related to "Graphics Quality" or "Advanced Graphics" and lower the settings there.

Ehh...That's the whole point? I have everything set to low yet when I open the game it's higher than what's supposed to. 
No need to be a dick about it

**Comment by SahilValve** [comment]
Hi, there are unfortunately no separate graphics settings for Nest of Thorns.
