### ISSUE TITLE
7.32: Mars's Arena of Blood was NOT fixed.

### ISSUE THREAD

**Issue by Mabadman** [ValveSoftware/Dota2-Gameplay#2307]
### Ability
Arena of Blood

### Description
(Preface; all testing done in Demo mode)
Despite what the patch log states (below), most flying heroes are still able to simply walk over Mars's ultimate.
> Fixed flying units sometimes being able to escape from arena

Following heroes can fly over Mars's Arena:
- Winter Wyvern (Arctic Curse)
- Visage (Scepter Upgrade)
- Night Stalker (Dark Ascension)

Only Batrider (Firefly) is unable to fly over the Arena's boundary. 

<br> 
<br> 
<br> 

### Extra
Following heroes don't have flying movement but they have a leap-like ability they can use to pass through the Arena (ignoring abilities which grant invulnerability or magic immunity, and ones which simply teleport/blink the caster). I don't think this update was meant to affect these skills, but I'll still include them here.
In order to pass through the wall, they need to get hit by the wall once (or twice, if the skill is short-ranged) in order to utilise the time gap between wall-attacks. See gif at the end for demonstration.
- Pangolier (Swashbuckle) (Shield Crash)
- Io (Tether)
- Dawnbreaker (Celestial Hammer- Converge)
- Phoenix (Icarus Dive)
- Sniper (Concussive Grenade)
- Earth Shaker (Sceptre Upgrade)
- Zeus (Heavenly Jump)
- Tiny (Toss) (The tossed hero, not Tiny, should be hit by the wall)
- Marci (Dispose) (The disposed hero, not Marci, should be hit by the wall)
- Techies (Blast Off!) (Only with Arcane Blink's buff, otherwise animation is too long)
- Earth Spirit (Rolling Boulder) (Totally unaffected by the wall, does not get hit)

Following skills share similarities to ones above, however they do not allow the hero to pass through the Arena.
- Mirana (Leap)
- Slark (Pounce)
- Snapfire (Firesnap Cookie)
- Magnus (Skewer)
- Wildling Ripper (Hurricane)
- Monkey King (Tree Dance)
- Primal Beast (Onslaught)
- Spirit Breaker (Charge of Darkness)
![ezgif-1-59355ea3e2](https://user-images.githubusercontent.com/42493726/186467649-c736eca1-d167-42cb-a0be-13390b16ba2b.gif)

**Comment by Dota-Exp** [comment]
This will be fixed in the next update
