### ISSUE TITLE
[Nest of Thorns] Echo Slash and Swashbuckle doesn't work as intended(?) on Linux, but seems to work fine in Windows

### ISSUE THREAD

**Issue by deanrih** [ValveSoftware/Dota2-Gameplay#23083]
### Ability name

Echo Slash and Swashbuckle

### Description

Ability Echo Slash and Swashbuckle in Nest of Thorns in Linux seems doesn't work as expected, the "slash" particles looks like hitting the enemy units however no damage nor knock back being dealt or applied, it Echo Slash only deal damage and knock back when an enemy is in the radius or area of effect of the Echo Slash, much like Axe's Counter Helix

### More information

```
Operating System: Manjaro Linux 
KDE Plasma Version: 6.1.5
KDE Frameworks Version: 6.6.0
Qt Version: 6.7.2
Kernel Version: 6.11.2-4-MANJARO (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i3-8100 CPU @ 3.60GHz
Memory: 31.1 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 2060/PCIe/SSE2

Monitors: 2
Primary Monitor Resolution: 3840x2160
In-game resolution: 1920x1080 (60 Hz) (Desktop-friendly Fullscreen)
Graphics API: Vulkan
NVIDIA Reflex Low Latency: Disabled
Advanced Settings: All On except VSync
Texture Quality: Med
Effects Quality: High
Shadow Quality: Med
Game Screen Render Quality: 60%
FidelityFX Super Resolution: On
Maximum frames per second allowed: 120
Dashboard maximum frames per second: 80
```

Video:
Linux gameplay:
https://github.com/user-attachments/assets/e748f899-24ff-4cba-ab6e-6ca76267da5c

Windows gameplay (from my friend):
https://github.com/user-attachments/assets/027ba1f8-5f48-4031-a0a4-1320b4bedc40

As you probably can see, in my case, the Echo Slash damages every enemy around Kez or I guess the hero, while in my friend's case, even the enemy at the back of the hero doesn't get damaged, it only damages enemies in front of the hero, just like where the particle effect is.

### Example Match ID (and possibly Timestamp)

N/A

**Comment by merry678** [comment]
Hello,
I also have same issue.
Best Regards
merry678

**Comment by deanrih** [comment]
The new patch fixes this bug and I already confirmed that the Echo Slash and Swashbuckle now works correctly (at least compared to what I see from Windows gameplay) after the new patch ([source](https://store.steampowered.com/news/app/570/view/4442333890575598739?l=english))

closing this issue
