### ISSUE TITLE
Nest of Thorns Tier 7 abuse -dev panel

### ISSUE THREAD

**Issue by dirubens21** [ValveSoftware/Dota2-Gameplay#23081]
### Description

Only work tier7 lvl -dev in launch options type -dev them F6 left click with mouse type "debugcontainer " change value "visibility" from "collapse" to "visible"

with dev panel you can use unlimited  Reroll and upgrade all your abilities ez tier 7 lvl 
Fix Valve thanks
Only work with 7 tier

### Example Match ID (and possibly Timestamp)

-

**Comment by dirubens21** [comment]
#23075

**Comment by centralnui** [comment]
Ban those who use it! Its the same a cheats or hacks!

**Comment by reven0ir** [comment]
> Ban those who use it! Its the same as cheats or hacks!

No, it's just a developer's mistake. As they say: first come, first serve!

**Comment by centralnui** [comment]
> > Ban those who use it! Its the same as cheats or hacks!
> 
> No, it's just a developer's mistake. As they say: first come, first serve!

It will be a revelation to you or something, but the possibility to use hacks, cheats in-game, can be called as a "developer's mistake" as well. 

Those who used -dev panel to gain easy walkthrough of nest of thorns are actually cheaters/hacker, they should be banned, or at least reset their activity in nest of thorns, as long as they don't deserve those rewards and score.

**Comment by reven0ir** [comment]
> > > Ban those who use it! Its the same as cheats or hacks!
> > 
> > 
> > No, it's just a developer's mistake. As they say: first come, first serve!
> 
> It will be a revelation to you or something, but the possibility to use hacks, cheats in-game, can be called as a "developer's mistake" as well.
> 
> Those who used -dev panel to gain easy walkthrough of nest of thorns are actually cheaters/hacker, they should be banned, or at least reset their activity in nest of thorns, as long as they don't deserve those rewards and score.

The problem is that only 1 button remained active, banning people who abused it I think is too harsh a punishment, but zeroing out progress I support it.
