### ISSUE TITLE
Did not get my re-rolls

### ISSUE THREAD

**Issue by Iampoptart** [ValveSoftware/Dota2-Gameplay#23094]
### Item name

Crownfall royal bundle

### Description

I bought 2 of them and i should get 20 re-rolls. however I only have 11. 1 is from a game i played. After i bought it, i have not tried to re-roll at all till they fix the issue. 

This has happened before when i claimed the 10 coin tokens for this bundle. I never got the re-rolls either. 
what should i do? i contacted support and its not getting anywhere.. The person seriously replied.. "I see that you got 21 when it says 11...." 

![doita2](https://github.com/user-attachments/assets/09bb502f-bb48-4d18-be99-b8dc4c5e135a)
![dota 2](https://github.com/user-attachments/assets/7ef223a2-79e4-44f6-a422-ae01b69c81c8)

### Example Match ID and Timestamp

20241130 - 5:38

**Comment by Kr3bm4** [comment]
You have 21 rerolls. 10 depicted as circles with a question mark in the middle. The Extra 11 is shown as the "+11"
