### ISSUE TITLE
Full life Meepo dies instantly - "Meepo is killed by Meepo!"

### ISSUE THREAD

**Issue by Poischich** [ValveSoftware/Dota2-Gameplay#23169]
### Description

While fighting, Meepo in the Megameepo form suddenly dies, losing 5409 hp in an instant

In the combat log, the message "Meepo is killed by Meepo!" appears

See replay from the match ID below, timestamp 26:13

### Example Match ID (and possibly Timestamp)

8068153376 timestamp 26:13

### Screenshots

![meepokilled](https://github.com/user-attachments/assets/efa8f660-75ae-401e-bfe3-3ac1b86ae15e)

**Comment by christopher356** [comment]
Enjoyed reading the article above, really explains everything in detail, and the article is very interesting and effective. Thank you and good luck with the upcoming articles.

**Comment by commentator24** [comment]
![image](https://github.com/user-attachments/assets/2eaaa202-9bdd-427d-9f87-c027b040c3a6)
using megameepo does not guarantee all clones will be in it. as you can see you left out 1 clone.
when 1 clone die, the rest die as normal
![image](https://github.com/user-attachments/assets/c675d6ea-44d9-4d8f-8dd0-5a0582c65ad6)

**Comment by Poischich** [comment]
good catch, I was quite sure all the meepos were accounted for but I guess I'm blind

I'm marking this as resolved
