### ISSUE TITLE
Meepo clones are not getting magic resistance

### ISSUE THREAD

**Issue by voddov** [ValveSoftware/Dota2-Gameplay#2323]
### Ability name

Divided We Stand

### Description

From the skill description it says all Meepos should get 10%/15%/20% magic resistance, but it's not. 
It only works on main Meepo. It's a bug for a while already, please fix it! Thank you dev.

### Example Match ID (and possibly Timestamp)
easy test

**Comment by DarkoniusXNG** [comment]
Afaik, clones get magic resistance after respawn. That's the important thing that you need to mention.

**Comment by voddov** [comment]
Even then it's still a bug. A skill that requires you to die first to funtion, isn't it a bit stupid?  :)
