### ISSUE TITLE
Can't get rid of custom maps, please help

### ISSUE THREAD

**Issue by Vint8** [ValveSoftware/Dota2-Gameplay#23277]
### Description

My Steam uploads custom Dota maps that i'm not subscribed to. My folder "SteamLibrary\steamapps\workshop\content\570" is about 15gb. It's very essential for me, because i need enough free disk space to play without lags.
I've written to Steam support 3 times, but they haven't helped me, so i'm asking for your help.

- Deleting "SteamLibrary\steamapps\workshop\" folder haven't helped - it uploads again. 
- I have no selected elements in "Workshop Tools"
- I have no subscriptions either in my workshop files or in guides
- I have no custom games in my library in Dota

Having those files takes not only unnecessary disk space, but it also endanger the security of my account.

### Screenshots

![Steam1](https://github.com/user-attachments/assets/94451844-1a9b-43c3-be3c-a45a1b45d081)
![Steam2](https://github.com/user-attachments/assets/50eab638-ce1a-4067-b32e-274346adb4b6)
![Steam3](https://github.com/user-attachments/assets/e62cf141-129a-43ee-9454-17c2e467a5a1)
![Steam4](https://github.com/user-attachments/assets/3d3b162d-58cc-4281-9194-1fefef53e2ee)
![Steam5](https://github.com/user-attachments/assets/3f5d4c75-79a1-4e04-a2d4-773d758ef342)

**Comment by commentator24** [comment]
try disable sync steam cloud in setting
then downloads clear downloads cache
delete ur files again
then restart steam, re-enable sync?

**Comment by Vint8** [comment]
> try disable sync steam cloud in setting then downloads clear downloads cache delete ur files again then restart steam, re-enable sync?

Thanks a lot!

**Comment by Vint8** [comment]
> try disable sync steam cloud in setting then downloads clear downloads cache delete ur files again then restart steam, re-enable sync?

Thanks a lot!
