### ISSUE TITLE
Invoker's Abilities Cannot Be Cast While Channeling

### ISSUE THREAD

**Issue by D00mC4ll3r** [ValveSoftware/Dota2-Gameplay#23292]
### Ability name

Quas, Wex, Exort, Invoke, Ghost Walk

### Description

I am no longer able to cast quas, wex, exort, invoke, or ghost walk while channeling as Invoker. 
At the timestamp, I tried to cast ghost walk and invoke tornado while teleporting to the outpost.
I tested this in demo after the match using town scroll and meteor hammer, and was still unable to cast any of the afore-mentioned spells while channeling either item.

Thank you in advance for your time and effort.

### Example Match ID (and possibly Timestamp)

8087649891 - 12:13

**Comment by seowth** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/23297

This issue also talks about the same problem.

**Comment by D00mC4ll3r** [comment]
Hello!

Thanks for the heads up on that. I appreciate it.

**Comment by SahilValve** [comment]
We've pushed an update that has fixed this. Thanks for reporting.
