### ISSUE TITLE
Invoker - Can no longer change orbs or invoke spells while teleporting

### ISSUE THREAD

**Issue by Garysmoak** [ValveSoftware/Dota2-Gameplay#23308]
### Ability name

Invoke / Quas / Wex / Exort

### Description

With the new Frostivus update, suddenly I am no longer able to change orbs or invoke spells while teleporting. Not sure if this was either intentionally changed without any patch note or if it's an unintended bug from something that was added. I loved this aspect of Invoker that was implemented somewhat recently. Please bring it back!

### Example Match ID (and possibly Timestamp)

8087702198 - 9:48 CT

**Comment by seowth** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/23297

**Comment by seowth** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/23297

This issue also talks about the same problem.

**Comment by SahilValve** [comment]
Thanks for the report, we have a fix being shipped soon.

**Comment by Garysmoak** [comment]
Thank you so much!! Fix just went live
