### ISSUE TITLE
Pudge toggle while ulting

### ISSUE THREAD

**Issue by Calciphoce** [ValveSoftware/Dota2-Gameplay#23303]
### Ability name

Dismember

### Description

Pudge is bugged and can't toggle rot, meat shield, or anything else during dismember. I think it has something to do with the frostivus hat ability channeling. You can see this by my casting of meat shield always going off right after channeling dismember during this game specifically. I tested it out in game to confirm at 15:32.

### Example Match ID (and possibly Timestamp)

8087923454 - 15:05, 15:32

**Comment by MrCemper** [comment]
same

**Comment by southcity4** [comment]
Yep, was actually going to open a ticket until I saw this. Same issue as well - definitely was able to rot after ulting before 2024-Frostivius update.

**Comment by maxxysfm** [comment]
![dota2_sIh9K2R2vP](https://github.com/user-attachments/assets/5879f003-a44d-471c-a3e5-e8837887171a)
Clarification on how to reproduce:

1. Enable the option: **Channeled Abilities Require Hold/Stop**
2. Pick Pudge
3. Use Dismember (Channeled ability) on enemy unit
4. Try to use Rot/Meat Shield

The player should be able to use Rot/Meat Shield, but they can't if the Channeled Abilities Require Hold/Stop is **Enabled**.
**This is in the muscle memory of most Pudge players to use rot during ult so please consider fixing it**. Maybe there are other related issues to the channeling abilities as well.

**Comment by Calciphoce** [comment]
Seems to
