### ISSUE TITLE
Earth Spirit Remnants giving vision without shard

### ISSUE THREAD

**Issue by scorchio22** [ValveSoftware/Dota2-Gameplay#2331]
### Ability name

Stone Remnant

### Description

I have vision around the remnant even without the aghanim's shard. i set one on tier 3 tower mid and saw enemy tinker near it. played in ranked mode. Match ID: 6722968517

### Example Match ID (and possibly Timestamp)

6722968517

**Comment by DarkoniusXNG** [comment]
I think this is fixed. So maybe close it?

**Comment by scorchio22** [comment]
Yes. I had a game and i see it fixed. Closing. Thanks
