### ISSUE TITLE
Invoker bug - you can’t cast abilities while teleporting

### ISSUE THREAD

**Issue by radikter** [ValveSoftware/Dota2-Gameplay#23312]
### Ability name

Quas, Wex, Exort, Invoke

### Description

Invoker bug - you can’t cast abilities while teleporting. The same error occurs during match making.
I provide video. Turn up the sound to make it more noticeable: https://cloud.mail.ru/public/ezit/EgCTMRNXT

### Example Match ID (and possibly Timestamp)

https://cloud.mail.ru/public/ezit/EgCTMRNXT

**Comment by radikter** [comment]
I also noticed that this is the only bug associated with using items and abilities on other characters.

**Comment by adriendelaurens** [comment]
I noticed that too. You can still use Orbs and Invoker during the channeling of Meteor Hammer and capturing outposts, but not Twin Gates. The interesting thing is that the sequence of keys (orbs + invoke) you press during the channeling is executed at the end of it, but not exactly : if you try to reinvoke your 2nd spell and then invoke a new one, you can see orbs changing but only the 2nd invoke is registered, making your former 2nd spell get lost, as if only 1 invoke input could be registered, and therefore using your latest invoke be registered

**Comment by joshmichael23** [comment]
Primal Beast also unable to cast Uproar (with stacks ofc) while channeling Pulverize.

**Comment by SahilValve** [comment]
Thank you for the report, we have a fix being shipped soon.
