### ISSUE TITLE
Teleport Requires Hold/Stop

### ISSUE THREAD

**Issue by OldAkki** [ValveSoftware/Dota2-Gameplay#23326]
### Hero and spell

Bounty Hunter/Dark Willow

### Description

It seems that this feature is currently not working as it is before. Before with this on, you can use shadow walk or shadow realm after casting a tp prompting you to tp in invisible or shadow realm state. Now if this is on, the feature will not allow you to go on Invisible mode or in shadow realm mode while using  a teleport/ twin gate or capturing outpost. But if this is currently off it will allow you to Teleport on shadow walk mode or shadow realm mode but prompting to move will cancel the tp

**Comment by SahilValve** [comment]
We just pushed an update to fix this. Thanks for the report.
