### ISSUE TITLE
Disruptor's W ability 0 cooldown

### ISSUE THREAD

**Issue by Enfield-Li** [ValveSoftware/Dota2-Gameplay#2334]
### Ability name

Glimpse

### Description

This is a [Reddit post](https://www.reddit.com/r/DotA2/comments/wx05sf/disruptors_w_ability_0_cooldown_is_this_cheating/?sort=new) I created showing a clip of Disruptor casting glimpse multiple times in sucession with 0 cooldown

### Example Match ID (and possibly Timestamp)

6722851751 - 22.02 and - 24.10

**Comment by DarkoniusXNG** [comment]
This is fixed. You can close this.
