### ISSUE TITLE
[Tiny] "Majesty of the Colossus", "Sword of the Colossus". Makes Tiny to hold sword incorrectly.

### ISSUE THREAD

**Issue by Polykomodo** [ValveSoftware/Dota2-Gameplay#23392]
### Cosmetic Item Name

Sword of the Colossus

### Description

I think the problem came after the "Frostmoot Tree was added to the game. The tree model was adjusted to match the "Frostmoot Tree" bell. So the issue is that Tiny holds his "Sword of the Colossus" wrong in different phases. In Pebble/Cobble/Monolith stages of the ultimate, you may see them in screenshot below. 

### Example Match ID

*

### Screenshots

This is how it looks now 
![Точечный рисунок](https://github.com/user-attachments/assets/ea4f42cf-3ab3-4780-b5d6-6a60485f8293)

This is how it should look 
![image](https://github.com/user-attachments/assets/53a04232-f577-44c0-bb38-caee33552f48)
![image](https://github.com/user-attachments/assets/51f8cabf-b585-41e3-854e-b05cce0ad458)
![image](https://github.com/user-attachments/assets/0301d20f-8343-4733-8093-cc9006c674f7)

**Comment by Astiberon** [comment]
FIXED
![image](https://github.com/user-attachments/assets/600e1921-54fc-4472-a39a-e469f4c44a81)
![image](https://github.com/user-attachments/assets/db99f31b-8bea-4d0c-9c8b-f3334f950f5b)
![image](https://github.com/user-attachments/assets/7f3d64f3-ffce-4a08-9a2f-aba6556ded39)
