### ISSUE TITLE
[Frostivus 2024] The Crownfall token rewards and the Legacy rewards are locked even after crafting T3 items

### ISSUE THREAD

**Issue by thedarknomad** [ValveSoftware/Dota2-Gameplay#23414]
### Description

The subtitle of the Crownfall tier rewards says "craft 1 Tier III Reward" and selecting any Act I/II/III/IV rewards shows "Tier Locked" on the Frostivus crafting screen. However, I already crafted a T3 Item: the Tormentor. That means since I crafted 1 T3 Item, I should have the Crownfall rewards available.

Same for the Frostivus 2023 legacy items.

### Example Match ID (and possibly Timestamp)

Frostivus 2024

### Screenshots

![frostivus_crownfall](https://github.com/user-attachments/assets/5d5af3bd-193d-4aaa-9335-93e127bb8256)

**Comment by oisinhg** [comment]
you need to craft 2 tier 3 items. the "CRAFT X TIER Y REWARD(S)" text updates based on how many you have crafted before.

you need to craft both the tier 3s to unlock the tier 4s. this is incredibly obvious and it is extremely clear that this is not fit for a github post

**Comment by thedarknomad** [comment]
> "and it is extremely clear that this is not fit for a github post"

Interesting the way you attacked this and instantly answered my thread after hunting down my posts when I said your post is not a bug. Very mature behaviour. 

There is a difference between "you need to craft one more item" and "you need to craft 1 item" and you know it. If you are going to act like a passively aggressive 10 year old kid that takes any post that doesn't agree with their opinion as a personal attack, please go to a different place, not github. Thanks in advance.

**Comment by oisinhg** [comment]
this is not a bug. if you had interacted with this ui page at any other point you would have seen the numbers changing.

**Comment by oisinhg** [comment]
this is the latest post on this github i didnt "track" anything down.

**Comment by commentator24** [comment]
not a bug. you need to craft 2 tier 3 to craft tier 4. and you only crafted tormentor
oisin is right, the number craft x tier will change
should close issue
