### ISSUE TITLE
Tier 4 Frostivus reward incorrectly needs 2 tier 3 crafts despite requiring only 1 as it says in the description

### ISSUE THREAD

**Issue by bjah23** [ValveSoftware/Dota2-Gameplay#23427]
### Description

progress bar shows 2, but says only needed 1? hello?

### Screenshots

![xCapture](https://github.com/user-attachments/assets/7a3952f9-5e98-430b-92db-7b679e577132)

**Comment by commentator24** [comment]
#23414
not a bug. you probably missed it, but it clearly says craft 2 before.
Craft X number will change depending on your progress. 
Your progress is 1/2. you made 1, and now the text change to craft 1 tier III instead of craft 2 tier III.
should close issue.
