### ISSUE TITLE
extracts for frostivus forge not given out

### ISSUE THREAD

**Issue by fierdanxpas** [ValveSoftware/Dota2-Gameplay#23444]
### Description

I perform the actions necessary to obtain extracts, it even shows me during the game that I receive them, but after the game everything is still zero
I've attached screenshots, the first one shows the problem, the second one shows that the games were already there after the update and I definitely should have received something

### Screenshots

![image](https://github.com/user-attachments/assets/5b252bf7-d6e4-482a-8c00-059ebb7dbb2a)
![image](https://github.com/user-attachments/assets/2a0925d4-263c-4e2a-bd33-e84d364786ee)

**Comment by commentator24** [comment]
arent you in low priority? in LP it will look like you still can get rewards etc but after game is over you dont get anything
should close issue not a bug i think

**Comment by fierdanxpas** [comment]
> arent you in low priority? in LP it will look like you still can get rewards etc but after game is over you dont get anything should close issue not a bug i think
I'll exit low priority now and try to get it again
thanks for the help
