### ISSUE TITLE
Basher doesn't work on Kez

### ISSUE THREAD

**Issue by bilbil22** [ValveSoftware/Dota2-Gameplay#23464]
### Item name

Basher

### Description

Tried in Demo, Kez didn't make a single bash in over 100 attacks with basher.

### Example Match ID and Timestamp

Demo

**Comment by Munkhtulga27** [comment]
Kez cannot proc basher while he is in his Sai discipline 
![image](https://github.com/user-attachments/assets/557e2c4a-fcc4-4203-a030-908a3f941246)

**Comment by bilbil22** [comment]
Ur right :) its my mistake then. The ticket is DONE. :))))  Have a good day.
