### ISSUE TITLE
Primal Beast - Level 25 Talent Pulverize Pierces Magic Immunity

### ISSUE THREAD

**Issue by shaileshgarg** [ValveSoftware/Dota2-Gameplay#2359]
### Ability name

Pulverize

### Description

Primal Beast - Level 25 Talent Pulverize Pierces Magic Immunity, changes the Spell Damage type to Pure. From the Talent wording it should remain Magic, but pierce magic immunity.

### Example Match ID (and possibly Timestamp)

-

**Comment by Dota-Exp** [comment]
This will be fixed in the next update
