### ISSUE TITLE
Silencer talents' bugs (Arcane Curse cannot be dispelled and +2 Glaives of Wisdom Bounces)

### ISSUE THREAD

**Issue by Wild-Magic-Sorcerer** [ValveSoftware/Dota2-Gameplay#2361]
### Ability name

Arcane Curse, Glaives of Wisdom

### Description

Silencer's level 20 talent (Arcane Curse cannot be dispelled) is bugged - Arcane Curse still can be dispelled with bkb-like abilities (Juggernaut's Blade Fury and Lifestealer's Rage, for example). Interestingly enough, each successful cast of bkb-like abilities dispels only one stack of undispellible Arcane Curse debuff. BKB itself no longer dispels Arcane Curse - it was recently fixed.

UPD: Found out several others abilities and upgrades that still dispels undispellible Arcane Curse: Huskar's ult, Pangolier's ult and shard ability, Elder Titan's aghs upgrade. Not sure if that's all of them. 

Silencer's level 25 talent (+2 Glaives of Wisdom Bounces) is also bugged with invisible enemy units under any source of detection - glaives bounces flies towards them, but neither deals any damage or steal intelligence from them.

**Comment by TheUnholyWrath** [comment]
#2027

**Comment by TheUnholyWrath** [comment]
I can't replicate Arcane Curse being dispelled with bkb-like abilities, seems like it has been fixed.

**Comment by Wild-Magic-Sorcerer** [comment]
> I can't replicate Arcane Curse being dispelled with bkb-like abilities, seems like it has been fixed.

Yes. It was fixed shortly after the release of the 7.32 patch. Yet Glaives of Wisdom bug was not fixed still.

**Comment by shaileshgarg** [comment]
Can we close this, given another issue exists for Level 25 bug.

**Comment by Wild-Magic-Sorcerer** [comment]
> Can we close this, given another issue exists for Level 25 bug.

Yeah. I guess so.
