### ISSUE TITLE
If Dark Willow denies rune while being in shadow realm projectile is invisible

### ISSUE THREAD

**Issue by GarnierDeNaplouse** [ValveSoftware/Dota2-Gameplay#240]
### Ability name

Shadow Realm

### Description

If Dark Willow denies rune while being in shadow realm projectile is invisible and music still plays even tho she's not in shadow realm

### Example Match ID (and possibly Timestamp)

don't have one, sry, easy to repeat in demo mode

**Comment by cjal95** [comment]
Tested in both demo and local lobby.
Steps to reproduce:
1. Spawn/find rune
2. Cast shadow realm
3. While in shadow realm issue attack command on the rune

Expected result should be that the projectile denying the rune is visible but that's not the case.

**Comment by eismant** [comment]
I've got an example for you. 

Match ID: 6616146298, time 6:10. Short video with dire and radiant view in a replay: https://youtu.be/djEYdPLcZo8

**Comment by Aluerie** [comment]
Same happens for dropped items : no projectile if DW attacks one from Shadow Realm

**Comment by Dota-Exp** [comment]
Will be fixed in upcoming update
