### ISSUE TITLE
Tempest Double Bug

### ISSUE THREAD

**Issue by pokupz** [ValveSoftware/Dota2-Gameplay#2415]
### Ability name

Tempest Double

### Description

Before 7.32 update
Everytime there is a mute ability in enemy team (eg: Disruptor Ulti with Aghs or Doom ulti), whenever i summon tempest double, i can't control the ulti unit until i highlight it and move it, im pretty sure its a bug.

As even if my hero is not in disruptor ulti, i still face the same issue. Or as long as i get Doom ulti even once in the game, subsequent summons of tempest double ulti faces the same issue, regardless if i am summoning my ulti.

After 7.32 update
Everytime i summon tempest double, it has a muted ambient effect on the summoned unit, and have to highlight it before contorlling it. Selecting all other units key does not work. Have tested with other accounts, hence its not only my problem.

### Example Match ID (and possibly Timestamp)

622626565

**Comment by beng1302** [comment]
Same issue here. Once tempest double is created it can only be selected by tab cycling or by clicking on the double at the base of its model, not by normal clicking select or by select all other units hotkey. The hitbox available to select seems to be smaller until the fountain immunity buff has gone. Once the tempest double has been selected once it can now be selected and controlled by normal methods aka select all other units or by clicking on the double, the selection hitbox also gets fixed. Incredibly frustrating.

Match id 6725990619 but it also works in demo mode.

**Comment by Dota-Exp** [comment]
This will be fixed in the next update
