### ISSUE TITLE
Tusk snowball permanently disabled after Walrus Punch!

### ISSUE THREAD

**Issue by ProphetDeSol** [ValveSoftware/Dota2-Gameplay#2420]
### Ability name

Snowball

### Description

After using Snowball and a Walrus Punch! on an enemy Spirit Breaker, the ability gets permanently stuck on Launch Snowball. It seems as if the game believes I'm constantly in 
![Tusk bug](https://user-images.githubusercontent.com/112201361/186971209-9a87a183-ff2a-4588-912c-26599eb1ef83.jpg)
the snowball.

### Example Match ID (and possibly Timestamp)

6725721117 - 13:10

**Comment by TheUnholyWrath** [comment]
#2343 Its another Planar Pocket bug

**Comment by RRFreemanArchitect** [comment]
Confirmed: Match ID 6729332231

**Comment by SaadLodhi35** [comment]
Another match where this happened. 
6734400669

**Comment by Dota-Exp** [comment]
Will be fixed in upcoming update
