### ISSUE TITLE
SB Planar Pocket + Tusk Snowball

### ISSUE THREAD

**Issue by GrinnValesti** [ValveSoftware/Dota2-Gameplay#2429]
### Ability name

Snowball

### Description

SB uses shard Planar Pocket and enemy Tusk uses Snowball...

1. Snowball directly to SB = Snowball doesn't get blocked. Snowball turns into "Launch Snowball" and doesn't revert back ever, thus Snowball can never be used again. Game-breaking bug.

2. Snowball to enemy near SB = Snowball doesn't get blocked, and a 2nd Snowball is cast on SB but without the roll up (Stationary) animation. Snowball again turns into "Launch Snowball" and clicking it doesn't do anything. Just have to wait for the roll up to finish and the Chase animation begins (no stun). Afterwards, "Launch Snowball" reverts back to Snowball and it is useable again. This is nothing major, but just weird interactions.

Attached is scenario 1.  and this is a friend's game, not mine.
![image](https://user-images.githubusercontent.com/55971849/187014428-53f5a031-acca-4d8a-ba09-90cef91bf842.png)

Can be replicated in Demo. Refresher doesn't fix.

### Example Match ID (and possibly Timestamp)

6726227426

**Comment by TheUnholyWrath** [comment]
#2420 #2343

**Comment by RRFreemanArchitect** [comment]
Confirmed match ID: 6729332231

**Comment by Dota-Exp** [comment]
Will be fixed in upcoming update
