### ISSUE TITLE
Witch Doctor. Aghs death ward's bounces got stuck in the invisible not moving units

### ISSUE THREAD

**Issue by yurok0900** [ValveSoftware/Dota2-Gameplay#244]
### Ability name

Death Ward with Aghanim's scepter

### Description

Bounces got stuck if the target of the first bounce is not moving and is invisible. After losing the invisibility effect bouncing simultaneously continues in the next target.
 
https://user-images.githubusercontent.com/83572024/171745878-0bbe87d3-bc8d-43b9-8f11-4ebf2efd333f.mp4

### Example Match ID (and possibly Timestamp)

Video attached

**Comment by Dota-Exp** [comment]
This will be fixed in the upcoming update. Thank you
