### ISSUE TITLE
Silencer's passive does not work after kill

### ISSUE THREAD

**Issue by Runnerblade84** [ValveSoftware/Dota2-Gameplay#2444]
### Ability name

intellect permanent steal

### Description

Silencer killed zeus, he was alive with Glaives of wisdom activated from beginning, and he does not took a stack

### Example Match ID (and possibly Timestamp)

6727669566 - 9:06

**Comment by TheUnholyWrath** [comment]
Silencer needs to get the last hit on a kill to steal int if he is not in range. The ranged creep got the last hit, so Silencer does not steal int
![20220828081701_1](https://user-images.githubusercontent.com/46859977/187049878-f723cbf1-42d3-4993-b7e7-b3dcf2c0a74a.jpg)

**Comment by TheUnholyWrath** [comment]
![20220828081701_1](https://user-images.githubusercontent.com/46859977/187049940-1c72da59-f8e3-40c7-b6cf-44cdbda20f95.jpg)
The ranged creep killed Zeus. Silencer needs to get the last hit on kills he is not in range for, otherwise he won't steal int.

**Comment by Runnerblade84** [comment]
> ![20220828081701_1](https://user-images.githubusercontent.com/46859977/187049940-1c72da59-f8e3-40c7-b6cf-44cdbda20f95.jpg)
> 
> The ranged creep killed Zeus. Silencer needs to get the last hit on kills he is not in range for, otherwise he won't steal int.

Thanks! Btw the game said that silencer got the kill, so the mistake.
