### ISSUE TITLE
Levelling tether on IO while tethered doesn't work.

### ISSUE THREAD

**Issue by RileyPeuter** [ValveSoftware/Dota2-Gameplay#2449]
### Ability name

Thether - Untether

### Description

Currently you're able to level up both tether and untether, however when i played a game, I put points into untether, and it didn't carry over to the tether ability, meaning that i burnt 3 skill points. 

The abilities might not be updating each other correctly?

### Example Match ID (and possibly Timestamp)

6727794656

**Comment by DarkoniusXNG** [comment]
Before posting bugs, check if they are already reported:

#2449
#2428 
#2413 
https://github.com/ValveSoftware/Dota2-Gameplay/issues/2406
https://github.com/ValveSoftware/Dota2-Gameplay/issues/2401
https://github.com/ValveSoftware/Dota2-Gameplay/issues/2383
https://github.com/ValveSoftware/Dota2-Gameplay/issues/2373
https://github.com/ValveSoftware/Dota2-Gameplay/issues/2371
https://github.com/ValveSoftware/Dota2-Gameplay/issues/2364
https://github.com/ValveSoftware/Dota2-Gameplay/issues/2351
https://github.com/ValveSoftware/Dota2-Gameplay/issues/2347
https://github.com/ValveSoftware/Dota2-Gameplay/issues/2302
https://github.com/ValveSoftware/Dota2-Gameplay/issues/2258

Maybe we should organize a battle royale of ignorance for you guys.

**Comment by shaileshgarg** [comment]
Fixed in Today's Update.

**Comment by Dota-Exp** [comment]
This will be fixed in the next update
