### ISSUE TITLE
Rubic can steal decay twice

### ISSUE THREAD

**Issue by JackNewley** [ValveSoftware/Dota2-Gameplay#2450]
### Ability name

Spell steal

### Description

Rubic w aghs can steal decay twice, taking both slots sharing a cooldown.
Tested alch through beast man and couldnt steal 2 of same spell.

### Example Match ID (and possibly Timestamp)

6727974828 sometime after 25 minute

**Comment by TheUnholyWrath** [comment]
Seems like this has been fixed, you can close this issue
