### ISSUE TITLE
Hoodwink's Sharpshooter gives both Decoy and Boomerang with Shard only

### ISSUE THREAD

**Issue by BlueMageBrilly** [ValveSoftware/Dota2-Gameplay#2451]
### Description

The Ability Draft mode does not properly change Decoy to being a new Scepter ability, but Boomerang is still a shard . It lists it properly once you're in game, but in the Ability Draft ... drafting, it lists them as their old set with Boomerang as Scepter and Decoy as Shard. But obtaining Shard actually gave me both; I have no idea if getting Scepter in Ability Draft would have given me them twice, or would have crashed the game, so I didn't get it to check. Felt a bit cheap to have both spells. 

### Example Match ID (and possibly Timestamp)

6727976351 20:35

**Comment by RGBKnights** [comment]
Please help tag post title with [Ability Draft].
