### ISSUE TITLE
Elder titan lvl 20 lvl talned DONT work 

### ISSUE THREAD

**Issue by Oracleseesall** [ValveSoftware/Dota2-Gameplay#2455]
### Ability name

Natural order

### Description

Elder titan lvl 20 lvl talent (+100 natural order aoe) dont work on astral spirit.
Elder titan himself gets bonus +100 aoe natural order from talant, but  NOT his astral spirit natural order aoe.
Checked just 1 min ago.

Ive linked match id. But u can check it everywhere, lobby etc

### Example Match ID (and possibly Timestamp)

6718287360

**Comment by Dota-Exp** [comment]
This will be fixed in the next update
