### ISSUE TITLE
Enter a short summary here!

### ISSUE THREAD

**Issue by Ziryorition** [ValveSoftware/Dota2-Gameplay#2456]
### Ability name

"Snowball" (tusk) with "Planar pocket" (spirit breaker)

### Description

Using Snowball rolling onto any target that affected by Planar pocket causing the snowball ability to be stuck onto "Lauching the snowball" making it not be able to be usable for the rest of the game

right at 14:45 of the replay that has given is when the bug that occurs

### Example Match ID (and possibly Timestamp)

6728647697

**Comment by TheUnholyWrath** [comment]
This has been fixed, please close this issue.
