### ISSUE TITLE
Slarks shard not working the same way the ultimate works in chronosphere.

### ISSUE THREAD

**Issue by FughyTC** [ValveSoftware/Dota2-Gameplay#2465]
### Ability name

Depth Shroud

### Description

While in chrono under depth shroud's effect [!!you are visible and can be targeted!!], even though you still have the regen from ult(which should mean that you are invisible, but you aren't).
When in chrono under ultimate you cannot be targeted at all, which is the way it should be.

### Example Match ID (and possibly Timestamp)

6729165039 - 35:10 and 38:40

**Comment by DarkoniusXNG** [comment]
Duplicate: #1907

**Comment by FughyTC** [comment]
Since its a duplicate can it be deleted?

**Comment by yckmm** [comment]
Just close this issue "as not planned".
