### ISSUE TITLE
Stormcrafter removes veno shard debuff.

### ISSUE THREAD

**Issue by Alexastias** [ValveSoftware/Dota2-Gameplay#2467]
### Item name

Stormcrafter

### Description

From how I understand it should work, Stormcrafter is not interacting correctly with Venomancer's new shard (Latent Toxicity) - it completely removes the debuff when used - no damage is taken or stun applied.

### Example Match ID and Timestamp

6729221363 - 40:55

**Comment by DarkoniusXNG** [comment]
How does it behave with Euls and Windwaker? 7.32 patch notes for Euls and Windwaker specifically say: "Now purges first, then applies Cyclone modifier". Maybe veno shard ability is one of the reasons for this?

**Comment by TheUnholyWrath** [comment]
Euls and Wind Waker purge first. Stormcrafter doesn't
![20220829051407_1](https://user-images.githubusercontent.com/46859977/187090833-f76917a8-ac15-4140-b76a-c9d3dcc9a9db.jpg)
![20220829051653_1](https://user-images.githubusercontent.com/46859977/187090837-5775371e-176f-4885-97e5-c5d88fed504b.jpg)

**Comment by Dota-Exp** [comment]
This will be fixed in the next update
