### ISSUE TITLE
QOL:  Icon for the Spirit bear (lone druid) on minimap

### ISSUE THREAD

**Issue by Avarise831** [ValveSoftware/Dota2-Gameplay#247]
### Description

Make Spirit Bear have an icon appear on the mini map please 

### Screenshots

![lonedruid](https://github.com/ValveSoftware/Dota2-Gameplay/assets/37029303/fc047f01-486e-4e97-8085-4307f50d26bb)
![lone druid2](https://github.com/ValveSoftware/Dota2-Gameplay/assets/37029303/01b70b09-1e4d-447d-bef3-271f421e54da)
at least make it similar like meepo/arc
![arcmeepo](https://github.com/ValveSoftware/Dota2-Gameplay/assets/37029303/6396519a-eb54-45c6-8a64-4f5fc35e0f30)

**Comment by ogremager** [comment]
Please its already fine no need update icon for it

**Comment by shaileshgarg** [comment]
Would be a nie QOL feature.

**Comment by Avarise831** [comment]
Thank you Valve Developers
