### ISSUE TITLE
Faceless Void Talent value missing

### ISSUE THREAD

**Issue by AHollowedHunter** [ValveSoftware/Dota2-Gameplay#2475]
### Hero and spell

Faceless Void - Level 25 Talent - Backtrack

### Description

The Vietnamese tooltip is missing the value, it appears to use the incorrect placeholder tag of "value" rather than "dodge_chance_pct" used in other language files

### Screenshots

![image](https://user-images.githubusercontent.com/45659989/187096510-f449c414-77b4-4d75-a1b0-bbb465fff6a3.png)

**Comment by Dota-Exp** [comment]
This will be fixed in the next update
