### ISSUE TITLE
Warlock's ultimate lost his pre-cast effect

### ISSUE THREAD

**Issue by SnabrielSnarsch** [ValveSoftware/Dota2-Gameplay#2478]
### Ability name

chaotic offering

### Description

his ultimate is now stunning enemies immediately without the pre-cast effect but this wasn't documented in the patch notes

Before (with pre cast)

https://user-images.githubusercontent.com/106764413/187102053-f3f1f2d3-1f26-4c40-87e1-26287e04ac47.mp4

Now (no pre cast, immediate stun)

https://user-images.githubusercontent.com/106764413/187102061-334ba77a-bdfa-4660-95a6-ee15554a2aa4.mp4

### Example Match ID (and possibly Timestamp)

any

**Comment by Dota-Exp** [comment]
This will be fixed in the next update
