### ISSUE TITLE
UNIT NOT AFFECTED BY CHRONOSPHERE WHILE RIDING CENTAUR'S CART

### ISSUE THREAD

**Issue by Zoomichi** [ValveSoftware/Dota2-Gameplay#2482]
### Ability name

Hitch A Ride - Centaur's new scepter skill

### Description

Hitch A Ride units not affected by Chronosphere. Lost game because of CM ult

https://user-images.githubusercontent.com/47381251/187105902-37d4b155-c935-4805-979d-08707893e3bc.mp4

### Example Match ID (and possibly Timestamp)

6724812546 - 34:08

**Comment by Zoomichi** [comment]
Tested other AoE skills in demo. Tried Slardar's AoE stun, it stunned unit on cart. Alche's Acid Spray also damages unit on cart.

**Comment by Dota-Exp** [comment]
This will be fixed in the next update
