### ISSUE TITLE
IO "Break Tether" can be leveled up independently from "Tether"

### ISSUE THREAD

**Issue by Stuntminer202** [ValveSoftware/Dota2-Gameplay#2483]
### Ability name

Tether

### Description

Match ID: 6729827352
Leveling Break Tether (i.e. trying to level Tether while actively tethered to someone) will increase the level of Break Tether, but not Tether. Leveling Tether will increase the level of Break Tether correctly, but not the other way around. It is _not_ a visual bug, and affects the mana/health share and slow, as easily shown by the level of tether displayed on the HUD, and the slow applied on creeps. In the linked game, I put 2 points into Break Tether, making it level 3 (It was already leveled from leveling Tether), yet Tether itself stayed at level 1. This worked correctly before 7.32.
Thank you. 

### Example Match ID (and possibly Timestamp)

6729827352

**Comment by TheUnholyWrath** [comment]
Its been fixed. Please close this

**Comment by Stuntminer202** [comment]
Posted this right before the patch came out. Can confirm it is fixed.
