### ISSUE TITLE
ICE BLAST HIT HEROES STILL HEALING LIKE WTF 

### ISSUE THREAD

**Issue by godx777** [ValveSoftware/Dota2-Gameplay#2490]
### Ability name

ICE BLAST 

### Description

ICE BLAST SHOULDNT HEAL OR REGEN EXCEPT SUPERNOVA, TIMELAPSE, SUNDER

HUSKAR AND SF HEALING LIKE NOTHING HAPPNED 

### Example Match ID (and possibly Timestamp)

6730001824 - 17:13

**Comment by TheUnholyWrath** [comment]
Ice Blast isn't stopping HP Regen. Pretty massive AA bug, needs fixing

**Comment by Hurricane14** [comment]
Probably part of the same problem as in #2486

**Comment by shaileshgarg** [comment]
All healing is doubled in Game.

**Comment by shaileshgarg** [comment]
This is fixed.
