### ISSUE TITLE
Doom is able to Doom Spirit Breaker due to SB shard

### ISSUE THREAD

**Issue by breadman-bread** [ValveSoftware/Dota2-Gameplay#2491]
### Ability name

Doom Aghs + Spirit Breaker shard interaction

### Description

When Doom uses Doom on himself near  Spirit Breaker  as he uses his shard ability, Planar Pocket, Spirit Breaker is doomed, silencing and muting him and is able of silencing and muting his teammates.

### Example Match ID (and possibly Timestamp)

6730043416 - 28:05

**Comment by Dota-Exp** [comment]
This will be fixed in the next update
