### ISSUE TITLE
Disruption gets redirected by friendly Spirit Breakers.

### ISSUE THREAD

**Issue by Undead94100** [ValveSoftware/Dota2-Gameplay#2497]
### Ability name

Disruption

### Description

Shadow Demon's Disruption gets redirected to an ally Spirit Breaker when another ally within Planar Pocket is targeted. Works as intended with enemy Spirit Breakers.

### Example Match ID (and possibly Timestamp)

6727339908 (18:37)

**Comment by Dota-Exp** [comment]
This will be fixed in the next update
