### ISSUE TITLE
Ursa Aghs Appears to not allow Ursa to cast Enrage during disables

### ISSUE THREAD

**Issue by jaredeg** [ValveSoftware/Dota2-Gameplay#2506]
MATCH ID 6731287588
 
Seems like most disables were still disabling Ursa Aghs.

Void Spirit Q (cant aghs) unsure if you should be able to
But the rest you should be able to unless I am missing something.

**Comment by Dota-Exp** [comment]
Enrage can be cast while stunned, slept and taunted, but not while hexed or silenced.
