### ISSUE TITLE
Bug with Stormcrafter and Venomancer new shard

### ISSUE THREAD

**Issue by gablogian** [ValveSoftware/Dota2-Gameplay#2516]
### Description

I tested the new Veno shard (which deals some DPS and slows you and if you dispel it it will stun you for 3 sec) to see the effect when using a variety of dispells (euls, wind waker, aeon, bkb, lotus, manta, satanic, witchbane, flicker, force boots, legion dispell, shadow demon, omni, oracle, etc etc) and in all of them the enemy hero gets stunned with the exception of the active of Stormcrafter.

**Comment by TheUnholyWrath** [comment]
#2467
