### ISSUE TITLE
Primal Beast Pulverize and Pudge Dismember Teleports Target

### ISSUE THREAD

**Issue by Adadadananana** [ValveSoftware/Dota2-Gameplay#2542]
### Ability name

Pulverize

### Description

When Primal Beast is ulting a target (hero or creep) and Pudge uses Dismember on the same target, the target will teleport around the map like crazy. It does not work if Pudge Dismembers first. I have tested this in demo hero and can easily reproduce this behaviour. Attached is a video of it happening in game.

https://user-images.githubusercontent.com/74089734/187618153-7d369160-22fc-425e-ae9d-4b83a4347526.mp4

*edit* turns out it also works if the Pulverize target is Dueled.

### Example Match ID (and possibly Timestamp)

6733251304 - 17:37

**Comment by Usera2** [comment]
Another Sample: ID 6733366832, Min 19
