### ISSUE TITLE
Shadow demon ulty against invulnerable opponents bug. 

### ISSUE THREAD

**Issue by Plyabla** [ValveSoftware/Dota2-Gameplay#2546]
### Ability name

Demonic purge

### Description

ability going on cooldown if target invulnerable. In my understanding, it should remain on invulnerable units, but for some reason it just goes on cooldown and the effect does not appear. this only works correctly if you use ulty for invulnerability which can be cleared.

https://user-images.githubusercontent.com/15859292/187669909-5048957d-f140-478d-870f-3ac49dead392.mp4

### Example Match ID (and possibly Timestamp)

-

**Comment by TheZett** [comment]
This is intended.

Nullifier got the same treatment, where the debuff is only applied to invulnerable units, if SD ult / Nullifier can dispel the source of the invulnerability.

This was added so people cannot pre-cast these abilities on units affected by Song of the Siren and deny them the ability to use certain abilities.
