### ISSUE TITLE
Been awarded Aghanim ability before purchasing the scepter

### ISSUE THREAD

**Issue by talk1about** [ValveSoftware/Dota2-Gameplay#2554]
### Description

Played Zeus on a turbo game and i've been awarded nimbus ability without purchasing the scepter

### Example Match ID (and possibly Timestamp)

6734265310 - 12:29

### Screenshots

![20220831220409_1](https://user-images.githubusercontent.com/95692330/187763904-58d69b3b-3645-4699-bada-c3b2d42cf180.jpg)

**Comment by TheUnholyWrath** [comment]
Alchemist gave it to you at 12:30

**Comment by talk1about** [comment]
> Alchemist gave you a scepter at 12:30

ouch, i have totally missed that. thanks!
