### ISSUE TITLE
Bounty Hunter Shard (upgarding SHadow Walk) will now break channeling spells

### ISSUE THREAD

**Issue by sinampv** [ValveSoftware/Dota2-Gameplay#2563]
### Ability name

Bounty Hunter Shard

### Description

Bounty Hunter Shard (Upgrading SHADOW WALK) will now break channeling spells after buying shard .

### Example Match ID (and possibly Timestamp)

s

**Comment by sinampv** [comment]
why is there still no response , it is a major issue needs to be fixed , it makes shard for bounty less efficent .

**Comment by shaileshgarg** [comment]
Haven't tested this but did the bounty have level 15 talent silence on shadow walk hit?

**Comment by sinampv** [comment]
anyone seeing into this issue ? Isn't it and urgent matter when the one of the main features of the skill vanishes after the upgrade ?

**Comment by Dota-Exp** [comment]
Will be fixed in the upcoming update. Thank you.
