### ISSUE TITLE
Meepo getting his 4th clone before ult lvl 3

### ISSUE THREAD

**Issue by SnabrielSnarsch** [ValveSoftware/Dota2-Gameplay#2564]
### Ability name

Divided we stand

### Description

meepo got his 4th clone at lvl 12
this shouldn't be possible

https://user-images.githubusercontent.com/106764413/187825889-b7e743c5-4c59-40e6-8295-954913e98718.mp4

### Example Match ID (and possibly Timestamp)

6734638659 -11:51

**Comment by SnabrielSnarsch** [comment]
btw i know this is out of scope, but the guy whos playing meepo is a script user, and here is his steam profile https://steamcommunity.com/profiles/76561198121878767/

**Comment by jess-hermosa** [comment]
this bug also occurs to me, im not a script user

**Comment by BMW325iLSX** [comment]
I as well do not script.  
Match ID: 6734871114
Minute 10.

**Comment by voddov** [comment]
Just saw this bug in a high ranked game, as a Meepo enjoyer i was so mad, shame on those bug abusers. >:(

**Comment by shaileshgarg** [comment]
Meepo Winrate is up 10%

**Comment by uramer** [comment]
> this bug also occurs to me, im not a script user match-id: 6734713161 time: 26.56
> 
> how to replicate the bug: get meepo to level 4, dont upgrade any other skill yet, only upgrade the ult. click the clone, upgrade some skill. you will get another meepo

To clarify, you don't actually need to keep a skill point. The extra clone appears the first time you level up a spell on a clone, so you could do it e. g. on level 5, even by playing normally up to that point.

**Comment by Nathanael-Valve** [comment]
Fixed as of the BP update.
