### ISSUE TITLE
one more meepo

### ISSUE THREAD

**Issue by dauay** [ValveSoftware/Dota2-Gameplay#2575]
### Ability name

divided we stand

### Description

was playing turbo and found that one. after learnin ultimate at one point i get 2 meepos instead of one. i was dyuing with 2 meepo, and after death reborn with 3. that it, hope u'll found  a bug, coz its kinda imbalance

### Example Match ID (and possibly Timestamp)

6735595045 - 04:40

**Comment by Nathanael-Valve** [comment]
fixed
