### ISSUE TITLE
+1 Meepo bug

### ISSUE THREAD

**Issue by helloGameGuy** [ValveSoftware/Dota2-Gameplay#2577]
Steps to reproduce (works in demo mode as well)
1. Level up to level 4 without putting any points into ransack (can still skill poof)
1. On level 4, put 1 point in Divided we stand
1. Select your clone and put 1 point in Ransack
1. Suddenly you have 3 meepos

Expected behaviour
1. Level up to level 4 without putting any points into ransack (can still skill poof)
1. On level 4, put 1 point in Divided we stand
1. Select your clone and put 1 point in Ransack
1. You still have 2 meepos

Example match id 6735617464 (please refund mmr :joy:)

**Comment by ErikHumphrey** [comment]
Worth noting you can't do Step 3 until you hit Level 5

**Comment by Nathanael-Valve** [comment]
Fixed.
