### ISSUE TITLE
No Rangefinder on New Nature's Prophet Aghs

### ISSUE THREAD

**Issue by ndrewGele** [ValveSoftware/Dota2-Gameplay#2583]
### Hero and spell

Nature's Prophet - Curse of the Oldgrowth

### Description

When hovering the spell, no green circle appears to indicate range of spell. The tooltip says 1200 units (IIRC), but that's not particularly helpful, especially to newer players.

### Screenshots

N/A

**Comment by TheUnholyWrath** [comment]
This has been fixed, you can close this issue
