### ISSUE TITLE
Error msg: Begin has already been called without an intervening render when try to get back to game after using task switcher to minimize game

### ISSUE THREAD

**Issue by Ziwei-Jia** [ValveSoftware/Dota2-Gameplay#2586]
![2NAIXC0PS5 $V@ _{ZKAOQE](https://user-images.githubusercontent.com/72219297/188019551-b88326f0-19b9-4e87-b4a9-fd3abab3d64c.png)

**Comment by Ziwei-Jia** [comment]
DX-11

**Comment by Slir3x** [comment]
same problem

**Comment by lbrdev** [comment]
same here

**Comment by Yurez23** [comment]
Found a way to fix it:
In graphic settings must choose "Current screen resolution" instead of "Advanced settings"

**Comment by Ziwei-Jia** [comment]
> Found a way to fix it: In graphic settings must choose "Current screen resolution" instead of "Advanced settings"

Works for me but this issue still needs to be solved.

**Comment by Sagragoth** [comment]
Confirmed on the minipatch that just dropped, still occuring on build 9436073

**Comment by bloodsign** [comment]
> Found a way to fix it: In graphic settings must choose "Current screen resolution" instead of "Advanced settings"

Issue still occurs even after setting to "Current screen resolution"

**Comment by markcaldropoli** [comment]
> > Found a way to fix it: In graphic settings must choose "Current screen resolution" instead of "Advanced settings"
> 
> Issue still occurs even after setting to "Current screen resolution"

After changing to "Current screen resolution" and applying the changes it crashes but seems to no longer crash after relaunching the game for me

**Comment by pneuma2121** [comment]
Esa configuracion corresponde a la de dota 2 (ingame), el error no deja abrir siquiera el juego para llegar alli

**Comment by sandrex0515** [comment]
> Confirmed on the minipatch that just dropped, still occuring on build 9436073

Issue still occurs

**Comment by wuno** [comment]
Same problem for me. Changed settings to “Current screen resolution” and crashed. Stopped crashing once I relaunched, but now my client is borderless.

**Comment by ttm43** [comment]
same problem for me.

**Comment by FeelGD** [comment]
After changing to "Current screen resolution" and applying the changes, it crashes. It seems not to crash anymore after relaunching the game after the change has been applied
İts worked

**Comment by GuilhermeFSCampos** [comment]
> > Found a way to fix it: In graphic settings must choose "Current screen resolution" instead of "Advanced settings"
> 
> Works for me but this issue still needs to be solved.

Only worked for me after changing to vulkan.

**Comment by RaphaelDDL** [comment]
Having the same: 

- Win10 Pro
- AMD Ryzen 7 5800X, RTX3060
- Rendering: DX11, All options on except Vsync
- Advanced Video: 16:9, 2560x1080 @ 75hz, Exclusive Fullscreen

Using the suggested fix "use my monitor settings" crashes then does not crash anymore, but now window type is Borderless Window

**Comment by sosiuk** [comment]
1. change screen resolution on my monitor (by control panel)
2. open Dota and selec "current screen resolution" and next "aply"
3. fix
4.

**Comment by jhriverasa** [comment]
I think this is already fixed with the last update.

**Comment by Nathanael-Valve** [comment]
Should be fixed.
