### ISSUE TITLE
Missing Set Names on Hero Loadout (low priority)

### ISSUE THREAD

**Issue by ajrendas** [ValveSoftware/Dota2-Gameplay#259]
### Description

The following cosmetics are missing set names on the Hero Loadout configuration screen:

Winter Lineage Sets - Cannot select any of the sets
Spring Lineage Sets - Cannot select any of the sets
Disruptor: Upland Pride - Cannot select set
Axe: Carnage of the Endless Hunt - Cannot select set
Ogre Magi: Stonebreak Excavators - Cannot select set
Nyx: Sapphire Crab - Cannot select set
Puck: Luminous Scarab - Cannot select set
Tusk: Eternal Icebreaker - Cannot select set
Enchantress: Song of the Solstice - Cannot select set
Weaver: Dimension Ripper - Cannot select set
Viper: King of the Corrupted Nest - Cannot select set
Winter Wyvern: Aurora's Pyre - Cannot select set
Faceless Void: Augur of Oblivion - Cannot select set
Pugna: Furious Nethergeist - Can select set, doesn't lock in
Shadow Fiend: Murder of Souls - Cannot select set
Treant Protector: Haven of the Hinterheart - Cannot select set

**Comment by NMOTH** [comment]
Could you please provide sample screenshot of this issue?

Is this exclusive to single draft for you? Are you able to see if happens in other modes?

**Comment by NMOTH** [comment]
> Hey,
> 
> This is on the Hero Loadout screen when you select cosmetics and related to not being able to pick the set, not related to single draft mode or a specific game mode.
> 
> Screenshots attached for Weaver Dimension Ripper, it shows only 1 set owned, can only pick 1 set, but I also own the Dimension Ripper Set that is not shown.
> 
> Hope that is clear ![20220603010637_1](https://user-images.githubusercontent.com/106782983/171760305-89a59993-2478-4711-90da-1dfb962f4464.jpg) ![20220603010621_1](https://user-images.githubusercontent.com/106782983/171760307-edef7149-ea9e-4610-89e9-f06a621c7e3c.jpg) ![20220603010624_1](https://user-images.githubusercontent.com/106782983/171760308-0de7941c-0b06-41f8-8b70-905ce567299a.jpg) .

sorry i think i replied to wrong thread, but thanks for providing screenshots.

I had this issue as well and my work around was making and saving them as custom sets

**Comment by MacSplody** [comment]
Also affects Sandking set **Ruler of the Frostbite Dunes**.


Saved as custom set as a workaround.

![image](https://user-images.githubusercontent.com/1944639/171762242-e7d936fb-7ad5-4044-a948-ec924fe6d49c.png)

**Comment by ArtemPikul** [comment]
Lion: Demon's Bacchanal 
![image](https://user-images.githubusercontent.com/16233703/172161835-aa31d5a8-209c-404d-a81d-63a138af8474.png)

**Comment by ArtemPikul** [comment]
Viper: King of the Corrupted Nest
![image](https://user-images.githubusercontent.com/16233703/172162040-da220c07-8352-4221-a0b9-d57a55ce96aa.png)

**Comment by ArtemPikul** [comment]
Bounty Hunter: Trappings of the Old-Timers
![image](https://user-images.githubusercontent.com/16233703/172164266-4c6c38b1-9d0e-430a-94eb-d921a6bfb968.png)

**Comment by vivi-lili** [comment]
Fixed in next patch
