### ISSUE TITLE
Dark map when entering a game on Linux

### ISSUE THREAD

**Issue by sbazarbay** [ValveSoftware/Dota2-Gameplay#2591]
### Description

When I enter a demo mode, or start a match with bots, the whole map is dark.

Did not try it in real match because of the risk to ruin it as it's very difficult to play under such conditions. But I assume its the same.

### Screenshots

https://imgur.com/a/9e1XBKy

**Comment by yogaxpto** [comment]
The issue seems to go away with `-vulkan` preset.

**Comment by mjspector** [comment]
same issue, macbook pro running macos big sur

**Comment by sbazarbay** [comment]
> The issue seems to go away with `-vulkan` preset.
> 
> But can be verified with opengl.

Yeah but vulkan runs badly on my laptop so I hope they will fix it for -gl option:(

**Comment by jas8669** [comment]
Same issue.  Also can't run vulkan because of another issue.

**Comment by 3guk37** [comment]
Same Issue with -vulkan present!

**Comment by jas8669** [comment]
> 

i tried -vulkan too but i assumed opengl was still active.  but yes doesn't work for me either.

**Comment by 3guk37** [comment]
@jas8669 You are right! But how I change it then?

**Comment by jas8669** [comment]
> 

i don't know, i can't seem to use vulkan either.  i have this issue where no matter what i change my settings to, when i reboot it is always the same.  which includes using opengl.  so the vulkan work around doesn't work for me.

**Comment by 3guk37** [comment]
@jas8669 Ok, thank you. I hope they are going to fix it :)

**Comment by DreadKnight** [comment]
The "-vulkan" worked for me fine so far on linux. Hope I won't jinx it xD

**Comment by Kamyabs** [comment]
I have exactly same problem after yesterday update ( battle pass) i cant switch to vulkan only way for me was opengl
Old laptop, ubuntu 18.0.4 , radeon 7600
Please i cant speak engilish well some one tell valve to fix it this is gonna ruin my life
I must play this game
I try every thing, every launch option nothing work
Please some one tell valve to fix this problem

**Comment by Kamyabs** [comment]
105mg update foxed problem, lets enjoy 🥳

**Comment by sbazarbay** [comment]
> 105mg update fixed problem, lets enjoy partying_face

Can confirm, thanks devs!
