### ISSUE TITLE
Client Crashes on Alt-Tab

### ISSUE THREAD

**Issue by FaftdunK** [ValveSoftware/Dota2-Gameplay#2593]
### Description

Client crashes on alt-tab. Error message attached appears.

### Screenshots

![image](https://user-images.githubusercontent.com/112666421/188023639-7bb35bac-bb38-4c5e-8497-c65c83f7ecc9.png)

**Comment by Zeka13** [comment]
so true ...

**Comment by Yurez23** [comment]
Found a way to fix it:
In graphic settings must choose "Current screen resolution" instead of "Advanced settings"

**Comment by FaftdunK** [comment]
> Found a way to fix it: In graphic settings must choose "Current screen resolution" instead of "Advanced settings"

This works glooks brother.

**Comment by Nathanael-Valve** [comment]
Thanks! That will help us narrow it down.

**Comment by markcaldropoli** [comment]
Duplicate of #2586

**Comment by historydev** [comment]
> Found a way to fix it: In graphic settings must choose "Current screen resolution" instead of "Advanced settings"

not working, after click apply i get error repeat

**Comment by Nathanael-Valve** [comment]
Should be fixed now.

**Comment by Nathanael-Valve** [comment]
(It's not a duplicate, this is a separate crash.)
