### ISSUE TITLE
Dota doesn't open on Mac after latest update and purchasing Compendium

### ISSUE THREAD

**Issue by MarcosDelSer** [ValveSoftware/Dota2-Gameplay#2599]
### Description

I just purchased compendium. There was an update, I  updated and the game won't open anymore. It freezes either in black or on the red dota icon screen. 

I've tried restarting steam, the computer and reinstalling dota, but the problem still stands, the game won't open.

Im playing on a Mac pro with Catalina as the OS.

**Comment by Realkai11** [comment]
Dude for me I cannot even open dota, it is always no respond for Mac Pro 2019

**Comment by Realkai11** [comment]
I believe they did not ready for updating on Mac platform

**Comment by pneuma2121** [comment]
i have an error at starting dota2 on steam, they ask me a file rendersystemdx11.dll, somebody help me?

**Comment by pneuma2121** [comment]
CMaterialSystem2AppSystemDict::AddRenderSystem() ?

**Comment by Realkai11** [comment]
Pneuma2121

**Comment by PatRibas** [comment]
Same issue on Linux Mint 20.3 Una. Happy to provide crash logs or hardware info if needed.

**Comment by Wispoi** [comment]
same shit on macbook pro 2019

**Comment by exegeses** [comment]
same issue

**Comment by nich961996** [comment]
Same issue

**Comment by ilkedemir** [comment]
It seems `libcairo.dylib` was not packaged with the update? See console at start up:

```
Loaded .../dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/libcairo.dylib, got 0x0
 failed to dlopen ".../dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/libcairo.dylib" error=dlopen(.../dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/libcairo.dylib, 9): image not found
Loaded libcairo.dylib, got 0x0
 failed to dlopen "libcairo.dylib" error=dlopen(libcairo.dylib, 9): image not found
```

**Comment by maicojay16** [comment]
Same issue here, Im using MacBook Pro 2018.  

![Screen Shot 2022-09-02 at 9 29 35 AM](https://user-images.githubusercontent.com/23121374/188039784-ff064ec7-9b49-4bd7-83a3-5768c2128b0a.png)

Before the update everything works fine, I even play 1 game with my friend. After i update the new patch for Battlepass 2022. Im stuck in the opening loading screen of Dota. 

Please help!!!

**Comment by ronakparhi** [comment]
same issue here :(

**Comment by fahim0173** [comment]
> It seems `libcairo.dylib` was not packaged with the update? See console at start up:
> 
> ```
> Loaded .../dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/libcairo.dylib, got 0x0
>  failed to dlopen ".../dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/libcairo.dylib" error=dlopen(.../dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/libcairo.dylib, 9): image not found
> Loaded libcairo.dylib, got 0x0
>  failed to dlopen "libcairo.dylib" error=dlopen(libcairo.dylib, 9): image not found
> ```

Same issue here. Issue started after yesterday’s big update (2.3GB). Screen stuck on black screen or the Dota logo(when I set launch option to -gl)

**Comment by isarrualde** [comment]
Same issue cant open after update on mamOS Monterey

**Comment by fahim0173** [comment]
> > It seems `libcairo.dylib` was not packaged with the update? See console at start up:
> > ```
> > Loaded .../dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/libcairo.dylib, got 0x0
> >  failed to dlopen ".../dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/libcairo.dylib" error=dlopen(.../dota 2 beta/game/bin/osx64/dota2.app/Contents/MacOS/libcairo.dylib, 9): image not found
> > Loaded libcairo.dylib, got 0x0
> >  failed to dlopen "libcairo.dylib" error=dlopen(libcairo.dylib, 9): image not found
> > ```
> 
> Same issue here on Macbook Pro 2018(updated to latest OS). Issue started after yesterday’s big update (2.3GB). Screen stuck on black screen or the Dota logo(when I set launch option to -gl)

<img width="1346" alt="Screenshot 2022-09-02 at 2 31 37 PM" src="https://user-images.githubusercontent.com/9362136/188098849-9e5db970-007f-4afe-8392-08c71d55a216.png">
Terminal Screenshot attached

**Comment by Realkai11** [comment]
Fahim0173 I think you can make a new post(issue) which is more easier to see your attachment for valves technicians.

**Comment by ramanbanka** [comment]
Same issue

**Comment by alfer-aws** [comment]
any update on this?

**Comment by everythingwillbetakenaway** [comment]
Same here

**Comment by yngrdyn** [comment]
sameee

**Comment by dobstotev** [comment]
Same for me guys, some devs people have fucked up :D with the pressure to release the update :D

**Comment by reutsharabani** [comment]
@dobstotev idk why you would say they "fucked up". Clearly mac wasn't the target for BP since they didn't even bother opening the game (let alone testing it).

You fuck up when you try to do something. They didn't even try.

I think they are going to drop mac support eventually since lately every BP and sometimes even patches have these problems.

**Comment by dobstotev** [comment]
> @dobstotev idk why you would say they "fucked up". Clearly mac wasn't the target for BP since they didn't even bother opening the game (let alone testing it).
> 
> You fuck up when you try to do something. They didn't even try.
> 
> I think they are going to drop mac support eventually since lately every BP and sometimes even patches have these problems.

Until officially announced, every update/release is supposed to be released and supported by all platforms their website claims that the game can be played on. 

It was a little joke as this happens always when you are pressured to release a product close to the due date but things were not ready. That's all. :)

**Comment by ShadowCat22** [comment]
Same issue unable to load dota, just becomes not responding, after the battle pass update. I'm using MacBook air Monterey 12.5.1.. tried the -autoconfig , and -gl launch options but still not loads. Don't they want Mac users to buy BP?

**Comment by destinationbugged** [comment]
> I think they are going to drop mac support eventually since lately every BP and sometimes even patches have these problems.

since there are so many tickets open here in relation with MacOS I doubt that they are going to drop the support any soon. Mac users have a limited selection of games and therefore they are willing to burn a shit ton of cash for those few. I know what im talking about, im the friendly Mac user from the neighborhood who has all the physical mini aegis collected ;)

**Comment by joey0** [comment]
Any update on this? i still can’t pass through the “not responding blackscreen”

**Comment by maksymdemeshok** [comment]
small indie company Valve

**Comment by abelernesto** [comment]
I've same problem.. any update about it??

**Comment by hbx2052** [comment]
same on my iMac...I can only see the icon jumping all the time as if I'm the joke.

**Comment by h0wtohide** [comment]
Same here!!!! Any solutions?

**Comment by h0wtohide** [comment]
Are they just gonna ignore us????

**Comment by ArtSaidanov** [comment]
Same issue - frozen screen with dota logo. MacBook Pro 16 2019

**Comment by nguyenviettuananh** [comment]
same issue, mac book pro 16inch 2019

**Comment by n-tk11** [comment]
same here with Mac Pro 2019

**Comment by bimax** [comment]
Ughhh. Friday updates....
Same issue on macbook pro 2019 Monterey 12.5.1

**Comment by sergio-contifico** [comment]
same here with mac book pro 2019, I think the problem probably fix the next week :(

**Comment by z0s0** [comment]
Same with mac pro 2019

**Comment by jemantilla** [comment]
SAMEDT sad life

**Comment by wickedm1ke-88** [comment]
same for me - I saw earlier a smaller update but with no changes for mac users

**Comment by mujtaba187** [comment]
Same issue for me, they need to fix it asap. Its Friday.

**Comment by bache01** [comment]
is this the only forum that speaks about this issue? hope steam fixes it soon.. am getting stressed out already lol

**Comment by raullamas** [comment]
Same here.

**Comment by awaiz100** [comment]
Same issue and they are doing nothing about that

**Comment by HalynaMelishkevich** [comment]
Same for me on macOS Monterey 12.5.1

**Comment by aleksey1lipkin** [comment]
Well, it seems like because of the lack of macOS gamers, they do not give a fck about the problem unfortunately 😞

**Comment by Loloner** [comment]
they dont even mention it and say anything fuck valve

**Comment by mallikarjun-b-r** [comment]
> Well, it seems like because of the lack of macOS gamers, they do not give a fck about the problem unfortunately 😞

Well they don't care about DOTA at all look at this year bp they release in two parts so that they can keep all the money, I'll switch to LOL

**Comment by dkalantari** [comment]
*Valve customer support after reading this tread* 
..
Should we make an announcement about this or keep our Mac user base in the dark? 
..
*thinking harder about it* 
..
Keeping them in the dark and losing them seem to be the correct option here

**Comment by malexxx22** [comment]
Guys, don’t be surprised :) 
Valve don’t care about the whole their industry, only for money🤙🏿
Could anyone please react to that message or give the reply once dota starts working?😴

**Comment by ShadowCat22** [comment]
Anyone tried installing Windows bootcamp on Mac? And launching dota 2 there?

**Comment by malexxx22** [comment]
> Anyone tried installing Windows bootcamp on Mac? And launching dota 2 there?
> […](#)

I guess that would work fine, but I guess that’s quite too much :)

**Comment by alekszavialov** [comment]
Same here.

**Comment by devang-patel** [comment]
Fuck you valve!!!! If you don't care about mac user's you're gonna be in deep shit

**Comment by Realkai11** [comment]
There was just an update but i still cannot load dota2 on mac

**Comment by dobstotev** [comment]
Same, probably we need to wait for tomorrow's update.

**Comment by javadamin1** [comment]
I have Hackintosh, it's better to go to Windows with this issue

**Comment by theteladras** [comment]
No fixes yet as it seems.

**Comment by densavinov** [comment]
Same issue Mac Pro 2018, BigSur update
Dota doesn't start

**Comment by joey0** [comment]
Just tested, 9hrs after my initial comment here.. The game is still not working.. this is kinda sad.

**Comment by marioSoftmedic** [comment]
Same issue here :S

**Comment by Nathanael-Valve** [comment]
Fixed in the build we're deploying now.

**Comment by nich961996** [comment]
@Nathanael-Valve THANKS SO MUCH! Despite the delay im glad its getting fixed

**Comment by raullamas** [comment]
Cool! Thanks!

**Comment by thiagomatar** [comment]
Thanks @Nathanael-Valve

**Comment by MarcosDelSer** [comment]
Thx for the quick fix. A quick acknowledge message would've been appreciated since there was even the rumor that you would depreciate MacOs all together

**Comment by maicojay16** [comment]
Cheers mate @Nathanael-Valve
