### ISSUE TITLE
(linux) client crashing when viewing battle pass rewards

### ISSUE THREAD

**Issue by auto-dan** [ValveSoftware/Dota2-Gameplay#2603]
### Description

While on the main dashboard for the dota2 client (linux).
Attempting to click on the "view battle pass" rewords link crashes the client.

Additional notes:
This issue was introduced with the most recent patch, as I was able to view the rewards earlier today when they were first added.

System:
Pop!_OS 22.04 lts
kernal: 5.19.0
DE: gnome
gpu: rtx 3080 max-q
cpu: i7-11800h

Some info to help track down:

output:

```

crash_20220901191455_2.dmp[155698]: Uploading dump (out-of-process)
/tmp/dumps/crash_20220901191455_2.dmp
/home/autodan/.steam/debian-installation/steamapps/common/dota 2 beta/game/dota.sh: line 109: 155504 Segmentation fault      (core dumped) ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
crash_20220901191455_2.dmp[155698]: Finished uploading minidump (out-of-process): success = yes
crash_20220901191455_2.dmp[155698]: response: CrashID=bp-85feb74e-4fe2-413a-affc-cea7e2220901
crash_20220901191455_2.dmp[155698]: file ''/tmp/dumps/crash_20220901191455_2.dmp'', upload yes: ''CrashID=bp-85feb74e-4fe2-413a-affc-cea7e2220901''
pid 155698 != 155697, skipping destruction (fork without exec?)
Game process removed: AppID 570 "/home/autodan/.steam/debian-installation/ubuntu12_32/reaper SteamLaunch AppId=570 -- '/home/autodan/.steam/debian-installation/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/autodan/.steam/debian-installation/steamapps/common/SteamLinuxRuntime'/scout-on-soldier-entry-point-v2 --  '/home/autodan/.steam/debian-installation/steamapps/common/dota 2 beta/game/dota.sh' +engine_experimental_drop_frame_ticks 1 +@panorama_min_comp_layer_dimension 0 -prewarm_panorama -map dota -vulkan_disable_steam_shader_cache", ProcID 155504 
ThreadGetProcessExitCode: no such process 155697
ThreadGetProcessExitCode: no such process 155506
ThreadGetProcessExitCode: no such process 155505
ThreadGetProcessExitCode: no such process 155504
ThreadGetProcessExitCode: no such process 155503
ThreadGetProcessExitCode: no such process 155452
ThreadGetProcessExitCode: no such process 155348
ThreadGetProcessExitCode: no such process 155347
ThreadGetProcessExitCode: no such process 155346
Game 570 created interface STEAMAPPLIST_INTERFACE_VERSION001 / 
Game 570 created interface STEAMAPPS_INTERFACE_VERSION008 / 
Game 570 created interface STEAMCHAT_INTERFACE_VERSION003 / 
Game 570 created interface STEAMHTMLSURFACE_INTERFACE_VERSION_005 / 
Game 570 created interface STEAMHTTP_INTERFACE_VERSION003 / 
Game 570 created interface STEAMHTTP_INTERFACE_VERSION003 / HTTP
Game 570 created interface STEAMINVENTORY_INTERFACE_V003 / 
Game 570 created interface STEAMMUSICREMOTE_INTERFACE_VERSION001 / 
Game 570 created interface STEAMMUSIC_INTERFACE_VERSION001 / 
Game 570 created interface STEAMPARENTALSETTINGS_INTERFACE_VERSION001 / 
Game 570 created interface STEAMREMOTESTORAGE_INTERFACE_VERSION016 / 
Game 570 created interface STEAMSCREENSHOTS_INTERFACE_VERSION003 / 
Game 570 created interface STEAMUGC_INTERFACE_VERSION016 / 
Game 570 created interface STEAMUSERSTATS_INTERFACE_VERSION012 / 
Game 570 created interface STEAMVIDEO_INTERFACE_V002 / 
Game 570 created interface SteamAppDisableUpdate001 / 
Game 570 created interface SteamController008 / 
Game 570 created interface SteamFriends017 / 
Game 570 created interface SteamGameCoordinator001 / 
Game 570 created interface SteamInput006 / 
Game 570 created interface SteamMatchGameSearch001 / 
Game 570 created interface SteamMatchMaking009 / 
Game 570 created interface SteamMatchMakingServers002 / 
Game 570 created interface SteamNetworking006 / 
Game 570 created interface SteamNetworkingSocketsSerialized005 / 
Game 570 created interface SteamUser021 / 
Game 570 created interface SteamUser021 / User
Game 570 created interface SteamUtils010 / 
Game 570 created interface SteamUtils010 / Utils
Game 570 method call count for IClientNetworkingSocketsSerialized::GetSTUNServer : 2
Game 570 method call count for IClientNetworkingSocketsSerialized::GetCachedRelayTicket : 1
Game 570 method call count for IClientNetworkingSocketsSerialized::GetCachedRelayTicketCount : 1
Game 570 method call count for IClientNetworkingSocketsSerialized::GetCertAsync : 1
Game 570 method call count for IClientAppDisableUpdate::SetAppUpdateDisabledSecondsRemaining : 1
Game 570 method call count for IClientUGC::GetItemInstallInfo : 26
Game 570 method call count for IClientUGC::GetItemState : 13
Game 570 method call count for IClientUGC::GetUserItemVote : 1
Game 570 method call count for IClientUGC::SetRankedByTrendDays : 2
Game 570 method call count for IClientUGC::SetReturnLongDescription : 21
Game 570 method call count for IClientUGC::SetReturnKeyValueTags : 21
Game 570 method call count for IClientUGC::AddRequiredTag : 6
Game 570 method call count for IClientUGC::ReleaseQueryUGCRequest : 19
Game 570 method call count for IClientUGC::GetQueryUGCKeyValueTag : 2055
Game 570 method call count for IClientUGC::GetQueryUGCNumKeyValueTags : 707
Game 570 method call count for IClientUGC::GetQueryUGCStatistic : 2283
Game 570 method call count for IClientUGC::GetQueryUGCPreviewURL : 761
Game 570 method call count for IClientUGC::GetQueryUGCResult : 761
Game 570 method call count for IClientUGC::SendQueryUGCRequest : 21
Game 570 method call count for IClientUGC::CreateQueryUGCDetailsRequest : 2
Game 570 method call count for IClientUGC::CreateQueryAllUGCRequest : 2
Game 570 method call count for IClientUGC::CreateQueryUserUGCRequest : 17
Game 570 method call count for IClientHTTP::SetHTTPRequestUserAgentInfo : 2
Game 570 method call count for IClientHTTP::ReleaseHTTPRequest : 126
Game 570 method call count for IClientHTTP::GetHTTPResponseBodyData : 125
Game 570 method call count for IClientHTTP::GetHTTPResponseBodySize : 124
Game 570 method call count for IClientHTTP::GetHTTPResponseHeaderValue : 60
Game 570 method call count for IClientHTTP::GetHTTPResponseHeaderSize : 60
Game 570 method call count for IClientHTTP::SendHTTPRequest : 127
Game 570 method call count for IClientHTTP::SetHTTPRequestGetOrPostParameter : 1
Game 570 method call count for IClientHTTP::SetHTTPRequestHeaderValue : 1
Game 570 method call count for IClientHTTP::SetHTTPRequestNetworkActivityTimeout : 6
Game 570 method call count for IClientHTTP::SetHTTPRequestContextValue : 61
Game 570 method call count for IClientHTTP::CreateHTTPRequest : 127
Game 570 method call count for IClientGameCoordinator::RetrieveMessage : 70
Game 570 method call count for IClientGameCoordinator::IsMessageAvailable : 141
Game 570 method call count for IClientGameCoordinator::SendMessage : 59
Game 570 method call count for IClientRemoteStorage::UGCRead : 3
Game 570 method call count for IClientRemoteStorage::GetUGCDetails : 3
Game 570 method call count for IClientRemoteStorage::UGCDownload : 3
Game 570 method call count for IClientRemoteStorage::GetFileNameAndSize : 30
Game 570 method call count for IClientRemoteStorage::GetFileCount : 2
Game 570 method call count for IClientRemoteStorage::FileExists : 24
Game 570 method call count for IClientRemoteStorage::GetFileSize : 25
Game 570 method call count for IClientRemoteStorage::FileWriteAsync : 3
Game 570 method call count for IClientRemoteStorage::FileRead : 23
Game 570 method call count for IClientNetworking::GetMaxPacketSize : 1
Game 570 method call count for IClientUserStats::GetNumberOfCurrentPlayers : 2
Game 570 method call count for IClientUserStats::FindLeaderboard : 1
Game 570 method call count for IClientUserStats::RequestCurrentStats : 1
Game 570 method call count for IClientAppManager::GetCurrentLanguage : 1
Game 570 method call count for IClientAppManager::GetAppStateInfo : 1
Game 570 method call count for IClientUtils::RecordSteamInterfaceCreation : 119
Game 570 method call count for IClientUtils::FilterText : 588
Game 570 method call count for IClientUtils::InitFilterText : 1
Game 570 method call count for IClientUtils::IsSteamChina : 5
Game 570 method call count for IClientUtils::GetLauncherType : 1
Game 570 method call count for IClientUtils::GetSteamUILanguage : 1
Game 570 method call count for IClientUtils::GetAPICallResult : 157
Game 570 method call count for IClientUtils::GetAppID : 126
Game 570 method call count for IClientUtils::GetImageRGBA : 70
Game 570 method call count for IClientUtils::GetImageSize : 70
Game 570 method call count for IClientUtils::GetIPCountry : 1
Game 570 method call count for IClientUtils::GetServerRealTime : 91
Game 570 method call count for IClientUtils::GetConnectedUniverse : 9
Game 570 method call count for IClientFriends::GetPlayerNickname_Public : 1101
Game 570 method call count for IClientFriends::GetFriendPersonaName_Public : 342
Game 570 method call count for IClientFriends::SetListenForFriendsMessages : 3
Game 570 method call count for IClientFriends::GetFriendRichPresence : 1522
Game 570 method call count for IClientFriends::SetRichPresence : 162
Game 570 method call count for IClientFriends::RequestUserInformation : 133
Game 570 method call count for IClientFriends::ActivateGameOverlayToWebPage : 2
Game 570 method call count for IClientFriends::GetFriendGamePlayed : 131
Game 570 method call count for IClientFriends::GetFriendByIndex : 585
Game 570 method call count for IClientFriends::GetFriendCount : 13
Game 570 method call count for IClientFriends::GetLargeFriendAvatar : 58
Game 570 method call count for IClientFriends::GetMediumFriendAvatar : 3
Game 570 method call count for IClientFriends::GetSmallFriendAvatar : 159
Game 570 method call count for IClientFriends::GetFriendPersonaState : 131
Game 570 method call count for IClientFriends::GetFriendRelationship : 265
Game 570 method call count for IClientFriends::GetPersonaState : 444
Game 570 method call count for IClientFriends::GetPersonaName : 1
Game 570 method call count for IClientUser::RequestSteamGroupChatMessageHistory : 1
Game 570 method call count for IClientUser::RequestSteamGroupChatMessageNotifications : 1
Game 570 method call count for IClientUser::GetDurationControl : 1
Game 570 method call count for IClientUser::GetSteamID : 193
Game 570 method call count for IClientUser::BLoggedOn : 4
Uploaded AppInterfaceStats to Steam

(process:155540): GLib-GObject-CRITICAL **: 19:15:00.055: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
src/steamexe/main.cpp (254) : Assertion Failed: reaping pid: 155540 -- gameoverlayui


```

**Comment by mathewtpower** [comment]
Same issue here
OS: Arch Linux
Kernel: 5.19.5
Desktop Environment: KDE Plasma
CPU: i5 2400
GPU: GTX 950

**Comment by ActionElly** [comment]
Experiencing the same behavior after the most recent update. Can also confirm that I was properly able to view the rewards before the most recent build.
OS: Pop OS 22.04
Kernel: 5.19
CPU: i7-9700k
GPU: GTX 1070ti

**Comment by Hammer2000** [comment]
Having the same issue. 
OS: Ubuntu LTS 22.04.1 64-bit
Kernel: 5.15.0
DE: GNOME 42.4
CPU: R7 3700
GPU: GTX 2060S

**Comment by UltraGreed** [comment]
Same issue.
OS: Gentoo Base System release 2.8 x86_64
Kernel: 5.15.59-gentoo
DE: No DE, openbox as window manager
CPU: i7-6700k
GPU: GTX 1080ti

**Comment by andrelbc** [comment]
Same here.
OS: EndeavourOS Linux x86_64
Kernel: 5.15.63-1-lts 
DE: GNOME 42.4
CPU: AMD Ryzen 7 2700x
GPU: AMD Radeon RX 580

**Comment by carpntr** [comment]
Same here.
OS: Ubuntu 20.04 
Kernel: 5.15.0-46-generic
DE: gnome
CPU: Ryzen 9 3900X
GPU: RTX 3090

**Comment by Mohsin-Ul-Islam** [comment]
Same here.
OS: Ubuntu 20.04
Kernel: 5.15.0-46-generic
DE: gnome
CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
GPU: NVIDIA Corporation GP107M [GeForce GTX 1050 Ti Mobile]

**Comment by Gigarange** [comment]
Same here.
OS: Debian GNU/Linux 11 (bullseye) x86_64
Kernel: 5.10.0-17-amd64
DE: Plasma 5.20.5
CPU: AMD Ryzen 5 3600 (12) @ 3.600GHz
GPU: NVIDIA GeForce GTX 1660 SUPER

**Comment by Disctanger** [comment]
Having the same issue. I have tried both Vulkan and OpenGL rendering engines.

OS: Manjaro Linux
Kernel: 5.15.60-1-MANJARO
DE: KDE Plasma 5.24
Graphics Platform: X11
WM: KWin
CPU: AMD Ryzen 5 5600G
GPU: Integrated
RAM: 16GB

**Comment by frryx** [comment]
Same as OP, I was initially able to access the rewards page, but a patch after that seems to have broken it. Tested both Vulkan and OpenGL. All other BP pages are fine.

OS: Fedora 36
Kernel: 5.19.4-200.fc36.x86_64
CPU: AMD Ryzen 5 3600X 6-Core 
GPU: NVIDIA Corporation NVIDIA GeForce GTX 1080/PCIe/SSE2
RAM: 16GB

**Comment by congeorges** [comment]
Same as OP; going to BP rewards crashes the client.

OS: Arch Linux
Kernel: 5.19.6-arch1-1
GPU: NVIDIA GeForce RTX 3080 (driver version 515.65.01)
Desktop: KDE Plasma 5.25.4 (X11)

**Comment by Mohsin-Ul-Islam** [comment]
> Same here. OS: Ubuntu 20.04 Kernel: 5.15.0-46-generic DE: gnome CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz GPU: NVIDIA Corporation GP107M [GeForce GTX 1050 Ti Mobile]

Mine is fixed in the recent update about 10 mins ago.

**Comment by theb4rt** [comment]
I had the same problem, but i think this was fixed already now.
OS: Arch Linux
Kernel: 5.19.6-arch1-1
GPU: NVIDIA GeForce GTX 1060 3GB
Desktop: GNOME 42.4
CPU: Intel i7-8700K (12) @ 4.700GHz
RAM: 32GB
Vulkan

**Comment by auto-dan** [comment]
Confirmed fixed as of morning of 9/2.  Thanks to everyone for confirming and verifying!

**Comment by Fajar-Islami** [comment]
I'm still having crashes

**Comment by Fajar-Islami** [comment]
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Fontconfig warning: "Z:\home\fajarislami\.local\share\Steam\steamapps\common\dota 2 beta\game\core\panorama\fonts\conf.d/41-rep
l-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "Z:\home\fajarislami\.local\share\Steam\steamapps\common\dota 2 beta\game\core\panorama\fonts\conf.d/41-rep
l-os-win.conf", line 160: Having multiple values in <test> isn't supported and may not work as expected
\dota2.exe: ../src-wine/dlls/ntdll/unix/virtual.c:1442: create_view: Assertion `!((UINT_PTR)base & page_mask)' failed.
ThreadGetProcessExitCode: no such process 17857
ThreadGetProcessExitCode: no such process 17874
ThreadGetProcessExitCode: no such process 17851
ThreadGetProcessExitCode: no such process 17845
ThreadGetProcessExitCode: no such process 17824
ThreadGetProcessExitCode: no such process 17821
ThreadGetProcessExitCode: no such process 17815
ThreadGetProcessExitCode: no such process 17811
pid 17817 != 17816, skipping destruction (fork without exec?)
Game process removed: AppID 570 "/home/fajarislami/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=570 -- /home/fajarislami/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/fajarislami/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/fajarislami/.local/share/Steam/compatibilitytools.d/GE-Proton7-35'/proton waitforexitandrun  '/home/fajarislami/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/win64/dota2.exe' -steam +engine_experimental_drop_frame_ticks 1 +voice_fadeouttime 0 -prewarm_panorama -vulkan_disable_steam_shader_cache", ProcID 17893 
ThreadGetProcessExitCode: no such process 17893
ThreadGetProcessExitCode: no such process 17833
ThreadGetProcessExitCode: no such process 17695
ThreadGetProcessExitCode: no such process 17694
Game 570 created interface STEAMAPPLIST_INTERFACE_VERSION001 / 
Game 570 created interface STEAMAPPS_INTERFACE_VERSION008 / 
Game 570 created interface STEAMHTMLSURFACE_INTERFACE_VERSION_005 / 
Game 570 created interface STEAMHTTP_INTERFACE_VERSION003 / 
Game 570 created interface STEAMHTTP_INTERFACE_VERSION003 / HTTP
Game 570 created interface STEAMINVENTORY_INTERFACE_V003 / 
Game 570 created interface STEAMMUSICREMOTE_INTERFACE_VERSION001 / 
Game 570 created interface STEAMMUSIC_INTERFACE_VERSION001 / 
Game 570 created interface STEAMPARENTALSETTINGS_INTERFACE_VERSION001 / 
Game 570 created interface STEAMREMOTESTORAGE_INTERFACE_VERSION016 / 
Game 570 created interface STEAMSCREENSHOTS_INTERFACE_VERSION003 / 
Game 570 created interface STEAMUGC_INTERFACE_VERSION016 / 
Game 570 created interface STEAMUSERSTATS_INTERFACE_VERSION012 / 
Game 570 created interface STEAMVIDEO_INTERFACE_V002 / 
Game 570 created interface SteamAppDisableUpdate001 / 
Game 570 created interface SteamController008 / 
Game 570 created interface SteamFriends017 / 
Game 570 created interface SteamGameCoordinator001 / 
Game 570 created interface SteamInput006 / 
Game 570 created interface SteamMatchGameSearch001 / 
Game 570 created interface SteamMatchMaking009 / 
Game 570 created interface SteamMatchMakingServers002 / 
Game 570 created interface SteamNetworking006 / 
Game 570 created interface SteamNetworkingSocketsSerialized003 / 
Game 570 created interface SteamNetworkingSocketsSerialized005 / 
Game 570 created interface SteamUser021 / 
Game 570 created interface SteamUser021 / User
Game 570 created interface SteamUtils010 / 
Game 570 created interface SteamUtils010 / Utils
Game 570 method call count for IClientNetworkingSocketsSerialized::GetCachedRelayTicketCount : 1
Game 570 method call count for IClientNetworkingSocketsSerialized::GetCertAsync : 1
Game 570 method call count for IClientUGC::SetReturnLongDescription : 10
Game 570 method call count for IClientUGC::SetReturnKeyValueTags : 10
Game 570 method call count for IClientUGC::ReleaseQueryUGCRequest : 8
Game 570 method call count for IClientUGC::GetQueryUGCKeyValueTag : 885
Game 570 method call count for IClientUGC::GetQueryUGCNumKeyValueTags : 296
Game 570 method call count for IClientUGC::GetQueryUGCStatistic : 903
Game 570 method call count for IClientUGC::GetQueryUGCPreviewURL : 301
Game 570 method call count for IClientUGC::GetQueryUGCResult : 301
Game 570 method call count for IClientUGC::SendQueryUGCRequest : 10
Game 570 method call count for IClientUGC::CreateQueryUGCDetailsRequest : 1
Game 570 method call count for IClientUGC::CreateQueryUserUGCRequest : 9
Game 570 method call count for IClientHTTP::ReleaseHTTPRequest : 1
Game 570 method call count for IClientHTTP::GetHTTPResponseBodyData : 1
Game 570 method call count for IClientHTTP::SendHTTPRequest : 2
Game 570 method call count for IClientHTTP::SetHTTPRequestHeaderValue : 1
Game 570 method call count for IClientHTTP::SetHTTPRequestContextValue : 1
Game 570 method call count for IClientHTTP::CreateHTTPRequest : 2
Game 570 method call count for IClientGameCoordinator::RetrieveMessage : 16
Game 570 method call count for IClientGameCoordinator::IsMessageAvailable : 33
Game 570 method call count for IClientGameCoordinator::SendMessage : 10
Game 570 method call count for IClientRemoteStorage::GetFileNameAndSize : 39
Game 570 method call count for IClientRemoteStorage::GetFileCount : 2
Game 570 method call count for IClientRemoteStorage::FileExists : 37
Game 570 method call count for IClientRemoteStorage::GetFileSize : 36
Game 570 method call count for IClientRemoteStorage::FileWriteAsync : 2
Game 570 method call count for IClientRemoteStorage::FileRead : 35
Game 570 method call count for IClientNetworking::GetMaxPacketSize : 1
Game 570 method call count for IClientUserStats::RequestCurrentStats : 1
Game 570 method call count for IClientAppManager::GetCurrentLanguage : 1
Game 570 method call count for IClientAppManager::GetAppStateInfo : 1
Game 570 method call count for IClientUtils::RecordSteamInterfaceCreation : 118
Game 570 method call count for IClientUtils::FilterText : 32
Game 570 method call count for IClientUtils::InitFilterText : 1
Game 570 method call count for IClientUtils::IsSteamChina : 5
Game 570 method call count for IClientUtils::GetLauncherType : 1
Game 570 method call count for IClientUtils::GetSteamUILanguage : 1
Game 570 method call count for IClientUtils::SetAPICallResultWithoutPostingCallback : 2
Game 570 method call count for IClientUtils::AllocPendingAPICallHandle : 2
Game 570 method call count for IClientUtils::GetAPICallResult : 15
Game 570 method call count for IClientUtils::GetAppID : 125
Game 570 method call count for IClientUtils::GetImageRGBA : 9
Game 570 method call count for IClientUtils::GetImageSize : 9
Game 570 method call count for IClientUtils::GetServerRealTime : 15
Game 570 method call count for IClientUtils::GetConnectedUniverse : 9
Game 570 method call count for IClientFriends::GetPlayerNickname_Public : 12
Game 570 method call count for IClientFriends::GetFriendPersonaName_Public : 10
Game 570 method call count for IClientFriends::SetListenForFriendsMessages : 3
Game 570 method call count for IClientFriends::GetFriendRichPresence : 59
Game 570 method call count for IClientFriends::SetRichPresence : 6
Game 570 method call count for IClientFriends::GetFriendGamePlayed : 7
Game 570 method call count for IClientFriends::GetFriendByIndex : 6
Game 570 method call count for IClientFriends::GetFriendCount : 1
Game 570 method call count for IClientFriends::GetSmallFriendAvatar : 25
Game 570 method call count for IClientFriends::GetFriendPersonaState : 7
Game 570 method call count for IClientFriends::GetFriendRelationship : 7
Game 570 method call count for IClientFriends::GetPersonaName : 1
Game 570 method call count for IClientUser::GetDurationControl : 1
Game 570 method call count for IClientUser::BIsPhoneVerified : 345
Game 570 method call count for IClientUser::GetSteamID : 30
Game 570 method call count for IClientUser::BLoggedOn : 4
Uploaded AppInterfaceStats to Steam

(process:17945): GLib-GObject-CRITICAL **: 14:49:23.926: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
src/steamexe/main.cpp (254) : Assertion Failed: reaping pid: 17945 -- gameoverlayui

src/steamexe/main.cpp (254) : Assertion Failed: reaping pid: 17945 -- gameoverlayui
