### ISSUE TITLE
Cursor goes out of the game's scope with multiple monitors (linux)

### ISSUE THREAD

**Issue by JetpackDuba** [ValveSoftware/Dota2-Gameplay#2604]
### Description

When playing a game, the cursor does to the next screen when trying to move the camera by _panning._ Happens randomly but very easy to reproduce by playing a few minutes and try to move the camera constantly.

OS info: Arch Linux Gnome with Wayland.

It may also be relevant that I have 3 displays and I play dota with the middle one, so the issue happens in both directions.

**Comment by Gigarange** [comment]
This is also happening when using 2 monitors.
OS: Debian GNU/Linux 11 (bullseye) x86_64
Kernel: 5.10.0-17-amd64
Resolution: 1920x1080, 1920x1080
DE: Plasma 5.20.5
CPU: AMD Ryzen 5 3600 (12) @ 3.600GHz
GPU: NVIDIA GeForce GTX 1660 SUPER
Dota 2 Version: 5,405

**Comment by taurenrogue** [comment]
ok ok... i figured out whats happening i think... does your dota not lock mouse only after issuing a right click command to move?

**Comment by Gigarange** [comment]
When i first load in its locked, but once i right click it becomes unlocked.

**Comment by congeorges** [comment]
Same issue for me: I have 2 monitors and play on the right; when panning left at the edge of the screen, it leaves the game and goes to my left monitor (and I click and the game loses focus, minimizing it).

OS: Arch Linux
Kernel: 5.19.6-arch1-1
GPU: NVIDIA GeForce RTX 3080 (driver version 515.65.01)
Desktop: KDE Plasma 5.25.4 (X11)

**Comment by JetpackDuba** [comment]
Seems to be fixed.

Closing the issue.
