### ISSUE TITLE
No Map and no vision after update - Mac OS

### ISSUE THREAD

**Issue by destinationbugged** [ValveSoftware/Dota2-Gameplay#2612]
### Description

After the update the map and the vision are got. 
Started a game right away after the update and it was mad. 
After switching to Vulcan the map and the vision were back but the fps were between 20 and 30. 

MacBook Pro (13-inch, M1, 2020), MacOS Monterey

### Example Match ID (and possibly Timestamp)

6736074004 - whole game 

### Screenshots

<img width="2560" alt="Bildschirmfoto 2022-09-02 um 01 00 48" src="https://user-images.githubusercontent.com/112668380/188030729-f745f6e3-652c-423b-a080-018063093317.png">

**Comment by destinationbugged** [comment]
Also applies to match playback 


<img width="2560" alt="Bildschirmfoto 2022-09-02 um 01 59 34" src="https://user-images.githubusercontent.com/112668380/188031907-d6663042-fb68-45c1-858f-63d88ad4f0f7.png">

**Comment by destinationbugged** [comment]
also applies for match playback 


<img width="2560" alt="Bildschirmfoto 2022-09-02 um 01 59 34" src="https://user-images.githubusercontent.com/112668380/188031989-122528f5-ff10-445e-8b92-5f8ff73fe9cc.png">

**Comment by prakashsurya** [comment]
same here, but I'm on linux.

**Comment by ladsoftware** [comment]
the same here :
OS: Arch Linux + Gnome + xorg
cpu: ryzen 1700
gpu: rx 580

image
![Screenshot from 2022-09-01 21-00-48](https://user-images.githubusercontent.com/411206/188038241-65cb4eeb-bae9-45cf-b8cc-1e6a6de00ab9.png)

**Comment by kuacgo** [comment]
I have the same problem on Linux , zorin os !!!

**Comment by k1ake** [comment]
Same. Not only in matches, but also in hero preview
I use arch btw

![Screenshot_2022-09-02_12-58-49](https://user-images.githubusercontent.com/97740611/188118315-40216caf-724a-4830-a520-1ef6b5dd1cc5.png)

**Comment by felpzinxd** [comment]
same here!!
linux mint playing in opengl

**Comment by ladsoftware** [comment]
switching to vulkan seems to fix the issue.

**Comment by destinationbugged** [comment]
>> After switching to Vulcan the map and the vision were back but the fps were between 20 and 30.

> switching to vulkan seems to fix the issue.

**Comment by ladsoftware** [comment]
for me switching to vulkan fixed the issue and the fps are up and it runs soo smooth with max setting.
runs better than opengl now.

**Comment by destinationbugged** [comment]
Works for MacOS again! Have a nice doto weekend bois!
