### ISSUE TITLE
Can't select webs playing as Broodmother

### ISSUE THREAD

**Issue by Vla2d** [ValveSoftware/Dota2-Gameplay#2613]
### Ability name

Spin Web

### Description

Hello
This bug appeared after latest update, with battle pass.
The thing is that I can't select any web with my mouse, this is possible only with Tab.
So the BM is totally unplayable now, because you are not able to manage your webs.
![image](https://user-images.githubusercontent.com/52933579/188031277-548d90b3-1e3c-4893-b814-a0b70cbe74de.png)

### Example Match ID (and possibly Timestamp)

Don't think this is needed

**Comment by IBS3501** [comment]
yeah i lost a game because of it

**Comment by Vla2d** [comment]
> yeah i lost a game because of it

Sure, me too. And hundreds of players are losing just now. It has to be fixed immdetiately.

**Comment by robthethrob** [comment]
Looks like most recent 200mb update fixed it !

**Comment by Vla2d** [comment]
> Looks like most recent 200mb update fixed it !

Yes.
