### ISSUE TITLE
CMaterialSystem2AppSystemDict::AddRenderSystem():Enter a short summary here!

### ISSUE THREAD

**Issue by rdz8** [ValveSoftware/Dota2-Gameplay#2627]
### Description

after i patched my dota2 this happen. pls help!

### Screenshots

![error dota](https://user-images.githubusercontent.com/112672292/188040150-5729d6cc-0d87-4d36-88ac-33febdfd92ea.png)

**Comment by titing1** [comment]
same problem here.. idont know how to fix

**Comment by prasedenica** [comment]
same issue here, which I'm unable to resolve
[duck life](https://ducklife.online)
