### ISSUE TITLE
New Immortals not able to be selected as skill effects

### ISSUE THREAD

**Issue by i2amroy** [ValveSoftware/Dota2-Gameplay#2636]
### Cosmetic Item Name

Battlepass 2022 Items

### Description

None of the new immortals/arcanas can have their effects selected on the skills (i.e. if you want the effect you  would need to equip the item). When there's a chance if they could be added to the lists so we could select their effects that would be really nice, thank you!

### Example Match ID

N/A

**Comment by LFC-Bionic** [comment]
Agreed. Cannot equip the effects from the dropdown selector

**Comment by shaileshgarg** [comment]
I think this has been fixed.

**Comment by i2amroy** [comment]
Yeah this appears fixed now. Closing.
