### ISSUE TITLE
Cursor travels outside of window in windowed mode (Linux/ Ubuntu)

### ISSUE THREAD

**Issue by f-kb24** [ValveSoftware/Dota2-Gameplay#2642]
### Description

Since the new update, cursor will not be contained within the game window in windowed mode. Ubuntu/Linux OS.

**Comment by yogaxpto** [comment]
I've noticed the same issue.
 
I've also noticed that it is only reproduced when the cursors has a high velocity.  
It will stick to the edge of the screen if it is moved slowly though.
