### ISSUE TITLE
Faceless Void Mace of Aeons Visual Compatibility Issues / Suggestions

### ISSUE THREAD

**Issue by sbsolarski** [ValveSoftware/Dota2-Gameplay#2646]
### Cosmetic Item Name

Mace of Aeons

### Description

1. Request to increase star brightness of arcana effect within Mace of Aeons effect and general alignment of the 'bubble', note the top end of the bubble and its misalignment.
![image](https://user-images.githubusercontent.com/112677452/188055776-39ae03c6-b5b0-4b23-95a2-3ebe464079b6.png)

2. Request to apply magenta tinge to Mace of Aeons bubble ult effect for arcana style 2. Image below shows current effect, the blue colour of the immortal effect overrides the current:
![image](https://user-images.githubusercontent.com/112677452/188055595-4fa715dd-e9af-4d43-bf1b-f2cd8b1ffd5c.png)

3. Stock images below (both styles):
![image](https://user-images.githubusercontent.com/112677452/188055871-a55e90e7-8c0a-4b59-87c0-632ddd61da14.png)

![image](https://user-images.githubusercontent.com/112677452/188056033-8c3e94f4-4292-46ab-9b8f-39f8a225ffbf.png)

### Example Match ID

N/A

### Screenshots

Refer above.

**Comment by Astiberon** [comment]
This has been corrected today.
The second bubble has been removed if the immortal mace is equipped.

**Comment by sbsolarski** [comment]
> This has been corrected today. The second bubble has been removed if the immortal mace is equipped.

Thank you for the update, I can confirm the second bubble has been removed with mace, however the mace itself has now lost some particle effects.

Also I wont close this yet as I'd like Valve to consider making the Mace Bubble a little more transparent.

**Comment by Astiberon** [comment]
This has just been fixed and a second style has been added for the orb when a mace is equipped.

**Comment by sbsolarski** [comment]
I can confirm the second style has been added, LOOKS AMAZING!

**Comment by BlahBlahWhiteGoat** [comment]
Hi astiberon, sbsolarski, valve team 

sorry for riding on this post

PLEASE kindly help to consider these suggestions/requests, to help with compatibility and consistency(link below) 

Really hope to at least get a reply, even if it’s a rejection 

https://github.com/ValveSoftware/Dota2-Gameplay/issues/3443#issue-1385814796
