### ISSUE TITLE
very big cursor size with new battlepass update

### ISSUE THREAD

**Issue by commentator24** [ValveSoftware/Dota2-Gameplay#2670]
i dont know what you developers did but the giant cursor made me laugh 
(my pc crashed dxgmms2.sys blue screen. back to normal after i restarted pc)
![cursor](https://user-images.githubusercontent.com/109324155/188099319-41263591-73de-4bbd-9339-93142aed9013.PNG)

**Comment by dobstotev** [comment]
Well at least u could start ur game haha :D (mac users are fkd rn incl. me :D )
