### ISSUE TITLE
Dota 2 stuck on Black Screen on Macbook after major Dota 2 update

### ISSUE THREAD

**Issue by fahim0173** [ValveSoftware/Dota2-Gameplay#2675]
### Description

After yesterday's major update (2.3GB), I am unable to launch the game on Macbook Pro 2018 running on MacOS Monterey. 

Issue - 
On launch, the game is stuck on black screen.

Attempted Workaround - 

- Updated launch option to -autoconfig from -vulkan 
- Updated launch option to -gl. In this case, the red dota logo appears but still the game doesn't load up
- Updated launch option to remove all launch configs
- Uninstalled the game completely and reinstalled the game. 

I tried running the game using the dota.sh file (before and after reinstalling). Always getting the same error. 
`failed to dlopen
"/Users/dl/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64/dota2. app/Contents/Mac0S/libcairo.dylib" error=dlopen(/Users/dl/Library/Application
Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64/dota2. app/Contents/Mac0S/libcairo.dylib, 0x0009): tried:
"/Users/dl/Library/Application Support/Steam/steamapps/common/dota 2 beta/ga
me/bin/osx64/libcairo.dylib' (no such file),
"Alibcairo. dylib' (no such file),
"/Users/dl/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64/dota2.app/Contents/Maco
S/libcairo.dylib' (no such file)`

Kindly check the screenshot attached.

Another issue suggesting the same problem #2599 

### Screenshots

<img width="583" alt="Screenshot 2022-09-02 at 3 17 04 PM" src="https://user-images.githubusercontent.com/9362136/188107312-d3925c0e-e208-417e-9235-3f6b04db6343.png">

<img width="1346" alt="Screenshot 2022-09-02 at 2 31 37 PM" src="https://user-images.githubusercontent.com/9362136/188107075-81d6769c-71a9-4bc3-9a96-0e97265859ca.png">

**Comment by thanieljay** [comment]
It's been 10 hours and still no update.

**Comment by lbrdev** [comment]
The same boot stuck has my friend with MacBook.

**Comment by alfer-aws** [comment]
You can rename a file called cairo.dylib thinking someone made a typo... but this is not the case, the error would go away but the issue still persists.

**Comment by fahim0173** [comment]
> You can rename a file called cairo.dylib thinking someone made a typo... but this is not the case, the error would go away but the issue still persists.

I think there are no workarounds for this issue. Have to wait for an update from Valve to fix this issue. Mac users missing out on latest battle pass! Has been over 13 hours and still no resolution 😩😩🤦🏽‍♂️

**Comment by MariusRossouw** [comment]
Same issue

**Comment by onetruezart** [comment]
Same issue

**Comment by JeffreyCheong** [comment]
Same fking issue
