### ISSUE TITLE
Autoexec.cfg file not loading correctly 

### ISSUE THREAD

**Issue by sshyino** [ValveSoftware/Dota2-Gameplay#2678]
### Description

Everything in autoexec.cfg file that used to change creeps/towers colors in minimap is not working anymore.

dota_minimap_creep_scale //

dota_enemy_color_r //

dota_enemy_color_g //

dota_enemy_color_b  //

dota_neutral_color_r //

dota_neutral_color_g //

dota_neutral_color_b //

dota_friendly_color_r //

dota_friendly_color_g //

dota_friendly_color_b //

### Screenshots

![bug](https://user-images.githubusercontent.com/112696810/188119689-652c3396-b024-4e11-85c4-5ffd2592be9c.PNG)

**Comment by h4uja2** [comment]
Same issue, as colorblind person this makes my game almost unplayable. (and i don't like built-in colorblind setting)

**Comment by sshyino** [comment]
> 

I feel you bro, hope they fix it asap.

**Comment by RecklessStar** [comment]
If you want to return the colors back, now you need to write in the config like this

**Comment by sshyino** [comment]
> 

for some reason it works, ty so much.

closing this.
