### ISSUE TITLE
Dota 2 not starting on mac system after new update.

### ISSUE THREAD

**Issue by Megastar777** [ValveSoftware/Dota2-Gameplay#2682]
### Description

Dota 2 not starting on mac system after new update. Its just stuck on welcome screen. And in panel its displayed as Application not responding.

1. Tried entering -gl,-vulkan, -vconsole & --autoconfig on game properties. Nothing worked
2. Uninstalled and installed dota 2 again. Nothing happened
3. Installed on another mac, and that machine is also having same issue.

System
MacOS Monterey- v12.3.1

### Screenshots

<img width="517" alt="Screenshot 2022-09-02 at 4 46 53 PM" src="https://user-images.githubusercontent.com/45449028/188128353-797d8b50-f9b2-4257-be27-62c1d66ab3cf.png">

**Comment by dobstotev** [comment]
Yeah, i have the exact same problem. It's bugged. Nothing helped to resolve it.

**Comment by nikelsk8** [comment]
Same issue…

**Comment by mrsnax** [comment]
same here

**Comment by fahim0173** [comment]
Facing the issue since Battle Pass update released around 14 hours ago 🤦🏽‍♂️

**Comment by jayashreecv** [comment]
Yes facing this same issue, please help with some fix :((

**Comment by Munovv** [comment]
me too
![image](https://user-images.githubusercontent.com/64223718/188142822-03dbbd4f-ad2c-44fa-aa7f-80e21feb591f.png)

**Comment by HiroAsashi** [comment]
Same issue

**Comment by TylerZhu1998** [comment]
Same issue!

**Comment by RoeelCohen** [comment]
Same

**Comment by MariusRossouw** [comment]
Same issue

**Comment by knigadima** [comment]
Hey

The same problem, Dota 2 not opening after battle pas 2022 update. Reinstalled Dota but it did not work :(

OS: macOS Catalina 10.15.7
Device: MacBook Air (13-inch, 2017)
Memory: 8 GB 1600 MHz DDR3
Graphics: Intel HD Graphics 6000 1536 MB
Processor: 1,8 GHz double core Intel Core i5

@ValveSoftware please help guys

**Comment by JeffreyCheong** [comment]
Same

**Comment by nobeard3** [comment]
SAME

**Comment by Nathanael-Valve** [comment]
Per Dan, I'm currently in the process of shipping this.

[danginsburg](https://github.com/danginsburg) commented 
We finally got this figured out. It was a tricky problem due to a change in our low level memory allocator and it didn't repro on most of our machines. Fix is checked in, it will be in the next update.
