### ISSUE TITLE
VALVE PLEASE FIX THIS ASAP!!! Dota 2 not working for MAC users

### ISSUE THREAD

**Issue by jayashreecv** [ValveSoftware/Dota2-Gameplay#2685]
### Description

Dota 2 is not loading for MAC users, not even getting the loading screen, it is just stuck on a black screen with the spinning colorful circle, Tried running -gl, -autoconfig, -safe, -vulkan, -vulkan -vconsole on launch option.
Tried reinstallting the game
Tried restarting steam and system
Still not working
On the panel it shows application not responding
Been like this since the battlepass update, no MAC users are able to play!!!
Please fix this asap 

### Screenshots

<img width="517" alt="188128353-797d8b50-f9b2-4257-be27-62c1d66ab3cf" src="https://user-images.githubusercontent.com/112703884/188149048-e765130a-17c2-427e-b9e7-218abf0a0647.png">

**Comment by TylerZhu1998** [comment]
I meet that problem too, hope VALVE fix it ASAP!

**Comment by Veladros** [comment]
Valve Please fix this ASAP!!

**Comment by RoeelCohen** [comment]
same

**Comment by DarkKris** [comment]
same! fix it!!!

**Comment by FanFanFantastic** [comment]
Fix it plz, we can't even purchase BP

**Comment by grantdelbrige** [comment]
Please fix, Mac users are gamers too!

**Comment by destinationbugged** [comment]
Fix it Volvo!!!

**Comment by joshjmnelson** [comment]
Same issue!

**Comment by JeffreyCheong** [comment]
Same

**Comment by RomanCoding** [comment]
same!

**Comment by nobeard3** [comment]
SAME!!

**Comment by Nathanael-Valve** [comment]
Per Dan, I'm currently in the process of shipping this.

[danginsburg](https://github.com/danginsburg) commented 
We finally got this figured out. It was a tricky problem due to a change in our low level memory allocator and it didn't repro on most of our machines. Fix is checked in, it will be in the next update.
