### ISSUE TITLE
It has been 16 hours and the game is still not even launching, are you guys sleeping?

### ISSUE THREAD

**Issue by ramanbanka** [ValveSoftware/Dota2-Gameplay#2687]
This bug thread is flooded with the same issue of the game not even launching on Mac. Hopefully it should be a quick fix with some file missing. Don't you morons have on call? At least reply to some issue so that everyone knows you are on it.

**Comment by RoeelCohen** [comment]
Having the same issue! Black screen, game won't boot up

**Comment by Zofraire** [comment]
Janitor needs to sleep. He was the only one working on BP whole night yesterday.

**Comment by destinationbugged** [comment]
> Janitor needs to sleep. He was the only one working on BP whole night yesterday.

![78a9e16f59958cf728c4dd89115372c9](https://user-images.githubusercontent.com/112668380/188174140-edcfddb8-ab58-43e6-bfcc-fab3c538344e.jpg)

**Comment by JeffreyCheong** [comment]
Same

**Comment by FanFanFantastic** [comment]
It's kinda sad when you have coming soon on a freaking taunt. Should have focused more on the BP instead of tweaking pointless changes and breaking the game.

**Comment by atif-rehman-ideofuzion** [comment]
The new battle pass seems wasting money I guess.

**Comment by nobeard3** [comment]
The game simply won't open, and I have tried everything there is

**Comment by Nathanael-Valve** [comment]
Per Dan, I'm currently in the process of shipping this.

[danginsburg](https://github.com/danginsburg) commented 
We finally got this figured out. It was a tricky problem due to a change in our low level memory allocator and it didn't repro on most of our machines. Fix is checked in, it will be in the next update.
