### ISSUE TITLE
[Linux Mint 22] Entire map is in fog of war, minimap is missing, abnormal cursor behavior

### ISSUE THREAD

**Issue by zedrex** [ValveSoftware/Dota2-Gameplay#2692]
### Description

Since the BP 2022 update, the entirety of the map is in fog of war. It is possible to see the HP bar of wards/entities in your vision range. The minimap is missing as well. The same problem persists in all video settings and match types (bots/pvp).

Additionally, the cursor now moves out of the screen (when using 2 monitors or in windowed mode)

### Example Match ID (and possibly Timestamp)

6736079382

### Screenshots

![image](https://user-images.githubusercontent.com/12676368/188154609-8f43197b-219c-4d40-bc0b-01b18284a196.png)
![image](https://user-images.githubusercontent.com/12676368/188154626-3a329176-3f00-49e3-8888-65214558e0b0.png)

**Comment by Visage982** [comment]
same issue can't play the game

**Comment by Skyliner0** [comment]
Same issue. I’m playing on a Mac. Reinstalling didn’t help, changing terrain didn’t work. Please help us!

**Comment by bilawalkazi** [comment]
same issue stuck on my mac

**Comment by n00n3-123** [comment]
Same issue with opengl driver on linux. Switching to vulkan helped (  -vulkan cli option ).

**Comment by Visage982** [comment]
solution found: do validate game files
right click on dota2 > properties > local files > verify integrity of game files...

this fixed it for me

**Comment by BlasmethiaN** [comment]
Same issue, verify integrity of game files didn't help

**Comment by BlasmethiaN** [comment]
> Same issue, verify integrity of game files didn't help

Switching to vulkan fixed the issue for me

**Comment by destinationbugged** [comment]
>> Switching to vulkan fixed the issue for me

> in my case i can't switch to vulkan :'(

You have to restart the game after picking Vulcan 
but its still a pain in the anus since Vulcan and MacOS don't get along very well, you'll have around 25 fps

**Comment by n00n3-123** [comment]
> > > Switching to vulkan fixed the issue for me
> 
> > in my case i can't switch to vulkan :'(
> 
> You have to restart the game after picking Vulcan but its still a pain in the anus since Vulcan and MacOS don't get along very well, you'll have around 25 fps

Vulkan doesn't get along very well with linux as well)
The idea here is to switch to different graphics driver, other than opengl.
This is a workaround, not a solution.

**Comment by izmankwa** [comment]
i tried still can't, i'm on kubuntu, after restart, the option back to openGL again, i tried change to vulka from command line also can't

**Comment by ducanh2526** [comment]
I just change the launch mode to --autoconfig and the game runs normally

**Comment by newprogrammergg** [comment]
I have the same issue with opengl driver on linux.

**Comment by 179wcr** [comment]
I filed almost similar issue for Ubuntu, Vulkan fps is unplayable for me :(

https://github.com/ValveSoftware/Dota2-Gameplay/issues/2698

**Comment by jnagar** [comment]
Any update on this?

**Comment by scarybenjz** [comment]
Same issue . I tried the above methods. But still not working. I use Ubuntu and Open gl

**Comment by Skyliner0** [comment]
Well it can be hoped that valve fixes this soon, because it obviously affects thousands of players.

**Comment by jnagar** [comment]
I have bought the BP, but I am not able to play :(

**Comment by 3guk37** [comment]
@Skyliner0 Maybe thousands of player, but they don't really care about us. We are the second-class player for them :)

**Comment by zedrex** [comment]
> I just change the launch mode to --autoconfig and the game runs normally

> Switching to vulkan fixed the issue for me

I can confirm that these workarounds does bring back the normal map. However, as @179wcr mentioned, vulkan FPS is very hard to play with.

**Comment by ShadOoW** [comment]
I'm having the issue with both vulkan and open gl.

No difference between the 2 options.

**Comment by zedrex** [comment]
Same issues:

- #2698 
- #2690 
- #2643 
- #2633 
- #2612 
- #2591

**Comment by ShadOoW** [comment]
My mistake switching to Vulkan does resolve the issue + the low frame rate.

Do they fix issues on weekends or see you in Monday?

**Comment by Manurmu** [comment]
i have the same problem since i updated the bp update, from elementary os odin

**Comment by Kamyabs** [comment]
Same here, just right after BP update, guys when you come here and suggest to use vulkan instead please consider that maybe some one cant or dont want to switch, this is not solution , solution is in valve hands beacuse they make this bug for us 
Just please please some one try to mention this problem in dota2 official forum and force valve to fix this, i email to steam suport for dota2 and tell them problem please you guys do it if you want force valve fix this

**Comment by taha-ghadirian** [comment]
Same issue on Arch Linux, i3 vm.

**Comment by dchiang** [comment]
> Same here, just right after BP update, guys when you come here and suggest to use vulkan instead please consider that maybe some one cant or dont want to switch, this is not solution , solution is in valve hands beacuse they make this bug for us Just please please some one try to mention this problem in dota2 official forum and force valve to fix this, i email to steam suport for dota2 and tell them problem please you guys do it if you want force valve fix this

I totally agree with your comment. As someone else said already, switching to Vulkan is a walk around and not really a solution. Specially since Vulkan have poor performance in most of our systems (even Windows user have reported issues with Vulkan before).

One thing that we all must consider is that maybe it is not a bug for Valve at all. Remember that they dropped support for OpenGL in Windows already so this might well be the first step of dropping support for OpenGL in other systems too. (I imaging some manager saying "hey we are late in our schedule so forget about testing compatibility for OpenGL since we are already dropping it")

I do wish this gets fixed asap. I also think that Valve decided to drop support for OpenGL too early even on Windows.

**Comment by Kamyabs** [comment]
I am agree with you, also i think even drop support for direct x9 was also a bad policy for valve, i mean it was just worked fine on low end systems same as opengl 

I hope they fix and not drop suport for opengl on linux, i cant buy brand new laptop/pc this game is 90% of my life (low life i now) and since yesterday its ruin my life because i dont now what to do if i dont play dota

**Comment by 3guk37** [comment]
@all They have fixed it :+1:

**Comment by felpzinxd** [comment]
> 
still the same problem here...

**Comment by 3guk37** [comment]
@felpzinxd did you update dota 2?

**Comment by felpzinxd** [comment]
> @felpzinxd did you update dota 2?

restarting steam now...

**Comment by felpzinxd** [comment]
105mb update on dota2, hope this is the "problem solving"

**Comment by ShadOoW** [comment]
Seems to be fixed

**Comment by Kamyabs** [comment]
> @ALL They have fixed it 👍

105 mg update fix confrimed 😍🥳🥳
Gg wp gl and thanks every one

**Comment by Kamyabs** [comment]
> > Same here, just right after BP update, guys when you come here and suggest to use vulkan instead please consider that maybe some one cant or dont want to switch, this is not solution , solution is in valve hands beacuse they make this bug for us Just please please some one try to mention this problem in dota2 official forum and force valve to fix this, i email to steam suport for dota2 and tell them problem please you guys do it if you want force valve fix this
> 
> I totally agree with your comment. As someone else said already, switching to Vulkan is a walk around and not really a solution. Specially since Vulkan have poor performance in most of our systems (even Windows user have reported issues with Vulkan before).
> 
> One thing that we all must consider is that maybe it is not a bug for Valve at all. Remember that they dropped support for OpenGL in Windows already so this might well be the first step of dropping support for OpenGL in other systems too. (I imaging some manager saying "hey we are late in our schedule so forget about testing compatibility for OpenGL since we are already dropping it")
> 
> I do wish this gets fixed asap. I also think that Valve decided to drop support for OpenGL too early even on Windows.

Lets enjoy our last moments in opengl 🥳🤝

**Comment by felpzinxd** [comment]
problem solved, guys!!
just update your dota and be happy again!
