### ISSUE TITLE
the treasures from Int 2020 , are still not marketable

### ISSUE THREAD

**Issue by gruianovac** [ValveSoftware/Dota2-Gameplay#2694]
### Item name

Immortal Treasure II 2020

### Description

these shouldve been marketable after TI. still arent 	

### Example Match ID and Timestamp

6725595192

**Comment by gruianovac** [comment]
items usually have a countdown in red.. these do not.. its a defect

**Comment by yckmm** [comment]
The treasures say "Marketable after The International 11" which has not happened yet.

**Comment by n0k8t** [comment]
1st September is just a placeholder. Wait till the end of TI
