### ISSUE TITLE
Win probability graph is broken

### ISSUE THREAD

**Issue by yckmm** [ValveSoftware/Dota2-Gameplay#2706]
### Description

Win probability graph in post game stats is broken.

### Example Match ID (and possibly Timestamp)

any

### Screenshots

![Untitled](https://user-images.githubusercontent.com/14143610/188196040-b5f9a246-d889-44a4-8e72-852c23402fb1.png)

**Comment by cpmcdaniel** [comment]
I confirm this is not an anomaly.
![20220902235411_1](https://user-images.githubusercontent.com/446044/188255002-dd67d433-cbc5-4685-a410-c5cd71a2c5de.jpg)
