### ISSUE TITLE
Rubick can't use stolen spell from Morph when he is another hero (Razor in this case)

### ISSUE THREAD

**Issue by crazzmc** [ValveSoftware/Dota2-Gameplay#2707]
### Ability name

Spell Steal

### Description

If Morphling is morphed to another hero and Rubick does spell steal, once rubick has that spell he can't use it.

![image](https://user-images.githubusercontent.com/42428396/188196413-445b4e4a-eda0-4228-a118-cc5b74ffdcf2.png)

### Example Match ID (and possibly Timestamp)

6737133096

**Comment by shaileshgarg** [comment]
Works fine now, this an be closed.
![20230102123840_1](https://user-images.githubusercontent.com/26450759/210202725-63e9b687-f051-4b0b-a507-df8322eb2fa1.jpg)

**Comment by crazzmc** [comment]
If this is fixed I'll be amazed I got flamed so much on the Reddit because everyone said this is an intended mechanic. I gotta test it today! Thanks for the update Sailesh.

**Comment by shaileshgarg** [comment]
You can close this issue, if its working fine for you.
