### ISSUE TITLE
Dota 2 Mac os BUG! Fix it! 

### ISSUE THREAD

**Issue by okolesnichenko** [ValveSoftware/Dota2-Gameplay#2716]
### Description

Today as always i run dota 2 on my Mac OS though the console and got something like that 

/Users/<>/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64/libcairo.dylib' (no such file), '/libcairo.dylib' 

My lovely Dota 2 stuck on black screen with loading cursor. 
Valve, today i missed crackers and table games. I want to play Dita!

**Comment by genisaretskiy** [comment]
same problem, os Big Sur 11.4 (20F71)

**Comment by awaiz100** [comment]
Same issue

**Comment by bengrau** [comment]
+

**Comment by interprise20** [comment]
Same problem !!!! I got home after work, wanted to play as normal and only a black screen is coming up with the loading cursor. launching with -gl flag     shows the Dota logo, but nothing further! we want you to fix it! OSX Mojave 10.14. 
No problems at all until yesterday.

**Comment by bengrau** [comment]
-safe doesnt work either

**Comment by Varun271** [comment]
we already opened issue way back, you guys can check this https://github.com/ValveSoftware/Dota2-Gameplay/issues/2632#issuecomment-1235620987

**Comment by Varun271** [comment]
an update, it would be fixed by monday !

**Comment by interprise20** [comment]
Varun, where di you get that info from? I am just updating Dota 2 now, hope that fixes the issue

**Comment by Varun271** [comment]
some said in our issue, https://github.com/ValveSoftware/Dota2-Gameplay/issues/2632#issuecomment-1235620987

**Comment by interprise20** [comment]
ahhh ok! I updated since, no changes to the black screen.

**Comment by elizarov017** [comment]
no fixed, ty

**Comment by Sheaffy** [comment]
Can confirm, just got the update and has bricked Dota on macOS 12.4,
Same symptoms as described in issue, blank screen on the start up of the game with loading cursor.

**Comment by Varun271** [comment]
[danginsburg](https://github.com/danginsburg) commented https://github.com/ValveSoftware/Dota2-Gameplay/issues/2632#issuecomment-1236000031
We finally got this figured out. It was a tricky problem due to a change in our low level memory allocator and it didn't repro on most of our machines. Fix is checked in, it will be in the next update.
