### ISSUE TITLE
Mac OSX Black screen with loading cursor. Fix it!!

### ISSUE THREAD

**Issue by interprise20** [ValveSoftware/Dota2-Gameplay#2717]
### Description

 got home after work, wanted to play as normal and only a black screen is coming up with the loading cursor. launching with -gl flag shows the Dota logo, but nothing further! we want you to fix it! OSX Mojave 10.14.
No problems at all until yesterday. I can see that other people having exactly the same issues on their Mac too.

**Comment by elizarov017** [comment]
The same problem

**Comment by doka666** [comment]
Tried reinstalling the game, problem persists
Please

**Comment by israx** [comment]
same thing

**Comment by FlorianWendelborn** [comment]
Very similar problem here, my entire dashboard was working fine but when I loaded into my ranked match just now I: 

1. couldn’t see the minimap
2. couldn’t see projectiles
3. couldn’t see any light on the map, it was like everything was in fog of war

I could only see hero models and creep models with HP bars. That’s it.

Of course my stupid carry flames me whole game even after explaining it, insisting I’m lying.

**Comment by Zofraire** [comment]
> Very similar problem here on OpenGL, my entire dashboard was working fine but when I loaded into my ranked match just now I:
> 
> 1. couldn’t see the minimap
> 2. couldn’t see projectiles
> 3. couldn’t see any light on the map, it was like everything was in fog of war
> 
> I could only see hero models and creep models with HP bars. That’s it.
> 
> Of course my stupid carry flames me whole game even after explaining it, insisting I’m lying.
> 
> When I switched to Vulkan during the match, the visual bugs were gone. However, that’s not a fix for me as Vulkan regularly freezes for 30 seconds randomly during teamfights, which is why I’m forced to be on OpenGL

That one is quite common among Linux users since the BP update

**Comment by Niknadim** [comment]
Same problem. Anybody there?! FIX IT!
![image](https://user-images.githubusercontent.com/112735986/188248157-b98d0ee5-6a12-42ed-90fc-aec53cdf23b4.jpg)

**Comment by Varun271** [comment]
[danginsburg](https://github.com/danginsburg) commented https://github.com/ValveSoftware/Dota2-Gameplay/issues/2632#issuecomment-1236000031
We finally got this figured out. It was a tricky problem due to a change in our low level memory allocator and it didn't repro on most of our machines. Fix is checked in, it will be in the next update.

**Comment by Nathanael-Valve** [comment]
Per Dan, shipping this.
