### ISSUE TITLE
macOS Dark Map, Minimap Missing, Projectiles Missing, various rendering issues

### ISSUE THREAD

**Issue by FlorianWendelborn** [ValveSoftware/Dota2-Gameplay#2720]
### Description

This happens since the Battlepass was released (I don’t own a battlepass yet, so it’s not related to that but it never happened before this update)

It is 100% reproducible on my system, including with a full OS restart.

_Please note that switching to Vulkan fixes **this issue** on my machine, but since Vulkan is freezing for 30 seconds every other teamfight since years I can’t play with it either. The entire system becomes unresponsive/trapped in Dota 2 until my match disconnects. So yeah, OpenGL it is for me._

OS: macOS Big Sur
GPU: Vega 64
CPU: i7-6700K
Renderer: **OpenGL**, both with best preset and with every checkbox turned off

https://user-images.githubusercontent.com/1133858/188229530-2e9e6efe-5b82-4f4d-9b85-d51a797a2fba.mp4

### Example Match ID (and possibly Timestamp)

any match, including demo mode

recording is from `6737559752` (custom bot lobby)

### Related Issues

- https://github.com/ValveSoftware/Dota-2/issues/2119

**Comment by Realkai11** [comment]
Your mac can run?

**Comment by FlorianWendelborn** [comment]
@Realkai11 if you call this running, then yes. I’m still on Big Sur though and it’s a hackintosh so that could explain the difference why you’re implying that yours doesn’t run it at all. It’s literally unplayable though, even with Vulkan (random 30s freezes in teamfights since years, hence OpenGL)

**Comment by profetabrazil** [comment]
On linux it's also showing the same bug in opengl, in vulkan I can play normal but I have a lot of FPS loss...

**Comment by Realkai11** [comment]
There was just an update but i still cannot load dota2 on mac

**Comment by FlorianWendelborn** [comment]
> There was just an update but i still cannot load dota2 on mac

Thanks for informing me, the latest update actually just fixed this issue. I no longer have weird vision on OpenGL. Closing ❤️
