### ISSUE TITLE
Well played! Shit dont work anymore

### ISSUE THREAD

**Issue by fatagun** [ValveSoftware/Dota2-Gameplay#2725]
### Description

Well Played Valve, well played. You release an update and it shits the bed. 

How can you release something that breaks a software? There is something called testing man. 

I am on MacOS and dota2 is not loading.

**Comment by Sheaffy** [comment]
See 
https://github.com/ValveSoftware/Dota2-Gameplay/issues/2632
https://github.com/ValveSoftware/Dota2-Gameplay/issues/2717

Both talking about it being bricked on macOS

**Comment by Nathanael-Valve** [comment]
Fixed in next updated.

**Comment by fatagun** [comment]
when is the next update. just logged in and didnt get any update.

**Comment by NathanKell** [comment]
I am in the process of shipping it. It'll go live in probably 15 minutes or so?

**Comment by Nathanael-Valve** [comment]
I am in the process of shipping it, probably ~15min?

**Comment by fatagun** [comment]
thank you.
