### ISSUE TITLE
Overwatch replays can't be played

### ISSUE THREAD

**Issue by MaerkQ** [ValveSoftware/Dota2-Gameplay#2734]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/MaerkQ/29e5c744d43ee80f14568bc8d10399d3).
* Have you checked for system updates? ✔
* Are you using the latest stable video driver available for your system? ✔
* Have you verified the game files? ✔

#### Please describe your issue in as much detail as possible:
As soon as Overwatch replay loads, the _End of Suspicious Activity Reached_ message and overlay appear. Rewinding doesn't remove it. The play button doesn't work properly (i.e. it seems to forward replays just by a few frames and then stop completely).

#### Steps for reproducing this issue:

1. Download and review an Overwatch case.

**Comment by Rihardskombu** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/2748 same

**Comment by MaerkQ** [comment]
I haven't noticed #2696.
