### ISSUE TITLE
Settings reverting on launch

### ISSUE THREAD

**Issue by AaronTheCleft** [ValveSoftware/Dota2-Gameplay#2744]
### Description

Everytime i launch Dota 2, my hotkeys and chat wheels are reset to default as well as right click ally options, i've tried disabling read -only also tried turning steam autocloud off and deleting the cache.

**Comment by andrei128x** [comment]
Probably a clone of [https://github.com/ValveSoftware/Dota2-Gameplay/issues/1415](url)

**Comment by AaronTheCleft** [comment]
realised something new, its also treating me as a new player on every launch.

**Comment by andrei128x** [comment]
If your name has special symbols, please try changing your display name (from Steam). It (amazingly) fixed it for me, after I tried EVERYTHING (including deleting cloud caches, full install/uninstall, enable/disable Cloud, etc).

Somehow, after the name change, Dota does not trigger deletion of the saved .vcfg file and replacement with a weird-ish one.

**Comment by AaronTheCleft** [comment]
> 

Thanks heaps, that has fixed it which is very strange and makes no sense to me.
