### ISSUE TITLE
Mars - Level 10 Talent 30% Bulwark Active Redirect Chance

### ISSUE THREAD

**Issue by shaileshgarg** [ValveSoftware/Dota2-Gameplay#2767]
### Ability name

Bulwark

### Description

With Level 10 Talent +30% Bulwark Active Redirect Chance, the total Redirect Chance goes to 100%. Eventhough the chance is 100% enemies are still able to attack allies behind mars with Bulwark active.

The redirect chance still seems to around 70%.

https://user-images.githubusercontent.com/26450759/188283328-f57a3bcc-c745-4e2e-97e8-d6cef5302fec.mp4

### Example Match ID (and possibly Timestamp)

-

**Comment by KAMOwO** [comment]
I tried to reproduce this issue and it seems that Mars needs to die before talent starts working.

**Comment by shaileshgarg** [comment]
> I tried to reproduce this issue and it seems that Mars needs to die before talent starts working.

Hmm, it should technically work before Mars dying once.

**Comment by TheUnholyWrath** [comment]
> I tried to reproduce this issue and it seems that Mars needs to die before talent starts working.

I'm assuming since this is closed you figured it out, but out of curiosity did you turn Bulwark off and on again after levelling the talent? Pudge needs to turn Rot off and on again when he gets talents/scepter for them to work.

**Comment by KAMOwO** [comment]
> I'm assuming since this is closed you figured it out, but out of curiosity did you turn Bulwark off and on again after levelling the talent? Pudge needs to turn Rot off and on again when he gets talents/scepter for them to work.

Didn't think about it the first time. Just tested it again and that's true, Mars just needs to turn off and on Bulwark, for talent to work.
