### ISSUE TITLE
Console won't open since 7.32 update.

### ISSUE THREAD

**Issue by jaccarmac** [ValveSoftware/Dota2-Gameplay#2782]
### Description

I'm using Linux. After the 7.32 update, my console bind stopped working. I checked the settings and the console had been disabled. Setting the option again and explicitly rebinding to `\` did not resolve the issue. Launching with `-console` allows the console to be opened but does not open it on start.

**Comment by NSurtsev** [comment]
Actually, now console does not work on windows too with -console

**Comment by Mabadman** [comment]
Can confirm.
Windows 10, console enabled via settings, multiple hotkeys tried, active launch options; -novid, -vulkan
Console won't launch unless the launch option -console is added
