### ISSUE TITLE
[Golden]Severing Crest No Ambient Effect

### ISSUE THREAD

**Issue by shaileshgarg** [ValveSoftware/Dota2-Gameplay#2793]
### Cosmetic Item Name

[Golden]Severing Crest

### Description

Razor Immortal - Severing Crest, doesn't have any particle/ambient effect. The glowing effect from the holes in the helmet is gone.

![20220904121914_1](https://user-images.githubusercontent.com/26450759/188301194-ae3adfd9-7efc-42ab-a510-dce466f07e45.jpg)

What is looked like.

https://static.wikia.nocookie.net/dota2_gamepedia/images/0/0c/Severing_Crest_Ambient.webm

### Example Match ID

-

**Comment by Astiberon** [comment]
The regular version of this helmet has the same bug

**Comment by shaileshgarg** [comment]
Fixed
