### ISSUE TITLE
Rubick attribute does not back as normal after stole attribute shift morphling

### ISSUE THREAD

**Issue by ghofaralhasyim** [ValveSoftware/Dota2-Gameplay#2795]
### Ability name

Spell Steall

### Description

I realized after stole attr shift, gained full str then die. Spell was gone but my str still didn't change. Just imagine what if I stole attribute shift and then gained full agility, but I can't steal that spell again, paper :) is it a bug right? you can try it on demo hero.

### Example Match ID (and possibly Timestamp)

6739996699

**Comment by Zet-ta** [comment]
i believe its a feature since it has been forever like this

**Comment by shaileshgarg** [comment]
This is intented and always has been this way.

**Comment by ghofaralhasyim** [comment]
I see thanks mate. And also I can steal allied skills from morph when it uses transform, it is a "feature" too? in my experience was steal doppelganger and enchant totem. But at some level I can't cast it, needs more level to cast
