### ISSUE TITLE
Can't join battlecup chat to look for players

### ISSUE THREAD

**Issue by Yunaii** [ValveSoftware/Dota2-Gameplay#280]
### Description

You can no longer play battlecup unless you have a premade stack. The button for "TIER 8 CHAT" is no longer there, and displays some error like "no enough players in this division", or something like that. 

I would love this fixed because I used to look forward to battlecup every week, and was the main reason I paid for D+

### Example Match ID (and possibly Timestamp)

N/A

**Comment by NMOTH** [comment]
Well, to be fair there literally aren't enough players in tier 8 who aren't in a stack already. Specially on NA servers.

**Comment by LuminaryIgor** [comment]
> Well, to be fair there literally aren't enough players in tier 8 who aren't in a stack already. Specially on NA servers.

Same error on 5 tier.


Please fix it.

**Comment by atocchi** [comment]
Can confirm issues is present in Tier 5 & Tier 6, `US West 6PM PST 6/4/2022` 

Some notes:
Switching between tiers does not seem to clear this message, and the message appears as soon as the player opens the UI. Either this response from API is immediate or this message is static. 

see below for console upon opening the battle cup panel
`[GCClient] Send msg 7197 (k_EMsgGCMatchmakingStatsRequest), 8 bytes
[GCClient] Recv msg 7198 (k_EMsgGCMatchmakingStatsResponse), 322 bytes`
(Pretty sure this just normal Handshake between the API and the application)

**Comment by JacobJustice** [comment]
I disagree, the way to make battle cup better, is to fix the bugs with battle cup chat rooms and to somehow get rid of smurfs.

**Comment by Hyperfrost1** [comment]
Confirmed issue in tier 5 SEA servers. I used to look forward to weekend battlecups with randoms, but now I can't party up with randoms anymore. :(

**Comment by jeffcox91** [comment]
This has been broken for so, so long. It's really a shame that Valve has just completely let battlecup die, between this and the hordes of smurfers that ruin it for everyone. I rarely run into smurfers playing ranked, with battlecup it is literally every single time.

**Comment by steve-11** [comment]
Please fix this issue.

**Comment by drowbert** [comment]
Still not fixed and it has been over a year now. fml

**Comment by Anti-Trust1984** [comment]
also having the same issue

**Comment by cameron-valve** [comment]
This should be fixed now, if you see this again re-open this issue!
