### ISSUE TITLE
Please, fix the problem with rendersystemdx11.dll

### ISSUE THREAD

**Issue by AdeleZONE** [ValveSoftware/Dota2-Gameplay#2829]
### Description

3 days ago i loaded new patch. since then i just can't enter the game due to the error.
CMaterialSystem2AppSystemDict::AddRenderSystem ():
Failed to load rendersystem dx11.dll, which is the default rendersystem and should not fail to load. Please verify the game install in Steam.

Please, Valve, fix it already.

### Screenshots

![123121232](https://user-images.githubusercontent.com/112848589/188377338-a699d669-a0d2-4abd-884e-8870b0da8302.jpg)

**Comment by AdeleZONE** [comment]
I have Windows 8.1 Pro Compact x64, DirectX 11. Everything worked before the patch/

**Comment by iambigslon** [comment]
Same issue for me. After BP update

**Comment by 4triple** [comment]
Same problem, 3 days without dota.

**Comment by AdeleZONE** [comment]
guys, they finally fixed it, congrats

**Comment by iambigslon** [comment]
Solved for me 2. 
Thanks!
