### ISSUE TITLE
Tusk snowball can't target stuck on release icon.

### ISSUE THREAD

**Issue by gamexgaming1997** [ValveSoftware/Dota2-Gameplay#2840]
### Ability name

Snowball

### Description

Played a game as tusk and I couldn't target any hero with my snowball. when I check the status it's like you already have a target but which I don't have. 

the bug started when I use snowball on spirit breaker around 21:40 

### Example Match ID (and possibly Timestamp)

6742385337

**Comment by TheUnholyWrath** [comment]
This has been fixed. You can close this issue.
