### ISSUE TITLE
Missing particles (has no Ambient effect)

### ISSUE THREAD

**Issue by densenene** [ValveSoftware/Dota2-Gameplay#2846]
### Cosmetic Item Name

Shattered Greatsword

### Description

Shattered Greatsword has no particles in game and main menu. 

All Dota players have the same problem. Hope it will be fixed as soon as possible.

Thanks! 

### Example Match ID

Game lobby

### Screenshots

![71229CF1-1449-4C0F-A328-96397B4C1C0F](https://user-images.githubusercontent.com/112860579/188502680-cbcdf8f0-3d08-44ed-a1ee-48768f9e7b38.jpeg)

**Comment by xyroc** [comment]
Same for Hellblade of the Daemon Prince

**Comment by shaileshgarg** [comment]
#2647

**Comment by NguyenThiHongPhan20012909** [comment]
Lets fix pls!!!!
