### ISSUE TITLE
Bushwhack + Pulverize causes huge mapwide teleportation

### ISSUE THREAD

**Issue by ZZalles11** [ValveSoftware/Dota2-Gameplay#2852]
It seems that if primal beast pulverizes someone while they're getting pulled into bushwhack, they can get moved wildly around the map. Potential to heavily impact game outcome. 

https://imgur.com/a/8L5NKDG

**Comment by ZZalles11** [comment]
I think this bug also kills replays, after going through this section once, trying to rewind makes all hero models disappear and become untargetable.

**Comment by TheUnholyWrath** [comment]
This has been fixed. You can close this issue.
