### ISSUE TITLE
Tusk snowball stuck at release state 

### ISSUE THREAD

**Issue by rainking185** [ValveSoftware/Dota2-Gameplay#2863]
### Ability name

Snowball

### Description

Tusk snowball stuck at release state towards the end of the game. Not sure when exactly that happened 

### Example Match ID (and possibly Timestamp)

6743508096

**Comment by TheUnholyWrath** [comment]
#2840 #2809 #2755 #2456 #2429 #2420 #2343

**Comment by Dota-Exp** [comment]
Will be fixed in upcoming update
