### ISSUE TITLE
Underlord Atropy Aura Bug In Turbo

### ISSUE THREAD

**Issue by djasindra** [ValveSoftware/Dota2-Gameplay#2875]
I just used Underlord in turbo, his Atrophy Aura doesnt work as intended where his attack buff randomly disappear for no reason. A level 4 atrophy aura sometimes lose the buff in 3-4 seconds after gaining it from nearby deaths, the same happens for lower level also.

**Comment by djasindra** [comment]
6743857946

Try looking at 7:30 minute mark

**Comment by TheUnholyWrath** [comment]
Its a visual bug, it happens when you die. The Damage Buff is getting removed from your HUD when you die but the Bonus Damage doesn't get removed, so when the Bonus Damage you had before you died starts decaying it subtracts from your new Damage Buff.
