### ISSUE TITLE
Planar rocket ability broken

### ISSUE THREAD

**Issue by qwenough** [ValveSoftware/Dota2-Gameplay#2894]
### Ability name

Planar rocket

### Description

Hello, after I used the Tusk ability "Snowball" targeting a Spirit breaker who was under the influence of a "Planar rocket" obtained with an aghanim shard, my snowball ability turned into a "Launch snowball"  until the end of the match and even restarting the game and character death did not unlock this ability for me. I checked this bug in the lobby, it always works
timecode - 12:20

### Example Match ID (and possibly Timestamp)

6745818833

**Comment by TheUnholyWrath** [comment]
#2863

**Comment by Dota-Exp** [comment]
Will be fixed in upcoming update
