### ISSUE TITLE
Suggestion: Abilities with different autocast behaviour should be separated

### ISSUE THREAD

**Issue by dobacetr** [ValveSoftware/Dota2-Gameplay#2908]
### Description

Some abilities gain new functionality with Aghanim's Shard/Scepter. These include Monkey King's _Boundless Strike_, Sven's _Storm Hammer_ and Marci's _Rebound_. MK and Marci gain these new functions with auto-cast enabled while Sven gets it with it disabled (which is an inconsistency that should be adressed at the very least).

Instead, these upgrades should simply grant a new copied ability that shares the cooldown with the original ability and performs the additional functionality. The auto-cast behaviour is too gimmicky, and inconsistent with what the auto-cast actually is.

Additionaly abilities that are owned by default are:

- Doom _Devour_
- Hoodwink _Acorn Shot_

Auto-cast should have a consistent behaviour across the hero pool.

**Comment by irismus** [comment]
OP, you may close this now since Alt-Cast has been added to the game. thanks!

**Comment by dobacetr** [comment]
Thank you for pointing this issue out.
Yes, alt-cast solves this perfectly (and you can't change which version you are using mid-cast, which fits perfectly with my description. )
