### ISSUE TITLE
TI Immortal 2020

### ISSUE THREAD

**Issue by BreadPiece** [ValveSoftware/Dota2-Gameplay#2930]
### Description

The 2021 TI Immortals have been listed on the community market, but the 2020 Immortals are not on the market. Is this intentional or oversight? I've been wanting to buy some of the Immortals to deck out my heros, but they're not available :(

**Comment by BreadPiece** [comment]
https://dota2.fandom.com/wiki/Immortal_Treasure_I_2020
Yeah, but it's been two years since they were released...

**Comment by shaileshgarg** [comment]
The recent immortals like Aghanims, nemestice, 2022, all have a fixed date for marketability, but ti2020 immortals only say after ti11 and don't provide a fixed date
