### ISSUE TITLE
Battle Pass chest bug

### ISSUE THREAD

**Issue by ze1den** [ValveSoftware/Dota2-Gameplay#2948]
### Description

Hello! There was a problem with the Dota 2 game event. After completing the second week of the Battle Pass with 2 stars, I did not receive the promised chest. The level remains the same as before, the changes are not shown in the history log, so this is not a visual bug.

### Screenshots

![Screenshot_1](https://user-images.githubusercontent.com/113208091/189426645-0b6bc8a7-980a-4bec-9d8a-00c7cbe78445.png)
![Screenshot_2](https://user-images.githubusercontent.com/113208091/189426659-0d69a1ce-ed25-48ec-9973-f49abad4e626.png)
![Screenshot_3](https://user-images.githubusercontent.com/113208091/189426671-22c6635b-a0ce-4c53-9a7f-8d83bfe8b6a0.png)
![Screenshot_4](https://user-images.githubusercontent.com/113208091/189426680-4aa67d92-5092-4f64-a713-e3d43a5f105a.png)

**Comment by nktvdv** [comment]
Open the inventory, there should be a chest with a seasonal reward.
