### ISSUE TITLE
Battle Pass chest bug

### ISSUE THREAD

**Issue by FennecFenev** [ValveSoftware/Dota2-Gameplay#2952]
### Description

Hello! There was a problem with the Dota 2 game event. After completing the second week of the Battle Pass with 2 stars, I only got one chest and didn't see the animation of its opening. The second chest is missing, although he writes that it was received.. No points were awarded for opening this chest. The level remains the same as before, the changes are not shown in the history log, so this is not a visual bug

### Screenshots

![Dota 2 Screenshot 2022 09 10 - 00 01 53 58](https://user-images.githubusercontent.com/113213329/189446318-680ecaa0-ac42-42db-8934-c9c32049dfb2.png)
![Dota 2 Screenshot 2022 09 10 - 00 02 08 26](https://user-images.githubusercontent.com/113213329/189446331-3af56739-a1d2-4556-b8c0-1c3abc57bab0.png)
![Dota 2 Screenshot 2022 09 10 - 00 02 21 77](https://user-images.githubusercontent.com/113213329/189446336-c8844b76-d2d4-4dc3-b4e7-42948cf63008.png)

**Comment by nktvdv** [comment]
Open the inventory, there should be a chest with a seasonal reward.
