### ISSUE TITLE
Battle pass week 2 chest bug

### ISSUE THREAD

**Issue by JesusDu** [ValveSoftware/Dota2-Gameplay#2954]
### Item name

Weekly quest chest reward

### Description

At the time of collecting the second chest of the second week of BP missions, I am going to collect the reward and I get the audio of the tusk but it does not appear, and I proceed to close the dota 2
I enter again and a chest appears, I proceed to enter the chest and the tusk appears, everything was normal while the tusk appeared, then it only lets me kick the chest once, it bugs and doesn't let me kick it anymore.

My steam identifier is: https://steamcommunity.com/profiles/76561198148068279/

MY DOTA ID: 187802551

![Jesus D](https://user-images.githubusercontent.com/113213940/189449013-b9afac36-3c8e-4cca-898f-22c2acb52a92.png)

### Example Match ID and Timestamp

ex. 187802551 y 4:15

**Comment by nktvdv** [comment]
Open the inventory, there should be a chest with a seasonal reward.

**Comment by JesusDu** [comment]
> 
If there was a chest, the error is that I opened the chest, the first kick of the tusk was fine, it gave me 1000 points, then I clicked on it and I didn't want to kick anything and the message told me that I had to keep kicking, I was giving click and did not want to kick and stayed like that.

![image](https://user-images.githubusercontent.com/113213940/189461086-5a7dcaa2-e49b-41a4-b0d8-95e8ccfc8ca0.png)


> Abre el inventario, debería haber un cofre con una recompensa de temporada.

**Comment by JesusDu** [comment]
![image](https://user-images.githubusercontent.com/113213940/190305918-4e24d0a5-1428-4a8a-ba34-5597bdee26e8.png)

The last chest is worth 1000 points, what is happening is not normal, it is a bug.
I want my chest of the week to reset.
I demand that you give me 10,000 points.

**Comment by JesusDu** [comment]
![image](https://user-images.githubusercontent.com/113213940/190306671-9137ca16-8f6b-4517-8667-648357d1b07b.png)
That it happens in 1 chest I understand, but in the others it is too rare.

**Comment by TheUnholyWrath** [comment]
You can close this issue.
