### ISSUE TITLE
Battle pass double rank tickets

### ISSUE THREAD

**Issue by f3ar161** [ValveSoftware/Dota2-Gameplay#2961]
### Item name

Battle pass 2022

### Description

Hey dota 2 folks the double rank tickets does not restore weekly.

I was digging in the internet to see if anyone has the same issue related to. 

Also this article mention that the tickets comes weekly

[https://dotesports.com/dota-2/news/how-do-ranked-double-down-tokens-work-in-dota-2](article)

### Example Match ID and Timestamp

6749792265

**Comment by commentator24** [comment]
article written by someone who doesnt play dota probably. i have never seen it refresh weekly though few years ago there was a bug, you simply just disconnect before you lose and the token wont be used up

**Comment by f3ar161** [comment]
played dota since 2011 and token refresh weekly by default at least one in every battle pass. I'm not raising an issue from nothing
