### ISSUE TITLE
The chest disappeared for the task of week 2

### ISSUE THREAD

**Issue by HurricaneXgod** [ValveSoftware/Dota2-Gameplay#2969]
### Description

I have 15/18 stars, I got 3 chest for 13 stars, but it didn't work out. The screenshot shows that I got only 2 chests and not 3.
Steam ID: 76561198818946899

### Example Match ID (and possibly Timestamp)

-

### Screenshots

![image](https://user-images.githubusercontent.com/113237559/189478082-5869204d-63cb-4da4-8476-937edd339d86.png)

**Comment by Arabell55** [comment]
Проверь инвентарь

**Comment by HurricaneXgod** [comment]
А для чего он нужен?
