### ISSUE TITLE
Charge of Darkness will continue if caster dies to Ice Blast

### ISSUE THREAD

**Issue by Mabadman** [ValveSoftware/Dota2-Gameplay#2984]
### Ability name

Charge of Darkness

### Description

Spirit Breaker will continue to charge to his target if he dies mid-charge to Ice Blast.
Same behaviour NOT observed with skills that are mechanically comparable with Ice Blast (tested Culling Blade, False Promise, Wraith Delay)

Demonstration in demo mode, Kinetic Field is not necessary and was only used to make the demonstration easier: (gif, 10mb)
![ezgif-5-46a6167ac2](https://user-images.githubusercontent.com/42493726/189489978-ec793200-427a-412a-99b1-701a4adb5de4.gif)

As seen in example match (gif, 8.5mb)
![ezgif-5-7d01145c16](https://user-images.githubusercontent.com/42493726/189490577-3006eee1-1656-4554-ab04-8b45cc2539ca.gif)

### Example Match ID (and possibly Timestamp)

6746902627 - 23:10

**Comment by Nathanael-Valve** [comment]
Should be fixed next update.

**Comment by TheUnholyWrath** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/assets/46859977/9d6661af-36b2-40b6-b570-fc4bca55b990

Spirit Breakers body doesn't chase them anymore, but the charge still connects for me.
