### ISSUE TITLE
Doom Devour

### ISSUE THREAD

**Issue by borte13** [ValveSoftware/Dota2-Gameplay#2989]
### Ability name

Devour

### Description

Doom is not getting devoured creeps ability.

### Example Match ID (and possibly Timestamp)

6750861348 - 17:18

**Comment by TheUnholyWrath** [comment]
Devour is an Auto-Cast ability. You can toggle it to do different things. 
![20220911060312_1](https://user-images.githubusercontent.com/46859977/189500119-51f423b0-cf41-4a57-92ea-d75300ef082e.jpg)
When it looks like this, Doom will get the creeps ability. 

![20220911060257_1](https://user-images.githubusercontent.com/46859977/189500127-b6648075-d02a-4e2d-a0b4-b043cac977e6.jpg)
When it looks like this, Doom will not get the creeps ability.
