### ISSUE TITLE
Silencer - last word - bug

### ISSUE THREAD

**Issue by Under-Mod** [ValveSoftware/Dota2-Gameplay#3003]
### Ability name

last word 

### Description

When using Last Word on Enigma/Shadow Shaman/Warlock/Base etc - these heroes can use channeling spells and not get silence while they use the ability. If Upheaval is applied for 9 seconds, Warlock will receive Silence only after 9 seconds.

Viedo → https://youtu.be/s3yvNXjfayM

### Example Match ID (and possibly Timestamp)

6749751806

**Comment by yckmm** [comment]
Not a bug, read the alt tooltip.

**Comment by TheUnholyWrath** [comment]
You can close this issue.
