### ISSUE TITLE
Snowball ability broken, stuck on “launch snowball”

### ISSUE THREAD

**Issue by Nolanzo** [ValveSoftware/Dota2-Gameplay#3010]
### Ability name

Snowball

### Description

Nearing the end of my game my snowball ability glitched and it remained as “launch snowball” for the rest of it. Meaning I couldn’t use the ability at all. This was obviously bad cause the hero revolves around it.

### Example Match ID (and possibly Timestamp)

6751801173 (33:40)

**Comment by TheUnholyWrath** [comment]
#2894 #2863 #2840 #2809 #2755 #2456 #2429 #2420 #2343

**Comment by Dota-Exp** [comment]
Will be fixed in upcoming update
