### ISSUE TITLE
Spell Steal bug with Astral Spirit!

### ISSUE THREAD

**Issue by BlueMageBrilly** [ValveSoftware/Dota2-Gameplay#302]
### Ability name

Spell Steal - Astral Spirit

### Description

Hard to put this one directly into words and it's not one that can come up without intending to do it, but Astral Spirit's secondary ability to move the spirit is still broken with Rubick's interactions. The ability to actual steal the Movement Sub ability was fixed in the Spring Cleaning, but the movement ability can still be stolen on its own unique way, which then turns into some looney toons stuff you'd expect in a glitch showcase in a speedrun of Ocarina of Time or something. Here's a whole thing trying to explain my experience with this glitchy ghost:

Stealing from Elder Titan after he casts the spirit steals it as normal, however if Elder Titan uses the sub ability and Rubick steals that, it creates a glitched version that cannot be returned manually and cannot be selected; it merely stands there and then returns once the timer runs out. But if Rubick steals the actual Astral spirit ability with a Scepter, he obtains TWO!? Copies of Astral spirit. Using the one created by stealing the Spirit Movement after using actual Astral Spirit ability causes the spirit to enter an eternal loop and become stuck, only ending if Rubick steals another spell; though stealing another spell while this is happening causes the glitched spirit's spell to go into the slot /after/ Rubick's ultimate; similar to what the Sub-movement ability was doing before the Spring Cleaning update, but this also seems to happen if you use the ability a second time with the remaining version of the Astral Spirit. 

The most broken part of this ability comes from the Eternal Spirit loop once it reaches the "return" timer, as Rubick is constantly bringing an invisible spirit back to his body after using the spirit a secondary time. If Rubick hits an enemy hero, or more, with the initial cast it constantly brings the spirit back to him on a constant loop until he dies or steals another spell, as mentioned before. However, because Scepter is required for this, this provides Rubick with 2 seconds of Spell Immunity, per Hero hit, for every single ghost that enters his body. Doing this for even a minute can provide hours of Spell Immunity until Rubick is killed, as the Spell Immunity lingers even if Rubick loses the Astral Spirit. Thankfully the damage does not, as each spirit overrides the previous, but this can also provide Rubick with a solid boost in attack for a short time, until he steals another spell or the timer runs out, depending on how many heroes he hits with the ghost. This is an absolutely broken interaction completely created by the odd spirit movement ability. 

I could still replicate it in Demo Mode as expected, but have no video or match ID where this would actually happen. Seems like it'd be hard to pull off unless you know what you're aiming for, though, so probably not a high priority.

### Example Match ID (and possibly Timestamp)

Elder Titan is hardly ever picked, so I have no personal ID. Apologies.

**Comment by TheUnholyWrath** [comment]
This has been fixed, you can close this issue.

**Comment by BlueMageBrilly** [comment]
Can confirm this is fixed as the movement ability can no longer be stolen. Thanks for letting me know.
