### ISSUE TITLE
the w of tusk stop working in the middle of the game

### ISSUE THREAD

**Issue by nalmeida94** [ValveSoftware/Dota2-Gameplay#3021]
### Ability name

Snowball

### Description

match 6752683746

I was playing tusk and the ability just stop working my 'w' key worked normally. But it was like the ability wasn't trigger anymore.
I disconect the match and reconect but didn't work

### Example Match ID (and possibly Timestamp)

6752683746 after minute 38

**Comment by TheUnholyWrath** [comment]
#3010

**Comment by Dota-Exp** [comment]
Will be fixed in upcoming update
