### ISSUE TITLE
IO guide problem

### ISSUE THREAD

**Issue by Rihardskombu** [ValveSoftware/Dota2-Gameplay#3029]
### Description

during the guide edit/creation by selecting a tether, a relocate will be selected as well.
![image](https://user-images.githubusercontent.com/56394602/189546199-71ea3ec6-51a0-4032-8313-70f71a1015ec.png)

which will make a confusion
![image](https://user-images.githubusercontent.com/56394602/189546335-d32f353f-64d7-4e7f-ab72-440b2536d770.png)

relocate lvl up?
![image](https://user-images.githubusercontent.com/56394602/189546295-35b9bd76-dae8-4cca-82e5-559236474488.png)

### Example Match ID (and possibly Timestamp)

Main menu

**Comment by TheUnholyWrath** [comment]
Likely related to #2519

**Comment by shaileshgarg** [comment]
This has been fixed in today's update.

**Comment by Rihardskombu** [comment]
> This has been fixed in today's update.

thanks, that's right, just checked it =>fixed

**Comment by shaileshgarg** [comment]
You can close the issue.

**Comment by Rihardskombu** [comment]
> You can close the issue.

Seems like I am not able to close is.
Or where is the button. Switching into edit mode, I can change only title of the issue.
