### ISSUE TITLE
Bug with Glaives of wisdom (silencer glaives)

### ISSUE THREAD

**Issue by Fr4mby** [ValveSoftware/Dota2-Gameplay#3031]
### Description

When the Silencer use his spell "Glaives of wisdom" on a target, some intel will be stolen.
But if the target die after this, the debuff disappear, but the intel is not restaured.
So in a few words, if you die with a silencer's glaive debuff, the intel lost will be permanent.

### Example Match ID (and possibly Timestamp)

6753472806 (9:24)

### Screenshots

Before the death and the debuffs:
![image](https://user-images.githubusercontent.com/63785985/189549054-0b5907f0-41b3-479d-ad77-9cb4077e37f9.png)

Just before the death:
![image](https://user-images.githubusercontent.com/63785985/189549103-7a94a9c6-a6f7-4760-9e03-d68cc4e40979.png)

After death, no more debuff, but still the same amount of mana:
![image](https://user-images.githubusercontent.com/63785985/189549123-26a1aae7-95e8-4fa7-9735-37c977670687.png)

After respawn:
![image](https://user-images.githubusercontent.com/63785985/189549146-1fa23a83-7687-4e88-8dad-7777f0860f34.png)

**Comment by shaileshgarg** [comment]
Silencer stole -2 intel

**Comment by Fr4mby** [comment]
> Silencer stole -2 intel

But no debuff visible about this stolen intel?

**Comment by DraconisDei** [comment]
> > Silencer stole -2 intel
> 
> But no debuff visible about this stolen intel?

When silencer kills you, he steals 2 intelligence (4 with shard) permanently. He also steals additional INT on hit with glaives. The INT stolen on hit is temporary. The INT stolen on a kill is permanent.

**Comment by Fr4mby** [comment]
> When silencer kills you, he steals 2 intelligence (4 with shard) permanently. He also steals additional INT on hit with glaives. The INT stolen on hit is temporary. The INT stolen on a kill is permanent.

Ok, so there is no bug, just the fact that there is no debuff visible on the permanent steal disturbed me :)
Btw, there is nothing written in the spell description that explains that there is a permanent steal on the target death. My game is in french, and there is not a word in the spell description about the permanent steal.

Thank you for your feedback!
