### ISSUE TITLE
Rubick's telekinesis doesn't have its marker anymore

### ISSUE THREAD

**Issue by Vessora** [ValveSoftware/Dota2-Gameplay#3038]
### Cosmetic Item Name

Both default and staff of the Perplex

### Description

Rubick's q doesn't have its marker on where units are suppose to land, this has been an issue for years, please fix.

### Example Match ID

N/A

**Comment by Morton69** [comment]
I appreciate the information and advice you have shared. I will try to figure it out for more.

**Comment by TheUnholyWrath** [comment]
You can close this issue.
