### ISSUE TITLE
Keeper of the Light Illuminate does much less damage than it should

### ISSUE THREAD

**Issue by allenchen** [ValveSoftware/Dota2-Gameplay#304]
### Ability name

Illuminate

### Description

When you cast Illuminate, it deals damage based on the duration of its channel. For example, if I do a full duration channel of Illuminate, it will do max damage (500). The full projectile of Illuminate takes roughly ~2-3 seconds to fully clear (especially with cast range buffs, like Keeper ult.), but all units along that projectile should take the full damage (500).

However, if your original projectile of Illuminate is _still traveling_ and you **re-cast/channel Illuminate** (which is easily achieved through cooldown reductions + Chakra reducing its cooldown), the _still traveling_ Illuminate will stop doing damage based on the original, full channel duration (500) and it will instead start doing damage based on the new Illuminate channel duration (usually close to the minimum amount of damage, ~100).

Expected Behavior: The existing _still traveling_ Illuminate should do 500 damage regardless of any new channeled Illuminate abilities. The two Illuminates (the still-traveling one, and the in-progress channeled one) should have entirely separate damage values.

### Example Match ID (and possibly Timestamp)

n/a

**Comment by NMOTH** [comment]
Please provide screen recording of this issue.
Can't replicate.

**Comment by allenchen** [comment]
First example Illuminate is just a regular channel, does 510 damage. This is expected behavior.

Second example starts with an Illuminate with a regular channel that should also do 510 damage. But before the Illuminate hits, I re-cast Illuminate. The first Illuminate only does 147 damage, and the second one does the full 510 damage. They should both do 510 damage.

https://user-images.githubusercontent.com/355936/171775066-8ab9542e-af4d-4ab0-b6ee-d22c5ffab825.mp4

**Comment by mdiller** [comment]
With the new changes in 7.32 this bug happens a LOT more often, as the reduced illuminate cooldown from the talent means you can even replicate this without octarine. with octarine itll happen constantly.

**Comment by Aluerie** [comment]
* fixed **https://github.com/ValveSoftware/Dota2-Gameplay/issues/10271#issuecomment-1662946839**
