### ISSUE TITLE
Glimpse Bug

### ISSUE THREAD

**Issue by feelsbadmans** [ValveSoftware/Dota2-Gameplay#3054]
### Ability name

Disruptor's Glimpse

### Description

Heroes keep applying auras and dealing aoe damage for short period of time (about 0.5-1s) after being glimpsed. Pudge killed disruptor using rot and gained 1 charge of flesh heap in larger radius. Tested with necro, radiance and some other auras.

### Example Match ID (and possibly Timestamp)

6755154552 (23:05 - 23:12)

**Comment by Dota-Exp** [comment]
Working as intended. Most auras have a short linger duration.
