### ISSUE TITLE
Tusk snowball bug

### ISSUE THREAD

**Issue by Ceoss1** [ValveSoftware/Dota2-Gameplay#3068]
### Ability name

Snowball and Planar pocket

### Description

Tusk Snowball bugged in a match. The ability bugged so that launch snowball didn't change back to snowball. Might be caused by spirit  breaker Planar pocket

### Example Match ID (and possibly Timestamp)

Match ID: 6755934448  Time stamp 37:45

**Comment by TheUnholyWrath** [comment]
#2420 #2343

**Comment by Dota-Exp** [comment]
Will be fixed in upcoming update
