### ISSUE TITLE
Bug report: Can still use items when hero is controlled or muted

### ISSUE THREAD

**Issue by ototsu** [ValveSoftware/Dota2-Gameplay#3088]
### Description

steps are as follows:
1.chose the courier or ally
2.use hotkey chose ur hero (advanced hotkeys--select allies)
3.mouse click the item

### Screenshots

![axe](https://user-images.githubusercontent.com/51513978/190145155-b05746a7-ef93-4e19-8856-cef2138df700.gif)

**Comment by Dota-Exp** [comment]
Will be fixed in the next update.

**Comment by ototsu** [comment]
@Dota-Exp can still use in chronosphere, xd
