### ISSUE TITLE
Battle Pass 2022 - Cavern Crawl - Didn't recieve shard

### ISSUE THREAD

**Issue by Terule** [ValveSoftware/Dota2-Gameplay#3091]
Found a fragment last week (first or second day of compendium release) but isnt counting towards unlucking the seccond style for Juggernault and i cant find another one on the board, plus it was not awarded to me.

**Comment by banff192** [comment]
в батл пасе я прошел до нового уровня там мне должны были дать кейс с уровнями мне его не дали . что мне делать ?

**Comment by TheUnholyWrath** [comment]
You can close this issue.
