### ISSUE TITLE
Ogre Bruisers use Ogre SMASH! at night when they should be sleeping

### ISSUE THREAD

**Issue by stahara** [ValveSoftware/Dota2-Gameplay#310]
### Description

If you stand near an ogre camp at night time, the ogres will use their "smash" attack even while sleeping.

### Example Match ID (and possibly Timestamp)

6456328523 - 8:53 (in the Dire jungle)

### Screenshots

https://user-images.githubusercontent.com/6586671/171777205-9d06a46c-5d4f-402a-8175-eee4d72e85f2.mp4

**Comment by somethingxful49** [comment]
I believe if this was an intended mechanic it wouldn't work while asleep either

**Comment by stahara** [comment]
(Note on the video: the sleeping "Z"s are actually there normally, but aren't visible due to the replay particle effect bug.  The ogre wakes up, smashes, and then returns to sleep immediately.)

**Comment by Dota-Exp** [comment]
Will be fixed in upcoming update
