### ISSUE TITLE
Enemy character is not loaded properly and I wasn't able to attack that character

### ISSUE THREAD

**Issue by Remzi-Gazi** [ValveSoftware/Dota2-Gameplay#3101]
### Description

Enemy character is not loaded properly and I wasn't able to attack that character for half an hour. I wasn't able to understand what happened. Probably character model wasn't properly loaded and I was seeing a piece of Legion Commander's suit and it's health bar.  But my character wasn't able to attack except the times Legion taunted my character. After exiting and restarting the game I was able to see and attack the Legion. Worst bug I have ever seen so far.

### Example Match ID (and possibly Timestamp)

6758356385

**Comment by TheUnholyWrath** [comment]
You can close this issue.
