### ISSUE TITLE
Bounty hunter Shadow Walk Break Chaneling spells Like TP after Upgrading with Shard

### ISSUE THREAD

**Issue by sinampv** [ValveSoftware/Dota2-Gameplay#3102]
### Ability name

Shadow walk

### Description

Bounty Hunter Shard (Upgrading SHADOW WALK) will now break channeling spells like TP or Meteor Hammer after buying shard .

### Example Match ID (and possibly Timestamp)

You can test it very quickly in Demo .

**Comment by TheUnholyWrath** [comment]
#2563

**Comment by Dota-Exp** [comment]
Will be fixed in the upcoming update. Thank you.
