### ISSUE TITLE
Lone Druid Savage Roar not working properly

### ISSUE THREAD

**Issue by psyordie** [ValveSoftware/Dota2-Gameplay#3107]
### Ability name

Savage Roar

### Description

I've noticed recently after 7.32 that whenever I use savage roar, it would not always work properly or the same. 

In the past, whenever pudge hooks or uses dismember on the lone druid bear, it could get canceled by savage roar if i cast it on the hero. Now it seems to not work anymore. Not sure if this was intended as a fix.  Bear savage roar doesnt proc correctly as it used to

### Example Match ID (and possibly Timestamp)

6758561790 at 11 minutes

**Comment by Dota-Exp** [comment]
Working as intended
