### ISSUE TITLE
First quest of second week doesn't count

### ISSUE THREAD

**Issue by forsakenedman** [ValveSoftware/Dota2-Gameplay#3117]
### Description

First quest of second week doesn't count, tried to activate previous week and then return but it doesn't work. 

### Screenshots

![Screenshot_2](https://user-images.githubusercontent.com/113583566/190342481-4b619bb6-ec18-4fa1-8f69-84d2f06d7e53.png)

**Comment by Babycora** [comment]
This quest on first week doesnt count too.

**Comment by forsakenedman** [comment]
Started counting after update, **maybe** fixed.

**Comment by TheUnholyWrath** [comment]
You can close this issue.
