### ISSUE TITLE
[Ability Draft] Missing Talents

### ISSUE THREAD

**Issue by RGBKnights** [ValveSoftware/Dota2-Gameplay#3127]
### Description

We recently did a [bug hunt](https://www.reddit.com/r/Abilitydraft/comments/x39tdw/talent_bug_hunt/) for missing and mismatching talents for AD. We found that following talents are missing or not functioning correctly.

- (Snapfire's) lvl 15 talent: +2 Lil' Shredder attacks
- (Riki) - lvl 15 talent: -4s Smoke Screen Cooldown
- (Omniknight) lvl 25 talent: +75% Hammer of Purity Damage
- (Puck) lvl 20 talent: -6s Waning Rift Cooldown
- (Broodmother) lvl 20 talent: 400 AoE Silken Bola
- (Luna) lvl 20 talent: 2 moon glaives fired on lucent beam
- (Lycan) lvl 25 talent: Howl reduces total attack damage
- (Natures Prophet) lvl 20 talent: Sprout leashes
- (Venomancer) lvl 25 talent: Poison Nova reduces 100 Attack Speed

### Example Match ID (and possibly Timestamp)

N/A

**Comment by TheUnholyWrath** [comment]
#1890 #1582 #1648 #1214 #1044
Broodmothers level 25 talent +35% Silken Bola Slow/Miss Chance is attached to Spin Web
Legion Commanders level 25 talent +50% Moment of Courage Lifesteal is attached to Duel

**Comment by dhabiheng** [comment]
Fixed in next patch

**Comment by TheUnholyWrath** [comment]
#2078
