### ISSUE TITLE
Mac OS 12.6 won't launch Dota2

### ISSUE THREAD

**Issue by joshjmnelson** [ValveSoftware/Dota2-Gameplay#3132]
### Description

Updated to Mac OS 12.6. Was able to launch without issue Dota2 just prior to update from 12.5. Immediately after update from 12.5 to 12.6 Dota2 will not actually launch. The game will indicate it is running, but the only thing I can do is force quit the application.

### Screenshots

<img width="1280" alt="Screen Shot 2022-09-15 at 10 57 08 AM" src="https://user-images.githubusercontent.com/112711225/190437542-6d11a98c-48bb-4143-bd8a-e3890e7338d9.png">

**Comment by Bishop444** [comment]
This shit is back, wtf
