### ISSUE TITLE
 catacombs

### ISSUE THREAD

**Issue by BillyHoup5** [ValveSoftware/Dota2-Gameplay#3154]
### Cosmetic Item Name

Style on the juggernaut

### Description

catacombs, completed tasks to get a juggernaut, and after receiving 3 fragments, the second style did not open

### Example Match ID

457692577

### Screenshots

![image](https://user-images.githubusercontent.com/113683662/190614819-ab78d6d9-2239-4d80-a546-dd96784d3c68.png)
![image](https://user-images.githubusercontent.com/113683662/190614910-671986ad-bac0-4d5a-8768-10554ebfe92c.png)

**Comment by Aluerie** [comment]
the way it works - after getting 3 fragments you get a special item into your inventory which should be used on all items from this set to give them second style. 

So check your armory for some Style Upgrade items.
