### ISSUE TITLE
broken predictions today

### ISSUE THREAD

**Issue by gruianovac** [ValveSoftware/Dota2-Gameplay#3159]
![image](https://user-images.githubusercontent.com/27729570/190576366-325252dc-4b2c-4561-8f7f-08d3d16e81c7.png)

#### Steps for reproducing this issue:

1. watch a tournament match
2. try to predict 
3. notice error

**Comment by Liam-NFLD** [comment]
+1

**Comment by thelazt16** [comment]
+1
I just got back to Dota to watch TI11 in game (no match played in the past years), notice this predict thing and tried to predict and got same error, tried almost every match I watched, same error

**Comment by TheUnholyWrath** [comment]
Please close this issue.

**Comment by Liam-NFLD** [comment]
> Please close this issue.

Has it been fixed? Or are we going to be getting the same issues next time the code for in-came predictions is used?

**Comment by TheUnholyWrath** [comment]
> Has it been fixed? Or are we going to be getting the same issues next time the code for in-came predictions is used?

its a pretty mainstream issue that was only spammed about for a day so odds are it was fixed during ti, but i can't confirm that. the issue creator doesn't have to do what i say, but leaving this open is essentially pointless

**Comment by Liam-NFLD** [comment]
> was

I experienced this issue multiple times throughout the tournament and did not see any evidence that it was fixed.

As for the pointlessness of keeping this open, I Kent comment intelligently.
