### ISSUE TITLE
Occult Bracelet can get more than 5 stacks

### ISSUE THREAD

**Issue by Meddan** [ValveSoftware/Dota2-Gameplay#3176]
### Item name

Occult Bracelet

### Description

By dropping and picking up occult bracelet you can get more than 5 stacks.

How to reproduce:

1. Get hit to get 5 stacks
2. Quickly drop and pickup Occult Bracelet
3. Get hit to get more stacks

### Example Match ID and Timestamp

6761292102 -  13:10, Slark

**Comment by shaileshgarg** [comment]
Fixed in today's update.

**Comment by Meddan** [comment]
Fixed in 7.32c
