### ISSUE TITLE
Dota plus 

### ISSUE THREAD

**Issue by KINZs** [ValveSoftware/Dota2-Gameplay#3180]
### Description

Can't complete dota plus welcome quests, "VIEW HERO-SPECIFIC GLOBAL RANK TRENDS", it does not count.

I've tryed restarting multiple times.

### Screenshots

![image](https://user-images.githubusercontent.com/48375198/190801821-6a6fee8d-d54b-4361-a960-7ac8c023cb00.png)
![image](https://user-images.githubusercontent.com/48375198/190801390-3ad56247-4ab1-4190-9307-478ded3359b6.png)

**Comment by KINZs** [comment]
https://steamcommunity.com/id/bruno1

**Comment by commentator24** [comment]
have you tried clicking all the brackets herald - immortal

**Comment by KINZs** [comment]
> have you tried clicking all the brackets herald - immortal

there's no immortal, but yeah, i've tried that :(

**Comment by KINZs** [comment]
ok i found it !
![image](https://user-images.githubusercontent.com/48375198/190840309-d85718dd-36f0-467e-81c9-f1d01d35182a.png)

**Comment by Multyashka07** [comment]
thank you very much
