### ISSUE TITLE
Wukong Command Cooldown Freezing in Ability Draft

### ISSUE THREAD

**Issue by davidtom-hub** [ValveSoftware/Dota2-Gameplay#3187]
After first use, it stays at 120s and aghs also has no image spawning effect.

**Comment by razorbraid** [comment]
This happened to me too. I was using it on Wukong model. Stuck on 100s cooldown, and aghanims doesn't work. Match 6763799312 for reference

**Comment by Paw2Pom** [comment]
This happened to me as well. Please fix this thank you!

The cooldown stuck at 120s.

**Comment by pudgepiska** [comment]
+1

**Comment by yahorwtns** [comment]
This happens in Normal mode as well in case of Rubic's Spell Steal. It got stucked for 120 sec. 
As refference 6792256658 - 20:14
