### ISSUE TITLE
CHEST REWARD NOT CLAIMED!

### ISSUE THREAD

**Issue by SENDHELP111** [ValveSoftware/Dota2-Gameplay#3198]
### Description

Today, after grinding for my chest reward in battles pass week I claimed the last weekly quest chest in week 2, but it didn't let me kick it(or open the chest) to receive the reward instead it lagged then disappeared. I checked the battle pass log points to see if I still got the points but it didn't.

send help

feel like i  got scammed....

### Screenshots

![Screenshot 2022-09-18 074932](https://user-images.githubusercontent.com/113808137/190880096-4d17d534-c927-45de-970f-dcb35347ff47.png) 

![Screenshot 2022-09-18 075216](https://user-images.githubusercontent.com/113808137/190880144-4f24ee87-3b64-4fa4-b44f-73058122aa04.png)

**Comment by TheUnholyWrath** [comment]
You can close this issue.
