### ISSUE TITLE
battle pass week 2 chest

### ISSUE THREAD

**Issue by Rajgo12** [ValveSoftware/Dota2-Gameplay#3236]
### Description

just finished the week 2 but i didn't get a chance to claim the 4 chest i don't know why but when i pressed the claim nothing popped up like the usual tusk chest

### Screenshots

![Screenshot (303)](https://user-images.githubusercontent.com/113918417/191041830-102caa6a-f523-4564-9fad-65ab92c7ccb6.png)
![Screenshot (304)](https://user-images.githubusercontent.com/113918417/191041852-4f6ba805-cba9-4dbf-8b1a-d275a032336c.png)
![Screenshot (305)](https://user-images.githubusercontent.com/113918417/191041856-ed67615a-7539-4a7b-8da3-14dd9d07143e.png)
![Screenshot (301)](https://user-images.githubusercontent.com/113918417/191041860-1c59d23e-e680-4032-ac4f-2868987a6b5d.png)
![Screenshot (302)](https://user-images.githubusercontent.com/113918417/191041868-7b928e42-a8cd-4de1-98ca-c334085c8a63.png)
![Screenshot (303)](https://user-images.githubusercontent.com/113918417/191041873-646384b9-d2ff-42ec-b13b-45af78a71fee.png)

**Comment by koralx** [comment]
bro i have the same problem
