### ISSUE TITLE
Aghs Shard still upgrades Mischief (7.32 should have removed this)

### ISSUE THREAD

**Issue by TheZett** [ValveSoftware/Dota2-Gameplay#3238]
### Ability name

Mischief

### Description

Monkey King’s former Mischief shard upgrade has not been fully removed from the game.

While the Mischief cooldown reduction from 15 to 8 seconds was indeed removed, the functionality of Mischief is still upgraded upon purchasing shard.

**Video:** https://youtu.be/ZfdA8dQc5hM

---

**Without shard:**

- Item/Tree/Rune transformations use 200ms as absolute¹ movement speed.

- Non-Courier creep transformations use transformation target’s movement speed (e.g. 400ms for Lycan Wolf) as absolute movement speed.

- Cannot disjoint projectiles.

**With shard:**

- All non-Courier transformations use your current total movement speed as absolute movement speed.

- Can disjoint projectiles.
---
_¹Movement speed cannot be slowed or increased at all, except for Hastes._

### Example Match ID (and possibly Timestamp)

Refer to the video linked above

**Comment by Dota-Exp** [comment]
Will be resolved in an upcoming update
