### ISSUE TITLE
Ability Draft Bug Spell error and my spell cooldown stuck 

### ISSUE THREAD

**Issue by KameSenpai** [ValveSoftware/Dota2-Gameplay#3241]
### Description

My ultimate spell "wukong command" cooldown wont move after first used. My hero is snapfire. And also, argahim sceptor wont work  too.
![20220919224150_1](https://user-images.githubusercontent.com/113928392/191067244-4bf04914-f59b-44c5-b763-301b15e1f123.jpg)
![20220919224010_1](https://user-images.githubusercontent.com/113928392/191067186-f1e0a9f1-c3c3-4051-850b-3262ec16ecb4.jpg)
### Example Match ID (and possibly Timestamp)

6766446712- 9/19/2022 - 10:07

**Comment by DarkoniusXNG** [comment]
Mark it as 'Ability Draft bug' in the title.

**Comment by TheUnholyWrath** [comment]
#3187
