### ISSUE TITLE
Liquid Fire and Liquid Frost Autocast priority issues and perhaps a possible bug.

### ISSUE THREAD

**Issue by irismus** [ValveSoftware/Dota2-Gameplay#3249]
### Ability name

Liquid Fire/Liquid Frost

### Description

Below is a table of the observations made, Jakiro is unable to apply both Liquid Fire and Liquid Frost if both are set to Autocast simultaneously. Multiple attack modifiers work perfectly in AD, they should be able to work properly in games as well.

However, there is a weird quirk/interaction I am unable to figure out:
**If Jakiro have more than 5 items (incld. neutral items, excld. backpack, TP and shard consumed) equipped, he cannot apply both Liquid Fire and Liquid Frost no matter what.**

|Ability|Ability|Manual Casting|Result|
|:-|:-|:-|:-|
|Liquid Fire|Liquid Frost (Autocast)|Liquid Fire|**Liquid Frost applied.**|
|Liquid Fire (Autocast)|Liquid Frost (Autocast)|Auto-attack|**Liquid Frost applied.**|
|Liquid Fire (Autocast)|Liquid Frost|Liquid Frost|**Both Fire and Frost is applied.**|
|Liquid Fire (Autocast)|Liquid Frost|Liquid Frost|**Liquid Frost (if you have 6 items equipped)**|

More love for our twin head dragon! Thank you for your time.

### Example Match ID (and possibly Timestamp)

n/a tested in lobby and demo mode

**Comment by TheUnholyWrath** [comment]
#266

**Comment by irismus** [comment]
Thanks for tagging issue 266 as well.
However, this one has an interaction with the inventory. With 6 items in total (including neutrals), both just doesn't work, no matter what.

**Comment by howardzijiesong** [comment]
I see the opposite behaviour. I can only apply both if I have 6 items in my inventory.

**Comment by PudiccaA** [comment]
My friend and I did some testing, it's a super weird bug.

The trick: first put liquid fire on autocasting, leaving liquid frost manual, and then cast liquid frost on target.

The result:

This trick works on my friend's client only if he put 6 items in the inventory.
This trick works on my client only if I put less than or equal to 4 items in the inventory.
It's just random.

**Comment by irismus** [comment]
Closing this since the #266 is opened earlier, will post more info there instead. Hope this gets fixed soon.
