### ISSUE TITLE
Is a rank 448 player using cheats?

### ISSUE THREAD

**Issue by AnanasSok** [ValveSoftware/Dota2-Gameplay#3267]
### Description

I just wanted to see how Elder Titan is played. From the first seconds I was confused by the movement of his camera, it was not natural. I decided to watch a little.

The first strange moment with the raising of the rune of wealth. When he walked towards it, he only saw the edge of the camera at 0:03, then he began to hit a Void and at 0:00 his mouse accelerated sharply to certain coordinates of the rune, then returned to its original location. This is visible at 0.25x.
![image](https://user-images.githubusercontent.com/66092930/191237830-14ef17c7-bd43-40d6-9a49-441b1320418e.png)
![image](https://user-images.githubusercontent.com/66092930/191239285-e19478e0-0113-4819-84da-f046f1fc96a5.png)
(At the very end, I rushed to check the creep block lol. Can people do that?)
![image](https://user-images.githubusercontent.com/66092930/191239629-1696ed54-8bd5-4243-9567-c8d7c7b6d3d8.png)

Then I started watching the laning. When using astral spirit, his camera accelerated sharply at the enemy, a skill was applied and the camera returned. Weird things also happened with last hitting creeps. Sometimes he himself finished off the creeps with the attack button or the mouse. At such moments, the cursor jerks a little over the creep and does not stay in one place for a long time (seen at 0.25x), this is due to hand tremor.
But in some moments, the creeps were finished off by a cheat. At 4:01 this is clearly visible (speed 0.25x). The mouse jerks around the creep (the hero is ordered to move), then accelerates sharply to the coordinates of the creep and hangs there until the creep is finished off. Then it accelerates sharply to the "order to move the hero."
![image](https://user-images.githubusercontent.com/66092930/191242120-d79c1aa0-b7f6-461f-bcf0-afc5e324511a.png)
First frame: a move order (human) is issued. Second frame: finish off the creep (cheat). Third frame: move order (person).

It looks like the work of a humanizer, and not the worst. Watch the whole game for a long time, but if you wish, you can find "strange moments" yourself.

![image](https://user-images.githubusercontent.com/66092930/191243496-dadd2c0f-4d1e-4827-88aa-b460ba805d32.png)
For example, at 18:15 he very "strangely" takes away a neutral object, it must be seen.

I'm not sure that I'm writing to the address, and that at least someone will read this text. But I propose to introduce some kind of function to mark such players in post-match replays. For example, I accidentally meet such players when I watch my replays.
Game ID: 6758527777. Player ID: 865985155.

P.S. I am one of those who are positive about changing skins or increasing the range of the camera, but cheats and other benefits are too unfair.

### Example Match ID (and possibly Timestamp)

6758527777

**Comment by AnanasSok** [comment]
After posting, I checked the player's profile. This is a Russian speaking user. I may even be able to name the deception he used. I think the developers know about this (in total, the community has more than 100 thousand subscribers).

**Comment by Mabadman** [comment]
Pretty sure cheats are "out of scope" for this bug-tracking repo.

**Comment by AnanasSok** [comment]
> Pretty sure cheats are "out of scope" for this bug-tracking repo.

I didn't quite understand what you mean, I chose the "other" template. Here I addressed the issue and suggested adding the ability to complain about players in post-match replays. We can also try to merge this theme with #1815. If you know where I should post a question, please let me know.

**Comment by commentator24** [comment]
you can report their steam account that they are cheating in a game with your evidence. if lucky they will get banned. replays only available for 1 week though, so I guess individual reviews can be exhausting and so they did nothing after replays no longer available.

Instead of ability to complain, it would be cool if someday dota has the ability/console command to suggest Overwatch review with your time stamps evidence. maybe something like /overwatch gameid, playerid, timestamps. but i guess this would be feature suggestion, not bug fixes

**Comment by TheUnholyWrath** [comment]
You can close this issue.
