### ISSUE TITLE
Marci bug with monkey's ulti

### ISSUE THREAD

**Issue by namphuong2409** [ValveSoftware/Dota2-Gameplay#3270]
### Description

monkey's Ulti is not working
and bulwark no applied bonus damage
![4](https://user-images.githubusercontent.com/61174741/191306242-b4e32c8a-7c32-4e7c-b380-aa5996e1fce1.jpg)

![2](https://user-images.githubusercontent.com/61174741/191306235-7f5ca2e6-e180-4f1c-aa3e-83b7e2f39fbe.jpg)
![3](https://user-images.githubusercontent.com/61174741/191306240-df462157-af5d-41f1-ac0d-6803cf2d9ae4.jpg)

![1](https://user-images.githubusercontent.com/61174741/191306228-16b46962-0eba-42dc-b7e2-517618ccacc2.png)

### Example Match ID (and possibly Timestamp)

6767863959 - 9:39 PM

**Comment by TheUnholyWrath** [comment]
You can close this issue.
