### ISSUE TITLE
Truestrike videos autoplay any time menu is opened

### ISSUE THREAD

**Issue by AHollowedHunter** [ValveSoftware/Dota2-Gameplay#3272]
### Description

Truestrike youtube videos autoplay. This is poor UX as they will play in the background with audio while you're in the middle of the game if you open the menu. Even if muted its still wasting bandwidth

**Comment by F0kT** [comment]
Same issue as: https://github.com/ValveSoftware/Dota2-Gameplay/issues/3274

Should be fixed now: https://github.com/SteamDatabase/GameTracking-Dota2/compare/e90a4c9aa371...fc258c59718f#diff-4abed47ecdc21a2f824671ad1d0fa6101142539005c56962393bae77d47ce7f9R72281

**Comment by AHollowedHunter** [comment]
as above, can confirm after update no more autplay
