### ISSUE TITLE
True Sight audio playing at Main Menu after update @ 20 September 2022 18:53:09 UTC

### ISSUE THREAD

**Issue by Flam3sDOTA** [ValveSoftware/Dota2-Gameplay#3274]
### Description

At main menu, a random true sight audio is being played after update @ 20 September 2022 18:53:09 UTC with no video being shown.

https://github.com/SteamDatabase/GameTracking-Dota2/commit/e90a4c9aa371ae32ff54d8eff0a41fc2196f90e8#diff-46a02338dac1d17daaf4bfc7c8bcff60fa7996d7fe8b26c7c99d167ee6c8e9d3L14

**Comment by F0kT** [comment]
Same issue as this one: https://github.com/ValveSoftware/Dota2-Gameplay/issues/3274

**Comment by okanfidan** [comment]
same issue

**Comment by kadirgun** [comment]
same here

**Comment by Flam3sDOTA** [comment]
Fixed with https://github.com/SteamDatabase/GameTracking-Dota2/compare/e90a4c9aa371...fc258c59718f#diff-4abed47ecdc21a2f824671ad1d0fa6101142539005c56962393bae77d47ce7f9R72281 Closing the issue.
