### ISSUE TITLE
Player's scoreboard in game visual issues

### ISSUE THREAD

**Issue by AntohaY** [ValveSoftware/Dota2-Gameplay#3275]
Player's scoreboard in game stretches out and **_heroes' levels_** are outside of circles **when** you **turn on to show items of your team**

**Comment by TheUnholyWrath** [comment]
#540 #2064

**Comment by LokeLok** [comment]
This has been fixed, you can close this.

**Comment by AntohaY** [comment]
Okay, thanks :)
