### ISSUE TITLE
2022 Battle Pass- Finished with a hero in Cavern Crawl, but no advancement

### ISSUE THREAD

**Issue by Gallahav** [ValveSoftware/Dota2-Gameplay#3282]
### Description

Hello,

Yesterday I played Single Draft with 2 friends (I wasn't the one who was LP, I was only helping a friend), and I picked Skywrath Mage out of my 3 options because I had 2 paths with him in my Cavern Crawl.
After we won, I saw the hero blowing up on the 2 paths and received random CC helping items (I don't remember which).
Today, I launched Dota2 and had a look at my CC map, I saw Skywrath Mage re-appeared, the 2 paths are blocked with him again, and the helping items are gone.
I have proof I played with him, won and yet have him blocking my Cavern paths- Attached.

MATCH ID: 6768323843

### Example Match ID (and possibly Timestamp)

6768323843

### Screenshots

![Screenshot 2022-09-21 112446](https://user-images.githubusercontent.com/74817304/191489397-9fdcc19a-65cd-4629-8f38-aa579cb0e235.png)
![Screenshot 2022-09-21 112512](https://user-images.githubusercontent.com/74817304/191489418-f778bc24-c670-4c24-a875-7f7ebf67e1c1.png)

**Comment by commentator24** [comment]
if not mistaken everyone in same party of LP will not gain any rewards from the match. you wont be able to complete guild contracts / challenge either

**Comment by TheUnholyWrath** [comment]
You can close this issue.

**Comment by Gallahav** [comment]
Closed.

**Comment by commentator24** [comment]
typing closed wont close it automatically 👀

**Comment by Gallahav** [comment]
Stop annoying me.
