### ISSUE TITLE
Issues with Profile Page

### ISSUE THREAD

**Issue by shaileshgarg** [ValveSoftware/Dota2-Gameplay#331]
### Description

Issue 1: Profile Level is offset from the its container box

![Screenshot 2022-06-03 112250](https://user-images.githubusercontent.com/26450759/171795428-4ba76502-8cfe-4595-9ac8-66d4def6e445.png)

Issue 2: Featured Hero is in the foreground, blocking Stuff behind it. It should be behind the other elements.

![20220617114932_1](https://user-images.githubusercontent.com/26450759/174237704-d78d53ac-0d7e-4bc8-ae12-352310dcbd87.jpg)

Issue 3: Typo in Tropies Page. Referring another Issue #1140

**Comment by LokeLok** [comment]
The ticket tab should also be hidden, when viewing trophy tab. So it doesn't overlap the profile icon, as it does in this picture.

**Comment by shaileshgarg** [comment]
Still not fixed.

**Comment by shaileshgarg** [comment]
Not fixed
