### ISSUE TITLE
Cavern Crawl not giving credit for wins

### ISSUE THREAD

**Issue by jborrero** [ValveSoftware/Dota2-Gameplay#3315]
### Description

This has persisted since earlier this week when the sticker update was released, where Cavern Crawl no longer provides credit for any wins. (Example Match ID provided)
Also, the Cavern Crawl overlay is not longer present during hero select in a matchmaking game (still appears in Heroes tab off of the main screen).

### Example Match ID (and possibly Timestamp)

6770128453

### Screenshots

![image](https://user-images.githubusercontent.com/4610544/191893709-447f9db2-c26e-45c1-8c48-9d2ed4acd595.png)

**Comment by boardgamesaz** [comment]
Amazing post. In the eventuality that you are unable to open your website, then I will refer you to one article about <a href="https://cookie-clicker.io/">cookie clicker</a> read this site and get this information.

**Comment by jborrero** [comment]
Seems like the hero-select overlay and cavern crawl progression have both started working today. Not sure what changed or if there was an update. No credit for any games previously played, however.
