### ISSUE TITLE
[Important] [UPDATED] [Earth Spirit] Double casting stone while rolling places stone behind Earth Spirit + other ES bugs

### ISSUE THREAD

**Issue by BlueHammer** [ValveSoftware/Dota2-Gameplay#336]
### Ability name

Rolling boulder + Stone remnant

### Description

**Double casting stone while already rolling places the stone behind Earth Spirit (wasting the stone pretty much).** 
This issue is introduced by changing default roll from 1200 to 1400 speed
Repro:
1. Have some latency by playing lobby (give or take 20ms++)
2. While already rolling, double cast stone remnant

Results:
1. Stone is placed behind Earth Spirit, essentially wasting the stone

Expected result:
1. Stone should be placed in front of Earth Spirit, allowing ES to boost his roll

Possible fix:
1. Let server decide where the stone should be placed (in front of ES) instead of the client deciding the location should be placed before sending to server
2. Revert Earth Spirit default roll speed to 1200.

Other bugs:
**Boulder smash prioritizing stone over hero/units**
Boulder smash behavior is bugged where it always prioritize to kick stone over units
https://i.redd.it/gmlg4a4mqoq81.gif
Repro (A):
1. Have stone nearby ES
2. Target Q to a unit

Results (A):
1. ES kicks the stone to the unit instead of kicking the unit

Expected result (A):
1. ES walk up to the unit and kick it

Repro (B):
1. Places a stone between ES and a unit some distance away
2. Target Q to the unit

Results (B):
1. ES will correctly walk towards the unit, however it will kick the stone to the unit instead as soon as a stone gets into its vicinity

Expected results (B):
1. ES walk up to the unit and kick it

Possible fix:
1. The spell should only attempt to kick a stone when targetting ground, if targetting a unit, ES should always attempt to kick the unit instead of kicking stone

**Geomagnetic pull prioritizing unit over stones**
https://i.redd.it/9tqpqgi7roq81.gif
It's impossible to pull a stone when unit is nearby
Repro:
1. Place a stone close to where a friendly creep is standing
2. Cast E on the stone

Results:
1. ES pulls the creep instead

Expected results:
1. ES should be able to pull the stone

Possible fix:
1. Stone remnant should be highlightable and it should have the same priority in being highlighted as normal unit

 **Boulder smash can target corpse**
https://i.redd.it/tkncpjworoq81.gif
ES will attempt to kick a dead unit so long as its corpse is still there
Repro:
1. Place a unit some distance away
2. Let ES cast Q on the unit
3. Before ES reaches the unit, kill the unit

Results:
1. ES will still walk up to the corpse and kick it

Expected results:
1. Like literally any other targetted spell, hero should stop attempting to cast the spell if the target is dead

Possible fix:
1. Change the spell mechanics to ignore corpse, currently the spell will only stop attempting to kick when the corpse expire after ~7 seconds

**Unable to cast Q [REPRO FOUND THANKS TO ANOTHER TICKET SUBMITTED]**
ES will be unable to kick any unit as long as there is a stone remnant in the 0,0,0 coordinate of the map (tested in demo map as well as normal map)
Repro:
1. Place a stone remnant in 0,0,0 of the map
2. Attempt to kick any unit

Results:
1. ES will walk up to the unit but will fail to kick the unit

Expected results:
1. ES should be able to kick the unit just fine

Possible fix:
1. Fix the code

**ES shard not granting charge**
This bug was introduced when the dev tried to fix the bug with charge-based abilities gaining infinite charge by buying/selling agha.
Repro:
1. Use up all ES stone charge
4. Buy a shard

Results:
1. No extra charges granted

Expected results:
1. ES immediately gain +4 charge (this was like that when it first released)

Possible fix:
1. Fix da code
3. Valve HR to increase the minimum standard of their hiring practice

**Comment by reacheight** [comment]
It's also very annoying when you start casting roll in a high angle direction (like behind) and self cast stone immidiatly after, the stone's placed somewhere between this angle and not in front of rolling direction. Probably not a bug tho, just the turn-rate thing 😩.

**Comment by BlueHammer** [comment]
> It's also very annoying when you start casting roll in a high angle direction (like behind) and self cast stone immediately after, the stone's placed somewhere between this angle and not in front of rolling direction. Probably not a bug tho, just the turn-rate thing 😩.

Unfortunately, I don't think it's a bug. It's like mirana jumping the wrong direction if you cast E too fast after making a high angle turn and before the turn fully completes.

**Comment by BlueHammer** [comment]
> Just to be clear, the rolling bug happpens if u use the remnant on the hero portrait while already rolling, it places the remnant behind the hero, but if u doulble tap the remnant it works correctly. Actually, if u are just standing and use remnant on the hero portrait it would place it just behind the hero, but if u double tap the spell it places it just in front of u.

No sorry, it's meant to be double casting and it's a real bug. You can try in 0 ms environment (ie. demo), double casting D while rolling will ALWAYS boost you. If you have some latency, it will only SOMETIMES boost you, other times it will place it behind. If your latency is high enough (say 50ms++), it will ALWAYS place it behind you. 

This bug was actually introduced by volvo changing the roll speed from 1200 to 1400. Too bad they don't test shit.

**Comment by shaileshgarg** [comment]
Some of thses fixed were fixed in today's update.

**Comment by stanleywilliamp** [comment]
Closing this, major bug fixes have been fixed.

Two bugs (or annoyances) left: 
- Unable to pull stone when units nearby
- Kick always prioritizing stone (latest patch note seems to suggest this is intentional)

**Comment by BlueHammer** [comment]
Closing this, all major bug fixes has been solved

2 left:
- Unable to pull stone when units nearby
- Kick always prioritizing stones (last patchnote seems to suggest this is intended)
