### ISSUE TITLE
Ability Draft - Normal punch is granted with shard

### ISSUE THREAD

**Issue by Muhammad-Shahbaz-Khan** [ValveSoftware/Dota2-Gameplay#3364]
### Description

If you buy shard with dark seer ultimate it grants normal punch. The ui displays normal punch as a septer upgrade but the spell in granted on purchasing the shard

### Example Match ID (and possibly Timestamp)

6771164732

**Comment by TheUnholyWrath** [comment]
You should put Ability Draft in the title
