### ISSUE TITLE
Crystal Maiden Frostbite not interrupting chanelling spells

### ISSUE THREAD

**Issue by Feedy88** [ValveSoftware/Dota2-Gameplay#3405]
### Ability name

Frostbite

### Description

When Crystal Maiden casts `Frostbite` onto enemy Heores that are chanelling spells, the channel is not interrupted.

### Example Match ID (and possibly Timestamp)

6771878463 - 4:39

**Comment by OkiPVP** [comment]
This is not a bug. Frostbite only interrupts TPs.

**Comment by CornejoS** [comment]
Enjoyed reading the article above , really explains everything in detail, the article is very interesting and effective. Thank you and good luck for the upcoming articles.

**Comment by ElizabethS13d** [comment]
Thanks for the information you shared. Loved the way you explained everything in this blog.

[Direct2HR
](https://www.direct2hr.us/)
