### ISSUE TITLE
Riki's assists were increasing on allied death

### ISSUE THREAD

**Issue by salavi** [ValveSoftware/Dota2-Gameplay#3438]
Description:

Riki got 37 assists while the Dire team (its team) scored 30 in total 

Match ID: 6776677135

Timestamp: 37:14

Screenshots:
An example of the bug is shown below. Riki's assists increase from 36 to 37 when Axe (an allied hero) dies.

<img width="1728" alt="Screen Shot 2022-09-25 at 3 39 36 PM" src="https://user-images.githubusercontent.com/7723894/192168933-aac4bc6f-b47b-47d8-a457-aa2009650827.png">

<img width="1718" alt="Screen Shot 2022-09-25 at 3 39 12 PM" src="https://user-images.githubusercontent.com/7723894/192168956-5980758d-07d5-4258-8fa5-ab7edce7c01c.png">

**Comment by murraymckay48** [comment]
Maybe I'm not qualified enough to spot the error here. But the color of the match was dramatic, so epic. [Elastic man](https://elasticman.co).

**Comment by TheUnholyWrath** [comment]
This has been fixed. You can close this issue.
