### ISSUE TITLE
Settings -> Options and Advanced Options toggles are resetting after restart game

### ISSUE THREAD

**Issue by Forise** [ValveSoftware/Dota2-Gameplay#3444]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
* Computer Information:
    Manufacturer:  ASUS
    Model:  System Product Name
    Form Factor: Desktop
    Touch Input Detected

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD Ryzen 9 5900X 12-Core Processor            
    CPU Family:  0x19
    CPU Model:  0x21
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  3700 Mhz
    24 logical processors
    12 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    AVX2:  Supported
    AVX512F:  Unsupported
    AVX512PF:  Unsupported
    AVX512ER:  Unsupported
    AVX512CD:  Unsupported
    AVX512VNNI:  Unsupported
    SHA:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Windows 11 (64 bit)
    NTFS:  Supported
    Crypto Provider Codes:  Supported 311 0x0 0x0 0x0

Video Card:
    Driver:  NVIDIA GeForce RTX 3070
    DirectX Driver Name:  nvldumd.dll
    Driver Version:  30.0.14.9676
    DirectX Driver Version:  30.0.14.9676
    Driver Date: 11 9 2021
    OpenGL Version: 4.6
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 143 Hz
    DirectX Card: NVIDIA GeForce RTX 3070
    VendorID:  0x10de
    DeviceID:  0x2484
    Revision:  0xa1
    Number of Monitors:  2
    Number of Logical Video Cards:  2
    No SLI or Crossfire Detected
    Primary Display Resolution:  2560 x 1440
    Desktop Resolution: 5120 x 1440
    Primary Display Size: 23.50" x 13.23" (26.97" diag)
                                            59.7cm x 33.6cm (68.5cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 8191 MB
    Supported MSAA Modes:  2x 4x 8x 

Sound card:
    Audio device: Realtek HD Audio 2nd output (Re

Memory:
    RAM:  32678 MB

VR Hardware:
    VR Headset: None detected

Miscellaneous:
    UI Language:  English
    Media Type:  Undetermined
    Total Hard Disk Space Available:  952572 MB
    Largest Free Hard Disk Block:  598178 MB
    OS Install Date: ??? 17 2021
    Game Controller: None detected
    MAC Address hash: 72dd51eb3b981be2aedee8ab19b50639e50925b3

Storage:
    Disk serial number hash: ac4d601
    Number of SSDs: 1
    SSD sizes: 1000G
    Number of HDDs: 0

* Have you checked for system updates?: [Yes/No] Yes

* Are you using the latest stable video driver available for your system? [Yes/No] Yes
* Have you verified the game files?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).
What i expectig: All the changes of settings and options in DOTA 2 are save. When i do change in Options it applies and saves after game Restart.
What happend: Settings->Options and Settings->Option->Advanced Options some options there are reseting all the time when i restart game.
I tried disable Steam Cloud sync. And enable back. And reinstall the game with deleting all the game files. Also tried to reinstall whole Steam app. Nothig helps. Have the same problem on my laptop also.

#### Steps for reproducing this issue:
!SteamCloud sync enabled. If SteamCloud sync is disabled than steps with user_convars.vcfg file are not valid, but the main problem still there.!
1. Start the game DOTA 2
2.  Go to Settings 
![image](https://user-images.githubusercontent.com/19363512/192250378-9641e58b-01bb-4b18-a94f-6c372e85a0f5.png)
4. Go to Options tap
![image](https://user-images.githubusercontent.com/19363512/192250449-1073944b-c21b-41fb-8a44-6a1692c150bb.png)
5. Change minimap toggle "Show minimap on the right". And other toggles (showed on screenshots)
was
![image](https://user-images.githubusercontent.com/19363512/192250797-4b635f0f-dd01-4ecb-bd19-e8a22c47747e.png)
new
![image](https://user-images.githubusercontent.com/19363512/192250936-8199d455-b920-4beb-8209-2a4cb3b736f1.png)
7. Go to "advanced options"
8. Change some toggles (Showed on screenshots)
was
![image](https://user-images.githubusercontent.com/19363512/192251319-e7c0872c-d876-41f9-86b5-aad20546e961.png)
new
![image](https://user-images.githubusercontent.com/19363512/192251408-c08ef7f1-b6ba-433c-99c7-fabc3d3632a6.png)
9. DO NOT CLOSE THE GAME
10. Go to C:\Program Files (x86)\Steam\userdata\USER_ID\570\remote
11. Open file user_convars.vcfg as text file
12. See that changed options are appeared as lines of config
![image](https://user-images.githubusercontent.com/19363512/192252451-b2ed466e-efc6-48ba-8a3d-40ff400cd9c0.png)
13. Close the opened user_convars.vcfg file
14. Close the game
15. Open file user_convars.vcfg as text file
16. Make sure that lines on config file are still there.
17. Close the opened user_convars.vcfg file
18. Start the game DOTA 2
19. Open file user_convars.vcfg as text file
20. See that changed/added lines are disappeared.
21. Go to Settings -> Options 
22. See that toggles have been reseted. 
![image](https://user-images.githubusercontent.com/19363512/192253372-b49f1147-2c06-4851-92ee-bc501f8c4305.png)
23. Same in "Advanced options"

**Comment by digitronce** [comment]
I am experiencing same issue. Tested on a laptop and a PC. PC is brand new with fresh Windows install.

**Comment by danieljennings** [comment]
We've shipped fixes for this today, can you confirm your problem here is resolved?

**Comment by ouroborouspanda** [comment]
> 
 I have had the same issue for a couple days, as of RIGHT NOW (9:44pm CST) my settings continue to be reset.

**Comment by Forise** [comment]
Still reproducing. NOT fixed

**Comment by DenisHarlamov** [comment]
Have the same problem

**Comment by tomba-pls** [comment]
> We've shipped fixes for this today, can you confirm your problem here is resolved?

Still reproducing in my case. I also made a thread with some of my specs etc here https://github.com/ValveSoftware/Dota2-Gameplay/issues/3170. If you need more info about my system or need me to run some sort of diagnostics tool feel free to let me know, I'd be happy to be of help.

**Comment by PAlNXtal** [comment]
Have the same problem

**Comment by mrpouyax** [comment]
OK, I just found the solution from another topic
https://github.com/ValveSoftware/Dota2-Gameplay/issues/2744#issuecomment-1267967817
#2744 

If your name has special symbols, please try changing your display name (from Steam). It (amazingly) fixed it for me, after I tried EVERYTHING (including deleting cloud caches, full install/uninstall, enable/disable Cloud, etc).

Somehow, after the name change, Dota does not trigger deletion of the saved .vcfg file and replacement with a weird-ish one.

**Comment by ouroborouspanda** [comment]
> OK, I just found the solution from another topic [#2744 (comment)](https://github.com/ValveSoftware/Dota2-Gameplay/issues/2744#issuecomment-1267967817) #2744
> 
> If your name has special symbols, please try changing your display name (from Steam). It (amazingly) fixed it for me, after I tried EVERYTHING (including deleting cloud caches, full install/uninstall, enable/disable Cloud, etc).
> 
> Somehow, after the name change, Dota does not trigger deletion of the saved .vcfg file and replacement with a weird-ish one.

I've found that removing the special characters didn't work, but changing the name entirely to one w/o special characters did??? lmao. freakin' maniacal. This solved my issue.

**Comment by Forise** [comment]
> > OK, I just found the solution from another topic [#2744 (comment)](https://github.com/ValveSoftware/Dota2-Gameplay/issues/2744#issuecomment-1267967817) #2744
> > If your name has special symbols, please try changing your display name (from Steam). It (amazingly) fixed it for me, after I tried EVERYTHING (including deleting cloud caches, full install/uninstall, enable/disable Cloud, etc).
> > Somehow, after the name change, Dota does not trigger deletion of the saved .vcfg file and replacement with a weird-ish one.
> 
> I've found that removing the special characters didn't work, but changing the name entirely to one w/o special characters did??? lmao. freakin' maniacal. This solved my issue.

JEASUS CHRIST IT WORKED! @danieljennings get atention to this problem. I've had nickname KARAS" - changed to KARAS (without "). and it's worked

**Comment by danieljennings** [comment]
Aha, thank you - I bet this was the crucial detail that prevented us from reproducing it internally

**Comment by danieljennings** [comment]
Okay, that was definitely the missing piece preventing us from reproducing the problem. I've got a fix for this bug in the release pipeline which should ship later today.

**Comment by danieljennings** [comment]
Okay this has been shipped, I'll close this in a couple days if I don't hear it's still broken. If anyone is still having this problem after patching today, let me know your repro steps (doesn't need screenshots) and your Steam profile URL (or your account/friend/Steam ID, anything works.)

**Comment by bptrsn** [comment]
@danieljennings This is still happening in 2024, is there a new issue I can track?

**Comment by moonarian** [comment]
This issue is still present in 2026. Most annoying is "Autoattack and autoattack on summoned units", though other settings are also observed to reset, though for me less commonly. Who knows maybe settings set in demo mode don't stick(kinda confirmed, why anyone would need separate settings for demo mode I've no idea. I use demo to set things up). Also turning off autoattack by holding "S"(cancel button) doesn't work, making autoattack of your units useless as you'll attack anyway, say, in bloodseekers ult.
