### ISSUE TITLE
KotL(Keeper of the Light) Illuminate leaves particles in front of dire mid t1 tower

### ISSUE THREAD

**Issue by Aphotic** [ValveSoftware/Dota2-Gameplay#345]
### Cosmetic Item Name

might be Kinetic Gem Effect: Northlight Illuminance or just Illuminate spell in general

### Description

 [Kinetic Gem Effect: Northlight Illuminance](https://dota2.fandom.com/wiki/Kinetic:_Northlight_Illuminance) &/or just Illuminate in general

that constantly flashes & leaves redundant white leftover particles in the center of the map, in front of dire mid t1 tower.
yes, i use that on top of Wings of Daybreak Immortal cus i believe the effects are more beautiful than the one horsy mangled by ugly Pegasus that Immortal Illuminate creates.

 also, fix his **tip of staff shimmer**([preview](https://static.wikia.nocookie.net/dota2_gamepedia/images/4/4f/Mastery_Northlight_Illuminance.gif/revision/latest?cb=20140622215941)) as it used to when we "channel" Illuminate.

other heroes with leftover map particles i recall:
Beastmaster's Axes
Lil' Shredder(Snapfire hero)
Bane nightmaring techies ulti/blast off would place his remote mine into this spot

### Example Match ID

6589009571 & 6598011626

### Screenshots

![image](https://user-images.githubusercontent.com/30921064/171806895-77e2c871-cca4-4ec5-b9f9-d5ce288dae6f.png)
![image](https://user-images.githubusercontent.com/30921064/171807122-b605f29d-f9c2-4b9a-8abc-ae23e34907cd.png)

**Comment by BlueHammer** [comment]
This also happens with some other particle effect. The particle is not correctly attached to a location/bones so it defaults to 0,0,0.

**Comment by Aphotic** [comment]
it gets even worse(bigger) particles with certain Items(my guess is the kinetic gem) as i named above and you can see in the screenshot below
 I'm farming in tringle, and that mangled effect appears in front of mid-tower, nowhere near me.
it can give enemy ideas on hey KOTL is farming something somewhere when they see that

![image](https://user-images.githubusercontent.com/30921064/172049381-30b1b4e2-5589-4bd9-91b2-1b375cbba889.png)

![image](https://user-images.githubusercontent.com/30921064/172049356-22f44ac2-13a9-483c-8b88-abda7c9d0c62.png)

**Comment by shubhrathi** [comment]
Batrider firefly also show at the center position.

**Comment by Oboo1** [comment]
puck also has similar issue, sometimes you can see maybe phase shift or orb animation on different side of map from where puck is currently.

**Comment by izvalve** [comment]
We tracked this down to the "Stag of the Northlight" variant for Illuminate.  This is now fixed and will be in the next update.

**Comment by Aphotic** [comment]
> We tracked this down to the "Stag of the Northlight" variant for Illuminate. This is now fixed and will be in the next update.

@izvalve 
since we are on the topic can we confirm that a similar particle-leak bug(colored reflect-damage of Tormentors) that occurs randomly all over the map when one of the Tormenters is being fought has been looked at/fixed as well?
 
It's kind game breaking since when you see the particle pop-up near you are 100% sure the enemy is taking a Tormentor even without having vision. 

but thank you, feels good to have this particle leak bug fixed after a year or more...

**Comment by LokeLok** [comment]
> > We tracked this down to the "Stag of the Northlight" variant for Illuminate. This is now fixed and will be in the next update.
> 
> @izvalve since we are on the topic can we confirm that a similar particle-leak bug(colored reflect-damage of Tormentors) that occurs randomly all over the map when one of the Tormenters is being fought has been looked at/fixed as well?
> 
> It's kind game breaking since when you see the particle pop-up near you are 100% sure the enemy is taking a Tormentor even without having vision.
> 
> but thank you, feels good to have this particle leak bug fixed after a year or more...

This was fixed in the 7.34c update. Taken from the update: Fixed Tormentor particles sometimes showing in fog of war
