### ISSUE TITLE
Isle of dragons 2nd Style Locked

### ISSUE THREAD

**Issue by ReilyX** [ValveSoftware/Dota2-Gameplay#3454]
### Cosmetic Item Name

Isle of dragons

### Description

I found 3 shards, before i unlock the skin and 2nd style is not working.
i do have 3 shards but the game not letting me use 2nd style its Locked for some reason...

### Example Match ID

6778266983

### Screenshots

![image](https://user-images.githubusercontent.com/114367173/192404985-6395a3be-d5c3-40f7-bbcd-0cb091da8ce2.png)
![image](https://user-images.githubusercontent.com/114367173/192405003-8fb9074c-a842-42fb-894d-8ff614a41e91.png)

**Comment by commentator24** [comment]
to unlock, use 2nd style in the armory 6x
