### ISSUE TITLE
Weekly Chest Battle Pass ( Tusk Chest )

### ISSUE THREAD

**Issue by irwanlimantauw** [ValveSoftware/Dota2-Gameplay#3457]
### Description

I **claimed** my last chest but screen stuck at weekly quest instead of tusk screen. then i relog my DOTA 2 
i cant see any claim. but **i didn't get my last tusk chest**

https://steamcommunity.com/id/irwanteneb/

### Screenshots

![weekly4](https://user-images.githubusercontent.com/30039348/192408256-0f2c8b51-a190-4028-9507-95e1d624aa54.png)
![log1](https://user-images.githubusercontent.com/30039348/192408249-1dfca206-ecf8-480b-b96a-1f13932e7f1c.png)
![log2](https://user-images.githubusercontent.com/30039348/192408233-246ac2e8-66ae-4c24-b5ad-bb271914193a.png)
![log3](https://user-images.githubusercontent.com/30039348/192408271-0b705584-eab3-4003-864b-70a0d56b031c.png)

**Comment by andrewsmithdesign** [comment]
check your armory/ inventory, might be sitting there still
