### ISSUE TITLE
Unable to spectate live games (stucked at loading screen)

### ISSUE THREAD

**Issue by jzhen94** [ValveSoftware/Dota2-Gameplay#3465]
### Description

Only had this problem few days ago, my Dota 2 is stucked at loading screen whenever I try to spectate any in-game matches, while loading lobby games/demo mode/watching a replay is fine. I have tried reinstalling and verifying game cache files but it still doesn't allow me to spectate any game.

Got this from console log. Is anyone facing the same issue or able to resolve it?

### Example Match ID (and possibly Timestamp)

Console log below

### Screenshots

[Client] CL:  CNetworkGameClient already exists for connection to '=[A:1:989343752:21422]'
[Client] CL:  connection to '=[A:1:989343752:21422]' already started
[Networking]       client =[A:1:989343752:21422[0]:  incoming timing out, last received 774.308640 [9.97 seconds ago]
[Networking]       client =[A:1:989343752:21422[0]:  incoming timing out, last received 774.308640 [19.97 seconds ago]
[Networking]       client =[A:1:989343752:21422[0]:  incoming timing out, last received 774.308640 [30.00 seconds ago]
[Networking]       client =[A:1:989343752:21422[0]:  incoming timing out, last received 774.308640 [40.01 seconds ago]
[Networking]       client =[A:1:989343752:21422[0]:  incoming timing out, last received 774.308640 [50.01 seconds ago]
[Networking]       client =[A:1:989343752:21422[0]:  incoming timing out, last received 774.308640 [60.01 seconds ago]
[Networking]       client =[A:1:989343752:21422[0]:  incoming timing out, last received 774.308640 [70.01 seconds ago]
[Networking]       client =[A:1:989343752:21422[0]:  incoming timing out, last received 774.308640 [80.02 seconds ago]
[Networking]       client =[A:1:989343752:21422[0]:  incoming timing out, last received 774.308640 [90.02 seconds ago]
[Networking]       client =[A:1:989343752:21422[0]:  incoming timing out, last received 774.308640 [100.02 seconds ago]
[Networking]       client =[A:1:989343752:21422[0]:  incoming timing out, last received 774.308640 [110.02 seconds ago]
[Console] Server connection ending: 29:NETWORK_DISCONNECT_TIMEDOUT
[Client] CL:  Server disconnected: 29: NETWORK_DISCONNECT_TIMEDOUT
ChangeGameUIState: DOTA_GAME_UI_STATE_LOADING_SCREEN -> DOTA_GAME_UI_DOTA_INGAME
[Client] LoadingDisplay changed from LOADING to NONE (map="")
[Client] Disconnection during connection phase. Sign-on state: 2 (SIGNONSTATE_CONNECTED). Disconnect reason: 29 (NETWORK_DISCONNECT_TIMEDOUT).
[Client] CL:  Disconnecting from server: NETWORK_DISCONNECT_TIMEDOUT
[NetSteamConn] Closing Steam Net Connection on socket 'client' to =[A:1:989343752:21422], handle #106765896 (2029 NETWORK_DISCONNECT_TIMEDOUT)
[NetSteamConn] CloseSteamNetConnection handle #106765896 (userdata 0)
[NetSteamConn] Disassociating NetChan       client                      [-1] (unknown) from Steam Net Connection handle #106765896 (userdata 0)
[Networking] Summary of connection [#106765896 SDR server steamid:90164000326168584 vport 1]:
[Networking]     End-to-end connection: connected
[Networking]         Remote host is in data center 'sgp'
[Networking]         Current rates:
[Networking]             Sent: 170.4 pkts/sec   5.5 K/sec
[Networking]             Recv:   1.0 pkts/sec   1.0 K/sec
[Networking]             Ping:2ms    Max latency variance: ???ms
[Networking]             Quality:  100%  (Dropped:0.00%  WeirdSeq:0.00%)
[Networking]             Est avail bandwidth: 102400.0KB/s  
[Networking]             Bytes buffered: 0
[Networking]         Lifetime stats:
[Networking]             Totals
[Networking]                 Sent:     18,951 pkts         610,107 bytes
[Networking]                 Recv:        130 pkts         125,185 bytes
[Networking]                 Recv w seq:        129 pkts
[Networking]                 Dropped   :          0 pkts   0.00%
[Networking]                 OutOfOrder:          0 pkts   0.00%
[Networking]                 Duplicate :          0 pkts   0.00%
[Networking]                 SeqLurch  :          0 pkts   0.00%
[Networking]             Ping histogram: (128 total samples)
[Networking]                      0-25    25-50    50-75   75-100  100-125  125-150  150-200  200-300     300+
[Networking]                       128        0        0        0        0        0        0        0        0
[Networking]                    100.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%
[Networking]             Ping distribution:
[Networking]                 5th   50th   75th   95th   98th
[Networking]                 2ms    2ms    2ms    3ms    4ms
[Networking]             Connection quality histogram: (7 measurement intervals)
[Networking]                 perfect    99+  97-99  95-97  90-95  75-90  50-75    <50   dead
[Networking]                       7      0      0      0      0      0      0      0      0
[Networking]                  100.0%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0%
[Networking]             Connection quality distribution:
[Networking]               50th  25th
[Networking]               100%  100%
[Networking]             Latency variance histogram: (9 total measurements)
[Networking]                       <1     1-2     2-5    5-10   10-20     >20
[Networking]                        9       0       0       0       0       0
[Networking]                   100.0%    0.0%    0.0%    0.0%    0.0%    0.0%
[Networking]         Rate stats received from remote host 19.9s ago:
[Networking]             Sent:   0.9 pkts/sec   0.9 K/sec
[Networking]             Recv: 170.2 pkts/sec   7.2 K/sec
[Networking]             Ping:2ms    Max latency variance: 1.4ms
[Networking]             Quality:  100%  (Dropped:0.00%  WeirdSeq:0.00%)
[Networking]             Bytes buffered: 0
[Networking]         Lifetime stats received from remote host 0.1s ago:
[Networking]             Totals
[Networking]                 Sent:        129 pkts         123,904 bytes
[Networking]                 Recv:     18,935 pkts         818,176 bytes
[Networking]                 Recv w seq:     18,934 pkts
[Networking]                 Dropped   :          0 pkts   0.00%
[Networking]                 OutOfOrder:          0 pkts   0.00%
[Networking]                 Duplicate :          0 pkts   0.00%
[Networking]                 SeqLurch  :          0 pkts   0.00%
[Networking]             Ping histogram: (127 total samples)
[Networking]                      0-25    25-50    50-75   75-100  100-125  125-150  150-200  200-300     300+
[Networking]                       127        0        0        0        0        0        0        0        0
[Networking]                    100.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%
[Networking]             Ping distribution:
[Networking]                 5th   50th   75th   95th   98th
[Networking]                 2ms    2ms    2ms    3ms    4ms
[Networking]             Connection quality histogram: (23 measurement intervals)
[Networking]                 perfect    99+  97-99  95-97  90-95  75-90  50-75    <50   dead
[Networking]                      23      0      0      0      0      0      0      0      0
[Networking]                  100.0%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0%
[Networking]             Connection quality distribution:
[Networking]               50th  25th   5th
[Networking]               100%  100%  100%
[Networking]             Latency variance histogram: (18933 total measurements)
[Networking]                       <1     1-2     2-5    5-10   10-20     >20
[Networking]                    18885      32      10       6       0       0
[Networking]                    99.7%    0.2%    0.1%    0.0%    0.0%    0.0%
[Networking]     Primary router: sgp#76 (103.10.124.117:27044)  Ping = 1+1=2 (front+back=total)
[Networking]         Current rates:
[Networking]             Sent: 170.5 pkts/sec   7.3 K/sec
[Networking]             Recv:   0.9 pkts/sec   1.1 K/sec
[Networking]             Ping:1ms    Max latency variance: ???ms
[Networking]             Quality:  100%  (Dropped:0.00%  WeirdSeq:0.00%)
[Networking]             Bytes buffered: 0
[Networking]         Lifetime stats:
[Networking]             Totals
[Networking]                 Sent:     18,951 pkts         819,145 bytes
[Networking]                 Recv:        144 pkts         125,396 bytes
[Networking]                 Recv w seq:        143 pkts
[Networking]                 Dropped   :          0 pkts   0.00%
[Networking]                 OutOfOrder:          0 pkts   0.00%
[Networking]                 Duplicate :          0 pkts   0.00%
[Networking]                 SeqLurch  :          0 pkts   0.00%
[Networking]             Ping histogram: (24 total samples)
[Networking]                      0-25    25-50    50-75   75-100  100-125  125-150  150-200  200-300     300+
[Networking]                        24        0        0        0        0        0        0        0        0
[Networking]                    100.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%
[Networking]             Ping distribution:
[Networking]                 5th   50th   75th   95th
[Networking]                 1ms    1ms    1ms    2ms
[Networking]             Connection quality histogram: (17 measurement intervals)
[Networking]                 perfect    99+  97-99  95-97  90-95  75-90  50-75    <50   dead
[Networking]                      17      0      0      0      0      0      0      0      0
[Networking]                  100.0%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0%
[Networking]             Connection quality distribution:
[Networking]               50th  25th
[Networking]               100%  100%
[Networking]             Latency variance histogram: (9 total measurements)
[Networking]                       <1     1-2     2-5    5-10   10-20     >20
[Networking]                        9       0       0       0       0       0
[Networking]                   100.0%    0.0%    0.0%    0.0%    0.0%    0.0%
[Networking]         Rate stats received from remote host 19.9s ago:
[Networking]             Sent:   1.1 pkts/sec   0.9 K/sec
[Networking]             Recv: 170.4 pkts/sec   7.2 K/sec
[Networking]             Ping:1ms    Max latency variance: 1.4ms
[Networking]             Quality:  100%  (Dropped:0.00%  WeirdSeq:0.00%)
[Networking]             Bytes buffered: 0
[Networking]         Lifetime stats received from remote host 0.1s ago:
[Networking]             Totals
[Networking]                 Sent:        143 pkts         124,928 bytes
[Networking]                 Recv:     18,936 pkts         819,200 bytes
[Networking]                 Recv w seq:     18,934 pkts
[Networking]                 Dropped   :          0 pkts   0.00%
[Networking]                 OutOfOrder:          0 pkts   0.00%
[Networking]                 Duplicate :          0 pkts   0.00%
[Networking]                 SeqLurch  :          0 pkts   0.00%
[Networking]             Ping histogram: (24 total samples)
[Networking]                      0-25    25-50    50-75   75-100  100-125  125-150  150-200  200-300     300+
[Networking]                        24        0        0        0        0        0        0        0        0
[Networking]                    100.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%
[Networking]             Ping distribution:
[Networking]                 5th   50th   75th   95th
[Networking]                 1ms    1ms    1ms    1ms
[Networking]             Connection quality histogram: (23 measurement intervals)
[Networking]                 perfect    99+  97-99  95-97  90-95  75-90  50-75    <50   dead
[Networking]                      23      0      0      0      0      0      0      0      0
[Networking]                  100.0%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0%
[Networking]             Connection quality distribution:
[Networking]               50th  25th   5th
[Networking]               100%  100%  100%
[Networking]             Latency variance histogram: (18933 total measurements)
[Networking]                       <1     1-2     2-5    5-10   10-20     >20
[Networking]                    18894      27       8       4       0       0
[Networking]                    99.8%    0.1%    0.0%    0.0%    0.0%    0.0%
[Networking]     Backup router: hkg#428 (153.254.86.183:27058)  Ping = -1+30=29 (front+back=total)
[Networking]     
[SteamNetSockets] [#106765896 SDR server steamid:90164000326168584 vport 1] closed by app, linger requested but not needed (2029) NETWORK_DISCONNECT_TIMEDOUT
[NetSteamConn] Removing Steam Net Connection for =[A:1:989343752:21422], handle #106765896
[Networking] Closing 'client' poll group
[HostStateManager] CHostStateMgr::QueueNewRequest( Idle (levelload), 7 )
[HostStateManager] Discarding pending request 'Remote Connect (=[A:1:989343752:21422]), 6'
[EngineServiceManager] SwitchToLoop levelload requested:  id [7] addons []
ChangeGameUIState: DOTA_GAME_UI_DOTA_INGAME -> DOTA_GAME_UI_STATE_LOADING_SCREEN
[Client] LoadingDisplay changed from NONE to LOADING (map="")
[HostStateManager] Idle (levelload)
[Client] CL:  CLoopModeLevelLoad::MaybeSwitchToGameLoop switching to "game" loopmode with addons ()
[EngineServiceManager] SwitchToLoop game requested:  id [7] addons []
[Server] CNetworkGameServerBase::SetServerState (ss_dead -> ss_waitingforgamesessionmanifest)
[Server] SV:  maxplayers set to 1
Initializing script VM...
...done
CSpeechScriptBridge was double-initialized: tearing down and rebuilding
[ResourceSystem] Error loading resource file "scripts/player.vdata_c" (Error: ERROR_FILEOPEN: File not found)
[ResourceSystem] Error loading resource file "scripts/vehicles.vdata_c" (Error: ERROR_FILEOPEN: File not found)
[Server] SV:  Spawn Server: <empty>
[Server] CNetworkGameServerBase::SetServerState (ss_waitingforgamesessionmanifest -> ss_loading)
[Server] CNetworkGameServerBase::SetServerState (ss_loading -> ss_active)
[Client] CL:  CWaitForGameServerStartupPrerequisite done waiting for server
[Client] CL:  CCreateGameClientJob creating client connection to 'loopback'
[SteamNetSockets] [#368267874 pipe] connected
[SteamNetSockets] [#207094117 pipe] connected
[Networking] Created poll group for socket 'client'
[Networking] Created poll group for socket 'server'
[Networking] Connected loopback client=15f35262@loopback:1 <-> server=c580165@loopback:0
[NetSteamConn] Associating NetChan        jzhen            loopback:0[1] (loopback:0) with Steam Net Connection handle #207094117 (userdata 0)
[NetSteamConn] Associating NetChan       client            loopback:1[0] (loopback:1) with Steam Net Connection handle #368267874 (userdata 1)
[Client] CL:  Connected to 'loopback:1'
[Server] SV:  Sending server info to client 'jzhen' at loopback:0
[Server] SV:  WriteInitialSpawnGroups sending 1 groups
[Server] Client 0 'jzhen' setting rate to 2000000000
[Client] Game: "Dota 2"
[Client] Map: "<empty>"
[Client] Players: 1 (0 bots) / 1 humans
[Client] Build: 9462 (revision 7535300)
[Client] Server Number: 4
[SignonState] CL:  CNetworkGameClient::ProcessServerInfo
ReadSteamRemoteStorageFile( bufOut, "voice_ban.dt" ) -> 0.000470 seconds
[ResourceSystem] Error loading resource file "maps/dota/entities/neutralcamp_evil_4_2699_9835.vmdl_c" (Error: ERROR_FILEOPEN: File not found)
[ResourceSystem] Error loading resource file "maps/dota/entities/neutralcamp_evil_5_2699_9833.vmdl_c" (Error: ERROR_FILEOPEN: File not found)
[ResourceSystem] Error loading resource file "maps/dota/entities/neutralcamp_good_1_2699_9829.vmdl_c" (Error: ERROR_FILEOPEN: File not found)
[ResourceSystem] Error loading resource file "maps/dota/entities/neutralcamp_evil_1_2699_9839.vmdl_c" (Error: ERROR_FILEOPEN: File not found)
[ResourceSystem] Error loading resource file "maps/dota/entities/unnamed_2699_9848.vmdl_c" (Error: ERROR_FILEOPEN: File not found)
[ResourceSystem] Error loading resource file "maps/dota/entities/unnamed_2699_9851.vmdl_c" (Error: ERROR_FILEOPEN: File not found)
[ResourceSystem] Error loading resource file "maps/dota/entities/unnamed_2699_25701.vmdl_c" (Error: ERROR_FILEOPEN: File not found)
[Client] CNetworkGameClientBase::LinkClasses took 23.837 msec
[ResourceSystem] Error loading resource file "particles/water_impact/water_splash_02.vpcf_c" (Error: ERROR_FILEOPEN: File not found)
[ResourceSystem] Error loading resource file "particles/water_impact/water_splash_03.vpcf_c" (Error: ERROR_FILEOPEN: File not found)
[ResourceSystem] Error loading resource file "particles/water_impact/water_splash_01.vpcf_c" (Error: ERROR_FILEOPEN: File not found)
[ResourceSystem] Error loading resource file "maps/dota/entities/neutralcamp_good_6_2699_9821.vmdl_c" (Error: ERROR_FILEOPEN: File not found)
[ResourceSystem] Error loading resource file "maps/dota/entities/neutralcamp_good_3_2699_9825.vmdl_c" (Error: ERROR_FILEOPEN: File not found)
[ResourceSystem] Error loading resource file "maps/dota/entities/neutralcamp_good_2_2699_9827.vmdl_c" (Error: ERROR_FILEOPEN: File not found)
[ResourceSystem] Error loading resource file "maps/dota/entities/unnamed_2699_25707.vmdl_c" (Error: ERROR_FILEOPEN: File not found)
[ResourceSystem] Error loading resource file "maps/dota/entities/unnamed_2699_26396.vmdl_c" (Error: ERROR_FILEOPEN: File not found)
[ResourceSystem] Error loading resource file "maps/dota/entities/neutralcamp_evil_8_2699_26645.vmdl_c" (Error: ERROR_FILEOPEN: File not found)
[ResourceSystem] Error loading resource file "maps/dota/entities/neutralcamp_evil_7_2699_27172.vmdl_c" (Error: ERROR_FILEOPEN: File not found)
[ResourceSystem] Error loading resource file "maps/dota/entities/neutralcamp_good_7_2699_27175.vmdl_c" (Error: ERROR_FILEOPEN: File not found)
[ResourceSystem] Error loading resource file "maps/dota/entities/neutralcamp_good_5_2699_27178.vmdl_c" (Error: ERROR_FILEOPEN: File not found)
[ResourceSystem] Error loading resource file "maps/dota/entities/neutralcamp_good_4_2699_9823.vmdl_c" (Error: ERROR_FILEOPEN: File not found)
[ResourceSystem] Error loading resource file "maps/dota/entities/neutralcamp_evil_6_2699_27320.vmdl_c" (Error: ERROR_FILEOPEN: File not found)
[ResourceSystem] Error loading resource file "maps/dota/entities/neutralcamp_evil_2_2699_9841.vmdl_c" (Error: ERROR_FILEOPEN: File not found)
[ResourceSystem] Error loading resource file "maps/dota/entities/neutralcamp_evil_9_2699_27340.vmdl_c" (Error: ERROR_FILEOPEN: File not found)
[ResourceSystem] Error loading resource file "maps/dota/entities/neutralcamp_good_8_2699_27461.vmdl_c" (Error: ERROR_FILEOPEN: File not found)
[ResourceSystem] Error loading resource file "maps/dota/entities/neutralcamp_good_9_2699_27484.vmdl_c" (Error: ERROR_FILEOPEN: File not found)
[ResourceSystem] Error loading resource file "maps/dota/entities/neutralcamp_evil_3_2699_9837.vmdl_c" (Error: ERROR_FILEOPEN: File not found)
[ResourceSystem] Error loading resource file "maps/dota/entities/unnamed_2699_27805.vmdl_c" (Error: ERROR_FILEOPEN: File not found)
[ResourceSystem] Error loading resource file "maps/dota/entities/bad_result_position_2699_28052.vmdl_c" (Error: ERROR_FILEOPEN: File not found)
[ResourceSystem] Error loading resource file "maps/dota/entities/bad_result_position_2699_28056.vmdl_c" (Error: ERROR_FILEOPEN: File not found)
[ResourceSystem] Error loading resource file "maps/dota/entities/bad_result_position_2699_28058.vmdl_c" (Error: ERROR_FILEOPEN: File not found)
[ResourceSystem] Error loading resource file "maps/dota/entities/bad_result_position_2699_28066.vmdl_c" (Error: ERROR_FILEOPEN: File not found)
[ResourceSystem] Error loading resource file "maps/dota/entities/bad_result_position_2699_28060.vmdl_c" (Error: ERROR_FILEOPEN: File not found)
[ResourceSystem] Error loading resource file "maps/dota/entities/unnamed_2716_4090_43.vmdl_c" (Error: ERROR_FILEOPEN: File not found)
[ResourceSystem] Error loading resource file "maps/dota/entities/unnamed_2716_4090_49.vmdl_c" (Error: ERROR_FILEOPEN: File not found)
[ResourceSystem] Error loading resource file "maps/dota/entities/unnamed_2716_2431_58.vmdl_c" (Error: ERROR_FILEOPEN: File not found)
[ResourceSystem] Error loading resource file "maps/dota/entities/unnamed_2699_27807.vmdl_c" (Error: ERROR_FILEOPEN: File not found)
[ResourceSystem] Error loading resource file "maps/dota/entities/roshan_location_2699_27790.vmdl_c" (Error: ERROR_FILEOPEN: File not found)
[Client] CL:  CGameClientConnectPrerequisite connection succeeded
ChangeGameUIState: DOTA_GAME_UI_STATE_LOADING_SCREEN -> DOTA_GAME_UI_STATE_DASHBOARD
[Client] LoadingDisplay changed from LOADING to NONE (map="<empty>")
[Server] SV:  IGameSystem::LoopActivateAllSystems {
[Host] HO:  IGameSystem::LoopActivateAllSystems {
[Host] HO:  } IGameSystem::LoopActivateAllSystems done
[Server] SV:  } IGameSystem::LoopActivateAllSystems done
[Server] SV:  Game started
[Client] CL:  IGameSystem::LoopActivateAllSystems {
ReadSteamRemoteStorageFile( bufOut, "scripts/control_groups.txt" ) -> 0.000471 seconds
[Client] CL:  } IGameSystem::LoopActivateAllSystems done
[SignonState] CL:  CNetworkGameClient::OnSwitchLoopModeFinished( game : success )
[GCClient] Send msg 7197 (k_EMsgGCMatchmakingStatsRequest), 8 bytes
[Server] SV:  Sending full update to client jzhen (reason:  initial update)
[Client] CL:  Receiving uncompressed update from server
[Networking]       client            loopback:1[0]:  NetChan Setting Timeout to 30.00 seconds
[Client] CL:  Signon traffic "client":  incoming 64.847 KB [143 pkts], outgoing 1.046 KB [138 pkts]
[Networking]        jzhen            loopback:0[1]:  NetChan Setting Timeout to 20.00 seconds
[GCClient] Recv msg 7198 (k_EMsgGCMatchmakingStatsResponse), 300 bytes
[SteamNetSockets] [#106765896 SDR server steamid:90164000326168584 vport 1] Discarding inactive session hkg#428 (153.254.86.183:27058).  ConnectionShutdown
[SteamNetSockets] [#106765896 SDR server steamid:90164000326168584 vport 1] Discarding inactive session sgp#76 (103.10.124.117:27044).  ConnectionShutdown
[SteamNetSockets] Received Stats from sgp#76 (103.10.124.117:27044) using incorrect/stale connection ID 106765896.  Rejecting wth NoConnection reply.
[SteamNetSockets] Received Stats from sgp#76 (103.10.124.117:27044) using incorrect/stale connection ID 106765896.  Rejecting wth NoConnection reply.
[SteamNetSockets] Received Stats from sgp#76 (103.10.124.117:27044) using incorrect/stale connection ID 106765896.  Rejecting wth NoConnection reply.
[SteamNetSockets] Received Stats from sgp#76 (103.10.124.117:27044) using incorrect/stale connection ID 106765896.  Rejecting wth NoConnection reply.
[SteamNetSockets] Received Stats from sgp#76 (103.10.124.117:27044) using incorrect/stale connection ID 106765896.  Rejecting wth NoConnection reply.
[SteamNetSockets] Received Stats from sgp#76 (103.10.124.117:27044) using incorrect/stale connection ID 106765896.  Rejecting wth NoConnection reply.
[SteamNetSockets] Received Stats from sgp#76 (103.10.124.117:27044) using incorrect/stale connection ID 106765896.  Rejecting wth NoConnection reply.
[SteamNetSockets] Received Stats from sgp#76 (103.10.124.117:27044) using incorrect/stale connection ID 106765896.  Rejecting wth NoConnection reply.
[SteamNetSockets] Received Stats from sgp#76 (103.10.124.117:27044) using incorrect/stale connection ID 106765896.  Rejecting wth NoConnection reply.
[SteamNetSockets] Received Stats from sgp#76 (103.10.124.117:27044) using incorrect/stale connection ID 106765896.  Rejecting wth NoConnection reply.
[SteamNetSockets] Received Stats from sgp#76 (103.10.124.117:27044) using incorrect/stale connection ID 106765896.  Rejecting wth NoConnection reply.
[SteamNetSockets] Received Stats from sgp#76 (103.10.124.117:27044) using incorrect/stale connection ID 106765896.  Rejecting wth NoConnection reply.
[SteamNetSockets] Received Stats from sgp#76 (103.10.124.117:27044) using incorrect/stale connection ID 106765896.  Rejecting wth NoConnection reply.
[SteamNetSockets] Received Stats from sgp#76 (103.10.124.117:27044) using incorrect/stale connection ID 106765896.  Rejecting wth NoConnection reply.
[SteamNetSockets] Received Stats from sgp#76 (103.10.124.117:27044) using incorrect/stale connection ID 106765896.  Rejecting wth NoConnection reply.
[SteamNetSockets] Received Stats from sgp#76 (103.10.124.117:27044) using incorrect/stale connection ID 106765896.  Rejecting wth NoConnection reply.
[SteamNetSockets] Received Stats from sgp#76 (103.10.124.117:27044) using incorrect/stale connection ID 106765896.  Rejecting wth NoConnection reply.

**Comment by jzhen94** [comment]
Managed to resolve it by deleting the dota 2 beta folder on my hard drive and reinstalling it.

**Comment by JoelMahon** [comment]
Not very helpful but for future readers: I had the same issue and deleting the dota 2 beta folder fixed it for me as well.

Don't make the same mistake I did: don't forget to move your autoconfig.cfg before you delete the folder.

**Comment by Staindk** [comment]
I'm running into this now as well. I don't think this issue should be closed TBH.

I ended up here after googling the below, unsure if these lines are actually causing the problem though.

```
[ResourceSystem] Error loading resource file "particles/water_impact/water_splash_03.vpcf_c" (Error: ERROR_FILEOPEN: File not found)
[ResourceSystem] Error loading resource file "particles/water_impact/water_splash_02.vpcf_c" (Error: ERROR_FILEOPEN: File not found)
[ResourceSystem] Error loading resource file "particles/water_impact/water_splash_01.vpcf_c" (Error: ERROR_FILEOPEN: File not found)
```

I really don't want to reinstall the game... but guess I will do so someday soon if this persists.

**Comment by AmirTahani** [comment]
Same issue here
