### ISSUE TITLE
Towers now incorrectly have a turn rate.

### ISSUE THREAD

**Issue by emirkmo** [ValveSoftware/Dota2-Gameplay#3466]
### Description

As of at least the latest battle pass with the crab towers, ALL towers now incorrectly have a turn rate. This means that the tower will sometimes stop hitting creeps, while “turning”, even though most towers obviously have no turn animations. This also means they can also do less damage to diving enemies, which is an unintended change.

Linking a Reddit thread showing the new bugged behavior, causing the mid OD to miss a creep last hit: https://www.reddit.com/r/DotA2/comments/xpb549/can_someone_explain_why_my_tower_suddenly_stop/

The thread has video evidence.

Edit: Although I am unsure of the previous behavior, as far as I can find, all towers had the fastest possible turn rate, since all units have a turn rate, but it is now conditionally noticeably slower in the linked clips. The desired behavior is, as before, that the tower does not miss hitting a creep or a hero running through at normal game speeds. The bug is this turn rate becoming noticeable enough to affect how towers hit units moving around within range.

### Example Match ID (and possibly Timestamp)

6777165804 at 6:02
6767565254 at 4:41

### Screenshots

[clip for matchID 1](https://www.reddit.com/r/DotA2/comments/xpb549/can_someone_explain_why_my_tower_suddenly_stop/)
[clip for matchID 2](https://clips.twitch.tv/HealthySwissPorcupineChocolateRain-ZsxGaGUJcJe5C70m)

Match IDs and clips thanks to @Galinhoo .

**Comment by Galinhoo** [comment]
Match ID: 6777165804 at 6:02
Clip: https://www.reddit.com/r/DotA2/comments/xpb549/can_someone_explain_why_my_tower_suddenly_stop/

Match ID: 6767565254 at 4:41
Clip: https://clips.twitch.tv/HealthySwissPorcupineChocolateRain-ZsxGaGUJcJe5C70m

**Comment by Fawesum** [comment]
Towers has had turn rates since day one I think.

**Comment by emirkmo** [comment]
> Towers has had turn rates since day one I think.

As far as I can find, they have had the fastest possible turn rate, since technically all units have a turn rate. But the behavior from @Galinhoo's post is new. I'll edit to make that clear.

**Comment by Aluerie** [comment]
> Fixed the motion correction buffering on attacking and casting sometimes increasing the effective distance. This fixes the issue with towers sometimes briefly stopping attacking

Fixed ?

**Comment by emirkmo** [comment]
Good catch, most likely? I can’t test

**Comment by Dota-Exp** [comment]
This issue should have been addressed in a previous update. Please let us know if this issue persists.
Closing for now. Thank you.
