### ISSUE TITLE
Tiny's Prestige Item Sword has a bug since  7.23

### ISSUE THREAD

**Issue by Polykomodo** [ValveSoftware/Dota2-Gameplay#3478]
### Cosmetic Item Name

Majesty Of The Colossus 

### Description

The problem is in position of the sword, i have put the screenchot from prevous versoin so you could compare.

### Example Match ID

123456789

### Screenshots

![image](https://user-images.githubusercontent.com/107393089/192583042-3b6d9a84-3ce0-40d2-b986-7c1219051bb6.png)

**Comment by shaileshgarg** [comment]
Still the same.

**Comment by shaileshgarg** [comment]
#103

**Comment by Astiberon** [comment]
FIXED
