### ISSUE TITLE
After 7.32c, Permanent Counterspell aura on Rubick HAS NOT FIXED.Enter a short summary here!

### ISSUE THREAD

**Issue by DpRd745** [ValveSoftware/Dota2-Gameplay#3486]
### Ability name

Spell steal

### Description

7.32c patch note : Fixed Rubick with Aghanim's Shard, stealing Anti-Mage's Counterspell, and receiving the Shard aura permanently.
After I DEMO, it still works with permenant Counterspell aura -10% spell reduction.
![image](https://user-images.githubusercontent.com/106855630/192684665-948b3f02-f52f-4522-affa-ecc0240c8a6f.png)

### Example Match ID (and possibly Timestamp)

DEMO

**Comment by Dota-Exp** [comment]
The issue was that the aura did not go away if Rubick lost  Counterspell. This has been fixed.
If Rubick has shard, he should get the aura when stealing Counterspell.
