### ISSUE TITLE
Made a mistake issue resolved I'm dumb

### ISSUE THREAD

**Issue by Jazazpear** [ValveSoftware/Dota2-Gameplay#3489]

**Comment by TheUnholyWrath** [comment]
"When Shadow Strike ends or is re-applied to an enemy Hero, the target emits a Scream of Pain, hitting any nearby enemies."

I watched your game, unless I'm missing something obvious QoP aghs is working fine. The scream doesn't hit the hero that dagger is being reapplied to, it only hits units in the AoE around them. The wording also seems to indicate that the scream doesn't work on creeps if you were confused by that as well. Seems like its kind of a shit aghs but what do I know.
