### ISSUE TITLE
Jugger set in cavern of secret

### ISSUE THREAD

**Issue by Barca692** [ValveSoftware/Dota2-Gameplay#3496]
### Item name

island of dragon

### Description

Hi, 
i have unlock the jugger's set in the cavern of secret and i have all the 3 fragments:

<img width="269" alt="1" src="https://user-images.githubusercontent.com/114565524/192717895-b2f01fc5-41e7-4556-a029-ef25ff8526d1.png">

but i have only the set base and not the trasmute (the blues set):

<img width="791" alt="2" src="https://user-images.githubusercontent.com/114565524/192717916-b204d0f2-cc13-467b-81fb-4c09160992ed.png">

I wanted to inform you that i have found before the 3 fragments and after i have unlock the base set:

<img width="157" alt="3" src="https://user-images.githubusercontent.com/114565524/192718040-39679a38-0fc2-4c7c-9c30-95cf9a827419.png">

I checked my inventory, but I don't have the treasure with the blue set inside.
Can you check my problem?
Thanks

### Example Match ID and Timestamp

i dont have any match id and timestamp for u

**Comment by ulmaer** [comment]
I have the same problem, how can it be solved?
