### ISSUE TITLE
-15% powershot damage reduction not taking effect

### ISSUE THREAD

**Issue by JQINX** [ValveSoftware/Dota2-Gameplay#3498]
Went in demo picked windrunner and lvl up to 15 and maxed power shot skill. Choose enemy lion and made power shot. Lion Hp dowend to 224 at lvl 1. Choose 
-15 % power shot talent from skill tree and made power shot againt and still hp downed to 224.

**Comment by TheUnholyWrath** [comment]
https://user-images.githubusercontent.com/46859977/192763192-9254432c-e981-4a0a-a23d-d5d1714fc4bd.mp4

**Comment by homephix** [comment]
I faced an issue where my -15% powershot damage reduction had not been taking effect for long[.](https://homephix.co.uk/) Please help me resolve this as well.

**Comment by Dota-Exp** [comment]
The damage reduction pertains to the Reduction per Unit value and looks to be working as intended

**Comment by onesmartsheep1** [comment]
I had witnessed a same activity on my Dota2 and now I figured it is also similar to the mentioned one. What am I supposed to do now[.](https://onesmartsheep.com/) Let me now. Thank you.
