### ISSUE TITLE
BP - True Sight missing Voiceline Reward

### ISSUE THREAD

**Issue by dankvada** [ValveSoftware/Dota2-Gameplay#3499]
### Description

one True Sight voiceline (Team Spirit) is missing as a reward

### Screenshots

![image](https://user-images.githubusercontent.com/114586087/192778236-0709d642-aaeb-41a9-a293-000b787407be.png)

**Comment by jaydenprime** [comment]
i have the same issue

**Comment by dankvada** [comment]
it got patched - popped up for me as reward 451
