### ISSUE TITLE
Rubick interaction with Astral Spirit + Aghs

### ISSUE THREAD

**Issue by angryansari** [ValveSoftware/Dota2-Gameplay#3513]
### Ability name

Spell Steal

### Description

Stealing Astral + Resturn Astral spirit with a Rubick created a weird interaction where rubick kept casting a free Astral spirit at the same effectivtly giving rubick permanent spell immunity, this effect lingered even after rubick had replaced both spell slots 

Spell immunity kicks in at Timestamp 25:15
Match ID: 6781166188

### Example Match ID (and possibly Timestamp)

Match ID: 6781166188 Timestamp  25:15

**Comment by angryansari** [comment]
![image](https://user-images.githubusercontent.com/35526493/192903594-484eeb35-d110-4d81-b0cd-85801f949e2e.png)

able to re-create it in practice mode by stealing astral spirit , using recall spirit then stealing astral spirit again before the original spirit comes back

**Comment by TheUnholyWrath** [comment]
#302

**Comment by angryansari** [comment]
Fixed
