### ISSUE TITLE
Wraith Pact attacks to destroy says 5 but is 4

### ISSUE THREAD

**Issue by mastercoms** [ValveSoftware/Dota2-Gameplay#3514]
### Item

Wraith Pact

### Description

"Totem can be destroyed in 5 hits" uses a static, non-bold 5, even though it was changed in 7.31d to 4 hits.

### Screenshots

![Tooltip](https://user-images.githubusercontent.com/2672245/192923003-321e447b-1ae7-4602-849e-28a5211e1be2.png)

**Comment by Dota-Exp** [comment]
Will be fixed in upcoming update.
