### ISSUE TITLE
Не дали сундук за задания недели из компендиума

### ISSUE THREAD

**Issue by Bellikon** [ValveSoftware/Dota2-Gameplay#3527]
### Description

Выполнил задание недели, открыл сундук, ни анимации, ничего не произошло, за то показывает что сундук открыт и уровень я якобы получил. Что мне делать? 

### Screenshots

![20220929113702_1](https://user-images.githubusercontent.com/114652875/192983348-7135447a-7a06-4136-b34a-828efae0e738.jpg)
![20220929113709_1](https://user-images.githubusercontent.com/114652875/192983359-180d4443-6bbe-4a28-8d16-13648c6835ef.jpg)

**Comment by TIP4IK3232** [comment]
У меня такая же проблема не знаю, что делать

**Comment by Bellikon** [comment]
VALVE отдали сундук
