### ISSUE TITLE
Venomancer Latent Toxicity incorrect interactions.

### ISSUE THREAD

**Issue by Bogdanov89** [ValveSoftware/Dota2-Gameplay#3533]
### Ability name

Latent Toxicity

### Description

Latent Toxicity states "If this poison is dispelled in any way, the target will receive a large amount of damage and be stunned.".
I tested through all the abilities and items that grant dispel, hard dispel, spell immunity and invulnerability and found the following inconsistent behaviors:

Phantom Lancer Doppelganger: removes the Latent Toxicity without suffering stun or damage.
Pudge shard (Dismember on teammates): removes the Latent Toxicity without the Dismember ally suffering damage nor stun.
Lifestealer Infest: removes the Latent Toxicity without suffering stun or damage.
Phoenix Supernova (self and teammate via Aghanims Scepter): removes the Latent Toxicity without anyone suffering stun or damage.
Huskar Life Break: Latent Toxicity properly triggers (damage and stun) but the Huskar fails to actually jump at the target (stays close to original location where it was cast).

**Biggest problem is Phantom Lancer Doppelganger because there are other similar abilities in Dota2 (like Chaos Knight Phantasm, Manta Style, Euls Scepter...) which properly activate Latent Toxicity's stun and damage, but the Doppelganger allows Phantom Lancer to dispel and completely avoid the penalties of Latent Toxicity.**

### Example Match ID (and possibly Timestamp)

not applicable

**Comment by oguzhangulaydin** [comment]
Hello,
'dispelled in any way' is a wrong statement, the correct one is 'dispelled'
Lifestealer gain spell immunity that's why he cant get effect coz Latent Toxicity does not pierce spell immunity.
phantom lancer is not effected coz he is not in the dota world during Doppelganger 
pudge shard same, eaten hero is not in the map to be effected but in pudge stomach
supernova turns phonix into a egg, and it's not a hero anymore u cant stun or spell egg,
if you think with this perspective, you would understand why those spells working like that

**Comment by Bogdanov89** [comment]
Latent Toxicity dispel penalty stun & damage do pierce spell immunity, it goes through spell immunity and even invulnerability (such as provided by Eul scepter). It will hurt and stun people who activate black king bar, and it will hurt and stun Lifestealer when he activates his Rage spell.
You could have easily tested this by yourself.

Phantom Lancer Doppelganger works the same as Chaos Knight Phantasm, Naga Mirror Image and item Manta Style - yet Latent Toxicity dispel penalty works against all those abilities, but fails to work versus Doppelganger... imho clearly an oversight.

Lifestealer Infest, Pudge Dismember and Phoenix Supernova simply hide the heroes - they still exist and can be affected by some effects. But whether Latent Toxicity should affect them or not should be properly clarified in game.

**Comment by Dota-Exp** [comment]
Huskar And Phantom Lancer will be fixed in an upcoming update. Infest and Dismember are for the time being working as intended.

**Comment by Bogdanov89** [comment]
Thanks!
