### ISSUE TITLE
Batrider Sticky Napalm Having the Wrong Cast Range

### ISSUE THREAD

**Issue by medrew** [ValveSoftware/Dota2-Gameplay#3576]
### Ability name

Sticky Napalm

### Description

According to the patch notes of patch update 7.32c, Batrider's Sticky Napalm ability should be set to a cast range of 600 at all levels, as opposed to the 550/600/650/700 it was previously. However, according to the tooltip in-game, Sticky Napalm's cast range is set as 550. Attached is evidence of this tooltip in-game, along with comparison of an ability with 575 cast range, Mist Coil. With Batrider and Abaddon standing at the same point, Mist Coil's range extends further than Sticky Napalm's proving that it is set at 550, and isn't just a tooltip error.

I presume either the patch notes were incorrect and the intent was to set Sticky Napalm's cast range at its lowest level, or that the ability was improperly set to its lowest level range for all levels, instead of its second lowest level as stated in the patch notes.

![Sticky_cast_range](https://user-images.githubusercontent.com/114832262/193426326-6ae4741a-c77c-43ee-8867-8b86e9837ff1.jpg)
![Mist_coil_cast_range](https://user-images.githubusercontent.com/114832262/193426329-59660bcc-cfa2-4cd8-840b-36dd5870d1dc.jpg)

I'm not sure if this is the right place to document improperly patched abilities, but either way it would nice to either receive clarity that the patch notes were incorrect, or if Batrider was accidentally nerfed harder than intended. I assume the match ID is unnecessary since it's evident from screencaps, so I've included a random match I pulled from Dotabuff with the 7.32c changes in effect.

In any case, thank you all for your service in maintaining the game we love.

### Example Match ID (and possibly Timestamp)

6784474333

**Comment by Dota-Exp** [comment]
fixed in upcoming update
