### ISSUE TITLE
monkey king ulti doesnt work

### ISSUE THREAD

**Issue by Artimansky** [ValveSoftware/Dota2-Gameplay#3577]
### Description

Monkey king ultimate "Wukong command" cooldown freezes after first use. And aganim scepter not create copy(totally not work)
Retry in lobby with another hero and issue repeats

### Example Match ID (and possibly Timestamp)

6785722541 - 2.10.2022 00:58

**Comment by TheUnholyWrath** [comment]
#3187

**Comment by Artimansky** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/3187
