### ISSUE TITLE
Medusa Split Shot works as a passive; Dark Seer Normal Punch does not turn off

### ISSUE THREAD

**Issue by Tf4ilure** [ValveSoftware/Dota2-Gameplay#358]
https://user-images.githubusercontent.com/24322051/171827362-9a6fd4c9-8e17-4acd-8d6c-60b2fcfd78b6.mp4

### Ability name

Split Shot; Normal Punch

### Description

Medusa Split Shot works as a passive. 
Normal Punch is not disabled by any break effects.

### Example Match ID (and possibly Timestamp)

6555123715 - 41:50

**Comment by Uwila** [comment]
Medusa behavior is intended: It's a passive that you can toggle to turn off; this behavior is probably intended. TheZett explained it in a reaction to my post here: #185 

Normal Punch does look bugged though.
