### ISSUE TITLE
Broken Earth Shaker Arcana Alt Style Progress / Progress Bar in Turbo

### ISSUE THREAD

**Issue by lipovac** [ValveSoftware/Dota2-Gameplay#360]
After finishing a turbo game as earthshaker using the arcana, the arcana progress bar appears and animates the addition of the total echo slam kills+assists earned during the game, but no progress is actually made/saved.

Assume you played a few normal games as ES with arcana, and were granted 100/500 echo slam kills/assists towards the alt skin style. Now, if you play a turbo game and get for example 10 kills, at the end of the game the animation will play showing that you progressed from 100/500 to 110/500. I you play another turbo game though, lets assume with 15 kills, it will play the animation starting from 100 again to 115, instead of from 110 to 125. If you then play a normal game and get 20 kills, it will play the animation from 100 to 120, but this progress will actually be saved, and in a subsequent game it will show progress starting from 120 instead of 100.

With Arcana progress, turbo games usually account for only half points. So either, this needs to be fixed to be (kill+assists)/2 and play the animation, or the animation should be entirely removed and no progress should be made when playing turbo. Ideally, it would be 1/2 progress to match the other arcanas.

**Comment by NMOTH** [comment]
on topic of older arcanas not incrementing in turbo #45

**Comment by GeneSylvari** [comment]
Mentioning this here as there are multiple similar threads open on the topic of certain arcanas such as Pudge, Earthshaker not working for even half credit in turbo.

**Comment by Aluerie** [comment]
Since this is the post with most upvotes highlighting issue about arcana gems not counting int turbo - I guess it would be a nice thing to list all arcanas that do not work in turbo (correct me i missed something):

* Phantom Assassin 
* Juggernaut
* Earthshaker
* Pudge

**Comment by Sultanswing** [comment]
![Uploading 041F5E22-670F-46D2-A07F-C4E8A1938AE3.png…]()

**Comment by gotrunks712** [comment]
To add to this. Hoodwink Acorn Shot Relic also doesn't update at all in Turbo. It worked at some point, because I have 49k progress. But a game with 20k Acorn Shot damage provided zero progress.

**Comment by Aluerie** [comment]
No PA arcana mention - sadge ; but nice that other arcanas are fixed.

![image](https://user-images.githubusercontent.com/33165440/223278863-54308e7a-2b15-41e9-a31d-5c2901c91dfc.png)

**Comment by Aluerie** [comment]
Eh now we have hundred of fixed issues about arcanas that OPs won't ever check back x_x and much more if we include other topics.

Also I wish we could open some mega-thread for non-working Relics instead of referencing this issue but idk, the concept of upvotes isnt well advertised for any new thread to go up without reddit push.

**Comment by Aluerie** [comment]
Still, @Valve is it intentional that PA arcana is the *only* one that does not work in turbo at all.

**Comment by kwanesir** [comment]
70% of relics still do not trck in turbo in 7.33

**Comment by maskalek** [comment]
have the same problems with sky mage
ps that was a good decision to buy dota plus for month, not for year )))

**Comment by Aluerie** [comment]
Made #8899 for that^

**Comment by lipovac** [comment]
Closing bug as it was fixed in 7.32E: https://www.dota2.com/deadreckoning
