### ISSUE TITLE
Outerworld Destroyer - Sanity's Eclipse does no damage on (ancient ?) creeps

### ISSUE THREAD

**Issue by DipSwitch** [ValveSoftware/Dota2-Gameplay#3605]
### Ability name

Sanity's Eclipse

### Description

I tried to help a teammate by damaging ancient creeps with my ultimate, and to see how much damage it does. But to my surprise it did no damage at all... I would have expected 200 damage + the mana pool difference.

### Example Match ID (and possibly Timestamp)

6788516839 - 20:25

**Comment by TheUnholyWrath** [comment]
the alt text says "Does not damage creeps or neutral units."

**Comment by DipSwitch** [comment]
Ow lol, never read the alt text then I guess. I'll close.
