### ISSUE TITLE
Ultimate Dazzle is dispelled from allies and opponents

### ISSUE THREAD

**Issue by Tf4ilure** [ValveSoftware/Dota2-Gameplay#363]
### Ability name

Bad Juju

### Description

Ultimate Dazzle is dispelled from allies and opponents

https://user-images.githubusercontent.com/24322051/171828358-c6ec9542-90b4-452f-92c8-25210e3d9b98.mp4

### Example Match ID (and possibly Timestamp)

See attached video

**Comment by TheUnholyWrath** [comment]
This has been fixed
