### ISSUE TITLE
I can't use talent voice lines from this year (2022)

### ISSUE THREAD

**Issue by BaiBuaBok11** [ValveSoftware/Dota2-Gameplay#3631]
### Item name

Ephey, SirActionSlacks, SUNSfan and TeaGuvnor voice lines

### Description

I can't use this year's talent voice line that I purchase (no sound, no text - seems like it's not working at all), but other voice lines work well (BP voice line, platinum guild voice line, and last year voice line - Avo+ You're dead).

I think it's because I buy the talent voice lines before buying the BP, so I can't use them and I can't refund them too.

https://user-images.githubusercontent.com/36475889/193751470-35041908-8b50-450e-a858-8c0e3567395e.mp4

### Example Match ID and Timestamp

since 03-10-2022 till present

**Comment by TheUnholyWrath** [comment]
#3573

**Comment by BaiBuaBok11** [comment]
It's working now thank you so much! @TheUnholyWrath
