### ISSUE TITLE
Arcane blink's debuff amplification does not work with Hammer of Purity

### ISSUE THREAD

**Issue by wmpay** [ValveSoftware/Dota2-Gameplay#3646]
### Ability name

Hammer of Purity

### Description

Arcane blink's debuff amplification does not work with hammer of Purity. At level 4, it is 38% both before and after using arcane blink.

### Example Match ID (and possibly Timestamp)

N/A found in demo mode

**Comment by TheUnholyWrath** [comment]
![20221005120121_1](https://user-images.githubusercontent.com/46859977/193957480-6c7c84be-b264-44ea-b858-1433facba4d7.jpg)
Debuff Amplification doesn't increase the value of the slow, it increases the duration its applied for.

**Comment by benw25** [comment]
![image](https://user-images.githubusercontent.com/21284372/195211456-6104ff28-a0ba-41ea-9c76-053749fb18f3.png)

Confirming what @TheUnholyWrath said above; the debuff amplification in this case applies to the duration of the debuff

Original duration: 5 seconds.
Modified duration with Arcane Blink buff active: 5 * ( 1 + 20% ) = 6 seconds

**Comment by wmpay** [comment]
I see, I will close then.
