### ISSUE TITLE
KOTL Illuminate Level 25 stun not working

### ISSUE THREAD

**Issue by simplyexperimental** [ValveSoftware/Dota2-Gameplay#3659]
### Ability name

Illuminate

### Description

Keeper of the light.
Can someone confirm. In demo mode at level 25 the talent to stun for 1.2 is not working.
Can you please confirm and fix this if it's also present in ranked.

### Example Match ID (and possibly Timestamp)

Check Demo mode first.

**Comment by LokeLok** [comment]
It works just fine

**Comment by simplyexperimental** [comment]
Resolved.
