### ISSUE TITLE
Shadow Poison level 2 does 32 damage per stack instead of 36. 

### ISSUE THREAD

**Issue by Mod-masta** [ValveSoftware/Dota2-Gameplay#3660]
### Ability name

Shadow Poison

### Description

According to previous patch notes, level 2 of shadow poison should have stack damage of 24/36/48/60. Which is a 12 increase per level. In game, however, the damage is 24/32/48/60. Level 2 is doing 4 less damage per stack than it is supposed to. This is both shown in the tooltip and also affects the actual damage numbers. 

### Example Match ID (and possibly Timestamp)

tested in demo

**Comment by TheUnholyWrath** [comment]
#926

**Comment by Dota-Exp** [comment]
This issue will be fixed in an upcoming update, thank you.
