### ISSUE TITLE
Talent line Chat wheel

### ISSUE THREAD

**Issue by rek222** [ValveSoftware/Dota2-Gameplay#3686]
### Description

I bought a talent line chat wheel yesterday, it appeared in the chat wheel itself, but nothing happens in the game when you click it
how to fix it?

6793514895 Match ID 

![talent line dota 2](https://user-images.githubusercontent.com/115182241/194544878-8c66fcc3-8f73-4605-88cf-ddc26c99d304.png)

### Example Match ID (and possibly Timestamp)

6793514895

### Screenshots

![talent line dota 2](https://user-images.githubusercontent.com/115182241/194545114-5dbb00ae-559a-4b85-b2fe-d6870bebbb92.png)

**Comment by TheUnholyWrath** [comment]
#3573

**Comment by kemiz1** [comment]
why was this closed? how was this fixed?
