### ISSUE TITLE
Can't spectate(watch game) anyone in my friends lists

### ISSUE THREAD

**Issue by siroasd** [ValveSoftware/Dota2-Gameplay#3692]
It used to work till last patch, i don't know whats happening, when i click watch game on friend it goes to load, i see loading screen but never does. After 3-4 mins it goes back to main menu without saying anything.

My system: i5-12600k - 16gbRam- GTX 1070

If i can provide any logs whatsoever, let me know.

Please help.
Thanks in advance.

![image](https://user-images.githubusercontent.com/115297238/194651047-8f59e4ef-0575-46b4-932f-f227e72bca0f.png)

**Comment by Aluerie** [comment]
People report that switching setting from high-end network to low helps them solve this spectate issue. 

Some say that you can even switch back to high end and be fine.

**Comment by siroasd** [comment]
> 

Yaas, this actually worked, thanks for help !

**Comment by rastla** [comment]
This should not be closed, because it's actually still an issue. Clicking this setting is just a workaround

**Comment by stuckin18** [comment]
> People report that switching setting in Advanced from high-end network to low helps solve this spectate issue.
> 
> Some say that you can even switch back to high end and be fine.

damn its not working for me before i try switch the network, after 1-2 minute it back to main menu, but now it just forever loading screen

**Comment by Aluerie** [comment]
Another known workaround for this is 
1) uninstall dota 
2) delete `dota 2 beta` folder manually from `Steam\steamapps\common` to cleanse it properly 
3) install dota back normally

This was mentioned as suggested workaround by Valve devs according to Gorgc on his stream and CapCasts in [this comment](https://www.reddit.com/r/DotA2/comments/y10k7m/comment/irvljm6/?utm_source=share&utm_medium=web2x&context=3).

**Comment by timothysykes** [comment]
The game should be improved so that gamers can follow anyone on their friends list. [URL=https://ovo-game.com][color=#efefef][size=1]ovo game[/size][/color][/URL]
