### ISSUE TITLE
Anti-Mage aghanim scepter causes Sven Storm Hammer to gain aghanim scepter upgrade

### ISSUE THREAD

**Issue by HeadYak** [ValveSoftware/Dota2-Gameplay#3702]
### Ability name

Counter Spell/Storm Hammer

### Description

When an Anti-Mage with aghanims scepter reflects Sven's Storm Hammer, the reflected stun gains the aghanims scepter upgrade. 

### Example Match ID (and possibly Timestamp)

https://www.youtube.com/watch?v=yKsuG9U5wp8

**Comment by yckmm** [comment]
This is how reflected abilities have always worked and therefore can be considered the intended behavior. The reflected abilities behave as if they are casted by the reflecting hero and get aghs/shard upgraded if the reflecting hero has them (even if the original caster does not).

**Comment by HeadYak** [comment]
I see, it didn't feel intuitive to me so I thought it was a bug. Thank you for clarifying.

**Comment by HeadYak** [comment]
Also another question, in this specific case, Sven after buying Aghanims Scepter will travel along a casted Storm Hammer however he can toggle the autocast behavior of Storm Hammer to not travel along with it. Anti-Mage however has no option to modify the reflected Storm Hammers behavior.

Would there be any merit in changing the Storm Hammer aghanims upgrade where its default unautocasted state does not force the caster to travel along side it where this behavior is then enabled when the spell is autocasted. 

This would change the behavior to what I originally expected.

**Comment by erickanu** [comment]
you have to visit this [site](https://classyapk.com/) to solve your problem.

**Comment by TheUnholyWrath** [comment]
> Would there be any merit in changing the Storm Hammer aghanims upgrade where its default unautocasted state does not force the caster to travel along side it where this behavior is then enabled when the spell is autocasted.

#2280 go give it a thumbs up/comment there.

**Comment by dianaannu** [comment]
To solve your problem you can take help from [snapchat mod apk](https://apksbrand.com/snapchat-mod-apk/).
