### ISSUE TITLE
Grimstroke's Level 10 talent +50 Phantom Embrace DPS does not work

### ISSUE THREAD

**Issue by ma4r** [ValveSoftware/Dota2-Gameplay#3716]
### Ability name

Phantom's Embrace

### Description

Grimstroke's Level 10 talent +50 Phantom Embrace DPS does increase the dps dealt

### Example Match ID (and possibly Timestamp)

6796496944 - 22:00

**Comment by ElizabethS13d** [comment]
Great article! I realized these are my favorite kinds of GI articles. Enough news and reviews, more stuff like this! Let the writers get creative!
