### ISSUE TITLE
Проблема при покупке одноразового предложения Battle pas

### ISSUE THREAD

**Issue by MAvisHola** [ValveSoftware/Dota2-Gameplay#3771]
### Description

Хотел купить одноразовое предложение Battlepas Где 120 уровней и сокровищницы, не получилось с первого раза, пополнил баланс стима, и хотел еще раз его купить, но предложение пропало, пожалуйста верните предложение для его покупки.
Steam - praimbd

**Comment by v1adeezy** [comment]
Пофиксили?
