### ISSUE TITLE
1×1 ward cliff next to the Radiant fountain (which you can TP onto, and get stuck)

### ISSUE THREAD

**Issue by anko** [ValveSoftware/Dota2-Gameplay#381]
### Description

Just north of the Radiant fountain, there is a tiny 1-tile-large highground ward cliff. You can place wards on it (which give flying-equivalent vision, as cliff wards do), and you can Blink or Force Staff to stand up there with a hero.

If you target a TP on the unpathable cliff behind the fountain shop, and the nearest pathable terrain happens to be this tiny cliff, you can end up stuck there, with your TP on cooldown.

Units or wards up there cannot see into the fountain area, probably because the fountain has an inward vision blocker, similar to the Roshan pit.

You can see the tiles better with the console commands `sv_cheats 1` followed by `cl_dota_gridnav_show 1`, as in the screenshot below.

I believe this has been in the game since 7.29d.

### Example Match ID (and possibly Timestamp)

Easy to replicate in any lobby using the default Dota 2 map.

### Screenshots

https://user-images.githubusercontent.com/5231746/171849854-0a95ae28-5555-4998-82fb-4d0fb4237be6.mp4

![gridnav](https://user-images.githubusercontent.com/5231746/171851156-38a7ac54-25aa-43de-ade2-9c29f2068b9e.png)

**Comment by Krimatoria** [comment]
Only the ward will not be very effective there. After all, at the end of the game, the towers are already broken, most likely if you have access to the fountain.

**Comment by Aluerie** [comment]
I just realised that you don't mention the real issue in this post... as other duplicates post say:


you can get stuck on this spot as any hero simply by teleporting with TP scroll.

**Comment by anko** [comment]
I updated the title, and added a brief description of how to get stuck there by TPing.

**Comment by MortonKenos** [comment]
ive had this issue before, i was panic clicking on the minimap and it happened, its so lonely up there

**Comment by Aluerie** [comment]
Apparently there is samish problem spot in the Dire base too (thanks to [this reddit post](https://www.reddit.com/r/DotA2/comments/15kt77e/my_first_ever_game_and_im_stuck_in_a_wall_am_i/))

You can get stuck by manually tping there. 

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/33165440/87b9184d-ea9f-46bd-ab47-f425fc47e675)

**Comment by GDoe5** [comment]
![20230908222723_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/12865776/84ad335c-654a-42b8-a5a2-17ecbfba50ca)

I managed to TP to this spot in a game the other day. It was frustrating as I was unable to do anything but wait for TP. My nature's prophet pushed me down with sprout.

**Comment by Aluerie** [comment]
https://steamcommunity.com/games/dota2/announcements/detail/3735230544064408128
> Fixed an area above the Radiant fountain that heroes could get stuck in

**Comment by anko** [comment]
Confirming fixed. :+1: 

The cliff has been removed. The area is now an additional dead-end path behind the trees. This screenshot shows the same tiles (`cl_dota_gridnav_show 1`) as my [earlier screenshot](https://user-images.githubusercontent.com/5231746/171851156-38a7ac54-25aa-43de-ade2-9c29f2068b9e.png):

![shot](https://github.com/ValveSoftware/Dota2-Gameplay/assets/5231746/5383bce8-0ca5-4fd4-98ee-a3a1e739f5fb)

**Comment by anko** [comment]
It's back...

(See issue backlinks and [this /r/dota2 post](https://www.reddit.com/r/DotA2/comments/1qyxyw6/be_careful_not_to_tp_to_base_by_hovering_your/)).
