### ISSUE TITLE
Arcane Curse Hits Longer and Harder than it should!

### ISSUE THREAD

**Issue by dotabugreporterforfree** [ValveSoftware/Dota2-Gameplay#3819]
### Ability name

Arcane Curse

### Description

Silencers Arcane Curse deals more damage on the initial first Curse hit and also hits longer than described. Alot of times the curse hits 8+ seconds without any spell/cast being done by Shadow Fiend. This happens throughout the game. Two timestamps have been provided. 

### Example Match ID (and possibly Timestamp)

6805649601 (4.18 and 4.52)

**Comment by TheUnholyWrath** [comment]
From the Arcane Curse tooltip: "Silenced enemies take 1.5x slow and damage." "The cooldown is paused as long as the target is silenced". In 7.32c Arcane Curse was buffed to do 40/60/80/100 Burst Damage on application. Looking at the combat log and watching the game this all seems to be working correctly

**Comment by dotabugreporterforfree** [comment]
> From the Arcane Curse tooltip: "Silenced enemies take 1.5x slow and damage." "The cooldown is paused as long as the target is silenced". In 7.32c Arcane Curse was buffed to do 40/60/80/100 Burst Damage on application. Looking at the combat log and watching the game this all seems to be working correctly

thanks for the feedback. I missed the 1.5x slow and damage on silenced units part -.- 

Guess there was never any issue, gonna close it. Have a nice weekend

**Comment by dotabugreporterforfree** [comment]
Just a quick question, why is the curse longer than 6 seconds? During the Laning phase the curse hits 8 sec+ according to combat log, but sf never casts any spells.

**Comment by TheUnholyWrath** [comment]
> Just a quick question, why is the curse longer than 6 seconds? During the Laning phase the curse hits 8 sec+ according to combat log, but sf never casts any spells.

"The cooldown is paused as long as the target is silenced" I don't think the wording for this isn't super clear, basically Arcane Curse duration gets extended by any time you are silenced. When Silencer uses Arcane Curse and a level 1 Last Word on you, Curse will last for 9s.

**Comment by dotabugreporterforfree** [comment]
Ah okay thanks for the clarification.
