### ISSUE TITLE
Losing the ability to cast Shadow Walk on self when channeling

### ISSUE THREAD

**Issue by krotgo** [ValveSoftware/Dota2-Gameplay#3825]
### Ability name

Shadow Walk

### Description

After buying Aghanim's Shard you lose the ability to cast Shadow Walk when you are channeling (i.e. Teleporting), but only on yourself.

### Example Match ID (and possibly Timestamp)

6803753775

**Comment by TheUnholyWrath** [comment]
#2563

**Comment by Dota-Exp** [comment]
Will be fixed in the upcoming update. Thank you.
