### ISSUE TITLE
only 6 ingame predictions got rewarded

### ISSUE THREAD

**Issue by gruianovac** [ValveSoftware/Dota2-Gameplay#3834]
am i missing something? i predicted over 20 correctly.. why just 6?

**Comment by Liam-NFLD** [comment]
I believe there is a daily limit of 6. I haven't seen any communication of this, but then there also hasn't been any communication that they're rewarded at all afaik.

**Comment by TheUnholyWrath** [comment]
I couldn't find any documentation for it this year, but last year they said this: "While watching matches during the Group Stage and Main Event, try your luck at In-Game Predictions and earn 100 Compendium Points per correct prediction, up to six per day." 
(https://www.dota2.com/newsentry/2870472829293831072 ). Seems like its deliberate and just carries over.

**Comment by Einarr228** [comment]
fuck same shit for me, first matches of a groop i got my 6 predicts, and then loose 5 hours for nothing ? fuck
