### ISSUE TITLE
Lion ulti not working

### ISSUE THREAD

**Issue by MeeMaster** [ValveSoftware/Dota2-Gameplay#3853]
Just now I played a match, where I played Lion and built agha.
On at least 4 occasions, I would use ult and no damage would be dealt. This basically cost us the match.
If I used the ult on creeps it would work just fine.
Match no. 6808362818

**Comment by TheUnholyWrath** [comment]
"When you take damage and your health falls below 70%, a strong dispel is applied and you gain a 2.5 second buff that provides +75% Status Resistance and causes all damage you deal and are dealt to be reduced to zero.". There is no bug here, the dragon knight even told you what was happening. The damage from Pugna's Ward was causing your Aeon Disk to activate, making you deal 0 damage. Please close this issue.
