### ISSUE TITLE
Hero description error (dota2.com)

### ISSUE THREAD

**Issue by Randomaize** [ValveSoftware/Dota2-Gameplay#3854]
### Description

https://www.dota2.com/hero/batrider
CAST RANGE:
550.0

Idk how feedback there, so written here
I made update heroes here (https://dota2.fandom.com/ru/wiki/Dota_2_%D0%92%D0%B8%D0%BA%D0%B8) and noticed wrong description in the official source. I guess there are maybe other errors 

Thanks for your attention :)

**Comment by TheUnholyWrath** [comment]
#3576

**Comment by Randomaize** [comment]
Thanks :)
