### ISSUE TITLE
dota freezes on startup on linux with vulkan

### ISSUE THREAD

**Issue by taurenrogue** [ValveSoftware/Dota2-Gameplay#3863]
### Description

Basically the title, it just freezes on the black screen with the dota2 logo...
Tried:
-various launch options, nothing works except "-gl"
-rebooting
-running both steam native/runtime
-verified game files

kernel version: 6.0.1
nvidia driver version: 520.56.06
arch/kde 5.26/X11

EDIT:
seems to  be working fine now, for me atleast on same nvidia drivers so volvo must have patched it out

**Comment by deek0146** [comment]
I'm having the same issue

**Comment by shoddysheep** [comment]
Same problem persists here. Also on fully updated Arch/X11. "-gl" works for now.

**Comment by DashKiller** [comment]
Same problem here

**Comment by ypo777** [comment]
I am also having the same issue. 
- Ubuntu 22.04 
- Ryzen 5 5600G
- [Full System Info](https://gist.github.com/ypo777/0a6a233fb927e0126c806b0df585c80b)](https://gist.github.com/ypo777/0a6a233fb927e0126c806b0df585c80b)

**Comment by dab0u** [comment]
Same problem here !
Manjaro up to date.

**Comment by Jbudone** [comment]
Same issue, I've narrowed my case down to nvidia driver version 520.56.x
Downgrading to 515.76.x allows the game to start

**Comment by FossForUs1** [comment]
Interestingly as per above comment Nvidia now recommend: 515.76 for my graphics card as per: https://www.nvidia.com/download/index.aspx

I havethe same issue, specs below:
OS: Nobara Linux 36 (Thirty Six) x86_64 
Kernel: 5.19.16-201.fsync.fc36.x86_64 
DE: GNOME 42.3.1
Nvidia driver version: 520.56.06

Vulkaninfo
Vulkan Instance Version: 1.3.224
GPU 0: Integrated GPU:
apiVersion        = 4206822 (1.3.230)
driverVersion     = 92282979 (0x5802063
GPU1: Discrete GPU
apiVersion        = 4206797 (1.3.205)
driverVersion     = 2181955968 (0x820e0180
GPU 2: CPU
apiVersion        = 4206822 (1.3.230)
driverVersion     = 1 (0x0001)

**Comment by kaiyazeera** [comment]
Problem also occurs on

Arch Linux

linux 6.0.6.arch1-1
nvidia 520.56.06-8
nvidia-utils 520.56.06-2

Cinnamon

**Comment by shoddysheep** [comment]
This is going to be a problem. On the update Valve made on November 3rd, they mention that it is the last big update to have OpenGL support, as it will be removed after that...

**Comment by JBraunJB** [comment]
Same problem here only starts with "-gl"

**Comment by taurenrogue** [comment]
-vulkan_disable_graphics_pipeline_library

^ this actually works
credit afaik to @tiritto in https://github.com/ValveSoftware/Dota2-Gameplay/issues/4930#issuecomment-1304609066

**Comment by taurenrogue** [comment]
working fine for me (as of 16.11.2022)
