### ISSUE TITLE
Misbehaving ranked matchmaking algorithm

### ISSUE THREAD

**Issue by davefojtik** [ValveSoftware/Dota2-Gameplay#3866]
# Prerequisites
- [x] I have a clean, VAC-free, long-standing account
- [x] I checked the steam community and found no answer
- [x] I created a discussion on steam community and got no answer
- [x] I checked the internet and studies about matchmaking systems in general
- [x] I recalibrated my MMR
- [x] I tried to change my game style, roles, time of day I play and also take a break or play more often to break this
- [x] I did more than enough repetitions of the pattern to be sure this is a consistent problem across patch updates

# Expected Behavior
As per the definition of skilled-based systems: The player progresses with well-balanced teams where both sides have an equal chance to win. The player can have some assigned skill point that the system thinks he should have (e.g. CSGO), and playing matches above this point should feel harder and more challenging, but the system does not purposefully ensure the loss of the player before the matches themselves by putting him into teams with a much lower chance of winning or finding opponents with much higher win chance to keep him there.

# Current Behavior
I am experiencing "hard stops" at specific MMR points. The winning streak games feel unfair as well, because my team is made out of friendly and well-behaving players while the other often isn't. If the enemy team had the same, this would be an expected quality of matches with 10k behaviour score. But balanced games happen very rarely.
When I hit that "MMR hard stop", I usually lose the exact same amount of games I won with such ease. I am placed into the bad behaving teams which feel like being made out of the lowest behaviour score players the game can find. These players tend to troll, blame, use really bad language, throw the game before it even starts and thus have a much lower chance of winning against normal behaviour teams. Please note that I am not at all discussing how each player plays. Everyone can have a bad day. But the fact that after reaching a certain MMR point, the behaviour score of the people I'm teamed with changes dramatically. And that doesn't make much sense after geting many recommendations from these winning streaks and no reason to be matched with them. I am attaching pictures of how such a pattern looks:

<p float="left">
<img src="https://user-images.githubusercontent.com/66263283/196065293-64cea20e-9ee5-4d55-9955-258dd093f39c.png" data-canonical-src="https://user-images.githubusercontent.com/66263283/196065293-64cea20e-9ee5-4d55-9955-258dd093f39c.png" width="200" height="400">
<img src="https://user-images.githubusercontent.com/66263283/196065296-b14611a8-20cb-4d7c-8646-93829e1d7e7b.png" data-canonical-src="https://user-images.githubusercontent.com/66263283/196065296-b14611a8-20cb-4d7c-8646-93829e1d7e7b.png" width="180" height="400">
<img src="https://user-images.githubusercontent.com/66263283/196065295-0a4326d3-47c2-4d3b-98e3-c5e6506e99df.png" data-canonical-src="https://user-images.githubusercontent.com/66263283/196065295-0a4326d3-47c2-4d3b-98e3-c5e6506e99df.png" width="133" height="400">
</p>

## Steps to Reproduce
1. Play solo ranked on my account for some time
2. See this pattern over and over

## Context
Account Behaviour Score in points whole time: 10.000
Account Debug info: "behavior_score: Normal"

##
I did not experience so precisely repeated patterns in any other competitive game and it does not feel right. It's almost as if the game would use behaviour scores to alter match balance, and that sounds more like an EOMM (Engagement Optimized Matchmaking), rather than Skill Based Matchmaking the developers say Dota has. Maybe I am wrong but in any case, it would be nice to have some official feedback from the developers how it's possible to see this happening. Thank you.

EDIT 18/10/22: Changed the description of the problem a bit so it's more clear.

**Comment by tellmewhyicefrog** [comment]
agreed, coward guy this icefrog

**Comment by davefojtik** [comment]
Closing this issue as stale. Seems like this repo is just spammed a lot and does not serve its purpose. One could recommend [Limiting interactions](https://docs.github.com/en/communities/moderating-comments-and-conversations/limiting-interactions-in-your-repository) but I guess nobody cares. Though I stopped playing the game, I wish the developers good luck.
