### ISSUE TITLE
Last word silenced by my own teammate silencer after lotus orb interaction

### ISSUE THREAD

**Issue by ligdota** [ValveSoftware/Dota2-Gameplay#3867]
**Ability name**
Last word

**Description**
I am playing morphling standing near my teammate silencer who presses last word, a single target ability (does not have aghs) onto an enemy hero that has a lotus orb activated on him. After doing so, I and the silencer are silenced with last word? and then I proceed to die. At first I thought it was the nagas orchid but no not that.

**Example Match ID (and possibly Timestamp)**
6809312857 - 30:32-30:49

**Comment by TheUnholyWrath** [comment]
Shadow Shaman had an aghs scepter, so the Lotus Orb reflected the AoE scepter version of Last Word. You can close this issue.
