### ISSUE TITLE
Earthshaker arcana not counting progress in Turbo games.

### ISSUE THREAD

**Issue by defStudios** [ValveSoftware/Dota2-Gameplay#3878]
### Cosmetic Item Name

Planetfall

### Description

Earthshaker arcana not counting progress in Turbo games.

I've played few turbo games (there were victories) but current progress just stuck at 8.

### Example Match ID

6810290518

### Screenshots

![Acf67NA](https://user-images.githubusercontent.com/27211442/196245741-dd59b28f-ce59-4f70-9ef5-631e4ec397f0.png)
![qihdiZa](https://user-images.githubusercontent.com/27211442/196245781-c91d2843-2eb1-4a88-9dd9-0d875c3b3a94.png)

**Comment by TheUnholyWrath** [comment]
#360
