### ISSUE TITLE
Dire safelane Tinker-ward-cliff allows warding an area much larger than others

### ISSUE THREAD

**Issue by anko** [ValveSoftware/Dota2-Gameplay#390]
### Description

The Dire safelane edge-of-map cliff ward spot has an eye symbol, but the area in which wards can be placed up there extends far beyond the eye symbol. In all 3 other edge-of-map cliff ward spots, wards can only be placed in the 2×2 area on top of the eye symbol.

This makes that specific Tinker-ward unusually difficult to deward without a vision spell, because the Sentry initial flying vision is too small to cover the whole area, and heroes can't stand up there.

### Example Match ID (and possibly Timestamp)

Easy to replicate in any lobby using the default Dota 2 map.

### Screenshots

https://user-images.githubusercontent.com/5231746/171858013-ff8bfc17-6c21-4dac-8476-c7fe98a57f0f.mp4

**Comment by anko** [comment]
Do the :-1: votes mean "This is low priority", or "I think this is an intended feature", or "Issue text contains mistake", or what?

**Comment by NMOTH** [comment]
> Do the 👎 votes mean "This is low priority", or "I think this is an intended feature", or "Issue text contains mistake", or what?

in this case here, this particular spot is intended. Although it would be nice if it wasn't.
using down emote helps prioritizing real issue once you sort them by votes. 
So if you see something that you know is not a bug or aren't enough details provided or is a troll post, feel free to down vote. Or comment on asking for details. It can be difficult for newer players to distinguish between intended mechanics and bugs.

**Comment by anko** [comment]
How do you know this is intended? All other Tinker-ward cliffs are 2×2 in size, which is the size of the eye symbol. All ordinary ward cliffs are also that size. That plus the unusual difficulty of dewarding this is what makes me think this outlier was accidental.

**Comment by NMOTH** [comment]
> How do you know this is intended? All other Tinker-ward cliffs are 2×2 in size, which is the size of the eye symbol. All ordinary ward cliffs are also that size. This is the only outlier, which makes it unusually and asymmetrically difficult to deward, hence why I figured it was accidental.

I am a support main, and there are many hidden warding spots that are hard to deward by enemies even if there is a sentry.  Hence the assumption this is intended as well.   I usually just fly my courier over and around this one when I dont have a hero with aoe vision spell.  It is intended game mechanic from my view.

**Comment by anko** [comment]
This was fixed in 7.33, through the map becoming larger, and the Tinker-ward-cliffs becoming ordinary 2×2 ward cliffs.
