### ISSUE TITLE
Unable to spectate games

### ISSUE THREAD

**Issue by AdamPuszka** [ValveSoftware/Dota2-Gameplay#3905]
### Description

Stuck on loading screen when trying to watch a game until i get timed out. Attaching console screenshot reporting successful connection and the following timeout.

### Screenshots

![image](https://user-images.githubusercontent.com/46558653/196851301-f23e85ef-3f0f-4fb7-be7f-ab777536c96d.png)

**Comment by TheUnholyWrath** [comment]
go read https://github.com/ValveSoftware/Dota2-Gameplay/issues/3692#issuecomment-1272324261
