### ISSUE TITLE
Five spells that are invisible if used from FoW

### ISSUE THREAD

**Issue by LokeLok** [ValveSoftware/Dota2-Gameplay#398]
### Ability name

A few

### Description

These five spells only appears if you have vision over the hero. You can hear the sound of the spells(except Hunter's Boomerang). Video below of all the spells

- Brew: Cinder Brew
- Hoodwink: Hunter's Boomerang(only ground targeted, works normally on heroes and units). Side note: The animation is not fluent when coming out of FoW, like other spells are. 
- Sniper: Concussive Grenade 
- Batrider: Flamebreak
- Zeus: Lightning Bolt

https://streamable.com/1x55t2

### Example Match ID (and possibly Timestamp)

Shown in demo

**Comment by LokeLok** [comment]
It is not working as intended. I've gone through all the spells and checked their behavior. These five are the only one with hidden animation, when casted from FoW. Any other spell that has a flying projectile of ground targeted effect is showing. Why  would you not be able to see spells flying towards you, if you have vision over that area? The spells i reported as bugged, are all avoidable(expect Lightning Bolt), by moving, blinking etc. 

When it comes to your CM ulti example. This is not true at all, as long as you have vision over some of the area it affects, you see the whole ulti. This is from jeffhill himself, from this thread: https://old.reddit.com/r/DotA2/comments/uywfxi/valve_please_overhaul_your_particle_system_and/
> The general rule of thumb is that "if you can see a spot where you would take damage if you stood there, you can see the spell." All of this comes together to create situations where you see a tiny corner of a Sandstorm in the Rosh pit or something, but because you're seeing the whole effect even though you only have FoW viz of the corner of the effect, it just looks weird.

**Comment by jeffercize** [comment]
Yeah fair enough I didn't realize that the way CM ult and such had been changed but I just tested and you are definitely right

**Comment by LokeLok** [comment]
No worries, I think we all need to be understanding on whats going on. So there is no confusion on how stuff should work. If I get something wrong when reporting bugs, I hope someone comes and enlighten me about it. Try to test you hypothesis and find a consistent way to reproduce it, to back it up.

**Comment by LokeLok** [comment]
All five spells fixed in the Dota 2 Update - 8/31/2022
