### ISSUE TITLE
#gift_error

### ISSUE THREAD

**Issue by yuimiyu** [ValveSoftware/Dota2-Gameplay#3987]
### Description

Hi. I have been having troubles with gifting. I get #gift_error since 17th October. There is no solutions of this error on any social media so I don't know how to fix it. I tried to delete steam and dota and then download it again, tried adding or deleting a gift's caption, tried cleaning steam's cache but nothing helped me. I contacted steam support but they only asked who I wanted to send the gifts to and then started ignoring me.
My steam friend id: 302849625
![1uyxvkdxsqad4h1wdj87](https://user-images.githubusercontent.com/116753266/198099581-2a667176-6bc1-42dc-a9f7-df17e42d4beb.jpg)

### Example Match ID (and possibly Timestamp)

-

**Comment by Kristiansibarani** [comment]
i have same issue, 
did your problem already solve or not @yuimiyu ?

**Comment by yuimiyu** [comment]
> i have same issue, did your problem already solve or not @yuimiyu ?

it solved itself after 10 days. sometimes it takes less time as i read from other users but i was pretty unlucky
