### ISSUE TITLE
Incorrect highlighting on trees for Hoodwink's Bushwhack.

### ISSUE THREAD

**Issue by Saggentemp** [ValveSoftware/Dota2-Gameplay#399]
### Ability name

Bushwhack

### Description

The targeting area indicator for Bushwhack is supposed to highlight trees in the area, but depending on the camera angle trees that are in the area might not get highlighted, or trees that are not in the area will be highlighted, sometimes only a couple of distance units outside the area.  The further "up" on the screen the more pronounced the issue is, my guess is that the trees have a vertical Z-axis "hitbox" that somehow intersects with a drawn line between the screen and the targeting area indicator.
Attached video is a brief illustration of the issue.

https://user-images.githubusercontent.com/106820662/171866176-6b2860a3-ec11-4e54-b21d-97f8ffe24f55.mp4

Example Match ID is just a random match, the attached video shows the issue clearly and I only assume it happened at least once during the match.

### Example Match ID (and possibly Timestamp)

6583609734

**Comment by Aphotic** [comment]
showcased on Reddit again in 2023:
https://old.reddit.com/r/DotA2/comments/17fy6f8/ever_wondered_why_you_missed_that_obviously/

related posts:
#7435 
#5656 
#3252

**Comment by eugene-valve** [comment]
Hi, this bug should be fixed in an upcoming update. Thanks for reporting this and taking a video especially!
