### ISSUE TITLE
Swag Bag 3 items Not Received

### ISSUE THREAD

**Issue by rodentskie** [ValveSoftware/Dota2-Gameplay#4060]
### Item name

Swag Bag Event

### 1st Gift

I got an `existing` Dota Plus Subscription, yet the date hasn't changed or add 30 days unto it.

### 2nd Gift

Current BP level is `314`, no addition `24` levels.

### 3rd Gift

I selected MK arcana, not received.

# User ID : 153027595

### Example Match ID and Timestamp

153027595

**Comment by pactwo** [comment]
i just got dota + , rest 2 prices i didnt, same thing

**Comment by rodentskie** [comment]
Will close this issue, received after playing one game. Thanks Valve.
