### ISSUE TITLE
Witchbane does not show damage in log

### ISSUE THREAD

**Issue by Krimatoria** [ValveSoftware/Dota2-Gameplay#407]
### Item name

Witchbane

### Description

Witchbane does not show the damage done in the log, in character test mode. I don't know if this is a bug. But there are other items for which damage is registered, there are only two of them:
1. Dragon Scale 
2. Fae Grenade
3. Cloak of Flames

![20220603172754_1](https://user-images.githubusercontent.com/106809386/171874291-3243374b-46f8-4bea-8f57-76c89e5e8c7e.jpg)
It is not clear exactly how much damage the item does along with other items in the assembly. Damage is considered a magic percentage, so it's hard to subtract it from the target's total damage.
- You can use a target and we will see the total damage with the item

![20220603171614_1](https://user-images.githubusercontent.com/106809386/171873416-bdea9767-c3cf-4048-b394-31e0dfbe3468.jpg)

Therefore, it is difficult to evaluate its effectiveness.

### Example Match ID and Timestamp

Can be checked in the test character mode

**Comment by somethingxful49** [comment]
Confirmed, able to reproduce

**Comment by TheZett** [comment]
This is because it deals attack damage, just like Javelin and MKB do.

Those do not appear as separate procs in the damage log, but they do apply their damage correctly.
