### ISSUE TITLE
i lost my item on marketplace steam

### ISSUE THREAD

**Issue by mxsssk** [ValveSoftware/Dota2-Gameplay#4077]
### Cosmetic Item Name

Arms of Desolation 

### Description

I put the lot on the marketplace with immortal Arms of Desolation and I decided to cancel the lot, the lot was canceled, but my item was never returned

### Example Match ID

657128312

### Screenshots

![image](https://user-images.githubusercontent.com/116762132/198128398-462b12fd-eb9d-4468-a510-52e8a2421d10.png)

**Comment by batrflyyy** [comment]
та же хуйня, пытался продать аркану, а она блять пропала

**Comment by blladwine** [comment]
у меня так же

**Comment by mxsssk** [comment]
пиздец, спасибо габен))

**Comment by sharinna** [comment]
а что делать парни

**Comment by mxsssk** [comment]
а вот хуй знает

**Comment by mxsssk** [comment]
я поэтому и написал

**Comment by sharinna** [comment]
а куда блять написать

**Comment by sharinna** [comment]
я не ебу просто

**Comment by mxsssk** [comment]
я вот сюда написал, я хуй знает куда ещё писать

**Comment by mxsssk** [comment]
сами валвы направили сюда

**Comment by mxsssk** [comment]
мол если проблемы с предметами - сюда

**Comment by AdityaYadav-123** [comment]
I am having a similar issue too
PFB screenshot attached:


![unknown](https://user-images.githubusercontent.com/116762673/198130257-61af4e2a-aa39-4e0c-ac81-37e0368e0aa5.png)

**Comment by sharinna** [comment]
блять я имею введу как выставить пост что у тебя проблема такая

**Comment by mxsssk** [comment]
ааа
понял
new essie зелёная кнопка

**Comment by blladwine** [comment]
> блять я имею введу как выставить пост что у тебя проблема такая

придется поебаться нормально

**Comment by sharinna** [comment]
понял, а как понять ответили ли? и ещё блять зачем айди матча вписывать?

**Comment by mxsssk** [comment]
айди матча не ебу, и как ответили тож не ебу 
первый раз сюда пишу

**Comment by sharinna** [comment]
а какие скрины нужны?

**Comment by sharinna** [comment]
блять а где взять скрин то что я выставил?

**Comment by sharinna** [comment]
бро

**Comment by sharinna** [comment]
ответь пожалуйста

**Comment by moroZOV24** [comment]
Такая же ситуация

**Comment by mxsssk** [comment]
на торговую площадку заходишь и в историю сделок
заходишь

**Comment by mxsssk** [comment]
чуруньк
скрин

**Comment by sharinna** [comment]
тебе ответили?

**Comment by mxsssk** [comment]
нет

**Comment by sharinna** [comment]
блять а как ты думаешь упадёт обратно айтем Crux of Perplex потому что хуй вернут я думаю

**Comment by mxsssk** [comment]
хз

**Comment by blladwine** [comment]
да хуй вернут, это же валв ебаные

**Comment by sharinna** [comment]
думаешь?

**Comment by sharinna** [comment]
я не собираюсь платить 700 рублей

**Comment by sharinna** [comment]
покупал за 200

**Comment by mxsssk** [comment]
я тоже не собираюсь заново покупать

**Comment by sharinna** [comment]
блять а что тогда на рубик абрать, прийдеться заукпать, тебе ответили? и как думаешь? когда оветят

**Comment by mxsssk** [comment]
бля, бро, зная валвов, если и ответят - то ну очень нескоро

**Comment by sharinna** [comment]
в смысле в небытьё?

**Comment by mxsssk** [comment]
ну, у меня ни в инвентаре ни на торговой площадке её теперь нет

**Comment by mxsssk** [comment]
фактически шмотка просто пропала

**Comment by sharinna** [comment]
блять, хоть бы вернули мне это прошу

**Comment by mxsssk** [comment]
бля, на твоём месте я бы уже не надеялся вернуть

**Comment by mxsssk** [comment]
валв - это не та компания, которая дорожит репутацией перед игроками

**Comment by mxsssk** [comment]
особенно в отношении доты

**Comment by batrflyyy** [comment]
вам то чё копейки, а у меня сука 3 аркагы ушло

**Comment by sharinna** [comment]
блять а что делать плокупать чтоли
 хоть бы упала в цене обратно пожалуйста, как ты думаешь економика завтра подтянеться? там за 200 рублей чтобы купить а не за 700 блять

**Comment by blladwine** [comment]
> вам то чё копейки, а у меня сука 3 аркагы ушло

у меня тоже аркана ушла

**Comment by mxsssk** [comment]
![image](https://user-images.githubusercontent.com/116762132/198150118-21b0dea0-3931-494e-ae66-1b35d1e39f91.png)

**Comment by mxsssk** [comment]
вернули

**Comment by blladwine** [comment]
мне тоже вернули
