### ISSUE TITLE
In-game report options are incomplete

### ISSUE THREAD

**Issue by ArmanJR** [ValveSoftware/Dota2-Gameplay#416]
### Description

Every time I try to report some booster/account buyer after a match, the matchmaking abuse report button fails and displays "failed to submit the report" in the console. The game itself is misery, at least fix this so we can report them.

EDIT: It turned out that if you report someone in the game you can not report them for another reason post-game. Please include account buying and boosting options in in-game reporting.

**Comment by NMOTH** [comment]
You cannot report post match if you have already reported during the match.
Please close this ticket.

**Comment by ArmanJR** [comment]
@NMOTH In-match reports are limited to suspicious movements and hacking, which are irrelevant to boosting and account buying. I will change the issue to this.

**Comment by NMOTH** [comment]
> @NMOTH In-match reports are limited to suspicious movements and hacking, which are irrelevant to boosting and account buying. I will change the issue to this.

please update the ticket title to reflect the new content of the issue
