### ISSUE TITLE
Swag bag temporarily closed

### ISSUE THREAD

**Issue by Gjelyawp** [ValveSoftware/Dota2-Gameplay#4190]
### Description

Message appears anytime when i click "Claim". Verifying Dota2 files didnt work, restart game didnt work, restart steam didnt work.

### Screenshots

![Screenshot_14](https://user-images.githubusercontent.com/84923442/198144824-4c26f31b-a448-4bab-ad5e-2ca274f2f06a.png)

**Comment by MaChKuLjA** [comment]
Same exact issue here!

**Comment by Gjelyawp** [comment]
![Screenshot_15](https://user-images.githubusercontent.com/84923442/198157005-9cfe1421-c37c-40c5-aa7f-12d2278a2071.png)
Claim arcana and battle pass ok.
Claim dota plus no ok.

**Comment by Bugork** [comment]
it's closed because people were getting TB or Techies arcana with prismatic gem, extracted gems and sold it
