### ISSUE TITLE
Cannot leave game

### ISSUE THREAD

**Issue by mastercoms** [ValveSoftware/Dota2-Gameplay#4197]
### Description

Terrorblade was shown as connected at the top hero bar, however chat kept counting down his DC until he got an abandon and the game became safe to leave and no stats recorded. Now we cannot leave, the Yes, leave game button is red and disabled after disconnecting (in the confirmation window).

### Example Match ID (and possibly Timestamp)

6824702254

**Comment by mastercoms** [comment]
Duplicate of #3910

**Comment by bezhdeyire** [comment]
same
![image](https://user-images.githubusercontent.com/90929097/198153110-4ceefd56-a492-4074-8d1e-e11fc430536d.png)
