### ISSUE TITLE
Random arcana

### ISSUE THREAD

**Issue by Exo8biT** [ValveSoftware/Dota2-Gameplay#4211]
### Item name

OGRE MAGI

### Description

When choosing the arcana, an error occurred, the arcana was automatically selected for the Ogre mage, please change the error and let me make the choice myself!

### Example Match ID and Timestamp

ID: 76561198114757697 1:05

**Comment by Exo8biT** [comment]
> ### Item name
> OGRE MAGI
> 
> ### Description
> When choosing the arcana, an error occurred, the arcana was automatically selected for the Ogre mage, please change the error and let me make the choice myself!
> 
> ### Example Match ID and Timestamp
> ID: 76561198114757697

**Comment by Kemar1s** [comment]
could you change ??

**Comment by papaback** [comment]
i got the same issue. please help
