### ISSUE TITLE
Баг с выбором арканы

### ISSUE THREAD

**Issue by Andrey43242341** [ValveSoftware/Dota2-Gameplay#4259]
### Description

Не было предоставлено выбора арканы, автоматом был орг-маг.

**Comment by BorisTurpanov** [comment]
решили проблему?

**Comment by nulotka** [comment]
нет

**Comment by nulotka** [comment]
они вообще молчат

**Comment by Georg4452** [comment]
Такая же проблема.

**Comment by foigjkdfjghfhgfjg** [comment]
у меня произошёл баг, и аркана далась без моего выбора автоматически, что делать?

**Comment by casstixx** [comment]
У меня тоже автоматов выпала аркана на огр мага,хотя я так хотел аркану на рубика(

**Comment by aomineeeeee** [comment]
ничего не поделать с этим, поддержка стим ответила мне, что они не могут поменять выданную аркану на другую
