### ISSUE TITLE
Free arcana bug

### ISSUE THREAD

**Issue by iandyone** [ValveSoftware/Dota2-Gameplay#4263]
### Description

Hi. I had a problem with selecting a free arcana item. The selection menu did not load and an error appeared on the screen. After restarting the game I was automatically given a arcana Ogre Mage arcane. I didn't select this item, I wanted to select the Shadow Fiend`s arcana (Demon Eater). I heard this is a regular problem. Please help me. 

https://steamcommunity.com/id/McSing173/

**Comment by keralbob** [comment]
Hi. I had a problem with selecting a free arcana item. The selection menu did not load and an error appeared on the screen. After restarting the game I was automatically given a arcana Pudge. I didn't select this item, I wanted to select the Rubik . I heard this is a regular problem. Please help me. sorry
