### ISSUE TITLE
Can't equip arcane item for Rubick

### ISSUE THREAD

**Issue by crossthefrog** [ValveSoftware/Dota2-Gameplay#4371]
### Description

I chose free arcane item for Rubick (the Magus Cypher), and i can see it in my inventory in Steam, BUT i don't see it in Dota 2 and i can't equip it in game on Rubick. Please help.

### Example Match ID (and possibly Timestamp)

null

### Screenshots

<img width="1270" alt="Снимок экрана 2022-10-28 в 10 57 21" src="https://user-images.githubusercontent.com/101556998/198484580-b3d593d1-e46e-4a0e-9bb1-079e3a47e66f.png">

**Comment by 22kolis22** [comment]
unpack the set in inventory

**Comment by crossthefrog** [comment]
yes thanks you @22kolis22
