### ISSUE TITLE
Linux: Game stuck at startup on Logo (Vulkan) 

### ISSUE THREAD

**Issue by SUBBSN** [ValveSoftware/Dota2-Gameplay#4427]
### Description

Game is stuck at startup on Logo when using Vulkan & Linux. I tried Arch Linux and Nobara 36. I have an i4xxx and a 1070Ti with latest nvidia drivers. Game worked flawlessly for some months now. This issue started approx. last week. I didnt change my system nor did a system update. After the game didnt start anymore I tried two reinstalls. Game is only working with OpenGL which has terrible performance.

**Comment by SUBBSN** [comment]
Wrong repo.

**Comment by tiritto** [comment]
Having the same issue. How did you solve it?

**Comment by SUBBSN** [comment]
I found the solution here: https://github.com/ValveSoftware/Dota-2/issues/2175

Use `-vulkan_disable_graphics_pipeline_library` as start parameter solved it.

**Comment by tiritto** [comment]
> Use `-vulkan_disable_graphics_pipeline_library` as start parameter solved it.

I've been looking for solution so many places and I've never even seen this launch option, it's undocumented even on the wiki. Thanks a lot for letting me know about that.
