### ISSUE TITLE
Firesnap Cookie with Aghanim's Shard on Rubick has no effect

### ISSUE THREAD

**Issue by NogrTL** [ValveSoftware/Dota2-Gameplay#4475]
### Ability name

Spell Steal, Firesnap Cookie

### Description

Firesnap Cookie stolen by Rubick with Shard has no Shard effect on Firesnap Cookie, regardless of Firespan has ult, or not

### Example Match ID (and possibly Timestamp)

Can be reproduced easly

**Comment by TheUnholyWrath** [comment]
This is mentioned in #561, you can close this.
