### ISSUE TITLE
Anti-Mage's Blink has inconsistent cast range with talent

### ISSUE THREAD

**Issue by real-vaLor** [ValveSoftware/Dota2-Gameplay#454]
### Ability name

Blink (Anti-Mage)

### Description

https://user-images.githubusercontent.com/106837775/171940460-fc839e7c-ff2c-4c26-86f0-08195c036cf5.mp4

After skilling increase blink range talent as antimage, Blink's cast behavior resembles Blink Dagger, with "overshooting" resulting in lower cast range than indicated by the ability. 

P.S.: How does one know when these bugs are fixed? 

### Example Match ID (and possibly Timestamp)

See attached video

**Comment by hardccd** [comment]
No its not a bug. its mechanic about using every blink skill included blink dagger.

it decrease the distance when you cast outside the ring

www.youtube.com/watch?v=VCf0yaRID_Y&ab_channel=KheZu

**Comment by real-vaLor** [comment]
> No its not a bug. its mechanic about using every blink skill included blink dagger.
> 
> it decrease the distance when you cast outside the ring
> 
> [www.youtube.com/watch?v=VCf0yaRID_Y&ab_channel=KheZu](http://www.youtube.com/watch?v=VCf0yaRID_Y&ab_channel=KheZu)

Im well aware of blink dagger's interaction, I mentioned it in the post. This is not supposed to apply to Anti-Mage's blink.

Antimage's blink (without cast range talent) has the same range regardless of overshooting, while antimage's cast range talent has inconsistent behavior (matching that of blink).

**Comment by smmarius** [comment]
To me it looks like after talent selection, it's behavior is the same as blink dagger usage. But yeah. probably bug

**Comment by yanevd** [comment]
Bug, for sure.

**Comment by NSurtsev** [comment]
Looks like the issue with AM's Blink with talent was solved as I tested.
Any other conformations?

**Comment by real-vaLor** [comment]
Tested today, appears to be fixed.
