### ISSUE TITLE
Dark Willow

### ISSUE THREAD

**Issue by mazzalina** [ValveSoftware/Dota2-Gameplay#4561]
### Ability name

Shadow Realm

### Description

The spell should make you untargetable to targeted spells however spells like decmember go through it whilst active

### Example Match ID (and possibly Timestamp)

6836250550

**Comment by TheUnholyWrath** [comment]
Dark Willow enters Shadow Realm 0.3s after you cast it (this change was made in 7.31). Pudge cast Dismember on you during those 0.3s. Please close this issue
