### ISSUE TITLE
Green Blood

### ISSUE THREAD

**Issue by She-zoed** [ValveSoftware/Dota2-Gameplay#4593]
### Description

I have got green blood (bloodseeker rupture, lifestealer ult, pa crit, sk finale caustic) enabled(i tryed launch game with perfectworld line in settings) and i don't how to disable it, i tryed in launch properties set -lv -lv=false command  and it doesn't works. I deleteted Game_LowViolence dota_lv line in gameinfo.gi and vac does not allow me to start a game, reinstall a game does not help, so what should i do? Please help.
UPD
I found solution, ingame console you need set value true to this commands
violence_ablood
violence_agibs
violence_hblood
violence_hgibs

![bug](https://user-images.githubusercontent.com/117261528/199430915-bbbe68ad-9057-4984-aa8c-b6bbaa6f53c1.jpg)

**Comment by She-zoed** [comment]
Bump

**Comment by She-zoed** [comment]
Please help!

**Comment by She-zoed** [comment]
Halp!!

**Comment by She-zoed** [comment]
Please help!

**Comment by She-zoed** [comment]
Please help!

**Comment by She-zoed** [comment]
Please help!

**Comment by She-zoed** [comment]
Please help!

**Comment by She-zoed** [comment]
Please help!

**Comment by She-zoed** [comment]
I found solution, ingame console you need set value true to this commands
violence_ablood
violence_agibs
violence_hblood
violence_hgibs

**Comment by Bedtimestory9** [comment]
Thank you this solved my issue. 
Commented for saved post.

**Comment by michaelan96** [comment]
This hasn't solved my issue. Any help?
