### ISSUE TITLE
Ancient Frostbitten Golem - Time Warp Aura buff tooltip

### ISSUE THREAD

**Issue by HenryBotX** [ValveSoftware/Dota2-Gameplay#4594]
### Hero and spell

Ancient Frostbitten Golem - Time Warp Aura

### Description

Please fix tooltip of buff from Ancient Frostbitten Golem's Time Warp Aura.

### Screenshots

![Screenshot 2022-11-02 162940 Time Warp Aura buff tooltip](https://user-images.githubusercontent.com/79627584/199438864-65c3d10a-c9e0-4e98-b03f-5ad9db37872f.png)

**Comment by vivi-lili** [comment]
Fixed in next build
