### ISSUE TITLE
morphling's talents is spelling wrong.

### ISSUE THREAD

**Issue by Neowise322** [ValveSoftware/Dota2-Gameplay#467]
### Hero and spell

Morphling - 10 and 25 talantes 

### Description

morphling at level 10 and 25 talents does not spell correctly

### Screenshots

![photo_2022-06-04_02-05-08](https://user-images.githubusercontent.com/106842555/171952762-90ed98b7-6b9b-45ca-a7e9-e5aa4b006e55.jpg)

**Comment by NMOTH** [comment]
This is duplicate of #92 please close

**Comment by shaileshgarg** [comment]
This has been fixed, can be closed.
