### ISSUE TITLE
Battle Pass 2022 - Candy Bag Bug

### ISSUE THREAD

**Issue by RogerCS17** [ValveSoftware/Dota2-Gameplay#4683]
### Description

Good evening. With the update today, there is an error with the bag of candy which is that the correct amount was not given. I drew 10 times the bag. 1 for recycling a treasure and 9 for the BP. But each time you draw a sack you should get 6, so it would be 10 x 6 = 60, however I only got 10 sacks. Please fix this bug. And also that we are rewarded for this kind of problems. Thank you.

### Screenshots

![Screenshot_1](https://user-images.githubusercontent.com/50506572/199858323-3ac9be45-bd77-44bf-8448-b6c9f1e4567f.png)

**Comment by mujigaegeomi** [comment]
me too, when filling the candy cells, I had 4 bags of 6 candies, and in the end only 4 cells were filled + after I melted the chest with immortals, and as a result I have 10 candies. sadness

**Comment by kanoalexis** [comment]
same for me. I didn´t get all my bags

**Comment by joyrede** [comment]
same problem.

**Comment by Hexzor** [comment]
i only  got treasures when i recycled and no candy sacks, i did this before diretide was released
