### ISSUE TITLE
Is it a bug or a new feature?

### ISSUE THREAD

**Issue by Joktun** [ValveSoftware/Dota2-Gameplay#4684]
### Description

So, the problem is that before the start of Part 2 of Compendium 2022, any exchange of treasures was 4 immortals/sets = 1 new chest + 1 candy bag. But for now its 4 immortals/sets = 1 new chest + 6 candy bag. Find myself a little dissapointed for losing like 20-30 candies (
Could it be somehow rewarded back? If it possible ofcourse. Thanks \[*-*\]

**Comment by sanketssc** [comment]
Agree I have probably recycled around 10 treasure that would have been easy 60 candies but I just got 10 candies for it
