### ISSUE TITLE
Gamebreaking Diretide Abuse

### ISSUE THREAD

**Issue by KnowYourDeadlane** [ValveSoftware/Dota2-Gameplay#4690]
### Description

Arc Warden can shield the wells with his Magnetic Field from Roshans attacks indefinitely.

After a short while, he stops attacking, the candy count of the well halfs and you can never add candy again. If the last well is the most near to Arcs fountain, he can shield from fountain.

As the last wells are close enough to shield them from fountain, this allows for Arc Wardens team to hide in their fountain as 5 and guaranteeing a win unless the enemy team manages to win a 5v5 within the fountain.

I'd say giving Roshan true strike solves the problem.

### Example Match ID (and possibly Timestamp)

6841584810

**Comment by nathank-valve** [comment]
This has been fixed. Closing.
