### ISSUE TITLE
Playing a Diretide game does not give half credit for the weekly quest

### ISSUE THREAD

**Issue by markcaldropoli** [ValveSoftware/Dota2-Gameplay#4696]
### Description

Playing a Diretide game does not give half credit for the weekly quest objective "For the love of the game" as it states it should in the tooltip. (The same may be true for the rest of the weekly quests except for "ancient predator")

"This quest can be completed in Diretide event games for half credit"

### Screenshots

![image](https://user-images.githubusercontent.com/22227236/199864367-e3a1e114-ca32-4c45-ad9b-b20f81948f01.png)

**Comment by Natalioquijada** [comment]
Same happen to me

**Comment by tesiawu** [comment]
Same - looks like there's a few Reddit threads about this as well: https://www.reddit.com/r/DotA2/comments/ylorzk/week_10_quests_not_working_in_diretide_mode/

**Comment by Bananik22** [comment]
This is still not fixed only quests that are working now are Candy Wandal and For Love of the Game.

Match ID: 6846065685
I shared 3 tangos, had a critical strike (crystalys) and hurricane pike and quests did not get counted.

**Comment by nathank-valve** [comment]
This has been fixed. Closing.
