### ISSUE TITLE
Cavern incorrect 250 bp and 125 dotaplus reward per small chest

### ISSUE THREAD

**Issue by commentator24** [ValveSoftware/Dota2-Gameplay#4707]
Hi i think you got the rewards mixed up?
it seems i received 125 BP points instead of 250 BP points (and 125 dotaplus shards)
and on my shards page i received 75 instead of 125.
is it because diretide is like turbo must do 2x?
![image](https://user-images.githubusercontent.com/109324155/199874723-724e218d-59ca-4159-af40-c06265da9f61.png)

**Comment by Gabesuweggg** [comment]
Same problem 
![image](https://user-images.githubusercontent.com/117413565/199881416-bf8c7fde-e4d7-47b0-9693-af373d838fca.png)
This is my steam ID: 902778547

**Comment by commentator24** [comment]
they fixed it, but only fix the tooltip 125 bp points and 75 shards...
