### ISSUE TITLE
Week 10 only records "Candy Vandal" in Diretide

### ISSUE THREAD

**Issue by DXChrisXD** [ValveSoftware/Dota2-Gameplay#4730]
### Description

In week 10 of the battle pass the others task aside of getting Taffy are not counting despite of the Information icon saying "This Quest can be completed in Diretide event games for half credit"

Quest of the week 10 not counting:
For love of the game
Truly Moving Experience
Two to Tango
Ancient Predator
Open Your Heart

### Screenshots

![20221103211131_1](https://user-images.githubusercontent.com/48728242/199897401-cbc68783-d520-4b39-84e4-d173caede16c.jpg)

**Comment by Dhondu69** [comment]
Same thing is happening with me Tango quest also didn't count even in turbo xD I shared like 100 tango with my teammates they ate them too still my count was 0.5 after that game

**Comment by markcaldropoli** [comment]
#4696

**Comment by Natalioquijada** [comment]
Match id 6854042452 isnt counting for me too the staff quest,

**Comment by nathank-valve** [comment]
This has been fixed. Closing.
