### ISSUE TITLE
FPS Limiter not working

### ISSUE THREAD

**Issue by MohsenEssa** [ValveSoftware/Dota2-Gameplay#4750]
### Description

FPS Limiter stopped working after diretide update

**Comment by xiaobaochan** [comment]
yeah, same problem too.Please fix it. FPS limit not working in DX11 mode.I use vulkan instead now.

**Comment by K4non82** [comment]
Yes me too, and game frame is rly unstable in game.. i go under 165 only in intense fight now at random he go down.. and i dont know why dota if i dont match FPS with my monitor HZ, 165, the camera start move choppy..

**Comment by CrazyMaxis** [comment]
Same problem, my PC is getting hot and I activated vertical sync
