### ISSUE TITLE
Can't see time options when watching replays

### ISSUE THREAD

**Issue by PowaHouse** [ValveSoftware/Dota2-Gameplay#478]
### Description

The options that let manipulate the game time without hotkeys just don't show up, and you have to restart the game to make them show. You can click every single option near where the options should be and it doesn't make them show.

### Screenshots

![20220603183444_1](https://user-images.githubusercontent.com/71946577/171958535-774429fa-8e12-424d-88d7-04828c8af3ce.jpg)

**Comment by PowaHouse** [comment]
After restarting the game it's back to normal.

![20220603184958_1](https://user-images.githubusercontent.com/71946577/171959014-163bb21e-904c-4100-9def-c0ecc750897b.jpg)

**Comment by NMOTH** [comment]
Hey can you verify integrity of your game files and see if this is still an issue?  Right click on game on steam library side bar and select properties under the files section there is button on verify integrity of game files. You have to do this while game is closed.

**Comment by PowaHouse** [comment]
I verified the files, it said everything was fine, I haven't had the issue since, if I have it again I'll send another comment on this post
