### ISSUE TITLE
THe item not returned into the inventory after cancel from market 

### ISSUE THREAD

**Issue by PoorguyDrifting** [ValveSoftware/Dota2-Gameplay#4812]
I lost 2 item ! disruptor immortal and a jugg sword , i canceled them but they didnt returned in my inventory / storage 

Friend id dota 2 : 252045173 please check the issue

**Comment by LiquiDog** [comment]
Hi! This happened to me too with a Terrorblade Arcana. Removed the listing and did not get the item back. Steam help options doesn't include this case within their options, and there is no "contact support" for that either.

Please help with possible next steps.
BR

**Comment by hystyle1** [comment]
Same happened to me. My "Avonance of the Veiled Ones" haven't returned to my inventory after I cancelled listing it.

**Comment by PoorguyDrifting** [comment]
my issue got hands done ty supports
