### ISSUE TITLE
Keeper of the Light's Recall no longer works

### ISSUE THREAD

**Issue by mothmaniac** [ValveSoftware/Dota2-Gameplay#4815]
### Ability name

Recall

### Description

Keeper of the Light's Recall doesn't work anymore, the particle effects do "teleport" to you but the targeted hero does not.

### Example Match ID (and possibly Timestamp)

6843121977 - 20:34

**Comment by lears123** [comment]
game ID: 6843942813

Same problem, with KOTL SHARD

**Comment by schneidero1** [comment]
tried every hero on our team, recall doesn't work, I want my 1400 gold back!

match id 6846614858

**Comment by Dota-Exp** [comment]
Fixed in upcoming update
