### ISSUE TITLE
Item went missing after I cancelled listing on market

### ISSUE THREAD

**Issue by hystyle1** [ValveSoftware/Dota2-Gameplay#4828]
### Description

The item "Avowance of the Veiled Ones" went missing after I cancelled the listing on market. Help please. Friend ID: 89156029

**Comment by exezick** [comment]
I experienced this too, My Codicil of the Veiled Ones that I listed in inscribe list is not showing in my inventory after I remove the item in steam market.

**Comment by denis-perevertov** [comment]
My Manifold Paradox Arcana is gone as well after I removed the item from steam market, although in my action history there appears to be no message about the item being delisted from the market.

**Comment by hystyle1** [comment]
It returned to my inventory.
