### ISSUE TITLE
Dota 2 client causes a GPU hang on Linux when running with Vulkan.

### ISSUE THREAD

**Issue by rommms07** [ValveSoftware/Dota2-Gameplay#4877]
### Description

I used to run Dota 2 via Vulkan, but after updating my NVIDIA proprietary driver (nvidia-lts), mesa and vulkan drivers my client stopped working when runned with Vulkan. I tried mitigating the problem by configuring and tweaking my system's kernel params but it didn't go as planned. I also suspected that it has something to do with my X11 (Xwayland) configuration but that also did not go well. :((

The game works fine when I run it via OpenGL (although a few glitches whenever I tick on Animated Portrait)

GPU: NVIDIA GTX 1050 Ti 
Kernel Version: Linux 5.15.76-1-lts x86_64 GNU/Linux
Vulkan Information: https://pastebin.com/dBWXu9jj

dmesg log:

[  146.718261] NVRM: Xid (PCI:0000:01:00): 69, pid=3424, name=dota2, Class Error: ChId 000c, Class 0000c197, Offset 00002380, Data 00000000, ErrorCode 00000004
[  947.285460] NVRM: Xid (PCI:0000:01:00): 69, pid=5971, name=dota2, Class Error: ChId 000c, Class 0000c197, Offset 00002380, Data 00000000, ErrorCode 00000004
[ 1051.186452] NVRM: Xid (PCI:0000:01:00): 69, pid=6732, name=dota2, Class Error: ChId 000c, Class 0000c197, Offset 00002380, Data 00000000, ErrorCode 00000004

**Comment by ds0nt** [comment]
Yep. They don't care.

**Comment by ds0nt** [comment]
Never have, or they would prevent this shit from happening. But the reality is that Dota2 has crashed for me on and off for 5 years regardless of hardware, or drivers.

**Comment by taurenrogue** [comment]
search feature

**Comment by rommms07** [comment]
#4851
