### ISSUE TITLE
Nvidia graphics card cannot set the maximum FPS

### ISSUE THREAD

**Issue by lsti98-proton** [ValveSoftware/Dota2-Gameplay#4878]
### Description

I have tried all my computers using NVIDIA graphics cards. After a recent update, I found that when they run dota2, they cannot set the maximum FPS in the video settings. Hope it can be repaired as soon as possible.

Thank you very much. Have a nice day.

**Comment by booshack** [comment]
Same - hope for fast fix

**Comment by MissPotato** [comment]
Can confirm as well, getting 100% cpu usage. https://i.imgur.com/QZJaZLA.png Doesn't seem to respect either slider.

**Comment by elicassion** [comment]
Same here :(

**Comment by Akz77** [comment]
same issue here. fps cap not working and gpu hitting 400-500 fps in game (which is hard to believe but GPU is being fully utilised)

**Comment by lsti98-proton** [comment]
already fixed
