### ISSUE TITLE
Magnus Horn Toss doesn't work!

### ISSUE THREAD

**Issue by Kilgrom** [ValveSoftware/Dota2-Gameplay#488]
### Ability name

Horn Toss

### Description

Horn Toss' ability description reads: "Enemies take damage, spend 0.6 seconds in the air, and then are heavily slowed upon landing." 

Despite this when an enemy is horn tossed they are only heavily slowed while in the air for 0.6 seconds. 

Upon landing the 100% Move/attack slow is removed.

Below is a slow motion video to show that upon landing axe reverts to his base movement speed:

https://user-images.githubusercontent.com/106846300/171962967-c2249366-aab6-48f3-93dd-23c2e5687958.mp4

### Example Match ID (and possibly Timestamp)

6600393618 54:35

**Comment by TheUnholyWrath** [comment]
This was fixed in 7.32

**Comment by Dota-Exp** [comment]
Issue should be fixed. Thank you.
