### ISSUE TITLE
Missing item after removing it from sale on the marketplace

### ISSUE THREAD

**Issue by NikitaZheleznov** [ValveSoftware/Dota2-Gameplay#4915]
### Description

I put the item "Shadow of the Dark Age" up for sale, then I wanted to remove the lot from the sale, after I removed it, it disappeared, it was written on the trading floor that it was sold, but I was not charged money for it.

### Screenshots

![Screenshot_1](https://user-images.githubusercontent.com/58141885/200121373-03d65fa1-47b2-4a45-bbc9-577b61a7827f.png)

**Comment by phanjysaID** [comment]
same with me.

**Comment by warpak12** [comment]
same with me also
![steam error](https://user-images.githubusercontent.com/117522279/200121612-f10e241a-c136-4c48-a7d0-82420bef4110.jpg)

**Comment by warpak12** [comment]
how can we report this?

**Comment by NikitaZheleznov** [comment]
I Don't know. Looks like it's a global problem.

**Comment by phanjysaID** [comment]
i dont know, how go to report.

**Comment by NikitaZheleznov** [comment]
If anyone knows how to report this issue, please post here.

**Comment by NikitaZheleznov** [comment]
I'm afraid this critical issue will go unnoticed...

**Comment by RickYDDT** [comment]
same, just lost item 
![image](https://user-images.githubusercontent.com/117525574/200124202-07ebe50e-bf46-4d5a-8781-e90913e050a4.png)

**Comment by RickYDDT** [comment]
got it, just little problems with servers as always
![image](https://user-images.githubusercontent.com/117525574/200125011-d7f9eef3-e02c-4736-ad89-49be40b93590.png)

**Comment by NikitaZheleznov** [comment]
same
