### ISSUE TITLE
Weekly Quests for Week 10 error 

### ISSUE THREAD

**Issue by njsjerome** [ValveSoftware/Dota2-Gameplay#4937]
### Description

Weekly Quest completion for Week 10 (at least that is the only one I am doing) does not work in Diretide even though it specifies "This Quest can be completed in Diretide event games for half credit". 

This includes: 
- TRULY MOVING EXPERIENCE 
- TWO TO TANGO 
- OPEN YOUR HEART

### Screenshots

![Screenshot (2)](https://user-images.githubusercontent.com/117528150/200126493-e41e21dd-70f1-48b3-9244-f82fe982d3cf.png)
![Screenshot (3)](https://user-images.githubusercontent.com/117528150/200126497-c926e325-660e-42a5-979c-f5722e11f4e7.png)

**Comment by Jarelk** [comment]
Same here.

**Comment by nathank-valve** [comment]
This has been fixed. Closing.
