### ISSUE TITLE
Steam friends tanking ingame performance

### ISSUE THREAD

**Issue by LokeLok** [ValveSoftware/Dota2-Gameplay#494]
### Description

Sometimes when playing, me and my friends experience huge fps drops. Restarting the game 
doesn't help. But if you close the steam friends window(steam dm's doesn't seem to relate), the fps comes back. Im 
wondering if any dota devs are aware of this issue? It's obviously an easy fix to the issue(just close the window), but i don't think so many people are aware of this. I've no idea how to reproduce this. The only thing i can think of causing this problem, is  with your friends going online/offline/in and out of games. With it somehow stacking up over time, causing huge performance loss in dota. I think it only happens to me, if I've had the friends window open for hours. If someone else has gotten the same bug, please share.

**Comment by LokeLok** [comment]
I can play the next few days with that setting of and see what happens. I can't guarantee fast feedback, since I don't really know what causes the problem.

**Comment by LokeLok** [comment]
Im very certain it is steam friends causing this. As I mention, the fps goes back to normal if I close that window. You can open it right away again and it's fine for a long time. It has happen to many of the people I play with. I asked them if they've steam friends open. The answer is yes and when i tell them to close it, everything is fine again. This is the only performance issue I encounter while playing dota and it all goes away when I exit the window.

**Comment by deliriam** [comment]
Post video evidence

**Comment by malicethegod** [comment]
yes i see this problem too

**Comment by LokeLok** [comment]
Closing since this seems to no longer be the case(not experienced this for a long time).
