### ISSUE TITLE
The game crashes in the mid of the match

### ISSUE THREAD

**Issue by CopKubar** [ValveSoftware/Dota2-Gameplay#5040]
### Description

The game crashes in the mid of the match, especially when a lot of affects from abilities are in use on the screen. The game just immediately exits without any error message or so. Is there a way to see crash report somewhere?
The error came with a new macOS update "Ventura 13.0".

PC:
MacBook Pro 2019
Processor: 2,6 GHz 6-Core Intel Core i7
Graphics: AMD Radeon Pro 5300M 4 GB / Intel UHD Graphics 630 1536 MB
Memory: 16 GB 2667 MHz DDR4
macOS: Ventura 13.0 (22A380)

**Comment by CopKubar** [comment]
I also use these configs for the game: -novid -high -gl

**Comment by nanuchas** [comment]
I have the same problem on my Macbook Pro 13" 2020 (intel) running Monterey 12.2.1. All these crashes began after November 3rd update of Battle Pass.

**Comment by RamiroFX** [comment]
> I have the same problem on my Macbook Pro 13" 2020 (intel) running Monterey 12.2.1. All these crashes began after November 3rd update of Battle Pass.

Same here, anynews?

**Comment by Kamyabs** [comment]
Its related to https://github.com/ValveSoftware/Dota2-Gameplay/issues/4851#issue-1436608105

**Comment by shadowdive10** [comment]
same here, with MacOS

**Comment by CopKubar** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/5065#issuecomment-1305641698 - this instruction has solved my problem, at least I have tested that in two dirtied games and no crashed has occurred
