### ISSUE TITLE
Diretide bug

### ISSUE THREAD

**Issue by LemonTeaEnjoyer** [ValveSoftware/Dota2-Gameplay#5122]
### Description

The player(nyx) was able to break the game by spamming the entire fountain with frogs.

### Example Match ID (and possibly Timestamp)

6849242646

### Screenshots

![bug](https://user-images.githubusercontent.com/117615104/200215372-05e154b7-46e6-4412-a1eb-6e06d9131e2e.png)

**Comment by nathank-valve** [comment]
This has been fixed. Closing.
