### ISSUE TITLE
Oracle's False Promise with Abaddon's Borrowed Time

### ISSUE THREAD

**Issue by Flati3** [ValveSoftware/Dota2-Gameplay#5254]
### Ability name

Borrowed Time

### Description

After the oracle's ultimate, Abaddon's health drops below the Borrowed Time trigger threshold. But Borrowed Time won't turn on
![Screenshot_3](https://user-images.githubusercontent.com/117827240/200827058-9aa6492b-f222-4a71-ba7d-81413c2a061f.png)

### Example Match ID (and possibly Timestamp)

for what

**Comment by Debeluk** [comment]
So after all, this is logical, the oracle's ultimate does not cause damage and does not heal, but changes the value of health. And Abaddon's no-damage ultimate won't activate without taking damage.

**Comment by Flati3** [comment]
but if i activate Borrowed Time by myself at the end of oracle's ulti all damage will be heal. And Dazzle's Shallow Grave also save from damage by False promise and in log written "Anti-mage deal Abaddon 2296 damage by False promise (2420 -> 124)". It's damage and heal

**Comment by Debeluk** [comment]
> but if i activate Borrowed Time by myself at the end of oracle's ulti all damage will be heal. And Dazzle's Shallow Grave also save from damage by False promise and in log written "Anti-mage deal Abaddon 2296 damage by False promise (2420 -> 124)". It's damage and heal

I understand what you mean, but the log records the damage in such a way that it would give the kill to the antimage in the event of the death of the abadon in the ult of the oracle, in reality this is not a bug, its HP status has simply changed.

**Comment by Flati3** [comment]
you are right

**Comment by pauldupont1** [comment]
if you were able to reproduce the issue in a specific match, providing the Match ID and Timestamp could help developers or support teams investigate the issue further.  [bluey](https://blueygame.com)

**Comment by thomas1803** [comment]
I've never felt so alive as when I'm dead staring at a loaded shotgun. This [Buckshot Roulette](https://buckshotroulette.com) game is a twisted paradox, a dance with mortality that's oddly exhilarating.
