### ISSUE TITLE
2020 Immortal treasure still has no sell button

### ISSUE THREAD

**Issue by No-44** [ValveSoftware/Dota2-Gameplay#5266]
### Description

My 2020 immortal treasure can't be sold, which I don't understand why, because there are existing listings for it and it's content in the community market. In my inventory, there is no sell button available, and its stated as not marketable. Why is this like this? And what makes other treasures different? Is there a different way to list this in the market? Please help.

Thank You

I've attached here some photos for reference.

D
![Proof 1](https://user-images.githubusercontent.com/117858804/200922591-fe4eeda4-97a2-4ae2-bb91-44d2b9d764b1.JPG)
![Proof 2](https://user-images.githubusercontent.com/117858804/200922596-a989c9c2-918d-49a3-829a-453112487bc1.JPG)
ate sent
10/11/2022

### Screenshots

![Proof 1](https://user-images.githubusercontent.com/117858804/200922637-3b63e339-30fe-4c02-91a7-efc721c233bf.JPG)
![Proof 2](https://user-images.githubusercontent.com/117858804/200922639-d2945974-8967-4ed8-bc52-6548a629b307.JPG)

**Comment by abadeergo** [comment]
i have the same problem. cant sell my immortal treasures yet :/

**Comment by No-44** [comment]
Treasures are now sellable. Thank you
