### ISSUE TITLE
Lucky shot does not trigger on Heartstopper aura

### ISSUE THREAD

**Issue by baudouinth** [ValveSoftware/Dota2-Gameplay#5294]
### Description

When drafting Pangolier's Lucky shot along with Necrophos' Heartstopper aura, Lucky shot does not trigger on aura damage instances.

However, the tooltip says it should trigger for any damage from an abilty.

### Example Match ID (and possibly Timestamp)

6855613552

**Comment by rickane58** [comment]
Heartstopper Aura isn't damage, it's HP removal. This is working as intended.
