### ISSUE TITLE
I JUST TOOK THINGS FROM INVENTORY

### ISSUE THREAD

**Issue by Zu4i11** [ValveSoftware/Dota2-Gameplay#5379]
### Description

I JUST EXCHANGE THE THINGS BY THEMSELVES, I DID NOT ACCEPT ANY EXCHANGE, I DID NOT RECEIVE ANY NOTIFICATIONS, NOTHING. JUST THINGS DISAPPEARED.

### Screenshots

![image](https://user-images.githubusercontent.com/118083343/201497884-041851bc-6235-4486-9b87-4590348237f5.png)

**Comment by Debeluk** [comment]
Стим гард стоит ?

**Comment by Zu4i11** [comment]
конечно

**Comment by Debeluk** [comment]
> конечно

и ты в это время никаких обменов не проводил, в магазинах ничего не покупал ?

**Comment by Zu4i11** [comment]
нет, я просто сидел в меню и увидел что у героев пропали шмотки, никаких уведомлений не приходило о попытке входа/обмене и т.д.

**Comment by Debeluk** [comment]
> нет, я просто сидел в меню и увидел что у героев пропали шмотки, никаких уведомлений не приходило о попытке входа/обмене и т.д.

ну тогда, во-первых ты не туда пишешь, заходи на сайт стим саппорт и выбирай там проблемы с инвентарём, пиши на английском обращение, так быстрее, во-вторых меняй пароль от стима, если честно то шансов на то что вещи тебе вернут критически мало, но хоть остальное всё обезопасишь

**Comment by Zu4i11** [comment]
Пароль от стима поменял уже, и от почты. Дело не в возврате в вещей, дорогих шмоток было очень мало, главное чтобы в будущем этого не случилось.

**Comment by Debeluk** [comment]
> Пароль от стима поменял уже, и от почты. Дело не в возврате в вещей, дорогих шмоток было очень мало, главное чтобы в будущем этого не случилось.

ну в стим саппорте как раз есть пункт о краже, там могут посмотреть с какого айпи производились обмены
