### ISSUE TITLE
Problems with emotes in dota2

### ISSUE THREAD

**Issue by SuperGeorge2002** [ValveSoftware/Dota2-Gameplay#5383]
### Item name

Ridicule : The Cat Dancer! , Call It What You Will , Float Where He Wanna , Advanced Bladework , Get the Blood Flowing , A Sproink in Your Step , Totem Roller , Sawed-off Watergun , Hot Eats , Soured Relationship , You Earned It ,  Some Light Horseplay , Curious Movements Indeed.

### Description

I can't sold this items after the international 11 in dota2
This also applies to another item on the hero Sven: "Vigil Odyssey"
![1](https://user-images.githubusercontent.com/118093370/201506405-0f11282a-41d1-49ec-afc3-19c55c6bb5b9.png)
![2](https://user-images.githubusercontent.com/118093370/201506410-55f9c154-50e5-4c59-afe2-267865772688.png)
![22](https://user-images.githubusercontent.com/118093370/201506413-7667611b-ac76-49cb-875b-daa50d35979e.png)
![11](https://user-images.githubusercontent.com/118093370/201506414-419cef86-a470-4dde-8e00-b6c5a82e2083.png)
![Нельзя продать](https://user-images.githubusercontent.com/118093370/201506417-f618a997-cc0c-4607-b74a-2abd261c6f8b.png)
![Нельзя продать 1](https://user-images.githubusercontent.com/118093370/201506419-8e56091a-bcb5-4946-b251-6ba01365f762.png)
![Нельзя продать 2](https://user-images.githubusercontent.com/118093370/201506420-eff65302-296b-425f-bde7-031975c6582e.png)
![Нельзя продать 3](https://user-images.githubusercontent.com/118093370/201506421-b88ff314-941b-4a9e-9b2c-74b0ea23a3c9.png)

### Example Match ID and Timestamp

https://steamcommunity.com/id/supergeorge2002

**Comment by shaileshgarg** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/5284
