### ISSUE TITLE
Bug in the catacombs

### ISSUE THREAD

**Issue by Xazarin** [ValveSoftware/Dota2-Gameplay#5388]
### Description

i went through the catacombs on the juggernaut, but they didn't give me a second style on it 

### Screenshots

![image](https://user-images.githubusercontent.com/118108385/201519157-addf83e2-5593-43d8-8c13-ce253194d1e4.png)
![image](https://user-images.githubusercontent.com/118108385/201519229-775306b6-7ccf-45c6-ada0-08f745c938e1.png)

**Comment by blakelmason** [comment]
Same thing happened to me. I have all 3 shards but the alternate style is still locked.
