### ISSUE TITLE
Experience Trophy didn't give the exact level for the account 

### ISSUE THREAD

**Issue by positive47** [ValveSoftware/Dota2-Gameplay#5420]
![20221114185931_1](https://user-images.githubusercontent.com/118184459/201662844-049b1d91-c148-464d-af22-577bf0f43621.jpg)

As the above photo when i reached 250 level in experience trophy , I should get 20+dota 2 account level but I only received 7 levels, Pls fix this bug,  Thank You,

**Comment by LokeLok** [comment]
This is working as intended. When the trophy is at level 100, you have 3100 points. For every level up you gain 10 points. At level 101 you will have 3110 etc, all the way up to 249 where you will have 4600 points. Which is 700 hundred away from 5300. Those 700 points is granted when you hit level 250 and 700 points = 7 levels. From level 100 to 250 you have gained a total of 2200 points which is the same as 22 levels.

**Comment by positive47** [comment]
> This is working as intended. When the trophy is at level 100, you have 3100 points. For every level up you gain 10 points. At level 101 you will have 3110 etc, all the way up to 249 where you will have 4600 points in total. Which is 700 hundred away from 5300. Those 700 points is granted when you hit level 250 and 700 points = 7 levels. From level 100 to 250 you have gained a total of 2200 points which is the same as 22 levels.

Thank you for explaining . I am misunderstood how the experienced trophy work.
