### ISSUE TITLE
Найти магазин с играми 

### ISSUE THREAD

**Issue by simeonovterver** [ValveSoftware/Dota2-Gameplay#5472]
### Ability name

Найти магазин с играми 

### Description

Всем привет! Кто знает, где сейчас можно купить новую FIFA. Я просто с другом хочу поиграть на xbox, а никак не могу купить ее? 

### Example Match ID (and possibly Timestamp)

6435345

**Comment by makarevich322** [comment]
Это место, чтобы багрепорты составлять, а не форум для общения. Какие еще магазины, как тебе пришла идея именно ТУТ разместить этот вопрос? Лол

**Comment by Harderov** [comment]
Я недавно нашёл очень крутой сайт на котором можно купить не только технику, но и игры на разные игровые приставки  https://www.moyo.ua/igra_fifa_23_xbox_series_x_russkaya_versiya_/521690.html   . Например, я уже себе прикупил пару крутых игры. Если вы тоже хотите купить FIFA 23 себе крутые игры или какую-то технику этот сайт точно вам подойдёт. Советую зайти и все глянуть. Там много крутого и полезного можно найти.

**Comment by simeonovterver** [comment]
Пока не пробовал этот сайт нужно будет больше про него информации найти.
