### ISSUE TITLE
Dot2 doesnt work with latest macOs update

### ISSUE THREAD

**Issue by JaniHuusko** [ValveSoftware/Dota2-Gameplay#5514]
Hey, I just installed latest macOs and when I try to open Dota 2 the icon on the bottom bar stays white and keeps popping upwards, but the game doesnt open at all.

The Version is macOS Ventura 13.0.1

**Comment by LegendreJ** [comment]
I'm hesitant to upload to macOS ventura because of this :(

**Comment by JaniHuusko** [comment]
Today the problem resolved itself after restarting mac, so I think its safe to download it.

**Comment by LegendreJ** [comment]
Was there any macos update or dota/steam update? Are there any performance issues with the game?
