### ISSUE TITLE
Weekly quest bonus chest

### ISSUE THREAD

**Issue by RedVampirium** [ValveSoftware/Dota2-Gameplay#5548]
### Item name

bonus chest

### Description

Hi i have tried to open 4 weekly quest bonus chest and they gave me just 1000 points each
i mean i kicked and a bug must have happen because i only got 1000 points 
please check my points log about this 4 chest
ps. the last weekly bonus chest is ok

### Example Match ID and Timestamp

570

**Comment by deathcola** [comment]
I have the same issue, but they can see your information here?

I also got 4 chest only got 1000 battle points, really furious...

**Comment by sirfatalx** [comment]
This happened to me as well.
