### ISSUE TITLE
My rerolls are not working, warlock still on the left

### ISSUE THREAD

**Issue by LadyUchiha** [ValveSoftware/Dota2-Gameplay#5565]
### Description

Hi, I have this warlock here already for a lot of rerolls, I don´t think, that this is right. I don´t need an arcana here, but something else should be nice. Can u please fix it? Thanks and have a nice day.  

### Example Match ID (and possibly Timestamp)

113642980

### Screenshots

![Candyworks1](https://user-images.githubusercontent.com/118691103/202924801-2ad6cf1c-62ac-4082-8b3e-346d3792922a.jpg)
![Candyworks2](https://user-images.githubusercontent.com/118691103/202924806-c8434a25-cc3b-4aa0-8e93-fc17c0649bc0.jpg)

**Comment by TheUnholyWrath** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/5384#issuecomment-1312651156
