### ISSUE TITLE
Diretide 2022 Collector's Cache not rewarding points properly

### ISSUE THREAD

**Issue by pythion** [ValveSoftware/Dota2-Gameplay#5601]
### Description

Purchasing the Cache suggests you can earn a total of 36 levels from

+ 2,500 | + 6,500 | + 27,000

However, the point log only added a total of 32 levels

+ 2,000 | + 6,000 | + 24,000

![image](https://user-images.githubusercontent.com/8550695/203449932-82751cab-20c4-4d4d-a4cd-5b8c359acac0.png)

![image](https://user-images.githubusercontent.com/8550695/203449917-56eaebe0-9532-49f6-bdac-dc1c15ef7a49.png)

**Comment by Plmjuhv** [comment]
![Incorrect points](https://user-images.githubusercontent.com/118867113/203457128-a30a94d2-53a5-4b40-bfff-9044525f460f.png)
I have also experienced the same issue

**Comment by BreadPiece** [comment]
yeah this is an issue that everyone has
![Dota 2 Screenshot 2022 11 22 - 19 43 45 84](https://user-images.githubusercontent.com/44326377/203465408-78c14153-494d-4538-9421-239cb67c06c3.png)

**Comment by pythion** [comment]
Issue appears to be fixed and missing points were rewarded
![image](https://user-images.githubusercontent.com/8550695/203471968-b52fa551-20b0-4a11-9c90-5a0852911378.png)
