### ISSUE TITLE
collector's 2022  baby invoker 

### ISSUE THREAD

**Issue by ccg13** [ValveSoftware/Dota2-Gameplay#5606]
### Description

I can't equip collector's set 
I have not received baby invoker 

### Screenshots
![Новый точечный рисунок](https://user-images.githubusercontent.com/118868720/203461131-3a0c7a1b-8632-47fc-bdfe-50e91319baa2.png)

**Comment by eddieparker** [comment]
This should be fixed now.  Let me know if not.
