### ISSUE TITLE
week candy fail or bug 

### ISSUE THREAD

**Issue by lonelynerd1** [ValveSoftware/Dota2-Gameplay#5652]
i was have 4 candy sacks from last week and this week start when i still have 4 sacks and now i have used them today but this week count the sacks i was have as a next week sacks so i will not gona win any this week cuz of this bug , here is this screenshot u can see that i have 4/4 but i and this week start like from 1 hr and i didn't get any i just played 1 turbo game

![Untitled](https://user-images.githubusercontent.com/119002334/203836990-e3dc4c67-ca79-4a6d-a2eb-a8c86158a9f9.png)

**Comment by glory61** [comment]
not bug, candies did refresh in another time. With 2k xp for games

**Comment by lonelynerd1** [comment]
> not bug, candies did refresh in another time. With 2k xp for games

thank you , yes it did refresh after the week with 6 hr
