### ISSUE TITLE
Rubick keeps buff stacks from spells and it's inconsitent

### ISSUE THREAD

**Issue by MissPotato** [ValveSoftware/Dota2-Gameplay#5706]
### Ability name

Spell steal

### Description

There are a few spells that give a buff when activated successfully.  From the behavior of Finger of Death being added a long time ago where the stacks vanish when it expires, I assume this isn't intended. 

Axe's Culling Blade - Rubick keeps the armor when he kills.
Necrophos's Reaper's Scythe - Keeps the 6 hp regen and 3 mana regen per stack.
Lion's Finger of Death - Gains stacks and their damage, vanishes when the spell is forgotten
Pudge's Flesh Heep -  Gains stacks and gains strength, but loses them on expire.
Wraith King's Vampuric Spirit - Gains skeleton charges, can summon them, loses charges when spell is lost.
Legion Commander's Duel - Gains duel damage as expected, doesn't lose it on expire.

I couldn't think of any other spells with permanent stat gain that was also stealable.

### Example Match ID (and possibly Timestamp)

6889633513

**Comment by TheUnholyWrath** [comment]
#561

**Comment by MissPotato** [comment]
> #561

You're right, my bad. I skimmed this one but must of missed it. Closing.
