### ISSUE TITLE
Tusk Old Aghanim´s Scepter "Frozen Sigil"

### ISSUE THREAD

**Issue by geewantsthefunk** [ValveSoftware/Dota2-Gameplay#5715]
### Ability name

Frozen Sigil

### Description

![tusk](https://user-images.githubusercontent.com/55582489/204346223-be994b2c-62a4-401e-b8ac-7e2f68d63590.png)

Hi together, frozen sigil still shown in hero view. this ability is not in the game anymore. 

thanks alot. 

### Example Match ID (and possibly Timestamp)

no matchid. it´s in the hero menu

**Comment by TheUnholyWrath** [comment]
#1064
