### ISSUE TITLE
Foo

### ISSUE THREAD

**Issue by azournas** [ValveSoftware/Dota2-Gameplay#5722]
### Ability name

Pulverize

### Description

It is not consistent but I had Pulverize being canceled on 2 targets under the effect of Soul Bind. At the same time, the secondary target was jerked towards Primal Beast with a somewhat glitchy movement.

### Example Match ID (and possibly Timestamp)

ex 6891267601 - 15:40

**Comment by TheUnholyWrath** [comment]
https://user-images.githubusercontent.com/46859977/204421090-228a6bc0-04aa-4774-a0c0-a9e0e4c06648.mp4

Headshot was cancelling Pulverize

**Comment by azournas** [comment]
Not sure if this is supposed to work that way, but that's good to know. Thank you
