### ISSUE TITLE
Razor level 15 Static Link talent double effect

### ISSUE THREAD

**Issue by duneblox** [ValveSoftware/Dota2-Gameplay#5753]
### Ability name

Static Link

### Description

The level 15 talent which should provide 5 extra attack damage steal with Static Link, provides 10 instead, allowing Razor to drain 80 more damage with the talent over the whole duration instead of 40 (at lvl 4 Static Link). Should either change the talent to say +10, change the tooltip to show damage drain in .5 second intervals, or correct the damage provided by reducing it by half. In any case, when picking the talent, the damage drain value in the tooltip is updated by +5, which is just factually incorrect, it should be +10 in its current state.

In the provided match, at 20:12 in game time, Razor uses Static Link on Primal Beast for about 6 seconds (6.2s by looking at the log), which provided him with 196 dmg, 196 divided by 6 is a little over 32, which confirms that the damage drain is not 27 per second as per the tooltip, but 32. All this happens after Razor has picked the +5 dmg lvl 15 talent of course.

### Example Match ID (and possibly Timestamp)

6889347079 @ 20:10

**Comment by commentator24** [comment]
i tested in lobby. it seems only level 2 is correct? perhaps drain rate is not the actual dmg or the last second not counted or something.

5 sec x 7 = not 35 but 34? with talent 5x12 not 60 but 84.
6 sec x 12 = 72 correct. with talent 6x17 not 102 but 132.
7 sec x 17 = not 119 but 117? with talent 7x22 not 154 but 186.
8 sec x 22 = not 176 but 174? with talent not 8x27= 216 but 254.

**Comment by Dota-Exp** [comment]
fixed in upcoming update
