### ISSUE TITLE
Slark's Depth Shroud is visible under Chrono

### ISSUE THREAD

**Issue by koiiphish** [ValveSoftware/Dota2-Gameplay#5754]
### Ability name

Depth Shroud

### Description

Slark's Depth Shroud (Shard) is states that slark and allies under the shroud would be hidden similarly to Shadow Dance. However, in the attached Game. Slark used Depth Shroud under Chrono and faceless void was still able to see slark and allies under the shroud. This was retested in demo mode and had similar results. If this is a feature it should be stated clearly in the spell detail as it technically does not work like Shadow Dance.

### Example Match ID (and possibly Timestamp)

6894963842 (45:30 in game time)

**Comment by TheUnholyWrath** [comment]
#1907
