### ISSUE TITLE
Templar Assassin Meld Bug

### ISSUE THREAD

**Issue by mdio49** [ValveSoftware/Dota2-Gameplay#579]
### Ability name

Meld

### Description

If Templar Assassin attacks a target, then melds and attacks another target (or the same target again) while the first projectile is still airborne, then if the first projectile hits the target before the meld projectile, then that projectile will apply the meld debuff to the target rather than the meld projectile, in which case the meld projectile behaves as a normal attack.

Although the [wiki](https://dota2.fandom.com/wiki/Templar_Assassin#Meld) details this behaviour of the spell, I do not believe that this is the intended behaviour as the meld projectile is visually distinct to TA's regular attacks. The same behaviour also applies for TA's level 25 bash talent, which in rare cases may cause the wrong target to become stunned if an attack projectile is already flying towards a different target. For these reasons, I feel like it would make more sense for the attack that comes out of meld to always be the attack that applies the debuff.

Below is a video demonstrating the bug; it was recorded a while ago using an older version of Dota 2, however the same behaviour is still present in the game today and this can easily be verified in demo mode.

https://user-images.githubusercontent.com/34671447/172030291-fb2483ac-63fb-4d02-821e-1d2c473a83cb.mp4

### Example Match ID (and possibly Timestamp)

N/A

**Comment by Dota-Exp** [comment]
Will be fixed in upcoming update. Thank you.
