### ISSUE TITLE
IMMORTAL TREASURE I(2022) RECYCLE BUG

### ISSUE THREAD

**Issue by SKORPJA** [ValveSoftware/Dota2-Gameplay#5805]
### Description

Greetings,

I have unlocked all Immortal treasure 1 skins except rare and beyond, But I recycled some of them.

Other than bristleback, templar assasin, centaur, hoodwink and battlepass 2022 emblem was shaded out (since i recyled all of them). But when i opened a new chest all of the previous skins from the chest become available again?.

I have already recycled rest of the not rare items. Now all of them are visible again.
There is an issue in my opinion.

**Comment by MasterOfUniverse82** [comment]
I had the same problem as you, the least rare should have come out, so BristleBack, instead they all reset and one that I already had came out. How sad! >_>

**Comment by TheUnholyWrath** [comment]
In the dropdown under "Each treasure contains 1 of these items": "Until it's purchased and opened, you won't know which one you'll receive. If you buy more than one, you won't receive duplicates until you own one of each non-rare item.
Also, if you're very lucky, in addition to the normal items you receive, you may also receive one of the rare bonus items."

Please close this issue.

**Comment by SKORPJA** [comment]
Thanks to battlepass and bonus missions, I opened 4 immortal treasure chests with progress. Then I recycle 4 items and got 1 immortal chest + 6 candies. The heroes I unlocked so far have turned gray (passive). When I opened the box that came with Recycle, Meepo's item was found. I had them all removed, down to the Bristle thing. I exchanged the candies in my hand for an immortal chest at the candy store. When I wanted to open the treasure again, all the items were active again as if I had never opened the box.

This has nothing to do with being lucky. There is an error and it needs to be fixed. There will be a box that we will have with the Recycle process, but the items will be active again? The Recycle system is completely unnecessary then?

**Comment by TheUnholyWrath** [comment]
Non-rare items are guaranteed every treasure you open, they grey out each time you open one so you can't get any duplicates. Once you have received all of them, they will become available again. The rare items work differently to the non-rare items. You're not guaranteed to receive them, but your odds of opening one increase for every treasure you have opened. The recycle system exists to allow you to recycle (duplicate) items to be able to open more treasures and have a better chance at opening a rare item. 

Please close this issue.
