### ISSUE TITLE
Elder Titan's level 25 1st talent is not working properly

### ISSUE THREAD

**Issue by TobbyMaBoi** [ValveSoftware/Dota2-Gameplay#5821]
### Ability name

Echo Stomp

### Description

after several times using Elder Titan i never realized that lvl 25 first talent i always use doesn't have effect on the game...

the talent simply said +450 echo stomp wake up damage, the enemies either waking up by my allies or even after the debuff is expired, none of the methods that causes the enemies awake gonna deal the damage.

and i also tried this in hero demo, and yeah, no damage is dealt after taking that talent.

### Example Match ID (and possibly Timestamp)

6901093617

**Comment by Firellius** [comment]
I think this talent is supposed to increase the amount of damage a sleeping target can take before they wake up, based on the fact the ability has a 'wake up damage threshold'.

**Comment by TobbyMaBoi** [comment]
then make it obvious, rename it accordingly, or whatever bcs others with similar ability clearly said "wake damage" as damage the unit took when they are put sleep and got woken up.... riki for example, where they put it clear that it's "wake damage" the damage the unit take after being put down to sleep...
