### ISSUE TITLE
OUTWORLD DESTROYER ASTRAL IMPRISONMENT PROBLEM WITH SCEPTER

### ISSUE THREAD

**Issue by AlveinTeng** [ValveSoftware/Dota2-Gameplay#5841]
When OD don't have SCEPTER AND Imprisonment on low-hp hero,  that hero can't BKB, but when OD has SCEPTER, that hero can BKB.

**Comment by AlveinTeng** [comment]
Steam id: 389858231

**Comment by amirullahizzan** [comment]
i dont think you have to include your steam id

**Comment by Dota-Exp** [comment]
Fixed in upcoming update, thank you.
