### ISSUE TITLE
Primal beast age of attrition set reveal hero pick before it should

### ISSUE THREAD

**Issue by commentator24** [ValveSoftware/Dota2-Gameplay#5903]
as shown. can see enemy pick primal beast
![image](https://user-images.githubusercontent.com/109324155/206875643-0e24af7b-4635-491b-bc74-46a781325461.png)

**Comment by commentator24** [comment]
![image](https://user-images.githubusercontent.com/109324155/206875762-58af65a6-5bae-481d-a6c0-170a8f0966e0.png)
to show the pick order. this is ranked

**Comment by TheZett** [comment]
If the same hero gets picked by both teams, it gets banned.
This can only happen two times in a row.

If this would happen 3 times in a row, the person who picked the hero first gets to keep it, instead of the hero being banned.

It has nothing to do with any item sets.

**Comment by commentator24** [comment]
is there a way to check if same bans happened? as far as i remember.. No same bans happened at all though...? would the replay show something like hero was chosen by both teams! or just Hero has been banned..? as you can see below, nothing showed that a hero was chosen by both teams! even after primal beast was picked.

matchID: 6911969714
https://user-images.githubusercontent.com/109324155/206880090-c05cf152-d77a-4d78-a9e7-a0ba172a47c0.mp4


![image](https://user-images.githubusercontent.com/109324155/206879891-53448655-2a0f-416b-be77-f01cb2bf109e.png)
![image](https://user-images.githubusercontent.com/109324155/206879896-fe1797ee-5dee-4898-96d2-5c408b89813e.png)
![image](https://user-images.githubusercontent.com/109324155/206879909-f67e7001-fd0d-4cae-8af6-0baa644eb0b0.png)

**Comment by TheUnholyWrath** [comment]
> as shown. can see enemy pick primal beast ![image](https://user-images.githubusercontent.com/109324155/206875643-0e24af7b-4635-491b-bc74-46a781325461.png)

if this image is a screenshot you cropped then I'm pretty sure you can uncrop it and see what was posted in chat. i can't see any other way of knowing, 16 heroes were banned though which would make the 3 ban thing more likely. if it was something attached to the skin theres no way it wouldn't have been replicated regularly

**Comment by commentator24** [comment]
well.. this is a normal ranked game without heroes chosen by both teams. its also 16..?

![image](https://user-images.githubusercontent.com/109324155/206895308-f4364a84-e6ed-469b-a1ba-8efdaa7bb6fc.png)

The mystery deepens...

**Comment by TheUnholyWrath** [comment]
Here's a reddit thread a dotabuff link of a game where this happened https://www.reddit.com/r/DotA2/comments/z0dvhp/why_wasnt_cm_banned/
https://www.dotabuff.com/matches/6876301668/chat

You can't see the replay because its 3 weeks old but it doesn't show in dotabuffs chat. If you can find a more recent one you can prove this definitively but theres almost certainly no mystery or anything interesting going on. PB just got picked by both teams and replays don't show when that happens.

**Comment by commentator24** [comment]
i really wished i streamed that time or didnt use snip tool.
as far as i remember, no 3 same bans happened. not even same bans happened at all. sure brown was highlighting the hero but he didnt pick that nor i remember anything on chat saying Primal beast was chosen by both teams. 
and earlier you said 16 makes it more likely but 16 is just normal bans. how do you explain that?
perhaps next time i get a game with 3 same bans i'll save the replay to see any difference in the total bans.

**Comment by commentator24** [comment]
> Here's a reddit thread and a dotabuff link of a game where this happened https://www.reddit.com/r/DotA2/comments/z0dvhp/why_wasnt_cm_banned/
https://www.dotabuff.com/matches/6876301668/chat

actually you just helped me prove that same bans didn't happened in my game.
i used https://www.dotabuff.com/matches/6911969714/chat as comparison.
 
 look at this. 16 bans compared to 18 bans in that cm game.
![image](https://user-images.githubusercontent.com/109324155/206910805-75babaa4-9ae0-402c-9086-3599b74814f5.png)

The mystery deepens...

**Comment by commentator24** [comment]
i also used #7158 as comparison here.  https://www.dotabuff.com/matches/7043981959/chat 
![image](https://user-images.githubusercontent.com/109324155/222924856-38ac3b99-ab95-44ea-adbc-9ea90384414b.png)
you can clearly see 18 bans here.

I learned that when 2 same bans happened, in replay the text will only say pudge and rubick was banned, instead of chosen by both team! Total bans are 18 instead of normally 16.

So now I noticed few things:
same bans didn't happen in my game. 16 bans instead of 18.
Invoker ban become the end of list for some reason. It was supposed to be first on the list.
There was Primal beast hero change update around that time. Maybe has nothing to do with set.
Still don't understand why I could see enemy primal beast pick. 

The mystery deepens..

**Comment by TheUnholyWrath** [comment]
https://imgur.com/a/qigSKLM

it really seems like you're reaching for something interesting here. this is by far the simplest answer

**Comment by commentator24** [comment]
how many times I need to say same bans did not occur in my game til you guys gets it 😁 
https://www.dotabuff.com/matches/6911969714/chat my game only had 16 bans like normal bans in any ranked games.
https://www.dotabuff.com/matches/7043981959/chat as comparison when 2 same bans occurred, total bans become 18.
https://www.dotabuff.com/matches/6876301668/chat as another comparison when 2 same bans occurred, total bans also 18.
yes I already know if 2 same bans occur, the next same hero chosen by both team won't be same ban, and the player gets it

now I very highly suspect it's something to do with invoker ban pushed to the end of list instead of first one on the list hence the game thought 15 same bans occurred? so it revealed the primal beast maybe

**Comment by TheUnholyWrath** [comment]
https://www.reddit.com/r/DotA2/comments/te5dow/please_fix_this_primal_beast_chosen_by_both_team/

how about this?

**Comment by TheUnholyWrath** [comment]
https://user-images.githubusercontent.com/46859977/222939350-6e023b19-5494-41f1-8dbd-376d0d08a630.mp4

mystery solved?

**Comment by commentator24** [comment]
while I do know newly released heroes can't be banned and first player to choose gets it, primal beast was released in February 2022 on 7.31 patch and my incident was December 2022 7.32d so it's been almost 10 months, 7 patches apart, and 7.31 becomes 7.32 already. but i guess you might be right. that could be it. if only I screenshot whole page of draft phase to show no same bans happened at all.. this wouldve been flawless mystery 👀 I keep telling you guys, same bans did not happen in my game.

In addition, when i watched your video the timer reset to 20 whenever same hero was chosen.
https://user-images.githubusercontent.com/109324155/206880090-c05cf152-d77a-4d78-a9e7-a0ba172a47c0.mp4 this primal beast was picked at 18 or 19 sec left, but the timer did not go back to 20. Your video shows you picked primal beast at 19 and it reset to 20. In my video, from :20 to :11 the timer still go smoothly because we dire did not pick primal beast and it never reset back to 20..

https://user-images.githubusercontent.com/109324155/222971348-18abf75f-bf5c-429b-9309-3bcfa2e42e11.mp4 as comparison for ID 7043981959 here you can see rubick was chosen by both team at around 10 seconds left and it reset to 20. 

if you still don't believe same bans did not occur in my game I don't know what to say 😁

**Comment by TheUnholyWrath** [comment]
https://imgur.com/a/wDW779Q
allies can't see the chat message that says "Primal Beast was picked by both teams". even if you had taken the screenshot correctly, it wouldn't have given any information.

for the first video, the picking animation starts at ~20s left. i'm not going to sift through replays to figure out exactly when in the picking animation heroes are actually picked, the start of it makes sense for me.

i'm not going to sit here and try to convince you, if you want to keep digging and testing every single cosmetic or hero ban combination or any other unrelated idea go nuts. i would love nothing more than to be wrong about this
