### ISSUE TITLE
Magnus' Aghanim's scepter bug

### ISSUE THREAD

**Issue by NiklasHallgrenCode** [ValveSoftware/Dota2-Gameplay#5914]
### Ability name

Shockwave

### Description

This problem will occur when having Aghanim's scepter and a Refresher's Orb.

1. Hit an enemy with Shockwave and the following erupt
2. Refresh
3. Use another Shockwave on an enemy before the effect of the first one has ended.
4. The enemy will not be damaged by the eruption

### Example Match ID (and possibly Timestamp)

Training mode

**Comment by TheUnholyWrath** [comment]
#1397

**Comment by Dota-Exp** [comment]
Currently working as intended
