### ISSUE TITLE
Bounty Hunter with new shard cannot go invisible while teleporting

### ISSUE THREAD

**Issue by MegamanEXE** [ValveSoftware/Dota2-Gameplay#5928]
### Ability name

Shadow Walk

### Description

Not a huge bug but an inconvenience as a long-time Bounty Hunter player. One of the little things us Bounty Hunters do is tp somewhere and go invis while it's channeling so when we arrive at the destination we're always invisible. This also saves us the fade time duration at low levels. This is obviously very important while escaping as well throughout all stages of the game.

But ever since the new shard which gives it 2 charges, you can no longer do that i.e. you can no longer go invisible while teleporting. And this really messes with muscle memory as well because we're used to trying to escape with invisibility.

**Current Behavior:** You cannot cast shadow walk while teleporting if you have the new shard which gives charges.

**Intended Behaviour** should be: You should be able to go invisible while teleporting regardless of if you have a shard or not. Additionally, you should be able to make your allies invisible as well **while** you're teleporting yourself.

I assume fixing one of these will automatically fix the other. The latter part is more of a feature request but it seems like the natural flow, no?

### Example Match ID (and possibly Timestamp)

None that I know but is easily tested in demo mode in 1 minute

**Comment by TheUnholyWrath** [comment]
#2563

**Comment by MegamanEXE** [comment]
I'm not sure if that's the same thing considering how that issue is worded, which is quite vague. I'm not really sure what they're talking about there. I tried making a CM who's using ult invisible, it's working fine. It doesn't mention anything about teleporting.

**Comment by Dota-Exp** [comment]
Will be fixed in upcoming update. Thank you.,
