### ISSUE TITLE
Techies with aghanim scepeter bug

### ISSUE THREAD

**Issue by Elemantreum** [ValveSoftware/Dota2-Gameplay#5946]
### Ability name

Reactive Tazer

### Description

Blow after Reactive Tazer with Aghanim doesn't dealing damage

### Example Match ID (and possibly Timestamp)

i found it in lobby

**Comment by shaileshgarg** [comment]
Tested in Demo

"Reactive Tazer can be cast on allies and deals damage on detonation. Also deals damage to any enemy that attacks the affected ally."

It does damage when attacked, but no damage when it detonates.

**Comment by TheZett** [comment]
It can only damage each enemy once per cast of Reactive Taser.

**Comment by LokeLok** [comment]
Just tested it, it does damage now on detonation. You can close this issue.
