### ISSUE TITLE
Wind Waker in flaming lasso Bug

### ISSUE THREAD

**Issue by Loraks010** [ValveSoftware/Dota2-Gameplay#5951]
### Item name

Wind Waker

### Description

wind waker not working on friend hero who was caught in Batrider's flaming lasso

### Example Match ID and Timestamp

6916599528 - 49:32

**Comment by TheZett** [comment]
This is intended.

Flaming Lasso overrides nearly every Forced Movement related ability, which includes Euls Scepter’s cyclone as well.
