### ISSUE TITLE
mkb not affected by mage slayer debuff

### ISSUE THREAD

**Issue by MohsenEssa** [ValveSoftware/Dota2-Gameplay#5963]
### Item name

mkb

### Description

dmg is less from mkb if target hero has mage slayer but isnt further reduced when attacking hero is debuffed by mage slayer

### Example Match ID and Timestamp

0

**Comment by cadaeic** [comment]
MKB pierce damage is considered attack damage, not spell damage. It can be reduced with e.g. Static Link, but Mage Slayer won't work. This is intended.

**Comment by cadaeic** [comment]
It's not amped by Kaya since it's not spell damage. Its damage on the target hero is dependent on magic resistance which is granted by Mage Slayer (25%).

**Comment by MohsenEssa** [comment]
ok i did test it and yes it is not amped by kaya as the tooltip is saying because when u hold alt while having kaya it shows that damage is increased while it actually isn't.
