### ISSUE TITLE
can't queue in low priority

### ISSUE THREAD

**Issue by IamElectric001** [ValveSoftware/Dota2-Gameplay#5965]
### Description

Can't queue single draft in low priority. The prompt says "Single Draft is the only game mode allowed in the low priority punishment pool" even when I've selected only single draft mode.

### Screenshots
![570_20221215155122_1](https://user-images.githubusercontent.com/120629933/207835034-5aa24348-8b70-44f4-ab56-703cd2231708.png)
![570_20221215155126_1](https://user-images.githubusercontent.com/120629933/207835097-985e2d02-522f-4548-9bd0-d0e4272c0855.png)

**Comment by TheUnholyWrath** [comment]
theres no point in creating this without putting up screenshots, its impossible to help you without seeing what you're doing wrong
