### ISSUE TITLE
 No effect on 2-3 styles of Bracers of Aeons

### ISSUE THREAD

**Issue by Wlsd12** [ValveSoftware/Dota2-Gameplay#5996]
### Cosmetic Item Name

Bracers of Aeons

### Description

I bought Bracers of Aeons from a style 3 item, with the first style, there are no problems, but if you choose style 2 or 3, then the immortal effect disappears!

### Example Match ID

1097293650

### Screenshots

![Dota 2 Screenshot 2022 11 18 - 20 45 54 71](https://user-images.githubusercontent.com/120754716/208194656-4cd81c94-0c4a-4928-87f5-6d3685eaa76e.png)
![Dota 2 Screenshot 2022 11 18 - 20 45 57 71](https://user-images.githubusercontent.com/120754716/208194672-ac8ab864-8b0f-422a-95bf-8b247e47d9d1.png)

**Comment by sadaharu25** [comment]
Style 2 and 3 was made for the arcana. it works if you have the void arcana
