### ISSUE TITLE
The Diretide 2022 Bundle Sale Dec 15 - Jan 12

### ISSUE THREAD

**Issue by haste0120** [ValveSoftware/Dota2-Gameplay#5998]
### Description

I currently only have money to buy one bundle on my account, but I can add funds to buy two bundles but I can't seem to click the PURCHASE TWO option because of a bug that saying I already purchased one. Here are the screen shot that shows my purchase history, you can see there that I didn't buy a bundle from Dec 15 - Jan 12. I also attach here my screen shot that shows I can't buy two bundles. Hope you can help me. Thank you.

### Screenshots

![image](https://user-images.githubusercontent.com/120758862/208203162-a9a552e4-9507-4a9b-9127-7ec4609c3b2d.png)
![image](https://user-images.githubusercontent.com/120758862/208203169-604534fb-206b-4f96-9d3f-1a75c7371335.png)

**Comment by TheUnholyWrath** [comment]
If you bought the first bundle back in October you can only buy 1 now. This isn't a bug and if thats the case you should close this issue
