### ISSUE TITLE
Diretide bundles rewards not appearing

### ISSUE THREAD

**Issue by runbyvaran** [ValveSoftware/Dota2-Gameplay#6020]
### Item name

Diretide bundle

### Description

my last 2 purchases of Diretide bundles have resulted in the money withdrawn from my account, but no rewards received in the game

### Example Match ID and Timestamp

14:46

**Comment by phx255** [comment]
Same here.

**Comment by phx255** [comment]
Go to armory->others->Unbundle.

**Comment by runbyvaran** [comment]
nice one, thanks
