### ISSUE TITLE
Templar Assasin Immortal Bug

### ISSUE THREAD

**Issue by ChatoyantL** [ValveSoftware/Dota2-Gameplay#6030]
### Cosmetic Item Name

Golden/Seclusion Of The Void & Mantle Of The Whispered Bond 

### Description

When i have the Seclusion Of The Void equipped with the Mantle Of The Whispered Bond the trap effects that the Seclusion of The Void is supposed to show does not appear, but anytime i unequip Manthe of The Whispered Bond the trap effects take place.
I dont think the items are in any way contradictory since one gives immortal effect to Templars Refraction the other gives it to the Psionic Traps

### Example Match ID

6923316578

### Screenshots

![image](https://user-images.githubusercontent.com/120823132/208256888-80e29c33-85f7-45b9-9d3b-425b804bd529.png)(This is with both immortals equipped)

![image](https://user-images.githubusercontent.com/120823132/208257012-0bb44abe-9a83-4b15-88bc-5454d3706e25.png)
(This is with only the Seclusion of the Void equipped)

**Comment by lj23onelove** [comment]
Have the same problem. Is there any solution or you have to choose between Refraction and Trap?

**Comment by ChatoyantL** [comment]
> Have the same problem. Is there any solution or you have to choose between Refraction and Trap?

I've figured out what causes this, Check if any of your equipped items have a rune on them, that is most likely what is interferring with the immortal effect.
