### ISSUE TITLE
Ember Spirit's Mentor of the High Plains weapons use default weapons particles

### ISSUE THREAD

**Issue by jlkj11** [ValveSoftware/Dota2-Gameplay#6038]
### Cosmetic Item Name

Spirit's Mentor of the High Plains weapons

### Description

The weapons use default particles which don't fit with the weapon's model.

### Example Match ID

none

### Screenshots

![image](https://user-images.githubusercontent.com/120787118/208302670-e54f4336-cd63-4f08-9c98-47091a7e8c5f.png)

**Comment by shaileshgarg** [comment]
In today's update the particle for this set were updated, they are now using the correct particles.
