### ISSUE TITLE
Rubick can steal Pudge's "Dismember" and cast it on an ally, but the "Eject" ability is "not learned"

### ISSUE THREAD

**Issue by Stuntminer202** [ValveSoftware/Dota2-Gameplay#6042]
### Ability name

Spell Steal

### Description

Match ID attached. Accidentally dismembered Razor, but was unable to eject him.

### Example Match ID (and possibly Timestamp)

6925140016 - 41:00

**Comment by Dota-Exp** [comment]
Will be fixed in upcoming update. Thank you.
