### ISSUE TITLE
Mars. Activated Bulwark does not forward projectiles.

### ISSUE THREAD

**Issue by sunofsparda** [ValveSoftware/Dota2-Gameplay#6043]
### Ability name

Bulwark

### Description

Mars. Activated Bulwark does not forward projectiles.

### Example Match ID (and possibly Timestamp)

6925162316

**Comment by sunofsparda** [comment]
![image](https://user-images.githubusercontent.com/10135454/208630825-988c04e9-26c5-4729-a169-d6e5a903417c.png)
![image](https://user-images.githubusercontent.com/10135454/208630852-58037776-a796-49d0-afe4-9f1c36a331db.png)
![image](https://user-images.githubusercontent.com/10135454/208630886-43e4f4f6-488b-4d30-be4a-21314178bbcd.png)
![image](https://user-images.githubusercontent.com/10135454/208630969-60695289-3843-4f6d-8d89-4ef7f1d596ba.png)

**Comment by Dota-Exp** [comment]
This behavior is intended.  Bullwark only blocks attacks when the intended target is behind Mars
