### ISSUE TITLE
Aghanims Death Ward hit is not bouncing

### ISSUE THREAD

**Issue by uncomplicated08** [ValveSoftware/Dota2-Gameplay#6071]
### Ability name

Death Ward

### Description

Witch Doctor casts death ward, hero has aghanims but the ultimate is only hitting one hero (spectre). only near the end of the cast, the ward starts to bounce to multiple heroes.
![20221221041606_1](https://user-images.githubusercontent.com/45179805/208777392-4d5c68be-78c9-4434-9a72-8d20dbecf95d.jpg)

![20221221042220_1](https://user-images.githubusercontent.com/45179805/208778253-3b7689b4-ffd6-4df3-8ea9-448166dad86e.jpg)

### Example Match ID (and possibly Timestamp)

6928426476 - 46:36

**Comment by Dota-Exp** [comment]
This will be fixed in the upcoming update. Thank you
