### ISSUE TITLE
Razor Arcana is missing English subtitles for it's new voice responses

### ISSUE THREAD

**Issue by VellyVice** [ValveSoftware/Dota2-Gameplay#6072]
Title. The new subtitles should be available in subtitles/subtitles_razor_english.dat file, but right now only default razor's subtitles are being presented in the file.

**Comment by shaileshgarg** [comment]
Subtitles are still not present for Razor Arcana

**Comment by VellyVice** [comment]
It was implemented recently, thanks devs.
