### ISSUE TITLE
Buying Aghanim's Shard on Shadow Demon levels Demonic Purge for free

### ISSUE THREAD

**Issue by UwU-epic-OwO** [ValveSoftware/Dota2-Gameplay#6088]
### Ability name

Demonic Purge

### Description

When buying aghanim's shard on shadow demon before leveling up demonic purge, demonic purge will also be leveled along with unlocking demonic cleanse, which allows the player to effectively have a free skill point. 

Here is a screen shot in demo mode showing a level 1 shadow demon with shadow poison, demonic cleanse, and demonic purge skilled:

![Screenshot (119)](https://user-images.githubusercontent.com/92698465/209013413-a6595db3-daa4-4b51-9a2e-d3f988d51bda.png)

Here is a screen shot in demo mode showing a level 15 shadow demon with maxed out normal abilites, 2 talents, and level 2 demonic purge (should only be possible at level 16):
![Screenshot (120)](https://user-images.githubusercontent.com/92698465/209013600-636d3bd5-2ef4-40a5-8d85-64e4c7eecd60.png)

### Example Match ID (and possibly Timestamp)

none

**Comment by Dota-Exp** [comment]
This will be fixed in an upcoming update. Thank you.
