### ISSUE TITLE
Player AFK for 10 minutes not being kicked

### ISSUE THREAD

**Issue by erickmiyazaki** [ValveSoftware/Dota2-Gameplay#6092]
### Description

Player was afk at minute 20 or so, he didn't move from base (Fountain) for like 10 minutes and did no get kicked?

### Example Match ID (and possibly Timestamp)

6930111656

**Comment by commentator24** [comment]
you get abandon for afk, not kicked

**Comment by erickmiyazaki** [comment]
Sorry, that’s what I meant.
If you download the replay you can watch the PA AFK from minute 20 and after 10 minutes he didn’t get abandon.

**Comment by commentator24** [comment]
![image](https://user-images.githubusercontent.com/109324155/209064981-ba43bfb4-a9d0-4a0a-a6fe-54846056f8a1.png)
you get this message after afk 5 min.

**Comment by commentator24** [comment]
and you cant see this message if you text mute the PA

**Comment by erickmiyazaki** [comment]
Ok, thanks

**Comment by commentator24** [comment]
dont forget to close issue~
