### ISSUE TITLE
Blink dagger not blinking to maximum range

### ISSUE THREAD

**Issue by PEDRAMJS** [ValveSoftware/Dota2-Gameplay#6099]
### Item name

Blink dagger

### Description

When using dagger to blink somewhere outside of blink daggers range, it will not blink the user to the maximum range of blink range

HOWEVER, when pointing exactly on the edge of blink daggers range, it DOES take you further than the previous case, which is a critical issue

### Example Match ID and Timestamp

In Demo

**Comment by shaileshgarg** [comment]
This is intended behavior. https://dota2.fandom.com/wiki/Blink_Dagger
