### ISSUE TITLE
Battle Pass bug: some stars dont count toward weekly quests progress

### ISSUE THREAD

**Issue by Macilvoy** [ValveSoftware/Dota2-Gameplay#6102]
### Description

After a Diretide game, I got only 1 star counted out of 4. Its been 2 hours into the new week's progression, and they are still not counted.

Edit: I saw some theories that a problem is with the taffy quest. But yesterday I completed it and got 1 more star counted, so I think its a problem with the whole progress system

### Screenshots

![dotabug](https://user-images.githubusercontent.com/62840389/209192026-349914d1-d162-426f-9845-bf234ef9d3f7.png)
![Screenshot 2022-12-23 174707](https://user-images.githubusercontent.com/62840389/209363567-7b6cb801-c54b-4a56-b8a2-a68eccfeb4bd.png)

**Comment by 1Luc1** [comment]
I do got the same problem.

**Comment by Macilvoy** [comment]
its fixed now (at least for me)
