### ISSUE TITLE
Cannot toggle Phantom Rush while ability on cooldown

### ISSUE THREAD

**Issue by Digit4** [ValveSoftware/Dota2-Gameplay#611]
### Ability name

Phantom Rush

### Description

Phantom Lancer's Phantom Rush, being a toggle ability, cannot be enabled/disabled while it is on cooldown, while a similar ability(Leshrac's Pulse nova can be toggled off even though the ability has a 1 second cooldown). Similar behaviour is also present in Bloodseeker's Aghanim's upgrade, Blood mist, but it explicitly states cannot be toggled off while on cooldown. No such descriptions exist for Phantom Rush.

### Example Match ID (and possibly Timestamp)

generic behaviour on ability

**Comment by dommeyer** [comment]
I want this to be changed for years. Thank you so much for opening this issue.

**Comment by TheZett** [comment]
This is caused by the ability being a Toggle spell and toggle spells cannot be switched while on cooldown (Rubick’s old Nullfield had the same behaviour).

Had they made the spell an Active Attack Modifier (aka. "auto-cast") spell instead, then you could toggle it on/off while on cooldown.

**Comment by Daar543** [comment]
The Toggle behavior should be also switched for the sake of consistency - toggle off would disable it, while the illusions would spawn with toggle on (also upon learning the skill).

**Comment by haqle314** [comment]
Jinada and Geminate Attack were already changed into an Active Attack Modifier in 7.30. Phantom Rush should also be changed into an Active Attack Modifier for both consistency and QoL.

**Comment by jeffhill** [comment]
This should be fixed in the next update. Phantom Rush now activates when the ability is toggled **on**, which it now is when first levelled up. It's always possible to toggle an ability off even when it's on cooldown so you can now turn off Phantom Rush while it's on cooldown. You must still wait for it to come off cooldown to toggle it on again, just like any other toggle ability.

Thank you for the bug report!

**Comment by Digit4** [comment]
Thank you for fixing this issue, I'll close this one now.
