### ISSUE TITLE
Arc Warden multiple copies from Tempest Double (game breaking)

### ISSUE THREAD

**Issue by Avarise831** [ValveSoftware/Dota2-Gameplay#6124]
### Ability name

Tempest Double

### Description

Arc Warden spawned 2 clones instead of one
Match id: 7304800595

**Comment by shaileshgarg** [comment]
![20221223133014_1](https://user-images.githubusercontent.com/26450759/209296894-9164e154-26e0-4eda-9e0c-a2a81995cfd1.jpg)

**Comment by sBLOCKER85** [comment]
Thats sick!

**Comment by Avarise831** [comment]
https://www.reddit.com/r/DotA2/comments/119uh0b/its_possible_to_create_multiple_copies_of_arc/
found this today explains a lot
