### ISSUE TITLE
Collector Cache 2 sets which were unboxed BEFORE you made them giftable again are not giftable at all

### ISSUE THREAD

**Issue by L3yne** [ValveSoftware/Dota2-Gameplay#6125]
### Description

6 hours before I have unboxed 15+ Collector Cache 2 sets. None of those are giftable. Unboxed 1 more 5 mins ago - already giftable. Make the early-unboxed Collector Cache 2 sets giftable aswell, please.

### Screenshots

![image](https://user-images.githubusercontent.com/110830660/209277831-a41d6ec8-5e5c-4248-9967-0c2d35f90d27.png)
Early-unboxed Set

![image](https://user-images.githubusercontent.com/110830660/209277897-a9fd10af-e0b7-4456-b999-fbdcdd87f13a.png)
Unboxed 5 mins ago

**Comment by kwnkwn2g** [comment]
i have the same problem, please FIX!!!

**Comment by arjayrj** [comment]
have the same issue.

**Comment by wist1337** [comment]
+1

**Comment by Mingur1** [comment]
still no update regarding this?

**Comment by bouncydragon** [comment]
still no update regarding this matter?

**Comment by Rovin13** [comment]
Still no update damn volvo i open 52 treasure now i have bunch of dupli that i cant gift to my friends lmao what do they want us to do in this shxt? recycle for 2 levels? damn not even worth it! im already 1k+ levels! VOLVO!

**Comment by kolobosio** [comment]
Same, 1000+ lvls and +2 is useless
Want to gift them to my friends

**Comment by Samicoron** [comment]
still no update????

**Comment by kolobosio** [comment]
No updates?????????
Almost whole week…

**Comment by WasabiCringe** [comment]
Я обращаюсь к Валве, Я в 2015 году купил несколько Collector's Cache, не могу дарить открытые сеты. И теперь такая же ситуация в 2022. Проверьте мой профиль !!! Исправьте вещи Collector's Cache 2015 в моем инвентаре. Я их сам открыл, их можно дарить но у меня отсутствует функция "завернуть в подарок"

ENG

I turn to Valve, I bought several Collector's Cache in 2015, I can't give open sets. And now the same situation in 2022. Check my profile!!! Fix the Collector's Cache 2015 items in my inventory. I opened them myself, they can be given, but I do not have the "wrap as a gift" function

![image](https://user-images.githubusercontent.com/121585919/209884976-9c987e79-7e59-43f6-b875-3ad2d25860c1.png)

**Comment by Mc3019** [comment]
me too

**Comment by andresm666** [comment]
The support told me that Valve has more important things to work. Before to fix the bug, so it won't be known if they think about fixing it or not.

**Comment by Visage982** [comment]
this needs to be fixed seriously I opened hundreds of treasures and they are not giftable !!!
all cc sets are liftable including diretide 2022 collector cache 2
this means that they should be giftable 100%

**Comment by bouncydragon** [comment]
it seems that there are other issues before that are not fixed, this is sad if Valve has no intention of fixing it.

**Comment by goodgallili** [comment]
Good day. On 23/12/2022 I bought 20 collector's cache -2 treasures in Dota 2. I bought them right after the treasure chest came out for sale. And they have the following error: they cannot be gifted to anyone as it should be. After some time the game client was updated and the bug was fixed for the new purchaises but my items were still bugged (cant be gifted). Today I bought another treasury to make sure that bug was fixed, and I confirm that the new item i got was already normal with activated gift function as it should be and the items I got before are still bugged. I ask you to fix the things that I menthion and add the possibility to gift them, or return the money since they do not have the functionality that I paid for.

**Comment by kwnkwn2g** [comment]
I have a huge number of friends with the same problem, as many bloggers have faced the same problem.
Please Valve Fix !!!

**Comment by Ferrocianuro** [comment]
1 week. Please Valve Fix !!!

**Comment by G1psyRa1nDanger** [comment]
still no update? it's already new year

**Comment by TheBest0555** [comment]
I bought sets, and I can’t give them to absolutely anyone. Straight from the chest. Fix it please. My profile https://steamcommunity.com/id/totkrasava/

**Comment by KarinKuba** [comment]
1 week. Please Valve Fix !!!

**Comment by kwnkwn2g** [comment]
Valve FIX!

**Comment by 11JP11** [comment]
Tengo el mismo problema, compre 152 cofres de Collector´s Cache 2 y no me permite regalar, por favor, Valve dueño de Dota 2 solución pronta, tengo mucho dinero invertido, me perjudica económicamente y psicológicamente.

**Comment by 11JP11** [comment]
Los cofres Collector's Cache 2 normalmente se puede regalar sellado y no abierto, pero en esta situación del problema que esta no permite regalar cerrado y abierto, solucione este error por favor.

**Comment by ahmadfar1d** [comment]
for me, the regular set can gift. valve already fix it. But got problem with rare set Treant Protector. This set still cant gift. Hopefully, valve can fix it ASAP.
 ![Screenshot_1](https://user-images.githubusercontent.com/121312247/210469016-19f9b5fd-9def-4880-95ba-5a67c2df0fde.png)

**Comment by G1psyRa1nDanger** [comment]
> for me, the regular set can gift. valve already fix it. But got problem with rare set Treant Protector. This set still cant gift. Hopefully, valve can fix it ASAP. ![Screenshot_1](https://user-images.githubusercontent.com/121312247/210469016-19f9b5fd-9def-4880-95ba-5a67c2df0fde.png)

yes for normal set valve already fixed it I just saw it but for rares like AM, VOID SPIRIT and TREANT still not fixed and still not giftable

**Comment by kwnkwn2g** [comment]
Normal sets fixed, but sets on AM, Void Spirit, Treant - dont fix.

**Comment by bouncydragon** [comment]
Same problem for AM, VOID and TREANT. All normal cache are giftable already. :)

**Comment by 11JP11** [comment]
Solo falta que arreglen los set raros y muy raros.

**Comment by soccerlove3** [comment]
The following sets are still ungiftable. BUG:
Rare Bundles
Anti Mage: Brands of the Reaper
Treant Protector: Grudges of the Gallows Tree
Very Rare Bundle
Void Spirit: Sublime Equilibrium

**Comment by josephjoshua30** [comment]
Valve pls fix it's been 3 weeks only.. why you need to leave out the rares?

**Comment by TheBest0555** [comment]
PLS VIX! DONT GIFTING - AM, TRENT AND VOID SPIRIT! MY PROFILE https://steamcommunity.com/id/totkrasava/

**Comment by TheBest0555** [comment]
> PLS FIX! DONT GIFTING - AM, TRENT AND VOID SPIRIT! MY PROFILE https://steamcommunity.com/id/totkrasava/

**Comment by chanchan4514012** [comment]
pls fix antimage, treant, void spirit cache sets cant b gifted !! my id steam https://steamcommunity.com/profiles/76561198280938617

**Comment by kwnkwn2g** [comment]
Normal sets fixed, but sets on AM, Void Spirit, Treant - dont fix.

**Comment by TheBest0555** [comment]
Pls FIX! Inlocked sets for collector cache 2 dont gift!(for all), and dont sealed sets on void spirit, am and trent dont gift! FIX! my profile https://steamcommunity.com/id/totkrasava/

**Comment by G1psyRa1nDanger** [comment]
still no fix for AM, Void and Treant in Collector's Cache 2

**Comment by TheBest0555** [comment]
Pls, fix!
My profile: https://steamcommunity.com/id/totkrasava/
Open sets (separate clothes), from the second chest - are not given.
Also not given are Trent, Am and Void Spirit, sealed and unpacked.
![image](https://user-images.githubusercontent.com/121733500/214291530-50245f
![image](https://user-images.githubusercontent.com/121733500/214291762-49838c4b-2f4d-4b93-a0cf-7449b097976f.png)
![image](https://user-images.githubusercontent.com/121733500/214291801-a583d5d9-c566-4fcd-952c-7877378a7f42.png)
And an example of printed sets:
![image](https://user-images.githubusercontent.com/121733500/214292017-10d3faa7-d328-43f8-91b4-db8e33536f24.png)
![image](https://user-images.githubusercontent.com/121733500/214292088-07cd653d-9d89-4895-be96-baf16410306b.png)
![image](https://user-images.githubusercontent.com/121733500/214292279-490dd6ea-e30b-478f-9b13-4306827d7596.png)
I've been waiting for over a month!

**Comment by eddieparker** [comment]
Can someone verify for me if this is fixed?  If not and you feel comfortable doing so, please link me your steam account so I can look into it.

**Comment by shaileshgarg** [comment]
Adding issues related to the above from @Aluerie 

* https://github.com/ValveSoftware/Dota2-Gameplay/issues/5284
* https://github.com/ValveSoftware/Dota2-Gameplay/issues/6720
* https://github.com/ValveSoftware/Dota2-Gameplay/issues/6546

**Comment by eddieparker** [comment]
> @eddieparker 0. Looks like it is fixed for all people I could check on, thanks a lot => CC2 sets from the first day batch are now giftable - both rare and non-rare sets.
> 
> And on a tangential note could I ask you about all other trade related issues. It would be nice if these were addressed because people spamming duplicate issues about it on daily basis to the point of complete disorder and chaos, which hurts the repo a lot. So here is the list:
> 
> 1. [FIXED] The following items from BattlePass 2020 are still _not_ tradable/marketable. There are ways to bypass it and put items on the market but without any tricks - items are not tradable.
>    
>    * [x]  Trust of Benefactor 2020
>    * [x]   Warden of the Hellborn (Warlock item from Immortal treasure I)
>    * [x]  All Taunts, namely:
>      
>      * [x]  Taunt: Curious Movements Indeed (VoidSpirit)
>      * [x]  Taunt: Some Light Horseplay (KotL)
>      * [x]  Taunt: You Earned It (TA)
>      * [x]  Taunt: Soured Relationship (Bane)
>      * [x]  Taunt: Hot Eats (Ember)
>      * [x]  Taunt: Sawed-off Watergun (Morph)
>      * [x]  Taunt: Totem Roller (Shaker)
>      * [x]  Taunt: A Sproink in Your Step (Ench)
>      * [x]  Taunt: Get the Blood Flowing (Mars)
>      * [x]  Taunt: Advanced Bladework (Tinker)
>      * [x]  Taunt: Float Where He Wanna (Snapfire)
>      * [x]  Taunt: Call It What You Will (Ogre Magi)
>      * [x]  Taunt: The Cat Dancer! (Luna)
> 2. [UPDATE: Full set is tradable/marketable BUT individual pieces are still NOT] Disruptor Rare Set (Upland Pride) from Aghanim's 2021 Continuum Collection treasure is not tradable/marketable - while it should be. Seems like, it's marked as Collector Cache set which it's not.
> 3. Latest Diretide Collector Cache 2 sets are not giftable after unbundling
>    
>    * while CC1 sets are _giftable_ after unbundling, piece by piece
>    * people want them to be giftable for consistency because people unbundled it expecting sets be still giftable like those in CC1 (a bit jebaited/false hope/sadness - people wouldn't have unbundled them otherwise, why there are suddenly different "laws" for CC1 and CC2).
> 4. QoP Ultra rare Dress (Bloodfeather Finery) items from Immortal Treasure II are not giftable _after_ unbundling
>    
>    * while its analogy Hoodwink Ultra rare (The strings of Suradan) items from Immortal I are giftable after unbundling, piece by piece
>    * Again, people also want it to be giftable for the same consistency/sadness as above^
> 
> Image showcasing differences that points 3. and 4. mention: ![image](https://user-images.githubusercontent.com/33165440/214977501-219232f2-12c1-441f-a211-e52fc60a043c.png)

@Aluerie - can you confirm that 3 & 4 are fixed?  I think #2 is not still, but feel free to confirm for me if you have the time.

If any are still not fixed, if you shoot me their item IDs I can try to figure out what's missing.  Thanks for your patience.

**Comment by Aluerie** [comment]
2. Upland Pride set: individual pieces are not tradable if the set was unbundled before the fix. Other situations: bundled set/unbundled after the fix pieces look fine. 
3. Looks fine 
4. Not fixed, QoP dress individual pieces (Bloodfeather Frock, Bloodfeather Boots, Taunt: Dancing Queen) are still not giftable once.

**Comment by ahmadfar1d** [comment]
hope valve fix this issue too. Thanks [Screenshot_2](https://user-images.githubusercontent.com/121312247/217294400-6e65e58c-ca5f-4bc1-a600-09c26505dc3e.png)
![Screenshot_1](https://user-images.githubusercontent.com/121312247/217294435-0bba1c8d-21c6-46de-acc9-eb8983a82fa8.png)

**Comment by eddieparker** [comment]
> 2. Upland Pride set: individual pieces are not tradable if the set was unbundled before the fix. Other situations: bundled set/unbundled after the fix pieces - look fine.
> 3. Looks fine
> 4. Not fixed, QoP dress individual pieces (Bloodfeather Frock, Bloodfeather Boots, Taunt: Dancing Queen) are still not giftable once.
> 5. Since person below didn't explain it in words: Hoodwink's "Taunt: In It For The Lute" from ultra rare bundle doesn't have "Wrap gift" option in the client despite it having the tag "giftable once". Note, that the actual guitar-bow is giftable once just fine. And important to mention that this issue also existed for Doom Ultra rare guitar bundle with "Taunt: Doom Shreds" from Aghs labs Battle Pass. However that item is fully tradable by now. And the issue would probably exist for QoP bundle if not for # 4. Nevertheless, looks like, it's some systematic issue with Ultra rare bundles that include taunts in them? whilte items are marked as gitfable ones - taunts don't have wrap gift option.
> 
> Eh well, after these bullet-points we gotta close ~300 duplicates 😰 trading folks really be like spamming. Sorry for this overall improper hijacking.


@Aluerie, can you check 2 & 4 again?  If any don't look correct, please send me their item IDs or account IDs if you know of them and I can investigate.  I do appreciate your help thus far - thanks again.

As for #5, I'm going to request that there be a separate bug for this so we can triage bugs better.

**Comment by Aluerie** [comment]
2\. Looks fine - all situations are covered.
4\.  Only dress item was fixed. For showcase, I will use item IDs from [my friend's inventory](https://steamcommunity.com/profiles/76561198158915098/inventory/): 
  - [x] Bloodfeather Frock - it is now giftable once just fine ✅
  - [ ] Bloodfeather Boots - not fixed. `item ID = 570_2_25964557194`.
  - [ ] Taunt: Dancing Queen - not fixed. `item ID = 570_2_25964557202`.

5\. There are quite a few duplicates on that but the oldest is probably #2945

**Comment by eddieparker** [comment]
> 

As always, thanks again.  I believe boots and dancing queen should be fixed up now.  Let me know if that's not the case, otherwise I'll close this bug.

**Comment by Aluerie** [comment]
Bloodfeather Boots - fixed ✅ tag is there and "wrap gift" option is there. 

However, looks like, Taunt: Dancing Queen has same problem as Hoodwink taunt in # 5 (mentioned #2945 issue). The tag "giftable once" is there, but there is no "Wrap Gift" option in the client. 

![image](https://user-images.githubusercontent.com/33165440/217909488-eae9029e-3562-4e0f-972a-80bed2dc7834.png)

**Comment by eddieparker** [comment]
> 

Alright, I think that gifting should be enabled now.   Let me know if not.

**Comment by Aluerie** [comment]
And now everything is good, the "Gift Wrap Item" is there for both QoP and Hoodwink taunts. Looks like all is fixed 🎉

**Comment by shaileshgarg** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/6819, can we also look into this, it is related to Giftablibity and Tradeablity of 2022 Immoratls.

**Comment by alvinkim080** [comment]
#6958 got the same issue, hoping to get a fix or help

![QOP1](https://user-images.githubusercontent.com/45165365/218979357-18cdebdd-1be2-4d98-8956-1a1458ceed2f.png)
