### ISSUE TITLE
Battele pass week 17

### ISSUE THREAD

**Issue by akilesh1997** [ValveSoftware/Dota2-Gameplay#6137]
### Description

Battele pass week 17 diertide quest Seasons greevilings  stars not counting to progress weekly quest stars

### Example Match ID (and possibly Timestamp)

6931231679 - 22:36

### Screenshots

![Screenshot (1)](https://user-images.githubusercontent.com/50032994/209332121-dec6a7d0-ee46-48f6-bae6-efd88166b3c7.png)

**Comment by Lonerwolf7** [comment]
it happen for me too lol last night i clear 4* after reset and it not counted
but the last star i clear now just got counted lol

**Comment by Dr-Bone** [comment]
exactly the same for me
![grafik](https://user-images.githubusercontent.com/52602038/209344769-12a37d9e-fafc-42ec-afad-34d5a39ba480.png)
This is one star from "Star Player" and the last star from Season's Greevlings. 4 Stars are missing. Please fix.

**Comment by Skorpion4853** [comment]
I have the same problem
![image](https://user-images.githubusercontent.com/98880853/209352032-b4263156-d1bd-4725-b382-74d00866a2d9.png)

**Comment by tisemh** [comment]
Same here!

**Comment by Dr-Bone** [comment]
just got fixed, I've the correct amount of stars now. Thank you!

**Comment by akilesh1997** [comment]
the isssue is resolved thanks
