### ISSUE TITLE
COLLECTOR CACHE 2 CANT GIFT AFTER OPENING A CACHE

### ISSUE THREAD

**Issue by ahmadfar1d** [ValveSoftware/Dota2-Gameplay#6146]
### Description

Hi, i want you guys clarity what happen to the collector cache 2.  After i opened a cache 2, the item didn't have a gift item button. i hope you guys can fix this bug ASAP. Thank you. 
![Screenshot_2](https://user-images.githubusercontent.com/121312247/209388000-db4dce75-e5e9-40b9-b112-592ec92352be.png)
's 

### Screenshots

![Uploading Screenshot_1.png…]()

**Comment by shaileshgarg** [comment]
#6125

**Comment by G1psyRa1nDanger** [comment]
same here. I have 2 complete extra sets that were supposed to be my gift to my friends in steam but still, it is a bug
