### ISSUE TITLE
dota2 macos crash

### ISSUE THREAD

**Issue by Loloner** [ValveSoftware/Dota2-Gameplay#6158]
2days ago after update vulkan not work on macos
after matchmaking game crash and for connecting again (pick/bann ) game crash again
i delete all files with vulkan and shader and gl and valid in file location but no diffrent at all
send mail to valve but no right respond or solution for problem
=)))) this is it, always after update macos users have problem

**Comment by Usera2** [comment]
deleting them wont work cause the game see them as missing files and download them again. You just have to go to video option  and select DX11 and restart the game

**Comment by Loloner** [comment]
> deleting them wont work cause the game see them as missing files and download them again. You just have to go to video option  and select DX11 and restart the game 

in game? can u Explain more precisely please i dont see dx11 in video
thank you

**Comment by Loloner** [comment]
@Nathanael-Valve

**Comment by Usera2** [comment]
![image](https://user-images.githubusercontent.com/78626849/209474509-c100d639-5656-4a80-891c-a8e4da979151.png)
Its in the Option > Video > Renderer

**Comment by Loloner** [comment]
> ![image](https://user-images.githubusercontent.com/78626849/209474509-c100d639-5656-4a80-891c-a8e4da979151.png)
> 
> Its in the Option > Video > Renderer 

i dont have it i just have gl and vulkan :(((

**Comment by Usera2** [comment]
so if your issue is with Vulcan, switch to GL and try to play some bot games

**Comment by Loloner** [comment]
> so if your issue is with Vulcan, switch to GL and try to play some bot games

gl is not working too 😂🤦🏻‍♂️

**Comment by Usera2** [comment]
Something fishy is here
Lets go back to basics

0. Restart your system
1. Verify game files in steam
2. Repair Steam Service
`Repair the Steam Service
The error may also indicate a Steam service failure. Please try repairing the Steam service:
Exit Steam.
Click Start > Run (Windows Key + R).
Type the following command: "C:\Program Files (x86)\Steam\bin\SteamService.exe" /repair
Launch Steam and test the issue again.
Note: This command requires administrator privileges and may take a few minutes. If you have installed Steam to another path, please replace C:\Program Files (x86)\Steam with the correct path.
`

3. Check for GPU driver update.
4. Check your system files (Sorry dont know how to do that in MacOs, in Windows its done by "sfc /scannow" command)
5. Check for updates for OS

**Comment by Loloner** [comment]
> Something fishy is here
> 
> Lets go back to basics
> 
> 
> 
> 0. Restart your system
> 
> 1. Verify game files in steam
> 
> 2. Repair Steam Service
> 
> `Repair the Steam Service
> 
> The error may also indicate a Steam service failure. Please try repairing the Steam service:
> 
> Exit Steam.
> 
> Click Start > Run (Windows Key + R).
> 
> Type the following command: "C:\Program Files (x86)\Steam\bin\SteamService.exe" /repair
> 
> Launch Steam and test the issue again.
> 
> Note: This command requires administrator privileges and may take a few minutes. If you have installed Steam to another path, please replace C:\Program Files (x86)\Steam with the correct path.
> 
> `
> 
> 
> 
> 3. Check for GPU driver update.
> 
> 4. Check your system files (Sorry dont know how to do that in MacOs, in Windows its done by "sfc /scannow" command)
> 
> 5. Check for updates for OS
> 
> 6. also try and disable GL and vulkan in steam DLC options
> 
> 7. Try to uninstall and Reinstall the game

i do all this things
still not work
