### ISSUE TITLE
Shadow Demon's shard ability level bug

### ISSUE THREAD

**Issue by Cassanderx** [ValveSoftware/Dota2-Gameplay#6167]
### Ability name

Demonic Cleanse

### Description

As soon as Shadow Demon obtains his shard, he will learn Demonic Cleanse at exactly level 1. The simplest fix for this would be to make cleanse match the current level of purge upon obtaining the shard.

Here's some issues that come with this that I found in demo:
- Obtaining the shard at level 1 will immediately grant access to level 1 demonic cleanse even before learning demonic purge.
- Obtaining the shard at level 12 or 18 with demonic purge at level 2/3 respectively will still only grant access to level 1 demonic cleanse
- Level ups where a discrepancy between demonic purge/cleanse level exists allow the player to apply skill points to demonic cleanse. These skill points are spent and result in being unable to obtain all talents at level 30 due to missing skill points.

### Example Match ID (and possibly Timestamp)

6933444081 - 7:40

**Comment by Bogdanov89** [comment]
Can confirm, the bug is that taking points in ultimate ability (R) does NOT carry over to the Shard ability if the Shard item is purchased after putting points into ultimate ability.

![image](https://user-images.githubusercontent.com/55892027/209440852-b079c626-7551-41ab-ae8c-defef09df8e5.png)

**Comment by matstrutz** [comment]
If you upgrade purge to level max, cleanse will upgrade to

Video example: https://streamable.com/alcx90

Another match example ID: 6938592737

**Comment by shaileshgarg** [comment]
#1465

**Comment by Bogdanov89** [comment]
@matstrutz  i do not know how is that relevant to this bug.
Cleanse should ALWAYS be the same level as Purge.
It should not require any further leveling up or anything else.

**Comment by matstrutz** [comment]
@Bogdanov89 i'm just explaining that leveling cleanse trough purge is working, the problem is just that cleanse always start at level 1, if you buy shard at purge level 1, nothing happens, but, shard at level 2 or 3 cause the bug, but, if you level purge when cleanse is under leveled, clenase will upgrade too

**Comment by pontuslaestadius** [comment]
Same issue: 6945864175 - 19:30

I don't remember SD being this buggy. It must be a new bug? But it's clearly a game ruining bug. I recommend that you don't play the hero until it's fixed.

**Comment by Cassanderx** [comment]
This bug is fixed as of the update released on 10 January 2023 – 02:50:17 UTC
![image](https://user-images.githubusercontent.com/62576705/211572668-2a109c5a-f902-4028-b66d-c0725824f40e.png)
