### ISSUE TITLE
Collection cache 2 can't be gifted

### ISSUE THREAD

**Issue by roscoewe** [ValveSoftware/Dota2-Gameplay#6185]
### Cosmetic Item Name

Cursed Cryptbreaker

### Description

my items that I received from collector's cache 2022 (the second treasure) cannot be gifted, but I looked at other people, and they can. my steam - https://steamcommunity.com/id/socialcrime/.

### Example Match ID

-

### Screenshots

![Screenshot_2](https://user-images.githubusercontent.com/121364589/209453416-23f51d87-9927-4791-8896-ce2ec931e835.png)
![Screenshot_22](https://user-images.githubusercontent.com/121364589/209453417-34d1eb84-a541-4019-8ad6-5c32169b3faa.png)
![Screenshot_1](https://user-images.githubusercontent.com/121364589/209453418-bca42103-c8d4-4235-86ad-7c0a34d78d20.png)

**Comment by rafael0915** [comment]
Same issue with me. Can you please fix it. I opened right away after the update

**Comment by shaileshgarg** [comment]
#6125
