### ISSUE TITLE
Post Game Statistics

### ISSUE THREAD

**Issue by BonOfSitch** [ValveSoftware/Dota2-Gameplay#6187]
### Description

The post game statistics are displaying incorrectly. This is post the most recent patch.
In short, the graphical chart display re experience, probability & net worth has been inverted for some reason.

Screenshot has been attached.

### Screenshots

Today's images - all inverted
![image](https://user-images.githubusercontent.com/94807154/209454852-d7970dcf-da53-4732-a1ac-8ba550a4f42b.png)
Yesterdays images - all correct
![image](https://user-images.githubusercontent.com/94807154/209454867-8362c920-a394-4009-a376-435880e0a32e.png)

**Comment by shaileshgarg** [comment]
The dire won so it makes sense that net worth, experience and win probability graph are on their side

**Comment by Usera2** [comment]
What is the problem here? it looks fine

**Comment by BonOfSitch** [comment]
> The dire won so it makes sense that net worth, experience and win probability graph are on their side
