### ISSUE TITLE
Diretide 2022 Collector's Cache II ungiftable

### ISSUE THREAD

**Issue by BreadPiece** [ValveSoftware/Dota2-Gameplay#6201]
### Description

I bought a collectors cache and was planning on gifting it to a friend to trade items with but the items in the cache and the cache itself is ungiftable.

### Screenshots

![Dota 2 Screenshot 2022 12 25 - 16 26 55 06](https://user-images.githubusercontent.com/44326377/209485847-b9b11d39-d850-4498-be19-c195d485ea4b.png)

**Comment by bouncydragon** [comment]
#6152

**Comment by Ferrocianuro** [comment]
Close?  Valve didn't fix anything

**Comment by BreadPiece** [comment]
It's because someone already has one up
