### ISSUE TITLE
Shadow Demon Shard Skill

### ISSUE THREAD

**Issue by Ciantb** [ValveSoftware/Dota2-Gameplay#6235]
### Ability name

Demonic Cleanse

### Description

Demonic Cleanse level did not attach to Ultimate skill ( Demonic Purge )
if i already have level 3 ultimate skill then buy shard
Demonic Cleanse Skill will only open at level 1 instead of level 3
![shadow demon](https://user-images.githubusercontent.com/121502620/209681089-14a0f37e-1054-4596-b15b-f4445a18776b.png)

### Example Match ID (and possibly Timestamp)

test hero

**Comment by shaileshgarg** [comment]
#1465

**Comment by shaileshgarg** [comment]
#6167

**Comment by Ciantb** [comment]
already posted... my bad...
