### ISSUE TITLE
No Rerolls in candyworks

### ISSUE THREAD

**Issue by shub011** [ValveSoftware/Dota2-Gameplay#6241]
### Description

I have won quite some games but i am not getting any rerolls in my candyworks shop despite it being available 10/10 weekly.

Attached is a screenshot.

Friend ID: 349937949

One example of a recent match for which I did not get the rolls:
6938847768 Match ID

Kindly fix this
![Screenshot 2022-12-27 125047](https://user-images.githubusercontent.com/121535739/209761188-f4990a3a-194f-49a2-a160-0c4e84aaedce.png)

### Example Match ID (and possibly Timestamp)

6938847768

### Screenshots

![Screenshot 2022-12-27 125047](https://user-images.githubusercontent.com/121535739/209761219-e225336b-394d-48b6-9167-b77696601ca5.png)

**Comment by shaileshgarg** [comment]
10/10 means you have earned all the available rerolls for the week.

**Comment by shub011** [comment]
thanks for the clarification. I thought otherwise

**Comment by shaileshgarg** [comment]
You can close the issue.
