### ISSUE TITLE
Proximity mine from the new Techies set comes as 2nd loading screen

### ISSUE THREAD

**Issue by Ian1996g** [ValveSoftware/Dota2-Gameplay#6254]
### Cosmetic Item Name

War Rig Eradicators

### Description

Proximity mine from the new Techies set comes as 2nd loading screen
Set name: War Rig Eradicators

### Example Match ID

6937301129

### Screenshots

![image](https://user-images.githubusercontent.com/104298755/209854480-ca747875-5131-4189-a529-11f5385a8840.png)

**Comment by shaileshgarg** [comment]
#6112,  duplicate issue already open, consider closing this one, and upvote the original.
