### ISSUE TITLE
Catacombs

### ISSUE THREAD

**Issue by St1movets** [ValveSoftware/Dota2-Gameplay#6283]
### Item name

Isle of Dragons ( Second Transmutation )

### Description

Didn't get the third juggernaut style, most likely due to the fact that I first went through the second catacombs instead of the first.
Не получил третий стиль джаггернаута, скорее всего из-за того, что сначала прошел вторые катакомбы вместо первых.
[https://prnt.sc/TFIXV3j3re54](url) | [https://prnt.sc/aU8UNOsVhcZw](url) | [https://prnt.sc/Ko3vh3zpL79e](url) | [https://prnt.sc/WVfiRyW-j1sN](url)

### Example Match ID and Timestamp

-

**Comment by shaileshgarg** [comment]
Close this duplicate.
