### ISSUE TITLE
Catacombs

### ISSUE THREAD

**Issue by St1movets** [ValveSoftware/Dota2-Gameplay#6284]
### Description

Didn't get the third juggernaut style, most likely due to the fact that I first went through the second catacombs instead of the first.
Не получил третий стиль джаггернаута, скорее всего из-за того, что сначала прошел вторые катакомбы вместо первых.

### Example Match ID (and possibly Timestamp)

-

### Screenshots

https://prnt.sc/TFIXV3j3re54 | https://prnt.sc/aU8UNOsVhcZw | https://prnt.sc/Ko3vh3zpL79e | https://prnt.sc/WVfiRyW-j1sN

**Comment by shaileshgarg** [comment]
Check your inventory you should have the style unlock present, as you have completed the Second Map.
