### ISSUE TITLE
the first sets of diretide 2 part 2 sets are not being able to gift

### ISSUE THREAD

**Issue by TadalaORusso** [ValveSoftware/Dota2-Gameplay#6287]
### Item name

Withering pain, darkbrew's transgression, freeboot fortunes, war rig eradicators, grand suppressor and transcendent path

### Description
![1](https://user-images.githubusercontent.com/121677489/210079056-c633de09-f55e-4f26-8cbf-deed4fdd04db.png)

hello, I bought the collector 2 items from diretide 2022 right when it was released, and they came with a bug of not being able to send as a gift, but I bought others after these and they can, so the first ones have the bug of not being able to send.
Items are Withering pain, darkbrew's transgression, freeboot fortunes, war rig eradicators, grand suppressor and transcendent path. all itens for collector 2 are buggy.
### Example Match ID and Timestamp

307846160 https://steamcommunity.com/id/Tadalaorusso/ 
![2](https://user-images.githubusercontent.com/121677489/210079062-37c7c6a4-642f-4740-9232-252e68fd6065.png)
![3](https://user-images.githubusercontent.com/121677489/210079073-6947c7b8-8087-438b-b76e-1a1f1647ae7d.png)
![4](https://user-images.githubusercontent.com/121677489/210079081-8b50f5eb-eb12-435c-8ee7-fc27e5bfb25a.png)
![5](https://user-images.githubusercontent.com/121677489/210079089-e330beae-5c36-435b-9c88-799854989242.png)
![6](https://user-images.githubusercontent.com/121677489/210079098-27df1003-758d-4d9c-9e9b-f5e6c4a746e4.png)
![7](https://user-images.githubusercontent.com/121677489/210079104-7de2f0dd-d4ef-43fd-bc07-e20b4f7d903a.png)
![8](https://user-images.githubusercontent.com/121677489/210079107-4478cab6-76c1-45e2-a6b1-b2bc3b9fd5cf.png)
![9](https://user-images.githubusercontent.com/121677489/210079111-1ad6a27a-d6f7-49d2-8dba-26b0ab515dc7.png)
![10](https://user-images.githubusercontent.com/121677489/210079127-153d837b-de6f-445a-bdec-4e05af707868.png)
![11](https://user-images.githubusercontent.com/121677489/210079134-980e8326-1abb-49cf-bc25-b36a9fc16eb5.png)
![12](https://user-images.githubusercontent.com/121677489/210079140-7b578fdc-3e98-4419-b93e-e60a52c3eebe.png)
![13](https://user-images.githubusercontent.com/121677489/210079143-99e53776-dc1b-4c40-8cb6-67a297b482e7.png)
![14](https://user-images.githubusercontent.com/121677489/210079150-e0633dc6-5cd3-4fcc-a2b8-c0d733df93a1.png)

**Comment by shaileshgarg** [comment]
#6125 duplicate, consider upvoting the orignal post and closing this one.
