### ISSUE TITLE
Rubick Talent +175 Telekinesis Landing Damage has no effect (does no damage)

### ISSUE THREAD

**Issue by dipique** [ValveSoftware/Dota2-Gameplay#6291]
To reproduce: go to demo mode with Rubick, go to max level and choose all talents/skills. Spawn an enemy and use telekinesis. It will do no damage at all.

**Comment by shaileshgarg** [comment]
The damage is done on the enemies on which the telekineiss enemy is thrown, not on the enemy that is lifted.

**Comment by dipique** [comment]
Apparently the bug is with me, not the game. Thanks!
