### ISSUE TITLE
treasure bugs

### ISSUE THREAD

**Issue by ibrhmazmi** [ValveSoftware/Dota2-Gameplay#6307]
### Item name

Immortal Treasure I 2020 bugs

### Description

duplicates item - i bought several Immortal Treasure I 2020 to get the immortals , but after 4-5 treasure opens, the cycle reset to zero hence the duplicates item.<br>
![image](https://user-images.githubusercontent.com/75335119/210150137-192ad6ca-ddc1-4252-a7a9-b80d5613097f.png)<br>
![image](https://user-images.githubusercontent.com/75335119/210150158-6e6fd3f1-9936-4866-be7f-3268608eca70.png)

### Example Match ID and Timestamp

-

**Comment by shaileshgarg** [comment]
Yeah, thats normal. You get the Common Immortal after you have 1 of all of the Commons, and this repeats. The Rare, Very Rare and Ultra Rare are chance based.

**Comment by ibrhmazmi** [comment]
ic. thanks for the clarification @shaileshgarg 😢

**Comment by shaileshgarg** [comment]
You can close the issue
