### ISSUE TITLE
Drow Ranger Multishot does not show range

### ISSUE THREAD

**Issue by Daar543** [ValveSoftware/Dota2-Gameplay#631]
### Hero and spell

Drow Ranger and Multishot

### Description

The spell has infinite casting range, yet the arrows fly only in 1.75x your attack range (unless they hit a target). 

Therefore: 
- the cast range indicator should show this distance, based on your attack range (as a tooltip)
- for QoL, the ability could also have limited range (=it won't be cast, unless the arrows can reach there), but this is questionable.

**Comment by Dota-Exp** [comment]
Will be fixed in the next update, thank you
