### ISSUE TITLE
Aghanim's Shard on Luna doesn't make attack on invisible unit

### ISSUE THREAD

**Issue by crykek** [ValveSoftware/Dota2-Gameplay#632]
### Ability name

Lucent Beam

### Description

Use Lucent Beam with Aghanim's Shard on invisible enemy (with having True Sight on him) and he will receive damage only from the ability without making attack from Aghanim's Shard.
![9275pK6](https://user-images.githubusercontent.com/34211000/172147502-49b5bce9-44c8-4d0c-889c-0e9304515e6f.png)

### Example Match ID (and possibly Timestamp)

Any game

**Comment by Dota-Exp** [comment]
This issue is no longer relevant due to a change to the shard.
