### ISSUE TITLE
I just bought a cosmetic and I cannot use it in game

### ISSUE THREAD

**Issue by wilhem514** [ValveSoftware/Dota2-Gameplay#6321]
### Cosmetic Item Name

Worship of the sleepless sect

### Description

Dota2 says I have it but I do not have the option to unbundle and use. I dont know what to do I never had that problem before.

### Example Match ID

wilhem514

**Comment by shaileshgarg** [comment]
Can you add some screenshots for it.

**Comment by wilhem514** [comment]
[dota2 screenshot.docx](https://github.com/ValveSoftware/Dota2-Gameplay/files/10331525/dota2.screenshot.docx)

see doc in attach. Note: I cant right click to open as usual or anything. Thank you.

**Comment by shaileshgarg** [comment]
In your Inventory, see if you can Right Click the set, and Unbundle and Equip option.

**Comment by wilhem514** [comment]
wow damn im stupid ! tyvm have a great day !
