### ISSUE TITLE
Witch doctor, BROKEN

### ISSUE THREAD

**Issue by yaya98** [ValveSoftware/Dota2-Gameplay#6324]
### Ability name

ALL

### Description

Look at how much this hero is being spammed and how overpowered he is.

### Example Match ID (and possibly Timestamp)

No

**Comment by shaileshgarg** [comment]
This is bug tracker, don't spam it with non issues.

**Comment by Tept1950** [comment]
Dialogue and character development not action would be the main focus. I am not a writer so I can’t really give you advice on writing such a character.
I would though recommend you some reading:
Superman: Earth One
Lucifer, the Mike Carey verison.
Sandma
