### ISSUE TITLE
I have purchased battlepass for gift and it charged me but didn't sent

### ISSUE THREAD

**Issue by odinvoker** [ValveSoftware/Dota2-Gameplay#6327]
### Item name

Battle Pass 2022

### Description

I have gifted 8 items before gifting battle pass, and then when I tried to gift battle pass, it first let me buy the item through steam marketplace and then when it's done, it says only 8 items can be gifted in 24 hours.

I have bought 200 bp level and I can't find it anywhere.

https://help.steampowered.com/en/wizard/HelpWithItemPurchase?transid=3215038785291906377&appid=570

This is my transaction page link

### Example Match ID and Timestamp

https://help.steampowered.com/en/wizard/HelpWithItemPurchase?transid=3215038785291906377&appid=570

**Comment by shaileshgarg** [comment]
They should be in your inventory.

If they are not there Contact Steam Support.

**Comment by odinvoker** [comment]
Thank you! Just found it

**Comment by shaileshgarg** [comment]
You can close the issue
