### ISSUE TITLE
Faceless Void: Backtrack Reversing Damage

### ISSUE THREAD

**Issue by Vash1116tv** [ValveSoftware/Dota2-Gameplay#6345]
### Ability name

Backtrack

### Description

Timewalk is reversing all damage, even if Faceless Void did not have the health to lose. This results in Shallow Grave and Time Walk full healing him. I (and everyone I've asked) assumes that it works more like Time Lapse, in that it would not count this healing because it's far more than he had before.

A video to demonstrate.

https://youtu.be/7PIta8uXCDE

### Example Match ID (and possibly Timestamp)

https://youtu.be/7PIta8uXCDE

**Comment by shaileshgarg** [comment]
Technically it converts the damage done in last 2s to Faceless to heal, even if faceless is shallow graved he is still taking damage.

**Comment by beH3uH** [comment]
You meant timewalk no ? This should also be interesting interaction with damage blocks. 

If you are at 2 hp for example, block 99 out of 100 and you timewalk at 1 hp, would you get to 101 hp ?

Seems like a bug a to me.

**Comment by shaileshgarg** [comment]
https://dota2.fandom.com/wiki/Dazzle, 

```
    Prevents the target from dying by setting its [minimum health](https://dota2.fandom.com/wiki/Min_health) to 1.
    Damage taken is not reduced, so any damaging event still registers the full damage.
```

So Damage is done to Void, and the damage is registered, so he can timewalk it off.

Void timewalks damage that is registered, in case of damage block, he would only timewalk the damage that he received. 

```
If you are at 2 hp for example, block 99 out of 100 and you timewalk at 1 hp, would you get to 101 hp ?

No, you would get to 2 HP.
```
