### ISSUE TITLE
Trust of the Benefactor 2020 Marketability Bug

### ISSUE THREAD

**Issue by pochitabestboi** [ValveSoftware/Dota2-Gameplay#6351]
### Description

Item was suppose to be marketable after The International 11. As you can see it is 2023 now and even Aghanim's and Nemestice's Trust of Benefactor are available to be sold  much earlier than the former.

![TOB2020UNMARKETABLE](https://user-images.githubusercontent.com/121862190/210337221-1825f730-2407-4868-9bdd-3307334599be.png)

**Comment by pochitabestboi** [comment]
Here's the current market status

![image](https://user-images.githubusercontent.com/121862190/210338061-45291e56-e912-4521-8890-96e3fe13f96f.png)

**Comment by shaileshgarg** [comment]
Can you check what immortals are still not marketable from 2020 and add then to https://github.com/ValveSoftware/Dota2-Gameplay/issues/5284, consider closing this issue and upvote that one.
