### ISSUE TITLE
Dota 2 gift system not working

### ISSUE THREAD

**Issue by howarron** [ValveSoftware/Dota2-Gameplay#6365]
### Description

The gifting friend list box disappeared. 
I also checked the gifting restrictions and it says 'all your friends are available for gifting. Give away! '
but somehow the friend list doesn't show up properly.

Please help to fix this ASAP. thanks.

### Screenshots

![20230104094823_1](https://user-images.githubusercontent.com/121913494/210472369-60a6f3e8-2fa4-4b08-8d5a-6e5cb6f4b280.jpg)

**Comment by shaileshgarg** [comment]
Probably a temparary server issue wher it is unable to load friend list.

**Comment by B54Carey2** [comment]
Try logging out of the steam client and relogging. This will force the system to pull information from the mobile authenticator as you need the code off the app to log in. This could fix a simple error where the system is overlooking the fact you have the authenticator.
