### ISSUE TITLE
"Taunt: Some Light Horseplay" is still unmarketable after The International 2022

### ISSUE THREAD

**Issue by 6222780106** [ValveSoftware/Dota2-Gameplay#6373]
### Cosmetic Item Name

Taunt: Some Light Horseplay

### Description

**"Taunt: Some Light Horseplay"** is a taunt of Keeper of the Light that was obtained by leveling The International 10 Battle Pass to 18. It was set to be marketable after The International 2022 (TI11), as shown in the first figure. However, after the end of The International 2022, this taunt is still unmarketable, as shown in the second figure. 

### Example Match ID

-

### Screenshots

![Taunt_Some Light Horseplay](https://user-images.githubusercontent.com/87574302/210558650-7c029b47-b1fa-42a8-ba01-651fae8688f8.png)
![Taunt_Some Light Horseplay_Now](https://user-images.githubusercontent.com/87574302/210558892-3dbefbe6-f923-4dcd-bf34-fcc8576727c9.png)

**Comment by delta14127** [comment]
Found similar issues here #5284
