### ISSUE TITLE
MAKE ALL PICK FASTER OR MAKE TURBO RANKED PLZZZZZZ

### ISSUE THREAD

**Issue by whyyoudidthis** [ValveSoftware/Dota2-Gameplay#6376]
### Description

THERE IS WORST DOTA IN HISTORY NOW, 50% OF GAMES ONE HOUR DURATION WTFFFF, NOONE ENJOYS THAT DURATION. TURBO NOW IS ALMOST LIKE ALL PICK IN THE PAST, 25-30 MINUTE GAMES 80% OF GAMES!?? DO SOMETHING PLZZZZZ WTFFFF
IF YOU WANT THIS LONG GAMES AT LEAST GIVE SUPPORTS MORE NETWORTH LIKE IN TURBO, IT WOULD BE MORE INTERESTING AT LEAST! ALL PICK IS TOO BORING NOW, TOO BORING, GABEN!!

**Comment by shaileshgarg** [comment]
This is bug tracker, don't spam it with non issues.

**Comment by Ciantb** [comment]
it really easy to solve this...
if you're boring of your match, you can abandoned it...
you can play again next day when you want it...
PROBLEM SOLVED...!!!!

man... you should know where to confide... this is not the right place... lol
