### ISSUE TITLE
Candyworks Bug

### ISSUE THREAD

**Issue by IkerShine** [ValveSoftware/Dota2-Gameplay#6389]
### Description

Hi. when i use "candyworks" i get 5000 battle points and 1000 battle points. but I didn't receive. they don't appear in my inventory. what should I do?

**Comment by shaileshgarg** [comment]
Check your points log

**Comment by shaileshgarg** [comment]
![Screenshot 2023-01-05 094017](https://user-images.githubusercontent.com/26450759/210700101-ac747b59-d207-4d7b-bc53-aaa1b4a1c630.png)

**Comment by IkerShine** [comment]
thank you
