### ISSUE TITLE
Dawnbreaker E does not account for multiple targets hit by Q 

### ISSUE THREAD

**Issue by Aluerie** [ValveSoftware/Dota2-Gameplay#6423]
### Ability name

Dawnbreaker E (Luminosity) + Q (Starbreaker)

### Description

Previously, when DB skills were working fine (before supposed fix for "Dawnbreaker loses Luminosity Stack when her attack misses" #706) it was like this - if you hit multiple targets with Q and E procs on swipe/smash then you get a huge bulk-heal combined from E on every target. 

Now it just heals from one.
  
Video showcase: https://youtu.be/1x48gkur2-k - you can see that we heal +132 from one Naga and samish +130 from hitting 4 Nagas with QE while it should be +520 for hitting 4 of them.

**Comment by hbthegreat** [comment]
Definitely really hurts Dawn as an offlaner currently as that big heal during a fight is one of the only things in her kit that gives her durability. Will be very excited once this one is fixed :)

**Comment by Aluerie** [comment]
This issue was stealth-fixed.

It looks like everything is fine now. 

* E works on normal hits
* EQ heals properly from multiple targets
* E does not lose stacks if attack is missed (does not grant too)
* Dying with 3 stacks does not crash the server
