### ISSUE TITLE
Carven Crawl Style not unlocking

### ISSUE THREAD

**Issue by rainking185** [ValveSoftware/Dota2-Gameplay#6455]
### Description

I would like to find out why I am not receiving the item for unlocking the style for Slardar.
Steam ID: 154284885

### Screenshots

![Screenshot 2023-01-07 203127](https://user-images.githubusercontent.com/15011545/211144087-62fa1d39-f9a7-43ee-b675-d0e344dd7417.png)

![image](https://user-images.githubusercontent.com/15011545/211143931-71b6c93b-21cd-4091-9e6a-16cdd5836c10.png)

**Comment by shaileshgarg** [comment]
The style Unlock is a separate item, find it in the inventory, and then Unlock Style.

**Comment by rainking185** [comment]
> The style Unlock is a separate item, find it in the inventory, and then Unlock Style.

Thanks. I managed to find that item in Others. Thought it should be under Hero category
