### ISSUE TITLE
Furion trents wrong damage 

### ISSUE THREAD

**Issue by Avarise831** [ValveSoftware/Dota2-Gameplay#6468]
### Ability name

Nature's Call

### Description

description  Nature's Call saying treants have 18/26/34/42 dmg, but in game 16/23/30/37

### Example Match ID (and possibly Timestamp)

-

**Comment by shaileshgarg** [comment]
The treant damage is correct, but the tooltip damage numbers is incorrect.

https://www.dota2.com/patches/7.31 treant damage was reduced to 16/23/30/37 in this patch.
