### ISSUE TITLE
Did not get style 2 for jugg in Cavern Crawl

### ISSUE THREAD

**Issue by tluckriki** [ValveSoftware/Dota2-Gameplay#6478]
### Description

I have Collected all fragments in both maps, 3 fragments for "The Fires of Ulmarain" & also 6 fragments for "The Chasms of Blueheart".... I have only received style 1 and style 3 of the jugg set... Please help, I need the style 2 .... This is my dota 2 friend ID 267369448

### Screenshots

![20230108180942_1](https://user-images.githubusercontent.com/122211520/211197316-c3966989-6be1-4b27-b535-24cfcdc05e7b.jpg)
![20230108180902_1](https://user-images.githubusercontent.com/122211520/211197319-94a72c0a-9dab-4b9d-8835-9e16cd6d8fc4.jpg)
![20230108180853_1](https://user-images.githubusercontent.com/122211520/211197321-2fdcde89-6de3-480b-ba77-8a385eb32665.jpg)
![20230108180845_1](https://user-images.githubusercontent.com/122211520/211197323-cce283ed-173f-49d9-af63-234674e04e73.jpg)

**Comment by shaileshgarg** [comment]
The style Unlock is a separate item, find it in the inventory, and then Unlock Style.
https://www.youtube.com/watch?v=zRYgPw6VDd8

**Comment by tluckriki** [comment]
> The style Unlock is a separate item, find it in the inventory, and then Unlock Style. https://www.youtube.com/watch?v=zRYgPw6VDd8

I do not have the item to unlock the style... Which I have also posted in the screenshots of my inventory

**Comment by tluckriki** [comment]
Was in inventory on "other" section
