### ISSUE TITLE
Arcana

### ISSUE THREAD

**Issue by Mike1xyz** [ValveSoftware/Dota2-Gameplay#6487]
### Description

Hello, I took the arcana on phantom assassin and I got the same arcana on phantom assassin from the candy store. can you replace it with any other arcana? The first arcana package is opened, the second one has not been opened yet.

**Comment by shaileshgarg** [comment]
This is bug tracker, don't spam it with non issues.

**Comment by Mike1xyz** [comment]
Removed, incorrect place to post
