### ISSUE TITLE
Broodmother damage of silken bola should be 160 at lvl 4 but it shows 120

### ISSUE THREAD

**Issue by ritwikthorat** [ValveSoftware/Dota2-Gameplay#6498]
### Ability name

SILKEN BOLA

### Description

Broodmother damage of silken bola should be 160 at lvl 4 but it shows 120
![Screenshot (19)](https://user-images.githubusercontent.com/28749372/211296617-cd79b233-6fe5-4ba2-962a-41c83576d21a.png)
![Screenshot (21)](https://user-images.githubusercontent.com/28749372/211296935-dacca909-8cf1-4627-9577-4b0f5caf84df.png)

### Example Match ID (and possibly Timestamp)

na

**Comment by shaileshgarg** [comment]
Heroes have 25% magic resist

**Comment by ritwikthorat** [comment]
DK is lvl 1 and I used it on dummy. From where they are getting magic resistance?

**Comment by Avarise831** [comment]
dummy and dk has 25% resit learn dota you can close this :)
