### ISSUE TITLE
Found all the fragments but the style did not open

### ISSUE THREAD

**Issue by BSQWERSO** [ValveSoftware/Dota2-Gameplay#6530]
### Description

Found all the fragments but the style did not open

### Screenshots

![Без имени](https://user-images.githubusercontent.com/122370875/211564705-52e4f798-70a6-4654-9834-ee866dbf9191.png)
![Без имени1](https://user-images.githubusercontent.com/122370875/211564716-2a45c4f3-1e85-4967-a6d0-daa749cce50c.png)

**Comment by shaileshgarg** [comment]
The style Unlock is a separate item, find it in the inventory, and then Unlock Style.
https://www.youtube.com/watch?v=zRYgPw6VDd8

**Comment by BSQWERSO** [comment]
> Разблокировка стиля — это отдельный предмет, найдите его в инвентаре, а затем Разблокируйте стиль. https://www.youtube.com/watch?v=zRYgPw6VDd8

there is no style in the inventory, sorted by hero, by date, no style.

**Comment by shaileshgarg** [comment]
Inventory -> Others

**Comment by BSQWERSO** [comment]
I found everything, thanks

**Comment by shaileshgarg** [comment]
You can close the issue.
