### ISSUE TITLE
Immortal item ability effect swap causes incorrect post-game loadouts

### ISSUE THREAD

**Issue by Cassanderx** [ValveSoftware/Dota2-Gameplay#6540]
### Description

When playing a game with an immortal ability effect swapped, the post-game summary loadouts will sometimes replace equipped items with the immortal items from which the ability FX originate instead. 

For example, when playing as Lich and using the immortal ability effect from the "Perversions of the Bloodwhorl" hat while having the "Hat of the Mad Mutineer" equipped will result in the post-game screen showing lich with the "Perversions of the Bloodwhorl" equipped instead. The "Hat of the Mad Mutineer" will still be listed in the equipped cosmetics section though. 

### Example Match ID (and possibly Timestamp)

6964261725

### Screenshots

![image](https://user-images.githubusercontent.com/62576705/211692387-a862e76b-2e8f-4940-a6d1-df335c65a1a9.png)

**Comment by shaileshgarg** [comment]
#1616
