### ISSUE TITLE
Clinkz Burning Barrage + Shadow Blade 

### ISSUE THREAD

**Issue by shaileshgarg** [ValveSoftware/Dota2-Gameplay#6549]
### Ability name

Burning Barrage

### Description

If Clinkz uses Shadow Blade after Burning Barrage, we remains invis, but the each burning barrage arrow does +175 extra damage.
This damage is the Shadow Blade bonus damage. Clinkz remains invis throughout.

Similar interaction with Silver edge, only the first arrow does the bonus damage, and breaks the target. Clinkz becomes visible.

Jug with Spin + Shard, does Instant Attack like Clinkz burning barrage, but Jug only does +175 damage on the first instant attack during spin and becomes visible.

Clinkz should also have similar interaction, either he remains invis and does no extra damage or becomes visible and does +175 extra only on the first burning barrage arrow.

### Example Match ID (and possibly Timestamp)

-

**Comment by eberek607** [comment]
Haha, this is so busted and 100% needs fixed xD

**Comment by Aluerie** [comment]
fixed pog 
![image](https://user-images.githubusercontent.com/33165440/223280339-51e9376f-d3e5-4448-8813-a81e8bbe3c79.png)
