### ISSUE TITLE
Lina bug

### ISSUE THREAD

**Issue by DenRJMexico** [ValveSoftware/Dota2-Gameplay#6556]
### Description

Lina after aegis
Passive stacks don't drop.

### Example Match ID (and possibly Timestamp)

6965083060 - 34:30

**Comment by shaileshgarg** [comment]
On death the expection is that Fiery Soul Stacks go from 7->0, but instead they follow the normal cooldown.

Don't know if this expected.

**Comment by TheUnholyWrath** [comment]
#5887
