### ISSUE TITLE
Behavior Score and Banned

### ISSUE THREAD

**Issue by fdionj** [ValveSoftware/Dota2-Gameplay#6559]
### Description

My behavior score went dropped from 5,132 to 1 because I'm accidently abandon a Turbo game. The game wasn't started yet, it's at "Selection Hero" Phase. In next game, i got inform that my account was banned. Any help for this case? 

Friend ID: 1493058636

### Example Match ID (and possibly Timestamp)

6965337793

### Screenshots

![image](https://user-images.githubusercontent.com/54367064/212001875-3da44696-d46d-400c-8c9e-d8c552b06f14.png)
![Capture](https://user-images.githubusercontent.com/54367064/212001891-9672d68f-a29d-4f16-8018-ec21775a6c6b.PNG)

**Comment by shaileshgarg** [comment]
#6471, for the sudden behavior drop

Abandon can lead to Banned, for how long were you banned.

**Comment by fdionj** [comment]
Last time i checked until 2038. Usually at similar case, the ban is permanent or durational? 
![image](https://user-images.githubusercontent.com/54367064/212081892-8cdb910f-a20e-4fd0-b61f-31e0a9ee27ac.png)
