### ISSUE TITLE
Another confirmation problem

### ISSUE THREAD

**Issue by Haunterrr** [ValveSoftware/Dota2-Gameplay#6573]
### Description

I just can't accept the game. The status "confirmation" hangs for a couple of minutes and again goes into the search for the game. Endless cycle.

Dear developers, thank you for the last hours of BP and the inability to simply play... Unforgettable emotions.

### Screenshots

![confirmation1](https://user-images.githubusercontent.com/12453075/212152815-178c4ab6-e214-47d5-949b-a1e389b2e3e6.png)
![confirmation2](https://user-images.githubusercontent.com/12453075/212152827-02dafbd7-9eb6-4056-bfb1-c8edaa685071.png)
![confirmation3](https://user-images.githubusercontent.com/12453075/212152837-b975908f-d9b5-480a-a6f1-5bc933700b9f.png)

**Comment by shaileshgarg** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/6567
