### ISSUE TITLE
Bundle still available after battle pass finished

### ISSUE THREAD

**Issue by itsquad-mdb** [ValveSoftware/Dota2-Gameplay#6576]
### Description

I purchased the bundle on the 12th (the last day of the event), whilst the battle pass and its levels were still visible. I got all the treasures, but the most valuable part, the levels and the items that go with them were not credited to my account. I restarted Dota and the battle pass had apparently ended and the items for the levels were missing. This is clearly a bug as it allows end-users to spend a non-trivial amount of money and get very little for it.

**Comment by Evviy** [comment]
The same situation (

**Comment by itsquad-mdb** [comment]
Devs, can we please get a solution to this? I want to get all my owned items delivered to my account.

**Comment by shaileshgarg** [comment]
Battle pass page can still be accessed, Top right corner Notifications and look for the bp entry

**Comment by itsquad-mdb** [comment]
Thank you for coming back. I can get to it, I can see that. However, my issue is that I purchased a 'Diretide 2022 Battle Level Bundle'. So this should have given me 120 levels and all the extra content that came with it.

My current level is 74 it is clear that I was charged and the BP levels were not credited to my account.
I hope that is clearer. Let me know what additional information you need to be able to sort this out please.

**Comment by shaileshgarg** [comment]
After purchasing the bundle you have to Use the bundle from the inventory to apply the levels. Don't know if that can done now.

**Comment by Evviy** [comment]
Sorry for sticking in with a comment: after unpacking (immediately after purchase) the bundle from the inventory, only treasures were given, but the levels were not added, therefore there are no additional items for the levels ((

**Comment by shaileshgarg** [comment]
https://www.youtube.com/watch?v=hwN0tMOKQxE, check this video, the levels have to applied after unbundling the bundle.

**Comment by Evviy** [comment]
Shaileshgarg, many thanks for video! I got all levels and additional items - no any questions from my side!

**Comment by shaileshgarg** [comment]
You can close this issue.
