### ISSUE TITLE
Moon Shard disappearance

### ISSUE THREAD

**Issue by PlayHard2023** [ValveSoftware/Dota2-Gameplay#6577]
### Item name

Moon Shard

### Description

Hero used : Sniper
Bug Description: After using Mjolnir for the clash, my **"Moonshard"** suddenly disappear. I didn't consume it, drop it or sell it.
If you watch the video, at **_49:20_** gameplay time I still have it then after activation of **Mjolnir** it was vanished **_(49:25)_** its gone. it's crystal clear that it was a bug. There's no indication of consumption of the item as seen on the photos below.

Match ID : **6967144996**

Your Steam Profile Link : **https://steamcommunity.com/profiles/76561198097707728/)**

Other Helpful Information:
![Still have Moonshard](https://user-images.githubusercontent.com/122568813/212177000-35cccc38-9172-451a-b3c1-8ff21f1be796.jpg)
![Vanished](https://user-images.githubusercontent.com/122568813/212177025-54cf7491-20ac-4613-98c1-0479fc75457e.jpg)

### Example Match ID and Timestamp

6967144996 - 49:20~25

**Comment by TheUnholyWrath** [comment]
You can use Moon Shard on allies and they will consume it. You used it on Night Stalker in this game. This isn't a bug, please close this issue.

**Comment by PlayHard2023** [comment]
As I review again the replay, You're right but I only activate the Mjolnir. Also I tried it in demo. No matter how far the ally you can activate it and consume to ally everywhere on the map.
Well thanks for your time.
