### ISSUE TITLE
Taunts from Ti10 BP are still not marketable/tradable

### ISSUE THREAD

**Issue by absolutathal** [ValveSoftware/Dota2-Gameplay#6584]
### Cosmetic Item Name

The International 10 Battle Pass Taunts

### Description

Taunts from TI10 Battle Pass are still not tradable/marketable. In-game description says "Marketable after The International 11". Steam item description tags them as "Not Marketable" and "Not Tradable".

### Example Match ID

6818876789

### Screenshots

![taunt2](https://user-images.githubusercontent.com/117948661/212227831-c4109a1f-69e7-4fb5-89ac-e9597d66cb06.PNG)
![taunt1](https://user-images.githubusercontent.com/117948661/212227834-f49132f2-adf1-4209-aded-ee78938e4e1a.PNG)
![taunt3](https://user-images.githubusercontent.com/117948661/212228089-e6aab5a4-c043-40a6-aac1-00deeafedced.PNG)

**Comment by shaileshgarg** [comment]
#5284
