### ISSUE TITLE
Battlepass 2022 chat wheels sounds are missing

### ISSUE THREAD

**Issue by centralnui** [ValveSoftware/Dota2-Gameplay#6586]
### Description

Hello!
By some reason I cant find those sounds, I spent money to this battlepass and these sounds was one of reasons why I spent money on it. Nothing were indicating that these sounds will disappear when battlepass expires. It never had a "seasonal" flag like special effects. The interesting thing, we still have smiles, but sounds are missing. 

### Screenshots

![20230113133644_1](https://user-images.githubusercontent.com/113243212/212256292-f1535bb0-7dbb-44b5-be8e-6d9611dc75f0.jpg)
![20230113134338_1](https://user-images.githubusercontent.com/113243212/212256301-d285dd08-cb70-497a-92a9-e474a15e4996.jpg)
![20230113135453_1](https://user-images.githubusercontent.com/113243212/212256619-9ac4b5c0-65ff-496e-995d-9b33939b22e8.jpg)

**Comment by shaileshgarg** [comment]
https://www.dota2.com/battlepass2022, Chat Sounds are mentioned as Seasonal.

**Comment by centralnui** [comment]
I spent money in game, I look for this battlepass and doing progress in game, what is this page? Why would I or anyone else visit it? Battlepass didnt mentioned that this was seasonal, so it wasnt then!

**Comment by centralnui** [comment]
You are saying that this "mentioned as Seasonal", BUT, read it with more attention. I dont see it the way you describe. It doesnt say that they will disappear when pb will be gone. So it HAS NO status of seasonal award. Look at the screenshots above.

![image](https://user-images.githubusercontent.com/113243212/212265896-8a08bae9-5694-40da-8b15-470d86a50c31.png)

**Comment by centralnui** [comment]
I would like to know when it will be fixed.
