### ISSUE TITLE
Treant Protector turns around if you double click Living Armor when you have aoe talent

### ISSUE THREAD

**Issue by Bu3nyy** [ValveSoftware/Dota2-Gameplay#659]
### Ability name

Living Armor

### Description

This was fixed for Dark Seer, LC, and Warlock as reported in issue #22 

Living Armor has this issue as well, if you get the AoE talent, and have some slight ping, he will turn around to cast it.

**Comment by AncientsAndAntiques** [comment]
I also just had this happen with Brewmaster Cinder Brew.

**Comment by Bu3nyy** [comment]
It's how area-targeted abilities behave in general.

The thing with Living Armor (and previously, Press the Attack, Surge, and Shadow Word) are single-target abilities by default, and you double-tap them to cast it on yourself, and they should still be able to do that with the talent as effective as without it.

**Comment by Dota-Exp** [comment]
Living Armor will be fixed in upcoming update.
Thank you
