### ISSUE TITLE
Advanced Bladework Tinker

### ISSUE THREAD

**Issue by Rongan1** [ValveSoftware/Dota2-Gameplay#6590]
### Description

The Dota 2 steam inventory states that the mockery can be transferred after The international 11, but it still cannot be transferred/sold.

### Screenshots

![image](https://user-images.githubusercontent.com/118563505/212272830-40ff6365-3289-4b25-917c-3a1b20bbab54.png)
![image](https://user-images.githubusercontent.com/118563505/212272942-956e3583-1cba-498d-b517-8c517581347c.png)

**Comment by shaileshgarg** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/5284
