### ISSUE TITLE
collector cache 2020 spirit of the sacred grove

### ISSUE THREAD

**Issue by kuroashi1992** [ValveSoftware/Dota2-Gameplay#6598]
### Item name

spirit of the sacred grove

### Description

Ti11 is over and the item cannot be sold/purchased on the steam market
![mirana ultra raro](https://user-images.githubusercontent.com/122607413/212301600-aa0ff28e-5852-46d2-a3d0-9ff61f083b64.png)

### Example Match ID and Timestamp

11-45

**Comment by shaileshgarg** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/5284

**Comment by menta841** [comment]
It also appears the same to me, the one from the legion commander could be exchanged but this is still nothing

**Comment by kuroashi1992** [comment]
Gracias.
