### ISSUE TITLE
Techies Sticky Bomb accelerates infinitely if the target teleports away

### ISSUE THREAD

**Issue by Bu3nyy** [ValveSoftware/Dota2-Gameplay#661]
### Ability name

Sticky Bomb

### Description

Techies's Sticky Bomb starts at a speed of 500 and accelerates at a rate of 2000.

The problem here is, if the target manages to teleport far away before the bomb reaches it, it may accelerate to a point where it can no longer latch onto the target and gets stucky pretty much permanently juggling around the target.

In the video, you can see how much it already escalates within 2 minutes.
[video demo](https://www.youtube.com/watch?v=9Uu-PQB4e1E)

If the game goes long enough, this will cause serious lags and fps drops, as the speed reaches absurdly high values. After stopping the recording, I let the server run for another 20 minutes and that was already enough to drop the fps down from a stable 144 to like 10fps.

Edit: 2 possible solutions:
1. A maximum speed cap (like 2k or something)
2. A distance cap or a max chase timer, so that the bomb stops chasing if the distance gets too great or the chase takes too long.

**Comment by Uwila** [comment]
Hate when this happens in my pubs

**Comment by khanghugo** [comment]
The sticky bomb seems to behave like that to avoid juking. It should be "sticky" and sticked to the target rather than following, like how Grimstroke's Phantom or Weaver's Swarm behaves.

**Comment by w8eight** [comment]
Ah yes, I watched only first example, my bad

**Comment by Dota-Exp** [comment]
Fixed in upcoming update
