### ISSUE TITLE
error 193 or 127

### ISSUE THREAD

**Issue by Miligat12** [ValveSoftware/Dota2-Gameplay#6625]
### Description

Can't start the game on Windows 7,
first it was error 127 now 193.
As soon as the update came out on 1/11/2023 i can't play,
please help me in this situation, I even installed the security
system and the windows security system, I saw how many wrote that
it helped them, but as always it didn’t help me

### Example Match ID (and possibly Timestamp)

3:32 11.01.2023-14.01.2023

### Screenshots

![Без імені](https://user-images.githubusercontent.com/122649541/212461130-deff77b1-1e8f-4dfe-be72-caa4161ba87a.jpg)

**Comment by shaileshgarg** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/6579
