### ISSUE TITLE
i can't sell my taunts from ti10 compendium 

### ISSUE THREAD

**Issue by Cintecs** [ValveSoftware/Dota2-Gameplay#6632]
### Description

when i can sell or trade my taunts from ti10 compendium?

### Screenshots

![image](https://user-images.githubusercontent.com/117559227/212474817-241cf49f-e257-408d-942a-0dfc8b78c9bd.png)

**Comment by shaileshgarg** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/5284
