### ISSUE TITLE
The courier does not deliver blocked items.

### ISSUE THREAD

**Issue by EvgeniyTelegin** [ValveSoftware/Dota2-Gameplay#6635]
### Item name

Any item locked for assembly.

### Description

![ex](https://user-images.githubusercontent.com/106628798/212493637-d54d908c-6976-4a22-83fd-4ea43dd3919b.png)

If there is an item in the courier and it is blocked for assembly (and it is there alone) Then the game thinks that the courier is empty. If there are more items there, then he will only deliver them.

### Example Match ID and Timestamp

Played everywhere

**Comment by TheUnholyWrath** [comment]
>  Courier items that are locked will now not be delivered nor will they be returned to the stash

This was a deliberate change made in 7.23c. You should close this issue.

**Comment by EvgeniyTelegin** [comment]
@TheUnholyWrath 
Oh... Thank you, I missed this moment. Strange mechanics, as for me, which plays a cruel joke when the courier simply does not give what he owes.
