### ISSUE TITLE
item not available on bde steam market

### ISSUE THREAD

**Issue by Darby20** [ValveSoftware/Dota2-Gameplay#6638]
### Item name

Warden of the Hellborn

### Description

International 10 ended a long time ago and I can't sell this item, I opened new chests and that specific item can't be sold, it's an error that I want to be fixed please
![Screenshot_20230114-184202_Steam~2](https://user-images.githubusercontent.com/108972482/212501889-48bcc052-076e-4a7f-b5a6-0df5dbe918a5.png)

### Example Match ID and Timestamp

6:46

**Comment by shaileshgarg** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/5284
