### ISSUE TITLE
Does not meet 2021 TI trade and sell trade unlock condition.

### ISSUE THREAD

**Issue by Tvice18** [ValveSoftware/Dota2-Gameplay#6654]
### Description

Does not meet the condition of unlocking the trade and sale on 2021 TI taunts, such as heroes: Tinker, Templar Assasin, Mars, Ember and others 
I attached screenshots to the post, which show that they will be open for sale and exchange after TI 11, but it has already ended, and the items have not been unlocked.
Please fix this error
I apologize in advance for the Russian localization on screenshots.
I also apologize for the grammatical errors, because this is a google translator

### Screenshots

![image (1)](https://user-images.githubusercontent.com/122788671/212668099-a6e11340-bcc3-4bf6-b278-cc6e1f7c588e.png)
![image (2)](https://user-images.githubusercontent.com/122788671/212668186-c836d8ea-5479-49db-91d0-95a292efaaf3.png)
![image](https://user-images.githubusercontent.com/122788671/212668196-d605c826-b935-43e5-a594-4bcaedd8d164.png)

**Comment by shaileshgarg** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/5284
