### ISSUE TITLE
QOP Immortal can't be gifted

### ISSUE THREAD

**Issue by whodeen** [ValveSoftware/Dota2-Gameplay#6661]
### Description

We have an inconsistency here, I get it if unbundled items are not supposed to be gifted, but the similar bundle items from the Battlepass may be gifted e.g. Bristalback items

### Screenshots

![image](https://user-images.githubusercontent.com/35227010/212759780-3a64c689-61f3-443c-bfa6-ac879363bc02.png)
![image](https://user-images.githubusercontent.com/35227010/212759770-74d8e99d-36f7-44f6-be3f-e737c861b11f.png)

**Comment by shaileshgarg** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/6546

**Comment by shaileshgarg** [comment]
This has been fixed.
