### ISSUE TITLE
Game crashes all the time in 5-10 minutes.

### ISSUE THREAD

**Issue by GooseMooz** [ValveSoftware/Dota2-Gameplay#6687]
### Description

Every time I try to play, the game crashes without error prompts after 5-10 minutes of the match. After I restart the game and reconnect it will crash randomly after some short amount of time. 
I believe I have tried every single solution on the internet and it still doesn't work. I want to find the crash log to find out what causes the game to crash. but I can't. 

My specs are: RTX 3070 Ti, i5-13600K, 32GB RAM

Thank you in advance for your help!

I can provide the games that I've crashed.

### Example Match ID (and possibly Timestamp)

6972290465 (Phoenix), 6972290465 (Sniper), 6972290465 (Primal Beast)

**Comment by GooseMooz** [comment]
I've found my log file and it says that this is the problem:
The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s.
I've run all the tests and my PC is fine, so it's not a RAM/Graphics Card/Processor thing, I believe.

**Comment by bumblebee117** [comment]
Did you find a fix? I have a issue where games running find then it will kick me to desktop but i still have game music and the game mouse… have to force close the game and reopen

**Comment by GooseMooz** [comment]
Yep, I have found a solution, but be aware that your problem differs from mine.
I had to undervolt my processor so it won't drop stacks because Dota and RoR2 were crashing because of this.
