### ISSUE TITLE
Queen of pains aghanim doesn't work

### ISSUE THREAD

**Issue by Bel13ve** [ValveSoftware/Dota2-Gameplay#6691]
### Item name

Aghanim

### Description

Aghanim on qop is supposed to triger scream of pain on and around the enemy when the shadow strike is ending or renewed, how ever it only works if another enemy is near them 

### Example Match ID and Timestamp

6978950107 min 20-21

**Comment by shaileshgarg** [comment]
The Aghanim is supposed to hit only nearby enemies and the not enemy of origin, so in case there are no enemies around it scream is not created.
