### ISSUE TITLE
Post game screen crashes PC.

### ISSUE THREAD

**Issue by 0xsven** [ValveSoftware/Dota2-Gameplay#6707]
### Description

Dota crashes myPC (black screen), which reboots after that.

- It happens irregularly all over the menus of the game
- It never happens in game
- I can reproduce it very reliably on the post game screen (see attached video)

I was trying to find logs. If you could tell me where to find those I will gladly add them.

System: AMD Ryzen 5 3600, AMD Radeon 5700 XT, Windows 10

### Screenshots

https://user-images.githubusercontent.com/973379/213884848-1df1e1de-dc16-4f6f-932e-58cf01a19f97.mp4

**Comment by shaileshgarg** [comment]
https://www.partitionwizard.com/partitionmagic/windows-10-crash-log.html

**Comment by 0xsven** [comment]
closing this. it was my dying graphics card causing the crashes.
