### ISSUE TITLE
Refresher & Octarine rework

### ISSUE THREAD

**Issue by Arenaman** [ValveSoftware/Dota2-Gameplay#6738]
### Description

It would be great to rework the freshener and octarine. It is necessary to create an item that will be crafted from ring of regen, sage's mask and a recipe for 1000 gold. It grants abilities with cooldowns under 10 seconds a 6% cooldown reduction, 10% to abilities with cooldowns between 10 and 30 seconds, and 15% to abilities with cooldowns over 30 seconds. Two such items are combined into a tier 2 item for twice the effect, then combined into a tier 3 item.

**Comment by Ciantb** [comment]
it would be great if you know what this web made for...
