### ISSUE TITLE
Rubick Arcana Bug

### ISSUE THREAD

**Issue by Sforelka** [ValveSoftware/Dota2-Gameplay#6739]
### Cosmetic Item Name

The Magus Chyper

### Description

After you steal an ability the first time, stealing abilities the next times won't change the color of Rubik's cloak

### Example Match ID

works in any match

### Screenshots

![изображение_2023-01-24_210642972](https://user-images.githubusercontent.com/123507786/214397304-8d631e6e-4c7b-4c3f-bd97-365e8198c287.png)

**Comment by Aluerie** [comment]
duplicate #810

Please, close your issue and instead upvote the linked one with 👍 reaction, comment extra details in there if any.
