### ISSUE TITLE
revenant brooch is not affected with spell amp

### ISSUE THREAD

**Issue by MohsenEssa** [ValveSoftware/Dota2-Gameplay#6744]
### Item name

Revenant Brooch

### Description

revenant brooch's witch blade passive not affected with spell amp. and no, there is no chance this is intended behavior as witch blade itself is affected with spell amp items/skills.

### Example Match ID and Timestamp

0

**Comment by Aluerie** [comment]
Can't reproduce. It seem to be affected in my testing:
* one dummy is hit by invoker lvl30 no talents, brooch, KnS
* another dummy is hit by invoker lvl30 no talents, brooch, staff+robi for that +16 int

Math also checks out (within right-click attack damage variance) 
* 255 + 4 * (162+61) * 0.75 * 1.16 = 1031
* 255 + 4 * (162+61) * 0.75 = 924

![image](https://user-images.githubusercontent.com/33165440/214641168-6613c5b3-a664-4b93-8450-5c3e63948fd5.png)

**Comment by MohsenEssa** [comment]
i apologize for wasting your time I didn't test it very accurately and depended on the tooltip when holding alt as it didn't show that it increased.
