### ISSUE TITLE
Ghost Form interaction with Spell Immunity

### ISSUE THREAD

**Issue by Avarise831** [ValveSoftware/Dota2-Gameplay#6745]
### Ability name

Decrepify,Nihilism,

### Description

![123](https://user-images.githubusercontent.com/37029303/214708934-b406ede3-7040-4086-a55d-a769b246258f.png)
![444](https://user-images.githubusercontent.com/37029303/214709203-b21a8beb-a8d1-4c12-9dcc-293b8af54f0b.png)
Ghost scepters flavor text (hold alt) states that effect doesn't work if its used while spell immune and immediately ends if unit becomes spell immune while its active.
But for some reason eblade doesn't have the same flavor text
1 screen if  use ethereal then bkb, ghost form doesn't dispells (All of them are supposed to function like Ghost Scepter and Ghost Shroud get dispelled when avatar bkb activated)
pugna decrepify.nihilism same bug - no dispell ghost form 

![666](https://user-images.githubusercontent.com/37029303/214712895-c2267703-31ec-4201-beea-2aaae41e97ac.png)

Decrepify can be reflected even when Pugna is Spell Immune (if used decrepify while bkb in lotus)

### Example Match ID (and possibly Timestamp)

-

**Comment by shaileshgarg** [comment]
Just to add

Eblade/Decrepify only persist after BKB is used on self/allies, if used on enemy then they BKB it is dispelled.

Only Pugna Decrepify is reflected back to pugna even if pugna has BKB active.
