### ISSUE TITLE
Hero Challenge Drow,Lone Druid  quest

### ISSUE THREAD

**Issue by Avarise831** [ValveSoftware/Dota2-Gameplay#6747]
### Hero and spell

-

### Description

![lonedruid555](https://user-images.githubusercontent.com/37029303/214984248-28e8eea0-a698-4d9a-ab15-cbb64e71319d.png)

does not count the damage of the bear, with main hero very hard to deal so much dmg

![drow1](https://user-images.githubusercontent.com/37029303/214742827-844026f3-dbfa-4e92-9874-431ee56388ca.png)
if frost arrows enabled, damage is not counted (upd only counts with aganim's but the description says nothing) 
Not sure about the other solution but technically Marksmanship doesn't deal damage unless you hit heroes with Agh's secondary arrows.

**Comment by shaileshgarg** [comment]
There are many hero Dota+ weekly Challenges that dont work either to old spell reworked spell, or simply the game not counting it. And there are multiple issue created for such things.

It is possible to create a consolidated issue, we add all details of all such Issues.

**Comment by commentator24** [comment]
i might add omniknight challenge a bit bugged too. 
as long as you healed 24x then buy soul ring before game ends, challenge is complete. this is totally different to buying soul ring first then heal 😄 

lone druid one not that hard actually. i usually just put radiance on hero during true form. or just blademail.

**Comment by shaileshgarg** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/5749, can you add the details in this issue, and close this issue.

**Comment by MariusDoxon** [comment]
> ### Hero and spell
> 
> ### Description
> ![lonedruid555](https://user-images.githubusercontent.com/37029303/214984248-28e8eea0-a698-4d9a-ab15-cbb64e71319d.png)
> 
> does not count the damage of the bear, with main hero very hard to deal so much dmg
> 
> ![drow1](https://user-images.githubusercontent.com/37029303/214742827-844026f3-dbfa-4e92-9874-431ee56388ca.png) if frost arrows enabled, damage is not counted (upd only counts with aganim's but the description says nothing) Not sure about the other solution but technically Marksmanship doesn't deal damage unless you hit heroes with Agh's secondary arrows.
> 
> ### Screenshots
> _No response_

The issue with the "secondary shot of aghanim" is that now that agh was updated (some months ago), the effect doesn't add another shot any longer. Instead it add hypothermia stacks.
