### ISSUE TITLE
Axe's culling blade not killing ursa below threshold

### ISSUE THREAD

**Issue by lindjacob** [ValveSoftware/Dota2-Gameplay#6762]
I played axe today in a match with the ID:
6989933142
 
At minute 44:40

The culling blade takes Ursa from 359 HP to 1.
Which is way below the threshold at 600 HP.
Ursa is not enraged but has "shallow grave" on.

So I'm not sure what creates the interaction.

Let me know if you receive the report.
I hope you will let me know if it indeed is a bug.
I just cannot see any other explanation for it.

**Comment by Aluerie** [comment]
You have checked combat log. Just a situation where everything happens too fast. Culling Blade brought Ursa from 654 HP to 54 HP.
![image](https://user-images.githubusercontent.com/33165440/215210351-0d663488-c071-491e-84cd-b1571b3f90b5.png)

Since there is no bug in here, please close your issue.
