### ISSUE TITLE
Some of my items have disappeared.

### ISSUE THREAD

**Issue by SHITZOR** [ValveSoftware/Dota2-Gameplay#6769]
### Description

I don't know if this is a bug or not but all the items I bought in Dota 2, half or a quarter of them have gone missing. I don't know where all the items go. As soon I click play Dota 2 and got into the game menu I received some items. But some of them are duplicated, I got 3 of the same loading screens on death prophet, 3 shurikens on bounty hunter, 4 the same wings on outworld devourer, and another 2 with the same loading screen on bounty hunter. I lost some immortal items such as from Huskar, Anti Mage, Chaos Knight, Timbersaw, Nightstalker, Lifestealer, and some other heroes that I haven't checked but I'm pretty sure I lost some of them. What the hell is happening? Where are all the items that I bought? They're all gone! What is this valve? Fix this!

**Comment by shaileshgarg** [comment]
Check marketplace history if items were sold. Sometimes dota does have loading issues where cosmetics don't show in the client.

**Comment by SHITZOR** [comment]
They were not sold at all when I check marketplace, it didn't show my immortals were sold, it just shows that I bought some items from a player even I haven't bought any items since Oct 11.

**Comment by SHITZOR** [comment]
This the player I bought items today at Jan 28. https://steamcommunity.com/profiles/76561199175373929 , let me explain this. I haven't bought any items from this guy, yet I bought items from him in which I haven't played dota 2, my last play was January 25, 2023, I played once and then decide to play other games because I got bored fast then I played again today at Jan 28, 2023. And it says I bought 47 items. I accept all, I check I got more duplicated bought items from a player in which I didn't go market buying yet. And now all the other items that I bought is gone. It turned to these duplicated items.

**Comment by shaileshgarg** [comment]
Maybe someone got access to your account, if you didn't bought items but someone did.

Change your password, try Steam Support in recovering your items. This is really not the right place for it.

**Comment by SHITZOR** [comment]
I checked my market history, my immortals... it didn't show that they were sold at all instead I think they turned into these items that I bought from the player.

**Comment by SHITZOR** [comment]
I check my trade history. No trades.

**Comment by SHITZOR** [comment]
I check my email preference. It was an email that wasn't mine at all.

**Comment by TheUnholyWrath** [comment]
Nothing will come of posting about this on here. The devs did not create the bug tracker for this purpose, this post will just be ignored. Please close this issue and go talk to Steam Support, this is a Steam problem not a Dota problem

**Comment by SHITZOR** [comment]
Wait uhhhh... how do you close it?

**Comment by TheUnholyWrath** [comment]
Next to the Comment button there should be a button that says Close Issue
