### ISSUE TITLE
BUG UNLOCKED IMMORTAL SPELL EFFECTS

### ISSUE THREAD

**Issue by WhoAmI247** [ValveSoftware/Dota2-Gameplay#6771]
### Description

I can't change effects immortal with normal item.
Here is my ID steam: 158881210

### Screenshots

https://user-images.githubusercontent.com/22971334/215263693-bcf6df20-cd1f-4b36-8760-842bfee61a76.mp4

**Comment by shaileshgarg** [comment]
![20230128170216_1](https://user-images.githubusercontent.com/26450759/215264230-9d9212b7-9d2d-4db7-be6c-1f2d71d9ffee.jpg)

Works fine.

While in Demo, Go Back to Hero Page and Apply it again and Return to Demo.

**Comment by WhoAmI247** [comment]
I just try many time and also restart steam and dota. But it still have
issues

**Comment by shaileshgarg** [comment]
https://user-images.githubusercontent.com/26450759/215268417-3a562ab0-f52f-4665-9cc6-822f4e275283.mp4

This is only a Demo issue.

**Comment by WhoAmI247** [comment]
I just try in game it normal but in demo still has issues

**Comment by shaileshgarg** [comment]
Yeah, in Demo the spells effects don't load properly.

You can close this issue, as the problem only exists in Demo.
