### ISSUE TITLE
НАСМЕШКИ С НАБОРОВ НЕ ПЕРЕДАЮТСЯ ПОДАРКОВ!!!?

### ISSUE THREAD

**Issue by Hackers59551** [ValveSoftware/Dota2-Gameplay#6776]
### Description

Возникла проблема с передачей насмешки с Комплект The Strings of Suradan на Hoodwink(Насмешка: In It for the Lute), не имеется кнопки завернуть в подарок только у насмешки, а иммортал предмет из этого комплекта передаётся,(у того и другого в свойствах написано что Этот предмет можно подарить один раз, хотелось бы чтобы исправили такую проблему. Я хотел подарить комплект своему другу, перед этим распробовав его, но разочаровался когда увидел что не могу насмешку передать, в то время как иммортал могу. По моему мнению на всех комплектах у которых есть насмешки такая же проблеме присутствует, я не открываю комплект Bloodfeather Finery боясь что насмешку тоже нельзя будет передавать, а имморталка без насмешки уже не то.
![Снимок экрана 2023-01-29 001544](https://user-images.githubusercontent.com/123834581/215286914-4e5e3a43-2990-4ff3-84aa-8e0f81f2b191.png)
![Снимок экрана 2023-01-29 002338](https://user-images.githubusercontent.com/123834581/215287138-b9bb5918-c73e-4929-8481-58609ee32fd5.png)
![Снимок экрана 2023-01-29 002523](https://user-images.githubusercontent.com/123834581/215287140-b014b1e8-3d45-4a53-8f33-8eb519c127b8.png)
Спасибо что уделили время!

**Comment by Aluerie** [comment]
Duplicate #2945

also this is an English speaking repository
---
Please, close your issue and instead upvote the original one with "👍" reaction. Comment extra details if any.

And in future, first, use search to find out if the bug you want to report was already submitted by somebody else so you can upvote it and not clutter the repository with duplicates.

**Comment by shaileshgarg** [comment]
This has been fixed.
