### ISSUE TITLE
(FIXED in 732e) Jinada & Geminate Attack are castable while Silenced, but not during Break

### ISSUE THREAD

**Issue by TheZett** [ValveSoftware/Dota2-Gameplay#6779]
### Ability names

Jinada, Geminate Attack

---

### Summary

**Current behaviour:** Jinada and Geminate Attack are auto-castable while silenced, but fully disabled by Break.

**Intended behaviour:** Jinada and Geminate Attack should not be castable while silenced, and have no interaction with Break.

*Jinada and Geminate Attack should behave like Tidebringer: Ignore Break, but not be castable while silenced.*

**Video (Jinada):** https://www.youtube.com/watch?v=gUhZARJE6yo

**Video (Geminate):** https://www.youtube.com/watch?v=QLaYeLDt_d4

---

### Full Description

Bounty Hunter's Jinada and Weaver's Geminate Attack spells are supposed to function like all other active attack modifiers ("orb effect") spells, as in they can be manually used without drawing creep aggro or they can be set to auto-cast to automatically use them when ordering a regular attack.

But currently Jinada and Geminate Attack have two issues that are unique to them, which is that the spells' auto-cast behaviour is currently bugged.

Even if Bounty Hunter is silenced, he can still use Jinada if its auto-cast is enabled.
Additionally, If Bounty Hunter is affected by Break, Jinada cannot be used at all.

As Jinada is now an active attack modifier spell, it should fully ignore the Break effect and fully obey the silence effect instead.

The exact same issue applies to Weaver's Geminate Attack spell.

---

The bug exists because both spells used to be passive spells that got improperly turned into active attack modifier spells.

As a comparison, Kunkka's Tidebringer used to be a passive spell and got turned into an active attack modifier.
Tidebringer is currently not usable while silenced (auto-cast on or off doesnt matter), but Tidebringer fully ignores the Break effect, as it is NOT a passive ability anymore.

---

### Example Match ID (and possibly Timestamp)

*two videos are provided above*

**Comment by commentator24** [comment]
what about Treant shard nature guise? the shard skill still active when treant is under break or silence effect. treant still invis and still can root on next attack

**Comment by Homilos** [comment]
When developing software or a finished product, it is worth paying detailed attention to usability testing in order to evaluate your product. For this reason I prefer 123 because they can provide an excellent opportunity to test your product and make it fit your expectations. I think it's perfect for such cases as a sign of the quality of your work.

**Comment by TheZett** [comment]
> what about Treant shard nature guise? the shard skill still active when treant is under break or silence effect. treant still invis and still can root on next attack

The issue I posted deals with active spells being castable despite being silenced, something that shouldnt be a thing.

---

Your Treant issue is effectively "why is his innate passive not breakable", which applies to a few other passive spell components as well (intentional ones e.g. Tiny ult, WK ult, etc) and some other spell components are also not breakable, likely unintentional though (MK Aghs, Wisp Aghs, etc).

**Comment by mastercoms** [comment]
Wasn't this auto-cast stuff added as a QoL change and not intended to change them from passives to spells?

**Comment by shaileshgarg** [comment]
This was in this 7.32e

**Comment by TheZett** [comment]
> Wasn't this auto-cast stuff added as a QoL change and not intended to change them from passives to spells? I guess it's nice for consistency's sake but feel like this is a balance change as well.

No, then they would have turned them into a Toggle, as those are affected by Break.

Since they made them an auto-cast spell, it HAS to respect silences and ignore breaks.

Valve fixed this bug in 7.32e, as shaileshgarg mention above, so this was a correct bug report.

**Comment by shaileshgarg** [comment]
We can close this then.

**Comment by mastercoms** [comment]
In my view, it was an implementation detail, I thought maybe the full context wasn't considered for the change.

**Comment by mastercoms** [comment]
7.33:
Geminate Attack
No longer disabled by silences. Instead disabled by break
