### ISSUE TITLE
incorrect tooltip for revenant brooch and mkb 

### ISSUE THREAD

**Issue by MohsenEssa** [ValveSoftware/Dota2-Gameplay#6784]
### Hero and spell

all heroes - mkb and revenant brooch

### Description

pressing alt while having spell amp shows increased damage for mkb while it doesn't.
and the other way around for revenant brooch as it it increases its passive (which blade damage) but tooltip doesn't show it.
 edit: same for radi alt doesn't show increased damage with spell amp holding alt

### Screenshots

![image](https://user-images.githubusercontent.com/56043652/215328018-2aac1f0e-661a-43f5-aee3-c37e4527c897.png)
![image](https://user-images.githubusercontent.com/56043652/215328041-e6a57648-2950-4eca-90cd-8d02a1b6949b.png)!

**Comment by shaileshgarg** [comment]
But what should the correct behavior be, should MKB deal the bonus damage or Revenent Brooch/Witch Blade shouldn't.

**Comment by MohsenEssa** [comment]
@shaileshgarg i believe they are behaving correctly just a tooltip bug

**Comment by shaileshgarg** [comment]
MKB tooltip says it does extra damage due to Spell Amp, but it doesn't.

Revenent Brooch/Witch Blade Passive says it doesn't, but it does extra damage.

What I am saying it they be consistent, either both items are affected or neither item is affected.
