### ISSUE TITLE
Insatiable Hunger

### ISSUE THREAD

**Issue by Avarise831** [ValveSoftware/Dota2-Gameplay#6788]
### Ability name

Insatiable Hunger

### Description

Insatiable Hunger broodmother
for some reason  lifesteal work when Templar Assassin has Refraction

### Example Match ID (and possibly Timestamp)

-

**Comment by shaileshgarg** [comment]
Satanic and other sources of Lifesteal also work. 

TA refraction does damage negation, in this the damage is still registered on the target but it does no damage to the target. But as the damage is registered, any effect like Lifesteal work.


This is not a bug, working as intended.
