### ISSUE TITLE
nemestice 2021 immortal treasure does not contain "Hidden Vector" at descriptions 

### ISSUE THREAD

**Issue by 1Crow98** [ValveSoftware/Dota2-Gameplay#6794]
### Cosmetic Item Name

Hidden vector void spirit immortal set

### Description

cant get hidden vector set
already at 1:9 odd 
feel sad man :/

### Example Match ID

there no 

### Screenshots

![error](https://user-images.githubusercontent.com/123910748/215365668-975daf98-b0e5-4a4c-9bfd-240cff985569.png)

**Comment by shaileshgarg** [comment]
The treasure still has the item though.

Not worth fixing.
