### ISSUE TITLE
Check this out : Description inside

### ISSUE THREAD

**Issue by SuperGeorge2002** [ValveSoftware/Dota2-Gameplay#6799]
### Cosmetic Item Name

All taunts 2020battlepass 

### Description

Я не могу продать предметы после The itenrational - это КОШМАР! Даже не все предметы отображаются в разделе "продать"
Проблему не можете решить по сей день . На заявки не отвечаете , а поддержка-steam мусолит - мусолит что-то невнятное и непонятное - что лично я не могу разобрать , а на вопросы не отвечаете . 
Давайте! Работаем! Жду уже 2-3 месяца  То , что Вы бездельники я уже понял . 
Я молчу по поводу того , что за целых 3 года не могу получить  награду CMD за 1000lvl . Ее так и не отправили с учетом того , что я не живу в россии.
Еще чуть-чуть и мое терпение лопнет и я махну ручкой valve и dota2 .

### Example Match ID

none

### Screenshots

![Снимок экрана 2023-01-30 115832](https://user-images.githubusercontent.com/118093370/215434556-b431f4e0-5b2a-4459-8ee5-ac5617180b42.jpg)
![Снимок экрана 2023-01-30 121132](https://user-images.githubusercontent.com/118093370/215434841-d34e6ee3-579a-4ad9-af46-fcfa435a8f8e.jpg)
![Снимок экрана 2023-01-30 121119](https://user-images.githubusercontent.com/118093370/215434847-d1ab6000-6270-46ed-b4f3-23e6497904de.jpg)
![Снимок экрана 2023-01-30 121055](https://user-images.githubusercontent.com/118093370/215434850-ceb709e4-665c-4279-8b7e-eedb4efb56bb.jpg)
![Снимок экрана 2023-01-30 121042](https://user-images.githubusercontent.com/118093370/215434852-58cf420a-2dc1-43bb-844b-f8360be893f0.jpg)

**Comment by Avarise831** [comment]
#5284
