### ISSUE TITLE
devour issue

### ISSUE THREAD

**Issue by chicharap** [ValveSoftware/Dota2-Gameplay#6809]
### Ability name

Devour

### Description

no skill acquired after devouring neutral creeps the whole game. 

### Example Match ID (and possibly Timestamp)

6995446738

**Comment by Aluerie** [comment]
does this solve your issue?
![image](https://user-images.githubusercontent.com/33165440/215778965-f2015e27-56f9-49c6-bd5c-972b2b4b2d88.png)
if yes, then, **please**, close it.
