### ISSUE TITLE
Primal Beast Ult Pulverize doesn't channel fully

### ISSUE THREAD

**Issue by cinderisles** [ValveSoftware/Dota2-Gameplay#6815]
### Ability name

Pulverize

### Description

Today's update broke Primal Beast's Pulverize. It will only hit one time and then cancel itself. 

### Example Match ID (and possibly Timestamp)

6996347773

**Comment by trstnt** [comment]
Imagine just playing a game and realising ur hero doesn't work properly KEKW
I don't have to imagine.

**Comment by DAIMELDMR** [comment]
Its really annoying my team keep telling me i was moving, i have primal enough to know there was bug , hope valve fix this asap

**Comment by OmegaAce** [comment]
I also experienced this issue today.
Match ID: 6996384023

**Comment by eboug92** [comment]
https://www.reddit.com/r/DotA2/comments/10qh653/primal_beasts_ult_pulverize_is_now_broken_and/

**Comment by ShadLiwanan** [comment]
Can confirm, this also happened to me earlier. Lost a 7 win streak spamming Primal Beast because of this.

**Comment by smmarius** [comment]
We should have an option to label such bugs because this is way too important

**Comment by shenzhiguo** [comment]
I also experienced this issue today.
Match ID:6996890658

**Comment by berithpy** [comment]
can confirm

**Comment by Irvin6969** [comment]
same thing happened to me, match id: 6996718664

**Comment by Dota-Exp** [comment]
Issue has been fixed. Thank you.
