### ISSUE TITLE
Primal Beast Ult

### ISSUE THREAD

**Issue by dionisiodominic** [ValveSoftware/Dota2-Gameplay#6820]
### Ability name

Pulverize

### Description

His ult only slam once. 

### Example Match ID (and possibly Timestamp)

6996727259

**Comment by shaileshgarg** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/6815

**Comment by Momon018** [comment]
Primal ult only once the hell is happening Gaben

**Comment by Dota-Exp** [comment]
Fix is live. Thank you
