### ISSUE TITLE
獸在试玩模式使用捶时，只会敲击一下地面就停止技能释放了

### ISSUE THREAD

**Issue by lengyueshaxing** [ValveSoftware/Dota2-Gameplay#6821]
### Ability name

捶

### Description

獸在试玩模式使用捶时，只会敲击一下地面就停止技能释放了

### Example Match ID (and possibly Timestamp)

。

**Comment by TheUnholyWrath** [comment]
#6815 This is a duplicate, please close this issue now

**Comment by shenzhiguo** [comment]
**这不是重复粘贴的问题，请官方注意**
Ability name
捶

Description
獸在游戏比赛中，捶技能只会敲击一下地面就停止技能释放了，在试玩模式中也是如此。

Example Match ID (and possibly Timestamp)
比赛ID：6996890658

出现问题时间是在2023/02/01的更新之后出现的。
