### ISSUE TITLE
Unable to watch friends' games live as a Dota Plus subscriber

### ISSUE THREAD

**Issue by Memicchu** [ValveSoftware/Dota2-Gameplay#6824]
### Description

No matter what I do, despite being subscribed to Dota Plus, the option to watch my friend's game live just isnt there

### Screenshots

![image](https://user-images.githubusercontent.com/124171468/216070803-9054d6bf-a56c-4a90-8fc4-08f6524ea6c8.png)

![image](https://user-images.githubusercontent.com/124171468/216070895-056dc30c-890e-4524-b9ed-6bbead06819e.png)

**Comment by Avarise831** [comment]
I don't remember exactly but you need to be friends for 2 weeks+

**Comment by Memicchu** [comment]
There's a "go live" option when you click "Watch game". That solved everything.
