### ISSUE TITLE
Primal Beast Pulverize auto cancels channeling.

### ISSUE THREAD

**Issue by Gnawkout** [ValveSoftware/Dota2-Gameplay#6826]
### Ability name

Pulverize

### Description

Pulverize cancels itself after 1 slam without any cancelling by self and opponent. Tested on demo mode, also cancels channeling on itself after 1 slam. did not channel for full 2.3 secs duration

### Example Match ID (and possibly Timestamp)

6997048942

**Comment by Avarise831** [comment]
#6815

**Comment by anhaaka** [comment]
its happened to me too

**Comment by anhaaka** [comment]
Match ID 6997055341

**Comment by storfucker** [comment]
Another one Match ID: 6997149640

**Comment by Mghawd** [comment]
Match ID: 6997208119

**Comment by boogie-woogiee** [comment]
Another match id : 6997252890

**Comment by GenAmnesia** [comment]
Match ID: 6997583325

**Comment by kuborek2** [comment]
Match ID: 6997598466

**Comment by Dota-Exp** [comment]
Fix is live. Thank you.
