### ISSUE TITLE
Primal Beast's Ulti

### ISSUE THREAD

**Issue by egulhan** [ValveSoftware/Dota2-Gameplay#6833]
### Ability name

Pulverize

### Description

hi. his ulti pulverize always hit the enemy to ground only once whenever I used it during the match today. I think it's broken now.
I also tried him on demo and the result is the same.

Version: 5,601
Gameplay Version: 7.32D

### Example Match ID (and possibly Timestamp)

6997623899

**Comment by irismus** [comment]
The game should have an update. 5602 should be available, close this issue if it's fixed.

**Comment by yckmm** [comment]
#6815
It's fixed. Please close and use the search before opening new issues.

**Comment by egulhan** [comment]
i've just tried it out. yes, it's fixed! thanks!
