### ISSUE TITLE
Sunfire Ethereal Gem

### ISSUE THREAD

**Issue by accelsynchro** [ValveSoftware/Dota2-Gameplay#6843]
### Cosmetic Item Name

Unusual Mango the Newt

### Description

Hi, I have an unusual mango the newt with sunfire ethereal gem and miasmatic grey prismatic gem but it is not showing as what i have seen in youtube videos. Anybody knows what the problem is and how to fix them. Thank you.

### Example Match ID

6997882204

### Screenshots

![Capture1](https://user-images.githubusercontent.com/124331171/216510739-04731ee4-d696-411f-b559-2384ef4a0e2f.JPG)
![Capture2](https://user-images.githubusercontent.com/124331171/216510747-013ea270-d333-4104-874d-414f7c585cd9.JPG)

**Comment by shaileshgarg** [comment]
Hmm, try changing Video Setting to Max and see if it works.

**Comment by accelsynchro** [comment]
> Hmm, try changing Video Setting to Max and see if it works.

Hi, I did try but still no effects.
![Capture3](https://user-images.githubusercontent.com/124331171/216524718-2c7eed69-92f3-4277-aa34-9665df67202a.JPG)
![Capture4](https://user-images.githubusercontent.com/124331171/216524721-746e54ef-d92c-4231-8a13-702ed44654d5.JPG)
