### ISSUE TITLE
Troll warlord aghs cannot dispel euls nor windwaker active

### ISSUE THREAD

**Issue by coolguy38** [ValveSoftware/Dota2-Gameplay#6848]
### Ability name

Whirling Axes (ranged)

### Description

Whirling Axes (ranged) with the scepter upgrade, adds a basic dispel against enemies. Despite this, Whirling Axes (ranged) does not dispel an enemy which has the euls or windwaker buff.

### Example Match ID (and possibly Timestamp)

7000372289 - 23:26

**Comment by shaileshgarg** [comment]
This is intended, during Euls target are invulnerable so they can are not affected by the whirling axes

**Comment by coolguy38** [comment]
> This is intended, during Euls target are invulnerable so they can are not affected by the whirling axes

But nullifier works on enemies that are eul'ed. What's the difference?

**Comment by shaileshgarg** [comment]
So, in general Invulnerable targets cannot be targetted, but Nullifier is the one item which can be, that is the purpose it was created for.

Other similar items, Witch Bane also cannot target euled target.

**Comment by coolguy38** [comment]
> So, in general Invulnerable targets cannot be targetted, but Nullifier is the one item which can be, that is the purpose it was created for.
> 
> Other similar items, Witch Bane also cannot target euled target.

Oracle q works on eul'ed targets.

**Comment by shaileshgarg** [comment]
As I said very few abilities and items can be used on invulnerable target. Troll sceptre is not one of them.

Please close the issue

**Comment by Aluerie** [comment]
🤔 
* Sven Q with aghs
* Brewmaster blue panda Q 
* Satyr trickster (the smallest one)

**Comment by Aluerie** [comment]
>  but sven Q cannot target invulnerable units.

I'm sorry, but it can 

https://user-images.githubusercontent.com/33165440/217095007-2436c710-ba60-43e1-b2ec-8f17c48881fa.mp4

**Comment by yckmm** [comment]
The purge from the blue necronomicon unit (from book of the dead T5 neutral) can remove eul's as well.
