### ISSUE TITLE
Draw Arcana bug with back immortal item silent wake

### ISSUE THREAD

**Issue by Bhavin1996** [ValveSoftware/Dota2-Gameplay#6856]
### Cosmetic Item Name

Silent wake

### Description

On draw arcana the back immortal of draw is not getting applied, only the feather is shown instead of entire cape. But when I put that on non-arcana it works perfectly.  This issue I have found when trying all combination in it's loadout.

### Example Match ID

NA

### Screenshots

![Dota 2 04-02-2023 11_54_47](https://user-images.githubusercontent.com/29658973/216752849-0d7a51a9-40e1-48f9-9c91-c96465fcce8e.png)
![Dota 2 04-02-2023 11_54_36](https://user-images.githubusercontent.com/29658973/216752850-5ee87872-1f41-41d8-ad1a-8c200cc7d23e.png)

**Comment by Bhavin1996** [comment]
In screenshots it's clearly visible how this item is not showing properly on arcana. This applied to all back immortal.

**Comment by TheUnholyWrath** [comment]
is this the same issue as #29 ?

**Comment by Aluerie** [comment]
yes, it is duplicate #29 

---
Please, close your issue and instead upvote the original one with "👍" reaction. Comment extra details if any.

And in future, first, use search to find out if the bug you want to report was already submitted by somebody else so you can upvote it and not clutter the repository with duplicates.

**Comment by Bhavin1996** [comment]
sure
