### ISSUE TITLE
snowball + lotus

### ISSUE THREAD

**Issue by Avarise831** [ValveSoftware/Dota2-Gameplay#6860]
### Ability name

Snowball

### Description

Sk or sf used ulty inside snowball bug or feature?
Sf
https://user-images.githubusercontent.com/37029303/216765892-54c20370-efd5-4b00-8e19-1024003bd0b9.mp4

Sk
https://user-images.githubusercontent.com/37029303/216765927-c249197a-4732-4b13-bdda-d7b16be628bd.mp4

### Example Match ID (and possibly Timestamp)

-

**Comment by Arabish** [comment]
100 mmr question

**Comment by TheZett** [comment]
The caster of Snowball is not silenced or fully disabled, only muted.

This means the caster of Snowball can use other spells from within Snowball.

Reflecting a spell via Lotus Orb effectively makes you the caster of the reflected spell, hence SK being able to use his ult while casting his own Snowball.
