### ISSUE TITLE
Backdoor protection not activated

### ISSUE THREAD

**Issue by hongminzhu** [ValveSoftware/Dota2-Gameplay#6871]
### Description

Right before the end of the game, backdoor protection was disabled for the dire ancient.
It should of been enabled as there were no radiant creeps at all.

### Example Match ID (and possibly Timestamp)

7002866133

**Comment by commentator24** [comment]
creeps do not have to be near throne to disable backdoor protection.
once creeps step on circular logo outside base on any lanes, backdoor is off until you kill it + 15 sec after that. hence enemy fortify.

![image](https://user-images.githubusercontent.com/109324155/216820555-388193db-16c4-480d-af13-70e65d765c01.png)
u can close the issue

**Comment by commentator24** [comment]
here u can see backdoor still on at 62:00 but off 1 sec after that 62:01
![image](https://user-images.githubusercontent.com/109324155/216821131-895ad221-06c7-4f75-91f2-9a92c121293f.png)

**Comment by commentator24** [comment]
unfortunately i think you shouldve cleared the wave first to maintain bd protection before capturing outpost. creeps cant defend mega. Almost comeback though wp
![image](https://user-images.githubusercontent.com/109324155/216821352-e172d9d7-0a1f-4657-b75b-573fc01cf892.png)

**Comment by hongminzhu** [comment]
I see! Thanks @commentator24 for the explanation. I always thought it was HG that acted as the trigger, did not know about the circle.

**Comment by commentator24** [comment]
dont forget to close the issue
