### ISSUE TITLE
#6087 - no one is even going to answer this request?

### ISSUE THREAD

**Issue by IIaBeJl96** [ValveSoftware/Dota2-Gameplay#6872]
### Description

It's been 2 months already, but no one even mentioned in this thread.
https://github.com/ValveSoftware/Dota2-Gameplay/issues/6087

**Comment by Aluerie** [comment]
Don't spam the repository with non-issues. Please, close this post. 

---
> been 2 months already

this is not how *this* bug tracker works. Just read the description of this repository:

"""the goal of this tracker is to provide a sorted list of high value tasks that devs can pick up to improve the game. The tracker collects a very large number of open issues and by having the community vote to rank the issues, we generate a sorted list. When a dev looks at the sorted list they can pick up work that suits their skillset and the block of time they've got free."""

There is no weekly quota "X bugs/week"; no deadline-promise to fix/answer all issues after X months. It is just a list of tasks for them to do *while they aren't busy and if they like.* Likelihood of "like" generally correlates with upvotes and importance.  

So again, please, close this issue and learn some github etiquette.

**Comment by IIaBeJl96** [comment]
This list doesn't move! Or was my problem ignored:?
