### ISSUE TITLE
Shiva's Guard Arctic Blast visual doesn't travel till edge of AOE.

### ISSUE THREAD

**Issue by shaileshgarg** [ValveSoftware/Dota2-Gameplay#6876]
### Item name

Shiva Guard

### Description

https://user-images.githubusercontent.com/26450759/216838239-99000546-3363-46a5-9aaa-ac26e42ad689.mp4

Shiva's Guard Arctic Blast ground indicator (The C shaped thing on the Ground) doesn't reach till end of AOE but hit the enemies at the edge.

The actual VFX it also not very clear like it used to.
https://www.youtube.com/watch?v=V3S86eYfiL0

### Example Match ID and Timestamp

-

**Comment by Aluerie** [comment]
this was just fixed

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/33165440/dc46ee88-4e42-4880-81b6-5b0b1608298f)

**Comment by kostakis** [comment]
Hi @shaileshgarg indeed the issue was fixed so close please close the issue,

**Comment by Aluerie** [comment]
Erm, a few reddit comments say that there is still something wrong compared to the OG fx, but don't say what and l'm not sure what they mean lol.

**Comment by shaileshgarg** [comment]
The ground effects looks better. The reddit comments are referring to the growing bubble, previously that was also very clear.
