### ISSUE TITLE
QOL: Underlord's Fiend's Gate should have a selfcast (double tap) behaviour.

### ISSUE THREAD

**Issue by anonymo0se** [ValveSoftware/Dota2-Gameplay#688]
### Description

I made this request as a post in #47 and jeff told me to submit it as a separate issue.

I think Underlord's ultimate should have a double tap behaviour similar to what his old ultimate (Dark Rift) had. Dark Rift's double tap behaviour was to cast it on the fountain as it was a building-target ability. Fiend's Gate should turn the hero towards the fountain and cast it right at the fountain's entrance (It's not possible to cast Fiend's Gate inside the fountain).

### Screenshots

![image](https://user-images.githubusercontent.com/53087065/172429827-0fe01012-b74c-4add-8111-d18dcc629765.png)

**Comment by moonrobin** [comment]
Would make this consistent with NP's and IO's global TP skills, which both teleport to base upon double tap. Please add this in!

**Comment by Dota-Exp** [comment]
Will be added in one of the upcoming updates. Thank you.
