### ISSUE TITLE
Guild challenges don't work in ability draft

### ISSUE THREAD

**Issue by chuckloveall** [ValveSoftware/Dota2-Gameplay#6884]
### Description

Guild challenges where more than 3 people are required to fulfill the challenge (weekly) do not trigger in ability draft. Guild challenges only work in normal all pick, etc. 

### Example Match ID (and possibly Timestamp)

n.a

**Comment by TheUnholyWrath** [comment]
#26 Please close this issue

**Comment by chuckloveall** [comment]
Closing as a duplicate. See [#26](https://github.com/ValveSoftware/Dota2-Gameplay/issues/26)
