### ISSUE TITLE
Warlock Golem doesnt use any responses

### ISSUE THREAD

**Issue by Foto-raptor** [ValveSoftware/Dota2-Gameplay#689]
### Description

Warlock Golem doesnt talk at all, though hes the only controlled unit with hes [own responses](https://dota2.fandom.com/wiki/Warlock_Golem/Responses) in the game. This bug probably appear after switching into source 2 engine.

**Comment by LiamWinterton** [comment]
I've definitely heard the death animations as I play warlock semi frequently. It's really sad when he dies and he makes comments on how he served his master :(

I don't to my memory recall hearing move command responses or attack responses so it might be trigger limited rather than a blanket "does not work"

**Comment by Daar543** [comment]
Another Warlock sound bug (happens for me in bot games, but probably in normal too): You can hear his "normal" voicelienes, which should be heard to controlling player only ("Your soul to crush", "Shadows encircle you") - at least is case for the other heroes.

**Comment by Foto-raptor** [comment]
> I've definitely heard the death animations as I play warlock semi frequently. It's really sad when he dies and he makes comments on how he served his master :(
> 
> I don't to my memory recall hearing move command responses or attack responses so it might be trigger limited rather than a blanket "does not work"

Yeah, he only talks when he die. Other then that hes muted. And it used to work 100% some time ago, probably in source 1.

**Comment by Liam-NFLD** [comment]
I would love to hear Golem regain it's voice.

**Comment by jeffhill** [comment]
I've checked in a fix for this but it won't ship for a little bit. I'm closing the issue so we know it's marked as "fixed".

Thanks for the bug report!
