### ISSUE TITLE
VConsole2 mojibake

### ISSUE THREAD

**Issue by laper32** [ValveSoftware/Dota2-Gameplay#6906]
### Description

VConsole2 should use icuuc/icui18n to make sure that character set can be converted each other(here, GBK/UTF8).
> The system language is schinese what is using GB2312, but it's possible that other character set will occur the same issue.

### Screenshots

![image](https://user-images.githubusercontent.com/44300879/217490533-00db8f91-22b5-4002-b3ec-104674159499.png)

**Comment by Aliceuri** [comment]
oh , got it [fm](https://www.gbwhatsapp.download/)
