### ISSUE TITLE
DOTA DEVELOPERS OVER PAID CUNTS

### ISSUE THREAD

**Issue by G188888** [ValveSoftware/Dota2-Gameplay#6908]
### Description

FUCK DOTA MATCHMAKING AND FUCKIGN THOSE USELESS CUNTS AT VALVE YOU CUNT NEED TO FUCK OFF INCOMPETENT CUNTS

**Comment by zeroedout** [comment]
Thanks, DotA devs. Ignore jerks like this guy. Extremely well-maintained, designed, and iterated game over many years and maintaining + improving Linux compatibility. I swear some of these people have never played other games from less capable devs before.
