### ISSUE TITLE
SURRENDER BUTTON

### ISSUE THREAD

**Issue by johncalesp** [ValveSoftware/Dota2-Gameplay#6915]
PLEASE PLEASE PLEASE,
Implement a surrender button so we don't have to waste 30 min in a game that is going anywhere, maybe a voting system or something like that.

**Comment by Aluerie** [comment]
Duplicate #356

---
Please, close your issue and instead upvote the original one with "👍" reaction. Comment extra details if any.

And in future, first, use search to find out if the bug you want to report was already submitted by somebody else so you can upvote it and not clutter the repository with duplicates.
