### ISSUE TITLE
There are changes that didn't get into the game though were stated in the patchnote (7.34b still work)

### ISSUE THREAD

**Issue by Avarise831** [ValveSoftware/Dota2-Gameplay#6932]
### Ability name

-

### Description

-  6.69 patch it's been a long time I'm afraid that other problems will also be ignored for a long time it would be great to fix until there is a new patch
#2764

- #1002
- #1767
- #3479 tooltip outdated
- #5592
- #5594
- #5593

### Example Match ID (and possibly Timestamp)

-

**Comment by shaileshgarg** [comment]
Hmm, don't get the point of this issue, the individual items already have issues open, and they are not even related, so a compilation issue is also not relevent.
