### ISSUE TITLE
Taunt unable to gift 

### ISSUE THREAD

**Issue by aminlionnaire** [ValveSoftware/Dota2-Gameplay#6956]
![0134380F-7AEB-4C03-8A2E-C3042CAFB092](https://user-images.githubusercontent.com/125389082/218802370-e411611b-689d-41cb-bf33-e7ab8d31c183.png)

As you can see, as an example, it shows that it is giftable. However, there’s no gift wrap option. Thank you in advance.

**Comment by shaileshgarg** [comment]
No 2022 battle pass Taunt is giftable currently.

But no previous Taunt from Nemestice, Aghanim or 2020 battle pass are giftable though. But they don't have this (Gifted Once) in there item description.

Probably a description issue, than a not giftable issue.

**Comment by aminlionnaire** [comment]
> 

I kinda figured but now I get some closure. Thank you!

**Comment by shaileshgarg** [comment]
You can close the issue
