### ISSUE TITLE
Low Priority don't work

### ISSUE THREAD

**Issue by P4rdal** [ValveSoftware/Dota2-Gameplay#6976]
### Description

I can't find games in low priority i set only Single Draft but don't work.

### Screenshots

![20230216171631_1](https://user-images.githubusercontent.com/2516862/219477994-50e6acbf-4b21-4a64-a29c-2b44437a5ebd.jpg)

![20230216171636_1](https://user-images.githubusercontent.com/2516862/219478056-03f9490b-5369-42c1-9b5a-4031568d7121.jpg)

**Comment by LokeLok** [comment]
You need to tick off the All Pick, then it will work.

**Comment by P4rdal** [comment]
Thanks
