### ISSUE TITLE
Nullifier effect immediately disappear upon hitting offensively cycloned opponent

### ISSUE THREAD

**Issue by deanrih** [ValveSoftware/Dota2-Gameplay#6980]
### Item name

Nullifier

### Description

When you cast Nullifier to an opponent and that opponent is under offensive cyclone effect, the Nullifier debuff will disappear immediately upon impact.

Offensively means the effect is coming from the opposite team, let's say Radiant's Hero casting Eul on Dire's Hero.

It doesn't matter if the cyclone is coming from the teammate of the Nullifier wielder or from the same hero as the Nullifier wielder, as long as it is an offensive cyclone, the Nullifier will disappear immediately upon impact.

Additional note or rather, a question, is it intended mechanic or not?

Personally, this feels unintuitive, when you can offensively cyclone an enemy affected by Nullifier and the effect still persists, but when you try to nullify an offensively cycloned enemy it disappears immediately.

I also want to make it clear I didn't ask why it doesn't dispel the offensive cyclone effect, that mechanic is 100% fine, it's about the effect doesn't even try to latch and disappear.

#### Step by step how to reproduce

1. Prepare two items, Nullifier and Eul.
2. Cast Nullifier at the enemy, and then immediately cast Eul on the enemy while the Nullifier projectile is still in transit.

#### What happened

The Nullifier projectile hits the offensively cycloned enemy target and then disappears, with no lingering effect or even an attempt to latch

#### What I expected if it is not a mechanic/design decision

The Nullifier still latches on to the enemy without dispelling the cyclone status as it is a debuff, not a buff.

### Example Match ID and Timestamp

5857088312 - I believe around 40 minutes, I can't remember exactly but it's about at the end of the match

**Comment by shaileshgarg** [comment]
Makes sense right, Nullifier is used to Dispel Enemies, so it removes Buffs from enemies, not Debuff. The same hero Euling the target counts as Debuff not Buff, so they can be euled by the Hero or the teammates.

**Comment by deanrih** [comment]
I'm very well aware of that and I don't have any problem with that mechanic, this bug report focus on the fact that the Nullifier Debuff effect doesn't apply or latch, just disappear when hitting the offensively cycloned enemy.

**Comment by shaileshgarg** [comment]
Yeah, it should stick on offensively cycloned enemy.

**Comment by deanrih** [comment]
> Yeah, it should stick on offensively cycloned enemy.

That's the reason why I create this issue, is it really a bug or actually intentional design decision, need to wait for Valve to look into this one.

**Comment by commentator24** [comment]
defensive cyclone + nullifier will hit and dispel cyclone, so i dont see why offensive cyclone + nullifier will not hit...

i think the enemy should still be flying / cycloned with the nullifier effect (but cyclone debuff not removed). currently nothing will happen and appears as if nullifier missed / disjointed.

**Comment by TheZett** [comment]
This is intended.

Nullifier only removes BUFFS off of enemy units, but not debuffs.

If you use Euls on an enemy, it is placed as a DEBUFF and thus your own Nullifier wont remove it.

If the enemy uses Euls himself, it is placed as a BUFF and thus your Nullifier will remove it.

**Comment by PeruSonOfWhores** [comment]
Remove peru apes from US servers

**Comment by commentator24** [comment]
the bug is not about removing or not removing debuff. it doesnt apply at all.
if nullifier can be applied on defensive eul, then it should be able to be applied on offensive eul as well... 

otherwise nullifier on defensive eul should miss / not applied as well if eul suppose to be invulnerable.
https://user-images.githubusercontent.com/109324155/219946583-760f5241-6255-4d13-8f73-d6f6ccdbb1f1.mp4

**Comment by shaileshgarg** [comment]
https://dota2.fandom.com/wiki/Nullifier/Changelogs, Nullifier cannot be applied to Invulnerable units if it cannot remove invulnerabiity. 


For offensive euls, which is a debuff, it cannot remove it so it is not applied.

**Comment by deanrih** [comment]
Since it is proven and documented as intentional, I'll close this issue.
