### ISSUE TITLE
''Feral the Werebat'' I have a problem with this item 

### ISSUE THREAD

**Issue by altanumut93** [ValveSoftware/Dota2-Gameplay#6982]
### Item name

Feral the Werebat

### Description

in 16 february Steam market says that i bought this item for 830try (44,00 USD) but i look after when I look at the sales chart, it was sold hundreds of times earlier, much cheaper than my sales request (like 10 cents) .To be honest, I don't even remember making such a purchase request.I don't understand why you're getting $44 from something that sells for 10 cents. please help me for my problem with this item. 
https://steamcommunity.com/id/umutaka/
https://imgur.com/a/Yroa0Im
https://imgur.com/a/WMVxYG5

### Example Match ID and Timestamp

53648567981 - 15:21

**Comment by Aluerie** [comment]
You got hacked/scammed/phished. Do all measures that are required for victims: password and everything change, check everything and etc.

---

And since this is a **bug** tracker (and not Steam Support or scam/ban appeal service) and your post is not a bug report - please close your issue.
