### ISSUE TITLE
Silencer’s Glaives of Wisdom cannot steal int from Meepo clones

### ISSUE THREAD

**Issue by TheZett** [ValveSoftware/Dota2-Gameplay#70]
This issue is in regards to Silencer’s Glaives of Wisdom and kind of Slark’s Essence Shift.

Both of these spells are able to passive steal stats, but their stat stealing behaviour is inconsistent regarding hero clones.

Essence Shift can steal Agility from Meepo clones and from Tempest Doubles, while Glaives of Wisdom can only steal Intelligence from Tempest Doubles, but not from Meepo clones.

I reported this years ago, when OD just got his int steal component on Arcane Orb, and I compared it to the previous int steal behaviour on Astral Imprisonment (pre-6.86), which did work against Meepo clones.

Realistically both temporary stat stealing abilities, Essence Shift and Glaives of Wisdom, should work against Meepo clones and the Tempest Double.

Old dev forum thread: https://dev.dota2.com/forum/bugs/gameplay-bugs/247494-stat-steal-mechanic-od-slark-is-inconsistent-regarding-hero-clone-units?t=266734#post1392804

**Comment by eugene-valve** [comment]
This will be fixed in an upcoming update, thanks!
