### ISSUE TITLE
Lost some of my skins

### ISSUE THREAD

**Issue by Mothernaut** [ValveSoftware/Dota2-Gameplay#7008]
### Description

So I open my steam, name changed to numbers for some reason, no big deal, I change it back - I go to dota 2 and realize I've lost some of my skins, immortals and all that. I got some of said parts lost skins as "new" in the armory and some I didn't even have to begin with.
I'm not exactly sure as what to do or attach in here so would love some help.

**Comment by TheUnholyWrath** [comment]
don't waste any time here, go directly to steam support. this is not at all a dota issue, you need to deal with steam support. good luck. please close this issue.
