### ISSUE TITLE
Natures Prophet lvl 20 talent sprout leashes talent not working

### ISSUE THREAD

**Issue by MarshIsTaken** [ValveSoftware/Dota2-Gameplay#7020]
#### Steps for reproducing this issue:

1.  Demo furion and sprout any unit with lvl 20 leash talent. Units can freely move in sprout and even exit if a tree gets cut.

**Comment by TheUnholyWrath** [comment]
You should close this issue. This interaction is consistent with Clockwerk's level 20 leash talent. Leash itself does not stop units from walking away, its only additional spell effects (like Slark's distance limit or Grimstroke's bind) that stop movement.
