### ISSUE TITLE
 False Ban

### ISSUE THREAD

**Issue by parnesha22** [ValveSoftware/Dota2-Gameplay#7041]
### Description

Hello, I go into the game and see that I was banned until 01/19/2038. I did not use cheats, this is not a smurf account. why i got banned??? Maybe someone else got into my account and used cheats. Please unban me

### Screenshots

![Dota 2 Screenshot 2023 02 22 - 17 26 46 89](https://user-images.githubusercontent.com/126086346/220651137-c2090a66-d03d-4286-93d0-8274a11cceda.png)

**Comment by Aluerie** [comment]
this is a bug tracker. not a service for ban appeal - so, please, close your issue.
