### ISSUE TITLE
GOOD JOB, VALVE?

### ISSUE THREAD

**Issue by Leyzik** [ValveSoftware/Dota2-Gameplay#7045]
### Description

Good afternoon, dear valve.Whenever I launched a rating, and in the enemy team I came across players on whose account the player is playing the game levels higher on this rating (boosters). And I've always crossed my fingers in the hope that valve will ban such players to hell)). But today I TURNED OUT TO BE A CHEATER, ARE YOU CRAZY? No one has access to my account and no one has ever played on my account with third-party software, I only had access to my account from other computers, because I played Dota 2 in the cyber arena (WITHOUT USING THIRD-PARTY software). I think blocking my native account is wrong. I hope you will understand me and reconsider your decision)

### Example Match ID (and possibly Timestamp)

7027355840

### Screenshots

![image](https://user-images.githubusercontent.com/126097667/220697726-e1d88d42-f15d-4c8b-8df0-f5eb0b6631ce.png)

**Comment by Aluerie** [comment]
this is a bug tracker, not a ban appeal service - please, close your issue.

**Comment by kikcimasss** [comment]
So where to write to remove the ban? If you didn’t use uncheats, on the wrong side of the program?

**Comment by Leyzik** [comment]
> this is a bug tracker, not a ban appeal service - please, close your issue.
