### ISSUE TITLE
Baned for what I didn't do

### ISSUE THREAD

**Issue by OmskiyOsel** [ValveSoftware/Dota2-Gameplay#7054]
A friend asked for an account in order to play with skins, I gave him an account. I did not know that he plays with cheats, and I was banned. I would like to unlock me.

**Comment by Aluerie** [comment]
this is a bug tracker, not a ban appeal service - please, close your issue.

**Comment by OmskiyOsel** [comment]
> A friend asked for an account in order to play with skins, I gave him an account. I did not know that he plays with cheats, and I was banned. I would like to unlock me.
