### ISSUE TITLE
Assists Count more than even whole team kills count.

### ISSUE THREAD

**Issue by hansanugrah** [ValveSoftware/Dota2-Gameplay#7060]
### Description

Assists is more than whole team kills, Riki get 41 assists on 37 kills whole team.
Our teams death is counted to 37 only too.

### Example Match ID (and possibly Timestamp)

7028902711

### Screenshots

![BugAssistDota](https://user-images.githubusercontent.com/57321532/220937793-4c7c33c9-a307-424a-b9d1-d2f037b12b80.png)

**Comment by shaileshgarg** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/83
