### ISSUE TITLE
Demo Mode - Shadow Fiend ultimate has no particles or damage effects

### ISSUE THREAD

**Issue by Symphona** [ValveSoftware/Dota2-Gameplay#7066]
### Description

When using Shadow Fiend in the "Demo Hero" mode, his ultimate ability plays the channel animation and the sound, but the lines do not appear, and no damage is dealt to nearby enemies. His three Raze abilities all perform as expected. Issue reproduced on two different accounts/machines, and leaving/re-entering Demo mode did not fix it.

Reproduction: 
Enter Demo Mode as Shadow Fiend, from his hero page.
Click Level Max on the left hand toolbar.
Pressing R will perform the ability as described, with sound and animations but no line graphics and no damage.

Adding Aghanims Scepter adjusts the sound as expected but still no damage.

**Comment by Aluerie** [comment]
ehm, do you know that you need souls stacks from the passive for R lines/damage to be here ? 

Farm some heroes first with Necromancery level'ed up.

---

If this solved your issue - then please, close your issue. 

rtfm moment.

**Comment by Symphona** [comment]
I will now close this thread in shame.
