### ISSUE TITLE
Io ultimate can't Teleport Sniper

### ISSUE THREAD

**Issue by gfgyfguy** [ValveSoftware/Dota2-Gameplay#7071]
### Ability name

Teleport

### Description

It's either a bug or that Sniper (Username "Broo") cheats with a script or something. I've tried 4 times to teleport sniper but can't. 

Skip first 15 mins of gameplay. 

### Example Match ID (and possibly Timestamp)

7028541212

**Comment by TheUnholyWrath** [comment]
When you disable help on an Io, they will not be able to teleport you with relocate. Watching your game this is almost certainly what happened, but I can't find the timestamp exactly when Sniper did it (likely after the first time you relocated him while he was dead {~24:14}. his mouse movement was very messy so I couldn't clearly see it). This isn't a bug. You should close this issue.

**Comment by gfgyfguy** [comment]
Hello, I'm back with time stamps
23:05- Io teleportation on Sniper success
33:50-Teleport Fail
40:10- Teleport Fail

I don't grief so it doesn't make sense to disable io teleportation skill just like that. Makes the game unbalanced especially if the support doesn't know.

Thank you

**Comment by gfgyfguy** [comment]
More timestamps
42:10
52:00

Other teleport from other heroes works fine

**Comment by TheUnholyWrath** [comment]
So now that we know that disabling help stops Relocate can you be a bit more specific about why this is still open? Am I wrong about all this? Is this interacting incorrectly? Timestamps are nice but I'm confused what you're trying to convey.
