### ISSUE TITLE
bannned for nothing

### ISSUE THREAD

**Issue by hisokazxc** [ValveSoftware/Dota2-Gameplay#7073]
### Description

Hello! Today I got banned from ranked Dota 2 games for a year for 15 wins in a row. the ban was for nothing, 9 games were played in 3 positions, my teammates threw me only 4 reports for the fact that I won the game for them, maybe this is due to the wave of bans, but only I played on my account, there was no boost, please unban me

https://steamcommunity.com/profiles/76561198872769621/

здравствуйте! сегодня я получил блокировку в рейтинговых играх доты 2 на год за 15 побед подряд. бан был ни за что, 9 игр были сыграны на 3 позиции, мои тиммейты кинули мне всего 4 репорта за то что я выиграл им игру, возможно это связанно с волной банов, но на моем аккаунте играл только я, никакого буста не было, пожалуйста разбаньте меня 

### Example Match ID (and possibly Timestamp)

7030742635

**Comment by Aluerie** [comment]
this is a bug tracker, not a ban appeal service - please, close your issue.

**Comment by propugnator101** [comment]
cheat and cry

**Comment by hisokazxc** [comment]
> cheat and cry

read carefully, the reason for the ban is not in cheats, but in boosting which was not on my account
