### ISSUE TITLE
Units become visible through fog of war (when newly summoned, or when illusions are spawned)

### ISSUE THREAD

**Issue by Mabadman** [ValveSoftware/Dota2-Gameplay#7078]
Units will become visible through fog of war under at least two circumstances;

- The unit in question is just summoned (#1753, #3026, possibly others)
- Illusions are spawned through manta/wall of replica/etc

The first instance is pretty well documented. Here's an example of the second instance:

### Example

**Match ID:** 7031858348 ([Demo File Mirror](https://drive.google.com/file/d/1Qj9AD-U72YEhuWGU0z_T6SPFn5n_veTV/view?usp=sharing)) 26:30

[Untitled_.webm](https://user-images.githubusercontent.com/42493726/221242259-55b831be-4665-4008-a4d9-21f3e8087f01.webm)

### More examples
These are older clips I recorded, unfortunately no replay files are present.
**Match IDs in order:** 6956642172, 6951700259, 6951075828, 6956415933, ????, 7012458279
**Suspected causes for bug instances in order:** Maybe Ice Vortex, maybe Astral Imprisonment, Medusa Manta activation, Venomancer Plague Ward, Venomancer Plague Ward, Wraith King skeleton summons.

[dex1.webm](https://user-images.githubusercontent.com/42493726/221263896-41b9da93-9a8c-4f17-8486-bd983134a56a.webm)

**Comment by Avarise831** [comment]
add: Storm used remnant u can see red dot on minimap,doppelganger pl,neutral troll camp spawn 3 skeletons

**Comment by jeffhill** [comment]
A fix for this will ship in the update today. Thank you for the bug report!
