### ISSUE TITLE
valve blocked 40 000 dicks in fat ass Gabe Newell BUT HIS SUCK MU DICK

### ISSUE THREAD

**Issue by BurningJanuary** [ValveSoftware/Dota2-Gameplay#7080]
### Description

HELLO DEAR  RETARD VALVE TEAM !
MAY YOU SHITHEAD MORONS BLOCKED GROPS FROM 4 RUS-TARD PEOPLE IN UNRANKED GAMES, IT WILL VERY KIND OF YOU, I NEED TO HAVE A CHOICE TO PLAY IN DOTA WITHOUT 4 RUSTARD PIGS IN TEAM. THANK YOU !!!
ALSO IF ITS POSSIBLE - MAKE DOTA A PAID GAME !!!!! thank you and fuck youmothers !

**Comment by Aluerie** [comment]
this is a bug tracker, not a forum for rants - please, close your issue and go to appropriate places.
