### ISSUE TITLE
Left ended match, got abandon

### ISSUE THREAD

**Issue by da0811** [ValveSoftware/Dota2-Gameplay#7085]
### Description

The ancient was destroyed and the match ended without results due to servers. So I left the match but got an abandon. I've done it before without issue. 

### Example Match ID (and possibly Timestamp)

7033504937

### Screenshots

![20230225104027_1](https://user-images.githubusercontent.com/61606269/221366252-fab2ce25-cec2-4012-8fa7-a017d05c957f.jpg)

**Comment by yckmm** [comment]
You didn't get an abandon, it would say "Abandon" and not "Loss". Dotabuff does not show an abandon either: https://www.dotabuff.com/matches/7033504937

**Comment by da0811** [comment]
The "Play Dota" button to queue for matches is red. I had a 15 minute penalty cooldown that did not allow me to queue for matches.

**Comment by Dota2user3** [comment]
I had an issue with servers yesterday too except my game didn't count. Yikes. Still not counting

**Comment by da0811** [comment]
I just got my 25-game summary and there are no abandons. I did wrongfully get blocked from matchmaking for 15 minutes, however.
![20230225171925_1](https://user-images.githubusercontent.com/61606269/221382119-bca2d586-3417-42cf-8456-930f4ca4eb90.jpg)

**Comment by Usera2** [comment]
If it was a timed block, it was a fail to press ready.
Next time try to see what those red lines says
