### ISSUE TITLE
gift:error

### ISSUE THREAD

**Issue by nozerrus1** [ValveSoftware/Dota2-Gameplay#7100]
### Description

why can't I gift Dota 2 items to all my friends who are on Steam Dota 2 and my friends have been friends for more than 30 days.
It's been three days and it still doesn't work, so help. I hope this can be fixed thank you
ID 254735071

### Example Match ID (and possibly Timestamp)

No response

### Screenshots

![20230225134238_1](https://user-images.githubusercontent.com/126410789/221425166-da03cd5f-64c4-48da-a2b3-96518c4c742f.jpg)

**Comment by Aluerie** [comment]
Duplicate #6333

---
Please, close your duplicate issue and instead upvote the original one with "👍" reaction. Comment extra details if any.

And in future, first, use search to find out if the bug you want to report was already submitted by somebody else so you can upvote it and not clutter the repository with duplicates.
