### ISSUE TITLE
View Profile Button Missing

### ISSUE THREAD

**Issue by Nyefan** [ValveSoftware/Dota2-Gameplay#7109]
### Description

Reproduction steps:

join game
during pick phase, right click on player's name
two options show - 'add friend' and '(un)ignore user'

Expected:
three options show - the above and 'view profile'

**Comment by TheUnholyWrath** [comment]
[- Player profiles can no longer be accessed in matchmaking during the pregame phase. They can still be accessed once the picking phase ends.](https://store.steampowered.com/news/app/570/view/3659774959178253450)
