### ISSUE TITLE
Expose Public Match Data disable still sharing my data (CRITICAL)

### ISSUE THREAD

**Issue by f3ar161** [ValveSoftware/Dota2-Gameplay#7115]
#### Windows 11

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:

If I disable my public data on social tab, game details should not be public. 

#### Steps for reproducing this issue:

1. Disable Expose Public Match Data, play a rank roles games
2. Go to DotaBuff check your profile and data is still visible. 
3. Restart de game enable/disable again, play a game check dotabuff profile, game details still visible

**Comment by shaileshgarg** [comment]
#1515

**Comment by yckmm** [comment]
The setting is working, but dotabuff ignores it. You can login on dotabuff and set your profile to private there.

**Comment by polosyss** [comment]
The new update makes it hard for me to see, especially with [tunnel rush](https://tunnelrush.co) I feel a bit laggy

**Comment by ginteraminense** [comment]
> The setting is working, but dotabuff ignores it. You can login on dotabuff and set your profile to private there.

Where exactly?

I have logged in and there's no option to set profile to private.
Worse: the site recognizes my profile is set to private but keeps exposing match history.

This issue seems to be very alive.

**Comment by yckmm** [comment]
It should show "You have exposing of match data disabled" in your dotabuff settings and then there is a checkbox to "Hide steam name" or something. It still shows your own matches when you are logged in, you have to logout (or open a private tab) and check your profile and then it should show as private.

**Comment by f3ar161** [comment]
> The setting is working, but dotabuff ignores it. You can login on dotabuff and set your profile to private there.

I'm literally watching my data as public from a private tab and I'm not even logged to dotabuff

I think it might me related to the dotaplus update 'cuz I have dota plus on my accs

**Comment by yckmm** [comment]
Maybe the dotabuff profile didn't update yet? It's definitely not related to dota plus.

Anyway, this is what my settings look like on dotabuff:
![image](https://user-images.githubusercontent.com/14143610/225947325-1e655da4-bdda-4f97-aa74-e8823e394b54.png)

And this is what my profile looks like when logged out:
![image](https://user-images.githubusercontent.com/14143610/225947546-5f765761-0e74-40e9-b1e3-1fc96ff94493.png)

**Comment by f3ar161** [comment]
still not fixed 

https://www.dotabuff.com/players/101838069

dota 2 settings 

![image](https://user-images.githubusercontent.com/14907413/230543172-20c6ff75-3755-4e38-ab16-7bf9916fa701.png)

dotabuff in private tab
![image](https://user-images.githubusercontent.com/14907413/230543209-e709679c-484a-474f-adc9-947fa79171f1.png)

**Comment by f3ar161** [comment]
![image](https://user-images.githubusercontent.com/14907413/230543296-7509733d-0640-4ef4-b463-c81e9810ef3c.png)

@yckmm

**Comment by f3ar161** [comment]
@yckmm as you can see I dont even sign in to my steam acc 
![image](https://user-images.githubusercontent.com/14907413/230543486-687f9fb3-732f-4767-8567-f465c73ac34f.png)

**Comment by Aluerie** [comment]
But did you update your dotabuff settings? You still haven't answered that.

**Comment by f3ar161** [comment]
@Aluerie profile has been private for a long time

![image](https://user-images.githubusercontent.com/14907413/230698615-402f855e-d70f-428c-a065-e0433bfff45f.png)

**Comment by Aluerie** [comment]
And you didn't scroll to the setting that is needed...

**Comment by f3ar161** [comment]
srry for the late response this one is solved now. thanks for the follow up.

**Comment by AnsBal** [comment]
how did you solve it?
