### ISSUE TITLE
Lima Major Fantasy not rewarding shards

### ISSUE THREAD

**Issue by TonyWitaFish** [ValveSoftware/Dota2-Gameplay#7119]
### Description

Been doing the fantasy everyday and it has not updated my standing nor given my shards. Some of the cards I've used on the Lima fantasy came from the daily packs before the major started, I'm thinking the issue is coming from the cards from DPC.  I've seen others post on the tracker that they are not getting shards either, but have not seen anything about the cards from before the Lima Major. 

### Screenshots

![Dota 2 Fantasy Bug Screenshot](https://user-images.githubusercontent.com/126605685/221934364-d60db222-9516-4bbc-bba6-c96c3f8b641b.jpg)
![20230228114302_1](https://user-images.githubusercontent.com/126605685/221934497-9fb67dd3-b5ec-4d93-b789-c42f618a4bb2.jpg)
![20230228114305_1](https://user-images.githubusercontent.com/126605685/221934509-1bec9e90-7658-4de1-837f-d81a5585d99e.jpg)
![20230228114307_1](https://user-images.githubusercontent.com/126605685/221934523-0cbe4284-986b-41a0-b2c8-8c952ec720d5.jpg)
![20230228114309_1](https://user-images.githubusercontent.com/126605685/221934534-68584466-73c7-4837-a236-a1cb144161fa.jpg)

**Comment by Aluerie** [comment]
Duplicate #7101

---
Please, close your duplicate issue and instead upvote the original one with "👍" reaction. Comment extra details if any.

And in future, first, use search to find out if the bug you want to report was already submitted by somebody else so you can upvote it and not clutter the repository with duplicates.

**Comment by TonyWitaFish** [comment]
Still hoping they check the cards from before Lima Major.
