### ISSUE TITLE
Camera control issue {"bind" command}

### ISSUE THREAD

**Issue by AlexiBlue** [ValveSoftware/Dota2-Gameplay#7130]
### Description

In short:    --bind KEY "toggle dota_camera_lock"--     stopped working

Spent hundreds of hours playing LoL with a camera lock bind. Spent hours trying to find a way to create that hotkey in Dota (since its not listed in the game's settings, i had to find a console command), but recently the command stopped working (in matchmade lobbies). Its extremely difficult (almost impossible, even) for me to play without it, and for some other people too.

I saw the patch notes, some abusable commands got disabled in MM games, but ""bind""? I dont know whether it was intentional or not. 

Please let us use "bind", or at least add a setting for the camera lock. If it was completely intentional or you dont plan to fix it... well, unlucky i guess

Thank you for your time!

**Comment by TheConfuZzledDude** [comment]
Try using `bind_toggle` instead of `bind` and `toggle` separately?

**Comment by AlexiBlue** [comment]
In short: IT WORKED!
So, basically...
I tried to use the "bindtoggle" command in a MM match, but it didnt work. However...
As soon as i unbound space (the key i used for the bind) from IN-GAME hotkeys, it worked. I'm pretty sure just "bind" will work too, haven't checked it
So, basically... The reason it didn't work was probably because it was overwritten or something? It worked perfectly fine before the update, thats why "overwriting" was such an unexpected reason.

Either way, now it works and i can freely enjoy Dota with my friends. Thank you so much!😁
