### ISSUE TITLE
Warlock level 20 talent does not stun

### ISSUE THREAD

**Issue by AdmiralRisi** [ValveSoftware/Dota2-Gameplay#7151]
### Ability name

Chaotic offering level 20 talent

### Description

Warlock level 20 talent does not stun when warlock dies

### Example Match ID (and possibly Timestamp)

test on demo mode and bots

**Comment by shaileshgarg** [comment]
Working fine

https://user-images.githubusercontent.com/26450759/222789121-2f2546b6-70e1-474c-aa62-d878545f5b80.mp4

**Comment by AdmiralRisi** [comment]
https://user-images.githubusercontent.com/106505034/222790934-2ed4b6cf-26f4-4528-8bc7-8eeb138691ef.mp4

**Comment by TheUnholyWrath** [comment]
https://user-images.githubusercontent.com/46859977/222811847-33b5144a-afcd-4bff-ac07-df07d3583e53.mp4

**Comment by commentator24** [comment]
tested in demo hero if you just LV30 without casting any golem it wont stun. but after you summon 1 golem it will stun

**Comment by TheUnholyWrath** [comment]
related to #3704 but much less significant
