### ISSUE TITLE
Candyworks no longer works

### ISSUE THREAD

**Issue by commentator24** [ValveSoftware/Dota2-Gameplay#7152]
Clicking notification international 2021 compedium has ended leads to International 2023, not candyworks, and it's not working anymore. is this intended?
![image](https://user-images.githubusercontent.com/109324155/222758925-ebb0e541-c5c1-4a66-b62c-6d77b5ef38c7.png)

**Comment by shaileshgarg** [comment]
Probably removed the server side code for the battlepass, so no response.
