### ISSUE TITLE
Pick banned hero in All pick mode

### ISSUE THREAD

**Issue by Cular** [ValveSoftware/Dota2-Gameplay#7158]
### Description

I have first pick rubic as pos 5, it was picked by enemy team also that causes ban of RUBIC.
Then I have picked Crystal Maiden and some how guys from enemy team also pick Crystal Maiden that causes ban of CRYSTAM MAIDEN,
BUT after I pick Lion, they pick Crystam Maiden despite on banned status.

How Crystal Maiden can be picked if I was first and it even has banned status?

### Example Match ID (and possibly Timestamp)

7043981959

### Screenshots

![image](https://user-images.githubusercontent.com/26927442/222915439-0976943e-b36a-4f85-ac41-e612b0d53fbc.png)

**Comment by commentator24** [comment]
In case you didnt know, same pick double bans only happen twice now. After that whoever faster gets the hero.

I watched the replay a bit
So first radiant pick pudge. then..
Dire picked rubick.
Radiant picked CM.
Dire picked pudge. Both team picked pudge so pudge banned.
radiant picked rubick. Both team picked rubick so rubick banned.
Dire picked lich.
then Dire picked Lion.
radiant picked witchdoctor.

you can close the issue, nothing unusual here
