### ISSUE TITLE
Rubick get damage while using Primal Beast ultimate "Pulverize"

### ISSUE THREAD

**Issue by Leenoplt** [ValveSoftware/Dota2-Gameplay#7170]
### Ability name

Spella steal(Pulverize)

### Description

When you steal ulti from Primal Beast and use it sometimes you get some damage

### Example Match ID (and possibly Timestamp)

7046288873 - 8:25

**Comment by TheUnholyWrath** [comment]
Primal Beast cast Trample, thats where the damage came from. Theres already an issue open for this interaction #4412. You should close this issue
