### ISSUE TITLE
Bugged party invites this patch

### ISSUE THREAD

**Issue by commentator24** [ValveSoftware/Dota2-Gameplay#7173]
not sure what you guys did, but in this patch sometimes cannot see friends invite until actually inside game drafting phase. Can see dota icon flashing though.
Party leader is not friend, but no i don't have block non friends setting on
![image](https://user-images.githubusercontent.com/109324155/223052141-290633d2-6e2a-4cf9-a001-88c2d43a64ca.png)

**Comment by commentator24** [comment]
maybe fixed, didnt happen anymore

**Comment by LokeLok** [comment]
Related to #842, it is not fixed.
