### ISSUE TITLE
Duel doesn't add correct damage

### ISSUE THREAD

**Issue by Sellmeyoursocks** [ValveSoftware/Dota2-Gameplay#7174]
### Hero and spell

Legion Commander + duel

### Description

If LC has the added duel damage talent from lvl 10, and the opponent uses lotus orb while being duelled, it will only add the base level damage from the duel skill twice, and the damage talent once. If the LC is lvl 10 and has the talent, and the opponent is affected by lotus orb, the winner will get +28 (10+10+8) damage and not 36(10+10+8+8). This is consistant on every level that it does not give the damage talent more than once. I don't know if this is intentional.
I have only tried this in demo mode, perhaps it behaves differently in the game

**Comment by TheUnholyWrath** [comment]
This is consistent with how Lotus Orb works. Lotus Orb is essentially making the enemy cast the spell, and since the enemy doesn't have your talent Duel will not give the +8 bonus damage. You should close this issue
