### ISSUE TITLE
Cannot set quickcast hotkey for neutral item 

### ISSUE THREAD

**Issue by CalvinBerrett** [ValveSoftware/Dota2-Gameplay#7185]
### Description

While the "Enable Advanced Quickcast/Autocast Hotkeys" option in the Advanced Hotkeys settings is enabled, the option to set a quickcast hotkey for TP scroll or Neutral Item slots doesn't show up

### Screenshots

![ItemCast](https://user-images.githubusercontent.com/31518724/223285445-2a714199-9d4b-4630-8e7d-cbcf5d470f4d.PNG)
![ItemQuickcast](https://user-images.githubusercontent.com/31518724/223285450-e35176a9-5f2f-4bbe-9c41-7055aecfdba1.PNG)

**Comment by shaileshgarg** [comment]
Looks like this is fixed.
