### ISSUE TITLE
Quickcast and Normal cast causes items/spells to be used twice

### ISSUE THREAD

**Issue by aralhibshi** [ValveSoftware/Dota2-Gameplay#7188]
### Description

If you use quickcast on an item/ability which also has a normal cast hotkey, the item/ability will be triggered twice, once on key press and once on key release (regardless of other quickcast settings). The only way to fix this is to remove the normal cast hotkey entirely. The hotkeys in the screenshots below create the problem.
![20230307032336_1](https://user-images.githubusercontent.com/118065642/223289307-867acce1-0653-4a26-8bec-ebc103707b34.jpg)

### Screenshots

![20230307032331_1](https://user-images.githubusercontent.com/118065642/223289302-1d4397cf-6fee-4be4-8dec-f18554bf04e4.jpg)

**Comment by ngavalas** [comment]
Confirmed. This is particularly egregious on Void Spirit ulti, which gets you basically instantly killed as I found out last game.

**Comment by Philaeux** [comment]
Related to #7196
