### ISSUE TITLE
Quickcast doesn't work on Legacy Keys

### ISSUE THREAD

**Issue by Momguy** [ValveSoftware/Dota2-Gameplay#7190]
### Description

Quickcast doesn't work when you use the Legacy Keys option

**Comment by MuhAiRoCino** [comment]
Fixed

**Comment by trytolose** [comment]
not fixed, still doesn't work on macos client

**Comment by shaileshgarg** [comment]
Tested on windows and macbook, quickcast for Legacy keys on Spells, is working fine.

Legacy Keys with Item Quick cast is not working.

**Comment by kwnkwn2g** [comment]
key release does not work, please fix! 
![gcXJydCenS0](https://user-images.githubusercontent.com/121286612/223996499-bef72101-ac43-4696-8988-37ed45a8c3b8.jpg)
