### ISSUE TITLE
Legacy keys Quick cast 

### ISSUE THREAD

**Issue by BestBeast1** [ValveSoftware/Dota2-Gameplay#7194]
### Description

After the update Legacy keys Quick cast is not working. There is a lightning button that turns on the quick cast, even when its on the spells need a mouse click now. I restarted game/steam and returned to default settings, nothing worked

**Comment by shaileshgarg** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/7190

**Comment by shaileshgarg** [comment]
Tested on windows and macbook, quickcast for Legacy keys on Spells, is working fine.

**Comment by BestBeast1** [comment]
Yes, it is fixed now, all good
