### ISSUE TITLE
Spark wraith 

### ISSUE THREAD

**Issue by Avarise831** [ValveSoftware/Dota2-Gameplay#7195]
### Hero and spell

Spark wraith 

### Description

7.32e  Aghanim's Scepter secondary Spark Wraith Search Radius decreased from 375 to 225 
tooltip in game still 375

### Screenshots

-

**Comment by shaileshgarg** [comment]
![Screenshot 2023-03-07 085323](https://user-images.githubusercontent.com/26450759/223312496-bc1b3b1d-1ade-4e0d-8da9-5cc3adcd02ab.png)

Looks fine.
