### ISSUE TITLE
Two of same character played on same team in Turbo mode

### ISSUE THREAD

**Issue by heyNIGO** [ValveSoftware/Dota2-Gameplay#7221]
### Description

Two of the same character was able to be picked in this turbo game.

### Example Match ID (and possibly Timestamp)

7048006845

### Screenshots

![2023-03-06T21:51:37,691366793-08:00](https://user-images.githubusercontent.com/107826367/223332438-2dcc78b0-d2c7-4587-907a-0bc6d00be9f7.png)

**Comment by Avarise831** [comment]
#7201

**Comment by heyNIGO** [comment]
Closing in favor of https://github.com/ValveSoftware/Dota2-Gameplay/issues/7201
