### ISSUE TITLE
Game crashes everywhere

### ISSUE THREAD

**Issue by Swewww** [ValveSoftware/Dota2-Gameplay#7227]
### Description

When i click testing or start the match, after pick stage game crashes, i read a forum, i'm not the only one who has such a problem.

**Comment by Stelph3y** [comment]
Did you fix that?

**Comment by Swewww** [comment]
yep

**Comment by Swewww** [comment]
Just change vulkan to dx11

**Comment by aghaasad11** [comment]
a couple of questions:

a) how do you change vulkan to dx11
b) I wasnt using vulkan before so what can I try?

**Comment by Swewww** [comment]
a) in settings go in graphics and change vulkan to dx11 (or go in launch parameters and write -vulkan or -dx11)
b) if you have radeon graphic card (I have radeon with dx11 60fps, with vulkan 120fps+) try it ( I from Russia sorry if you don't understand).
