### ISSUE TITLE
2 hero in turbo

### ISSUE THREAD

**Issue by Pewchenka** [ValveSoftware/Dota2-Gameplay#7231]
### Description

If you swap heroes with a person who does not take a hero to turbo, then there will be 2 identical heroes in the game

### Example Match ID (and possibly Timestamp)

7048243694

### Screenshots

![20230307163009_1](https://user-images.githubusercontent.com/60707825/223380983-683a7971-2dcc-459d-bcf6-386424800a3d.jpg)

**Comment by Avarise831** [comment]
#7201
