### ISSUE TITLE
[BUG][CRITICAL] It is possible to pick the same hero twice in game

### ISSUE THREAD

**Issue by super-mario-beep** [ValveSoftware/Dota2-Gameplay#7247]
### Description

I just played a match where the enemy team got two IOs. After Pudge was banned, one player picked IO and the other picked it randomly. That should not be possible. Here are the screenshots.

### Example Match ID (and possibly Timestamp)

7048503677

### Screenshots

![dotabug1](https://user-images.githubusercontent.com/74832420/223425838-080b3b04-c0ce-402c-b15e-0a73aade38fd.PNG)
![dotabug2](https://user-images.githubusercontent.com/74832420/223425847-89ddc4d4-f601-4c0c-9aee-43e74bbebeec.PNG)
![dotabug3](https://user-images.githubusercontent.com/74832420/223425857-dadc7e40-f1ea-4537-b9ba-4112516f8aa2.PNG)

**Comment by Avarise831** [comment]
#7201
