### ISSUE TITLE
Rubick and Morphling are not able to use some spells with Quickcast (even when the settings are specified)

### ISSUE THREAD

**Issue by Mishka-VFX** [ValveSoftware/Dota2-Gameplay#7257]
These are only a few examples of the spells : Enchant Totem(Aghanim's upgraded), Fissure, Shockwave, Stroke Of Fate... I am using unit-specific hotkeys. Every spell is set to be used on key down for every hero ( including Shaker, Magnus, and Grimstroke).

**Comment by Mishka-VFX** [comment]
Other examples include Dismember, Charge of Darkness, Nether Strike

**Comment by shaileshgarg** [comment]
Tested with Rubick and Shaker, working fine now.

**Comment by shaileshgarg** [comment]
Set the hotkeys for the Default Hero.
![Screenshot 2023-03-13 192720](https://user-images.githubusercontent.com/26450759/224723320-7d6c07d6-507a-48d4-98ea-d15ca5449bc0.png)

Then for Rubick and the other Hero press Clear
![Screenshot 2023-03-13 192803](https://user-images.githubusercontent.com/26450759/224723571-29988e80-998b-4d47-bf7d-e6aedade64e8.png)

Should work after that, even if you Rubick hot keys.

**Comment by Mishka-VFX** [comment]
In the options I also have "Enable Advanced Quickast/Autocast Hotkeys" checked, so the UI of hotkeys are a little different. Valve never fails to complicate simple things...

**Comment by shaileshgarg** [comment]
Do the same procedure with Advanced keys on, it should work

**Comment by shaileshgarg** [comment]
#7538

**Comment by Digit4** [comment]
Is this working now? if yes could you explain a little on what settings need to be configured? Also could we close this bug if it's fixed/an issue with the settings?

**Comment by shaileshgarg** [comment]
So, as per my testing.

If the default Hero has, Q W E D F R, configured for spell, quick cast KeyUp or Down, if Rubick Overrides the D F keys quickcast behavior, but the original Hero hasen't overridden anything, then Rubicks config is used. But if the original has overridden the config then his config is used.

To check if Hero has overidden config, then see if you can see Clear Button on the Hero config.

**Comment by Mishka-VFX** [comment]
My god, this is overcomplicated... So it appears that I need to set every single hero's hotkey manually for them to work properly on Rubick. How lovely is that <3

**Comment by shaileshgarg** [comment]
Makes sense right given you want each spell to have different key up/ key down behaviour

**Comment by Mishka-VFX** [comment]
Thank you for your effort , at least now I understand how to make it work
