### ISSUE TITLE
PA arcana doesn't count wins in turbo at all.

### ISSUE THREAD

**Issue by NAlexP** [ValveSoftware/Dota2-Gameplay#7258]
### Cosmetic Item Name

Manifold Paradox

### Description

The arcana does not count wins in turbo at all. It's sad to see that others are getting full credit after the last update and this one doesn't get any at all for years.

### Example Match ID

/

**Comment by Aluerie** [comment]
linking relevant original/initial #360 issue

**Comment by NAlexP** [comment]
> 

I don't see the relevance, the es arcana got fixed this patch.

**Comment by Aluerie** [comment]
Read my comment in there ; 

Valve devs asked people to organize threads into megathreads wherever possible so we did with this one. 

I mean you don't need to remove your post. I'm just linking the original.
