### ISSUE TITLE
rubbick can't quick cast ember spirit's skill 

### ISSUE THREAD

**Issue by sallyandrain** [ValveSoftware/Dota2-Gameplay#7274]
### Description

i tried either unit specific hotkeys or normal hotkeys rubbick can't quickcast ember spirit's skills.

### Screenshots

![rubbick](https://user-images.githubusercontent.com/101641350/223493662-7e8f5f92-4689-4d89-9f37-0ceaf5f9fcec.png)
![rubick3](https://user-images.githubusercontent.com/101641350/223493738-386c67b4-305b-4886-a83d-a17c6918325c.png)
![rubick2](https://user-images.githubusercontent.com/101641350/223493581-7915ac19-41a6-47cc-a471-de7460eb462c.png)![rubbick1](https://user-images.githubusercontent.com/101641350/223493624-03e02df7-3ab2-4643-8990-fa6d2886df93.png)

**Comment by shaileshgarg** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/7257
