### ISSUE TITLE
2 Same hero pick on opposite team 

### ISSUE THREAD

**Issue by MickoNarag** [ValveSoftware/Dota2-Gameplay#7275]
### Description

Turbo Game - Radiant side has 2 Zeus and 2 Spirit Breaker
![Screenshot (8)](https://user-images.githubusercontent.com/127235192/223494238-388a8d44-4dbd-4407-99d2-78a67f9c51dc.png)

### Example Match ID (and possibly Timestamp)

7048993646

### Screenshots

![image](https://user-images.githubusercontent.com/127235192/223494137-61707fb6-60da-4d21-a4c9-b4f86cd1ce02.png)

**Comment by Janposs** [comment]
![grafik](https://user-images.githubusercontent.com/48968955/223497134-db78940b-d3a9-4e63-8a92-4618de8331ef.png)


same here with 2 skywraths

Match ID: 7049019842

**Comment by commentator24** [comment]
#7222

**Comment by Aluerie** [comment]
Duplicate #7201

---
Please, close your duplicate issue and instead upvote the original one with "👍" reaction. Comment extra details if any.

And in future, first, use search to find out if the bug you want to report was already submitted by somebody else so you can upvote it and not clutter the repository with duplicates.
