### ISSUE TITLE
Dark map

### ISSUE THREAD

**Issue by MonaKhant** [ValveSoftware/Dota2-Gameplay#7283]
### Description

The map is dark like there is no vision.

### Screenshots

![Screenshot_2215](https://user-images.githubusercontent.com/127243498/223520102-c3db8edf-d0c9-4685-985c-dcd1cabcb4fc.png)

**Comment by shaileshgarg** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/6303

**Comment by gangrelmal** [comment]
same problem here, plus #7302

**Comment by MonaKhant** [comment]
Still can't fix that.
