### ISSUE TITLE
Unfair to charge premium prices for skins and then release them in a chest for so much cheaper than $300 for the whole public to get who didn't buy the set through the battle pass. this is such a scam

### ISSUE THREAD

**Issue by JosephKhalil2209** [ValveSoftware/Dota2-Gameplay#7292]
I have been playing dota for many years now, but one thing that is now annoying me is how we paid over $300 across 2 battle passes, invoker kid persona and the Pudge persona and now they become so cheap.

When getting the battle pass they are exclusive items why are we charging a premium price when the following year a set for $7 is released and everyone then gets access to the skin we spent over $300 for; this is frustrating because the battle passes are a scam in that case, for paying premium prices you are getting more personas than arcanas/exclusive items and the only difference we get is a word in the skin saying it exalted which means jack shit anyways.

**Comment by Mabadman** [comment]
![image](https://user-images.githubusercontent.com/42493726/223559062-e508ca85-3818-4aa5-af9f-0736668cf767.png)

**Comment by Aluerie** [comment]
Valve aren't scamming or lying, or false advertising with Invoker or Pudge personas. You need(-ed) to be more attentive/scrupulous on details to what you buy if you gonna complain about "exclusivity". 

All old Battle pass items were advertised as exclusive like this. And when item was exclusive - it clearly had a tag alongside of it so people understand inevitable FOMO. 
![image](https://user-images.githubusercontent.com/33165440/223697204-d2fe6265-94b8-463f-959c-2917e93d0c81.png)

However note how invoker item does not have any tags like that anywhere on that page. Same for Pudge and a lot of newer BP items. 
![image](https://user-images.githubusercontent.com/33165440/223698002-45bde896-c846-4a3b-8f94-36a5b6a1d769.png)

It was not marked as *exclusive to that battle pass*. So yeah, nothing wrong here, you should close this issue as invalid.

**Comment by JosephKhalil2209** [comment]
Fair enough that they don't market it as exclusive in that stance, but would you argue that it is fair to charge these prices for example for invoker it was lvl 300 to get the persona; to charge people for something later in the next months they could get for less than $40 from chests? 

Take for example this image, the idea of with a minigame possibly giving you the persona and a set for $0 is such a scam. what benefit do those who pay for the battle pass get? a non-marketable set that will sooner or later be provided if a community of people vote for it during a cached chest or a mini-game just supplying it for no apparent reason. 
![image](https://user-images.githubusercontent.com/74638554/223703108-35e0f830-ed47-47da-9070-ace257e732d4.png)
