### ISSUE TITLE
Muerta 1st skill issue

### ISSUE THREAD

**Issue by UgbemugbemOsas** [ValveSoftware/Dota2-Gameplay#7308]
### Ability name

Dead Shot

### Description

When Muertas 1st skill apply fear, any source of slow does not work. For example when you buy Eye of Skadi, hit enemy and then apply fear with first skill, hero moves with his move speed without any reduction. 

Also tested with Warlocks 3rd skill, it also does not work 

### Example Match ID (and possibly Timestamp)

Tested in lobby

**Comment by TheUnholyWrath** [comment]
According to #7199 this is intentional

**Comment by shaileshgarg** [comment]
ALT spell tooltip says target is Unslowable, this is intentional.

You can  close the issue.

**Comment by UgbemugbemOsas** [comment]
sorry, my bad. did not see that
thanks a lot
