### ISSUE TITLE
Fog of war not working properly

### ISSUE THREAD

**Issue by osipovartem** [ValveSoftware/Dota2-Gameplay#7319]
### Description

After new patch enemy heroes instantly disappear in the fog of war, even after an attack, even if there are creeps nearby.

### Screenshots

![1](https://user-images.githubusercontent.com/59066880/223679390-4205ab0a-f38c-4170-a6c8-f3f8809a5379.jpeg)
![2](https://user-images.githubusercontent.com/59066880/223679407-f3ea2bbf-64e8-4b37-b011-ed87d474c761.jpeg)
![3](https://user-images.githubusercontent.com/59066880/223679419-531a1d01-1078-4b6b-8799-f3bf85f9b95d.jpeg)
![4](https://user-images.githubusercontent.com/59066880/223679426-98712896-ffb7-4635-9413-a2aed2b1539a.jpeg)
![5](https://user-images.githubusercontent.com/59066880/223679430-0c09c134-9548-4ca5-90bf-28a43efa2700.jpeg)
![6](https://user-images.githubusercontent.com/59066880/223679436-f94700f3-1d4e-4b4c-b99d-4b1bc031853d.jpeg)
![7](https://user-images.githubusercontent.com/59066880/223679438-2c5a7e71-c3c8-45e3-b308-976eec90c1c1.jpeg)
![8](https://user-images.githubusercontent.com/59066880/223679445-335b6004-4652-44ab-a4ce-0aaceccac27c.jpeg)

**Comment by Jazzlook** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/7203
