### ISSUE TITLE
Audio is messed up after the 7.32e update. Audio artifacts on announcer/heroes responses

### ISSUE THREAD

**Issue by airuhelp** [ValveSoftware/Dota2-Gameplay#7320]
### Description

Audio artifacts appeared after the 7.32e update.
Sizzle sounds (https://www.youtube.com/watch?v=Rw8b4VFVHYA&ab_channel=Airu) appear on most of the responses.

### Screenshots

https://www.youtube.com/watch?v=Rw8b4VFVHYA

**Comment by commentator24** [comment]
when is the sizzle sound? i cant tell. sounds smooth to me

**Comment by airuhelp** [comment]
> when is the sizzle sound? i cant tell. sounds smooth to me

It may be that your headset does not catch these sounds. My headset is Sennheiser HD 2.20S

**Comment by JinNada** [comment]
My friend started complaining about this since the patch.  I keep my Game Sounds audio low but I immediately started hearing it as well when I turned it up some.

**Comment by mitkoyanev** [comment]
Can confirm, same crackly sounds. It's horrid.

**Comment by j0fflin3** [comment]
2 weeks and still no fix. Random sounds in game have big crackling noices. Fix asap please @valve

https://user-images.githubusercontent.com/128149685/225901426-a7647280-7a8c-4312-9b86-e869ea5b1724.mp4

**Comment by j0fflin3** [comment]
MY PC SPECS:

7950X, X670E - F ROG, TUF 4080 OC, Fully updated Win 11 + BIOS + Drivers, Tried Cloud II Headset + My main Realtek onboard speakers. Only DOTA 2 has this bug and started with last big update.

**Comment by exsinner** [comment]
Cant say i heard any crackling from the video, the only thing i heard from the video is just minor sizzling noise.. I believe I dont have this issue, I'm using usb dac Fiio K5 Pro ESS at 32bit 192KHz with HifiMan Sundara headphone

**Comment by j0fflin3** [comment]
> 

You can't be serious :D My cheap Cloud II can hear all sound sizzling and you saying "I only hearing normal sound with my expensive headset"? All people here and on Reddit, saying "I have same issue".

**Comment by exsinner** [comment]
> > 
> 
> You can't be serious :D My cheap Cloud II can hear all sound sizzling and you saying "I only hearing normal sound with my expensive headset"? All people here and on Reddit, saying "I have same issue".

Well, my headphone does 75000Hz max sampling rate and its just minor sizzling, that csound does sound more crakling like when I used my sony xm4 which only does 40000Hz/20000Hz at most.

**Comment by j0fflin3** [comment]
> 

I'm using regular gaming headset (HyperX Cloud II). And tried connect sound to my LG C1 TV. I can still hear that dirty noice effects. Game sound files are broken I think. You can check sound effects on this page:

https://dota2.fandom.com/wiki/Muerta/Sounds Please listen " Plays when a unit is silenced." sound effect. That one is terrible example for this bug :) After try that, please answer me again. Thank you.

**Comment by j0fflin3** [comment]
up

**Comment by j0fflin3** [comment]
Valve is need to fix this asap :(

**Comment by j0fflin3** [comment]
Still no fix in today's update :(

**Comment by airuhelp** [comment]
> Still no fix in today's update :(

best thing you can do for now is lower your sound in dota and send everyone with this problem to this issue ticket. With enough people they wont be able to ignore it at some point

**Comment by j0fflin3** [comment]
I believe. Valve will fix this bug in this week ^^

**Comment by j0fflin3** [comment]
still no fix

**Comment by airuhelp** [comment]
> still no fix
big unluck

**Comment by zacharyreese** [comment]
Still no fix sadge

**Comment by j0fflin3** [comment]
Today is new update, still no fix.

**Comment by j0fflin3** [comment]
up

**Comment by krdee1** [comment]
Still broken for me

**Comment by krdee1** [comment]
I was able to resolve my problems by upping my clock rate in my user pipewire.conf file and restarting pipewire. I commented out the 19200 line and replaced it with 48000.

`    ## Properties for the DSP configuration.`
`        default.clock.rate          = 48000`
`        #default.clock.rate          = 19200`

**Comment by j0fflin3** [comment]
> I was able to resolve my problems by upping my clock rate in my user pipewire.conf file and restarting pipewire. I commented out the 19200 line and replaced it with 48000.
> 
> ` ## Properties for the DSP configuration.` ` default.clock.rate = 48000` ` #default.clock.rate = 19200`

is this file editing safe? I don't want to get VAC BAN

**Comment by j0fflin3** [comment]
There is no file named as pipewire.conf in DOTA folder. Whatever, I will wait for fix - update from Valve.

**Comment by airuhelp** [comment]
> I was able to resolve my problems by upping my clock rate in my user pipewire.conf file and restarting pipewire. I commented out the 19200 line and replaced it with 48000.
> 
> ` ## Properties for the DSP configuration.` ` default.clock.rate = 48000` ` #default.clock.rate = 19200`

would be good if you could share the guide or solution with the rest of us :)

**Comment by krdee1** [comment]
At least, for me, the issue was not within dota. I was able to fix it by updating my pipewire config.
Pipewire is a commonly used audio service for linux. 

The user config for pipewire is at ~/.config/pipewire/pipewire.conf, but there a global config may be available in /etc/pipewire/pipewire.conf.d/

I don't know if any equivalent option is available in Windows, but you can try looking for more advanced audio drivers/settings and adjusting the clock rate/sample rate/rtc rate if you have the ability.

**Comment by zacharyreese** [comment]
Valve pls fix.
WIndows 10
Audio crackling on most sounds
Since muerta update

**Comment by j0fflin3** [comment]
Today I bought SteelSeries Artics Nova Pro headset. It's connected with 24 bit / 96 kHz support. Guess what. I can hear that terrible crackling noices still :D My Cloud II was conected to 16 bit / 44 kHz. I said myself "maybe quality headset can handle that noices". But no. Whatever. Cause of this sound bug, I found a great headset. Thanks Valve :D 🥇

**Comment by DiamondGallery** [comment]
The fact this hasn't been fixed yet is really disheartening. Please fix this Valve!

**Comment by noobschoolbus** [comment]
Is there a temporary fix for this? Every hero line causes extremely bad audio clipping

**Comment by j0fflin3** [comment]
> Is there a temporary fix for this? Every hero line causes extremely bad audio clipping

No bro. Random sound files are broken in game. I don't know how they will fix this. Because, not only new hero lines, all random sound effects are broken. They need to find alllllllllllll bugged files and need to replace with fixed versions. This looks like a huge problem.

**Comment by DiamondGallery** [comment]
I am on Windows 10 and may have found a fix (hopefully for more ppl than just me). I went to Windows settings and went to system -> sound. My normal output device is 'Speakers (High Definition Audio Device)' and I made sure that was selected as my output device, then chose device properties -> additional device properties. A new window will open with the properties for your output device and some tabs. I chose the Advanced tab and changed my Default Format setting from 32 bit, 48000Hz to 32 bit, 96000Hz and it fixed all of my audio popping/crackling issues with Dota.

**Comment by zacharyreese** [comment]
> I am on Windows 10 and may have found a fix (hopefully for more ppl than just me). I went to Windows settings and went to system -> sound. My normal output device is 'Speakers (High Definition Audio Device)' and I made sure that was selected as my output device, then chose device properties -> additional device properties. A new window will open with the properties for your output device and some tabs. I chose the Advanced tab and changed my Default Format setting from 32 bit, 48000Hz to 32 bit, 96000Hz and it fixed all of my audio popping/crackling issues with Dota.

This worked for me after a computer restart! Thank you so much!

**Comment by krdee1** [comment]
It sounds like we've clearly identified that the issue has to do with the PC audio device sample rate, regardless of platform. I hope that means valve will be able to push out a speedy fix for all users shortly.

**Comment by j0fflin3** [comment]
Is this fixed? Sounds look like clear to me.

**Comment by shaileshgarg** [comment]
In today's update all of muerta sound files were changed, and there were changes as well

**Comment by j0fflin3** [comment]
Thank you Valve! <3

**Comment by shaileshgarg** [comment]
can this issue be closed?
