### ISSUE TITLE
Muerta Q ability removes slows on the ricochet hit instead of slowing

### ISSUE THREAD

**Issue by MohsenEssa** [ValveSoftware/Dota2-Gameplay#7321]
### Ability name

Deadshot

### Description

in the spell description it says that it should slow heroes for 100% 0.5 secs (duration separate of the fear duration) but what happens is it completely removes slows of target. for example if enemy is slowed with diffu blade and u hit them with the ability they just run away full speed. teammates saving ppl with this spell more than killing them. at least stop the spell from removing slows this is such a grief.

### Example Match ID (and possibly Timestamp)

0

**Comment by yckmm** [comment]
The enemy being unslowable during the fear is intended, check the alt tooltip of the ability.

**Comment by MohsenEssa** [comment]
the slow is on the initial hit actually but still this would make the spell good only if you get too close to fear them into your direction and thats very hard for a ranged carry.
