### ISSUE TITLE
Hotkey Update Bugged Out Legacy Key

### ISSUE THREAD

**Issue by MangBaldo** [ValveSoftware/Dota2-Gameplay#7328]
### Description

Quick cast won't work with legacy key, instead, normal cast key would be a quick cast in default with "Per-item override". Most of the time legacy key users will have issues when new skills are added but this time it's different.

Btw, if somehow any devs read about this post, I really wanted to have specific hotkeys on each heroes for a very long time, but the courier and creeps skills are also bugged using legacy key.

**Comment by shaileshgarg** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/7190

**Comment by shaileshgarg** [comment]
This has been fixed, you can close the issue.
