### ISSUE TITLE
Bug - quickcast of character abilities does not work in the ability draft.

### ISSUE THREAD

**Issue by Rehted29** [ValveSoftware/Dota2-Gameplay#7330]
### Description

I played two matches in the ability draft, and in both matches the quickcast of the heroes' abilities did not work for me, although the bindings in the settings are just as fast. But the quickcast works with items in the inventory. In other modes, everything is fine.

### Example Match ID (and possibly Timestamp)

7049412866 all time

**Comment by PaddyVu** [comment]
Same here, even quickcast enabled, it stills cast like normal, not quick :(
