### ISSUE TITLE
[Visual Bug] Enigma light beam

### ISSUE THREAD

**Issue by Fjara-h** [ValveSoftware/Dota2-Gameplay#7333]
### Cosmetic Item Name

Armor of the Twisted Maelstrom

### Description

There is a light beam coming out of the back of enigma. I'm fairly sure that Armor of the Twisted Maelstrom is the cosmetic affected, but the other currently equipped cosmetics are Autographed World Chasm Artifact, Eye of the Twisted Maelstrom, Eidelon of the Twisted Maelstrom, and Taunt: Enigmatic Style.

### Example Match ID

7050738466

### Screenshots

https://clips.twitch.tv/GrotesquePlayfulEelDuDudu-fXAdgomurWqjuF6-

**Comment by Tumbert** [comment]
I have the exact same issue. The "beam" always points to where Enigma spawned and it gets longer as you walk away from there.

**Comment by shaileshgarg** [comment]
Can this be fixed already, too annoying to play and watch Pro games with this.

**Comment by Tumbert** [comment]
Still nothing?

**Comment by zeusyaaa** [comment]
why dont valve fix this? it's not funny

**Comment by Astiberon** [comment]
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/107125193/92fda0a1-75b2-4368-8ca8-aebce22a4565)

**Comment by Astiberon** [comment]
FIXED
