### ISSUE TITLE
Blade Mail now returns magical damage, which is blocked by BKB

### ISSUE THREAD

**Issue by david-simoes-93** [ValveSoftware/Dota2-Gameplay#7342]
### Item name

Blade Mail

### Description

Blade Mail mentions it returns the same damage type of the attack.

![image](https://user-images.githubusercontent.com/9117323/223849032-659e5707-5f0c-4d26-8d62-553c6a16128d.png)

However, it is now returning magical damage.

### Example Match ID and Timestamp

7049222137 26:30

**Comment by Philaeux** [comment]
No, blade mail returns the same damage type, but it doesn't not pierce spell immunity, even if it's physical.
In your example timestamp, clockwerk is attacked by a sniper using bkb, so he doesn't take any returning damage, even physical.
