### ISSUE TITLE
inventory items Quickcast is broke on legacy layout

### ISSUE THREAD

**Issue by izemar** [ValveSoftware/Dota2-Gameplay#7360]
### Item name

inventory 

### Description

game ignoring items on quickcast while legacy mode is on. temporary solution for my legacy brothers: use unit specific hotkeys and change it on your heropool like it was on legacy(don't forget about cour) - quickcast on items will work! it will take 5 mins max for 10- heroes. also you can bind some forgotten by developers skills like creep's ability on Clinkz(15 lvl talent) or aghanim punch on Tuskar by using this method(mister, who in charge for this section, pls fix this micro-bugs too! there is not so many skills unnamed on legacy, pls bro!)
thanks for supporting our club of perverts who rejects qwer-system, hope you will fix it soon!

### Example Match ID and Timestamp

-

**Comment by shaileshgarg** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/7190

**Comment by shaileshgarg** [comment]
This has been fixed, you can close the issue.
