### ISSUE TITLE
Pause debounce delay regression

### ISSUE THREAD

**Issue by Nyefan** [ValveSoftware/Dota2-Gameplay#7363]
### Description

Description: when multiple people on the same team attempt to pause simultaneously, the game pauses and then immediately unpauses

Expected Behavior: there is a debounce period between pause/unpause inputs on the same team

**Comment by deepvelocity** [comment]
Literally happens in every game. Please, fix

**Comment by acelery420** [comment]
please add a 1 second debounce, and maybe allow pausing after first blood

**Comment by dobacetr** [comment]
Why is this issue still present? This was solved a decade ago already, brought back by an update.
Bump, please.

**Comment by lozarian** [comment]
for the love of christ please fix this it's game ruining.
