### ISSUE TITLE
Aeon disk + duel Legion bug

### ISSUE THREAD

**Issue by douglased01** [ValveSoftware/Dota2-Gameplay#7366]
### Item name

Aeon Disk

### Description

In game time 34:00 when dueling with the legion against an aeon disk target, the duel cd when activating the aeon disk and 1s is this normal? It happened twice to me once playing against doctor and in this match against a Jugg. I tested it in training mode, it doesn't work.

### Example Match ID and Timestamp

7051272387 Min 34:00

**Comment by TheUnholyWrath** [comment]
After Aeon Disk activates, the hero will get a buff that provides 70% Status Resistance for 2.5s. When you cast duel into this, it makes it last for the ~1s that you were experiencing. Its not a bug, you need to cast duel before/after the buff actives or dispel the buff with a nullifier.

**Comment by douglased01** [comment]
> After Aeon Disk activates, the hero will get a buff that provides 70% Status Resistance for 2.5s. When you cast duel into this, it makes it last for the ~1s that you were experiencing. Its not a bug, you need to cast duel before/after the buff actives or dispel the buff with a nullifier.

I saw the replay at 0.25x and it was really cool to activate it when I used it on the 3 occasions!!
