### ISSUE TITLE
Item advance quick cast not working

### ISSUE THREAD

**Issue by kwnkwn2g** [ValveSoftware/Dota2-Gameplay#7381]
### Description

Quick application of items does not work. The ability to release the keys does not work. Please FIX!

### Screenshots

![qu7STpFSj6I](https://user-images.githubusercontent.com/121286612/224002372-9727b3ff-7a19-4a18-8dec-c15f3de9e76f.jpg)

![gcXJydCenS0](https://user-images.githubusercontent.com/121286612/223992209-a71e1de7-33bc-4efa-9ee6-83924cd4f74d.jpg)

**Comment by kwnkwn2g** [comment]
It doesn't work right! See:
![XOnsdSiN1xI](https://user-images.githubusercontent.com/121286612/223998706-a63a0048-3581-463a-a332-915dece904d8.jpg)
![zYjsZYeIYQQ](https://user-images.githubusercontent.com/121286612/223998721-ab91e0a5-f363-4e02-9f42-3eac5642dcec.jpg)

**Comment by kwnkwn2g** [comment]
This is how it should work! I pressed the button but the quickcast didn't work until I let it go!
PLEASE FIX!!!
![AgApLjncKLE](https://user-images.githubusercontent.com/121286612/223999222-0b95d3d7-4e4e-4333-849b-ba338d4f632d.jpg)

**Comment by kwnkwn2g** [comment]
#7190

**Comment by kwnkwn2g** [comment]
Valve, are you familiar with the problem?
Up topic

**Comment by voddov** [comment]
Same problem, please fix this!

**Comment by GigaTiddy** [comment]
![image](https://user-images.githubusercontent.com/126759443/224537843-99816d17-9318-4122-880c-b5cda7692126.png)

**Comment by shaileshgarg** [comment]
> ![image](https://user-images.githubusercontent.com/126759443/224537843-99816d17-9318-4122-880c-b5cda7692126.png)

Neutral don't work this way, they still on normal cast when doing this.
