### ISSUE TITLE
Quick Cast Items not working while Legacy Keys enabled

### ISSUE THREAD

**Issue by fenixf4** [ValveSoftware/Dota2-Gameplay#7412]
### Description

Since the new update, Items QuickCast stopped working when Use Legacy Keys is enabled.

Here is a quick screencast of the issue, you will see keys that I am pressing on the screen and also all of my options.
[https://www.screencast.com/t/L8nhUrOSdIz7](https://www.screencast.com/t/L8nhUrOSdIz7)

Same issues: #7360, #7329, #7316, #7243, #7220, #7204, #7194, #7397

Please fix

**Comment by shaileshgarg** [comment]
This has been fixed, you can close the issue.

**Comment by fenixf4** [comment]
Confirmed. Thanks
