### ISSUE TITLE
Pierce the Veil's transformation time and buff is applied at the same time

### ISSUE THREAD

**Issue by irismus** [ValveSoftware/Dota2-Gameplay#7420]
### Ability name

Pierce the Veil

### Description

Buff duration should be applied after the transformation duration (e.g. Alchemist's Chemical Rage).

Muerta's Pierce the Veil is applied at the same time, resulting a 0.35s duration less, overall duration of 5.65/6.65/7.65. Not sure if this is intended.

Thank you!

### Example Match ID (and possibly Timestamp)

n/a

**Comment by TheUnholyWrath** [comment]
This should have been fixed today
