### ISSUE TITLE
Multiple Monkey King clones in demo hero mode.

### ISSUE THREAD

**Issue by Dsfnctn** [ValveSoftware/Dota2-Gameplay#7422]
### Description

When you create enemy/ally Monkey King, then delete him, on fountain spawns a lot of MK clones, which can move/level up/die/respawn and etc.

### Screenshots

![2023-03-10_01-49-53](https://user-images.githubusercontent.com/127449188/224168140-40204134-3029-4922-b8f2-b73c3609ddf3.png)

**Comment by TheUnholyWrath** [comment]
#2760. Please close this issue
