### ISSUE TITLE
Game Crash after load of game // demo hero

### ISSUE THREAD

**Issue by threeceees** [ValveSoftware/Dota2-Gameplay#7429]
### Description

Game will crash without any error message after loading game // demo 

Tried every graphics settings possible
tried safe_mode // vulcan
tried reinstalling steam and game exe
tried updating graphics driver

Still does not work

**Comment by UnpopularOpinion** [comment]
can you provide a recording of what happened (with the dota 2 console open if possible) to help reproduce or observe the issue?

**Comment by threeceees** [comment]
error is solved from redownloading and installing:
i missed the part where i have to remove the dump files from the saved game folders within steam thats not uninstalled properly

**Comment by RabbitsRun** [comment]
> error is solved from redownloading and installing:
> i missed the part where i have to remove the dump files from the saved game folders within steam thats not uninstalled properly

I don't get it.

You said you tried to reinstall steam and game then didn't work.What's the difference between the reinstallings that fix it and not?

**Comment by RabbitsRun** [comment]
I'm in the same situation but without removing whatever the dump files. Just after 7.32e patch it keep crashing

**Comment by threeceees** [comment]
you should remove whatever is in the folder thats within /dota2 after uninstalling.

**Comment by RabbitsRun** [comment]
Removing and reinstalling steam works for me.It nearly drove me to buy one new card.money saved haha.
