### ISSUE TITLE
Control lockout during Hoodwink ultimate cast

### ISSUE THREAD

**Issue by Lostmaniac9** [ValveSoftware/Dota2-Gameplay#743]
### Ability name

Sharpshooter

### Description

Rare issue with Hoodwink ult where sometimes my controls disable completely during the ultimate. I cannot turn, I cannot manually release the ultimate, I am locked in place until it fires automatically. The only idea I have that causes this is casting her abilities in a certain order but I have no idea if that is correct. This has only happened to me three times in easily a dozen Hoodwink games.

In this particular timestamp you can see that I cast my stun, can the ult to the left a bit, turn to straighten out, but only turn so far and then hold the ult until it releases automatically. I was unable to turn anymore and was unable to fire it.

### Example Match ID (and possibly Timestamp)

6606770692 - 13:21

**Comment by LokeLok** [comment]
This was fixed back in June, you can close this.
