### ISSUE TITLE
Unselectable courier model

### ISSUE THREAD

**Issue by Luminance69** [ValveSoftware/Dota2-Gameplay#7430]
### Cosmetic Item Name

Eimer Hillburrow

### Description

The Eimer Hillburrow's model is unselectable. Began after 7.32e.

applies to the following `.vmdl`'s:
```
models/items/courier/mole_messenger/mole_messenger.vmdl
models/items/courier/mole_messenger/mole_messenger_lvl2.vmdl
models/items/courier/mole_messenger/mole_messenger_lvl3.vmdl
models/items/courier/mole_messenger/mole_messenger_lvl4.vmdl
models/items/courier/mole_messenger/mole_messenger_lvl5.vmdl
models/items/courier/mole_messenger/mole_messenger_lvl6.vmdl
models/items/courier/mole_messenger/mole_messenger_lvl7.vmdl
```
flying version unaffected

### Example Match ID

1234567890

### Screenshots

video showing the issue:
https://youtu.be/uBECYUMTnGs

**Comment by pantsuX** [comment]
gay was here

**Comment by korrozia666** [comment]
+1

**Comment by pinguluk** [comment]
How could that happen

**Comment by korrozia666** [comment]
What?

  
>Среда, 15 марта 2023, 11:30 +03:00 от Pinguluk ***@***.***>:
> 
> 
>How could that happen
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you commented. Message ID:  <ValveSoftware/Dota2-Gameplay/issues/7430/1469564841 @ github . com> 
 
 
--
Алексей .

**Comment by pinguluk** [comment]
> Алексей

I mean how did they messed up

**Comment by korrozia666** [comment]
idk how, sorry

  
>Среда, 15 марта 2023, 21:52 +03:00 от Pinguluk ***@***.***>:
> 
> 
>Алексей
I mean how did they messed up
—
Reply to this email directly,  view it on GitHub , or  unsubscribe .
You are receiving this because you commented. Message ID:  <ValveSoftware/Dota2-Gameplay/issues/7430/1470598953 @ github . com>  
 
--
Алексей .

**Comment by zanthous** [comment]
same issue 7160066957, its click box is to the bottom left of it somewhere a the start of the game and clicking directly on it doesn't work

**Comment by Nathanael-Valve** [comment]
Fixed in next update.
