### ISSUE TITLE
Lycans wolf skin bug

### ISSUE THREAD

**Issue by Shortsinabox** [ValveSoftware/Dota2-Gameplay#7432]
### Cosmetic Item Name

Winter Lineage Form of the Grey Ghost 

### Description

Lycan when using this skin and ulted, turns into a tiny little error message that cannot be targeted but can target others 

### Example Match ID

7052877499

### Screenshots

![lycans](https://user-images.githubusercontent.com/117139345/224221822-d2322589-1512-451c-8217-ffe465f81a0d.png)
![image](https://user-images.githubusercontent.com/117139345/224221825-2cf226c2-98f1-4ad3-b23b-cf6f023e9ac6.png)
![lycan](https://user-images.githubusercontent.com/117139345/224221830-fea5127c-c8ce-4d14-aa7a-ce69af3311e9.png)

**Comment by TheUnholyWrath** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/7327#issuecomment-1462813198 This issue has already been fixed, awaiting update.
