### ISSUE TITLE
unable to queue for matchmaking with the -dev or -tools launch option enable

### ISSUE THREAD

**Issue by topik13** [ValveSoftware/Dota2-Gameplay#7441]
### Description

cant play or match making

### Screenshots

![dota 2 error](https://user-images.githubusercontent.com/127509655/224329052-17a5e004-00c5-4d7f-82f7-0b5ba8eb8616.png)

**Comment by shaileshgarg** [comment]
This is intended to prevent cheating, remove them from launch options before queuing.

**Comment by topik13** [comment]
> 
THANK YOU! BIG HELP

![dota 2 errorg](https://user-images.githubusercontent.com/127509655/224330745-f77b4d14-6436-45a9-947a-7479c21ebe8a.png)

**Comment by Krisko12** [comment]
Were i can remove it

**Comment by Krisko12** [comment]
I don't know what i need to remove

**Comment by topik13** [comment]
> I don't know what i need to remove

watch youtube bro.

launch option is on steam

**Comment by Krisko12** [comment]
Thanks
