### ISSUE TITLE
enemy items viewable with the top bar player's hero icon

### ISSUE THREAD

**Issue by ChrisADR** [ValveSoftware/Dota2-Gameplay#7448]
Match ID: 7053868673

Hi I was playing today and noticed that I was able to view enemy hero's items even when they were hidden in fog, by clicking the hero's icon at the top of the screen. I was able to see all enemy hero's items and I was playing with a friend who also was able to see their items.

Best regards,

**Comment by Usera2** [comment]
Can also confirm this.

**Comment by TheUnholyWrath** [comment]
[Clicking on enemies via the top bar during a game will show their last seen location / inventory state](https://www.dota2.com/deadreckoning)
