### ISSUE TITLE
Quickcast not working with Neutral Items

### ISSUE THREAD

**Issue by AzimsTech** [ValveSoftware/Dota2-Gameplay#7449]
### Description

When playing Dota 2 and trying to use Quickcast with Neutral Items, the Quickcast function is always off and cannot be activated.

### Steps to Reproduce:

1. Launch Dota 2 Demo Mode.
2.  Enable Quickast
3. Obtain a Neutral Item.
4. Attempt to use Quickcast with the Neutral Item.
5. Notice that the Quickcast function does not activate.

### Expected behavior:
Quickcast should be able to be used with Neutral Items in the same way it can be used with other items.

### Actual behavior:
Quickcast cannot be activated with Neutral Items, rendering the Quickcast function unusable with them.

### Additional Information:
This issue only occurs with Neutral Items and does not affect any other items in the game.

### Video

https://user-images.githubusercontent.com/12103851/224474499-f0e1d4de-fe49-42df-bca6-c3ba54ef4419.mp4

### Screenshots

<table>
  <tr>
    <td rowspan=2><img src='https://user-images.githubusercontent.com/12103851/224474585-08d8e28e-59a6-4ffa-a9e1-88543a6ff8cc.png' title='Settings > Hotkey > Items > Per-Item Overrides  '></td>
    <td><img src='https://user-images.githubusercontent.com/12103851/224474603-33110849-e949-49c4-8bb7-61fb2a549254.png' title='Settings > Hotkey > Items '></td>
  </tr>
  <tr>
    <td><img src='https://user-images.githubusercontent.com/12103851/224470836-dbeda5c6-0964-4ce8-8ed4-a9baa68e0dd9.png' title='Settings > Hotkeys > Advanced Hotkeys > Hotkeys Options'></td>
  </tr>
</table>

**Comment by shaileshgarg** [comment]
Working fine for both Key Up and Key Down.

**Comment by AzimsTech** [comment]
> Working fine for both Key Up and Key Down.

show me your settings

**Comment by AzimsTech** [comment]
> Working fine for both Key Up and Key Down.
 
@shaileshgarg  show me your settings

**Comment by shaileshgarg** [comment]
![Screenshot 2023-03-11 121226](https://user-images.githubusercontent.com/26450759/224469571-2dd4bfc9-26bc-4e1a-931a-8aa520235a97.png)

![Screenshot 2023-03-11 121242](https://user-images.githubusercontent.com/26450759/224469575-c7983794-bb4f-4810-9e7e-a0f0fca7eb0b.png)
![Screenshot 2023-03-11 121331](https://user-images.githubusercontent.com/26450759/224469597-89bc2ffd-ced8-4bcf-88e0-52d6676b5934.png)


I can see that you have quick cast on Key Up by default and then you have changed everyitem to be Key Down except seeds of serenity. 

There is a issue https://github.com/ValveSoftware/Dota2-Gameplay/issues/7381, where changing the KeyUp/KeyDown per item doesn't work, maybe you are referring to this.

**Comment by AzimsTech** [comment]
@shaileshgarg I copied your settings 1 to 1, and now **all neutral items and normal items** are on Quickcast, regardless of any changes I make in the Settings (Per-item Overrides)


|  ![dota2_pvnPxmv1Ya](https://user-images.githubusercontent.com/12103851/224471246-c4ff33a0-385a-4f06-b0a4-e8a5967398f0.png) |   |   
|---|---|
|  ![dota2_ClrH46mrK3](https://user-images.githubusercontent.com/12103851/224471306-0b1fc89b-4b9c-450c-a93a-76a72f4b9b2d.png) |  ![dota2_xdH18rxZBb](https://user-images.githubusercontent.com/12103851/224471329-94e95c50-5d32-454b-9f30-c359debebce3.png)


---


> I can see that you have quick cast on Key Up by default and then you have changed everyitem to be Key Down except seeds of serenity.

It doesn't matter if I use Quickcast on Key Down or Key Up, both options result in a similar issue.

![dota2_bxfMdgW7Bu](https://user-images.githubusercontent.com/12103851/224470836-dbeda5c6-0964-4ce8-8ed4-a9baa68e0dd9.png)


> There is a issue https://github.com/ValveSoftware/Dota2-Gameplay/issues/7381, where changing the KeyUp/KeyDown per item doesn't work, maybe you are referring to this.

no.

**Comment by AzimsTech** [comment]
### Solution
 I was able to find a solution to this issue thanks to this Reddit [comment.](https://www.reddit.com/r/DotA2/comments/11pawu2/comment/jc0y41e/?utm_source=share&utm_medium=web2x&context=3)
Disabling and then re-enabling the item quickcast option resolved the issue.

https://user-images.githubusercontent.com/12103851/224649238-26f00e07-b396-48a9-b6e4-377d890f4d11.mp4

**Comment by solaris5000** [comment]
There is no way to set a quickcast bind in dota's menu, but you can fix it through cfg file

\Steam\userdata\%userid%\570\remote\cfg\dotakeys_personal.lst

and find  theese rows to fix your bindings, right here is quickcast and Alt-cast on key 4
```
"InventoryNeutral"
		{
			"Mode"		"1"
		}
		"InventoryNeutralAutoCast"
		{
			"Mode"		"0"
		}
		"InventoryNeutralQuickCast"
		{
			"Key"		"4"
			"Mode"		"1"
		}
		"InventoryNeutralQuickAutoCast"
		{
			"Key"		"4"
			"Modifier"		"ALT"
			"Mode"		"0"
		}
```

**Comment by JAspeling** [comment]
I mean, this still needs to be fixed. I am trying to understand why it's closed. 

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/5423967/09a1400a-3c46-44c4-b1db-ce3a69f4e6ec)

With my key setup on neutrals:
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/5423967/c30dbac6-d03d-4fd2-8779-b51d6f4b2093)

It works fine for all other items but not for neutrals. I'm guessing it's because the shortcut for the neutral is under the "Cast" section and, there is nothing to be set under the quick cast.
