### ISSUE TITLE
Teammates can drop item in game while u in dc 

### ISSUE THREAD

**Issue by gowthamang56** [ValveSoftware/Dota2-Gameplay#7460]
### Description

My teammates drop item ,before reconnect , there gab between full reconnect access your hero , i can link video clip, https://youtu.be/yOnXhQzXZMo

Pls fix , it s big gifing.item drop when u dc , i almost quit DotA it happen to me,

**Comment by shaileshgarg** [comment]
Hasn't this been in the game since when.
Not really a bug.

**Comment by gowthamang56** [comment]
I know it's not like bug, but u can  change right , before reconnect
teammates use my hero ,drop item , it good for players play this game?
Every game  i dc for 1 min , PPL use my hero drop item some where , i can't
play game , what is system?
