### ISSUE TITLE
HP from strength is being incorrectly calculated

### ISSUE THREAD

**Issue by abdullahkhalids** [ValveSoftware/Dota2-Gameplay#7462]
### Description

The Strength to HP formula is not what it should be. 

Example: A level 1 Magnus, with no items should have 200 Base HP + 25 Strength x 20 = 700 HP. 

But as can be seen in the following, screenshot from a Matchmaking game, the Magnus has 720 HP. 

![image](https://user-images.githubusercontent.com/2965278/224466376-2df370ce-29ca-479b-917a-2a8acecc3669.png)

Looking at a few other examples, the following formula emerges

200 + 20 Strength x 20 + (Total Strength - 20) x 24 + Flat bonus

We can see for the Magnus this results in

200 + 20 Strength x 20 + 5 Strength x 24 = 720 HP.

Here is another example

![image](https://user-images.githubusercontent.com/2965278/224466550-0948dd78-bc44-494b-bd94-2154195adee3.png)

Storm should have

200 + 81 Strength x 20 + 200 (Falcon blade) + 75 (Fairy trinket) + 250 (Level 15 Talent) = 2345 HP

However, Storm has

200 + 20 x 20 + (81-20) x 24 + 200 + 75 + 250 = 2589 HP

I cannot replicate this in an empty lobby. However, watching any live match inside Dota or Twitch stream yields these results.

# How to replicate
1. Enter a Matchmaking game.
2. Pick any hero and item combination with Strength greater than 20
3. Calculate the strength using above formulas.

### Example Match ID (and possibly Timestamp)

7054447469

**Comment by TheUnholyWrath** [comment]
![20230311165730_1](https://user-images.githubusercontent.com/46859977/224467908-9d873141-5172-49fc-8ae4-fe02c9e4c586.jpg)
Seems like base HP got reduced to 120 and every point of str gives 24hp, instead of str needing to be greater than 20 for str to give 24

**Comment by ErikHumphrey** [comment]
> 200 + 20 x 20 + (81-20) x **20** + 200 + 75 + 250 = 2589 HP

This 20 should say 24

**Comment by abdullahkhalids** [comment]
This has been fixed.
