### ISSUE TITLE
All cosmetic items in "Collection" leave trails when scrolled left or right, or when an item is dragged somewhere

### ISSUE THREAD

**Issue by kutaykartoz** [ValveSoftware/Dota2-Gameplay#7478]
### Cosmetic Item Name

All cosmetic items in "Collection"

### Description

All cosmetic items in "Collection" leave trails when the "Collection" tab is scrolled left or right, or when an item is dragged somewhere

### Example Match ID

Not Applicable, a Main Menu Bug

### Screenshots

![trail](https://user-images.githubusercontent.com/25235417/224493419-2aa69040-ca4f-4e9e-969a-991e36343226.jpg)

**Comment by ophee** [comment]
Same thing for ~3 weeks already: [screenshot](https://steamuserimages-a.akamaihd.net/ugc/2026096191578774377/8075C7203906DAB056669A6EB3D5F7131258668F/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false).

**Comment by shaileshgarg** [comment]
This doesn't seem to happen anymore, can you check.

**Comment by kutaykartoz** [comment]
> 

Sorry to say but sadly it is still happening , still not fixed yet.

**Comment by shaileshgarg** [comment]
What is your hardware config, HDD vs SSD, RAM, VRAM sizes?

Mostly seems like asset loading is slow, when loading happens for a lot of them at the same time.

**Comment by shaileshgarg** [comment]
I changed my game from SSD to HDD, I am able to reproduce the issue. Definitly a asset loading issue due to slow storage.

**Comment by kutaykartoz** [comment]
> I changed my game from SSD to HDD, I am able to reproduce the issue. Definitly a asset loading issue due to slow storage.

SSD : Samsung 970 Evo Plus 250 GB 3500MB/s Reading 2300MB/s Writing NVMe M.2
HDD : Seagate BarraCuda 2 TB 7200 rpm 256MB/s

(I don't have more detailled info or technical knowledge about what you asked.)

However; my Dota 2 is installed on SSD drive, and I have other friends who has this same issue.

**Comment by ophee** [comment]
Issue still there. Reproduced on two different devices within the same account.
1) AORUS 15 XE4 laptop
12th Gen Intel® Core™ i7-12700H (2.3GHz~4.7GHz)
NVIDIA® GeForce RTX™ 3070 Ti Laptop GPU 8GB GDDR6
GIGABYTE AG470S1TB-SI B10 (1TB)
16GB (2x8GB) 3200 MHz

2) Desktop PC. Can also provide specs if needed.

**Comment by SavePandas400** [comment]
Add me to the pile of users affected by that.

PC Specs : 
Samsung SSD 970 PRO 1TB
AMD Ryzen 5 5600X
2x8 ddr4 3200
B550 AORUS ELITE V2 
GeForce RTX 2060 SUPER

**Comment by shaileshgarg** [comment]
Could be related to inventory size.

**Comment by kutaykartoz** [comment]
> Could be related to inventory size.

It is not related to inventory size. My friends with less than 100 cosmetic items have the same issue.

**Comment by CarlDeanCatabay** [comment]
It's the same for me. Also, whenever I right click on an item, Dota 2 crashes.
![20230414223322_1](https://user-images.githubusercontent.com/2046679/232074363-b20edb8d-e74c-4606-9c4f-c728958826e8.jpg)

**Comment by Triberpunk** [comment]
My collection is the same

A bunch of cosmetics basically dont show up at all

Right clicking any of them crashes Dota2

**Comment by SavePandas400** [comment]
It's been months with this going on and we still have not a single answer. Updated (even tried downgrading to previous) drivers of gpu did nothing. Clean install of the game (on a new drive) did nothing . I keep on getting this weird bug shit in the degree that it's literally impossible to browse armory

**Comment by kutaykartoz** [comment]
> It's been months with this going on and we still have not a single answer. Updated (even tried downgrading to previous) drivers of gpu did nothing. Clean install of the game (on a new drive) did nothing . I keep on getting this weird bug shit in the degree that it's literally impossible to browse armory

Totally agree.. This stupid bug needs attention and fix ASAP

**Comment by ophee** [comment]
Not a single following up comment from devs for months. Issue is still there.
Busy with BattlePass probably.

**Comment by hackadlv** [comment]
I have the same problem and valve support just told me to post this issue at github. It has ben like 3 month from that.
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/53877687/17b1e5db-ad7a-4562-91e2-05cc29db9959)

**Comment by Triberpunk** [comment]
Having previously commented on this one, I assume with todays inventory overhaul (summer client update)

This issue can now be resolved, and makes sense why it was unfixed for so long
