### ISSUE TITLE
Vengeful Spirit Aghanim's Scepter Does Not Trigger on Death

### ISSUE THREAD

**Issue by Bjbrostoff** [ValveSoftware/Dota2-Gameplay#7489]
### Item name

Aghanim's Scepter

### Description

Vengeful spirit's aghanim's scepter illusion does not spawn after venge is killed. 

In this replay, vengeful spirit is killed and her illusion does not spawn.   Item is purchased ~18:34 (while dead), does not enter backpack before next death ~19:20.

I have two guesses for this bug:
1) Purchasing the scepter while dead encounters a logic failure in a trigger toggle that prevents a second illusion from being spawned when the illusion itself is killed.  Essentially a boolean state is improperly initialized (no flame, game is 11/10).

2) It appears as though being disabled by shadow shaman started an internal cooldown on the scepter.  I only judge this based on the fact that the item gets shaded white after shaman cast spells on me, this part could be behaving as intended.

### Example Match ID and Timestamp

7054450310 - 19:20

**Comment by TheUnholyWrath** [comment]
Aghs is an upgrade to Vengeance Aura. You need to have at least 1 skill point in it for the illusion to spawn

**Comment by Bjbrostoff** [comment]
100% accurate, surprised I didn't notice that.  Closing.
