### ISSUE TITLE
Dota 2 Lina new set cosmetic bug

### ISSUE THREAD

**Issue by CayenSrvt** [ValveSoftware/Dota2-Gameplay#7494]
### Cosmetic Item Name

Dead Heat Coronet

### Description

New Lina set has a bug that whenever you equip the set the head slot wont change anymore and the mask that she has stays on all heads. only changes if i equip arcana for head slot.

### Example Match ID

no match ID

### Screenshots

![Dota 2 Screenshot 2023 03 10 - 16 58 36 48](https://user-images.githubusercontent.com/127634847/224516165-a67b4b48-1a6f-4f6f-aa9f-0b3e44a125bd.png)
![Dota 2 Screenshot 2023 03 10 - 16 58 16 34](https://user-images.githubusercontent.com/127634847/224516178-1ee39285-538b-4952-b20c-5460342389d0.png)
![Dota 2 Screenshot 2023 03 10 - 16 58 23 43](https://user-images.githubusercontent.com/127634847/224516206-b86fccf6-eaa2-427a-8b60-769a7b2e9634.png)

**Comment by Aluerie** [comment]
The face paint is included in arms and in head pieces. 

You use arm piece at these screenshots so Ofc it's there. Not a bug.

**Comment by CayenSrvt** [comment]
Thanks for letting me know, its kinda weird for a arm slot to change the face too.

**Comment by ani917** [comment]
there is also a visual bug with the "Hellfire Insurgent Belt" item while wearing an arcane, please fix 

here you will find a screenshot - https://www.reddit.com/r/DotA2/comments/wjoxdc/hellfire_insurgent_belt_bug_with_linas_arcana/
