### ISSUE TITLE
Vengeful Spirit Swap Doesn't Cancel The CM Ultimate.

### ISSUE THREAD

**Issue by Lci-Gaming** [ValveSoftware/Dota2-Gameplay#7502]
### Ability name

Nether Swap. BUG.

### Description

Match ID : 7056516186
1st time : 17:05
2nd time : 21:16
when CM try to ULTI, and VS swap it, it doesn't cancel the chanelling spell.
![Capture1](https://user-images.githubusercontent.com/127652084/224531735-82792abf-1969-42fb-b5f4-7c131607faa1.JPG)
![Capture2](https://user-images.githubusercontent.com/127652084/224531739-bc08dd66-5fb7-4910-b47b-c76882049f26.JPG)

### Example Match ID (and possibly Timestamp)

7056516186 - 17:05, 21:16

**Comment by TheUnholyWrath** [comment]
#111. Please close this issue
