### ISSUE TITLE
Support Club purchase crashes Dota 2 client [macos]

### ISSUE THREAD

**Issue by tikhonov-aleksandr** [ValveSoftware/Dota2-Gameplay#7504]
### Description

Hello,

I would like to purchase a Gold Support Club package for the Cybercats team. However, when I click on the button to do so, the Dota 2 client crashes after a few seconds. A system report log appears, and I have attached it to this ticket for your reference. Could you please take a look and let me know what the issue might be?

BR
Aleksandr 

### Screenshots

![Screenshot 2023-03-12 at 15 05 51](https://user-images.githubusercontent.com/7353054/224535441-8e3bc88f-4b7f-43fe-8ad3-435d9f9f21be.png)
[report_dota2.txt](https://github.com/ValveSoftware/Dota2-Gameplay/files/10950416/report_dota2.txt)

**Comment by gabimoncha** [comment]
Hi. I think I'm facing the same issue when trying to buy any Hero item from secondary market
