### ISSUE TITLE
i can click on enemies icon at top screen and see their items

### ISSUE THREAD

**Issue by Curos-M** [ValveSoftware/Dota2-Gameplay#7516]
### Description

i dont know how exactly to do it, it just work when someone disconnected and paused the game

video : https://youtu.be/BMkJ82OAow0

### Example Match ID (and possibly Timestamp)

7056705475

**Comment by Aluerie** [comment]
read the patch and close this issue. 

![image](https://user-images.githubusercontent.com/33165440/224569142-b3fd2d9a-cbdd-493f-90a8-ef4a56b98b8d.png)
