### ISSUE TITLE
Experience bugged for 2 heroes on 2 waves at level 1

### ISSUE THREAD

**Issue by smqrblomst** [ValveSoftware/Dota2-Gameplay#7522]
### Description

At level 1 with 2 heroes you should both get to lvl 2 in 2 full waves. But currently both heroes will be at 238 experience instead of 240. And for some reason in demo mode it is 236 experience.
3 waves for 3 heroes nets 242 experience to each. So I am not sure if there is some bug with the first 2 waves.

Screenshot shows 8 last hits and 238 experience.

### Screenshots

![image](https://user-images.githubusercontent.com/13099446/224577698-9eb9a7e0-b8e8-447b-aa68-13ce7aa8f055.png)

**Comment by commentator24** [comment]
![image](https://user-images.githubusercontent.com/109324155/224581301-3f761815-7ef1-4396-87c5-5ce93e0740aa.png)

**Comment by smqrblomst** [comment]
> ![image](https://user-images.githubusercontent.com/109324155/224581301-3f761815-7ef1-4396-87c5-5ce93e0740aa.png)

Not sure what this comment suggests. But 1 wave is 240 exp. Hence 2 waves should be lvl 2 for 2 heroes.

**Comment by commentator24** [comment]
previously you need 230 xp so you level up. this time you need 240 so you dont...

1 wave is not 240xp. u get 3 melee 57xp and 1 ranged 69xp or something so its 220xp when shared by 2 ppl its 28 and 34 so you lose that 2xp maybe

**Comment by commentator24** [comment]
previously you need 230 xp so you level up. this time you need 240 so you dont...

when shared by 2 ppl its 28 and 34 instead of 57 and 69 so you lose that 2xp maybe

**Comment by smqrblomst** [comment]
> previously you need 230 xp so you level up. this time you need 240 so you dont...
> 
> when shared by 2 ppl its 28 and 34 instead of 57 and 69 so you lose that 2xp maybe

Which is a bug then

**Comment by TheUnholyWrath** [comment]
> And for some reason in demo mode it is 236 experience
Outpost gives 2xp

**Comment by commentator24** [comment]
oh yeah outpost xp/min. there u go the missing 2xp
![image](https://user-images.githubusercontent.com/109324155/224586729-d08e5b1c-fd62-42df-8ffa-0482e0934130.png)

**Comment by commentator24** [comment]
please close this issue
