### ISSUE TITLE
Muerta's 1st skill work wrong with eth blade

### ISSUE THREAD

**Issue by NepuPon** [ValveSoftware/Dota2-Gameplay#7539]
### Ability name

Dead shot

### Description

I played muerta in the test lobby and was surprised that the dead shot fear didn't slow the opponent down while in ghost form, regardless of the item or ability that applied the effect. Any other source of fear will not nullify the slow from ghost form (if it slows). Only with a dead shot it happens that the fear target of a dead shot is not slowed down. I doubt that this is such a feature, but other sources of slowdown do not work either. The screenshots show the debuffs imposed on the hero and his move speed. Under the fear of a dead shot, the speed does not slow down, although it should, because this is the same fear as the rest. In addition, it breaks the meaning of the movement slow from 2 skills, if the fear of a bullet removes the slow for the duration of the fear. 
![20230313175543_1](https://user-images.githubusercontent.com/127765193/224740278-5316b0eb-c61c-43cb-9968-65288a4dd3d7.jpg)
![20230313175553_1](https://user-images.githubusercontent.com/127765193/224740285-7ccabb7d-6801-4a42-aa98-846fc4e95de8.jpg)
![20230313175154_1](https://user-images.githubusercontent.com/127765193/224740365-f28400d3-fd2e-4008-88e8-efc08a93aaf2.jpg)
![20230313175121_1](https://user-images.githubusercontent.com/127765193/224740379-89d18ce8-2280-4802-9bd7-b45950c4060d.jpg)
![20230313175129_1](https://user-images.githubusercontent.com/127765193/224740383-0994e47d-95b4-428f-bb95-c75d0c8ed5da.jpg)
![20230313175149_1](https://user-images.githubusercontent.com/127765193/224740385-bff334ad-e12a-44c0-aebb-49196f14561b.jpg)

### Example Match ID (and possibly Timestamp)

ex. 7054223943 - 3.18

**Comment by yckmm** [comment]
Press alt and read the tooltip, it's intended.

**Comment by NepuPon** [comment]
Yeah. My bad )).

пн, 13 мар. 2023 г. в 18:23, yckmm ***@***.***>:

**Comment by commentator24** [comment]
i suspect dev lazy to fix and just add alt tooltip its intended :)))) hehe

**Comment by Aluerie** [comment]
Close the issue, if there is no problem.
