### ISSUE TITLE
[Legion Commander]Arcana+Silhouette (TP Scroll)

### ISSUE THREAD

**Issue by Astiberon** [ValveSoftware/Dota2-Gameplay#755]
### Cosmetic Item Name

Legion Commander Arcana

### Description

Wrong silhouette. The character's pose is wrong. One of the blades is under the feet.

### Example Match ID

-

### Screenshots

![image](https://user-images.githubusercontent.com/107125193/172636877-6d34f97f-79cd-406a-8a10-ed1b4663c919.png)

**Comment by shaileshgarg** [comment]
Did it fix?

**Comment by Astiberon** [comment]
> Did it fix?

Hello) Yes, I don't know when, but it was fixed. I just decided to check all my posts and see if they are up to date.
