### ISSUE TITLE
Source 2 Filmmaker is broken due to very recent update (2-3 days back?), likely in their cloth physics

### ISSUE THREAD

**Issue by videogameplayer909** [ValveSoftware/Dota2-Gameplay#7551]
### Description

Problem is honestly self-descriptive in the attached video. All heroes are basically glitched whenever transformed.

### Screenshots

https://user-images.githubusercontent.com/57112418/224869542-069544b1-95c9-4b65-a284-473b90a20445.mp4

**Comment by liamec** [comment]
I confirm the problem

**Comment by videogameplayer909** [comment]
> I confirm the problem

Great! Then I'd appreciate 'thumbs up'-ing the question so it gets prioritized :)

**Comment by mpunishm** [comment]
I said how to fix this here

#7597

**Comment by videogameplayer909** [comment]
UPDATE: Looks like the latest update fixed this problem for new SFM creations
But my older dmx files still remain messed up sadly :(
Luckily I had nothing complicated in the works, but this would've been really bad for someone that's been working on something for weeks/months to have their older files affected
![image](https://user-images.githubusercontent.com/57112418/226509581-20f5258a-7f55-4101-bfcf-7ffe0194c319.png)

**Comment by shaileshgarg** [comment]
I don't think it's possible for valve to fix the existing saves.

**Comment by videogameplayer909** [comment]
Aight well, I guess I can close it then
Sucks that it happened, but it iz wat it iz
