### ISSUE TITLE
Neutral items always got self-casted

### ISSUE THREAD

**Issue by michgreg1233** [ValveSoftware/Dota2-Gameplay#7605]
### Description

I don't know what's the problem with it. every neutral item that have active component. When i use it (single cast it), it always self casted instantly even when my smart double tap option is turned off.I cannot even target my neutral item ability to somebody else . My current hotkey for neutral is Alt-Z but when i change it to other hotkey, the problem still persist. Thank you

### Screenshots

![image](https://user-images.githubusercontent.com/53866843/225990156-07aefce4-13af-4d4a-a5a7-b80622176148.png)
![image](https://user-images.githubusercontent.com/53866843/225990198-e3ec2e6e-71c6-4dff-84f3-4787b691ecbf.png)

**Comment by shaileshgarg** [comment]
Tested with your setting, no issues. 

Does your "Z" key have double click issue?

**Comment by michgreg1233** [comment]
I actually fixed it but idk what's the problem. The way i did is turn on quickcast on some neutral then turn them off again.
