### ISSUE TITLE
Chines of the Inquisitor - Arms not working as intended with Arcana

### ISSUE THREAD

**Issue by muertalover** [ValveSoftware/Dota2-Gameplay#7612]
### Cosmetic Item Name

Chines of the Inquisitor - Arms

### Description

Problem is evident in the Screenshot, it works properly on one arm of the Arcana but isn't removed on other

### Example Match ID

7065882603

### Screenshots

![image](https://user-images.githubusercontent.com/128221852/226099691-68ced6aa-2d01-45c9-a520-08e74b4697b5.png)

**Comment by Aluerie** [comment]
Duplicate #5836

---
Please, close your duplicate issue and instead upvote the original one with "👍" reaction. Comment extra details if any.

And in future, first, use search to find out if the bug you want to report was already submitted by somebody else so you can upvote it and not clutter the repository with duplicates.
