### ISSUE TITLE
Dark Seer taunt does not have audio that it had during batlepass

### ISSUE THREAD

**Issue by AntohaY** [ValveSoftware/Dota2-Gameplay#7613]
### Cosmetic Item Name

More Than Mental Mass

### Description

Dark Seer taunt does not have audio that it had during batlepass. Usually taunts have some music or audio during taunt effect. Dark Seer taunt had one but it does not work anymore :(
It can be replicated in demo mode.
I provided Match ID, and I am using taunt right after camera pans to the fountain after loading screen.
Thanks!

### Example Match ID

7064988417

**Comment by shaileshgarg** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/6238 ?

**Comment by AntohaY** [comment]
> #6238 ?

Thanks, yeah, it seems that immortal head item "Insight of Forlorn Precipice" does 'break' taunt audio somehow. I think I will keep this open still, maybe it will be fixed sometime.
Thanks for your comment

**Comment by Astiberon** [comment]
FIXED

**Comment by AntohaY** [comment]
Thank you, have a nice day. I will close it now :)
