### ISSUE TITLE
Can't start arcade games by myself

### ISSUE THREAD

**Issue by Nekancito** [ValveSoftware/Dota2-Gameplay#7616]
### Description

I've been having this error/(bug maybe) for like a week now, everytime i try to start an arcade game with me as a host i get this *offline for maintenance* message and i literally can't play, if i join someone else's lobby it's fine. This happens with all of the arcade games, not only the one showing in the screenshot.

### Screenshots

![image](https://user-images.githubusercontent.com/128245700/226120558-44618806-ad38-4f32-815c-c4433d5f559b.png)

**Comment by ithasarms** [comment]
I've been having the same problem for the last two weeks. I haven't found a way to solve this. I run DOTA on linux. I don't know if that has anything to do with the problem. Hopefully somebody else jumps in with some information.
![2023-03-22T17:20:15,101862342-03:00](https://user-images.githubusercontent.com/82852995/227028574-db8c5ab0-eaf5-403f-906f-48eba7f553ba.png)

**Comment by Nekancito** [comment]
> I've been having the same problem for the last two weeks. I haven't found a way to solve this. I run DOTA on linux. I don't know if that has anything to do with the problem. Hopefully somebody else jumps in with some information. ![2023-03-22T17:20:15,101862342-03:00](https://user-images.githubusercontent.com/82852995/227028574-db8c5ab0-eaf5-403f-906f-48eba7f553ba.png)

Honestly i forgot about the post since no one was answering, i see you are also in argentina, try creating a lobby in the US servers, that should work
