### ISSUE TITLE
Wraith King Skeletons missing in Taunt: The king doesn't walks, He rules

### ISSUE THREAD

**Issue by shaileshgarg** [ValveSoftware/Dota2-Gameplay#7623]
### Cosmetic Item Name

Taunt: The king doesn't walks, He rules

### Description

Skeletons are missing in WK Taunt: The king doesn't walks, He rules.

![20230319003009_1](https://user-images.githubusercontent.com/26450759/226130595-b7a07258-20ce-420e-b210-fd7c0b055479.jpg)

### Example Match ID

-

**Comment by Astiberon** [comment]
![image](https://user-images.githubusercontent.com/107125193/228644191-1d107607-c6c2-4c66-9bb9-8a36975e69cd.png)

**Comment by Astiberon** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/107125193/235124046-983db336-6216-4e05-9d5a-d9d0cc7c2812.png)
