### ISSUE TITLE
Omniknight Shard passive AOE tooltip range affected by increased cast range. 

### ISSUE THREAD

**Issue by burnskull55** [ValveSoftware/Dota2-Gameplay#7639]
### Hero and spell

Omniknight - Degen Aura

### Description

Having increased cast range from ether lens or neutral items affects the tooltip aoe, does not affect gameplay in my testing. only a visual bug.

### Screenshots

![image_2023-03-19_114953947](https://user-images.githubusercontent.com/51763770/226183931-bcd8a49f-c0e3-4264-b8bc-9e0ba3aae48a.png)

**Comment by shaileshgarg** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/1712
