### ISSUE TITLE
Dark Ascension doesn't allow flying over Arena of blood

### ISSUE THREAD

**Issue by evilgoldy** [ValveSoftware/Dota2-Gameplay#7648]
### Description

Yesterday in ability draft game I picked up Dark Ascension and multiple time during game with active ultimate I wasn't able to leave enemy's Arena of Blood.

### Example Match ID (and possibly Timestamp)

7068385198

**Comment by TheUnholyWrath** [comment]
This change is deliberate and was made as a part of fixing issue #2307. If there is something inconsistent with flying abilities being able to pass over Mars' Arena, please either create a new issue or remake this one to be more specific. Otherwise please close this issue.
