### ISSUE TITLE
CAppSystemDict::LoadSystemAndDependencies() error

### ISSUE THREAD

**Issue by Halifay** [ValveSoftware/Dota2-Gameplay#7665]
### Description

After Muerta update the game started to have visual bugs. I then reinstalled game and now it doesn't even launch. 
My system is Ubuntu 20.04
Game tells to verify files as they are corrupted. Verification does not help.
Tried both default and beta Steam versions
Reinstalled Steam, Dota and various graphics libraries for them.
My only partition is ext4.
libva2:amd64 is installed systemwide
Other games are running fine. Either proton and native.
I can't find human readable crash logs to determine what could raise the error. I believe only Valve could read log from /tmp/dump/*.dmp, therefore I'm attaching one. 
[crash_20230321152109_2.zip](https://github.com/ValveSoftware/Dota2-Gameplay/files/11028364/crash_20230321152109_2.zip)

### Screenshots

First message
![Screenshot from 2023-03-21 14-32-59](https://user-images.githubusercontent.com/29117268/226611333-7cbf1819-821d-4c91-b54d-2fa8f115ec3c.png)

Second message
![Screenshot from 2023-03-21 14-33-51](https://user-images.githubusercontent.com/29117268/226611426-17e2ea31-d265-4145-9f21-39d289c676a7.png)

**Comment by shaileshgarg** [comment]
https://github.com/ValveSoftware/Dota-2, try posting the issue on this tracker.

**Comment by Halifay** [comment]
Thanks, this issue is solved.
