### ISSUE TITLE
Level 1 Spirit Lance causes Blink Dagger to Cooldown even if Templar Assassin has Refraction

### ISSUE THREAD

**Issue by tzukie** [ValveSoftware/Dota2-Gameplay#7670]
### Ability name

Spirit Lance, Refraction

### Description

I created four Phantom Lancer with each Spirit Lance level going up, level 1 Spirit Lance causes Templar Assassin's Blink to go on cooldown even if she has Refraction. I tried this with Level 2/3/4 Spirit Lance and it doesn't seem to cause this problem.

Video provided on [Reddit](https://www.reddit.com/r/DotA2/comments/11xpkdw/level_1_spirit_lance_causes_blink_dagger_to_go_on/)

### Example Match ID (and possibly Timestamp)

I just noticed it on Demo while finding a match

**Comment by TheUnholyWrath** [comment]
Please close this issue
