### ISSUE TITLE
Bugged Visual for Elder Titans Item: Ornaments of the Wyrmforge Shard back

### ISSUE THREAD

**Issue by tzyp** [ValveSoftware/Dota2-Gameplay#7672]
### Cosmetic Item Name

Ornaments of the Wyrmforge Shard back

### Description

A piece of the model is stuck to the ground wherever the hero had spawned at the start of the game.

### Example Match ID

7061022582

### Screenshots

![image](https://user-images.githubusercontent.com/128562220/226794300-74371584-6465-4e6a-bb92-d95d5a52903e.png)

**Comment by Astiberon** [comment]
FIXED
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/107125193/d94f1f21-ca70-425a-ac2f-0304a6ed585c)
