### ISSUE TITLE
is there recalibration issue if done at start of new season? win 3 lose 7 -380 MMR

### ISSUE THREAD

**Issue by commentator24** [ValveSoftware/Dota2-Gameplay#7685]
So i made a note on discord everytime i recalibrate.
last year I won 8 lost 2 and got 430 MMR. was super happy 👍 
![image](https://user-images.githubusercontent.com/109324155/227032031-045bf8a4-48cb-45ce-8591-5fd1cc4da9dc.png)
![image](https://user-images.githubusercontent.com/109324155/227032536-f7b00078-f0af-46c7-8c1f-1c14db3aa2c0.png)
my highest MMR was legend 3 in december as shown, then i've been losing a lot.
![image](https://user-images.githubusercontent.com/109324155/227027659-7e6ec51d-1ca1-432a-8496-453a16a66830.png)
This year I started recalibration at crusader 4 2080 MMR > crusader 1 1700 MMR as shown.
i prepared the same role mid all solo, mid only 10x, just like last year.
unfortunately in 3 of my calibration games my support DC....another 2 games my pos 1 DC. can't help it i guess. (there seem to be a lot of disconnects recently..?) I also DC few days ago and got abandon.
with L3WL3W2L win 3 lost 7 this means instead of losing -120 MMR I lost -380 MMR for 7 loss 3 wins, which make each game around +/-95 MMR per game. my id is 48546538

I don't really mind it, but I think recalibration formula should be changed. Currently I think it's a bit disheartening to expect going back archon 2 or 3 since I was legend 3 last season, but end up with the lowest MMR possible 😭 especially since can only recalibrate once a year. e.g. if peak mmr was legend 3 3400 and current mmr is the lowest crusader 4 2080, shouldn't recalibration 3 win 7 loss is expected to be around 30% of 1320 difference  / mmr lost? or would be nice if calibration is simply 2x or 3x MMR tokens, but -30 mmr as normal.

I hope developers can look into it, perhaps there's an error because it's a new season as well e.g. total games played not counted properly? or too sensitive or something because I played a lot. if nothing being done, don't worry then. i'll just save my recalibration towards the end of season next time

**Comment by Mullins22W** [comment]
This information is really helpful for who really needs this.  I am grateful to you and expect more number of posts like these. Thank you very much.

**Comment by shaileshgarg** [comment]
Recaliberation matches have higher MMR +- per match. So it looks fine.
