### ISSUE TITLE
Stuck at dire mid ramp

### ISSUE THREAD

**Issue by samboeyy** [ValveSoftware/Dota2-Gameplay#7693]
### Description

When you walk to the edge of the dire mid ramp, you will get stuck at the spot.

### Example Match ID (and possibly Timestamp)

7073359248 / 2:35 min 

### Screenshots

![pic](https://user-images.githubusercontent.com/76203656/227156666-481d05c8-b8db-46d9-a320-eabee1e6e0d2.jpg)

**Comment by Aluerie** [comment]
dup #7284

---

Please, close your duplicate issue and instead upvote the original one with "👍" reaction. Comment extra details if any.

And in future, first, use search to find out if the bug you want to report was already submitted by somebody else so you can upvote it and not clutter the repository with duplicates.
