### ISSUE TITLE
Dota plus. Impossible Initial Mission.

### ISSUE THREAD

**Issue by kr1v4** [ValveSoftware/Dota2-Gameplay#7752]
### Description

Hello, I purchased dota plus, I can't complete the initial mission, in which you need to click on the hero and open the "Trends" tab. I tried to open it several times on different heroes, but this task is still not completed, can you help?
As you can see in the screenshots, I opened the trends, but the mission was not completed.
my dota2 id for invite friends: 1031248134

### Screenshots

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/99667101/227931486-459227b6-07a5-4b19-9afe-31c503eab95b.png">
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/99667101/227931612-a34b8885-7ba4-4f94-9299-55b3b59e7bb7.png">

**Comment by Avarise831** [comment]
click any hero>trends

**Comment by Avarise831** [comment]
Heroes>click any hero>trends
