### ISSUE TITLE
Enemy Heroes’ Items are visible without any visions 

### ISSUE THREAD

**Issue by aldrinalindogan20** [ValveSoftware/Dota2-Gameplay#7753]
### Description

You can see Enemy Heroes’ Items without any visions or sight by just clicking enemy heroes’ icon on the top.

**Comment by Aluerie** [comment]
read the patch 7.32e - bug fix part

**Comment by aldrinalindogan20** [comment]
I just played right now and I’m pretty sure it’s still the same. Or maybe the bug fix is not yet deployed.

**Comment by Aluerie** [comment]
wdym ; this is intended, read the patch
