### ISSUE TITLE
[Pudge]Belt of the Jolly Reaver. Stretched textures.

### ISSUE THREAD

**Issue by Astiberon** [ValveSoftware/Dota2-Gameplay#7760]
### Cosmetic Item Name

Belt of the Jolly Reaver. 

### Description

During movement, the textures that are tied to the gun hanging on the back are stretched.

### Example Match ID

-

### Screenshots

![image](https://user-images.githubusercontent.com/107125193/228055916-f47e9979-a809-4967-8b68-8c196b58d855.png)

**Comment by saradean90** [comment]
Thanks  for sharing..

**Comment by Astiberon** [comment]
FIXED
