### ISSUE TITLE
[Windranger] Arcana+Songs of the Soulfinch Offhand.The quiver is hanging in the air.

### ISSUE THREAD

**Issue by Astiberon** [ValveSoftware/Dota2-Gameplay#7764]
### Cosmetic Item Name

Windranger Arcana+Songs of the Soulfinch Offhand

### Description

The quiver is in the wrong place.
![image](https://user-images.githubusercontent.com/107125193/228064710-cfc37ad3-fce8-4161-b4e9-428c97802652.png)

### Example Match ID

-

**Comment by TheUnholyWrath** [comment]
#7230
