### ISSUE TITLE
This bug happens to me multiple times a week

### ISSUE THREAD

**Issue by 444Raven** [ValveSoftware/Dota2-Gameplay#7770]
### Description

Guilde contracts just not working.
I've noticed that if you leave a game at the end(when ancient collapses) guild contracts just not count. But this game I didn't leave and waited untill the mvp screen

### Screenshots

![image](https://user-images.githubusercontent.com/100593119/228286791-2b18d0d7-0874-474f-9460-d99a719d7abf.png)

**Comment by Aluerie** [comment]
You need to win as well.
