### ISSUE TITLE
Reset the counter of games in the ranking

### ISSUE THREAD

**Issue by seakness** [ValveSoftware/Dota2-Gameplay#7790]
### Description

I played 8 games in the ranking, calibrated, but after 9'th match 7083647518 the counter from 1 game (remainder) was reset to 10.
my id - 1281998693

### Example Match ID (and possibly Timestamp)

7083647518

### Screenshots

https://media.discordapp.net/attachments/1069222634207846410/1090770508355747840/image.png?width=535&height=326

https://media.discordapp.net/attachments/1080832597011210242/1090771889183535155/image.png?width=1112&height=581
30.03.2023 00:47 ranking
27.03.2023 12:45-22:46 4 ranking games

https://media.discordapp.net/attachments/1080832597011210242/1090772032360288296/image.png?width=787&height=307
11.02.2023 16:00-17:09 2 ranking games

https://media.discordapp.net/attachments/1080832597011210242/1090772629906018435/image.png?width=783&height=288
25.02.2023 19:23 ranking

**Comment by shaileshgarg** [comment]
#7784
