### ISSUE TITLE
There is no delay after someone pauses to unpause

### ISSUE THREAD

**Issue by Poischich** [ValveSoftware/Dota2-Gameplay#7814]
### Description

When someone on your team pauses, there is no delay for you to unpause.

For example, if someone disconnects on your team and everyone rushes to pause, the input of each player registers: the game unpauses as soon as it was paused

It didn't happen this way before patch 7.32e
There was a buffer/delay after a pause was issued, meaning that the server didn't register the "pause" inputs from other players for 1 or 2 seconds

**Comment by TheUnholyWrath** [comment]
#7363
