### ISSUE TITLE
..Have been put in low priority for 30m and them, *find match* button is not, ever functioning to search for it... Any way.. Poossibruu!

### ISSUE THREAD

**Issue by feonji** [ValveSoftware/Dota2-Gameplay#7820]
### Description

...What's with this, apparently, 'Unsolved'.. Or.. 'Not resolved'.. Hm.. 'Indirectly..' Bug issue? @_@

..Have been banned for network issues in the past, still..
My reputation, untouched. Is.. similar.. to... ma 'main'.. soo.. waiting patiently... to fix my issue, alrdy...

### Screenshots

https://user-images.githubusercontent.com/129637924/229329030-68a20dd0-48a5-45cf-97c5-41d930d8b49b.mp4

**Comment by TheUnholyWrath** [comment]
Unselect All Pick. Please close this issue.
