### ISSUE TITLE
Disable help doesn't disable death seeker.

### ISSUE THREAD

**Issue by NAlexP** [ValveSoftware/Dota2-Gameplay#7826]
The devs working on this game either don't get paid enough or just don't give a shit. That's the biggest issue. Second one is visible in the title.

**Comment by AbyssalD2** [comment]
Same with Wolf Bite and Book of Shadows. Can't be disabled.

**Comment by shaileshgarg** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/328

**Comment by NAlexP** [comment]
closed as it no longer makes people ethereal
