### ISSUE TITLE
Some ORB-effects doesn't work properly with Monkey King's ulty (critical)

### ISSUE THREAD

**Issue by Parckes** [ValveSoftware/Dota2-Gameplay#7877]
### Ability name

Wukong's Command

### Description

First of all some Orb-effects images doesn't appear above the healthbar (i suppose, these are the ones who are bugged), when monkey king's soldiers hit someone, but that's not actually the issue. Some items doen't work properly with Wukong's Command, for example Desolator: when Somebody gets hit by wukong's command soldier (also by aghanim soldier) he doesn't get armour reduction, but gets debuff of Desolator, that reduces armour by !0!, and even if real MK will hit this creature, it will not still get minus armour, the debuff of desolator (that gives -0 armour) will just refresh. But if MK was the first who hit the creature (not the soldier) everythink works fine, soldiers will refresh Desolator with expected -armour. That's certainly a bug, because if soldiers are not supposed to reduce armour, then they would not refresh MK's Desolator and even if so, MK hits must have armour reduction, but they can't because of soldiers. Also what's interesting, everyithing works fine with Stygian Desolator (neutral item), soldiers reduce armour as expected. Also Eye of skadi works strange. The situation with sequence of attacks is the same, if MK hits first then everything is OK, but if soldiers hit first, target will get minus movespeed, but not minus healing, and similarly to Desolator, attacks of MK will not give the target proper debuff. This bug makes MK insanely weaker, even when fighting solo target, it can make some items of MK useless, since he cannot re-debuf the target with proper debuff, what to talk about team fights… And I was wondering why MK is so weak in this patch xD. Example match (with time) shows how items I stated doen't work, look at the AM. Thank you and have a nice day!

### Example Match ID (and possibly Timestamp)

7095283482 - 52:30

**Comment by TheUnholyWrath** [comment]
#440 #6705

**Comment by rovky544** [comment]
Do you know YouTube is a most loved video streaming platform? which you can make it more amazing with [YouTube ReVanced ](https://revancedapk.org/)app.
