### ISSUE TITLE
Elder Titan Earth Splitter not dealing any damage to enemy heroes

### ISSUE THREAD

**Issue by Qwertenx** [ValveSoftware/Dota2-Gameplay#7888]
### Ability name

Earth Splitter

### Description

Two heroes (Faceless Void and Axe) are getting exactly zero damage from Elder Titan's ultimate. First ultimate blown up on 72:54 and second one on 73:03. Void not getting damage can be explained by Backtrack, but for Axe there is no explanation.

### Example Match ID (and possibly Timestamp)

7097043382 - 72:54 and 73:03

**Comment by TheUnholyWrath** [comment]
Your Aeon Disk activated both times, all your damage was reduced to zero. Please close this issue.
