### ISSUE TITLE
Psychic Headband does not trigger Linkens Sphere

### ISSUE THREAD

**Issue by lvlyRyuzaki** [ValveSoftware/Dota2-Gameplay#7907]
### Item name

Psychic Headband, Linkens Sphere

### Description

Psychic Headband does not trigger Linkens Sphere

In Example match I tried as pudge to trigger linkens on lina, 

### Example Match ID and Timestamp

7098465562, 35:50

**Comment by Aluerie** [comment]
Intended, read patches.

7.30e

**Comment by lvlyRyuzaki** [comment]
> Intended, read patch 7.30e

ty
