### ISSUE TITLE
[Suggestion] Rework shop hotkeys.

### ISSUE THREAD

**Issue by someApprentice** [ValveSoftware/Dota2-Gameplay#7910]
### Description

The purpose of an every feature is to make some of the actions easier. The current usage of the shop hotkeys has some issues, which are partly mentioned in #1111 (and should be considered too) and I would like to extend this list and give an idea of how the usage of shop hotkeys could make it easier to buy items.
The advantage of using hotkeys should be the speed up and convenience of buying items, but the current implementation of hotkeys does not fit to this definition. I give you an illustrative example why it is so.

For example, to buy Aghanim's Shard, I need to press the `q[` key sequence. To reach the `[` key I need to move my right hand from the mouse to the keyboard. So what is the convenience and speed up of using hotkeys? I can just use search and hit `Enter` to buy an item while both of my hand are on the keyboard. That is, my point is that the usage of keys that are on the right side of the keyboard should not be used, and instead should be used the keys that can be reached with one hand, so the hands are always lay on the proper devices.

I suggest using the `qwerzxc` (maybe worth it to change the `c` key for secret shop to `t` and remove the `zx` keys for the side shops since they are no longer in DotA) and `asdfgh` keys to select the category as before and use keys from `1` to `5` to select a row and then to select an item/column. The hotkey labels should change accordingly.

So, now, in order to buy me Aghanim's Shard, I will need to sequentially press the `q41` keys, because it is on the 4th row and in the 1st column.

Thus, the speed and convenience of buying items will be greatly improved due the the fact that hands are always on the proper devices.

It is also necessary to mention that when using hotkeys, you cannot queue items in the quick buy panel (when using the Ctrl + Shift combination).

### Screenshots

I photoshopped the screenshots to show what I mean:

After pressing `w`  key, the support section should be selected and the item rows should be labeled
![shop_hotkeys_after_pressing_s](https://user-images.githubusercontent.com/6327801/230767425-309475a1-16d3-4b49-add5-e072a823385a.jpg)

Then, after pressing `w3` key sequence, the items/columns should be labeled accordingly
![shop_hotkeys_after_pressing_s3](https://user-images.githubusercontent.com/6327801/230767524-a09f07e2-0e5c-42c6-8e3e-fd33484ae164.jpg)

And then, after pressing `w31` key sequence, the Mekansm should be bought.

**Comment by Aluerie** [comment]
I don't have PC with dota installed for a week or two to check if it works fully 1x1 like you want, but as I say in #1111 you can edit `C:\Program Files (x86)\Steam\userdata\YOUR_DOTA_FRIEND_ID\570\remote\cfg\dotakeys_personal.lst` file to rebind these keys and make your desire come true. 

There is little chance Valve will update these hotkeys so you might be better updating them yourself.

**Comment by someApprentice** [comment]
> I don't have PC with dota installed for a week or two to check if it works fully 1x1 like you want, but as I say in #1111 you can edit `C:\Program Files (x86)\Steam\userdata\YOUR_DOTA_FRIEND_ID\570\remote\cfg\dotakeys_personal.lst` file to rebind these keys and make your desire come true.
> 
> There is a little chance Valve will update these hotkeys so you might be better updating them yourself.

Already tried that didn't work. Maybe it is because I'm on linux, but setting `dotakeys_personal.lst` shop hotkeys doesn't affect anything.

**Comment by someApprentice** [comment]
Closing due to it's a skill dependent action.

<ins>Almost</ins> every item can be bought without taking your other hand off the mouse, using search and the item's abbreviated name.

Ex. "Mek**ans**m", "Black King **Bar**",  "**Dagger**", etc.
