### ISSUE TITLE
Arc Warden Level 25 Talent: 40% Tempest Double Cooldown Reduction Not Working as Intended

### ISSUE THREAD

**Issue by stefanthe1ne** [ValveSoftware/Dota2-Gameplay#7916]
### Ability name

Tempest Double with 40% cooldown ulti talent on level 25

### Description

As the title says, the skill with the applied said talent does not work properly. 
-Tried reconnecting, didn't work
-Tried exiting/reentering the game, didn't work.
-I checked in demo heroes if the problem still persists, and it's still bugged as well.
-I asked my party members  after the match if they are experiencing the same problem and check it out on demo heroes, the bug still persists.
-To further note, the left level 25 talent (+12s Tempest Double Duration) works properly.

For fast reference:
Normal CD: 60/50/40
With talent: 36/30/24

Game was very tight and could've used the extra edge on the hero's ultimate and honestly, it could have been the deal breaker in the game. It was one of the many factors that led us to to lose the match and in all honesty, I didn't mind losing at the end cause we all experienced the "one more game" syndrome and gave us an insane 1 hour 30 minutes game.  Stuff was tiring.

### Example Match ID (and possibly Timestamp)

7100073247 - 46:30 until the end of the game

**Comment by TheUnholyWrath** [comment]
The talent gives the Tempest Double itself 40% Cooldown Reduction. It is working for me. The phrasing of the talent is a little bit confusing, if you want to remake this issue with a better idea for how it should be phrased to make it more obvious this is how it works you are welcome to. Otherwise you can close this issue.

**Comment by commentator24** [comment]
i tested this in demo hero. so basically what he's saying is when you just used the clone (still active) and level up that talent 40 sec does not reduce to 24 sec the next time the skill is ready -  still 40

**Comment by commentator24** [comment]
screenshot as proof - you can see here I leveled up all talents, cd still 40.
![image](https://user-images.githubusercontent.com/109324155/230805218-618c120b-3e54-4aea-a34a-be0a398b1775.png)
interestingly the clone is correctly shown as 24 sec cd, but not the real hero.
so it only works properly when you level up the talent when the ult is ready, not during cooldown. respawning etc still cause the cd 40 not 24

**Comment by commentator24** [comment]
the phrasing just a bit confusing, so basically your clone gets 40% cd to all skills. e.g. flux 9.6 sec instead of 16 sec on your clone only. it doesn't mean to reduce ultimate CD by 40% 40 to 24 sec cd (even though the clone show ult becomes 24 sec cd)

you can close the issue.

**Comment by stefanthe1ne** [comment]
Was it always like this? I feel like I've played games with the hero where I was taking advantage of the ulti cooldown of the main hero. 

Indeed, that does sounds better. Rephrasing it would be a nice touch or an added tooltip in the level 25 talent.

Thanks for the responses! I'll close this.
