### ISSUE TITLE
Inactivity Problem

### ISSUE THREAD

**Issue by thpndx32** [ValveSoftware/Dota2-Gameplay#7925]
### Description

two other teammates were afk since early minutes in game, and yet while i was waiting for our ancient to be destroyed moving my hero around since huskar and beastmaster didn't wanna play anymore i was detected as innactive, idk what i should do in this situation? since feeding or going lanes that end up on death can also result in some kind of ban from reports, just add a forfeit feature pls. this began from minute 4 or 5 with beastmaster not wanting to play anymore just because he died 2 times in lane

### Example Match ID (and possibly Timestamp)

7101954513

**Comment by commentator24** [comment]
at least now you know you get abandon if no xp within 5 min.
how are you immortal and don't know this? moving around in base has nothing to do to detect timer.
if scared of getting reported, can smoke and gain xp before 5 min up. e.g. go to jungle and kill 1 creep in 5 min? then afk again. or do it like beastmaster, afk in trees

you can close the issue.
