### ISSUE TITLE
Проблема с набором на Pudge (Doll of the Dead)

### ISSUE THREAD

**Issue by matveybliat** [ValveSoftware/Dota2-Gameplay#7928]
Поскольку денег на набор за 1800 рублей у меня нет, я покупал набор по частям это и дешевле и удобнее. Но как только я начал покупать этот набор по частям я заметил что я не могу надеть эти предметы на персонажа, у меня просто не показываются эти предметы в Dota 2, а в игровом клиенте стима у меня предметы появлялись. И теперь после того как я собрал все 5 частей набора я попытался одеть их на героя, но у меня не высвечиваются они в игре!!! И теперь я не знаю что делать, если продавать предметы то я получу горазда меньше за предметы чем отдавал.

**Comment by matveybliat** [comment]
и как мне это исправить?

**Comment by Aluerie** [comment]
You have to buy the bundled set.

**Comment by matveybliat** [comment]
за 1800?!?! а что мне делать с этими предметами которые я купил?? я же получу явно меньше денег

**Comment by matveybliat** [comment]
КАКОЙ ПАЛЕЦ

**Comment by matveybliat** [comment]
ЧТО МНЕ ДЕЛАТЬ С ПРЕДМЕТАМИ В МОЕМ ИНВЕНТАРЕ,
