### ISSUE TITLE
Etherealblade attibute dmg messed up

### ISSUE THREAD

**Issue by MartinMagino** [ValveSoftware/Dota2-Gameplay#7981]
### Item name

Etherealblade

### Description

I trie the item in Demo and it seems like i deals always around 300 dmg no mather how high the primary attibute is. Maybe it is intended but the tooltip is stil pre rework of e-blade 

### Example Match ID and Timestamp

any Match

**Comment by yckmm** [comment]
The damage is based on the **target's** primary attribute, not the user's. It's working as intended and the tooltip is correct as well.

**Comment by MartinMagino** [comment]
oh verry interesting on the german tooltip that is not rly clear. "Ihres Primäratributes" is dependent on the perspectiv.
1. "the game tells to me that 1,5 of my attribute is dealed as dmg"
2.  "the target takes 1.5 of its prim. attribute" 
to make it clear it should say: "... das 1.5-fache des Primärattributes des Ziels + 50 ..."

**Comment by yckmm** [comment]
The translations are done by community contributors, so they might be outdated or have errors. If you want to suggest a better translation you have to go to https://valve.crowdin.com/dota-2
