### ISSUE TITLE
Slark Depth shroud regen is double the Schadowdance regen

### ISSUE THREAD

**Issue by MartinMagino** [ValveSoftware/Dota2-Gameplay#7982]
### Ability name

Deph Schroud

### Description

when Slark is in Depthshroud his passiv ult effect is trigged twice (can you be twice as unseen? XD) so he has 320 hp regen onstead of 160.

### Example Match ID (and possibly Timestamp)

7109871148    - 29:23 min

**Comment by yckmm** [comment]
duplicate #1643, you should close this.
