### ISSUE TITLE
[Elder Titan] Earth Splitter can be cast in such a way as to teleport enemies to its cast position.

### ISSUE THREAD

**Issue by ExplodedCow** [ValveSoftware/Dota2-Gameplay#7987]
### Ability name

Earth Splitter

### Description

Picked up via [this post](https://www.reddit.com/r/DotA2/comments/12oaj23/et_ult_bug_teleport_heroes_and_creeps_to_fountain/) on Reddit, which includes an in-game example (match 7109538508, at 37:30).

[YouTube video demonstrating the bug](https://www.youtube.com/watch?v=GaMTKPojxDA)

Elder Titan's Earth Splitter can be cast in such a way that enemies hit are teleported to the position it was cast from, rather than just pulled in towards the crack.
To do this, you need to cast Earth Splitter precisely on Elder Titan's current location. This can be achieved by giving him a move order in the direction you want to target, then shift-queuing Earth Splitter without moving the cursor.

**Replication Steps:**

- Create a custom lobby with cheats enabled, play as Elder Titan
- Spawn some enemy heroes in your base
- Level Elder Titan up to 6 and skill Earth Splitter
- Give Elder Titan a move order a short distance away in the direction you want the crack to go, then shift-queue Earth Splitter on the exact same spot (don't move the cursor between orders)

If done correctly, when the crack explodes, the enemies will be teleported to the point from which Earth Splitter was cast.

### Example Match ID (and possibly Timestamp)

7109538508, 37:30

**Comment by Avarise831** [comment]
#3677 similar problem bug

**Comment by nathank-valve** [comment]
This will be fixed in the next hotfix. Closing
