### ISSUE TITLE
Drow Ranger Markmanship Challenge

### ISSUE THREAD

**Issue by dubista1421** [ValveSoftware/Dota2-Gameplay#7989]
### Description

The challenge doesn't complete or trigger even if you proc markmanship while damaging heroes. This has been not working for years now! I came back to Dota and it's still not working.

### Example Match ID (and possibly Timestamp)

7110598209 - 15:00 onwards since I already have the Markmanship talent at this point I believe

### Screenshots

![image](https://user-images.githubusercontent.com/130931801/232338581-446f03da-6252-4195-b1bc-ea2fcfb3968a.png)

**Comment by Avarise831** [comment]
#5749   only counts with aganim's but the description says nothing)

**Comment by Avarise831** [comment]
#5749  only counts with aganim's but the description says nothing

**Comment by Avarise831** [comment]
#5749 only counts with aganim's but description says nothing

**Comment by Kinslayer666** [comment]
true

**Comment by dubista1421** [comment]
thanks, been years I didn't know this.
