### ISSUE TITLE
Lich Frost shield lvl 25 talent & holy locket heal amplification.

### ISSUE THREAD

**Issue by FilipC93** [ValveSoftware/Dota2-Gameplay#7991]
### Item name

Holy Locket

### Description

Even though holy locket states that amplifies heals you provide by 30%, it doesnt work on Lich's frost shield lvl 25 healing talent.

### Example Match ID and Timestamp

Any game you can check.

**Comment by irismus** [comment]
Not a bug, health regeneration and healing (health restoration) are two different mechanisms.

HP regen can be amplified by Sange but not Holy Locket, and vice versa. Hope this explains!
