### ISSUE TITLE
pudge doll cosmetic bug cant equip it 

### ISSUE THREAD

**Issue by hiro1010** [ValveSoftware/Dota2-Gameplay#7992]
### Cosmetic Item Name

doll of the dead set 

### Description

i have the entire set unpacket but cant equip it and doesnt appear on the screen, just on the armory and on the button part of the screen. is there a bug or what is happening? hope theres a solution to it 

### Example Match ID

1

### Screenshots

![pudge cosmetic](https://user-images.githubusercontent.com/130951404/232371761-3a2eb2fb-fb52-42a6-9750-ee1b67e482c7.jpg)
![pudge cosmetic 1](https://user-images.githubusercontent.com/130951404/232371767-d4566977-6a71-4de0-a189-06c09dce1d1a.jpg)
![pudge cosmetic 2](https://user-images.githubusercontent.com/130951404/232371968-f2308b48-fef1-49cc-882f-8f822ebf60d4.jpg)

**Comment by TheUnholyWrath** [comment]
If you don't already own the pudge persona you need to buy Doll of the Dead set as a bundle. Only unbundling the set will give you the persona you need to be able to use this set. This isn't a bug, please close this issue.
