### ISSUE TITLE
Clinz burning barrage is not effected by spellamp.

### ISSUE THREAD

**Issue by MartinMagino** [ValveSoftware/Dota2-Gameplay#7993]
### Ability name

Burning barrage

### Description

I tested cliz dmg output with his q.
It seems like spell lifesteal works on burning barrage and on searing arrows. => spell dmg.
spellamp. only inceases the dmg of searing arrows and not burning barrage.
so the total dmg output with s&k is higher than without but only about 9 dmg per arrow (16% of 60 searing arrow dmg) 

### Example Match ID (and possibly Timestamp)

any match

**Comment by cadaeic** [comment]
It's the other way round, Burning Barrage being able to proc spell lifesteal is a bug. #7744
