### ISSUE TITLE
Keeper of the Light Illuminate damage does low damage if a new one is channelled while the old one is mid-air.

### ISSUE THREAD

**Issue by xxwauroxx** [ValveSoftware/Dota2-Gameplay#7995]
### Ability name

Illuminate

### Description

If you shoot out an Illuminate, and due to having low cooldown can fire another one instantly. The 1st Illuminate takes the damage value of the 2nd Illuminate, which has barely charges. 

Example
0.00 - start casting illuminate #1
1.00 - Chakra magic kotl himself
3.00 - #1 is released
3.20 - start casting illuminate #2
3.50 - illuminate #1 hits target for the damage of the current charge in illuminate #2

At least that seems to be the case - i assume wouldn't be the intended way, but rather just how the spell is taking some charge value that resets when you charge a new one.

 

### Example Match ID (and possibly Timestamp)

7111415588 - 12:25 bot lane example

**Comment by TheUnholyWrath** [comment]
#304

**Comment by xxwauroxx** [comment]
> 

i missed this in my search before posting, sorry :)
