### ISSUE TITLE
error when reviewing an overwatch case

### ISSUE THREAD

**Issue by gaphriel** [ValveSoftware/Dota2-Gameplay#8024]
### Description

error when reviewing an overwatch case
more details in the picture

### Screenshots

![error dota](https://user-images.githubusercontent.com/131416118/233514603-443f18d7-dd29-4b8f-9b97-d2c487655812.jpg)

**Comment by LoveLessDev** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/8183

**Comment by Nathanael-Valve** [comment]
Fixed
