### ISSUE TITLE
Templar Assassin's Psionic Trap new autocast mode is not working as intended

### ISSUE THREAD

**Issue by IohanChristian** [ValveSoftware/Dota2-Gameplay#8053]
### Ability name

Psionic Trap

### Description

Templar Assassin's Psionic Trap new autocast mode is not working as intended.
The traps are being activated in a random order, no matter where the cursor is.
The intended behaviour is activating the trap closest to the cursor location.

This is the video proof I recorded in demo mode - https://youtu.be/yzZ5b7hHQD8

### Example Match ID (and possibly Timestamp)

https://youtu.be/yzZ5b7hHQD8

**Comment by flovnes** [comment]
When the trap ability is in the autocast state, it seems to detonate the lowest right one (relative to the map)
https://youtu.be/tCb1fGrZM20

**Comment by Aluerie** [comment]
Fixed, you can close the issue.

**Comment by rosshadden** [comment]
It is indeed fixed, thank you! It doesn't work with the minimap like her Aghanim's Scepter upgrade does unfortunately, but the game never claimed to so that's not a bug.

**Comment by Aluerie** [comment]
Opened #8675 for that request.
