### ISSUE TITLE
Legion Commander - Overwhelming Odds not autocasting on casting Duel

### ISSUE THREAD

**Issue by mdo111OCC** [ValveSoftware/Dota2-Gameplay#8075]
### Ability name

Overwhelming Odds

### Description

Overwhelming Odds isn't automatically triggered upon the Duel cast.
Skill is not on Cooldown, tested in Rank Game and Demo hero lobby.

https://streamable.com/k939s6

### Example Match ID (and possibly Timestamp)

7116684541 - 23:24

**Comment by a7xdnc** [comment]
if you spam Overwhelming Odds during a duel you also just keep casting and canceling the skill instead of casting it once and autoattacking. It shouldn't work like that.

**Comment by mdo111OCC** [comment]
Yes, and that stuttering cast problem too
I have it in the video but didn't mention. It's annoying.

**Comment by mdo111OCC** [comment]
Half fixed: no autocast on Duel, but instant Overwhelming Odds during Duel.
