### ISSUE TITLE
Eternal Shroud completely does not work on Medusa

### ISSUE THREAD

**Issue by Catastropherz** [ValveSoftware/Dota2-Gameplay#8088]
### Item name

Eternal Shroud

### Description

Eternal Shroud completely does not work on Medusa. The mana restore per spell damage taken does not work. Magic resistance number goes up but doesn't reduce magic damage at all. Other sources of magic resistance work fine.

### Example Match ID and Timestamp

https://youtu.be/odnRNVMPlzc

**Comment by seowth** [comment]
Regular [Cloak] doesn't seem to work as well, I just tested by casting the same spell on Medusa with:
1) No Cloak, no Eternal Shroud
2) With Cloak, no Eternal Shroud
3) No Cloak, with Eternal Shroud

Result: In all 3 cases, medusa takes the same amount of damage.

I tested using Grimstroke's [Ink Swell] & [Phantom's Embrace] for each of the 3 cases.

**Comment by AnanasSok** [comment]
In the first case you lost 1384->1200 = 184 MP and 10 HP. In the second case you lost 1228->1046 = 182 MP and 7 HP. 100*(1-(7/10))= 30% magic resistance. You took 7 HP damage and recovered 25% MP, 7*25%=1.75 MP. 
In my opinion, everything is correct. ha ha

**Comment by Zixell** [comment]
Yes, I tested the same but with Zues and it is seems to be an issue.

**Comment by CombatWorthyWombat** [comment]
I don't believe its an issue. The priority goes (dusa shield) -> (resistances) -> (HP bar).
The magic resistance works, it just only works on the damage let through from shield. All armor and magic resistance is essentially 98% less effective.
Its an intended feature - as illustrated by changes to eternal shroud's mana return priority.
