### ISSUE TITLE
Clicking on Watcher's "Lit" status crashes the game

### ISSUE THREAD

**Issue by LionKing10** [ValveSoftware/Dota2-Gameplay#8093]
### Description

MacBook Pro M1, macOS Ventura Version 13.3.1. Tested in lobby.

Clicking on Watcher's (new ward) "Lit" buff to check its duration results in throwing nullptr exception and crashes the game.

### Screenshots

<img width="848" alt="Screenshot 2023-04-21 at 10 45 53" src="https://user-images.githubusercontent.com/40217604/233575322-9dba5a58-5dfb-438b-b7d5-21e7c5e29638.png">

**Comment by sarunmrzn** [comment]
This literally can  be used as griefing, I told teammates about it and they kept hovering whenever I reconnected. it completely crashes my popOS

**Comment by AlexanderArvidsson** [comment]
Duplicate of https://github.com/ValveSoftware/Dota2-Gameplay/issues/8160

**Comment by LionKing10** [comment]
Duplicate post mentioned the issue was fixed. Closing.
