### ISSUE TITLE
Grimstroke's Dark Portrait Illusion does not have 95% Magic Resistance

### ISSUE THREAD

**Issue by AnanasSok** [ValveSoftware/Dota2-Gameplay#8114]
### Ability name

Dark Portrait

### Description

Grimstroke's Dark Portrait Illusion does not have 95% Magic Resistance.
Illusion takes 319 damage (_125 * 3.5 * (1-0.27)_) when it should take 16 (_125 * 3.5 * (1-0.27) * (1-0.95)_).

![image](https://user-images.githubusercontent.com/66092930/233611290-cc128fb5-1340-428f-b30f-be664e9d380f.png)

### Example Match ID (and possibly Timestamp)

I did not dare to buy it in a real game.

**Comment by AnanasSok** [comment]
This error is probably very difficult to correct. Bought in a real game, the illusion dies for a random skill. Grimstroke prays to Valve.

**Comment by DpRd745** [comment]
This is a serious bug. I wish they'll fix it as soon as possible.

**Comment by nathank-valve** [comment]
This will be fixed in the next hotfix. Closing
