### ISSUE TITLE
Harpoon Double Attack Bug

### ISSUE THREAD

**Issue by Janista20** [ValveSoftware/Dota2-Gameplay#8146]
### Item name

Harpoon

### Description

While holding 2 Harpoons
Hit 1 time to any creep/hero
Sell 1 Harpoon while the passive status is counting down

After the status finished counting down
Only 1 Harpoon that holding can make it always double attack

### Example Match ID and Timestamp

7117275285 - 12:35 - Ogre

**Comment by yonparas** [comment]
+1 on this bug as of 2023/04/21 11:04PM PHT

Monkey King bought 2 Harpoon and sold 1 after to proc double attack forever
![image](https://user-images.githubusercontent.com/35593434/233671077-8b29f3d1-f3e4-43be-974e-758739d29854.png)

Match ID: 7117620808
Match Time: 2023/04/21 10:00PM PHT

**Comment by aloata** [comment]
more:
match id: 7117718877
sven get max atk speed after that
![image](https://user-images.githubusercontent.com/12968808/233686522-f8bbf5c1-1dbe-4aea-9da0-14d4664842d8.png)

**Comment by stbennet** [comment]
https://www.youtube.com/watch?v=z8si-1QGmCw

**Comment by nathank-valve** [comment]
Fixed in the next hotfix

**Comment by KaneoHunter** [comment]
7118199575 another replay
