### ISSUE TITLE
[Omniknight] Fetters of Omniscience. Due to the removal of the ability, the immortal item has partially lost its feature.

### ISSUE THREAD

**Issue by Astiberon** [ValveSoftware/Dota2-Gameplay#8157]
### Cosmetic Item Name

 Fetters of Omniscience / Fetters of Omniscience of the Crimson Witness

### Description

suggestion:

- Change third ability icon
- Replace the visual effect of the slow applied by the third ability with the visual effect that was applied by the removed passive.

![image](https://user-images.githubusercontent.com/107125193/233648238-3b8bb0e8-c99d-4140-81bd-a1b28097bfa3.png)
![image](https://user-images.githubusercontent.com/107125193/233648086-3756d91e-2b25-401e-b2bf-a61a2fb7cea3.png)
![image](https://user-images.githubusercontent.com/107125193/233646544-3e33dd40-9a10-4255-b721-9810627b8a90.png)
![image](https://user-images.githubusercontent.com/107125193/233647615-00d75caf-a861-4468-9155-80b4f246286b.png)

### Example Match ID

-

**Comment by HappyKitty93** [comment]
dont let this down, please Valve check this! it's an expensive item

**Comment by Astiberon** [comment]
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/107125193/ca4b9371-a93e-47dd-b4d6-3651036499e4)
The ability effect has been updated, but the icon is still unchanged.
