### ISSUE TITLE
Bounty Hunter's [Track] puts [Phylactery] on cooldown without proccing the damage if the enemy is already affected by the Track debuff.

### ISSUE THREAD

**Issue by seowth** [ValveSoftware/Dota2-Gameplay#8166]
### Item name

Phylactery

### Description

- Axe correctly gets hit by Phylactery when Track is casted on him. Note that Axe did not have the Track debuff prior.
![20230421045541_1](https://user-images.githubusercontent.com/87141050/233656232-a3ab76f0-ac5d-4aac-b005-590f2c917827.jpg)

![20230421045541_2](https://user-images.githubusercontent.com/87141050/233656240-3ce63578-7875-4cd6-9213-6efbb6eb08be.jpg)

- Axe is now affected by track. With Phylactery not on cooldown, casting Track again puts Phylactery on cooldown but Axe is not hit with Phylactery's damage proc.
![20230421045549_1](https://user-images.githubusercontent.com/87141050/233656556-b9c06635-1990-41c5-9aee-d948c21b5dc5.jpg)

![20230421045549_2](https://user-images.githubusercontent.com/87141050/233656581-c4db067b-1fe6-4cce-8836-add499e93adb.jpg)

### Example Match ID and Timestamp

N/A - Tested in Demo mode.

**Comment by RediskaRnD** [comment]
fixed

**Comment by seowth** [comment]
Seems to indeed be fixed. Closed.
