### ISSUE TITLE
Silencer Int steal on Ogre Magi broken

### ISSUE THREAD

**Issue by DudeWhoShallNotBeNamed** [ValveSoftware/Dota2-Gameplay#8180]
When killing Ogre Magi as Silencer I got 1 Int at one point in the game. On consecutive kills there was no Int steal at all

**Comment by savijNx** [comment]
Ogre only has 1 intelligence even though he is meant to have 0 now - read the patch notes. 

So you will only get the 1 intelligence the hero has.

**Comment by LeTrash1** [comment]
This bug takes effect on the next kill and happened to me. The first kill I was a part of was Ogre in which I gained 0 permanent int as expected, however, it seemed to break my stat tracker for int stolen.
![image](https://user-images.githubusercontent.com/131720027/234389803-a851ca57-de45-47e8-ac2d-2a74b9481176.png)

Then on the next kill on the Monkey King in which I should've gained 2 permanent intelligence I only gained 1. Monkey did lose 2 int.
![image](https://user-images.githubusercontent.com/131720027/234389971-f8eb1d5b-2614-4908-9e30-241fc239d27c.png)

**Match ID**
7125237125 - Ogre kill: 6:15      Monkey King kill: 7:17

**Comment by LeTrash1** [comment]
I did more testing and it is repeatable in demo mode, if Slencer gains 0 int from Ogre before having any permanently stolen int then the next kill only counts as 1 instead of 2.

**Comment by nathank-valve** [comment]
This will be fixed in the next hotfix.
@LeTrash1 does your game crash in the Progress tab of the Heroes page, or did you mean the post-game relic progress screen?

**Comment by LeTrash1** [comment]
@nathank-valve was just a crash in post-game relic progress screen. After playing another silencer game the relic progress reverted to normal and no more crashing.
