### ISSUE TITLE
CNetworkGameClientBase::ReadEnterPVS():

### ISSUE THREAD

**Issue by MrPersival** [ValveSoftware/Dota2-Gameplay#8183]
### Description

Whenever I click on "Review Case" on "Overwatch case" I am getting an error and crash after the load screen.
Error code:
`CNetworkGameClientBase::ReadEnterPVS():
CopyNewEntity: invalid class index (1519), classname 'CTriggerBuoyancy'`

### Screenshots

![image](https://user-images.githubusercontent.com/41645021/233672721-ae32995f-d089-4c58-acf4-2b6e10a77fd9.png)

**Comment by Anon6669** [comment]
I have the same exact bug, I don't know why or how but it's pretty annoying.

**Comment by farhrenheit** [comment]
![image](https://user-images.githubusercontent.com/115539114/233695533-1c96bb5a-6cd5-4f23-a430-51700f5152d0.png)

**Comment by R4zarOx** [comment]
I have the same problem
![dota2_WEAIptl0SO](https://user-images.githubusercontent.com/128534887/233697776-2b7fa7b0-3b9d-4f85-bf7d-318badae174d.png)

**Comment by oheil** [comment]
Same here.
First review in 7.33 worked fine. With the second review the client crashes every time.

![dota_crash](https://user-images.githubusercontent.com/5408557/233700462-7f93bcfd-c81a-4a21-931a-ac7783d73a2f.jpg)

**Comment by TomRiddle1988** [comment]
i got the same problem and tried deleting bin folder and redownloading but didnt work there is 2 more issues thaqt are submited with same problem

**Comment by pontuslaestadius** [comment]
Boys do 'thumbs up' on the issue as that is the way issues are sorted by here.

**Comment by chromanite** [comment]
![image](https://user-images.githubusercontent.com/26741875/233794539-c962685a-7223-4d74-90e6-f2aa9a708331.png)
issue still persisting

**Comment by dilip-krishnan** [comment]
![image](https://user-images.githubusercontent.com/17922772/233798136-697d29f5-0db3-423f-8819-4dee9f3f2896.png)

Facing same error.!

**Comment by pontuslaestadius** [comment]
I'm counting maybe 50 of the same issue open right now. We could've had this post at 50+ thumbs up and actually have some traction on it.

(A lot of them are just incorrectly tagged with "ERROR" and no seachable terms. And they just post and forget about their ticket.)

https://github.com/ValveSoftware/Dota2-Gameplay/issues?q=Overwatch+sort%3Areactions-%2B1-desc

**Comment by farhrenheit** [comment]
By the way, Valve acknowledged about the problem, there is no reason to continue filling it up

**Comment by Nathanael-Valve** [comment]
Fixed.
