### ISSUE TITLE
Pure damage pierces templar assassin's refraction

### ISSUE THREAD

**Issue by Kapralis** [ValveSoftware/Dota2-Gameplay#8186]
### Ability name

Refraction

### Description

Having analyzed the matches before the patch, Templar Assassin calmly tanked any type of damage. But one in the new patch's match, whose ID is given below, Tinker's Laser calmly breaks through her refraction, and Timbersaw destroys her with absolutely any skill.

### Example Match ID (and possibly Timestamp)

7117361629 - 5:10 (Tinker) and 23:13 (Timbersaw)

**Comment by MayMour** [comment]
Refraction should block any type of dmg, its a bug and critical bug just lost match because of this.

**Comment by Aluerie** [comment]
Fixed, you can close the issue.
