### ISSUE TITLE
Mega Meepo Bug(s)

### ISSUE THREAD

**Issue by paaooo** [ValveSoftware/Dota2-Gameplay#8198]
### **Ability Name**
MegaMeepo

### **Description**

- *FIXED* Flinging a clone to an enemy will make it so that the clone will resume to its previous command after contact, instead of attacking the target, which was how the previous shard worked. This makes it a total pain since you have to select the clone only after contact because it's un-selectable with ctrl groups while it's mounted or while it's being flung.
- *FIXED* If you manta dodge your meepo clones, you permanently remove the meepoes dodged from the game.
- (Not sure if intended) Banish spells that are not your Dig ability cancels MegaMeepo, since Dig is intended. Abilities like Snowball, Astral Imprisonment, Undying Tombstone Shard, Disruption, and Manta (with the additional bug from above).
- *FIXED* From PandamanPete - If the main meepo dies while the transformation into MegaMeepo happens (while clones are going towards the main), you will keep the Fling ability for the rest of the game and be able to fling each meepo ONCE for the game. You will never get the transform ability back.

- Extra: It would be convenient if the clones are flung in chronological order (2nd then 3rd then 4th etc. If available) instead of the random order it collides with the main.
- Extra: The cast animation for flinging feels like an eternity since you would lose 2-3 hits flinging 1 or 2 clones so you could continue an Earthbind link (This might've been intended though).

**Comment by Neacroe** [comment]
Yes totally, very annoying. They should start autoattacking the target when they hit it, like ever other time you cast a spell on an enemy hero.

**Comment by PandamanPete** [comment]
Another here- if you die while meepos are being stacked then it breaks megameepo for the rest of the match

**Comment by voddov** [comment]
Another quality of life request, MegaMeepo hotkey should be R just like the Fling we had before, help us on this easy fix please.

**Comment by seanelius** [comment]
Just had an issue with one of the Meepos being deleted - looked like as one Meepo poofed in, just as the poof was finishing the new aghs ability was used but this deleted one. At least it looks like this is what happened, not 100% clear. Match ID 7118497929

**Comment by Bysees** [comment]
Incorrect calculation of damage from poof in megameepo form.

Example:
if poof = 100dmg, the damage done from:

just one meepo (1) = 100 dmg
MegaMeepo (2) = 100 dmg
MegaMeepo (3) = 200 dmg
MegaMeepo (4) = 300 dmg
MegaMeepo (5) = 400 dmg

So there is always not enough damage from one meepo

**Comment by Bysees** [comment]
Also autocast works in a very unobvious way in many little things

Starting with the fact that if you use poof with autocast during a megameepo form, then at the end of that form all the meepo starts farting back and forth.

Similar problem if you use fling after autocast.

Also, if you just use poof with autocast near any meepo and cancel it with ctrl + s (to interrupt poof on all meepos), and then use it again, the meepos start using poof differently. 

It's hard to explain, but it's obvious that this mechanism is crude and needs to be refined.

**Comment by TheChetu** [comment]
Not sure if this is a glitch or intended but Meepo also gets significantly healed when he goes MegaMeepo. All the Meepos can be nearly dead and he will just instantly have at least 70% MegaMeepo health.
