### ISSUE TITLE
DAWNBREAKER Attack

### ISSUE THREAD

**Issue by Valentyn-Lukashuk** [ValveSoftware/Dota2-Gameplay#8248]
### Ability name

STARBREAKER

### Description

When DAWNBREAKER buy Aghanim's Shard and use STARBREAKER , her attack dont have animation

### Example Match ID (and possibly Timestamp)

7118305788 - 16:46

**Comment by larsksu** [comment]
Yes, your normal attack animation stops working and your character just stands there. I think its only player client side.

**Comment by Valentyn-Lukashuk** [comment]
Don't think so, my teammates said they see the same.

**Comment by Valentyn-Lukashuk** [comment]
pls fix this one, imposible to play.
