### ISSUE TITLE
Ancient Thunderhide animation bug after attack

### ISSUE THREAD

**Issue by nikitabalomozhnov** [ValveSoftware/Dota2-Gameplay#8252]
### Description

After Medusa had used her skill MYSTIC SNAKE there is bug animation and sound bug like Thunderhide is trying to use its ability.

### Screenshots

https://user-images.githubusercontent.com/45919574/233732169-43895b43-94c6-4421-bf20-9e9837b85b98.mp4

**Comment by Aluerie** [comment]
you have `-wtf` on so it tries to cast it 24/7 because it can, not really a bug/issue semantics aside.

**Comment by nikitabalomozhnov** [comment]
Yeah! You're right. Thank you for answer!

**Comment by nikitabalomozhnov** [comment]
> you have `-wtf` on so it tries to cast it 24/7 because it can, not really a bug/issue semantics aside.

Yeah! You're right. Thank you for answer!
