### ISSUE TITLE
Megameepo causes other meepos to be removed after respawn

### ISSUE THREAD

**Issue by hernancarreras** [ValveSoftware/Dota2-Gameplay#8270]
### Ability name

Megameepo

### Description

If you die while in megameepo form grabbing all but one clone, all but the main meepo disappear when you respawn. I was using Manta Style and I also used the Dig skill in that short period of time. I don't know if it could be related.

Related to #8198
Similar to #8074  

### Example Match ID (and possibly Timestamp)

7118538288 - 37:00

**Comment by Dota-Exp** [comment]
Issue should be fixed in upcoming update. Thank you.
