### ISSUE TITLE
Got penalty after a game crash

### ISSUE THREAD

**Issue by guizanchett** [ValveSoftware/Dota2-Gameplay#8288]
### Description

Was finding a match and decided to review an Overwatch case while waiting. When the replay was loading, the game crashed. When I opened the game I was unable to play for 2 minutes due to excessive reporting, abandon or other negative behaviors.

This happened after the New Frontiers update.

Unfortunately I didn't get the crash error (I do have the crash dump, but don't know if that is useful). I'm also afraid of trying to reproduce again and my penalty being increased.

**Comment by LoveLessDev** [comment]
Assuming this is a reference to https://github.com/ValveSoftware/Dota2-Gameplay/issues/8183
