### ISSUE TITLE
Heroes disappeared from map

### ISSUE THREAD

**Issue by IsaacNewtonKim** [ValveSoftware/Dota2-Gameplay#8290]
### Ability name

Recall

### Description

I think it was the recall, not sure. Luna disappeared from the map and was unplayable. When kotl tried to recall luna she became unplayable. Riki hit kotl and became unplayable. When I say unplayable they disappeared from the map entirely, sent to the shadow realm. PLZ ICEFROG

### Example Match ID (and possibly Timestamp)

7118691805 around 48 49 minutes

**Comment by IsaacNewtonKim** [comment]
I think it might have been hurricane pike actually that caused it initially, seems like there was another similar bug

**Comment by IsaacNewtonKim** [comment]
Both the lich/kotl forced at the same time, maybe?

**Comment by TheUnholyWrath** [comment]
You can close this issue.
