### ISSUE TITLE
Forced to play match 4v5 (Immortal Draft)

### ISSUE THREAD

**Issue by SethDusek** [ValveSoftware/Dota2-Gameplay#8291]
### Description

I just played a match where one of the players in the lobby was not assigned to any team. He disconnected during the draft. Now the game is stuck on last-pick (instead of gold ticking down). Someone disconnected during the game and as captain the player I drafted got unselected. I selected him again, which I assume made the game think I had drafted 2 players when I had only drafted 1. 

Hopefully MMR is returned for this (match should be considered invalid)

### Example Match ID (and possibly Timestamp)

7118725527

### Screenshots

![image](https://user-images.githubusercontent.com/9436380/233757849-f832b0b3-82ec-4c3d-9339-3ea7e158a84e.png)
![image](https://user-images.githubusercontent.com/9436380/233758619-da471fe4-5973-4e27-b2ec-4380d145220c.png)

**Comment by nevinm** [comment]
I really hope they let people not pick players as well. This would counter picking toxic players. (Like EE in immortal bracket). That would get people to become better in the game.
