### ISSUE TITLE
Tranquil Boots breaking on non-player controlled units attack

### ISSUE THREAD

**Issue by mr795137** [ValveSoftware/Dota2-Gameplay#8292]
On the previous patch, this only breaks on hero/hero controlled units (druid's bear, np's treants, etc), this is also stated on the new frontiers update page

![image](https://user-images.githubusercontent.com/51732212/233759045-1ee1bc55-5933-458c-85df-c15bd7dc3068.png)

Now it breaks on creep wave attacks

![image](https://user-images.githubusercontent.com/51732212/233758728-35cdc2c2-2348-47d3-8852-8528a210cc60.png)

**Comment by commentator24** [comment]
huh? tranquil always break when you got hit by creeps dude.
it also cancel when you attack hero.

now that line similar to tranquil is about extra movement speed at night.. you get this bonus until you attack a hero or get hit
you just misunderstood it, you can close this issue
