### ISSUE TITLE
Overwatch error is crashing the game

### ISSUE THREAD

**Issue by ShinigamiGamingInc** [ValveSoftware/Dota2-Gameplay#8296]
### Description

As soon as the overwatch console is appearing im getting an error that freezes the game or just ends it.

### Screenshots

![Unbenannt](https://user-images.githubusercontent.com/112681867/233762022-cf3cbccc-b9bb-44d3-b1a8-8b06a875008b.png)

**Comment by pontuslaestadius** [comment]
Duplicate of #8183 please close and upvote the existing ticket.

**Comment by Nathanael-Valve** [comment]
Fixed
