### ISSUE TITLE
Riki's smoke cloud grants assists to Riki when allies die that have been inside it

### ISSUE THREAD

**Issue by Admiral-Billy** [ValveSoftware/Dota2-Gameplay#83]
Doesn't matter a whole lot for gameplay, but could end up skewing a TI prediction or something of the sort like the Dark Seer assist bug.

There are definitely more important issues to fix but hey, figured I'd drop it here!

**Comment by TheUnholyWrath** [comment]
This has been fixed. You can close this issue.
