### ISSUE TITLE
Zeus shard stopped working mid game, only worked with manta illusions

### ISSUE THREAD

**Issue by SovietElf** [ValveSoftware/Dota2-Gameplay#8301]
### Ability name

Lightning Hands

### Description

Halfway through the game, Lightning Hands no longer provided arc lightning procs for main hero, only for manta illusions. It was still working around 42 minutes but sometime between then and the 50 minute mark it just stopped. 

Match ID 7118787568 I was the Zeus

### Example Match ID (and possibly Timestamp)

7118787568 42:00-48:00

**Comment by commentator24** [comment]
it looks like shard stopped working when you lost then renewed well wishes buff. maybe conflict with witchblade too
![image](https://user-images.githubusercontent.com/109324155/233764851-de36922e-facf-4f2f-8918-563e7a94ad6e.png)

**Comment by mohammadakbar906** [comment]
I had the same thing happening to me in a game.

Ability name
Lightning Hands

Description
Between minute 21 and 22 Zeus shard Lightning Hands stopped working on the main hero. But it continued to work on manta illusions. This was the case for the entire game.

Example Match ID (and possibly Timestamp)
7124103068 - (21:00 - 22:30)

**Comment by TheUnholyWrath** [comment]
Turning off the auto cast on Lightning Hands disables the ability. If you think that this is working incorrectly you should make a new issue regarding its functionality or remake this one. Otherwise, you should close this issue.
