### ISSUE TITLE
Phylactery does not impose an effect on boulder smash

### ISSUE THREAD

**Issue by Ampioops** [ValveSoftware/Dota2-Gameplay#8304]
### Description

Lotus orb reacts to bolder smash, but phylactery does not (no damage and slowdown).

### Screenshots

![Снимок экрана 2023-04-22 105211](https://user-images.githubusercontent.com/99460994/233765659-96d54f12-29a5-4ba2-9b80-3d994644c396.png)
![Снимок экрана 2023-04-22 105410](https://user-images.githubusercontent.com/99460994/233765702-d2029de6-8a9a-4a23-b102-a8c75422bcdb.png)

**Comment by TheUnholyWrath** [comment]
This should have been fixed in the 7.33b patch, you can close this issue.
