### ISSUE TITLE
free meepo aghanims

### ISSUE THREAD

**Issue by CrazySnakeMan** [ValveSoftware/Dota2-Gameplay#8312]
### Ability name

megameepo

### Description

if you buy the meepo aghs, use the ability 'megameepo' then sell the item for full price and wait until the duration expires, you will get the ability for free. I only tested this in demo mode and in a private lobby so im not sure if the same interaction happens in a normal game.

### Example Match ID (and possibly Timestamp)

tested in demo mode + private lobby

**Comment by nathank-valve** [comment]
This has been fixed. Closing
