### ISSUE TITLE
Overwatch Review Case Error

### ISSUE THREAD

**Issue by alwayscommit** [ValveSoftware/Dota2-Gameplay#8316]
### Description

When you click on the "Review Case" button after downloading the gameplay, the attached screenshot shows the error that pops up each time.  
![dota 2 error](https://user-images.githubusercontent.com/59132376/233770854-b1d94f2c-00c4-4a5a-9a42-8d95d96471a3.png)

**Comment by pontuslaestadius** [comment]
Duplicate of #8183 please close and upvote the existing ticket.

**Comment by alwayscommit** [comment]
Duplicate of https://github.com/ValveSoftware/Dota2-Gameplay/issues/8183
