### ISSUE TITLE
Oracle False Promise ignore all damage reduction

### ISSUE THREAD

**Issue by Blob65** [ValveSoftware/Dota2-Gameplay#8326]
### Ability name

False Promise

### Description

False Promise ignore all damage reduction including Oracle lvl 10 talent (+10 false promise armor), fate's edict, all armor and magic resistence, all shield (pipe of insight...).
To be clear I am not talking about the burst a the end of the duration.

### Example Match ID (and possibly Timestamp)

test lobby

**Comment by Mabadman** [comment]
#8221, #8269, #8279

**Comment by Xenolzzz** [comment]
I found this bug too #8368

**Comment by Aluerie** [comment]
fixed, you can close the issue.
