### ISSUE TITLE
Dota Plus Hero Levels bugged out in Immortal matchmaking

### ISSUE THREAD

**Issue by sicarionox** [ValveSoftware/Dota2-Gameplay#8333]
(This is something I've only noticed in twitch streams, since I'm not Immortal myself, so if there's people in the rank who could confirm/deny this in the comments, it'd be highly appreciated.)

As it is right now, in Immortal matchmaking (the new player drafting system), only the "captain's" Dota Plus hero levels are visible. For everyone else, the level is not visible in the HUD, and post game it states that "you have reached level 1 on [hero]", as if the player played it for the first time. I am not certain if this is only a visual bug or if it actually affects hero level progression.

**Comment by Podnotthehacker** [comment]
I am playing in Immortal games right now and I can confirm it is NOT a visual bugs, I cannot use any voicelines nor my hero medal shows on top heroes portrait, all times when the game picks a captain to draft, they're the only ones who have hero level showing up.

**Comment by Moo000000** [comment]
I'm immortal and I noticed that this only affects my level 30 heroes (they are considered level 1). I can use voice lines on heroes below lvl 30.

**Comment by zopad** [comment]
I can confirm the same, some match IDs where 8 out of 10 players had no voicelines and dota+ levels: 7121214515 , 7121061064

**Comment by sicarionox** [comment]
Looks like this has been resolved with the latest patch, so I shall be closing this. Thanks, devs!
