### ISSUE TITLE
Meteor hammer bug not slow by 20% 

### ISSUE THREAD

**Issue by MijeMijan** [ValveSoftware/Dota2-Gameplay#8334]
### Item name

Meteor Hammer

### Description

Latest changes in meteor hammer mention that it will slow by 20% for 6 sec but no slow debuff applies to the enemy

### Example Match ID and Timestamp

N/a

**Comment by TheUnholyWrath** [comment]
This has been fixed. You can close this issue.

**Comment by MijeMijan** [comment]
fixed
