### ISSUE TITLE
tangos unable to be used (possibly veno specific)

### ISSUE THREAD

**Issue by derpbiscuits** [ValveSoftware/Dota2-Gameplay#8336]
### Item name

tango

### Description

https://youtu.be/B_HmNQUOAUA

here is the bug in action - using tango (hotkey and manually pressing it) does not activate it, makes veno turn to the last tree he cut, walks past it and then comesumes it (sometimes right past it, sometimes ~500 units away?)

does not happen with teammates' shared tangos

it's not just veno specific, happened when i picked pudge too

### Example Match ID and Timestamp

7119255192 -2523

**Comment by savijNx** [comment]
This may be due to using a custom map - if you have installed the map through the steam guide remove -temp_content launch option and use the original map and test again.

**Comment by derpbiscuits** [comment]
yeah it turned out to be a map specific issue, restarted with the default map and it was all okay
