### ISSUE TITLE
Aghanim's Shard not Dropped by Tormentor

### ISSUE THREAD

**Issue by pdzxc** [ValveSoftware/Dota2-Gameplay#8362]
### Description

Aghanim's Shard was not dropped by Tormentor upon being defeated.

### Example Match ID (and possibly Timestamp)

7119536016 21:18

### Screenshots

![image](https://user-images.githubusercontent.com/3389528/233790928-5c41d469-ca6c-47c9-a9fd-5697ec41a550.png)

**Comment by vrompasa** [comment]
Watched the replay, and wanted to add that Bounty Hunter (lowest net worth with Earth Spirit) is disconnected when the Tormentor is defeated. Maybe the dice roll tried to give the shard to Bounty and bugged because they were DC'd? The Tormentor just goes to 0 hp and keeps regenerating the barrier.

**Comment by TheUnholyWrath** [comment]
#8136

**Comment by TheUnholyWrath** [comment]
You can close this issue.
