### ISSUE TITLE
TA's Trap with Shard, autocast ON

### ISSUE THREAD

**Issue by NSurtsev** [ValveSoftware/Dota2-Gameplay#8371]
### Ability name

Trap

### Description

Trap with Shard and autocast ON should trigger the trap that is nearest to cursor, not TA herself.
But it is very unstable. It works like 15-20% of the time. 80-85% it still triggers the nearest Trap.
Fix it, please!

### Example Match ID (and possibly Timestamp)

Lobby

**Comment by artillicime** [comment]
It does follow a weird pattern, but it is not first to last nor the nearest... It is something else

**Comment by NSurtsev** [comment]
> It does follow a weird pattern, but it is not first to last nor the nearest... It is something else

It just works the old way, but 1 time out of 6 or more it suddenly works the new way as intended and again the old way.,,

**Comment by artillicime** [comment]
I've tried to put 4-5 traps each at its same location and changed my cursor of position. But it was ALWAYS following the same order and in my case the closest was the last to explode...
