### ISSUE TITLE
Dawnbreaker shard ruins all animations

### ISSUE THREAD

**Issue by floptropica** [ValveSoftware/Dota2-Gameplay#8384]
### Ability name

Starbreaker

### Description

When dawnbreaker buys the shard and uses starbreaker she immediately goes into a frozen T pose. She stays in this pose until the game is restarted. Even if game is restarted if you use starbreaker again she goes back to the T pose. 

### Example Match ID (and possibly Timestamp)

7120032340

**Comment by floptropica** [comment]
Also this can be replicated in demo mode. None of her running, idle or attacking animations work, when she uses celestial hammer, starbreaker, or her ult the animation is normal but then goes back to the T pose bug.

**Comment by shaileshgarg** [comment]
#8248
