### ISSUE TITLE
Riki smoke screen shard disables enemy global skills during smoke

### ISSUE THREAD

**Issue by yukoshen** [ValveSoftware/Dota2-Gameplay#8389]
### Ability name

Smoke screen

### Description

_Smoke Screen Shard description_ - Enemies caught in the smoke screen have their armor reduced by 7 and **cannot be targeted by their allies**.

[BUG]
Enemy global skills not working during smoke screen. Example: Centaur - Stampede, Chen - Hand of God

**Reproduction Step:**
1. Use smoke screen on any enemy
2. Enemy Centaur uses stampede in order for the ally to escape during smoke screen

**Expected:**
Stampede should effect on the smoked ally,

**Result:**
Stampede did not effect on the smoked ally.

### Example Match ID (and possibly Timestamp)

7120028790 - 22:25

**Comment by TheUnholyWrath** [comment]
This was fixed as part of the bug fixes attached to 7.33b. You can close this issue.
