### ISSUE TITLE
Immortal Party Que

### ISSUE THREAD

**Issue by Lightstruck** [ValveSoftware/Dota2-Gameplay#8397]
### Description

Immortal party que puts you both (in this case me and my friend were duo queing) in the captain draft pool, and the captain can separate both of you into two separate teams. This happened to me and it was super funny and weird, but I dont think its intended as this could be abused to MMR donate or share information to each other live by being on enemy teams. I hope this issue could be fixed soon. Proving my match data for the same. I was undying my friend was Lina ,
Match ID : 7120316680

### Example Match ID (and possibly Timestamp)

7120316680

### Screenshots

![image](https://user-images.githubusercontent.com/107354518/233805406-85149ac5-1e29-482c-ba1e-4871db4fa6e1.png)

**Comment by commentator24** [comment]
#8246 u can close the issue

**Comment by Lightstruck** [comment]
Closing because of #8246 duplicating it
