### ISSUE TITLE
Overwatch crashing while opening the game to review

### ISSUE THREAD

**Issue by juanqdt** [ValveSoftware/Dota2-Gameplay#8399]
### Description

Being assigned an overwatch case. Download the repetition, click on review. Opening the review crashed on loading screen. m

### Screenshots

![image](https://user-images.githubusercontent.com/13675334/233806144-62ea3899-7cc8-4ba1-a064-978b9f581af9.png)

**Comment by pontuslaestadius** [comment]
Duplicate of #8183 please close and upvote the existing ticket.

**Comment by Nathanael-Valve** [comment]
Fixed
