### ISSUE TITLE
Zeus Shard loses it's effect

### ISSUE THREAD

**Issue by Scquarn** [ValveSoftware/Dota2-Gameplay#8400]
### Ability name

Lightning Hands

### Description

Hello, 

I played a game with the new zeus shard. After attack a bounty hunter with lotus orb and killing him and hitting level 25 my lightning hands passive was no longer working.

There were no further zaps for the rest of the game :(

41:54 - fight with bounty
42:07 - passive no longer works for the rest of the game

### Example Match ID (and possibly Timestamp)

7120398396 - 42:07

**Comment by TheUnholyWrath** [comment]
#8301

**Comment by TheUnholyWrath** [comment]
Turning off the auto cast on Lightning Hands disables the ability. If you think that this is working incorrectly you should make a new issue regarding its functionality or remake this one. Otherwise, you should close this issue.
