### ISSUE TITLE
Nightstalker repeats his "night time end" responses whenever he enters a Void Zone

### ISSUE THREAD

**Issue by jlkj11** [ValveSoftware/Dota2-Gameplay#8416]
### Description

With his new Aghs, Nightstalker creates a Void Zone that acts as night even during the day. However, whenever he enters or exists the area, he uses one of the lines when normal night times ends. It gets pretty jarring after a while, especially considering how often Void can be used during a teamfight.

**Comment by shaileshgarg** [comment]
#8233
