### ISSUE TITLE
Bot matches degrades 25~50% of performance

### ISSUE THREAD

**Issue by wfzyx** [ValveSoftware/Dota2-Gameplay#8423]
### Description

Doesn't happen on demo mode. Only on bot matches, both on default and ranked ai.

I'm aware that having 9 more units consumes more rendering time, and having 9 bots consumes processing power - *but* this is still pretty heavy compared to previous patches.

### Screenshots

Demo:
![image](https://user-images.githubusercontent.com/5880370/233819751-9d60f23e-1ed4-4a84-a018-89795e88c29a.png)

Custom lobby
![image](https://user-images.githubusercontent.com/5880370/233819785-6b14387b-9e98-48c4-9f76-d0f32e7ec06f.png)

Bot match
![image](https://user-images.githubusercontent.com/5880370/233819830-9988e769-aebc-4bca-8b13-c4f1206576cc.png)

**Comment by Daar543** [comment]
Related #8189

I think the bots simply cannot cope with the new map, skills, items, so their algorithms for decision making are slower.
