### ISSUE TITLE
Cannot attack the tormenter

### ISSUE THREAD

**Issue by elbegnyamdorj** [ValveSoftware/Dota2-Gameplay#8434]
### Description

We were attacking the tormenter and it was almost dead. But at the last second when the tormentor should've been dead, we were no longer be able to attack the tormentor and it started healing its armor. We still couldn't attack it after the armor is full. The HP shows 0/1 which indicates the tormentor should've died but no shard has been given nor we can attack it once more.

You can see the armor is still regenerating and the hp shows 0/1 in the following screen shot

### Example Match ID (and possibly Timestamp)

7120328546, 24:24-24:40,

### Screenshots

![Capture](https://user-images.githubusercontent.com/94470595/233826509-cdfc287e-8c71-4df1-b731-8132e1fadc49.PNG)

**Comment by TheUnholyWrath** [comment]
#8136

**Comment by TheUnholyWrath** [comment]
You can close this issue.
