### ISSUE TITLE
Oracles "fates edict" not working in his "False promise"

### ISSUE THREAD

**Issue by Sirovich** [ValveSoftware/Dota2-Gameplay#8456]
### Ability name

False promise

### Description

If you use false promise and then gives fates edict. Target still receiving magic damage. So magic resistance not applied

### Example Match ID (and possibly Timestamp)

7121487551 - 17:06

**Comment by Luff1Lin** [comment]
faced with the same error

**Comment by Aluerie** [comment]
#8326

**Comment by Aluerie** [comment]
fixed, you can close the issue.
