### ISSUE TITLE
Harpoon and Force Staff sharing same cooldown

### ISSUE THREAD

**Issue by elbegnyamdorj** [ValveSoftware/Dota2-Gameplay#8468]
### Item name

Harpoon, Force staff

### Description

Force staff is not in the recipe of Harpoon yet they share the same cooldown. If it is not a bug, shouldn't it be specified in the item description?

### Example Match ID and Timestamp

tested in demo

**Comment by Daar543** [comment]
This kinda breaks the interaction with hurricane pike, i guess

**Comment by TheUnholyWrath** [comment]
#8353

**Comment by TheUnholyWrath** [comment]
You can close this issue.
