### ISSUE TITLE
7.33 Soulbind bind behaviour

### ISSUE THREAD

**Issue by KirmesBude** [ValveSoftware/Dota2-Gameplay#8469]
### Ability name

Soulbind

### Description

Grimstroke's Soulbind ability pierces Debuff Immunity (previously Spell Immunity), but the behaviour of the ability in regards to BKB has changed. In 7.32 all aspects of Soulbind still worked on BKB'd targets (both main target and nearby ally). 

The main debuff still gets applied, but the target no longer gets bound to nearby allies. If Soulbind last longer than BKB, the nearest ally is bound when BKB runs out. If the target uses BKB after Soulbind has been cast on it and an ally has already been bound, the bind persists. 
Binding to a new ally if the first one died behaves the same (if main target is BKB'd no new ally is bound). 
If the nearby ally has BKB active they do not get bound, which is also different to its behaviour from 7.32.

7.32 behaviour (See Match ID below as well):
https://youtube.com/clip/UgkxFAy48-zuP-1KSwD7w2mX76C3stQiYp6u (main target bkb)
https://youtube.com/clip/Ugkx6rOA5ykMwEmOFPHzf6VK9gdkdjPe4XJ6 (nearby ally bkb)

7.33 behaviour (See Match ID below as well):
https://youtu.be/_lqA5Ytmgyo 

Reproducible in Demo mode:
https://youtu.be/k1feW0RbxaU  (main target bkb)
https://youtu.be/P2fQgAjTQ80  (combat log + nearby ally bkb)

### Example Match ID (and possibly Timestamp)

(7.32) 7090235373 - 22:15/31:00; (7.33) 7120493031 - 41:05

**Comment by nathank-valve** [comment]
The new interaction is correct, Soulbind does not pierce debuff immunity. The flag in the ability tooltip will be fixed in the next hotfix. Closing

**Comment by joeph-narro** [comment]
> The new interaction is correct, Soulbind does not pierce debuff immunity. The flag in the ability tooltip will be fixed in the next hotfix. Closing

Should Grimstroke's ultimate really go from fully piercing BKB to nearly not at all piercing, as a result of a BKB _nerf_? And without even a patch note to notify people of the nerf? That's the biggest negative effect this BKB _nerf_ has had on a single ability. 

Plus it does still ignore BKB if it has connected to another hero. It's still the only leash that doesn't get removed when BKB is cast. Yet it has the same tooltip as other leashes (Cannot Be Dispelled, Pierces Debuff Immunity: No)
