### ISSUE TITLE
can be closed my bad

### ISSUE THREAD

**Issue by starryskies2** [ValveSoftware/Dota2-Gameplay#8470]
### Ability name

hammer of purity

### Description

omni went mid,he basically 2 shot most of our team via that combo,the hammer of purity into harpoon,for some reason it makes it trigger twice?i tested it with harpoon,and if thats how it supposed to work its quite powerful

### Example Match ID (and possibly Timestamp)

7121756887

**Comment by starryskies2** [comment]
nvm i saw the shard sorry

**Comment by commentator24** [comment]
you can close this issue
