### ISSUE TITLE
7.33 Invoker Shard still reduced Chaos Meteor cooldown 15s

### ISSUE THREAD

**Issue by Avarise831** [ValveSoftware/Dota2-Gameplay#8471]
### Ability name

Chaos Meteor

### Description

7.33 Aghanim's Shard Upgrade removed. Effect moved to level 20 talent 
but shard still reduced cooldown meteor from 55>40

### Example Match ID (and possibly Timestamp)

-

**Comment by rosshadden** [comment]
Please delete this issue :smiling_face_with_tear:
