### ISSUE TITLE
Losing Glimmer Cape's active buff

### ISSUE THREAD

**Issue by NotYourDope** [ValveSoftware/Dota2-Gameplay#8475]
### Description

Intended or not: when an enemy breaks through your active 300 magic shield from Glimmer Cape's active ability, you lose all buffs that were given with that ability (you are not longer invisible and increased move speed disappears). Not sure if that's an intended thing or not therefor ask for answer.
But if it is an intended thing I thing you should provide information in a tooltip

**Comment by nathank-valve** [comment]
This will be fixed in the next hotfix. Closing
