### ISSUE TITLE
Unable to watch live games

### ISSUE THREAD

**Issue by Momhadi** [ValveSoftware/Dota2-Gameplay#8476]
### Description

i'm not able to watch games through the "watch games" tab, although I can watch my friends live games normally.
My pc specs are good as well I'm running a 3080 and I7 10th gen . When I click watch in-game I get stuck in loading for 3 minutes then the game returns to the game menu.

**Comment by dobacetr** [comment]
Solution (work-around):
Go to options.
Switch your network quality from high to low.
Try to watch a game.
You can know return to high quality network.

**Comment by Momhadi** [comment]
lol that was a weird fix. it worked thanks
