### ISSUE TITLE
7.33 Slark does not retain his depth shroud if hit with muerta parting shot

### ISSUE THREAD

**Issue by Crazy-KSK** [ValveSoftware/Dota2-Gameplay#8482]
### Ability name

parting shot or depth shroud

### Description

when slark gets hit by muerta with her aghs ability parting shot slarks ghost form does not retain his shard ability depth shroud thus being unable to use it

to reproduce this use muertas aghs parting shot on slark equiped with shard and observe that depth shroud is missing from slarks ghost form

### Example Match ID (and possibly Timestamp)

tested in demo mode

**Comment by BradMuir** [comment]
cannot repro this one in demo mode. can you check it again? thanks!

**Comment by Crazy-KSK** [comment]
this seems to have been fixed at some point
