### ISSUE TITLE
Blur gets cancelled by new buildings

### ISSUE THREAD

**Issue by NAlexP** [ValveSoftware/Dota2-Gameplay#8483]
### Ability name

Blur

### Description

Blur gets cancelled by both twin gates and the lotus pools which seem to not be assigned teams.

Maybe get blur cancelled by enemy twin gate and neither pools, or maybe enemy pool?

I haven't tested for the barrier gates.

### Example Match ID (and possibly Timestamp)

/

**Comment by ohahaha00** [comment]
Blur also gets cancelled by watchers. Weird bug ngl.

**Comment by NAlexP** [comment]
> 

Only those activated by enemies. Those seem to work as intended.
