### ISSUE TITLE
Naga Siren Ensnare does not work on units slept by Song of the Siren if the Naga Siren has an Aghanim's Scepter

### ISSUE THREAD

**Issue by ybabts** [ValveSoftware/Dota2-Gameplay#8493]
### Description

Naga cannot cast Ensnare on units that are slept by Song of the Siren if she possesses an Aghanim's Scepter. If she drops the item she can then cast Ensnare on the slept unit, but cannot cast it with the upgraded version of Ensnare.

### Example Match ID (and possibly Timestamp)

7122361691 - 28:00

**Comment by TheUnholyWrath** [comment]
#8078
