### ISSUE TITLE
Templar Assassin's Refraction isn't blocking pure damage.

### ISSUE THREAD

**Issue by jlkj11** [ValveSoftware/Dota2-Gameplay#8501]
### Ability name

Refraction

### Description

TA's Refraction isn't blocking instances of pure damage.

![image](https://user-images.githubusercontent.com/120787118/233870142-fef326fd-8b72-4509-9048-a2b117b27c9b.png)

### Example Match ID (and possibly Timestamp)

none

**Comment by Aluerie** [comment]
#8186
