### ISSUE TITLE
Blood Grenade with sticky napalm 

### ISSUE THREAD

**Issue by Avarise831** [ValveSoftware/Dota2-Gameplay#8514]
### Item name
Blood Grenade
-

### Description
https://www.dota2.com/patches/7.33b
There are changes that didn't get into the game though were stated in the patchnote
work after 7.33b if hold skill point for sticky napalm used grenade and upgrade napalm extra damage still adding

### Example Match ID and Timestamp

-

**Comment by TheUnholyWrath** [comment]
Should have been fixed in 7.33b

**Comment by Avarise831** [comment]
work after 7.33b if hold skill point for sticky napalm used grenade and upgrade napalm extra damage still adding

**Comment by TheUnholyWrath** [comment]
#9016
