### ISSUE TITLE
Shiva's Guard dealing >1k dmg in a single hit

### ISSUE THREAD

**Issue by Litchio** [ValveSoftware/Dota2-Gameplay#8526]
### Item name

Shiva's Guard

### Description

Shiva's Guard dealt 1111 damage to a Jakiro with ~50% magic resistence in a single damage instance. Thats ~10x what it should have dealt. It's unclear why it dealt that much damage and other heroes recieved normal amounts of damage.

![image](https://user-images.githubusercontent.com/69739087/233942107-744090b9-7e87-4ce1-b6d6-cd8175a38f71.png)

### Example Match ID and Timestamp

7121815040 47:33.700

**Comment by TheUnholyWrath** [comment]
This has been fixed. You can close this issue.
