### ISSUE TITLE
DOTA 2 crashes when playing replay from earlier patches

### ISSUE THREAD

**Issue by MClondon123** [ValveSoftware/Dota2-Gameplay#8538]
### Description

DOTA crashes when playing a replaying from previous patch. Pop-up provides following error message:

CNetworkGamesClientBase::ReadEnterPVS():
CopyNewEntity: invalid class index (1519), classname 'CTriggerBuoyancy'

### Screenshots

![image](https://user-images.githubusercontent.com/46286109/234004134-1276b4bf-7aee-4ed9-9dc5-c0b6193613f2.png)

**Comment by CherryEx** [comment]
yeah same errors when trying to watch overwatch cases from previous patch

**Comment by Nathanael-Valve** [comment]
Fixed
