### ISSUE TITLE
Riki shard causes Pudge hook to miss

### ISSUE THREAD

**Issue by Amanoo** [ValveSoftware/Dota2-Gameplay#8548]
### Ability name

Smoke Screen

### Description

If Riki has a shard, Smoke Screen makes it so that enemies inside the smoke cannot be targeted by their allies. I took this to mean that targeted spells and items (force staff, glimmer cape, firesnap cookie) cannot be used on enemies caught in the smoke. However, abilities such as Pudge hook also miss, even though those are not target-based. Meat Hook just passes through the intended ally and will hook Riki instead. Instead of merely a saved ally, this results in a very dead Riki. 

It is possible that this is intended behaviour, but the wording "cannot be targeted" suggests that it applies just to targeted spells/abilities/items. 

### Example Match ID (and possibly Timestamp)

7122151183 - 24:30

**Comment by Petrie02** [comment]
Can't reproduce this in demo mode for some reason, Riki's shard prevents targeted abilities but Pudge's hook still functions as normal. This is possibly a replay bug and/or weird hitbox stuff going on?

**Comment by Amanoo** [comment]
> Can't reproduce this in demo mode for some reason, Riki's shard prevents targeted abilities but Pudge's hook still functions as normal. This is possibly a replay bug and/or weird hitbox stuff going on?

I could reproduce it in demo mode earlier today. I could hook through a whole group of allies. They must have fixed it between then and now.
