### ISSUE TITLE
Server crashes with Rubick stolen megameepo fling

### ISSUE THREAD

**Issue by vozhyg** [ValveSoftware/Dota2-Gameplay#8554]
### Ability name

Spell steal megameepo fling 

### Description

Spell stealen megameepo fling crashes the server
To reproduce:
As Rubick
1) Steal Megameepo as a rubick with Aghs.
2) Use Megameepo (which has no effect since there are no rubick clones)
3) Steal megameepo fling (as a second spell)
4) Use megameepo fling as rubick while under no visible effect from megameepo 
5) Server crashes. 
Note:
- Demo mode just crashes the game immediately
- Custom lobby crashes for all players with no ability to reconnect 
I assume same will happen with normal game.

### Example Match ID (and possibly Timestamp)

Haven't tested in actual game because well, meepos are rare.

**Comment by nathank-valve** [comment]
This will be fixed in the next hotfix. Closing
