### ISSUE TITLE
Spectre Shard Not Working as expected

### ISSUE THREAD

**Issue by revanthash** [ValveSoftware/Dota2-Gameplay#8562]
Spectre shard should reflect 100% damage dealt to her and leave her unharmed, but it is damaging her as well.

**Comment by revanthash** [comment]
I tried the above scenario in demo of spectre with sniper as an enemy

**Comment by leamare** [comment]
Quote from the patch note:
>  Only increases the outgoing damage, doesn't mitigate the incoming damage

Shard only increases the outgoing Dispersion damage. It is working as intended.

**Comment by TheUnholyWrath** [comment]
> Spectre shard should reflect 100% damage dealt to her and leave her unharmed, but it is damaging her as well.

the share increases the damage dealt by 100%, not to 100%. You should close this issue

**Comment by revanthash** [comment]
Thank you..
