### ISSUE TITLE
Relics on multiple heroes are grayed out since 7.33

### ISSUE THREAD

**Issue by zockolade** [ValveSoftware/Dota2-Gameplay#8570]
### Description

We invest a lot of shards and now relics are disabled

### Screenshots

![20230424224024_1](https://user-images.githubusercontent.com/11655186/234132707-d83cc62d-818b-4a14-b85f-998641ce9304.jpg)
![20230424224122_1](https://user-images.githubusercontent.com/11655186/234132720-4d7e1734-7849-4989-b306-313a2ba5a0da.jpg)
![20230424224151_1](https://user-images.githubusercontent.com/11655186/234132729-8480c70e-912f-4652-a1bc-de86beff3c7b.jpg)
![20230424224204_1](https://user-images.githubusercontent.com/11655186/234132737-566d30b8-a129-4512-80e8-b0b334bcbf7a.jpg)

**Comment by Aluerie** [comment]
Rofl, it just a colour for Universal heroes. Grayish kinda fitting since it's neither agi/str/int.

**Comment by zockolade** [comment]
> Rofl, it just a colour for Universal heroes. Grayish kinda fitting since it's neither agi/str/int.
> 
> I guess you can ask for a better colour like purple or something.

I see so that is what universal mean.

**Comment by zockolade** [comment]
By the way can we get the gray relics also displayed on the versus screens?
I guess that was what make me believe that something is broken.

**Comment by Aluerie** [comment]
Open a new issue with this problem. 

Maybe it will get attention and fix.
