### ISSUE TITLE
Phylactery possible bugs and unexpected interactions 

### ISSUE THREAD

**Issue by LeTrash1** [ValveSoftware/Dota2-Gameplay#8572]
### Item name

Phylactery

### Description

I went through every hero in demo mode and tested unit-targeted spells to see if phylactery was applying as expected these are the results I found:

**1. Seem to be bugged, not applying phylactery and only unit targetable spells**
Alchemist
	Unstable concoction (throw): Bugged
Dark Seer
	Ion Shell: Bugged, does not apply
Enchantress
	Little friends: Bugged, does not apply
Tusk
	Snowball: Bugged? Spell can only be unit cast but does not apply (items get muted in snowball so might be intentional?)

**2. Phylactery applying when point-targeted as well as being unit-targeted**
Earth Spirit
	Boulder Smash: Works even when point targeting the floor to move heroes
Lion
	Earth Spike: Bugged? Works even when point targeted
Sand King
	Burrow Strike: Bugged? Works even when point targeted

**3. Spells with point targeting and unit targeting and only applying when unit targeting (Working as expected but possibly imply .4 spells are not working as intended)**
Hoodwink
	Hunter's Boomerang: Works (Applies only if unit targeted)
Nature's Prophet
	Sprout: Works if unit-targeted
	Wrath of Nature: Works on first unit if unit-targeted

**4. Spells not applying phylactery when unit-targeting but can also be cast as point-targeted (Most of these skills do not pop linkens sphere)**
Death Prophet
	Crypt Swarm: Bugged? Spell can be unit cast but does not apply
Dragon Knight
	Breathe Fire: Bugged? Spell can be unit cast but does not apply
Jakiro
	Dual Breath: Bugged? Spell can be unit cast but does not apply
Lina
	Dragon Slave: Bugged? Spell can be unit cast but does not apply
Magnus
	Shockwave: Bugged? Spell can be unit cast but does not apply
Marci
	Rebound Shard: Bugged? Doesn't apply when jumping off enemies
Spectre
	Spectral Dagger: Bugged? Spell can be unit cast but does not apply
Tidehunter
	Gush: Works
		Aghs: Bugged? Spell can still be unit cast but does not apply
Tiny
	Toss: Bugged? Spell can only be unit cast but does not apply (even before talent)
	Tree Throw: Bugged? Spell can be unit cast but does not apply
Troll Warlord
	Whirling Axes (Ranged): Bugged? Spell can be unit cast but does not apply

**5. Other**
Hoodwink
	Acorn Shot: Bugged? Applies if unit targeted, but is an auto-attack so not a spell?

**6. No longer unit-targeted spells after AoE upgrade therefore phylactery is longer being applied. Probably working as intended but felt worth including based on other reports.**
Bristleback
	Nasal Goo: Works 
		Aghs: Breaks, no longer unit targetable
Lich
	Sinister Gaze: Works
		Aghs:  Breaks, no longer unit targetable
Lion
	Hex: Works
		25 Talent: Breaks, no longer unit targetable
Night Stalker
	Void: Works
		Aghs: Breaks, no longer unit targetable
Queen of Pain
	Shadow Strike: Works
		Aghs: Breaks, no longer unit targetable
Silencer
	Last Word: Works
		Aghs: Breaks, no longer unit targetable
Zeus - EXCEPTION
	Lightning Bolt: Works
		25 Talent: Still works

### Example Match ID and Timestamp

Demo hero mode
Fixed:
Dazzle
	Shadow Wave: aghs upgrade does apply

**Comment by commentator24** [comment]
@LeTrash1 should close issue, i updated it on #12590
alche, ds, ench, marci, tusk works now
lion, sk, tide no longer works
maybe you can comment on mine if i missed any hero

**Comment by phreeghow** [comment]
Silencer
Last Word: no longer works
