### ISSUE TITLE
Roshan walking to gate will return to pit if stunned

### ISSUE THREAD

**Issue by commentator24** [ValveSoftware/Dota2-Gameplay#8577]
if you stun roshan while it walks to gate, it will return to its pit as shown
in this case it was stunned by sniper assassinate i think. ID 7124113553
![image](https://user-images.githubusercontent.com/109324155/234144058-b98a9207-3d0f-4599-b73a-d6ec8f779d3a.png)

**Comment by trey-jones** [comment]
Probably related: Roshan turned around to kill Skeletons from Clinkz, then stayed on the wrong side.  At the next change to night, he then sort of moved, then stayed there.  Video here: https://streamable.com/5hr2t0

**Comment by Tenzarian** [comment]
Saw the same issue in a game of mine, although it doesn't appear to be related to any stun or effect on him? He uses the gate on radiant side, then immediately uses the dire gate and returns to radiant side incorrectly. No player had a stun on him to interrupt his channel or anything, and no player was at the dire gate before him, he was first to arrive and immediately uses the gate to return upon arrival before players can follow him.
Match id: 7156386690

**Comment by commentator24** [comment]
you did stun. 
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109324155/238029f1-d9fe-4940-bf11-22818ec18697)

**Comment by commentator24** [comment]
seems fixed, didnt happen in my game today

**Comment by commentator24** [comment]
thought it was fixed, guess not completely 7.33c

**Comment by commentator24** [comment]
so far hvnt seen it happening again in 7.34c, will close until then
