### ISSUE TITLE
Viper's poison attack range isn't 600/640/680/720.

### ISSUE THREAD

**Issue by DpRd745** [ValveSoftware/Dota2-Gameplay#8597]
### Ability name

poison attack

### Description

Viper's attack range is 575.
I notice that Viper's poison attack is 575/615/655/695 instead of 600/640/680/720 as the tooltip/changelog mentioned.
By using lvl4 poison attack, you are still get hitted by tower which is 700 attack range.
![image](https://user-images.githubusercontent.com/106855630/234267066-86bdc1c3-e999-44f1-af5c-306e7fa8612c.png)

### Example Match ID (and possibly Timestamp)

DEMO

**Comment by Aluerie** [comment]
It's not a bug. 

The tooltip includes bounding size of a hero which is 25. 

Cast ranges work from centre to edge, while attack ranges work from edge to edge, this is why cast range needs to account for it.

**Comment by DpRd745** [comment]
Thank you so so much @Aluerie for the explanation! Gracious! I'm sorry for adding your load :< . Really happy to know its mechanism!!!!  

> It's not a bug. cast range != attack range.
> 
> The tooltip for cast range includes bounding size of a hero which is 25.
> 
> Cast ranges work from centre to edge, while attack ranges work from edge to edge, this is why cast range needs to account for it.
