### ISSUE TITLE
ARC WARDEN

### ISSUE THREAD

**Issue by LUST99** [ValveSoftware/Dota2-Gameplay#8611]
### Ability name

FLUX, MAGNETIC FIELD, SPARK WRAITH

### Description

Оригинальный герои и копия поменялись способностями.
Пример
Spark wraith героя активируется через 2 секунды.
Spark wraith копии активируется через 1 секунды.
Баг поменял способности у героя и копии.
Spark wraith героя активируется через 1 секунды.
Spark wraith копии активируется через 2 секунды.
Подобное случилось и с остальными способностями.
Также поменялись иконки способностей и визуальные эффекты.

### Example Match ID (and possibly Timestamp)

7125173114

**Comment by Aluerie** [comment]
![image](https://user-images.githubusercontent.com/33165440/234365840-574a070d-6ea2-44d1-88ca-68b310537f01.png)

**Comment by LUST99** [comment]
The original heroes and the copy have swapped abilities.
Example
The hero's Spark wraith is activated after 2 seconds.
Spark wraith copies are activated after 1 second.
The bug changed the abilities of the hero and the copy.
The hero's Spark wraith is activated after 1 second.
Spark wraith copies are activated after 2 seconds.
The same thing happened with the rest of the abilities.
The ability icons and visual effects have also changed.

**Comment by Aluerie** [comment]
dude, read the patch. 

the hero and clone swap abilities when Arc Warden is Dire.
