### ISSUE TITLE
MMR Change shouldn't be locked behind a Paywall

### ISSUE THREAD

**Issue by tonyzhu163** [ValveSoftware/Dota2-Gameplay#8621]
### Description

As the title suggests, now that MMR change in dota is not constant, we should have a free option to show MMR per match.

I have been a dota plus subscriber for years, but having to pay for a basic QOL improvement is unfair.

Thanks

**Comment by MikioKyo** [comment]
As many issues on this repository: this is a bug tracker
I agree with the change you're suggesting, but it isn't a bug. Write a post on reddit and maybe valve will implement the change soon tm
