### ISSUE TITLE
Phylactery dosent work on dazzel aghanim 

### ISSUE THREAD

**Issue by Sjdmepo12** [ValveSoftware/Dota2-Gameplay#8624]
### Item name

Phylactery 

### Description

Dazzel aghanim turn his 3rd ability so can target enemy but if u have Phylactery and aghanim , phylactery doesnt hit enemy when u use shadow wave. On them 

### Example Match ID and Timestamp

1

**Comment by TheUnholyWrath** [comment]
This should have been fixed in the 7.33b patch, you can close this issue.
