### ISSUE TITLE
Glimmer cape's invisibility disabled after damage breaks the barrier

### ISSUE THREAD

**Issue by artillicime** [ValveSoftware/Dota2-Gameplay#8632]
### Item name

Glimmer Cape

### Description

Many times in the match the invisibility breaks after the 300 barrier shield is consumed.

Noticed on Skywrath mage.

at 34:58 it just simply not appears.

### Example Match ID and Timestamp

Match ID : 7125640879 - 22:49 - 25:24 - 34:58

**Comment by TheUnholyWrath** [comment]
This was fixed in the 7.33b patch. Please close this issue.
