### ISSUE TITLE
Some hero didnt have base stats

### ISSUE THREAD

**Issue by Latist1** [ValveSoftware/Dota2-Gameplay#8638]
### Description

Medusa: didnt have str 0, 164 hp for all game, even with lvl up no str stats plus.
Tiny: didnt have agility 0 stats.

### Example Match ID (and possibly Timestamp)

7124172485, 7125706746

**Comment by Daar543** [comment]
Works as intended by IceFrog.

**Comment by Latist1** [comment]
> Works as intended by IceFrog.
from you words, Medusa should have 164 HP for all game with 0 str stat?
