### ISSUE TITLE
7.33B the visual effects of Clinkz's TAR BOMB are unchanged.

### ISSUE THREAD

**Issue by DpRd745** [ValveSoftware/Dota2-Gameplay#8639]
### Ability name

TAR BOMB

### Description

The visual effects of it remain unchanged, It doesn't match the raidus.

![image](https://user-images.githubusercontent.com/106855630/234458393-b9edc328-4084-4d26-bba4-6db5129eeff8.png)

### Example Match ID (and possibly Timestamp)

DEMO

**Comment by mrskeltal94** [comment]
Appears to be fixed in todays update (8th May 2023), visual effects are much larger and more closely reflect the actual radius

**Comment by DpRd745** [comment]
> Appears to be fixed in todays update (8th May 2023), visual effects are much larger and more closely reflect the actual radius

Yeah, it is fixed! Thank you! And thank valve employee for the hard work!

**Comment by DpRd745** [comment]
> Appears to be fixed in todays update (8th May 2023), visual effects are much larger and more closely reflect the actual radius

Yeah, it is fixed! Thank you! And thank valve employee for the hard work!
