### ISSUE TITLE
mirana shard bug leap 

### ISSUE THREAD

**Issue by newbean57** [ValveSoftware/Dota2-Gameplay#8653]
### Ability name

leap

### Description

mirana leap bug when upgrade with shard, the damage keep going constantly after the leap until the game finish. Can see at the radiant site tier 3 bottom at 17 minute, the new spawn creeps get damage from the previous leap.

### Example Match ID (and possibly Timestamp)

7125860413 - 17

**Comment by Janista20** [comment]
+1 

7126225385 - 16:00 and afterward

**Comment by TBN312** [comment]
Same issue: match ID 7126638057

**Comment by Michaelliem99** [comment]
7126445377, time 16:00 then permanently through the game, mirana with 701 LH 795 GPM 283 XPM

**Comment by nathank-valve** [comment]
This will be fixed in a hotfix later today. Closing
