### ISSUE TITLE
Mirana (Priestess Of The Moon) shard bug? Kindly refer match ID

### ISSUE THREAD

**Issue by BugFinder1DOta** [ValveSoftware/Dota2-Gameplay#8676]
### Ability name

3rd ability <Leap> with Aghanim shard

### Description

Permanent duration shard whole game, instantly clearing creeps after creep spawning, really unsure how to replicate it. kindly refer replay.

### Example Match ID (and possibly Timestamp)

7126514629 , time 17:45, and whole game afterwards

**Comment by Michaelliem99** [comment]
7126445377, time 16:00 then permanently through the game, mirana with 701 LH 795 GPM 283 XPM

**Comment by Aluerie** [comment]
Duplicate  #8653

---
Please, close your duplicate issue and instead upvote the original one with "👍" reaction. Comment extra details if any.

And in future, first, use search to find out if the bug you want to report was already submitted by somebody else so you can upvote it and not clutter the repository with duplicates.
