### ISSUE TITLE
didnt get the selected neutral item from neutral token - and magically my item completed from a item part from base

### ISSUE THREAD

**Issue by ReyAdmiradoo** [ValveSoftware/Dota2-Gameplay#8684]
### Item name

tier 2 token - bullwhip

### Description

i was ogre magi and got a tier 2 token and wanted to select the item, i selected bullwhip but didnt get the item and my token vanished as well. i had two parts of medallion of courage (chainmail and sobi mask) in my backpack and the third part of it (blight stone) was in base and i had the token in the first backpack slot and the 2 items mentioned above in the other 2. i pressed the token and got 5 options as it should be and selected bullwhip (invoker already had one maybe this caused the bug idk), when i selected it my medallion combined with the item from stash but the token didnt turn into bullwhip. i looked inside the neutral items in base and it only showed me the thumblers toy that i got for tier 1 items. and in replay it says 5/5 items but there is only 4 as shown in the screenshot (the one that is not taken is for slardar he didnt use his yet). 

https://user-images.githubusercontent.com/108564910/234678383-d7398bfb-86bd-4fad-b115-f55e5d4dc120.mp4
![neutrall](https://user-images.githubusercontent.com/108564910/234679916-ab676bf3-a94e-427f-8d0b-4d1c86adbce4.png)

tested some stuff that will help the process and posted them in the comment below

### Example Match ID and Timestamp

7126712714 - 19:50 - 20:05

**Comment by ReyAdmiradoo** [comment]
edit: tried to recreate the bug in lobby and found some stuff

if you have some component of a item and the other components needed in base stash and the token be in the `third slot of back pack`, the item will be completed! and you will get the neutral item in the third slot of back pack

if you have this items
![huh](https://user-images.githubusercontent.com/108564910/234682638-30ebefe0-9041-459f-b241-f501c9946324.png)

and you use the token item will be completed where ever you are on the map
![huh 2](https://user-images.githubusercontent.com/108564910/234682952-7e3e0467-bb10-4885-8af9-af3d87cae667.png)



but if you have the token in the first slot of backpack the token will vanish and you wont get the neutral item as well but the item will be completed from base stash.
![kek](https://user-images.githubusercontent.com/108564910/234683806-14c768ce-c598-4330-9236-880277db20bf.png)


completed 

![kekekee](https://user-images.githubusercontent.com/108564910/234683893-ca0b74ea-ea2c-4cb1-ac22-03375f84a4e4.png)


`notes: `

1- tried any item (other than medallion) the same thing happens and it will be completed
2- if you dont have 6 items in the inventory and the token be in your first backpack slot the item will be completed and you `will` get the neutral item in the first slot of your backpack.

# so for the bug to happen 
you need to have all 6 slots full and have a neutral item already equipped and have 2 components  of a item in the second and the third slot of backpack and the rest of the item should be in stash (so you have all the other components in stash) and you need to have the token in the first backpack slot and you use it. this will result in neutral item and token getting destroyed and the item being completed anywhere on the map you are.

**Comment by leosorno** [comment]
same happened to me

**Match ID:** 7127051123
**Min:** 28:39
**Heroe:** Undying
**Item:** Pipe

**Also:** dead courier

**Comment by ETalanian** [comment]
Closed #8735 as duplicate

Match ID: 7127146312
Min: 38:21
Heroe: Weaver
Item: Medallion / T4 Neutral Token

**Comment by GDoe5** [comment]
Just happened to me -
Match ID: 7128368001
min: 28:05

**Comment by nathank-valve** [comment]
Item combine from stash when selecting a neutral item is fixed and will be in the next hotfix. After that change, I wasn't able to repro the neutral item not being granted. But I'll keep this issue open for a few days in case there are any further reports
