### ISSUE TITLE
Primal beast and IO destroying fountain

### ISSUE THREAD

**Issue by cmcdota** [ValveSoftware/Dota2-Gameplay#8688]
### Ability name

PULVERIZE

### Description

Primal beast and IO destroying moving tormentor, using their ultimates to destroy enemy fountain.

Video: https://www.youtube.com/watch?v=aEtU2VllrLY
Match id: 7126922050

### Example Match ID (and possibly Timestamp)

7126922050

**Comment by Aluerie** [comment]
Duplicate  #8679 and will be fixed

---
Please, close your duplicate issue and instead upvote the original one with "👍" reaction. Comment extra details if any.

And in future, first, use search to find out if the bug you want to report was already submitted by somebody else so you can upvote it and not clutter the repository with duplicates.
