### ISSUE TITLE
Mirana shard Leap bug

### ISSUE THREAD

**Issue by uwulynn** [ValveSoftware/Dota2-Gameplay#8689]
### Ability name

Leap

### Description

Mirana does a weird thing after he gets shard. she walks straight to our lane from 15:14 after getting aghs shard and does some weird shit that killed our creep wave whole game. she did it in all three lanes which made us lose the game. 

link: https://youtu.be/KVwo07DUzWo

### Example Match ID (and possibly Timestamp)

7126921116 (15:14)

**Comment by Aluerie** [comment]
#8653 will be fixed next update, please, close this issue.
