### ISSUE TITLE
Mirana gamebreaking bug, killing creepwave using global starstorm 

### ISSUE THREAD

**Issue by Ko-chan21** [ValveSoftware/Dota2-Gameplay#8702]
### Ability name

Starstorm

### Description

Mirana keep killing our creepwave using starstorm even tou she didnt cast it near the creepwave, and its hit all our creepwave at the same time by doing global damage

i dunno how she did it but its make our team cant destroy the tower because we dont have a creep

https://user-images.githubusercontent.com/131927078/234729006-1e7cd4f3-356e-4d47-b46c-a83592c96e91.mp4

### Example Match ID (and possibly Timestamp)

7127045404

**Comment by Aluerie** [comment]
Duplicate  #8653 and will be fixed next update

---
Please, close your duplicate issue and instead upvote the original one with "👍" reaction. Comment extra details if any.

And in future, first, use search to find out if the bug you want to report was already submitted by somebody else so you can upvote it and not clutter the repository with duplicates.
