### ISSUE TITLE
Battle stats does not update with new game 

### ISSUE THREAD

**Issue by ahajirnis** [ValveSoftware/Dota2-Gameplay#8706]
### Description

Got kicked out a game. After which that game disappeared from history.

Since then battle stats do not record any new games played. But game history in Profile does.

### Example Match ID (and possibly Timestamp)

7127147096

### Screenshots

![battlestats](https://user-images.githubusercontent.com/3473708/234752396-1bddaf45-e3a9-4833-b64a-d3d0d2261763.png)
![game history](https://user-images.githubusercontent.com/3473708/234752400-53fbecb5-b7ba-47c5-92ea-62a8508940cb.png)

**Comment by kdmadej** [comment]
Might be related to https://github.com/ValveSoftware/Dota2-Gameplay/issues/8394
