### ISSUE TITLE
Shared wards can be duplicated

### ISSUE THREAD

**Issue by ghiffaryuthian** [ValveSoftware/Dota2-Gameplay#8710]
### Item name

Observer and Sentry Wards

### Description

You can duplicate a shared observer and sentry wards that was placed in different item slot

How to reproduce it:
you need obs + sentry wards to be on separate item slot, which happen automatically after ally shared in the loadout screen, then you ctrl + click the ward to your hero which will combine the wards with an additional item

In game example https://imgur.com/a/AArFAV6

### Example Match ID and Timestamp

7127201013 - -0:55

**Comment by nathank-valve** [comment]
Should be fixed now. Closing
