### ISSUE TITLE
7.33 Sunder heal yourself on enemy bkb

### ISSUE THREAD

**Issue by Avarise831** [ValveSoftware/Dota2-Gameplay#8716]
### Ability name

Sunder 

### Description
if enemy uses bkb, you cannot transfer your hp with enemy but now with new patch you can heal youself. Tb can heal himself (based on enemy's current hp) when he is fighting. Before bkb nefr you could not use sunder when enemy used bkb
bug or no?

-

### Example Match ID (and possibly Timestamp)

-

**Comment by floptropica** [comment]
yes if you use sunder on a bkb target the swap still happens but the target doesn't lose any health.
