### ISSUE TITLE
Pugna didn`t get aghanim shard when killed tormentor

### ISSUE THREAD

**Issue by BMagic19** [ValveSoftware/Dota2-Gameplay#8718]
### Item name

Aghanim shard

### Description

Pugna didn`t get aghanim shard when killed tormentor. The lowest networth pugna didn`t get Agh. Shard.

### Example Match ID and Timestamp

7127462461 - 20:15, 30:45

**Comment by TheUnholyWrath** [comment]
[Destroying a Tormentor grants an Aghanim's Shard buff to one of the two lowest networth allied heroes that still do not have the Shard when it dies](https://www.dota2.com/patches/7.33)

Is there a bug here? It seems to be working as the patch notes have documented it. Io got the first shard, Pudge got the second shard, Pugna got unlucky.
