### ISSUE TITLE
Neutral Item Disappeared Upon Choosing, Combined Other Item From Stashed Components

### ISSUE THREAD

**Issue by ETalanian** [ValveSoftware/Dota2-Gameplay#8735]
### Item name

Neutral Token

### Description

What happened:

Weaver is 6-slotted, has Blight Stone in Backpack, Chainmail+Sage's Mask+Wind Lace in Stash.
Weaver obtains a T4 Neutral Token, and selects Spell Prism.
The tick Weaver chooses Spell Prism, the Blight Stone is combined to create Medallion (no Courier delivery / no entering Fountain) and Spell Prism vanishes.

![image](https://user-images.githubusercontent.com/36826759/234942023-1bfb5cfa-73da-489c-b32f-e06d4cdc3149.png)
![image](https://user-images.githubusercontent.com/36826759/234942091-d749dc9c-5565-4d12-a3e8-3990e0fc09d2.png)
![image](https://user-images.githubusercontent.com/36826759/234942148-0b38c16a-1ad8-48e8-9325-f9114e4b543f.png)
![image](https://user-images.githubusercontent.com/36826759/234942180-f04af941-e93f-4942-800b-cdf60b35fd96.png)

### Example Match ID and Timestamp

7127146312 - 38:21

**Comment by Avarise831** [comment]
#8684

**Comment by ETalanian** [comment]
Closing as duplicate
