### ISSUE TITLE
Natural item disappeared after selection and appeared near enemy's melee barracks 

### ISSUE THREAD

**Issue by avidabush** [ValveSoftware/Dota2-Gameplay#8759]
### Item name

Natural item

### Description

Natural item disappeared after selection and appeared near enemy's melee barracks.

it happed to Necro. 

### Example Match ID and Timestamp

7128608278 - 51:10

**Comment by nionys** [comment]
Same issue, used tier 2 token from stash while dead (got _eye of the vizier_), token appears at corpse's position
Match id : 7129044103 
client says 'failed to decompress replay file', but happened at around 22 minutes near the dire middle battacks.
My stash may have been full, i cant check right now.

**Comment by nathank-valve** [comment]
This will be fixed in the next hotfix. Closing
