### ISSUE TITLE
Can't cast Firesnap cookie on myself

### ISSUE THREAD

**Issue by andrrrw** [ValveSoftware/Dota2-Gameplay#8772]
### Ability name

Firesnap cookie

### Description

quick cast with ALT+ combination don't work
Can't cast Firesnap cookie on myself with ALT+ 
Other abilities works properly like Bane's nighmare or Seeker bloodrage
I definitely have no idea what's wrong with this game

https://user-images.githubusercontent.com/81991382/235121311-f02ea535-ea6d-4250-b893-398663857c5e.mp4

### Example Match ID (and possibly Timestamp)

tested in demo mode

**Comment by Aluerie** [comment]
cant reproduce. Show settings.

**Comment by andrrrw** [comment]
i cheked and find another used comb ALT+W
sorry, i am so stupid
close this bug
