### ISSUE TITLE
Gem cd bug

### ISSUE THREAD

**Issue by Djakondos** [ValveSoftware/Dota2-Gameplay#8773]
### Item name

Gem of True Sight

### Description

I picked up lost gem (was bought by my support Witch Doctor), which was dropped after enemy chrono kill. I used it active button "Reveal" to check my highground and after once, its coldown didn't recover till end of the game. I tried to return owner, WD, but it didn't work too. Is it bug? Was it because teammate died inside new chrono?
![Gem bug scr](https://user-images.githubusercontent.com/132060295/235122650-3a65a7cd-6292-4e59-8388-c7b2ed86ea4c.png)

### Example Match ID and Timestamp

7128877859 - 25:51

**Comment by shaileshgarg** [comment]
Seems like a result of new Chrono.

**Comment by anotherCoward** [comment]
It is related to the new Chronosphere and that the gem is dropped on death. 

It can be "repaired" with a second Chronosphere where the original owner has the gem and survives the chronosphere. - After this the cooldown will work again.

**Comment by christucket** [comment]
Also happens to abilities or more specifically, Charge of Darkness. They both seem related but possibly not.


### Ability name
Spirit Breaker - Charge of Darkness

### Description
The cooldown of my charge of darkness stayed at zero for most of the game. Quick summary of events: I was in a fight, as I was dying, I tried to charge away. I started charging and then died. While I was dead, the cooldown looked normal but once it hit zero, the number "0" stayed on the ability and I couldn't use it anymore.

### Example Match ID and Timestamp
7183328970 - 9:13

https://youtu.be/VRas5-s6XlQ
https://youtu.be/tqAxBntO4Yk

**Comment by ErikHumphrey** [comment]
Also happened in match ID 7259791150 with a Faceless Void in the match

**Comment by pavlichenkod** [comment]
Also happened in match ID 7261845333 with a Faceless Void in the match (after 44:06).

**Comment by manoel-eduardo** [comment]
Also happened in match ID 7279385847, time 41:50. I used the gem to reveal high ground as Lich and the cooldown didn't recover.

**Comment by Aphotic** [comment]
video showcase on Reddit:
https://old.reddit.com/r/DotA2/comments/16b7wmu/gem_and_chronosphere_interaction_is_this_bug_or/

**Comment by Nathanael-Valve** [comment]
Fixed in next update.
