### ISSUE TITLE
Broodmother global cast range on Spin Web uses outdated radius

### ISSUE THREAD

**Issue by ThinkPortals** [ValveSoftware/Dota2-Gameplay#8776]
### Ability name

Spin Web

### Description

Broodmother's Spin Web has a global cast range when the new web would be touching an already placed web.
When detecting existing webs, the new web detects for 900 aoe, instead of the 1200 with the 7.33b increased web radius.

### Example Match ID (and possibly Timestamp)

7126006259

**Comment by Avarise831** [comment]
#8633

**Comment by ThinkPortals** [comment]
> #8633

#8637 is closer, that one seems to be specific to the visual side of the brood web.
