### ISSUE TITLE
Pavise Barrier does not work against physical spell damage

### ISSUE THREAD

**Issue by TheZett** [ValveSoftware/Dota2-Gameplay#8779]
### Item name

Pavise

### Description

Pavise states that it grants a physical damage barrier and blocks up to 300 physical damage.

This currently only works for physical attack damage, but not for physical spell damage (e.g. Bristle Quills or Slardar stun).

As a comparison, Glimmer Cape's magical barrier works against magical spell damage and magical attack damage (e.g. MKB procs).

Either Pavise should state that it only works against physical **attack** damage, or the item should get bugfixed to block physical spell damage as well (and thus would be a physical counterpart to glimmer cape's barrier).

### Example Match ID and Timestamp

none

**Comment by anotherCoward** [comment]
#8512

**Comment by TheZett** [comment]
Fixed as of 7.33c, thanks!
