### ISSUE TITLE
Rubick aghs upgraded Last word has no vision on neutral creeps

### ISSUE THREAD

**Issue by commentator24** [ValveSoftware/Dota2-Gameplay#8781]
as shown
![image](https://user-images.githubusercontent.com/109324155/235172008-531f5916-da9d-45ee-bbe5-6502b7cdb715.png)
![image](https://user-images.githubusercontent.com/109324155/235172085-c1e90ad8-ca90-4b3e-b576-04fe7ecb9c8a.png)

and demo hero version works properly as shown
![image](https://user-images.githubusercontent.com/109324155/235172757-15e310ff-c64e-4f7d-9e40-d1f75fa7118e.png)

**Comment by anotherCoward** [comment]
On Silencer it doesn't reveal them either. It only provides vision on the "enemy team" the description is misleading.

**Comment by commentator24** [comment]
7.36 just passive ability now
