### ISSUE TITLE
"sdr SDRClient_ForceRelayCluster sgp" Doesnt work anymore.

### ISSUE THREAD

**Issue by Happybanana12** [ValveSoftware/Dota2-Gameplay#8790]
### Description

Hi, I know its a specific request, but I figured it was worth a try. I know valve sees reddit and fixes stuff (has happened before).

I play on Singapore server and I have constant 3-10 packet loss. No its not my net as I ping other things and its perfectly fine. This ALWAYS happens with dota in EVERY game.

But for almost an year I found that command and it made my ping lower and cleared the packet loss. After the new patch this command doesnt work anymore.

It would be amazing if you guys can have a look at it. Thanks!

**Comment by mohadnansyarif** [comment]
try to use this :  "net_option SDRClient_ForceRelayCluster sgp"
