### ISSUE TITLE
Neutral Items drops where you are dead instead of in your inventory

### ISSUE THREAD

**Issue by pimta** [ValveSoftware/Dota2-Gameplay#8800]
reproduce:
1. you are dead 
2. buy a token at fountain
3. redeem it for a neutral item
4. item drops at dead spot instead of in your inventory

**Comment by pimta** [comment]
Match ID 7129638227
at between T1 and T2 mid of dire side

**Comment by Aluerie** [comment]
it was fixed, now after choosing the item it stays in stash instead of teleporting to your (dead) location.

you can close the issue.
