### ISSUE TITLE
Neutral item can be obtained instantly

### ISSUE THREAD

**Issue by Andites** [ValveSoftware/Dota2-Gameplay#8801]
### Item name

Neutral Tokens

### Description

Neutral item can be obtained instantly if you just open Neutral Token when it in stash

https://user-images.githubusercontent.com/61075552/235231175-5244964f-87ae-4f88-b014-33e08c84127f.mp4

### Example Match ID and Timestamp

7129665777 - 21:47

**Comment by Aluerie** [comment]
intended, please close the issue.
![image](https://user-images.githubusercontent.com/33165440/235236727-c399dafc-3b74-431b-869a-d6a23880e95d.png)

**Comment by BarsikTheCaT** [comment]
> intended, please close the issue. ![image](https://user-images.githubusercontent.com/33165440/235236727-c399dafc-3b74-431b-869a-d6a23880e95d.png)

This is absolutely not intended and this is a bug.
It should be merged with https://github.com/ValveSoftware/Dota2-Gameplay/issues/8800
The converted item drops at your location, and if you are dead, it drops at the location of your death.

**Comment by commentator24** [comment]
he can convert from stash but not suppose to drop to hero location instead of stash i think

**Comment by Aluerie** [comment]
* OP title "can be obtained instantly" 
* OP text "can be obtained instantly" 
* Patch notes "can be obtained instantly" 

Ofc it's intended. 

Yes, dropping location is bugged, but that's not what OP is reporting.

**Comment by Andites** [comment]
> * OP title "can be obtained instantly"
> * OP text "can be obtained instantly"
> * Patch notes "can be obtained instantly"
> 
> Ofc it's intended.
> 
> Yes, dropping location is bugged, but that's not what OP is reporting.

now its fixed by valve, any questions?

**Comment by Aluerie** [comment]
close the issue if your problem is solved

**Comment by Andites** [comment]
> close the issue if your problem is solved

find job

**Comment by commentator24** [comment]
should close the issue, its fixed
