### ISSUE TITLE
Jogo trava na seleção de heróis

### ISSUE THREAD

**Issue by LucasWL1** [ValveSoftware/Dota2-Gameplay#8811]
### Description

Não sei se esse é o lugar certo pra relatar esse problema mas enfim.
60% das vezes que eu aceito uma partida, ao carregar, o jogo simplesmente trava mas com o som rolando, obrigando-me 
a fechar e abrir o jogo para voltar a funcionar, e isso ja fez com que eu desse disconnect em duas partidas e pegar low priority.
Antigamente, antes dessa nova atualização, isso acontecia sempre quando eu não estava com a janela do dota aberta,
mas agora acontece independente disso, porém, como eu falei, não é em todas partidas.

### Screenshots

https://user-images.githubusercontent.com/112062780/235281046-56ec842b-acf1-4860-8b66-103a3ebbf9cf.mp4

um video de quando isso aconteceu

**Comment by marlborao777** [comment]
estou com esse mesmo problema no meu jogo
