### ISSUE TITLE
Glimmer Cape speed bonus / mechanics

### ISSUE THREAD

**Issue by artillicime** [ValveSoftware/Dota2-Gameplay#8824]
### Item name

Glimmer Cape

### Description

I am not sure if it is how the item should work because there was no info on that. But if the invisibility is broken the speed bonus is also removed. So in my case Zeus ult breaks the invisibility **and** the speed bonus at 20:09 and then using an item at 20:12 also remove the speed bonus. I don't know if it is how the item is intended to work or the buffs should be independent from one another. Since there was a previous bug with the shield barrier cancelling invisibility when depleting...

### Example Match ID and Timestamp

7129943880 - 20:09 - 20:12

**Comment by artillicime** [comment]
Also you cannot move through unit anymore with the invisibility? Had the feeling it didn't work in a match with SS ultimate which I don't have the ID. But if you try in the demo mode you can't walk through the ward of shadow shaman, which I used to do with glimmer cape.

**Comment by anotherCoward** [comment]
As soon as you reveal yourself during the buff, the movespeed gets also removed. The speed bonus works similar to the old +40% magic resistance, it was only granted while being fully invisible to the enemy.

The changelog doesn't mentioned that the new effect has phased movement.
> #### Glimmer Cape
> - Recipe cost decreased from 450 to 350 (Total cost increased from 1950 to 2150)
> - Magic Resistance bonus increased from +20% to +25%
> - Glimmer now grants invisibility, +40 movement speed and 300 magic damage barrier. Duration: 5s. Mana Cost: 90. Cooldown: 12s

Plus the fix from 7.33b where the effect got separated from the barrier again:
> Fixed Glimmer Cape invisibility and move speed being removed when barrier was broken

**Comment by artillicime** [comment]
The old description wasn't specifying the phased movement speed so that's why I was wondering.

But thanks for the precision!
