### ISSUE TITLE
Earthshaker can't jump while stunned with activated BKB

### ISSUE THREAD

**Issue by Deymoss** [ValveSoftware/Dota2-Gameplay#8830]
### Ability name

Enchant Totem

### Description

Earthshaker cannot jump using enchant totem with activated BC when he is supposedly under the stun/hex

### Example Match ID (and possibly Timestamp)

7128320887 - 37:00

**Comment by Aluerie** [comment]
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/33165440/f1c971e3-dd8f-4532-a725-3953d77ae880)

**Comment by Deymoss** [comment]
Thanks!
