### ISSUE TITLE
Muerta Relics Not Tracking in Turbo

### ISSUE THREAD

**Issue by Jonathanace** [ValveSoftware/Dota2-Gameplay#8839]
### Description

Some Muerta relics are not functioning in Turbo, as shown in the screenshots attached. 

### Screenshots

![image](https://user-images.githubusercontent.com/55035716/235337282-66676566-312b-47b7-b410-df457b5132e9.png)
![image](https://user-images.githubusercontent.com/55035716/235337290-c74186b5-3862-4dbb-aaec-a2115ad04cfd.png)
![image](https://user-images.githubusercontent.com/55035716/235337294-a1b8dfd7-ca39-43e1-bc1d-9af06daad35b.png)
![image](https://user-images.githubusercontent.com/55035716/235337296-89561d94-6030-44a1-8206-8c3fe4139570.png)
![image](https://user-images.githubusercontent.com/55035716/235337298-880ccbb0-ebb9-4ffa-a10b-b5026d64b91d.png)
![image](https://user-images.githubusercontent.com/55035716/235337299-4243364c-a4a4-40b2-a2a8-8e1dfa874496.png)
![image](https://user-images.githubusercontent.com/55035716/235337301-3a8a84d2-f68f-40d4-bb25-e9b54b25406e.png)
![image](https://user-images.githubusercontent.com/55035716/235337306-af4366bf-bc42-4499-9b35-2afe08a795a6.png)

**Comment by Aluerie** [comment]
it's fixed, please close. I checked all those relics.
