### ISSUE TITLE
Crystal Maiden Conduit of the Blueheart

### ISSUE THREAD

**Issue by JiizukeUsernameTaken** [ValveSoftware/Dota2-Gameplay#8840]
### Cosmetic Item Name

Conduit of the Blueheart

### Description

Every time cm attacks it always shows an "X" underneath her.

### Example Match ID

Every Match

### Screenshots

![Screenshot (10)](https://user-images.githubusercontent.com/131482106/235337610-ac4ec72e-6bff-4792-8a7d-be837e8ac018.png)
![Screenshot (7)](https://user-images.githubusercontent.com/131482106/235337614-aa05464a-56da-4968-b250-8a47ef56a381.png)
![Screenshot (8)](https://user-images.githubusercontent.com/131482106/235337616-dcef80ea-0ae3-46e5-b2f1-cde9e89588ad.png)

**Comment by Astiberon** [comment]
#8640
