### ISSUE TITLE
Can't able to access replay after updates

### ISSUE THREAD

**Issue by Zanderhastings** [ValveSoftware/Dota2-Gameplay#8841]
### Description

Can't able to access replay after updates

### Example Match ID (and possibly Timestamp)

7111832272

### Screenshots

![Screenshot 2023-04-30 111415](https://user-images.githubusercontent.com/132186795/235337910-acca380b-03bb-45dd-9b83-8f389390c8d8.png)
![Screenshot 2023-04-30 112125](https://user-images.githubusercontent.com/132186795/235337950-8e25c74f-2997-4d92-af50-f91419fc2e4e.png)

**Comment by Aluerie** [comment]
This happens when you try to watch replay from previous patch, which linked match id is.

**Comment by Nathanael-Valve** [comment]
Fixed
