### ISSUE TITLE
Nyx Assassin's aghanim scepter description typo

### ISSUE THREAD

**Issue by luvwy-dev** [ValveSoftware/Dota2-Gameplay#8844]
### Hero and spell

Nyx Assassin - Burrow

### Description

After Mana Burn changed to Mind Flare, the Burrow spell description wasn't updated. It still says "Mana Burn"

### Screenshots

![image](https://user-images.githubusercontent.com/58365194/235346383-6a1274a9-e477-4cdc-8ed8-69951c3c5385.png)

**Comment by TheUnholyWrath** [comment]
#8650
