### ISSUE TITLE
MEEPPO AND LOTUS ITEMS

### ISSUE THREAD

**Issue by revientor** [ValveSoftware/Dota2-Gameplay#8848]
### Item name

 LOTUS 

### Description

WHEN meepo takes lotus from the funtainin top or bottom lines
if the meepo that take the lotus is a bad clone, a new set of boots is generated in that meepo.

I had a bad mepo clone with 6 tranki boots (no stats are agregated I think)

### Example Match ID and Timestamp

.

**Comment by nathank-valve** [comment]
This will be fixed in the next hotfix. Closing
