### ISSUE TITLE
Pangolier Rolling Thunder is held in place by Mars Arena of Blood

### ISSUE THREAD

**Issue by ybabts** [ValveSoftware/Dota2-Gameplay#8872]
### Ability name

Rolling Thunder

### Description

Rolling Thunder stops moving and cannot move when you are touching the wall of the Mars Arena of Blood. Normally you would move through the wall as if it wasn't there, for example with a Black King Bar or equivalent debuff immunity abilities. You effectively get stuck on the wall and can't move, even if you use Shield Crash. I don't see this as being intentional because no other ability interacts with Rolling Thunder or debuff immunity in this way.

### Example Match ID (and possibly Timestamp)

7133348224

**Comment by RCM0808** [comment]
7135180096
here is another replay of this bug

**Comment by eetusa** [comment]
To add, even if it were intentional that pango can't roll through the arena, pango still can't pass through Mars Arena of Blood even if they have BKB activated while rolling. That cannot be intentional.

**Comment by Jonahdude** [comment]
another few examples, 
7155093452 at 25:30 and 33:20

**Comment by Aluerie** [comment]
https://steamcommunity.com/games/dota2/announcements/detail/6252732681178927719
> Fix Pangolier's Rolling Thunder being blocked by Mars' Arena of Blood

you can close this issue
