### ISSUE TITLE
Tempest's ability got swapped with the real Warden from game start.

### ISSUE THREAD

**Issue by Agisyah** [ValveSoftware/Dota2-Gameplay#8876]
### Ability name

Tempest Double

### Description

First Screenshot: Main Arc Warden, portrait, ability icon, and how the ability behave is swapped with Tempest's.

![Screenshot 2023-05-01 081242](https://user-images.githubusercontent.com/108935065/235392514-4e184de8-3d0c-4633-97f0-eddb0b3dd79a.png)

2nd Screenshot: Level 6 Arc Warden, Tempest's portrait, ability icon, and how the ability behave is swapped with the real Zet.

![Screenshot 2023-05-01 081528](https://user-images.githubusercontent.com/108935065/235392471-ddbe6420-ada8-46e4-82b9-dca8873eb22a.png)

Cause is unknown and it happened from the very start of the game (after drafting).

### Example Match ID (and possibly Timestamp)

7133433033 - 00:00

**Comment by Aluerie** [comment]
read the patch 7.33, it's intended

**Comment by Aluerie** [comment]
For immortal - upvote/reference https://github.com/ValveSoftware/Dota2-Gameplay/issues/8447 issue.
