### ISSUE TITLE
Flame Guard barrier health ui does not update properly on first damage instance

### ISSUE THREAD

**Issue by bmzhu2** [ValveSoftware/Dota2-Gameplay#8884]
### Ability name

Flame Guard

### Description

When Flame Guard takes its first instance of magic damage, the barrier health ui does not update with how much damage has been taken unless that instance was enough to remove the barrier outright. All subsequent instances of magic damage will remove the appropriate amount of barrier health, but the first instance's damage will still be missing, so the barrier health will be misleading.

To be clear this seems to be a ui/visual bug, and the mechanics are working properly. Also this behavior does not occur with any other barrier as far as I could tell.

Ex1: _Level 1 Ember (27% MR) vs Level 1 Ogre. Level 1 Fireblast does ~36 damage to Flame Guard (65 barrier)._ 

Result: Flame Guard barrier shows 0 damage taken on first Fire Blast, then disappears after second. 

Ex2: _Level 3 Ember w/ Level 2 Flame guard vs Level 1 CM. Level 1 Frostbite should do 7 instances of damage._ 

Result: The barrier takes 6 instances of 10 damage, showing 85 remaining health instead of 75.

Reproducible in demo mode.

### Example Match ID (and possibly Timestamp)

7131741445 - 0:28

**Comment by zanieta** [comment]
It's not a visual bug. Try using finger of death/laguna on lvl 4 ember shield. See the amount of damage he takes. vs the actual computation.

**Comment by bmzhu2** [comment]
@zanieta

>Also damage is absorb before reduction. See shield description.

I think this is the root of your misunderstanding here; one of the big changes in 7.33 is that all magic barriers now calculate their absorptions after reductions, instead of before (this is why Pipe has seen a huge resurgence). 

https://www.dota2.com/newfrontiers?v=2
(search "magic barrier" and it should be the first result)

So while pre-patch Finger of Death would easily break lv4 Flame Guard, in 7.33 this is actually not the case because of the aforementioned barrier change as well as the fact that Intelligence gives Magic Resist now.

600 damage * .717 (25% base MR + 3.3% from int at lv7 with no items) * .7 (lv4 Flame Guard barrier) = 301.14 damage to the barrier, just barely not enough to break its 305 health.

**Comment by zanieta** [comment]
@bmzhu2  

Thnks for the info but still. if you try what i mentioned on the latter part. You'll understand what I meant on ember flame guard and its interactions.

**Comment by bmzhu2** [comment]
@zanieta 

You'll have to be more detailed with evidence then if you still believe there to be a mechanical bug, since the Void Spirit example that you provided earlier does not contradict the way I said the UI bug works

As I described, the first instance of magic damage taken is not reflected in the barrier health UI. That's why when you cast Q and E, it looks like one of their damages is negated, when in reality it's not and it's just a visual bug.

I'm assuming you think that the bug is the damage is fully negated and the barrier health UI is correct; if that is true, then if you use 2 Finger of Death in a row, they should both be blocked by Flame Guard, correct?

If it's a mechanical bug:
-Finger of Death 1 does 0 damage to Flame Guard and 129 to hero, 305 HP left on Flame Guard
-Finger of Death 2 does 301 damage to Flame Guard and 129 to hero, 4 HP left on Flame Guard

If it's a UI bug: 
-Finger of Death 1 does 301 damage to Flame Guard and 129 to hero, 4 HP left on Flame Guard (visually 305)
-Finger of Death 2 does 4 damage to Flame Guard and 426 to hero, Flame Guard disappears

You can test it for yourself as well, but this is the result
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/46500367/99676c73-c113-493d-8acc-405a0b4ec211)

**Comment by zanieta** [comment]
Thank you for this detailed version. Will try this after work. Cheers

**Comment by Ganza6** [comment]
This guy absolutly right about _first instance of magic damage, the barrier health ui does not update_ and _All subsequent instances of magic damage will remove the appropriate amount of barrier health_

Valve fix pls, I am tired to stay againt ember mid and don't undestand how his shield is strong

**Comment by bmzhu2** [comment]
Fixed in 7.34b

**Comment by Ganza6** [comment]
> Fixed in 7.34b

How did you know about it? Patch note doesn't have info about this change

**Comment by Aluerie** [comment]
https://steamcommunity.com/games/dota2/announcements/detail/7160213079742934634

> Fixed Ember Spirit Flame Guard not updating the first time magic damage was applied

**Comment by Moxentoxen** [comment]
![Screenshot_2](https://github.com/ValveSoftware/Dota2-Gameplay/assets/42179748/7106eb8d-a114-4957-8f4b-b9e3df266e7a)
![Screenshot_3](https://github.com/ValveSoftware/Dota2-Gameplay/assets/42179748/b8991e56-367e-41f5-8b49-b8963cf1ec42)
200=140 Noted nice patch, valve math working
