### ISSUE TITLE
Muerta is not presented in all-hero challenge list

### ISSUE THREAD

**Issue by bkmz12353** [ValveSoftware/Dota2-Gameplay#8889]
### Description

**Muerta** is not presented in all-hero challenge list, should be after **Primal Beast** on screenshot 

### Screenshots

![image](https://user-images.githubusercontent.com/61599600/235450159-06d9ffbe-bc6e-4388-9193-380281ea1129.png)

**Comment by TheUnholyWrath** [comment]
![235450159-06d9ffbe-bc6e-4388-9193-380281ea1129](https://user-images.githubusercontent.com/46859977/235450759-a76cd530-a2de-449c-b54a-88d5ed53beae.png)

**Comment by bkmz12353** [comment]
My bad than
