### ISSUE TITLE
Primal Beast - Pulverize - PIERCES SPELL IMMUNITY - Yes/No

### ISSUE THREAD

**Issue by anthonyAA11** [ValveSoftware/Dota2-Gameplay#8896]
### Hero and spell

Primal Beast - Pulverize

### Description

Pulverize from Primal Beast in Heroes menu shows PIERCES SPELL IMMUNITY to Yes but in game it shows No.
In reality it's Yes as it can stop CM (with BKB activated) Frozen Field.

### Screenshots

![image](https://user-images.githubusercontent.com/107254644/235461413-ca2b9fbc-f5c3-490f-9a94-9ec4c6982d2f.png)
![image](https://user-images.githubusercontent.com/107254644/235461377-bc9aa7dc-762a-48d1-b54c-a18525df5f1c.png)

**Comment by nathank-valve** [comment]
This will be fixed in the next hotfix - the ability will always show that it pierces debuff immunity. Closing
