### ISSUE TITLE
Game Crashes when viewing older Replays

### ISSUE THREAD

**Issue by ritesh-bansode** [ValveSoftware/Dota2-Gameplay#8905]
Whenever I try to view a replay older than 7.33, the game loads the versus screen but crashes soon after.
screenshot attached
![image](https://user-images.githubusercontent.com/93593130/235552720-717bd454-5850-4484-b08a-ad26041e0886.png)

**Comment by Aluerie** [comment]
duplicate https://github.com/ValveSoftware/Dota2-Gameplay/issues/8183

**Comment by Nathanael-Valve** [comment]
Fixed.
