### ISSUE TITLE
7.33 problem. (fix by 1 min) Grimm's dark pact have no 95% magic resist.

### ISSUE THREAD

**Issue by MiTiMg** [ValveSoftware/Dota2-Gameplay#8912]
### Ability name

Dark pact (Grimm's agh)

### Description

Grimm's dark pakt illusion get all magic dmg and don't decreases by 95% (it have no any magic resist) 

### Example Match ID (and possibly Timestamp)

Test it yourself

**Comment by anotherCoward** [comment]
Duplicate #8628

**Comment by AnanasSok** [comment]
We are all very sad #8114

**Comment by Aluerie** [comment]
will be fixed https://github.com/ValveSoftware/Dota2-Gameplay/issues/8114#issuecomment-1539182187, you can close your issue.

**Comment by MiTiMg** [comment]
Fixed.
