### ISSUE TITLE
Wraith King skeletons not hitting the towers when they are near to a tower

### ISSUE THREAD

**Issue by ktha00** [ValveSoftware/Dota2-Gameplay#8915]
### Description

Wraith king after summoning his skeletons they were hitting enemy hero and moved near  to dire T3 tower after that skeletons standing idle in there location. this happens twice in the match. 

### Example Match ID (and possibly Timestamp)

7135296436 - 25:27

### Screenshots

![1](https://user-images.githubusercontent.com/119751906/235603989-790dfaad-2289-4792-89c3-4588cb2b5d32.png)

**Comment by ktha00** [comment]
https://user-images.githubusercontent.com/119751906/235605515-32a4dc2e-604c-4585-8502-da246fee54b1.mp4

**Comment by anotherCoward** [comment]
Duplicate #644
