### ISSUE TITLE
Duplicate Energy booster 

### ISSUE THREAD

**Issue by Dkwatts22** [ValveSoftware/Dota2-Gameplay#8923]
So I was playing pango and I bought arcane boots. Eventually disassembled them to make an octarine core. Went back to the secret shop to buy another energy booster and when I unlocked my boots it created my arcane boots again but also produced an extra energy booster.

Match ID 7135928914
Time 19:30

**Comment by commentator24** [comment]
you bought 2 and spent 1400g for it so of course produced an extra energy booster 🙄

**Comment by Dkwatts22** [comment]
Apologies. Did not notice that. I used my quick buy key, not sure why it would have bought two.
