### ISSUE TITLE
Blade mail as Medusa against nyx Vendetta is not 1-to-1 exchange.

### ISSUE THREAD

**Issue by chiat88** [ValveSoftware/Dota2-Gameplay#8924]
### Ability name

Vendetta

### Description

A 4000 mana Medusa with Blade Mail active does not return 2000 damage to Nyx Vendetta.
I found the damage is returned in 50% form, and this should not be the way.
Example: lvl 6 nyx with 758 hp vendetta gets <50% hp damage, which is 400-ish. This is wrong.

In contrast, Invoker's EMP did 600-ish damage to Medusa with blade mail active, then it is reflected 600-ish damage back to Invoker. This behaves correctly.

### Example Match ID (and possibly Timestamp)

just demo is enough

**Comment by anotherCoward** [comment]
Why should Medusa return 2000 Damage to Nyx? Nyx Ulti just removes 50% of the max mana, it doesn't deal it as damage.

![image](https://user-images.githubusercontent.com/32858537/236004893-54c6ec73-948b-4c93-a38a-fe3c230720f1.png)

**Comment by chiat88** [comment]
Now I get it, the mana removed is not counted as damage at all. 
But I dont get the logic. Medusa is the special unit that can return EHP(mana lost) as damage. 
EMP removes mana to Medusa right? Then why 'full damage' is returned to Invoker with blade mail active?
Mana burn removes mana to Medusa too, (I understand there is 1 hp to 1 mana burn) but blade mail interaction seems correct where EHP damage is returned.

**Comment by chiat88** [comment]
There is untested comparison: urn and spirit vessel, with the removal mechanism.
I am not sure Spirit Vessel damage can be returned with blade mail active.
I guess your will vote on won't. Is it?

**Comment by chiat88** [comment]
No... How come our logic do not converge?
![image](https://user-images.githubusercontent.com/9295494/236209684-964c9e05-5752-47e2-b43a-df31c336c830.png)
The purpose blade mail is made so is to grant passive 20% damage return all the time, while having total ~100% damage return when active.
Who cares the complex active portion damage calculation of blade mail, as the total damage return is 100% (105% in fact)?

I can accept if you say vessel-ed target with blade mail active does not return damage back to caster (I didn't test out) cause it is hp 'removal', not damage.
Then in comparison mana removal 50% from nyx vendetta is not counted as damage too, or perhaps for balancing reason, mana removal portion cannot be reflected back to nyx as Medusa with blade mail active.
Medusa's mana shield always absorb 98% (bah just assume 100%) pure damage without any magic/physical reduction at all, perhaps to avoid being too overpowered.
Lvl 30 Invoker's EMP max-ed damage onto lvl 30 Medusa, somehow is 600, and almost total of it is being returned to Invoker with Medusa blade mail active. So I see no problem at all.

A 4000 mana Medusa with blade mail active (~100% damage return) 'can' return pure 2000+600 pure damage back to nyx, which easily results in nyx insta-death. 
I understand if this cheese strategy against Nyx cannot happen, but ~300hp damage return traded with 2300 mana damage onto Lvl6 Nyx with lvl 1 Vendetta is just upright unfair.

**Comment by chiat88** [comment]
OK so misunderstanding happened on Blade Mail as well. 
And thanks for the EMP interaction calculation too.

I close this ticket, although Nyx mana removal mechanism is hopefully counted as damage to Medusa someday.
I understand she is a OP for now (especially spamming snake at lvl 1 as pos 4/5), but Nyx being able to cheese out 50% mana like that, unblockable, unreflectable, is terrible.

**Comment by chiat88** [comment]
I can't like your comment as you flagged it as off-topic. I like to talk a lot on Medusa thing. But perhaps I should stop posting here.
