### ISSUE TITLE
Undying supposedly cannot steal str from 0 str Medusa.

### ISSUE THREAD

**Issue by chiat88** [ValveSoftware/Dota2-Gameplay#8936]
### Ability name

Decay

### Description

Just merely forward this case here.
https://www.reddit.com/r/DotA2/comments/135k5or/decay_medusa_interaction/

### Example Match ID (and possibly Timestamp)

Just demo it.

**Comment by commentator24** [comment]
doubt you can steal str from any hero that has 0 str.  you will still gain decay str, but the target stays 0 str.

**Comment by chiat88** [comment]
I think this should not be the way.

In comparison,
Silencer cannot steal int from pwning Ogre Magi, (with int 0)
Medusa also did not gain mana with Mystic Snake onto 0 mana neutrals.
How can Undying gain str from 0 str Medusa? This is unfair even Medusa does not lose str.

**Comment by anotherCoward** [comment]
@chiat88 Silencer has two "steal" abilities. The one on death won't steal from Ogre, but the one on autohit does increase Silencers int with every hit.

Slark also gets 3 Agi on every hit on Medusa, Ogre and Tiny. Even tho, he could only get two without stats item (except ogre). 
- Tiny has 0 Agi and no Agi gain.
- Same for Medusa with Strength.
- Ogre same for Int, but also additional stats get removed.

The skills just grant the strength/int/agi always, no matter how much stats the unit has. Only the passive (permanent Int steal) from Silencer and the "Essence Shift"-Debuff from Slark won't go beneath 0.

**Comment by chiat88** [comment]
@anotherCoward Your reason is more legit then. So I close this. Not a bug.

**Comment by Aluerie** [comment]
> So I close this. Not a bug.

Press the button then 👀
![image](https://user-images.githubusercontent.com/33165440/236059255-1a39dad3-7dd5-4542-bfd0-5a117617be61.png)
