### ISSUE TITLE
7.33 Legion Overwhelming Odds radius tooltip is incorrect

### ISSUE THREAD

**Issue by Megionate** [ValveSoftware/Dota2-Gameplay#8951]
### Hero and spell

Legion Commander - Overwhelming Odds

### Description

Current Overwhelming Odds radius tooltip in game and from patch notes is 600.
Actual Overwhelming Odds radius is less than 600. Seems to be ~500?

Screenshot for comparison of Drums of Slom and Overwhelming Odds. 
Both spells have a damage radius of 600, but Overwhelming Odds radius is considerably smaller.

### Screenshots

![WHICHISITVALVE](https://user-images.githubusercontent.com/127669055/235911458-81207a71-4fbc-4e1a-9422-ab72d9e1db27.png)

**Comment by anotherCoward** [comment]
Isn't the green line supposed to be the cast range too? On level 1 it's a lot smaller and matches with the old values for the cast range. Looks like a simple oversight.

**Comment by Megionate** [comment]
Nah, old overwhelming odds range was about 1000 iirc. Significantly further than this.
Its current radius shown in game does accurately represent its actual radius, so it's really just the tooltip (and the patch notes) that are wrong.
