### ISSUE TITLE
Rubick: Telekinesis visual indicator does not appear.

### ISSUE THREAD

**Issue by hallsteinx** [ValveSoftware/Dota2-Gameplay#898]
### Ability name

Telekinesis

### Description

Telekinesis is supposed to have a green visual indicator that tells Rubick and his teammates where units will land once Telekinesis ends.

Bug: The particle effect that indicates where a unit will land doesn't show in-game.

Related to this bug: The visual indicator WILL appear for a very brief moment **IF** the Rubick player takes the +0.6 Telekinesis Lift Duration talent at level 15.

This bug is unaffected by cosmetic items, and appears for both me and my friend on separate clients.

### Example Match ID (and possibly Timestamp)

6608449421

**Comment by shaileshgarg** [comment]
Still not Fixed

**Comment by igxx** [comment]
Can we please get a fix for this? Makes Rubick really hard 2 play with randoms!

**Comment by GeneSylvari** [comment]
Weekly not fixed comment

**Comment by jeffhill** [comment]
This will be fixed in the next update.
