### ISSUE TITLE
Dawnbreaker is immune to pure damage during Starbreaker.

### ISSUE THREAD

**Issue by ieceweme** [ValveSoftware/Dota2-Gameplay#8981]
### Ability name

Starbreaker

### Description

Pure damage does no damage during the first spell dawnbreaker.
![Снимок экрана (124)](https://user-images.githubusercontent.com/132615603/236323116-80efed80-1266-46ac-83d7-ae810cc0864c.png)
![Снимок экрана (123)](https://user-images.githubusercontent.com/132615603/236323148-c9b4fc78-ffe3-4640-a49e-d9f170b15a62.png)
![Снимок экрана (125)](https://user-images.githubusercontent.com/132615603/236323169-82f454b6-688a-4ddd-9cff-5cc993ae144b.png)

### Example Match ID (and possibly Timestamp)

7139109902 - 8:39 1st spell, 10:42 1st spell

**Comment by ieceweme** [comment]
Pure damage does no damage during the first spell dawnbreaker

**Comment by Aluerie** [comment]
OP, can you edit your title/post. It's kinda too low quality for this rather big issue. After all, it's English speaking repository. And omniknight in particular has nothing to do with the bug. 

Title: Dawnbreaker is immune to pure damage during Starbreaker. 

Looks like the issue only exists pre-shard. 

Showcase clip:

https://github.com/ValveSoftware/Dota2-Gameplay/assets/33165440/75d6789f-55cc-4874-b619-572e85e37ce9

**Comment by TheZett** [comment]
This issue also affects Nyx' Vendetta damage, even though Vendetta damage even pierces Spell/Debuff Immunity.
Strangely enough, the shard version of Starbreaker is not affected by this bug.

**Comment by kuso-ge** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/assets/12083007/456965bd-6714-4bd4-872d-fbd47067d414

00:20-00:22 secs
Pudge hook doesn't damage Dawnbreaker from u/A532(reddit)

**Comment by eugene-valve** [comment]
This bug should be fixed in an upcoming update, thank you all for reporting this!
