### ISSUE TITLE
Nyx assassin aghs glitch

### ISSUE THREAD

**Issue by MaximumHavoc** [ValveSoftware/Dota2-Gameplay#8984]
### Ability name

burrow

### Description

You can sell your aghs scepter but keep nyx assassins aghs ability. If you burrow in your fountain and sell your aghs you keep the burrow ability without needing scepter. This can also be abused to get a free aghs scepter by saving up the 4200 gold before buying the components. You can buy the ultimate orb and then tp to your fountain to buy the rest of the components. Afterwards you burrow and then sell the aghs while burrowed to get a 100% refund. 

### Example Match ID (and possibly Timestamp)

7136612228 46:45

**Comment by nathank-valve** [comment]
This will be fixed in the next hotfix. Closing
