### ISSUE TITLE
ward timer on HUD still broken

### ISSUE THREAD

**Issue by Avarise831** [ValveSoftware/Dota2-Gameplay#8986]
### Description

same bug for illusion times

### Example Match ID (and possibly Timestamp)

-

### Screenshots

![2](https://user-images.githubusercontent.com/37029303/236360848-10ddf7c7-33ed-443d-8d99-06ee477261eb.png)

**Comment by StingyJack** [comment]
Also showing the full time is the "Battle Pass 2022" HUD

The "Triumph" HUD truncates the minutes from the time.

**Comment by Aluerie** [comment]
Same for all timed units, like Arc Warden R, Ench creeps, Beast's boar, necro, etc. You should probably edit the title to showcase that the bug happens with all such units.

**Comment by Aluerie** [comment]
wtf lol, [link](https://www.reddit.com/r/DotA2/comments/14xya1z/found_the_other_half_of_the_bugged_ward_timer/)

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/33165440/9aa67509-9861-4942-8b1e-f5b1c7a03632)

**Comment by Meeeds** [comment]
I have the same issue ! Thanks for mentionning that there is no bug with  "Battle Pass 2022" HUD

**Comment by robert-gogolan** [comment]
The issue **is present** on these HUDs:
- Default
- Cruel Diretide
- Crystallized Mana
- Mana Pool 
- The International 2016

- **Works on**:
- Battle Pass 2022
- The International 2021

**Comment by eugene-valve** [comment]
This should be fixed in an upcoming update, thank you everyone for your bug reports.
