### ISSUE TITLE
Bring back cloud shadows

### ISSUE THREAD

**Issue by xdugyx** [ValveSoftware/Dota2-Gameplay#899]
When Dota 2 was ported to Source 2 we lost many atmospheric elements. Please, bring back cloud shadows and atmospheric fog!

![vlQt1Nu](https://user-images.githubusercontent.com/107167740/172768659-fc8dd76d-0d1d-478c-9512-b34ddbfcf854.gif)

**Comment by DuMuT6p** [comment]
The Summer update added the cloud shadows - https://www.dota2.com/summer2023. We can probably close the issue.
