### ISSUE TITLE
So many missing items from my inventory

### ISSUE THREAD

**Issue by endrureza** [ValveSoftware/Dota2-Gameplay#8996]
I'm decided to play dota 2 again for after so long time, but somehow so many items missing from my inventory. I haven't done any transaction related to dota 2 at all for that long.

**Comment by commentator24** [comment]
should close this issue, this is not the place to ask support for your missing items. 
did you even check your dota gifting history and trade history?

**Comment by endrureza** [comment]
Care to suggest where can i ask about this problem ? @commentator24 , i've already checked my gifting and trade history and there is no such transaction regarding the missing item yet my item is missing.

**Comment by commentator24** [comment]
![image](https://user-images.githubusercontent.com/109324155/236504545-c141b4d5-d4c7-49d6-9fcc-6b59d3f3f3cd.png)
