### ISSUE TITLE
Fate's Edict relic issue

### ISSUE THREAD

**Issue by KArlek1no** [ValveSoftware/Dota2-Gameplay#9007]
### Ability name

Fate's Edict

### Description

There is some issue with Oracle Fate's Edict relic. The amount of blocked damage is calculated incorrectly after each game after the update 7.33. It shows about 100 - 300 damage, which is obviously not true.

### Example Match ID (and possibly Timestamp)

7139230895

**Comment by Aluerie** [comment]
Added to #8899

**Comment by chrisf-valve** [comment]
This has been fixed in today's update
