### ISSUE TITLE
Roshan Gateway bug

### ISSUE THREAD

**Issue by TylorBurgan** [ValveSoftware/Dota2-Gameplay#9013]
### Description

as normal, at 35mins time switches from day to night and Roshan moves up to the gate and teleports, however immediately after teleports back and stays in the incorrect Roshan pit for the rest of the game. Thought the enemy team was making it up until I checked the replay. the game doesn't go beyond the 45min mark so its hard to tell if it was only once or bugged for the rest of the game.

### Example Match ID (and possibly Timestamp)

7140758886 - 35:00

### Screenshots

![Rosh_bug](https://user-images.githubusercontent.com/114634280/236588269-2c04d418-c249-40b1-b9fb-8686e7d0f3f8.png)

**Comment by artillicime** [comment]
Happened something similar to me too... forgot to report, etc.

**Comment by Tenzarian** [comment]
same thing happened to me, Roshan was on radiant side, at day/night change at 30m he uses the radiant gate, teleports to dire gate, then uses dire gate and teleports back to radiant pit.
match id: 7156386690

**Comment by commentator24** [comment]
seems fixed like #8577, should close this issue
