### ISSUE TITLE
Neutral tokens found by Arc Warden's Tempest Double become unavailable for the team

### ISSUE THREAD

**Issue by AdamAndrewsSU** [ValveSoftware/Dota2-Gameplay#9022]
Hi,

This bug concerns the interaction between neutral token drops/teleporting to base, and the Tempest Double illusion for the Arc Warden.

## Description:

Neutral tokens found by a hero, beyond the first one, is expected to be automatically teleported to the team's pool of tokens for team mates to choose from. 

However, in the game that I played, the Arc Warden in my team discovered two neutral tokens with his Tempest Double. While these were immediately teleported away, they were not available for the team mates. This bug also appears in the replay itself, by the number of available tokens not increasing after tokens are found/teleported.

It seems to also be irrelevant if the Tempest Double uses Hand of Midas to find a token, or gets the last hit on the neutral creep.

## Example Match ID (with times stamps):

Match ID: 7140433806

19:33: Arc Warden's Tempest Double uses Hand of Midas on the Satyr Mindstealer, which triggers a Tier 2 Neutral token to appear, which is instantly teleported away. However, it is not available for the team via the neutral item shop.

19:37: Arc Warden's Tempest Double gets the last hit on the Satyr Tormenter, which triggers another Tier 2 Neutral token to appear, which again is instantly teleported away. However, it is not available for the team via the neutral item shop.

### Image one: neutral items and time stamp, before the bug occurring:

![Pre_bug](https://user-images.githubusercontent.com/43173039/236620390-0f9d4629-607d-451b-a653-b2d5c6bd94a7.png)

### Image two: neutral items and time stamp, after the bug occurring

![Post_bug](https://user-images.githubusercontent.com/43173039/236620399-11eb6e5a-02a0-4ff7-838d-98fba28d0dd8.png)

__Note here the mismatch between number of Tier 2 Neutral Items found, versus in use by the team__

**Comment by BdBrian** [comment]
This happens with Monkey King Aghanim's Scepter as well. The clone will automatically send a dropped neutral item to base, except it just disappears to the void and the team cannot access it.

**Comment by nathank-valve** [comment]
Should be fixed now. Closing.
