### ISSUE TITLE
Arcane Blink

### ISSUE THREAD

**Issue by SirBocha** [ValveSoftware/Dota2-Gameplay#9028]
### Item name

Arcane Blink

### Description

Bad bonuses when using Arcane Blink

### Example Match ID and Timestamp

-

**Comment by Aluerie** [comment]
ehm but the bonus is insanely good blink cd, extra 200 distance and it's in tooltip..?
![image](https://user-images.githubusercontent.com/33165440/236641266-7b21f24d-66b3-4784-b92f-090b42405f97.png)

**Comment by SirBocha** [comment]
Ooo Cool bonus for 6800 gold. I wonder how many times players will buy it? 
It was possible, when using a blink, to reduce a little cd of spells and mana consumption on them.

**Comment by Aluerie** [comment]
Oh I thought you reporting some tooltip bug, like Octarine has.

Well, this repo is not for patch suggestions.

**Comment by SirBocha** [comment]
Так это и есть ошибка, недороботка вещи.

**Comment by SirBocha** [comment]
Let the range of the ability increase and more ...

**Comment by SirBocha** [comment]
Aluerie, who are you?

**Comment by SirBocha** [comment]
I generally keep quiet about the new super ill-conceived map. Especially the bottom creep camp which is located on the low ground

**Comment by SirBocha** [comment]
Blood grenade = unbalanced item

**Comment by ValveHatesDotA** [comment]
> ehm but the bonus is insanely good blink cd, extra 200 distance

It also doesn't belong in the game though. Blink was always partially balanced by the fact that it had no upgrades. Made it less braindead of an item purchase too.
