### ISSUE TITLE
Immortal draft without a player selection stage

### ISSUE THREAD

**Issue by pryadadev** [ValveSoftware/Dota2-Gameplay#9030]
### Description

I clicked role search. I got into the game without roles under the icons of the players on top. According to this, it can be judged that the game is in immortal draft. But there was no player selection stage. The players were already in the teams and the ban stage immediately began. There was confusion because no one knew what his role was. Being the support of the 5th position, I had to play offline, which is why, for the most part, we lost.

- Match ID: 7141931241
- Steam Profile Link: https://steamcommunity.com/id/satona76/

### Example Match ID (and possibly Timestamp)

7141931241

**Comment by pryada2001** [comment]
I met this issue again. Match ID: 7144443131

**Comment by pryada2001** [comment]
Met this issue again. Match ID: 7146020968
[A screenshot of what you see as soon as the match starts](https://fastpic.org/view/121/2023/0509/_a336f4f1fda11bb5af6cf11264c88dbc.png.html)
Please note that the players have no roles
