### ISSUE TITLE
Permanently lose meepo clone if you cast Megameepo fling with pre-mature megameepo

### ISSUE THREAD

**Issue by DpRd745** [ValveSoftware/Dota2-Gameplay#9043]
### Ability name

megameepo

### Description

if you have 2 clone, 1 is next to you and the other is far from you.
Your main meepo casts megameepo. Right after the first one arrived you fling it to the target immediately while the other clone is still megameepo-flying to your main meepo.  It will result the other clone permanently lost in the game. 
The picture below shows it will soon disappear in game like a corpse.

![image](https://user-images.githubusercontent.com/106855630/236670262-139702e9-e86c-4371-9bd2-eb41d956d36d.png)
![image](https://user-images.githubusercontent.com/106855630/236669712-c48f0b1b-c27f-4fc5-9cae-4190f835292f.png)

### Example Match ID (and possibly Timestamp)

7141982612 - 12:59

**Comment by nathank-valve** [comment]
This will be fixed in the next hotfix. Closing

**Comment by DpRd745** [comment]
Thank you!
