### ISSUE TITLE
The problem when Doom using Ultimate in Lotus on enemy having an aghanim, then aghanimed Doom returned to Doom 

### ISSUE THREAD

**Issue by 734maboy** [ValveSoftware/Dota2-Gameplay#9044]
### Item name

Lotus Orb

### Description

there was a bug when DOOM used his ultimate (without having an aganim) in lotus on Lina, which had an aganim, back to Doom returned an aganimed ultimate, it must be a bug :`D
![photo_2023-05-07_14-30-18](https://user-images.githubusercontent.com/47525374/236675043-2a1af3b2-d6ae-46a5-a897-e00ecb014419.jpg)
![photo_2023-05-07_14-29-35](https://user-images.githubusercontent.com/47525374/236675049-6443322d-b31c-446b-a065-b8b93d0d1694.jpg)

### Example Match ID and Timestamp

7142257774 - 35:30

**Comment by rapturemain** [comment]
Works as intended since  
> Abilities reflected receive its Aghanim's Scepter upgrades only if the reflecting hero has Aghanim's Scepter, regardless of whether the original caster has it or not. This applies to abilities upgraded by Talent and Aghanim's Shard as well.

**Comment by 734maboy** [comment]
> Works as intended since
> 
> > Abilities reflected receive its Aghanim's Scepter upgrades only if the reflecting hero has Aghanim's Scepter, regardless of whether the original caster has it or not. This applies to abilities upgraded by Talent and Aghanim's Shard as well.

Okay got it, i thought that was not correct behaviour, sorry
