### ISSUE TITLE
Heart of Tarrasque was put in neutral item slot

### ISSUE THREAD

**Issue by rapsiboy** [ValveSoftware/Dota2-Gameplay#9052]
### Item name

Heart of Tarrasque

### Description

Heart of Tarrasque was put in neutral item slot. Works for meepo. Stats was added as well. 
i tried this on demo hero as well. works for meepo.  

Bug Description:
Match ID (important): 7143408045
Your Steam Profile Link (important): https://steamcommunity.com/profiles/76561198243256430/
Other Helpful Information:  done at 18:33 on my game. 

### Example Match ID and Timestamp

7143408045 - 18:33

**Comment by seowth** [comment]
I don't think it's a bug - Meepo's 2nd LVL 25 talent - [Pack Rat] - allows Meepo to equip regular items in the neutral item slot. It's a turbo game right? That's why it was done so quickly.

**Comment by rapsiboy** [comment]
Ohh, i see.
