### ISSUE TITLE
Hero relics still shown in "Dota plus percs"

### ISSUE THREAD

**Issue by heywood8** [ValveSoftware/Dota2-Gameplay#906]
### Description

Hero relics are now available to all players, but still shown in description for Dota Plus as percs

### Screenshots

![image](https://user-images.githubusercontent.com/11490740/172774977-af8efade-510d-4192-9b9f-59687b0589d2.png)

**Comment by Daar543** [comment]
Currently not a bug since they do not actually work without DotaPlus :D

**Comment by heywood8** [comment]
I'm not gonna lie, you got me in the first half
