### ISSUE TITLE
[7.33] Items that cost HP show their cost while in backpack

### ISSUE THREAD

**Issue by Aluerie** [ValveSoftware/Dota2-Gameplay#9074]
![hp-backpack](https://user-images.githubusercontent.com/33165440/236805684-bbcd2b8b-df7e-48b2-93fa-7ef3f5a4aa8d.png)

It's just inconsistent. 

Items that cost mana do not show their cost while in backpack - as we can see Pavise doesn't tell its mana cost, while blood grenade does. So it should be changed to either show mana costs or not show hp costs. 

Same with Soul Ring:

![image](https://user-images.githubusercontent.com/33165440/236815960-a634d5bf-29c1-442b-9fcd-a5a245ee0fb5.png)

**Comment by eugene-valve** [comment]
This should be fixed in an upcoming update, thanks!
