### ISSUE TITLE
Смотритель

### ISSUE THREAD

**Issue by Aaatata** [ValveSoftware/Dota2-Gameplay#9080]
### Ability name

Смотритель

### Description

В рейтинговой игре команда сил тьмы на 28:21 убивает рошана и сразу после этого абсолютно все смотрители на карте становятся под их контролем.

### Example Match ID (and possibly Timestamp)

7145384245

**Comment by rapturemain** [comment]
Works as intended since

> When Roshan is killed, all Watchers (including the destroyed ones) are automatically captured for the killer's team
