### ISSUE TITLE
Glicko isn't working porperly? Hidden pool or tagged account?

### ISSUE THREAD

**Issue by baby-mama** [ValveSoftware/Dota2-Gameplay#9092]
I first played a match, where a party of two players refused to coop (Match 7146247708). Guys dind't listened to calls and just were throwing the game, anwsering in voice "we don't care". I got **-40** mmr for this game with stat 5/5/4. Not the best game from me, but why I lose so much mmr? I even solo killed this omniknight on mid. 
Best part og the story is ahead. Next game, I play Void Spirit (Match 7146278612) with 21/0/12 and getting only **38** mmr, as **match best player** with great impact in the game and good space for my Anti-Mage carry. 
All this means i have **loss** of 2 mmr, allthough I tried hard in both games. This makes upranking absolutely impossible, with winrate ~50%. 
It's started since new callibration. I get only few mmrs for win every time and lose therefore **>40** mmr for every lose, no matter what impact I did in this game. Another great example: Match 7146247708. We got overdrafted and I got charged >40mmr with 39 assists a lot of impact on the game.
Is there any way my account is on some list(ex: hidden pool)? otherwises I cannot explain it. There are ofc games I could play a way better, as everyone of us as humanbeeing. But before new patch I had more mmr (200 mmr more as now) and it kept growing, when I played seriously and full effort.

**Comment by baby-mama** [comment]
Please upvote, if you have the same issue

**Comment by baby-mama** [comment]
> Your performance, score or anything doesn't matter for mmr gains.
> 
> Only your and other players rating number, your and other players variance number (which is roughly presented by confidence) and match outcome.

i played against ancient 4 on mid. even if you are right, and the only rating numbers is important - other players had +- same rating, which meand the game should think we should deffinitely win against ancient 4, who has 2000mmr more?

**Comment by Aluerie** [comment]
You only played around 10 ranked games on this account since 7.33. Meaning your rank confidence is probably low. And at low confidence numbers +-40 is a normal thing at balanced games. The higher the confidence - the lower the gains at balanced matches without anomalies. You can read some ideas of this algorithm [here](https://en.wikipedia.org/wiki/Glicko_rating_system#The_algorithm_of_Glicko)

**Comment by baby-mama** [comment]
> You only played around 10 ranked games on this account since 7.33. Meaning your rank confidence is probably low. And at low confidence numbers +-40 is a normal thing for balanced games. The higher the confidence - the lower the gains (assuming no anomalies). You can read some ideas of this algorithm [here](https://en.wikipedia.org/wiki/Glicko_rating_system#The_algorithm_of_Glicko)

I guess you missing my statement.  I know how Rank confidence is working. But, what I wanted to say, that no matter how I play and no matter who I’m playing against, it feels that the system is working false. As for example: win 2 games and lose 2 games would make me -10mmr. And also you said: it’s based on players mmr only. Okay, but why I get -40 for a lose against a ancient 4 and get charged so much and my wins getting me such low amount of mmr. Just think how unfair this sounds, a 2900mmr player should win a 5500mmr player, according to system. Because you get more mmr charged if you lose against WEAK enemy player.  How could that be possible?

**Comment by commentator24** [comment]
> I know how Rank confidence is working.
are you sure..? then you should already know that all matches will be around 39-40 mmr per game no matter what until 45% rank confidence.. doesn't matter what medal you vs against. It will be 39 or 40 mmr. the system only try to find similar skilled opponents for you.
then you will get less and less mmr like me #8421
so you should be happy that you still get 40 mmr per game. though i feel the new system should reset to 0% everytime we reach 100% rank confidence or something.. or perhaps for every new season. e.g. next one June 1st hopefully.

while it does seems unfair and the system feels like matching you with unfair opponents, it's like battlecup.. if your party has a tier 6 then you'll meet another tier 6 party. apparently your doom was the tier 6 (ancient 1)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109324155/c630d43e-8aaf-49c6-9aa4-e9cca86952cd)

and you should already know if you're on a win streak then you get worse and worse teammates until you lose 3-4 games and it's back to normal to get you that 50-50 winrate algorithm 😆
