### ISSUE TITLE
game crash for all players by earth spirit

### ISSUE THREAD

**Issue by crusty5g** [ValveSoftware/Dota2-Gameplay#9097]
### Description

we were winnig this ranked game
match id: 7146231495
earth spirit at 
48:40 selling his items and buy refresher orb then at
49:10 he rapidly uses all stone remenant and magnetize to make game crash
and game turnes to safe to leave and he saves his mmr and we don't get our mmr

### Example Match ID (and possibly Timestamp)

7146231495

**Comment by Avarise831** [comment]
#9086
