### ISSUE TITLE
EARTH SPIRIT'S AGHANIM 

### ISSUE THREAD

**Issue by SuctionSemen** [ValveSoftware/Dota2-Gameplay#9099]
### Ability name

ENCHANT REMNANT

### Description

Enchant remnant deals no damage after the end of the effect, but deals damage while under BKB effect.
Please(( fix it. 

### Example Match ID (and possibly Timestamp)

Don't have it (

**Comment by TheUnholyWrath** [comment]
It is working correctly for me, can you check and see if this has been fixed. If it is still bugged for you, please upload a video of how you are replicating the bug
