### ISSUE TITLE
ogre magi 17% fire blast chance on attack talent bug

### ISSUE THREAD

**Issue by linpyaeaye** [ValveSoftware/Dota2-Gameplay#9101]
### Ability name

17% fire blast chance on attack talent 

### Description

If you take the 17% fire blast chance on attack talent on ogre magi after buying aghanim's scepter and sell it, it will no longer proc the fire blast on attack chance ,until you buy aghanim's scepter again.

### Example Match ID (and possibly Timestamp)

Tested on demo hero

**Comment by Nathanael-Valve** [comment]
Fixed in next update.
