### ISSUE TITLE
the thing sold itself

### ISSUE THREAD

**Issue by useless7202** [ValveSoftware/Dota2-Gameplay#9118]
### Description

https://github.com/ValveSoftware/Dota2-Gameplay/assets/133148998/690e2ea4-d5ff-4d90-a733-f8f3eaeca198

Before I died, I bought the thing, and it sold itself for some reason

### Screenshots

no

**Comment by commentator24** [comment]
play the video at 0.25 speed. then you'll see you were too late and didnt actually buy it. 
if you bought it wouldve gone to stash first anyway

you can close the issue

**Comment by useless7202** [comment]
The item was rolled out of the bottom right corner, and there was a purchase sound, are you saying that I didn't have time to buy it?

**Comment by useless7202** [comment]
how to close?
