### ISSUE TITLE
Dota Plus Challenge for Lone Druid to Heal X HP from Spirit link is unable to be completed

### ISSUE THREAD

**Issue by worm45s** [ValveSoftware/Dota2-Gameplay#9121]
### Description

Dota Plus challenge "Heal X / Y / Z HP from Spirit Link" for hero Lone Druid is unable to be completed, nothing counts towards the progression.

### Example Match ID (and possibly Timestamp)

7148761689

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/130658065/5b272a15-6e1c-42e5-85cc-d83ba6f755d8)

**Comment by commentator24** [comment]
it doesn't progress if you're at full hp.. 

unless they did something different this patch. im pretty sure i've done this challenge many times

**Comment by worm45s** [comment]
> it doesn't progress if you're at full hp.. and you need to damage enemy heroes
> 
> unless they did something different this patch. im pretty sure i've done this challenge many times its quite easy

I'm aware of that, all game it stayed at 0, I did plenty of damage and healed using it. It's currently bugged.

**Comment by commentator24** [comment]
i dont know why but i keep crashing trying to watch your replay. i think cannot watch replays at the moment

**Comment by commentator24** [comment]
#9153

**Comment by worm45s** [comment]
the issue has been fixed as of 7.33c
