### ISSUE TITLE
Не работают реликвии

### ISSUE THREAD

**Issue by kkpunep** [ValveSoftware/Dota2-Gameplay#9134]
Приобрел все реликвии на героя, у половины поднимается уровень, а у других не поднимается, хотя задания выполняю.
ID: 110568998
дата 6.05.2023 время 20:53
игра 7141867614
Время в игре 15:30-15:40
![2023-05-04_23-21-28](https://github.com/ValveSoftware/Dota2-Gameplay/assets/133261004/6f4cd488-116c-4cbb-b593-6d02e888fd29)
![2023-05-06_22-21-16](https://github.com/ValveSoftware/Dota2-Gameplay/assets/133261004/8b5a8b11-c4b1-4819-9c50-8515b532d35d)
![2023-05-04_23-20-57](https://github.com/ValveSoftware/Dota2-Gameplay/assets/133261004/25f6684b-a210-4b4d-be0c-e85fa25a1dd8)
![2023-05-06_22-20-03](https://github.com/ValveSoftware/Dota2-Gameplay/assets/133261004/4ae02d57-b496-438e-92ee-c6d56d230be0)

https://github.com/ValveSoftware/Dota2-Gameplay/assets/133261004/eb057ee9-17ce-4483-89f9-31d184693115

**Comment by Aluerie** [comment]
#8899

**Comment by kkpunep** [comment]
> #8899

Добрый день! Дополнил тему скринами и видео.
