### ISSUE TITLE
Client crashes while watching replays

### ISSUE THREAD

**Issue by Scionara867** [ValveSoftware/Dota2-Gameplay#9140]
### Description

My dota client crashes after watching a few minutes. I had tested with another replay I watched earlier today, and my client still crashed.

Verifying files and rebooting my PC did not work.

**Comment by archcorsair** [comment]
Same issue! I thought maybe it was related to specific match ids, here are some IDs where I have confirmed reproducible crashes:
- 7148379578
- 7144240501

Playback works until around first blood (for both).

**Comment by PrivateKlinch** [comment]
All replays I checked today crashed the game.

**Comment by vincent2092** [comment]
me tooI can't create new content today.

**Comment by ayushkamadji** [comment]
> Check if disabling 3rd party software like Logitech Game Hub solves your issue: [#9153 (comment)](https://github.com/ValveSoftware/Dota2-Gameplay/issues/9153#issuecomment-1546588882)

Tried this workaround, but still crashing for me.

**Comment by Nathanael-Valve** [comment]
Fixed

**Comment by TheGreatGimmick** [comment]
> Fixed

This has not been fixed, as per https://github.com/ValveSoftware/Dota2-Gameplay/issues/9523
