### ISSUE TITLE
Zeus Shard is Bugged ( wont release lighting when hitting = cant deal dmg from the shard )

### ISSUE THREAD

**Issue by marcokidkgb** [ValveSoftware/Dota2-Gameplay#9145]
### Ability name

Lighting hands

### Description

Steam ID: https://steamcommunity.com/profiles/76561198130825966/
From the min 35 to the rest of the match: doesnt have effect of the arc lighting from the aghanim 's shard. Even dying cant solve the problem

### Example Match ID (and possibly Timestamp)

7150565666 - 35:20

**Comment by yckmm** [comment]
#8301 you probably disabled autocast.
