### ISSUE TITLE
Manta Style/Mega Meepo interaction

### ISSUE THREAD

**Issue by UltrosFF** [ValveSoftware/Dota2-Gameplay#9148]
### Ability name

Mega Meepo

### Description

If you use manta style after using Mega Meepo, all the Meepos mounted will pop out instantly with the Manta.
I don't think that's expected behavior.

### Example Match ID (and possibly Timestamp)

7150825044 - 23:15-23:25

**Comment by voddov** [comment]
Even illusion rune cancels MegaMeepo which i believe is a bug too.

**Comment by Avarise831** [comment]
#8074
