### ISSUE TITLE
Replay bug

### ISSUE THREAD

**Issue by Dandris123** [ValveSoftware/Dota2-Gameplay#9149]
### Description

If you want to watch back replays at some point the game will crash. I tried steam restart but it made it even worse, i clicked on "watch replay" and it crashed instantly. Also there's a lot of people who has the same issue.

### Example Match ID (and possibly Timestamp)

Client bug

**Comment by Dandris123** [comment]
my description explains everything

**Comment by Avarise831** [comment]
#9140

**Comment by Nathanael-Valve** [comment]
Fixed
