### ISSUE TITLE
the game crashes when viewing a certain replay

### ISSUE THREAD

**Issue by betwayasd** [ValveSoftware/Dota2-Gameplay#9153]
### Description

7150181243 
the game crashes at 12:03

### Example Match ID (and possibly Timestamp)

7150181243 12:03

**Comment by adamschroder** [comment]
I was going to post a new issue, but I had the same issue with this replay: 7149097720

**Comment by ayushkamadji** [comment]
+1 this, all replays I tried crash a few minutes into the game for me

**Comment by GauravDe-git** [comment]
+1 all replays I download and try to watch crashes after few minutes into the game

**Comment by 4Quick** [comment]
+1 . Replay 7143520855 . First blood . Crash.

**Comment by ayushkamadji** [comment]
> Please submit gameplay bugs for the Dota team to look at here. We'd like to use the "thumbs up" reaction as an upvote to track priority from the community, so to "+1" an issue please add a thumbs up reaction to it.

Don't forget to thumbs up reaction on the original issue post folks

**Comment by ayushkamadji** [comment]
> > Please submit gameplay bugs for the Dota team to look at here. We'd like to use the "thumbs up" reaction as an upvote to track priority from the community, so to "+1" an issue please add a thumbs up reaction to it.
> 
> Don't forget to thumbs up reaction on the original issue post folks

give a thumbs emoji on the first comment

**Comment by w200me** [comment]
+1
I asked for help JJ and he checked crash file:
"so what happens is that the Dota 2 process tries to read or write memory it doesn't own"

**Comment by ayushkamadji** [comment]
> @ayushkamadji it is no bug that Valve has to fix. It is a bug that Logitech has to fix. (at least in my case)
> 
> The issue was solved for me after disabling GHUB Integration (tried several replays, no crash anymore), therefor I can't confirm this issue and a 👍 would be false.

@anotherCoward got it 👍

I'm also reminding everyone who hasn't so the issue can be prioritized

**Comment by adamschroder** [comment]
FWIW, I don't have this GHUB integration, and I'm experiencing t he crashes still.

**Comment by 4Quick** [comment]
+1 to adam's post. I do not think Logitech is a problem here. Valve has to look into this. I had the Logitech Gaming Software which I turned off and removed all background processes of Logitech. Doesn't help. Still crashes. Same replay 7143520855 now doesn't crash at first blood but at the 2:00 mark. Happens after a kill/death event.

**Comment by Dandris123** [comment]
> Seems to be related to some 3rd party software, had a crash too, caused by Logitech Game Hub when skipping scenes fast.
> 
> XML report from Event Viewer
> Edit: After deactivating the GHUB integration for the game, it didn't crash anymore.
> 
> To deactivate the integration for a specific game:
> 
> * Open Logitech Game Hub
> * Click on the Menu Icon in the upper left corner
> * Choose `Videogames & Apps`
> * Search for `Dota 2` and click on it
> * Go to `Integration`
> * And click on `Deactivate`

I don't have logitech gamehub but still have the same crashes_

**Comment by Dandris123** [comment]
> @Dandris123 there can also be other software that interacts in some way. The easiest way to check what could've caused the crash is the Event Viewer.
> 
> I also added in a later reply, that it just solved the issue for me. It doesn't mean it works for everyone or that everyone uses Logitech Products who is affected by this. I just added it here, as it is also related to crashes that can occur only during replays.
> 
> To view the log entry on the Event Viewer:
> 
> 1. Press Windows Key + R
> 2. Enter `eventvwr.msc` into the prompt and confirm it.
> 3. Inside the Microsoft Management Console expand `Windows-Protocols`
> 4. Navigate to `Applications`
> 5. Search for a `Application Error`  (column Source) that occured at the time when DotA was just closed without any message.

Normal replays seem to be fine, but still league game replays are crashing out.
I checked the  application error, there was nothinh.

**Comment by Dandris123** [comment]
> @Dandris123 there can also be other software that interacts in some way. The easiest way to check what could've caused the crash is the Event Viewer.
> 
> I also added in a later reply, that it just solved the issue for me. It doesn't mean it works for everyone or that everyone uses Logitech Products who is affected by this. I just added it here, as it is also related to crashes that can occur only during replays.
> 
> To view the log entry on the Event Viewer:
> 
> 1. Press Windows Key + R
> 2. Enter `eventvwr.msc` into the prompt and confirm it.
> 3. Inside the Microsoft Management Console expand `Windows-Protocols`
> 4. Navigate to `Applications`
> 5. Search for a `Application Error`  (column Source) that occured at the time when DotA was just closed without any message.
> 
> If there is nothing listed in the Event Viewer, DotA itself has crashed "normally" and should've created a `.mdmp` file next to the binary. These files are stored under `\steamapps\common\dota 2 beta\game\bin\win64` and are named `dota2_yyyy_mmdd_hhnnss_0_shortTextOfTheCause.mdmp`
> 
> For example: `dota2_2023_0513_094351_0_accessviolation.mdmp`
> 
> In this case, you could attach them (must be compressed using zip) with your post here.
> 
> There are several interactions that can cause a crash in replays with Broadcasters currently.
> 
> * I can confirm the crash in the replay 7143520855 at the moment when DS kills CM at the bottom lane with Vacuum.
> * Another crash happened when changing the camera settings on the same replay.
>   
>     
>       
>       
>   
>       7143520855_crashes.mp4
> 
> Dump Data

**Comment by Dandris123** [comment]
@anotherCoward here it is.
[dota2_2023_0514_133425_0_accessviolation.zip](https://github.com/ValveSoftware/Dota2-Gameplay/files/11471792/dota2_2023_0514_133425_0_accessviolation.zip)

**Comment by w200me** [comment]
any update on this?

**Comment by Dandris123** [comment]
> @Dandris123 there can also be other software that interacts in some way. The easiest way to check what could've caused the crash is the Event Viewer.
> 
> I also added in a later reply, that it just solved the issue for me. It doesn't mean it works for everyone or that everyone uses Logitech Products who is affected by this. I just added it here, as it is also related to crashes that can occur only during replays.
> 
> To view the log entry on the Event Viewer:
> 
> 1. Press Windows Key + R
> 2. Enter `eventvwr.msc` into the prompt and confirm it.
> 3. Inside the Microsoft Management Console expand `Windows-Protocols`
> 4. Navigate to `Applications`
> 5. Search for a `Application Error`  (column Source) that occured at the time when DotA was just closed without any message.
> 
> If there is nothing listed in the Event Viewer, DotA itself has crashed "normally" and should've created a `.mdmp` file next to the binary. These files are stored under `\steamapps\common\dota 2 beta\game\bin\win64` and are named `dota2_yyyy_mmdd_hhnnss_0_shortTextOfTheCause.mdmp`
> 
> For example: `dota2_2023_0513_094351_0_accessviolation.mdmp`
> 
> In this case, you could attach them (must be compressed using zip) with your post here.
> 
> There are several interactions that can cause a crash in replays with Broadcasters currently.
> 
> * I can confirm the crash in the replay 7143520855 at the moment when DS kills CM at the bottom lane with Vacuum.
> * Another crash happened when changing the camera settings on the same replay.
>   
>     
>       
>       
>   
>       7143520855_crashes.mp4
> 
> Dump Data

Do you have any news?

**Comment by w200me** [comment]
Looks like new replays (1-2 days old) are fixed. Old replays are still broken, even tournament ones like ESL Berlin. Can we get a help?

**Comment by michaelarrington** [comment]
Make sure your [basketbros](https://iogamesio.org/basketbrosio) game has the most recent patches and upgrades. Updates are frequently released by developers to address bugs and boost stability.

**Comment by rony9707** [comment]
The game is crashing when running old replay's on new 7.33 patch. This maybe has something to do with the patch of the replay we are trying to see. The replay for the match id 5970615007 is not crashing but the the match id mentioned in this issue(6539826718) is crashing.

**Comment by robinh-valve** [comment]
This should be fixed in the next release that is going out in the next hour or so.
