### ISSUE TITLE
Invoker abilities in the hero page after Battle Report update.

### ISSUE THREAD

**Issue by acrubecz** [ValveSoftware/Dota2-Gameplay#916]
### Description

Redial blast and Aghanims icon were squished and misplaced? 

Suggestion, however: make a sub-menu and like how you can view all the spells of invoker from the in-game HUD.

### Screenshots

![image](https://user-images.githubusercontent.com/107175677/172792608-a39b95d6-2a53-4a8b-be38-38a7954eb9cd.png)

**Comment by shaileshgarg** [comment]
For Invoker Persona the abilitity icons are slightly larger than Normal Invoker abilities icons on Loadout.

**Comment by Aluerie** [comment]
![image](https://user-images.githubusercontent.com/33165440/201890484-47cab74e-1067-4f2a-9262-618af589d525.png)
fixed (I have 16:9 screen), I guess it's closeable 🤔

**Comment by shaileshgarg** [comment]
This can be closed
