### ISSUE TITLE
7.33C SPECIALIST'S ARRAY damage dealing is questionable.

### ISSUE THREAD

**Issue by DpRd745** [ValveSoftware/Dota2-Gameplay#9192]
### Ability name

Crackshot 

### Description

```
7.33C
SPECIALIST'S ARRAY (+5 all attributes, +12 damage )
Crackshot now deals 20 bonus damage
Crackshot now prioritizes heroes as secondary targets
```
1. When a ranged hero equips it, it only gives +20 damage rather than +32 damage (12+20=32).
After you hit the crackshot. +20 damage returns to +12 damage in cooldowns.
Crackshot now deals 20 bonus damage
**It should be the +32 damage rather than +12 damage.**
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/106855630/c86c4948-ad89-4d28-83eb-8f9ffa04e6aa)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/106855630/b9f4f441-eaa0-4587-b173-8c5d5ec02641)

2. When a meele hero equips it, it **always gives +20 damage rather than +12 damage and crackshot never goes to cooldown.**
Also, the bonus damage part is the same with the ranged hero.
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/106855630/c5382746-3d9e-4923-8e7b-0e9ed64d2437)

### Example Match ID (and possibly Timestamp)

DEMO

**Comment by commentator24** [comment]
then maybe just tooltip mistake. 20 bonus dmg while active and 12 during cooldown.

**Comment by DpRd745** [comment]
SPECIALIST'S ARRAY now deals +32 raw damage until crackshot is into cooldown. 
But meele hero still always has the free +32 raw damage because crackshot never goes into cooldown.

**Comment by commentator24** [comment]
seems fixed. 
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109324155/18ef13ff-c563-47d6-8931-f0d916b5d133)

should close the issue then. melee heroes are not ranged so it won't ever go into cooldown.
but i agree 32 dmg on melee seems a bit op for T2 token. it should've been 12 and no bonus 20 since that's for ranged heroes only.

**Comment by DpRd745** [comment]
All has been fixed. Thank you valve employee!
