### ISSUE TITLE
Muerta Ult Negates Magic damage

### ISSUE THREAD

**Issue by protagg** [ValveSoftware/Dota2-Gameplay#9207]
### Ability name

Pierce the Veil

### Description

Muerta Ult, Pierce the Veil, has a brief window of invulnerability where she will not take magic damage. Interaction was between Sniper and Muerta. Muerta was low health, Sniper tps in and ults. Muerta ults herself right before the sniper ult hits and lives.

### Example Match ID (and possibly Timestamp)

7155097834 - 3:34

**Comment by TheUnholyWrath** [comment]
I think Pierce the Veil disjoints projectiles on cast. It should have an alt text tooltip that mentions that it disjoints(similar to Chemical Rage)

**Comment by protagg** [comment]
> I think Pierce the Veil disjoints projectiles on cast. It should have an alt text tooltip that mentions that it disjoints(similar to Chemical Rage)

Is it only intended when ulting at a precise time? Because sniper can ult her and if she messes up the timing it hit her still.

**Comment by functionalleaf** [comment]
> > I think Pierce the Veil disjoints projectiles on cast. It should have an alt text tooltip that mentions that it disjoints(similar to Chemical Rage)
> 
> Is it only intended when ulting at a precise time? Because sniper can ult her and if she messes up the timing it will hit her still.

Yes she has a transform window of 0.35 seconds
