### ISSUE TITLE
Techies gaining control of sticky bomb

### ISSUE THREAD

**Issue by michaelmir915** [ValveSoftware/Dota2-Gameplay#9208]
### Ability name

Sticky Bomb

### Description

Techies can gain control of his sticky bomb by making it go through a twin gate. Watched an overwatch case where a techies used this to set up sticky bombs in the enemy fountain. He used this to premanently gain vision in the enemy fountain.
![20230514172533_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/89858891/4615c5dc-8734-4346-9e7e-35d5065a4e02)

### Example Match ID (and possibly Timestamp)

7151426562

**Comment by TheUnholyWrath** [comment]
#8703 You can close this issue.
