### ISSUE TITLE
Tango targets different tree

### ISSUE THREAD

**Issue by YashSwaraj** [ValveSoftware/Dota2-Gameplay#9229]
**Description**

Using tango causes your hero to walk across the map and eat some other random tree, making it basically useless

**Example Match ID**
7155994311(Spirit Breaker, First 5 minutes)
7156218758(Spirit Breaker, First 9 minutes)
7156261869(IO, First 2 minutes)

**Comment by tehybel** [comment]
As a workaround, try to toggle `cl_dota_unified_tree_hitboxes`.

**Comment by stevanstetzvanin** [comment]
I'm having this issue since update 7.34 (8 aug 2023), that issue is so annoying and it happens every game constantly.
