### ISSUE TITLE
Spirit Breaker (Charge BUG) i cant use it

### ISSUE THREAD

**Issue by Experiment626s** [ValveSoftware/Dota2-Gameplay#9242]
### Ability name

Charge of Darkness

### Description

On my game 15mins I die and then when I respawn I cant use my Firstskill I dunno what happen its a bug cause I buy refresher and even I use refresher my Firstskill is still loading I cant use. I hope my mmr will be back.
TIME 15:30
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/133744087/ad56eb4a-cbca-466b-83a9-60e251cb6ff6)

### Example Match ID (and possibly Timestamp)

7156731233

**Comment by Experiment626s** [comment]
even I use refresher it didt work!

**Comment by Avarise831** [comment]
#9218

**Comment by Nathanael-Valve** [comment]
Should be fixed next update.

**Comment by Experiment626s** [comment]
Thank you <3
