### ISSUE TITLE
Pavise showing wrong barrier color

### ISSUE THREAD

**Issue by SinaArya1** [ValveSoftware/Dota2-Gameplay#9244]
### Item name

Pavise

### Description

Since 7.33c, Pavise active shows the barrier hp as yellow rather than red for physical damage. Mechanically, it still functions as a physical barrier but in-game UI is bugged. 
![Screenshot (85)](https://github.com/ValveSoftware/Dota2-Gameplay/assets/67868912/8bcaf26f-c54d-464b-80c3-978cc35b63f2)

In the example match, Undying uses Pavise on a Void Spirit and since Resonant Pulse is a physical barrier, Pavise hp should also add to it but it shows a separate all damage barrier along with the physical barrier of Resonant Pulse. Also shown in the screenshot in demo mode. 

### Example Match ID and Timestamp

7154734955 - 8:04

**Comment by cadaeic** [comment]
It is very counter-intuitive that Pavise blocks physical spells while Resonant Pulse doesn't. Pavise didn't need buffs anyway, and the buff resulted in a hacky implementation that leads to confusing UI display.

For the record Resonant Pulse description is the same as Pavise's: "physical damage barrier".

It would be probably a lot clearer (and arguably more balanced) to revert the change and simply clarify that Pavise gives a "physical attack barrier".

**Comment by Nathanael-Valve** [comment]
Fixed in next update.
