### ISSUE TITLE
Axe Cull not counted

### ISSUE THREAD

**Issue by devotion26** [ValveSoftware/Dota2-Gameplay#9246]
### Ability name

Culling Blade

### Description

Axe performs a Culling Blade, but the target dies from a counter helix and then the culling blade animation starts. No permanent culled armor buff is given and no cooldown reset is given. However the culling blade buff is activated which is meant to happen from a culling blade kill.

### Example Match ID (and possibly Timestamp)

7156829275 -10:42

**Comment by TheUnholyWrath** [comment]
![20230517001806_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/46859977/b58ba032-21f9-4a98-b787-5d5695347f50)

You dunked a creep. Please close this issue.

**Comment by devotion26** [comment]
Should this be a fault with this english description then. "Axe spots a weakness and strikes, dealing pure damage. **When an enemy hero is killed** with Culling Blade, its cooldown is reset, Axe gains bonus armor permanently and all nearby allied units gain bonus movement speed." Specifically says enemy hero kill. Why does Axe get the culling blade buff from a melee creep?
