### ISSUE TITLE
earthshaker bug item on "Q" key 

### ISSUE THREAD

**Issue by Larajie** [ValveSoftware/Dota2-Gameplay#9255]
### Item name

anything item

### Description

any item u cant use on earthshaker when u setting the key on Q for the key press, it will tell u "the abillity is not learned" when i always using legacy key that earthshaker doesnt have Q for the abillity. hope u guys fix this faster , just felt this after the new patch -+ 40 min ago , im using dagger on my Q T-T so its big wave for me

### Example Match ID and Timestamp

7157684336 01:53

**Comment by bilalirfanpk** [comment]
Oh god same issue for me. And not just shaker but WR as well. I played with mirana and my Q item key works fine. WR and ES both have same issues. Will try on other heroes as well. I use Q for blink item key and I just couldn't play both games properly.

**Comment by Nathanael-Valve** [comment]
Should be fixed.

**Comment by Noname5666** [comment]
The same problem happen to me yesterday when I play WR it keep saying ability not learned

**Comment by Larajie** [comment]
broo my account still bug, cant party play arcade game, it said banned, but until like forever, the days count gonna be plus plus everydaySent from my iPhoneOn 18 May 2023, at 07.57, Nathanael-Valve ***@***.***> wrote:﻿
Should be fixed.

**Comment by philipborbon** [comment]
Existing now Juggernaut with legacy keys. Can't assign Q to items
