### ISSUE TITLE
Jugg skill problem and shortcuts for items

### ISSUE THREAD

**Issue by Zardonic98** [ValveSoftware/Dota2-Gameplay#9258]
### Ability name

the use of q and w in the jugg

### Description

I play with classic keys and I get skill not ready with the hero jugg with the letters Q and W and I use those letters for the shortcuts of my items it is super annoying and uncomfortable since that's why I lost my rank receiving reports flames in the middle of the game

### Example Match ID (and possibly Timestamp)

7157730876

**Comment by Aluerie** [comment]
Not sure what you even mean since Jugg legacy keys are FGCWE. No Q...

But just change your item keys ? 

Or untick legacy option and use unit specific keys and bind whatever you want to Jugg spells.

**Comment by Aluerie** [comment]
#9255

**Comment by Nathanael-Valve** [comment]
Should be fixed.
