### ISSUE TITLE
[7.31d] Shadow Demon Shadow Poison unmentioned change

### ISSUE THREAD

**Issue by porottaja** [ValveSoftware/Dota2-Gameplay#926]
### Ability name

Shadow Poison

### Description

While only the hit damage was supposed to be changed, the patch also changed level 2 stack damage from 36 to 32 for the ability.

![shadow_demon_731d](https://user-images.githubusercontent.com/13699929/172827173-3db798c1-147d-456e-b0d2-fa6a481ca374.png)

### Example Match ID (and possibly Timestamp)

Patch notes

**Comment by Dota-Exp** [comment]
This issue will be fixed in an upcoming update, thank you.
