### ISSUE TITLE
Juggernaut using Legacy keys and inventory key Q

### ISSUE THREAD

**Issue by kuber00t** [ValveSoftware/Dota2-Gameplay#9265]
Hi,

Just after last update i saw that when playing juggernaut with Legacy Keys option i am not able to keep using Q as an inventory key, as when i press Q it is saying "Ability not learned" as it is saying for other heroes that do have abilities on Q key. 
Juggernaut with legacy keys has only F,G,R,W as abilities.
I tried different heroes (ex. MK,WK) and as they don't have abilities mapped to Q key when using Legacy Keys and the Q set for the inventory is working with any items that have active effects.

**Comment by Asgeezy** [comment]
Same with Nyx Assassin

**Comment by diegodelzo** [comment]
Same here, I usually use Q to use my first item of my inventory

**Comment by thedinocomedy** [comment]
Same with Razor and the key "D"

**Comment by Aluerie** [comment]
#9255 duplicate, pls close, upvote original and comment extra details here.

**Comment by Nathanael-Valve** [comment]
Should be fixed.

**Comment by MostafaWmG** [comment]
This is not fixed
