### ISSUE TITLE
The DUEL stolen by RUBICK does not work properly

### ISSUE THREAD

**Issue by Tf4ilure** [ValveSoftware/Dota2-Gameplay#9269]
### Ability name

DUEL

### Description

Playing **Rubik**, I stole a duel from **Legion Commander** and used a **duel** in **Legion Commander**, which in turn used a **duel** on my allied hero. The **Rubick** duel lasts longer than the **Legion Commander** duel, but after the **Legion Commander** duel ended, the **Rubick** duel also ended.
Dear Dota _enjoyers_ (**developers**), please **FIX** it.

https://github.com/ValveSoftware/Dota2-Gameplay/assets/24322051/843d6457-6e2e-4c9d-ac21-d8097041fc38

### Example Match ID (and possibly Timestamp)

7157608737 - 9:05

**Comment by TheUnholyWrath** [comment]
The main Rubick issue is #561. This bug is already in there so you can close this issue. If you want to report any new Rubick bugs in the future, #561 is the best place to comment it, just make sure it hasn't already been reported. Thank you
