### ISSUE TITLE
Invoker persona loadout is broken

### ISSUE THREAD

**Issue by Crayz12** [ValveSoftware/Dota2-Gameplay#927]
### Description

full hd 16:9 display 

### Screenshots

![Screenshot_1](https://user-images.githubusercontent.com/70708880/172827756-1c07c88c-774b-4442-99b3-f03e20c3ef62.png)

**Comment by Crayz12** [comment]
UPD: exort sphere also has bugged particle
![Screenshot_3](https://user-images.githubusercontent.com/70708880/172829378-c6b5578a-810c-4ca7-9a42-1b3e98d4fb5e.png)

**Comment by guigax** [comment]
The loadout is a duplicate from #916 and the second issue should [have it's own issue open](https://www.reddit.com/r/DotA2/comments/v7az1m/bug_tracker_update_67/):

> If a single issue has multiple problems listed in it, one of the problems might be important and gather votes for the issue, but the other problems listed will "come along for the ride" and skip the voting process. To keep the voting process fair in this case, when a dev takes the issue, we'll address what appears to be the most important problem and ask that issues be created for any other problems so they can be voted on. This isn't a comment on the importance of those problems, it's just necessary that we do this so the voting system continues to work.

**Comment by shaileshgarg** [comment]
> UPD: exort sphere also has bugged particle ![Screenshot_3](https://user-images.githubusercontent.com/70708880/172829378-c6b5578a-810c-4ca7-9a42-1b3e98d4fb5e.png)

I had the same issue, lowing the graphics to low, and then high again fixed this issue for me.

**Comment by Aluerie** [comment]
![image](https://user-images.githubusercontent.com/33165440/201890484-47cab74e-1067-4f2a-9262-618af589d525.png)
As for now the problem in the first message looks fixed (I have 16:9 screen), I guess this issue is closeable 🤔

**Comment by shaileshgarg** [comment]
This issue can be closed
