### ISSUE TITLE
D and F hotkeys dont work for item usage with legacy keys

### ISSUE THREAD

**Issue by JustWinner** [ValveSoftware/Dota2-Gameplay#9270]
### Description

I play with legacy keys and i use different keys for item usage depends on the hero. Today i noticed that D and F got blocked from all heroes and it shows You havent learned this ability yet even to heroes who doesnt have D/F hotkey skill. Its extremely strange bug.

**Comment by Aluerie** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/9255

**Comment by Aluerie** [comment]
Looks like it's fixed, you can close the issue, if problem doesn't occur.

**Comment by JustWinner** [comment]
General problem has been fixed but it still exists when i play lone druid. Keys doesnt work for spirit bear
