### ISSUE TITLE
Disperser typo and convoluted tooltip

### ISSUE THREAD

**Issue by IngEyn** [ValveSoftware/Dota2-Gameplay#9276]
### Hero and spell

Disperser - Suppress

### Description

The first issue is that the word 'targeting' is not written with two 't's (as it is written 'targetting' in the current tooltip).

The second issue is that the tooltip is convoluted and can be difficult to understand as most of the effect is written down twice.

I'd suggest the following changes:

1. Clear the current tooltip.
2. Add the first section reading the following: 'If targeting an enemy, slows it for **4** seconds.'

- I've corrected the 'targeting' here already.
- I've left out the decreasing duration part as it returns later.

4. Add a second section reading the following: 'If targeting an ally, applies a basic dispel, increases their movement speed and makes them unslowable for **4** seconds.'

- I've removed the wrong 'and's after the commas.
- I've removed the 'by 100%' as it resurns later anyway and is true for both effects regardless.
- I've seperated the description of this effect from the decreasing duration part that follows later.

6. Add a third section reading the following: 'Both movement speed reduction and increase start at **100%** and gradually decrease to **0%** over the course of the duration.'

- I've combined both present decreasing duartion parts into one correct one.
- I've highlighted the '100%' and the '0%' for consistency reasons.
- I've added a '%' symbol following the 0 as it is also referring to the percentage number.

8. Leave in the 'Range: 600'.

Alternatively you could remove the '**4** seconds' parts in step 2 and step 3 and add it in step 4 instead of 'over the course of the duration' if you keep both at 4 seconds in the future.

The completely new tooltip would look like this:

"If targeting an enemy, slows it for **4** seconds.

If targeting an ally, applies a basic dispel, increases their movement speed and makes them unslowable for **4** seconds.

Both movement speed reduction and increase start at **100%** and gradually decrease to **0%** over the course of the duration.

Range: 600"

I've followed the notation of the tooltip of Spirit Vessel as it seperates the effects when targeting an enemy/ally instead of the one section present in Solar Crest (which should probably also be changed for consistency reasons).

### Screenshots

![grafik](https://github.com/ValveSoftware/Dota2-Gameplay/assets/6011827/431134ce-6b66-44d7-9b46-8213813eb9d4)

**Comment by Dota-Exp** [comment]
Good feedback. Will be updated in the next update. Thank you.
