### ISSUE TITLE
Item hotkeys bug after latest update 'Q' key

### ISSUE THREAD

**Issue by bilalirfanpk** [ValveSoftware/Dota2-Gameplay#9280]
### Ability name

Any item set on Q item key

### Description

I play with legacy keys and use item keys such as Q, SPACE, 1, 2 and 3 etc. No ability on heroes that I play have a key 'Q' beside jakiro and invoker yet heroes which doesn't have Q as their spell key such as WR, shaker etc; giving me error "Ability not learned". I have thoroughly checked my hotkey and advanced hotkey settings and checked hero spells shortcut/ability casting keys yet I am not able to fix it. I use Q for major items such as blink and magic stick etc which are really crucial in the game and now I am totally unable to focus due to this bug. Anyone else facing this issue?

### Example Match ID (and possibly Timestamp)

7159167660

**Comment by bilalirfanpk** [comment]
#9255

**Comment by Nathanael-Valve** [comment]
Should be fixed.

**Comment by philipborbon** [comment]
Existing now Juggernaut with legacy keys. Can't assign Q to items
