### ISSUE TITLE
Rubick Disappears after casting Death Seeker and then immediately stealing another spell

### ISSUE THREAD

**Issue by jurgyy** [ValveSoftware/Dota2-Gameplay#9293]
### Ability name

Death Seeker

### Description

If Rubick steals Death Seeker, steals another spell, then casts Death Seeker before the other spell is stolen, Rubick disappears completely from the map.

Example:
https://github.com/ValveSoftware/Dota2-Gameplay/assets/22032197/fb029fe0-80bc-4dda-8ee3-98d68974e1dd

### Example Match ID (and possibly Timestamp)

7159446347 - 20:30

**Comment by Aluerie** [comment]
Duplicate #8208

---
Please, close your duplicate issue and instead upvote the original one with "👍" reaction. Comment extra details if any.

And in future, first, use search to find out if the bug you want to report was already submitted by somebody else so you can upvote it and not clutter the repository with duplicates.
