### ISSUE TITLE
Game crashes when watching replays

### ISSUE THREAD

**Issue by weewaaweewaa** [ValveSoftware/Dota2-Gameplay#9312]
### Description

As title, game crashes when watching replays. Was watching tournament replays from Majors. Skipping time crashes the game, as does watching the replays on normal speed. Selecting a time using the time bar sometimes instantly crashes the game. 

Seems to be happening for replays from both the current patch and the previous patch.

Verifying integrity of Dota game files and restarting steam does not seem to fix the problem.

Seems to be an issue for other people since a week ago, since I found these 2 reddit threads:
https://www.reddit.com/r/DotA2/comments/13fb9f4/my_game_crashes_when_i_try_to_watch_replays/ 
https://www.reddit.com/r/DotA2/comments/13g70dt/replay_bug_game_crashes_while_watching_replays/

### Example Match ID (and possibly Timestamp)

-

**Comment by Aluerie** [comment]
Duplicate #9140

**Comment by w200me** [comment]
Im waiting for ESL Berlin Major replays 2nd week now. Same issue game crashing at specific moments. 
New replays (2-5 days old) working fine now.

**Comment by robinh-valve** [comment]
This should be fixed in the next release that is going out in the next hour or so.
