### ISSUE TITLE
Stone Remnant(9) + Refresher Orb(9)  = server crashes(18)

### ISSUE THREAD

**Issue by Toroh911** [ValveSoftware/Dota2-Gameplay#9313]
### Ability name

Stone Remnant

### Description

When a player buys a Refresher orb on an Earth Spirit and then uses 8 remnants in one spot, hits refresh, and uses 8 more remnants in the same area, the server crashes. 

### Example Match ID (and possibly Timestamp)

7161033899

**Comment by Jimmy9877** [comment]
Several people have had this happen be4

**Comment by Dota-Exp** [comment]
Issue will be fixed in upcoming update. Thank you.
