### ISSUE TITLE
enigma shiny particle tethers to spawn point?

### ISSUE THREAD

**Issue by jtz7575** [ValveSoftware/Dota2-Gameplay#9324]
### Cosmetic Item Name

armor of the twisted maelstrom 

### Description

the particle attached to his right shoulder, outermost tine, halfway tethers to the spawn point on the map and the further from that point i go, the longer the line becomes? my teammates see this too. it happens in regular lobbies and in demo mode 

my entire cosmetic lineup, in case this is due to an interaction between two items is as follows:

head- eye of twisted maelstrom
arms - world chasm artifact
armor - armor of twisted maelstrom
eidolons - inscribed geodesic eidolon
taunt - enigmatic style

it has been happening for several months now at this point, so i do not believe it to be something caused by the big 7.33 (dota4) update

![enigma cosmetic bug](https://github.com/ValveSoftware/Dota2-Gameplay/assets/134114399/ecaccb0c-e2e0-4337-98b9-ff37bede574b)

### Example Match ID

7159265105

**Comment by Astiberon** [comment]
#7333

**Comment by Aluerie** [comment]
This was fixed today, you can close your issue.
