### ISSUE TITLE
Poor network conditions have been detected. No stats will be recorded for this match. 9 Players Crashed except 1

### ISSUE THREAD

**Issue by Jimmy9877** [ValveSoftware/Dota2-Gameplay#9330]
### Description

I just played a ranked dota2 game and everything seemed to run perfectly fine, however at around a certain moment (28:57), near the midlane at the Radiant's base suddenly everyone disconnected/crashed except for Arc Warden - who is pushing the bot wave.

From what I have seen I think that it has something to do with everyone that had their camera near the midlane crashed (unsure)?
I have added evidence of the match - (4) video's and (2) screenshots.

1st video) ArcWarden's perspective and console shown
2nd video) Oracle (my) perspective of how the game crashed
3rd video) Watching how everyone crashed using free camera and player perspective and this time my game didn't crash when I used player view on me
4th video) Bounty hunter perspective - crashed at the same time

### Example Match ID (and possibly Timestamp)

7162711689 ~ 28:57

### Screenshots

https://github.com/ValveSoftware/Dota2-Gameplay/assets/91598432/45f72a48-9494-48a8-91fc-98935375faae

https://github.com/ValveSoftware/Dota2-Gameplay/assets/91598432/a67dcf7a-1227-457a-b790-0d04d46133f2

https://github.com/ValveSoftware/Dota2-Gameplay/assets/91598432/49465963-cd8d-4660-8a2e-df306343a5ed

https://github.com/ValveSoftware/Dota2-Gameplay/assets/91598432/c39b579f-d341-4cc7-b76c-380a63409460

![C1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/91598432/cc1acee1-13b0-4d0f-882b-54cf94caf4b1)
![C2](https://github.com/ValveSoftware/Dota2-Gameplay/assets/91598432/59ea9745-8970-4893-8790-074f91c04633)

**Comment by Avarise831** [comment]
#9086 es crash your game

**Comment by Jimmy9877** [comment]
You think so? It's possible I guess XD

**Comment by Jimmy9877** [comment]
Nvm I just read that issue I think that you're right thanks bro!

**Comment by Jimmy9877** [comment]
I saw it from ES pov again, with high certainty that he crashed the game on purpose so he doesn't lose mmr points.
Now I know about this thanks alot again man <3
