### ISSUE TITLE
Voodoo Switcheroo does not slow Death Ward attack rate

### ISSUE THREAD

**Issue by NogrTL** [ValveSoftware/Dota2-Gameplay#9346]
### Ability name

Voodoo Switcheroo

### Description

Voodoo Switcheroo say it has -30 attack speed but attack rate, attack speed is the same.

Either bug in Death Ward info or Voodoo Switcheroo doesn't apply attack slow

### Example Match ID (and possibly Timestamp)

demo

**Comment by TheUnholyWrath** [comment]
![20230521220622_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/46859977/095da502-842c-4c30-a3e5-6067cfc1cec5)
![20230521220655_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/46859977/170bd3f4-220b-4d87-8168-06324018df1c)

Voodoo Switcheroo definitely attacks slower than Death Ward.

**Comment by NogrTL** [comment]
In game tooltip is incorrect then. Both Death Wards has same damage, attack speed and attack rate.

Sample - LVL1 Death Ward 

AS - 772
AR - 0.22
DMG - 90


![20230522222224_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/12021449/f018b037-0fd5-42a4-8a00-1b24b97a6305)
![20230522222218_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/12021449/7ff0b290-7bee-49f7-8c39-2a699ae80846)

**Comment by Dota-Exp** [comment]
Fixed display issue in upcoming update. thank you
