### ISSUE TITLE
Dota2 freezes my whole computer (is unplayable).

### ISSUE THREAD

**Issue by 1username-102** [ValveSoftware/Dota2-Gameplay#9353]
## Problem Description

4-5 minutes into any Dota2 match, my whole computer:
* freezes the video, nothing on my monitor ever changes, no matter what keys I press
* begins to accelerate its fans **a lot**, without stopping
* outputs (through the speakers) a weird, **very loud** noise, **as if** the same audio buffer repeats endlessly

Once this problem occurs, the only way out is to hold the physical power butter on my computer until it shuts down everything.

This problem happened every single Dota2 match since I installed it, with the exception of just two games. It also happened two times on other video games (only after playing almost a hundred hours) - but it's clearly something with Dota2 due to the fact that it happens so often, only a few minutes in, every single time.

## Specifications / Settings

My computer's specifications are **way above** the minimum requirements for Dota2:
* i7, 8-core 3Ghz processor
* 16GB of RAM
* DirectX 12
* 275 Free GB (even after installing Dota2)
* Intel UHD Graphics 630
* Windows 11

Relevant Dota2 video settings:
* aspect ratio: 16:9
* brightness: 150%
* size: 1920x1080 (60Hz)
* display mode: exclusive fullscreen
* rendering API: Direct3D 11
* animate portrait: off
* additive light pass: off
* world lightning: off
* ambient occlusion: off
* normal maps: off
* ambient creatures: off
* ambient cloth simulation: off
* grass: off
* anti-aliasing: off
* specular: off
* specular and light blooms: off
* high quality water: off
* atmospheric fog / caustics: off
* high quality dashboard: off
* vsync: off
* tree winds: off
* compute shaders: off
* texture quality: low
* effects quality: low
* shadows: off
* game screen render quality: 40%
* FidelityX super resolution: off
* maximum frames per second allowed: 120
* dashboard maximum frames per second: 60

While the game runs (before the problem occurs), task manager indicates normal CPU and memory usage (around 2-3GB RAM). I do not know what the case is after the problem occurs, since I cannot check it.

## Things I tried

I tried:
* verifying (through Steam) the game files, nothing changed
* reinstalling the whole game 2 different times, nothing changed
* reinstalling Visual C++ Redistributables, nothing changed
* increasing the amount of virtual memory, nothing changed
* launching with the `-safe` option, nothing changed
* from Windows graphics settings, setting Dota2 to power saving mode, nothing changed
* from Windows graphics settings. setting Dota2 to high performance mode, nothing changed
* enabling, from Dota2 graphics settings, the "compute shaders" option, nothing changed
* updating (through Windows Settings), all of my drivers, nothing changed
* setting the graphics settings to be **the absolutely minimum possible**, except for maximum frames per second allowed, which I set to 120 instead of 60, and the game screen render quality to be 100%, the problem occurs almost instantly when I enter a match
* setting the graphics settings to be **the absolutely minimum possible**, except for maximum frames per second allowed, which I set to 120 instead of 60 (see the "Relevant Dota2 video settings" section of this bug report), the problem occurs usually after 4-5 minutes, as mentioned in the "Problem Description" section of this bug report
* setting  the graphics settings to be **the absolutely minimum possible**, makes the problem happen way later in the game

---

If any other information is needed, let me know. Thanks in advance for any help!

**Comment by commentator24** [comment]
maybe try -console mode and check console when it freeze or fps changed to get an idea? you can always see FPS in game if you tick box show network info

also check all 3 resolution settings.. e.g. display setting..nvidia (i dont know what intel graphics control panel has, but nvidia has resolution setting and 3D global settings that may interfere) and finally dota setting. I try to make all settings the same so pc not working too hard.
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109324155/59155e04-660f-488c-8f1a-5000161691af)

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109324155/9b9e630f-89ef-43ab-a7f0-053584ee38f4)
this is my setting. maybe try borderless window? and im not sure why mine set to 56% but i think i didnt change anything. just try reset first maybe.

**Comment by 1username-102** [comment]
Hello, @commentator24.

Launching the game with the `-console` flag didn't do anything. No console appeared in which I can see any logs. What can I do in order too see that window ?

Thanks in advance!

**Comment by commentator24** [comment]
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109324155/fbcdcbbb-999e-403b-8831-786133d6736a)

show network info is under options advanced
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109324155/eb34154c-3553-4ff0-86d4-fd7f88c2f7c6)

**Comment by 1username-102** [comment]
Interesting. I will check out the possible causes you mentioned. Thanks!
