### ISSUE TITLE
PL 4th skill + Radiance abuse in ranked

### ISSUE THREAD

**Issue by ste-lab** [ValveSoftware/Dota2-Gameplay#9373]
### Ability name

 Juxtapose + Aghanim

### Description

the problem the effect of radiance is still on the side, and it doesn't disappear, and i just tried it on Demo and it works
please fix this 
also i makae video on youtube for the detail
https://youtu.be/6I7BTZfs4xc

### Example Match ID (and possibly Timestamp)

7166931563 - Late game before lose

**Comment by Avarise831** [comment]
#8660

**Comment by Dota-Exp** [comment]
Issue will be fixed in upcoming update. Thank you
