### ISSUE TITLE
Sniper mana instant refilling without mango after shrapnel

### ISSUE THREAD

**Issue by Wulfdragon** [ValveSoftware/Dota2-Gameplay#9374]
Match ID:  7166899329

in-game time bug is observed:  2:41  &  3:00
hero:  Sniper

Issue:  at the times specified, just after Sniper casts his Shrapnel, his mana refills as if he ate a mango, but he has no mango in inventory or other method of refilling mana instantly.  His opponent Outworld Destroyer had been using Astral Imprisonment on him.  The Astral Imprisonment does not fall off during these times and it is my understanding that even when maximum mana is restored via the debuff from Astral Imprisonment expiring, the target's current mana is unaffected.

Screenshots:

![20230523010158_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/134362231/a75b88a4-b46d-4230-9c83-193312b4bd3f)
![20230523010201_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/134362231/d0659b30-d770-4f26-b0fc-44645b5498f2)
![20230523010202_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/134362231/bdc008b3-bfed-4e00-8585-285654e63fa6)
![20230523010209_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/134362231/2b217c78-b89e-48a9-b907-b50d256c3602)
![20230523010210_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/134362231/b57046c7-ba96-48c7-a17b-0493f04d07f7)
![20230523010213_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/134362231/ecb5df6e-de0d-4f18-87c8-8f20eb1088bd)

Same screenshots on steam cloud:

https://steamcommunity.com/sharedfiles/filedetails/?id=2979539416
https://steamcommunity.com/sharedfiles/filedetails/?id=2979539436
https://steamcommunity.com/sharedfiles/filedetails/?id=2979539446
https://steamcommunity.com/sharedfiles/filedetails/?id=2979539463
https://steamcommunity.com/sharedfiles/filedetails/?id=2979539474
https://steamcommunity.com/sharedfiles/filedetails/?id=2979539489

**Comment by TheUnholyWrath** [comment]
#1113

**Comment by Nathanael-Valve** [comment]
Fixed in next update.
