### ISSUE TITLE
Zeus aghanim shard not working properly with Witchblade

### ISSUE THREAD

**Issue by trunghdang** [ValveSoftware/Dota2-Gameplay#9376]
### Ability name

Lightning hands

### Description

Lightning hands (Zeus shard) not working properly after equipping Witch Blade. Illusions (from Manta and rune) still works.

### Example Match ID (and possibly Timestamp)

7167211014

**Comment by TheUnholyWrath** [comment]
Turning off the auto cast on Lightning Hands disables the ability. If you think that this is working incorrectly you should make a new issue regarding its functionality or remake this one. Otherwise, you should close this issue.

**Comment by Dota-Exp** [comment]
Can not reproduce. Autocast does toggle Lightning hands active/non active. - Closing issue.
