### ISSUE TITLE
Earth Spirit - Crash Server ⚡⚡⚡

### ISSUE THREAD

**Issue by flynesss** [ValveSoftware/Dota2-Gameplay#9377]
### Description

Earth Spirit buy the Refresher -> Put all stones with Refresher -> Use ulti near enemy (creep/hero) -> When ulti ends, all stones destroyed = crash server. Random video from youtube for example https://www.youtube.com/watch?v=Fy_hG4Pc2Y8. All matches with this crash do not count

**Comment by Avarise831** [comment]
#9086

**Comment by Dota-Exp** [comment]
Will be fixed in upcoming update. Thank you.

**Comment by Aluerie** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/9485

Looks like linked there match happened just 3 hours ago...

So not fixed ?

**Comment by Aluerie** [comment]
another match id 7180139236 from https://github.com/ValveSoftware/Dota2-Gameplay/issues/9086#issuecomment-1570736047
