### ISSUE TITLE
Aether Remnant canceling movement ability while having bkb on

### ISSUE THREAD

**Issue by Dafrily** [ValveSoftware/Dota2-Gameplay#9385]
### Ability name

Aether Remnant, Rolling Boulder, Swashbuckle, Blast Off etc

### Description

I don't know if this is an issue or as intended by the Dev but Aether Remnant canceling move with moving component even though the user is using BKB. For example blast off, rolling boulder, swashbuckle etc. This Debuff Imunity is still confusing so can you clarify is this a bug or it is just how it was intended. Thanks beforehand  

### Example Match ID (and possibly Timestamp)

716808150 - 65:42

**Comment by Dota-Exp** [comment]
Will be fixed in an upcoming update, thank you
