### ISSUE TITLE
Cheese ignores Heal Amplification entirely (positive & negative alike)

### ISSUE THREAD

**Issue by TheZett** [ValveSoftware/Dota2-Gameplay#9402]
### Item name

Cheese

### Description

Cheese currently ignores all forms of Heal Reduction and Heal Amplification effects, except for False Promise.

This means its 2500 health restore is not increased by Holy Locket, Paladin Sword or Rain of Destiny (Oracle Aghs).

Also its 2500 health restore is not decreased by Eye of Skadi, Drow Aghs or Spirit Vessel.

It used to be affected by these kind of things, but it currently always heals for a static 2500 health.

**Heal Reduction effects:** https://youtu.be/lO7GR9PicHY

**Heal Amplification effects:** https://youtu.be/rl7TtbJvfQI

### Example Match ID and Timestamp

two videos are provided above

**Comment by Dota-Exp** [comment]
Currently working as intended
