### ISSUE TITLE
Rubick Cosmetic bugged

### ISSUE THREAD

**Issue by Skateboardlegend** [ValveSoftware/Dota2-Gameplay#9405]
### Cosmetic Item Name

Cape of the Itinerant Scholar

### Description

the item streches infinetly when equipped 

### Example Match ID

7140346178

### Screenshots

https://steamcommunity.com/sharedfiles/filedetails/?id=2980197627

**Comment by Aluerie** [comment]
dup #8980

pls close your duplicate issue, upvote the original with 👍 and comment extra details if any.
