### ISSUE TITLE
Echo Slam only creates 1 echo per hero instead of 2

### ISSUE THREAD

**Issue by aquasarus** [ValveSoftware/Dota2-Gameplay#9406]
### Ability name

Echo Slam

### Description

Earth Shaker's echo slam is supposed to send 2 echos per hero/strong illusion, and 1 echo per creep/weak illusion to all other targets. In testing, I only ever see 1 echo coming out. This happens in both demo mode and a full All Pick lobby.

I've included video demonstrations in my Reddit post: https://www.reddit.com/r/DotA2/comments/13qux1j/echo_slam_only_sends_1_echo_per_hero_instead_of_2/

### Example Match ID (and possibly Timestamp)

N/A

**Comment by TheUnholyWrath** [comment]
Your videos on reddit aren't loading for me, can you check and see that this isn't #2036 causing this? Trying to replicate this the combat log is showing me 1 damage instance but the heroes are taking both.

**Comment by aquasarus** [comment]
> Your videos on reddit aren't loading for me, can you check and see that this isn't #2036 causing this? Trying to replicate this the combat log is showing me 1 damage instance but the heroes are taking both.

Just checked. It is indeed the same issue! Thanks for looking into this.
