### ISSUE TITLE
Cannot level stats at level 17 and are forced to select an ability instead.

### ISSUE THREAD

**Issue by Unranked44** [ValveSoftware/Dota2-Gameplay#9407]
### Description

You cannot select +2 stats as an option at level 17 and must instead select an ability. I have also sometimes had this occur at level 9, although not in the example provided. You are not given the option, you have no other choice but to scale an ability instead.

### Example Match ID (and possibly Timestamp)

7163848471 - 27:16

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/134562253/d1294dd2-6e17-486d-9a3c-c9881b019a72)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/134562253/ef933e5b-9c24-4fa4-92e0-62f45372098d)

**Comment by Aluerie** [comment]
This is most likely intended (not a bug)

Stats levels have same mechanic hero level requirements as QWER spells (like you need to be a hero level 1/3/5/7 to skill them 1/2/3/4 times) 

But for attributes since 7.33 it's 

6/8/10/12/14/16/18 for levels 1/2/3/4/5/6/7

So yeah you can't do that at level 17 because it requires level 18.

**Comment by Unranked44** [comment]
> This is most likely intended (not a bug)
> 
> Stats levels have same mechanic hero level requirements as QWER spells (like you need to be a hero level 1/3/5/7 to skill them 1/2/3/4 times)
> 
> But for attributes since 7.33 it's
> 
> 6/8/10/12/14/16/18 for levels 1/2/3/4/5/6/7
> 
> So yeah you can't do that at level 17 because it requires level 18.

I wasn't aware they had a level requirement, The only thing that they stated in their patch notes was that you couldn't level them up prior to level 6. Was this in the fine print somewhere else that I failed to read? Prior to this patch you could level them up non-stop every level. My favorite way to build wyvern was to max arctic burn by 7, 1 level in ulti, 1 level in heal, and the rest into +2 stats until level 21.

**Comment by Unranked44** [comment]
> The requirement was always there (even in Dota 1 days). It was 1/3/5/7/9/11/13 so your build fit nicely with it.
> 
> The patch notes thing is exactly why I say "most likely". Idk, the mechanic was always there.

Ah I see that makes sense why I never noticed, your explanation seems very plausible now that I understand that mechanic a little better. Thanks for the insight.
