### ISSUE TITLE
Phylactery sometimes prevents single target spells from working

### ISSUE THREAD

**Issue by Luminance69** [ValveSoftware/Dota2-Gameplay#9426]
### Ability name

Mystic Snake

### Description

It seems like when I bought phylactery in this game my mystic snake started randomly not bouncing.

### Example Match ID (and possibly Timestamp)

7171354662 - 12:08 (plus many more times during the game)

**Comment by Luminance69** [comment]
Video for lazy people https://youtu.be/BqMLSTI7bG8

**Comment by ejlocop** [comment]
seems like it's similar to this issue.
https://www.reddit.com/r/DotA2/comments/13s74bx/bug_tinkers_laser_splash_damage_doesnt_work_with/

**Comment by Luminance69** [comment]
just had the same thing happen with disruptor Q: 7173422447 36:30ish

**Comment by Luminance69** [comment]
seems like it happens when the target dies to the phylactery damage

**Comment by Aluerie** [comment]
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/33165440/68b9fa5f-dc0a-4b2e-8b93-ac783a79e97c)

**Comment by Luminance69** [comment]
pog
