### ISSUE TITLE
Techies innate ability uses wrong form of "its" in tooltip

### ISSUE THREAD

**Issue by BenLubar** [ValveSoftware/Dota2-Gameplay#9438]
### Hero and spell

Techies - Minefield Sign

### Description

Current caption reads:

> Plant a warning sign, causing mines in **it is** radius to be invulnerable.

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/4257305/494c3c31-f92c-42dd-b4de-cfafcbba4257)

**Comment by Nathanael-Valve** [comment]
Fixed in next release.
