### ISSUE TITLE
All pick

### ISSUE THREAD

**Issue by benimaru1235** [ValveSoftware/Dota2-Gameplay#9442]

**Comment by BenLubar** [comment]
Is there a reason you cropped out the match ID?

**Comment by benimaru1235** [comment]
No, I can show all match indicators. No problem

**Comment by benimaru1235** [comment]
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/134759781/9fdafb1d-f0ea-4819-986c-a67da3fff726)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/134759781/44e1cb74-1ca0-4fe0-9c6d-e665341fbd58)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/134759781/9cf228a5-0992-45e6-810a-f840407402c8)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/134759781/7f08e766-30ba-4756-bb7a-920a1519450d)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/134759781/ff864731-9044-41d3-ae90-4fe4d36772c2)
