### ISSUE TITLE
Please fix pangoier for dota 2 workshop, it is not possible to publish work for hero

### ISSUE THREAD

**Issue by Y9Jjj** [ValveSoftware/Dota2-Gameplay#9454]
### Item name

Pangolier Dota 2 Workshop tools

### Description

Please fix pangoier for dota 2 workshop, it is not possible to publish work for hero, gives an error loading models and compiling textures,

### Example Match ID and Timestamp

Dota workshop

**Comment by TheUnholyWrath** [comment]
#9444

**Comment by Nathanael-Valve** [comment]
Should be fixed now.
