### ISSUE TITLE
Hoodwink's Acorn Shot doesn't bounce if a unit killed by Phylactery damage first.

### ISSUE THREAD

**Issue by deanrih** [ValveSoftware/Dota2-Gameplay#9456]
### Ability name

Acorn Shot

### Description

If you damage a unit enough so the proc damage of Phylactery kills the unit and then unit-targeting it with an Acorn Shot, the Acorn Shot won't bounce off to another unit.

And I think this is specific interaction with the Phylactery since if you try to cast Acorn Shot onto the unit and kill the unit first by any means, e.g. using Dagon, the Acorn Shot will still bounce off to another unit.

Also, Witch Doctor's Paralyzing Cask doesn't have this bug (still bounces off even if the primary target is killed by Phylactery damage first)

Step I took to test it:
## Test Acorn Shot + Phylactery

0. (Optional) Open combat log to see what happened
1. Stack a jungle camp with as many stacks as you like
2. Damage one unit to very low health that Phylactery proc damage will kill it (150 magical damage) or just use the mean of damage amplification
3. Target the said unit with Acorn Shot
4. Notice that the unit has been killed but the Acorn Shot ability stops or not even bouncing in the first place
5. (Optional) Open the combat log so that you can see the unit being killed first by the Phylactery damage and doesn't even try to damage or apply any Acorn Shot effect to the target unit

## Test Acorn Shot + Dagon

0. (Optional) Open combat log to see what happened
1. Prepare or cheat yourself items like Dagon 1 (it instantly kills any non-ancient creep, so it's fine), Aether Lens, Seer Stone and an Observer Ward to make sure you have the vision of the camp
2. Put the observer ward that is not blocking the camp but also gives 100% vision into the camp
3. Stack a jungle camp with as many stacks as you like
4. Move as far away as possible so that you can reach your Acorn Shot and Dagon
5. Target the said unit with Acorn Shot
6. Quickly target the same unit with Dagon
7. Notice that the unit has been killed but the Acorn Shot ability still bounces off to other unit
9. (Optional) Open the combat log so that you can see the unit being killed first by the Dagon damage but still try to damage or apply any Acorn Shot effect to the target unit

### Example Match ID (and possibly Timestamp)

7172918049 (Practice private lobby that I discovered the interaction, but not the testing session)

### Update

As you might already know it also doesn't work with Zeus's Arc Lightning and Medusa's Mystic Snake as mentioned in #9448, but it also doesn't work on Bounty Hunter's Shuriken Toss, Clinkz's Tar Bomb (No AOE Effect), Phantom Lancer's Spirit Lance's Aghanim's Scepter upgrade, Leshrac's Lightning Storm, Muerta's Dead Shot, Nature's Prophet Sprout (No trees), Rubick's Fade Bolt, Warlock's Fatal Bonds, Dazzle's Poison Touch, Vengeful Spirit's Magic Missile's Aghanim's Shard upgrade, Windranger's Shackle Shot and Winter Wyvern's Splinter Blast

Since the previous issue already exists or at least similar, I'll reference it here, like @Aluerie have mentioned

#9448 and #9426

**Comment by Aluerie** [comment]
#9448 https://github.com/ValveSoftware/Dota2-Gameplay/issues/9426

**Comment by ShizoidMan** [comment]
Same thing with Rubick's fade bolt I think,if the phylactery kills the unit upon cast of fade bolt,it doesn't bounce between minions when they are close to each other

**Comment by deanrih** [comment]
> Same thing with Rubick's fade bolt I think,if the phylactery kills the unit upon cast of fade bolt,it doesn't bounce between minions when they are close to each other

Yes, and I already listed it in the detail above, also referencing the older issue that similar to this.

**Comment by Aluerie** [comment]
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/33165440/1d4fd1a6-5cc7-4d43-ad33-ceda7592997d)

**Comment by deanrih** [comment]
> 

Haven't checked the latest patch yet, I'll try it after work and I'll close this issue after that, thank you for notifying me.

**Comment by deanrih** [comment]
> ![image](https://user-images.githubusercontent.com/33165440/242126408-1d4fd1a6-5cc7-4d43-ad33-ceda7592997d.png)

Although curiously they don't mention the other bugged interaction I've mentioned above, hopefully going to be fixed on another patch

**Comment by deanrih** [comment]
Closing this issue since it's already been fixed.
