### ISSUE TITLE
（BUG）美杜莎BUG

### ISSUE THREAD

**Issue by WatchRats** [ValveSoftware/Dota2-Gameplay#9462]
### Description

秘术异蛇偶尔只命中一个单位，装备了灵匣
Mysterious Snake occasionally hits only one unit，Equipped with a phylactery

### Example Match ID (and possibly Timestamp)

7174629944 - 12：05

**Comment by Aluerie** [comment]
#9426

**Comment by Aluerie** [comment]
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/33165440/9dba2a2e-1b5a-4889-8f69-d2c5568a11f4)
