### ISSUE TITLE
Specter shard on activation return less damage.

### ISSUE THREAD

**Issue by Pankul94** [ValveSoftware/Dota2-Gameplay#9465]
### Ability name

Dispersion

### Description

Specter's reflected damage on activating dispersion(shard ability) is lesser than without her shard. I have attached a screenshot of the combat log in demo mode. 

Can you please help us identify if this is a bug or if is this an expected behavior?

Looking at the tooltip, 
> Adds an active component to Dispersion that increases damage reflected to 16%/24%/32%/40% (Talent 26%/34%/42%/50%) while active, with the passive effects still present.

According to this, the reflected damage should be 2X but that is not what we see in the combat log.

![WhatsApp Image 2023-05-28 at 00 28 20](https://github.com/ValveSoftware/Dota2-Gameplay/assets/33594135/c57f1e8b-2f6a-49ed-88a1-2d97dda255ea)
 
Thanks

### Example Match ID (and possibly Timestamp)

7174756925 - 20:56

**Comment by Anutyagi007** [comment]
Faced the same issue please have a look on it ASAP its ruining the gaming experience of Boosters playing spectre in ranked game.

**Comment by harshkul93** [comment]
I am also facing the same issue from a long time and this has ruined my life. Please fix this asap.

**Comment by A5HW1NR** [comment]
Unintentionally nerfed ???!

**Comment by TheUnholyWrath** [comment]
Melee heroes have a 50% chance of blocking 16 damage. Try attacking Spectre with a few Rapiers. The shard should be working correctly.

**Comment by Pankul94** [comment]
Thanks for that explanation. I tested it out and it works fine. I will close this one

**Comment by A5HW1NR** [comment]
Plus one community !

**Comment by tvdisplayman** [comment]
Just done some testing and it seems that spectres shard only doubles the damage output of dispersion and does not make spectre tankier.

I dont think this is Intentional but if it is, the ability should read increases dispersion damage by 100%.

saying it increases her dispersion relection damage implies it makes her tankier.
