### ISSUE TITLE
Necromastery's description is incorrect

### ISSUE THREAD

**Issue by Draze22** [ValveSoftware/Dota2-Gameplay#9479]
### Hero and spell

Shadow Fiend - Necromastery

### Description

Necromastery's description says "On death, he releases 40% of the from bondage." when he actually loses 30% of his Necromastery stacks on death.

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/63279022/3f1b601b-7cd7-44ee-a6d1-afb725676edb)

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/63279022/a03dc5d4-0090-4677-b152-e1ee6a7b307f)

**Comment by Aluerie** [comment]
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/33165440/d3913353-da9b-4d41-a947-0ccc3def5009)

**Comment by Aluerie** [comment]
> can teach me how to check the values? which file is it

* `steamapps\common\dota 2 beta\game\dotapak01_dir.vpk`
* open it with tool like GCFScape
* navigate to `scripts\npc\npc_abilities.txt`
* Explore the file

**Comment by sommerVA** [comment]
Russian localization Necromastery tooltip still 40%
