### ISSUE TITLE
TP scrolls keep getting bought on deaths

### ISSUE THREAD

**Issue by igorpakushin** [ValveSoftware/Dota2-Gameplay#9484]
### Item name

TP Scroll

### Description

Tp scrolls automatically bought for me when I die, keeping getting things worse!
Super annoying!

You can check my tp scrolls. I am not alone I am CM, but Venge has these issues too! And every other team member has around 5 tp scrolls at mark 50:00 while we are defending heavily. They couldn't have bought them on purpose!

I thought I was buying them myself but then I removed quick buy hotkey, but the issue kept happening.

I had 17 tp scrolls at the end of the game!

### Example Match ID and Timestamp

7176685580 - 14:32

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/2378704/a19327de-f12f-43d2-86aa-456dffcbab4a)

**Comment by Aluerie** [comment]
Read patch 7.29

**Comment by igorpakushin** [comment]
@Aluerie thanks, looks like a bug from players perspective tho
