### ISSUE TITLE
[Techies] Munitions of the Powderkeg Patrol.Stretch textures.

### ISSUE THREAD

**Issue by Astiberon** [ValveSoftware/Dota2-Gameplay#9495]
### Cosmetic Item Name

Munitions of the Powderkeg Patrol

### Description

The textures of the gun are stretched during the movement of the hero.
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/107125193/9df4e463-01a2-4ff3-b4bb-a0ea7d07ba88)

### Example Match ID

-

**Comment by tvidotto** [comment]
fixed on the next update

**Comment by Astiberon** [comment]
> fixed on the next update

Please pay attention to a few more similar bugs.
#7216
#7672
#7333
#1244
#7948
#8993
#7760
