### ISSUE TITLE
Pugna/Lion Channeling Spells

### ISSUE THREAD

**Issue by BPCx** [ValveSoftware/Dota2-Gameplay#9508]
### Ability name

Life Drain, Mana Drain

### Description

Can't target invisible heroes under sentry effect with either one of these spells. Only after using dust they've become targetable. Decrepify works with just the sentry.

### Example Match ID (and possibly Timestamp)

7180295677 - 29:55

**Comment by u2knwy** [comment]
pls fix

**Comment by chrisf-valve** [comment]
This should be fixed in today's update.
