### ISSUE TITLE
Casting Ion Shell on Spirit Breaker cancels Charge of Darkness

### ISSUE THREAD

**Issue by aenapoeka** [ValveSoftware/Dota2-Gameplay#9510]
### Ability name

Charge of Darkness

### Description

Found a bug on an ongoing match, 
Spirit Breaker was charging Techies from base, when he was in range of his ally Dark Seer, DS used Ion Shell on SB. 
This pulled Bara towards DS, canceling the charge? Is this intentional?

Here is a video of it:

https://github.com/ValveSoftware/Dota2-Gameplay/assets/46532072/7ad68423-d3b4-4569-8dc0-a47c7bf0e7da

### Example Match ID (and possibly Timestamp)

7180399249 (05:47)

**Comment by aenapoeka** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/assets/46532072/2bf06946-4d1f-4c7c-ba50-bf31436cbf48

**Comment by LokeLok** [comment]
Not a bug. Spirit Breaker stopped the Charge on his own, Dark Seer Ion himself and not Spirit Breaker.

**Comment by aenapoeka** [comment]
There is something very strange happening here, Spirit Breaker issues a weird move command to his left, but moves to his right and cancels the charge. This occurs at the same time as DS casts the Shell.

https://github.com/ValveSoftware/Dota2-Gameplay/assets/46532072/70181cee-85f1-484a-8285-5e4752cd70e7

**Comment by aenapoeka** [comment]
DS perspective:
https://github.com/ValveSoftware/Dota2-Gameplay/assets/46532072/52fdeab6-c2ab-4fc7-94a1-cdd5d15c0de5

**Comment by LokeLok** [comment]
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/106764092/f4113c47-0502-4ed2-b8eb-18740f8b5343)

Charges stops before Dark Seer cast Ion Shell. I don't see how Ion Shell has anything to do with Charge getting canceled. Spirit Breaker's movement might look a bit funky when the Charge stops, since it's inside trees.
