### ISSUE TITLE
Rubick [Fade Bolt] is not bouncing on multiple visible targets

### ISSUE THREAD

**Issue by Unranked44** [ValveSoftware/Dota2-Gameplay#9530]
### Ability name

Fade Bolt

### Description

Using fade bolt with a phylactery in your inventory in the split second after using a stolen earthshaker fissure results in fade bolt not bouncing to nearby targets and only strikes one time. Inconsistent but repeatable bug, in that it happened at least 2 times during my match.

Example 1:
https://github.com/ValveSoftware/Dota2-Gameplay/assets/134562253/9ed5f3f5-39de-4bb1-b9bf-a48e4f501294

Example 2:
https://github.com/ValveSoftware/Dota2-Gameplay/assets/134562253/8cfc528e-94be-4f93-a436-42427a555d2a

I'm quite stumped as to why this issue is happening.

### Example Match ID (and possibly Timestamp)

718984058 - 32:24, 33:55

**Comment by TheUnholyWrath** [comment]
The fade bolt interaction is in #9499, you can close this issue. This happens when you cast on a unit with ~100 or less HP, the Phylactery damage kills the unit and spell doesn't apply properly.
