### ISSUE TITLE
Dota 2 pinned items missing

### ISSUE THREAD

**Issue by Bliddddddd3** [ValveSoftware/Dota2-Gameplay#9557]

**Comment by Bliddddddd3** [comment]
The problem occurs when I want to add specifically an additional seventh slot. 
The item will disappear

**Comment by Avarise831** [comment]
#1286 #3225

**Comment by Bliddddddd3** [comment]
Bug with the disappearance of a pinned item (slot 7)

Screenshots and video

Screenshot1 
Open shop, pinned items 6
1)flask 2)mango 3)tango 4)clarity 5)stick and 6)boots

Screenshot2 
I click on the pencil (unlock the menu to add 1 more item)

Screenshot3 
Added a bracer (slot 7)

Screenshot4 
clicked the pencil again (lock the menu)

Screenshot5 
I press the exit button to start a new session
(this example shows a hero tryout, but in a normal game/lobby the problem persists as well)

Screenshot6 
I press try the hero (to go in again)

Screenshot7 
And we see that the seventh item (bracer) is not saved and so we have to do it again
Moreover, many have a problem that the number of fixed slots decreases and let's say they can not add more than three items

Screenshot8 
Here I am trying to add the seventh slot (bracer) through the config files of the game (2 files in the folder dota/cfg and 1 file in the folder 570/remote)


Screenshot9
But even so nothing has changed, the problem is not solved, please fix it

![1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/135523246/92ad1d66-804a-4269-965d-aefa4159afb9)
![2](https://github.com/ValveSoftware/Dota2-Gameplay/assets/135523246/d940e26a-17ef-4e1d-9831-29252e6e28b6)
![3](https://github.com/ValveSoftware/Dota2-Gameplay/assets/135523246/ffc88c4a-53da-49ba-be87-a8026444525f)
![4](https://github.com/ValveSoftware/Dota2-Gameplay/assets/135523246/70051e74-0fc9-495d-8cf0-305b7b66f889)
![5](https://github.com/ValveSoftware/Dota2-Gameplay/assets/135523246/30498093-8eaa-4ea6-b601-1c398933dd07)
![6](https://github.com/ValveSoftware/Dota2-Gameplay/assets/135523246/bb957fcc-b16e-43c6-8afb-27d96470dc02)
![7](https://github.com/ValveSoftware/Dota2-Gameplay/assets/135523246/3afbd18f-dcc9-4912-8274-496421a346be)
![8](https://github.com/ValveSoftware/Dota2-Gameplay/assets/135523246/aae1a298-ad41-4345-8b05-ede75bb1c9d2)
![9](https://github.com/ValveSoftware/Dota2-Gameplay/assets/135523246/5b150ed8-a4a3-4738-aa8c-4a1ad32c64a8)
