### ISSUE TITLE
Bounty Hunter — Shadow Walk doesn't active with Double Tap of Key Press after receiving Aghanim Shard

### ISSUE THREAD

**Issue by emikoyamasaki** [ValveSoftware/Dota2-Gameplay#9558]
**Bounty Hunter** 

- Spell: Shadow Walk 
- [ ] Problem: Doesn't active with Double Tap of Key Press after receiving Aghanim Shard.

**Comment by Aluerie** [comment]
Couldnt't reproduce. 🤔 works fine on my machine. 

Can you check/show your settings and etc.

**Comment by emikoyamasaki** [comment]
Please find attached screenshots of settings and in-game screenshot of the error that pops up when I try to cast "Shadow Walk" after having received an Aghanim Shard. 

**Problem:** Self-Casting is not working. 
![2023-06-04_180346](https://github.com/ValveSoftware/Dota2-Gameplay/assets/64431363/d6679cd8-14c0-4cee-81aa-bad82afd9033)

![2023-06-04_180358](https://github.com/ValveSoftware/Dota2-Gameplay/assets/64431363/0934c54d-bfc7-4125-8ef9-215d98a08767)

![2023-06-04_180506](https://github.com/ValveSoftware/Dota2-Gameplay/assets/64431363/0a11f92e-0e8a-4840-a3c1-516b0c2643fc)

**Comment by Aluerie** [comment]
Is your E quickcast or normal cast key ?

**Comment by emikoyamasaki** [comment]
Hmm. It is quickcast.

**Comment by Aluerie** [comment]
then ofc double tapping won't work. Try Alt E.

**Comment by emikoyamasaki** [comment]
Yes, Alt + E works. But it is too difficult. 

I did what you suggested and disabled quickcast on the "E" keybind, and now it works perfectly!

Thanks for helping me figure this out.

**Comment by Aluerie** [comment]
well, you can close the issue then if all is good.
