### ISSUE TITLE
morphling infinite hp

### ISSUE THREAD

**Issue by Khashayar-almasi** [ValveSoftware/Dota2-Gameplay#9571]
### Ability name

attribute shift

### Description

morphling gained more tahn 12k hp at end of the game, what did cause the bug i dont know here is the match 
at the end u can see he has 300damage and 12k hp 

### Example Match ID (and possibly Timestamp)

7187059059 mid to end game(end game most obvious)

**Comment by commentator24** [comment]
its chen's granite aura +17% max hp and his aghs stealing 55 str
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109324155/b934a012-d0e1-4b6a-b82c-db3decf12212)
a level 30 morph can have up to 8.6k with that items. i forgot to add neut / hex and not sure how to level up creep abilities so maybe 10k*1.17
u can close this issue.
