### ISSUE TITLE
Dire right extension buff seems to miss the localization for the +5 damage buff.

### ISSUE THREAD

**Issue by DortyTheGreat** [ValveSoftware/Dota2-Gameplay#9579]
### Hero and spell

DOTA_tooltip_modifier_bonus_d...

### Description

With the 7.33 we have received 4 "map extensions". Close to some structure you can receive a special buff, 3 of them have the right localization, while the right one seems to have the wrong one(at least something breaks with russian localization)

### Screenshots

![Dorty — копия (2)](https://github.com/ValveSoftware/Dota2-Gameplay/assets/72660192/e2de0aa4-0b2e-44b0-9aef-524748e57214)
![Dorty — копия](https://github.com/ValveSoftware/Dota2-Gameplay/assets/72660192/8c0bb239-4b47-44a7-b7c9-6badaf356dd7)
![Dorty](https://github.com/ValveSoftware/Dota2-Gameplay/assets/72660192/45718c39-6297-42eb-a06b-d525a704014f)
![Dorty — копия — копия](https://github.com/ValveSoftware/Dota2-Gameplay/assets/72660192/dbed87b3-bf7d-4f4b-8d48-8234b1a1a3b8)

**Comment by Aluerie** [comment]
duplicate #8060

> (at least something breaks with russian localization)

it's a problem with all languages.
