### ISSUE TITLE
skywrath talent arcane bolt pierce bkb ignore 50% magic resist

### ISSUE THREAD

**Issue by commentator24** [ValveSoftware/Dota2-Gameplay#9586]
bkb supposedly grant 50% magic resist. but sky bolt dmg is not halved when bkb active.

**Comment by Aluerie** [comment]
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/33165440/9af7565a-7dde-4c10-bb34-330c98f9e8a9)

**Comment by commentator24** [comment]
oh oops guess i misunderstood it, was reading from the wiki
