### ISSUE TITLE
7.33c - Universal heroes have incorrect attack damage display during picking phase

### ISSUE THREAD

**Issue by Magic-wei** [ValveSoftware/Dota2-Gameplay#9587]
### Hero and spell

All universal heroes

### Description

Patch: 7.33c

During hero picking phase, all universal heroes have incorrect attack damage display.

### Screenshots

![universal_heroes_incorrect_damage_display](https://github.com/ValveSoftware/Dota2-Gameplay/assets/29951097/b7b36fe2-2866-497a-a2c7-58414972d8b5)
![universal_heroes_incorrect_damage_display-2](https://github.com/ValveSoftware/Dota2-Gameplay/assets/29951097/59bc9439-fbf5-4604-ad26-8b12ab2e472d)

**Comment by Woodsoniop** [comment]
This article is really amazing. Thanks for the sharing.

**Comment by Aluerie** [comment]
https://steamcommunity.com/games/dota2/announcements/detail/3692434931953973991
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/33165440/d71f6691-6038-4d76-b8f0-9cbdd2208fbf)
fixed

**Comment by Magic-wei** [comment]
@Aluerie Confirmed, thank you for fixing it! This issue will be closed.

**Comment by Magic-wei** [comment]
@Aluerie Confirmed, thank you for fixing it! This issue will be closed.
