### ISSUE TITLE
Dota doesn't open on Mac after latest update to sonoma

### ISSUE THREAD

**Issue by AyushyaChitransh** [ValveSoftware/Dota2-Gameplay#9591]
### Description

Description
I updated mac to sonoma which brings in game mode.The game won't open anymore. It freezes in black screen. When application is viewed in dock, it displays as "Application not responding"

I've tried restarting steam, the computer and reinstalling dota, but the problem still stands, the game won't open.

Im playing on a Mac pro with Sonoma as the OS.

### Screenshots

<img width="392" alt="About this Mac" src="https://github.com/ValveSoftware/Dota2-Gameplay/assets/13914634/4e1b01e4-2992-442b-9c94-65ffa3ff9066">

**Comment by LokeLok** [comment]
You should close this issue and open a new one over at: https://github.com/ValveSoftware/Dota-2/issues where they help with mac issues.

**Comment by Aluerie** [comment]
Duplicate https://github.com/ValveSoftware/Dota-2/issues/2357

**Comment by krikaoli** [comment]
Same problem!

**Comment by AyushyaChitransh** [comment]
Closing this issue as this is a duplicate of https://github.com/ValveSoftware/Dota-2/issues/2357
