### ISSUE TITLE
Dawnbreaker Starbreaker ability makes her immune to Pure damage

### ISSUE THREAD

**Issue by samhsar** [ValveSoftware/Dota2-Gameplay#9594]
### Ability name

Starbreaker

### Description

While performing the Starbreaker animation, Dawnbreaker becomes immune to all forms of Pure damage (QOP ult, Omniknight, etc.). She is not immune to magic or physical.

### Example Match ID (and possibly Timestamp)

7189288145 - 4:20

**Comment by Aluerie** [comment]
Duplicate  #8981

---
Please, close your duplicate issue and instead upvote the original one with "👍" reaction. Comment extra details if any.

And in future, first, use search to find out if the bug you want to report was already submitted by somebody else so you can upvote it and not clutter the repository with duplicates.
