### ISSUE TITLE
Disruptor Phylactery using Thunder Strike on Low Health Creep Causes Thunder Strike to disappear

### ISSUE THREAD

**Issue by SebastianBury** [ValveSoftware/Dota2-Gameplay#9600]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
* Have you checked for system updates?: [Yes/No]
* Are you using the latest stable video driver available for your system? [Yes/No]
* Have you verified the game files?: [Yes/No]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

#### Steps for reproducing this issue:

1. Pick Disruptor
2. Buy Phylactery
3. Cast Thunder Strike on low health creep (less than damage from Phylactery
4. Creep Dies, Thunder Strike goes on Cooldown, Thunder Strike orb never exists and is not there

**Comment by TheUnholyWrath** [comment]
#9499

**Comment by TheUnholyWrath** [comment]
This has been fixed. Please close this issue.
