### ISSUE TITLE
Courier not delivering items.

### ISSUE THREAD

**Issue by dunce345** [ValveSoftware/Dota2-Gameplay#9601]
### Description

Recently played a match where the courier wouldn't deliver items to me, it wasn't the keyboard because I was able to select the courier itself with the keyboard (I use '2' to deliver items and 'Alt+2' to select the courier.)
Was unable to manually grab items by the grab items button as well.

Made the game extremely rough because I had to TP all the way back to base and get my items.

First noticed it at around 11:00 in the match and happened multiple times throughout.

Match ID: 7189883874
Hero: Magnus
Region: SEA

### Example Match ID (and possibly Timestamp)

7189883874; TIMESTAMP - First noticed it at 11:00 and happened other times afterward.

### Screenshots

Attached clip below.

https://github.com/ValveSoftware/Dota2-Gameplay/assets/17759116/5e6d73c0-20a1-48b9-bfef-ad17ab08183a

**Comment by Aluerie** [comment]
#8449

**Comment by dunce345** [comment]
Closed.
