### ISSUE TITLE
Ogre Magi's Fire Shield can't be set on autocast

### ISSUE THREAD

**Issue by jlkj11** [ValveSoftware/Dota2-Gameplay#9604]
### Ability name

Fire Shield

### Description

Fire Shield can't be set to autocast even though it has the functionality according to the alt-tooltip. 

### Example Match ID (and possibly Timestamp)

any

**Comment by commentator24** [comment]
i think alt tooltip says multicast, not autocast.
if you check bloodlust it will say ability: autocast 
while fire shield is ability: unit target
you can close this issue
