### ISSUE TITLE
Tiny can infinite tree toss while under the effect of Muerta agh

### ISSUE THREAD

**Issue by nghialun1234** [ValveSoftware/Dota2-Gameplay#9608]
### Ability name

Tree throw + Parting shot

### Description

Tiny can tree throw infinite time when under the effect of Muerta parting shot

### Example Match ID (and possibly Timestamp)

7189957917

**Comment by Aluerie** [comment]
Same for Alchemist W - you can infinitely throw it while "dead".

**Comment by Aluerie** [comment]
https://steamcommunity.com/games/dota2/announcements/detail/6252732681178927719

> Fix Tiny having infinite Tree Tosses when affected by Muerta's Parting Shot

Tiny + Muerta is fixed thus this issue is closeable. 

---

Alchemist + Muerta untoched tho #9737

**Comment by Aluerie** [comment]
you can close the issue
