### ISSUE TITLE
South East Asia PING much higher than usual for the past 20 days.

### ISSUE THREAD

**Issue by JosephKhalil2209** [ValveSoftware/Dota2-Gameplay#9611]
I am from Australia, and am an immortal ranked player, I cannot find any games without waiting 20+ minutes on an Aus server.

So for the past year I have been playing in the SEA server which has been fine. I used to get ping of around 120ms (minimum) and during the game it may go as high as 300ms for a few minutes before decreasing.

Recently when running the tests, this is for the past 20 days, in all hours of the day the minimum is now 300ms for me that even US west and Japan have a lower latency.

Is there an issue with the server?

**Comment by Gunnarmag** [comment]
Hi Joseph,

Which are ISP are you using? I am using iinet and I believed there are some issues with TPG as they said "Due to a third party planned activity some customers in nationwide might experience latency towards Asian Destinations."

**Comment by jennikim266** [comment]
Thank you for sharing this data. [ara ara meaning](https://wikimean.io/what-does-ara-ara-mean-use-cases-and-examples) really enjoy what you've written on your blog. You've shared a very useful and entertaining blog post with the public.

**Comment by JosephKhalil2209** [comment]
thank you for the help. Yes, I am with TPG. I did call them however to see if they were working on something or knew the reason for the high latency; they denied anything. thank you for the help.
