### ISSUE TITLE
Flaming lasso gets broken if lassoed target is feared

### ISSUE THREAD

**Issue by powerdes** [ValveSoftware/Dota2-Gameplay#9613]
### Ability name

Flaming Lasso

### Description

1) Lasso Target
2) Use any ability that fears on target

Lasso will break instantly.

### Example Match ID (and possibly Timestamp)

7190747174 - 51:39

**Comment by TheUnholyWrath** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/1267#issuecomment-1324301450

Working as intended. Please close this issue.
