### ISSUE TITLE
Golden Item not Gold

### ISSUE THREAD

**Issue by LGMeow** [ValveSoftware/Dota2-Gameplay#9614]
### Cosmetic Item Name

Genuine Golden Gravel Maw

### Description

It really sucks that a 200$ item isn't working properly, it currently looks even worse than a normal gravelmaw.

### Example Match ID

7156781469

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/135935222/d76587e7-eb90-4321-8e51-d459b7f3fac1)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/135935222/f6a5e595-00cd-4a6c-a880-dd1d7e755198)

**Comment by BenLubar** [comment]
Wasn't able to download the match replay, but the item looks okay on my machine:

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/4257305/56eb8f73-a830-4559-812a-5cd31e49ca74)

**Comment by BenLubar** [comment]
Ah, found the setting that controls it - in Video settings, turn on "Specular".

**Comment by LGMeow** [comment]
> Ah, found the setting that controls it - in Video settings, turn on "Specular".



You're awesome dude, thanks! It changed when 7.33 started, I don't know why.

**Comment by BenLubar** [comment]
Weird, specular being turned off seems to only break it if shadows are also turned off. Probably something wrong in a shader.
