### ISSUE TITLE
Red dots on the minimap.

### ISSUE THREAD

**Issue by Redor55555** [ValveSoftware/Dota2-Gameplay#9617]
### Description

Sometimes, under certain conditions of the use of abilities by opponents, red dots appear on the minimap, today we learned that the opponents went to Roshan. This is not visible on the replay.
We were for the forces of light.

### Example Match ID (and possibly Timestamp)

7190979882 - 25:00

**Comment by Aluerie** [comment]
upvote https://github.com/ValveSoftware/Dota2-Gameplay/issues/7078 and comment those certain conditions/examples when exactly it happens.

**Comment by Nathanael-Valve** [comment]
Fixed in next
