### ISSUE TITLE
Mars Bulwark Redirect does nothing

### ISSUE THREAD

**Issue by ds0nts2** [ValveSoftware/Dota2-Gameplay#9619]
### Ability name

Bulwark

### Description

I activate it and nothing is redirected. ever. Try it.

Been this way since 7.33c. Also give me my mmr back.

### Example Match ID (and possibly Timestamp)

7191017336 maybe around 40m i try it on windrunner. Earlier on towers. Nothing ever redirected. MMR plz.

**Comment by ds0nts2** [comment]
second game like this.

**Comment by TheUnholyWrath** [comment]
![lmao](https://github.com/ValveSoftware/Dota2-Gameplay/assets/46859977/78d75fbf-d62a-4bd8-8451-575413e6252d)
![20230608192812_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/46859977/23787616-002c-46de-85da-901041776417)

At 40 minutes you're not positioned correctly for Redirect to work

**Comment by ds0nts2** [comment]
well, something like this works.
![20230608163830_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/74405917/4dc14d81-9777-4253-8a6f-618d7216bb12)

**Comment by ds0nts2** [comment]
I guess they changed it this patch or something. I thought it used to be that you could hide in trees while redirecting tower shots and stuff.

**Comment by TheUnholyWrath** [comment]
> I guess they changed it this patch or something. I thought it used to be that you could hide in trees while redirecting tower shots and stuff.

Looks like it was changed as part of 7.32. The changelogs sound like what you're describing

**Comment by TheUnholyWrath** [comment]
Anyway I'd recommend you be more specific with this issue. We know that Redirect does actually work, but if its not working correctly or if the tooltip is describing the interaction incorrectly/unclearly you should should remake this issue to be about that. If you want to go through and find the timestamps when it wasn't working on towers that could also be helpful

**Comment by ds0nts2** [comment]
though 100 range is super tiny. It would be WAY cooler if it was like 250 range, so mars could right click follow to protect someone

**Comment by ds0nts2** [comment]
I have to like directional walk into huskar to get 100 range close. lol.

**Comment by ds0nts2** [comment]
Also that really should not be ALT text. It's extremely important.

**Comment by ds0nts2** [comment]
I reopenned it because I think it should not be ALT text. Its mandatory information.
