### ISSUE TITLE
No damage after Dismember

### ISSUE THREAD

**Issue by Chuva4ock** [ValveSoftware/Dota2-Gameplay#9640]
### Description

After casting Dismember on Sniper, Sniper did not deal damage to Pudge. The battle logs show very small damage numbers, which definitely cannot be true.

### Example Match ID (and possibly Timestamp)

7191837174 - 4:23

### Screenshots

![Безымянный123123](https://github.com/ValveSoftware/Dota2-Gameplay/assets/136020557/1a98dbf1-f683-4f50-b385-72750c0ccd72)

**Comment by TheUnholyWrath** [comment]
You got unlucky. Sniper shot 4 times after being dismembered and all 4 were blocked by Vanguard. Pudge also had Flesh Heap active. There is no bug here. Please close this issue.
