### ISSUE TITLE
tombstone shard suck in enemy

### ISSUE THREAD

**Issue by monkbreakz** [ValveSoftware/Dota2-Gameplay#9643]
### Ability name

Tombstone Shard

### Description

In my game the enemy tombstone sucked me in. I played Axe, it happend while BKB and Blademail on calling the enemys.
Happens twice in this game.

I just  have the timestamp from the crusial one.

### Example Match ID (and possibly Timestamp)

7191981804   time 37.50 minutes

**Comment by TheUnholyWrath** [comment]
There is no enemy tombstone, Undying is on your team. This is how his new Shard works, you clicked on Tombstone and jumped inside it. If you think the functionality of this is incorrect then remake your issue to be about that. Otherwise there is no bug here, please close your issue.
