### ISSUE TITLE
Arc Warden Bug.

### ISSUE THREAD

**Issue by Profectuss** [ValveSoftware/Dota2-Gameplay#9653]
### Ability name

All ability

### Description

If Ark Varden is playing as the Dair, all of his abilities are swapped with the clone's, meaning "Spark Wrath" triggers after a second instead of the intended two, "Flux" deals more damage, and his field gives additional magic damage to auto attacks, all with first level. This can even be seen in the visual design of the abilities.

![zF4dDedf3mE](https://github.com/ValveSoftware/Dota2-Gameplay/assets/106770203/41e8853c-3bda-46ff-b365-a948a9610bf7)

### Example Match ID (and possibly Timestamp)

7192748278 00:00 - 03:30

**Comment by commentator24** [comment]
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109324155/0c1ff412-891a-4eab-9a12-d543612623f8)
basically if you play radiant, your hero is Normal, ult is tempest version. 
If you play dire, your hero is Tempest version, ult is normal
and the tempest version has stronger Q and W but weaker E and faster activation delay, not 2 but 1.

you can close the issue
