### ISSUE TITLE
Basher dispels Wyvern's Ultimate

### ISSUE THREAD

**Issue by Kettle5000** [ValveSoftware/Dota2-Gameplay#9660]
### Ability name

Winter's Curse

### Description

While playing a turbo match, it seems that if a Winter's curse target gets stun by an ally with basher, the ability ends prematurely. Im not exactly sure why this happens or even sure if basher is the responsable for this but for some reason it ends.

https://github.com/ValveSoftware/Dota2-Gameplay/assets/93736713/9ac24a9d-c61c-4658-8d9a-b5d201a704e6

### Example Match ID (and possibly Timestamp)

7193533078 - 15:38

**Comment by TheUnholyWrath** [comment]
![hum](https://github.com/ValveSoftware/Dota2-Gameplay/assets/46859977/0080b4c4-e802-484a-9a9c-d44f3c404db5)

You can close this issue.
