### ISSUE TITLE
matchmaking is not working correctly

### ISSUE THREAD

**Issue by Downdate** [ValveSoftware/Dota2-Gameplay#9663]
### Description

please fix the problem with fair team and enemy composition 

this match ID that I have given you is just one of the many matches that I get bad team and better enemies it doesn't matter what I do when my team keeps feeding left and right 

just take a look at the scoreboard and you will see what am I talking about.

matchmaking keeps giving me feeder team mates and stronger enemies.

instead of ranking up I am stuck at the same mmr with smurfs 
if I am good enough to play against a smurf then I am good enough to rank up but I am not ranking up!

### Example Match ID (and possibly Timestamp)

7193944849

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/112897962/3977d3fb-6e2f-497c-838d-e2c133b431bb)

**Comment by BenLubar** [comment]
You spent most of the match nowhere near your team, so they had to take every engagement 4v5.

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/4257305/d868c65f-c639-451d-98ac-f0d12fb687d0)

**Comment by Downdate** [comment]
it's fine just found out that should play just for fun this system is a joke

raipier every game is the way to go

**Comment by Downdate** [comment]
BTW, doesn't that mean the enemy is better than our team?
just saying.

It happens every single time you can check all of my history if you want I got a rampage in a game and we just lost like it meant nothing 
I am tired of this so I am just playing relaxed and don't care and if I give up on my team like that match I go farm my items and see what happens.

**Comment by Downdate** [comment]
if you just take a look at the draft you can clearly say which team has better players
