### ISSUE TITLE
Earth Shaker Hero relics are not counted in turbo

### ISSUE THREAD

**Issue by gogogalstone** [ValveSoftware/Dota2-Gameplay#9667]
### Description

**All the Gold color relics and some of the normal relics are not counted in Turbo matches:**

Three hero Fissures
Enchant Totem Kills
10 Enemy Aftershock
Three Hero Echoslams
Kills
Triple Kills
Dominating Killstreaks

### Example Match ID (and possibly Timestamp)

7194295332

### Screenshots

![Screenshot 2023-06-10 223712](https://github.com/ValveSoftware/Dota2-Gameplay/assets/136180029/06f713e6-3d29-4e81-bcdc-61ace8ebcb5f)

**Comment by Aluerie** [comment]
#8899 upvote the megathread with 👍/comment exact relics/close your subissue.

**Comment by gogogalstone** [comment]
Three hero Fissures
Enchant Totem Kills
10 Enemy Aftershock
Three Hero Echoslams
Kills
Triple Kills
Dominating Killstreaks

**Comment by Aluerie** [comment]
I meant in #8899
