### ISSUE TITLE
Earth Spirit Hero Relic not Counting in Turbo

### ISSUE THREAD

**Issue by gogogalstone** [ValveSoftware/Dota2-Gameplay#9669]
### Description

Hero Relic progression not being counted in turbo for his Relics:

Magnetize Three Heroes
Long Duration Magnetizes

### Example Match ID (and possibly Timestamp)

7194687143

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/136180029/d3d66c57-eb62-4790-9d7f-4ec53c7183ce)

**Comment by Aluerie** [comment]
#8899
