### ISSUE TITLE
Ethereal Blade doesn't add main attribute damage for universal heroes (or Nyx at least)

### ISSUE THREAD

**Issue by kalealca** [ValveSoftware/Dota2-Gameplay#9673]
### Item name

Ethereal Blade

### Description

Ethereal Blade doesn't add main attribute damage for universal heroes (or Nyx at least).

Don't even need the Match ID or timestamp. Just demo Nyx and use Ethereal on Dummy. 

### Example Match ID and Timestamp

7194857055

**Comment by Aluerie** [comment]
ehm duplicate #8094 

...and continuing our conversation from there. 

Correct way of testing Ethereal Blade interaction with Universal heroes would be using it on them. So, for example, lvl1 WR with no items takes just ~100hp, and WR lvl1 with some stats takes a lot more. 

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/33165440/f92c5df7-bfe6-48a9-b855-b9d5855cc1a4)

You can close this issue.
