### ISSUE TITLE
Illusion rune, units in fog.

### ISSUE THREAD

**Issue by JackNewley** [ValveSoftware/Dota2-Gameplay#9727]
### Description

When activating an illusion rune units are visible in fog for a brief moment. Can't reproduce in lobby.
Also noticed seeing WK skeletons getting summoned in fog.

https://github.com/ValveSoftware/Dota2-Gameplay/assets/9077011/5b1a2885-1a41-4dd2-a22d-3e061200852f

**Comment by Aluerie** [comment]
Dup #7078 pls close
