### ISSUE TITLE
Gem of true sight infinity cooldown

### ISSUE THREAD

**Issue by kontroman** [ValveSoftware/Dota2-Gameplay#9766]
### Item name

Gem of true sight

### Description

After picking up gem from enemy and using it ones, it has infinite 12sec cooldown, even if other hero takes it

### Example Match ID and Timestamp

7204009369, 40:00 - endgame

**Comment by Avarise831** [comment]
#8773

**Comment by chiat88** [comment]
another example: 7204849202
at least last 10 mins when Shadow Demon holds Clockwerk's gem.
Stuck at 12s cd

**Comment by Nathanael-Valve** [comment]
Fixed in next update.
