### ISSUE TITLE
Bought a starting item more than what its worth.

### ISSUE THREAD

**Issue by krysolite1** [ValveSoftware/Dota2-Gameplay#9771]
### Item name

Circlet

### Description

A circlet should only cost 155 gold. However, during the starting phase, I bought it for 255 as computed from my gold left. I started buying my starting items with 590 gold. Resold all items to check my actual remaining gold. It was 490 gold after.

### Example Match ID and Timestamp

720423157 -1:20

**Comment by krysolite1** [comment]
I was the Phantom Assassin on the Radiant side

**Comment by BenLubar** [comment]
@krysolite1 replay ID goes to a replay from 2014 - are you sure you copied the whole number?

**Comment by krysolite1** [comment]
sorry will check later

**Comment by krysolite1** [comment]
7204231357

**Comment by BenLubar** [comment]
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/4257305/b1a6e3ba-bc4d-4e11-a0d2-b3285edaa5c5)
You lost 10 gold during the last picking stage, and once the match started, your net worth was 10 less than the other players.

**Comment by krysolite1** [comment]
No that is not the issue. Look at my gold after I bought the circlet. it
went from 300 to 45 instead of 145. it should only cost 155 gold but thr
shop charged me 255.

**Comment by krysolite1** [comment]
Additionally, I noticed this immediately and sold all items within the 30
second limit. My networth (590) does not match my current gold (490).

**Comment by TheUnholyWrath** [comment]
You bought a TP scroll

**Comment by TheUnholyWrath** [comment]
![20230618114300_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/46859977/32c8e78d-5c3d-4230-8e66-daeffcd495c5)

**Comment by krysolite1** [comment]
Rookie mistake. Been playing for more than a decade and I encounter this
lol. thanks

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by TheUnholyWrath** [comment]
i'm assuming you're using hotkeys to buy things in the shop, might be worth moving things around or unbinding Purchase Sticky to avoid this in the future. If not, then this issue is even easier to solve. GL
