### ISSUE TITLE
[7.33d] [Phantom Lancer] Phantom Rush being off after respawn

### ISSUE THREAD

**Issue by VeanZ** [ValveSoftware/Dota2-Gameplay#9777]
### Ability name

Phantom Rush

### Description

After each respawn Phantom Rush state is set to off, which is extremally irritating, as off state is not useful beside laning stage of the game. The Player has to remember to activate the ability after each death.

Repro rate: 1 / 1 + 1 / 1 in demo mode

Repro Steps:
1. Boot the Title
2. Start any match (demo included)
3. Pick Phantom Lancer
4. Skill Phantom Rush
5. Get Phantom Lancer killed
6. Observe the issue

Actual Result: Phantom Rush is reset to off on each death.
Expected Result: Phantom Rush state is the same as prior to death.

### Example Match ID (and possibly Timestamp)

7204707490 - 11:10

**Comment by chrisf-valve** [comment]
This should be fixed with today's update. Phantom Rush toggle will maintain it's state when Phantom Lancer dies.
