### ISSUE TITLE
Riki Cloak and Dagger

### ISSUE THREAD

**Issue by Vash1116tv** [ValveSoftware/Dota2-Gameplay#9778]
### Ability name

Cloak And Dagger

### Description

Riki and his illusions are sometimes not able to be targeted by targeted spells. Please check the replay down below. Probably has to do with some interaction with shard, but definitely not working correctly.

### Example Match ID (and possibly Timestamp)

7204724647 - 41:45

**Comment by Aluerie** [comment]
if duplicate #9508 then pls close and upvote the original

**Comment by TheUnholyWrath** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/9508#issuecomment-1608531449

You can close this issue.
