### ISSUE TITLE
Items not showing in inventory

### ISSUE THREAD

**Issue by perniciousop** [ValveSoftware/Dota2-Gameplay#9786]
### Item name

all Immortal set eg- tempest revelation, arms etc....

### Description

All of my immortal items are disappeared, not even a single one visible on inventory. Also checked trade history no details found no one hacked or something. Might be a bug Kindly Please look into it. 

![Screenshot (2)](https://github.com/ValveSoftware/Dota2-Gameplay/assets/137002726/917c3a69-4fc2-402f-aaf2-6716bafcfd1a)
![Screenshot (3)](https://github.com/ValveSoftware/Dota2-Gameplay/assets/137002726/29833151-acc0-498a-b49b-ef241f9b7bab)

### Example Match ID and Timestamp

1267086377 - 01.23

**Comment by perniciousop** [comment]
I just found out all my items listed in community market on 12/06/2023 at 12:32 pm.

![Screenshot (5)](https://github.com/ValveSoftware/Dota2-Gameplay/assets/137002726/1195d412-b218-4f83-a340-e202d4dd2f20)
![Screenshot (4)](https://github.com/ValveSoftware/Dota2-Gameplay/assets/137002726/1abc64cc-8457-4ea6-889d-607b4eb4bffe)

**Comment by perniciousop** [comment]
Please help me someone hacked my account or i don't know what kind of glitch is this....

**Comment by TheUnholyWrath** [comment]
This is a Steam issue, not a Dota issue. Please close this and go open a ticket with Steam Support. They are the only ones that can help you
