### ISSUE TITLE
Zeus shard randomly stops working during game

### ISSUE THREAD

**Issue by terontero** [ValveSoftware/Dota2-Gameplay#9788]
### Ability name

LIGHTNING HANDS

### Description

During game, zeus "new" shard randomly stops working (ON MAIN HERO, still works on with manta illusions).
Everything was fine until around 38:30 in game time, nothing really happens, it just stops working after ancient camp is taken at 38:10.

I tried cycling items and reconnecting but nothing worked.
 

### Example Match ID (and possibly Timestamp)

7206119277 (38:15 - 01:18:15)

**Comment by TheUnholyWrath** [comment]
Lightning Hands is an Auto-Cast ability. When you toggle it off, it stops working. You toggled it off at 38:41. Please close this issue.
