### ISSUE TITLE
Silencer Relics Not Leveling in Turbo

### ISSUE THREAD

**Issue by gogogalstone** [ValveSoftware/Dota2-Gameplay#9804]
### Description

Silencer Relics don't work 

Multi Hero Curses
Damage During Global Silence
Intelligence stacks stolen
Last word Silence duration

### Example Match ID (and possibly Timestamp)

7207689739

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/136180029/c6653da0-412f-4d67-bd08-9162d2bc436d)

**Comment by Aluerie** [comment]
#8899
