### ISSUE TITLE
Woodland Warbands - Radiant Creeps visual bug with back ahead

### ISSUE THREAD

**Issue by phassaol** [ValveSoftware/Dota2-Gameplay#9815]
### Cosmetic Item Name

Woodland Warbands - Radiant Creeps

### Description

I got a bug since the release of 7.33 . A Visual bug with bp creeps " Woodland Warbands - Radiant Creeps"  their back goes ahead of them and it's boring to see it every match.  It's ironic that I paid for bugs creeps to have bugs. It only happens while creeps moving, model is ok when they are fighting or stand still. I tried reinstalling dota/changing creeps to standard and back/checking files and nothing helped. It happened only with creeps for radiant and others work fine.

### Example Match ID

any match or demo hero ex 7207241038

### Screenshots

![bug1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/137179818/a63efc31-50eb-433a-898f-d9a2fb15f824)
![bug2](https://github.com/ValveSoftware/Dota2-Gameplay/assets/137179818/efd9ed41-6912-4cac-9944-fbebc685725e)
![bug3](https://github.com/ValveSoftware/Dota2-Gameplay/assets/137179818/5d930dca-f2b6-49a7-b704-c0d7ab143aa2)
![bug4](https://github.com/ValveSoftware/Dota2-Gameplay/assets/137179818/d39df4fd-984c-42b2-b2d8-bdbf60ac11b8)
![bug5](https://github.com/ValveSoftware/Dota2-Gameplay/assets/137179818/5edfeb29-25cc-4b4a-a088-3179129ec70c)

**Comment by Aluerie** [comment]
#7331 dup/close/upvote/comment/etc
