### ISSUE TITLE
Phoenix Relics not Counting

### ISSUE THREAD

**Issue by gogogalstone** [ValveSoftware/Dota2-Gameplay#9816]
### Description

Allied sunray Heals
3 hero supernova stuns
Long Range kills
Veils leading to kills
Enemy ward kills
wards placed
kill assists
kills
Megakill streaks

### Example Match ID (and possibly Timestamp)

7208174769

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/136180029/8ce21301-9a5b-4f66-8662-8063771b5038)

**Comment by Aluerie** [comment]
#8899

**Comment by gogogalstone** [comment]
working again
