### ISSUE TITLE
Rubick - Cosmetic Bug

### ISSUE THREAD

**Issue by FrancoDelCastillo** [ValveSoftware/Dota2-Gameplay#9827]
### Cosmetic Item Name

Cape of the Itinerant Scholar

### Description

This cosmetic gets stuck in base, If I start walking, the cape stretches with a reference point.
Here is a video with all the set details I am using for a practice match
https://github.com/ValveSoftware/Dota2-Gameplay/assets/29493379/90d450b0-a699-486d-91e6-1937c99985ff

### Example Match ID

7209029289

### Screenshots

![Dota 2_2023 06 20-20 37_clip_1_3](https://github.com/ValveSoftware/Dota2-Gameplay/assets/29493379/79b3e24b-be6b-4779-ae66-e0ebc435a861)

**Comment by CereusRPG** [comment]
I came here just to report it. Ty.

**Comment by FrancoDelCastillo** [comment]
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/29493379/aa0b1d04-daea-49b2-ad35-ce9165625eb9)
