### ISSUE TITLE
Pugna's Life Drain uncastable on an invisible enemy, when revealed by either Sentry Wards , Gem, or True Sight from Buildings

### ISSUE THREAD

**Issue by Kupa707** [ValveSoftware/Dota2-Gameplay#9831]
### Ability name

Life Drain

### Description

Whenever an invisble enemy is revealed, either with Gem/Sentry/Buildings, Pugna cannot cast Life Drain on the revealed enemy. This bug is only unique to Gem/Sentry/Building. Other abilities and items that grant True Sight (such as Dust of Appearance, Slardar's Corrosive Haze, Void Spirit's Aether Remanent with talent, Bounty Hunter's Track) allows Life Drain to be casted. This bug is also present regardless of how the enemy goes invisible (with items or abilities).

Replicable in Demo Mode.

### Example Match ID (and possibly Timestamp)

7208880311 (53:20)

**Comment by TheUnholyWrath** [comment]
#9508 Please close this issue.
