### ISSUE TITLE
Enigma Eidolons

### ISSUE THREAD

**Issue by patrickthehero** [ValveSoftware/Dota2-Gameplay#9843]
### Ability name

DEMONIC CONVERSION

### Description

Eidolons move when only Enigma is moved or Enigma moves when Only Eidolons are moved.

### Example Match ID (and possibly Timestamp)

7210138978

**Comment by commentator24** [comment]
you probably has the setting auto select summoned units...

**Comment by patrickthehero** [comment]
I dont have the setting Auto Select Summoned Units activated but its still
happening. Other players I know have the same Issue. There are no settings
causing this issue. Hoping for your help.


commentator24 ***@***.***> schrieb am Do., 22. Juni 2023,
08:34:

**Comment by commentator24** [comment]
then you have the Unified orders with CTRL. your ctrl key is stuck

**Comment by patrickthehero** [comment]
Problem is solved. Thank you for your help and have a nice Day.
:D


commentator24 ***@***.***> schrieb am Do., 22. Juni 2023,
11:25:

**Comment by Aluerie** [comment]
close your issue then, please.
