### ISSUE TITLE
Second Wraith Band Attack Speed and Armor Incorrect

### ISSUE THREAD

**Issue by mengullojerome** [ValveSoftware/Dota2-Gameplay#9852]
### Item name

Wraith Band

### Description

In the image below, I noticed first that there should be +4 in the armor instead of + 2. When I go to demo, it indeed says +4 instead of +2 and the attack speed for Dark Willow Level 3 with 2 Wraith Band and 1 Branch should be 177.

This happened in match 7211482964

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/31769398/f2cd0dc3-bdc6-404e-bea5-e280d72b7b6e)

### Example Match ID and Timestamp

7211482964 - 3:01

**Comment by Aluerie** [comment]
it's just a visual bug. can happen with any +green stats.

I'm not sure what issue is the original to this duplicate though.

**Comment by mengullojerome** [comment]
Might be visual bug, indeed. The damage still counted and correct

**Comment by mengullojerome** [comment]
Can't replicate this anymore. I'm closing this issue.
