### ISSUE TITLE
Nyx Assassin's Mind Flare doesn't deal the bonus damage

### ISSUE THREAD

**Issue by jlkj11** [ValveSoftware/Dota2-Gameplay#9856]
### Ability name

Mind Flare

### Description

As of 7.33d, Mind Flare is only dealing the INT-based damage, completely ignoring the bonus damage aspect of the skill.
![Captura de tela 2023-06-22 224436](https://github.com/ValveSoftware/Dota2-Gameplay/assets/120787118/110b78e6-c3b5-476e-951f-e449e249bbce)

### Example Match ID (and possibly Timestamp)

any

**Comment by Aluerie** [comment]
#8046 somewhat related
