### ISSUE TITLE
Invoker's tornado removes invulnerability in demo

### ISSUE THREAD

**Issue by Rob9955** [ValveSoftware/Dota2-Gameplay#9859]
### Ability name

Tornado

### Description

If you give any hero invulnerability in the demo and then cast invoker's tornado spell on them, it removes the invulnerability completely. This works both ways: you casting the spell on an enemy, and the enemy casting the spell on you.

### Example Match ID (and possibly Timestamp)

No ID to provide

**Comment by Rob9955** [comment]
Edit:

**Comment by Rob9955** [comment]
Edit: This also happens with Eul's scepter of divinity

**Comment by Avarise831** [comment]
#1299
