### ISSUE TITLE
Phantom Lancer's Phantom Rush ability toggles off on death

### ISSUE THREAD

**Issue by ilyanep** [ValveSoftware/Dota2-Gameplay#9890]
It looks like a recent update made it so that Phantom Rush doesn't trigger on right clicks unless it is toggled on (which is the opposite of the old behavior, where you had to explicitly toggle it off to _not_ have it trigger). However, it now toggles back off whenever you die. Instead, ideally the toggle state would be preserved on death (I imagine a lot of players would prefer for it to be toggled on most of the time, so having to remember to toggle it back on after respawning is mildly annoying).

**Comment by TheUnholyWrath** [comment]
#9777

**Comment by ilyanep** [comment]
Oh, my bad. I didn't realize there was a separate project for in-game issues.
