### ISSUE TITLE
Mind Flare

### ISSUE THREAD

**Issue by GoldenDarkness228** [ValveSoftware/Dota2-Gameplay#9891]
### Ability name

Mind Flare

### Description

The Nyx Assassin's mind Flash does not increase the damage from itself, that is, if you press 2 Nyx skill, then refresh and apply this ability again, the damage from it will not increase but will be the same

### Example Match ID (and possibly Timestamp)

123

**Comment by Aluerie** [comment]
#8046 dup/upvote/close/comment/sub/search/etc
