### ISSUE TITLE
Relocate for Io is not working properly

### ISSUE THREAD

**Issue by assssss330** [ValveSoftware/Dota2-Gameplay#9892]
### Ability name

Relocate

### Description

As I understand, Io's Relocate should work even if Io and his teammate were stunned, silenced, or whatever it can be if it has been already pressed. But the problem is that it is not working, if Io got stunned or silenced during cast of Relocate. I assume, that that is not a part of mechanic, instead of a bug that appeared in new patches. Here is an archive with a video, that is demonstrating details about bug.
[bug demonstration.zip](https://github.com/ValveSoftware/Dota2-Gameplay/files/11866532/bug.demonstration.zip)

I saw that bug while training versus bots, so there is no match ID, but anyway, please have a look on it. If it is not a bug but a mechanic contact me pls by that email: astraimer.ru@gmail.com

### Example Match ID (and possibly Timestamp)

no match id

**Comment by Aluerie** [comment]
read the tooltip.

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/33165440/e53b610a-40c6-4264-b52c-da86fd40a196)

**Comment by assssss330** [comment]
oh ssory, in my client there is no tooltip)
