### ISSUE TITLE
Earth Spirit shard does not grand additional charges on purchase

### ISSUE THREAD

**Issue by jrh785** [ValveSoftware/Dota2-Gameplay#99]
It used to be that earth spirit shard gave you the extra charges off cooldown when you purchased it whereas now it only increases the cap. This may have been an intentional nerf but it is not how it used to work and does not inuitively correspond to how other shard/aghs work e.g. ember spirit aghs.

**Comment by BlueHammer** [comment]
Help upvote the larger ES bug thread too #336 !

**Comment by shaileshgarg** [comment]
Fixed in today's update.

**Comment by Dota-Exp** [comment]
Issue should be fixed. Thank you.
