### ISSUE TITLE
Battle Stats > Matches - Don't Update Realtime

### ISSUE THREAD

**Issue by mengullojerome** [ValveSoftware/Dota2-Gameplay#9918]

**Comment by mengullojerome** [comment]
*Commenting because description didn't get saved

I've read in the past updates that the Battle Stats now update realtime but I don't see it happening in the Matches Tab. It would be very nice to see it update realtime. Also it makes more sense to see the Rank Change by default, instead of the Hero Damage (to make the table still look good).

Here the Matches tab shows the last match to be 27/06/2023
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/31769398/62f60786-991e-44c1-86d4-913ee03cb39b)

I already played a game today (28/06/2023 UTC +8:00)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/31769398/e2ed47fc-4b08-4c36-9b9f-17d631ba308e)

It would be nice to see the Matches tab update realtime and the Rank Change displayed by default.

**Comment by Aluerie** [comment]
duplicate https://github.com/ValveSoftware/Dota2-Gameplay/issues/8394

**Comment by mengullojerome** [comment]
Closing this one due to duplicate.
