### ISSUE TITLE
Dota2 only works on first load on Mac

### ISSUE THREAD

**Issue by naturligasteg** [ValveSoftware/Dota2-Gameplay#9935]
### Description

When I start up Dota2 on my Mac M1 Studio it works as normal first time, but if I quit Dota for an update or any other reason Dota does not work on reload. Load is extremely slow and the preload or the main menu does not respond to mouse clicks. I have to close down the Steam Client totally and relaunch Dota to get Dota to start again.

**Comment by Aluerie** [comment]
for mac specific issues please use https://github.com/ValveSoftware/Dota-2 to search/report about your problems and not this repo, so pls close.

**Comment by naturligasteg** [comment]
Ok, moved it to the other repo.

**Comment by naturligasteg** [comment]
Moved to other repo.
