### ISSUE TITLE
All time cooldown gem

### ISSUE THREAD

**Issue by ArtemkaBL** [ValveSoftware/Dota2-Gameplay#9944]
Gem goes on endless cooldown 
![image](https://github.com/ValveSoftware/Dota-2/assets/56271413/2fff2cae-7deb-4dd0-b4cd-49eb50ca3482)

**Comment by Avarise831** [comment]
#8773

**Comment by lenkalee266** [comment]
Thank you for producing such a fascinating essay on this subject [atari breakout](https://klassicgames.io/atari-breakout). This has sparked a lot of thought in me, and I'm looking forward to reading more.

**Comment by Nathanael-Valve** [comment]
Fixed in next update.
