### ISSUE TITLE
Fantasy score stops working

### ISSUE THREAD

**Issue by WarpGhost** [ValveSoftware/Dota2-Gameplay#9961]
### Description

Current Major. First day score works ok, player cards get scores, total score calculated. Next day, percentile determinate and everything is fine. Next day, plaers scores calculated again normaly.
DAY THREE
Every player card score since day one gone. Total result only displayed for first day

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/74701599/e8f87128-8774-445a-af1e-18cc602acaa3)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/74701599/8c253133-8832-4599-97b1-cfea759a7175)

**Comment by somedumbname** [comment]
I am having the same issue.

**Comment by On3St4B** [comment]
Same here, last update was 29th of June, after that its stopped showing points.

**Comment by WarpGhost** [comment]
UPD. What ever you did, player cards score now visible, but TOTAL score only visible for june 29 and july 5
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/74701599/6694dd3e-3274-4f96-9435-07e239bbd27c)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/74701599/26648f90-3e46-43cb-9391-5f46411fd55b)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/74701599/cfb33d8d-7286-475f-88d6-d4bbffa1c983)

**Comment by chrisf-valve** [comment]
Score calculations for June 29th -> July 4th have been fixed. You will no longer see your player card roster as the event is over, but you should be able to see your overall score for the period, your percentile rank, and your place on the leaderboard. Rewards are being processed now, you receive shards within the next hour or so.

**Comment by chrisf-valve** [comment]
Thanks for following up! We took another look and indeed some scores did not get updated yesterday. While we are not able to recover those scores, we have awarded fantasy levels to players for each period that was not scored. You should see the fantasy level change (and appropriate shard rewards) in your account now.
