### ISSUE TITLE
Gem + Faceless Void

### ISSUE THREAD

**Issue by fraltnn** [ValveSoftware/Dota2-Gameplay#9976]
### Item name

Gem of True Sight

### Description

If a gem drops in a void's chronosphere, it becomes unusable after use, permanent cd of 12 seconds

### Example Match ID and Timestamp

7226886277 - 39

**Comment by Aluerie** [comment]
Dup #8733 pls close+upvote+comment/sub

**Comment by Avarise831** [comment]
#8773

**Comment by Nathanael-Valve** [comment]
Fixed in next update.
