### ISSUE TITLE
Fantasy points not displayed

### ISSUE THREAD

**Issue by serak88** [ValveSoftware/Dota2-Gameplay#9991]
After day one of Bali Major fantasy points are shown as 0 for every player, even for the Regionals where the levels were already distributed.
The last distributed points belong to the first day of the Major.

### First week of Regionals - points already distributed
![image](https://github.com/ValveSoftware/Dota-2/assets/29153205/b792cda6-b0c7-4a9c-8a48-6a51acac6706)

### First day of Bali - points already distributed
![image](https://github.com/ValveSoftware/Dota-2/assets/29153205/c2ddd6c8-92a5-4889-9617-ca0bb9450152)

### Second day of Bali - not working
![image](https://github.com/ValveSoftware/Dota-2/assets/29153205/120efe67-cc93-4658-8163-b53f858b8be2)

**Comment by serak88** [comment]
Since today's patch card scores are back but from 30/06 through 03/07 totals, top scores and rewards are still missing.

**Comment by chrisf-valve** [comment]
Score calculations for June 29th -> July 4th have been fixed. You will no longer see your player card roster as the event is over, but you should be able to see your overall score for the period, your percentile rank, and your place on the leaderboard. Rewards are being processed now, you should receive any earned shards within the next hour or so.
