### ISSUE TITLE
Fantasy Points not displayed... From Day 2 until present

### ISSUE THREAD

**Issue by skamacanan** [ValveSoftware/Dota2-Gameplay#9992]
### Description

I can't view my Fantasy points for the current DPC Bali Major Tournament and I am just assigned 0 points for all players picked.

### Screenshots

https://steamcommunity.com/id/macx98/screenshot/2048623604680140258/

**Comment by 89magnum89** [comment]
I have the same exact issue!

**Comment by Golf129** [comment]
same issue

**Comment by gine1** [comment]
same

**Comment by skamacanan** [comment]
Hi,

Thanks for fixing my July 5 day fantasy points!

I would like to report that the other days are still bugged.

Description of bug: Player Cards would show scores, but Global Score is still not visible plus total points rewarded for the day is not visible.

 (Please see screenshots)
June 30: https://steamcommunity.com/id/macx98/screenshot/2048623604683178857/
July 1: https://steamcommunity.com/id/macx98/screenshot/2048623604683175893/
July 2: https://steamcommunity.com/id/macx98/screenshot/2048623604683176665/
July 3: https://steamcommunity.com/id/macx98/screenshot/2048623604683169022/

**Comment by chrisf-valve** [comment]
Score calculations for June 29th -> July 4th have been fixed. You will no longer see your player card roster as the event is over, but you should be able to see your overall score for the period, your percentile rank, and your place on the leaderboard. Rewards are being processed now, you should receive any earned shards within the next hour or so.
